### ISSUE TITLE
Search list is not scrollable

### ISSUE THREAD

**Issue by SarangWadode** [mantinedev/mantine#1000]
### Link to the page where something nasty is located

https://mantine.dev/getting-started/

### Exact quote of what is wrong

While searching for component (e.g. `List`), the suggestions container is not scrollable, which hides additional items as in below image.
![Screenshot from 2022-03-13 23-46-53](https://user-images.githubusercontent.com/73584423/158073410-43cc52b3-e751-4247-8aec-46efde652a72.png)
> I've searched for `List`, it is showing lots of items, but suggestion for `List` **Component** is hidden below and the suggestion container is not scrollable, making it harder to navigate to the component through search.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Congratulations on creating issue #1000! There are no plans for adding scrollable content for spotlight, but I'll improve searching algorithm to prioritize items that have search term in title.

**Comment by SarangWadode** [comment]
> Congratulations on creating issue #1000!

Glad to know that :smile:

**Comment by Phosphorus-M** [comment]
I added this line to the SpotlightProvider

```TypeScript
styles={{ actions:{ height: "300px", overflow: "auto"}}}
```
This is the result
![Peek 25-03-2022 11-10](https://user-images.githubusercontent.com/19656993/160137020-9dd595c8-27a3-46a0-80ad-5b5d7dae7524.gif)

**Comment by rtivital** [comment]
Fixed in 4.1.5 – items are now prioritized by title with default filter
