### ISSUE TITLE
useNotifications does not work in App.js and padding does not work for Header

### ISSUE THREAD

**Issue by elibroftw** [mantinedev/mantine#1003]
### What package has an issue

@mantine/notifications

### Describe the bug

```
Uncaught Error: @mantine/notifications: NotificationsProvider was not found in tree
    useNotifications use-notifications.ts:6
    App App.js:32
    React 17
    js index.js:7
    factory react refresh:6
    Webpack 3
```

```
function App() {
    const notifications = useNotifications();
return (
    <MantineProvider theme={{ colorScheme: colorScheme, fontFamily: 'Open Sans, sans serif' }} withGlobalStyles >
      <NotificationsProvider>
</NotificationsProvider>
    </MantineProvider>
);
}
```

### In which browser did the problem occur

FF

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
You are calling useNotifications hook outside of NotificationsProvider context. Header pading prop was renamed in 4.0, see documentation.

**Comment by elibroftw** [comment]
I fixed the Header issue, but how am I supposed to call useNotifications inside NotificationsProvider if I want to call notifications from the App.js file? I shouldn't need to create a file just to call notifications.

**Comment by rtivital** [comment]
It's not a bug/feature request, it is how react context works. You cannot use context without provider.

**Comment by elibroftw** [comment]
In my books, unintuitiive = bug. The reason I say this is because, there are no useful examples in https://mantine.dev/core/notification/, where the notification gets spawned by a state change and goes away after 5 seconds or so. 

These docs don't even specify if the Notification component behaves like a notification or it's simply for show. Only https://mantine.dev/others/notifications/ shows good examples, but there's no example where notifications are spawned in the same file that calls `useNotifications`.
