### ISSUE TITLE
Some property aren't available in "RadioGroup" and "Radio" components.

### ISSUE THREAD

**Issue by jsxclan** [mantinedev/mantine#1004]
I'm having two issues with `@mantine/core` and `@mantine/rte` packages.

First: some property aren't available in `RadioGroup` and `Radio` components.
![Screenshot 2022-03-14 042358](https://user-images.githubusercontent.com/51025764/158100530-f8816d3f-5725-4a9c-9331-1bb30e095231.png)

Second: I would like to add custom image handler to the `RichTextEditor` but it seems like my approach isn't right.
![Screenshot 2022-03-14 042452](https://user-images.githubusercontent.com/51025764/158100699-f53308e6-057d-49b0-a91b-68a8fa7c515f.png)

Please help me out ASAP, I'm stuck! 🙏

**Comment by rtivital** [comment]
You are using 3.x version of Mantine while documentation is for 4.x, you can find 3.x docs here – https://v3.mantine.dev/
