### ISSUE TITLE
Submenu support

### ISSUE THREAD

**Issue by sukechris** [mantinedev/mantine#1005]
### Usage example, including component/hook API

Hi Vitaly, Thank you for your great work! I use `Mantine UI` for my desktop app and it works fine, I plan to use `Menu` component to build contextmenu, and my contextmenu has some submenus, like this:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/36565253/158226090-2f490adb-b74f-4135-bb9f-b65040522b28.png">

are there plans to support submenu?

### Possible implementation – describe how the feature can be implemented

```jsx
<Menu>
    <Menu.Item icon="new-text-box" onClick={this.handleClick} text="New text box" />
    <Menu.Item icon="new-object" onClick={this.handleClick} text="New object" />
    <Menu.Item icon="new-link" onClick={this.handleClick} text="New link" />
    <Menu.Divider />
    <Menu.Item text="Settings..." icon="cog">
        <Menu.Item icon="tick" text="Save on edit" />
        <Menu.Item icon="blank" text="Compile on edit" />
    </Menu.Item>
</Menu>

```

**Comment by Kayrim** [comment]
Hey, did this feature ever get added?

**Comment by rtivital** [comment]
No, it was not

**Comment by S1SYPHOS** [comment]
Is there any way to achieve this currently?
