### ISSUE TITLE
Uncaught TypeError: _a2.getTime is not a function

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [mantinedev/mantine#1012]
### What package has an issue

@mantine/dates

### Describe the bug

`Uncaught TypeError: _a2.getTime is not a function`

I get this error when setting default value that maybe not an instance of a `Date`

This is my component:
```
import { TimeRangeInput } from '@mantine/dates'
import { InputWrapper } from '@mantine/core'
import { useField } from 'formik'
import 'dayjs/locale/pl'

interface TimeRangeProps {
  name: string
  label: string
  className: string
}

function TimeRange(props: TimeRangeProps) {
  const [field, meta, helpers] = useField(props.name)
  const { setValue } = helpers

  const handleChange = (value: [Date | null, Date | null]) =>
    setValue({ start: value[0], end: value[1] })

  return (
    <InputWrapper label={props.label} error={meta.error}>
      <TimeRangeInput
        onChange={handleChange}
        value={[field.value?.start, field.value?.end]}
        clearable
      />
    </InputWrapper>
  )
}

export default TimeRange

```
`field.value` is at first `undefined` but this alone triggers this:
```
// TimeRangeInput.tsx:129 
 useDidUpdate(() => {
      if (
        value[0]?.getTime() !== _value[0]?.getTime() ||
        value[1]?.getTime() !== _value[1]?.getTime()
      ) {
        setValue(value);
      }
    }, [value]);
```
as `value` is `undefined` and not `Date` we don't have access to `getTime` method. I think this could be made optional by adding `?` before function call

### In which browser did the problem occur

Edge, Firefox Developer Edition

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

I propose a change in this piece of code - add `?` before function execution
```
 useDidUpdate(() => {
      if (
        value[0]?.getTime?() !== _value[0]?.getTime?() ||
        value[1]?.getTime?() !== _value[1]?.getTime?()
      ) {
        setValue(value);
      }
    }, [value]);
```

**Comment by rtivital** [comment]
Please provide a sandbox that reproduces this error with a minimal example, I've checked both controlled and uncontrolled inputs and they work fine – https://codesandbox.io/s/dawn-platform-ojkf56?file=/src/App.tsx

**Comment by pawelkrystkiewicz** [comment]
Thanks for the example. I couldn't get this error in sandbox. Turns out that formik converts Dates under the hood to ISO strings 😞 
I think we can close this issue
