### ISSUE TITLE
DefaultMantineColor type no longer has 'teal' as an option

### ISSUE THREAD

**Issue by jhayworthg** [mantinedev/mantine#1013]
### What package has an issue

@mantine/core

### Describe the bug

In 4.0.4 typescript is throwing an error on build because 'teal' is no longer in the DefaultMantineColor type. All other colors from open-color are still there.

### In which browser did the problem occur

Chrome

**Comment by rtivital** [comment]
@iDavidB Do you know if your changes may have caused that?

**Comment by iDavidB** [comment]
> @iDavidB Do you know if your changes may have caused that?

@rtivital Looks like I did accidentally remove that in one of my commits, no idea how that happened. 
https://github.com/mantinedev/mantine/commit/7c60a1ad2b9a221f7a686e2ad6f77b97a74330e6#diff-60e675de06e54cf405bc944cfaf4cd969460939a556509b298eeed1acd8917f2L11

I can create a PR if you'd like, just need to put it back. @jhayworthg If you can't wait you can add teal to your custom type for now.

**Comment by rtivital** [comment]
Yes, PR is welcome, thanks!
