### ISSUE TITLE
Select/Autocomplete closes Popover despite withinPortal = false

### ISSUE THREAD

**Issue by kierien** [mantinedev/mantine#1014]
### What package has an issue

@mantine/core

### Describe the bug

According to [documentation](https://mantine.dev/core/popover/#usage-with-other-overlays), adding the withinPortal prop to elements that render overlays within Portal within Popover will ensure correct behaviour. 

When selecting an option from the Select component with withinPortal as false, the parent Popover still closes.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/withered-platform-w08wr4

**Comment by rtivital** [comment]
Fixed in 4.0.7
