### ISSUE TITLE
Creatable MultiSelect with empty data is displaying empty dropdown

### ISSUE THREAD

**Issue by jCobbSK** [mantinedev/mantine#1017]
### What package has an issue

@mantine/core

### Describe the bug

When we use `MultiSelect` also for creation and in some cases we don't have any data, empty dropdown is displayed until we write some query.

### In which browser did the problem occur

All

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/eloquent-hill-45t8g0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

It seems that removal of `isCreatable` in `shouldRenderDropdown` constant in `MultiSelect.tsx` helped to fix this issue. We should be able to rely that when actual value can be created, new item is pushed into `filteredData` and rendered.

**Comment by rtivital** [comment]
@achmurali can you have a look?

**Comment by achmurali** [comment]
> @achmurali can you have a look?

Yeah, definitely

**Comment by rtivital** [comment]
Fixed in 4.0.8
