### ISSUE TITLE
index parameter in applyWhere helper in use-list-state hook

### ISSUE THREAD

**Issue by antoinesion** [mantinedev/mantine#1018]
### What package has an issue

@mantine/hooks

### Describe the bug

In [use-list-state](https://github.com/mantinedev/mantine/blob/01b6be15a7b97f788b5298772166aa0a09dc4643/src/mantine-hooks/src/use-list-state/use-list-state.ts#L80), in `applyWhere` helper:
```ts
const applyWhere = (
    condition: (item: T, index?: number) => boolean,
    fn: (item: T, index?: number) => T
  ) => setState((current) => current.map((item) => (condition(item) ? fn(item) : item)));
```

`index` is always `undefined` in `condition` and `fn` functions, could it be retrieved from the `map` and passed to both of them? (see possible fix below)

Moreover, `index` should not be optional I think in the typing (same thing for the `apply` helper).

### In which browser did the problem occur

All

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

```ts
const applyWhere = (
    condition: (item: T, index: number) => boolean,
    fn: (item: T, index: number) => T
  ) => setState((current) => current.map((item, index) => (condition(item, index) ? fn(item, index) : item)));
```

**Comment by bogordesaincom** [comment]
i have same problem
