### ISSUE TITLE
[Feature Request] Optional auto-focus for useFocusTrap hook

### ISSUE THREAD

**Issue by korac** [mantinedev/mantine#1024]
### Usage example, including component/hook API

I use Mantine's `Drawer` component which consumes `useFocusTrap` hook.
The hook itself triggers a focus on first tabbable/focusable element within its scope.

While being great for keyboard-supported devices, I find this being a poor UX for mobile and (keyboardless) tablet devices - the drawer adds a focus on the first item (even though mobile devices don't support this behavior).

I would like to opt-out of this auto-focus behavior.

### Possible implementation – describe how the feature can be implemented

Add a second argument to the hook: `options` object.

This object can contain specific (boolean) property that determines if the focus should be performed or not.
Furthermore, expose new boolean prop on `Drawer` component which is passed within `options` object to `useFocusTrap` hook.

Also, `options` object could find its purpose for future updates.

### Do you want to contribute this feature and create a pull request

Yes

**Comment by rtivital** [comment]
If the initial element is not focused, it means that focus trap will not work. Drawer and other components already provide `withFocusTrap` to disable focus trap entirely.

**Comment by korac** [comment]
Thanks for the explanation. Great package btw!
