### ISSUE TITLE
PasswordInput innerInput stylesAPI not working

### ISSUE THREAD

**Issue by official-carledwardfp** [mantinedev/mantine#1025]
### What package has an issue

@mantine/core

### Describe the bug

PasswordInput innerInput stylesAPI is not working

Code:
```
<PasswordInput
   {...props}
   styles={{
      innerInput: { fontSize: 16, color: 'red' },
   }}
/>
```

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Add innerInput to Input and InputWrapper since styles is passed to both components

**Comment by rtivital** [comment]
Fixed in 4.0.6
