### ISSUE TITLE
Slider value with floating step

### ISSUE THREAD

**Issue by MathieuPuech** [mantinedev/mantine#1030]
### What package has an issue

@mantine/core

### Describe the bug

When I use the `step` property of `<Slider>` with a floating value, the value is not exactly following the steps

Example with the codesandbox shared:

![image](https://user-images.githubusercontent.com/9367152/158880752-9d618512-92a7-4ef2-8605-8fe1e0d5481c.png)

This is because in JavaScript `0.1 + 0.2 = 0.30000000000000004`

### In which browser did the problem occur

chrome 99.0.4844.74 linux

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/green-snowflake-dvh5zi?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

determine the number of digits to use after the decimal point and use [.toFixed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) with this number.

**Comment by rtivital** [comment]
I do not think that this should be done on library level, since you provide value, onChange handler and step, there might be some issues when we try to get significant digits on our side.
