### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by konsumer** [mantinedev/mantine#1033]
### What package has an issue

@mantine/ssr

### Describe the bug

Following the remix directions on [getting started](https://mantine.dev/getting-started/) I get `ReferenceError: Buffer is not defined`

```sh
# this is the basic stup I did to make this project

npx create-remix@latest mantine-remix

# What type of app do you want to create? Just the basics
# Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Cloudflare Workers
# TypeScript or JavaScript? JavaScript
# Do you want me to run `npm install`? Yes

cd mantine-remix
npm install @mantine/hooks @mantine/core @mantine/ssr

# replace entry.server.jsx with js equiv of text in article

npm run dev
```

### In which browser did the problem occur

N/A

### If possible, please include a link to a codesandbox with the reproduced problem

N/A

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by konsumer** [comment]
[this demo project](https://github.com/remix-run/remix/tree/main/examples/mantine) seems to work ok, which also uses cloudflare-workers & JSX, so there may just be some mismatch somewhere.

**Comment by rtivital** [comment]
I've repeated your steps and everything works correctly, repository – https://github.com/rtivital/remix-mantine-debug

**Comment by konsumer** [comment]
Maybe we have different versions of something. I am on Mac M1, running OSX 12.3. I am using [this entry.server.jsx](https://gist.githubusercontent.com/konsumer/fb5b41c7b110309084c34eaaa810e205/raw/1d15acd907350d647de77343d5e33c406d879fb4/entry.server.jsx).

Here is it failing on a few different version-combos for me:

- [M1 native, node v17.6.0\, npm 8.5.1](https://asciinema.org/a/04XZGm1Xe4iBhglE3rlZnkAbF)
- [docker node:16](https://asciinema.org/a/TPczTaSudyr3uaSU5kUJ8bGqu)
- [docker node:17](https://asciinema.org/a/k0ussYVF2UNI4o4zHeu3S37Oh)

I am happy to test some other way, if you need more info.

For my immediate issue, I got it running with remix-esbuild-override and @esbuild-plugins/node-globals-polyfill.

**remix.config.js**:
```const nodepoly = require('@esbuild-plugins/node-globals-polyfill').default

module.exports = {
  serverBuildTarget: 'cloudflare-workers',
  server: './server.js',
  devServerBroadcastDelay: 1000,
  ignoredRouteFiles: ['.*'],

  esbuildOverride: (option, { isServer, isDev }) => {
    option.plugins = option.plugins || []
    option.plugins.push(nodepoly({ buffer: true }))

    option.define = option.define || {}
    option.define.global = 'globalThis'

    return option
  }
}```

remix-esbuild-override can feel a little flakey if you don't run the updater before every build, though, and it seems like something that I should report to someone, anyway (something is using `Buffer`, even though that is not available on cloudflare-workers.) I'm not sure where the problem is, as it could be remix, mantine, or some other lib, but

**Comment by rtivital** [comment]
Emotion server does not support cloudflare-workers

**Comment by konsumer** [comment]
Ah, so the remix directions are only for other remix backends? That makes sense. Thanks.

**Comment by konsumer** [comment]
remix-esbuild-override stopped working, due to changes in remix, so this is an issue for me again.

Is there a way to disable Emotion server and still use mantine with remix & cloudflare-workers?

I am having a bit of trouble figuring out where to report this issue, even. Like mantine supports remix, and remix supports cloudflare-workers, but mantine does not support remix, if I use cloudflare-workers. If I were using mantne with some other setup, I would modify my esbuild setup to polyfill these, but remix doesn't expose the esbuild config. Maybe it should be added to the "getting started" page? I think this is a fairly common target for remix.

**Comment by rtivital** [comment]
I do not have any experience with Remix, so cannot advise anything, I think you can get help with that on Remix discord server or by reaching out to remix-esbuild-override maintainers.

**Comment by konsumer** [comment]
Yep, I talked with the remix-esbuild-override maintainer, and we are both trying to get help with remix. I really love mantine, and remix seems to be the main thing keeping me from using it on cloudflare-workers (regular esbuild config makes it simple) so I might just drop remix and use worker-pages directly. I appreciate you looking into this.

**Comment by rtivital** [comment]
Alright, if you find a working solution, please ping me, I'll add it to documentation

**Comment by Viranchee** [comment]
I get similar error
`[pages:err] ReferenceError: Buffer is not defined`

https://github.com/remix-run/remix/issues/2813#issuecomment-1356051032

**Comment by nastynaz** [comment]
This was a huge pain to fix. I managed to fix it and [wrote up a guide](https://medium.com/@denzity/how-to-make-remix-work-with-mantine-cloudflare-pages-workers-907888bc00fc) so other's don't have to suffer.

The two issues I had were:
1. Not working with Cloudflare (solution was to write my own `createStylesServer` using an Emotion server that didn't have the node bits.
2. A flash of unstyled content (FUOC) causing a janky UX. I fixed this by ensuring the same cache is used everywhere.
3. The `<style>` tags for global styles being rendered in the body. Fixed by wrapping app inside an Emotion `CacheProvider` in `entry.server.tsx

Repo that works with the latest Mantine, latest Remix & Cloudflare Pages/Workers: [nastynaz/mantine-remix-cloudflare](https://github.com/nastynaz/mantine-remix-cloudflare)

@rtivital What do you think about updating the official docs to make the integration more seamless? I'm happy to do it if you accept PRs, just let me know where.

**Comment by rtivital** [comment]
Well there is a migration to native CSS going on, it will be introduced in 7.0. So, all issues will be solved then

**Comment by larissa-n** [comment]
@nastynaz excellent write-up, thank you for sharing. Did you run into any issues with `@mantine/ssr` referencing `@emotion/server`? `@mantine/ssr` shows in your lockfile (dependency of `@mantine/remix`) and one of the package files is referencing `@emotion/server`: https://github.com/mantinedev/mantine/blob/b661b4bddd49c93252da8ded73b6e0f34e3a5a43/src/mantine-ssr/src/create-styles-server.ts#L2 
When I replicate your approach, that results in 
 ```
> node_modules/@mantine/ssr/esm/create-styles-server.js:1:32: error: 
Could not resolve "@emotion/server/create-instance" 
(mark it as external to exclude it from the bundle)
    1 │ import createEmotionServer from '@emotion/server/create-instance';
      ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Going in and editing `@mantine/ssr` to remove the original `createStylesServer` function is a possible fix, but, conceivably, not very smooth. Did you find another way, or did you have to fork it?

@rtivital that's great to hear. Do you already have a timeline for 7.0?

**Comment by nastynaz** [comment]
@larissa-n I had to create my own polyfill and use that instead: https://github.com/nastynaz/mantine-remix-cloudflare/blob/master/app/mantine-polyfill.js

See the full repo for a working example. You need to import the exported `createStyleServer` in your `entry.server.tsx`

**Comment by larissa-n** [comment]
@nastynaz yes I saw that. Great solution. What I was talking about is that `@mantine/ssr` still references `@emotion/server`. Your polyfill is there to replace it and it shouldn't be a dependency, but the import line in `@mantine/ssr` is still there. And it looks like you didn't fork `@mantine/ssr`. Right? Thanks!
