### ISSUE TITLE
Select and checkbox don't have `cursor: pointer` css

### ISSUE THREAD

**Issue by hunterwilhelm** [mantinedev/mantine#1036]
### What package has an issue

@mantine/core

### Describe the bug

When I hover over <Select/> and <Checkbox/> they don't have the CSS `cursor: pointer` enabled. The browsers tell them to just have the normal cursor look.

### In which browser did the problem occur

Chrome, Safari

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/switch-no-pointer-mantine-u6ez5p?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Add `cursor: pointer` to the CSS of input and label. Because those have click events attached to them.

**Comment by rtivital** [comment]
Default checkbox does not have pointer cursor. You can add cursor styles to your components using Styles API – https://codesandbox.io/s/switch-no-pointer-mantine-forked-fdgtq9?file=/src/App.tsx

**Comment by elibroftw** [comment]
Helper:
```jsx
const styles = {
    checkbox: { input: {cursor: 'pointer'}, label: {cursor: 'pointer'} }
}
return (
  <Checkbox styles={styles.checkbox} label={t('Has the corporations address changed since the last time the CRA was notifiied?')} />
);
```

**Comment by Toshinaki** [comment]
@rtivital 
As @hunterwilhelm also mentioned select, https://mantine.dev/core/select/#clearable
this document page shows a _clearable_ select(1) and a _clearable_+_searchable_ select(2).

1 has pointer cursor and 2 has text cursor. 

I can see the cursor of select is default to pointer and becomes text cursor when `searchable` is set.
Is this inconsistency the expected behavior?

**Comment by rtivital** [comment]
It is expected behavior

**Comment by kaviyarasank** [comment]
Working.....
