### ISSUE TITLE
Group column behaviour doesn't match Box with the same styles

### ISSUE THREAD

**Issue by itmecho** [mantinedev/mantine#1040]
### What package has an issue

@mantine/core

### Describe the bug

Looking at the `Group` component documentation, I would assume that the `position` prop would apply the `justify-content` CSS property regardless of the `direction` prop. However, it seems to only work properly when `direction` is set to `row`.

In other words, I would assume these to have the same behaviour:
```tsx
<Group direction="column" position="apart" grow sx={{ height: "100%" }}>
```

```tsx
<Box
  sx={{
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    flexGrow: 1,
  }}
>
```

It would seem this was fixed previously (https://github.com/mantinedev/mantine/pull/755) but has been reintroduced?

### In which browser did the problem occur

Firefox

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/silly-worker-dcly0c?file=/src/App.js

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Reapply the changes from https://github.com/mantinedev/mantine/pull/755 to the latest codebase

**Comment by itmecho** [comment]
Oh my bad, I've just seen these changes were rolled back on `4.0.3`!

**Comment by rtivital** [comment]
It will be fixed the other way in future releases.
