### ISSUE TITLE
LoadingOverlay causes 'React state update on unmounted component'

### ISSUE THREAD

**Issue by chris-metz** [mantinedev/mantine#1041]
### What package has an issue

@mantine/core

### Describe the bug

I'm using LoadingOverlay on a login page and control it's visibility with react-query's mutation 'isLoading' state.

When the form submit / login is successful, a call to react-router's 'navigate()' function is invoked.

Upon navigating , the following warning is issued:

![grafik](https://user-images.githubusercontent.com/3713630/159123854-7d73901d-3110-4dcc-aea0-9e7dd4573743.png)

This problem does not occur when removing the LoadingOverlay component. Any suggestions on how to fix this?

### In which browser did the problem occur

All tested browsers (FF, Chrome)

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by mctessi** [comment]
Could you please provide more information like your package.json? A minimal code example would be very beneficial, since I was not able not reproduce this behavior with the current versions of @mantine/core, @mantine/hooks and react-router-dom! 
Regards

**Comment by chris-metz** [comment]
I can't reproduce it with just this libraries in a sandbox, too. Will close this, sorry for the issue.
