### ISSUE TITLE
Some components still uses padding prop

### ISSUE THREAD

**Issue by alimehasin** [mantinedev/mantine#1063]
### What package has an issue

@mantine/core

### Describe the bug

I have noticed that the Drawer component **still have padding prop and not p**, but I have read in the v4 release note that all component now support the new (p, px, ...) props and some padding props have been renamed to the new (p, ...), after I search the source code I have found that there are a couple of components still have padding prop
1. [AppShell](https://github.com/mantinedev/mantine/blob/800923221e80798be17da9da680edb7ba924c187/src/mantine-core/src/components/AppShell/AppShell.tsx#L34)
2. [Drawer](https://github.com/mantinedev/mantine/blob/800923221e80798be17da9da680edb7ba924c187/src/mantine-core/src/components/Drawer/Drawer.tsx#L42)
3. [Modal](https://github.com/mantinedev/mantine/blob/800923221e80798be17da9da680edb7ba924c187/src/mantine-core/src/components/Modal/Modal.tsx#L76)
4. [Dropzone](https://github.com/mantinedev/mantine/blob/800923221e80798be17da9da680edb7ba924c187/src/mantine-dropzone/src/Dropzone/Dropzone.tsx#L23)
5. [CardSection](https://github.com/mantinedev/mantine/blob/800923221e80798be17da9da680edb7ba924c187/src/mantine-core/src/components/Card/CardSection/CardSection.tsx#L12)
6. [FullScreenDropzone](https://github.com/mantinedev/mantine/blob/800923221e80798be17da9da680edb7ba924c187/src/mantine-dropzone/src/FullScreenDropzone/FullScreenDropzone.tsx#L33)

### In which browser did the problem occur

Brave

### Do you know how to fix the issue

Yes

### Possible fix

Make these components accepts (p, px, ...) and delete padding prop, it is also possible to make **all components accept padding prop along with (p, px, ...)** this solution might be better for backward compatibility and for those how wants to use padding prop instead of p

**Comment by rtivital** [comment]
In these components, padding prop does not work the same way as `p` prop (it does not add padding to root element), and thus it should remain as is to avoid contusion.
