### ISSUE TITLE
Default button background colour is transparent, only shows on hover

### ISSUE THREAD

**Issue by MarkwinVI** [mantinedev/mantine#1064]
### What package has an issue

@mantine/core

### Describe the bug

Whenever I use the Button component with the "filled" variant or just leave the variant prop blank, the button's default colour is always transparent and only shows up when I hover over it. 

With the "outline" variant this doesn't happen.

I can solve this by manually adding the background property to the button, but this isn't an ideal solution 

### In which browser did the problem occur

Chrome / Brave

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
You have global styles that override Mantine component styles, you can set prepend: false if you want to prevent global styles from overriding Mantine styles – https://mantine.dev/theming/mantine-provider/#change-styles-insertion-point

**Comment by zephaniahong** [comment]
@rtivital Hi! I'm facing the same issue. Could you clarify as to where to put the ```prepend: false```? I cant' seem to find it in the documentation.

Thank you!

**Comment by tarasowski** [comment]
Thank you for the solution! @rtivital
