### ISSUE TITLE
Static font size should be removed from Table component

### ISSUE THREAD

**Issue by reorx** [mantinedev/mantine#1065]
### What package has an issue

@mantine/core

### Describe the bug

In https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/Table/Table.styles.ts there are multiple occurrences of `font-size: 14` which should be removed, so that the font size on ancestors could be properly passed down.

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 4.0.8, table font size can now be controlled with `fontSize` prop
