### ISSUE TITLE
the `onClose` in NotificationProps should be optional ?

### ISSUE THREAD

**Issue by ikapta** [mantinedev/mantine#1077]
### What package has an issue

@mantine/core

### Describe the bug

In typescript file, while I copy official site <Notification /> demo, I get the issue below. so I thank `onClose` property is should be optional?  (when I custom it by MantineProvider, also I get this issue. respect~

`_Property 'onClose' is missing in type '{ children: string; title: string; }' but required in type 'NotificationProps'._` 

![image](https://user-images.githubusercontent.com/1364025/159613555-b2093cc4-004a-40e8-9430-607caedae438.png)

### In which browser did the problem occur

chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/happy-elgamal-mb5mq8?file=/src/App.tsx

**Comment by rtivital** [comment]
Fixed in 4.0.8
