### ISSUE TITLE
Rich text editor. Pasting over highlighted text deletes old text and doesn't paste new text.

### ISSUE THREAD

**Issue by runthis** [mantinedev/mantine#1086]
### What package has an issue

@mantine/rte

### Describe the bug

Highlight some text in the rich text editor, paste new text over it. The old text is deleted and the new text is not added. Unable to replicate using react quill without Mantine.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/nice-proskuriakova-iqbrl8?file=/src/App.tsx

### Do you know how to fix the issue

No

### Possible fix

Unsure if related: https://stackoverflow.com/questions/59825450/react-quill-custom-image-handler-module-causing-typing-issues-with-the-editor

**Comment by rtivital** [comment]
Fixed in 4.1.3
