### ISSUE TITLE
KeyboardEvent.code vs KeyboardEvent.key from KeyboardEvent 

### ISSUE THREAD

**Issue by caldunn** [mantinedev/mantine#1091]
### What package has an issue

@mantine/spotlight

### Describe the bug

Hi,

"Pop up" elements such as modals and the spotlight search can be closed using the `ESC` key. The event listening matches based on `KeyboardEvent.code` which reflects the physical key pressed instead of the key it is mapped to. This means that you have to press the physical `ESC` key instead the key that it is bound to.

For example,
I have swapped `ESC` and `CapsLock` keys.
![image](https://user-images.githubusercontent.com/49628408/159924431-d4270f61-a76b-4387-b0bb-5eeaf6ba7dd6.png)

[Google Dev Blog about KeyboardEvent code vs key](https://developers.google.com/web/updates/2016/04/keyboardevent-keys-codes)

I am fairly new to the React scene and maybe `KeyboardEvent.code` is used for cases beyond my knowledge. 

Thanks!

### In which browser did the problem occur

Chrome-Based (Chromium 99)

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Switch case statements to match on KeyboardEvent.key instead of KeyboardEvent.code.

**Comment by rtivital** [comment]
`event.key` is not used because it will not work for users with languages that are not English. For example, when I press `K` button on my keyboard:
- With English language: `event.code` is `K`, `event.key` is `K`
- With Russian language: `event.code` is `K`, `event.key` is `Л`
This makes it impossible to handle most of the keyboard events.

**Comment by caldunn** [comment]
Ahh that makes sense.

Thanks for the library its an absolute blast to use.
