### ISSUE TITLE
Move table from Typography to Data Display

### ISSUE THREAD

**Issue by adamerose** [mantinedev/mantine#1096]
### Link to the page where something nasty is located

https://mantine.dev/core/table/

### Exact quote of what is wrong

I think the Table component docs page should be under `Data Display` rather than `Typography`. This would be more intuitive and conform with other packge docs like Antd & PrimeReact.

![image](https://user-images.githubusercontent.com/10884874/160006123-6e47b692-8e69-4e6e-8a27-e61e73f5d8c7.png)

**Comment by rtivital** [comment]
I consider table to be a typography component, it should remain as it.

**Comment by egyptik** [comment]
@rtivital I think a case can be made for both. The current Table implementation is great for simple, small tables that would fit under the typography definition. But what is currently missing is a virtualized table / data table for more advanced tables with larger datasets and features such as sorting, resizing, row selection, etc.

Here's a great example of such a component:

https://element-plus.org/en-US/component/table-v2.html
