### ISSUE TITLE
Can't import TransferListData

### ISSUE THREAD

**Issue by Alecattie** [mantinedev/mantine#1099]
### What package has an issue

@mantine/core

### Describe the bug

Attempted import error: 'TransferListData' is not exported from '@mantine/core'.

### In which browser did the problem occur

Safari

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
It works fine in codesandbox – https://codesandbox.io/s/musing-haibt-6usk31?file=/src/App.tsx
Type is exported from the package.
