### ISSUE TITLE
Examples page claims to be 404

### ISSUE THREAD

**Issue by AbreuOliver** [mantinedev/mantine#110]
The /examples pages claims to be a 404 error page.
Otherwise, the docs look great!

**Comment by rtivital** [comment]
Hi, thanks for reporting, how did you get on this page? I've removed it from the site so this is expected

**Comment by AbreuOliver** [comment]
https://user-images.githubusercontent.com/38667404/120549958-3f6b4b00-c3c2-11eb-9472-0ab2c02a822f.mov

The GitHub page for Mantine lists an `Examples` page (https://mantine.dev/pages/examples/) that claims to be a secret 404 page. I have included a video showing the issue.

**Comment by rtivital** [comment]
Thanks for video feedback, the issue was fixed
