### ISSUE TITLE
Module not found: Error: Can't resolve './icons/brand-firefox.js' in '*/mantine/node_modules/tabler-icons-react/dist'

### ISSUE THREAD

**Issue by alimehasin** [mantinedev/mantine#1104]
### What package has an issue

@mantine/core

### Describe the bug

I have followed the [contributing page](https://mantine.dev/pages/contributing/#get-started-with-mantine-locally) but when I run "npm run storybook" I got the following error

> ERROR in ./node_modules/tabler-icons-react/dist/index.js
Module not found: Error: Can't resolve './icons/brand-firefox.js' in '*/mantine/node_modules/tabler-icons-react/dist'

"npm run docs" command also have not work for the same reason

### In which browser did the problem occur

None

**Comment by rtivital** [comment]
Try reinstalling dependencies

**Comment by alimehasin** [comment]
> Try reinstalling dependencies

I have pulled the latest changes, delete node_modules and reinstall but got the same issue.

**Comment by rtivital** [comment]
Well, no idea how to help you then

**Comment by alimehasin** [comment]
After updating tabler-icons-react to the latest version "v1.41.0", I managed to solve the problem
