### ISSUE TITLE
Having two Text components as children causes infinite re-renders

### ISSUE THREAD

**Issue by Chrischuck** [mantinedev/mantine#1105]
### What package has an issue

@mantine/core

### Describe the bug

Hello, very weird issue and I was unable to repro in a codesandbox. I have a work around, but curious what could potentially be the issue. I was getting infinite re-renders in my app and was able to narrow it down to a seemingly simple/innocuous component:

<img width="672" alt="Screen Shot 2022-03-26 at 10 45 07 AM" src="https://user-images.githubusercontent.com/13311268/160251402-75a405dd-5af3-4239-9c75-2bab6bed7f49.png">

When I deleted the `<Text>` tag that contained the `title` param, the re-rendering would stop. I tried deleting the `<Text>` tag containing the `subtitle` param but the re-rendering continued. I removed the props from the `title` param text tag, but it still persisted.

Eventually I just switched the `title` param to a `Title` tag and the issue stopped.

Curious what could be the problem here?

build: 

"next": "v12.0.11-canary.7",
"@mantine/core": "^4.0.7",
"@mantine/next": "^4.0.7",

### In which browser did the problem occur

Chrome Version 99.0.4844.83

**Comment by rtivital** [comment]
Please send a sandbox with an issue, note that we do not support experimental builds and features of Next.js. Also make sure that your issue is caused by Mantine components.

**Comment by Chrischuck** [comment]
Hi @rtivital, Issue was actually on our end with a scrollable component causing the re-render. Apologies.
