### ISSUE TITLE
Mapping Accordion Items

### ISSUE THREAD

**Issue by jacksonblankenship** [mantinedev/mantine#1106]
### What package has an issue

@mantine/core

### Describe the bug

I'm attempting to map `Accordion.Item`'s into an `Accordion`. I'm doing this because I need to have control over the item's label prop from a child component. I'm using data from a hook to populate this property. When I use the accordion normally, I don't have any issues. However, if I create an `Accordion.Item` in a child component, import it into the parent, and use it for a map function, nothing renders. (this is a bit confusing to type out so I included a CodeSandbox lol)

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/strange-framework-cxtobf?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

I've messed around with this quite a bit and haven't figured out a way around it. I'm wondering if this is a ref/forwardRef issue?

**Comment by jacksonblankenship** [comment]
I'm not sure how committal the "willing to participate" question is, but I'm happy to help investigate further. I'm just pretty tight on time so I defaulted that question to "no."

**Comment by jacksonblankenship** [comment]
I'm noticing now that the types for the `Accordion` children specifically say the following...

```
/** <AccordionItem /> components only */
children: React.ReactNode;
```

This may be a dumb question, but would that rule out custom children? Is there a way to work around this?

**Comment by rtivital** [comment]
Yes, currently that is not supported, it will require breaking changes, so Accordion and other similar components will be Migrated to context with next major release (5.0)
