### ISSUE TITLE
Transition durations = 0

### ISSUE THREAD

**Issue by SamyZog** [mantinedev/mantine#1110]
### What package has an issue

@mantine/core

### Describe the bug

Great effort, love the library.

using 4.0.8

On your transitions demo page (https://mantine.dev/core/transition/) in the docs animations do not seem to work, tested locally, also no animation. For example I added a tooltip with a transitionDuration = 300 and nothing, checked the console there was no transition duration applied to it. Is this correct behavior? Am I missing something?

Adding transitionDuration to root and body selectors via Styles API did not work.

### In which browser did the problem occur

chrome 99, edge 99

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Most of the Mantine animations are based on Transition component. It checks if user prefers to reduce motion and if it is so, then all animations are disabled. It can be configured in the settings of your OS.

**Comment by SamyZog** [comment]
> Most of the Mantine animations are based on Transition component. It checks if user prefers to reduce motion and if it is so, then all animations are disabled. It can be configured in the settings of your OS.

thanks for the answer, that was the reason. 

is there a way to prevent OS settings from affecting component animations?

**Comment by rtivital** [comment]
No, currently we do not support such option.
