### ISSUE TITLE
Creatable multiselect not working with `NumpadEnter`

### ISSUE THREAD

**Issue by jCobbSK** [mantinedev/mantine#1116]
### What package has an issue

@mantine/core

### Describe the bug

On Large keyboard layouts with numeric parts, there is `NumpadEnter` key which should act the same as the enter key. In `<MultiSelect />` (but probably in other inputs as well) this does not work.

To reproduce we can use `ANSI (Large)` mac virtual keyboard.

<img width="1069" alt="Screenshot 2022-03-28 at 07 41 04" src="https://user-images.githubusercontent.com/4012010/160334046-4dd39e11-8ab6-4c2e-b9bd-7b72de4e1e17.png">

### In which browser did the problem occur

All

### Possible fix

I think we can either add `case 'NumpadEnter'` in addition to `case 'Enter'` to `handleInputKeydown` or change switch value to `event.nativeEvent.key` instead of `event.nativeEvent.code`

**Comment by rtivital** [comment]
@achmurali Can you add `NumpadEnter` support for Autocomplete, Select, MultiSelect, TransferList, DatePicker, DatePickerBase, TagInput and Spotlight component?

**Comment by achmurali** [comment]
> @achmurali Can you add `NumpadEnter` support for Autocomplete, Select, MultiSelect, TransferList, DatePicker, DatePickerBase, TagInput and Spotlight component?

Yeah, definitely

**Comment by rtivital** [comment]
@achmurali nvm, I'll be working on another solution for this

**Comment by rtivital** [comment]
Fixed in 5.0
