### ISSUE TITLE
useNotifications creates an endless loop

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#1121]
### What package has an issue

@mantine/notifications

### Describe the bug

The notification is repeatedly shown again and again.
When the useNotifications is used in a useEffect

### In which browser did the problem occur

Brave

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/compassionate-lederberg-3f555d

**Comment by jerebtw** [comment]
Because of the new event-based system, it's probably not worth fixing

**Comment by rtivital** [comment]
Will not fix that, simply do not pass it to useEffect, functions will be removed from hook in 5.0
