### ISSUE TITLE
App shell "View full source code" link redirects to a 404.

### ISSUE THREAD

**Issue by paolotiu** [mantinedev/mantine#1124]
### Link to the page where something nasty is located

https://mantine.dev/core/app-shell/

### Exact quote of what is wrong

![image](https://user-images.githubusercontent.com/61054234/160529159-8266d648-3d1f-4a5b-b562-c4f907fa8d5f.png)

When clicking "View source code", the page redirects to a GitHub 404 page. 

I would like to work on this.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Thanks for reporting, the issue was fixed.
