### ISSUE TITLE
FloatingTooltip position bugs on elements at the extremeties

### ISSUE THREAD

**Issue by official-carledwardfp** [mantinedev/mantine#1126]
### What package has an issue

@mantine/core

### Describe the bug

- [ ] Floating tooltip position bugs when you put the target element at the extreme sides of the viewport/container

### In which browser did the problem occur

Chrome, Safari

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/charming-wave-yn3gv3?file=/src/App.tsx

### Possible fix

Update `coordinates` to return correct `x` and `y` positions

**Comment by mctessi** [comment]
@maintainers 

Unfortunately I cannot provide a solution but maybe some hints for someone more familiar with the codebase and the overall publishing process to npm! 
This glitch seems to occur, if one installs @mantine/core and @mantine/hooks v4.1.0 (v4.0.9 also tested) via npm. Building the repo locally, both against master and next-minor seems to resolve the issue! 
To troubleshoot I have created a vanilla vite react-ts project 'issue-1126' in src/mantine-core and imported the freshly build stuff via: 
`import { Box, Group, FloatingTooltip, MantineProvider } from '../../esm/index'; // works like a charm except from eslint errors
// import { Box, Group, FloatingTooltip, MantineProvider } from '@mantine/core'; // glitch`
Hope it helps somebody to resolve the issue

Kind regards

**Comment by mctessi** [comment]
take

**Comment by wes337** [comment]
I'm able to see this bug in your Codepen example, but I'm not able to reproduce it when running Mantine on localhost. The import fix you found is quite strange.

I also noticed that removing the `withGlobalStyles` and `withNormalizeCSS` props from `MantineProvider` causes the working tooltip to break in the same way.

**Comment by wes337** [comment]
Also, setting `withinPortal={false}` will fix this in your Codepen example.

**Comment by auronsan** [comment]
it's not happen on storybook. but happen on just normal component. it's weird glitch from position props of mantine popper
