### ISSUE TITLE
API to override input sizes

### ISSUE THREAD

**Issue by Krantisinh** [mantinedev/mantine#1128]
Hi,

I am redesigning Mantine components as per our organization's design system. I want to change the height & padding of all input elements to match our design guidelines. e.g. 

height of buttons for
- 'sm' size should be 32 instead of the default 36
- 'md' size should be 40 instead of the default 42

I found that there's is `const` defined in the code under https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/Input/Input.styles.ts

`
export const sizes = {
  xs: 30,
  sm: 36,
  md: 42,
  lg: 50,
  xl: 60,
};
`
Is there a way to override these sizes through Styles API? I want to have something similar to below snippet.

```
export const Styles = {
  Button: (theme: MantineTheme) => ({
    // root: {
      // [if(ButtonSize === 'lg')]: { height: 48 },
      // [if(ButtonSize === 'md')]: { height: 40 },
      // [if(ButtonSize === 'sm')]: { height: 32 },
    // },
    filled: {
      backgroundColor: theme.colors.blue[5],
      '&:hover': {
        backgroundColor: theme.colors.blue[6],
      },
    },
    outline: {
      borderColor: theme.colors.blue[5],
      color: theme.colors.blue[5],
      '&:hover': {
        backgroundColor: theme.colors.blue[0],
      },
    },
  }),
};
```

**Comment by rtivital** [comment]
No, currently it is not supported though styles API on MantineProvider.

**Comment by Krantisinh** [comment]
I found a way to resolve this using `ButtonStyleParams` -

```

const CustomSize: { [ key in MantineSize]: CSSObject } = {
    xs: {
      size: 24,
    },
    sm: {
      size: 32,
    },
    md: {
      size: 40,
    },
    lg: {
      size: 48,
    },
    xl: {
      size: 56,
    },
};


export const Styles = {
  Button: (theme: MantineTheme, params: ButtonStylesParams) => ({
    root: {
      height: CustomSize[params.size].size,
    },
  }),
};
```

**Comment by holzenburg** [comment]
@rtivital We also need this API feature and offer to implement it. Are you ok with that?

**Comment by rtivital** [comment]
It is planned to introduce a feature to customize sizes and variants with styles API. It is a breaking change thought, so it can only be introduced in version 6.0, which is planned to be released in Q2 of 2023.

**Comment by rtivital** [comment]
I want to avoid introducing a new feature that will result in breaking changes

**Comment by activenode** [comment]
Does it result in breaking changes? I would assume it would not. Sample:

Currently in `Input.styles.ts` we see this hardcoded:

```
export const sizes = {
  xs: 30,
  sm: 36,
  md: 42,
  lg: 50,
  xl: 60,
};
```


-> The idea is to still have these exact values but move them simply to the theme defaults same as `spacing: {}` we would simply use the component defaults which could then be overridden in a way that shouldn't be breaking: `components: { Input: { whateverSizes } }`

Or even more analogous to `spacing`:

`theme = { sizes: { Input: { xs: 123, ... }}}`

But by default they would be the same old hardcoded values.

**Comment by rtivital** [comment]
I mean that if we introduce this feature now, then it will require additional breaking changes in 6.0

**Comment by activenode** [comment]
Understood
