### ISSUE TITLE
Notification autoClose prop triggers React warning

### ISSUE THREAD

**Issue by akhrarovsaid** [mantinedev/mantine#1129]
### What package has an issue

@mantine/notifications

### Describe the bug

When using @mantine/notifications package version 4.1.0, providing the autoClose prop triggers the following React warning:

`Warning: React does not recognize the 'autoClose' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase 'autoclose' instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

The component still behaves as expected aside from throwing this warning.

### In which browser did the problem occur

Chrome Version 99.0.4844.84 (Official Build) (64-bit)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-dev-notification-autoclose-bug-4kfzi1?file=/src/App.tsx

### Possible fix

Prevent passing 'autoClose' prop to underlying HTML element.

**Comment by rtivital** [comment]
Fixed in 4.1.2
