### ISSUE TITLE
Modal with target element is not rendered correctly

### ISSUE THREAD

**Issue by pgr3931** [mantinedev/mantine#1134]
### What package has an issue

@mantine/core

### Describe the bug

A ```<Modal>``` element is still rendered at the center of the screen even if it has a query selector as its ```target``` prop.

I assume this is because it uses an ```<Overlay>``` element that uses the whole screen height and width.

To reproduce the issue simply give an element an id of ```#test``` and set the modal like this:
```<Modal opened={true} onClose={() => {}} target={'#test'} >```

Furthermore, if the target is a button element like ```<ActionIcon>``` then the modal is rendered inside of it, which triggers a re-render on every click outside or inside the modal.

See the codesandbox for an example

### In which browser did the problem occur

Firefox, Edge

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/wonderful-sun-vbfih6

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
In 99% of cases, you should not specify a target element for the Modal. Target prop is used to specify a container that Portal will use to add node to. Appending modal node to ActionIcon does not make any sense, do not do that – use Modal as described in documentation and everything will be fine.

**Comment by pgr3931** [comment]
Alright, thank you for the answer!

What I'm trying to achieve is a modal that is next to any item, while also having an overlay effect.
I want to use this for a "News" modal, that highlights new items (e.g. a new button) and provides some text.

how would I go about implementing something like this? Or is this something I need to do myself?

**Comment by rtivital** [comment]
Set `<Modal withinPortal={false} />`
