### ISSUE TITLE
[Violation] Forced reflow while executing JavaScript took 830ms

### ISSUE THREAD

**Issue by dexter4life** [mantinedev/mantine#1135]
### What package has an issue

@mantine/core

### Describe the bug

When using the ScrollArea, the scrollbar lags or delays by some milliseconds and cause this message to be shown 

[Violation] Forced reflow while executing JavaScript took 830ms

### In which browser did the problem occur

Google Chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I believe to fix this problem, we might have to look at the async function used in useCallback maybe this is the reason. Since is possible that the async wait is taking longer than what is expected.

**Comment by rtivital** [comment]
Please send a sandbox that reproduces this issue. There are no such errors on mantine.dev website.

**Comment by PandasProperty** [comment]
@dexter4life have you found a fix or the cause of the issue? Help would be very much appreciated.
