### ISSUE TITLE
Select sends label as value in form

### ISSUE THREAD

**Issue by fubz** [mantinedev/mantine#1137]
### What package has an issue

@mantine/core

### Describe the bug

Trying to use the Select component with the built in label, value feature; however, upon posting the Select component through an html form the label is sent instead of the value.  I found this while using Remix, but the same symptoms occur with a plain html form.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/distracted-bell-lbtm8m?file=/app/routes/index.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by ramlab-jose** [comment]
I encountered the same bug. A workaround seems to be using the controlled version of the Select component, which correctly uses the value for the `onChange` callback.

**Comment by joelrozen** [comment]
I also came across this issue today, I found a work around though. The onChange handler providers the correct value, so you just need to change to be a controlled component.

Taking your example:

```typescript
export const action: ActionFunction = async ({ request }) => {
  const form = await request.formData();
  const [selectedEnv, setSelectedEnv] = useState();

  console.log({ form: JSON.stringify(form) });

  return null;
};

export default function Index() {
  return (
    <Form method="post">
      Select Bug Label vs Value
      <Select 
          name="env"
           label="Environment"
          data={environment} 
          value={selectedEnv}
          onChange={setSelectedEnv} 
      />
      <Button type="submit">Submit</Button>
    </Form>
  );
}
```

**Comment by joelrozen** [comment]
Adding to this though - the onChange function gets passed the value and only the value. It would be great if this could instead get passed the event instead to keep consistency (I note onBlur gets passed the full event).

**Comment by rtivital** [comment]
> Adding to this though - the onChange function gets passed the value and only the value. It would be great if this could instead get passed the event instead to keep consistency (I note onBlur gets passed the full event).

That is not possible with Select component, and will never be implemented.

**Comment by rtivital** [comment]
Fixed in 4.1.2, hidden input was added with real select value, also applicable to MultiSelect component

**Comment by pavi2410** [comment]
@rtivital This [patch](https://github.com/mantinedev/mantine/commit/383a040f691e7f6a085c28948799e7895c864d67) breaks form functionality.

```jsx
<Select
 form="update_form"
 name="category"
 label="Category"
 data={_.keys(CATEGORIES)}
 value={category}
 onChange={setCategory}
/>
```

results in two inputs:

```html
<input type="hidden" name="category" ... />
<input form="update_form" ... />
```

**Comment by rtivital** [comment]
Okay, I'll fix that with next patch
