### ISSUE TITLE
Checkbox in Accordion.Item label rotates when clicked

### ISSUE THREAD

**Issue by kbzowski** [mantinedev/mantine#1140]
### What package has an issue

@mantine/core

### Describe the bug

Placing a checkbox in the Accordion.Item label causes it to rotate when the item is expanded.

### In which browser did the problem occur

Chrome 99.0.4844.82

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/optimistic-wood-vi0txe?file=/src/App.tsx:0-681

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Checkbox should not rotate

**Comment by rtivital** [comment]
Set `disableIconRotation` prop on Accordion component if you do not want that – https://codesandbox.io/s/pensive-darkness-5y57l5

**Comment by kbzowski** [comment]
Thank you for the reply. This is the solution, but I don't mind rotating the icon to the right. I would like to keep this functionality without rotating the Checkbox in the label.

**Comment by rtivital** [comment]
You can implement this with Styles API
