### ISSUE TITLE
Modal `Transition` initial rendering has no effect

### ISSUE THREAD

**Issue by u3u** [mantinedev/mantine#1142]
### What package has an issue

@mantine/core

### Describe the bug

If I render a `Modal` component via dynamic import, there is no transition effect when I first open it

Like this:

```jsx
import dynamic from 'next/dynamic';
import { Modal } from '@mantine/core';

const Login = dynamic(() => import('login'), { ssr: false });

const Foo = () => {
  const login = useLogin();

  return (
    <>
      {/* No transition effect when both `render` and `opened` are `true` for the first time */}
      {login.render && <Login opened={login.opened} onClose={login.close} />}

      {/* Or set `opened` directly to `true` to have no transition effect when refreshing the page */}
      <Modal opended onClose={() => {}}>
        {/* ... */}
      </Modal>
    </>
  );
};
```

### In which browser did the problem occur

Any

### Do you know how to fix the issue

Yes

### Possible fix

The `Transition` component should have a property similar to `appear`

**Comment by rtivital** [comment]
To animate Modal on mount set `opened` state use useEffect – https://codesandbox.io/s/cocky-euler-hxxsq1?file=/src/App.tsx

**Comment by u3u** [comment]
Yes, that's how I solved it now, but Modal almost always needs to be imported dynamically, and each one needs to have similar logic written in it.

**Comment by rtivital** [comment]
You can create your own wrapper for Modal component that will use this logic.

**Comment by u3u** [comment]
Okay, I will try it, thanks!
