### ISSUE TITLE
AppShell Navbar footer hidden for mobile users with address bar on top

### ISSUE THREAD

**Issue by sunneydev** [mantinedev/mantine#1171]
### What package has an issue

@mantine/core

### Describe the bug

As mobile browsers implement `vh` units as the height of the screen the bottom part of the `Navbar` is not visible unless you manually scroll.

### Footer not visible
![photo_2022-04-03_08-59-45](https://user-images.githubusercontent.com/55714870/161412543-74d52059-3bdd-487b-8824-3495e0b228c0.jpg)

### Footer visible after scrolling
![photo_2022-04-03_08-59-45--2-](https://user-images.githubusercontent.com/55714870/161412779-6d2bc12f-d714-4c08-9e50-2984d12607f0.jpg)

![unknown](https://user-images.githubusercontent.com/55714870/161412382-a192a9e5-27a6-4ab2-91e5-300fc95087c6.png)

### In which browser did the problem occur

Any mobile browser with address bar on top

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/beautiful-water-4ipk7d

### Do you know how to fix the issue

Yes

### Possible fix

credits to @mattrunyon 

Adding `sx={{ bottom: 0, height: "auto" }}` to `Navbar`

**Comment by rtivital** [comment]
Thanks for reporting and investigation

**Comment by TobiasHansen** [comment]
Also getting this error, let me know if more information is needed.

**Comment by rayhk6** [comment]
Thanks for the temporary solution.

**Comment by IAFahim** [comment]
I have figured out if you add a bottom padding of
```paddingBottom: props.theme.spacing.xl``` it goes away
[GitHub link](https://github.com/IAFahim/uni/tree/master/src/Components/AppShell/FooterMantine)

**Comment by rtivital** [comment]
Fixed in 5.1.4, Navbar now has `bottom: 0` css property, we cannot set height to auto though as there are header and footer height dependencies in css variables. Height can be set with corresponding prop: `<Navbar height="auto" />`
