### ISSUE TITLE
useFullscreen hooks on custom element always returns false

### ISSUE THREAD

**Issue by eltongonc** [mantinedev/mantine#1172]
### What package has an issue

@mantine/hooks

### Describe the bug

When using the `use-fullscreen` hook on a [Custom root element](https://mantine.dev/hooks/use-fullscreen/#custom-root-element), the fullscreen property is always false.

```jsx
const { ref: videoFullscreenRef, toggle, fullscreen } = useFullscreen();

// fulscreen is always false

return (
 <PlayerWrapper ref={videoFullscreenRef}>
   {/* rest of children */}
   <button>{fullscreen ? <FiMinimize2 /> : <FiMaximize2 />}</button>
 </PlayerWrapper>
)
```

### In which browser did the problem occur

Chrome Version 99.0.4844.84 (Official Build) (x86_64)

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Does your `PlayerWrapper` component supports `ref` prop (have you used `forwardRef`)?

**Comment by eltongonc** [comment]
@rtivital Haven't looked into that, but `Playerwrapper` here is a `styled-component`, styled.div to be exact.
Will try to `forwardRef` and see if that works.

**Comment by eltongonc** [comment]
Forwarding the ref doesn't seem to work. I've tried:
```jsx
export const StyledPlayer = styled.div`
  position: fixed;
  width: 100%;
  height: 41vh;
  max-height: 400px;
  z-index: 2;
  overflow: hidden;

  @media ${device.tablet} {
    position: relative;
    padding-top: 39px;
    max-height: none;
  }

  @media ${device.laptop} {
    padding-top: 0;
    height: 100%;
  }
`;

export const PlayerWrapper = forwardRef(({ ...props }, forwardedRef) => {
  console.log('forwardedRef', forwardedRef); // inputRef

  // eslint-disable-next-line react/jsx-props-no-spreading
  return <StyledPlayer ref={forwardedRef} {...props} />;
});
```

**Comment by eltongonc** [comment]
@rtivital here is a minor update. I've copied the `useFullscreen` hook file to my project. 

When I log the `fullscreenElement` next to the `document` I see that document has a fullscreenElement, but if I log the fullscreenElement it returns `null`:

<img width="537" alt="Screenshot 2022-04-09 at 10 36 55" src="https://user-images.githubusercontent.com/14180132/162564009-6c3bc4fd-4780-470a-a665-431b3b8e0efa.png">
<img width="537" alt="Screenshot 2022-04-09 at 10 37 17" src="https://user-images.githubusercontent.com/14180132/162564010-d8e21fe6-9842-4bc0-85ab-fc72d640a429.png">
ment` it gives weird results:

**Comment by eltongonc** [comment]
@rtivital I've found the issue:
```jsx
 useEffect(() => {
   // Fullscreen change is only being handled if there is no custom ref
    if (!_ref.current && window.document) {
      console.log('no ref');

      _ref.current = window.document.documentElement as T;
      return addEvents(_ref.current, {
        onFullScreen: handleFullscreenChange,
        onError: handleFullscreenError,
      });
    }
   
   // adding this bit ensures the custom element toggles the fullscreen state
    if (_ref.current) {
      return addEvents(_ref.current, {
        onFullScreen: handleFullscreenChange,
        onError: handleFullscreenError,
      });
    }

    return undefined;
  }, []);
```

**Comment by rtivital** [comment]
Can you send a PR with a fix?

**Comment by eltongonc** [comment]
Done 
https://github.com/mantinedev/mantine/pull/1212

**Comment by rtivital** [comment]
Fix was merged and released
