### ISSUE TITLE
formList requires items to be an object

### ISSUE THREAD

**Issue by hyusetiawan** [mantinedev/mantine#1178]
### What package has an issue

@mantine/form

### Describe the bug

unable to use `formList` with non object, ex: array of strings because `getListInputProps` requires the field name, index, and then a required property name of the object inside the array. This does not make sense if the list is just a list of primitives such as string, number, etc. 

### In which browser did the problem occur

any

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

make the third parameter optional

**Comment by rtivital** [comment]
Form list is defined to work with objects only, it is intentional. If you want other values, you can use arrays instead of form lists.

**Comment by hyusetiawan** [comment]
@rtivital would you mind showing an example?

**Comment by rtivital** [comment]
https://codesandbox.io/s/elastic-goldwasser-7k3grh?file=/src/App.tsx
