### ISSUE TITLE
SegmentedControl does not render the correct width

### ISSUE THREAD

**Issue by T-Hugs** [mantinedev/mantine#1180]
### What package has an issue

@mantine/core

### Describe the bug

When a `SegmentedControl` is the direct child of a container with a fixed width and padding, because its `width` is set to `inherit`, it will always try to be the same width as its parent, causing it to overflow the padding. As you can see in this screenshot and linked CodeSandbox, the `SegmentedControl` overflows the Drawer:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/397836/161562687-88df08d0-4240-4bf3-a251-706823991a0f.png">

### In which browser did the problem occur

All of them

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/divine-architecture-sf2j3e?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Will follow up with a PR to fix, but I am very new to Mantine so please take it with a grain of salt.

Also, I think the `fullWidth` prop should be deprecated. There are many ways in CSS to affect an element's width (e.g. setting width and setting `flex-grow` - depending on the situation you might need one or the other). In the current case, the `fullWidth` prop is misleading at best. For the horizontal `SegmentedControl` it only affects whether the element is rendered inline or at block-level! If anything, the prop should be `inline` (but honestly I think that situation is so rare it should be left to a custom style).

**Comment by rtivital** [comment]
`fullWidth` prop should not be deprecated, it works as expected. The issue can be fixed by changing width to auto – https://codesandbox.io/s/romantic-chebyshev-y4xobg?file=/src/App.tsx

**Comment by T-Hugs** [comment]
Setting `width` to inherit by default is a bad design and leads to the "happy path" not working as expected. Of course there are ways to work around it (such as adding `width: auto` or nesting in a plain `div`). But if this is the accepted ideal behavior I will close the issue.

**Comment by rtivital** [comment]
It will be changed to auto in one of the next patches.

**Comment by rtivital** [comment]
Fixed in 4.1.4
