### ISSUE TITLE
Textarea show warning `value` prop on `textarea` should not be null

### ISSUE THREAD

**Issue by bogordesaincom** [mantinedev/mantine#1181]
### What package has an issue

@mantine/core

### Describe the bug

**Textarea**  component show warning: 

```

Warning: `value` prop on `textarea` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
```
<img width="1024" alt="Jepretan Layar 2022-04-04 pukul 23 11 21" src="https://user-images.githubusercontent.com/51335197/161586572-5d059beb-fb17-46e6-9cf3-a8048e4d9cb6.png">

### In which browser did the problem occur

chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
You are setting `null` value on your side.
