### ISSUE TITLE
Notifications position are not centered in mobile devices

### ISSUE THREAD

**Issue by princesust** [mantinedev/mantine#1183]
### What package has an issue

@mantine/notifications

### Describe the bug

When I set position="top-center" in NotificationsProvider it working fine in desktop. But in iphone it's not working. Please check the below screenshot
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/743248/161589912-12c7601e-e93e-4570-857e-ec6c46b08eef.png">

### In which browser did the problem occur

chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/damp-moon-cr6t9u?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Need to update the parent class of  **mantine-Notification-root** . you just need to add below code and it will work perfectly

```
left: 50%;
transform: translateX(-50%);
```

**Comment by rtivital** [comment]
Can you create a PR with a fix?

**Comment by princesust** [comment]
> Can you create a PR with a fix?

Sure, will do
