### ISSUE TITLE
TextInput type="number" does not work

### ISSUE THREAD

**Issue by elibroftw** [mantinedev/mantine#1194]
### What package has an issue

@mantine/core

### Describe the bug

```jsx
<TextInput label={'date' + ' (YYYYMMDD)' } type="number" minLength={8} maxLength={8} />
```
I can still enter letters in this textinput. Am I using it incorrectly?

### In which browser did the problem occur

Firefox

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by elibroftw** [comment]
The letters show up when typed but the onChange function does not get called unless a number was typed. value={} is not respected either.

**Comment by rtivital** [comment]
TextInput works exactly the same as `input[type="number"]`, nothing should be done on our side.
