### ISSUE TITLE
useForm issue with typescript: validate is not typed inside of the useForm interface

### ISSUE THREAD

**Issue by HelySaul** [mantinedev/mantine#1199]
### What package has an issue

@mantine/form

### Describe the bug

When trying to add the ```validate``` field to the useForm hook, it says that is not typed on the useForm interfac
<img width="1075" alt="Screen Shot 2022-04-07 at 11 23 31 AM" src="https://user-images.githubusercontent.com/17388459/162221738-08079aac-5fea-4c6c-a479-5363de957b65.png">

### In which browser did the problem occur

All of em

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Add the new type of the validate inside of the interface

**Comment by rtivital** [comment]
Where did you import `useForm` from?

**Comment by HelySaul** [comment]
> Where did you import `useForm` from?

@mantine/hooks..... Now I see the problem.

Still, you should remove the useForm from the hooks library

**Comment by rtivital** [comment]
It is left there until 5.0 release for backwards compatibility.
