### ISSUE TITLE
Module @mantine/hooks has no exported member 'formList

### ISSUE THREAD

**Issue by na0495** [mantinedev/mantine#1224]
### What package has an issue

@mantine/hooks

### Describe the bug

i'm trying to import `formList` but i got the following error :
<br>
![Screenshot from 2022-04-11 12-26-38](https://user-images.githubusercontent.com/36574492/162739024-ce1ac385-d574-4907-ac50-193ad0219251.png)

i have the last verison of Mantine v4.1.3

### In which browser did the problem occur

chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
`@mantine/hooks` does not export `formList`, it is exported from `@mantine/form` package like described in documentation.

**Comment by fatihhyldz** [comment]
Module '@mantine/form' has no exported member 'formList'

**Comment by fatihhyldz** [comment]
Module @mantine/hooks has no exported member 'formList

**Comment by fatihhyldz** [comment]
Module @mantine/form has no exported member 'formList`

**Comment by rtivital** [comment]
It was removed in 6.x, use the same documentation version as your packages.

**Comment by mfnash** [comment]
what should I use to replace 'formList' in version 7.x?

**Comment by rtivital** [comment]
https://mantine.dev/form/nested/#nested-arrays
