### ISSUE TITLE
NumberInput doesn't respect rightSectionWidth

### ISSUE THREAD

**Issue by frec-mike** [mantinedev/mantine#1225]
### What package has an issue

@mantine/core

### Describe the bug

The NumberInput appears to be ignoring the rightSectionWidth value.
I think the handling just needs to happen here:
https://github.com/mantinedev/mantine/blob/b5cf9f3654442656f30c56215491bfcd362f3521/src/mantine-core/src/components/NumberInput/NumberInput.tsx#L365

### In which browser did the problem occur

All

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Sorry, I don't know if I have time to actually try this out and test it at the moment but I think it would look something like this:
```
rightSectionWidth={
  rightSectionWidth !== undefined
    ? rightSectionWidth
    : hideControls
    ? 0
    : theme.fn.size({ size, sizes: CONTROL_SIZES }) + 1
}
```

**Comment by rtivital** [comment]
Fixed in 4.1.4
