### ISSUE TITLE
Modal scroll issue on mobile

### ISSUE THREAD

**Issue by dukesx** [mantinedev/mantine#1227]
### What package has an issue

@mantine/core

### Describe the bug

When I scroll on mobile, such as Samsung Galaxy S10 plus on Mobile Edge and Mobile Chrome, the modal and its overlay show weird behavior.

https://user-images.githubusercontent.com/5988991/162780832-456ab887-3f39-401f-ab30-0c1e733b863f.mp4

### In which browser did the problem occur

All mobile browsers on android 

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

No idea, it's weird behavior

**Comment by dukesx** [comment]
> I do not think that anything can be done on library level. Overlay already has fixed position with inset 0. Browsers have this gap during scrolling because they are trying to offset browser UI, which is usually located at the bottom and hidden when user scrolls down.

But what about the nasty glitch ? can that be fixed ?

**Comment by rtivital** [comment]
I cannot fix that, docs website works fine on iOS and I do not have Android phone to test it.
