### ISSUE TITLE
CheckboxGroup is not exported from @mantine/core

### ISSUE THREAD

**Issue by govindkumwat** [mantinedev/mantine#1233]
### What package has an issue

@mantine/core

### Describe the bug

./src/components/CategoryProduct.js
Attempted import error: 'CheckboxGroup' is not exported from '@mantine/core'.

### In which browser did the problem occur

Chrome, Firefox, Safari

### If possible, please include a link to a codesandbox with the reproduced problem
https://stackblitz.com/edit/react-akihuc

_No response_

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by ruessej** [comment]
I don't have the problem with the default codesandbox see: https://codesandbox.io/s/peaceful-panka-6zjwxv

**Comment by ruessej** [comment]
Also with the provided example i don't get that problem

![image](https://user-images.githubusercontent.com/85690286/162932674-b3f27916-16da-46fc-a52c-f90db00ae1e4.png)

You could try to delete the node_modules folder and reinstall your deps and restart your IDE
