### ISSUE TITLE
Select clearable button can't be removed from tab index

### ISSUE THREAD

**Issue by ahweis** [mantinedev/mantine#1241]
### What package has an issue

@mantine/core

### Describe the bug

When using the select component and enabling "Clearable" the cross (clear) button is included in the tab index, which make it less user-friendly when "tabbing" between multiple input elements.

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by ahweis** [comment]
> Do you want to create a PR with a fix? Should be pretty simple: add `clearButtonTabIndex?: -1 | 0` prop to Select, MultiSelect, DatePicker and DateRangePicker components.

I will give it a go shortly

**Comment by ahweis** [comment]
I have now added a pull request to get this into next minor release [PR](https://github.com/mantinedev/mantine/pull/1242)

**Comment by ahweis** [comment]
Sorry for the mixup - just needed to be sure to use a specific account for the contribution.

**Comment by rtivital** [comment]
Released in 4.1.4
