### ISSUE TITLE
Style won't applied on production

### ISSUE THREAD

**Issue by fuzunspm** [mantinedev/mantine#1248]
### What package has an issue

@mantine/core

### Describe the bug

When we are working on `yarn dev` mantine and it's packages are working fine with styles but when we switch over to `yarn start` which is `export NODE_ENV=production && next build && nodemon server.js`, mantine is working functionally but all styles are lost, even the defaults ones for mantine components like buttons. We have a few projects that are using mantine but only one of them has the issue. Mantine and Nextjs are both updated to the latest version.

I will provide sample codes if you guide me or request the part you need to look in to.

### In which browser did the problem occur

Firefox, Brave

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
I do not really know how to help you. From our side, we provide next template that is known to not have any issues – https://github.com/mantinedev/mantine-next-template

If you already have working apps, I can only recommend using them as a base for your other application. Also, see general instructions in #1246

**Comment by fuzunspm** [comment]
on production, non of mantine.* css classes not available like .mantine-196gdbl on a button, Is it possible to import .css file manually?

**Comment by rtivital** [comment]
Mantine does not have any css files, all styles are in js.

**Comment by fuzunspm** [comment]
I managed to fix this by adding 
```
emotionOptions={{ key: "mantine", prepend: false }}
```

into MantineProvider
