### ISSUE TITLE
Can't concanate multiple className from createStyles

### ISSUE THREAD

**Issue by ilomon10** [mantinedev/mantine#1259]
### What package has an issue

@mantine/core

### Describe the bug

I tried to make reuse component, let say `container`.

```tsx
//  Component.tsx

import { Box, Sx, createStyles } from "@mantine/core";

const useStyles = createStyles({
  //  mantine-AAA
  body: {
    // some style
  }
})

export const Container: React.FC = ({ children, sx, className})=> {
  const { classes } = useStyles();
  return (
    <Box
      sx={sx}
                //  mantine-AAA    mantine-BBB
      className={`${classes.body} ${className}`}
    >
      {children}
    </Box>
  )
}
```

```tsx
//  Home.tsx

import { Container } from "Container";
import { createStyles  } from "@mantine/core";

const useStyles = createStyles({
  //  mantine-BBB
  customStyle: {
    // some style
  }
})

const Home: React.FC = ()=> {
  const { classes } = useStyles();
  return (
    <>
      <Container
        className={classes.customStyle}
      >
        {/* some element */}
      </Container>
      <Container
        sx={{
          //  mantine-CCC
          // some custom inline style
        }}
      >
        {/* some element */}
      </Container>
    </>
  )
}

```

It gets combine their style and create new className
```html
<div class="mantine-DDD"></div> <!-- it get combine and generate new className -->
<div class="mantine-CCC"></div>
```

I need concanate className not combine style
```html
<div class="mantine-AAA mantine-BBB"></div> <!-- need just to concanate classname string -->
<div class="mantine-CCC"></div>
```

### In which browser did the problem occur

Tested on Chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

I need concanate className not combine style
```html
<div class="mantine-AAA mantine-BBB"></div> <!-- need just to concanate classname string -->
<div class="mantine-CCC"></div>
```

**Comment by rtivital** [comment]
I do not see why you need to concanate classes, Mantine does not support this option (and will not support in future). If you need static selectors, use Global component instead.

**Comment by ilomon10** [comment]
I think it cause of `cx` that merge className, how do i can disable that  for specific component, or any options to force write string without pass `cx` className on mantine component?

**Comment by rtivital** [comment]
You seem to just ignore my previous message, so one again: Mantine does not support this option for a reason, if you try to do it with concatenation you will have issues with styles overriding.

**Comment by IvanDimitrov2002** [comment]
Hi, well if it merges classnames then how to fix the problem with disappearing elements?

Example:
```js
<svg
      className={cx(classes.ham, open && classes.active, className)}
      viewBox="0 0 100 100"
      onClick={onClick}
    >
      <path
        className={cx(classes.line, classes.top)}
        d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"
      />
      <path className={cx(classes.line, classes.middle)} d="m 30,50 h 40" />
      <path
        className={cx(classes.line, classes.bottom)}
        d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"
      />
    </svg>```
    
I'm using Next.js and on dev everything is fine but once I build for prod and activate the `active` classname, the element disappears because the classname changes its name :/

**Comment by rtivital** [comment]
Class names is a low-level API that is handled by emotion. Provide a sandbox with a disappearing element, it is not clear what your issue is based on description alone. It works as expected in all Mantine components which use the same logic, e.g. https://codesandbox.io/s/wizardly-minsky-78esfi?file=/src/App.tsx

**Comment by IvanDimitrov2002** [comment]
Hi, here is a sandbox: [https://codesandbox.io/s/voion1](https://codesandbox.io/s/voion1)

Strangely enough, here when you build and start the project for prod, the SVG gets all messed up. On local, it just disappears when being clicked.

**Comment by rtivital** [comment]
@IvanDimitrov2002, I cannot reproduce that neither in sandbox nor with production builds in next-template – https://github.com/mantinedev/mantine-next-template/tree/mantine-1259

https://user-images.githubusercontent.com/10353856/163690615-26b53914-04de-4f04-a7c6-097cf5177064.mov



I do not really know how it is supposed to work, but my guess is that it works correctly

**Comment by IvanDimitrov2002** [comment]
Really strange...Something is happening on prod build, I will investigate further. Thanks

**Comment by IvanDimitrov2002** [comment]
Update: 
It turns out that putting font via a link in `_app.tsx` scrambles all styles in prod. Transferring them into `_documents.tsx` fixes the issue :)

**Comment by ilomon10** [comment]
@rtivital can you share best practice to custom and extending mantine please?

**Comment by rtivital** [comment]
@ilomon10 see documentation, it includes everything you need to use Mantine.
