### ISSUE TITLE
Mantine Menu Makes Scrollbar Appear/Disappear Quickly

### ISSUE THREAD

**Issue by justurbo** [mantinedev/mantine#1262]
### What package has an issue

@mantine/core

### Describe the bug

Makes the scrollbar flash when refreshing the page. Content shifts.
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/35397173/163674659-09cc585a-adb6-4e5c-b7ec-ca68170a1e02.png">

Works as expected. Content doesn't shift. Browser scrollbar is not appearing/disappearing quickly.
<img width="1599" alt="image" src="https://user-images.githubusercontent.com/35397173/163674688-600f3c37-54fa-49a8-80c0-e922dc2a191b.png">

I've tried the withinPortal flag without success. :(

### In which browser did the problem occur

Chrome

**Comment by rtivital** [comment]
I do not see browser scrollbars on your screenshots.

**Comment by justurbo** [comment]
> I do not see browser scrollbars on your screenshots.

I’ll record it once I get home

**Comment by justurbo** [comment]
Can no longer reproduce it. Could be a macOS or Chrome issue. This is the URL of the Mantine application that had the scrollbar appear/disappear on page switch/page refresh: https://bit.ly/3uN4EHa

**Comment by RaVeN-ShP** [comment]
This issue still seems to exist on both firefox and chromium (CEF) for me.

I've attached two gifs showing the issue. One for [CEF](https://i.imgur.com/OhQDw9P.gif)  and one for [Firefox](https://i.imgur.com/8BA4tOt.gif). The issue can be seen when switching to the "library" page. 


Source code is roughly equivalent to:

```
<ScrollArea>
  <SimpleGrid
    <Menu control={Card} >
      <Menu.Label>Settings</Menu.Label>
    </Menu>
    <Menu control={Card} >
      <Menu.Label>Settings</Menu.Label>
    </Menu>
    <Menu control={Card} >
      <Menu.Label>Settings</Menu.Label>
    </Menu>
     more menu items....
  </SimpleGrid>
</ScrollArea>
```

**Comment by RaVeN-ShP** [comment]
Seems like it's somehow related to React.StrictMode. The problem disappears after disabling it!

**Comment by rtivital** [comment]
Strict mode issue: not affecting production, disable strict mode to not have this issue in development.
