### ISSUE TITLE
Layout Shift with NextJS

### ISSUE THREAD

**Issue by killpowa** [mantinedev/mantine#1275]
### What package has an issue

@mantine/core

### Describe the bug

I set up a new project with NextJS and Mantine but when profiling the performance, I noticed that it causes a layout shift on load when importing a button. This does not happen with Chakra (the second layout shift is caused by an external font, you can ignore it).

Mantine Performance Profile
![image](https://user-images.githubusercontent.com/10165264/163734209-6dbce433-eb0d-4dfc-89c3-2340969a1a70.png)
![image](https://user-images.githubusercontent.com/10165264/163734838-99e1e2e9-c24b-4881-bf1b-ae1e75eda32a.png)

Chakra Performance Profile
![image](https://user-images.githubusercontent.com/10165264/163734214-2fd56fd3-b09f-45ca-aaf7-eb55b1691f43.png)

This can easily be reproduced by creating a new next project with

`npx create-next-app@latest`

For both Mantine and Chakra, you just need to set up the provider and import a button on the index page. If you profile using chrome's dev tools you'll see the LS in Mantine but not in Chakra. This is quite a dealbreaker for me.
Is there any way to fix this?

### In which browser did the problem occur

Chrome version 100.0.4896.88

**Comment by killpowa** [comment]
You can easily see what I'm talking about by disabling network cache, set slow 3g and run a performance profile on https://koperate-webapp-9uzlelns7-killpowa.vercel.app/.
On the other hand, if you try it with Chakra, it won't happen: https://koperate-webapp-gbzr9e5pq-killpowa.vercel.app/

**Comment by rtivital** [comment]
You need to setup server side rendering, follow getting started guide or used next template – https://github.com/mantinedev/mantine-next-template
