### ISSUE TITLE
RichTextEditor: TypeError: range is null

### ISSUE THREAD

**Issue by Eesssn** [mantinedev/mantine#1288]
### What package has an issue

@mantine/rte

### Describe the bug

Hi.
I' using this package in next js project and when i use onImageUpload method, it give a a runtime error.
my code is:
`import React from "react";
import axios from "axios";
import RichTextEditor from "../../../components/TextEditor";

function Create() {
  const [value, onChange] = React.useState("");

  const handleImageUpload = (file) =>
    new Promise((resolve, reject) => {
      const formData = new FormData();
      formData.append("image", file);

      fetch("/api/common/upload", {
        method: "POST",
        body: formData,
      })
        .then((response) => response.json())
        .then((result) => {
          resolve(result.url);
        })
        .catch(() => reject(new Error("Upload failed")));
    });

  return (
    <div>
      <RichTextEditor
        value={value}
        onChange={onChange}
        dir="rtl"
        lang="fa"
        onImageUpload={handleImageUpload}
      />
    </div>
  );
}

export default Create;
`

Am i doing wrong anything or it's bug?

### In which browser did the problem occur

firefox

**Comment by wes337** [comment]
Solution: https://github.com/quilljs/quill/issues/1940#issuecomment-821985035
