### ISSUE TITLE
Autocomplete - doesn't show list if the entered text = one of the options

### ISSUE THREAD

**Issue by cstrat** [mantinedev/mantine#129]
In most cases this is probably the expected behaviour, but there are edge cases which might want a flag to disable this.

With `Autocomplete` if you have entered the exact text of an option, the option list will not display even if there are options which still match the entered text.

For example if you had a data set of:

[John, John Butler, Johnny Drama, Johnny] - entering "John" would hide the other Autocomplete options.

I suggest there should be a toggle to disable this.

Reproduction:
https://codesandbox.io/s/mantine-autocomplete-syzs5?file=/src/App.js

My actual use case is the battery entry - there are many more options than that, but it is helpful to always see the matching options. You will see that the CR2020 option isn't even visible, if you type C it matches `C` and doesn't show an option. It would be good to still show matching CRxx options.

**Comment by cstrat** [comment]
If you use the incorrect case, you can see the behaviour I think might be preferred in some scenarios.

(search 'john' in the first or 'c' in the battery example)

**Comment by rtivital** [comment]
Yep, that's a bug, will fix it in 2.0.2, right now autocomplete checks if data has exact item, instead it should perform a regular search

**Comment by rtivital** [comment]
Resolved with #135
