### ISSUE TITLE
ColorInput in form in Popover: Selecting color causes the Popover to close

### ISSUE THREAD

**Issue by sourcelocation** [mantinedev/mantine#1290]
### What package has an issue

@mantine/core

### Describe the bug

https://user-images.githubusercontent.com/52459150/164230523-c7b5d199-2c0a-49e8-a5f5-842b0f9bfe97.mp4

The popover should not close after selecting a color from ColorInput

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/nice-brook-0fedvs

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
- https://mantine.dev/core/popover/#usage-with-other-overlays
- https://codesandbox.io/s/vigorous-paper-v5bnmi?file=/src/App.js

**Comment by sourcelocation** [comment]
Thanks
