### ISSUE TITLE
Mantine Menu hover event not working with NextLink passHref control

### ISSUE THREAD

**Issue by ilomon10** [mantinedev/mantine#1291]
### What package has an issue

@mantine/core

### Describe the bug

Tried to make Nav nested Menu link but it seem not working after i wrapped button with NextLink 
On my NextJS Project
```jsx
<Menu  
  control={
    <NextLink href={link.link} passHref>
      <Button component="a" href={link.link}>
        <span>{link.label}</span>
      </Button>
    </NextLink>
  }>
    {menuItems}
</Menu>
```

### In which browser did the problem occur

Chrome `latest`

**Comment by rtivital** [comment]
Menu can work only with components that accept `ref`, Next.js Link does not accept `ref`

**Comment by ilomon10** [comment]
How do i fix this with mantine style guide?

**Comment by rtivital** [comment]
Wrap it with div

**Comment by ilomon10** [comment]
Thank you
