### ISSUE TITLE
TimeInput onChange not called when cleared

### ISSUE THREAD

**Issue by micaww** [mantinedev/mantine#1294]
### What package has an issue

@mantine/dates

### Describe the bug

When a TimeInput is cleared using the "clearable" prop, the onChange prop is not invoked.

https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/TimeInput/TimeInput.tsx#L225

### In which browser did the problem occur

All

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Since the `handleClear` function is not using `setDate`, it doesn't ever call `props.onChange`

The easiest solution would be to call `onChange?.(null)` inside `handleClear`, or refactor to use setDate

**Comment by rtivital** [comment]
Thanks for reporting, would you like to create a PR with a fix?

**Comment by micaww** [comment]
sure, can do

**Comment by rtivital** [comment]
@micaww ping
