### ISSUE TITLE
Can't use DatePicker within a form as it triggers form to submit

### ISSUE THREAD

**Issue by cstrat** [mantinedev/mantine#130]
Love the `DatePicker` component - unfortunately it seems to submit any forms that it is part of.

See reproduction here:

https://codesandbox.io/s/mantine-date-picker-in-forms-nvo2f

**Comment by rtivital** [comment]
I forgot the `type=button` on the input, will fix in 2.0.2

**Comment by cstrat** [comment]
I didn't get to look under the hood but thats a much simpler issue than I thought it might be - awesome. I was worried there was an embedded form or something in the component.

**Comment by rtivital** [comment]
It's usually always the case in such situations as button element type defaults to submit

**Comment by rtivital** [comment]
Resolved with #135
