### ISSUE TITLE
Vertical centering of text

### ISSUE THREAD

**Issue by Kombustor** [mantinedev/mantine#1301]
### Link to the page where something nasty is located

https://mantine.dev/

### Exact quote of what is wrong

Not sure if that is intended, and also not sure if that is present when actually using Mantine, but almost all text on the website is not centered properly.

Maybe that is a design choice, although an odd one imo.

Some examples:
![image](https://user-images.githubusercontent.com/4238281/164704253-9a483db7-a84c-4e18-bcd5-ca2f429fe350.png)
![image](https://user-images.githubusercontent.com/4238281/164704417-b9260d31-bdb6-4d6f-922b-d390cdd53ef9.png)

**Comment by rtivital** [comment]
What browser and os are you using?

**Comment by Kombustor** [comment]
My user agent is `Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0`

**Comment by apoco** [comment]
I'm annoyed by the same thing. I notice if I uncheck the inline `line-height: 1.55` in the body CSS it fixes things.

**Comment by rtivital** [comment]
mantine.dev home page works correctly in Firefox
<img width="1276" alt="Снимок экрана 2022-08-11 в 19 42 54" src="https://user-images.githubusercontent.com/10353856/184187955-66cb3901-8fcf-4dba-9331-25c9c2913644.png">
