### ISSUE TITLE
Wrap useForm functions with useCallback

### ISSUE THREAD

**Issue by abdulgafur24** [mantinedev/mantine#1306]
### What package has an issue

@mantine/form

### Describe the bug

If use `setFieldValue` in `useEffect` and add it to the dependency array it will infinitely trigger `useEffect`

### In which browser did the problem occur

chrome

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

just wrap with useCallback

**Comment by rtivital** [comment]
Duplicate of #1196
