### ISSUE TITLE
PasswordInput loses it's focus and you can't type on it

### ISSUE THREAD

**Issue by NdozHH** [mantinedev/mantine#1313]
### What package has an issue

@mantine/core

### Describe the bug

The `PasswordInput` with popover to show strength loses focus when clicked and cannot be typed in, see the codesandbox. I'm using the version `4.1.2` of Mantine

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-forked-cgb9e8?file=/src/App.tsx

### Do you know how to fix the issue

No

**Comment by zhulien-ivanov** [comment]
This is not a bug. That happens because `Popover` traps the focus by default when opened thus removing it from the input. You need to apply `trapFocus={false}` on `Popover`.

**Comment by rtivital** [comment]
There is a working example in docs – https://mantine.dev/core/password-input/#strength-meter-example
