### ISSUE TITLE
Hightlight Type 'Element' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by kulame** [mantinedev/mantine#1321]
### What package has an issue

@mantine/core

### Describe the bug

i need to show a dangerouslySetInnerHTML on mantine <highlight> element.

```typescript 
      <Highlight
        highlight={word}
        size="sm"
        style={{ color: secondaryColor, lineHeight: 1.5 }}
      >
        <div
          dangerouslySetInnerHTML={{
            __html: purify.sanitize(data.content)
          }}
        />
      </Highlight>
```

it show error 
```shell
error TS2322: Type 'Element' is not assignable to type 'string'.
```

how can i do for this feature?

### In which browser did the problem occur

chrome

### Do you know how to fix the issue

Yes

**Comment by rtivital** [comment]
Highlight cannot work with HTML elements and components, it parses children string value and highlights given part, error that ts gives you is correct.

**Comment by kulame** [comment]
How do I deal with this scene by mantine?
i need to highlight text on react dangerouslySetInnerHTML.

**Comment by rtivital** [comment]
Highlight component does not support this feature, you should highlight your html before setting inner html.
