### ISSUE TITLE
Text inputs prevent Modal closeOnEsc from working.

### ISSUE THREAD

**Issue by OrangeRed** [mantinedev/mantine#1327]
### What package has an issue

@mantine/core

### Describe the bug

Text inputs inside of Modals trap focus and prevent `closeOnEscape` from working. 

Switching focus to something that isn't a Text input makes the flag work as expected again.

### In which browser did the problem occur

Firefox and Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/vigorous-flower-7yfn23?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Your sandbox works fine for me in all major browsers, escape closes the modal as expected.

**Comment by OrangeRed** [comment]
> Your sandbox works fine for me in all major browsers, escape closes the modal as expected.

When the text input is in focus pressing ESC doesn't close the modal.

**Comment by skelawsky** [comment]
In my opinion, this is the desired behavior

**Comment by rtivital** [comment]
I cannot reproduce the issue
