### ISSUE TITLE
Unable to set state in modal

### ISSUE THREAD

**Issue by alimehasin** [mantinedev/mantine#1337]
### What package has an issue

@mantine/modals

### Describe the bug

Can't perform setState in @mantine/modals 

## Code snippets

```tsx
import { useModals } from '@mantine/modals';

const [checked, setChecked] = useState(false);
const modals = useModals();

const foo = () => {
  modals.openModal({
    children: (
      <Checkbox
        checked={checked}
        onChange={(event) => setChecked(event.currentTarget.checked)}
      />
    ),
  });
};
```

### In which browser did the problem occur

Chrom/Firefox

**Comment by rtivital** [comment]
Setting state this way is not possible, once modal was opened it cannot receive updates from outside, you can encapsulate the state withing a child component, see example with form – https://codesandbox.io/s/hungry-feather-2185x
