### ISSUE TITLE
Select (new select) doesn't update the value if state modified externally [controlled]

### ISSUE THREAD

**Issue by cstrat** [mantinedev/mantine#134]
It appears that if you change the underlying value of the `Select` it works, but doesn't update the UI to show the user.
You need to click into the field and back out to see the update.
This results in the UI & value being out of sync:

<img width="233" alt="image" src="https://user-images.githubusercontent.com/4209076/124548933-c902b280-de71-11eb-86b4-34ced86e2ebe.png">

Open the sandbox, choose 'Hello' or 'World' - then click the button which updates the state to equal 'Testing'.
The `Select` will still show the previous value, although state has been updated.

See reproduction here:
https://codesandbox.io/s/mantine-select-not-updating-5uf0u?file=/src/App.js

**Comment by rtivital** [comment]
Thanks for reporting will fix in 2.0.2

**Comment by rtivital** [comment]
Resolved with #135

**Comment by SebasFavaronSirius** [comment]
Hi! It seems using a form value as a controlled causes this issue to reappear
https://codesandbox.io/p/sandbox/mantine-select-not-visually-updating-xr4z23

**Comment by SebasFavaronSirius** [comment]
If you have no other value that changes (maybe it's just a "clear select value" button), you can always have an ever increasing keyCounter state
