### ISSUE TITLE
compilation error in DatePicker Component

### ISSUE THREAD

**Issue by celeronCoder** [mantinedev/mantine#1346]
### What package has an issue

@mantine/dates

### Describe the bug

When Compiling my React Application (with Vite) the following error occurred:

```
Interface 'DatePickerProps' incorrectly extends interface 'Omit<CalendarSharedProps, "size" | "classNames" | "styles">'.
  Types of property 'onChange' are incompatible.
    Type '((value: Date | null) => void) | undefined' is not assignable to type '((value: Date | Date[]) => void) | undefined'.
      Type '(value: Date | null) => void' is not assignable to type '(value: Date | Date[]) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'Date | Date[]' is not assignable to type 'Date | null'.
            Type 'Date[]' is missing the following properties from type 'Date': toDateString, toTimeString, toLocaleDateString, toLocaleTimeString, and 37 more.ts(2430)
```

It's in `node_modules/@mantine/dates/lib/components/DatePicker/DatePicker.d.ts`.

It doesn't occur at runtime, no issues with the date-picker and no errors in the console also.

I'm using `@mantine/dates@4.2.1` with vite.

### In which browser did the problem occur

Brave

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I got a **workaround** for this issue by adding a ts-ignore comment above this line:
```
...
/* @ts-ignore 2430 */
export interface DatePickerProps extends Omit<DatePickerBaseSharedProps, 'onChange'>, Omit<CalendarSharedProps, 'size' | 'classNames' | 'styles'> {
...
```

**Comment by rtivital** [comment]
Make sure you are not typechecking node_modules folder, generally it is a bad practice, set `skipLibCheck` option in your tsconfig or find another solution if that does not help. There is no issue on Mantine side, since all of our code does not use strict mode.
