### ISSUE TITLE
Alert, CloseButton won't show if title is not provided

### ISSUE THREAD

**Issue by yudatadei** [mantinedev/mantine#1348]
https://github.com/mantinedev/mantine/blob/28dc8cdb997d503f43d8fa0a3c406e01aba9907d/src/mantine-core/src/components/Alert/Alert.tsx#L94-L111

**Comment by PrathameshAshra** [comment]
if we apply && with span instead of the whole wrapper, we can see the close button even if the title isn't provided. 
Can I take this ?

**Comment by rtivital** [comment]
Fixed in 5.1.4
