### ISSUE TITLE
export ProviderStyles type

### ISSUE THREAD

**Issue by maybesmurf** [mantinedev/mantine#1349]
### What package has an issue

@mantine/core

### Describe the bug

Title says it all

### In which browser did the problem occur

Any

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

export type ProviderStyles

**Comment by rtivital** [comment]
You can get provider styles type with 

```tsx
import { MantineProviderProps } from '@mantine/core';

type Styles = MantineProviderProps['styles'];
```
