### ISSUE TITLE
Tooltip in navbar cause scrollbar to appear and disapear

### ISSUE THREAD

**Issue by Burane** [mantinedev/mantine#1350]
### What package has an issue

@mantine/core

### Describe the bug

When i'm changing page by clicking in the navbar the scrollbar appear and disapear multiple times quickly, it happen too after hovering the element wich make appear the tooltip

### In which browser did the problem occur

All

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/heuristic-wozniak-3g3ny7?file=/src/components/Layout.tsx

### Do you know how to fix the issue

No

**Comment by 777Rob** [comment]
This issue can be fixed by setting withinPortal to false in a tooltip. After changes Tooltip should look like this:
`
 <Tooltip
      withinPortal={false}
      label={label}
      position="right"
      withArrow
      transitionDuration={0}
    >
`

**Comment by rtivital** [comment]
Fixed in 5.0
