### ISSUE TITLE
TextInput inside Popper cannot get focus

### ISSUE THREAD

**Issue by marktoman** [mantinedev/mantine#1353]
### What package has an issue

@mantine/core

#### Steps to reproduce:

1. Click Reference element
2. Click on the input element

#### Expected behavior:
TextInput gains focus

#### Actual behavior:
Nothing happens

#### Workaround:
Use Tab to navigate

### In which browser did the problem occur

Chrome 100.0.4896.127

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/serene-poincare-qbq9bq

### Do you know how to fix the issue

No

**Comment by probablycorey** [comment]
@rtivital's `pointer-events: all` trick works. But I was expecting this to be the default behavior (or at least documented in Popper api)
