### ISSUE TITLE
Title component should also accept Text component's props

### ISSUE THREAD

**Issue by maybesmurf** [mantinedev/mantine#1355]
### What package has an issue

@mantine/core

### Describe the bug

Title says it all

### In which browser did the problem occur

any

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

export interface TitleProps extends TextProps {}

**Comment by rtivital** [comment]
I cannot think of any Text prop that can be useful for title component.
