### ISSUE TITLE
Type `(status: DropzoneStatus) => ReactNode` is not assignable to type `ReactNode`

### ISSUE THREAD

**Issue by Manokii** [mantinedev/mantine#1356]
### What package has an issue

@mantine/dropzone

### Description
Typescript compiler somehow converts all the Dropzone Children into `ReactNode` where it expects `(status: DropzoneStatus) => ReactNode`

### Screenshot
![image](https://user-images.githubusercontent.com/49423729/166075949-e3bac5f0-f196-4161-87eb-96b4ee66a261.png)

### In which browser did the problem occur

on build time (npx tsc)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/broken-framework-xux0i2?file=%2Fsrc%2FApp.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Make sure you are not typechecking node_modules folder, generally it is a bad practice, set `skipLibCheck` option in your tsconfig or find another solution if that does not help. There is no issue on Mantine side, since all of our code does not use strict mode.
