### ISSUE TITLE
defaultRadius overrides local borderRadius styling

### ISSUE THREAD

**Issue by LeunensMichiel** [mantinedev/mantine#1367]
### What package has an issue

@mantine/core

### Describe the bug

Using Remix v1.4.3 and @mantine/core v4.2.2:

I applied local borderRadius styling on a button component. But the css always defaults to the `defaultRadius` prop defined in `MantineProvider`'s theme prop.

![image](https://user-images.githubusercontent.com/18447679/166215782-54d339ca-b4d4-43da-8e6e-5aa2f07743a9.png)

Fixed it by using `!important` in createStyles, but I don't think that should be the case.

Here's a snippet of my `createStyles` code

```
const useStyles = createStyles(
  (theme, { variant }: CustomSharedButtonProps) => ({
    root: {
      height: '3rem',
      padding: '.75rem 1.5rem',
    },
    filled: {
      ...(variant === 'primary' && {
        borderRadius: `${theme.radius.xl}px !important`,
      }),
    },
    outline: {
      ...(variant === 'secondary' && {
        borderColor: 'black',
        color: 'black',
        borderRadius: `${theme.radius.xl}px !important`,
      }),
      ...(variant === 'tertiary' && {
        borderColor: 'gray',
        color: 'gray',
        borderRadius: `${theme.radius.sm}px !important`,
      }),
    },
  }),
);
```
```
 <MantineButton
        classNames={{
          root: classes.root,
          filled: classes.filled,
          outline: classes.outline,
        }}
        ref={ref}
        variant={getMantineVariant(variant)}
        {...props}
      >
        {children}
      </MantineButton>
```

### In which browser did the problem occur

Chrome v100

**Comment by rtivital** [comment]
I cannot reproduce that on codesandbox – https://codesandbox.io/s/relaxed-engelbart-g08q9s?file=/src/App.tsx

**Comment by LeunensMichiel** [comment]
Reproduced it by adding a butting using the classNames prop (which I'm using)
```
     <Button classNames={{ filled: useStyles().classes.button }}>
          className radius
     </Button>
```

**Comment by rtivital** [comment]
These classes are meant for colors customizations only, you can add radius with `root` selector
