### ISSUE TITLE
Font pops in when loading main page

### ISSUE THREAD

**Issue by jrobichaud** [mantinedev/mantine#137]
Font pops in when loading main page.

Repro steps:
1. Go to https://mantine.dev/
2. refresh page

Result:
![font-pops](https://user-images.githubusercontent.com/12142702/124639415-23901480-de5a-11eb-845a-fb656c169e39.gif)
(the gif loops but the problem occurs only once in reality)

**Comment by rtivital** [comment]
Well, yep, I've made a mistake by relying on [web-font-loader](https://github.com/typekit/webfontloader) to load fonts on the page, will change it to regular link tag. Thanks for reporting!

**Comment by rtivital** [comment]
Fixed
