### ISSUE TITLE
fixOnBlur prop missing from DateRangePicker

### ISSUE THREAD

**Issue by DanielGibbsNZ** [mantinedev/mantine#1373]
### What package has an issue

@mantine/dates

### Describe the bug

The documentation defines a `fixOnBlur` prop for `DateRangePicker` that behaves the same as the `DatePicker` but no such prop seems to exist. When I try to use the prop I get the error:

```
Warning: React does not recognize the `fixOnBlur` prop on a DOM element
```

The code I used was:

```
<DateRangePicker value={dateRange} onChange={this.onDateRangeChange} fixOnBlur />
```

### In which browser did the problem occur

Brave 1.37.111 (Chromium 100.0.4896.79)

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Implement the `fixOnBlur` property as described or remove from the docs. From a quick glance it looks like it might be a bit more complicated than in `DatePicker`.

I can have a go implementing it if someone gives me some pointers on the best way to approach this.

**Comment by rtivital** [comment]
DateRangePicker does not support free input, and thus `fixOnBlur` prop does not make any sense.

**Comment by DanielGibbsNZ** [comment]
I think there is a use case for `fixOnBlur`: for example if the user clicks only one date and doesn't select the second and then blurs the component. It would be nice to have the component call `onChange` with the last known good date.

But at the very least the docs should probably be updated to not indicate that there is a `fixOnBlur` for the `DateRangePicker` component.

**Comment by rtivital** [comment]
It makes sense, but I do not think that it should be handled on library level. DateRangePicker is a controlled component – you can enhance value picking logic on your side.
