### ISSUE TITLE
[@mantine/core] Indicator is shown above the Modal component.

### ISSUE THREAD

**Issue by realpacific** [mantinedev/mantine#1377]
### What package has an issue

@mantine/core

### Describe the bug

Thanks for the amazing library.

In `@mantine/core:4.2.2`, the `Indicator`'s [zIndex](https://github.com/mantinedev/mantine/blob/a4edab9bdafbbd064516daa618c0aae0cd5a2e22/src/mantine-styles/src/theme/utils/get-default-z-index/get-default-z-index.ts#L6) is set to `getDefaultZIndex('overlay')`, which is higher than that of `elevations.modal` https://github.com/mantinedev/mantine/blob/a4edab9bdafbbd064516daa618c0aae0cd5a2e22/src/mantine-styles/src/theme/utils/get-default-z-index/get-default-z-index.ts#L3) 

This makes the `Indicator` display above `Modal`. 

### In which browser did the problem occur

Tested on Chrome

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Set the Indicator's zIndex to something more sensible OR increase the zIndex of the modal.

**Comment by rtivital** [comment]
Thanks for reporting, the issue will be fixed in next patch

**Comment by rtivital** [comment]
Fixed in 4.2.3
