### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by FizzBuzz791** [mantinedev/mantine#1381]
### What package has an issue

@mantine/core

### Describe the bug

It's actually @mantine/next but I can't choose that in the dropdown.

`pnpm add @mantine/next` gives the following error;
![image](https://user-images.githubusercontent.com/2747764/166611505-ce18e41e-976c-47a4-8be3-ddf4f635fa68.png)

This looks to be due to the fact that @mantine/ssr is locked to html-react-parser@1.3.0
https://github.com/mantinedev/mantine/blob/master/src/mantine-ssr/package.json#L41

The latest version of html-react-parser supports react 18
https://github.com/remarkablemark/html-react-parser/blob/master/package.json#L79

### In which browser did the problem occur

N/A

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I _think_ it's just a matter of upgrading the dependency in @mantine/ssr? It's only a patch release so there shouldn't be any breaking changes (checked the release notes, couldn't see any).

**Comment by rtivital** [comment]
use `npm install --legacy-peer-deps` or yarn

**Comment by FizzBuzz791** [comment]
Sure, but that's not really a fix, it's a workaround. Plus, the next time I try to `pnpm add` something, it'll complain again.

**Comment by FizzBuzz791** [comment]
> Yeah, annoying, but fixed with "pnpm install --strict-peer-dependencies false"

As you can see above, I've submitted and merged a PR that fixes it properly. Thanks for the redundant suggestion though.

**Comment by savager** [comment]
Wow, passive aggressive much. I did not see that or I wouldn’t have commented. Enjoy being rude.
