### ISSUE TITLE
@mantine dropzone React image upload issues while image upload on login form

### ISSUE THREAD

**Issue by Ferhad-Karimli** [mantinedev/mantine#1384]
### What package has an issue

@mantine/form

### Describe the bug

I tried for getting the image path with Dropzone in this way {...form.getInputProps("tourImages")} but it gives undefined . Also, I tried getting an image input with useState hooks, image path is displaying but, it is not displaying inside of form. Please, see the below :

    

### In which browser did the problem occur

google

### If possible, please include a link to a codesandbox with the reproduced problem

https://ecotourizm.com/en/addguide

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

      const getImage = (imageFile: any) => {
           setImageUpload(imageFile[0].path);
      };
      const [imageUpload, setImageUpload] = useState( );
    
      const form = useForm({
        schema: joiResolver(schema),
        initialValues: {
          name: "",
          sername: "",
          email: "",
          tourImages : "" ,
          imageUpload,
         
        },
      });

 <Dropzone
                    onDrop={(files) => {
                      getImage(files);
                    
                    }}
                    onReject={(files) => console.log("rejected files", files)}
                    maxSize={3 * 1024 ** 2}
                    accept={IMAGE_MIME_TYPE}
                    {...form.getInputProps("tourImages")}
                  >
                    {(status) => dropzoneChildren(status, theme)}
                  </Dropzone>

**Comment by rtivital** [comment]
`form.getInputProps` returns `value` and `onChange` handlers, while dropzone does not accept these props. You are trying to use Dropzone component as input while it is not an input – the single purpose of it – capture files from user: it does not store or display them anywhere. Try using other form handlers with dropzone, for example – https://mantine.dev/form/use-form/#setfieldvalue-handler
