### ISSUE TITLE
[bug] find two weird behavior of `@mantine/rte`

### ISSUE THREAD

**Issue by percy507** [mantinedev/mantine#1389]
### What package has an issue

@mantine/rte

### Describe the bug

- Paste something at the end of long document, the editor will auto scroll into the start position of the editor.

![2022-05-05 14 49 36 (1)](https://user-images.githubusercontent.com/18365078/166877942-eed82489-0f04-43c8-8c4d-2e4835f3c5a2.gif)

- Sometimes insert image will create a shadow image.

![2022-05-05 15 12 07](https://user-images.githubusercontent.com/18365078/166878061-c2012e1f-7e10-489e-8919-40f086877ae1.gif)

### In which browser did the problem occur

Chrome 101.0.4951.41

**Comment by wes337** [comment]
There is a lot of discussion about the scroll issue over on the react-quill Github issues: https://github.com/zenoamaro/react-quill/issues/394.

The solution seems pretty simple, to add `scrollingContainer="html"` to the Editor component.

Unsure about the shadow image bug though. Does it happen randomly, or with certain images? Is there a way to reliably reproduce the shadow image?

**Comment by rtivital** [comment]
Feel free to send a PR

**Comment by wes337** [comment]
Will do.

 Also, do you know why we have these styles on the `ql-clipbord` class? They cause a "flickering" when you paste anything:
![image](https://user-images.githubusercontent.com/9464690/167480686-88cee6be-cc1b-4161-85be-3ef0d27b3aa8.png)
Changing the position to `fixed` will fix this problem. But these styles look specific (and strange). Are they there for a good reason?

**Comment by rtivital** [comment]
It has to be hidden, basically it's a copy from quill theme, it does not work without it. Bu I guess we can change position to fixed as it should not matter.

**Comment by wes337** [comment]
Regarding the shadow image: it's created when uploading the image, by the `createImageBlot` function. It is supposed to be removed after the image uploads, in your case it is sometimes not. I can't reproduce this bug though. @percy507 If you could share your `onImageUpload` callback you pass to the Editor component, maybe this could help?

**Comment by percy507** [comment]
> If you could share your `onImageUpload` callback you pass to the Editor component, maybe this could help?

Hi @wes337,

I just use the [official example](https://mantine.dev/others/rte/#demo) for testing. And here is the image which I use(almost 1.1MB). https://anonfiles.com/B9y7l7fbya/1252748_png

Strange. I insert the image into the position which as marked in below image, it has greater chance to reproduce.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/18365078/167777323-69aca63f-7284-4c6a-9fcf-9126a4f1cd4c.png">
