### ISSUE TITLE
Select and NativeSelect breaks jest snapshot tests

### ISSUE THREAD

**Issue by schowdhuri** [mantinedev/mantine#1392]
### What package has an issue

@mantine/core

### Describe the bug

Each render of  `Select` or `NativeSelect` produces new class name hashes, causing snapshot tests to fail:

```diff
<div
  class="mantine-Select-root mantine-1m3pqry"
>
  <div
-       aria-controls="mantine-0ed4kpat5"
+       aria-controls="mantine-tem39dzzo"
    aria-expanded="false"
    aria-haspopup="listbox"
-       aria-owns="mantine-0ed4kpat5-items"
+       aria-owns="mantine-tem39dzzo-items"
    role="combobox"
    tabindex="-1"
  >
```

```diff
<select
  aria-invalid="false"
  class="mantine-NativeSelect-defaultVariant mantine-NativeSelect-input mantine-1nymnbu"
-         id="mantine-2726oaz9o"
+         id="mantine-ukkfdue77"
>
  <option
```

[@emotion/jest](https://emotion.sh/docs/@emotion/jest) isn't able to resolve it either.

## Repository to reproduce the issue

https://github.com/schowdhuri/mantine-select-bugs

### In which browser did the problem occur

NA

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Set `id` prop if you do not want random id to be generated for you.

`<Select id="test-id" />`

**Comment by schowdhuri** [comment]
Works! Should have noticed that it was the `id` and not the class name 🤦🏽‍♂️  Thanks, @rtivital!
