### ISSUE TITLE
DatePicker - TypeScript compiling error

### ISSUE THREAD

**Issue by szymonkwak** [mantinedev/mantine#1397]
### What package has an issue

@mantine/dates

### Describe the bug

![2022-05-06_00h06_42](https://user-images.githubusercontent.com/40847193/167033279-d1ee43bf-3300-4607-b50c-5fc24557457e.jpg)

### In which browser did the problem occur

-

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Changing onChange value types in interface DatePickerProps from `(value: Date | null)` to **`(value: Date | Date[])`**

**Comment by rtivital** [comment]
See #1346
