### ISSUE TITLE
Divider can't set color

### ISSUE THREAD

**Issue by thuonghdbhsoft** [mantinedev/mantine#1410]
### What package has an issue

@mantine/core

### Describe the bug

When I set the color for the divider component, it disappears that color

### In which browser did the problem occur

Chrome, Nextjs 12.5

**Comment by rtivital** [comment]
I cannot replicate that – https://codesandbox.io/s/intelligent-hill-ldg8vj?file=/src/App.tsx

**Comment by thuonghdbhsoft** [comment]
I add the Hexa color. 

https://codesandbox.io/s/pensive-herschel-b9wtgt?file=/src/App.tsx
