### ISSUE TITLE
Issues with Preact

### ISSUE THREAD

**Issue by bjarneo** [mantinedev/mantine#142]
I figured out the issue is that `preact-compat` is not supported for newer versions of preact, as it is built-in. The `preact.config.js` is also using the built-in `preact/compat`. However, your demo repository still has `preact-compat` installed, even though `preact` should complain if you try to install it. Nevertheless, if you try to remove `preact-compat` dependency, reinstall the packages, and run the application, it will throw the same errors as from this Reddit thread. 

I am not sure how to solve this yet. If you try to add `preact-compat` by force, it will still throw the error.

Reddit thread: https://www.reddit.com/r/reactjs/comments/oeuspg/mantine_20_is_out_100_hooks_and_components_with/h4diaku/?context=3

**Comment by rtivital** [comment]
Thanks for reporting, I'll try out new version of preact-cli and update the docs

**Comment by rtivital** [comment]
The guide was updated, everything now works with newer versions of preact cli
