### ISSUE TITLE
Feature Request, highlighting : Ability to highlight multiple terms

### ISSUE THREAD

**Issue by ingloriousp** [mantinedev/mantine#143]
package: @mantine/core
version:2.0.2
browser/OS: chrome 91, mac OS Big sur

In Highlighting feature:
<img width="844" alt="duplicate value" src="https://user-images.githubusercontent.com/79135076/125192545-16ae5f00-e266-11eb-9c2c-b3c936f15f3e.png">
"this" may be highlighted twice in the image above.

<img width="852" alt="two terms" src="https://user-images.githubusercontent.com/79135076/125192550-1910b900-e266-11eb-8828-74013d18f281.png">
Ability to highlight multiple terms in a single term may be done. i.e. "this" and "one" may be highlighted using above syntax

FYI: huge fan of mantine :)

**Comment by rtivital** [comment]
Hi, thanks for feedback and feature proposition, I do not have capacity to work on this right now, so I'm leaving this to community, fell free to implement this and send a pull request

**Comment by yoroshikun** [comment]
Hi, I'll take a crack at working on this, I'm not certain about the syntax, would you rather have the ability to pass an array to the component or split the string based on certain symbol.

**Comment by yoroshikun** [comment]
Functionality for this has been merged into version 2.1.0~
I will close this

**Comment by ingloriousp** [comment]
Thank you :)


Kind Regards,
Gaurav Bhati
