### ISSUE TITLE
Select creatable with object data is lost value when blur

### ISSUE THREAD

**Issue by viiiprock** [mantinedev/mantine#1434]
### What package has an issue

@mantine/core

### Describe the bug

Basically it's the "different" version of https://mantine.dev/core/select/#creatable
but with `SelectItem[]` instead of `string[]` (see codesandbox example below)

Reproduce steps:
* Add Select 
* Add state with some initial data
* Add a value not existed in menu list
* Click create new data
* New data is created with a new value in the select input
* Click outside in the same screen (on blur)
* Input value disappear

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-select-error-meufu8?file=/src/App.js

**Comment by rtivital** [comment]
When you create a new item with a random string as value, Select has no way of knowing which value should be selected, in this case you need to manage value state on your side – https://codesandbox.io/s/mantine-select-error-forked-vmo8zm?file=/src/App.js

**Comment by viiiprock** [comment]
Alright, basically the experience between `string[]` and `SelectItem[]` are different. 
Thanks for the answer @rtivital
