### ISSUE TITLE
Slider component can have high CPU usage

### ISSUE THREAD

**Issue by ramiel** [mantinedev/mantine#1436]
### What package has an issue

@mantine/core

### Describe the bug

If the value of the slider changes often, the CPU is intensively used. This is because emotion needs to put new styles on the DOM because of the changing position. Probably, a fairly simple solution would be to use `style` instead of `sx` in the Thumb component to set the new position.

### In which browser did the problem occur

Any

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/friendly-hooks-vg11ph?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Use `style` instead of `sx` in the `Thumb` component

**Comment by rtivital** [comment]
Feel free to create a PR for this, but make sure that RTL direction works as expected
