### ISSUE TITLE
Property 'openRef' does not exist on type 'FullScreenDropzoneProps'

### ISSUE THREAD

**Issue by ThielNS** [mantinedev/mantine#1439]
### What package has an issue

@mantine/dropzone

### Describe the bug

First, thank you very much for lib ❤️.

I'm trying to create a button to make a call that opens the file window as shown in the dropzone documentation, ["Open file browser manually"](https://mantine.dev/others/dropzone/#open-file-browser-manually), but for the `FullScreenDropzone` component, but the openRef property is not a valid prop.

according to the [documentation](https://mantine.dev/others/dropzone/#fullscreendropzone-component) the FullScreenDropzone component "supports the same props and features as Dropzone component shown above (except maxSize, onReject, and loading props)." so, I imagine that employee in the same way passing the openRef, but no.

is there any way to be able to open the file window manually, without having to just drag?

I thank you for your attention.

### In which browser did the problem occur

none

### Possible fix

Implement the same openRef functionality from the `Dropzone` component to the `FullScreenDropzone` component

**Comment by rtivital** [comment]
I'll add the mention to the docs that FullScreenDropzone does not support openRef, we cannot provide that feature since it does not use react-dropzone.

**Comment by ThielNS** [comment]
> Vou adicionar a menção aos documentos que FullScreenDropzone não suporta openRef, não podemos fornecer esse recurso, pois ele não usa react-dropzone.

D'oh!... but that's ok, it's like an idea for a future version.
Thank you for your attention!

**Comment by ThielNS** [comment]
> I'll add the mention to the docs that FullScreenDropzone does not support openRef, we cannot provide that feature since it does not use react-dropzone.

D'oh!... but that's ok, it's like an idea for a future version.
Thank you for your attention!

**Comment by rtivital** [comment]
Documentation was updated
