### ISSUE TITLE
Both yarn and npm used in package.json

### ISSUE THREAD

**Issue by nrayburn-tech** [mantinedev/mantine#1440]
### What package has an issue

@mantine/core

### Describe the bug

In `mantine/package.json`, yarn is used for installing dependencies.  However, inside of the various scripts npm is used for running other scripts.

`postinstall` uses `npm run docs:docgen`, I would expect `yarn run docs:docgen`.
`release:prepare` uses `npm test`, I would expect `yarn test`.

Not a big issue, just requires both npm and yarn to be used for contributing.

### In which browser did the problem occur

N/A

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Replace `npm run` and `npm *` commands with `yarn run` and `yarn *` commands in the package.json and GitHub workflows.

**Comment by rtivital** [comment]
If you have Node.js installed on your computer – you have npm, I do not see why this is an issue

**Comment by nrayburn-tech** [comment]
It's mostly just an inconsistency, (bug probably isn't the right label).  I don't think it causes any real issue.

I can submit a PR if you would like, if not then you can go ahead and close the issue.
