### ISSUE TITLE
Can't style Timeline.Item with classNames prop

### ISSUE THREAD

**Issue by MFrizzy** [mantinedev/mantine#1441]
### What package has an issue

@mantine/core

### Describe the bug

I'd like to override Timeline styling to my Timeline.Item like this :

```tsx
<Timeline>
  <Timeline.Item 
    title="title" 
    classNames={{
      itemBullet: "hidden",
    }}
  >
    description
  </Timeline.Item>
  <Timeline.Item title="title">description</Timeline.Item>
</Timeline>
```

But none of the classes given through classNames are actually given in the Timeline.Item props. I noticed that the items props are override by the Timeline component props [here](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/Timeline/Timeline.tsx#L76)

### In which browser did the problem occur

all

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Timeline.Item does not support Styles API, it is the expected behavior. You need to set classNames on Timeline component.
