### ISSUE TITLE
-1 become 1

### ISSUE THREAD

**Issue by amzeshan** [mantinedev/mantine#1458]
### What package has an issue

@mantine/core

### Describe the bug

I write a negative number into an integer，e.g. -2 become 2，If I enter a value of -2, I get -2. How should I set it

![1652509886(1)](https://user-images.githubusercontent.com/67269639/168413906-86c81050-bfb2-4a78-97b5-eb376a166a77.png)

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

No

**Comment by mattrunyon** [comment]
Should be fixed in #1445 (should be in next patch release)

Also, your code example has a minimum value of 0, so you can't go below 0 in your example

**Comment by rtivital** [comment]
Fixed in 4.2.5
