### ISSUE TITLE
Autocomplete createStyles getRef for 'icon' not working

### ISSUE THREAD

**Issue by official-carledwardfp** [mantinedev/mantine#1471]
### What package has an issue

@mantine/core

### Describe the bug

- `AutoComplete` component
- _See attached photo:_ The icon **does not change its color** when the input is hovered
- In codesandbox, I added a style to the placeholder to show that the icon does not change its color on input hover

#### Steps to Replicate
1. Go to [this codesandbox](https://codesandbox.io/s/lucid-grass-8ht133?file=/src/App.tsx)
2. Hover mouse on to the AutoComplete component
3. The placeholder color changes but the icon color does not change

![AutoComplete icon getRef bug](https://user-images.githubusercontent.com/72434354/168643901-32936fe7-f3e7-491e-9f1e-e4eae0c99383.png)

### In which browser did the problem occur

Chrome, Safari

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/lucid-grass-8ht133?file=/src/App.tsx

### Do you know how to fix the issue

No

### Possible fix

N/A

**Comment by rtivital** [comment]
You are trying to target the icon assuming that it is inside input. Input cannot have children – icon in rendered with absolute position above it. Icon is an adjacent node to input. You can use use-hover hook or other CSS selector to target it while input is hovered.
