### ISSUE TITLE
useId does not persist with NextJS SSR and produces console error

### ISSUE THREAD

**Issue by longprao** [mantinedev/mantine#1477]
### What package has an issue

@mantine/hooks

### Describe the bug

Using `useId()` with next js ssr produces this error on console:

> Warning: Prop `htmlFor` did not match. Server: "mantine-hkk5ezeb6" Client: "mantine-pr96zih46"

I have applied SSR setup in `_app` and `_document` but not worked.

### In which browser did the problem occur

Chrome v101

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
It will be fixed in 5.0, we will introduce react useId hook integration to make it works on server

**Comment by rtivital** [comment]
Fixed in 5.0
