### ISSUE TITLE
MantineProvider theme font-family not loading in Nextjs bundle

### ISSUE THREAD

**Issue by krush11** [mantinedev/mantine#1492]
### What package has an issue

@mantine/core

### Describe the bug

I have been trying to load font globally using Nextjs and Mantine. I am using MantineProvider theme to do this and when I build the code and run the nextjs bundle, I am unable to see the fonts-family loaded in HTML. How do I load the theme's fontFamily globally? 

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/sleepy-feynman-twg59n

**Comment by rtivital** [comment]
https://codesandbox.io/s/objective-lewin-15v8z9?file=/pages/_app.js
