### ISSUE TITLE
NumberInput doesn't change when form is reset

### ISSUE THREAD

**Issue by canac** [mantinedev/mantine#1495]
### What package has an issue

@mantine/core

### Describe the bug

Resetting a form doesn't reset the value of a `NumberInput` to its default value. `TextInput` resets correctly.

In the Codesandbox, change the value of the number and the text input. Then click the reset button. Only the text input reverts back to the default value.

### In which browser did the problem occur

Brave v1.38.119

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/number-input-5j0f93

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
I do not think that it is possible to reset NumberInput, it uses internal state to manage value
