### ISSUE TITLE
am/pm cannot be localized for TimeInput

### ISSUE THREAD

**Issue by DJDavid98** [mantinedev/mantine#1496]
### What package has an issue

@mantine/dates

### Describe the bug

The `TimeInput` component is hard/coded to use am/pm for 12-hour clocks, and these values are not configurable for different locales.

### In which browser did the problem occur

all

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

At the very least it would be necessary to allow providing these values as props to the input so the localization can be provided from any external source. The more ideal solution would likely be a `TimePicker` component (similar to `DatePicker`) that uses dayjs locales to specify the clock type and the correct am/pm suffix.

**Comment by OlegGulevskyy** [comment]
Hey @DJDavid98 , you marked in your message that you are willing to participate in fixing this. Have you done any progress on that or I can cook something up and submit a PR?

**Comment by rtivital** [comment]
Check if dayjs provides translations for those labels, if so then use them, it not then add option for user to provide them via prop. Do not forget that keyboard controls should work for all locales.
