### ISSUE TITLE
Rich text editor not working properly

### ISSUE THREAD

**Issue by lingayya0124** [mantinedev/mantine#1504]
### What package has an issue

@mantine/rte

### Describe the bug

When using RTE if you select bold or italic controls the first letter appears at last 
"Hello" become "elloH"

https://user-images.githubusercontent.com/69788802/169981843-aff24851-cacf-4ea8-8d88-4fa82636fe02.mp4

here is a screen recording.

### In which browser did the problem occur

Chrome and Firefox

**Comment by jimmyruann** [comment]
Can't seem to reproduce the issue. https://codesandbox.io/s/frosty-snyder-k0wewf?file=/src/App.tsx

**Comment by lingayya0124** [comment]
The above issue is getting resolved if we don't add a placeholder.

**Comment by rtivital** [comment]
It works fine for me with and without placeholder (Chrome) – https://codesandbox.io/s/suspicious-rgb-hq8mf1?file=/src/App.tsx

**Comment by dohomi** [comment]
I think the best would be replacing `react-quill` with `react-quilljs` hook approach. This reduces problems with SSR rendering and is closer to the Quill editor itself.

**Comment by wes337** [comment]
> I think the best would be replacing `react-quill` with `react-quilljs` hook approach. This reduces problems with SSR rendering and is closer to the Quill editor itself.

There does seem to be a lot of weird issues with `react-quill`... But how to know if `react-quilljs` will be any better?

**Comment by lingayya0124** [comment]
> It works fine for me with and without placeholder (Chrome) – https://codesandbox.io/s/suspicious-rgb-hq8mf1?file=/src/App.tsx
@rtivital still giving the problem 
![Screenshot from 2022-06-07 12-57-39](https://user-images.githubusercontent.com/69788802/172321048-37bb2d50-3ac0-4626-93af-b88222f798c3.png)

**Comment by rtivital** [comment]
Maybe it is specific to your system, I cannot reproduce that

**Comment by rtivital** [comment]
The issue is not reproducible

**Comment by adrianflda** [comment]
Hey guys I am having the same issue, using ReachText on Nextjs

**Comment by keaysma** [comment]
I'm seeing this as well - Using RTE on top of NextJS as well, here's a video of the issue in action

https://user-images.githubusercontent.com/25709557/208348682-fa6bcafd-57bf-4fe8-949e-6dbf5a7410f6.mov

**Comment by rtivital** [comment]
`@mantine/rte` package is deprecated, use `@mantine/tiptap` instead and see if it solves the issue
