### ISSUE TITLE
ScrollArea of type auto leaves space in the scrollbar at the bottom when it shouldn't

### ISSUE THREAD

**Issue by gl3nn** [mantinedev/mantine#1509]
### What package has an issue

@mantine/core

### Describe the bug

![Screenshot 2022-05-24 at 17 23 31](https://user-images.githubusercontent.com/1133073/170072949-7b237926-fb48-403f-b7de-bcb4b466bf50.png)

The scrollbar is not able to go all the way down when the type is set to auto or always. It seems to keep some space at the bottom (equal to the amount set in ScrollbarSize). This is probably compensating for when there is a horizontal scrollbar as well but ideally it shouldn't do this compensation when the horizontal scrollbar isn't present.

### In which browser did the problem occur

Latest Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/scroll-area/

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
This is how Radix scroll area works, you can try hiding corner with Styles API

**Comment by gl3nn** [comment]
If I add `type="auto"` to `<ScrollArea/>` in the demo ( https://codesandbox.io/s/angry-bose-mqqrbx?file=/App.js ) of https://www.radix-ui.com/docs/primitives/components/scroll-area , it doesn't have this problem however. Or is this not how Mantine uses it?

With the Mantine scrollarea the horizontal scrollbar as well as the corner are still there, just with opacity 0. The Radix scroll area just doesn't render the horizontal and corner at all (as is preferred).

I tried fiddling a bit with the Styles API but it's not ideal.

**Comment by gl3nn** [comment]
I gave it a quick look but couldn't immediately figure out what it was, might give it a proper try in the future. Is there some sort of label we can add that indicates that this is an issue people could contribute to?

**Comment by wes337** [comment]
There is some some at the bottom which prevents the scrollbar from reaching the bottom of the content:
![image](https://user-images.githubusercontent.com/9464690/174536118-c2e9462b-f060-4716-8924-12cfcd45cfae.png)

**Comment by wes337** [comment]
Fix seems pretty straightforward. Use the CSS selector for `data-state` and display none if it is hidden:
![image](https://user-images.githubusercontent.com/9464690/174537518-8500d99f-273b-442f-aa31-8f1f2ce73d82.png)
