### ISSUE TITLE
JSS Error for Inputs - :disabled:placeholder

### ISSUE THREAD

**Issue by cstrat** [mantinedev/mantine#151]
With any forms I am now seeing my console littered with:

![image](https://user-images.githubusercontent.com/4209076/125601295-104d22c1-5754-42c5-ba55-b8c923cf0744.png)

The form itself renders fine - haven't noticed an issue with the color like it implies.

I don't know enough about JSS to understand the error, maybe a simple problem?

**Comment by rtivital** [comment]
Thanks for reporting, I forgot an extra colon before placeholder, the selector should be `input:disabled::placeholder`

**Comment by rtivital** [comment]
Fixed in [2.0.5](https://github.com/mantinedev/mantine/releases/tag/2.0.5)
