### ISSUE TITLE
Controlled inputs shouldn't set their value

### ISSUE THREAD

**Issue by Kukkimonsuta** [mantinedev/mantine#154]
_Packages:_ @mantine/hooks @mantine/core
_Version:_ 2.0.5
_Browsers:_ Edge 91 (not relevant)
_Codesandbox:_ https://codesandbox.io/s/clever-gagarin-qik7m?file=/src/App.tsx
_Contribution:_ I haven't looked into the hook in detail to consider how the issue should be fixed, however I'm willing to contribute it if instructed to do.

_Description:_
Input components in controlled mode should never set their own value - it needs to always come from outside as the requested change may be blocked and parent component might not render again. As you can see in codesandbox the native selects value correctly never changes (because the handler is omiting the setValue call), but `Select` component does. This applies to all components using `useUncontrolled` as far as I can tell.

**Comment by rtivital** [comment]
Hi, thanks for reporting, this is a bug in uncontrolled hook, it can easily be fixed by adding extra checks, feel free to contribute
