### ISSUE TITLE
sizes is ignored in Container

### ISSUE THREAD

**Issue by michaelhuber1937** [mantinedev/mantine#1554]
### What package has an issue

@mantine/core

### Describe the bug

As I understand the documentation correctly, the sizes-attribute can be used to specify how large the container is with specific viewport-sizes. But the sizes are ignored, only the size of md is used for the container, the rest is ignored.

`<Container sizes={{ xs: 400, sm: 600, md: 700, lg: 900, xl: 1200 }}>Content</Container>`

### In which browser did the problem occur

Chrome, Firefox etc.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Container does not support responsive styles from props, `sizes` prop defines container max-width at given `size` prop, see documentation – https://mantine.dev/core/container/#configure-sizes
