### ISSUE TITLE
MultiSelect IME bug.

### ISSUE THREAD

**Issue by lightsound** [mantinedev/mantine#1565]
### What package has an issue

@mantine/core

### Describe the bug

When I select a choice from the IME, the input is confirmed. The following video is easy to understand.
https://user-images.githubusercontent.com/8220973/171986763-e6bfb05d-7e50-4349-a1ca-c57032a8effa.mp4

With this bug, Japanese, Chinese and Korean users would not be able to use multi-select.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

It can be reproduced in the Mantine docs example.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

I don't know the exact cause, but it seems to be due to the fact that the focus is already enabled when selecting from the IME. I think the [compositionend event](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionend_event) is related.

![2022年06月04日 15時06分@2x](https://user-images.githubusercontent.com/8220973/171987094-c6743a5d-90bb-4673-b794-81fbd3a5cad7.png)

**Comment by wes337** [comment]
This seems to be working fine for me:
![2sxWWGQXMV](https://user-images.githubusercontent.com/9464690/172023910-c023f22c-04cf-4f8c-ab84-7120aab7b983.gif)

And for creatable as well:
![creatable](https://user-images.githubusercontent.com/9464690/172023921-208748c4-26bb-4046-aa70-77a179dd5bb5.gif)

Am I missing something? I couldn't watch the video you included. The link does not work.

**Comment by lightsound** [comment]
@wes337 
The IME you are using does not seem to be used much in Japan. In Japan, macOS default or [Google IME](https://www.google.co.jp/ime/) is often used. I have tried both IMEs in Chrome/Safari and both did not work well.
　
Could you see any of the following videos?
- https://share.cleanshot.com/M3rfPa
- https://user-images.githubusercontent.com/8220973/172030022-bc7d4b43-85d1-41b9-b464-439096a31dbe.mp4

**Comment by wes337** [comment]
Yeah that video works. I can reproduce this now. 

It started happening after installing Google IME, and it's also happening on the other previously working IME now too.

**Comment by wes337** [comment]
I was able to fix this using the composition events like you mentioned. It feels a bit weird, but then again I'm not used to working with IMEs.

I wonder if this is happening in other inputs/components where we have a custom `handleInputKeydown` method?

**Comment by lightsound** [comment]
Thank you very much!

I looked at the component where `handleInputKeydown` is used, but I didn't have any problems in my application.
