### ISSUE TITLE
MultiSelect and form.getListInputProps Typescript problem

### ISSUE THREAD

**Issue by oferitz** [mantinedev/mantine#1566]
### What package has an issue

@mantine/form

### Describe the bug

Actually there are two problems in the following example:

1. creatable `MultiSelect` doesn't seem to work at all in form list. new tags are not created.
2. `form.getListInputProps` unable to infer `listItem` correctly.

**EDIT**: Seems like adding `getCreateLabel` solves the first issue. This is weird if it only works with `getCreateLabel` it should be mandatory prop.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/busy-snyder-npmku7

### Do you know how to fix the issue

No

**Comment by wes337** [comment]
1. In your Code sandbox, you are passing an empty array to `data` prop of the `Multiselect` component. This is probably why it doesn't work like you expect.
2. In your Code sandbox change the `EmployeesFormValues` interface to:  
```
interface EmployeesFormValues {
   employees: FormList<EmployeeGroup>;
}
```
And it will work as expected.

**Comment by oferitz** [comment]
@wes337 Thanks!
1. I Actually do want to start with empty array because all values are defined by the user, this is why its a creatable MultiSelect. Adding  `getCreateLabel` solve it.

2. Yeah that did the trick.
