### ISSUE TITLE
Type error for maintine ssr style extraction on nextjs _document.tsx 

### ISSUE THREAD

**Issue by dellysoul** [mantinedev/mantine#1569]
### What package has an issue

@mantine/core

### Describe the bug

^ could not find the @maintine/next package in that dropdown, so adding core for now. 

Following the docs for setup Mantine ssr styles extraction via https://mantine.dev/theming/next/  results in the following

``` Class static side 'typeof _Document' incorrectly extends base class static side 'typeof Document' 

  The types returned by 'getInitialProps(...)' are incompatible between these types.
    Type 'Promise<{ styles: Element; html: string; head?: (Element | null)[] | undefined; }>' is not assignable to type 'Promise<DocumentInitialProps>'.
      Type '{ styles: JSX.Element; html: string; head?: (JSX.Element | null)[] | undefined; }' is not assignable to type 'DocumentInitialProps'.

```

### In which browser did the problem occur

n/a - this is a typescript type issue

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Not sure what the fix could be, but the error is a type error where the suggested fragment is read as type Element, which is not accepted for styles, which accepts JSX.element type.

Tried explicitly typing the style to a JSX.Element , but something seems to be getting lost in translation 
<img width="533" alt="Screen Shot 2022-06-04 at 11 06 38 PM" src="https://user-images.githubusercontent.com/14019580/172037710-3090e477-da19-4868-b872-914229ce3962.png">

**Comment by rtivital** [comment]
Ts strict mode issue, you can use `as any` for now

**Comment by rtivital** [comment]
I've added `any` type to `ServerStyles` in `4.2.8` you can update to this version and the issue should be resolved, if you experience this issue after the update, please reopen this issue.
