### ISSUE TITLE
The dropdown style is not applied when withinPortal is true

### ISSUE THREAD

**Issue by MR-Mostafa** [mantinedev/mantine#1571]
### What package has an issue

@mantine/core

### Describe the bug

Hi,
When we use `Select` Component and the `withinPortal` props is `true`,
the `.mantine-Select-dropdown` and `.mantine-Select-item` is not applied .

### In which browser did the problem occur

Google Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/dropdown-style-f19d37?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Styles are not applied in your case because when `withinPortal` is true, dropdown is not rendered within the same node. If you want to style elements this way, you should use `styles` prop instead, `sx` will never work. 

https://codesandbox.io/s/dropdown-style-forked-kssiw6?file=/src/App.tsx
