### ISSUE TITLE
Slider onChange unexpected behavior

### ISSUE THREAD

**Issue by mthongkerd** [mantinedev/mantine#1574]
### What package has an issue

@mantine/core

### Describe the bug

Slider component seems to store outdated outside values after setting a new value.

In this [codesandbox example](https://codesandbox.io/s/7pyqtt?file=), clicking `sliderA` to some number then click `sliderB` to some number. By doing so the value for `sliderA` (and numInpC) resets to the original values, this does not occur if you set `numInpC` to a number.

### In which browser did the problem occur

Electron, Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/7pyqtt?file=

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
onChange function is internally memoized, you need to use useState callback function if you need this kind of logic, see example – https://codesandbox.io/s/mantine-slider-bug-example-forked-8tpbdw?file=/src/App.js

**Comment by mthongkerd** [comment]
@rtivital Thanks for the answer and your rapid response, much appreciated. 😃
