### ISSUE TITLE
Dropzone onDrop does not call to update children on "click to select file"

### ISSUE THREAD

**Issue by SuperCoolAlan** [mantinedev/mantine#1576]
### What package has an issue

@mantine/dropzone

### Describe the bug

Mantine Dropzone only calls to update children with onDrop and onReject. To provide an improved UI, I'd like to update children after a user clicks to select a file.

After a file is selected in a user's file explorer, call to update Children. Here, I'd like to also display the file name of what was selected before submitting the form.

### In which browser did the problem occur

Ubuntu 20.04 Brave 1.39.111

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/affectionate-thunder-y865u0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Append a new option to the Dropzone function with a label similar to 'onSelect' which provides instructions on what to do when the Dropzone is clicked to select.

**Comment by rtivital** [comment]
It updates fine for me on sandbox – https://codesandbox.io/s/delicate-water-wpup8z?file=/src/App.tsx

**Comment by thevahidal** [comment]
@SuperCoolAlan Can you explain your problem a little bit more?
Did you try to define a function for onDrop callback? 

Something like this:
```
  const [files, setFiles] = useState([])
  
  // setting the accepted files in an state
  const handleDrop = (files) => {
    setFiles(files)
  }
  
  // and then in your render...
  <Dropzone
      onDrop={handleDrop}
      // ...
  >
    // ...
  </Dropzone>
```

**Comment by SuperCoolAlan** [comment]
I finally had time to look back at this function. I was not passing `files` through to DropzoneChildren. Thanks for the examples here.
