### ISSUE TITLE
Autocomplete & Select warning when using group values with custom data

### ISSUE THREAD

**Issue by MR-Mostafa** [mantinedev/mantine#1590]
### What package has an issue

@mantine/core

### Describe the bug

Hi,
The following error is displayed when we group the available data and pass it to the component.
This error occurs when we click on the component to display the dropdown.
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `@mantine/core/SelectItems`. See https://reactjs.org/link/warning-keys for more information.
```

### In which browser did the problem occur

google chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/error-unique-key-oo2d1n

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
each value in data array should be unique, it is used for keys

**Comment by MR-Mostafa** [comment]
Even though all my values are unique, this error still appears.

My Sample Data:
```js
const data = [
  { name: "United States", id: 1, isPriority: true },
  { name: "United Kingdom", id: 2, isPriority: true },
  { name: "China", id: 3, isPriority: true },
  { name: "Russia", id: 4, isPriority: true },
  { name: "Japan", id: 5, isPriority: false },
  { name: "Italy", id: 6, isPriority: false },
  { name: "United Arab Emirates", id: 7, isPriority: false },
  { name: "Canada", id: 8, isPriority: false },
  { name: "India", id: 9, isPriority: false },
  { name: "Spain", id: 10, isPriority: false },
  { name: "IRAN", id: 11, isPriority: false },
  { name: "Germany", id: 12, isPriority: true },
  { name: "Australia", id: 13, isPriority: false },
  { name: "Turkey", id: 14, isPriority: false },
  { name: "France", id: 15, isPriority: true },
  { name: "Netherlands", id: 16, isPriority: false }
];

/**
 * Add value & group property to data's
*/
const countryList = data.map((item) => ({
  ...item,
  value: item.name,
  group: item.isPriority ? "Priority" : ""
}));
```

Then this error is appear:
```
Warning: Each child in a list should have a unique "key" prop.
```

I tested the code several times and found that the error occurs when I add a `group` property to the data. (No error occurs when I comment on this property)

Please see the test project on codesandbox:
**[codesandbox](https://codesandbox.io/s/error-unique-key-2-e9jiwk)**

**Comment by MR-Mostafa** [comment]
I found the problem
This error occurs when the `group ` property is `group: ''`.
