### ISSUE TITLE
Hydration failed in nextjs when using useLocalStorage hook

### ISSUE THREAD

**Issue by georgegrigorita** [mantinedev/mantine#1595]
### What package has an issue

@mantine/hooks

### Describe the bug

I'm using the localStorage hook in a nextJS project: 

`const [active, setActive] = useLocalStorage({ key: 'active', defaultValue: 0 });` 

It's all working fine until I refresh the page, that's when I get the hydration error: `Error: Hydration failed because the initial UI does not match what was rendered on the server.`

### In which browser did the problem occur

N/A

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Hi George! You need to set `getInitialValueInEffect: true` to prevent hydration mismatches. By setting this value, you will tell the hook to use the default value during server-side rendering and update it with the actual value only after component mounts. You can learn more about other hook settings in hook definition – https://mantine.dev/hooks/use-local-storage/#definition

**Comment by georgegrigorita** [comment]
Hi Vitaly! Wow, how did I missed that in the docs?! Thank you!
