### ISSUE TITLE
emotionOptions.prepend is deprecated

### ISSUE THREAD

**Issue by lightsound** [mantinedev/mantine#1606]
### What package has an issue

@mantine/core

### Describe the bug

It appears that [emotionOptions.prepend](https://mantine.dev/theming/mantine-provider/#change-styles-insertion-point) in MantineProvider props is [deprecated](https://github.com/emotion-js/emotion/blob/main/packages/sheet/README.md#prepend). We need to use `insertionPoint` instead of `prepend`.  I tried to use `insertionPoint` but it did not work. Do you have any examples of `insertionPoint` working?

Looking at past issues, there have been several reports of prepend not working. Prepend did not work in my environment too, so I looked into it and found that it was deprecated.  I think that replacing `insertionPoint` would be useful to reduce the number of similar issues.

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
`emotionOptions.prepend` works as expected, although it is deprecated, it is still working fine. MantineProvider passes `emotionOptions` to emotion cache directly without modifications so you can use `insertionPoint` as well.
