### ISSUE TITLE
Menu items have no focus styles when using keyboard to navigate

### ISSUE THREAD

**Issue by wes337** [mantinedev/mantine#1614]
### What package has an issue

@mantine/core

### Describe the bug

When using the arrow keys to navigate through the `Menu` component's items, there are no focus styles in Chrome, Edge, and Safari. So you do not know which menu item is currently the active element.

In Firefox it seems to work as expected:
![image](https://user-images.githubusercontent.com/9464690/173221300-d03b795a-9d15-4e8c-995a-f8a9993778c8.png)

In Chrome, Edge, and Safari, nothing:
![image](https://user-images.githubusercontent.com/9464690/173221310-1b7ba86b-9902-42fb-857d-667a6b7b091d.png)

### In which browser did the problem occur

Chrome, Edge, Safari

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Starting point is somewhere in the styles file, or possibly the `handleKeyDown` function in the `components/Menu/Menu.tsx` file.

**Comment by rtivital** [comment]
Fixed in 4.2.9
