### ISSUE TITLE
Dropzone MimeType Error

### ISSUE THREAD

**Issue by fatih-dogmus** [mantinedev/mantine#1619]
### What package has an issue

@mantine/dropzone

### Describe the bug

When I make the example on the site myself, the decline symbol appears.

@mantine/dropzone@4.2.9

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by fatih-dogmus** [comment]
On hover

**Comment by rtivital** [comment]
Please send a sandbox that reproduces the issue

**Comment by fatih-dogmus** [comment]
`import { Upload, Photo, X } from 'tabler-icons-react';
import { Dropzone } from "@mantine/dropzone";
import { useMantineTheme, Group, Text, Card, Title } from "@mantine/core";

function getIconColor(status, theme) {
    return status.accepted
        ? theme.colors.red[theme.colorScheme === 'dark' ? 4 : 6]
        : status.rejected
            ? theme.colors.red[theme.colorScheme === 'dark' ? 4 : 6]
            : theme.colorScheme === 'dark'
                ? theme.colors.dark[0]
                : theme.colors.gray[7];
}


function ImageUploadIcon({
    status,
    ...props
}) {
    if (status.accepted) {
        return <Upload {...props} />;
    }

    if (status.rejected) {
        return <X {...props} />;
    }

    return <Photo {...props} />;
}

export const dropzoneChildren = (status, theme) => (
    <Group position="center" spacing="xl" style={{ minHeight: 220, pointerEvents: 'none' }}>
        <ImageUploadIcon status={status} style={{ color: getIconColor(status, theme) }} size={80} />

        <div>
            <Text size="xl" inline>
                Yolla gelsin
            </Text>
            <Text size="sm" color="dimmed" inline mt={7}>
                Jpg formatında herhangi bir resmi buraya sürükle ve buraya tıkla
            </Text>
        </div>
    </Group>
);

function Demo() {

    const theme = useMantineTheme();

    return (
        <Card>
            <Card.Section>
                <Title order={3} p="lg">
                    Palet Oluşturucu
                </Title>
            </Card.Section>
            <Card.Section p="lg">
                <Dropzone accept={["image/jpeg"]} onDrop={(file) => console.log(`kabul: ${file}`)} onReject={(file) => console.log(file)}>
                    {(status) => dropzoneChildren(status, theme)}
                </Dropzone>
            </Card.Section>
        </Card>

    )
}`

**Comment by fatih-dogmus** [comment]
import { Upload, Photo, X } from 'tabler-icons-react';
import { Dropzone } from "@mantine/dropzone";
import { useMantineTheme, Group, Text, Card, Title } from "@mantine/core";

function getIconColor(status, theme) {
    return status.accepted
        ? theme.colors.red[theme.colorScheme === 'dark' ? 4 : 6]
        : status.rejected
            ? theme.colors.red[theme.colorScheme === 'dark' ? 4 : 6]
            : theme.colorScheme === 'dark'
                ? theme.colors.dark[0]
                : theme.colors.gray[7];
}


function ImageUploadIcon({
    status,
    ...props
}) {
    if (status.accepted) {
        return <Upload {...props} />;
    }

    if (status.rejected) {
        return <X {...props} />;
    }

    return <Photo {...props} />;
}

export const dropzoneChildren = (status, theme) => (
    <Group position="center" spacing="xl" style={{ minHeight: 220, pointerEvents: 'none' }}>
        <ImageUploadIcon status={status} style={{ color: getIconColor(status, theme) }} size={80} />

        <div>
            <Text size="xl" inline>
                Yolla gelsin
            </Text>
            <Text size="sm" color="dimmed" inline mt={7}>
                Jpg formatında herhangi bir resmi buraya sürükle ve buraya tıkla
            </Text>
        </div>
    </Group>
);

function Demo() {

    const theme = useMantineTheme();

    return (
        <Card>
            <Card.Section>
                <Title order={3} p="lg">
                    Palet Oluşturucu
                </Title>
            </Card.Section>
            <Card.Section p="lg">
                <Dropzone accept={["image/jpeg"]} onDrop={(file) => console.log(`kabul: ${file}`)} onReject={(file) => console.log(file)}>
                    {(status) => dropzoneChildren(status, theme)}
                </Dropzone>
            </Card.Section>
        </Card>

    )
}

**Comment by fatih-dogmus** [comment]
https://paste.ofcode.org/wrbq5f4zbb7FvB8St2n6A

**Comment by rtivital** [comment]
It works as expected for me (the same way it is described in code) in codesandbox – https://codesandbox.io/s/quiet-microservice-z1qv4v?file=/src/App.tsx

**Comment by fatih-dogmus** [comment]
You are write exactly. But not working on my pc. I'm using NextJS 12.1.6 with React 18.1.0. I am not using Typescript.

![image](https://user-images.githubusercontent.com/43666342/173250608-120ab012-5cce-49a4-908a-11e28c491663.png)

**Comment by fatih-dogmus** [comment]
It's working on CodeSandbox

**Comment by fatih-dogmus** [comment]
my package.json file

https://paste.ofcode.org/42qcPQiezVCnxeidfAUpGB

**Comment by rtivital** [comment]
Dropzone does not work with react 18, you need to either downgrade react to 17 or update Mantine to 5.0 alpha version – https://v5.mantine.dev/

**Comment by fatih-dogmus** [comment]
Thank you very much
