### ISSUE TITLE
Prop did not match with DateRangePicker

### ISSUE THREAD

**Issue by KevinPy** [mantinedev/mantine#162]
Hello,
I would use te DateRangePicker in a NextJS project, but I have an error when I use this component. I built a demo app with the basic usage from Mantine documentation, and we can see in console:

```
Warning: Prop `htmlFor` did not match. Server: "mantine-f6quwf3w1" Client: "mantine-9woky8pog"
```

When I remove the label of DateRangePicker, it's display an another error => `id`for button (not `htmlFor`). I use the `2.0.6` of Mantine. 

Demo: https://stackblitz.com/edit/nextjs-aunbfb?devtoolsheight=33&file=pages/index.js

Thank you for your help.

**Comment by rtivital** [comment]
Hi Kevin, mantine inputs use random id to connect label to input, to make this work you need to provide static id:

```tsx
<DateRangePicker id="my-date-range" />
```

Demo – https://stackblitz.com/edit/nextjs-hdznxz?devtoolsheight=33&file=pages/index.js

**Comment by KevinPy** [comment]
It's works. Thank you
