### ISSUE TITLE
Page load before third party provider styles are applied

### ISSUE THREAD

**Issue by archocron** [mantinedev/mantine#1620]
### What package has an issue

@mantine/core

### Describe the bug

Apparently, with next 12.1.6 when you load the page, the content is loaded first, and after that, styles are applied, so visually you can see during a few milliseconds the html without styles.

To reproduce the problem clone this repo https://github.com/mantinedev/mantine-next-template.git  everything will work smooth beacuse is using version  12.1.4 , in the moment you switch to 12.1.6 you will see this problem.

### In which browser did the problem occur

All

### Do you know how to fix the issue

Yes

### Possible fix

Going back to 12.1.5 version solve this issue.

**Comment by rtivital** [comment]
Next.js 12.1.6 has issues with css-in-js libraries, it is a known issue, you should either downgrade to 12.1.5 or upgrade to 12.1.7 canary version.
