### ISSUE TITLE
initialValues needlessly required on useForm

### ISSUE THREAD

**Issue by mlarcher** [mantinedev/mantine#1623]
### What package has an issue

@mantine/form

### Describe the bug

When using mantine/form, not providing an `initialValues` object results in an error serverside (using nextjs ssr) : `TypeError: Cannot read properties of undefined (reading 'password')`
Providing an empty `initialValues` is enough to avoid the issue.

### In which browser did the problem occur

chrome (or nodejs? as it is serverside...)

### Do you know how to fix the issue

Yes

### Possible fix

fallback to an empty object if initialValues is not provided

**Comment by rtivital** [comment]
Fixed in 5.0
