### ISSUE TITLE
getInputProps throws destructure error in 4.2.9

### ISSUE THREAD

**Issue by sep2** [mantinedev/mantine#1624]
### What package has an issue

@mantine/form

### Describe the bug

If the second argument is omitted  in `getInputProps`:

```jsx
<TextInput {...form.getInputProps('account')}/>
```

This error will be throwed:
 > Uncaught TypeError: Cannot destructure property 'type' of 'undefined' as it is undefined.
    at Object.getInputProps (use-form.a9841fd0.js:formatted:439:34)

This is okay:
```jsx
<TextInput {...form.getInputProps('account', {})}/>
```

### In which browser did the problem occur

Chrome latest version

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Before destructuring the `options` argument, check for nullability.

**Comment by rtivital** [comment]
I was not able to reproduce this error – https://codesandbox.io/s/clever-flower-dd8lvu?file=/src/App.tsx
Please send a sandbox that reproduces the issue

**Comment by sep2** [comment]
I'am not able to reproduce it in the sandbox, wired. However I was able to setup a minimal github repository that can reproduce this issue:

https://github.com/sep2/mantine-input-props

please clone the repo and do the following step:
```
yarn install
yarn build
yarn preview
```

**Comment by sep2** [comment]
After I deleted `yarn.lock` and did `yarn install` again the issue resolved. Seem like a bug in babel or someting.. Feel free to close. Thank you!
