### ISSUE TITLE
Mantine Rich Text Editor change value props not updating

### ISSUE THREAD

**Issue by hyusetiawan** [mantinedev/mantine#1625]
### What package has an issue

@mantine/rte

### Describe the bug

Using NextJS framework and following the integration guide, I have the following setup:

```
<RichTextEditor
  placeholder='Type "#" to insert auto fields'
  sx={{ minHeight: 500 }}
  value={content}
  onChange={setContent}
  mentions={mentions}
/>
```

when loading the `content` from graphql on the clientside, where the RTE would load first and then setContent is called after graphql request finishes, the content being rendered by RTE does not update and it's just going to render as empty. A way to work around it is not to mount it until the value of content is available, so this works:

```
{content != null && <RichTextEditor
  placeholder='Type "#" to insert auto fields'
  sx={{ minHeight: 500 }}
  value={content}
  onChange={setContent}
  mentions={mentions}
/>}
```
I would assume changes in content would change the rendering, like any controlled component would. I have also tried using `key` trick to force remount but it still does not update the value being rendered.

### In which browser did the problem occur

chrome, latest

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I am not sure

**Comment by rtivital** [comment]
This is how quill works, if the value is forced, then it will throw errors in certain scenarios. We've moved rte to a default value recently and this logic will not be changed.

**Comment by hyusetiawan** [comment]
@rtivital I see, can you suggest how to change the value after the component is mounted then?

**Comment by rtivital** [comment]
You can get access to quill instance with ref prop – https://mantine.dev/others/rte/#get-editor-ref
Then you will be able to call method that sets editor content (check quill docs, I do not remember which one it is)

**Comment by hyusetiawan** [comment]
figured out how, instead of the suggested integration with NextJS in the docs, do this:
```
export default dynamic(
  async () => {
    const { default: RQ } = await import('@mantine/rte')

    return ({ editorRef, ...props }: RichTextEditorProps & { editorRef: Ref<Editor> }) => (
      <RQ ref={editorRef} {...props} />
    )
  },
  {
    ssr: false,
  },
)

```
you can't just do forwardRef on dynamically imported components, so we created a custom prop instead of the special `ref` prop, called `editorRef`. Here's how you use it:

```
const editorRef = useRef<Editor>()
  useEffect(() => {
    editorRef.current?.editor?.clipboard.dangerouslyPasteHTML(selectedTemplate?.content ?? '')
  }, [editorRef.current?.editor, selectedTemplate])
```
