### ISSUE TITLE
Overriding `flex-grow` with `sx` doesn't work

### ISSUE THREAD

**Issue by kwiat1990** [mantinedev/mantine#1631]
### What package has an issue

@mantine/core

### Describe the bug

Hey, I have a problem using a `Textarea` and two `Button`components inside a `Group`. I want that textarea fill all free space, so I set `flexGrow: 1`. The problem is that `Group` sets on all its children `flexGrow` property as well and this will be appended to children styles, so it overrides all styles set direct on children with `sx` or `styles` props. 

To solve this problem I tried to use `!important` but somehow TS is not happy if I make it for `flexGrow`. In case of `padding` adding `!important` wasn't a problem.

In Codesanbox you can see what I mean.  

### In which browser did the problem occur

Every

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/funny-violet-dgt3m5?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
You can use flex instead of flexGrow – https://codesandbox.io/s/quirky-hodgkin-8v99rs?file=/src/App.tsx

**Comment by kwiat1990** [comment]
@rtivital do you know why is it doesn't work with the other property? It seems a little bit strange that with some properties it doesn't trigger this error.

**Comment by rtivital** [comment]
Properties that allow any string value do not trigger error when you use string with `!important`, other properties accept only specific values
