### ISSUE TITLE
Multiselect incorrectly applying label styles to values

### ISSUE THREAD

**Issue by lkaratun** [mantinedev/mantine#1633]
### What package has an issue

@mantine/core

### Describe the bug

When using either `classNames` or `styles` prop on Multiselect component, label props are incorrectly applied both on the label and values
![image](https://user-images.githubusercontent.com/17469132/173709511-4573e8fa-bec5-434d-9f04-3785ef745a8f.png)

### In which browser did the problem occur

Brave

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/weathered-cache-849j24?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Thanks for reporting, the issue will be fixed in next patch

**Comment by rtivital** [comment]
Fixed in 4.2.10
