### ISSUE TITLE
Warning: Prop `className` did not match mantine-UnstyledButton-root

### ISSUE THREAD

**Issue by bogordesaincom** [mantinedev/mantine#1635]
### What package has an issue

@mantine/core

### Describe the bug

Warning where using `className` in UnstyledButton component 

```Warning: Prop `className` did not match. Server: "mantine-UnstyledButton-root mantine-aa6a7y" Client: "mantine-UnstyledButton-root mantine-hc4lhc"```

### In which browser did the problem occur

chrome

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
This happens in these two cases:
- You haven't configured ssr correctly
- You have logic on client that is different from the logic on server, e.g. `useMediaQuery` hook, random values, etc.

**Comment by bogordesaincom** [comment]
ahh ... i see. i forget useMediaQuery is server side renderning. okok thanks @rtivital
