### ISSUE TITLE
Documentation - Signature of updateNotification does not match demo

### ISSUE THREAD

**Issue by MrOnosa** [mantinedev/mantine#1645]
https://github.com/mantinedev/mantine/blob/0b38cfe2a421f6b1cea7872e603d1acf3d7884d7/src/mantine-demos/src/demos/notifications/Notifications.demo.update.tsx#L27-L34

Demo passes `updateNotification` 1 parameter.

https://github.com/mantinedev/mantine/blob/0b38cfe2a421f6b1cea7872e603d1acf3d7884d7/src/mantine-notifications/src/NotificationsProvider/use-notifications-state/use-notifications-state.ts#L24

In practice, there are 2 parameters. This caused me some confusion when TypeScript said `Expected 2 arguments, but got 1.`

**Comment by rtivital** [comment]
updateNotification function takes single argument – https://github.com/mantinedev/mantine/blob/0b38cfe2a421f6b1cea7872e603d1acf3d7884d7/src/mantine-notifications/src/events.ts#L22
