### ISSUE TITLE
RTE strikethrough icon is a U?

### ISSUE THREAD

**Issue by noahgrant** [mantinedev/mantine#1646]
### What package has an issue

@mantine/rte

### Describe the bug

Hello!

Just wondering why the stikethrough icon on the RTE is a U:
![image](https://user-images.githubusercontent.com/1355779/174132453-1fe7ef9e-9faa-4cc6-a91c-31e1006d3b80.png)

I would expect something more like an S:

![image](https://user-images.githubusercontent.com/1355779/174132661-3480ca85-2405-464c-a96b-4c547968343a.png)

Are you open to changing this?

Thank you!

### In which browser did the problem occur

Chrome

**Comment by rtivital** [comment]
Icons for rich text editor are changed in 5.0 – https://v5.mantine.dev/others/rte/
