### ISSUE TITLE
Dropzone not rejecting correctly with react 18

### ISSUE THREAD

**Issue by konsumer** [mantinedev/mantine#1647]
### What package has an issue

@mantine/dropzone

### Describe the bug

With react 18, Dropzone does not correctly change the color/icon with the example code. It still accepts it, but always sets status to `rejected: true`, so it displays wrong. If I downgrade to react 17, it works fine.

![](https://files.slack.com/files-pri/T04NA3XDG-F03L3V32AQL/screen_shot_2022-06-16_at_6.37.41_pm.png)

### In which browser did the problem occur

chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hardcore-meitner-wv5xj3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Investigate why it is incorrectly setting status with same version of mantine, on 2 different versions of react.

**Comment by ZhouZ-1** [comment]
Had the same issue. I looked into it and the source of the bug is from react-dropzone and not Mantine. The solution is to update the react-dropzone dependency to 14.1.1 or higher. 

Source: https://github.com/react-dropzone/react-dropzone/issues/1167

**Comment by rtivital** [comment]
Fixed in 5.0
