### ISSUE TITLE
RangeSlider doesn't update when `max` prop provided

### ISSUE THREAD

**Issue by brandongregoryscott** [mantinedev/mantine#1650]
### What package has an issue

@mantine/core

### Describe the bug

When the `max` prop is provided to the `RangeSlider` component, it seems to break the component's state/change handling behavior - nothing happens on click/drag.

```tsx
<RangeSlider max={5} />
```

As an example, I'd like to use a `RangeSlider` to select a value between 1 and 5, but clicking and dragging on each thumb doesn't update the component - controlled or uncontrolled.

### In which browser did the problem occur

Google Chrome Version 102.0.5005.115 (Official Build) (x86_64)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/rangeslider-with-min-max-props-cx6lp0?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by brandongregoryscott** [comment]
Oops - turns out this isn't a bug, but maybe some less obvious behavior. After digging into the source, I noticed the default props:

https://github.com/mantinedev/mantine/blob/b0ac2efb6c04ab34da7b679e825d57acaa9ce735/src/mantine-core/src/components/Slider/RangeSlider/RangeSlider.tsx#L106-L108

Looks like it wasn't allowing any change because the `minRange` value was always larger than the `max` value. I'm wondering if that default value makes sense - what if it was set to 1 by default, which would still enforce the minimum and maximum values to be unique, but prevent this pitfall for consumers defining a smaller range?

**Comment by rtivital** [comment]
You need to set minRange – https://codesandbox.io/s/rangeslider-with-min-max-props-forked-9fvfkj
