### ISSUE TITLE
disable Chrome Autocomplete behavior

### ISSUE THREAD

**Issue by mlarcher** [mantinedev/mantine#1656]
### What package has an issue

@mantine/core

### Describe the bug

In chrome, the browser's native autocomplete behaviour makes the experience with Mantine's Autocomplete component disappointing, as we see both the suggestions from Mantine's component _and_ the browsers' suggestions on top of it.

It seems that chrome doesn't honor the `autocomplete="off"` attribute.
From https://stackoverflow.com/a/30976223/263440 we learn more about Chrome's point of view on the matter, and in particular : "In cases where you want to disable autofill, our suggestion is to utilize the autocomplete attribute to give semantic meaning to your fields. If we encounter an autocomplete attribute that we don't recognize, we won't try and fill it."

I tested changing the value in the DOM, and indeed setting `autocomplete="whatever"` prevents chrome's dropdown from showing up.

Would it be possible to make the autocomplete value one of the component's props, so that we have control over it ?

### In which browser did the problem occur

chrome

### Do you know how to fix the issue

Yes

### Possible fix

allow providing a value for the autocomplete attribute that would be different from 'off'.

**Comment by mlarcher** [comment]
I juste realized we just have to pass the attribute and it will be forwarded. Sorry for the useless issue :|

**Comment by rtivital** [comment]
You can set `autoComplete="value"` on your side, we've received multiple requests to remove non-standard attributes.
