### ISSUE TITLE
Dates in Calendar is not focusable with keyboard

### ISSUE THREAD

**Issue by vanquishkuso** [mantinedev/mantine#1663]
### What package has an issue

@mantine/dates

### Describe the bug

For accessibility when navigating by keyboard, in some situations it's not possible to focus on dates:

- When the first date is excluded (ex. in June on calendar it's 30th of May).
- When trying to reach dates that are on the other side of a row of excluded dates (ex. when excluding date.getDay() === 3)
- When using minDate on todays date

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/elegant-greider-7hj3jp?file=/src/App.js

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
If you also disable click events, then yes
