### ISSUE TITLE
weekendDays not passed from Calendar to Month

### ISSUE THREAD

**Issue by valentic** [mantinedev/mantine#1665]
### What package has an issue

@mantine/dates

### Describe the bug

The Month object now supports the weekendDays paramater as of v4.2.9. However, I don't see a way to pass this from the Calendar object. If you specify it, it gets captured in the ...other catchall which is then passed to Box. It seems like it needs to be actually listed in the params and then directly passed to MonthList.

### In which browser did the problem occur

Firefox

### Possible fix

Add weekendDays to CalendarBaseProps and pass to MonthList

**Comment by rtivital** [comment]
Thanks for reporting, the issue will be fixed in next patch

**Comment by rtivital** [comment]
Fixed in 4.2.11
