### ISSUE TITLE
No width set on chips component checkIcon SVG, resulting in huge icon on initial render before CSS load

### ISSUE THREAD

**Issue by maxratajczak** [mantinedev/mantine#1666]
### What package has an issue

@mantine/core

### Describe the bug

Since the checkIcon on the Chips component doesn't have a width set directly on the svg element, the svg icon displays as a massive icon when the page loads prior to the CSS styling being applied. You can see it for a split second when you refresh a page with a chip component that has a pre-selected chip. Another easy way to replicate is to set network throttling to "slow" in chrome dev tools and disable caching.

### **Before CSS Load**
![Screen Shot 2022-06-21 at 9 06 37 PM](https://user-images.githubusercontent.com/75450072/174921850-8e2becc7-4942-4fa3-875e-98d69b7aaca7.png)

### **After CSS Load**
![Screen Shot 2022-06-21 at 9 08 01 PM](https://user-images.githubusercontent.com/75450072/174921892-01ef8fbd-e62b-472c-830f-8a0a332bbbde.png)

### In which browser did the problem occur

Google Chrome

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Set the width directly on the SVG element for the checkIcon.

**Comment by rtivital** [comment]
The issue is not with icon, you have broken server side rendering
