### ISSUE TITLE
Mantine Forms makes Text Inputs uneditable

### ISSUE THREAD

**Issue by DD10654** [mantinedev/mantine#1668]
### What package has an issue

@mantine/form

### Describe the bug

I was making a calendar app, where the user can make events and save them to local storage. When the user clicked add event it would open a modal with 2 text inputs, Event Title, and description.
![Screen Shot 2022-06-22 at 12 06 21 PM](https://user-images.githubusercontent.com/75024070/174960017-02ce469b-e016-48c0-b6ee-095a34d39a5c.png)
![Screen Shot 2022-06-22 at 12 06 29 PM](https://user-images.githubusercontent.com/75024070/174960031-e7b85382-c71b-4552-853c-b747b4d42ef7.png)

I was searching for a way how I could get the text from the text input, and found the use-form() hook in mantine, but when I tried to use it, I could not type. I was pressing my keys to no result. And next time when I opened the modal, it displayed the last character from the last time I typed in it. (For example If I wrote "hello", the next time I opened the modal it would already be filled with "o")

Here is my code:

 `const form = useForm({`
`    initialValues: {`
`      title: '',`
`      description: '',`
`    },`
`  });`

`  const modals = useModals();`
`  const openContentModal = () => {`
`    const id = modals.openModal({`
`      title: 'Add Event',`
`      children: (`
`        <>`
`       <form onSubmit={form.onSubmit((values) => console.log(values))}>`
`          <TextInput label="Event Title" {...form.getInputProps('title')} required />`
`          <TextInput label="Event Description" {...form.getInputProps('description')} required />`
`          <Button fullWidth type="submit" onClick={() => `
`            {`
`              modals.closeModal(id)`
`              console.log(form.values)`
`            }} mt="md">`
`            Submit`
`          </Button>`
`          </form>`
`        </>`
`      ),`
`    });`
`  };`

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
You cannot use interactive elements this way with `@mantine/modals` package, if you want a form within the modal you need to create a wrapper component that will encapsulate the state logic, see example – https://codesandbox.io/s/hungry-feather-2185x

**Comment by DD10654** [comment]
Thank you so much!
