### ISSUE TITLE
Footer links hide in small devices.

### ISSUE THREAD

**Issue by gyancodes** [mantinedev/mantine#1673]
### What package has an issue

@mantine/core

### Describe the bug

While using footer in small media devices all the links get hidden, It would be better If they are still on small media devices. 

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine-app.vercel.app/

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Like we can use flex-direction: column; so that It don't create a mess and we can able to navigate properly even in small media devices.

**Comment by rtivital** [comment]
Hi @gyancodes, we cannot provide support for your project, when you copy/paste the code, you take full ownership of the code.

**Comment by gyancodes** [comment]
@rtivital  Thanks for your help, I will figure out the solution.
