### ISSUE TITLE
Checkbox styles from MantineProvider are not applied to Checkboxs inside a CheckboxGroup

### ISSUE THREAD

**Issue by ahulterstrom** [mantinedev/mantine#1676]
### What package has an issue

@mantine/core

### Describe the bug

According to the [docs](https://mantine.dev/theming/mantine-provider/#styles-on-mantineprovider), 
> You can add context styles to components that support [Styles API](https://mantine.dev/theming/styles-api/) with MantineProvider. All components that are rendered inside MantineProvider will inherit those styles

This works as expected on a `Checkbox`, but when a `Checkbox` is placed inside a `CheckboxGroup`, those styles are no longer applied.

<img width="491" alt="image" src="https://user-images.githubusercontent.com/55113250/175657353-a1f7e487-93ff-439d-b215-c52c17a0b296.png">

See the [codesandbox link](https://codesandbox.io/s/billowing-smoke-12qcen?file=/src/App.tsx) for a minimal example

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/billowing-smoke-12qcen?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Already fixed in 5.0

**Comment by abassi94** [comment]
> 

when to release 5.0 .
I have the same issue .

**Comment by rtivital** [comment]
Fixed in 5.0
