### ISSUE TITLE
Ugly select dropdown jump

### ISSUE THREAD

**Issue by gonciuu** [mantinedev/mantine#1680]
### What package has an issue

@mantine/core

### Describe the bug

Hi, I made a simple form using mantine select, but I found a little bug. Only in the first page load when I click select the dropdown goes a little left and then jump to the correct position. 
Please watch my youtube video of that : https://youtu.be/KMm75RrItUk

The bug only appear when the items count is more than 4

### In which browser did the problem occur

brave

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by Maetes** [comment]
Do you have applied any transition?

**Comment by gonciuu** [comment]
I found a solution. You just need to add  `withinPortal={false}` and the bug disappear.

**Comment by piotrkraszewski** [comment]
`withinPortal={false}` indeed fixes the issue, however I think the bug still remains because developer would expect correct rendering by default. I think the issue should still be open.

**Comment by gonciuu** [comment]
Yep, you're right. I reopened the issue

**Comment by rtivital** [comment]
Should be fixed in 5.0, we've migrated the library from popper to floating ui
