### ISSUE TITLE
Transition duration not correctly applied

### ISSUE THREAD

**Issue by Maetes** [mantinedev/mantine#1686]
### What package has an issue

@mantine/core

### Describe the bug

This is a react 18 issue. I think the problem is that the Transition component within the useTransition.ts is using the useDidUpdate hook. Within React 18 the strict mode now executes useeffect twice so the hook is more or less useless? Since because of the second loop it is deemed mounted but is not actually.

This cause several problems like the one i faced. The transitions are not correctly applied to the dropdown of the Select component. On top of that, there is a side effect issue within the useTransition.ts causing a duration missmatch between the variables _duration and transitionDuration.

I found a workaround to fix the sideeffect issue. Nevertheless I think the useDidUpdate hook is also worth to rethink. I'll create a pull request updating the useTransitions.ts to apply the transitions correctly in dev mode under react 18.

If I still miss something I'm happy to discuss

### In which browser did the problem occur

any

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Fixed in 5.0
