### ISSUE TITLE
DatePicker's Modal not receiving styles 

### ISSUE THREAD

**Issue by korac** [mantinedev/mantine#1695]
### What package has an issue

@mantine/dates

### Describe the bug

When rendering `DatePicker` component with `dropdownType='modal'` prop, it is not possible to style the modal with `DatePicker`'s `styles` prop (as with styling the `popover`).

[Inside `DatePickerBase` component](https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/DatePickerBase/DatePickerBase.tsx#L362-L370), `Modal` doesn't receive any of the parent component's styles.

### In which browser did the problem occur

Chrome

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Not familiar 100% with Styles API under the hood but I believe we could pass certain classnames to `Modal` component being rendered within `DatePickerBase`.

**Comment by rtivital** [comment]
Fixed in 5.0, DatePicker now supports `modalProps` prop
