### ISSUE TITLE
Scrollbar glitch of Select dropdown with large number of options

### ISSUE THREAD

**Issue by medihack** [mantinedev/mantine#1700]
### What package has an issue

@mantine/core

### Describe the bug

In v5-alpha18 the Select dropdown shows a native scrollbar in addition to the styled small scrollbar when the options list is very long and you scroll down to the bottom of the list.

![ugly_scrollbar2](https://user-images.githubusercontent.com/120626/176548602-fb97167e-e9f5-4d23-8f3b-f70bff064b6b.png)

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/xenodochial-tamas-1nfnzx?file=/src/App.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by rtivital** [comment]
Fixed in `5.0.0-alpha.19`
