### ISSUE TITLE
@mantine/rte not able to dynamically update the contents with response I receive from backend

### ISSUE THREAD

**Issue by amartya-dev** [mantinedev/mantine#1709]
### What package has an issue

@mantine/rte

### Describe the bug

I want the content editor to update its value once I receive it from my backend API, the update only works sometimes, most of the times it keeps displaying the initial blank page with which it initializes.

This is what I am trying to do (only relevant code snippets pasted:

```typescript
async function getBlogDetails() {

    const [blogContent, setBlogContent] = useState<string>("");
    
    const response = await apiCall({
      toast: toast,
      apiFunc: async () => {
        return await axios.get<BlogDetails>(`/api/blogs/${slug}/user`);
      },
    });

    if (response?.data) {
      setBlogDetails(response.data);
      response.data.content && setBlogContent(response.data.content);
      response.data.tags && setBlogsTags(response.data.tags);
    }
  }
....
    <ContentEditor
        stickyOffset={80}
        value={blogContent}
        onChange={(content) => {
          setBlogContent(content);
          setBlogDetails({
            ...blogDetails,
            content: content,
          });
        }}
      />
....
```

The blogContent state does get updated after a few iterations but the editor defaults to `<p><br><p>` for the entire duration.

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
RichTextEditor cannot be fully controlled, see how to update value after mount – https://github.com/mantinedev/mantine/issues/1625#issuecomment-1154506482

**Comment by amartya-dev** [comment]
So I use the ref to change the content?

**Comment by rtivital** [comment]
Yes, you can do so

**Comment by amartya-dev** [comment]
I did try assigning and dangerously pasting it to the editor till according to the suggested code, doesn't seem to work for me:
```typescript
const editorRef = useRef<Editor>(null);

useEffect(() => {
    editorRef?.current?.editor?.clipboard.dangerouslyPasteHTML(
      blogDetails.content || ""
    );
  }, [editorRef.current?.editor, blogDetails]);

<ContentEditor
        stickyOffset={80}
        value={blogDetails.content || ""}
        ref={editorRef}
        onChange={(content) => {
          setBlogDetails({
            ...blogDetails,
            content: content,
          });
        }}
      />
```

**Comment by rtivital** [comment]
Well, then I can only advise not to render rte until you've received the data from the backend

**Comment by amartya-dev** [comment]
Yyup, that works, I plugged in a loading state to wait for the content, thanks for the suggestion

**Comment by amartya-dev** [comment]
Closed the issue since my problem is solved, do you think we could do something for making this dynamically controllable ?
