### ISSUE TITLE
[v5] RadioGroup is not available in '@mantine/core' 

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#1713]
### What package has an issue

@mantine/core

### Describe the bug

RadioGroup not exist in exported values in '@mantine/core' 
Autoimport give me also wrong path: 
`import { RadioGroup } from '@mantine/core/lib/components/Radio/RadioGroup/RadioGroup';`

```bash
Module not found: Can't resolve '@mantine/core/lib/components/Radio/RadioGroup/RadioGroup'
```

### In which browser did the problem occur

chrome

**Comment by captchafree** [comment]
You need to use `Radio.Group` with v5:

```jsx
import { Radio } from '@mantine/core'

function Component() {

    return (
        <Radio.Group>
        ...
        </Radio.Group>
    )
}
```

**Comment by 7iomka** [comment]
> You need to use `Radio.Group` with v5:
> 
> ```js
> import { Radio } from '@mantine/core'
> 
> function Component() {
> 
>     return (
>         <Radio.Group>
>         ...
>         </Radio.Group>
>     )
> }
> ```

Oh, is so hard without docs)
