### ISSUE TITLE
Menu position don't work in first open

### ISSUE THREAD

**Issue by esqui2002** [mantinedev/mantine#1716]
### What package has an issue

@mantine/core

### Describe the bug

This issue is using mantine v5.0.0-alpha.13

Menu component, when is used with position prop,  in this case, "bottom-end", the first time doesn't calculate propelly the position and the size of the menu. 

The first time when i open the menu
![image](https://user-images.githubusercontent.com/25133940/176997734-727a990e-399f-4904-a329-a7f8b6f251f5.png)

The second time i open the menu. This is the expected way. 
![image](https://user-images.githubusercontent.com/25133940/176997754-446444fe-9f04-47c9-9a64-bab7cbfc6d64.png)

Source code of menu: 
``` tsx
<Menu position="bottom-end">
      <Menu.Target>
        <Avatar color="cyan" radius="xl" mr="sm" className={classes.avatar}>
          {name.charAt(0)}
        </Avatar>
      </Menu.Target>
      <Menu.Dropdown>
        <Menu.Item
          icon={
            colorScheme === "dark" ? <Sun size={14} /> : <MoonStars size={14} />
          }
          onClick={() => toggleColorScheme()}
        >
          {colorScheme === "dark" ? "Tema claro" : "Tema oscuro"}
        </Menu.Item>
        <Menu.Item
          color="red"
          icon={<Logout size={14} />}
          onClick={() => logOut()}
        >
          Cerrar sesión
        </Menu.Item>
      </Menu.Dropdown>
    </Menu>
```

### In which browser did the problem occur

Brave

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Please send a sandbox that reproduces the issue, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6
