### ISSUE TITLE
Invalid background-image property in Button

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#1717]
### What package has an issue

@mantine/core

### Describe the bug

In generated styles for button I see wrong value for background-image
```css
background-color: #228be6;
background-image: #228be6;
```

### In which browser did the problem occur

Chrome

### Possible fix

set background-image: none, or not set this prop at all.

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by rtivital** [comment]
I do not see background-image styles in devtools 
<img width="617" alt="Снимок экрана 2022-07-02 в 19 57 35" src="https://user-images.githubusercontent.com/10353856/177009547-0e36bfcf-1e01-43b7-8284-9785ef12c291.png">

**Comment by 7iomka** [comment]
@rtivital is for variant="outline"

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/18473137/177010794-7a4e08f2-24b9-40f1-8ee1-7a2db1ff1dec.png">

**Comment by 7iomka** [comment]
Also I would think about consecrating the issue with the ability for the user to control `autoprefixer` settings, because, for example `-webkit-text-decoration` no more needed long time ago.
As a good practice is to consider user `browserslist` key in your `package.json`, how do this next.js
https://nextjs.org/docs/advanced-features/customizing-postcss-config#customizing-target-browsers

**Comment by rtivital** [comment]
I cannot find background-image styles on outline button, can you create a sandbox that reproduces the issue?
<img width="623" alt="Снимок экрана 2022-07-02 в 22 20 51" src="https://user-images.githubusercontent.com/10353856/177013799-0ba7e69b-fdd7-47d1-b112-16cc1b9e294c.png">

**Comment by 7iomka** [comment]
@rtivital 
https://codesandbox.io/s/happy-breeze-jl6kcv?file=/src/App.tsx

**Comment by rtivital** [comment]
Fixed in 5.0.2

**Comment by rtivital** [comment]
Will be fixed in 5.0.3, PR is merged
