### ISSUE TITLE
Checkbox inside button is not valid html markup

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#1718]
### Link to the page where something nasty is located

https://ui.mantine.dev/category/inputs

### Exact quote of what is wrong

How I see for custom checkable options you use `UnstyledButton` which renders `button`
Checkbox inside button is not valid html markup, even if is not focusable.
Possible fix: add `component` prop to `UnstyledButton` with `div` or `span` as one of accepted variants.
Or propose another workaround to have valid markup

**Comment by rtivital** [comment]
ui.mantine.dev provides examples, if valid html markup is important for our project you should fix the issue on your side after copying the code.
