### ISSUE TITLE
Fullscreen modal get cutted on the left on Windows and Linux

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#1721]
### What package has an issue

@mantine/core

### Describe the bug

https://v5.mantine.dev/changelog/5-0-0/#fullscreen-modal

Inner padding for content of modal (20px in this example) get cutted by negative margin
```
margin-left: calc(var(--removed-scroll-width, 0px) * -1);
```

### In which browser did the problem occur

Chrome

### Possible fix

You need to choose different workarounds for 2 cases - when overflow="outside" or "inside"
If outside, put padding with `var(--removed-scroll-width, 0px)` on fixed wrapper
If inside maybe the same, because it the same behavior when is fullwidth.

Another case that needed to be fixed is time when --removed-scroll-width was calculated.
For now is calculated AFTER modal was open. This cause CLS for fullwidth variant, and this is not good.

**Comment by rtivital** [comment]
Fixed in 5.1.6
