### ISSUE TITLE
State in Rich Text Editor not updated in readOnly mode

### ISSUE THREAD

**Issue by liliwei25** [mantinedev/mantine#1726]
### What package has an issue

@mantine/rte

### Describe the bug

When RTE is set to read only mode, the component is not updated when the state of the value changes

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/ecstatic-parm-dz4s3f?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Use `value` instead of `defaultValue` [here](https://github.com/mantinedev/mantine/blob/master/src/mantine-rte/src/components/RichTextEditor/RichTextEditor.tsx#L159)

**Comment by rtivital** [comment]
See #1709 for discussion. rte cannot be fully controlled.
