### ISSUE TITLE
[v5] @emotion/cache `prepend` options not working on production with Next.js

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#1730]
### What package has an issue

@mantine/core

### Describe the bug

I use latest version of next.js.
In dev mode all works fine, `prepend: false` works as expected.
In build mode, it works like don't see this option and prepend styles.
I tested, and I see if I disable javascript in devtools, then styles location in correct.
How to find what cause this issue?
Help needed.

https://user-images.githubusercontent.com/18473137/177079017-1bb86b4f-cb78-40a4-ac80-c68d52368448.mp4

### In which browser did the problem occur

Chrome

**Comment by rtivital** [comment]
Fixed in 5.0. You are now required to provide your own emotion cache – styles insertion point is fully managed on your side.
