### ISSUE TITLE
DateRangePicker and DatePicker not calling onChange when date/dates are cleared.

### ISSUE THREAD

**Issue by JavanHuang** [mantinedev/mantine#1737]
### What package has an issue

@mantine/dates

### Describe the bug

When a DatePicker/DateRangePicker is cleared using the `clearable`  prop, the `onChange` prop is not invoked.

This is similar to https://github.com/mantinedev/mantine/issues/1294 where when TimeInput is cleared, `onChange` is not called.

### In which browser did the problem occur

All

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/DateRangePicker/DateRangePicker.tsx#L159

https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/DatePicker/DatePicker.tsx#L169

Looks like a similar fix done in https://github.com/mantinedev/mantine/pull/1342.

**Comment by rtivital** [comment]
It works as expected on codesandbox – https://codesandbox.io/s/charming-shaw-fk6tww?file=/src/App.tsx

If you still have this issue:
- try turning off strict mode
- try building a production app and see if you can experience the issue in prod env
