### ISSUE TITLE
DatePicker UI Broken with @mantine/dates v4.2.12

### ISSUE THREAD

**Issue by sgrobert** [mantinedev/mantine#1745]
### What package has an issue

@mantine/dates

### Describe the bug

Hi there,

I am currently using the following codes to activate the `modal` type:

```
import { DatePicker } from "@mantine/dates";
...

<DatePicker 
    ...
    dropdownType="modal" 
    ...
/>

```

After `onClick` of the component, it throws the following buggy UI.

---
Screenshot 1:
![Screenshot 2022-07-06 at 10 27 14 AM](https://user-images.githubusercontent.com/759805/177520352-ac62faf2-9b66-4296-bb0b-7da9392b1e33.png)

Screenshot 2:
![Screenshot 2022-07-06 at 10 27 24 AM](https://user-images.githubusercontent.com/759805/177520398-f5873ac4-8343-483e-8b99-7eb78ee0bb0c.png)

---

### In which browser did the problem occur

Version 1.40.107 Chromium: 103.0.5060.53 (Official Build) (arm64)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/patient-moon-oogczz?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Though I have tried replicating the issue, I was unable to via the above link, thus I might presume the issue might come from a "clash" between different use of libraries.

I'm listing out potential libraries that might be the cause of the current issue. Hope it helps:

---

```
    ...
    "@emotion/react": "^11.9.3",
    "@emotion/styled": "^11.9.3",
    "@mantine/core": "^4.2.12",
    "@mantine/dates": "^4.2.12",
    "@mantine/hooks": "^4.2.12",
    "@mantine/next": "^4.2.12",
    "@mui/lab": "^5.0.0-alpha.89",
    "@mui/material": "^5.8.7",
    "date-fns": "^2.28.0",
    "dayjs": "^1.11.3",
    "next": "^12.2.0",
    "react": "18.2.0",
    "react-responsive-carousel": "^3.2.23",
    "react-select": "^5.4.0",
    "react-switch": "^7.0.0",
    ...

```

---

**I do think it is a CSS issue ultimately**, but definitely, if you need help for me to test it out, do let me know. Cheers!

**Comment by rtivital** [comment]
You have the error in your sandbox. After fixing it, I cannot reproduce the issue – https://codesandbox.io/s/boring-cohen-icrpyw?file=/src/App.tsx
