### ISSUE TITLE
Performance of select component rendering with >= 200 items.

### ISSUE THREAD

**Issue by abouolia** [mantinedev/mantine#1747]
### What package has an issue

@mantine/core

### Describe the bug

I think the select component is not designed for that, the rendering performance of the menu becomes incredibly slow and takes time just to show up when injecting more than >=200 items. is there any plan in the future to do a virtual list or lazy rendering?

### In which browser did the problem occur

Doesn't matter

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Doing virtual list.

**Comment by justinsmid** [comment]
The recommendation usually given here for these problems is to use the `limit` prop to limit the number of rendered items, though I am personally not a very big fan of that solution either and would also prefer something like a virtual list implementation.

**Comment by rtivital** [comment]
Yep, I recommend to use `limit` prop, there are no plans of adding virtualization any time soon

**Comment by h3adache** [comment]
Is mantine not suitable for domains that intrinsically have large data? finance for example?
Coming from react aria, the performance of mantine is pretty bad in these scenarios.
