### ISSUE TITLE
Title fontSize theming

### ISSUE THREAD

**Issue by hoodsy** [mantinedev/mantine#1748]
### Link to the page where something nasty is located

https://mantine.dev/theming/extend-theme/

### Exact quote of what is wrong

theme.headings – controls font-family, line-height and font-size of h1-h6 tags in [Title](https://mantine.dev/core/title/) and [TypographyStylesProvider](https://mantine.dev/core/typography-styles-provider/) components

How is it possible to specify sizes of h1, h2, h3 etc in the theme? I haven't been able to find an example online and what I've tried hasn't worked.

### Are you willing to create pull request with the fix?

No

**Comment by ivan-kleshnin** [comment]
To style `h1` you'd have to write your own `Typography` component. It's an issue that the original version of the component does not repeat Theme styles but duplicate hardcoded Mantine styles instead. I've also noticed many inconsistencies with code size, blockquote not having an icon an so on. So I ended up copying `TypographyStylesProvider` to `Typography` (frequent component, name should be short). Here's my version FYI: https://gist.github.com/ivan-kleshnin/fd2e990ea02247818b5155b064751606

**Comment by jason-dark** [comment]
@ivan-kleshnin on a related note, what is the suggested way to set heading sizes at various breakpoints? I realise this syntax isn't support, but to illustrate what I mean;

```
  // MantineThemeOverride
  headings: {
    fontFamily: 'Georgia, serif',
    fontWeight: 400,
    sizes: {
      h1: {
        fontSize: '80px',
        lineHeight: '140%',
        [`@media (max-width: 300px)`]: {
          fontSize: '40px',
          lineHeight: '120%',
        }
      },
      ...
  },
```

The only (global) way I've found to achieve this is to use global styles with `!important` overrides on the css `font-size` properties, otherwise their values end up getting set by the default Mantine theme heading values. Thinking that perhaps there is a better way and I'm missing something.

**Comment by ivan-kleshnin** [comment]
I've switched to ChakraUI after all 😅 It's so much easier to customize and the API without endless `sx` is a joy to work with.

**Comment by rtivital** [comment]
You can specify font-sizes of each heading with `theme.headings.sizes`:
```tsx
import { Button, Code, Title, MantineProvider } from '@mantine/core';

function Demo() {
  return (
    <MantineProvider
      theme={{
        headings: { sizes: { h1: { fontSize: 22 }, h2: { fontSize: 20 }, h3: { fontSize: 18 }  } },
      }}
    >
      <App />
    </MantineProvider>
  );
}
```

**Comment by jason-dark** [comment]
> You can specify font-sizes of each heading with `theme.headings.sizes`:
> 
> ```tsx
> import { Button, Code, Title, MantineProvider } from '@mantine/core';
> 
> function Demo() {
>   return (
>     <MantineProvider
>       theme={{
>         headings: { sizes: { h1: { fontSize: 22 }, h2: { fontSize: 20 }, h3: { fontSize: 18 }  } },
>       }}
>     >
>       <App />
>     </MantineProvider>
>   );
> }
> ```

@rtivital is there a way to set heading sizes at various breakpoints at the theme level?

**Comment by rtivital** [comment]
No, that is not supported on `theme.headings`, you can add any additional styles with `theme.components` – https://codesandbox.io/s/optimistic-butterfly-x87xrg?file=/src/App.tsx
