### ISSUE TITLE
RangeSlider on Touch devices throws error "Unable to preventDefault inside passive event listener invocation"

### ISSUE THREAD

**Issue by raulcrisan** [mantinedev/mantine#1751]
### What package has an issue

@mantine/core

### Describe the bug

When using RangeSlider on touch devices I can see in the browser's console some errors:

-  [Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
onTouchMove @ use-move.js?6bc9:75
onTouchStart @ use-move.js?6bc9:72

- Unable to preventDefault inside passive event listener invocation

![image](https://user-images.githubusercontent.com/16705083/177771208-afbbbf2a-1f92-4344-9df8-e38d7ed9a6ef.png)

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Fixed in 5.1.4
