### ISSUE TITLE
Years before 100 aren't accessible

### ISSUE THREAD

**Issue by LoryPelli** [mantinedev/mantine#1758]
### What package has an issue

@mantine/dates

### Describe the bug

I found out that years before 100 doesn't work and for example 99 take you to 1999...

### In which browser did the problem occur

Chrome but I think that in all browsers this happens

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/embed/g8b7k

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
That is how JavaScript handles dates, for example, date `1 January 70` is considered to be `1 January 1970`. You can try providing your own `dateParser` to handle this use case.
