### ISSUE TITLE
`Calendar` / `RangeCalendar` throw an error when `amountOfMonths` is used in combination with `minDate` & `maxDate`

### ISSUE THREAD

**Issue by justinsmid** [mantinedev/mantine#1765]
### What package has an issue

@mantine/dates

### Describe the bug

As of `v4.2.12`, `Calendar` and `RangeCalendar` throw `Cannot read properties of undefined (reading 'getFullYear')` when the `minDate` and `maxDate` props are used together with `amountOfMonths`.

In the provided codesandbox, you can see that downgrading to `4.2.11` gets rid of the error, and so does removing either `minDate` and `maxDate`, or `amountOfMonths`. These props seem to work fine when used separately, but break when combined.

### In which browser did the problem occur

Verified on Chrome and Firefox, though it presumably occurs on others as well

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-forked-cq224i?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 5.0
