### ISSUE TITLE
[v5] - Select's onCreate does not allow you to return a simple string

### ISSUE THREAD

**Issue by justinsmid** [mantinedev/mantine#1768]
### What package has an issue

@mantine/core

### Describe the bug

As of v5, `Select` & `MultiSelect`'s  `onCreate` prop requires you to return a `SelectItem` from the onCreate function, but does not allow you to return a simple `string`, forcing you to use `SelectItem` where a `string` would've previously worked fine.

### In which browser did the problem occur

TypeScript-related, so not browser-specific

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-forked-8xbgj0?file=/src/App.tsx

### Possible fix

Allow returning strings from the onCreate function when the Select's `data` is a `string[]` rather than `SelectItem[]`

**Comment by rtivital** [comment]
Fixed in 5.0
