### ISSUE TITLE
[v5] - TypeScript error when passing `ref` to `Radio`

### ISSUE THREAD

**Issue by justinsmid** [mantinedev/mantine#1769]
### What package has an issue

@mantine/core

### Describe the bug

As of v5, `Radio` gives the error `Property 'ref' does not exist on type 'IntrinsicAttributes & RadioProps'` when passed a ref in the way described in the [docs](https://v5.mantine.dev/core/radio/#get-input-ref).

As you can see in the codesandbox, the ref does **work** since the expected value is logged to the console, so it seems to be a TypeScript issue only.

### In which browser did the problem occur

TypeScript-related error, so not browser-specific

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-forked-ih5mo0?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 5.0
