### ISSUE TITLE
Grid responsive

### ISSUE THREAD

**Issue by thuonghdbhsoft** [mantinedev/mantine#1774]
### What package has an issue

@mantine/core

### Describe the bug

I see that the small screen for grid breakpoints starts at 769px. It should be 768px
![Screenshot 2022-07-12 at 11 15 06](https://user-images.githubusercontent.com/38204111/178407319-2f611045-7534-4c96-87e3-ef855fd896ea.png)
x

### In which browser did the problem occur

Chrome, Nextjs 12.5

**Comment by rtivital** [comment]
This is how Mantine treats breakpoints to make sure that `min-width` and `max-width` media queries do not intersect. It is expected behavior.
