### ISSUE TITLE
Switch component handle has incorrect offset when `dir: 'rtl'` is set

### ISSUE THREAD

**Issue by obillekyle** [mantinedev/mantine#1778]
### What package has an issue

@mantine/core

### Describe the bug

Switch component have incorrect offset when `dir` is set to `rtl`

https://user-images.githubusercontent.com/69447211/178517211-b9c6bfae-44d5-4165-86e7-7ac197acc645.mp4

### In which browser did the problem occur

Chrome v103

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/spring-morning-whpvnw?file=/src/App.js

**Comment by rtivital** [comment]
Switch has broken styles because you did not follow rlt setup guide, `stylis-plugin-rtl` is required – https://mantine.dev/theming/rtl/
