### ISSUE TITLE
Multiple instances of @emotion/react

### ISSUE THREAD

**Issue by amberzaragoza** [mantinedev/mantine#1779]
### What package has an issue

@mantine/core

### Describe the bug

Hello,

I am getting the following warning whenever I run my application:

> You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.

For reference, I am using the following modules:

- @mantine/core
- @mantine/dropzone
- @mantine/form
- @mantine/modals
- @mantine/next
- @mantine/notifications

Is there anything I can do to resolve this?

### In which browser did the problem occur

Google Chrome

**Comment by rtivital** [comment]
Fixed in 5.0
