### ISSUE TITLE
[V5] Global styles has not 1st order in dom three, even if cache has `prepend: false`

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#1781]
### What package has an issue

@mantine/core

### Describe the bug

How docs say's [here](https://v5.mantine.dev/styles/global-styles/#global-component)
I added my custom global reset styles like
```js
'[type="button"],[type="reset"],[type="submit"]': {
        WebkitAppearance: 'button',
},
```

Expected behavior - global styles has 1st order in dom three, even if append or prepend option's in @emotion/cache settled.
Real behavior
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/18473137/178685900-e3dd4e1a-d94a-472b-ad36-e90c2541fed2.png">

I use next.js (latest) with the latest version of v5 mantine, with setup from the docs with the same exemplar of @emotion/cache in provider and _document

What's wrong and how to figure out? This breaks mantine styles, but I still need some reset styles for usage with another libraries.

### In which browser did the problem occur

Chrome

### Possible fix

Make some research with @emotion library

**Comment by rtivital** [comment]
This is expected behavior – when you define styles on your side, you are supposed to override Mantine components styles. If it is implemented differently, we will have a lot of other styles overriding issues.
