### ISSUE TITLE
[V5] Add a way to polyfill `gap` property, used in library code

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#1785]
### What package has an issue

@mantine/core

### Describe the bug

In my code with `css-in-js` approach, if I want to use some risky props like `gap` with flex elements, I use workaround like [this one](https://codesandbox.io/s/flex-gap-styled-components-q9tg8?from-embed=&file=/src/index.tsx)
With css I use `flex-gap-polyfill` package as postcss plugin.
I very like your ui-library, but this is very strange to drop users who uses iPhone 11 with the iOS 13.x.

It is possible to add similar workaround like from the example above, or to add a way to pass a function-wrapper (for example in MantineProvider, which be used in similar way under the hood?

Any other ideas?)

### In which browser did the problem occur

All

**Comment by rtivital** [comment]
Flexbox gap support is good enough for me, I do not think that I can provide any polyfills on my side, you should look for stylis plugins if you need to support old browsers.

**Comment by 7iomka** [comment]
Can someone help me to create a plugin for this purpose?
https://github.com/thysultan/stylis/issues/295
