### ISSUE TITLE
[V5] Shared object will change multiple ones

### ISSUE THREAD

**Issue by drager** [mantinedev/mantine#1790]
### What package has an issue

@mantine/form

### Describe the bug

See linked codesandbox: https://codesandbox.io/s/elated-sky-vfvddx?file=/src/App.js:0-1982

Fill a value in age and it will change for both inputs.

### In which browser did the problem occur

Firefox

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/elated-sky-vfvddx?file=/src/App.js:0-1982

### Do you know how to fix the issue

Instead of doing using `initialPerson` directly we need to spread the value to create a new object:

```ts
const initialPerson = {
  name: "",
  active: false,
  key: randomId(),
  nested: { age: 0 },
};

const form = useForm({
  initialValues: {
    employees: [{ ...initialPerson}],
    people: [{ ...initialPerson}],
  },
});
```

However, this was not the case in V4 and is a bit cumbersome... Also, this will not solve the issue for nested `age` part. So updating that would change both inputs even with the code above.

Doing this would work though:

```ts
const initialPerson = {
  name: "",
  active: false,
  key: randomId(),
  nested: { age: 0 },
};

const form = useForm({
  initialValues: {
    employees: [{ ...initialPerson, nested: { age: 0 } }],
    people: [{ ...initialPerson, nested: { age: 0 } }],
  },
});
```

_No response_

**Comment by rtivital** [comment]
It is expected behavior – use-form hook does not clone the initial values, if you need this you need to clone them on your side, for example with https://www.npmjs.com/package/lodash.clonedeep
