### ISSUE TITLE
TimeInput field disabled state background is different color

### ISSUE THREAD

**Issue by hammo92** [mantinedev/mantine#1795]
### What package has an issue

@mantine/dates

### Describe the bug

When set to disabled the background of the TimeInput component is a different color to other disabled input components.

### In which browser did the problem occur

Firefox, Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/lively-flower-7skwwb?file=/src/App.js

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Opacity for TimeInput is being set on Wrapper and Component so opacity is half the expected 0.6 value. Remove opacity from the TimeInput wrapper

**Comment by khobiziilyes** [comment]
Did you fill a PR or should I do it instead?

**Comment by hammo92** [comment]
Apologies, I've been away. I'll fill a PR

**Comment by rtivital** [comment]
Fixed in 5.0
