### ISSUE TITLE
[V5] Update @radix-ui dependencies for react18

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#1808]
### What package has an issue

@mantine/core

### Describe the bug

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/18473137/179476908-ff5c66eb-605f-4ddd-99da-b680c6fc4ffa.png">

But for now @radix-ui packages has correct settled per deeps, for example [this one](https://github.com/radix-ui/primitives/blob/main/packages/react/scroll-area/package.json#L34)

### In which browser did the problem occur

All

**Comment by rtivital** [comment]
The packages are updated when next version is released, I do not see much point in updating to the version that is not released yet.
