### ISSUE TITLE
allowLevelChange not respected

### ISSUE THREAD

**Issue by rfdrake27** [mantinedev/mantine#1812]
### What package has an issue

@mantine/dates

### Describe the bug

When allowLevelChange is set to false, and the initialLevel is set to month, the level still changes to days when a month is selected.

```
function Demo() {
  return <Calendar allowLevelChange={false} initialLevel='month' />;
}
```

With this combination of props, I would expect the calendar to select the month immediately when the user clicks a month. 

### In which browser did the problem occur

Edge 103

**Comment by khobiziilyes** [comment]
Already started working on this issue.

**Comment by rfdrake27** [comment]
Yes. 
My use case is that the user is presented with the "month" picker. Once they click the month, the input will blur, and show the value as the first of that month. 

So as an example, the user clicks "July" on the calendar. It blurs. The value in the input is "July 1st, 2022" (or however the format prop is configured). 
Hypothetically, if the calendar were set to the following props:
`<Calendar allowLevelChange={false} initialLevel='year' />`

If the user selects "2022", I would expect that the calendar will select the date value to "Jan 1st, 2022".  

Presently those two examples are not possible with the calendar picker. Even with the allowLevelChange prop set to false, the calendar will continue changing levels down until the user is required to select a day.

**Comment by rtivital** [comment]
DatePicker does not support this option – it is designed to pick dates, not months. We are not planning to add month picker any time soon.
