### ISSUE TITLE
Provide a way to style modals from @mantine/modals

### ISSUE THREAD

**Issue by arunpdl** [mantinedev/mantine#1817]
### What package has an issue

@mantine/modals

### Describe the bug

I can't seem to find anything on the docs regarding the styling of the modals created by using useModals hook.

I'm currently triggering the modals as shown:

```
 const modals = useModals();

  const openModal = () => {
    modals.openModal({
      title: `Modal`,
      children: <ModalContent />,
      centered: true,
    });
  };

```

Is there a way set the styles of the modal like width, height, etc?

### In which browser did the problem occur

Chrome, Firefox, 

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
You can use any Modal component props in `openModal` function
