### ISSUE TITLE
NumberInput +/- buttons get stuck if given a min

### ISSUE THREAD

**Issue by gabrielnvian** [mantinedev/mantine#1820]
### What package has an issue

@mantine/core

### Describe the bug

NumberInput works fine, I can increase and decrease the value no problem.

However, when I add a min={0} parameter, I'm only able to increase the value.

I can update the field by manually inputting 0 

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/compassionate-euler-r27efl?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
You are mixing controlled and uncontrolled input. For your example to work, either change `value` to `defaultValue` or make `onChange` handler change actual value. 

https://codesandbox.io/s/nameless-leaf-7z04dv?file=/src/App.tsx
