### ISSUE TITLE
RichTextEditor: TypeError: Cannot read properties of null (reading 'index')

### ISSUE THREAD

**Issue by abhijhacodes** [mantinedev/mantine#1824]
### What package has an issue

@mantine/rte

### Describe the bug

<strong>I'm using the latest version of all mantine packages.</strong> <br/>
But getting `TypeError: Cannot read properties of null (reading 'index')` when using list (ordered and unordered both) in Rich Text Editor. <br/>
I've gone through all the previous issues in this project but couldn't find a solution, this just doesn't seem to work with `Toolbar.list`
Rest everything is working completely fine, just anyone please tell me how to fix this

![rteerror](https://user-images.githubusercontent.com/77770628/179991079-1b4d121f-a491-4672-92b0-975ddbaf86eb.png)

### In which browser did the problem occur

Chrome, Brave, Firefox

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

No idea

**Comment by NithinSK04** [comment]
Even I'm facing the same issue

**Comment by binoy638** [comment]
Yeah, facing the same issue.

**Comment by rtivital** [comment]
The issue happens only in with react strict mode, disable strict mode to fix it.
