### ISSUE TITLE
@mantine-core's Table verticalSpacing non-operational if there's a global spacing theme

### ISSUE THREAD

**Issue by aready87** [mantinedev/mantine#1832]
### What package has an issue

@mantine/core

### Describe the bug

If there is a global theme for spacing, Table component's verticalSpacing no longer applies, UNLESS horizontalSpacing is assigned a value other than "xs". If horizontalSpacing is assigned a value besides "xs", verticalSpacing overrides the global theme (as it should).

Expectation: verticalSpacing value should apply override the global theme spacing even without horizontalSpacing is applied.

### In which browser did the problem occur

Chrome and Firefox

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/elastic-wind-t35912

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 5.1.5, thanks for reporting!
