### ISSUE TITLE
`useColorScheme` reference inside state isn't working as expected.

### ISSUE THREAD

**Issue by thevipinmishra** [mantinedev/mantine#1838]
I don't know know if this belongs in the Issues section or discussions, sorry!

I'm managing a state for the Color scheme and toggling later in my app to handle the dark/light mode.

But setting the reference of useColorScheme in a state is not working as expected.

![IMG_20220723_093505_558.png](https://user-images.githubusercontent.com/52159805/180591085-0a85bc56-8a74-4138-95d2-a2f4e13de8f9.png)

**Comment by rtivital** [comment]
Once your `theme` state is initialized, its value is not changed unless you call `setTheme` function. `useColorScheme` hook is always initialized with `light` value and when `window` object is available value changes to actual color scheme.

**Comment by SV96** [comment]
Same issue while i have tried to put colorScheme in state.When value of state was check it was wrong.

**Comment by yumemi-omi** [comment]
I followed [the documentation](https://mantine.dev/guides/dark-theme/#detect-user-preferred-color-scheme) to implement it, but I got the same result as the issue. After adding the following code, it worked as expected.

```tsx
 useEffect(() => {
    setColorScheme(preferredColorScheme);
  }, [setColorScheme, preferredColorScheme]);
```
