### ISSUE TITLE
ColorInput closes the parent Popover

### ISSUE THREAD

**Issue by shaileshshivam** [mantinedev/mantine#1847]
### What package has an issue

@mantine/core

### Describe the bug

`ColorInput` on colour selection closes the parent `Popover`

https://user-images.githubusercontent.com/75574368/180703659-343a3c93-0fb6-4097-aa8e-9dbe10f983e9.mov

### In which browser did the problem occur

Brave

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hopeful-boyd-mem994?file=/src/App.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
You need to add `withinPortal={false}` to ColorInput:

- https://v4.mantine.dev/core/popover/#usage-with-other-overlays
- https://codesandbox.io/s/modest-greider-o6oejx?file=/src/App.tsx
