### ISSUE TITLE
5.0.0 Release Link on GitHub is broken

### ISSUE THREAD

**Issue by dunklesToast** [mantinedev/mantine#1853]
### Link to the page where something nasty is located

https://mantine.dev/changelog/5.0.0/

### Exact quote of what is wrong

The first link on the [5.0.0 release on GitHub](https://github.com/mantinedev/mantine/releases/tag/5.0.0) redirects to an invalid URL:

Current:
https://mantine.dev/changelog/5.0.0/

Expected:
https://mantine.dev/changelog/5-0-0/

If you could quickly [edit](https://github.com/mantinedev/mantine/releases/edit/5.0.0) the release's description 👀 

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
Thanks for reporting, the issue is fixed
