### ISSUE TITLE
Looks like Popover’s onBlurCapture, onFocusCapture and target props have been deprecated

### ISSUE THREAD

**Issue by sunknudsen** [mantinedev/mantine#1855]
### What package has an issue

@mantine/core

### Describe the bug

This is not mentioned in https://mantine.dev/changelog/5-0-0/#popover and breaks password strength example from 4.2.0.

How can one replicate password strength example now? Thanks for helping out!

### In which browser did the problem occur

Firefox

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
You can find strength meter example in Popover documentation – https://mantine.dev/core/popover/

**Comment by sunknudsen** [comment]
Missed updated example… thanks for helping out @rtivital  and kudos for push to v5. 🙌
