### ISSUE TITLE
FileInput and form onSubmit

### ISSUE THREAD

**Issue by RicardoValero95** [mantinedev/mantine#1856]
### What package has an issue

@mantine/core

### Describe the bug

The `FileInput` calls the `onSubmit` when clicking it
![Jul-25-2022 10-30-09](https://user-images.githubusercontent.com/55701657/180817419-dfb1edf7-3553-4cc0-9a3f-9f81f5073e45.gif)

### In which browser did the problem occur

Safari, Edge

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-fileinput-form-issue-z4mk7o

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I believe that `FileInput` uses a `FileButton` which may be responsible for firing the submit

**Comment by D3kion** [comment]
Feels like #1854 is breaks cuz this problem

**Comment by rtivital** [comment]
Fixed in 5.0.2
