### ISSUE TITLE
Error on Tabs onTabChange prop.

### ISSUE THREAD

**Issue by BinDohry** [mantinedev/mantine#1862]
### What package has an issue

@mantine/core

### Describe the bug

```
Type 'Dispatch<SetStateAction<string>>' is not assignable to type '(tabIndex: number, tabKey?: string | undefined) => void'.
  Types of parameters 'value' and 'tabIndex' are incompatible.
    Type 'number' is not assignable to type 'SetStateAction<string>'.ts(2322)
Tabs.d.ts(22, 5): The expected type comes from property 'onTabChange' which is declared here on type 'IntrinsicAttributes & TabsProps'
```

### In which browser did the problem occur

macOS Edge

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/gallant-waterfall-zfi35r?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by pkro** [comment]
If anyone stumbles upon this, I had the same problem when putting the tab state in a hook, and even using the solution above didn't help as typescript just knows that the returned array elements are string or function and refuses to call setActiveTab as it could also be a string. 

Adding `as const` to the returned array fixed that.

This post cleared it up:

https://kentcdodds.com/blog/wrapping-react-use-state-with-type-script

The hook:
    
    export default function useTabNavigation(basePath: string, defaultTabId: string) {
        const navigate = useNavigate();
        type paramType = {
            tabId: string;
        };
    
        const {tabId} = useParams<paramType>();
    
        const [activeTab, setActiveTab] = useState(tabId ?? defaultTabId);
    
        const mySetActiveTab = (tab: string) => setActiveTab(tab);
    
        useEffect(() => {
            navigate(`/${basePath}/${activeTab}`);
        }, [activeTab, basePath, navigate]);
    
        return [activeTab, mySetActiveTab] as const; // important, see https://kentcdodds.com/blog/wrapping-react-use-state-with-type-script
    }

Usage in tab component:
    
    const [activeTab, setActiveTab] = useTabNavigation('users', 'personals');
    // ...
    <Tabs variant="outline" className={styles.tabs} value={activeTab} onTabChange={setActiveTab}>
