### ISSUE TITLE
MediaQuery doesnot work when inner child has display grid

### ISSUE THREAD

**Issue by suparthghimire** [mantinedev/mantine#1863]
### What package has an issue

@mantine/core

### Describe the bug

I am using Tailwind along with Mantine. 
The code Snippet is as follows:
```ts
 <Center className="w-full">
      <div className="flex h-full w-full">
        <Box className="grid w-full">
          <Center>
            <h1 className="font-bold">Part 1</h1>
          </Center>
        </Box>
        <MediaQuery smallerThan="sm" styles={{ display: "none" }}>
          <Center className="grid w-full">
            <Blockquote>Part 2</Blockquote>
          </Center>
        </MediaQuery>
      </div>
    </Center>
```
This should make the Entirity of M<Center/> component for "Part 2" display none, which it doesnot.

### In which browser did the problem occur

Chrome, Firefox

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
You are overriding Mantine styles with tailwind:
1. You set `@media (max-width: 755px) { display: none }` styles
2. Then you set `display: grid` styles which override Mantine styles

If you want Mantine styles to override tailwind you can configure emotion cache – https://mantine.dev/theming/emotion-cache/
