### ISSUE TITLE
Allow to remove default padding top for inputs group

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#1864]
### What package has an issue

@mantine/core

### Describe the bug

https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Checkbox/CheckboxGroup/InputsGroup.tsx#L17

Ho to remove / override this padding?
In my case I use radio.group and checkbox.group and this padding is redundant.
Please, fix this or give an option to disable it locally (override with styles)

### In which browser did the problem occur

Chrome

**Comment by Cararr** [comment]
Padding top comes from Stack comp which is used for groups. Try adding default class name for Stack root with p0.

**Comment by rtivital** [comment]
Fixed in 5.0.2, use `offest` prop.
