### ISSUE TITLE
Menu onChange and onClose not trigger  (5.0.0)

### ISSUE THREAD

**Issue by mthongkerd** [mantinedev/mantine#1865]
### What package has an issue

@mantine/core

### onClose: 

Menu doesn't trigger `onClose` when click on the outside of the dropdown area. Although It does trigger when you click on one of the `Menu.Item`s or the `Menu.Target` component.

### onChange: 

Menu doesn't trigger `onChange` at all.

### In which browser did the problem occur

Electron, Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-5-0-0-menu-onchange-onclose-bugs-q957to?file=/src/App.js

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Fixed in 5.0.2

**Comment by mthongkerd** [comment]
That's awesome!
