### ISSUE TITLE
How to access previous documentation (4.x)

### ISSUE THREAD

**Issue by MR-Mostafa** [mantinedev/mantine#1869]
### Exact quote of what is wrong

Hello,
My project is using the previous version (v4.x) and I am not going to upgrade (because of the big break change). Is there a way to view the old document on the website visually?
It appears that the previous version of the document has been removed from the website. 😢
Thanks ❤🌹

### Are you willing to create pull request with the fix?

No

**Comment by lawff** [comment]
maybe you can clone the repo to your local, `git checkout 4.2.12 `, then run `npm run docs`

**Comment by MR-Mostafa** [comment]
@lawff 
This is true, but I develop on a variety of environments, so it's harder for me.
It would have been better if we could access the old version of the document

**Comment by sunknudsen** [comment]
@MR-Mostafa Is [this](https://v4.mantine.dev/) what you are looking for?

**Comment by MR-Mostafa** [comment]
@sunknudsen 
Yes, exactly.
Thanks a lot 🌹

**Comment by sunknudsen** [comment]
@MR-Mostafa Pleasure! Stumbled upon link on [Discord](https://discord.gg/eUZpPbpxb4).
