### ISSUE TITLE
NotificationsProvider zIndex not working

### ISSUE THREAD

**Issue by capelaum** [mantinedev/mantine#1877]
### What package has an issue

@mantine/notifications

### Describe the bug

The zIndex prop o NotificationsProvider does not alter the actual z-index of the notifications container wrapper, this is happening using Next v12 and React 18

```
<NotificationsProvider
  limit={5}
  position="top-right"
  autoClose={false}
  zIndex={99999}
>
```

And it doesn't matter if I change the z-index of the `mantine-Notification-root` or of the container, by the image bellow it seems a div container with prop `dir="ltr"` with `z-index: 1` is causing the issue

![image](https://user-images.githubusercontent.com/37607384/181034928-b98819f7-9ba9-40cf-906e-9780d9f5ebf4.png)

### In which browser did the problem occur

Firefox and Google Chrome

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
z-index is set correctly from version 5.0.0 – https://codesandbox.io/s/thirsty-sinoussi-hjx746?file=/src/App.tsx

<img width="518" alt="Снимок экрана 2022-07-31 в 11 07 41" src="https://user-images.githubusercontent.com/10353856/182016280-718db88d-f170-43fb-8e78-a4c3c413f356.png">
