### ISSUE TITLE
Module not found: Can't resolve 'hoist-non-react-statics'

### ISSUE THREAD

**Issue by tdotmain** [mantinedev/mantine#1878]
### What package has an issue

@mantine/core

### Describe the bug

Date: July 26th 2022, 11AM EST.
Device: MacOS M1 Apple silicon (macbook air)

package.json
```{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@emotion/react": "^11.9.3",
    "@emotion/server": "^11.4.0",
    "@mantine/carousel": "^5.0.0",
    "@mantine/core": "^5.0.0",
    "@mantine/dates": "^5.0.0",
    "@mantine/dropzone": "^5.0.0",
    "@mantine/form": "^5.0.0",
    "@mantine/hooks": "^5.0.0",
    "@mantine/modals": "^5.0.0",
    "@mantine/next": "^5.0.0",
    "@mantine/notifications": "^5.0.0",
    "@mantine/nprogress": "^5.0.0",
    "@mantine/prism": "^5.0.0",
    "@mantine/rte": "^5.0.0",
    "@mantine/spotlight": "^5.0.0",
    "dayjs": "^1.11.4",
    "embla-carousel-react": "^7.0.0-rc05",
    "hoist-non-react-statics": "^3.3.2",
    "next": "^12.2.3",
    "next-fonts": "^1.5.1",
    "react": "18.1.0",
    "react-dom": "18.1.0"
  },
  "devDependencies": {
    "@types/node": "17.0.35",
    "@types/react": "18.0.9",
    "@types/react-dom": "18.0.5",
    "typescript": "4.7.2"
  }
}
```
```
import "../styles/globals.css";
import { AppProps } from "next/app";
import Head from "next/head";
import { MantineProvider } from "@mantine/core";
// import { CustomFonts } from "../fonts/CustomFonts";

export default function App(props: AppProps) {
  const { Component, pageProps } = props;

  return (
    <>
      <Head>
        <title>Page title</title>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
      </Head>

      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
      >
        {/* <CustomFonts /> */}
        <Component {...pageProps} />
      </MantineProvider>
    </>
  );
}
```

Run: `yarn` && `yarn dev`

Result:
```
warn  - Port 3001 is in use, trying 3002 instead.
ready - started server on 0.0.0.0:3002, url: http://localhost:3002
error - ./node_modules/@emotion/react/_isolated-hnrs/dist/emotion-react-_isolated-hnrs.browser.esm.js:1:0
Module not found: Can't resolve 'hoist-non-react-statics'

Import trace for requested module:
./node_modules/@emotion/react/dist/emotion-react.browser.esm.js
./node_modules/@mantine/styles/esm/index.js
./node_modules/@mantine/core/esm/index.js
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found
```

Attempted on node.js version v16 and v14, same result.
**Downloading the mantine-next-template has the same result as attempting to install to a custom next.js repo.**

### In which browser did the problem occur

Firefox

### If possible, please include a link to a codesandbox with the reproduced problem

TBD

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
try removing yarn.lock and node_modules, then install dependencies

**Comment by tdotmain** [comment]
> 

<img width="812" alt="image" src="https://user-images.githubusercontent.com/72108746/181048839-75ff4585-6d9f-4fd7-97aa-34ca780c9277.png">

I've attempted that, same result :(

**Comment by tdotmain** [comment]
Running `yarn add hoist-non-react-statics` does not resolve this issue.
It's been added to my package.json as noted in the original bug report.
`"hoist-non-react-statics": "^3.3.2",`

**Comment by rtivital** [comment]
We provide a template for Next.js, you can use it as reference. Something might be wrong with your setup or installation process – I do not think that I can provide any further assistance.

**Comment by tdotmain** [comment]
> We provide a template for Next.js, you can use it as reference. Something might be wrong with your setup or installation process – I do not think that I can provide any further assistance.

What version of node.js are you using?

The template code had the same result when copying into a fresh repo.

**Comment by rtivital** [comment]
v16.13.2
