### ISSUE TITLE
closeOnEscape and closeOnClickOutside do not trigger onClose prop for Menu component

### ISSUE THREAD

**Issue by maybesmurf** [mantinedev/mantine#1879]
### What package has an issue

@mantine/core

### Describe the bug

Title says it all

### In which browser did the problem occur

All browsers

**Comment by Cararr** [comment]
V5 made some improvements but for Menu imo it's step behind, controlled Menu is useless with this bug. Shame size prop was removed too.

**Comment by rtivital** [comment]
`size` prop was renamed to `width`

**Comment by Cararr** [comment]
> `size` prop was renamed to `width`

Thanks, missed that change.

**Comment by rtivital** [comment]
Fixed in 5.0.2
