### ISSUE TITLE
Popover wrong z-index while transitioning

### ISSUE THREAD

**Issue by dan-lee** [mantinedev/mantine#188]
I am seeing an issue with the `Popover` component:

While the component is transitioning it seems like the `z-index` seems to be lower than some other components (in this case `Button` and `Switch`).

**CodeSandbox**: https://codesandbox.io/s/aged-resonance-z3q2q

**Video**:

https://user-images.githubusercontent.com/571589/127624901-6986066b-3a65-4556-a4fc-a4d4453bc3d2.mov

**Comment by rtivital** [comment]
Hi @dan-lee, thanks for detailed report and demo, this will be fixed in next minor release (2.2.0)

**Comment by rtivital** [comment]
Fixed in [2.1.5](https://github.com/mantinedev/mantine/releases/tag/2.1.5)

**Comment by dan-lee** [comment]
Thanks a lot, it works great now! :)
