### ISSUE TITLE
ActionIcon disabled state while in "transparent" variant still shows background

### ISSUE THREAD

**Issue by eliranbenishai** [mantinedev/mantine#1883]
### What package has an issue

@mantine/core

### Describe the bug

ActionIcon disabled state while in "transparent" variant still shows the predetermined background color. Also styling the disabled state with `classNames` (which is vastly preferrable to me since I'm using Tailwind) became confusingly difficult since v5. The `emotion` class takes precedence, keeping the background in its predetermined color.

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

Yes

### Possible fix

Reinstate the `disabled` option in `classNames`? Or maybe make the `transparent` variant truly transparent?

**Comment by rtivital** [comment]
Fixed in 5.0.3
