### ISSUE TITLE
[docs(@mantine/core)] links to component source code are broken

### ISSUE THREAD

**Issue by BWsix** [mantinedev/mantine#1886]
### Link to the page where something nasty is located

All pages related to @mantine/core

### Exact quote of what is wrong

This commit ([Remove redundunt components folder](https://github.com/mantinedev/mantine/commit/775aa406238d4e76c871f69aab0bbba542cb6734)) changes the folder structure but there's no corresponding changes made to the docs, so all `View Source Code` links break.
Here's an example: https://mantine.dev/core/app-shell/
I'm willing to fix all the broken links in [this folder](https://github.com/mantinedev/mantine/tree/master/docs/src/docs/core) if that sounds good to you.

### Are you willing to create pull request with the fix?

Yes

**Comment by mattrunyon** [comment]
Should be fixed by #1906, but I'm still seeing incorrect links on the live docs
