### ISSUE TITLE
minDate of DatePicker not working in safari browser

### ISSUE THREAD

**Issue by cecil-work** [mantinedev/mantine#1887]
### Exact quote of what is wrong

I set the minDate to 2022-01-01, which is ok in the chrome browser, but in the safari browser, the month cant be selected, and the months are all disabled.

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
Works as expected in Safari on codesandbox – https://codesandbox.io/s/practical-leftpad-42hxew?file=/src/App.tsx

**Comment by rtivital** [comment]
Feel free to reopen the issue or reach out on Discord if you have any question
