### ISSUE TITLE
Modals dont work with an id

### ISSUE THREAD

**Issue by PringlePot** [mantinedev/mantine#1889]
### What package has an issue

@mantine/modals

### Describe the bug

When creating a modal with an id, it will error

### In which browser did the problem occur

Google Chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by mmahalwy** [comment]
yeah same problem here as well

**Comment by mmahalwy** [comment]
something weird happening with use ref:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/3749095/181853105-d44e6861-fea1-4a31-bc93-1af7cb2e3b58.png">

**Comment by rtivital** [comment]
Fixed in 5.0.2, it is now required to use `modalId` instead of `id`
