### ISSUE TITLE
Group child styles not applied to external components

### ISSUE THREAD

**Issue by nowlena** [mantinedev/mantine#189]
There appears to be an issue with applying styles to external components.

I don't know if this is an issue with `mantine`, `react-jss`, or some other library being utilized.

Example of "mantine-group-child" styles not being applied as expected:
 - https://codesandbox.io/embed/sweet-shtern-slk2z?fontsize=14&hidenavigation=1&theme=dark
 - ie. our mapped links don't have their margins

**Comment by rtivital** [comment]
Hi @nowlena Group component relies on `className` property being handled by child components/elements. If you add it to your NavLink component it will work fine – https://codesandbox.io/s/goofy-field-16kcz?file=/src/App.js

You can find more information about Group component here – https://mantine.dev/core/group/
