### ISSUE TITLE
Huge bundle size of @mantine/form at version 5.0.0

### ISSUE THREAD

**Issue by theMasix** [mantinedev/mantine#1890]
### What package has an issue

@mantine/form

### Describe the bug

Hi, Thanks for your great work.

It seems `lodash.clonedeep` has been ruined the bundle size of `@mantine/form@5.0.0`. [Link from bundlephobia](https://bundlephobia.com/package/@mantine/form@5.0.0)

<img width="1304" alt="Screen Shot 2022-07-27 at 16 02 17" src="https://user-images.githubusercontent.com/22872117/181236676-7911b84d-4d9c-431a-bc57-a0c1d6984128.png">

### In which browser did the problem occur

*

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Yep, seems like we need to implement our own clonedeep function

**Comment by yudai-nkt** [comment]
FWIW, [klona](https://www.npmjs.com/package/klona) is a tiny and performant alternative for deep cloning.

**Comment by rtivital** [comment]
Fixed in 5.0.2, migrated to klona, thanks @yudai-nkt!
