### ISSUE TITLE
useForm schema option replaced by validate without warning

### ISSUE THREAD

**Issue by mlarcher** [mantinedev/mantine#1896]
### Link to the page where something nasty is located

https://github.com/mantinedev/mantine/releases/tag/5.0.0

### Exact quote of what is wrong

the `@mantine/form changes` section doesn't talk at all about a sneaky breaking change :

in 4.2.12 docs:
```
validate (optional) – an object with validation rules or a validation function that receives form values as an argument and returns object with validation errors
schema (optional) – [zod](https://www.npmjs.com/package/zod), [joi](https://www.npmjs.com/package/joi) or [yup](https://www.npmjs.com/package/yup) validation schema, if provided validate is ignored
```

in 5.0.0 docs:
```
validate – an object with validation rules, [schema](https://github.com/mantinedev/mantine/blob/5.0.0/form/schema) or a validation function that receives form values as an argument and returns object with validation errors
```

Also, passing the schema via the `schema` option doesn't raise a warning, it just lets the form go unvalidated.
It took me a while to figure out what what going on !

replacing `schema: joiResolver(schema)` with `validate: joiResolver(schema)` fixed the validation process successfully.

**Comment by rtivital** [comment]
Fixed in 5.0.2
