### ISSUE TITLE
Calendar's onMonthChange prop is not called anymore

### ISSUE THREAD

**Issue by Stouffi** [mantinedev/mantine#1898]
### What package has an issue

@mantine/dates

### Describe the bug

since v5 Calendar's onMonthChange prop is not called anymore.
Here is the repro codesandbox : https://codesandbox.io/s/repro-onmonthchange-t9nxio

Below is the same codesandbox with v4.2.12
https://codesandbox.io/s/repro-onmonthchange-4-x-qz2690

### In which browser did the problem occur

Any

### If possible, please include a link to a codesandbox with the reproduced problem

 Here is the repro codesandbox : https://codesandbox.io/s/repro-onmonthchange-t9nxio

**Comment by rtivital** [comment]
Fixed in 5.0.2
