### ISSUE TITLE
/form/lists is now 404 in the docs website

### ISSUE THREAD

**Issue by youssefsiam38** [mantinedev/mantine#1901]
This page was a bookmark in my browser and when navigated to it I found this beautiful 404 page.

![screencapture-mantine-dev-form-lists-2022-07-27-23_08_42](https://user-images.githubusercontent.com/54387513/181372654-cd2fb64b-a430-438c-8eec-c5db7e772e39.png)

**Comment by rtivital** [comment]
It is expected, the page was removed. You can find updated page here – https://mantine.dev/form/nested/
