### ISSUE TITLE
Missing info in Changelog for v5

### ISSUE THREAD

**Issue by ubeid** [mantinedev/mantine#1903]
### Link to the page where something nasty is located

~~https://github.com/mantinedev/mantine/releases~~
https://mantine.dev/changelog/5-0-0/

### Exact quote of what is wrong

Changelog doesn't mention that Button component Styles API no longer support variants. 

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
Fixed in 5.0.2
