### ISSUE TITLE
`useDidUpdate` mutes errors 

### ISSUE THREAD

**Issue by cliffoo** [mantinedev/mantine#1904]
Consider this:

```tsx
useDidUpdate(() => {
  return new Promise((a, b) => void a(null));
}, []);
```

There is an error, as an effect callback can't be a promise. But the error is muted, and it only appears when you replace `useDidUpdate` with `useEffect`:

<img width="596" alt="Screen Shot 2022-07-28 at 06 40 40" src="https://user-images.githubusercontent.com/41348973/181384797-e89e2369-a96e-4466-9b28-98a726ced738.png">

Take a look at another example:
```tsx
const [a,] = useState();
useEffect(() => {
  console.log(a);
}, [])
```
You'd get `react-hooks/exhaustive-deps` with eslint configured properly. But it's `No issues found` written happily in green if you switch it out for `useDidUpdate` ;)

**Comment by rtivital** [comment]
Fixed in 5.0.2
