### ISSUE TITLE
NumberInput parser/formatter doesn't work well with backspace.

### ISSUE THREAD

**Issue by arel** [mantinedev/mantine#1905]
### What package has an issue

@mantine/core

### Describe the bug

When using the parser/formatter feature of NumberInput, the backspace key doesn't work correctly when editing a value.

This is reproducible even on the documentation site.

For instance, from the example given here: https://mantine.dev/core/number-input/#parser-and-formatter, type in the number: $1,234. Then move the cursor between the 2 and the 3 and try to delete the first two digits. After deleting one character, the cursor moves to the end of the number.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/number-input/#parser-and-formatter

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

One possible solution may be to not to format the string when deleting and always format on blur.

**Comment by rtivital** [comment]
Fixed in 5.0.2
