### ISSUE TITLE
Where I can check v4 document?

### ISSUE THREAD

**Issue by jaehong-hwang** [mantinedev/mantine#1907]
### Link to the page where something nasty is located

https://mantine.dev/

### Exact quote of what is wrong

Hi! I need help someone..  
I'm using mantine v4, but I can found only v5 document in web site  
Can I found v4 document?

I was checked  v5.0.0 button but that was redirect to release log..
<img width="197" alt="image" src="https://user-images.githubusercontent.com/10570004/181444969-b92339a9-284b-4fd1-9095-6f7427716017.png">

**Comment by rtivital** [comment]
https://mantine.dev/pages/about/#previous-versions-documentation
