### ISSUE TITLE
docs: Box Component props nothing found

### ISSUE THREAD

**Issue by ryuhangyeong** [mantinedev/mantine#1911]
### Link to the page where something nasty is located

https://mantine.dev/core/box/?t=props

### Exact quote of what is wrong

![image](https://user-images.githubusercontent.com/27342882/181487613-d99e05e2-a1e6-4bdc-a306-7a27c6254b69.png)

## Description

I'm stepping through the code through components and documentation to understand mantine.

Looking through the documentation, I found that the Props information of the Box component was empty.

Is this intentional? I thought so.

If not, I'll post a PR by adding the props description for the children props.

## Work Target

```tsx
// mantine-core/src/Box.tsx
export interface BoxProps extends DefaultProps {
  // here
  children?: React.ReactNode;
}
```

## Etc

If you don't need the work, please close the issue!

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Fixed in 5.0.2
