### ISSUE TITLE
All Component that uses use-id can't be rendered in next.js stack.

### ISSUE THREAD

**Issue by rasyidf** [mantinedev/mantine#1913]
### What package has an issue

@mantine/core

### Describe the bug

I tried to use next js 12 with mantine. but it shows error like this
![image](https://user-images.githubusercontent.com/28984914/181519772-cecfc913-bd3a-4304-8f8d-fc5490a5edf7.png)

### In which browser did the problem occur

edge, firefox, chrome

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Update node.js to 16+ version

**Comment by rasyidf** [comment]
noted.
