### ISSUE TITLE
Styles API on Switch component doesn't work

### ISSUE THREAD

**Issue by mateuszdziuba** [mantinedev/mantine#1914]
### What package has an issue

@mantine/core

### Describe the bug

Styles API on Switch component doesn't render styles prop into css, it's rendered to html as object.

### In which browser did the problem occur

chrome, firefox

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/dry-grass-cuh9yq?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 5.0.2
