### ISSUE TITLE
DateRangePicker breaks inside mantine form

### ISSUE THREAD

**Issue by mateuszdziuba** [mantinedev/mantine#1916]
### What package has an issue

@mantine/core

### Describe the bug

When using DateRangePicker with useForm hook getInputProps it breaks, showing error with getFullYear comparision.

### In which browser did the problem occur

chrome, firefox

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/loving-wescoff-q5x8n0?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
You've provided incorrect value – https://codesandbox.io/s/hungry-marco-l5vu6g?file=/src/App.js

**Comment by mateuszdziuba** [comment]
You are right, sorry for confusion, could you please take a look at this one https://github.com/mantinedev/mantine/issues/1811
