### ISSUE TITLE
Rich Text Edtior video embed popover location is off

### ISSUE THREAD

**Issue by juliuslissau** [mantinedev/mantine#1924]
I guess it happened in the v5 update. It happens in the docs, and on my website too. Click on the video embed button on the editor: https://mantine.dev/others/rte/#images-and-videos-embeds 

(Embedding a video also loads a 404 page instead of the video (also happens in the docs), but the RichTextEditor value seems correct, so that's not necessarily a deal breaker, but would be nice if the video could load).

Tested on both Chrome and Firefox on macOS.

![example](https://user-images.githubusercontent.com/71498286/181722581-68e26575-177f-4573-91cd-88c31bcdd9e7.png)

![example2](https://user-images.githubusercontent.com/71498286/181723284-56550a52-0aa1-45c9-9ee4-48be49ec2ba3.png)

**Comment by rtivital** [comment]
It works fine for me

https://user-images.githubusercontent.com/10353856/181724359-e3e829e0-fc95-4850-94eb-9f35d48aa43e.mov

**Comment by juliuslissau** [comment]
Ah alright I noticed from your link that I shouldn't insert the whole iframe code, just the video link, so that was the issue for the 404 page. 

And I see that the position is based on the cursor from your video as well, I guess I just expected it to be below the button, and I always had my cursor on the side. 

Thanks for the clarification
