### ISSUE TITLE
How to pass classNames to `Menu`

### ISSUE THREAD

**Issue by imranbarbhuiya** [mantinedev/mantine#1934]
### Exact quote of what is wrong

in v4, I was using 

```ts
<Menu
				trigger="hover"
				withArrow
				classNames={{
					root: 'flex items-center',
					body: 'mt-1',
				}}
			>
...other components
</Menu>
```
but in v5 I'm getting ts error
```bash
Type '{ root: string; body: string; }' is not assignable to type 'Partial<Record<MenuStylesNames, string>>'.
  Object literal may only specify known properties, and 'root' does not exist in type 'Partial<Record<MenuStylesNames, string>>'.
```
and it's not applying the class names too.

In v5 migration guide, there is no mention of `classNames` changes for `Menu` components so I'm not able to find a solution for this. What changes do I need to apply for it to work like before?

**Comment by rtivital** [comment]
Menu styles api selectors were changed in 5.0. It does not accept `root` selector anymore. You need to add those classes directly to child component:

```tsx
<Menu.Target>
  <Element classsName="your-root-class-here" />
</Menu.Target>
```

**Comment by imranbarbhuiya** [comment]
ok, thanks. Also are there any changes in menu item paddings? because 

previous menu item without any custom style 
![image](https://user-images.githubusercontent.com/74945038/181908420-6c38ecaf-2057-4ca3-b12c-c5a65bdc35c1.png)


now

![image](https://user-images.githubusercontent.com/74945038/181908408-2d03e5ed-14ca-45c2-a6a4-86495bcdafd8.png)

**Comment by rtivital** [comment]
Default Menu.Item styles were not changed, it looks the same on mantine.dev and v4.mantine.dev
