### ISSUE TITLE
Safari: Animated Skeleton does not have border-radius

### ISSUE THREAD

**Issue by pang0103** [mantinedev/mantine#1937]
What package has an issue
@mantine/core

Describe the bug
Using `<Skeleton circle height={300} />` can shows a circle skeleton in Chrome. But in Safari it became 300x300 square

In which browser did the problem occur
Safari 15.5

**Comment by rtivital** [comment]
Example of issue

https://user-images.githubusercontent.com/10353856/181927576-d119d0f4-461a-4ae6-9910-a35a6b99bed3.mov

**Comment by rahulgpt** [comment]
Hey, I can work on this issue

**Comment by rtivital** [comment]
Fixed in 5.0.3
