### ISSUE TITLE
Card padding is applied after styles added via createStyles

### ISSUE THREAD

**Issue by TheRarita** [mantinedev/mantine#1944]
### What package has an issue

@mantine/core

### Describe the bug

The same issue as was with [Menu](https://github.com/mantinedev/mantine/issues/1852) (solved in 5.0.2), padding added to Card via className is applied before the default value.

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
It is expected behavior. Card.Section uses `p` prop to calculate negative margins. If you do not need Card.Section component, use Paper instead.
