### ISSUE TITLE
openConfirmModal from Modal

### ISSUE THREAD

**Issue by gius** [mantinedev/mantine#1945]
### What package has an issue

@mantine/modals

### Describe the bug

When calling `openConfirmModal` from already opened `<Modal>` (e.g., you use `<Modal>` as an item detail screen and want to display a confirmation dialog when closing without saving), the confirmation dialog is displayed **below** the already opened `Modal`.

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-modal-bug-t56v8c

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

A quick workaround is to set `zIndex={190}` on the `Modal`.

I guess a solution could be if ModalsProvider rendered its dialogs after any other contents, including opened modals.

**Comment by rtivital** [comment]
You can set all Modal props with `openConfirmModal` function, including `zIndex`

https://codesandbox.io/s/mantine-modal-bug-forked-s3x6e7?file=/src/Demonstrator.tsx
