### ISSUE TITLE
React ^17 peer from embla-carousel-react

### ISSUE THREAD

**Issue by daszybak** [mantinedev/mantine#1949]
### What package has an issue

@mantine/carousel

### Describe the bug

Could not resolve dependency:
peer react@"^17.0.2" from embla-carousel-react@6.2.0

peer embla-carousel-react@6.2.0 from @mantine/carousel

### What version of @mantine/hooks page do you have in package.json?

"@mantine/hooks": "^5.0.0"

**Comment by mcmxcdev** [comment]
Mantine will need to upgrade embla-carousel-react to v7 (which was just released today), then this peer dep issue will be resolved.

See more: https://github.com/davidjerleke/embla-carousel/issues/305

**Comment by AimanAlmureish** [comment]
Any updates about this?

**Comment by mcmxcdev** [comment]
Vitaly fixed it in https://github.com/mantinedev/mantine/commit/d348b1d365a145ed09e88ebe7a3ae2ab7a6c9bc2, so you can expect it to land in the next release.

**Comment by rtivital** [comment]
Fixed in 5.0.3
