### ISSUE TITLE
keydown event handler fails on gethotkeyhandler

### ISSUE THREAD

**Issue by Geczy** [mantinedev/mantine#1952]
### What package has an issue

@mantine/hooks

### Describe the bug

i want to use the usehotkeys hook but since that only works in input fields i cant, so i have to use gethotkeyhandler sadly

prefer instead if usehotkeys has a setting to enable or disable input fields like here https://react-hotkeys-hook.vercel.app/docs/api/use-hotkeys 

```js
enableOnTags: false // <-- what i need
```

but the bug is this:

```js
  document.body.addEventListener("keydown", getHotkeyHandler([
        ['mod+Enter', handleSubmit],
        ['mod+S', handleSave],
      ]));
```

>TypeError: Cannot destructure property 'altKey' of 'event' as it is undefined.

>Argument of type '(event: KeyboardEvent<HTMLElement>) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.
      Type '(event: KeyboardEvent<HTMLElement>) => void' is not assignable to type 'EventListener'.
        Types of parameters 'event' and 'evt' are incompatible.
          Type 'Event' is missing the following properties from type 'KeyboardEvent<HTMLElement>': altKey, charCode, ctrlKey, code, and 15 more.

### What version of @mantine/hooks page do you have in package.json?

4.6.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Added in 5.1.5, `getHotkeyHandler` now can be added to any dom node with `.addEventListener` – https://mantine.dev/hooks/use-hotkeys/#targeting-elements
