### ISSUE TITLE
Typescript types removed variable name

### ISSUE THREAD

**Issue by mmahalwy** [mantinedev/mantine#1956]
### What package has an issue

@mantine/modals

### Describe the bug

See example for modals:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/3749095/182210348-5e49c933-bb9e-4c40-9b15-c5ac63af3c94.png">

See example for notifications:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/3749095/182210464-8ee74a9d-f429-4e1c-a524-360f443f87ba.png">

The problem is `payload_0` is not descriptive and is a regression from v4. 

### What version of @mantine/hooks page do you have in package.json?

^5.0.2

**Comment by rtivital** [comment]
This issue is not fixable with current implementation. Also, I do not consider this to be a bug, small formatting issue.
