### ISSUE TITLE
Group component taking up more than available width.

### ISSUE THREAD

**Issue by achmurali** [mantinedev/mantine#196]
- mantine/core
- 2.2.1
- Google Chrome (92.0.4515.107) - 1920*1080
- Group Component is occupying more space than the available space due to the negative margin applied in the Group root style. - ```margin: (-1 * getSizeValue({ size: spacing, sizes: theme.spacing })) / 2```.
Example - the 404 page is having a horizontal scroll bar because of the negative margin given to Group Component.
- I believe we don't need negative margin and that could fix the mantine dev 404 page, if not lets discuss and I shall do the fix.
- Yes I am more than willing to fix the issue 😄. 

![image](https://user-images.githubusercontent.com/22786016/128623381-0001a87d-5f57-4d48-8876-fee84f89cd16.png)

**Comment by rtivital** [comment]
This is not an issue with Group component – it behaves exactly as planned. Negative margins are required as they negate positive margins of Group's child elements, without them group will have unexpected spacing on all sides.

404 page is broken because of how Gatsby handles the layout – not sure at what time this happened. You can investigate this and wrap it in Container to make it look nicer if you want.

**Comment by achmurali** [comment]
The reason I saw it as an issue with Group component and not with gatsby was because (for my screen of width 1920px) -
- The Navbar is occupying `260px` and the rest of the page should occupy the available `1660px`, but it exceeds the `1660px` width because of the negative margin hence causing a horizontal scroll bar.
- I expected a container (Group component) to occupy the available width.

**Comment by rtivital** [comment]
>The Navbar is occupying 260px and the rest of the page should occupy the available 1660px, but it exceeds the 1660px width because of the negative margin hence causing a horizontal scroll bar.

It's an issue with docs 404 page, not Group component – something's not right there, in normal circumstances Group will not cause scrollbars to appear, here is an example – https://codesandbox.io/s/mantine-template-ts-forked-qggl8?file=/src/App.tsx

**Comment by achmurali** [comment]
> The reason I saw it as an issue with Group component and not with gatsby was because (for my screen of width 1920px) -
> 
> * The Navbar is occupying `260px` and the rest of the page should occupy the available `1660px`, but it exceeds the `1660px` width because of the negative margin hence causing a horizontal scroll bar.
> * I expected a container (Group component) to occupy the available width.

Please check this example - https://codesandbox.io/s/mantine-template-ts-forked-qugr4?file=/src/App.tsx, and let me know if you see a scroll bar on viewing in full-width.

**Comment by rtivital** [comment]
Yep, I see it there, it disappears when parent has padding – https://codesandbox.io/s/mantine-template-ts-forked-6ylj1?file=/src/App.tsx

Seems like a bug with `grow` prop, not sure how this can be fixed as removing negative margin will result in extra spacing on all sides

**Comment by achmurali** [comment]
It disappears on adding padding because it negates the negative margin.

Even material-ui [container](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Container/Container.js#L45) component has internal padding or spacing, may be could consider removing that -ve margin and make that 8px spacing optional by using it via a prop type `gutter`?

**Comment by rtivital** [comment]
Group != Container, Container is designed to provide horizontal padding

**Comment by achmurali** [comment]
I shared the material-ui container to mention about the prop `disablegutter`, which also adds padding to the left and right. As, i want to work towards a solution, these are the things that come to mind to solve this issue - 
- Put the negative margin optional via a prop `disablegutter`.
- Disable margin to the left and right for the first and last child of group component.

and do let me know if you see the group component differently and suggest an appropriate solution.

**Comment by rtivital** [comment]
> Put the negative margin optional via a prop disablegutter

That can be done by setting `spacing` to 0

> Disable margin to the left and right for the first and last child of group component.

That won't work since group can be multiline when children are wrapped into second flex row (`flex-wrap` property)

**Comment by achmurali** [comment]
I find adding another explicit prop very intuitive. 
If `spacing` is set to 0, doesn't it remove the spacing between the children as well?

**Comment by rtivital** [comment]
> If spacing is set to 0, doesn't it remove the spacing between the children as well?

Yep, but there is no way to remove only negative margin and keep children spacing while keeping current behavior
