### ISSUE TITLE
Some style differences/issues with TextInput and MultiSelect

### ISSUE THREAD

**Issue by josch0** [mantinedev/mantine#1962]
### What package has an issue

@mantine/core

### Describe the bug

I use TextInput and MultiSelect together in one form. I noticed that both inputs look different.

- Placeholders have different font styles
- Inputs have different heights
- Placeholder in MultiSelect is not centered

(See Codesandbox-Example)

ScreenShot using current Edge Browser:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/104630690/182385690-cecafd66-8c24-4126-990e-fbb18d65153f.png">

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hungry-khorana-bw26vo

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by wes337** [comment]
This is caused by the `line-height: 1.15` on the `input` element. Works fine in Firefox, only visible in Chrome/Edge

**Comment by rtivital** [comment]
Thanks for investigation, it is also an issue only on Windows – works correctly in Chrome on macos
