### ISSUE TITLE
MultiSelect: Unexpected behavior with deviating values in "value" and "data"

### ISSUE THREAD

**Issue by josch0** [mantinedev/mantine#1969]
### What package has an issue

@mantine/core

### Describe the bug

If a value is set in "value" array that does not exist in "data" array, then the component behaves strangely:
- No badge for this value is displayed in the input field
- But also no placeholder is displayed (if the unknown value is the only selected value, see codesandbox)
- The value is also always contained in the onChange event.

I would expect the following behaviors:

Either (preferably) the unknown value should be ignored completely (removed from the "value" input array), or the unknown value should be included in the input field so that you can explicitly remove it with the "x" (but not add it again).

How about adding a prop for this?
("handleUnknownValuesInInput": "ignore" | "include")

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/jolly-lehmann-sir98k

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Thanks for reporting, the issue will be fixed in one of the next patches

**Comment by mcmxcdev** [comment]
This is actually similar to what I have opened as a discussion here https://github.com/mantinedev/mantine/discussions/1744

**Comment by josch0** [comment]
Hmm... Thinking about possible fixes... Including/Displaying the unknown value will be difficult if we don't have a suitable label for it in "data" anymore. One solution could be to display the raw value and give the badge a red background? To highlight it as unknown value.

Highlighting unknown values could be a good idea/feature in general.

**Comment by rtivital** [comment]
Fixed in 5.0.3

**Comment by aldenho52** [comment]
@rtivital I see it now. 

"Fixed in 5.0.3, all values that do not exist in data are no longer displayed in the input"

This is causing the issue with my project where I'm using async data from an APi call to populate the data field.
If I search `Alden` and select a user named `Alden`, then I want to search `Chris` to search a user named Chris, `Alden` wont be in the Chris search results so it'll no longer be a selected value. Is there a work around this?

**Comment by rtivital** [comment]
You need to handle this logic on your side, selected items must always be in the `data` array. You can store these values in state.
