### ISSUE TITLE
Accordion.Control and Accordion.Panel throws an error Element type is invalid

### ISSUE THREAD

**Issue by michaelsoriano** [mantinedev/mantine#1970]
### What package has an issue

@mantine/core

### Describe the bug

I get an error when using **Accordion.Control** / **Accordion.Panel** inside an Accordion.Item:

_Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in..._

I'm using version 4.2.12. To replicate, see https://codesandbox.io/s/gifted-dust-4m0ppn?file=/src/App.js - simply uncomment lines 9-10 to see the error. 

Question - if this is new to version 5 and up, what is the proper way to add control / panels inside an Accordion Item? 

Thank you.

### What version of @mantine/hooks page do you have in package.json?

4.2.12

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/gifted-dust-4m0ppn?file=/src/App.js

**Comment by rtivital** [comment]
Hi @michaelsoriano, you are using 4.x packages with 5.x documentation. You can find 4.x documentation here – https://v4.mantine.dev/

**Comment by michaelsoriano** [comment]
@rtivital  - thank you
