### ISSUE TITLE
Chip color prop broken?

### ISSUE THREAD

**Issue by xorander00** [mantinedev/mantine#1985]
### What package has an issue

@mantine/core

### Describe the bug

Chip color prop appears to not have any affect after the most recent update. After checking my own code, I looked at the docs site example and noticed it's not working there either.  
  
[Try changing the color on the Chip component](https://mantine.dev/core/chip/)

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Not sure, I just noticed and haven't had a chance to look further into it yet. Happy to provide feedback as needed though.

**Comment by rtivital** [comment]
Chip has color only when it is checked.

**Comment by xorander00** [comment]
Doh! You're right, I got Chip confused with Badge. I need sleep heh. Sorry about that. Closing issue.
