### ISSUE TITLE
wrong command in "usage with vite guide"

### ISSUE THREAD

**Issue by adamni21** [mantinedev/mantine#1992]
### Link to the page where something nasty is located

https://mantine.dev/guides/vite/

### Exact quote of what is wrong

"5. Start development server: `npm start`"
Should be: `npm run dev`.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Can you create a PR with a fix?

**Comment by adamni21** [comment]
Yes.

**Comment by adamni21** [comment]
https://github.com/mantinedev/mantine/pull/1998

**Comment by rtivital** [comment]
Fixed in 5.0.3
