### ISSUE TITLE
NumberInput formatter/parser sample behaving differently in documentation

### ISSUE THREAD

**Issue by esistgut** [mantinedev/mantine#2005]
### What package has an issue

@mantine/core

### Describe the bug

Focus the input in the Codesandbox sample, select everything with CTRL+A and type something like "1234". For some reason this is working on the documentation but doing something strange on the Codesandbox.

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/currying-darkness-fje015?file=/src/App.tsx

**Comment by esistgut** [comment]
Could be related to https://github.com/mantinedev/mantine/pull/1908

**Comment by rtivital** [comment]
Fixed in 5.0.3
