### ISSUE TITLE
When passing modalId as prop to openModal it is added to the DOM

### ISSUE THREAD

**Issue by aludvigsen** [mantinedev/mantine#2009]
### What package has an issue

@mantine/modals

### Describe the bug

When passing `modalId` as prop to `openModal()` its put on the root `<div class="mantine-Modal-root" modalId="some-id">` element, and React complains that its not recognized as a valid prop.

```
openModal({modalId: "some-id"})
```

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/weathered-dust-0weojj?file=/src/App.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Fixed in 5.0.3
