### ISSUE TITLE
Why is my select dropdown open by default while opening Drawer ?

### ISSUE THREAD

**Issue by NithinSK04** [mantinedev/mantine#2010]
### What package has an issue

@mantine/core

### Describe the bug

I've a mantine select inside my Drawer component and every-time when a sidebar open action is called the select dropdown opens up by default !. 

### What version of @mantine/hooks page do you have in package.json?

5.0.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Drawer component uses use-focus-trap hook to manage focus, it means that the first interactive element will be focused when Drawer opens. If you do not need to trap focus, you can disable it with `<Drawer trapFocus={false} />`
