### ISSUE TITLE
.reset() method ignores initialValues change

### ISSUE THREAD

**Issue by michael-khaliavski** [mantinedev/mantine#2011]
### What package has an issue

@mantine/form

### Describe the bug

Per the source code, `useForm().reset()` method is a callback with zero dependencies, however, it makes a set of initialValues. With that said, each reset will cause my form to be set with values passed during the first render. 

I'd like to have control over my initialValues when resetting the form.

What do you think? 

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Looks like callbacking this function does not add any performance boost here. So I'd suggest either remove callback at all, or put initialValues as dependency.

```
const reset = () => {
    _setValues(initialValues);
    clearErrors();
}
```

**Comment by rtivital** [comment]
It is expected behavior, initial values are not supposed to be changed.
