### ISSUE TITLE
`chevronSize` for `Accordion` doesn't increase properly

### ISSUE THREAD

**Issue by mcmxcdev** [mantinedev/mantine#2016]
### What package has an issue

@mantine/core

### Describe the bug

In a client project of mine, we want to have bigger chevron for the `Accordion`.

Increasing `chevronSize` just leads to a bigger div, but not a bigger chevron svg.

It is reproducible on the docs: https://mantine.dev/core/accordion/#usage
Decreasing the `chevronSize` works here, and it gets visually smaller, but increasing the size doesn't work.

### What version of @mantine/hooks page do you have in package.json?

^5.0.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
It is expected behavior. `chevronSize` prop does not increase the size of the icon – it increases parent container width instead.

**Comment by mcmxcdev** [comment]
Then maybe renaming it to `chevronContainerSize` would make it more obvious.

How to increase the chevron size itself?

**Comment by rtivital** [comment]
Provider your own chevron icon with desired size – https://mantine.dev/core/accordion/#change-chevron

**Comment by wowczarczyk** [comment]
I also stumbled upon this one, it is a bit counter-intuitive. I think prop called `chevronSize` should increase the size of the icon.
