### ISSUE TITLE
Set `size` in defaultProps on provider does nothing

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#2019]
### What package has an issue

@mantine/core

### Describe the bug

From docs: https://mantine.dev/core/input/#default-props-on-mantineprovider
I try:
```
    Input: {
      defaultProps: {
        size: 'xl',
        variant: 'filled',
      },
    },
```

First question:
variant is applied, but size not!
Why? How to fix that?
When I set size for specific type on input, for ex.: TextInput - it works.

Second question:
It is possible to override somehow sizes for inputs?
Now it's incapsulated [inside](https://github.com/mantinedev/mantine/blob/c7d080c2133b0196e3a8382ec6134838632c8f9a/src/mantine-core/src/Input/Input.styles.ts#L19) 

Thanks!

### What version of @mantine/hooks page do you have in package.json?

latest

**Comment by rtivital** [comment]
`size` property cannot be declared as default property of Input component. Each component that extends Input and Input.Wrapper declares its value individually. It is required for some parts of components to have correct styles, for example increment/decrement controls in NumberInput component. Unfortunately, it is not possible to configure `size` for all inputs  in one place on MantineProvider – you will need to add these props for each individual component.

**Comment by 7iomka** [comment]
> Second question:
> It is possible to override somehow sizes for inputs?

Ok.
But, how about second question?
Second question:
It is possible to override somehow `sizes` object for inputs? it's incapsulate now :(

**Comment by rtivital** [comment]
You can change Input styles (including height and padding) with styles on MantineProvider – https://mantine.dev/styles/styles-api/#inputs-styles-api-on-mantineprovider
