### ISSUE TITLE
NumberInput does not support setting selection range.

### ISSUE THREAD

**Issue by arel** [mantinedev/mantine#2024]
### What package has an issue

@mantine/core

### Describe the bug

NumberInput does not support setting the selection range via `select()` or `setSelectionRange()` even though the wrapped element is an `<input type="text" />` element.

I would expect to be able to use a ref to set the cursor position and selection range of a NumberInput. If this is the intended behavior, I would expect the documentation to mention this.

I notice that `select()` does work with TextInput components.

For example:
```javascript
import { useState, useRef } from "react";
import { MantineProvider, Space, NumberInput, TextInput } from "@mantine/core";

export default function App() {
  const numRef = useRef<HTMLInputElement>(null);
  const textRef = useRef<HTMLInputElement>(null);
  const [val, setVal] = useState<number | undefined>(1234);
  const [textVal, setTextVal] = useState<string | undefined>("1234");
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <NumberInput
        label="Fails to select all on focus (and cursor misplaced)"
        ref={numRef}
        value={val}
        onChange={setVal}
        onFocus={() => {
          const el = numRef.current;
          el?.select();
        }}
      />
      <Space h="xl" />
      <TextInput
        label="Selects all on focus"
        ref={textRef}
        value={textVal}
        onChange={(e) => setTextVal(e.currentTarget.value)}
        onFocus={() => {
          const el = textRef.current;
          el?.select();
        }}
      />
    </MantineProvider>
  );
}
```

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/focused-breeze-xj5jku?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by nmay231** [comment]
Wrapping it in `setTimeout` seems to work https://codesandbox.io/s/vigilant-shadow-2dzvzv?file=/src/App.tsx:677-718

**Comment by rtivital** [comment]
Works as expected in 5.0.3 – https://codesandbox.io/s/falling-wildflower-h1vqxk
