### ISSUE TITLE
Close Select dropdown when clicking on the input itself

### ISSUE THREAD

**Issue by Kukkimonsuta** [mantinedev/mantine#203]
Package: @mantine/core
Version: 2.2.1

When select has visible dropdown it should be able to close it clicking on the select (yellow area) again. This change would make Select and NativeSelect behave the same in that regard.

![image](https://user-images.githubusercontent.com/737093/129026968-03faf647-1cb0-41ab-9b98-ddc0e9dfe1eb.png)

**Comment by rtivital** [comment]
Will be fixed in 2.4.0, already done

**Comment by rtivital** [comment]
Released in [2.4.0](https://github.com/mantinedev/mantine/releases/tag/2.4.0)
