### ISSUE TITLE
`useViewportSize` doesn't work in mantine-next-template

### ISSUE THREAD

**Issue by 1604295917** [mantinedev/mantine#2034]
### What package has an issue

@mantine/hooks

### Describe the bug

`useViewportSize` doesn't work in mantine-next-template.

I was do as `https://mantine.dev/hooks/use-viewport-size` in `https://github.com/mantinedev/mantine-next-template`
but it's no work.

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

I'm noob...

**Comment by 1604295917** [comment]
error is https://nextjs.org/docs/messages/react-hydration-error

**Comment by rtivital** [comment]
Can you share error message that you have?

**Comment by 1604295917** [comment]
1.error:Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
2.Unhandled Runtime Error
Error: Text content does not match server-rendered HTML.
3.Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
4.Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

**Comment by rtivital** [comment]
useViewportSize hook cannot be used to manipulate markup if you have ssr – you will have hydration mismatch as value cannot be calculated on server.
