### ISSUE TITLE
Website breaks on switching between dark and light mode

### ISSUE THREAD

**Issue by dukesx** [mantinedev/mantine#204]
The issue : Website breaks when i switch between dark and light mode. Doesn't matter, regardless of whether its next-dark-mode or use-dark-mode or through context api, if i switch it, the whole website just breaks, the css, the JavaScript, everything. It just happened suddenly and i don't know what just happened. Check Sandbox link for detailed demo. 

Note: the demo is fork of the project under issue. This is based on your Nextjs Starter Kit (Template)

Thanks for reaching out!

Please provide following information:
- What package has an issue (@mantine/core, mantine/hooks or other)?
A. Cannot say
- What package version are you using?
 A. Latest 2.2.1
- In which browser and operating system issue occurred?
A. All Major Including Edge
- If possible please attach link to codesandbox with reproduced issue
A. https://codesandbox.io/s/recursing-meitner-6otcb
- Do you have an idea how to fix the issue?
A. No Idea where its coming from
- Are you willing to participate in fixing this issue (it's totally fine if not) and create a pull request with the fix?
A. Absolutely

**Comment by rtivital** [comment]
Hi @dukesx, thanks for reproduction, try removing `{ minify: true }` both from `_app.tsx` and `_document.tsx`

**Comment by dukesx** [comment]
> Hi @dukesx, thanks for reproduction, try removing `{ minify: true }` both from `_app.tsx` and `_document.tsx`

Hi Thanks for the prompt reply, was using minify for generating ids a typo ? because after the removal, the issue seems to be gone.

**Comment by rtivital** [comment]
It was an error in documentation on getting started with next.js, seems like minify option does not work well with next.js – now the issue is fixed both in docs and Next template

**Comment by dukesx** [comment]
> It was an error in documentation on getting started with next.js, seems like minify option does not work well with next.js – now the issue is fixed both in docs and Next template

It is however strange since the ssr docs for react jss don't specifically say that minify won't work but nevertheless, would have been a good option to reduce the name string length. I haven't checked the class name lengths after change but I hope they aren't that long.
