### ISSUE TITLE
Spotlight should close when running closeSpotlight in onTrigger

### ISSUE THREAD

**Issue by Meierschlumpf** [mantinedev/mantine#2040]
### What package has an issue

@mantine/spotlight

### Describe the bug

When using spotlight-provider with closeOnActionTrigger set to false and defining actions with onTrigger the closeSpotlight function is not working.

### What version of @mantine/hooks page do you have in package.json?

5.0.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-spotlight-close-issue-nx3hq4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Thanks for reporting, I'll add an option to override `closeOnActionTrigger` on action level in one of the next releases.

**Comment by Meierschlumpf** [comment]
I would create a pr if it's fine :). It will be finished until tomorrow.

**Comment by rtivital** [comment]
Sure

**Comment by rtivital** [comment]
Fixed in 5.1.1
