### ISSUE TITLE
Mantine v5 Dropzone with `name` prop does not send file in request

### ISSUE THREAD

**Issue by Amaan18** [mantinedev/mantine#2044]
### What package has an issue

@mantine/dropzone

### Describe the bug

I'm using Remix, and for file uploads I was using the `name` prop on `Dropzone`. After updating to v5 and updating the necessary Dropzone component, the submitted request FormData no longer has a value for `name` and `size`. In the attached picture you can see 2 submissions, one is from `<input type="file" name="csv" />` and the other is 
```tsx
<Dropzone
  openRef={openRef}
  onDrop={(files) => {
  setFile(files[0])
  console.log('accepted files', files)
}}
  onReject={(files) => console.log('rejected files', files)}
  className={classes.dropzone}
  radius="md"
  name="csv"
  accept={[MIME_TYPES.csv]}
  maxSize={30 * 1024 ** 2}
>
```

The `console.log` in `onDrop` does log the proper file with name and other values, but submitting the form doesn't. None of my other form related things have changed

<img width="605" alt="Screen Shot 2022-08-08 at 3 53 14 AM" src="https://user-images.githubusercontent.com/55897964/183402151-ca64ade3-f72f-41a6-aacd-439f1336ba19.png">

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hi @Amaan18, can you please provide a sandbox that describes the issue that you have? We have input field rendered within dropzone with react-dropzone props – https://github.com/mantinedev/mantine/blob/master/src/mantine-dropzone/src/Dropzone.tsx#L184

**Comment by Amaan18** [comment]
Hi @rtivital, unfortunately I didn't have time to find the problem/wait for a fix. I've shifted to using a simple `FileInput` component
