### ISSUE TITLE
Select/MultiSelect with data group undefined or empty string raise each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by AntoineGst** [mantinedev/mantine#2045]
### What package has an issue

@mantine/core

### Describe the bug

When group is undefined or empty, a warning appear : 
```
Warning: Each child in a list should have a unique "key" prop. 
```

### What version of @mantine/hooks page do you have in package.json?

5.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/multiselect-with-empty-group-0gr59x

### Possible fix

 Introduce `group label` and `group key` separately instead of `group` to avoid this warning.

**Comment by rtivital** [comment]
Fixed in 5.1.5
