### ISSUE TITLE
Loader is not visible if color is not specified

### ISSUE THREAD

**Issue by claudious96** [mantinedev/mantine#2047]
### What package has an issue

@mantine/core

### Describe the bug

In Mantine v 5.1.0, `Loader` component is not visible if the color prop is not provided, it should fallback to the theme's primary color. This affects `LoadingOverlay` too as it uses `Loader` internally. See codesandbox below for an example.

### What version of @mantine/hooks page do you have in package.json?

5.1.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/optimistic-roentgen-191jpv?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Could be fixed by using `primaryFallback: true` in [Loader.tsx#L58](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Loader/Loader.tsx#L58).

This possibly affected other components as there are similar changes to lines that used `color || theme.primaryColor` in commit [c9b5e7e](https://github.com/mantinedev/mantine/commit/c9b5e7e7d0f82a0df2daaac1af9cfbf290729721).

**Comment by rtivital** [comment]
Thanks for reporting, the issue will be fixed in next patch

**Comment by rtivital** [comment]
Fixed in 5.1.1
