### ISSUE TITLE
Textarea’s onFocus prop no longer works

### ISSUE THREAD

**Issue by sunknudsen** [mantinedev/mantine#2049]
### What package has an issue

@mantine/form

### Describe the bug

Just updated to `5.1.0` from `5.0.0` and, when using [use-form](https://mantine.dev/form/use-form/), it appears `{...form.getInputProps("foo")}` now overrides `onFocus` prop which broke my app.

### What version of @mantine/hooks page do you have in package.json?

5.1.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/recursing-architecture-47c8y6

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
`onFocus` is required for touched state support, you can turn that off by setting `{ withFocus: false }` prop on `form.getInputProps` – https://codesandbox.io/s/competent-silence-rzq5ff?file=/src/App.tsx

**Comment by sunknudsen** [comment]
Thanks for helping out @rtivital.
