### ISSUE TITLE
Progress component styling typo causing browser console error

### ISSUE THREAD

**Issue by jesse-holden** [mantinedev/mantine#205]
Styling should be `&:first-child`

https://github.com/mantinedev/mantine/blob/9583a2a66c4223429c3f77c78861fdc63d37b753/src/mantine-core/src/components/Progress/Progress.styles.ts#L53

![Screenshot 2021-08-11 164059](https://user-images.githubusercontent.com/7012733/129100180-0ddbb1f9-3e66-4172-b171-45e0c0827983.png)

**Comment by rtivital** [comment]
Thanks for reporting, issue is fixed in 2.2.2 release
