### ISSUE TITLE
Module not found: Can't resolve '@emotion/cache'

### ISSUE THREAD

**Issue by Nzent** [mantinedev/mantine#2051]
### What package has an issue

@mantine/core

### Describe the bug

![image](https://user-images.githubusercontent.com/26079832/183508778-9626a20c-1aa4-4750-9dab-8ce0f4bd8ded.png)

I got this error on the Mantine carousel and Tooltip components
On framework Next.js

### What version of @mantine/hooks page do you have in package.json?

5.1.0

**Comment by rtivital** [comment]
You need to install `@emotion/react` package like described on the getting started page, if that does not help additionally install `@emotion/cache @emotion/serialize @emotion/utils` (it may be required for some deployment platforms like Heroku).

**Comment by Nzent** [comment]
Yeah need to inslall all packages `@emotion/react @emotion/cache @emotion/serialize @emotion/utils`, and now error gone thank you
