### ISSUE TITLE
Tooltip does not work with custom components

### ISSUE THREAD

**Issue by pgr3931** [mantinedev/mantine#2060]
### What package has an issue

@mantine/core

### Describe the bug

Using a tooltip with a `forwardRef` on custom components does not seem to work. To reproduce simply use the the example from the docs: https://mantine.dev/core/tooltip/#required-ref-prop

There are no errors or anything - the tooltip just does no appear when I hover over the element.

### What version of @mantine/hooks page do you have in package.json?

5.1.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/happy-lamarr-07xy23

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
You need to spread prop – https://codesandbox.io/s/vigilant-dhawan-1tgl68?file=/src/App.tsx
It will be added to docs with next patch.

**Comment by kinoli** [comment]
I suggest adding a comment in the docs for this on Menu component. This held me up for a couple of days. :(
