### ISSUE TITLE
`@mantine/rte` and `@mantine/carousel` - have diffrent React versions in peerDependencies

### ISSUE THREAD

**Issue by pstachula-dev** [mantinedev/mantine#2063]
### What package has an issue

@mantine/rte

### Describe the bug

When I use `@mantine/rte` and `@mantine/carousel` - 5.1.1 version

I have errors in Next.js:

```
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

I found that `react-quill` uses diffrent version of React than `@mantine/carousel` (embla is 7.0.0)

Embla-carouesel-react:
```
"peerDependencies": {
    "react": "^18.1.0"
  }
```

React-quill peer-deps:
```
"peerDependencies": {
    "react": "^16 || ^17",
    "react-dom": "^16 || ^17"
  },
```

### What version of @mantine/hooks page do you have in package.json?

5.1.1

### Possible fix

Fix React version in `@mantine/rte` packages

**Comment by rtivital** [comment]
React is a **peer** dependency, it is always installed on your side. Your problem is not related to this, carousel and rte can be used in one application – https://codesandbox.io/s/crimson-cdn-x9pkth?file=/src/App.tsx

**Comment by pstachula-dev** [comment]
Thanks for fast answer!

The problem was in monorepo... to fix this I had to declare React 18 version in main package.json to overwrite peerDependencies in monorepo
