### ISSUE TITLE
ScrollArea not working within Group

### ISSUE THREAD

**Issue by josch0** [mantinedev/mantine#2064]
### What package has an issue

@mantine/core

### Describe the bug

I want to use a ScrollArea in a fixed height Group. The ScrollArea overflows and does not display the scrollbars.

Unfortunately, I have no idea what props or CSS hacks I can use to fix this.
Is this a bug? Or am I using the components incorrectly?

### What version of @mantine/hooks page do you have in package.json?

5.1.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/reverent-bas-ordf4b

### Do you know how to fix the issue

No

**Comment by matinrco** [comment]
Add height to `ScrollArea`

```ts
import { MantineProvider, Box, ScrollArea, Group } from "@mantine/core";

export default function App() {
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <Group style={{ height: 400, backgroundColor: "#faa" }}>
        <ScrollArea style={{ height: "100%" }}>
          {new Array(20).fill().map((_, index) => (
            <Box style={{ padding: "10px 20px", border: "1px solid #000" }}>
              Menu item {index}
            </Box>
          ))}
        </ScrollArea>
        <Box>Content</Box>
      </Group>
    </MantineProvider>
  );
}
```

**Comment by josch0** [comment]
Hmm sorry.... I have simplified the example a bit too much. I have additional elements above the ScrollArea. So I can't give 100% height to the ScrollArea. The ScrollArea should use the remaining height automatically.

I have changed the codesandbox accordingly.

**Comment by matinrco** [comment]
> Hmm sorry.... I have simplified the example a bit too much. I have additional elements above the ScrollArea. So I can't give 100% height to the ScrollArea. The ScrollArea should use the remaining height automatically.
> 
> I have changed the codesandbox accordingly.

try this :
```ts
import { MantineProvider, Box, ScrollArea, Group, Stack } from "@mantine/core";

export default function App() {
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <Group style={{ height: 400, backgroundColor: "#faa" }}>
        <Stack spacing="sm" sx={{ height: "100%" }}>
          <Box>Content with dynamic height</Box>
          <ScrollArea>
            {new Array(20).fill().map((_, index) => (
              <Box style={{ padding: "10px 20px", border: "1px solid #000" }}>
                Menu item {index}
              </Box>
            ))}
          </ScrollArea>
        </Stack>
        <Box>Content</Box>
      </Group>
    </MantineProvider>
  );
}

```

**Comment by rtivital** [comment]
- If you want ScrollArea to fill in all remaining height, put it in flexbox container – https://codesandbox.io/s/solitary-water-b80lvp?file=/src/App.tsx
- If you want to set max height, then use ScrollArea.Autosize – https://mantine.dev/core/scroll-area/#scrollareaautosize
