### ISSUE TITLE
Popover with trapFocus fails to add focusRing to focused element within popover, except on first run

### ISSUE THREAD

**Issue by Slapbox** [mantinedev/mantine#2069]
### What package has an issue

@mantine/core

### Describe the bug

The first element inside of a popover with trapFocus receives focus (as it used to) but no longer has an outline around it which is quite confusing for the user trying to determine where their focus is after opening a popup and might lead to accidental button presses, but the element does get the expected outline if we press Tab and then Shift+Tab to return focus to the element.

BUT: The focus ring DOES work for the first render of the opened popover per app-load, but after that, never again

### What version of @mantine/hooks page do you have in package.json?

5.1.1

### Do you know how to fix the issue

No

**Comment by Slapbox** [comment]
> By default, focus ring is not visible when user uses mouse as for default browser controls

I don't understand this because:

1. The user didn't focus the focused element inside the popover with their mouse, so the user needs the feedback in this situation
2. This behavior doesn't match Mantine 4.x  - we never used `focusRing: 'always'` before, nor do we want to - but we don't want our users to wonder where their focus went in this single scenario in which the behavior doesn't match previous versions
3. The migration guide doesn't mention any changes to `focusRing` behavior

It still seems like a bug to me. Shouldn't the behavior match Mantine 4?

**Comment by rtivital** [comment]
No, the behavior should not match 4.x versions (that is the idea of major releases). I 5.0 focus trap behavior was changed to fix several issues across different browsers, this might also change the way how focus ring behaves. Also note that when `focusRing: 'auto'` is set, we do not control whether focus ring is visible or not – it is managed automatically by browser (we only set some styles).

**Comment by Slapbox** [comment]
@rtivital there's definitely something weird going on with the styling in some cases, always during first run. I get what you mean about the browser managing focus, but it seems like applying the focus-ring styles does not occur on the first `focus`ing of an element. This occurs whether the focus is initiated from the mouse, keyboard, or programmatically.

**We're now basically seeing the inverse of the original issue. In 5.6.3, the behavior is as below. In 5.1.1, the behavior is as described in the original comments:**

This behavior appears to have changed when moving from `5.5.x` to `5.6.x`

![image](https://user-images.githubusercontent.com/6835891/198421330-1b31675d-ea20-498c-b633-7039825e73b4.png)

This resolves following the first Tab/Shift+Tab to return to the element, and the issue no longer occurs until the element or the page is reloaded.  - but for some elements, the first Tab event does not move the focus.

So the order of events is like:

1. Focus an element (Nothing happens)
2. Press tab (with buttons this moves to the next item properly, but with `tabIndex="-1"`, the first `Tab` press focuses the same element, but shows the focus-ring)

You can see in this screen capture, that the element turns red when it's `:focus` but does not receive the focus-ring until Tab is pressed again, even though it's already the active element.

https://imgur.com/a/ipNLvux
