### ISSUE TITLE
Typescript issue with Vite and mantine 2.2.2

### ISSUE THREAD

**Issue by mindreframer** [mantinedev/mantine#207]
Hey, was just checking out mantine, looks really sharp! 

This example repo: https://github.com/rtivital/vite-mantine-example (as feedback to this issue https://github.com/mantinedev/mantine/issues/114) fails to build, when updated to `2.2.2`. 

```
"dependencies": {
    "@mantine/core": "^2.2.2",
    "@mantine/hooks": "^2.2.2",
    "@modulz/radix-icons": "^4.0.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-jss": "^10.6.0"
  },
```

```
$ yarn build 
```

is failing with 

```bash
$ tsc && vite build
node_modules/@mantine/core/lib/src/components/Title/Title.d.ts:266:18 - error TS2307: Cannot find module '@emotion/core' or its corresponding type declarations.

266     css?: import("@emotion/core").InterpolationWithTheme<any>;
                     ~~~~~~~~~~~~~~~


Found 1 error.

```

I hope this gives you enough information to reproduce this issue.

**Comment by mindreframer** [comment]
Last working version seems to be "2.1.5". "2.2.0" and later the build fails with the `@emotion/core` issue.

**Comment by rtivital** [comment]
Hi, to fix this, change `"skipLibCheck": true` option to `false` in your tsconfig.json

**Comment by rtivital** [comment]
Just found out that `React.createElement` produces types with emotion even if it is not used. Fixed this in 2.2.3, there should not be an error even with `"skipLibCheck": false`

**Comment by mindreframer** [comment]
@rtivital This is awesome, thank you for the quick fix! 

And thanks again for Mantine, it's kinda mindblowing how much progress you've made in such a short period of time. I like that the bundled size is quite modest for the fact, that we have a full blown React UI framework of such professional polish. Big props for having a good consistent test suite, using Typescript and having an outstanding documentation! I see a lot of similarities with ChakraUI, but Mantine's default look feels more lightweight and less opinionated. I have compared all the major UI frameworks for React in March 2021 and Mantine was NOT on my radar back then. For my next project I will use Mantine :) 

Cheers, 
Roman

**Comment by mindreframer** [comment]
Just checked, the issue is indeed fixed. Closing 👍

**Comment by rtivital** [comment]
Thanks for feedback, glad you've found Mantine useful
