### ISSUE TITLE
SelectItem's background color doesn't work

### ISSUE THREAD

**Issue by cheechoo28** [mantinedev/mantine#2072]
### What package has an issue

@mantine/core

### Describe the bug

When I used this example is doesn't work:
        styles={(theme) => ({
               item: {
                  '&[data-selected]': {
                   backgroundColor: '#2684FF',
                },
            },
         })}
Also I tried this example Styling with classNames. That didn't work either.
How to properly style the selected item in the select?

### What version of @mantine/hooks page do you have in package.json?

4.2.9

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### I think the problem is in data-selected, if it is removed the color is applied to all items. The example with this attribute works: 
        item: {
              '&[aria-selected]': {
                '&:hover': {
                  backgroundColor: theme.fn.rgba('#343212', 1),
                  color: theme.white,
                },
              },
            },

_No response_

**Comment by rtivital** [comment]
You are using version 4.x while following 5.x documentation. Either update mantine packages to 5.x or use v4 docs – https://v4.mantine.dev/
