### ISSUE TITLE
Bug Checkbox icons style when disabled

### ISSUE THREAD

**Issue by marieamelier** [mantinedev/mantine#2073]
### What package has an issue

@mantine/core

### Describe the bug

Hi, First, I'd like to thank you for the awesome library! I have encountered a problem since v5 and I think it might be a bug (or a missing update in the doc), I can't change the style (the color in the example) of the checkbox icons since migrating to v5.

### What version of @mantine/hooks page do you have in package.json?

5.1.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/distracted-maxwell-moccgq?file=/src/App.tsx

**Comment by rtivital** [comment]
Checkbox.Group does not support styles API for checkbox anymore, you need to set it directly on Checkbox component – https://codesandbox.io/s/cool-brook-d7g56y?file=/src/App.tsx
