### ISSUE TITLE
 Indicator component is not visible if color is not specified

### ISSUE THREAD

**Issue by mmarszal** [mantinedev/mantine#2075]
### What package has an issue

@mantine/core

### Describe the bug

The indicator will not render if a color is not specified. In previous versions the indicator would default to the primary color. This is now however not the case. Setting a color allows the Indicator to render.

### What version of @mantine/hooks page do you have in package.json?

5.1.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/silent-thunder-31yuc1?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 5.1.3
