### ISSUE TITLE
NumberInput defaultValue update issue with react state 

### ISSUE THREAD

**Issue by electroheadfx** [mantinedev/mantine#2076]
### What package has an issue

@mantine/core

### Describe the bug

The NumberInput doesn't refresh at the second state update, the defaultValue send null.

Test on codesandbox, edit Circle one time, update the value, save, and edit a second time, the value in the NumberInput doesn't take the state, it send no data to defaultValue.

The repo:
https://github.com/electroheadfx/mantine-typescript-input

### What version of @mantine/hooks page do you have in package.json?

5.1.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/silent-pond-dlg8ho

### Do you know how to fix the issue

No

### Possible fix

No

**Comment by rtivital** [comment]
defaultValue is used for uncontrolled components, if you want to control component state use `value` instead. Also, null is not supported, value should be either number or undefined.

**Comment by electroheadfx** [comment]
I changed defaultValue to value and it doesn't work: 
<NumberInput name='squareWidth' data-autofocus required label="Enter the square's width" value={square.width} />
You can test on codesandbox.

I don't return null to state

**Comment by rtivital** [comment]
Controlled input requires onChange handler – https://mantine.dev/core/number-input/#controlled

**Comment by rtivital** [comment]
Your sandbox link is empty btw, you need to save it

**Comment by electroheadfx** [comment]
Not it doesn't work, onChange not make working in the second and more edit.
Its weird because it works on the first edit. In my exemple I use state with an object : { radius: 5, modal: false }
so the value on input is circle.radius, maybe its why mantine is lost ? it need state with primitive only ?

**Comment by electroheadfx** [comment]
I have already posted a sandbox, I updated it now: https://codesandbox.io/s/silent-pond-dlg8ho?file=/src/components/Drawer.tsx
thanks

**Comment by electroheadfx** [comment]
I will test mantine input with a minimal project based on a controlled state with object. Thanks

**Comment by rtivital** [comment]
Sorry I cannot spend too much time debugging 200+ line component, you can find controlled input example here – https://codesandbox.io/s/hungry-star-tnbv83?file=/src/App.tsx

**Comment by electroheadfx** [comment]
no worry, I will come back with a simplier minimalistic code, sorry. Thx

**Comment by electroheadfx** [comment]
Hey rtivital, Iam back, Its an issue relative to the modal With input.

you can reproduce the bug here with this simple sample:
https://codesandbox.io/s/priceless-paper-2ulm2o?file=/src/App.tsx

Steps for reproduce:
- Edit the the value
- Change the value : Input has the right default value = 0
- submit the form
- Edit again the value : the input has blank value

**Comment by rtivital** [comment]
You are setting value as string, while NumberInput supports only numbers. Convert value to number to avoid that.
https://codesandbox.io/s/eloquent-shape-kp1os3?file=/src/App.tsx
