### ISSUE TITLE
@mantine/dates Time Input onChange not firing when changing the time with arrow keys

### ISSUE THREAD

**Issue by newtdogg** [mantinedev/mantine#208]
When using the arrow keys to change the values in a Time Input, the onChange event doesn't occur, only when you type the time into the input
This issue was found in @mantine/dates 2.2.1, using Chrome on MacOS.
Let me know if you need any more information (didn't include code sandbox as its fairly simple to recreate)

**Comment by rtivital** [comment]
Thanks for reporting, this will be fixed in next patch

**Comment by rtivital** [comment]
Fixed in [2.3.1](https://github.com/mantinedev/mantine/releases/tag/2.3.1)
