### ISSUE TITLE
React 18 StrictMode breaks NotificationSystem

### ISSUE THREAD

**Issue by josch0** [mantinedev/mantine#2081]
### What package has an issue

@mantine/notifications

### Describe the bug

If <React.Strict> ist used, no notifications pop up using "showNotification"

### What version of @mantine/hooks page do you have in package.json?

5.1.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/priceless-cohen-8gj2mv

### Do you know how to fix the issue

No

**Comment by Geczy** [comment]
same issue but turning off react strict didn't fix it, on nextjs next.config

**Comment by amberzaragoza** [comment]
I am also experiencing the same issue.

**Comment by TrashPandacoot** [comment]
I'm also seeing the same thing in addition to the Modals manager also not working with with `openContextModal`.
v5.1.1 I'm not having the issues. Looking at the diff my only thought is it might be from the recent changes to `createUseExternalEvents` in the util package [in this file](https://github.com/mantinedev/mantine/blob/0cad366613d78f4749dc7577d10944ff3d9f6bad/src/mantine-utils/src/create-use-external-events/create-use-external-events.ts), but I'm not sure

**Comment by neolivz** [comment]
I tried and it is still broken with 5.1.3 https://github.com/neolivz/mantine-notification

**Comment by rtivital** [comment]
It will be fixed in 5.1.4 patch.

**Comment by rtivital** [comment]
Fixed in 5.1.4
