### ISSUE TITLE
A Menu in an AppShell Header is rendered underneath Aside

### ISSUE THREAD

**Issue by jvanamerongen2002** [mantinedev/mantine#2086]
### What package has an issue

@mantine/core

### Describe the bug

When building an `AppShell` and placing a `Menu` component in the `AppShell`'s header, the `Menu.Dropdown` will open underneath (in terms of z axis) the `Aside` of the same `AppShell`. See the reproduction.

### What version of @mantine/hooks page do you have in package.json?

5.1.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/friendly-paper-hz2n85

### Do you know how to fix the issue

Yes

### Possible fix

A quick inspection shows that the `Menu` has `z-index: 300` and `Aside` and `Header` have `z-index: 100`. But since `Aside` and `Header` are at the same level, and the `Menu` is a child of `Header`, it is covered. Setting different `z-index`'s (!= 100) to either `Aside` or `Header` shows the `Menu` again. Or the higher z-index of `Menu` should work outside of the scope of `Header`.

**Comment by rtivital** [comment]
Set `withinPortal` to fix that – https://codesandbox.io/s/kind-bartik-wdjj4k?file=/src/App.js
You can also configure Menu z-index with `zIndex` prop.

**Comment by jvanamerongen2002** [comment]
Thanks for your response! Is it worth mentioning this in the docs of AppShell or Menu? Setting `withinPortal` was not at all obvious until you pointed it out and I can imagine that there are more places where this might occur.
