### ISSUE TITLE
Badge in anchor tag has inconsistent styles in Firefox and Chrome

### ISSUE THREAD

**Issue by taobojlen** [mantinedev/mantine#2087]
### What package has an issue

@mantine/core

### Describe the bug

I'm using the `Badge` component wrapped in an anchor tag, to use it as a clickable link. My code looks like this:

```js
<MantineProvider withNormalizeCSS withGlobalStyles>
  <a href="#">
    <Badge color="red" variant="filled" style={{ cursor: "pointer" }}>
      Badge link
    </Badge>
  </a>
</MantineProvider>
```

Because I'm using normalize.css via `withNormalize`, I would expect this to look the same across browsers. However,  in Firefox the link text is not underlined, while in Chrome it is.

Firefox:
<img width="119" alt="Screen Shot 2022-08-12 at 11 43 54" src="https://user-images.githubusercontent.com/66130243/184329079-21cd49de-48af-42db-84c3-2a60d920434f.png">

Chrome:
<img width="117" alt="Screen Shot 2022-08-12 at 11 44 12" src="https://user-images.githubusercontent.com/66130243/184329117-1fa89886-1484-4d58-85d8-c0907d0a80cd.png">

### What version of @mantine/hooks page do you have in package.json?

5.1.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/flamboyant-https-941gss?file=/src/App.tsx:104-321

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Hi @taobojlen, we cannot control styles of external components from inside Mantine component. You should either disable those styles on your side or use `component` syntax – https://codesandbox.io/s/competent-kalam-nsbtz9?file=/src/App.tsx
