### ISSUE TITLE
DatePicker doesn't trigger browser validation when required

### ISSUE THREAD

**Issue by jpekeene** [mantinedev/mantine#2089]
### What package has an issue

@mantine/dates

### Describe the bug

If you add a `DatePicker` with the `required` attribute and leave that field empty, it does not trigger the browser validation.

### What version of @mantine/hooks page do you have in package.json?

5.1.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hardcore-rgb-iu7h9d?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Hi @jpekeene, unfortunately it is not possible to have native browser validation for DatePicker and some other components. See #1561 for details.
