### ISSUE TITLE
Select / Autocomplete / Multiselect issue with click outside of modal for data selection

### ISSUE THREAD

**Issue by cstrat** [mantinedev/mantine#209]
Repo: https://codesandbox.io/s/event-propagation-issue-f1jni

As discussed on discord. There is an issue with the data list menus triggering modals to close.
Updated the repo with the other elements too.

**Comment by my-name-was-already-taken** [comment]
Same happens when using Select inside of a <Drawer /> component - the drawer closes when an element is selected by clicking on it.

**Comment by rtivital** [comment]
Fixed in [2.3.1](https://github.com/mantinedev/mantine/releases/tag/2.3.1)

**Comment by Lokinorse** [comment]
> Fixed in [2.3.1](https://github.com/mantinedev/mantine/releases/tag/2.3.1)

But didn't fixed for Popovers which is basicaly are same. Why don't you just expose some api to handle this behaviour? This or fix it across all modal-like components?

**Comment by rtivital** [comment]
If you want to report an issue with the library, open a new issue with a proper description and reproduction.
