### ISSUE TITLE
TypeError : Cannot read properties of undefined (reading 'emit')

### ISSUE THREAD

**Issue by abhishekram404** [mantinedev/mantine#2091]
### What package has an issue

@mantine/rte

### Describe the bug

# TypeError : Cannot read properties of undefined (reading 'emit')

## Bug Description 
I am using @mantine/rte package with Next JS. Everything works fine on desktop. 

But while testing it on my android phone's chrome browser, it throws this error `TypeError : Cannot read properties of undefined (reading 'emit')` when I press the `return` key on my phone's keyboard while writing in the `Mantine RTE` 

## Bug reproduction
OS : Android 9
Browser : Chrome 103.0.5060.129
Reproduction steps : 
- Write some content inside the Mantine RTE and press `Enter` on your phone's keyboard
- Normally the bug reproduces when I choose `h1` text style, write some heading, then press `Enter`. Pressing `Enter` is causing this sometimes.

## Screenshots

![photo_2022-08-12_20-09-30](https://user-images.githubusercontent.com/55845306/184376476-04178adb-90c7-408f-8839-d4c930780a6e.jpg)

My `package.json` file looks like this : 
```
{
  "name": "the-next-blog",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@emotion/react": "^11.10.0",
    "@emotion/server": "^11.10.0",
    "@hookform/resolvers": "^2.8.8",
    "@iconify/react": "^3.2.1",
    "@mantine/core": "^5.1.4",
    "@mantine/hooks": "^5.1.4",
    "@mantine/next": "^5.1.4",
    "@mantine/rte": "^5.0.3",
    "@reduxjs/toolkit": "^1.8.4",
    "framer-motion": "^7.1.0",
    "next": "12.1.6",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-hook-form": "^7.31.1",
    "react-redux": "^8.0.2",
    "sass": "^1.51.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@types/node": "17.0.33",
    "@types/quill": "^2.0.9",
    "@types/react": "18.0.9",
    "@types/react-dom": "18.0.4",
    "@types/react-redux": "^7.1.24",
    "eslint": "8.15.0",
    "eslint-config-next": "12.1.6",
    "typescript": "4.6.4"
  }
}

```

### What version of @mantine/hooks page do you have in package.json?

^5.1.4

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Please verify that issue is reproducible in production builds

**Comment by abhishekram404** [comment]
Seems to be working fine in production build.
I think I should close this issue now.

**Comment by rtivital** [comment]
strict mode issue, rte does not work with it – https://mantine.dev/others/rte/#react-strict-mode-limitations
