### ISSUE TITLE
NavLink not working in last version 

### ISSUE THREAD

**Issue by abdelhak101** [mantinedev/mantine#2100]
### What package has an issue

@mantine/hooks

### Describe the bug

NavLink  crashing, also in site https://mantine.dev/core/nav-link/

if i used @mantine/hooks version 5.1.4 or 5.1.5 NavLink not working from @mantine/core

(@mantine/core 5.1.5 with @mantine/hooks 5.1.3 working good)

this image from site 
![image](https://user-images.githubusercontent.com/6784544/184477974-dbf6f9fa-1e7c-4391-bffd-4e72b51c4b89.png)

### What version of @mantine/hooks page do you have in package.json?

5.1.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/currying-fog-kq47yg

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Hi @abdelhak101, codesandbox that you've provided works correctly, website also works correctly for me in all browsers on macos and windows. You may have stale cache, try "Clean cache and hard reload".

**Comment by abdelhak101** [comment]
Hi @rtivital thank you for your quick response
i try what you said and still i see same problem 
![image](https://user-images.githubusercontent.com/6784544/184480404-e97472e9-3c80-48c8-8f54-aa610354b234.png)

but any way i m use old version now thank you so much

**Comment by rtivital** [comment]
I do not see any errors in sandbox that you've provided, cannot tell anything about this issue
