### ISSUE TITLE
Spotlight renders out to the left of the screen in Production using Remix (express server)

### ISSUE THREAD

**Issue by ihpannu** [mantinedev/mantine#2107]
### What package has an issue

@mantine/spotlight

### Describe the bug

Spotlight renders out to the left of the screen in Production using Remix (express server). Works perfectly well using in Dev environment. I had the same issue with modals but solved using within portal props and facing problems on the latest @remix and "@mantine/hooks": "^5.1.5",

Please suggest

### What version of @mantine/hooks page do you have in package.json?

5.1.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hi @ihpannu, you can set `withinPortal` prop on SpotlightProvider the same way as on Modal component. If that does not help, please provide a repository with minimal reproduction, use mantine remix template as base for your repository.

**Comment by ihpannu** [comment]
-I will submit today also having few other issues such as 

- _rightSection_ icon in input renders out of the box on initial page load
- 404 doesn't render styles. After a refresh styles load back.
- Spotlight renders under the navbar to the left

Attached some screenshots for now will push an repo to show live results
 ![image](https://user-images.githubusercontent.com/26369180/185027821-67b643ff-54b1-4b12-9c6e-a261c5985877.jpeg)
![image](https://user-images.githubusercontent.com/26369180/185027848-8130cc8c-7aed-45e4-992c-3e33c7bdde02.jpeg)

**Comment by rtivital** [comment]
@ihpannu are you using mantine-remix-template?

**Comment by rtivital** [comment]
React 18 is not supported with Remix template, downgrade to react 17 to solve these issues.

**Comment by ihpannu** [comment]
@rtivital Rolled back to React 17 and Mantine 5.1.6 all same issues still persist. This app is running in production on Railway using remix/express server

**Comment by rtivital** [comment]
Well, I cannot help much, if you can reproduce an issue in mantine-remix-template and send the repo I can have a look

**Comment by ihpannu** [comment]
@rtivital attached is the link to the repo using mantine-remix-template on GitHub [https://github.com/ihpannu/mantine-remix-template](url)
and link to the live site reproducing the error [https://mantine-remix-template-production.up.railway.app/](url)

**Comment by andremonteiro95** [comment]
> React 18 is not supported with Remix template, downgrade to react 17 to solve these issues.

Is supporting React 18 w/ Remix on the roadmap?

**Comment by rtivital** [comment]
In a long term – maybe, in short term – no. With current remix direction (server streaming as default) I doubt that it will worth the effort to support remix at all. As for current state – remix feels very unstable – we've already had to change ssr logic twice in the past 6 months, so I'm not planning to work on it any time soon until remix becomes at least a little more mature (in terms of css-in-js handling).

**Comment by ihpannu** [comment]
@rtivital do you recommend porting over to Next.js? we cannot afford to change the UI lib at the moment and given the mantine/remix plan it doesn't seem ideal to continue using the broken framework on the production level

**Comment by rtivital** [comment]
Well, it's up to you, I have several next.js app running in production without any issues built with Mantine.

**Comment by ihpannu** [comment]
@rtivital Thank you for advice

**Comment by alukach** [comment]
Possibly related to https://github.com/mantinedev/mantine/issues/2311

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
