### ISSUE TITLE
Forced padding in SelectPopover.

### ISSUE THREAD

**Issue by raymonddaikon** [mantinedev/mantine#2108]
### What package has an issue

@mantine/core

### Describe the bug

Impossible to change the default padding of 4px in Multiselect and Select.
Even when setting padding: !0, the dropdown in Select and Multiselect will have a 4 padding. 
Not sure if this is intended behaviour but it would be nice to leave padding of the dropdown to the user.

### What version of @mantine/hooks page do you have in package.json?

5.1.5

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

In SelectPopover.tsx the div on line 41 has a padding: 4 property. Unsetting this value should fix it.

**Comment by rtivital** [comment]
Fixed in 5.2.4
