### ISSUE TITLE
Autocomplete/Select not auto-focus option

### ISSUE THREAD

**Issue by JFuenmayor** [mantinedev/mantine#2109]
### What package has an issue

@mantine/core

### Describe the bug

Hi! I'm trying to be able to autofocus the first option of any select when dropdown opens, just as React-select component works (https://react-select.com/home), I tried onFocusTrap for the dropdownComponent just as the codesandbox, however with or without the focus hook, the console pops an issue regarding forwarding refs on the dropdownComponent.

Is there any way to expose the dropdown component ref to make use of this hook? or to make inherent the auto-focus behavior to the Autocomplete/Select components? 

### What version of @mantine/hooks page do you have in package.json?

5.1.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/little-surf-ledh0i?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

(I'm quite new with react, so deep down on the library perse I'm quite lost) A) Expose the dropdown props to handle this behavior on developer will or B) make it inherent to the usual component behavior

**Comment by rtivital** [comment]
Hi @JFuenmayor, use-focus-trap hook is incompatible with Select and other components' dropdown. Dropdown manages hovered/selected items on its own, as it is required to make components accessible (keyboard interactions, screen reader support). Items rendered in dropdown never receive focus on their own. Changing hovered/selected logic will not be configurable as it will require a lot of maintenance.
