### ISSUE TITLE
DatePicker cannot be used in modals or drawers

### ISSUE THREAD

**Issue by my-name-was-already-taken** [mantinedev/mantine#211]
The DatePicker component from @mantine/dates (version 2.3.0) does not open the actual date picker box when used inside of a Modal or Drawer component. Tested in Safari 14 and Chrome 92 on Mac. This is likely due to the component being rendered behind the Drawer / Modal.

https://codesandbox.io/s/datepicker-does-not-open-wcqp9?file=/src/App.js

**Comment by rtivital** [comment]
Thanks for reporting, this will be fixed in next patch

**Comment by prawee** [comment]
same me

**Comment by rtivital** [comment]
Fixed in [2.3.1](https://github.com/mantinedev/mantine/releases/tag/2.3.1)

**Comment by rtivital** [comment]
Specify `zIndex` prop to use DatePicker within Modal:

```tsx
<DatePicker zIndex={1000} />
```

**Comment by Manitej66** [comment]
Same issue for `DateTimePicker`

**Comment by omair-bhatti** [comment]
> Specify `zIndex` prop to use DatePicker within Modal:
> 
> ```tsx
> <DatePicker zIndex={1000} />
> ```

not working

**Comment by MrWarzo** [comment]
Same problem with MonthPickerInput

**Comment by philr35** [comment]
Happening as well for me with Modal and DateTimePicker in Mantine v8. Trying to diagnose why it all of a sudden broke as it was working recently... `zIndex=1000` does not seem to help

**Comment by philr35** [comment]
Found the bug after removing one thing at a time. At some point I switched from using `<Modal />` to using Modal [compound components](https://mantine.dev/core/modal/#compound-components) which is listed under the same docs.

By reverting back to non-compound component Modal, fixed the issue I was having. No clue why.
