### ISSUE TITLE
Menu inside Card - NOT WORKING

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#2112]
### What package has an issue

@mantine/core

### Describe the bug

My desired result is this:
![Screenshot 2022-08-14 at 09 35 45](https://user-images.githubusercontent.com/22228431/184525494-80803ae2-5b3d-4f58-9145-7c98df0e437f.png)

However, putting a `Menu` component inside `Card` produces this.

Before clicking:
![Screenshot 2022-08-14 at 09 32 13](https://user-images.githubusercontent.com/22228431/184525503-7ca53060-1e39-4c76-a66c-a206068131bb.png)

After clicking:
![Screenshot 2022-08-14 at 09 32 29](https://user-images.githubusercontent.com/22228431/184525536-48bcee6c-054a-48eb-9b55-911223d61f0c.png)

`Menu` becomes centered and hidden inside `Card`. I think it's a bug. I tried `<Menu zIndex='999999'>` but still got the same result.

Please fix!

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

[LINK TO PROBLEM](https://codesandbox.io/s/determined-shannon-7c7znq)

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

No idea.

**Comment by atumas-bananamilk** [comment]
[LINK TO PROBLEM](https://codesandbox.io/s/determined-shannon-7c7znq)

**Comment by rtivital** [comment]
Set withinPortal on Meni – https://codesandbox.io/s/festive-dijkstra-0tzvl0?file=/src/App.tsx

**Comment by atumas-bananamilk** [comment]
Nice one!
