### ISSUE TITLE
Documentation for reset the file with FileButton should be improved

### ISSUE THREAD

**Issue by Meierschlumpf** [mantinedev/mantine#2113]
### Link to the page where something nasty is located

https://mantine.dev/core/file-button/

### Exact quote of what is wrong

I would like to have an additional part where the reset of the current file is described.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Would you like to send a PR with these docs?

**Comment by Meierschlumpf** [comment]
Of course 👍🏼
