### ISSUE TITLE
Polymorphic components accepts props from base component

### ISSUE THREAD

**Issue by hornta** [mantinedev/mantine#2117]
### What package has an issue

@mantine/core

### Describe the bug

If I for example create a button and set the `component="a"` then I'm still allowed to provide a `type` prop even though `type` isn't a valid HTML attribute for `<a>` 

```ts
// I expect this to fail TS compilation but it's not
<Button component="a" type="button">
<Button component="a" disabled="">
```

### What version of @mantine/hooks page do you have in package.json?

5.1.4

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Polymorphic component extends given component or element props, it works as expected for button element.
- `disabled` prop will exist for every element as it used to control styles, not just adds an attribute
- `type="button"` is a valid attribute for `a` tag – https://codesandbox.io/s/bitter-rgb-g2o7qg?file=/src/App.tsx

**Comment by hornta** [comment]
> disabled prop will exist for every element as it used to control styles, not just adds an attribute
Yes but I don't think it should. It should only exist for form elements, namely the ones listed here. https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#enabling-and-disabling-form-controls:-the-disabled-attribute. I would like TS to raise an error if disabled is provided for non-form controls.

> type="button" is a valid attribute for a tag
Same with this attribute. It doesn't make sense for this attribute to exists with non button elements. I would like TS to raise an error here as well. https://html.spec.whatwg.org/multipage/input.html#button-state-(type=button)

**Comment by rtivital** [comment]
> Yes but I don't think it should. It should only exist for form elements

When we did not have this attribute for anchors people got confused: they created at least 4 issues about it and asked more than 20 time on discord. So no, it will remain as is.

> Same with this attribute. It doesn't make sense for this attribute to exists with non button elements

It is an issue with types provided by TypeScript or `@types/react` – we do not add anything extra on our side.

**Comment by hornta** [comment]
> It is an issue with types provided by TypeScript or @types/react – we do not add anything extra on our side.

Alright that's weird. I tried to pass `autoFocus` for on a `<Button component="a">` and it errors as I expect, nice.

> When we did not have this attribute for anchors people got confused: they created at least 4 issues about it and asked more than 20 time on discord. So no, it will remain as is.

I don't agree. Disabling an anchor makes no sense. It makes me confused as to why it is like this, but I guess it's 4-1 then.

**Comment by hornta** [comment]
Actually it's 4-2 since this issues states the same problem as I do: https://github.com/mantinedev/mantine/issues/994
