### ISSUE TITLE
Full screen modal scrolls when content overflows

### ISSUE THREAD

**Issue by daviderusso1984** [mantinedev/mantine#2118]
### What package has an issue

@mantine/core

### Describe the bug

Hello, I attach the link to the gif with the error [https://drive.google.com/file/d/1IAVdzejWZ2oc_83AIE-rV4E7qFn0WAei/view](url)

### What version of @mantine/hooks page do you have in package.json?

5.1.1

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by jimmyruann** [comment]
I have reproduced here in codesandbox: https://codesandbox.io/s/dark-sky-lmn7rs?file=/src/App.tsx

**Comment by rtivital** [comment]
Fixed in 5.1.7
