### ISSUE TITLE
Multiselect 'creatable' behavior bugged when in controlled state

### ISSUE THREAD

**Issue by eliranbenishai** [mantinedev/mantine#2120]
### What package has an issue

@mantine/core

### Describe the bug

When Multiselect is in a controlled state, creating new items is ignored. I tried several permutations of the data structure (SelectItem and string literals for both data / value attributes) and the result is the same. This is definitely a new bug in version 5.
Thanks.

### What version of @mantine/hooks page do you have in package.json?

5.1.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/twilight-dream-od3xj8?file=/pages/index.tsx

**Comment by rtivital** [comment]
Thanks for reporting, the issue will be fixed in one of the next releases

**Comment by rtivital** [comment]
Hi @eliranbenishai, I've checked your sandbox one more time and it seems like Select component works as expected – you need to manage data state on your side (documentation – https://mantine.dev/core/select/#creatable), onChange handler will be called automatically with the value that you've returned from the function. 

https://codesandbox.io/s/pensive-hellman-8f6gzi?file=/pages/index.tsx

**Comment by eliranbenishai** [comment]
Thanks for the help! Though this tight relationship between the `data` and `value` attributes isn't mentioned anywhere (especially when the "creatable" example isn't controlled, which it would often be, I'd imagine). Also it didn't work like that in v4. Maybe it's worth a mention in the migration/upgrade notes?
Thanks again!

**Comment by rtivital** [comment]
It is mentioned in 5.0 changelog – https://mantine.dev/changelog/5-0-0/#other-breaking-changes
Apart from requiring items to be returned from the onCreate callback there were no other changes – it was also required to managed data state in 4.x versions.
