### ISSUE TITLE
@mantine/core: `Select` and `NativeSelect` not rendering properly when using TailwindCSS

### ISSUE THREAD

**Issue by devj3ns** [mantinedev/mantine#2126]
@mantine/core, Version ^5.1.6

### Describe the bug

Normally `Select` and `NativeSelect` look like this:
![image](https://user-images.githubusercontent.com/20878653/184547580-b8e37599-fa24-47f3-9043-ea33a88ec449.png)

Unfortunately, when I add TailwindCSS to my project, it looks like this:
![image](https://user-images.githubusercontent.com/20878653/184547574-695f450e-2ec5-4d28-a299-4f7239670218.png)

**Comment by rtivital** [comment]
Hi @devj3ns, you've installed a third-party library to your project that overrides Mantine styles. To fix that issue, either remove those styles or change emotion cache options to make Mantine styles override third-party library styles – https://mantine.dev/theming/emotion-cache/

**Comment by devj3ns** [comment]
Hey @rtivital 

Thank you so much for the prompt reply.

I got it working now :)
