### ISSUE TITLE
Select dropdown having an horizontal scroll

### ISSUE THREAD

**Issue by neolivz** [mantinedev/mantine#2127]
### What package has an issue

@mantine/core

### Describe the bug

`<Select />` dropdown has a horizontal scrollbar.

The generated HTML is
```
<div
  data-radix-scroll-area-viewport=""
  class="mantine-xlwgkm mantine-ScrollArea-viewport"
  style="overflow: scroll"
>
  <div style="min-width: 100%; display: table">
    <div
      style="display: flex; flex-direction: column; width: 100%; padding: 4px"
    >
      <div
        class="mantine-qxv4uk mantine-Select-item"
        id="mantine-rb-0"
        role="option"
        data-ignore-outside-clicks="true"
        tabindex="-1"
        aria-selected="false"
      >
        React
      </div>
      <div
        class="mantine-qxv4uk mantine-Select-item"
        id="mantine-rb-1"
        role="option"
        data-ignore-outside-clicks="true"
        tabindex="-1"
        aria-selected="false"
      >
        Angular
      </div>
      <div
        class="mantine-qxv4uk mantine-Select-item"
        id="mantine-rb-2"
        role="option"
        data-ignore-outside-clicks="true"
        tabindex="-1"
        aria-selected="true"
        data-hovered="true"
      >
        Svelte
      </div>
      <div
        class="mantine-qxv4uk mantine-Select-item"
        id="mantine-rb-3"
        role="option"
        data-ignore-outside-clicks="true"
        tabindex="-1"
        aria-selected="false"
      >
        Vue
      </div>
    </div>
  </div>
</div>
```

What i feel the issue is 
The parent having the style `min-width: 100%;display: table;`
and child is `display: flex; flex-direction: column; width: 100%; padding: 4px`
either remove the padding of 4px or reduce width to calc(100% - 8px)

### What version of @mantine/hooks page do you have in package.json?

5.1.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-select-scroll-bar-c2wt2q

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by neolivz** [comment]
Adding `*, ::before, ::after {
    box-sizing: border-box;
}` solved the problem

**Comment by nammi-kobler** [comment]
> Adding `*, ::before, ::after { box-sizing: border-box; }` solved the problem

Which element did you add this to?

**Comment by rtivital** [comment]
@nammi-kobler set `withGlobalStyles` and `withNormalizeCSS` on MantineProvider.
