### ISSUE TITLE
Color props doens't autocomplete variants

### ISSUE THREAD

**Issue by Zeko369** [mantinedev/mantine#2129]
### What package has an issue

@mantine/core

### Describe the bug

It would be great if this also autocompleted i.e. `red.3`

![image](https://user-images.githubusercontent.com/3064377/184622967-415bcb56-f7eb-4ca3-8d67-2aca6eada214.png)

### What version of @mantine/hooks page do you have in package.json?

5.1.6

### If possible, please include a link to a codesandbox with the reproduced problem

Any mantine project

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Linked PR

**Comment by rtivital** [comment]
See #2130 for explanation
