### ISSUE TITLE
Modal - if state is outside component, transitions stop working

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#2136]
### What package has an issue

@mantine/core

### Describe the bug

This one works:

```
import { Button, Modal } from "@mantine/core";
import React from "react";

export default function App() {
  function CustomModal() {
    const [opened, setOpened] = React.useState(false);
    return (
      <>
        <Modal
          opened={opened}
          onClose={() => setOpened(false)}
          transition="rotate-left"
          title="RANDOM"
        ></Modal>
        <Button onClick={() => setOpened(true)}>AAAA</Button>
      </>
    );
  }

  return (
    <div className="App">
      <CustomModal />
    </div>
  );
}
```

This one ruins the transition:

```
import { Button, Modal } from "@mantine/core";
import React from "react";

export default function App() {
  const [opened, setOpened] = React.useState(false);
  function CustomModal() {
    return (
      <>
        <Modal
          opened={opened}
          onClose={() => setOpened(false)}
          transition="rotate-left"
          title="RANDOM"
        ></Modal>
      </>
    );
  }

  return (
    <div className="App">
      <CustomModal />
      <Button onClick={() => setOpened(true)}>AAAA</Button>
    </div>
  );
}
```

I want to keep the modal as a standalone component.
So does the trigger button **(that's a part of another component)** always have to be passed INSIDE the modal's component? Why does the state from parent component ruin transitions?

Thanks

### What version of @mantine/hooks page do you have in package.json?

5.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-playground-forked-8z0snw

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

-

**Comment by rtivital** [comment]
It does now play transition because on each render you are creating new component – react does not like that, I would recommend avoiding that as it hurts performance. Create component outside of App function call and it will work as expected – https://codesandbox.io/s/mantine-playground-forked-ltluyq?file=/src/App.tsx
