### ISSUE TITLE
Checkbox not showing the check icon when toggled.

### ISSUE THREAD

**Issue by Mikkelzu** [mantinedev/mantine#2138]
Hey there, 

Currently I'm using version 5.1.3 and using the checkbox it doesn't toggle the checked visibility, it does however update its checked state.

I've tried to also set the icon itself to be the <Check /> icon from tabler icons but this also does not seem to fix my issue. I also can't find anything much in the documentation on this.

Any ideas? Is there a chance I implement it wrong?

See example below on my issue:

```const DataTableDimensionCheckboxes = ({ dimensions }: { dimensions: any }) => {
  const [checked, setChecked] = useState(false);

  return (
    <Box
      sx={{
        position: 'relative',
        padding: 25,
      }}
    >
      <>
        {dimensions.cube.map((dim: any) => {
          return (
            <Checkbox
              checked={checked}
              onChange={(event) => setChecked(event.currentTarget.checked)}
              label={dim.label}
            />
          );
        })}
      </>
    </Box>
  );
};

**Comment by rtivital** [comment]
It works as expected on codesandbox – https://codesandbox.io/s/adoring-wilson-cjkows?file=/src/App.tsx
Make sure that:
- you do not have third party libraries that override styles
- you provide correct `checked` value to Checkbox component

**Comment by rtivital** [comment]
@Mikkelzu if you have any other questions or can provide a sandbox with reproduction, then feel free to reopen the issue.
