### ISSUE TITLE
Selecting date in DatePicker within a Popover causes Popover to close 

### ISSUE THREAD

**Issue by billop** [mantinedev/mantine#2144]
### What package has an issue

@mantine/dates

### Describe the bug

Selecting date in DatePicker within a Popover causes Popover to close 

### What version of @mantine/hooks page do you have in package.json?

5.1.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/fancy-architecture-ywwowr?file=/src/App.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Set withinPortal={false} on DatePicker component – https://codesandbox.io/s/lingering-tree-k6y8uy?file=/src/App.tsx

**Comment by SrBrahma** [comment]
@rtivital I am having this when using withinPortal={false} in my DatePick in my Popover:

![image](https://user-images.githubusercontent.com/28177550/203152944-bc87b10a-beb7-4bbd-a09b-6d073d07a665.png)

(way bigger and strange overall)

Not sure why this is happening. Any idea?

**Comment by rtivital** [comment]
No idea, provide a sandbox

**Comment by moranbw** [comment]
@rtivital why does this happen when `withinPortal={true}`?

Understood that `withinPortal={false}` is the workaround...but what if you want or need to use a portal?
