### ISSUE TITLE
Tooltip issue - Date Picker under Tooltip not working on @mantine 5.1.5 and 5.1.16

### ISSUE THREAD

**Issue by kkarwowski** [mantinedev/mantine#2145]
### What package has an issue

@mantine/core

### Describe the bug

When placing Date Picker as a child of Tooltip - Date Picker is not getting selected when cliccked. Affected versions are 5.1.5 and 5.1.16 - earlier version of mantine/core work fine.

I have created Codesandbox to demonstrate. Changing @mantine/core package to 5.1.14 fixes Tooltip and Datepicker gets selected.

### What version of @mantine/hooks page do you have in package.json?

5.1.15 and 5.1.16

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-5-1-6-tolltip-and-datepicker-tv1003?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hi @kkarwowski, you need to wrap your DatePicker with div element, unfortunately, there is not any other good way of fixing this issue – https://codesandbox.io/s/mantine-5-1-6-tolltip-and-datepicker-forked-ommnkt?file=/src/App.js
