### ISSUE TITLE
Skeleton not working with dynamic <Text>

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#2147]
### What package has an issue

@mantine/core

### Describe the bug

I made a reusable `Skeleton`, however it doesn't work with Mantine `<Text>`, if text is dynamic.
My text is coming from NextAuth user session.

Reusable skeleton:
```
import React, {useEffect, useState} from 'react';
import {Skeleton as MantineSkeleton} from '@mantine/core';
import {useSession} from "next-auth/react";

const Skeleton = ({ children }: any) => {
  const [isLoading, setIsLoading] = useState(true)
  const { data: session } = useSession()
  const user = session?.user

  useEffect(() => {
    if (user){
      setIsLoading(false)
    }
  }, [user])

  return (
    <div>
      <MantineSkeleton visible={isLoading}>
        {children}
      </MantineSkeleton>
    </div>
  )
}

export default Skeleton
```

This works (shows skeleton):
```
  <Skeleton>
    <Avatar src={user?.image} size='md' />
  </Skeleton>
```

This doesn't work (doesn't show skeleton):
```
  <Skeleton>
    <Text>
      {user?.name}
    </Text>
  </Skeleton>
```

How can I make a reusable skeleton appear on all components I wish?

### What version of @mantine/hooks page do you have in package.json?

5.0.2

**Comment by rtivital** [comment]
Hi @atumas-bananamilk, please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by atumas-bananamilk** [comment]
It's hard to replicate because I use NextAuth sessions. A delay for simulating loading session data worked fine, however, when loading NextAuth session data that's inside `<Text>` component - doesn't work. But that ONLY HAPPENS with the `<Text>` component..

**Comment by rtivital** [comment]
You do not need NextAuth session for minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. Just create a sandbox that reproduces the issue and that we can use for debug purposes.

**Comment by rtivital** [comment]
Hi @atumas-bananamilk, if you can provide a reproduction, feel free to reopen the issue
