### ISSUE TITLE
headers have different names in controls and formats

### ISSUE THREAD

**Issue by Tno-MSA** [mantinedev/mantine#2148]
### What package has an issue

@mantine/rte

### Describe the bug

first of all, I'm not sure if this is related to the package section or the website ¯\_(ツ)_/¯

secondly, you are using different names for headers in both controls and formats without mentioning it!
in controls, we use: `["h1", "h2", "h3", "he", ..."h6"]`
but in formats, neither of `["h1", "h2", "h3", "h4"]` or `headers` (like react-quill) works! but the one that works is `header`

### What version of @mantine/hooks page do you have in package.json?

5.1.6

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

mention it in the docs or change it to `h1, h2, ...h6` like controls, or at least use `headers` like QuillJS.

**Comment by rtivital** [comment]
Formats prop is coming from quill, I'll add link to the docs.
https://quilljs.com/docs/formats/

**Comment by Tno-MSA** [comment]
> Formats prop is coming from quill, I'll add link to the docs. https://quilljs.com/docs/formats/

thanks!

**Comment by rtivital** [comment]
Documentation updated.
