### ISSUE TITLE
Skeleton with visible={false} and Overlay are not working well together

### ISSUE THREAD

**Issue by suchintan** [mantinedev/mantine#2153]
### What package has an issue

@mantine/core

### Describe the bug

Reproducable scenario here:
https://codesandbox.io/s/friendly-orla-kc4tjg?file=/src/index.js

TL;DR:

```
      <AppShell
        navbar={
          <Navbar width={{ base: 300 }} p="xs">
            <Skeleton height="100%" visible={false}>
              <Group spacing="xs" position="apart" noWrap>
                <Text size="xs">Stuff</Text>
                <Group spacing="xs" noWrap sx={{ float: "right" }} align="end">
                  <Text> Stuff </Text>
                </Group>
              </Group>
              <Overlay
                opacity={0.5}
                color="#000"
                blur={2}
                sx={{ width: "100vw", height: "100vh" }}
              />
            </Skeleton>
          </Navbar>
        }
        header={
          <Header height="100">
            <Text>Stuff</Text>
          </Header>
        }
      >
        <App />
      </AppShell>
```

An App-shell with a hidden Skeleton and a nested overlay cause the Overlay to only occupy the Navbar

![image](https://user-images.githubusercontent.com/3853670/185272825-f9405148-078b-4d81-b02e-ff98f6048370.png)

However, bringing the overlay outside of the Skeleton instance causes it to work as expected

```
      <AppShell
        navbar={
          <Navbar width={{ base: 300 }} p="xs">
            <Skeleton height="100%" visible={false}>
              <Group spacing="xs" position="apart" noWrap>
                <Text size="xs">Stuff</Text>
                <Group spacing="xs" noWrap sx={{ float: "right" }} align="end">
                  <Text> Stuff </Text>
                </Group>
              </Group>

            </Skeleton>
            <Overlay
                opacity={0.5}
                color="#000"
                blur={2}
                sx={{ width: "100vw", height: "100vh" }}
              />
          </Navbar>
        }
        header={
          <Header height="100">
            <Text>Stuff</Text>
          </Header>
        }
      >
        <App />
      </AppShell>
```

![image](https://user-images.githubusercontent.com/3853670/185272877-5a548683-927d-439c-a705-872920d03c34.png)

**Expected behaviour**: Hidden skeleton should not interfere with overlay

### What version of @mantine/hooks page do you have in package.json?

5.1.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/friendly-orla-kc4tjg?file=/src/index.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

I'm still quite new to React and front-end development, so I would have no idea about how to go about fixing this! You are a master @rtivital , and I'm learning so much by navigating this wonderful project you've built

**Comment by suchintan** [comment]
Deleting the `Skeleton` also makes it work as expected

**Comment by rtivital** [comment]
Hi @suchintan, it is expected behavior, Skeleton has position relative. Rendering Skeleton all time is required to prevent layout shifts. I recommend not to use Overlay inside Skeleton.

**Comment by suchintan** [comment]
That's interesting. So the expectation is to not use the visible property of the skeleton and just not render it instead?

I ended up scrapping this approach and used the Modals package with predefined modals instead. Do you know why the built in overlay in that doesn't conflict with skeleton?

**Comment by suchintan** [comment]
@rtivital I worked around this by wrapping my Skeleton in a conditional render. I was wondering if it would be possible to have the `visible` parameter just do something like that under the hood instead. What do you think?

```
export default function ConditionalWrapper({
  condition,
  wrapper,
  children,
}: ConditionalWrapperProps) {
  return condition ? wrapper(children) : children
}
```

```
export const isFetchingSkeletonWrapper = (
  children: React.ReactNode,
  isFetching: boolean
) => (
  <Skeleton height="100%" visible={isFetching}>
    {children}
  </Skeleton>
)
```

```
<ConditionalWrapper
      condition={isFetching}
      wrapper={(children) => isFetchingSkeletonWrapper(children, isFetching)}
    >
```
