### ISSUE TITLE
MultiSelect doesn't work with controlled react-hook-form after updating to v5.1.6

### ISSUE THREAD

**Issue by Tno-MSA** [mantinedev/mantine#2159]
### What package has an issue

@mantine/core

### Describe the bug

I had a working controlled `MultiSelect` (v5.0.0) field with `react-hook-form` (v7.33.1) using their `FormProvider` and `useFormContext`, but after updating to v5.1.6 and v7.34.2, this field, in particular, stopped accepting creatable values.

codesandbox link provided below

```javascript

<Controller
      name="tags"
      control={control}
      defaultValue={[]}
      render={({ field }) => (
        <MultiSelect
          {...field} //<= if this line is removed, it will work but you lost the controlled field benefits (v5.1.6 and v7.34.2).
          required
          clearable 
          creatable 
          searchable
          label="Tags"
          placeholder="Select or enter 3 tags"
          description="Select at least 1 tag"
          disabled={isLoading}
         data={tags} 
         limit={5} 
          maxSelectedValues={3} 
          maxDropdownHeight={160}
          getCreateLabel={(query) => `+ Create ${query}`} 
          error={errors?.tags?.message}
        />
      )}
    />

```

### What version of @mantine/hooks page do you have in package.json?

5.1.6

### If possible, please include a link to a codesandbox with the reproduced problem

[https://codesandbox.io/s/flamboyant-joana-e4e9u1](https://codesandbox.io/s/flamboyant-joana-e4e9u1)

**Comment by rtivital** [comment]
Update all `@mantine/` packages to 5.1.7 and make sure you are following creatable documentation – https://mantine.dev/core/multi-select/#creatable

**Comment by Tno-MSA** [comment]
> Update all `@mantine/` packages to 5.1.7 and make sure you are following creatable documentation – https://mantine.dev/core/multi-select/#creatable

done and done, but still doesn't work for me.

**Comment by rtivital** [comment]
I cannot recommend anything with react-hook-form as I do not use it, controlled component works as expected with useState and `@mantine/form` package – https://codesandbox.io/s/cocky-phoebe-6d286o?file=/src/App.tsx
