### ISSUE TITLE
Modal transition not working

### ISSUE THREAD

**Issue by SamuelLin95** [mantinedev/mantine#2166]
### What package has an issue

@mantine/modals

### Describe the bug

Opening the modal with transition effect does not work anymore. I have also tried the examples from the main website https://mantine.dev/core/modal/ section "Change transitions". They do not work as well. 

### What version of @mantine/hooks page do you have in package.json?

5.1.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/shy-brook-wjbk6d?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Modal transitions work as expected, most likely you are not seeing them because of your OS settings, if you want to disregard user reduced motion preference, you can change that in theme – https://mantine.dev/theming/theme-object/#respectreducemotion

**Comment by SamuelLin95** [comment]
Oh wow. I didn't know such option existed. It is working as expected now. Thanks a lot!
