### ISSUE TITLE
Multiselect new value not creatable by pressing enter

### ISSUE THREAD

**Issue by fynngoettert** [mantinedev/mantine#2167]
### What package has an issue

@mantine/core

### Describe the bug

I've use @mantine/core@4.2.2 in a project but needed to update to the newest version (5.1.7) for the new popup mechanics. 

In Version 4.2.2 in the Multiselect I could press enter when creating a new value and it directly created the value, but in the new version I have to click the create label to create the new value or press arrow-down to select the createLabel and then press enter.

My desired behavior is that when the user is in the multiselect field and wants to create a new data-item that they can simply press enter when the createLabel is shown (like it worked in 4.2.2), and not have to press arrow-down. I don't know if this is desired behavior for other use cases.

### What version of @mantine/hooks page do you have in package.json?

5.1.7

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/cool-yalow-ebxbu6?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by fynngoettert** [comment]
Alright, thank you.

**Comment by jfeaver** [comment]
How many people liked the 4.2.2 behaviour but didn't say anything because they didn't know it was going to change? We're probably switching to a different library for a creatable multiselect because of this issue. (Probably https://react-select.com/home)

**Comment by 7iomka** [comment]
@rtivital It is possible to somehow make a prop `selectOnEnterPress` that can add old-way behavior?
It is expected for most users that uses keyboard. When input receives focus, you type the text for a new option, and is expected behavior to have an action to finalize creation without advanced navigation with arrow keys.

**Comment by rtivital** [comment]
There are plans to revamp combobox components after 6.0 release. It is planned to provide more customization options that will allow different behaviors. As for now, there is no way of achieving it.
