### ISSUE TITLE
Dropzone file browser doesn't open after click or manual call on Chrome

### ISSUE THREAD

**Issue by svrakata** [mantinedev/mantine#2168]
### What package has an issue

@mantine/dropzone

### Describe the bug

Trying my own implementation and the docs examples.
Manual call `openRef.current()` is not working too.
Works fine with Firefox.
OS: Linux Mint 20.3
Chrome: Version 104.0.5112.101 (Official Build) (64-bit)

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Hi @svrakata, dropzone demo works as expected on mantine documentation website – https://mantine.dev/others/dropzone/#open-file-browser-manually

Please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by svrakata** [comment]
Hello @rtivital , thanks for the reply.
I guess it's related to this [issue](https://github.com/react-dropzone/react-dropzone/issues/1190) and cannot be helped.

**Comment by rtivital** [comment]
Okay, I guess it is react-dropzone issue then.
