### ISSUE TITLE
Install Dependencies Text overlap copy button

### ISSUE THREAD

**Issue by vatana7** [mantinedev/mantine#2171]
### Link to the page where something nasty is located

https://mantine.dev/guides/next/

### Exact quote of what is wrong

![image](https://user-images.githubusercontent.com/61142258/185640550-65828cea-4a2e-4cde-a543-bed9f746a7f1.png)

The copy button is overlapped by the text and I think we can avoid that by giving a background color to the Copy button. 

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Hi  @vatana7, feel free to send a PR, I suppose we should add a background color to copy button.

**Comment by vatana7** [comment]
Will do!

**Comment by vatana7** [comment]
May I ask where is the web repo for Mantine website?

**Comment by rtivital** [comment]
In this repository

**Comment by rtivital** [comment]
Fixed in 5.2.4
