### ISSUE TITLE
Misleading description for Container fluid prop

### ISSUE THREAD

**Issue by jvllmr** [mantinedev/mantine#2175]
### What package has an issue

@mantine/core

### Describe the bug

https://github.com/mantinedev/mantine/blob/8a2b20e7388d66fbb911c15f872ad1a545dd2e3b/src/mantine-core/src/Container/Container.tsx#L15

"always take 100% of width" makes me think that the Container has the css prop `width: 100%`, but in reality it has `max-width: 100%`. It took me 10 minutes and the devtools to find out that it follows the second behaviour. :(

### What version of @mantine/hooks page do you have in package.json?

^5.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Change description to `If fluid is set to true, size prop is ignored and Container can expand to 100% of width` or something similar (maybe reference the `max-width` prop as well)

**Comment by rtivital** [comment]
Can you send a PR with a fix?

**Comment by jvllmr** [comment]
Of course, will create it asap
