### ISSUE TITLE
Mantine + Tailwind issue

### ISSUE THREAD

**Issue by MariuzM** [mantinedev/mantine#2176]
### What package has an issue

@mantine/core

### Describe the bug

When using Mantine + Tailwind in my project, then importing Mantine Button component the Button does not have background only when hovering i see the background color. 

![Screen Shot 2022-08-20 at 11 24 18](https://user-images.githubusercontent.com/36937039/185728831-44029d1b-7b76-4435-8801-a826709e15ae.jpg)

If i remove `@tailwind base;` from index.css file then it starts showing 
![Screen Shot 2022-08-20 at 11 25 23](https://user-images.githubusercontent.com/36937039/185728856-58f92c30-49fd-4b0f-8755-5ed855c10318.jpg)

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://github.com/MariuzM/react-double-log-issue/tree/master

**Comment by rtivital** [comment]
Hi @MariuzM, you've installed a third-party library to your project that overrides Mantine styles. To fix that issue, either remove those styles or change emotion cache options to make Mantine styles override third-party library styles – https://mantine.dev/theming/emotion-cache/

**Comment by MariuzM** [comment]
The way i have done it is 

    <MantineProvider withGlobalStyles withNormalizeCSS>
      <App />
    </MantineProvider>
  
Then disabled `/* @tailwind base; */` in index.css

**Comment by MariuzM** [comment]
But also tried your suggestion also worked thank you

**Comment by andremonteiro95** [comment]
@MariuzM you don't have to remove the `@tailwind base;` import as it will probably create undesired side effects, you can just exclude Tailwind's preflight styles (https://tailwindcss.com/docs/preflight) in its configuration file (`tailwind.config.js`).

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx,jsx,js}'],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {},
  },
  plugins: [],
};
```
