### ISSUE TITLE
Title component does not respect inline=true 

### ISSUE THREAD

**Issue by Narcha** [mantinedev/mantine#2180]
### What package has an issue

@mantine/core

### Describe the bug

A `<Title inline>` element does not set `line-height` to 1 because the property is defined twice.
![grafik](https://user-images.githubusercontent.com/42248344/185744225-9810b15e-62c9-4b16-b0f3-c8986bf9a864.png)

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/optimistic-architecture-vj6t9f

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Amend [getLineHeight](https://github.com/mantinedev/mantine/blob/557d7728ccebfe2b15cf38ec2095efe83d81118c/src/mantine-core/src/Title/Title.styles.ts#L20) to return 1 if inline is set to true.

**Comment by rtivital** [comment]
Do you want to create a PR with a fix?

**Comment by Narcha** [comment]
I think I'll give this a try.

**Comment by Narcha** [comment]
Am I missing something, or does this if statement not do anything?
https://github.com/mantinedev/mantine/blob/0326f9b75525a1acebaf69ae569c7b4b394a6fd3/src/mantine-core/src/Title/Title.styles.ts#L21-L25
Or is line 22 supposed to say `return theme.headings.sizes[size].lineHeight;`?

**Comment by rtivital** [comment]
Yep, that is an error

**Comment by Narcha** [comment]
I'll fix that in the PR as well if that's ok
