### ISSUE TITLE
DropZone

### ISSUE THREAD

**Issue by guynaa** [mantinedev/mantine#2191]
### What package has an issue

@mantine/dropzone

### Describe the bug

Dropzone does not accept zip files on drag-n-drop when the appropriate mime type is selected (application/zip)

this happens on windows on both chrome/fireox

on mac, it works fine

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/misty-shape-3o1c3j

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Hi @guynaa, try using different zip mime types – https://stackoverflow.com/a/7027582

**Comment by guynaa** [comment]
@rtivital thanks, when i added those it did accept .zip files on windows as well,
1) why does it work differently on windows/mac?  (is this a mantine bug?)

2) what are the correct mimes to accept files, if i want to only accept .zip files? (the original list accepts .bin as well for example)
