### ISSUE TITLE
Mantine Select dropdown popup always appears with a horizontal scroll bar.

### ISSUE THREAD

**Issue by intelseb** [mantinedev/mantine#2197]
### What package has an issue

@mantine/core

### Describe the bug

Not sure how to access the styles for the Dropdown items because it hides on all clicks, 

The dropdown seems to appear with a horizontal scrollbar always, it looks like the content (width) of the dropdown itself is larger than the Select width.

![Screen Shot 2022-08-22 at 2 10 03 pm](https://user-images.githubusercontent.com/990614/185851141-8ae68717-55ce-49c7-b678-b8c5ff28ae73.png)

This doesnt seem to happen on the Mantine.dev https://mantine.dev/core/select/ documentation, but even if I wrap it in a fixed width div - similar to the demos I can reproduce it in a code-sandbox

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-forked-3yk9gm?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Not sure how to debug the styling :(

**Comment by rtivital** [comment]
Add withNormalizeCSS and withGlobalStyles to your MantineProvider – https://codesandbox.io/s/mantine-forked-oe191s?file=/src/App.tsx

**Comment by intelseb** [comment]
ah well this is embarrassing, thanks!
