### ISSUE TITLE
Fixed version of `embla-carousel-react` is required in peer dependencies rather than range of versions

### ISSUE THREAD

**Issue by mcmxcdev** [mantinedev/mantine#2200]
### What package has an issue

@mantine/carousel

### Describe the bug

A specific version of `embla-carousel-react` is required here https://github.com/mantinedev/mantine/blob/master/src/mantine-carousel/package.json#L27

Projects with strict peer dependencies setting will fail once `embla-carousel-react` version diverges.

It would be better to allow `^` so that patch and minor versions can be used. (There is an important 7.0.1 release since a couple of days)

### What version of @mantine/hooks page do you have in package.json?

5.1.6

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
fixed in 5.2.3
