### ISSUE TITLE
`styles` prop on `Accordion.Item` doesn't seem to do anything

### ISSUE THREAD

**Issue by mcmxcdev** [mantinedev/mantine#2202]
### What package has an issue

@mantine/core

### Describe the bug

I am trying to style `Accordion.Item` different based on if it contains a selected checkbox inside it or not.

According to provided mantine Typescript types this should work:

```
<Accordion.Item
      styles={{
        item: {
          backgroundColor: 'black',
          borderColor: 'red',

          '&[data-active]': {
            borderColor: 'green',
          },
        },
      }}
/>
```

But I can't seem to make it change styles at all. It also doesn't look like it is supported in the documentation:
https://mantine.dev/core/accordion/?t=styles-api

I know that its possible to style items directly through styles prop on `Accordion`, but that doesn't work for our use case of styling `Accordion.Item` differently based on a condition. 

### What version of @mantine/hooks page do you have in package.json?

5.1.6

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
It is expected behavior, you need to add styles to Accordion component, not Accordion.Item.

**Comment by anthonyalayo** [comment]
@rtivital what if we would like to modify the content class of an individual accordion item?
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Accordion/AccordionPanel/AccordionPanel.tsx#L44

I have been trying to figure out how to have a padding difference for one of them, but I can't seem to get anything working.

**Comment by anthonyalayo** [comment]
Update: I just happened to figure it out after asking. In case anyone else is also wondering, this is what you can do:

```
<Accordion.Panel sx={{ '.mantine-Accordion-content': { padding: 0 } }}>
...
</Accordion.Panel>
```
