### ISSUE TITLE
"@mantine/core" does not work in conjunction with React Native macOS App

### ISSUE THREAD

**Issue by reyzitwo** [mantinedev/mantine#2206]
### What package has an issue

@mantine/core

### Describe the bug

I created an application according to the [instructions](https://microsoft.github.io/react-native-windows/docs/0.64/rnm-getting-started), added packages using the command:
`yarn add @mantine/core @mantine/hooks @emotion/react`

When trying to import any component, an error occurs that react-dom is missing from node_modules, the instructions in the screenshot do not help:
<img width="300" alt="Снимок экрана 2022-08-22 в 22 54 14" src="https://user-images.githubusercontent.com/73870113/185988605-9df6e687-7031-4428-8f03-3ab3a5e65595.png">

After installing react-dom, importing components is not possible:
<img width="500" alt="Снимок экрана 2022-08-22 в 22 53 48" src="https://user-images.githubusercontent.com/73870113/185988851-963d0686-bf08-4b4e-8679-1add4aa782bf.png">

### What version of @mantine/hooks page do you have in package.json?

^5.2.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hi @reyzitwo, Mantine does not support react-native, it can be used with react-dom only (web). If you want to build a desktop application and still use Mantine I can recommend using Electon or tauri.

**Comment by reyzitwo** [comment]
Thank you tried tauri, everything works!
