### ISSUE TITLE
[Feature Request] Async and Creatable for Autocomplete/Select component

### ISSUE THREAD

**Issue by nghiepit** [mantinedev/mantine#221]
Hi, 
As the title, we need a way to load options from a remote source as the user types
https://react-select.com/async
And allow [creatable](https://react-select.com/creatable) a new option.

I Hope, The feature request should be added to [Roadmap](https://trello.com/b/e1AT7w4M/mantine-roadmap)

**Comment by rtivital** [comment]
Hi @nghiepit you can use dynamic data both with select and autocomplete components, see Autocomplete example – https://mantine.dev/core/autocomplete/#dynamic-data, I guess the only thing missing here is `onSearchChange` function in Select, it will be added in next minor release.

**Comment by nghiepit** [comment]
Thanks, @rtivital, so what about `Creatable`?

**Comment by rtivital** [comment]
I do not see the point of adding create option to autocomplete. For now you can do it on your own with custom item component and filtering function in Autocomplete, Select and MultiSelect components (after `onSearchChange` is implemented). Maybe this feature will be added separately in future releases.
