### ISSUE TITLE
Multiple Radio inputs can't be tabbed between

### ISSUE THREAD

**Issue by tlqvst** [mantinedev/mantine#2211]
### What package has an issue

@mantine/core

### Describe the bug

When using multiple <Radio.Group>'s, you can only tab to the first group, or the last one if you're tabbing from below. I think this means forms with multiple radio groups aren't fully accessible, unless I'm missing something. See the demo link.

### What version of @mantine/hooks page do you have in package.json?

5.2.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-multiple-radio-inputs-ybyzm9?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hi @tlqvst, like in regular html inputs with type="radio" it is required to set name on those inputs in order for them to work correctly – https://codesandbox.io/s/mantine-multiple-radio-inputs-forked-qm5sr6?file=/src/App.tsx

**Comment by tlqvst** [comment]
Thank you so much!
