### ISSUE TITLE
Fix nested pre/code styles with TypographyStylesProvider

### ISSUE THREAD

**Issue by dasveloper** [mantinedev/mantine#2219]
### What package has an issue

@mantine/core

### Describe the bug

When converting Markdown to HTML code blocks like this:

\```
{
  "firstName": "John",
  "lastName": "Smith",
  "age": 25
}
\```

is converted to nested pre/code tags like this:
```
<pre>
  <code> 
    {
      "firstName": "John",
      "lastName": "Smith",
      "age": 25
    }
  </code>
</pre>
```

When that HTML is wrapped in a TypographyStylesProvider, inline code styles are applied to the code tags and then block code styles are applied to the pre tags, creating a broken looking nested styling like this:
<img width="574" alt="Screen Shot 2022-08-23 at 7 20 17 PM" src="https://user-images.githubusercontent.com/28981975/186300789-18a3a08f-553f-4c88-820f-d690fe9264c3.png">
 
 Instead, any code tags wrapped in a pre tag should not have the inline styles applied.

### What version of @mantine/hooks page do you have in package.json?

none

### Do you know how to fix the issue

No

### Possible fix

Issue is coming from here where code and pre are styled indepenently:
https://github.com/mantinedev/mantine/blob/c7d080c2133b0196e3a8382ec6134838632c8f9a/src/mantine-core/src/TypographyStylesProvider/TypographyStylesProvider.styles.ts#L92

Possibly use CSS not selector to target code that isn't direct descendant of pre:
https://stackoverflow.com/questions/23853931/how-can-i-style-code-only-if-its-parent-is-not-pre

**Comment by rtivital** [comment]
Fixed in 5.2.4
