### ISSUE TITLE
<ColorInput> not working when inside a <Drawer>

### ISSUE THREAD

**Issue by arindamghoshal** [mantinedev/mantine#222]
The <ColorInput> is not working when inside a <Drawer> component. Please refer the sample code at https://codesandbox.io/s/nostalgic-tereshkova-xvvxy to reproduce the same.

**Comment by rtivital** [comment]
Thanks for reporting, this will be fixed in next patch

**Comment by rtivital** [comment]
Fixed in [2.3.2](https://github.com/mantinedev/mantine/releases/tag/2.3.2)
To use color input in modal and drawer set `dropdownZIndex={1000}` prop

**Comment by arindamghoshal** [comment]
> Fixed in [2.3.2](https://github.com/mantinedev/mantine/releases/tag/2.3.2)
> To use color input in modal and drawer set `dropdownZIndex={1000}` prop

Thanks @rtivital for the quick fix.
