### ISSUE TITLE
RingProgress should not render Tooltip if no tooltip is provieded

### ISSUE THREAD

**Issue by sep2** [mantinedev/mantine#2220]
### What package has an issue

@mantine/core

### Describe the bug

In our grid we render a large number of `RingProgress` components but did not provide `tooltip` in the `sections` props, however in the [code](https://github.com/mantinedev/mantine/blob/42098c2bc6b8eb40f071a073fbeb46202004cf08/src/mantine-core/src/RingProgress/Curve/Curve.tsx#L37) there is no way to avoid the extra tooltip components being rendered, results in a bunch of (hundreds of) empty divs in the page.

```html
<div>
<div dir="ltr">
<div class="mantine-Tooltip-tooltip mantine-1lf7an" style="z-index: 300; display: none; left: 0px;"></div>
</div>
</div>
```

![2022-08-24_11-03](https://user-images.githubusercontent.com/39055101/186311407-f894190d-3a5b-4840-93a8-0b561c2eb701.png)

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Don't render anything for tooltip if it is disabled.

**Comment by sep2** [comment]
[This issue](https://github.com/mantinedev/mantine/discussions/1919) maybe related and could possibly be fixed in one go.

**Comment by rtivital** [comment]
Fixed in 5.2.4

**Comment by sowizz** [comment]
@rtivital this is also a problem with the latest v6 release (6.0.21). Any idea how to prevent this?

As soon as I render 4 RingProgress I get 12 portals (btw I'd expect 8, because I have 4 RingProgress components, 2 sections each).


![image](https://github.com/mantinedev/mantine/assets/1541634/d8f431c6-7998-4519-aab6-f40904832142)

**Comment by sowizz** [comment]
Applying the same solution as in #[50d4e64](https://github.com/nmay231/mantine/commit/50d4e644bb190a7966ccfc87a77784692f9ebf87) seems to fix the issue.
