### ISSUE TITLE
Select with ScrollArea

### ISSUE THREAD

**Issue by wildsonc** [mantinedev/mantine#2226]
### What package has an issue

@mantine/core

### Describe the bug

The dropdown is getting hidden when passing the ScrollArea maxHeight, is it possible for it to be visible?

<img width="291" alt="image" src="https://user-images.githubusercontent.com/72408418/186541941-7c0a966c-5ac3-4de5-9ee2-10af1b20485e.png">

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/throbbing-cloud-ux6bm6?file=/src/App.tsx

**Comment by rtivital** [comment]
https://codesandbox.io/s/interesting-wilson-zh0s0b
