### ISSUE TITLE
NotAllowedError - Document is not focused

### ISSUE THREAD

**Issue by Slapbox** [mantinedev/mantine#2227]
### What package has an issue

@mantine/core

### Describe the bug

I'm not clear on what exactly causes this, but it's somehow related to our use of Mantine's tooltips (we've never seen the error before we started using them.)

It may be related to using `events={ focus: true }` but I'm not certain.

Note that all 5 errors in the logbox are the same error, "Document is not focused."

![image](https://user-images.githubusercontent.com/6835891/186549079-a397b602-9a59-40eb-9411-7f3aa08e1a29.png)

### What version of @mantine/hooks page do you have in package.json?

5.2.3

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Hi @Slapbox, please provide a sandbox or repository with minimal reproduction

**Comment by rtivital** [comment]
Hi @Slapbox, feel free to reopen the issue if you can provide a reproduction
