### ISSUE TITLE
onChange event isn't triggered when clearing a Select

### ISSUE THREAD

**Issue by jfilby** [mantinedev/mantine#2232]
### What package has an issue

@mantine/core

### Describe the bug

There are two ways to clear a Select:
- Reselect the selected item
- Click the x icon on the right-side of the Select

Neither approach fires the onChange event.

### What version of @mantine/hooks page do you have in package.json?

^5.1.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Select component works as expected on codesandbox – https://codesandbox.io/s/restless-dawn-frv2ly?file=/src/App.tsx

**Comment by jfilby** [comment]
It was my own error in a more complex function. But thanks for reviewing the issue!
