### ISSUE TITLE
Missing TypeScript typings for color shadings in <Text>

### ISSUE THREAD

**Issue by hornta** [mantinedev/mantine#2243]
### What package has an issue

@mantine/core

### Describe the bug

The `<Text>` component color type `MantineColor` has only the base color names as possible colors. It would be good to extend that type with the different color shades.

I found out I could write `<Text color="red.7">` but I had no idea I could do that since the types didn't include this color shade.

**Comment by rtivital** [comment]
See https://github.com/mantinedev/mantine/pull/2130#issuecomment-1216558970
