### ISSUE TITLE
Warning "Cannot update a component" message while using <ColorInput />

### ISSUE THREAD

**Issue by arindamghoshal** [mantinedev/mantine#225]
Getting this warning message in Code Sandbox Console - 
Warning: Cannot update a component (@mantine/core/ColorInput) while rendering a different component (@mantine/core/ColorPicker).

Link to sample code to reproduce the warning - https://codesandbox.io/s/prod-moon-zvttl

Steps to reproduce the warning - 

1. Click on the Open Drawer button
2. Click on the ColorInput
3. Select a color.

**Comment by rtivital** [comment]
Released in [2.4.0](https://github.com/mantinedev/mantine/releases/tag/2.4.0)
