### ISSUE TITLE
@mantine/ds mantine svg icon is not round

### ISSUE THREAD

**Issue by teaguestockwell** [mantinedev/mantine#2255]
### What package has an issue

@mantine/core

### Describe the bug

Hello,

I would like to add the Mantine icon to simple icons. While doing this, I noticed that the svg icon appears to be very slightly out of round. Is this expected? If not is there another source that I should use for this? Thanks 😄 

https://github.com/simple-icons/simple-icons/pull/7633

### What version of @mantine/hooks page do you have in package.json?

na

**Comment by rtivital** [comment]
Well, yeah, it is not perfectly round, if you want you can resize it in figma or other editor that supports svg

**Comment by LitoMore** [comment]
@teaguestockwell You could pick the icon from https://github.com/mantinedev/mantine/blob/f2da0287bfcda19dcf7866f4d03a05d1ee7b49f7/docs/src/images/logo.svg for Simple Icons.

The circle here is the correct one:

```html
<rect width="30" height="30" fill="#339AF0" rx="15"/>
```

**Comment by LitoMore** [comment]
### Out of this topic

We are using `163` as `height` for the `viewBox`. Maybe we could use another more friendly value (like `240`, `240` can be divided by `[2, 3, 4, 5, 6, 8, 10, 12, ...]`) instead.
