### ISSUE TITLE
use-local-storage always returns the initial value

### ISSUE THREAD

**Issue by mkroemer** [mantinedev/mantine#2266]
### What package has an issue

@mantine/hooks

### Describe the bug

I try to use the localStarage hook but after each page reload, the storage is set to the default values. Codesandbox is attached.

``` typescript
    const initialValues: FormValues = { name: 'Bob', occupation: 'Tester' };
    const [value, setValueStorage] = useLocalStorage({ key: 'user-form', defaultValue: initialValues });
    const form = useForm<FormValues>({ initialValues: value });
```

### What version of @mantine/hooks page do you have in package.json?

5.2.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/exciting-swirles-dfeyqs

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
@zhulien-ivanov, seems like this is caused by your changes, can you have a look?

**Comment by zhulien-ivanov** [comment]
The hook itself works fine: https://codesandbox.io/s/admiring-varahamihira-w0h1wk?file=/src/App.tsx. It is caused by the interaction between `useForm` and/or `debounced` somehow, I'll have to investigate.

By the way, the reported version is `5.2.4` but the sandbox you provided uses `5.2.3`. When were the changes to the hook released @rtivital ?

**Comment by zhulien-ivanov** [comment]
I just checked and the problem is introduced in `5.1.4`:

Version `5.1.3`: https://codesandbox.io/s/sleepy-hodgkin-77f8g4?file=/src/App.tsx
Version `5.1.4`: https://codesandbox.io/s/eloquent-sunset-w5ip3q?file=/src/App.tsx

**Comment by mkroemer** [comment]
Thank you, I checked and can confirm that `getInitialValueInEffect: false` solves the issue.

**Comment by rtivital** [comment]
Okay, great, thanks for investigation @zhulien-ivanov!
