### ISSUE TITLE
`hovered` option on Autocomplete does not respect passed classnames

### ISSUE THREAD

**Issue by pdevito3** [mantinedev/mantine#2268]
### What package has an issue

@mantine/core

### Describe the bug

When using the `hovered` property on the autocomplete control, the classes passed are not honored. In the code sandbox example posted here, I'd expect the hover background to be red and it isn't.

### What version of @mantine/hooks page do you have in package.json?

5.2.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-quirks-pk5p9w?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Thanks for reporting, `hovered` and other outdated selectors will be removed from styles api table in next patch

**Comment by pdevito3** [comment]
Gotcha. Is that in the docs anywhere? Didn't see it on the notes for the components or even the styles api page

**Comment by rtivital** [comment]
Fixed in 5.2.5
