### ISSUE TITLE
modal doesn't go back to right tab index on close

### ISSUE THREAD

**Issue by HermanNygaard** [mantinedev/mantine#227]
it resets tab index, doesn't go back to the button that triggered it 
https://mantine.dev/core/modal/

**Comment by rtivital** [comment]
Alright, I've built this feature, here is an [implementation](https://github.com/mantinedev/mantine/blob/next-minor/src/mantine-hooks/src/use-focus-return/use-focus-return.ts) if anybody is interested.
This feature will be released in 2.4.0 release (September 8th)

**Comment by rtivital** [comment]
Released in [2.4.0](https://github.com/mantinedev/mantine/releases/tag/2.4.0)
