### ISSUE TITLE
Tooltip not working on mobile devices

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#2270]
### What package has an issue

@mantine/core

### Describe the bug

It is expected behavior when any tooltips not working on mobile devices?
It not opening on real mobile device (in my case xiaomi redmi note 7 pro), nor in chrome devtools in mobile mode.

### What version of @mantine/hooks page do you have in package.json?

latest

### Possible fix

Add touch events alongside with mouse events too or another fix

**Comment by zhulien-ivanov** [comment]
You have to allow `touch` event throught the `events` property of `Tooltip` - https://mantine.dev/core/tooltip/#change-events.
