### ISSUE TITLE
Color scheme flicker when color-scheme is dark (localstorage)

### ISSUE THREAD

**Issue by AdisonCavani** [mantinedev/mantine#2274]
### What package has an issue

@mantine/core

### Describe the bug

Steps to reproduce:
- open [mantine.dev](https://mantine.dev) in incognito window without any extensions
- page loads with light theme
- click theme icon in top right corner in order to switch theme to dark
- refresh page, see - page loads in light theme and flickers to dark

This also happens on my website (also using localstorage), so it's not mantine.dev related issue

### What version of @mantine/hooks page do you have in package.json?

^5.2.3

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
It is expected, mantine.dev is a static website that is prerendered with light color scheme. In your application you can use cookie to avoid that – https://mantine.dev/guides/dark-theme/#save-color-scheme-in-cookie
There are other similar discussions, if you want a more deep explanation, check out discussions –  https://github.com/mantinedev/mantine/discussions
