### ISSUE TITLE
Autocomplete data grouping does not work perfectly when data is updated

### ISSUE THREAD

**Issue by RedFour** [mantinedev/mantine#2278]
### What package has an issue

@mantine/core

### Describe the bug

![image](https://user-images.githubusercontent.com/3815691/187307214-2df590d4-6eab-4ae3-88ec-d8340d8731f6.png)

I posted a screenshot showing the issue. Item2 has group Item3. But when I add two new items also with group Item3, they are group by themselves.

The actually data has no difference between the groups. This issue only resolves itself when I refresh the app completely. All three items will be with the same group. 

The issue only happens when I update the data behind Autocomplete.

### What version of @mantine/hooks page do you have in package.json?

5.2.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by zhulien-ivanov** [comment]
Please, include a codesandbox representing the issue.

**Comment by RedFour** [comment]
https://codesandbox.io/s/silly-banach-8yotvi?file=/src/App.js

**Comment by rtivital** [comment]
@achmurali can you have a look at this?

**Comment by zhulien-ivanov** [comment]
I found where the issue is. I'll post a PR with a fix in a couple of hours.
