### ISSUE TITLE
Select cannot be used inside of Card

### ISSUE THREAD

**Issue by my-name-was-already-taken** [mantinedev/mantine#228]
The @mantine/core 2.3.2 component Select cannot be used inside of a Card component, as the select option dropdown is cut off inside of the Card.
Same most likely applies to Autocomplete, MultiSelect, DatePicker etc.

A code sandbox showing the issue can be found here: https://codesandbox.io/s/select-cannot-be-used-in-card-wcqp9?file=/src/App.js

**Comment by rtivital** [comment]
This is determined by Card default overflow style, you can set it to visible to make it work – https://codesandbox.io/s/select-cannot-be-used-in-card-forked-d0vhn

**Comment by my-name-was-already-taken** [comment]
I'm sorry for not noticing myself and having wasted your time! And - thank you for creating this awesome library, it's both great to look at and to work with.

Somewhat related PS: should the default overflow style for Drawer be set to overflow: auto, so that scrollbars appear if needed (at least vertically)? I'd assume that's the more generally used way for drawers than cutting off the overflow...?

**Comment by rtivital** [comment]
Not sure about Drawer, if you experience any issue or think that it can be done better, please create new issue with example
