### ISSUE TITLE
Full screen modal content layout shift when OS scrollbar visible 

### ISSUE THREAD

**Issue by Hurtak** [mantinedev/mantine#2283]
### What package has an issue

@mantine/core

### Describe the bug

When on macOS with visible scrollbars (eg when mouse is connected) the fullscreen modal has layout shift when opening it (probably related to the scrollbar hiding/showing)

https://user-images.githubusercontent.com/6587821/187374287-fff9d166-e1e6-4277-bed3-8b18dce55785.mov

### What version of @mantine/hooks page do you have in package.json?

same version as docs https://mantine.dev/core/modal/

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/modal/

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by epicmau5time** [comment]
Have also been experiencing this with the full screen modals

**Comment by wes337** [comment]
Happens in Windows too. Yes, probably because of the scrollbar disappearing.

Instead of hiding the scrollbar, maybe a better solution would be the new "inert" HTML attribute. It was added in 2022 but has pretty good browser support right now (and a polyfill): https://developer.chrome.com/articles/inert/, https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert

**Comment by epicmau5time** [comment]
I should add that a temporary workaround I have been using is setting the width to "100vw" on the modal inline style. Avoids the jumping of the fullscreen modal width.

```javascript
function ModalTest() {
	const [opened, setOpened] = useState(false);

	return (
		<>
			<Modal
				opened={opened}
				onClose={() => setOpened(false)}
				title="This is fullscreen modal!"
				fullScreen
				style={{ width: "100vw" }}
			>
				{Array.from({ length: 1000 }).map((_, index) => (
					<span key={index}>testing {index} </span>
				))}
			</Modal>

			<Group position="center" mt={50}>
				<Button onClick={() => setOpened(true)}>Open Modal</Button>
			</Group>
			<div style={{ height: 1000 }}></div>
		</>
	);
}
```
