### ISSUE TITLE
Error when using Select and creating a production build

### ISSUE THREAD

**Issue by mihbog-atra** [mantinedev/mantine#2290]
### What package has an issue

@mantine/core

### Describe the bug

Hello,

I am trying to use the <Select> component (after switching from Autocomplete which worked fine).
Dev build looks ok and works as expected, but as soon as I try to use the production build, I encounter a white page and it fails with:
Uncaught SyntaxError: Unexpected token '<' (at main.db184f0d.js:1:1)

After reverting to Autocomplete, looks fine again.

Thanks in advance!

### What version of @mantine/hooks page do you have in package.json?

5.0.0

**Comment by nmay231** [comment]
That error looks like you're somehow importing an HTML file like it's javascript. That is not an issue with Mantine, but with your bundler (like webpack). I would delete the output directory (probably something like `build/`) and rebuild.

**Comment by rtivital** [comment]
Hi @mihbog-atra, most likely your issue is not related to Mantine, it may be caused by your build system. If you can provide a repository with **minimal** reproduction, I can have a look.

**Comment by rtivital** [comment]
@nmay231 feel free to reopen the issue if you can provide a reproduction.
