### ISSUE TITLE
DatePicker throws error if minDate falls on a future page

### ISSUE THREAD

**Issue by micaww** [mantinedev/mantine#2293]
### What package has an issue

@mantine/dates

### Describe the bug

Setup:
- Today is Aug 30, 2022
- minDate is set to Sept 8, 2022 (or any date in the future that wouldn't show on this calendar month)

Once the DatePicker is opened, it immediately throws an error because `firstIncludedDay` is undefined and passed into `isSameDate` here https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/Month/Month.tsx#L258

It's undefined because there are no "included days" in the entire month being displayed, as the minDate is past all of the days displaying on the first page.

### What version of @mantine/hooks page do you have in package.json?

4.2.12 (still present in v5)

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

A fix for the linked line could be this:

```js
firstInMonth={firstIncludedDay ? isSameDate(date, firstIncludedDay) : false}
```

**Comment by rtivital** [comment]
It does not throw any errors in v5 – https://codesandbox.io/s/loving-varahamihira-d9t8fn?file=/src/App.tsx
Can you provide a sandbox that throws?

**Comment by rtivital** [comment]
@micaww feel free to reopen the issue if you can provide a sandbox with reproduction
