### ISSUE TITLE
The DatePicker component is blocked by the upper one in it's doc's demo.

### ISSUE THREAD

**Issue by RE0x2A** [mantinedev/mantine#2300]
### Link to the page where something nasty is located

https://mantine.dev/dates/getting-started/

### Exact quote of what is wrong

![image](https://user-images.githubusercontent.com/20656708/187680119-50a3475d-74c4-454f-9eb5-55eb5dc1a69a.png)

It looks weird.😂

**Comment by rtivital** [comment]
Thanks for reporting, the issue will be fixed with next patch

**Comment by rtivital** [comment]
Fixed
