### ISSUE TITLE
inputWrapperOrder prop of PasswordInput Component console error: Warning: React does not recognize the `inputWrapperOrder` prop on a DOM element.

### ISSUE THREAD

**Issue by jackyleefu** [mantinedev/mantine#2308]
### What package has an issue

@mantine/core

### Describe the bug

inputWrapperOrder prop of PasswordInput
console error: Warning: React does not recognize the `inputWrapperOrder` prop on a DOM element.

### What version of @mantine/hooks page do you have in package.json?

v5.2.4

**Comment by rtivital** [comment]
Thanks for reporting, the issue will be fixed in next patch

**Comment by DhrjArun** [comment]
I am not sure how to reproduce this issue.

**Comment by rtivital** [comment]
Fixed in 5.3.0
