### ISSUE TITLE
[Feature Request] Support number of months to render in DatePicker and DateRangePicker

### ISSUE THREAD

**Issue by nghiepit** [mantinedev/mantine#232]
Hey,

This is a feature request for `DatePicker `, `DateRangePicker`.
Most of the date ranger picker libraries support multiple months.

![datepicker](https://raw.githubusercontent.com/airbnb/react-dates/master/react-dates-demo.gif)

**Comment by rtivital** [comment]
Hi @nghiepit this feature is out of current scope and I will not work on it in the next six months. I'm leaving this with "help wanted" badge, if you or anybody else is interested in working on this ping me here and I'll provide some basic instructions.

**Comment by rtivital** [comment]
Released in 3.2
