### ISSUE TITLE
RichTextEditor paste error with @mantine/form

### ISSUE THREAD

**Issue by mvskvortsov** [mantinedev/mantine#2328]
### What package has an issue

@mantine/rte

### Describe the bug

I use RichTextEditor with getInputProps from @mantine/form in my form.
Then I'm trying to paste some text in the end of text after some empty symbol (space, new line) nothing happens. If I paste text in some other text it works but cursor stays in old place - do not move to the inserter text end.
If I use simple "controlled" case (value - onChange) all works fine.

I use getInputProps with index - {...getInputProps(`blocks.${idx}.richtext`)}

### What version of @mantine/hooks page do you have in package.json?

5.2.4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by mvskvortsov** [comment]
I found some workaround)
I simply use form field values without getInputProps. Something like this:
`value={values.blocks[idx].richtext} onChange={(value) => setFieldValue(`blocks.${idx}.richtext`, value)}`
I think problem is in the getInputProps function.

**Comment by rtivital** [comment]
Okay, please use your workaround for now, rte package is planned to be revamped in 6.0, and I do not think that fixing issues with current implementation will worth the effort.
