### ISSUE TITLE
React.ComponentProps returns {} with Mantine components

### ISSUE THREAD

**Issue by Narcha** [mantinedev/mantine#2330]
### What package has an issue

@mantine/core

### Describe the bug

I'm not sure if this is a bug with Mantine or with React.
If I use `React.ComponentProps` or similar generics on Mantine components (I tested this on `Button` and `Text`), instead of returning the component props, it returns `{}`.

I've been trying to add a wrapper component around `Button`, which keeps all of its props and adds one more.
I tried setting the props of my wrapper to something like this:
```
type MyButtonProps = {addedProp: string} & React.ComponentProps<typeof Button>;
```
but this resulted in `type MyButtonProps = {addedProp: string}`.
Is there any other way than using `ComponentProps` to achieve the same behavior?

I made a [sandbox](https://codesandbox.io/s/determined-wave-7my42u?file=/src/App.tsx) demonstrating this.

### What version of @mantine/hooks page do you have in package.json?

5.2.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/determined-wave-7my42u?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Hi @Narcha, it is not an issue: Button and other similar components are polymorphic, it means that their props are calculated dynamically based on generic argument that is controlled by `component` prop. You can import types of all components from a corresponding package, for example `import type { ButtonProps } from '@mantine/core';`:

```ts
import React from 'react';
import { ButtonProps } from '@mantine/core';

interface MyButtonProps extends ButtonProps, React.ComponentPropsWithoutRef<'button'> {
  newProp: string;
}
```

**Comment by Narcha** [comment]
Thank you! I knew that they were polymorphic, I just assumed React would use the default component ("button" in this case).
