### ISSUE TITLE
Checkbox has default cursor

### ISSUE THREAD

**Issue by kimfucious** [mantinedev/mantine#2332]
### What package has an issue

@mantine/core

### Describe the bug

Normally a checkbox's cursor is set to "pointer" by default.

However, it appears that this is not the case with the Checkbox component.

I've tried forcing it with styles and wrapperProps, but to no avail.

If this is not a bug, can you please let me know how to change the pointer style on the box and the label.

Thanks!

### What version of @mantine/hooks page do you have in package.json?

5.2.4

### Do you know how to fix the issue

No

**Comment by zhulien-ivanov** [comment]
https://mantine.dev/theming/theme-object/#cursortype.

**Comment by kimfucious** [comment]
Thanks for that super fast response, @zhulien-ivanov
