### ISSUE TITLE
Custom `monthPickerControl` styles overriding `monthPickerControlActive` styles on `DatePicker`

### ISSUE THREAD

**Issue by pdevito3** [mantinedev/mantine#2333]
### What package has an issue

@mantine/dates

### Describe the bug

When you select a date using the `DatePicker` control, it will not apply `monthPickerControlActive` styles when `monthPickerControl` styles supplied. The active styles do get applied when monthPickerControl` styles are removed.

The same happens for `YearPickerControls`

### What version of @mantine/hooks page do you have in package.json?

5.2.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-datepicker-styling-issue-ypdqjg?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Hi @pdevito3, DatePicker works as expected with `createStyles` function and `styles` prop (recommended way of applying styles). We provide support only for built-in Mantine styling solution with emotion, if you've decided to use a third-party styling library, then it's up to you to figure it out how to apply styles correctly – unfortunately, we cannot help with it.

**Comment by pdevito3** [comment]
heard that you can't support other libs, but for what it's worth, this happens whenever you you `classNames` regardless of lib. Here it happens with vanilla CSS: 
https://codesandbox.io/s/mantine-datepicker-styling-issue-forked-t45d7r?file=/src/App.tsx

**Comment by rtivital** [comment]
Well, it is not planned to be fixed with current implementation, in version 6.0 it will be migrated to `data-` attributes like in other components. For now, you can use several workarounds:
- Use createStyles or styles
- Increase specificity – https://codesandbox.io/s/mantine-datepicker-styling-issue-forked-e0pn3q?file=/src/App.tsx
- Or just use !important
