### ISSUE TITLE
DatePicker weekdays order with muslim/israel locale

### ISSUE THREAD

**Issue by Gallevy** [mantinedev/mantine#2334]
### What package has an issue

@mantine/dates

### Describe the bug

DatePicker doesn't start the week on the correct day for israel (and many more muslim countries)

Current @mantine/dates DatePicker:
![mantine-dates-original](https://user-images.githubusercontent.com/17080607/188283592-1a1343bf-e22a-4704-8164-dc6bfd7ecff3.png)

As explained here: https://en.wikipedia.org/wiki/Workweek_and_weekend

Example from windows 10 on how it should look like:
![mantine-dates](https://user-images.githubusercontent.com/17080607/188283581-85d5b5ea-565c-40f4-8875-6a4c8c7f296f.png)

As we can see, the week in Israel should start from `א` and not from `ב`
weekendDays doesn't solve this issue since the calendar still starts the week on the wrong day.
As far I checked, there is no current solution for this issue, 

### What version of @mantine/hooks page do you have in package.json?

5.2.4

**Comment by rtivital** [comment]
The issue will be resolved in 6.0 version

**Comment by rtivital** [comment]
Hi @DhrjArun, this issue is already fixed in private dates revamp repository

**Comment by DhrjArun** [comment]
ok

**Comment by rtivital** [comment]
Fixed in 6.0
