### ISSUE TITLE
useLocalStorageValue update issue

### ISSUE THREAD

**Issue by Sakkhor909** [mantinedev/mantine#2340]
### What package has an issue

@mantine/hooks

### Describe the bug

I have used @mantine/hooks 3.6.9 and there was no problem for geting an object from useLocalStorageValue hooks to set the theme of my Next JS website. But Today I updated @mantine/hooks to 5.2.5

It shows error immediately like this,
```
error - pages\_app.js (21:61) @ MyApp
TypeError: (0 , _mantine_hooks__WEBPACK_IMPORTED_MODULE_4__.useLocalStorageValue) is not a function or its return value is not iterable

> 21 |   const [colorScheme, setColorScheme] = useLocalStorageValue({
     |                                                             ^
  22 |     key: "mantine-color-scheme",
  23 |     defaultValue: "light",
  24 |   });
```

### What version of @mantine/hooks page do you have in package.json?

5.2.5

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Hook was renamed – https://mantine.dev/hooks/use-local-storage/
You should check release notes for breaking changes when updating to next major version.
