### ISSUE TITLE
Interesting text input suggestions

### ISSUE THREAD

**Issue by Hexa-IT** [mantinedev/mantine#2344]
### What package has an issue

@mantine/core

### Describe the bug

I'm getting some weird suggestions in chrome when entering something the the `TextInput` component

![Report](https://user-images.githubusercontent.com/34255516/188320802-738621d2-2f47-41a3-b4ed-027da5e0a27d.PNG)

### What version of @mantine/hooks page do you have in package.json?

5.2.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by zhulien-ivanov** [comment]
This is browser's native autocomplete suggestions, not related to Mantine.

**Comment by rtivital** [comment]
Hi @Hexa-IT, usually these suggestions are based on `name` and `id` attributes, try setting those attributes on your input:

```tsx
<TextInput name="your-input-name" id="your-input-id" />
```

**Comment by Hexa-IT** [comment]
Hi I'm back ;) It's amazing to see what Mantine has become in such a relatively short period.
But this "problem" persists. I can't see how this is not related to mantine my code: `<TextInput />`
And that gives me the following suggestions:

![Untitled](https://user-images.githubusercontent.com/34255516/212186363-e6b37a14-cfbf-4351-88f7-e634bb1bbfa9.png)

I mean it isn't a big probleem of course but I'm just very curious what causes this behavior maybe there is some kind of caching being committed?

**Comment by rtivital** [comment]
Have you set `name` and `id` attributes?

**Comment by Hexa-IT** [comment]
> Have you set `name` and `id` attributes?

No I haven't I'm using the bare `<TextInput />` component without any attributes. I know setting the `name` and `id` attributes fixes this like you stated above. But I'm just curious why these suggestions pop up when not setting the `name` and `id` attributes.

**Comment by rtivital** [comment]
Because ids that are automatically generated are not unique and are repeated for different inputs on different pages
