### ISSUE TITLE
RichTextEditor with Next.js

### ISSUE THREAD

**Issue by wildsonc** [mantinedev/mantine#2350]
### What package has an issue

@mantine/rte

### Describe the bug

Only when I paste (CMD+V) an image raise the error, even with strict mode disabled:
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/72408418/188331920-40c74f1d-fd31-43e9-ac57-f1ae52eb0f00.png">

**next.config.js**
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
};

module.exports = nextConfig;
```
If I insert the image through the button, it works as expected.

### What version of @mantine/hooks page do you have in package.json?

5.2.5

### If possible, please include a link to a codesandbox with the reproduced problem

Can reproduce in https://mantine.dev/others/rte/#images-upload

### Do you know how to fix the issue

No

**Comment by pauloendoh** [comment]
I'm having this problem as well. Only when copy pasting images on latest NextJS version.
