### ISSUE TITLE
`DatePicker` can't accept date only ISO 8601 strings like normal html input

### ISSUE THREAD

**Issue by pdevito3** [mantinedev/mantine#2363]
### What package has an issue

@mantine/dates

### Describe the bug

So maybe I'm missing something, but I can't get the datepicker to play nice with ISO 8601 formatted strings. 

My api layer is passing in dates formatted like `2022-09-06` on par with ISO 8601, and while a normal date input can handle this just fine (see example), the mantine datepicker has some issues. Particularly, it seems to store the value (potentially*) properly, but not display it in the input.

> *Note in the example I also need an `onChange` event to have it store the proper value, otherwise it will apply a timezone to the date. 

Seems off that a control meant to pick only a date need to have hoops jumped through like this, but hopefully I'm just missing something! Couldn't figure it out with the discord group.

### What version of @mantine/hooks page do you have in package.json?

5.2.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/dateformat-for-mantine-forked-0zxjcu?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

i've tried integrating dayjs options on the `value` prop as well as several other things to no avail.

**Comment by rtivital** [comment]
DatePicker component value is a Date object, it does not support strings or other values – you need to convert your string date into the Date object before passing it to the component.

**Comment by pdevito3** [comment]
Yeah, I hear you. 

Guess this should have been more of a feature enhancement discussion on discord to help people avoid all the gymnastics for date only workflows. Regardless, sorry to clog your issues with this.

**Comment by rtivital** [comment]
Okay, there is no plan to add string support to DatePicker and other dates component, so I'm closing this issue, feel free to reach out on discord if you have any other questions.

**Comment by pdevito3** [comment]
FYI, seems that dayjs figured this all out under the hood if you just use their `toDate()`  method:
```
        value={
          value === null || value === undefined ? null : dayjs(value).toDate()
        }
        onChange={(date) => {
          if (date !== undefined && date !== null) {
            onChange(dayjs(date).toDate());
          } else onChange(null);
        }}
```

https://day.js.org/docs/en/display/as-javascript-date
