### ISSUE TITLE
Abnormal Grid Behavior (NOT simple grid)

### ISSUE THREAD

**Issue by dukesx** [mantinedev/mantine#237]
Thanks for reaching out!

What happened ?

The Grid component is acting abnormally. Firstly, it can't differentiate between the breakpoint span and the "MAIN" span prop, for e.g if a Col has span={1} and on the same Col it has xl={2} then on xl breakpoint it will still follow span={1}, regardless of client sided or server sided (react refresh change vs page reload).

1.  i am also now seeing that the span and grow and i am not sure about other props, they don't seem to work. Grow doesn't make columns take the remaining space (i mean calculated according to span of individual Columns, if space still remains, take up the remaining) 

2. Another one is that, the Span doesn't make it take the allocated space. If i edit during dev mode of Next-js, without page reload, i do see it working, which means that the column now takes the allocated space accordingly (since its client sided) but if i reload the page (also during dev mode), the columns don't have any max-width or width set at all, despite having individual span={number}. it just equally widths the columns (since i have grow prop = true)

Note: I just upgraded from 2.3.1. I also tried removing all packages, removing .next folder, clearing browser cache, etc but doesnt matter. 

Pic 1 
![grid](https://user-images.githubusercontent.com/5988991/131669162-4e276085-187a-41b3-92ab-9443ff3ed34d.png)

Pic 1 shows grow=true behavior with span={number}

Pic 2

![grid2](https://user-images.githubusercontent.com/5988991/131669256-347b539f-44b7-4940-a8eb-d1881a9121c7.png)

Pic 2 shows grow={false} behavior with allocated spans;

**My configuration is :** 

Total Columns: 12, i am taking 11/12
 4 Columns, First has span={2} (the text logo) , 2nd has span={5} (the search bar), 3rd has span={2} (the icons on right of search bar) and last one has span={2} (the get started button and the sun icon on left of it)

Note: I love the direction of where this is going and i really really appreciate you guys putting every ounce of effort you have in this component. 

Please provide following information:
- What package has an issue (@mantine/core, mantine/hooks or other)?
@mantine/core
- What package version are you using?
Latest @ 2.4.0
- In which browser and operating system issue occurred?
All
- If possible please attach link to codesandbox with reproduced issue
Unfortunately, not 
- Do you have an idea how to fix the issue?
No Idea
- Are you willing to participate in fixing this issue (it's totally fine if not) and create a pull request with the fix?
Noop, Busy in the same project where i am utilizing this library

**Comment by rtivital** [comment]
Hi @dukesx, thanks for reporting this, can you try setting static `id` prop on grid and see if it works:

```tsx
<Grid id="my-app-grid" />
``` 

This is missing from docs, will add this soon

**Comment by rtivital** [comment]
@dukesx I've updated docs to reflect new changes, please see if it will help you

**Comment by everek** [comment]
I can reproduce it as well. Can confirm it only happens client-side with Next.js when switching pages. Once deployed and static, it doesn't happen anymore. But setting a static `id` on the `Grid` fixes the problem.

Thanks for updating the docs @rtivital. Sorry about the issue.

**Comment by dukesx** [comment]
> @dukesx I've updated docs to reflect new changes, please see if it will help you

I can confirm that the id prop fixes the issue. Thank you for fixing it !

**Comment by dukesx** [comment]
One more thing @rtivital , i think there should be a XXL and XXS prop as well, xxs for devices smaller than 400px (Galaxy S5, old iphones etc) and xxl for better accommodating breakpoints, i mean even bootstrap has a xxl breakpoint, i use their breakpoint values and i just think it can prove a lot useful to people who would really want to target Hi-res iMACs and 4k Displays (future proofing etc)

**Comment by rtivital** [comment]
I'll make breakpoints the same as in bootstrap, it's a good idea since it will be familiar to most people. I do think that we should add XXS breakpoint, as 576px is enough to consider device a mobile

**Comment by rtivital** [comment]
Oh, cool we already have all bootstrap breakpoints, I will add this to the docs
