### ISSUE TITLE
Spotlight onClick button error

### ISSUE THREAD

**Issue by Mbensler** [mantinedev/mantine#2370]
### What package has an issue

@mantine/spotlight

### Describe the bug

After copy pasting the spotlight example code/demo and installing all dependencies I get the following error from the "Open spotlight" button:

```js
(property) onClick?: MouseEventHandler<SVGElement> | undefined
Type '(payload_0?: undefined) => void' is not assignable to type 'MouseEventHandler<SVGElement>'.
  Types of parameters 'payload_0' and 'event' are incompatible.
    Type 'MouseEvent<SVGElement, MouseEvent>' is not assignable to type 'undefined'.ts(2322)
index.d.ts(1479, 9): The expected type comes from property 'onClick' which is declared here on type 'IntrinsicAttributes & OmitCommonProps<SVGProps<SVGSVGElement>, keyof IconProps> & IconProps & OmitCommonProps<...> & { ...; }'
```

The "onClick" has a red underline that gives the error above.
I am using .tsx

The button still works, but I am now unable to upload to Vercel because of the error.

### What version of @mantine/hooks page do you have in package.json?

5.2.5

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Hi @Mbensler, try `onClick={() => openSpotlight()}` instead. I'll update documentation to avoid confusion in future.

**Comment by rtivital** [comment]
I've updated documentation, it should not show any typescript errors now
