### ISSUE TITLE
Title doesn't support weight props

### ISSUE THREAD

**Issue by adarshaacharya** [mantinedev/mantine#2378]
### Link to the page where something nasty is located

 https://mantine.dev/core/title/#text-props

### Exact quote of what is wrong

 As mentioned in docs above, mantine should support weight props in `Title` component but it doesn't actually supports it.

![image](https://user-images.githubusercontent.com/50266088/188840260-cc53834d-61b8-457d-a606-361981007e44.png)

```jsx
<Title order={3} weight={100} align="center">
        H3 heading aligned to center with 100 font-weight
 </Title>
```

### Are you willing to create pull request with the fix?

Yes

**Comment by zhulien-ivanov** [comment]
It does support it. You have to use a version of `5.2.0` or greater.

**Comment by rtivital** [comment]
Update all  `@mantine` packages to latest version

**Comment by adarshaacharya** [comment]
thanks !
