### ISSUE TITLE
TS1110: Type expected in some of Mantine's files

### ISSUE THREAD

**Issue by rehypothecation** [mantinedev/mantine#2387]
### What package has an issue

@mantine/core

### Describe the bug

```
ERROR in /tmp/build/a94a8fe5/repo/web/node_modules/@mantine/core/lib/Floating/types.d.ts
ERROR in /tmp/build/a94a8fe5/repo/web/node_modules/@mantine/core/lib/Floating/types.d.ts(3,55):
TS1110: Type expected.

ERROR in /tmp/build/a94a8fe5/repo/web/node_modules/@mantine/core/lib/Indicator/Indicator.types.d.ts
ERROR in /tmp/build/a94a8fe5/repo/web/node_modules/@mantine/core/lib/Indicator/Indicator.types.d.ts(3,41):
TS1110: Type expected.

ERROR in /tmp/build/a94a8fe5/repo/web/node_modules/@mantine/core/lib/Title/Title.d.ts
ERROR in /tmp/build/a94a8fe5/repo/web/node_modules/@mantine/core/lib/Title/Title.d.ts(6,33):
TS1110: Type expected.
```
TypeScript is reporting some typing errors.

### What version of @mantine/hooks page do you have in package.json?

"^5.2.5"

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I don't know how to fix this.

**Comment by rtivital** [comment]
Hi @rehypothecation, based on my research, this issue is caused by outdated typescript version 
- https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8769
- https://stackoverflow.com/questions/37400681/error-ts1110-type-expected-when-using-export-type

**Comment by rehypothecation** [comment]
Thank you.
