### ISSUE TITLE
Menu `trigger="hover"` should be accessible

### ISSUE THREAD

**Issue by italodeandra** [mantinedev/mantine#2390]
### Discussed in https://github.com/mantinedev/mantine/discussions/2389

<div type='discussions-op-text'>

<sup>Originally posted by **italodeandra** September  8, 2022</sup>
> Menu with trigger="hover" is not accessible – users that navigate with keyboard will not be able to use it
> [Source](https://mantine.dev/core/menu/#show-menu-on-hover)

This seems like it could be easily fixable by also accepting the click event. Was this by design or is it a limitation? Why?</div>

<div type='discussions-op-text'>

<sup>Originally posted by **rtivital** September  8, 2022</sup>
I'm not really sure, maybe we should add it</div>

I think it is a good idea to implement this. At the moment I don't have the time to work on it, but I'm creating this issue so we can address it in the future.

**Comment by rtivital** [comment]
Alright, lets try adding onClick event to hover menu and see if that produces any UX issues. Do you want to open a PR for this?

**Comment by rtivital** [comment]
I've checked this issue – menu cannot be opened with click for hover trigger because focus will not be trapped. It does not make much sense to open the menu in this case.
