### ISSUE TITLE
@mantine/dates overriding MantineProvider theme

### ISSUE THREAD

**Issue by godart-corentin** [mantinedev/mantine#2392]
### What package has an issue

@mantine/dates

### Describe the bug

@mantine/dates package is overriding the MantineProvider theme configuration.

![Capture d’écran 2022-09-08 à 11 13 52](https://user-images.githubusercontent.com/43783685/189084107-8ca594a5-ef6b-4581-9127-89c43b0a5052.png)

<img width="324" alt="Capture d’écran 2022-09-08 à 11 11 12" src="https://user-images.githubusercontent.com/43783685/189083949-7530c237-69b4-4bfc-a410-d62540499734.png">

### What version of @mantine/hooks page do you have in package.json?

5.2.6

**Comment by rtivital** [comment]
Hi @godart-corentin, it works correctly on codesandbox – https://codesandbox.io/s/objective-margulis-i13rvm?file=/src/App.tsx
Please provide a reproduction

**Comment by godart-corentin** [comment]
Hello @rtivital, thank you for your answer.
I think it should be related to yarn workspaces in that case: my DateField component is located in an external package and I use this component inside a package having my MantineProvider.

I'll try to provide a reproduction after work.

**Comment by godart-corentin** [comment]
Issue fixed, my problem was due to some weird workspaces package error with Vite.
Adding "@mantine/dates" in the dedupe property of Vite's config fixed the issue !

Thank you for your time.
