### ISSUE TITLE
TransferList, cant select item after form.setFieldValue

### ISSUE THREAD

**Issue by ManuelDeode** [mantinedev/mantine#2395]
### What package has an issue

@mantine/form

### Describe the bug

I have a TransferList that is empty on default.
i load a list of users from the database.
after the users are loaded i use form.setFieldValue('users', [userData,[]])

it looks good but the items on the transfer list are not selectable one on one.

the button to move all of them works as expected.

### What version of @mantine/hooks page do you have in package.json?

^5.2.4

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Hi @ManuelDeode, please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by ManuelDeode** [comment]
Hi, trying to reproduce the issue i found the error. it seems that you cant use an integer as value in the list elements, i changed the value to string and it works perfectly now.

Maybe its something that could be mentioned somewhere?

**Comment by rtivital** [comment]
Okay, I'll add it to documentation
