### ISSUE TITLE
v2.4.1 breaks Grid in NextJS apps

### ISSUE THREAD

**Issue by mhanslik** [mantinedev/mantine#240]
The new @mantine/core v2.4.1 logic to generate grid col CSS class names using ID seems to not work with NextJs, as the CSS class ID generated in Grid does not seem to match the one then actually used by Col child components, resulting in the Grid not being rendered correctly as styles are missing.

Minimal example here based on the Getting Started guide with NextJS: https://codesandbox.io/s/gracious-sound-utbs6?file=/pages/index.js

The Grid has two Cols, but their CSS class names reference a non-existing class; whereas the Grid's child style tag has the CSS classes, but uses a different ID.

**Comment by mhanslik** [comment]
Closed as it just seemed to work after reloading Codesandbox; however, then noticed it actually happens during next's dev mode (maybe the watch mode?). The HTML I've got is e.g.

`<div style="margin:0;display:flex;flex-wrap:wrap;justify-content:flex-start;align-items:stretch" class="mantine-grid"><style> .mantine-svbl4u1qh-col-1 {
          flex-basis: 8.333333333333334%;
          flex-shrink: 0;
          max-width:  8.333333333333334%;
        } .mantine-svbl4u1qh-col-2 {
          flex-basis: 16.666666666666668%;
          flex-shrink: 0;
          max-width:  16.666666666666668%;
        } .mantine-svbl4u1qh-col-3 {
          flex-basis: 25%;
          flex-shrink: 0;
          max-width:  25%;
        } .mantine-svbl4u1qh-col-4 {
          flex-basis: 33.333333333333336%;
          flex-shrink: 0;
          max-width:  33.333333333333336%;
        } .mantine-svbl4u1qh-col-5 {
          flex-basis: 41.66666666666667%;
          flex-shrink: 0;
          max-width:  41.66666666666667%;
        } .mantine-svbl4u1qh-col-6 {
          flex-basis: 50%;
          flex-shrink: 0;
          max-width:  50%;
        } .mantine-svbl4u1qh-col-7 {
          flex-basis: 58.333333333333336%;
          flex-shrink: 0;
          max-width:  58.333333333333336%;
        } .mantine-svbl4u1qh-col-8 {
          flex-basis: 66.66666666666667%;
          flex-shrink: 0;
          max-width:  66.66666666666667%;
        } .mantine-svbl4u1qh-col-9 {
          flex-basis: 75%;
          flex-shrink: 0;
          max-width:  75%;
        } .mantine-svbl4u1qh-col-10 {
          flex-basis: 83.33333333333334%;
          flex-shrink: 0;
          max-width:  83.33333333333334%;
        } .mantine-svbl4u1qh-col-11 {
          flex-basis: 91.66666666666667%;
          flex-shrink: 0;
          max-width:  91.66666666666667%;
        } .mantine-svbl4u1qh-col-12 {
          flex-basis: 100%;
          flex-shrink: 0;
          max-width:  100%;
        }  @media (min-width: 576px) {  .mantine-svbl4u1qh-col-xs-1 {
          flex-basis: 8.333333333333334%;
          flex-shrink: 0;
          max-width:  8.333333333333334%;
        } .mantine-svbl4u1qh-col-xs-2 {
          flex-basis: 16.666666666666668%;
          flex-shrink: 0;
          max-width:  16.666666666666668%;
        } .mantine-svbl4u1qh-col-xs-3 {
          flex-basis: 25%;
          flex-shrink: 0;
          max-width:  25%;
        } .mantine-svbl4u1qh-col-xs-4 {
          flex-basis: 33.333333333333336%;
          flex-shrink: 0;
          max-width:  33.333333333333336%;
        } .mantine-svbl4u1qh-col-xs-5 {
          flex-basis: 41.66666666666667%;
          flex-shrink: 0;
          max-width:  41.66666666666667%;
        } .mantine-svbl4u1qh-col-xs-6 {
          flex-basis: 50%;
          flex-shrink: 0;
          max-width:  50%;
        } .mantine-svbl4u1qh-col-xs-7 {
          flex-basis: 58.333333333333336%;
          flex-shrink: 0;
          max-width:  58.333333333333336%;
        } .mantine-svbl4u1qh-col-xs-8 {
          flex-basis: 66.66666666666667%;
          flex-shrink: 0;
          max-width:  66.66666666666667%;
        } .mantine-svbl4u1qh-col-xs-9 {
          flex-basis: 75%;
          flex-shrink: 0;
          max-width:  75%;
        } .mantine-svbl4u1qh-col-xs-10 {
          flex-basis: 83.33333333333334%;
          flex-shrink: 0;
          max-width:  83.33333333333334%;
        } .mantine-svbl4u1qh-col-xs-11 {
          flex-basis: 91.66666666666667%;
          flex-shrink: 0;
          max-width:  91.66666666666667%;
        } .mantine-svbl4u1qh-col-xs-12 {
          flex-basis: 100%;
          flex-shrink: 0;
          max-width:  100%;
        } } @media (min-width: 768px) {  .mantine-svbl4u1qh-col-sm-1 {
          flex-basis: 8.333333333333334%;
          flex-shrink: 0;
          max-width:  8.333333333333334%;
        } .mantine-svbl4u1qh-col-sm-2 {
          flex-basis: 16.666666666666668%;
          flex-shrink: 0;
          max-width:  16.666666666666668%;
        } .mantine-svbl4u1qh-col-sm-3 {
          flex-basis: 25%;
          flex-shrink: 0;
          max-width:  25%;
        } .mantine-svbl4u1qh-col-sm-4 {
          flex-basis: 33.333333333333336%;
          flex-shrink: 0;
          max-width:  33.333333333333336%;
        } .mantine-svbl4u1qh-col-sm-5 {
          flex-basis: 41.66666666666667%;
          flex-shrink: 0;
          max-width:  41.66666666666667%;
        } .mantine-svbl4u1qh-col-sm-6 {
          flex-basis: 50%;
          flex-shrink: 0;
          max-width:  50%;
        } .mantine-svbl4u1qh-col-sm-7 {
          flex-basis: 58.333333333333336%;
          flex-shrink: 0;
          max-width:  58.333333333333336%;
        } .mantine-svbl4u1qh-col-sm-8 {
          flex-basis: 66.66666666666667%;
          flex-shrink: 0;
          max-width:  66.66666666666667%;
        } .mantine-svbl4u1qh-col-sm-9 {
          flex-basis: 75%;
          flex-shrink: 0;
          max-width:  75%;
        } .mantine-svbl4u1qh-col-sm-10 {
          flex-basis: 83.33333333333334%;
          flex-shrink: 0;
          max-width:  83.33333333333334%;
        } .mantine-svbl4u1qh-col-sm-11 {
          flex-basis: 91.66666666666667%;
          flex-shrink: 0;
          max-width:  91.66666666666667%;
        } .mantine-svbl4u1qh-col-sm-12 {
          flex-basis: 100%;
          flex-shrink: 0;
          max-width:  100%;
        } } @media (min-width: 992px) {  .mantine-svbl4u1qh-col-md-1 {
          flex-basis: 8.333333333333334%;
          flex-shrink: 0;
          max-width:  8.333333333333334%;
        } .mantine-svbl4u1qh-col-md-2 {
          flex-basis: 16.666666666666668%;
          flex-shrink: 0;
          max-width:  16.666666666666668%;
        } .mantine-svbl4u1qh-col-md-3 {
          flex-basis: 25%;
          flex-shrink: 0;
          max-width:  25%;
        } .mantine-svbl4u1qh-col-md-4 {
          flex-basis: 33.333333333333336%;
          flex-shrink: 0;
          max-width:  33.333333333333336%;
        } .mantine-svbl4u1qh-col-md-5 {
          flex-basis: 41.66666666666667%;
          flex-shrink: 0;
          max-width:  41.66666666666667%;
        } .mantine-svbl4u1qh-col-md-6 {
          flex-basis: 50%;
          flex-shrink: 0;
          max-width:  50%;
        } .mantine-svbl4u1qh-col-md-7 {
          flex-basis: 58.333333333333336%;
          flex-shrink: 0;
          max-width:  58.333333333333336%;
        } .mantine-svbl4u1qh-col-md-8 {
          flex-basis: 66.66666666666667%;
          flex-shrink: 0;
          max-width:  66.66666666666667%;
        } .mantine-svbl4u1qh-col-md-9 {
          flex-basis: 75%;
          flex-shrink: 0;
          max-width:  75%;
        } .mantine-svbl4u1qh-col-md-10 {
          flex-basis: 83.33333333333334%;
          flex-shrink: 0;
          max-width:  83.33333333333334%;
        } .mantine-svbl4u1qh-col-md-11 {
          flex-basis: 91.66666666666667%;
          flex-shrink: 0;
          max-width:  91.66666666666667%;
        } .mantine-svbl4u1qh-col-md-12 {
          flex-basis: 100%;
          flex-shrink: 0;
          max-width:  100%;
        } } @media (min-width: 1200px) {  .mantine-svbl4u1qh-col-lg-1 {
          flex-basis: 8.333333333333334%;
          flex-shrink: 0;
          max-width:  8.333333333333334%;
        } .mantine-svbl4u1qh-col-lg-2 {
          flex-basis: 16.666666666666668%;
          flex-shrink: 0;
          max-width:  16.666666666666668%;
        } .mantine-svbl4u1qh-col-lg-3 {
          flex-basis: 25%;
          flex-shrink: 0;
          max-width:  25%;
        } .mantine-svbl4u1qh-col-lg-4 {
          flex-basis: 33.333333333333336%;
          flex-shrink: 0;
          max-width:  33.333333333333336%;
        } .mantine-svbl4u1qh-col-lg-5 {
          flex-basis: 41.66666666666667%;
          flex-shrink: 0;
          max-width:  41.66666666666667%;
        } .mantine-svbl4u1qh-col-lg-6 {
          flex-basis: 50%;
          flex-shrink: 0;
          max-width:  50%;
        } .mantine-svbl4u1qh-col-lg-7 {
          flex-basis: 58.333333333333336%;
          flex-shrink: 0;
          max-width:  58.333333333333336%;
        } .mantine-svbl4u1qh-col-lg-8 {
          flex-basis: 66.66666666666667%;
          flex-shrink: 0;
          max-width:  66.66666666666667%;
        } .mantine-svbl4u1qh-col-lg-9 {
          flex-basis: 75%;
          flex-shrink: 0;
          max-width:  75%;
        } .mantine-svbl4u1qh-col-lg-10 {
          flex-basis: 83.33333333333334%;
          flex-shrink: 0;
          max-width:  83.33333333333334%;
        } .mantine-svbl4u1qh-col-lg-11 {
          flex-basis: 91.66666666666667%;
          flex-shrink: 0;
          max-width:  91.66666666666667%;
        } .mantine-svbl4u1qh-col-lg-12 {
          flex-basis: 100%;
          flex-shrink: 0;
          max-width:  100%;
        } } @media (min-width: 1400px) {  .mantine-svbl4u1qh-col-xl-1 {
          flex-basis: 8.333333333333334%;
          flex-shrink: 0;
          max-width:  8.333333333333334%;
        } .mantine-svbl4u1qh-col-xl-2 {
          flex-basis: 16.666666666666668%;
          flex-shrink: 0;
          max-width:  16.666666666666668%;
        } .mantine-svbl4u1qh-col-xl-3 {
          flex-basis: 25%;
          flex-shrink: 0;
          max-width:  25%;
        } .mantine-svbl4u1qh-col-xl-4 {
          flex-basis: 33.333333333333336%;
          flex-shrink: 0;
          max-width:  33.333333333333336%;
        } .mantine-svbl4u1qh-col-xl-5 {
          flex-basis: 41.66666666666667%;
          flex-shrink: 0;
          max-width:  41.66666666666667%;
        } .mantine-svbl4u1qh-col-xl-6 {
          flex-basis: 50%;
          flex-shrink: 0;
          max-width:  50%;
        } .mantine-svbl4u1qh-col-xl-7 {
          flex-basis: 58.333333333333336%;
          flex-shrink: 0;
          max-width:  58.333333333333336%;
        } .mantine-svbl4u1qh-col-xl-8 {
          flex-basis: 66.66666666666667%;
          flex-shrink: 0;
          max-width:  66.66666666666667%;
        } .mantine-svbl4u1qh-col-xl-9 {
          flex-basis: 75%;
          flex-shrink: 0;
          max-width:  75%;
        } .mantine-svbl4u1qh-col-xl-10 {
          flex-basis: 83.33333333333334%;
          flex-shrink: 0;
          max-width:  83.33333333333334%;
        } .mantine-svbl4u1qh-col-xl-11 {
          flex-basis: 91.66666666666667%;
          flex-shrink: 0;
          max-width:  91.66666666666667%;
        } .mantine-svbl4u1qh-col-xl-12 {
          flex-basis: 100%;
          flex-shrink: 0;
          max-width:  100%;
        } }</style><div style="box-sizing:border-box;flex-grow:0;padding:0" class="mantine-col mantine-raeq0cnzg-col-2">1</div><div style="box-sizing:border-box;flex-grow:0;padding:0" class="mantine-col mantine-raeq0cnzg-col-2">2</div></div>`

**Comment by everek** [comment]
@mhanslik see #237, yes it only happens in dev mode. It can be fixed by giving the `Grid` an `id`.
