### ISSUE TITLE
Update embla-carousel-react to version at least ^7.0.2

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#2403]
### What package has an issue

@mantine/carousel

### Describe the bug

See recommendations to update version: https://github.com/davidjerleke/embla-carousel/discussions/365#discussioncomment-3606311

### What version of @mantine/hooks page do you have in package.json?

latest

### Possible fix

https://github.com/mantinedev/mantine/blob/master/src/mantine-carousel/package.json#L27
"embla-carousel-react": "^7.0.2",

**Comment by rtivital** [comment]
You can install `embla-carousel-react@7.0.2` on your side, it is a peer dependency, `^` symbol means any `7.x.x` version is compatible

**Comment by 7iomka** [comment]
> You can install `embla-carousel-react@7.0.2` on your side, it is a peer dependency, `^` symbol means any `7.x.x` version is compatible

ok, but it would still be good manners not to be confusing
