### ISSUE TITLE
Invalid props for generated Styled Component with Mantine Components

### ISSUE THREAD

**Issue by hassanzohdy** [mantinedev/mantine#2412]
### What package has an issue

@mantine/core

### Describe the bug

When using `@emotion/styled` with  any Mantine Component, typescript checker throws an error:

`Type '{ children: string; }' has no properties in common with type 'IntrinsicAttributes & { theme?: Theme | undefined; }`

### What version of @mantine/hooks page do you have in package.json?

>= 5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/cold-butterfly-l4p28k

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hi @hassanzohdy, Box is a polymorphic component, if you do not need Box props, then use `styled.div` instead. Otherwise, you should follow polymorphic component documentation – https://mantine.dev/styles/styled/#polymorphic-components

https://codesandbox.io/s/sad-hertz-kd6j4v?file=/src/App.tsx

**Comment by hassanzohdy** [comment]
Thanks @rtivital for the tip
