### ISSUE TITLE
Fullscreen modal issue

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#2419]
### What package has an issue

@mantine/core

### Describe the bug

Hi.
I have a little problem with fullscreen modal when I initialize vendor map when modal is open, I get horizontal scrollbar appeared, and I don't know why? Maybe this is related with padding-fix removal during opening or something else.
Anyone who know how to fix that, help me please)

### What version of @mantine/hooks page do you have in package.json?

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/silly-sutherland-4nmz2y

**Comment by 7iomka** [comment]
There is a source of problem!
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Modal/Modal.styles.ts#L90
Why this margin exists?)

**Comment by 7iomka** [comment]
Also, you need to add to inner `overflowX: 'hidden'`
Because [overflowY](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Modal/Modal.styles.ts#L58) adds issues, so when you open modal fullscreen content can show horizontal scrollbar for a moment, and this can be a huge issue in my case, when map inside it use parent dimmensions (height can be different)

**Comment by rtivital** [comment]
Can you please confirm that it is still an issue in 7.0?

**Comment by 7iomka** [comment]
> Can you please confirm that it is still an issue in 7.0?
I'm still in the process of migrating and I'm not sure if it's a quick process to say for sure.
You can close it for now, but reopen it later in case of anything.

**Comment by rtivital** [comment]
Thanks!
