### ISSUE TITLE
Popover.Dropdown does not show up

### ISSUE THREAD

**Issue by Manokii** [mantinedev/mantine#2424]
### What package has an issue

@mantine/core

### Describe the bug

5.x made breaking changes with Popover

title is moved to `Popover.Dropdown` component but it does not appear anywhere

### What version of @mantine/hooks page do you have in package.json?

5.3.0

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by zhulien-ivanov** [comment]
https://mantine.dev/changelog/5-0-0/#popover.
Title isn't supported anymore for `Popover` since v5.
