### ISSUE TITLE
TAB navigation issue with date pickers

### ISSUE THREAD

**Issue by NeilJS** [mantinedev/mantine#2426]
### What package has an issue

@mantine/dates

### Describe the bug

Trying out the demo on the website – using TAB to navigate the date pickers. When a datepicker popup is opened, hitting TAB will cycle through the UI: previous month '<', month name, next month '>' then the day '1'.

Example issue: select next month '>' then hit TAB to cylce the UI again. It is no longer possible to gain focus on the days, only the month controls.

Also:

- can be difficult to escape from the year selector. Maybe use ESC to go back a level
- sometimes focus leaves the date picker and enters another component yet the date picker popup remains open

### What version of @mantine/hooks page do you have in package.json?

Website demo

### If possible, please include a link to a codesandbox with the reproduced problem

Website demo

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by arekrgw** [comment]
My first thought was the issue with `tabIndex` html tag, tried to fix that by setting `focusable` to `true` in `MonthsList.tsx` while rendering `Month.tsx` but it didn't work

**Comment by rtivital** [comment]
Will be fixed in 6.0 release
