### ISSUE TITLE
Button gets hidden when using tailwind 

### ISSUE THREAD

**Issue by Hinterberger-Thomas** [mantinedev/mantine#2437]
### What package has an issue

@mantine/core

### Describe the bug

Button gets hidden when using tailwind 

When I tried to add the `@tailwind` directives to the `global.css` file, all the buttons disappeared.  I was trying to use the t3 stack and I tried to set it up myself, however, it still didn't work.

### What version of @mantine/hooks page do you have in package.json?

5.3.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hi @Hinterberger-Thomas, you've installed a third-party library to your project that overrides Mantine styles. To fix that issue, either remove those styles or change emotion cache options to make Mantine styles override third-party library styles – https://mantine.dev/theming/emotion-cache/

**Comment by Hinterberger-Thomas** [comment]
Oh yeah that fixed it! Just got confused because when i updated mantine this problem accured 

thanks for the help!

**Comment by zx013** [comment]
You can add this in tailwind.config.js, it can fix it.
```
corePlugins: {
  preflight: false,
},
```

**Comment by rtivital** [comment]
https://mantine.dev/styles/mantine-styles/#css-layers

**Comment by Crayon-ShinChan** [comment]
> @rtivital thanks, I was able to solve it by importing tailwind styles first and then mantine styles!

I still can't solve this issue, here is my globals.css:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@import "@mantine/core/styles.layer.css";
@import "@mantine/dates/styles.css";
@layer base, mantine;
```
could you elaborate your method? thank you!
