### ISSUE TITLE
incompatible support for RTL with Carousel

### ISSUE THREAD

**Issue by hassanzohdy** [mantinedev/mantine#2442]
### What package has an issue

@mantine/carousel

### Describe the bug

When wrapping the application in RTL, the carousel are flipped, also it only renders the first carousel item

### What version of @mantine/hooks page do you have in package.json?

5.3.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/stoic-meninsky-1s5fdw?file=/src/App.tsx

### Do you know how to fix the issue

No

**Comment by NarSiiiS** [comment]
According to the documentation you need Add dir="rtl" to html element:

`<html dir="rtl">...</html>`

**Comment by rtivital** [comment]
It works as expected then – https://codesandbox.io/s/cranky-ptolemy-ustws2

**Comment by hassanzohdy** [comment]
thanks, that was my mistake :)
