### ISSUE TITLE
Slider not showing correct values

### ISSUE THREAD

**Issue by yaldram** [mantinedev/mantine#2444]
### What package has an issue

@mantine/core

### Describe the bug

For the Slider component if I have the following code - 
```javascript
 <Slider
    labelAlwaysOn
    min={1}
     max={100}
     step={10} 
  />
```
My `min = 1 & max = 100`. I am getting `101` as my max value - 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/13429535/190203156-d9313d32-8b8b-46b2-8294-7427d11a49a4.png">

### What version of @mantine/hooks page do you have in package.json?

5.3.1

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I think under - `src/mantine-core/src/Slider/utils/get-change-value/get-change-value.ts`  on line number 22 the `Math.round()` is causing this issue.

**Comment by yaldram** [comment]
Technically this is not a Bug, this is how the math works, I have seen the same behaviour in other libraries

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by yaldram** [comment]
We can do the following under `src/mantine-core/src/Slider/utils/get-change-value/get-change-value.ts` - 

```javascript
return Math.max(Math.min(nextValue, max), min);
```
instead of just 

```javascript
return nextValue;
```

**Comment by yaldram** [comment]
Also check the following scenario - 

```javascript
 <Slider
    labelAlwaysOn
    min={-100}
     max={1}
     step={10} 
  />

```

**Comment by yaldram** [comment]
Also Please check the following scenario for the RangeSlider with minRange = stepSize it does not work - 
```javascript
<RangeSlider
          labelAlwaysOn
          min={-100}
          max={10}
          step={10}
          minRange={10}
          defaultValue={[1, 10]}
/>
```

Check this example from React Material UI - https://codesandbox.io/s/ph7nci?file=/demo.tsx

**Comment by yaldram** [comment]
Also Please check the following scenario the RangeSlider is stuck at 81 - 100 I am unable to choose a value 91 -100 - 
```javascript
     <RangeSlider labelAlwaysOn min={1} max={100} step={10} minRange={10} />
```

**Comment by yaldram** [comment]
I would say if we have a non-uniform scale like `min - 1 to max - 100` as opposed to `min - 0 to max - 100` we are gonna face such issues. The Material UI Slider it does not have min range at all.

**Comment by yaldram** [comment]
Material UI has a demo with `minRange` & stepSize here - https://codesandbox.io/s/tezue3?file=/demo.tsx
