### ISSUE TITLE
Update @mantine/rte dependency of react-quill to 2.0.0 from the beta 4, 2.0.0-beta.4

### ISSUE THREAD

**Issue by AddictArts** [mantinedev/mantine#2449]
### What package has an issue

@mantine/rte

### Describe the bug

The beta version of react-quill has peerDependencies for react and react-dom `^16 || ^17`. This can result in a local `npm install` using react 18 failing. This creates confusion especially in a npm workspaces configuration. Version 2.0.0 of react-quill adds ^18, which would eliminate any Mantine running into installation fails and runtime `react-dom/client` import fails.

### What version of @mantine/hooks page do you have in package.json?

5.3.1

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Change the @mantine/rte dependency to `2.0.0` from `2.0.0-beta.4`.

**Comment by rtivital** [comment]
Fixed in 5.3.2
