### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'display')

### ISSUE THREAD

**Issue by kyawkhaing-genie** [mantinedev/mantine#2451]
### What package has an issue

@mantine/dates

### Describe the bug

DatePicker component from @mantine/dates throws style.display error in web component. It works everywhere, but, unfortunately, it doesn't work inside shadow dom. Can you guys check it out?  

### What version of @mantine/hooks page do you have in package.json?

5.3.0

**Comment by emewjin** [comment]
same issue in Modal component when using it inside shadow DOM.
https://discord.com/channels/854810300876062770/1019167978731880498

**Comment by kyawkhaing-genie** [comment]
yes! It should be! But, the mantine component will be messy just to support shadowDOM. Perhaps using React's useRef will be the better solution instead of using querySelector directly.

**Comment by rtivital** [comment]
Hi @kyawkhaing-genie, currently we do not provide any official support for shadow DOM, and it is not a part of the roadmap.

**Comment by laugri** [comment]
For anyone trying to make Mantine work in a shadow dom, it might be helpful to reference this conversation that offers solutions: https://github.com/orgs/mantinedev/discussions/598#discussioncomment-9547255
