### ISSUE TITLE
Indicator example & showZero prop

### ISSUE THREAD

**Issue by vegar** [mantinedev/mantine#2452]
### Link to the page where something nasty is located

https://mantine.dev/changelog/5-3-0/

### Exact quote of what is wrong

The code example indicates that the third profile should be shown without indicator if the value is zero, but the indicator is shown with a value of zero

![2022-09-15_10-40-02_vivaldi](https://user-images.githubusercontent.com/764517/190357741-60291c33-c48f-4bb0-b960-cd7683f0dae8.png)

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by rtivital** [comment]
Fixed

**Comment by vegar** [comment]
Looking at the fix - is it so that `showZero` only works if `dot` is `false`?

**Comment by rtivital** [comment]
yes
