### ISSUE TITLE
Weird behaviour when pressing arrow keys in select when hovering item

### ISSUE THREAD

**Issue by hornta** [mantinedev/mantine#2457]
### What package has an issue

@mantine/core

### Describe the bug

When hovering an item with the cursor and at the same time pressing `arrow down` to scroll down when the next item needs to be scrolled into view then the hovered item under the corsor gets selected.

![Animation (2)](https://user-images.githubusercontent.com/4553604/190396595-864c0eba-2057-4d96-b2b5-6eb17c31baa7.gif)

### What version of @mantine/hooks page do you have in package.json?

5.3.0

### Possible fix

Select needs to keep track if the mouse cursor was actually moved and base the select logic on that.

**Comment by telcy** [comment]
It is indeed a weird behavior and would require to move the mouse out of the dropdown list to use keys properly.
