### ISSUE TITLE
`Skeleton` ignores `classNames`

### ISSUE THREAD

**Issue by 108EAA0A** [mantinedev/mantine#2467]
### What package has an issue

@mantine/core

### Describe the bug

Passing `classNames` to `Skeleton` is ignored.
As a result, `classnames="[object Object]"` is output to the DOM.
![SS 2022-09-16 15 00 17](https://user-images.githubusercontent.com/23615952/190567825-1b3dfbe8-1a36-4259-bc2c-04d1c6fe92cc.png)

Perhaps it's because you're not explicitly receiving and processing `classNames` props in `Skeleton`.
https://github.com/mantinedev/mantine/blob/5cf81d288a7c47c115b2dd92efe9a6b0008fdb45/src/mantine-core/src/Skeleton/Skeleton.tsx#L36

### What version of @mantine/hooks page do you have in package.json?

5.3.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-example-ypvqjp?file=/src/App.tsx

**Comment by rtivital** [comment]
It is expected behavior, Skeleton renders one node, you can add styles to it with sx or className props

**Comment by 108EAA0A** [comment]
I didn't know that, thanks!
But then, wouldn't it be better not to accept `classNames` ?
It is unkind that there is no error despite the unintentional rendering to the DOM.
I think the type definition needs to be improved.

**Comment by rtivital** [comment]
I wasn't able to make it work, if you know how to implement that, feel free to send a PR to DefaultProps type

**Comment by 108EAA0A** [comment]
@rtivital
Since this is a Skeleton-specific issue, we have created a PR against SkeletonProps.
https://github.com/mantinedev/mantine/pull/2471
