### ISSUE TITLE
Selected text wraps the whole input content for PasswordInput

### ISSUE THREAD

**Issue by mcmxcdev** [mantinedev/mantine#2468]
### What package has an issue

@mantine/core

### Describe the bug

When using https://mantine.dev/core/password-input/ and https://mantine.dev/core/text-input/ on the same page, they look inconsistent due to their differently sized selected text highlighting.

![Screenshot from 2022-09-16 08-14-04](https://user-images.githubusercontent.com/16797721/190569747-2a99f629-4ef1-432c-89b2-6f10e053568c.png)

![Screenshot from 2022-09-16 08-13-54](https://user-images.githubusercontent.com/16797721/190569737-3a585052-f50d-4cfa-bfdf-e2d509a803f5.png)

### What version of @mantine/hooks page do you have in package.json?

5.2.7

**Comment by rtivital** [comment]
Fixed in 5.3.3
