### ISSUE TITLE
[DateRangePicker] Picker doesn't clear when value gets set to undefined

### ISSUE THREAD

**Issue by kyiii** [mantinedev/mantine#247]
Hi, thanks for the great work on Mantine!

I'm using the Mantine DateRangePicker with react-hook-form that initialises DateRangePicker with undefined pass to the value prop. Everything works great, except for when I reset the form (and undefined now passed again to the DateRangePicker value prop as a consequence), the original selected value remains in the picker. 

To me, the expected behaviour is that if the value prop receives an undefined value, the previously displayed date range should clear.

**Comment by rtivital** [comment]
Hi @kyiii DateRange picker works with a tuple of two dates `[new Date(), new Date()]`, when value is set to undefined component considers itself to be uncontrolled and initializes internal state from previous value. In other words you should always provide a valid value format in order for component to work as expected. This applies to all Mantine inputs, not only DateRangePicker.

To clear component values you should set value to `[null, null]`, can you configure that with your form library?

**Comment by kyiii** [comment]
Hi @rtivital, thanks for the clarification! So I did some further testing, and came across something very strange - when setting the value to [null, null], the picker only clears if React.StrictMode is not enabled. Below are two minimal working reproducible examples on CodeSandbox.

With React.StrictMode (picker doesn't clear):
https://codesandbox.io/s/nervous-saha-e47xc

Without React.StrictMode (picker clears):
https://codesandbox.io/s/cranky-frost-fpt9v

**Comment by rtivital** [comment]
Well, we do not support StrictMode anyway due to react-jss problems, so I would recommend removing it (it does not help since there is no output and just introduces a new bug).

Regarding value types – these will be changes in next minor release (September 28th or earlier)

**Comment by rtivital** [comment]
`Date | null` type was added to all @mantine/dates components in 2.5.0, feel free to reopen this issue if something is not right
