### ISSUE TITLE
Invalid ARIA attribute value reported for aria-controls with uppercase values

### ISSUE THREAD

**Issue by mcmxcdev** [mantinedev/mantine#2470]
### What package has an issue

@mantine/core

### Describe the bug

Our `Tabs` component uses enum values like `YES` and `NO` and when rendered in the DOM this leads to `aria-controls="mantine-r6-panel-YES"`

[Axe](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd) reports this as "Invalid ARIA attribute value". It seems that the value has to be all lowercase I assume.

### What version of @mantine/hooks page do you have in package.json?

5.2.7

### Possible fix

Maybe a simple `.toLowerCase()` on the `aria-controls` values could handle this already.

**Comment by rtivital** [comment]
Hi @mcmxcdev, please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example.

**Comment by rtivital** [comment]
Hi @mcmxcdev feel free to reopen the issue if you can provide a sandbox
