### ISSUE TITLE
File input taking only the first accept attribute

### ISSUE THREAD

**Issue by csanchez24** [mantinedev/mantine#2481]
### What package has an issue

@mantine/dropzone

### Describe the bug

Hi,

on the Dropzone Component when clicking to open the file browser is taking only the first accept attribute.

![Screen Shot 2022-09-16 at 8 05 33 PM](https://user-images.githubusercontent.com/16311853/190832149-3b8abd55-46bd-43da-8011-5f35aa7edacd.png)

in the about example the first accept value is PNG so when clicking the dropzone show only png file and not the rest of the files in this case jpg and svg.

![Screen Shot 2022-09-16 at 8 06 22 PM](https://user-images.githubusercontent.com/16311853/190832191-5db20ea6-2b1e-4189-9884-2e38fcade6a2.png)

but if I force to show the hidden file and click on it to open the file browser it worked. 

![Screen Shot 2022-09-16 at 8 10 25 PM](https://user-images.githubusercontent.com/16311853/190832361-efda30c7-26a6-4236-bfb5-25c954cc4685.png)

![Screen Shot 2022-09-16 at 8 10 49 PM](https://user-images.githubusercontent.com/16311853/190832377-aac2829d-b612-4422-ae3a-8bf3f63980fe.png)

thanks

### What version of @mantine/hooks page do you have in package.json?

5.1.4

**Comment by rtivital** [comment]
Fixed in 5.3.3
