### ISSUE TITLE
`@mantine/rte` not displaying the editor on Remix

### ISSUE THREAD

**Issue by danestves** [mantinedev/mantine#2488]
### What package has an issue

@mantine/rte

### Describe the bug

As you can see on the screenshot, the `ref` is set correctly, I'm doing a simple example of `value` and `onChange` but it's appearing that quill editor is never rendered

![CleanShot 2022-09-18 at 22 05 49](https://user-images.githubusercontent.com/31737273/190939347-f38c5ef3-c1df-43b9-a658-0613bad4bfd3.png)

### What version of @mantine/hooks page do you have in package.json?

5.3.3

### Do you know how to fix the issue

No

**Comment by danestves** [comment]
Adding the `id` prop to the component makes everything work

**Comment by russell-davis** [comment]
Had the same issue today. I added the `id` prop to the component like @danestves suggested and it fixed the issue. The code seems to default to the value that the `useId` hook returns, and only uses the `id` if provided, so I expected to be able to create a new instance without providing an `id` prop. 🤔
