### ISSUE TITLE
Missing styles documentation for Card component

### ISSUE THREAD

**Issue by chrisganov** [mantinedev/mantine#2491]
### Link to the page where something nasty is located

https://mantine.dev/core/card/

### Exact quote of what is wrong

The documentation for styling the Card component is missing

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
Card component supports everything described in the theming section, there is no need to include anything extra in its documentation.

**Comment by dellwatson** [comment]
@rtivital card cant modify the width 
```
    <Card
            styles={() => ({
              card: { width: 300 },
            })}
            key={i}
            shadow="sm"
            padding="xl"
            component="div"
   
          >
          ```
          
          tried hours for this

**Comment by chrisganov** [comment]
@dellwatson try “root” selector - also i would recommend that you check the selectors using the devtools of the browser, it will be easier to know what you need to select
