### ISSUE TITLE
Keep the indentation with multiline contents of Item in List

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#2494]
### What package has an issue

@mantine/core

### Describe the bug

When content in List.Item is wrapping, it starts on start of a new line without the same space as mark has.
<img width="829" alt="image" src="https://user-images.githubusercontent.com/18473137/191090638-b09f0c6c-1011-49e3-8630-833deed7f720.png">

I think, this is because you use `list-style-position: inside`.
<img width="730" alt="image" src="https://user-images.githubusercontent.com/18473137/191091360-60e2402e-cffc-494a-b6b4-95ca1540b5fb.png">

### What version of @mantine/hooks page do you have in package.json?

latest

### Possible fix

If this is a native list (no custom icon, etc..)
for `itemWrapper` use styles
```css
    display: inline-block;
    vertical-align: top;
    max-width: calc(100% - 1.5em);
```

or as for custom one use flex
```css
    display: inline-flex;
    flex-direction: column;
    max-width: calc(100% - 1.5em);
```

`1.5em` is a value of a dot width plus default space between it and content of item.

Currently, there is no other way to fix this, except to make a custom implementation for the default list types

**Comment by 7iomka** [comment]
Another simpler way to fix without any hack with `maxWidth`

```js
item: {
    whiteSpace: 'nowrap',
},
itemWrapper: {
    display: 'inlineFlex',
    whiteSpace: 'normal',
}
```

**Comment by rtivital** [comment]
Fixed in 5.5.0

**Comment by 7iomka** [comment]
@rtivital 
Why you changed `list-style-position: outside;` ?
Outside position ignore indentation at all, and make me crazy to align my lists.
why didn't you just take [my suggestion](https://github.com/mantinedev/mantine/issues/2494#issuecomment-1252702904) to fix the problem?

**Comment by rtivital** [comment]
I guess because that's how you've described an issue. I did not work on it and the PR seemed fine. If you want to fix it other way, feel free to submit a PR.

**Comment by 7iomka** [comment]
@rtivital Done.
