### ISSUE TITLE
Inherit by default params in List.Item from List

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#2495]
### What package has an issue

@mantine/core

### Describe the bug

For now how I see all params available on `ListStylesParams` is not inherited on `List.Item` by default.
This behavior produce impossible to check params on List when you trying to configure it on Provider level.
For example I tried to fix by myself [this issue](https://github.com/mantinedev/mantine/issues/2494)
See the demo link, open console and you will see.

### What version of @mantine/hooks page do you have in package.json?

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/currying-violet-hnkvx0?file=/src/App.tsx

### Possible fix

Separate configuration for List and ListItem or inherit params passed in List unless they are overridden

**Comment by rtivital** [comment]
Sandbox works correctly with 5.5.2 – https://codesandbox.io/s/thirsty-pare-hkwgsy?file=/src/App.tsx

**Comment by 7iomka** [comment]
> Sandbox works correctly with 5.5.2 – https://codesandbox.io/s/thirsty-pare-hkwgsy?file=/src/App.tsx

What you mean it works correctly?
Is there same problem
<img width="641" alt="image" src="https://user-images.githubusercontent.com/18473137/193873537-fe4241f2-3a8c-4302-80e8-7270a37af272.png">

listStyleType is undefined on Item logs

**Comment by rtivital** [comment]
Should be fixed now – https://codesandbox.io/s/thirsty-pare-hkwgsy?file=/src/App.tsx
