### ISSUE TITLE
Search functionality inexistent on mobile 

### ISSUE THREAD

**Issue by hichemfantar** [mantinedev/mantine#2496]
### Link to the page where something nasty is located

https://mantine.dev/

### Exact quote of what is wrong

I suggest adding it the mobile nav menu

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
It is not planned to add search on mobile

**Comment by hichemfantar** [comment]
May I ask why?
I believe search on desktop uses spotlight so it would just be a matter of putting the search box inside the mobile menu.
