### ISSUE TITLE
useViewportSize doesn't provide dimensions on initial render

### ISSUE THREAD

**Issue by ludwignagelhus** [mantinedev/mantine#2501]
### What package has an issue

@mantine/hooks

### Describe the bug

`useViewportSize` sets its values in a useEffect, which means the size on the initial page render is

```
{
    width: 0,
    height: 0,
  }
```

This causes a quick flicker on pages where I use these values to set the size of a div to take up all horizontal and vertical space.

Would it be okay to change the hook to instead set `width` and `height` with a `useLayoutEffect`?

### What version of @mantine/hooks page do you have in package.json?

5.3

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

```typescript
import { useCallback, useState, useLayoutEffect } from 'react';
import { useWindowEvent } from '../use-window-event/use-window-event';

const eventListerOptions = {
  passive: true,
};

export function useViewportSize() {
  const [windowSize, setWindowSize] = useState({
    width: 0,
    height: 0,
  });

  const setSize = useCallback(() => {
    setWindowSize({ width: window.innerWidth || 0, height: window.innerHeight || 0 });
  }, []);

  useWindowEvent('resize', setSize, eventListerOptions);
  useWindowEvent('orientationchange', setSize, eventListerOptions);
  useLayoutEffect(setSize, []);

  return windowSize;
```

**Comment by rtivital** [comment]
Are you sure that this will not produce hydration mismatch?

**Comment by ludwignagelhus** [comment]
I am not. I'll do some reading about hydration mismatch this week to see if I can figure it out.

**Comment by ludwignagelhus** [comment]
I am not sure what to do about possible hydration mismatch. I will be working on some projects where I plan on doing something similar to my proposal. I will come back with an update if I find something that works and doesn't produce hydration mismatch.
