### ISSUE TITLE
Disabled Mantine labels are inconsistent for radios and checkboxes.

### ISSUE THREAD

**Issue by omarsy** [mantinedev/mantine#2507]
### Link to the page where something nasty is located

https://codesandbox.io/s/wild-sunset-6zkf4u?file=/src/App.tsx

### Exact quote of what is wrong

Now when we disable the radio we have the label of the input changing color and the data-disabled is changed, which will also make styling the component easier. 
![Capture d’écran 2022-09-20 à 20 04 59](https://user-images.githubusercontent.com/15034695/191331906-ce24b186-856d-4ef0-802e-6a4985e407f6.png)

I would like to have the same behaviour for the checkbox.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Hi @omarsy, feel free to create a PR with this change, please also make sure that it is consistent across Checkbox, Radio and Switch components
