### ISSUE TITLE
Carousel not update indicators when reinit, responsive

### ISSUE THREAD

**Issue by hungnmhocmai** [mantinedev/mantine#2512]
### What package has an issue

@mantine/carousel

### Describe the bug

1. When I getApi embla and reinit with new number slideToScroll, indicators not update.
2. When responsive indicators not update.
### What version of @mantine/hooks page do you have in package.json?

"@mantine/carousel": "^5.4.0",

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Hi @hungnmhocmai, please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by rtivital** [comment]
Hi @hungnmhocmai, feel free to reopen the issue if you can provide a sandbox.
