### ISSUE TITLE
Switch component's 'onLabel' and 'offLabel' shows TypeError

### ISSUE THREAD

**Issue by Saifurrahmanemon** [mantinedev/mantine#2516]
### What package has an issue

@mantine/core

### Describe the bug

Switch component from **@mantine/core** shows TypeError when I try to Icon as children.
I took the code from Mantine core docs.

<img width="920" alt="Switch tsx (1)" src="https://user-images.githubusercontent.com/70877552/191461297-4fe647fb-cab9-48f3-b5ed-ebc7fd7ffd4f.png">

### What version of @mantine/hooks page do you have in package.json?

		"@mantine/core": "^5.2.4",

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

probably we could set Element type in the SwitchProps

``` /** Inner label when Switch is in unchecked state */
    offLabel?: string | Element;
    /** Inner label when Switch is in checked state */
    onLabel?: string | Element;
```

**Comment by rtivital** [comment]
Hi @Saifurrahmanemon you need to update your `@mantine/*` packages to latest version (5.4.0) to use new Switch component features
