### ISSUE TITLE
MantineServerStyles not found

### ISSUE THREAD

**Issue by dukesx** [mantinedev/mantine#252]
Thanks for reaching out!

Please provide following information:
- What package has an issue (@mantine/core, mantine/hooks or other)?
 Package is @mantine/core
- What package version are you using?
2.5.0
- In which browser and operating system issue occurred?
All
- If possible please attach link to codesandbox with reproduced issue
Not available
- Do you have an idea how to fix the issue?
Just needs to be exported
- Are you willing to participate in fixing this issue (it's totally fine if not) and create a pull request with the fix?
Unknown

![check](https://user-images.githubusercontent.com/5988991/133665065-c002963a-cfe9-4312-a964-ef16b3a3a4cb.png)

**Comment by rtivital** [comment]
Thanks for reporting, this is an incorrect component name in documentation, it should be just `ServerStyles`, I'll fix it as soon as possible
