### ISSUE TITLE
Pagination does'nt seem to work in Next.js

### ISSUE THREAD

**Issue by nghiepit** [mantinedev/mantine#253]
I have 3 issues when to use `Pagination` in `Next.js`.

Please provide following information:
- What package has an issue (@mantine/core, mantine/hooks or other)?
**@mantine/core**
- What package version are you using?
**2.5.0**
- In which browser and operating system issue occurred? 
**Chrome, macOS**
- If possible please attach link to codesandbox with reproduced issue
**https://github.com/nghiepit/mantine-pagination-bug**. 
**I must provide GitHub reproduction because to reproduce the issue in production mode.**

Issues:

**1.** In dev mode the `Pagination` broken layout
![image](https://user-images.githubusercontent.com/4768095/133725749-e3f94f94-a167-453f-946c-9ce63301371a.png)

**2.** In dev mode warning `className` dis not match. Even though I provided `id` for `Pagination`.
> Warning: Prop `className` did not match. Server: "button-0-2-11 button-d0-0-2-12 mantine-unstyled-button child-0-2-8 child-d1-0-2-10 mantine-group-child item-0-2-1 item-d0-0-2-4 mantine-pagination-item" Client: "button-0-2-16 button-d1-0-2-18 mantine-unstyled-button child-0-2-11 child-d3-0-2-15 mantine-group-child item-0-2-1 item-d3-0-2-7 mantine-pagination-item"

**3.** In production mode the`Pagination` just broken any styles.
![image](https://user-images.githubusercontent.com/4768095/133725957-3f6d7a16-49bf-4311-963a-e54b306dd557.png)

**UPDATED**: When I try to disable `reactStrictMode` issues **1** and **2** have been resolved.

**Comment by rtivital** [comment]
Hi @nghiepit, we do not support strict mode. I've released 2.5.1 which should fix styles in production build.
