### ISSUE TITLE
Issue while running tests with mantine/hooks

### ISSUE THREAD

**Issue by vishnup-ditto** [mantinedev/mantine#2533]
### What package has an issue

@mantine/hooks

### Describe the bug

When running a snapshot test using jest (@storybook/addon-storyshots)-[Link](https://storybook.js.org/addons/@storybook/addon-storyshots) in storybook I keep running into an error with a slider component. 

Posting the stack trace here.

```
Error: Uncaught [TypeError: Cannot read properties of null (reading 'addEventListener')]
        at reportException (/home/***/Documents/******/***/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)

at /home/********/node_modules/@mantine/hooks/src/use-move/use-move.ts:81:17

 The above error occurred in the <@mantine/core/Slider> component:
        at /home/vishnu/Documents/XXXX/node_modules/@mantine/core/src/Slider/Slider/Slider.tsx:60:14

```

I believe this is due to https://github.com/mantinedev/mantine/blob/master/src/mantine-hooks/src/use-move/use-move.ts#L113 which tries to set a `addEventListener` on a null ref. I tried to work around but since the ref is set internally, I believe there is very little I can do to override it(please correct me if I am wrong here)

I can fix it by putting the code inside a check for `ref.current`. 

### What version of @mantine/hooks page do you have in package.json?

5.2.4

### If possible, please include a link to a codesandbox with the reproduced problem

N/A

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

A check on `ref.current`

**Comment by rtivital** [comment]
Hi @vishnup-ditto, this issue is not related to Mantine, most likely you have incorrect test environment setup. We have tests for Slider component that work as expected with jest, you can check them as reference – https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Slider/Slider/Slider.test.tsx

You can find jest configuration example here – https://github.com/mantinedev/mantine/blob/master/jest.config.js
