### ISSUE TITLE
Hide Menu with `withinPortal` when it target is hidden (itself or one of parents)

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#2535]
### What package has an issue

@mantine/core

### Describe the bug

I have sticky header, when header is static - it have the navigation with Menu target (I'm used it to make priority navigation pattern)
When header is sticky, navigation is hidden.

So, I have a problem when I opened Menu (`withinPortal`), and scrolled and header changed status into sticky, target (trigger) is hidden, but menu still visible.

https://user-images.githubusercontent.com/18473137/191861274-bc36b39b-7648-4821-9d6d-58b0db31a455.mp4

### What version of @mantine/hooks page do you have in package.json?

latest

### Possible fix

Maybe you can use `use-intersection` internally or something similar to trigger close

**Comment by devstardude** [comment]
@7iomka @rtivital This looks interesting, Can I work on this?

**Comment by rtivital** [comment]
Yes, you can work on this

**Comment by devstardude** [comment]
@7iomka Can you please share the code from the above video, I want to try an idea that might fix the issue.

**Comment by 7iomka** [comment]
@devstardude https://codesandbox.io/s/dreamy-leftpad-mdfkgd?file=/src/App.tsx
Click to open menu, then try to scroll

**Comment by wes337** [comment]
What is the expected behavior? Should the menu close if you scroll it's toggle button out of view?

**Comment by rtivital** [comment]
I suppose that it should work the same way as Menu without Portal

**Comment by wes337** [comment]
Closing the menu dropdown using the menu context, when the children of `MenuTarget` unmount seems to fix this:

in `src/Menu/MenuTarget/MenuTarget.tsx`:
```jsx
    useEffect(
      () => () => {
        ctx.closeDropdown();
      },
      [children]
    );
```

However the transition effect still applies, which gives a slight delay: 
![image](https://user-images.githubusercontent.com/9464690/194234444-7ffe6396-3f4e-41b8-af72-45b787a9d160.png)

**Comment by wes337** [comment]
It also seems to work for when the element becomes hidden:

- `<div style={{ visibility: isSticky ? 'hidden' : 'visible' }}>`: works for this
- `<div hidden={isSticky}>`: works for this too

**Comment by rtivital** [comment]
@7iomka the fix provided by @wes337 will be available in next patch, reopen this issue if it does not solve it

**Comment by 7iomka** [comment]
What is actual fix for issue? Seems that prev solution is reverted and now issue is active for me with latest v5 version.
