### ISSUE TITLE
RichTextEditor not working with latest version

### ISSUE THREAD

**Issue by imaddev** [mantinedev/mantine#2536]
### What package has an issue

@mantine/rte

### Describe the bug

does not work with versions higher than 5.3.1

### What version of @mantine/hooks page do you have in package.json?

5.4.0

### Possible fix

maybe keep source with version **5.3.1** which works

**Comment by rtivital** [comment]
It works correctly on mantine.dev website – https://mantine.dev/others/rte/
Please provide a sandbox that reproduces the issue

**Comment by Zonalds** [comment]
I have the same issue. I am on nextJs. This only happens when I upgrade to the latest version

Here is what I get

**Comment by rtivital** [comment]
See https://github.com/mantinedev/mantine/issues/2488

**Comment by Zonalds** [comment]
> See #2488

Thanks, adding `id` works.
