### ISSUE TITLE
Modal manager's functions are not memoized

### ISSUE THREAD

**Issue by justinsmid** [mantinedev/mantine#2537]
### What package has an issue

@mantine/modals

### Describe the bug

Looking at [ModalsProvider](https://github.com/mantinedev/mantine/blob/322538d9ed2848816e6ffaf40fec92438d33fc3b/src/mantine-modals/src/ModalsProvider.tsx#L83-L136), it seems it's functions aren't memoized (`useCallback`). This is causing some of our components to re-render since we are passing these functions to dependency arrays of `useMemo` & `useCallback` and they change each render.

The same goes for NotificationsProvider and it's functions.

### What version of @mantine/hooks page do you have in package.json?

5.4.0

### Do you know how to fix the issue

Yes

### Possible fix

Memoize the modal manager's and notification manager's functions using `useCallback`

**Comment by rtivital** [comment]
Both modals and notifications functions are based on external events – https://github.com/mantinedev/mantine/blob/master/src/mantine-modals/src/events.ts

There is always one instance of each function – they do not change.

**Comment by justinsmid** [comment]
After further experimentation, I figured out a fix for my issue:

We have wrapper functions around `useModals` and `UseNotifications` that provide us with some extra functions and default styling:

```ts
import { useModals as useMantineModals } from "@mantine/hooks"

export function useModals() {
  const { openModal, ...rest } = useMantineModals()
  
  // Our own functions
  
  return useMemo(() => ({
    ...rest,
    // Our own functions
  }), [
    rest,
    // Our own functions
  ])
}
```

As you can see, we were passing `rest` into our `useMemo`'s dependency array. If we instead explicitly get each function from mantine's hook and explicitly add these to the array, it works!:

```ts
// ...
const {
    openConfirmModal,
    openModal,
    openContextModal,
    closeModal,
    closeAll,
    modals,
  } = useMantineModals()
  
  // ...
  
  return useMemo(
    () => ({
      openConfirmModal,
      openModal,
      openContextModal,
      closeModal,
      closeAll,
      modals,
      // Our own functions
    }),
    [
      openConfirmModal,
      openModal,
      openContextModal,
      closeModal,
      closeAll,
      modals,
      // Our own functions
    ]
  )
```

Not entirely sure why this is the case, but I'll take it.
