### ISSUE TITLE
DatePicker onDropdownClose is called every mouse click outside component when no date was selected

### ISSUE THREAD

**Issue by Martijn-Schoenmaker-Webbio** [mantinedev/mantine#2538]
### What package has an issue

@mantine/dates

### Describe the bug

When opening the datepicker and closing it again after not having selected a date, the onDropdownClose call is fired every time you click outside a component. It only stops when opening again and selecting a date.

### What version of @mantine/hooks page do you have in package.json?

5.4.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-datepicker-ondropdownclose-calls-jhujml?file=/src/App.tsx

**Comment by snehilvj** [comment]
+1

**Comment by Martijn-Schoenmaker-Webbio** [comment]
@rtivital I think this issue is fixed with the 5.5.1 update by this merge --> https://github.com/mantinedev/mantine/pull/2602

**Comment by rtivital** [comment]
This PR is for MultiSelect only, there were no changes for DatePicker component

**Comment by Martijn-Schoenmaker-Webbio** [comment]
It seems like it did, I cannot replicate the issue in v 5.5.1: [Codesandbox](https://codesandbox.io/s/mantine-datepicker-ondropdownclose-calls-forked-2h3d99?file=/src/App.tsx)

**Comment by rtivital** [comment]
Well, no idea how it fixed it, but I'll take it
