### ISSUE TITLE
DatePicker onChange is called multiple times when allowFreeInput is set to true

### ISSUE THREAD

**Issue by Martijn-Schoenmaker-Webbio** [mantinedev/mantine#2539]
### What package has an issue

@mantine/dates

### Describe the bug

The following issues occur when allowFreeInput is set to true:

- When clearing the datepicker, the dropdown opens
- onChange is called when onBlur is called on the component, even though the value is the same.

### What version of @mantine/hooks page do you have in package.json?

5.4.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-datepicker-onchange-callbacks-5xblxg

**Comment by rtivital** [comment]
It is expected behavior, it is not planned to be fixed
