### ISSUE TITLE
use-idle documentation does not state what unit the timeout is in

### ISSUE THREAD

**Issue by JavaScriptJohn** [mantinedev/mantine#2540]
### Link to the page where something nasty is located

https://mantine.dev/hooks/use-idle

### Exact quote of what is wrong

I know this isn't a big deal and I'm sure it's in milliseconds, but it had me looking around for it

**Comment by rtivital** [comment]
First sentence: `use-idle detects if user does nothing for given time in ms:`

**Comment by JavaScriptJohn** [comment]
I completely missed it!
