### ISSUE TITLE
Group overwrites flexGrow of children due to css selector

### ISSUE THREAD

**Issue by jjantschulev** [mantinedev/mantine#2543]
### What package has an issue

@mantine/core

### Describe the bug

I found this commit after some digging into a css issue I'm having after upgrading to mantine 5.4.0 from 5.3.0. 

If I have a `<Group spacing={2} />` with several children and I want only a single one of these children to have `flex-grow: 1` then the child selector `& > *` will sometimes overwrite the `flex-grow: 1` of the child component with the `flex-grow: 0` rule since the parent Group component has `grow=false`. This happens if the group re-renders it's css class after the children have already rendered. 

This issue does not occur in mantine version 5.3.0

Here is a sample snippet to show this effect:
```tsx
import { Group, Stack, Box, MantineProvider, Button } from "@mantine/core";
import { useState } from "react";

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <Stack>
        <Group spacing={count}>
          <Box sx={{ backgroundColor: "red" }} p={10}>
            Normal Content here
          </Box>

          <Box sx={{ backgroundColor: "orange" }} p={10}>
            More Content here
          </Box>
          <Box sx={{ backgroundColor: "lightblue", flexGrow: 1 }} p={10}>
            Spacer {count}
          </Box>
          <Box sx={{ backgroundColor: "yellow" }} p={10}>
            Right side content
          </Box>
        </Group>
        <Button onClick={() => setCount((c) => c + 1)}>click</Button>
      </Stack>
    </MantineProvider>
  );
}


```

In this example, the initial render will be correct however, after clicking the button the box with `flexGrow: 1` will no longer expand to fill the space. 

I believe that this issue was introduced with this commit: 
https://github.com/mantinedev/mantine/commit/c4f6c7bf4be643e69e54e0309e0b289018573587

### What version of @mantine/hooks page do you have in package.json?

5.4.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/optimistic-spence-9i41n4?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hi @jjantschulev, this is expected behavior based on new selector that Group uses, we've discussed it and decided that it will be a better approach rather than injecting className into every child. You can use `!important` to make sure that Group will not override your flex-grow styles.
