### ISSUE TITLE
Popover: the second time you click outside, popover will no longer hide

### ISSUE THREAD

**Issue by jackyleefu** [mantinedev/mantine#2551]
### What package has an issue

@mantine/core

### Describe the bug

Popover: the first time you outside, it will be hidden, but the second time you click outside, popover will no longer hide

mantine official website with the reproduced problem

### What version of @mantine/hooks page do you have in package.json?

v5.4.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/popover/#usage

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by rtivital** [comment]
Fixed in 5.5.0
