### ISSUE TITLE
@mantine/rte npm vulnerabilities warning

### ISSUE THREAD

**Issue by Celso-Ricardo** [mantinedev/mantine#2552]
### What package has an issue

@mantine/rte

### Describe the bug

The Quill rich text editor package seems to throw a warning when installing, please build the @mantine/rte with Facebooks Lexical 

https://github.com/facebook/lexical

### What version of @mantine/hooks page do you have in package.json?

"^5.4.0"

### Do you know how to fix the issue

No

### Possible fix

use alternative rich text editor in the package.

**Comment by rtivital** [comment]
It is not an issue with `@mantine/rte` package
