### ISSUE TITLE
Grid offset overwritten to 0 on all breakpoints by default

### ISSUE THREAD

**Issue by TheRarita** [mantinedev/mantine#2556]
### What package has an issue

@mantine/core

### Describe the bug

https://codesandbox.io/s/quirky-night-zjv0rj?file=/src/App.tsx

All offset values have defaulted now to 0 so it no longer works as `min-width` query, as documentation claims - https://mantine.dev/core/grid/?t=props. 

In the sandbox you can see that the offset only shows on medium breakpoint, but returns to 0 on large.

### What version of @mantine/hooks page do you have in package.json?

5.4.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/quirky-night-zjv0rj?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by rtivital** [comment]
Fixed in 5.5.4
