### ISSUE TITLE
Calendar: `hideOutsideDates` doesn't work if the outside day is disabled

### ISSUE THREAD

**Issue by klswn** [mantinedev/mantine#2568]
### What package has an issue

@mantine/dates

### Describe the bug

If an "outside" day is `disabled` (by setting a `minDate` for instance) then it doesn't receive the `data-outside` prop and the styling that enforces `hideOutsideDates` is never applied.

### What version of @mantine/hooks page do you have in package.json?

5.4.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/autumn-hill-efnv81?file=/src/App.tsx

### Possible fix

I was able to get it working with `data-outside={(outside && (!disabled || hideOutsideDates)) || undefined}` but I'm not sure if there are any unintended consequences from overriding `disabled` here

**Comment by swee76** [comment]
Any Updates?  when disabling dates (maxDate) show the outside Dates on calendar

**Comment by rtivital** [comment]
It will be fixed in 6.0 release

**Comment by rtivital** [comment]
Fixed in 6.0
