### ISSUE TITLE
AppShell creates small gaps between header, navbar, and children

### ISSUE THREAD

**Issue by RedFour** [mantinedev/mantine#2570]
### What package has an issue

@mantine/core

### Describe the bug

When using the AppShell component, it leaves a small one or two pixel gap at the bottom of the header. This can be seen between the header and the navbar, or the header and the children content.

### What version of @mantine/hooks page do you have in package.json?

5.4.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/charming-smoke-ln3vyd?file=/src/App.js

**Comment by rtivital** [comment]
It is header border – https://codesandbox.io/s/vibrant-jerry-z9y1nb
