### ISSUE TITLE
startNavigationProgress from global context generates state issues

### ISSUE THREAD

**Issue by defrex** [mantinedev/mantine#2571]
### What package has an issue

@mantine/nprogress

### Describe the bug

I'm attempting to use `@mantime/nprogress` with Apollo Client (as an `ApolloLink`) for a global loading indicator. The exact timing of Apollo request isn't bound to the React rendering flow. Unfortunately, if `startNavigationProgress` is called while React is rendering, React throws the following.

```
Cannot update a component (`NavigationProgress`) while rendering a different component
```

I've also noticed that, since progress is stopped by `resetNavigationProgress`, multiple requests at once don't stack well. That is, the first request to complete will clear the loading state from the next, even if it's still in progress.

Ideally I could call `startNavigationProgress` at arbitrary times, and an arbitrary number of times, and be able to stop them individually. A `stopNavigationProgress` return value would suffice if a global stack is too complex.

### What version of @mantine/hooks page do you have in package.json?

5.2.4

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Store the progress state globally, and `useEffect` to sync it with the React component.

**Comment by rtivital** [comment]
Navigation progress and other similar modules use events that are added with `useLayoutEffect`. If you experience issues with firing events during render, you can call these functions in `useEffect`. I am not convinced that the fix should be done on our side.

**Comment by defrex** [comment]
I'm firing the events from outside React, so I have no opportunity to put them inside a `useEffect` callback.

To solve this without a Mantine fix, I'd need to manage my own global loading state with a very similar API, then call the nprogress methods from a custom effect somewhere near the top of my React tree. Doable but annoyingly redundant. 

Plus I suspect my usage here is pretty typical, so it seems like something worth solving at the framework level. Have you tried using the current API with Apollo? The only in-React opportunity to handle loading is with the result object of a `useQuery` hook, which would mean adding the progress implementation to every component that requests data, somewhat defeating the point of a global indicator, IMO.

**Comment by rtivital** [comment]
Alright, if you think that it should be solved on library level, let's start with a minimal reproduction that illustrates the issue, please use template to compose a sandbox – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6
