### ISSUE TITLE
V5.4.2 `ref` error on `SWITCH`

### ISSUE THREAD

**Issue by BignonAG** [mantinedev/mantine#2579]
### What package has an issue

@mantine/core

### Describe the bug

v5.4.2 has an error on `Switch`,  => `Property 'ref' does not exist on type 'IntrinsicAttributes & SwitchProps'`.

For reference, see issue #1769 

### What version of @mantine/hooks page do you have in package.json?

5.4.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/busy-surf-6b3xxd?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 5.5.0
