### ISSUE TITLE
Inconsistent focus management with `MultiSelect` and `Select`

### ISSUE THREAD

**Issue by steschwa** [mantinedev/mantine#2586]
### What package has an issue

@mantine/core

## Problem

> To understand the below lines please refer to the attached Codesandbox

Clicking on a `<MultiSelect>` input/trigger toggles the open state for the dropdown. In simple words: If the dropdown is closed and i click on the input/trigger it opens and if i click again it closes.

This behaviour is different to `<Select>` where a click on input/trigger with an opened dropdown **does not** toggle the dropdown. This only happens if the `<Select>` is created with a `searchable={true}` prop. If `searchable={true}` this code part makes sure the dropdown is always open on input focus: https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Select/Select.tsx#L506

## Expected

I would expect that both `<MultiSelect>` and `<Select>` behave the same if clicked independent of the value of `searchable`. I suggest to also toggle the dropdown for `<Select>` (adapt behaviour of `<MultiSelect>`)

### What version of @mantine/hooks page do you have in package.json?

5.1.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/happy-drake-qdc5j7?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Replace `handleInputFocus` at https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Select/Select.tsx#L506 with (not tested)
```typescript
const handleInputFocus = (event: React.FocusEvent<HTMLInputElement>) => {
  typeof onFocus === 'function' && onFocus(event);

  setDropdownOpened(!dropdownOpened);
  if(dropdownOpened) {
    scrollSelectedItemIntoView();
  }
};
```

**Comment by rtivital** [comment]
You are welcome to create a PR with a fix
