### ISSUE TITLE
Unable to import  SpotlightActionProps from '@mantine/spotlight'

### ISSUE THREAD

**Issue by pragathrao** [mantinedev/mantine#2587]
### What package has an issue

@mantine/spotlight

### Describe the bug

I would like to change how my action components would look and in the docs, SpotlightActionProps from '@mantine/spotlight' is being imported and specific properties are being extracted and then styled, but I am unable to import SpotlightActionProps in the First Place.

<img width="1279" alt="error" src="https://user-images.githubusercontent.com/78464411/193295928-cb82306c-afe6-448c-b991-672de574ae19.png">

### What version of @mantine/hooks page do you have in package.json?

5.4.1

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
`SpotlightActionProps` is a type, if you do not use TypeScript you need to remove all types imports from your code

**Comment by pragathrao** [comment]
Sorry, I  don't have knowledge of TypeScript, Could You Please then Tell, me how could I get the action property in JS so that I can customize the Spotlight

**Comment by rtivital** [comment]
Remove everything that is not JavaScript from your code.

**Comment by pragathrao** [comment]
I got it to work, Thanks a lot, Was just unable to understand how just destructuring spotlight properties in a random function made it work,
