### ISSUE TITLE
Type issue when referencing theme.primaryShade

### ISSUE THREAD

**Issue by aviemet** [mantinedev/mantine#2592]
### What package has an issue

@mantine/core

### Describe the bug

When using a theme system with light and dark options for `theme.primaryShade`, typescript gives an error when directly referencing the shade variable:

```typescript
const SomeComponent = () => <Box
	sx={ theme => ({
		borderColor: theme.colors[theme.primaryColor][theme.primaryShade.light]
                 // Property 'light' does not exist on type 'Shade | MantinePrimaryShade'.
                 // Property 'light' does not exist on type '0'.ts(2339)
	}) }
/>
```

I'm not sure how to achieve this, but it seems the final type of the theme object needs to choose either `Shade` or `MantinePrimaryShade` depending on whether it's using a toggle-able color scheme.

### What version of @mantine/hooks page do you have in package.json?

^5.4.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/quizzical-dew-bvf0fc?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
`theme.primaryShade` can be a string or an object, use `theme.fn.prumaryShade` function instead – https://codesandbox.io/s/sweet-cray-4xvh54?file=/src/App.tsx
