### ISSUE TITLE
Spoiler with buttons for labels causes nested <buttons /> warning

### ISSUE THREAD

**Issue by blahbleepew** [mantinedev/mantine#2594]
### What package has an issue

@mantine/core

### Describe the bug

Using a spoiler with something like an action icon as a label works but causes a chromium warning

Example:

`<Spoiler showLabel={<ActionIcon />} />`

Result:

`<button> cannot appear as a descendant of <button>`

### What version of @mantine/hooks page do you have in package.json?

5.4.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/objective-cartwright-nc9ul7?file=%2Fsrc%2FApp.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
It is expected, spoiler control is already a button, you cannot use ActionIcon or other buttons as labels.
