### ISSUE TITLE
FileButton onChange event is not trigerring

### ISSUE THREAD

**Issue by dauletbaev** [mantinedev/mantine#2595]
### What package has an issue

@mantine/core

### Describe the bug

I am creating `Menu` with `FileButton` and regular `Button`s when I click and select file on `FileButton`'s `onChange` event is not firing.

### What version of @mantine/hooks page do you have in package.json?

5.4.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hardcore-silence-tyjuds?file=/src/Component.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
FileButton does not trigger onChange because it is unmounted from the dom before user picks the value – https://codesandbox.io/s/gallant-edison-z4jk8c?file=/src/Component.tsx

**Comment by dauletbaev** [comment]
> FileButton does not trigger onChange because it is unmounted from the dom before user picks the value – https://codesandbox.io/s/gallant-edison-z4jk8c?file=/src/Component.tsx

Thanks, got it.
