### ISSUE TITLE
[bug] Tooltip doesn't work with icon property of Input component

### ISSUE THREAD

**Issue by percy507** [mantinedev/mantine#2596]
### What package has an issue

@mantine/core

### Describe the bug

See below code, the tooltip doesn't show the label.

```tsx
<TextInput
  label="Your email"
  placeholder="Your email"
  icon={
    <Tooltip label="This is a message">
      <div><IconAt size={14} /></div>
    </Tooltip>
  }
/>
```

> Here is a demo. https://codesandbox.io/s/intelligent-jackson-v624en?file=/src/App.tsx:461-468

### What version of @mantine/hooks page do you have in package.json?

5.4.2

**Comment by rtivital** [comment]
https://codesandbox.io/s/great-meadow-ee1h60
