### ISSUE TITLE
Unable to compile Gatsby docs

### ISSUE THREAD

**Issue by Jarrodsz** [mantinedev/mantine#260]
Trying to compile the Gatsby docs with yarn install and also tried npm install to no avail:

Cannot find module 'react/package.json'
Require stack:
- /System/Volumes/Data/srv/mantine/docs/node_modules/gatsby/dist/utils/webpack.config.js
- /System/Volumes/Data/srv/mantine/docs/node_modules/gatsby/dist/utils/start-server.js
- /System/Volumes/Data/srv/mantine/docs/node_modules/gatsby/dist/services/start-webpack-server.js
- /System/Volumes/Data/srv/mantine/docs/node_modules/gatsby/dist/services/index.js
- /System/Volumes/Data/srv/mantine/docs/node_modules/gatsby/dist/state-machines/develop/services.js
- /System/Volumes/Data/srv/mantine/docs/node_modules/gatsby/dist/state-machines/develop/index.js
- /System/Volumes/Data/srv/mantine/docs/node_modules/gatsby/dist/commands/develop-process.js

Any thoughts on how to resolve this? 
I cleared all caches and removed the .lock files tried several times with yarn and also with npm

**Comment by rtivital** [comment]
Make sure that you also install main repo dependencies

**Comment by rtivital** [comment]
You can find getting started guide here – https://trello.com/c/8j4I7zfg/3-getting-started-with-mantine-locally
