### ISSUE TITLE
RangeError: Invalid array length in Modal documentation

### ISSUE THREAD

**Issue by HoHieuLuc** [mantinedev/mantine#2601]
### Link to the page where something nasty is located

https://mantine.dev/core/modal/#size-auto

### Exact quote of what is wrong

If you keep clicking "Remove badge" button in the modal, count will be less than 0, and the website turns white with error: "RangeError: Invalid array length"

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
Thanks for reporting, the issue is fixed
