### ISSUE TITLE
objectPosition property does not result in object-position setting of image

### ISSUE THREAD

**Issue by grahampcharles** [mantinedev/mantine#2612]
### What package has an issue

@mantine/core

### Describe the bug

Setting the `objectPosition` property on the `sx` object of an `<Image>` does not set the corresponding `object-position` property in the object.

The code below returns a cropped image at position `50% 50%`, not the requested `0% 20%`

Inspecting the generated HTML you can see there's no `object-position` set.

```
        <Image
          height={300}
          width={500}
          fit={"cover"}
          sx={{ imagePosition: "0% 20%" }}
          src={
            "https://images.pexels.com/photos/12999041/pexels-photo-12999041.jpeg"
          }
        ></Image>
```

### What version of @mantine/hooks page do you have in package.json?

4.2.12 (but the codesandbox is running 5.4.2 and it's got the same issue)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/happy-fire-64thxs?file=/src/App.tsx:283-296

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Since other properties are conveyed to the element's `style` correctly (e.g., `border: "3px blue solid"` works fine) I would think that this property simply hasn't been included.

**Comment by rtivital** [comment]
You can apply styles to imp element using styles api – https://codesandbox.io/s/angry-heisenberg-x9n83j?file=/src/App.tsx

**Comment by grahampcharles** [comment]
Thanks! I see now that the css property (should have been `object-position` was being set on one of the containing parent divs, where it didn't have any visual effect.)
