### ISSUE TITLE
Button: bad UI when button is in loading state

### ISSUE THREAD

**Issue by HoHieuLuc** [mantinedev/mantine#2618]
### What package has an issue

@mantine/core

### Describe the bug

When button is in loading state, it is very hard to read the text
![image](https://user-images.githubusercontent.com/62865718/193591871-2292fab6-e5ba-4b03-972e-c564f68e6e97.png)
![image](https://user-images.githubusercontent.com/62865718/193591903-85192c5b-3ba8-4e50-8c74-a143c46af928.png)

This is what it used to look like:
![image](https://user-images.githubusercontent.com/62865718/193601795-5161b923-fd34-4384-9a7b-0abbb8716167.png)
![image](https://user-images.githubusercontent.com/62865718/193601842-e671cbbf-f8e5-450e-b149-115537595a19.png)

### What version of @mantine/hooks page do you have in package.json?

5.5.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/button/#loading-state

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Fixed in 5.5.1
