### ISSUE TITLE
Support Portal for Select/Autocomplete component

### ISSUE THREAD

**Issue by nghiepit** [mantinedev/mantine#262]
When using `Select` the select item component may be obscured by the parent element.
So we need support `Portal` to can be set `z-index` to override the parent element.
![image](https://user-images.githubusercontent.com/4768095/134241710-0f1600db-22e4-4179-aca9-33d28af2b687.png)

**Comment by cstrat** [comment]
I think this is an issue with overflow - not z-index.
On the portal div set the style to `overflow: visible` -- by default I am sure it is `hidden`.
Happens on a few other elements too.

**Comment by rtivital** [comment]
Duplicate of #202
