### ISSUE TITLE
Menu component keyboard navigation limited to two items

### ISSUE THREAD

**Issue by asplem** [mantinedev/mantine#2623]
### What package has an issue

@mantine/core

### Describe the bug

When using keyboard navigation with arow keys after expanding the Menu component, only the first two elements are accessible.

This can be demonstrated in both Chrome and Firefox, using both our own app and using the Mantine documentation.

This seems to have been introduced in 5.5.0, as the codesandbox template (with Mantine 5.4.2) in the bug report template has it working.

Working, with Mantine 5.4.2: https://codesandbox.io/s/agitated-hamilton-9mjzx6?file=/src/App.tsx

Not working, with Mantine 5.5.0: https://codesandbox.io/s/beautiful-galileo-219j69?file=/src/App.tsx

### What version of @mantine/hooks page do you have in package.json?

5.5.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/beautiful-galileo-219j69?file=/src/App.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by rtivital** [comment]
Fixed in 5.5.2
