### ISSUE TITLE
MultiSelect and form usage not working as before

### ISSUE THREAD

**Issue by BenJeau** [mantinedev/mantine#2627]
### What package has an issue

@mantine/core

### Describe the bug

Controlling `MultiSelect` with a form does not work like before (was using `5.0.0` and just upgraded to `5.5.2`). After some testing, it seems like the last version that worked as I expected it was `5.0.2`, so it seems it _may_ be a change introduced in `5.1.0` - you can try it by changing the versions of the packages to `5.0.2` in the codesandbox.

## Code

```ts
import { MultiSelect } from "@mantine/core";
import { useForm } from "@mantine/form";

const Example = () => {
  const form = useForm({
    initialValues: {
      emails: []
    }
  });

  return (
      <MultiSelect
        required
        data={[]}
        creatable
        searchable
        getCreateLabel={(query) => `+ Add '${query}' as an email`}
        rightSection={<></>}
        {...form.getInputProps("emails")}
      />
  );
};
```

## Expected behavior

When clicking the "Add ..." when typing in the field, I expect it to be added to the list of emails in the `MultiSelect` itself.

## Bug

Nothing is being shown after selecting the create label (when in the form itself there's a value in the array) and when adding more, nothing is still being shown (and looking in the form values, the list gets replaced with a list with only one element)

### What version of @mantine/hooks page do you have in package.json?

5.5.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/wizardly-benji-164b8c

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
It is how MultiSelect component is supposed to work, it is required to manage data state on your side – https://codesandbox.io/s/upbeat-orla-89u02k?file=/src/App.tsx

You can find an example of treatable multi select in documentation – https://mantine.dev/core/multi-select/#creatable
