### ISSUE TITLE
Image placeholder works not as expected

### ISSUE THREAD

**Issue by josch0** [mantinedev/mantine#2631]
### What package has an issue

@mantine/core

### Describe the bug

Without absolute height and width the placeholder is not usable. For responsive layouts, absolute height and width is not possible.

I would expect Image and AspectRatio in combination to solve the problem, but then the placeholder is not displayed at all.

### What version of @mantine/hooks page do you have in package.json?

5.5.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hungry-elgamal-gw2txo

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 5.5.6
