### ISSUE TITLE
Inheritance doesn't work as expected / confusion

### ISSUE THREAD

**Issue by activenode** [mantinedev/mantine#2632]
### What package has an issue

@mantine/core

### Describe the bug

We love the `MantineProvider` - yet, we are confused about it's inheritance model and not sure if this is intended or a bug and **if** intended it misses some architectural description in the docs.

Sample:

```
import { TextInput } ...
import { MantineProvider as Provider } ... 

<Provider theme={{
  components: {
    Input: {
      styles: { input: { background: 'red' } }
    }
  }
}}>

 
<Provider inherit theme={{
  components: {
   Select: {/** really doesnt matter ** /}
 }
}}>
   <TextInput /> /** this is not red **/
</Provider>
```

### What version of @mantine/hooks page do you have in package.json?

5.5.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/embed/mantine-provider-nesting-inheritance-qknmu0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Well long story short: Merge Strategy per Component when `inherit` is true.

**Comment by rtivital** [comment]
It is intended behavior to reduce theme merging complexity, themes are shallowly merged. Currently, there are not any plans to change merging logic.

**Comment by activenode** [comment]
Alright. But may I know in which way it reduces complexity? From a perspective of expecting  inheritance with the `inherit` property it's quite confusing.

You probably mean the complexity of merging deeply nested props on the mantine side. I'd get that but it would be nice to at least have a default of `components: {  ...prev.components }` .

Because otherwise one most do that in every single point of `MantineProvider` usage which is quite inconvenient. My proposal: A new flag `inheritComponents` - so it would be non-breaking. Or even more generic `inheritMode: 'shallow' | 'deep'`

**Comment by rtivital** [comment]
Components props can include `styles`, `classNames` and `defaultProps`. If full merging is implemented:
- `styles` from all MantineProviders should be applied (`styles` can be an object or a function)
- all `classNames` from all MantineProviders should be added to component styles api
- `defaultProps` should be merged

I do not really want to implement and then maintain this feature as it does not bring much value (you probably do not need it in 99% of applications).

I do not think that `inheritComponents` flag will make much sense – it will be as misleading as current `inherit`.

**Comment by activenode** [comment]
> Components props can include `styles`, `classNames` and `defaultProps`. If full merging is implemented:
> 
>     * `styles` from all MantineProviders should be applied (`styles` can be an object or a function)
> 
>     * all `classNames` from all MantineProviders should be added to component styles api
> 
>     * `defaultProps` should be merged

Agreed.

> I do not think that `inheritComponents` flag will make much sense – it will be as misleading as current `inherit`.

Agreed.

In a Design-Systems way of thinking where a specific context decides on specific looks (e.g. different look in dark mode) it kinda makes sense to inherit most of the stuff though.

I mean we can workaround it with doing `components: {...theme.components}` that'll do it for now. Also we might just write a `MantineProvider` wrapper that will do the job for us and we're good.

One thing we tried on component level was this:
```
<MantineProvider
        withNormalizeCSS
        withGlobalStyles
        theme={{
          components: {
            Input: {
              styles: (theme, params) => {
                return {
                  ...(theme.components.Input.styles(theme, params)),
                  otherCssProperty: 'whatever'
                }
              }
            }
          }
        }}
      >
```

but that lead to infinite recursion because in that lifecycle we are referring to the immediately same function.

Any good proposals / ideas other than building a custom wrapper?

**Comment by rtivital** [comment]
You can store theme overrides in variables and merge them on your side without using `inherit` option

**Comment by activenode** [comment]
Gotcha. Is there any good documentation what exactly to expect from `inherit` prop on `MantineProvider`? Maybe I missed it.

And say I'd invest a bit of time of proposing a merging mechanism would you want to see that or would you want to avoid it at all costs as of potential maintenance efforts?

**Comment by rtivital** [comment]
`inherit` is `{ ...parentTheme, ...themeOverride }`. You are welcome to submit a PR if you want to work on that.

**Comment by activenode** [comment]
Alright, thanks for the useful clarification. Curious where we go with this. Closing it for now :)
