### ISSUE TITLE
Chip colour prop is not changing the colour of the chip

### ISSUE THREAD

**Issue by SalhiYassine** [mantinedev/mantine#2634]
### What package has an issue

@mantine/core

### Describe the bug

On the mantine docs the chips do not change colour as and when selected, the same behaviour is observed in my own application.

https://mantine.dev/core/chip/?t=props

![image](https://user-images.githubusercontent.com/44145823/194074622-e7d5fa72-0666-4aad-bbef-04055fe57cb4.png)

### What version of @mantine/hooks page do you have in package.json?

"@mantine/core": "4.2.7",

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Color changes only for selected chip, same as for Checkbox, Radio and Switch components

**Comment by loganbenjamin** [comment]
I also came across this issue, it turns out the `Badge` component was a better fit for what I was doing.
