### ISSUE TITLE
withGlobalStyles and withNormalizeCSS do not respect emotionCache

### ISSUE THREAD

**Issue by stepzhou** [mantinedev/mantine#2641]
### What package has an issue

@mantine/core

### Describe the bug

Reading through https://mantine.dev/theming/emotion-cache/, I got the impression that all styles should use the custom emotion cache. However, only styles created via `createStyles` use the custom cache.

## Repro

Codesandbox has the repro. Inspecting the page, my custom style are under the new container. While the global styles are appended to the head.

### What version of @mantine/hooks page do you have in package.json?

5.4.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/awesome-leakey-gzl3my?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Possible fix

In MantineProvider https://github.com/mantinedev/mantine/blob/aa3b261914a873ede6ade244cda5df8812aec71c/src/mantine-styles/src/theme/MantineProvider.tsx, wrap `NormalizeCSS`, `GlobalStyles`, `Global` in emotion's `CacheProvider` if `emotionCache` is passed

**Comment by rtivital** [comment]
I've tried integrating emotion cache into Global component, but it broke ssr in Remix. You can change emotion cache of these styles by using CacheProvider exported from `@emotion/core` package.

**Comment by stepzhou** [comment]
@rtivital I don't see CacheProvider exported in the `@emotion/core` package. Or am I missing something?

**Comment by rtivital** [comment]
https://emotion.sh/docs/cache-provider

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
