### ISSUE TITLE
Avatar gradient variant

### ISSUE THREAD

**Issue by flamrdevs** [mantinedev/mantine#2643]
### What package has an issue

@mantine/core

### Describe the bug

Avatar gradient variant don't respect default theme gradient

### What version of @mantine/hooks page do you have in package.json?

5.5.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-avatar-bug-rj5jxq

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Maybe remove local default gradient

**Comment by zhulien-ivanov** [comment]
I'll take a look in an hour.
