### ISSUE TITLE
The rich text editor has some severity vulnerabilities

### ISSUE THREAD

**Issue by kisstamasj** [mantinedev/mantine#2644]
### What package has an issue

@mantine/rte

### Describe the bug

The npm package manager says there are severity vulnerabilities issues with the text editor wich is inculdes to the @mantine/rte package. 
```
npm audit
# npm audit report

quill  <=1.3.7
Severity: moderate
Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r
fix available via `npm audit fix --force`
Will install @mantine/rte@3.4.3, which is a breaking change
node_modules/quill
  quill-mention  *
  Depends on vulnerable versions of quill
  node_modules/quill-mention
    @mantine/rte  *
    Depends on vulnerable versions of quill-mention
    Depends on vulnerable versions of react-quill
    node_modules/@mantine/rte
  react-quill  >=0.0.3
  Depends on vulnerable versions of quill
  node_modules/react-quill

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```
The ``` npm audit fix --force``` command can't help.
Please consider the package update.

### What version of @mantine/hooks page do you have in package.json?

5.4.1

**Comment by rtivital** [comment]
In 6.0 rich text editor will be migrated to tiptap

**Comment by dwfee** [comment]
yes!!!

**Comment by imranbarbhuiya** [comment]
Are there any eta for v6?

**Comment by rtivital** [comment]
Tiptap editor was released in 5.8, `@mantine/rte` package should no longer be used

**Comment by twiddler** [comment]
If `@mantine/rte` should no longer be used, why is it still being updated? We're on 5.10.4 now, and we missed these vulnerabities. Deprecating the package now (at least without a major version bump) might break some projects, but I'd personally prefer that over carrying a vulnerability without knowing.

**Comment by rtivital** [comment]
It receives updates to stay compatible with `@mantine/core` in minor and patches releases.
