### ISSUE TITLE
Box inherited components like Breadcrumbs have no component property in typescript

### ISSUE THREAD

**Issue by AmirRivar** [mantinedev/mantine#2647]
### What package has an issue

@mantine/core

### Describe the bug

Although [Breadcrumbs main component is Box](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Breadcrumbs/Breadcrumbs.tsx#L60) and `component` property is supported by Breadcrumbs in plain Javascript, Typescript shows error.
This is happening in other components like Grid.

### What version of @mantine/hooks page do you have in package.json?

-

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/sparkling-platform-nc07fh

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
It is correct behavior, polymorphic components have huge performance impact, components that are not marked as polymorphic in documentation do not support `component` prop.
