### ISSUE TITLE
Datepicker month property cannot be used

### ISSUE THREAD

**Issue by Stouffi** [mantinedev/mantine#2648]
### What package has an issue

@mantine/dates

### Describe the bug

Datepicker component exposes a `month` property to enable controlled mode for the month display. But the `onMonthChange` prop counterpart is not available. In addition the value given to `month` is ignored.

Comparing with the `Calendar` component, everything work as expected the `month` and `onMonthChange` can be used and the month display is controlled.

I've linked to a codesandbox which reproduce the issue for `Datepicker` and showing how `Calendar` is currently working.

### What version of @mantine/hooks page do you have in package.json?

5.5.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/repro-datepicker-month-prop-ksfldr?file=/src/App.tsx

### Possible fix

When `month` and `onMonthChange` are provided, `Datepicker` should enable controlled mode for month display. i.e. `month` value should be forwarded to the inner `Calendar` and `onMonthChange` should be called directly from the inner `Calendar` as well as from various handlers where `setCalendarMonth` is called.

**Comment by rtivital** [comment]
Fixed, documentation for DatePicker and Calendar no longer includes this and other related props
