### ISSUE TITLE
Don't use color override in components with getRef

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#2653]
### What package has an issue

@mantine/core

### Describe the bug

Don't use color override in code like this
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Checkbox/Checkbox.styles.ts#L139
This makes it almost impossible to override color for (in this case) Checkbox icon in active state on MantineProvider level, because it doesn't support `getRef`.

### What version of @mantine/hooks page do you have in package.json?

latest

### Possible fix

Not use double color setup, or add a way to use getRef on provider level.
Because for now is only working solution is to use !important

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
