### ISSUE TITLE
Why Are There No Options for Non-TypeScript based Components?

### ISSUE THREAD

**Issue by Justin-Bento** [mantinedev/mantine#2654]
### Link to the page where something nasty is located

https://ui.mantine.dev/category/headers

### Exact quote of what is wrong

Why are there no updates for plain React Components? 

So my project are not big enough to use Typescript, but they do require a significant amount of components. So I decided to use Mantine UI, since it was very flexible. When I found their components pages, all the components were only integrated with typescript and React. However, I do not want to use Typescript since my bundle size is too large, and I would have to learn a new language.

I've tried replacing some Typescript elements inside the component. But I've have had no luck with it due my limited knowledge and how the React components are structured. So My question for the dev team is why has there been no update for both options since most people only need React? 

### Are you willing to create pull request with the fix?

I can help with some components

**Comment by rtivital** [comment]
Mantine UI is built with TypeScript, the website provides source code of components, we do not have source code written in JavaScript. Adding this feature will require a lot of additional maintenance, which we would like to avoid. To convert components to JavaScript:
- Remove all types from the code
- If you do not know what a type is, then remove everything that is not JavaScript, after that remove all imports
