### ISSUE TITLE
Tooltip is cut off by Card boundary

### ISSUE THREAD

**Issue by RedFour** [mantinedev/mantine#2655]
### What package has an issue

@mantine/core

### Describe the bug

Create component with tooltip in Card. On hover, the tooltip is cut off by the Card boundary.

### What version of @mantine/hooks page do you have in package.json?

5.4.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/optimistic-gagarin-i61qb9?file=/src/App.tsx

**Comment by rtivital** [comment]
https://codesandbox.io/s/hardcore-antonelli-ydw1fu?file=/src/App.tsx
