### ISSUE TITLE
Radio labelWrapper

### ISSUE THREAD

**Issue by dekisr** [mantinedev/mantine#2660]
This [commit](https://github.com/mantinedev/mantine/commit/0513a481428fac9b1b4cd4547df07b3393630fe4#diff-e124c5671eb583bcac043dcf043a4e3f25f9f1ffcb13a0998d3217d4c4ca3ba5) removed some properties that broke when using some react node as label.

- before:
![Captura de Tela 2022-10-07 às 14 10 40](https://user-images.githubusercontent.com/38201274/194617483-6c8e9431-898e-4739-b7be-0f24628b4f98.png)

- after:
![Captura de Tela 2022-10-07 às 14 10 46](https://user-images.githubusercontent.com/38201274/194617555-766debd0-85de-4fb7-8c60-b8f07ebf626a.png)

**Comment by aiheon** [comment]
does this break edit field?

**Comment by rtivital** [comment]
Fixed in 5.7.2
