### ISSUE TITLE
"global styles guide" link redirects to 404 page

### ISSUE THREAD

**Issue by maxratajczak** [mantinedev/mantine#2662]
### Link to the page where something nasty is located

https://mantine.dev/theming/theme-object/

### Exact quote of what is wrong

At the globalstyles section, the "global styles guide" link redirects to "https://mantine.dev/styles/global/" which is an invalid page.

**Comment by adarshaacharya** [comment]
I've [raised pr](https://github.com/mantinedev/mantine/pull/2666) for this issue.
@rtivital
