### ISSUE TITLE
404 page - guides to working with ssr

### ISSUE THREAD

**Issue by felipe2g** [mantinedev/mantine#267]
I found a link on Reddit who give this link: https://mantine.dev/guides/ssr/

And now this link is broken, thats correct?

Post on reddit.
https://www.reddit.com/r/javascript/comments/n3y4ov/mantine_new_react_library_60_hooks_and_components/

**Comment by rtivital** [comment]
Hi @felipe2g, that's correct, we've added better getting started guide, you can find it here – https://mantine.dev/getting-started/
