### ISSUE TITLE
Typo in CHANGELOG Version 5.0.0 Dropzone section

### ISSUE THREAD

**Issue by CShatto99** [mantinedev/mantine#2671]
### Link to the page where something nasty is located

https://mantine.dev/changelog/5-0-0/#dropzone

### Exact quote of what is wrong

The second bullet point under the CHANGELOG Version 5.0.0 Dropzone changes contains a typo. Here is the bullet point in question:

- `FullScreenDropzone` component is no loner exported from the @mantine/dropzone package, use Dropzone.FullScreen component instead

The word "loner" should be "longer"

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Feel free to send a pr with a fix

**Comment by CShatto99** [comment]
> Feel free to send a pr with a fix

Will do, thanks!

**Comment by rtivital** [comment]
Fixed
