### ISSUE TITLE
GridAutoColumns: dynamic simple grid columns based on a given width

### ISSUE THREAD

**Issue by EricEchemane** [mantinedev/mantine#2677]
This component will dynamically assign the number of columns of the grid. Basically, it will compute the number of columns with a given width-`widthBasis` that can span across the parent.

```typescript
import { SimpleGrid } from '@mantine/core';
import { useViewportSize } from '@mantine/hooks';

type Props = {
    widthBasis: number;
    children: JSX.Element[];
    spacing?: number | "xs" | "sm" | "md" | "lg" | "xl";
};

export default function GridAutoColumn({ widthBasis, children, spacing }: Props) {
    const { width } = useViewportSize();
    return (
        <SimpleGrid
            spacing={spacing}
            cols={Math.floor(width / widthBasis)}>
            {children}
        </SimpleGrid>
    );
}
```
![image](https://user-images.githubusercontent.com/68469018/194814141-0df94b66-5d75-44cb-aa0c-5f62cba2711b.png)
![image](https://user-images.githubusercontent.com/68469018/194814188-a8ce5324-2fbc-4d95-9e5d-904b04bf39f7.png)

**Comment by EricEchemane** [comment]
This way, we don't need to configure `cols` explicitly on different breakpoints.

**Comment by rtivital** [comment]
Hi @EricEchemane, please use issues only to report bugs, you can request features and ask questions in discussions.
We already provide auto size columns for Grid component – https://mantine.dev/core/grid/#auto-sized-columns
