### ISSUE TITLE
Add styles api support for Group and Stack components

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#2678]
### What package has an issue

@mantine/core

### Describe the bug

Please, add styles api support for Group and Stack components
I'm still have a problem with a lot of library components in Safari < 14, because `gap` in flex is not supported in this browsers. Of course, I know you not supported Safari < 14, but I'm not found any workaround to make polyfill myself (I read about stilis plugins, but not found any helpful info in documentation).

So I decided to make changes in Group and Stack components on Mantine provider level, but I was disappointed because I saw that api styles support is not added for it.

Tell me if it can be done
If you tell me how - I will make PR.

### What version of @mantine/hooks page do you have in package.json?

latest

**Comment by rtivital** [comment]
Group and Stack components support styles api, you can add styles to both components using sx or className prop or using root selector on MantineProvider – https://mantine.dev/styles/styles-api/#root-selector
