### ISSUE TITLE
Menu Dropdown position left or right, doesnt stay put on scroll

### ISSUE THREAD

**Issue by Adel-ak** [mantinedev/mantine#2688]
### What package has an issue

@mantine/core

### Describe the bug

When menu position is

- right
- right-start
- right-end
or 
- left
- left-start
- left-end

during scroll, it stays stuck on the top or bottom

https://user-images.githubusercontent.com/47484379/195162226-19a8317c-60f9-492e-a238-bc3499fb665b.mp4

### What version of @mantine/hooks page do you have in package.json?

^5.5.4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by davidtaing** [comment]
Hi @rtivital,
Can I please look into this? I'm not sure if I can fix it but I would like to try 🙂.

**Comment by Adel-ak** [comment]
@davidtaing this might help you out.

The issue has to be this

https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Popover/PopoverDropdown/PopoverDropdown.tsx#L71


I tired putting a limit to ctx.y yesterday, but the solution was mad ugly 😅

**Comment by davidtaing** [comment]
Thanks @Adel-ak, you've helped me get a lot closer.

That's pulling the value off the Popover Context. I'm trying to figure out how the `x` and `y` values are calculated.

This is quite fun 🙂.

### Popover.tsx
https://github.com/mantinedev/mantine/blob/aa3b261914a873ede6ade244cda5df8812aec71c/src/mantine-core/src/Popover/Popover.tsx#L214-L228

### usePopover.ts
https://github.com/mantinedev/mantine/blob/aa3b261914a873ede6ade244cda5df8812aec71c/src/mantine-core/src/Popover/use-popover.ts#L73-L89

**Comment by Adel-ak** [comment]
@davidtaing yaa I haven't been lucky enough in finding that part of the logic, I'll give it a go tonight again if you get unlucky as well

**Comment by davidtaing** [comment]
I'm completely lost, gotta pull out of this race, hahaha.

**Comment by Adel-ak** [comment]
@rtivital && @davidtaing I believe I've fixed it, a PR is coming soon

**Comment by davidtaing** [comment]
My man! Good work!

**Comment by rtivital** [comment]
Fixed in 5.5.6, thanks @Adel-ak!
