### ISSUE TITLE
Indicator not updates on dot prop change

### ISSUE THREAD

**Issue by nicolabosco87** [mantinedev/mantine#2697]
### What package has an issue

@mantine/core

### Describe the bug

Indicator dot not update when dot prop changes.

### What version of @mantine/hooks page do you have in package.json?

5.5.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/wizardly-worker-rxscy3?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Seems that in https://github.com/mantinedev/mantine/blob/7814222c56/src/mantine-core/src/Indicator/Indicator.tsx#L119 the hook depencencies is missing dot

**Comment by rtivital** [comment]
There is no dot switch in documentation

**Comment by zhulien-ivanov** [comment]
There is no dot switch in the Usage demo you're referencing.

**Comment by rtivital** [comment]
This prop is used only for numbers – https://mantine.dev/core/indicator/#usage-with-numbers

**Comment by rtivital** [comment]
You should use disabled prop to toggle Indicator visibility – https://codesandbox.io/s/intelligent-driscoll-rb5r96

**Comment by nicolabosco87** [comment]
Ok maybe the documentation should be edited (dot property usage is confusing). Thanks for the explanation
