### ISSUE TITLE
Scroll top affix with inconsistent enter animation

### ISSUE THREAD

**Issue by jca41** [mantinedev/mantine#2700]
### What package has an issue

@mantine/core

### Describe the bug

Rendering the scroll top affix example from the docs in a nested react component results in a inconsistent animation.

This can be observed on the docs page itself (https://mantine.dev/core/affix/) notice how the enter animation sometimes doesn't trigger.

Rendering the same example at the root react element instead of nested fixes the issue.
It seems that the presence of `useWindowScroll()` at the root element also fixes this.

### What version of @mantine/hooks page do you have in package.json?

5.5.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Hi @jca41, please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by jca41** [comment]
Tried a minimal repro, https://codesandbox.io/s/competent-borg-d1yitg?file=/src/App.tsx, https://d1yitg.csb.app/
It's not so noticeable, the "bug" was showing initially when dev-ing but the shared codesandbox seems fine?

But the issue can still be seen on your affix docs page https://mantine.dev/core/affix/ .
I'm using latest chrome MacOS.

**Comment by rtivital** [comment]
I do not see any issues on mantine.dev website or your sandbox (Chrome, Safari and Firefox on MacOS)

**Comment by jca41** [comment]
Weird wondering if it's specific to my browser setup? I'll try to find out.

What I'm seeing is that sometimes the enter animation doesn't trigger and the element just appears

**Comment by rtivital** [comment]
Cannot reproduce the issue, @jca41 feel free to reopen it if you can provide more details
