### ISSUE TITLE
Export Pagination's DefaultItem

### ISSUE THREAD

**Issue by affanshahid** [mantinedev/mantine#2703]
### What package has an issue

@mantine/core

### Describe the bug

I am using pagination and just want to wrap the default pagination controls in some anchor tags however I can't seem to import the DefaultItem from the pagination module, it isn't directly exported and I have to explicitly use the cjs path to import it. (Which lacks types so need to declare those manually as well).

### What version of @mantine/hooks page do you have in package.json?

^5.5.4

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Export `DefaultItem` from https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Pagination/index.ts

**Comment by rtivital** [comment]
You should set `itemComponent` instead:

```tsx
function MyComponent({ page }) {
  return <div>{page}</div>
}

<Pagination itemComponent={MyComponent} />
```

DefaultItem is internal component, it will not be exported from the library.

**Comment by rtivital** [comment]
Use itemComponent prop as shown above

**Comment by OrkhanAlikhanov** [comment]
Seems like `DefaultItem` can be access from esm folder but typescript won't resolve types.
```tsx
import {PaginationItemProps} from '@mantine/core'
import {
  DefaultItem as DefaultPaginationItem,
  // @ts-expect-error
} from '@mantine/core/esm/Pagination/DefaultItem/DefaultItem'
```

Note that since `DefaultItem` is an internal component it can be updated or removed without any need to be explained
