### ISSUE TITLE
Popover is not closing when click outside on the second time. 

### ISSUE THREAD

**Issue by csanchez24** [mantinedev/mantine#2710]
### What package has an issue

@mantine/core

### Describe the bug

the popover component is not closing on the second time when click outside.

popover open and close on target without problem but when click outside to close only the first time is working after the first time the popover is not closing clicking outside

thanks

### What version of @mantine/hooks page do you have in package.json?

5.4.1

**Comment by rtivital** [comment]
Update to the latest version, the issue is fixed.
