### ISSUE TITLE
Searchable Select filter breaks after choosing option

### ISSUE THREAD

**Issue by jagoral** [mantinedev/mantine#2717]
### What package has an issue

@mantine/core

### Describe the bug

**Steps to reproduce**

1. Go to [searchable select docs](https://mantine.dev/core/select/#searchable)
2. Open searchbox
3. Pick any value, for example `React`
4. Open the searchbox again

**Expected**
Only `React` value option is shown

**Current**
All values are shown, although the search query is equal to `React`. Also after removing the letter `t` from the end and adding it, still all values are shown. If we type another option, for example `Vue`, search works, until it will be selected.

### What version of @mantine/hooks page do you have in package.json?

5.5.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/select/#searchable

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Hint: I've tried to set custom `filter` function and on search change, when the value is equal to selected value, the `filter` function is not invoked.

**Comment by rtivital** [comment]
This is expected behavior, you can change that by setting `filterDataOnExactSearchMatch` prop

**Comment by jagoral** [comment]
That's right, thanks :) I think the more intuitive behaviour will be to set it by default to `true`, but this is just my opinion ;) Thanks for helping
