### ISSUE TITLE
NextJS Class errors

### ISSUE THREAD

**Issue by HigorAlves** [mantinedev/mantine#274]
- Using mantine core
-  Package version: 2.5.1
- In which browser and operating system issue occurred? All

I'm using NextJS with the configuration from the offical site and i get this error:

<img width="504" alt="Screen Shot 2021-10-01 at 22 33 45" src="https://user-images.githubusercontent.com/11262976/135699755-b8329f9f-dcb8-4cf6-9976-7f6f0d5d7177.png">

**Comment by taktran** [comment]
@HigorAlves You might want to follow https://mantine.dev/theming/next/ or https://github.com/mantinedev/mantine-next-template

I had a similar issue here: https://github.com/mantinedev/mantine/issues/53#issuecomment-912048220

**Comment by rtivital** [comment]
Closing this as issue was resolved in Discord
