### ISSUE TITLE
Using "height" <Image /> resolution becomes grainy

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#2741]
### What package has an issue

@mantine/core

### Describe the bug

Using inline styles for image height we get normal images:

```
const Photo = forwardRef<any, any>(({url, index, style, height, ...props}: any, ref) => {
  const inlineStyles = {
    transformOrigin: '0 0',
    height: height,
    overflow: 'hidden',
    objectFit: 'cover',
    ...style,
  }

  return (
    <Image ref={ref}
           src={url}
           className='bg-gray-200'
           style={inlineStyles}
           {...props}
    />
  )
})
```
![Screenshot 2022-10-19 at 13 16 54](https://user-images.githubusercontent.com/22228431/196664937-ba5394ac-c057-40a7-bded-83aa906dfb6f.png)

Using Mantine's `height` prop for image we get grainy images:

```
const Photo = forwardRef<any, any>(({url, index, style, height, ...props}: any, ref) => {
  const inlineStyles = {
    transformOrigin: '0 0',
    overflow: 'hidden',
    objectFit: 'cover',
    ...style,
  }

  return (
    <Image ref={ref}
           src={url}
           style={inlineStyles}
           height={height}
           {...props}
    />
  )
})
```
![Screenshot 2022-10-19 at 13 17 07](https://user-images.githubusercontent.com/22228431/196664992-949e53ae-b519-4a7c-8c57-12a2fe641678.png)

### What version of @mantine/hooks page do you have in package.json?

5.5.5

### If possible, please include a link to a codesandbox with the reproduced problem

-

### Possible fix

-

**Comment by rtivital** [comment]
Hi @atumas-bananamilk, please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by rtivital** [comment]
Hi @atumas-bananamilk, feel free to reopen the issue if you can provide a reproduction
