### ISSUE TITLE
[@mantine/core] Timeline.Item does not apply styles/classes when using Styles API

### ISSUE THREAD

**Issue by joelzwarrington** [mantinedev/mantine#2745]
### What package has an issue

@mantine/core

### Describe the bug

I am trying to modify the styles of a single `Timeline.Item` within `Timeline` but `styles` or `classNames` does not work.

Doesn't work:
```jsx
<Timeline>
  <Timeline.Item styles={{ itemBullet: { display: "none" } }}></Timeline.Item>
</Timeline>
```

Works, but applies to all Timeline items:
```jsx
<Timeline styles={{ itemBullet: { display: "none" } }}>
  <Timeline.Item></Timeline.Item>
</Timeline>
```

### What version of @mantine/hooks page do you have in package.json?

5.5.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-timeline-item-does-not-respect-styles-api-43g3q1?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by joelzwarrington** [comment]
@rtivital - any idea when this might be fixed? Would you want help to fix this issue?

**Comment by rtivital** [comment]
It is not planned to introduce styles API to static components in the future, `sx` prop can be used
