### ISSUE TITLE
Calendar month label does not update if controlled value changed

### ISSUE THREAD

**Issue by rfdrake27** [mantinedev/mantine#2749]
### What package has an issue

@mantine/dates

### Describe the bug

To reproduce:
1: Programmatically change the value of a controlled DatePicker without focusing the DatePicker. 
2: If you then focus the DatePicker, the month label at the top will be the previous date value. 

Simply blurring and then focusing the DatePicker again will update the value to the expected one. 

### What version of @mantine/hooks page do you have in package.json?

5.5.5

**Comment by rtivital** [comment]
Fixed in 6.0
