### ISSUE TITLE
Rating Component may be required React v18+

### ISSUE THREAD

**Issue by imaddev** [mantinedev/mantine#2760]
### What package has an issue

@mantine/core

### Describe the bug

I'm using Mantine with RedwoodJS v3.2.0 which uses React v17, the error is:

**WARNING in ../node_modules/@mantine/core/esm/Rating/RatingItem/RatingItem.js 64:13-18**
`export 'useId' (imported as 'useId') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)`

### What version of @mantine/hooks page do you have in package.json?

5.6.0

**Comment by imranbarbhuiya** [comment]
This is fixed in 99998dc4a484f160ce8d9ba4c8e8832b0d39b5f6

**Comment by rtivital** [comment]
Fixed in 5.6.1
