### ISSUE TITLE
Floating point value in playground of `Rating` component crashes the site.

### ISSUE THREAD

**Issue by PhantomKnight287** [mantinedev/mantine#2762]
### Link to the page where something nasty is located

https://mantine.dev/core/rating/

### Exact quote of what is wrong

Go to the [Rating Component](https://mantine.dev/core/rating), in the playground of the rating component change the integer into a floating point number(ex: 2.5), the site crashes.

The logs in the console
![image](https://user-images.githubusercontent.com/76196237/197138545-14aaceb1-2551-437b-9058-919789965e1a.png)

**Comment by zhulien-ivanov** [comment]
I'm onto it.

**Comment by rtivital** [comment]
Fixed
