### ISSUE TITLE
tailwind dark mode does not effect in Drawer

### ISSUE THREAD

**Issue by zx013** [mantinedev/mantine#2765]
### What package has an issue

@mantine/core

### Describe the bug

When I use tailwind dark mode like the following, it can work well.
```
function App() {
  const [colorScheme, setColorScheme] = useState<ColorScheme>('light');
  const toggleColorScheme = (value?: ColorScheme) =>
    setColorScheme(value || (colorScheme === 'dark' ? 'light' : 'dark'));

  return (
    <ColorSchemeProvider colorScheme={colorScheme} toggleColorScheme={toggleColorScheme}>
      <MantineProvider theme={{ colorScheme }} withGlobalStyles withNormalizeCSS>
        <div className={colorScheme}>
          ...
        </div>
      </MantineProvider>
    </ColorSchemeProvider>
  );
}
```
I use dark mode like this. It works well anywhere, but when I use it in Drawer, it doesn't work. I don't know why this problem is, is there any way to fix it?
```
<a href="#" className='text-green-600 dark:text-red-600'>
  Something show
</a>
```

### What version of @mantine/hooks page do you have in package.json?

5.6.0

**Comment by zx013** [comment]
I find the reason when I look at the Drawer's code. Drawers use OptionalPortal, so dark mode does not effect.  Then it's easy to solve it, set within Portal to false can let dark mode effect.

**Comment by LarsOlt** [comment]
Tailwind classes are not applied with the default withinPortal=true, fixed it by setting withinPortal to false.

```
  <Drawer
    opened={menuOpened}
    onClose={() => setMenuOpened(false)}
    title="Menu"
    padding="xl"
    size="xl"
    withinPortal={false}
  >
    <h2 className="text-xs font-normal text-yellow-400">Settings</h2>
    <h3 className="text-base">Payment Methods</h3>
  </Drawer>
```
