### ISSUE TITLE
Typo in code block for Ratings doc

### ISSUE THREAD

**Issue by pillows** [mantinedev/mantine#2773]
### Link to the page where something nasty is located

https://mantine.dev/changelog/5-6-0/

### Exact quote of what is wrong

```
import { Radio } from '@mantine/core';

function Demo() {
  return <Rating defaultValue={2} />
}
```
I believe the import should be of Rating and not Radio.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Fixed
