### ISSUE TITLE
Tooltip not working on mobile

### ISSUE THREAD

**Issue by BoringBoredom** [mantinedev/mantine#2775]
### What package has an issue

@mantine/core

### Describe the bug

Expected behavior: touching and holding the element shows the tooltip
Result: tooltip is not showing
Tested browsers: Chrome's device toolbar (Windows), Firefox (Android)

### What version of @mantine/hooks page do you have in package.json?

5.6.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/tooltip/

**Comment by rtivital** [comment]
Tooltip is hidden on mobile by default, you can enable touch events in your application – https://mantine.dev/core/tooltip/#change-events
