### ISSUE TITLE
Fields whose specified `validate` function has Regex need to be changed on every submit

### ISSUE THREAD

**Issue by tfedawy** [mantinedev/mantine#2791]
### What package has an issue

@mantine/form

### Describe the bug

I have a login form with email and password. It's validate property is set as follow 
```
validate: {
      email: (value: string) => emailRegex.test(value) ? null : "Invalid email",
      password: (value: string) => value.length > 0 ? null : "Password is required",
    }
```

If I submit the form with **a valid email and an empty password**, validate will work as expected and only shows an error for the password email.

However, once I fill the password and resubmit. It shows a validation error for the email (which has an unchanged valid input).

### What version of @mantine/hooks page do you have in package.json?

 "@mantine/core": "^5.5.5",     "@mantine/form": "^5.5.5",

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/crazy-feynman-yvosl3?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Haven't gone through the source code deep enough to suggest anything.

**Comment by tfedawy** [comment]
I did some more investigation and it works fine if I put the regex itself directly in the validate, instead of the variable it's assigned to.

I'm not entirely sure if this behavior is indeed expected if the Regex is assigned to a variable, so I'll leave this open until it's reviewed.

**Comment by rtivital** [comment]
I cannot reproduce the issue in your sandbox – https://codesandbox.io/s/vibrant-robinson-oph7kh?file=/src/App.tsx


https://user-images.githubusercontent.com/10353856/197693097-9f036422-47fa-4cd2-814e-8e1333088688.mov
