### ISSUE TITLE
Custom theme not rendering different variants of the same component.

### ISSUE THREAD

**Issue by gfera** [mantinedev/mantine#2813]
### What package has an issue

@mantine/core

### Describe the bug

Hey folks, 

I'm trying to set custom variants for a `<Select />` component. 

The root (and only) theme, has specific `border` styling according to the component's variant (`default` | `filled`).

The final result does not reflect the specified styling. 

After doing some debugging, the custom theme receives many calls (for the different sub-components that conform the `<Select />` component)  but with missing props.:

<img width="770" alt="Screenshot 2022-10-26 at 20 02 35" src="https://user-images.githubusercontent.com/6557215/198154783-affa0fa5-505c-44e8-9efb-bd9ff3f06beb.png">

### What version of @mantine/hooks page do you have in package.json?

5.6.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-theme-variant-bug-b8i56l

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Select does not support styles params, that is why the package does not export `SelectStylesParams` type, you should not use it. You can customize Input on MantineProvider instead – https://mantine.dev/styles/styles-api/#inputs-styles-api-on-mantineprovider

**Comment by gfera** [comment]
Hi @rtivital, thanks for your quick response. 

Are there any plans for supporting an eventual `SelectStylesParams` param at the custom theme level?
