### ISSUE TITLE
Dropzone reject status is not disaplayed when file that exceeds `maxSize` is dragged over

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#2814]
### What package has an issue

@mantine/dropzone

### Describe the bug

When you hover over a file that exceeds `maxSize`, the `<Dropzone.Reject />` icon is not showing up, instead it shows `<Dropzone.Accept />` icon.

![Screenshot 2022-10-27 at 08 57 40](https://user-images.githubusercontent.com/22228431/198203307-0857a799-661b-4ed9-870c-0b4b27330d55.png)

You can even see it on Mantine example:
https://mantine.dev/others/dropzone/#usage

Or code example:
https://codesandbox.io/s/ancient-frost-jf1qm4

### What version of @mantine/hooks page do you have in package.json?

5.6.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/ancient-frost-jf1qm4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
I suppose that react dropzone does not support that because there is no way of knowing file size before it was dropped

**Comment by atumas-bananamilk** [comment]
I remember it worked before, but I think I was using the `5.1.5` version.

**Comment by rtivital** [comment]
Maybe an issue with react-dropzone package

**Comment by chewhx** [comment]
This is a known bug: https://github.com/react-dropzone/react-dropzone/issues/1238

**Comment by rtivital** [comment]
The issue must be fixed on react-dropzone side, nothing can be done on out side
