### ISSUE TITLE
Proper focus styling not applied to chip & styling unaccessible for config

### ISSUE THREAD

**Issue by maxratajczak** [mantinedev/mantine#2821]
### What package has an issue

@mantine/core

### Describe the bug

When focusing on a chip component, mantine classes are not applied, making it unable to be customized.

Just as an example, if setting global focus styling and explicitly setting the component state in chrome dev tools then proper styles apply.

<img width="558" alt="Screen Shot 2022-10-27 at 9 48 46 AM" src="https://user-images.githubusercontent.com/75450072/198302476-18e3d0b5-d3c5-44f1-bb22-a155fe94b57c.png">

<img width="470" alt="Screen Shot 2022-10-27 at 10 16 08 AM" src="https://user-images.githubusercontent.com/75450072/198310282-5919ba72-c58c-4247-b215-948b38c1d932.png">

However, when **actually** using the keyboard to navigate, classes do not apply and default styling is applied, making it unable to change styles.

<img width="377" alt="Screen Shot 2022-10-27 at 9 51 19 AM" src="https://user-images.githubusercontent.com/75450072/198303140-f0d15ee2-8fd4-479a-909b-692d4b25d8d0.png">

I've tried editing the component level styles and all sorts of overriding, but nothing seems to work.

### What version of @mantine/hooks page do you have in package.json?

5.6.2

**Comment by rtivital** [comment]
As I've mentioned in this discussion – https://github.com/mantinedev/mantine/discussions/2789, you can change Chip focus styles by following the same logic as used in component styles – https://codesandbox.io/s/affectionate-sky-zkx37q?file=/src/App.tsx
