### ISSUE TITLE
Mantine has hydration error with Remix that breaks styling

### ISSUE THREAD

**Issue by aniravi24** [mantinedev/mantine#2823]
### What package has an issue

@mantine/core

### Describe the bug

Mantine is getting a hydration error with Remix. I don't recall this happening before, but now, even with the [mantine remix template](https://github.com/mantinedev/mantine-remix-template/), it's showing a hydration error that wasn't there before. It causes the styling to break on the page. In the codesandbox below, the page usually shows up with a dark background, but it's showing up light when there's an error. If you try opening the codesandbox below in an incognito tab in Chrome (there are codesandbox errors in the devtools console where it can't access certain window objects because the browser seems to be preventing it), the styling works fine. I think the window/DOM modifications that are happening with the emotion cache could be causing this issue. It may happen with React SSR in general, but I'm not sure.

The codesandbox is just a fork of the mantine remix template with no changes.

![image](https://user-images.githubusercontent.com/5902976/198383509-aad01bac-dac7-4e75-a2f2-15ebcba84911.png)

### What version of @mantine/hooks page do you have in package.json?

5.6.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/github/aniravi24/mantine-remix-template-codesandbox/master

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hydration mismatch is caused by extensions that are injecting elements in the head. It causes remix to throw an error. You can open your sandbox in incognito mod, it will work correctly.
<img width="1347" alt="Снимок экрана 2022-10-28 в 12 39 26" src="https://user-images.githubusercontent.com/10353856/198544018-05f6eefc-df09-4837-8d63-0f7f17365bd3.png">

**Comment by aniravi24** [comment]
@rtivital I don't think it's because of browser extensions, because it happens on mobile Chrome as well as the Chrome guest profile, which is a clean browser session with no extensions.

As I had mentioned in my original post, I think the fact that it works in incognito is only because it's actually unable to access certain DOM elements, so the styling looks like it's working but it might not be getting cached correctly. The errors in the screenshot below only show up in an incognito tab. You can inspect the console in codesandbox to see the errors below in incognito mode.

![image](https://user-images.githubusercontent.com/5902976/198702028-05f8589b-faff-49b3-96ef-a17c1455dac4.png)

**Comment by aniravi24** [comment]
@rtivital Oh strange, I notice the error happens in codesandbox in the chrome guest profile, but it actually doesn't seem to be happening when I'm running my actual app in the guest profile. So while it is caused by browser extensions, whatever codesandbox is doing to render the app in their sandbox is also causing the same behavior. Interesting, thanks!

**Comment by aniravi24** [comment]
@rtivital Oh strange, I notice the error happens in codesandbox in the chrome guest profile, but it actually doesn't seem to be happening when I'm running my actual app in the guest profile. So while it is caused by browser extensions, whatever codesandbox is doing to render the app in their sandbox is also causing the same behavior. Interesting, thanks! I did figure out what browser extension is causing it locally for me.

I wonder if React or Remix (whichever one is causing this issue) has a way of handling this so it's more resilient to browser extensions.

**Comment by aniravi24** [comment]
For anyone else that runs into this, here's an issue you can look through to see what others are saying:
https://github.com/remix-run/remix/issues/4175

**Comment by aniravi24** [comment]
Will close since mantine is not causing it.
