### ISSUE TITLE
Defining primaryColor throws "Cannot read properties of undefined (reading '5')"

### ISSUE THREAD

**Issue by Slapbox** [mantinedev/mantine#2824]
### What package has an issue

@mantine/core

### Describe the bug

If `primaryColor` is defined as anything other than a named HTML color (eg 'red', 'orange'), Mantine throws an error like `Cannot read properties of undefined (reading '5')`

**Important: Only occurs if there's an element that's a candidate for receiving focus-ring**

### What version of @mantine/hooks page do you have in package.json?

5.6.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/fancy-morning-gfjbbw?file=/src/App.tsx

### Do you know how to fix the issue

No

### Possible fix

Not sure what the cause is.

**Comment by rtivital** [comment]
https://mantine.dev/theming/colors/#primary-color

<img width="842" alt="image" src="https://user-images.githubusercontent.com/10353856/198526043-43ce689d-fb4a-495b-bbbf-8ea29fe9f618.png">

**Comment by Slapbox** [comment]
Whoops sorry to open this nonsense issue, I didn't see that.
