### ISSUE TITLE
Odd click behaviour of Menu.Target

### ISSUE THREAD

**Issue by fmca-celine** [mantinedev/mantine#2828]
### What package has an issue

@mantine/core

### Describe the bug

I found an odd behaviour while working on a site and made a sandbox with a reduced example. 

When changing the size of the Menu.Target (on same state as Menu itself), the clickable area stays where the original element was. Expected behaviour is for the new size of the element to act as the close button.

There is more information describing the issue in the sandbox itself, with instructions on how to see the issue.

### What version of @mantine/hooks page do you have in package.json?

5.6.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-menu-issue-i0lv2s?file=/src/App.jsx

### Do you know how to fix the issue

No

**Comment by bobwade** [comment]
Change your `onClick` to `onMouseDown` for the Drawer trigger.

From MDN (emphasis mine):

> An element receives a click event when a pointing device button (such as a mouse's primary mouse button) is both pressed **and released** while the pointer is located inside the element.

By the time the release happens the mouse is not located inside the wide bookings button as the menu button has resized 🙂

**Comment by fmca-celine** [comment]
Changing the trigger works. Does not feel great, but if it works, it works 🙂
Thank you for the help!

**Comment by bobwade** [comment]
No worries! Another option is to keep the menu trigger the same width (e.g. with padding or making the text transparent) when it's toggled so the other links/triggers don't move around, depends on what you need tho.
