### ISSUE TITLE
Slider with min and max specified only accepts values less or equal than `max - min`

### ISSUE THREAD

**Issue by el1f** [mantinedev/mantine#2834]
### What package has an issue

@mantine/core

### Describe the bug

When a slider has both its minimum and maximum value specified it seems to stop working correctly. Using a slider with `min={32}` and `max={64}` it doesn't detect any change, when changing max to `max={96}` it accepts values up to `64`,  raising it to `max={128}` accepts only values up to `96` and so on.

### What version of @mantine/hooks page do you have in package.json?

5.6.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/lucid-bessie-7suk2d?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
@wes337 another one related report
