### ISSUE TITLE
Default padding (gaps) not rendered in Safari

### ISSUE THREAD

**Issue by gtanev** [mantinedev/mantine#2836]
### What package has an issue

@mantine/core

### Describe the bug

I'm testing out Mantine and finding Safari doesn't render what seems to look like the default horizontal padding between components, implemented with the CSS `gap` property.

Safari:

![SafariGap](https://user-images.githubusercontent.com/11413402/198730918-8c8a8d3c-bd86-4f1f-8d9b-27c47ee2ce52.png)
---
Chrome, Edge, Brave, Firefox: 

![ChromeGap](https://user-images.githubusercontent.com/11413402/198730947-eebef95b-ad9f-481b-bd3f-35e15cc616d9.png)
---
When I disable the CSS gap property in Chrome, I get the same result as in Safari.

![MantineGap](https://user-images.githubusercontent.com/11413402/198731203-3e1a247c-e236-4ed2-be86-7991197aaa5f.png)
---
The components being rendered are `ColorSwatch` instances with `Text` next to them:

```  
const LabeledSwatch = ({ color, label }) => (
    <>
        <ColorSwatch key={label} color={color} radius={0} size={20} mr={-5}/>
        <Text size={"sm"}>{label}</Text>
    </>
);
```  

The reason I'm adding the margin is to narrow the gap between the color swatch and the label, but Safari seems to only consider the margins and ignore the gaps.

I am using  `@mantine/core` v5.5.5 and my `MantineProvider` is initialized with `withGlobalStyles` and `withNormalizeCSS`.

### What version of @mantine/hooks page do you have in package.json?

5.5.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by gtanev** [comment]
P.S. The same thing happens when I render `Switch` components next to one another inside a parent `Group`. There is no gap in Safari between the `label` of the preceding `Switch` and the next toggle, so this seems to be a global issue.

**Comment by rtivital** [comment]
It is mentioned in documentation, flexbox gap is not supported in older versions of Safari – https://mantine.dev/core/group/#browser-support
There are no plans to fix that, see https://github.com/mantinedev/mantine/issues/2804

**Comment by gtanev** [comment]
> It is mentioned in documentation, flexbox gap is not supported in older versions of Safari – https://mantine.dev/core/group/#browser-support There are no plans to fix that, see #2804

I was testing it on Safari 14.1, which isn't that old, and according to [official docs](https://developer.apple.com/documentation/safari-release-notes/safari-14_1-release-notes) should support the flexbox gap property. I also tested on older versions of Chrome and Firefox (pre-2020) and the gap seems to render fine. 

Perhaps instead of saying "In older browsers Group children will not have spacing" on your website, you could be more specific and include a link to https://developer.mozilla.org/en-US/docs/Web/CSS/gap#browser_compatibility or something similar?

I find it amusing how according to both of the aforementioned resources the gap property should work in Safar 14.1, and yet it doesn't in this case.

**Comment by 7iomka** [comment]
@gtanev Hi.
 did you really find this problem in action on the mobile version of safari 14.1? 
Desktop Safari has gap support since v 14.5.
I am very concerned about this question at the moment.
I am currently using a workaround in the form of overwriting gap to 0 with the indentation set as negative values on the container and positive values on the children. This approach have different issues, and and I'm wondering how critical it would be to abandon support for 1-2% of users of such browsers.

**Comment by gtanev** [comment]
@7iomka Yeah, it's unfortunate they decided to implement this with the gap property. What I wound up doing in my case was setting the `columnGap` property of the parent `Group` component to `unset`  and then simply adding a margin to the children that need to be offset. This works well across browsers and doesn't produce any undesired side-effects.

**Comment by 7iomka** [comment]
> @7iomka Yeah, it's unfortunate they decided to implement this with the gap property. What I wound up doing in my case was setting the `columnGap` property of the parent `Group` component to `unset` and then simply adding a margin to the children that need to be offset. This works well across browsers and doesn't produce any undesired side-effects.

Currently I used the workaround that I described here
https://stackoverflow.com/a/75720902/4788881
