### ISSUE TITLE
[Feature Request] Freeform DatePicker

### ISSUE THREAD

**Issue by slbls** [mantinedev/mantine#284]
Is there currently any support or planned support for manual date entry via typing using `DatePicker`? Right now it seems the option available is selecting a date through the GUI itself, but it would be useful to be able to type a date on its own.

**Comment by rtivital** [comment]
We do not support it now, but it will be done in one of the future 3.x releases

**Comment by rtivital** [comment]
Done, will be released as a part of 3.2 release (December 3rd or earlier)

**Comment by rtivital** [comment]
Released in 3.2
