### ISSUE TITLE
Arrow key navigation in carousel should be disableable

### ISSUE THREAD

**Issue by macjuul** [mantinedev/mantine#2841]
### What package has an issue

@mantine/carousel

### Describe the bug

I'm using the mantine carousel to provide a clean way of sliding between different "pages" in a side drawer. In these carousel pages I use input elements, in which arrow key navigation doesn't work and instead will slide the carousel.

I noticed in the code an event is used to handle this [right here](https://github.com/mantinedev/mantine/blob/master/src/mantine-carousel/src/Carousel.tsx#L217), however there appears to be no way to disable it. Would it be possible to make this functionality disableable?

Thanks!

### What version of @mantine/hooks page do you have in package.json?

5.6.3

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

An additional prop to disable key based navigation, which should still default to true

**Comment by rtivital** [comment]
This feature was introduced in 5.7.0, set `withKeyboardEvents={false}` to disable keyboard events
