### ISSUE TITLE
@mantine/next: NextLink is not compatible with NextJS 13

### ISSUE THREAD

**Issue by openscript** [mantinedev/mantine#2843]
### What package has an issue

@mantine/core

### Describe the bug

> Starting with Next.js 13, <Link> renders as <a>, so attempting to use <a> as a child is invalid.
https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor

Currently `NextLink`injects a `<a>` element which triggers the error:
https://github.com/mantinedev/mantine/blob/9ca897acbf55331dc1eb272c918a89eb9af57e04/src/mantine-next/src/NextLink.tsx#L23-L37

### What version of @mantine/hooks page do you have in package.json?

5.6.3

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

A solution is to remove the `<a>` element and pass the `ref` and the `otherProps` to the `<Link>` itself, but this is a breaking change for projects that haven't migrated to NextJS 13.

How we should deal with this breaking change?

**Comment by rtivital** [comment]
NextLink component will be removed in 6.0, if you use Next.js 13 now, then just do not use NextLink component

**Comment by openscript** [comment]
Thank you for the quick reply @rtivital.

I followed your recommendation and it works. So if you just migrated to Next.js 13 use `Link` from `next/link` instead `NextLink` from `@mantine/next`.

Example:

```
import { NextLink } from '@mantine/next';

<Button component={NextLink} href="/example">
    Your button
</Button>
```

becomes

```
import Link from 'next/link';

<Button component={Link} href="/example">
    Your button
</Button>
```
