### ISSUE TITLE
Context menu not working correctly with RTL

### ISSUE THREAD

**Issue by ShahriarKh** [mantinedev/mantine#2845]
### What package has an issue

@mantine/core

### Describe the bug

I'm using https://github.com/icflorescu/mantine-datatable and the[ context menus](https://icflorescu.github.io/mantine-datatable/examples/row-context-menu) doesn't work correctly with RTL mode. I'm not sure if the bug is from `mantine-datatable` or the `mantine` itself.

Here are two screenshots. The red cross is where I right-clicked to open the menu.
![image](https://user-images.githubusercontent.com/31452340/198876680-28578da0-186f-4171-a436-157983052098.png)
![image](https://user-images.githubusercontent.com/31452340/198876698-21091949-98de-45cc-bd3e-d0e845dd7846.png)

Other things are working correctly. The table data is correctly filled from right to left, and even the menu options are correctly in RTL (notice the position of icons and text-alignment). However, the position for specifying where the menu should open is mirrored.

### What version of @mantine/hooks page do you have in package.json?

5.6.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Mantine does not provide context Menu component.

https://github.com/icflorescu/mantine-datatable package was not built and is not maintained by Mantine team. You can report issues associated with this library in the corresponding repository.
