### ISSUE TITLE
Popover issue

### ISSUE THREAD

**Issue by dexter4life** [mantinedev/mantine#2849]
### What package has an issue

@mantine/core

### Describe the bug

Hello, sorry if this is the wrong place.

I am having something similar as a problem. any idea what I have to do to fix it?

I downloaded the release file from github, build it and then ran the storybook. Strange enough everything was working fine for the popover, but then when I use it in my project, the same issue happened. So is really hard to reproduce this error since is working for the storybook and not working in my project. Any idea what may be the cause?

![image](https://user-images.githubusercontent.com/10168414/198917610-80668a5b-21e3-4c68-8bee-09e950ec53b1.png)

### What version of @mantine/hooks page do you have in package.json?

5.6.3

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Hi @dexter4life, please describe the issue and provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by dexter4life** [comment]
I am trying to reproduce it, I will post my code when I am done.

**Comment by dexter4life** [comment]
I was able to figure out the reason for the problem, somehow when I remove the overflow: auto or hidden, it works well.

**Comment by dexter4life** [comment]
![image](https://user-images.githubusercontent.com/10168414/199096747-906f068d-20cc-4a4f-a3b1-6cb2494adbe7.png)

and here the children is the popover
