### ISSUE TITLE
Hydration error with Next js 13

### ISSUE THREAD

**Issue by vipindigiqt** [mantinedev/mantine#2851]
### What package has an issue

@mantine/core

### Describe the bug

I was running Next 12 and everything was fine, now I tried to move on to 13, and I got this hydration error.

I followed the `framework guide` of next as mentioned on Mantine docs to set up the initial `_app.js` and `_document.js`.

Is there something I'm doing wrong?

![image](https://user-images.githubusercontent.com/81612126/199146942-12851c9b-95b7-4caa-84c3-6111502c7b6d.png)

### What version of @mantine/hooks page do you have in package.json?

5.6.3

**Comment by caykey** [comment]
I am also experiencing this issue. Happening with Anchor component in particular.

**Comment by rtivital** [comment]
It is not clear from your issue what is causing this issue, please isolate the faulty code and send it here.

**Comment by yunger7** [comment]
This is likely due to the new `Link` behavior in Next.js, since it doesn't require a child anchor tag anymore.

If you're using a polymorphic component inside a Next.js `Link`, try refactoring like so:
```tsx
// From
<Link href="/hello" passHref>
  <Button component="a">Hello</Button>
</Link>

// To
<Button component={Link} href="/hello">Hello</Button>
```

or adding the `legacyBehavior` prop to next/link.

**Comment by rtivital** [comment]
Seems like so, @yunger7 thanks for investigation!
