### ISSUE TITLE
Checkbox `label` alignment problem

### ISSUE THREAD

**Issue by mthongkerd** [mantinedev/mantine#2854]
### What package has an issue

@mantine/core

### Describe the bug

When using component (not string) as the input for Checkbox label the component appears on the bottom right of the checkbox. 

### What version of @mantine/hooks page do you have in package.json?

5.6.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-checkbox-label-alignment-problem-jlho96?file=/src/App.js

**Comment by julihereu** [comment]
The same issue appears when using the Switch component label with elements instead of a string. 

https://codesandbox.io/s/switch-label-alignment-xspcyk?file=/src/App.js

**Comment by adarshaacharya** [comment]
@rtivital I've raised pr fixing this issue, please check it !

https://github.com/mantinedev/mantine/pull/2881

**Comment by rtivital** [comment]
Fixed in 5.7.2
