### ISSUE TITLE
Slider `step` unexpected behavior

### ISSUE THREAD

**Issue by mthongkerd** [mantinedev/mantine#2855]
### What package has an issue

@mantine/core

### Describe the bug

When using `Slider` component setting the `min` value to an odd number and setting `step` value to an even number, the step is not behaving correctly (goes to even number). The dragging also seem to be lagging behind.

This is the same when the `max` value is set to an odd number when the `step` value is an even number.

### What version of @mantine/hooks page do you have in package.json?

5.6.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-slider-step-problem-ophjnt?file=/src/App.js

**Comment by wes337** [comment]
I believe this will be fixed by #2839

**Comment by wes337** [comment]
> @wes337 @rtivital Updated to `5.6.4` but the problems are still there.
> 
> See: https://codesandbox.io/s/mantine-slider-step-problem-5-6-4-l0zmlx?file=/src/App.js

Yeah, you’re right. I will take another look into this

**Comment by rtivital** [comment]
Fixed in 5.7.2. First case was fixed, second case should work fine – user should be able to reach the end of the slider independent of the `step` prop
