### ISSUE TITLE
NativeSelect placeholder is ignored in favour of data[0]

### ISSUE THREAD

**Issue by Huskehhh** [mantinedev/mantine#2860]
### What package has an issue

@mantine/core

### Describe the bug

Refer: https://mantine.dev/core/native-select/#usage

Value defaults to the first value in `data` when it should start at `placeholder`

### What version of @mantine/hooks page do you have in package.json?

5.6.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by MariaSolOs** [comment]
@rtivital Could I try tackling this?

**Comment by rtivital** [comment]
Sure

**Comment by MariaSolOs** [comment]
Hmmm actually nvm. After further investigation it seems like native `select` components simply don't accept a placeholder. There are some hacks (described [here](https://stackoverflow.com/questions/5805059/how-do-i-make-a-placeholder-for-a-select-box)) but this might not work in all browsers, and so I wouldn't want to introduce that to this library.

**Comment by rtivital** [comment]
Yep, it was removed recently because there were errors with `defaultValue` and incorrect props on `option` component

**Comment by MariaSolOs** [comment]
@rtivital Maybe the docs should include a disclaimer of the placeholder having no effect?

**Comment by rtivital** [comment]
Yes, it will be removed from the demo soon

**Comment by yairopro** [comment]
![image](https://user-images.githubusercontent.com/8110568/216409089-d301adf6-8880-46d1-a5f4-69e9a3c1644a.png)
