### ISSUE TITLE
Radio attribute checked is not listed in component props docs

### ISSUE THREAD

**Issue by miiik4** [mantinedev/mantine#2863]
### Link to the page where something nasty is located

https://github.com/mantinedev/mantine/blob/master/docs/src/docs/core/Radio.mdx#controlled

### Exact quote of what is wrong

In the docs, it shows how to make Radio controlled, but the checked attribute used is not documented in the component props tab.

![image](https://user-images.githubusercontent.com/31065498/199481789-adb79813-3720-41a6-91bf-72881c6d96ef.png)
![image](https://user-images.githubusercontent.com/31065498/199481660-749ee29b-f440-4ba8-98b4-2b798a98cc59.png)

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Radio component supports all props that are supported by `input` element, they are not listed in the props table because there are more than 300 of them. It is not planned to add these props to documentation.
