### ISSUE TITLE
Custom mime type filters not working properly on windows

### ISSUE THREAD

**Issue by Zheruel** [mantinedev/mantine#2864]
### What package has an issue

@mantine/dropzone

### Describe the bug

This seems to be Windows issue (tested on mac for the same use-case and it doesn't happen)
Did not test this on Linux.

When you add custom mime types to the accept property of the component related to powerpoint files (.ppt, .pptx) they work fine if they are the only mime types given to the component.

However, if you have things in there other than the powerpoint mime types then it starts to not show these files until you select "all files. If you select all files and upload these files they will still work fine (it's just that they don't show until you select all files)

![123](https://user-images.githubusercontent.com/35663757/199498779-856c3d5e-1892-4cbc-bdb4-8f40b795fa53.png)

### What version of @mantine/hooks page do you have in package.json?

5.6.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/naughty-chebyshev-qk59oj?file=/src/Example.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

It's possible that this bug is not with you guys but instead the dropzone third party module you're using.

**Comment by rtivital** [comment]
This is not something we can fix on our side, try searching for similar issues in react-dropzone repository – https://github.com/react-dropzone/react-dropzone
