### ISSUE TITLE
onClickOutside with Select unexpected behavior, also nodes array question

### ISSUE THREAD

**Issue by aviemet** [mantinedev/mantine#2867]
### What package has an issue

@mantine/hooks

### Describe the bug

When using `onClickOutside` to show and hide a `Select` dropdown, clicking inside the dropdown triggers the clickoutside handler. I've seen some other issues this may be related to, but couldn't suss out a solution from them.

I'm also a touch confused by the optional last argument to the hook. From what I can gather, it wants the state value from a `useState` hook for which the state setter method has been passed as a ref to a node. This didn't work for my use case, but also resulted in typescript errors. TS doesn't like me passing the state setter method to a ref, and also doesn't like me passing the state value in an array to the `onClickOutside` call.

Code link included below

Thank you

### What version of @mantine/hooks page do you have in package.json?

^5.5.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/blissful-frost-1b6ghf?file=/src/Attempt2.tsx

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
