### ISSUE TITLE
Event is of type `any` in `onChange` property of `InputBase` 

### ISSUE THREAD

**Issue by MariaSolOs** [mantinedev/mantine#2868]
### What package has an issue

@mantine/core

### Describe the bug

The `onChange` property of the `Input` and `InputBase` component seems to be incorrectly typed, since the following happens:
```
import { InputBase, TextInput } from "@mantine/core";

export default function MyComponent() {
  return (
    <div>
      {/* Event is of type 'any' */}
      <InputBase onChange={(event) => console.log(event)} />
      {/* Event is of the expected type */}
      <TextInput onChange={(event) => console.log(event)} />
    </div>
  );
}
```

### What version of @mantine/hooks page do you have in package.json?

^5.6.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/modern-resonance-ksqkx4?file=/src/MyComponent.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

This is more of a workaround than an actual fix, but the following module augmentation fixes the issue:
```
// mantine.d.ts
import type { InputBaseProps as MantineInputBaseProps } from '@mantine/core';
import type { ChangeEventHandler } from 'react';

interface InputBaseProps extends MantineInputBaseProps {
  onChange?: ChangeEventHandler<HTMLInputElement> | undefined;
}
```

**Comment by rtivital** [comment]
InputBase is a polymorphic component, it cannot usually pick up correct types information if you do not provide generic type – https://codesandbox.io/s/loving-thunder-1py1v1?file=/src/MyComponent.tsx

**Comment by MariaSolOs** [comment]
Ohhh got it, thanks @rtivital!
However, shouldn't the type definition ensure that the non-generic type always is set to `InputBase<'input'>`?

```
export declare const InputBase: (<C = "input">(props: import("@mantine/utils").PolymorphicComponentProps<C, InputBaseProps>) => React.ReactElement<any, string | React.JSXElementConstructor<any>>) & Omit<React.FunctionComponent<(InputBaseProps & {
    component?: any;
} & Omit<Pick<any, string | number | symbol>, "component" | keyof InputBaseProps> & {
    ref?: any;
}) | (InputBaseProps & {
    component: React.ElementType<any>;
})>, never> & Record<string, never>;
```

**Comment by rtivital** [comment]
It is made in this part `<C = "input">`, if it is done any other way ts performance will degrade

**Comment by MariaSolOs** [comment]
> It is made in this part `<C = "input">`, if it is done any other way ts performance will degrade

@rtivital, correct, so where I'm getting at is that shouldn't this make setting `InputBase<'input'>` redundant since the default value of the generic argument is already `'input'`?

**Comment by rtivital** [comment]
That is one of the mysteries of TypeScript, I have no idea why it is required in some cases

**Comment by MariaSolOs** [comment]
> That is one of the mysteries of TypeScript, I have no idea why it is required in some cases

Fair enough lol. Closing this as typing the generic argument fixes the issue :)
Thanks @rtivital!
