### ISSUE TITLE
Slider `inverted` styles incorrect with `marks` enabled on track

### ISSUE THREAD

**Issue by EmBeaux** [mantinedev/mantine#2877]
### What package has an issue

@mantine/core

### Describe the bug

When utilizing the Slider `inverted` prop and the `marks` prop on the same track it results in the marks styles becoming confused and thinking they are under the `default` track when in reality they are not because the track is inverted.

This may be an over site on styles where the `marks` simply aren't aware of what `inverted` is. I climbed through the PR that introduced the `inverted` prop and it looks like it wasn't added from the get go.

![Screen Shot 2022-11-03 at 3 00 23 PM](https://user-images.githubusercontent.com/43078490/199811424-d3610eca-e73f-4e51-a806-79e27b1e8937.png)

### What version of @mantine/hooks page do you have in package.json?

5.6.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/infallible-tess-7j5t34?file=/src/App.js

**Comment by rtivital** [comment]
Thanks for reporting!

**Comment by bobwade** [comment]
PR ready and passing checks, let me know if it needs any changes 🙂

**Comment by rtivital** [comment]
Fixed in 5.7.2
