### ISSUE TITLE
Checkbox input and label different behavior on click handling 

### ISSUE THREAD

**Issue by ascentiskelvin** [mantinedev/mantine#2878]
### What package has an issue

@mantine/core

### Describe the bug

The `Checkbox` ([link](https://mantine.dev/core/checkbox/)) component has different onClick behavior when clicking on the input and the label within the checkbox. I have a `Checkbox` in the `Accordion.Control` in my project to handle the select all checkboxes inside the accordion, however there is 2 different behavior when clicking on the input and the label.

Default implementation without override onClick event, clicking on the input will trigger the accordion expand/collapse, but it won't trigger when clicking on the label.
![default behavior](https://user-images.githubusercontent.com/106225279/199888937-9112bf65-c478-4797-acd3-6ade4f307b9d.gif)

In the second implementation with the override of the onClick event, input and label behavior have changed and have opposite behavior. Clicking on the label will trigger the accordion to expand/collapse, but clicking on the input won't trigger it.
`onClick={(event)=>{ event.stopPropagation(); }}`
![second implementation behavior](https://user-images.githubusercontent.com/106225279/199889729-dfe4a023-1362-4ab6-a41f-8b414b852a7f.gif)

Is there any way to make the two HTML element input and label behave the same?

### What version of @mantine/hooks page do you have in package.json?

^5.5.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/vigilant-water-tuqg9h

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Checkbox component renders `input[type="checkbox"]` and associated label element, you are trying to use it as a button. Use `onChange` handler instead: `<Checkbox onChange={yourFunction} />`. 

If you really want to use `onClick`, then just wrap the checkbox with `span`:

```tsx
<span onClick={yourHandler}>
  <Checkbox />
</span>
```

**Comment by ascentiskelvin** [comment]
Thanks, @rtivital. Wrapping the checkbox with `span` did help to make the two behaviors consistent.
