### ISSUE TITLE
"right" style prop is missing

### ISSUE THREAD

**Issue by viczam** [mantinedev/mantine#2886]
### What package has an issue

@mantine/core

### Describe the bug

Since `5.7.0` we have `top`, `left`, `bottom`, but `right` is missing :) 

### What version of @mantine/hooks page do you have in package.json?

5.7.0

**Comment by rtivital** [comment]
Thanks for reporting!

**Comment by adarshaacharya** [comment]
@rtivital I've raised pr fixing this issue, please check it out
https://github.com/mantinedev/mantine/pull/2887
