### ISSUE TITLE
tailwind ordered list and unorderd list not showing correctly

### ISSUE THREAD

**Issue by vincent0426** [mantinedev/mantine#2904]
### What package has an issue

@mantine/rte

### Describe the bug

Update:
I found that it's because I use tailwind css which hide the list icon by default but how can I let the rich editor show the icon? Thanks!

Hi,

I've followed the steps to import rich text to my application. However, everything goes well instead of the icon of ordered list and unordered list. They do move right a little after pressing them but there is no icon showing. 

Due to the above issue, I tried to import {List} and try to test the List.Item. Unfortunately, the icons didn't appear, neither.

Thank you.
![Screenshot 2022-11-07 at 9 27 13 PM](https://user-images.githubusercontent.com/68840528/200322090-32422d0b-e412-450d-b8bb-4f0e5d678412.png)

### What version of @mantine/hooks page do you have in package.json?

"@mantine/core": "^5.7.1", "@mantine/hooks": "^5.7.1", "@mantine/rte": "^5.7.1",

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Hi @vincent0426, you've installed a third-party library to your project that overrides Mantine styles. To fix that issue, either remove those styles or change emotion cache options to make Mantine styles override third-party library styles – https://mantine.dev/theming/emotion-cache/

**Comment by vincent0426** [comment]
Yeah, thanks!!!

BTW,
For those who encounters the same problem, you can add
```
@layer base {
    ul,
    ol {
        list-style: revert;
    }
}
```
under your
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
to revert the list style.
