### ISSUE TITLE
Checkbox vertical alignment bug

### ISSUE THREAD

**Issue by codyebberson** [mantinedev/mantine#2905]
### What package has an issue

@mantine/core

### Describe the bug

Hi, thanks for an amazing library.

I believe there may be a regression in the `<Checkbox>` component regarding vertical alignment.  It appears correct in version 5.4.0 and incorrect in 5.7.1.

My example is based on "Authentication form with title":  https://ui.mantine.dev/component/authentication-title

![image](https://user-images.githubusercontent.com/749094/200379230-0c912e3d-d142-440f-bda9-4931f03be98f.png)

(It appears that ui.mantine.dev currently uses 5.4.0: https://github.com/mantinedev/ui.mantine.dev/blob/master/package.json)

Using version 5.4.0, the text is ***correctly*** vertically aligned:

https://codesandbox.io/s/mantine-checkbox-5-4-0-2v1fvq

<img width="531" alt="image" src="https://user-images.githubusercontent.com/749094/200376490-f34deb9a-1364-4616-a9bb-997ad55a7804.png">

Using version 5.7.1, the text is ***incorrectly*** vertically offset:

https://codesandbox.io/s/mantine-checkbox-5-7-1-bnbx9j

<img width="533" alt="image" src="https://user-images.githubusercontent.com/749094/200376739-c2acfa42-963e-4d21-8f74-d57122b8978c.png">

I believe it may be related to the introduction of `mantine-Checkbox-body`.

In version 5.4.0, the DOM has `mantine-Checkbox`, `mantine-Checkbox-inner`, and `mantine-Checkbox-label`:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/749094/200377064-ee074c23-33ea-48ce-af3f-d23ba00e507b.png">

In version 5.7.1, the DOM also includes `mantine-Checkbox-body`, which introduces extra vertical spacing:

<img width="529" alt="image" src="https://user-images.githubusercontent.com/749094/200377187-d42f4da4-0f6d-4ac4-940e-68ecd2963cf2.png">

### What version of @mantine/hooks page do you have in package.json?

5.7.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-checkbox-5-7-1-bnbx9j

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by daddasoft** [comment]
After Review your code there is a  line-height specefied in body element try re-define it on checkbox 
```jsx 
<Checkbox sx={{lineHeight:1}} label="Remember me" />
```

**Comment by daddasoft** [comment]
sine you using mantine 5.7.1 you can also use Flex Component

```jsx

 <Flex align="center" justify="space-between">
       <Checkbox sx={{ lineHeight: 1 }} label="Remember me" />
       <Anchor onClick={(event) => event.preventDefault()} href="#" size="sm">
            Forgot password?
       </Anchor>
 </Flex>

```

**Comment by codyebberson** [comment]
@daddasoft Thanks for looking!

Adding `<Checkbox sx={{ lineHeight: 1 }}` is an improvement, but there is still an extra 1.33 pixels of vertical space (versus 6.13 pixels before).

**Comment by minosss** [comment]
because `Checkbox` move flexbox to body children. body's height is 20px, but checkbox's height is 26.4px  :<

1. set checkbox root or body to flex `<Checkbox styles={{body: {display: 'flex'}}} label="Remember me" />`
2. set parent element font-size to 0 `<Checkbox sx={{fontSize:0}} label="Remember me" />`

**Comment by daddasoft** [comment]
yes actually since in version 5.4 there was no body on checkbox but now is it making body flex fix this issues it's should be fix by a pull request .
but you can  fix it without specify fontsize  just ``` display : flex ``` on checkbox body

**Comment by rtivital** [comment]
I've tested it on the ui.mantine.dev website with 5.7.2 – https://ui.mantine.dev/component/authentication-title
Alignment works correctly when `sx={{ lineHeight: 1 }}` is set. Unfortunately, setting line-height is now required in this case to support new Checkbox features (description and error). Same logic is applied for Radio and Switch components.

Alignment with ruler:
<img width="358" alt="Снимок экрана 2022-11-12 в 16 41 22" src="https://user-images.githubusercontent.com/10353856/201474396-ceddbe36-5eee-400e-acb1-e8f36d4c389e.png">

**Comment by daddasoft** [comment]
great to fix that thank you ✌️✌️✌️
