### ISSUE TITLE
warn  - `enableUndici` option is unnecessary in Node.js v18.0.0 or greater.

### ISSUE THREAD

**Issue by jesse996** [mantinedev/mantine#2906]
### What package has an issue

@mantine/core

### Describe the bug

nextjs 13,node 19, come with this wran:
```
warn  - `enableUndici` option is unnecessary in Node.js v18.0.0 or greater.
```

### What version of @mantine/hooks page do you have in package.json?

5.7.1

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Hi @jesse996, have you been able to isolate the issue to verify that it is an issue with Mantine components?

**Comment by ngrhadi** [comment]
using `Node v.16.17.1` it's solved for me

**Comment by jesse996** [comment]
> 



> Hi @jesse996, have you been able to isolate the issue to verify that it is an issue with Mantine components?

yes,it only appears when i use mantine,so i am sure it's cursed by mantine

**Comment by jesse996** [comment]
> It's a nextjs issue and occurs only when u enable app dir in node 18+ it was fixed in canary too

appreciate
