### ISSUE TITLE
MantineProvider theme context breaking for compiled in version > 5.6.2

### ISSUE THREAD

**Issue by drenther** [mantinedev/mantine#2909]
### What package has an issue

@mantine/core

### Describe the bug

I use Mantine to maintain an internal component library and multiple application dependent on it.

Up until v5.6.2 components were working fine in the component library (bundled using vite) when they were accessing custom theme colors because the theme was passed correctly from the `MantineProvider` used in the app that was consuming this library.

But something broke this in v5.6.3 changes.

Now, custom a theme object passed in the `MantineProvider` is not being picked up by the bundled components. When I drop the dependency to 5.6.2, it works again.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Looking at the theming or styling related commits made post 5.6.2 release

**Comment by zhulien-ivanov** [comment]
First, I guess you talk about `5.4.2` when you say `6.4.2` as there is no version 6 at all. Also, there is no version `5.4.3`. Your question is so confusing with all the inaccuracies so please update it with proper versions. Also, provide the theme object you're passing to `MantineProvider`. You haven't given any debug details and your issue is highly custom to your case.

**Comment by rtivital** [comment]
@drenther please provide more details and a reproduction

**Comment by drenther** [comment]
Sorry for the massive amount of typos around version numbers. Not sure what I was thinking when I wrote this.

Have corrected them.

@rtivital Will add soon.

**Comment by rtivital** [comment]
Try this:
- reset vite cache that you have in the browser – open console, press `Ctrl + Shift + R`
- Reinstall dependencies (remove node_modules directory and install them with your package manager) 
- Update all `@mantine/` packages to the latest version – 5.7.1 (All packages should be the same version)

**Comment by drenther** [comment]
Thanks for the patience!

Apologies. False alarm. The issue was stemming from a turborepo cache.
