### ISSUE TITLE
Rating is showing the "filled" stars as outlines instead of filled

### ISSUE THREAD

**Issue by 684efs3** [mantinedev/mantine#2911]
### What package has an issue

@mantine/core

### Describe the bug

When I use the Rating component, the stars show up as outlined with white inside, instead of filled inside. 

### What version of @mantine/hooks page do you have in package.json?

5.7.1

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Is there a way to have a prop that tells the svg to be filled?

**Comment by 684efs3** [comment]
![image](https://user-images.githubusercontent.com/48864759/200653031-1793ff6b-340a-41a6-9db5-3373704de70e.png)

**Comment by rtivital** [comment]
This is how the component looks for me, maybe there is an issue with a specific browser?
<img width="121" alt="Снимок экрана 2022-11-08 в 23 17 07" src="https://user-images.githubusercontent.com/10353856/200655273-a3ffeb85-6400-48b6-b13c-82ae29a17ba1.png">

**Comment by 684efs3** [comment]
I am using Brave. I am using Mantine.dev with WindiCSS (a fork of TailwindCSS) on NextJS. I'm not sure why this is happening. The other props all work - changing the color, size, making it read-only.

**Comment by rtivital** [comment]
Try disabling third-party styles and see whether that will fix the issue

**Comment by rtivital** [comment]
I cannot reproduce the issue in Safari, Chrome and Firefox, if you can provide a sandbox that reproduces the issue, feel free to reopen it
