### ISSUE TITLE
SegmentedControl Doesn't Change Checked Value

### ISSUE THREAD

**Issue by cwbuecheler** [mantinedev/mantine#2917]
### What package has an issue

@mantine/core

### Describe the bug

Minor issue, but it seems that while `SegmentedControl` uses hidden checkboxes (I assume for accessibility reasons but it might be something else), the `checked` value never actually changes as you click around the control. It's always the first checkbox that remains checked. I noticed this while doing some basic unit testing. I also checked using the DOM inspector in the [official Mantine docs](https://mantine.dev/core/segmented-control/), and it doesn't change there either.

### What version of @mantine/hooks page do you have in package.json?

5.1.6

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

It looks like based on this code:
```javascript
      <input
        className={classes.input}
        disabled={disabled || item.disabled}
        type="radio"
        name={uuid}
        value={item.value}
        id={`${uuid}-${item.value}`}
        checked={_value === item.value}
        onChange={() => handleValueChange(item.value)}
      />
```

The `checked` value should change, but it doesn't. I haven't had a lot of time to go through the rest of the code but I assume something here:

```javascript
  const [_value, handleValueChange] = useUncontrolled({
    value,
    defaultValue,
    finalValue: Array.isArray(data)
      ? data.find((item) => !item.disabled)?.value ?? data[0]?.value ?? null
      : null,
    onChange,
  });
```

Isn't working as expected.

**Comment by minosss** [comment]
if you mean `checked` attribute not update in dom, that is react problem, use `defaultChecked` instead. it should be works

```jsx
<input
  ...
  defaultChecked={_value === item.value}
  ...
/>
```

**Comment by cwbuecheler** [comment]
I indicated I'm unable to help on this one but that might not be true. Depends on my schedule. I'll take a look today and if it's as straightforward as @minosss mentions, and see if I can get a working PR in.

**Comment by cwbuecheler** [comment]
Switching `checked` to `defaultChecked` works to resolve my issue but introduces a new issue that's caught in testing - it's causing the "Controlled Input" tests to fail. You can't have both `checked` and `defaultChecked` on the input or `defaultChecked` gets ignore.

Further research indicates that React not updating the DOM is intentional on the part of the React team (see [this thread](https://github.com/facebook/react/issues/24439)). So I think this is less of a Mantine issue or even a React issue, and potentially more of a Testing Library issue - their `isChecked` method should probably check the DOM object's properties and not the attributes, though it's certainly possible that they have a good reason for not doing that, either.

With all that in mind, I'm going to close this issue, unless anyone thinks there's a valid reason to keep it open.
