### ISSUE TITLE
Modal closes on dragging from the content, and release drag outside the content

### ISSUE THREAD

**Issue by Sajarin-M** [mantinedev/mantine#2920]
### What package has an issue

@mantine/core

### Describe the bug

- Modal is closing when you start dragging from the content, and release drag outside the content.start dragging from the content, and release drag outside the content
- We should prevent this because it is not technically considered as a "click outside"

### What version of @mantine/hooks page do you have in package.json?

5.7.1

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

- add this onMouseDown event in overlay element and save the target
`onMouseDown={(event) => {
                  mouseDownRef.current = event.target;
                }}`
- check if both target are same in onClick
`onClick={(event) =>
                  mouseDownRef.current === event.target && closeOnClickOutside && onClose()
                }`

**Comment by conor-kelleher** [comment]
Also running into this issue. Interesting that the Modal component doesn't make use of their own `useClickOutside` which supports an array of event types which would be handy here

**Comment by rtivital** [comment]
Fixed in 5.7.2
