### ISSUE TITLE
transition's don't work on tooltip

### ISSUE THREAD

**Issue by Geczy** [mantinedev/mantine#2924]
### What package has an issue

@mantine/core

### Describe the bug

transition's don't work on tooltip https://mantine.dev/core/tooltip/

FADE
SCALE
SCALE-Y
SCALE-X
SKEW-UP
SKEW-DOWN
ROTATE-LEFT
ROTATE-RIGHT
SLIDE-DOWN
SLIDE-UP
SLIDE-LEFT
SLIDE-RIGHT
POP
POP-BOTTOM-LEFT
POP-BOTTOM-RIGHT
POP-TOP-LEFT
POP-TOP-RIGHT

### What version of @mantine/hooks page do you have in package.json?

latest, dont work on your site either

**Comment by rtivital** [comment]
None of the transitions will work if you prefer to reduce motion – https://mantine.dev/theming/theme-object/#respectreducemotion

**Comment by Geczy** [comment]
wow that's neat thx
