### ISSUE TITLE
Radio doesn't support `checked` prop

### ISSUE THREAD

**Issue by defrex** [mantinedev/mantine#2926]
### What package has an issue

@mantine/core

### Describe the bug

Hello. Been loving Mantine. Appreciate the well designed library!

In the controlled, non-group, Radio component example, the docs say I can use a `checked` boolean prop to set the state. However in practice, the types only allow setting a `value: string` prop.

https://mantine.dev/core/radio/#controlled

<img width="662" alt="Screen Shot 2022-11-09 at 4 20 24 PM" src="https://user-images.githubusercontent.com/57580/200944141-aaab0e53-dd70-4f99-a26f-304bda24d3e1.png">

I'd love to use it controlled without the group, as described in the docs.

### What version of @mantine/hooks page do you have in package.json?

5.5.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Value is required for every Radio element. It is not related to checked prop in any way.

**Comment by defrex** [comment]
I see you made the change, thanks! My intent is to use it in a controlled mode, analogously to how a controlled `Checkbox` might work. In that case, the `value` of the Radio isn't relevant.

**Comment by rtivital** [comment]
Fixed in 5.8.2
