### ISSUE TITLE
Modal does not render when rendered in a nested route in combination with lazy loading

### ISSUE THREAD

**Issue by jansedlon** [mantinedev/mantine#2932]
### What package has an issue

@mantine/core

### Describe the bug

We treat some modals as standalone routes to keep user's experience nice. That means when a user opens complex modal with tabs, etc, we treat as routes. However I noticed that in some cases where we deal with nested routes and lazy loading, the modal does not open. The route itself is rendered but the modal is not injected to body through Portal. When you add `withinPortal={false}` it should work.

### What version of @mantine/hooks page do you have in package.json?

5.7.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/funny-james-6124oq

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
See console message in your sandbox, it tells that you do not have matching route.
If you change the link, the modal will be opened – https://codesandbox.io/s/nervous-goldberg-scy5kj?file=/src/route-page.js

**Comment by jansedlon** [comment]
Oh god 🤦‍♂️ Yeah, my bad with the repro but that's not the case with my bad unfortunately. I've got the correct route, i get consoles logs from the route, just the modal does not render. When I change something in my editor and save it, on the next render, the modal shows up. I'll keep trying to make the repro

**Comment by rtivital** [comment]
I cannot help unless you reproduce the issue on the codesandbox

**Comment by rtivital** [comment]
@jansedlon, the issue seems to be in your application, not with the library itself. If you can reproduce it in the codesandbox, feel free to reopen it
