### ISSUE TITLE
Size of @mantine/core/Select is very big compared to other elements

### ISSUE THREAD

**Issue by Lucasvo1** [mantinedev/mantine#2933]
### What package has an issue

@mantine/core

### Describe the bug

First of all, thanks for this great library. I have been using it the last couple of days to make an internal dashboard application and I've been able to do it very efficiently because of Mantine. For the bug, I noticed that the bundled size of the Select component is huge when you compare to other components. See below for a comparison. Is there anything I can do to make it smaller? Better to use NativeSelect?

![With Select](https://user-images.githubusercontent.com/109728866/201084388-d575766c-4069-4c3a-939e-1358f9cc1386.png)

![Without Select](https://user-images.githubusercontent.com/109728866/201084493-93959521-ef6e-4eee-8a4e-38dd71334c75.png)

![With NativeSelect](https://user-images.githubusercontent.com/109728866/201085463-56535b55-afdd-4db2-979e-9dad36a9404a.png)

### What version of @mantine/hooks page do you have in package.json?

5.7.1

**Comment by rtivital** [comment]
Select is a very complex component, it uses several other components under the hood – ScrollArea, Popover, Input, etc. It is expected for it to have significant impact on the bundle size compared to other components.

**Comment by Lucasvo1** [comment]
Thanks
