### ISSUE TITLE
Bug: `root`, `error`, `description` styles in `Input` seems broken

### ISSUE THREAD

**Issue by activenode** [mantinedev/mantine#2934]
### What package has an issue

@mantine/core

### Describe the bug

Using a styles function to style `root` depending on params seems broken. 

Facts:
- It works for  other properties e.g. `wrapper`, `input` etc but `root`, `error` and `description` we found not to be working (see sandbox)
- Looking through the Mantine Source code we found that the following are exported in `Input.styles.ts`: 
  ```ts
   return {wrapper, input, withIcon, invalid, disabled, icon, rightSection}
   ```
-> Comparing this to other components such as e.g. `Button` it feels like it can only be restyled what's exported (unsure though) - and most of them do export `root: { someStylesWhatever }`. The `Input.tsx` itself (start checking from line `Input.tsx#130@Mantine-5.7.1`) only uses theses classes in the input / wrapper:

```
<Box
      className={cx(classes.wrapper, className)}
...

{icon && <div className={classes.icon}>{icon}</div>}

...

className={cx(classes[`${variant}Variant`], classes.input, {
          [classes.withIcon]: icon,
          [classes.invalid]: invalid,
          [classes.disabled]: disabled,
        })}

{rightSection && (
        <div {...rightSectionProps} className={classes.rightSection}>
          {rightSection}
        </div>
      )}
```

### What version of @mantine/hooks page do you have in package.json?

5.7.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/youthful-sanderson-o7uikg?from-embed=&file=/src/App.tsx:0-707

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I'd have to dig a bit deeper but it seems like one fix could be exporting a `root` property object inside the returned `Input.styles` object.

The problem probably lies in `create-styles.ts#75` where only the `cssObject` (containing the returned values/keys) is traversed:

```
Object.keys(cssObject).map((key) => { ... // no root, description, error...
```

**Comment by rtivital** [comment]
TextInput component does not support styles params, that is why `TextInputStylesParams` type is not exported from the package. Different components receive different styles params, for example in your case, TextInput consists of `Input.Wrapper` and `Input` components:
- `Input` component receives `InputStylesParams`
- `Input.Wrapper` does not have any style params and thus the object is empty

You can apply styles to `Input` and `Input.Wrapper` components on MantineProvider like described in documentation – https://mantine.dev/styles/styles-api/#inputs-styles-api-on-mantineprovider
But you cannot get `Input` variant in `Input.Wrapper` – this feature is supported and is not planned to be added to the library.

**Comment by activenode** [comment]
Okay understood but this page then is understandably misleading, don't you think? https://mantine.dev/core/text-input/?t=styles-api 

As per page/docs one can safely assume this is possible.

**Comment by activenode** [comment]
But think of someone checking that documentation in combination with reading the docs about `Styles API`. It would directly lead to the understanding that you can use what's described as bug above.

Or in other words: Leading to more bug reports like this because of false assumptions. Wouldn't it rather make sense to remove the `Styles API` Tab there and refer with a link to the original `Input` where it becomes clear?

**Comment by rtivital** [comment]
TextInput supports styles api of Input and Input.Wrapper component, it also has its own static selectors, documentation does not show usage with styles params.

**Comment by activenode** [comment]
I'm still confused how to read that. It says `TextInput component Styles API` on that exact link https://mantine.dev/core/text-input/?t=styles-api which contains a `root` prop as well. But using that has not really an effect in combination with that herementioned Styles API. 

I don't see how this can be understood considering that exact information on the provided link. I'd assume all users checking that exact documentation would assume that they could make use of `root` .

**Comment by rtivital** [comment]
Styles API table describes which selectors can be used in `styles` and `classNames` props. You can use `root` and other selectors to apply styles via:
- component props – https://codesandbox.io/s/awesome-saha-yre1zd?file=/src/App.tsx:0-701
- or MantineProvider – https://codesandbox.io/s/ecstatic-kalam-mrz4kg?file=/src/App.tsx

**Comment by activenode** [comment]
I understand what you are saying but my point is: Where does it become clear to the user on the `TextInput` documentation that you can use `styles={{root: CSSProps}}` but not `styles={ (theme, params) => if (params...` .

This is what I am trying to understand how one should derive that information without being a Mantine Maintainer.

**Comment by rtivital** [comment]
Currently, styles params are not documented well as for now it is mostly an internal feature. There are some changes planned to be added to the variants and sizes in the next major release, I'll add more documentation and I hope that you will not need styles params at all.

**Comment by activenode** [comment]
Okay is there a public branch to follow up to and get some insights? I would love to state the reason why we are using it:

We allow in the App to choose different themes. Some Styles are actually dependent on the params. If it was one theme only you could "hardcode" it in the Component. But with multiple themes you cannot really hardcode it as it would become unmaintainable.

So imagine this sample: The Input must behave differently in one specific `variant` with one specific theme e.g. because it's a completely customized one that also takes the params e.g. text length into account (similiar to whats shown in samples in `ui.mantine.dev` where Inputs are customized but in our case integrating params as well).

That's why we think the `styles` as `function` is an awesome concept if you wanna style things based on `params` but globally in the `ThemeProvider` .

**Comment by rtivital** [comment]
6.0 development was not started yet, so no branch right now. I cannot provide any additional details either – I haven't finalized the API for variants and sizes yet. But I can tell now that it will not be possible to implement variant styles for TextInput component even with the new API – you will be able to apply variants only to Input component.
