### ISSUE TITLE
Mantine Autocomplete Component

### ISSUE THREAD

**Issue by bwhitney2439** [mantinedev/mantine#2936]
### What package has an issue

@mantine/core

### Describe the bug

When passing options to the data prop for the Autocomplete component if one of those options is null then the application errors with the following.  TypeError: Cannot read properties of null (reading 'value').  Obviously filtering out null's before hand prevents this error.  Should the Autocomplete component defend against this?

### What version of @mantine/hooks page do you have in package.json?

5.6.4

**Comment by rtivital** [comment]
No, we do not transform data on our side as in certain cases it can lead to incorrect behavior, for example when you provide custom item component or filter function
