### ISSUE TITLE
[@mantine/form] setFieldValue doesn't trickle down on nested fields

### ISSUE THREAD

**Issue by gdostie** [mantinedev/mantine#2937]
### What package has an issue

@mantine/form

### Describe the bug

When a form has nested fields, calling `setFieldValue` on the nested fields parent does not clear the dirty state or the error state of its nested fields. This is problematic because you can end-up in confusing states like a form for which `form.values === initialValues` but `form.isDirty()` returns `true`.

See attached sandbox for a live example of the problem.

### What version of @mantine/hooks page do you have in package.json?

5.7.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/peaceful-browser-3kgjf4?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by minosss** [comment]
why not use list handlers? https://mantine.dev/form/nested/#list-handlers

**Comment by gdostie** [comment]
> why not use list handlers? https://mantine.dev/form/nested/#list-handlers

List handlers would indeed work in that case, but my issue is more that `setFieldValue` can lead to bugs, not so much about how to implement this behaviour so that it works properly.

**Comment by auronsan1st** [comment]
@gdostie 
I try review it seems it's the problem between switch using `users` and `users.2` 
and implementation step 4 is mistake should be `setFieldValue("users.2","josh")` and when do step 1 only + step 4 the dirty will gone.

step 3 bug occur caused error path is `users.2` but setFieldValue to `users` as will little hard to remove error on users.2 if setField the parent. caused we will need do recursively and will make longer computing.

@rtivital I confused should I try make fixes by checked children error when parent value changed by setFieldValue?

**Comment by rtivital** [comment]
@auronsan1st There is already some logic that clears errors for lists, maybe it can be applied for this case? https://github.com/mantinedev/mantine/blob/dev/src/mantine-form/src/clear-list-state/clear-list-state.ts

**Comment by auronsan1st** [comment]
yeah error solved by added it it on inside _setValues(). @rtivital

**Comment by gdostie** [comment]
If its too hard / bug prone to get it working properly, here are a few ideas that could help mitigate this bug IMHO:
1. Adding a notice on the documentation site to acknowledge this limitation by saying setFieldValue shouldn't be used for setting the value of parent fields _(IMPORTANT)_
2. Returning callbacks for `reorderListItem`, `removeListItem`, and `insertListItem` instead of `onChange` when calling `getInputProps` on a path that is of type `Array` _(NICE TO HAVE)_

**Comment by gdostie** [comment]
When trying out idea #2 on my side, I noticed https://github.com/mantinedev/mantine/issues/3001

**Comment by rtivital** [comment]
Fixed in 5.9.1
