### ISSUE TITLE
HoverCard in ScrollArea -> zIndex issue 

### ISSUE THREAD

**Issue by Retr0327** [mantinedev/mantine#2944]
### What package has an issue

@mantine/core

### Describe the bug

There is a zIndex problem when a HoverCard is displayed in ScrollArea:

<img width="774" alt="Screen Shot 2022-11-12 at 7 48 20 PM" src="https://user-images.githubusercontent.com/48786838/201472591-83f4df76-796d-4c67-a672-c6584740f9f7.png">

Only half of the HoverCard content will be presented. I've tried to set the zIndex to 100, but it still doesn't work.

### What version of @mantine/hooks page do you have in package.json?

5.7.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hover-scrollarea-x1degl

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Set `withinPortal` – https://codesandbox.io/s/hover-scrollarea-forked-s69ztj?file=/src/App.tsx
