### ISSUE TITLE
Next 13 with turbo support

### ISSUE THREAD

**Issue by zumbidoweb** [mantinedev/mantine#2945]
### What package has an issue

@mantine/core

### Describe the bug

next dev --turbo

 Error during SSR Rendering
 TypeError: The "superCtor.prototype" property must be of type object. Received undefined

### What version of @mantine/hooks page do you have in package.json?

5.7.2

**Comment by rtivital** [comment]
We do not provide support for experimental features. Turbo is in alpha – there is no point to support it now as its api will change. Anyway, from our side we provide cjs/esm files that work well with all other bundlers (we do not have any special syntax in files and do not even require any additional transforms) – if it does not work with Turbo, then it is an issue with Turbo, not Mantine.

**Comment by zumbidoweb** [comment]
I complete undertand. Really  the issue is more related with runing emotions with turbo.
Thanks for the feeback and congratulations for making this amazing complete library MIT. Well done.

**Comment by rtivital** [comment]
I doubt that this is an issue with emotion either, Mantine does not use `css` emotion prop – we do not require any additional transforms, the code shipped with mantine + emotion in regular cjs/ems modules.

**Comment by anthonyshew** [comment]
Vercel person here! @zumbidoweb, I can confirm for you that this sounds a lot like the kind of thing that the Turbo team hasn't covered yet. I wouldn't expect anything to be wrong with Emotion or Mantine!

**Comment by ryantando** [comment]
@zumbidoweb have you found a solution for this?
