### ISSUE TITLE
Next.JS error - TypeError: Cannot read properties of null (reading 'useReducer')

### ISSUE THREAD

**Issue by taxibickle** [mantinedev/mantine#2946]
### What package has an issue

@mantine/modals

### Describe the bug

error - TypeError: Cannot read properties of null (reading 'useReducer')
    at Object.useReducer (/home/user/Documents/code/node_modules/react/cjs/react.development.js:1626:21)
    at ModalsProvider (/home/user/Documents/code/node_modules/@mantine/modals/cjs/ModalsProvider.js:94:35)

When i remove the <ModalsProvider>, the error goes away

my _app.js:
`return (
    <SessionProvider session={session}>
      <MantineProvider theme={{ fontFamily: 'Roboto, sans-serif', colorScheme: 'dark' }}>
        <ModalsProvider>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </ModalsProvider>
      </MantineProvider>
    </SessionProvider>
  )
}`

` "dependencies": {
    "@mantine/core": "^5.6.2",
    "@mantine/form": "^5.7.1",
    "@mantine/hooks": "^5.7.2",
    "@mantine/prism": "^5.7.1",
    "@tabler/icons": "^1.108.0",
    "next": "12.3.1",
    "next-auth": "^4.15.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "swr": "^1.3.0"
  },`

### What version of @mantine/hooks page do you have in package.json?

^5.7.2

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Try updating all mantine packages to the latest version, reinstalling dependencies, cleaning next.js cache and restarting dev server. It seems like it cannot load react in your application.

**Comment by taxibickle** [comment]
Worked, Thanks! A very frustrating bug.
