### ISSUE TITLE
`Button` does not render `svg` react component

### ISSUE THREAD

**Issue by scarf005** [mantinedev/mantine#2954]
### What package has an issue

@mantine/core

### Describe the bug

![image](https://user-images.githubusercontent.com/54838975/201616318-3164ac2a-7e92-4fab-b436-c5547034eb05.png)

`Button`'s `leftIcon` property cannot render svg react component.

### What version of @mantine/hooks page do you have in package.json?

^5.7.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/youthful-pine-u4mgdn?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Because your icon does not have size, it is rendered but not visible – https://codesandbox.io/s/muddy-sky-0kqx12?file=/src/GoogleIcon.tsx

**Comment by scarf005** [comment]
oh, that was the case, thank you.
