### ISSUE TITLE
Number input doesn't respect "readOnly" prop

### ISSUE THREAD

**Issue by Sajarin-M** [mantinedev/mantine#2955]
### What package has an issue

@mantine/core

### Describe the bug

The value of number input is changeable even if the `readOnly` prop is set, by
clicking on the controls
or by arrow key press

### What version of @mantine/hooks page do you have in package.json?

5.7.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/readonly-numberinput-6bbtlt?file=/src/App.js:286-294

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

manually check if `readOnly` prop is set like already done for `disabled` prop

**Comment by rtivital** [comment]
Fixed in 5.8.2
