### ISSUE TITLE
Opening modal removes scrollbar and moves page content 

### ISSUE THREAD

**Issue by lukvermeulen** [mantinedev/mantine#296]
Link to the page: https://mantine.dev/core/modal/

Opening the modal removes the scrollbar (probably by setting "overflow: hidden" on the body) resulting in an (IMO) unwanted movement of the page. Everything moves horizontally to fill the now higher width. Maybe this is also related to the component, not the page(?)

**Comment by EmilMalanczak** [comment]
Yes, I can do it

At my current project, I use the `reach-ui` library and they handle it pretty well. 

Assign me to it, does this issue has prior over `use-scroll-into-view`?

**Comment by lukvermeulen** [comment]
You guys are awesome, thanks for the quick actions!
I noticed the same behavior with the [use-scroll-lock](https://mantine.dev/hooks/use-scroll-lock/) hook, just wanted to add this in case this is related to the modal :)

**Comment by rtivital** [comment]
Here are some questions:
- How we can find all position fixed elements?
- How we may know that those elements are affected by scrollbar? For example, Navbar in docs is fixed but will not be affected since it is on the left side.

**Comment by lukvermeulen** [comment]
Thanks for the fix! Works great and seamlessly in most cases. I just noted one minor issue with the [modal](https://mantine.dev/core/modal/): 
although the content of the site doesn't move, the modal itself moves upon closing it. 
It looks like the scroll-lock / padding functionality is executed before the animation of the modal closing has finished, resulting in the modal moving after I press the closing button. Is there a way of switching this?

**Comment by EmilMalanczak** [comment]
@lukvermeulen I'll try to cover that before 3.2 but its kinda tricky to do and might cause other issues due to operating on the modal element (probably by transformX)

**Comment by rtivital** [comment]
It should not be hard, we should just postpone scrollbars removal/adding back while animation is playing. In other words:
- when modal/drawer opens, wait until animation is done playing and lock scroll
- when modal/drawer closes, wait until animation is done playing and unlock scroll 

Should prevent flickering

**Comment by rtivital** [comment]
We've fixed flickering in 3.1.1 patch
