### ISSUE TITLE
error TS2304: Cannot find name 'DocumentVisibilityState'

### ISSUE THREAD

**Issue by limitless-dev** [mantinedev/mantine#2961]
### What package has an issue

@mantine/hooks

### Describe the bug

When I try to build my project `npm run build` which does `tsc && vite build` I get the following error:

```node
node_modules/@mantine/hooks/lib/use-document-visibility/use-document-visibility.d.ts:1:50 - error TS2304: Cannot find name 'DocumentVisibilityState'.

1 export declare function useDocumentVisibility(): DocumentVisibilityState;
```

My tsconfig.json has the following scopes.
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
    },
    "types": ["vitest/globals"]
  },
  "include": ["src/**/*", "tests/**/*"],
}
```

I am not even using mentioned hook in the error but the build fails regardless.

### What version of @mantine/hooks page do you have in package.json?

5.7.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Try setting `skipLibCheck: true`

**Comment by limitless-dev** [comment]
Setting `skipLibCheck: true` fixed it for me.
