### ISSUE TITLE
spotlight doesn't scroll when using ArrowDown/ArrowUp

### ISSUE THREAD

**Issue by ika18** [mantinedev/mantine#2965]
### What package has an issue

@mantine/spotlight

### Describe the bug

Spotlight content overflows, and spotlight doesn't scroll when using ArrowDown/ArrowUp.

### What version of @mantine/hooks page do you have in package.json?

5.7.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/naughty-wiles-1g7qm5

### Do you know how to fix the issue

No

### Possible fix

Maybe we can add a hook to check hovered Action whether need to scroll into view in ActionList component.

**Comment by colinricardo** [comment]
+1 on this one

**Comment by ChristophWahnsinn** [comment]
+1

**Comment by chhpt** [comment]
Is there any updates on the progress here?

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
