### ISSUE TITLE
Menu.Item does not allow legacyBehaviour for NextLink

### ISSUE THREAD

**Issue by mlarcher** [mantinedev/mantine#2968]
### What package has an issue

@mantine/core

### Describe the bug

https://mantine.dev/core/menu/#menuitem-as-nextjs-link states that we can use `<Menu.Item component={NextLink} href="/hello">` to use Next's Link but this doesn't appear to work with NextsJS 13 that changed the behaviour of the Link component.

### What version of @mantine/hooks page do you have in package.json?

5.7.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

add away to spcify if we want the new or legacy behaviour for the NextLink component

**Comment by rtivital** [comment]
For Next.js 13 just use Link instead of NextLink

**Comment by rtivital** [comment]
Fixed in 5.8.2, misleading documentation was removed

**Comment by Johannes-B-stock** [comment]
I can second what @wilsonwg  was saying, I also had to copy & paste from the previous version. This is with NextJS 12 and mantine 6
