### ISSUE TITLE
Inconsistent styles in TimeInput

### ISSUE THREAD

**Issue by siimaoo** [mantinedev/mantine#2969]
### What package has an issue

@mantine/dates

### Describe the bug

All inputs with variant unstyle and disabled prop true has the background transparent but TimeInput not.

![image](https://user-images.githubusercontent.com/34813589/201921028-d70db718-4b04-48af-821f-905791b3505d.png)

### What version of @mantine/hooks page do you have in package.json?

5.7.2

**Comment by rtivital** [comment]
Fixed in 6.0
