### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by kulame** [mantinedev/mantine#2979]
### What package has an issue

@mantine/core

### Describe the bug

when i try to use mantine Pagnation component.

![A%Q8QUYNZJU(I@51K4HHTBM](https://user-images.githubusercontent.com/57868732/202221913-9ff74b58-2af3-48d5-9797-2b9efd63817c.png)

i got the page  "391.7" string type value.

I expected it should be a number type  391

### What version of @mantine/hooks page do you have in package.json?

5.6.3

**Comment by zhulien-ivanov** [comment]
Well, you have provided `391.7` to `total`. Even thought that this potentially should be covered on component level, you **SHOULD** definitely take care of yourself before passing to the component. Use `Math.trunc(<total>)` and then pass it to `Pagination`.

**Comment by rtivital** [comment]
Fixed in 5.8.2
