### ISSUE TITLE
Typescript error while using styled on Text

### ISSUE THREAD

**Issue by AlonMiz** [mantinedev/mantine#2980]
### What package has an issue

@mantine/core

### Describe the bug

prop children is not allowed while using styled/emotion
it happens with more components.

```tsx

import { Text, MantineProvider } from "@mantine/core";
import styled from "@emotion/styled";

const StyledText = styled(Text)`
  background-color: magenta;
`;

export default function App() {
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      Your example here
      <StyledText>wow</StyledText>
    </MantineProvider>
  );
}
```

error thrown
```

Type '{ children: string; }' has no properties in common with type 'IntrinsicAttributes & { theme?: Theme | undefined; }'.ts(2559)

```
<img width="660" alt="image" src="https://user-images.githubusercontent.com/1812912/202264401-ffc8d5ae-db55-4b51-9c06-45cff4a0cad2.png">

using `createPolymorphicComponent` helps but it's a pretty bad Dev experience to do it on each usage.
createStyles is another bad alternative, as I need to "remember" what classes I use, where to place them, and which one goes where. 

### What version of @mantine/hooks page do you have in package.json?

5.7.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/quirky-resonance-d1hgjd?file=/src/App.tsx

### Do you know how to fix the issue

No

### Possible fix

using `createPolymorphicComponent`
```
export const StyledText = createPolymorphicComponent<'span', TextProps>(_StyledText);
```

**Comment by rtivital** [comment]
Polymorphic components section is a part of styled components documentation – https://mantine.dev/styles/styled/#polymorphic-components

**Comment by AlonMiz** [comment]
don't you think it's a lousy developer experience?
it feels much more like a bug than a requirement to use this workaround.

**Comment by rtivital** [comment]
There is nothing that can be done on our side to fix it – polymorphic components types cannot be correctly extracted by `styled` function

**Comment by AlonMiz** [comment]
is there an issue on their side? maybe they can help with that issue?

**Comment by rtivital** [comment]
Nope, it is how polymorphic components work – prop type is unknown until the component is used, you can find implementation details here – https://github.com/mantinedev/mantine/blob/master/src/mantine-utils/src/create-polymorphic-component/create-polymorphic-component.ts#L32:L40
