### ISSUE TITLE
Cannot read property of undefined theme - Remix + Algolia SSR

### ISSUE THREAD

**Issue by ayuhito** [mantinedev/mantine#2983]
### What package has an issue

@mantine/core

### Describe the bug

This is a really really niche issue that seems to be happening when using `useStyles` and a custom theme value in a Remix + Algolia SSR environment. I used the official Algolia template [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react-hooks/#with-remix) and then applied a basic Mantine installation on top of it.

```
TypeError: Cannot read property '1' of undefined
    at /sandbox/app/components/Header.tsx:8:74
    at useStyles (/sandbox/node_modules/@mantine/styles/src/tss/create-styles.ts:50:23)
    at Header (/sandbox/app/components/Header.tsx:13:23)
    at processChild (/sandbox/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/sandbox/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/sandbox/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/sandbox/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/sandbox/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at execute (/sandbox/node_modules/react-instantsearch-hooks-server/dist/cjs/getServerState.js:84:3)
    at /sandbox/node_modules/react-instantsearch-hooks-server/dist/cjs/getServerState.js:43:12
```

If you refer to the sandbox `Header.tsx` and remove `color: theme.colorScheme === "dark" ? theme.colors.text[0] : theme.colors.text[1]` from `createStyles()`, things work fine again. The undefined value comes from `theme.colors` which renders fine in a normal Remix environment but breaks with Algolia SSR.

Perhaps the theme value is lost in Algolia SSR? Does this look familiar? 

I know it's kind of hard to see whether Mantine or Algolia is responsible for the bug, but perhaps you may have some clues before I try the other parties. At least more context for other teams whether it's related to `emotion` or something else.

Steps to reproduce:
- Fork [Remix + Algolia SSR template](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react-hooks/#with-remix)
- Follow Mantine installation + Mantine Remix installation
- Add component which uses `createStyles()` and `useStyles()` with a `theme` parameter

Thanks for your awesome work! Really appreciate it!

### What version of @mantine/hooks page do you have in package.json?

5.7.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/fervent-napier-6oq0je?file=/app/components/Header.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Most likely, you do not have MantineProvider in your tree

**Comment by ayuhito** [comment]
Thank you so much! That was exactly it since Instantsearch was trying to render a subtree of `root.tsx` which has the original provider. Wrapping a new provider just for the Algolia SSR pass fixes things!
