### ISSUE TITLE
`Dropzone` failed to compile

### ISSUE THREAD

**Issue by XDean** [mantinedev/mantine#299]
When use `Dropzone`, typescript complain type error as below.

```
./node_modules/@mantine/dropzone/src/Dropzone/Dropzone.tsx:75:42
Type error: Argument of type 'Partial<Record<"loading" | "root" | "active" | "reject", CSSProperties>> | undefined' is not assignable to parameter of type 'Partial<Ma
ntineStyles<Record<"loading" | "root" | "active" | "reject", string>>>'.
  Type 'undefined' is not assignable to type 'Partial<MantineStyles<Record<"loading" | "root" | "active" | "reject", string>>>'.
```

**Comment by rtivital** [comment]
Hi @XDean, I've checked Dropzone, it works as expected. Make sure that you have `skipLibCheck` set to `true` in your tsconfig.json and that you use dropzone correctly:

```tsx
<Dropzone onDrop={() => {}}>
  {() => <div style={{ pointerEvents: 'none' }}>Drop files here</div>}
</Dropzone>
```

**Comment by XDean** [comment]
I do set `skipLibCheck`. I find following statement in [ts document](https://www.typescriptlang.org/tsconfig/#skipLibCheck)

> Rather than doing a full check of all d.ts files, TypeScript will type check the code you specifically refer to in your app’s source code.

Event `skpiLibCheck = true`, compiler with still check the code we used.

I think the quickest solution is to change the function to accept `undefined`.

**Comment by rtivital** [comment]
But you do not use `mergeStyles` function in your code, thus it should not be checked by ts. Please try also adding `node_modules` folder to `exclude`.

**Comment by rtivital** [comment]
It's not a bug, we do not use `strict` option in our development process that's why we do not include undefined as possible type in none of our internal functions. But we do include add necessary types in public API.

**Comment by XDean** [comment]
@rtivital I see. Do you think this is possible related to NextJS? I'm using it.

I will create a minimize reproduce case for you.

**Comment by rtivital** [comment]
I've checked Dropzone with https://github.com/mantinedev/mantine-next-template, and it did not show any errors. If you provide a reproduction repo, I'll have a look.

**Comment by XDean** [comment]
Finally, I find root cause. My IDE auto import dropzone from `@mantine/dropzone/src/Dropzone/Dropzone` instead of `@mantine/dropzone`. Sorry to bother you. 
I like mantine as always. 😀
