### ISSUE TITLE
@mantine/hooks use-scroll-lock does not prevent scrolling on iOS Safari

### ISSUE THREAD

**Issue by dallanlee** [mantinedev/mantine#300]
Mantine v 3.0.4
iOS Safari 15.0.1

The `use-scroll-lock` hook does not lock scrolling on iOS Safari (testing demo page https://mantine.dev/hooks/use-scroll-lock/).

Here's an up-to-date article that goes into the specific problems and how to properly prevent scrolling in iOS Safari that may be worth referencing for a fix: https://pqina.nl/blog/how-to-prevent-scrolling-the-page-on-ios-safari/

edit: fix link to article

**Comment by dallanlee** [comment]
I can imagine. iOS Safari has had quirks with locking the body and keeping the scroll position already and now iOS 15 introduces *new* issues 🙃

Oops 🤦‍♂️ Here's the article link: https://pqina.nl/blog/how-to-prevent-scrolling-the-page-on-ios-safari/

**Comment by iDavidB** [comment]
I just tried this on my iPhone running iOS 15.1 and it works. I did notice that sometimes it takes an extra second or so before the lock "kicks in" allowing you to scroll at least once more. However, this seems to be an issue with mobile browsers in general.

**Comment by rtivital** [comment]
Demo on home page also works for me on iOS 15, but it does not work with Modal which uses use-scroll-lock

**Comment by iDavidB** [comment]
> Demo on home page also works for me on iOS 15, but it does not work with Modal which uses use-scroll-lock

I'm assuming you mean you can still scroll what is behind the modal? I actually get the same behavior there as I described in my previous comment. It will lock, it just takes a second. Strangely after it worked once, closing and opening the modal again doesn't cause this behavior again.

**Comment by mikirejf** [comment]
I can try and work on this issue. IMO there are two possible solutions:

1. the one that @dallanlee linked,
2. and another one where you set `body` to `position: fixed;`.

As far as I know, the downside of these approaches is that it forces the browser to show the address and navigation bar. The pros are that the implementation is very simple and straightforward and therefore easy to maintain.

https://user-images.githubusercontent.com/8895894/143319206-6af0520e-1f33-4265-8e4d-069886150abe.mp4

Airbnb uses the solution with `position: fixed;`. I guess if it's good enough from the UX perspective for Airbnb, it would be good enough for sites built with mantine. :D

@rtivital tell me if the behavior is acceptable and I can submit a pr.

**Comment by EmilMalanczak** [comment]
will that work will internal scrollable content? Also, there's a big issue with that approach - when u set `position: fixed` body content scrolls to the top which looks strange

**Comment by mikirejf** [comment]
It will work, since we are not canceling any events etc. By setting the `position` to `fixed`, you are basically telling the browser to take that element out of the normal flow and expand it to it's full dimensions -> scrollbar disappears. The other elements are not affected.

The scroll position needs to be handled accordingly. Save the scrollY before invoking any other changes and then restore it after the scroll has been enabled again.

**Comment by EmilMalanczak** [comment]
Sounds good, I tried something similar before but still had issues on iphone (used ip7)

**Comment by mikirejf** [comment]
Just to update, I'm still working on the solution when I have time (almost none recently).  The current PR implementation causes flicker under certain circumstances. Also, the current solution doesn't handle text input focusing correctly (e.g. for a form in a modal), making the UI unusable in some cases or at least severely reducing the UX.

**Comment by mikirejf** [comment]
@rtivital 
We can only hope that Apple fixes it. IMO their philosophy is to somewhat hinder the experience on the web (no fullscreen API on iPhones also) so devs would build more iOS apps, which means more revenue for Apple.

**Comment by rtivital** [comment]
It's time to let it go. We've already wasted too much time on this.
