### ISSUE TITLE
make @tabler/icons optional

### ISSUE THREAD

**Issue by imranbarbhuiya** [mantinedev/mantine#3017]
### What package has an issue

@mantine/tiptap

### Describe the bug

`@mantine/tiptap` now requires installing `@tabler/icons` even tho I'm not using `ColorPicker` in my editor so I don't want to bundle an icon package. 

### What version of @mantine/hooks page do you have in package.json?

5.8.2

### Possible fix

Maybe make it load dynamically or change it to a new component that'll load `@tabler/icons` only if anyone imports that component.

**Comment by rtivital** [comment]
Tabler icons are used in every control. The package cannot be optional.

**Comment by imranbarbhuiya** [comment]
Ic  thanks for the quick response. I'm already using another icon package and don't want to use this one too. Also, I'm not using any controllers. I'm using keyboard shortcuts and markdowns like `**`. So is it possible to make `RichTextEditor.Controller` a separate component?

**Comment by rtivital** [comment]
All modern bundlers will remove code that you do not use with tree shaking in production builds. If you do not use any controls, then none of the icons will be included in the production bundle.

**Comment by imranbarbhuiya** [comment]
Thanks.
