### ISSUE TITLE
Unable to use either kebab case or camelCased CSS attribute for `-webkit-line-clamp`

### ISSUE THREAD

**Issue by mcmxcdev** [mantinedev/mantine#3023]
### What package has an issue

@mantine/core

### Describe the bug

`@emotion/serialize` is throwing the following warning when using kebab-case attributes e.g. `'-webkit-line-clamp': '1'` and passing it to `sx` prop of `Text` component: `Using kebab-case for css properties in objects is not supported. Did you mean WebkitLineClamp?`

When changing code to `WebkitLineClamp: '1'`, the following TS issues pop up:

```
Type '(theme: MantineTheme) => { WebkitLineClamp: string; color: [string, string, string, string, string, string, string, string, string, string]; }' is not assignable to type 'Sx | (Sx | undefined)[] | undefined'.
  Type '(theme: MantineTheme) => { WebkitLineClamp: string; color: [string, string, string, string, string, string, string, string, string, string]; }' is not assignable to type '(theme: MantineTheme) => CSSObject'.
    Call signature return types '{ WebkitLineClamp: string; color: [string, string, string, string, string, string, string, string, string, string]; }' and 'CSSObject' are incompatible.
      The types of 'WebkitLineClamp' are incompatible between these types.
        Type 'string' is not assignable to type 'WebkitLineClamp | (WebkitLineClamp | undefined)[] | (Globals | "none")[] | undefined'.
        ```

### What version of @mantine/hooks page do you have in package.json?

5.7.1

**Comment by rtivital** [comment]
It works correct on codesandbox – https://codesandbox.io/s/confident-galois-45sjnr?file=/src/App.tsx

**Comment by mcmxcdev** [comment]
> It works correct on codesandbox – [codesandbox.io/s/confident-galois-45sjnr?file=/src/App.tsx](https://codesandbox.io/s/confident-galois-45sjnr?file=/src/App.tsx)

It actually also gives TS issues in the codesandbox, but just found out it works as number rather than string: `WebkitLineClamp: 1`

I am sure I have tried it with number before, but whatever, thank you!
