### ISSUE TITLE
Multiselect create not working

### ISSUE THREAD

**Issue by ValentinKolb** [mantinedev/mantine#3026]
### What package has an issue

@mantine/core

### Describe the bug

i would like to combine mantine form with the multiselect. the select should also be creatable.
but this doesn't work, only the last created item is displayed. if i create a new item the last created item is removed.
if i don't use the "value" prop it works, but then i can't control the select like this anymore.

### What version of @mantine/hooks page do you have in package.json?

5.7.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/agitated-hill-sm97bi?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
You need to update `data` – https://codesandbox.io/s/goofy-bird-18vj7j?file=/src/App.tsx
