### ISSUE TITLE
[Feature Request] Date controls: Make first day of week locale aware.

### ISSUE THREAD

**Issue by jimbolla** [mantinedev/mantine#303]
It's much more common in the US for calendars to be shown with Sunday as the first day of week. 

It looks like dayjs has a [Weekday plugin](https://day.js.org/docs/en/plugin/weekday) to detect which day is the first day of week, so this seems like a logical way to pick this value.

**Comment by rtivital** [comment]
Done, will be released as part of 3.2.0 release (December 3rd or earlier)

**Comment by rtivital** [comment]
Released in 3.2
