### ISSUE TITLE
Properties of types 'p' are not assignable to CardProp

### ISSUE THREAD

**Issue by Haberkamp** [mantinedev/mantine#3037]
### What package has an issue

@mantine/core

### Describe the bug

While upgrading Mantine from 5.5.0 to the newest 5.8.0 / 5.5.3 I had an issue with my custom Card component that is a wrapper around the Mantine Card component. Typescript complains that the 'p' prop is not assignable when providing it with the props from the Style API.

![Screenshot 2022-11-23 at 13 18 51](https://user-images.githubusercontent.com/35109813/203545153-5380457c-cac6-4da0-bd4b-65771d10fd2f.png)

### What version of @mantine/hooks page do you have in package.json?

^5.8.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/condescending-waterfall-0ht2cp?file=/src/CustomCard.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 6.0
