### ISSUE TITLE
theme.breakpoints redirect leads to 404

### ISSUE THREAD

**Issue by markbeep** [mantinedev/mantine#3046]
Clicking on theme.breakpoints in the documentations redirects to https://mantine.dev/styles/responsive-styles/ which leads to the 404 page.
![image](https://user-images.githubusercontent.com/20665331/203658544-ee3ff540-9a43-4a19-bf1a-e1cdf8300fac.png)

**Comment by rtivital** [comment]
Fixed, thanks for reporting!
