### ISSUE TITLE
Stepper auto submits form when using Mantine Button

### ISSUE THREAD

**Issue by pedrogius** [mantinedev/mantine#3050]
### What package has an issue

@mantine/core

### Describe the bug

I'm building a multi step form (using react-hook-form). Below the stepper there are two mantine buttons to move forward or backwards. When the active step is the Step.Completed, the button has a submit type and an inner text of "Finish".

When I move from the last step to the completed step, even though the button is the "Next" button, the form is submitted. Using an event listener I can see the form was submitted using the submit button, however it wasn't clicked, I just moved into this step.

This doesn't happen if I use the native html button element.

### What version of @mantine/hooks page do you have in package.json?

5.8.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/practical-lamport-i1r39m?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by pedrogius** [comment]
Adding a key with any value to the button element (not even inside a map) for some reason solves this problem.

**Comment by rtivital** [comment]
Not related to Mantine, form will be submitted even if you use native HTML buttons – https://codesandbox.io/s/delicate-shadow-plfi80

**Comment by pedrogius** [comment]
Yes, however if you use native button on the first element ("finish"), and mantine button on the "next" button, the form isn't submitted. Do you have any idea where it might be coming from if it's not mantine? I've solved it adding a key to the button for the time being.

**Comment by rtivital** [comment]
`key` is required in this case

**Comment by engincannot** [comment]
Why does adding `key` solve this? What's the point of `key`?
