### ISSUE TITLE
useForm validate options isn't typed properly when using nested fields

### ISSUE THREAD

**Issue by joelzwarrington** [mantinedev/mantine#3055]
### What package has an issue

@mantine/form

### Describe the bug

```javascript
useForm({
  initialValues: {
    user: {
      name: ``,
    },
    anotherField: ``,
  },
  validate: {
    user: {
      name: (value, values) => {
        console.log(values);
        return null;
      },
      // ✅ value is string
      // ❌ values is { name: string }
      // but when looking at the log, you can see that `anotherField` is present
    },
  },
});
```

### What version of @mantine/hooks page do you have in package.json?

5.8.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/intelligent-microservice-0ywj4z?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by PaulAshraf** [comment]
+1

**Comment by Noubar-Kassabian** [comment]
I don't quire understand, aren't you adding it as an object to begin with? `{...form.getInputProps(`user.name`)` should return an object because you are defining it as the name within the user object. Or am I understanding this thing wrong?

**Comment by joelzwarrington** [comment]
@Noubar-Kassabian, see the example below:
```
useForm({
  initialValues: {
    user: {
      name: ``,
    },
    anotherField: ``,
  },
  validate: {
    user: {
      name: (value, values) => {
        console.log(values);
        return null;
      },
      // ✅ value is string
      // ❌ values is { name: string }
      // but when looking at the log, you can see that `anotherField` is present
    },
  },
});
```

The issue lies in that the `values` argument for the validate function of a nested field isn't what it should be (either the type is wrong, or the values passed to it are wrong).

The value of `values` through Typescript is:
```
{ name: string }
```
when in reality the value is:
```
{ anotherField: "", user: { name: "" } }
```

**Comment by rtivital** [comment]
The issue is fixed – https://codesandbox.io/s/frosty-ben-50d8wu?file=/src/App.tsx
