### ISSUE TITLE
Validation of form children is not right

### ISSUE THREAD

**Issue by dmgauthier** [mantinedev/mantine#3064]
### What package has an issue

@mantine/form

## Use Case
Validation of a form with children using `form.isValid('children')`

### Description

When a specific field nested within the form is invalid, the whole form and the specific path will properly update its valid state, but not the child wrapping the field.

### What version of @mantine/hooks page do you have in package.json?

5.6.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/brave-cache-r98l1m?file=/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Fixed in 5.9.1
