### ISSUE TITLE
NumberInput Styles API won't override color when disabled

### ISSUE THREAD

**Issue by lgaspari** [mantinedev/mantine#3071]
### What package has an issue

@mantine/core

### Describe the bug

Hey there!

I'm trying to override `NumberInput` styles using the Styles API from [NumberInput docs](https://mantine.dev/core/number-input/?t=styles-api), but upon overriding the `input` class it looks like it won't go over `disabled` styles.

As seen in the [codesandbox](https://codesandbox.io/s/modest-lehmann-734v3h) shared below, we have two inputs and only one of them is actually overriding the input's color (`black` or `white`, based on color scheme) over the disabled state (`gray`, default).

My take is that `disabled` styles must go above everything else to ensure accessibility, so it makes sense not being able to override the disabled styles. However, what would be the "best case" to override these styles without doing something "hacky" like changing `.mantine-NumberInput-input` class directly?

### What version of @mantine/hooks page do you have in package.json?

5.8.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/modest-lehmann-734v3h

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

**Option 1**

The first option I can think of is always using user's styles on top of input's styles. That way, we can always modify whatever we want from the input regardless of the input settings.

**Option 2**

If option 1 is discouraged because we would lose accessibility, then I would suggest having some kind of "edge-case" documented for this use case.

**Comment by rtivital** [comment]
https://codesandbox.io/s/restless-star-gnlrrf?file=/src/App.tsx

**Comment by lgaspari** [comment]
Hi @rtivital, thanks for being prompt!

Alright, it makes sense adding the `:disabled` modifier taking into account that the input is actually disabled 😅, plus it's for display only. I thought I had to hack it somehow using `!important` but yeah this is a cleaner approach, thanks.

Closing this one!
