### ISSUE TITLE
DatePicker example is off by 1 month

### ISSUE THREAD

**Issue by mikesholiu** [mantinedev/mantine#3075]
### Link to the page where something nasty is located

https://mantine.dev/dates/date-picker/

### Exact quote of what is wrong

The DatePicker example shows:

```
const [value, setValue] = useState<DateRangePickerValue>([
    new Date(2021, 11, 1),
    new Date(2021, 11, 5),
  ]);
```
However, the UI is rendering with December 1, 2021 - December 5, 2021, which is ahead by 1 month.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
This is how dates work in JavaScript, months start at 0, 11 is December,
