### ISSUE TITLE
Types not inferred correctly in validation object when using union types.

### ISSUE THREAD

**Issue by Dinishka** [mantinedev/mantine#3091]
### What package has an issue

@mantine/form

### Describe the bug

When declared form values like this.
`interface FormValues {
   code: string;
   name: string;
   parentId: string | null;
   parentRatio: number | undefined;
}`
The fields that accept union types cannot infer types correctly in the validation section. Those fields give both value & values as any. But the other fields can infer types correctly.
![UseForm](https://user-images.githubusercontent.com/84142140/205111700-8f2a8274-4692-4ae0-971e-99bce4c09883.png)

### What version of @mantine/hooks page do you have in package.json?

5.8.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/crimson-dust-3znmon

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Fixed in 5.9.2
