### ISSUE TITLE
Warning: [JSS] Rule is not linked. Missing sheet option "link: true".

### ISSUE THREAD

**Issue by chrisvariety** [mantinedev/mantine#31]
When starting the [mantine-next-example](https://github.com/mantinedev/mantine-next-example) with `npm run dev`, when you visit the root in your browser, you will see a flood of `Warning: [JSS] Rule is not linked. Missing sheet option "link: true".` messages in the terminal (not in the browser) due to SSR.

It looks like this is due to https://github.com/cssinjs/jss/issues/1277 but you may want to at least call this out in the SSR documentation so it doesn't surprise folks / make them think something is wrong?

**Comment by rtivital** [comment]
Yes, that's a good point, I'll add mention about this to docs, thanks

**Comment by khushal87** [comment]
This even occurs in the package itself. We need to fix it here too.

**Comment by rtivital** [comment]
Where it happens? Never seen this before

**Comment by khushal87** [comment]
Oh sorry, my bad! Was actually getting this `Cannot write file 'c:/Users/hrith/mantine/configuration/jest/enzyme.setup.js' because it would overwrite input file.`

**Comment by rtivital** [comment]
[Released in 1.0.4](https://github.com/mantinedev/mantine/releases/tag/1.0.4)
