### ISSUE TITLE
AppShell responsive issue when layout is set to "alt"

### ISSUE THREAD

**Issue by aleyrizvi** [mantinedev/mantine#3105]
### What package has an issue

@mantine/core

### Describe the bug

Have a look at the official example here: https://mantine.dev/app-shell-demo-alt/

When its in mobile mode and burger menu appears, click on it. Navbar takes over and header is not displayed (it does, but its behind navbar). There is no way to close navbar other than refresh the page.

### What version of @mantine/hooks page do you have in package.json?

^5.8.4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

I haven't studied mantine in detail yet to find the fix.

**Comment by rtivital** [comment]
Fixed in 5.9.2

**Comment by TavaresDev** [comment]
Hello, I'm having the same problem with the AppShell, using the alt Layout. There is no way of closing the Navbar. I tried the 5.9.2 version and the 5.9.5.

Without the alt layout works fine.

any suggestions?

Thanks

**Comment by rtivital** [comment]
You can find demo source code here – https://github.com/mantinedev/mantine/blob/modal-base/docs/src/pages/app-shell-demo-alt.tsx#L10

**Comment by TavaresDev** [comment]
Thanks Vitaly, That helped :)

**Comment by anthonyalayo** [comment]
@rtivital is there a new location for that demo? I can't seem to find it, and I'm also struggling with the alt layout. Thanks in advance!

**Comment by rtivital** [comment]
https://github.com/mantinedev/mantine/blob/master/docs/src/pages/app-shell-demo-alt.tsx#L10

**Comment by anthonyalayo** [comment]
@rtivital I tried out that demo, and it's showing me the same issue that I had before I started searching for this example. My content inside the app shell is hidden behind the nav bar (including the header). Would you have any idea why that would be the case? Did something change with the components such that a different setting is needed?

If I set fixed={false}, my content actually appears to the right of the navbar, but then the alt layout isn't working anymore (the header is on top of the nav).

**Comment by rtivital** [comment]
Send a sandbox that reproduces the issue

**Comment by annalbirena** [comment]
Hi @rtivital, is there a new location for this demo? v6 https://v6.mantine.dev/app-shell-demo-alt/
