### ISSUE TITLE
`hideOutsideDates` is not respected when using `maxDate` or `minDate`

### ISSUE THREAD

**Issue by filiptammergard** [mantinedev/mantine#3114]
### What package has an issue

@mantine/dates

### Describe the bug

`hideOutsideDates` is not respected when days are disabled because of `maxDate`/`minDate` for example. 

`<DatePicker hideOutsideDates />` hides dates that don't belong to current month:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/44197016/205637531-092084fa-be0a-4fe6-ae32-61994f2c7052.png">

However, when adding a `minDate`, it doesn't.

`<DatePicker hideOutsideDates minDate={new Date()} />` takes the outside dates back:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/44197016/205637781-7d2f4b48-5999-4a1b-be25-b33a5946dc44.png">

### What version of @mantine/hooks page do you have in package.json?

5.9.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/silly-forest-fcvs01?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Right now, `data-outside` is only `true` when `Day` is not disabled. Days on the wrong side of `minDate` are disabled, which results in them not getting `data-outside="true"` and therefore not being visually removed.

https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/Month/Day/Day.tsx#L76

Changing `data-outside={(outside && !disabled) || undefined}` to `data-outside={outside || undefined}` is simple, but I'm not sure if that'd break something else.

**Comment by rtivital** [comment]
It will be fixed in 6.0 release

**Comment by rtivital** [comment]
Fixed in 6.0
