### ISSUE TITLE
getFilesFromEvent is not a function

### ISSUE THREAD

**Issue by mr-josh** [mantinedev/mantine#3115]
### What package has an issue

@mantine/dropzone

### Describe the bug

Mantine 5.9.1 throws an error when selecting/dropping a file into dropzone.

Error:
`getFilesFromEvent is not a function`

@porkopek has found a work around in comment linked below:
https://github.com/mantinedev/mantine/pull/3053#issuecomment-1336466512

### What version of @mantine/hooks page do you have in package.json?

5.9.1

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

We could include the above work around made by @porkopek and include it as default props for the dropzone component?

**Comment by porkopek** [comment]
My workaround is just while this is not solved. The real solution is make this prop optional

**Comment by rtivital** [comment]
Fixed in 5.9.2
