### ISSUE TITLE
useClickOutside multiple nodes documentation shows broken 'null' argument

### ISSUE THREAD

**Issue by charliequin** [mantinedev/mantine#3119]
### Link to the page where something nasty is located

https://mantine.dev/hooks/use-click-outside/#multiple-nodes

### Exact quote of what is wrong

The following hook is documented as taking two `null` values as argument for the `nodes` parameter like so

```js
const [dropdown, setDropdown] = useState(null);
const [control, setControl] = useState(null);

useClickOutside(() => console.log('outside'), null, [control, dropdown]);
```

but throws a TS due to being typed as an `HTMLElement`
```ts
function useClickOutside<T extends HTMLElement = any>(
  handler: () => void,
  events?: string[] | null,
  nodes?: HTMLElement[]
): React.MutableRefObject<T>;
```

The documentation should reflect this or be typed to accept `null` as an argument by default until a ref to an element has been supplied.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Fixed in 5.9.4
