### ISSUE TITLE
Select input item triggers on mouse down instead of on click

### ISSUE THREAD

**Issue by hichemfantar** [mantinedev/mantine#3120]
### What package has an issue

@mantine/core

### Describe the bug

Items are usually selected when the onclick event is triggered, not on mouse down.
Basically using onClick I can cancel out of the action by moving the cursor out of the box, however using onMouseDown, the event is triggered without giving me the chance to cancel.

### What version of @mantine/hooks page do you have in package.json?

5.9.2

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Usage of `onMouseDown` is required to prevent focus from shifting to the item component when it is clicked.

**Comment by hichemfantar** [comment]
Do you mean you want to keep the select box focused when an item is clicked?

**Comment by rtivital** [comment]
Yes
