### ISSUE TITLE
Menu inside Table with ScrollArea ignores dropdown position

### ISSUE THREAD

**Issue by noahsb** [mantinedev/mantine#3122]
### What package has an issue

@mantine/core

### Describe the bug

When adding a `Menu` within a `Table` with `ScrollArea` wrapping the table, `Menu` dropdown position is always shown above (overriding the `position` prop)

It seems like this happens when the entire `Table` is wrapped in a `Stack`

### What version of @mantine/hooks page do you have in package.json?

5.9.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/strange-joliot-y9lz7l

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Set `withinPortal` – https://codesandbox.io/s/throbbing-shadow-ljzkt0?file=/src/App.tsx
