### ISSUE TITLE
RichTextEditor doesn't accept sx props

### ISSUE THREAD

**Issue by AabhasDhaubanja** [mantinedev/mantine#3124]
### What package has an issue

@mantine/tiptap

### Describe the bug

The RichTextEditor doesn't have type-checking for sx props. 

![Screenshot from 2022-12-06 11-17-28](https://user-images.githubusercontent.com/43627146/205824988-34dd2d0a-ec1f-4fe2-99cf-14451e78af7b.png)

### What version of @mantine/hooks page do you have in package.json?

5.9.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-playground-forked-rk44qh?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by adarshaacharya** [comment]
@rtivital raised pr fixing the issue, https://github.com/mantinedev/mantine/pull/3142

**Comment by AabhasDhaubanja** [comment]
Thanks @adarshaacharya
