### ISSUE TITLE
Transition resolves instantly sometimes

### ISSUE THREAD

**Issue by twiddler** [mantinedev/mantine#3126]
### What package has an issue

@mantine/core

### Describe the bug

`Transition` sometimes shows its content instantly. I encountered this error in my app and was able to reproduce it on [Mantine's documentation page on Transitions](https://mantine.dev/core/transition/):

[Transition bug on try 4 and 7](https://user-images.githubusercontent.com/13364827/205909417-4475ed94-2915-46ac-bb9f-2055417ce157.webm)

In the video, the dropdown is shown instantly when opening it the 4th and the 7th time.

I cannot reproduce this bug every time. It seems to happen randomly.

I am running Fedora 37. I encounter this bug in Mozilla Firefox 107.0, Chromium 105.0.5195.125 and Chrome 110.0.5449.0. I did not try it in other browsers or versions.

### What version of @mantine/hooks page do you have in package.json?

5.9.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/transition/

### Do you know how to fix the issue

No.

### Are you willing to participate in fixing this issue and create a pull request with the fix

I don't believe I can, so no.

**Comment by rtivital** [comment]
I cannot reproduce it in Chrome, Safari and Firefox on macOS.

**Comment by rtivital** [comment]
Your issue is not related to this issue, see https://mantine.dev/theming/theme-object/#respectreducemotion

**Comment by crstffr** [comment]
You are right. It does look to be the reduced motion settings. I'm sorry for the confusion.

**Comment by cyantree** [comment]
I can reproduce it on Win 10 with Chrome.

It might be related to the following timeout:
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Transition/use-transition.ts#L57

My theory:
Sometimes this timeout resolves within the same animation frame. This leads to the browser rendering the `pre-entering` animation state (e. g. `opacity: 0`) and `entering` animation state (e. g. `opacity: 1`) in the same frame. Therefore the transition gets skipped entirely (because there is nothing to animate).
The current timeout of `10ms` might be relevant too because it's less than 1/60th of a second (or approx. 16.67ms) (typical refresh rate of displays).
So maybe it doesn't occur on displays with higher refresh rates like 120 hz (or approx. 8.33ms).

If I reduce the timeout from `10` to `1` I can reproduce it quite reliably.

```ts
      const preStateTimeout = window.requestAnimationFrame(() => {
        window.requestAnimationFrame(() => {
          typeof preHandler === 'function' && preHandler();
          setStatus(shouldMount ? 'entering' : 'exiting');
        });
      });
```

On the other hand increasing the timeout from `10` to `50` seems to eliminate it for my case.

So besides choosing an arbitrary timeout another solution might be switching to `requestAnimationFrame()` as this should ensure that there's a frame switch happening.

However in my tests I needed to wait for two frames to get it working.
```ts
      const preStateTimeout = window.requestAnimationFrame(() => {
        window.requestAnimationFrame(() => {
          typeof preHandler === 'function' && preHandler();
          setStatus(shouldMount ? 'entering' : 'exiting');
        });
      });
```

I don't know why this is. Maybe because the first `requestAnimationFrame()` still resolves in the same frame?

**Comment by cyantree** [comment]
I've checked this issue with the `v6` and can confirm that it's still an issue there.
However I also realized that my proposal doesn't work realiably.

After some more digging I think I found the real problem:
It's related to update batching of React. v18 introduces state update batching for calls like `setTimeout()`. This means that in these cases the call `setStatus(shouldMount ? 'entering' : 'exiting');` within the timeout will be batched with `setStatus(shouldMount ? 'pre-entering' : 'pre-exiting');`. Therefore the state `pre-entering` won't get processed at all.

A solution for this would be forcing the state update with `ReactDOM.flushSync()`:
```ts
    flushSync(() => {
      setStatus(shouldMount ? 'pre-entering' : 'pre-exiting');
    });
```

More details on this feature:
https://reactjs.org/blog/2022/03/29/react-v18.html#new-feature-automatic-batching
And some technical details including the way to opt out of batching:
https://github.com/reactwg/react-18/discussions/21

Another solution could be using effect hooks that make sure that `pre-entering` really has been set before continuing with with setting `entering`.

**Comment by runthis** [comment]
Hey there @rtivital just wanted to provide another replicated example that I think shows the issue more clear than the original video. I've noticed it for some time so I have avoided using it for anything interactive but I regularly check back on the component from time to time to see if it's better 😀.

chrome, mantine 6, react 18, standard usage of component.

In the video I am clicking pretty fast but it can happen after a long wait also. I hope this helps adjust this awesome component.

https://github.com/mantinedev/mantine/assets/8216720/09d8b2b9-478e-4a06-930c-7fb9f43185b0

**Comment by elibroftw** [comment]
This occurs on Windows 11 with Firefox as well. Text shows up before rather than along with the transition.

**Comment by cyantree** [comment]
I've revisited this issue and tried the `requestAnimationFrame()` solution again. Now it seems to work which I've tested for the demo in the docs and the demo from #5193.

Sandbox which uses a patched package:
https://codesandbox.io/p/devbox/mantine-transition-test-next-forked-f65whv?file=%2Fpackage.json%3A12%2C23&workspaceId=8bab33a5-6cc6-4fd2-9a92-7ae3f118fdf8

And here are the changes:
https://github.com/mantinedev/mantine/compare/master...cyantree:mantine:3126_fix-transition-handling?expand=1

If this seems fine I'll prepare a PR for it.

**Comment by rtivital** [comment]
Yeah, sure, you are welcome to submit a PR

**Comment by rtivital** [comment]
@cyantree I've copied and tested your changes, they work well. I've integrated them, so there is no need for a PR. Thanks for the research!

**Comment by rilrom** [comment]
I am still able to reproduce this in 7.6.1, though less often than before.

It seems more prevalent when the example provided above is moved into storybook instead of codesandbox, and even more prevalent in Firefox compared to chromium based browsers.
