### ISSUE TITLE
AppShell and Container don't play nice together

### ISSUE THREAD

**Issue by lgaspari** [mantinedev/mantine#3132]
### What package has an issue

@mantine/core

### Describe the bug

Honestly, I don't think this is an actual issue but I stumbled upon this problem while trying to have a fixed `Header` at the top along the content pushed down (see [example 1](https://codesandbox.io/s/jovial-smoke-tc114h?file=/src/App.tsx)). So, instead of adding the padding manually I went to the docs and found the `AppShell` component that solves the problem.

However, since I'm using a `Container` as inner wrapper for both Header and Main Content, now I'm seeing double padding on the Main Content area on low resolution devices (see [example 2](https://codesandbox.io/s/focused-robinson-wjrxrd?file=/src/App.tsx)).

I guess my questions are:

1. Are the AppShell and Container meant to play nice together or not?
2. Would it be possible to achieve this layout (AppShell + Container)? Otherwise, I'm thinking on move on with example 1

Thanks!

### What version of @mantine/hooks page do you have in package.json?

5.8.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/focused-robinson-wjrxrd?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Please use GitHub issues only to report issues, to ask questions, open a discussion.

**Comment by lgaspari** [comment]
> You can disable padding both on AppShell and Container components:
> 
> * `<AppShell padding={0} />`
> * `<Container px={0} />`

Actually, using `<Container px={0} />` solves the mobile devices problem, but adds another one on desktop devices (see [example 3](https://codesandbox.io/s/romantic-lewin-wxm5lw?file=/src/App.tsx)).

Looks like I would have to go with `<AppShell padding={0} />` instead and use `<Container py="md" />` to have consistent paddings around the content (see [example 4](https://codesandbox.io/s/sharp-goldberg-i00euf?file=/src/App.tsx)).

> Please use GitHub issues only to report issues, to ask questions, open a discussion.

You're right, apologies. I'm going to go ahead and close this issue, now. Thanks a lot for your help man.
