### ISSUE TITLE
TabsList - add spacing prop to control space between tabs

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#3139]
### What package has an issue

@mantine/core

### Describe the bug

TabsList - add spacing prop to control space between tabs
Now, for one variant which has spacing, this spacing value is hardcoded.
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Tabs/TabsList/TabsList.styles.ts#L46

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You can control that with sx prop on Tabs.List – https://codesandbox.io/s/gallant-minsky-hefw12?file=/src/App.tsx

**Comment by 7iomka** [comment]
> You can control that with sx prop on Tabs.List – https://codesandbox.io/s/gallant-minsky-hefw12?file=/src/App.tsx

it's not that pretty.
Besides, if you are like me who provides support for `gap` for older browsers in this way
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/18473137/206262499-d842e23e-0ab8-45dd-95fa-b1205e2f5ca3.png">


 it already looks painful in cases when you don't want this space
 
 
<img width="596" alt="image" src="https://user-images.githubusercontent.com/18473137/206262632-d335c65c-1a93-49c3-81d9-244fc01b62ef.png">

**Comment by rtivital** [comment]
So, how does the prop that allows to change gap will help you in this case?

**Comment by 7iomka** [comment]
> So, how does the prop that allows to change gap will help you in this case?

 I can use value from `spacing` prop and can use the same override pattern like in other cases, which uses `gap` internally
<img width="686" alt="image" src="https://user-images.githubusercontent.com/18473137/206281315-e93b21d2-5af1-4a9e-ac24-e7ffefc00fd9.png">

Without prop I need to keep in mind what exactly happens in default styles to just remove spacing.

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
