### ISSUE TITLE
[Bug] Confirm modal has wrong z-index relative to classic modal

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#3154]
### What package has an issue

@mantine/modals

### Describe the bug

Hi.
See repo link.
When confirm modal is opened (triggered) from currently opened modal it is unaccessible because DOM location where confirm modal always placed is before classic modals

### What version of @mantine/hooks page do you have in package.json?

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/distracted-noyce-ls4zx1?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
All modals are built with Modal component, zIndex is the same. It is not possible to decide on library level which modal should go on top of other modals. You should manage this logic on your side – https://codesandbox.io/s/smoosh-cache-s793s8?file=/src/App.tsx

**Comment by 7iomka** [comment]
> https://codesandbox.io/s/smoosh-cache-s793s8?file=/src/App.tsx

This is weird behaviour.
I mean, the last modal needed to be rendered in DOM after the previous one which is already rendered.
How other libraries resolve this issue under hood without this hacks on user side?

**Comment by rtivital** [comment]
I suppose that other libraries do not provide modals manager

**Comment by rtivital** [comment]
Fixed in 5.9.4 – `@mantine/modals` package now sets zIndex that is larger than Modal component zIndex

**Comment by imranbarbhuiya** [comment]
This fix is causing issues in my site. I can't set anything with higher zindex than the modal even with a fixed zindex using the `zindex` props. I'm not using the modals provider but the `Modal` from `mantine/core`

**Comment by rtivital** [comment]
Your issue is not related to this fix. Modal code was not changed. You can set `zIndex` prop to change Modal z-index: `<Modal zIndex={1000} />`.
