### ISSUE TITLE
MutableRefObject from use-scroll-into-view not compatible with ref prop

### ISSUE THREAD

**Issue by gljusty** [mantinedev/mantine#3156]
### What package has an issue

@mantine/hooks

### Describe the bug

use-scroll-into-view appears to be unusable with certain elements in typescript. The ref typings are throwing errors, 

"Type 'MutableRefObject<Element>' is not assignable to type 'RefObject<HTMLDivElement>'" 

or in the case of regular divs,

Type 'MutableRefObject<HTMLElement>' is not assignable to type 'LegacyRef<HTMLDivElement> | undefined'.
  Type 'MutableRefObject<HTMLElement>' is not assignable to type 'RefObject<HTMLDivElement>'.
    Types of property 'current' are incompatible.
      Property 'align' is missing in type 'HTMLElement' but required in type 'HTMLDivElement'.

notably on blank divs, Card and Group (possibly others, havent tested). Error comes up any time I try to assign the targetRef from the use-scroll-into-view hook.

### What version of @mantine/hooks page do you have in package.json?

5.8.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Can update the typing on the component refs to take in either Type 'MutableRefObject<Element>' or 'RefObject<HTMLDivElement>'

**Comment by rtivital** [comment]
Please send a sandbox or code that reproduces the error

**Comment by rtivital** [comment]
@gljusty I cannot reproduce the issue – https://codesandbox.io/s/xenodochial-butterfly-rmqpr0?file=/src/App.tsx
You are welcome to reopen the issue if you can provide a reproduction.

**Comment by gljusty** [comment]
Sorry, after further investigation today it seems to have been in my project causing the typing mismatch as I can't reproduce it in a sandbox but am reliably seeing it in my project reportedly as coming from index.d.ts in React 18.2. I can pass along the package.json and a screenshot of the error + relatively simple components in question if you're interested, but I think it's ok to just leave this closed.

Sorry again and thanks anyway for your time.

**Comment by gljusty** [comment]
I was finally able to reproduce the issue in a clean vite react-typescript template with only mantine installed. Setting the type solved it. Not sure if its a tsconfig issue? But for now this is a good solution. Thanks

If anyone comes across this with a similar issue, I solved it by explicitly setting the type
<code>const {targetRef, scrollIntoView} = useScrollIntoView\<HTMLDivElement>\({})
</code>
