### ISSUE TITLE
Issues with ModalTypes only extending unknown instead of any

### ISSUE THREAD

**Issue by Meierschlumpf** [mantinedev/mantine#3159]
### What package has an issue

@mantine/form

### Describe the bug

As already described in #3141 some types were not accepted to be used with use-form validation. The same is currently happening to me with ContextModalProps and OpenContextModal. (Both also just extend Record<string, unknown> instead of Record<string, any>).

### What version of @mantine/hooks page do you have in package.json?

5.9.3

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Change type of ContextModalProps and OpenContextModal to extend Record<string, any> instead of Record<string, unknown>.

**Comment by rtivital** [comment]
Fixed in 6.0
