### ISSUE TITLE
Custom Icon in tiptap RTE needs double click to toggle

### ISSUE THREAD

**Issue by wilsonbley** [mantinedev/mantine#3169]
### What package has an issue

@mantine/tiptap

### Describe the bug

When using a custom icon for a RTE control you need to click it twice to activate/deactivate. 

When you click the first time, it removes the focus from the *content* element and doesn't toggle the control. Clicking the second time it returns the focus to the *content* element toggling the control.

I can't tell if this is a bug in tiptap or mantine.

### What version of @mantine/hooks page do you have in package.json?

5.9.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/relaxed-hermann-h4ttkd?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Store icons as separate components – https://codesandbox.io/s/reverent-jang-7jqzeu?file=/src/App.tsx

**Comment by wilsonbljr** [comment]
Thanks, it worked!
