### ISSUE TITLE
Invalid initial value for "online" state in use-network hook

### ISSUE THREAD

**Issue by Sajarin-M** [mantinedev/mantine#3177]
### What package has an issue

@mantine/hooks

### Describe the bug

While use-network hooks works very well with network state changes it returns initial value `online : true` even  if not connected

### What version of @mantine/hooks page do you have in package.json?

5.9.4

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

maybe use `navigator.onLine` to get initial value ?
don't know if there is any issue with ssr while doing this

**Comment by rtivital** [comment]
Fixed in 5.9.5
