### ISSUE TITLE
ColorInput withEyeDropper prop does nothing

### ISSUE THREAD

**Issue by danielmilner** [mantinedev/mantine#3185]
### What package has an issue

@mantine/core

### Describe the bug

Setting `withEyeDropper` to `false` does not turn off the eye dropper.

### What version of @mantine/hooks page do you have in package.json?

^5.9.4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 5.10.0
