### ISSUE TITLE
The typographyStylesProvider and content in RichTextEditor styles do not take effect

### ISSUE THREAD

**Issue by jackyleefu** [mantinedev/mantine#3195]
### What package has an issue

@mantine/tiptap

### Describe the bug

The typographyStylesProvider and content in RichTextEditor styles do not take effect

### What version of @mantine/hooks page do you have in package.json?

5.9.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/vibrant-snow-wne697?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
