### ISSUE TITLE
The icon in Rich Text Editor Link cannot be changed

### ISSUE THREAD

**Issue by Avas77** [mantinedev/mantine#3196]
### What package has an issue

@mantine/core

### Describe the bug

We can change icons of Rich Text Editor controls by passing icon prop. This does not work for Rich Text Editor Link control and we are stuck with the default icon

### What version of @mantine/hooks page do you have in package.json?

5.9.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/fervent-minsky-4wv5yh?file=/src/Editor.js

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Fixed in 5.9.5
