### ISSUE TITLE
Custom theme keys are discarded

### ISSUE THREAD

**Issue by chrisvariety** [mantinedev/mantine#32]
Providing a custom theme like this:

```jsx
<MantineProvider theme={{brand: 'red'}}>
...
</MantineProvider>
```

... ends up discarding the `brand` key silently. I believe this is because of https://github.com/mantinedev/mantine/blob/12ceb348f579fcdcbeb88c1d1b6abb7d00bf1eb3/src/mantine-theme/src/utils/merge-theme/merge-theme.ts#L12

I think at least documentation here would be nice (I checked the unpublished theming doc), but ideally these keys would be merged into the theme object.

**Comment by rtivital** [comment]
Unfortunately there is no way to support correct types in TypeScript for custom keys as theme is passed via context – this means that theme shape should be static. If you need to pass some value deep into the tree, use separate context provider. Mantine theme merging is made this way intentionally.

**Comment by chrisvariety** [comment]
Gotcha, thanks much 🙏
