### ISSUE TITLE
Text prop "color" not working when styles for Text are set in MantineProvider theme

### ISSUE THREAD

**Issue by karlas** [mantinedev/mantine#3211]
### What package has an issue

@mantine/core

### Describe the bug

If color style is set in the theme at MantineProvider, it prevails over the color prop. Please check codesandbox

Don't really known if it's a bug, or it's intenctional

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/text-color-i619hs

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
This is intended behavior, if you want to override color use defaultProps instead – https://codesandbox.io/s/text-color-forked-vqzjlo?file=/src/App.tsx

**Comment by karlas** [comment]
Ooops didnt know, thanks for the clarification!
