### ISSUE TITLE
Span prop on Title component not rendering span

### ISSUE THREAD

**Issue by pkat** [mantinedev/mantine#3214]
### What package has an issue

@mantine/core

### Describe the bug

According to the [docs](https://mantine.dev/core/title/?t=props), the `Title` component has a prop called `span` defined as a `boolean` `Shorthand for component="span"`.

I have not been able to get this working as it always still renders a `<h1>`, `<h2>`, etc component instead of the `<span>` component.

Additionally when i attempt to use `component="span"` I get the following typescript error:
```
TS2322: Type '{ children: (string | Element)[]; order: 4; component: string; }' is not assignable to type 'IntrinsicAttributes & TitleProps & RefAttributes<HTMLHeadingElement>'.   Property 'component' does not exist on type 'IntrinsicAttributes & TitleProps & RefAttributes<HTMLHeadingElement>'.
```

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/snowy-https-qvlwze?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 5.10.0, span prop was removed
