### ISSUE TITLE
Card Image Section border radius not working properly in Safari (webkit)

### ISSUE THREAD

**Issue by jukrb0x** [mantinedev/mantine#3216]
### What package has an issue

@mantine/core

### Description

The card corners (border radius) are not showing properly in the Card component properly if the **first** or **last** `<Card.Section>` is `<Image>` from `@mantine/core`. The img overlapping the card.

### Snippet
```tsx
<Card radius={ 'lg' } withBorder className={ 'tw-w-[500px]' }>
    <Card.Section>
        <Image
            src='https://images.unsplash.com/photo-1527004013197-933c4bb611b3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=720&q=80'
            height={ 160 }
            alt='Norway'
            fit={ 'cover' }
        />
                                                                                                                                                                               
    </Card.Section>
    <div>
        ....
    </div>
</Card>

```

### In Safari/webkit (buggy)

![image](https://user-images.githubusercontent.com/15688641/208782356-f0d9b899-b9fe-4171-83cd-394b8e2fdb9e.png)

### In Chrome (as expected)
![image](https://user-images.githubusercontent.com/15688641/208782385-d435ecc8-1444-433a-8147-709921cf21fa.png)

### What version of @mantine/hooks page do you have in package.json?

^5.9.4

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

remove `position: relative` in `mantine-Image-imageWrapper` fix this.

current workaround is:
```tsx
<Image
    src='https://images.unsplash.com/photo-1527004013197-933c4bb611b3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=720&q=80'
    height={ 160 }
    fit={'cover'}
    alt='Norway'
    styles={()=>(
        {
            imageWrapper: {
                position: 'static',
            }
        }
    )}
                                                                                                                                                                       
/>
```

See #3217

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
