### ISSUE TITLE
Select menu is not fully visible inside Card component 

### ISSUE THREAD

**Issue by nsztyk** [mantinedev/mantine#3226]
### What package has an issue

@mantine/core

### Describe the bug

Select menu is not overflowing its wrapper when Card component is used. For comparison Paper component works as expected

![image](https://user-images.githubusercontent.com/24680812/209098241-b831525c-65d4-465a-99df-4342d853a20d.png)

### What version of @mantine/hooks page do you have in package.json?

5.9.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/card-paper-mhvkno

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Set withinPortal – https://codesandbox.io/s/card-paper-forked-j9gb2g?file=/src/App.tsx
