### ISSUE TITLE
React App Build Failed (Cannot read properties of undefined (reading 'constantViolations'))

### ISSUE THREAD

**Issue by seeratawan01** [mantinedev/mantine#3229]
### What package has an issue

@mantine/core

### Describe the bug

![image](https://user-images.githubusercontent.com/26021449/209189150-b0be928d-4807-4881-87e9-7e9b2212206d.png)

React app is working fine in dev mode, but with build command I'm getting this error. I created the simple react app with CRA and added mantine and typescript after that. Wrapped the <App> component in `MantineProvider` and try to build the app with `npm run build` and this error is failing the build process.

@floating-ui is being used by Mantine internally so I think it's due to mantine.

app.tsx
<img width="744" alt="image" src="https://user-images.githubusercontent.com/26021449/209190280-4492e129-37f8-4354-b8a2-c916cab5325b.png">

tsconfig.json
```json
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"]
}
```

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by seeratawan01** [comment]
https://github.com/babel/babel/issues/15300 this is issue is from babel side and not fixed yet.

**Comment by rtivital** [comment]
The issue is with your build system, applications with `@mantine` packages build correctly with other bundlers. I advise using vite instead of CRA.
