### ISSUE TITLE
"amPmInput" style API not working as expected

### ISSUE THREAD

**Issue by bettyyyin** [mantinedev/mantine#3235]
### What package has an issue

@mantine/dates

### Describe the bug

I want to change the style of every element of the time inputs, which include Hours, Minutes, AM/PM. I am able to change the style of Hours and Minutes inputs by using the timeInput style API. However, I cannot change the style of AM/PM by using amPmInput style API in the same way of timeInput API. 

Can someone have a check with this problem? Thanks so much for helps! 

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/thirsty-germain-4pgig6?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
The current implementation of TimeInput will be deprecated with 6.0 release, until then, no changes to the dates package are planned. You can view upcoming TimeInput component hanges here – https://rtivital.github.io/mantine-dates-6/

**Comment by rtivital** [comment]
Fixed in 6.0
