### ISSUE TITLE
Container's responsiveness is broken

### ISSUE THREAD

**Issue by akshatmittal** [mantinedev/mantine#3236]
### What package has an issue

@mantine/core

### Describe the bug

The `Container` component is always stuck at `md` values and never goes above or below it. The bug is easily visible in any of the Mantine UI examples that use the `Container` component. For example: https://ui.mantine.dev/component/header-simple

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://ui.mantine.dev/component/header-simple

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Container component works as intended, `size` prop sets max-width, there are no responsive styles.
