### ISSUE TITLE
Modal Close icon not changble

### ISSUE THREAD

**Issue by shakibdshy** [mantinedev/mantine#3242]
### What package has an issue

@mantine/modals

### Describe the bug

I just try design my template and I'm facing a problem when I try to resize the close icon or change it and add a new icon. I see it's not customizable.

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You can set `withCloseButton={false}` and add any close button on your side.
