### ISSUE TITLE
Components will have CLS issue with any styling method (createStyles, styled-components, inline) 

### ISSUE THREAD

**Issue by nedacc** [mantinedev/mantine#3243]
### What package has an issue

@mantine/core

### Describe the bug

i tried all the ways of styling components and i customized most of the components in "NEXTJS", but CLS issue will cause in every case and it's such a obvious Layout Shift! please, i used mantine in 2 other projects as well.

### What version of @mantine/hooks page do you have in package.json?

^5.9.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

i think it's the server-side rendering matter or it's javascript hydration needed to assign classes to components and it causes the delay of accepting classes.

**Comment by rtivital** [comment]
Follow Next.js setup documentation, if that does not work, use template as reference, it works correctly.
https://github.com/mantinedev/mantine-next-template
