### ISSUE TITLE
Cannot use custom id for modal

### ISSUE THREAD

**Issue by Satont** [mantinedev/mantine#3246]
### What package has an issue

@mantine/modals

### Describe the bug

When using `openModal` with custom id, i get error `TypeError: Cannot create property 'current' on string ':R1lcm:'`

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hungry-elion-g1qyrl?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
`id` prop is not supported, it can be a react issue. Use `modalId` prop instead if you want to reference modal in your code.

**Comment by Satont** [comment]
Ah, ok, I'll try. Thats just not documented, so thats why i missed this thing.
