### ISSUE TITLE
Nested ScrollArea not working properly; Also request feature for preventing either horizontal scroll or vertical scroll

### ISSUE THREAD

**Issue by EUGinsane** [mantinedev/mantine#3248]
### What package has an issue

@mantine/core

### Describe the bug

The example below demonstrates 2 problems:
* Nested ScrollArea not showing a scrollbar when the size of content reaches its parent size, press `ADD` button to add more items, it's horizontally scrollable, but the scrollbar is hidden, only when resizing the window, it shows. This does not happen with the native scrollbar.
* There is not an official way to prevent either horizontal scroll or vertical scroll, the below example also describes an use case in which a child needs to be as long as the parent's width, but only horizontally scrollable inside the child, since ScrollArea use `display: table`, which the width of the parent will be extended base on its contents, that's not what we want, the example also shown the hack

### What version of @mantine/hooks page do you have in package.json?

5.8.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hungry-napier-i4tr5x?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

It is also shown in the example

**Comment by rtivital** [comment]
Mantine ScrollArea uses radix-ui, you can report this issue in radix-ui repo, nothing can be done on our side about this.

**Comment by hoangmissingcorner** [comment]
> Mantine ScrollArea uses radix-ui, you can report this issue in radix-ui repo, nothing can be done on our side about this.

Ok thanks, I was thinking the same
