### ISSUE TITLE
Image placeholder is not showing when the image is in loading state

### ISSUE THREAD

**Issue by rexwangcc** [mantinedev/mantine#3252]
### What package has an issue

@mantine/core

### Describe the bug

Previously in pre- mantine v5.6 versions, we have been relying on the `withPlaceholder` and `placeholder` properties to show a shimmer effects when the actual image is still being loaded from the CDN. Since we have migrated to v5.9, the behavior has changed and the placeholder is not showing up anymore. 

After some digging, it seems this behavior has been changed in 5.7 in https://github.com/mantinedev/mantine/commit/f9ea471890d806bb9fb458beb5f6afe75d548b48. Is there a specific reason to drastically change this behavior? If so, what's the best way to show a placeholder when the image is still being loaded? (there's no onload callback on `Image` so it seems we cannot use an external state to control `{isLoaded ? <Image /> : <Placeholder /> `, can we?)

Thank you very much!

### What version of @mantine/hooks page do you have in package.json?

^5.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Previous loading behavior produced race conditions and images were not loaded with ssr frameworks (Next.js) if image was loaded from cache (`onLoad` function was not called).

**Comment by rexwangcc** [comment]
> Previous loading behavior produced race conditions and images were not loaded with ssr frameworks (Next.js) if image was loaded from cache (`onLoad` function was not called).

So I guess the suggested way of displaying shimmer effects / skeletons of images is to completely move off from mantine Image and use something like `next/image` instead? (coincidentally we are using next, but haven't run into race conditions so far)

**Comment by rtivital** [comment]
If you use Next.js, there is no reason to use Mantine Image component

**Comment by rexwangcc** [comment]
We have migrated to next/image as suggested, thanks!
