### ISSUE TITLE
I am getting style ssr glitch in nextjs

### ISSUE THREAD

**Issue by kingRayhan** [mantinedev/mantine#3256]
### Discussed in https://github.com/mantinedev/mantine/discussions/3255

<div type='discussions-op-text'>

<sup>Originally posted by **kingRayhan** December 29, 2022</sup>

https://user-images.githubusercontent.com/7611746/209910589-ab67f6be-74c3-4ba5-8887-9b97b8a8e81c.mp4

I am working on a project, everything was going fantastic but all of a sudden I got this styling glitch. For recreating the issue I create another small mantine-next project but this project also catches the same style glitching problem.

Here is the reproduction project: https://github.com/kingRayhan/mantine-ecommerce-dashboard</div>

**Comment by rtivital** [comment]
Please do not duplicate your question both to issues and discussions.
