### ISSUE TITLE
Unable to pass styles or sx prop to HoverCard due to Typescript

### ISSUE THREAD

**Issue by amitsingh-007** [mantinedev/mantine#3257]
### What package has an issue

@mantine/core

### Describe the bug

Basically the title. Unable to pass `styles` or `sx` prop to Hovercard since TypeScript throws the following error:
```
Property 'styles' does not exist on type 'IntrinsicAttributes & HoverCardProps'.
```
Using `@ts-ignore` temporarily solves the issue. The styles does apply, its just that TypeScript throws the error.
Same thing with `sx` prop.

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/wandering-hooks-d71k9u?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

I think it's due to `HoverCardProps` extends `PopoverBaseProps` but `PopoverProps` has `styles` prop. Maybe we can extend `PopoverProps` or add missing props in `HoverCardProps`. If the fix is simple, I will be happy to raise a PR.

**Comment by rtivital** [comment]
Fixed in 5.10.1
