### ISSUE TITLE
When cookies are blocked, localstorage is not available

### ISSUE THREAD

**Issue by abdhass** [mantinedev/mantine#3259]
### What package has an issue

@mantine/core

### Describe the bug

Getting SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document when trying to use local storage
```  
const [user, setUser] = useLocalStorage({ key: 'haukUser', defaultValue: {} });
```
Reproduce by blocking all cookies (tested on Brave)

### What version of @mantine/hooks page do you have in package.json?

5.8.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/elastic-wu-xjkiqi

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

check if cookies or localstorage is accessbile?

**Comment by nrayburn-tech** [comment]
This error occurs when local storage access is denied by the browser settings. https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failed-to-read-localstorage-from-window-access-deni.

I'm not sure what else the `useLocalStorage` hook could do, except _maybe_ catch the error and fallback to the default value.
Updates would likely need to be made to the below functions (anywhere window.localStorage or window.sessionStorage is used).

https://github.com/mantinedev/mantine/blob/a891fe43c9b649ab4249727f6eeade27d3bdf3da/src/mantine-hooks/src/use-local-storage/create-storage.ts#L49-L60
https://github.com/mantinedev/mantine/blob/a891fe43c9b649ab4249727f6eeade27d3bdf3da/src/mantine-hooks/src/use-local-storage/create-storage.ts#L64-L82
https://github.com/mantinedev/mantine/blob/a891fe43c9b649ab4249727f6eeade27d3bdf3da/src/mantine-hooks/src/use-local-storage/create-storage.ts#L84-L88

**Comment by abdhass** [comment]
I went with this at the end: 
```
function isLocalStorageAvailable() {
  var test = 'test';
  try {
    localStorage.setItem(test, test);
    localStorage.removeItem(test);
    return true;
  } catch (e) {
    return false;
  }
}
```
The try catch will fail quietly at least.
