### ISSUE TITLE
ColorInput: withEyeDropper={false} not working

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#3265]
### What package has an issue

@mantine/core

### Describe the bug

ColorInput: withEyeDropper={false} not working
EyeDropper still visible on the right section.

### What version of @mantine/hooks page do you have in package.json?

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/young-water-0o3otw?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 5.10.0
