### ISSUE TITLE
CopyButton does not work on production build

### ISSUE THREAD

**Issue by gubi** [mantinedev/mantine#3271]
### What package has an issue

@mantine/core

### Describe the bug

Hi,
I simply followed the example given in the [official page](https://mantine.dev/core/copy-button/), but the CopyButton does not work **only with `build`**.

This is my code:
``` javascript
<CopyButton value="test" timeout={2000}>
  {({ copied, copy }) => (
    <Tooltip label={copied ? 'Copied!' : 'Click to copy'} withArrow position="right">
      <ActionIcon ml={5} sx={{ display: "inline", verticalAlign: "-1px", padding: "2px" }} color={copied ? 'teal' : 'grey'} onClick={copy}>
        {copied ? <IconClipboardCheck size={20} /> : <IconCopy size={20} />}
      </ActionIcon>
    </Tooltip>
  )}
</CopyButton>
```

### What version of @mantine/hooks page do you have in package.json?

5.8.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
It works correctly on documentation website production build. What exactly does not work?

**Comment by rtivital** [comment]
@gubi you are welcome to reopen the issue if you can provide more information

**Comment by Aldo111** [comment]
It doesn't work for me either in nextjs (in a client component) on the latest version of mantine hooks/core and nextjs v13.2

**Comment by Aldo111** [comment]
I came here to mention I had the same issue locally but then I found this https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined and it's possible the user was not in a secure context/isn't running https. I ran into it because locally I had my localhost mapped to another domain.
