### ISSUE TITLE
Skeleton in @mantine/core is not animating

### ISSUE THREAD

**Issue by spdrstar** [mantinedev/mantine#3272]
### What package has an issue

@mantine/core

### Describe the bug

`import {
  Skeleton,
  Box,
  Button,
  Stack,
  Card,
  Text,
  Image,
  UnstyledButtonProps,
  Group,
  Avatar,
  createStyles,
  BackgroundImage,
  Anchor,
  Center
} from "@mantine/core";
`

`<Skeleton animate={true} height={70} circle mb="xl" style={{marginTop:"20px"}} />`
`<Skeleton animate visable={true} height={8} mt={6} width="300px" radius="xl" />`
`<Skeleton height={8} mt={6} width="300px" radius="xl" />`
`<Skeleton animate height={8} mt={6} width="300px" radius="xl" />`

On implementation, animate={true}, animate, and doing nothing all don't correctly animate on a react app in Vite. 

### What version of @mantine/hooks page do you have in package.json?

^5.8.4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
It works correctly on codesandbox – https://codesandbox.io/s/modest-bassi-nckvou?file=/src/App.tsx
Provide a sandbox that demonstrates the issue.

**Comment by rtivital** [comment]
@spdrstar you are welcome to reopen the issue if you can provide a sandbox with reproduction
