### ISSUE TITLE
Flicker occurs when opening modal on top of overlay

### ISSUE THREAD

**Issue by sunknudsen** [mantinedev/mantine#3274]
### What package has an issue

@mantine/core

### Describe the bug

When opening modal on top of overlay, it appears overlay disappears for a brief moment after which it is replaced by modal overlay.

### What version of @mantine/hooks page do you have in package.json?

5.9.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/peaceful-galileo-65nbhk

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by cyantree** [comment]
This is still relevant in v6. Also the flickering has changed:
https://codesandbox.io/s/relaxed-water-qn9qwh?file=/src/App.tsx

**Comment by rtivital** [comment]
Fixed in 7.0, I can no longer reproduce the issue both when Modal is under and over the Overlay:

https://github.com/mantinedev/mantine/assets/10353856/89c31c4c-56f5-4f36-a651-f59dfc171d84

https://github.com/mantinedev/mantine/assets/10353856/b0d191c8-607d-4410-a1f2-2f3bab2b8e1f
