### ISSUE TITLE
ColorInput is not validating

### ISSUE THREAD

**Issue by m4rvr** [mantinedev/mantine#3280]
### What package has an issue

@mantine/form

### Describe the bug

I'm using the ColorInput with the zod schema validator but it doesn't validate the empty field.
Other fields like TextInput work fine.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem
https://stackblitz.com/edit/react-ts-mjdfd8?file=App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment]
I've created a fix for it in #4012. The issue is not related to `zod` but to the execution order of `onChange()` and `onBlur()`. Please see the PR for more details.
