### ISSUE TITLE
Invlaid types for Custom Component (MyComponentStylesNames)

### ISSUE THREAD

**Issue by maazakn** [mantinedev/mantine#3281]
### Link to the page where something nasty is located

https://mantine.dev/guides/custom-components/

### Exact quote of what is wrong

**MyComponent.styles.ts**
```
import { createStyles, MantineNumberSize } from '@mantine/core';

// Styles params are optional
export interface MyComponentStylesParams {
  radius: MantineNumberSize;
}
```

**MyComponent.tsx**
```
interface MyComponentProps extends DefaultProps<MyComponentStylesNames, MyComponentStylesParams> {
  radius?: MantineNumberSize;
}
```

There is a type mismatch in the **radius** type ( _syles.ts_ file) where it is marked as required while in  _MyComponent.tsx_ it is Optional

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
You are welcome to create a PR with a fix

**Comment by maazakn** [comment]
Hey Mantinedev/Mantine,

Is there any special instructions or process for raising PR?
