### ISSUE TITLE
Mantine removes the mobile filter button when used with Elastic's Search UI

### ISSUE THREAD

**Issue by 684efs3** [mantinedev/mantine#3282]
### What package has an issue

@mantine/core

### Describe the bug

If I install https://codesandbox.io/s/national-parks-example-kdyms (Elastic Search UI) on NextJS and add Mantine, then the mobile filter button will disappear. 

![image](https://user-images.githubusercontent.com/48864759/210659533-b232f63f-3260-401d-8d0a-cb262d05470a.png)

### What version of @mantine/hooks page do you have in package.json?

5.9.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/national-parks-example-kdyms?resolutionWidth=320&resolutionHeight=675

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
The sandbox that you've sent includes the button
<img width="382" alt="Снимок экрана 2023-01-05 в 10 57 13" src="https://user-images.githubusercontent.com/10353856/210720380-06d42d64-7238-446a-9580-4c169cdd0ed3.png">

**Comment by 684efs3** [comment]
I apologize - wrong sandbox. That one does not have Mantine installed. Here is the right one that I have reproduced: https://codesandbox.io/p/github/684efs3/mantine-search

**Comment by rtivital** [comment]
Your sandbox renders only an empty screen
<img width="1728" alt="Снимок экрана 2023-01-05 в 21 47 52" src="https://user-images.githubusercontent.com/10353856/210846627-ef89ff65-a5cd-437d-8613-f529f84d51e1.png">

**Comment by 684efs3** [comment]
Sorry try this: https://codesandbox.io/p/github/684efs3/mantine-search/draft/muddy-mountain?file=%2FREADME.md

**Comment by rtivital** [comment]
Your filters button has a hidden attribute. If you remove it, then the button will be visible. Elements with `hidden` attribute are hidden by normalize.css. If it is unwanted behavior, remove `withNormalizeCSS` prop from MantineProvider.
