### ISSUE TITLE
Tooltip not working on Dropzone

### ISSUE THREAD

**Issue by galto4ir** [mantinedev/mantine#3284]
### What package has an issue

@mantine/dropzone

### Describe the bug

```

<Tooltip label="bla bla">
      <TestComp />
</Tooltip>

const TestComp = React.forwardRef((props, ref) => {
     return <Dropzone ref={ref}>Upload Bla Bla</Dropzone>
})

```

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx
