### ISSUE TITLE
Modals manager doesn't handle closing modals properly

### ISSUE THREAD

**Issue by Njiallu** [mantinedev/mantine#3289]
### What package has an issue

@mantine/modals

### Describe the bug

When closing a modal which is not the one currently opened, causes weird behaviors.

for example when :
- open modal 1
- open modal 2
- close modal 1
Closes all the modals when it should only be removing modal 1 from the stack of the manager.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/crazy-lake-pi78fl?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I believe that the bit of code here assumes that we always close the last modal opened :
https://github.com/mantinedev/mantine/blob/db0551288e6fcccea5bd321c9255f61b1de61a6b/src/mantine-modals/src/reducer.ts#L35

Which I believe could be changed to something like this : 
```ts
    // ...
    case 'CLOSE': {
      const modals = state.modals.filter((m) => m.id !== action.payload)
      return {
        current: modals[modals.length - 1] || null,
        modals,
      };
    }
    // ...
```

**Comment by naofel1** [comment]
Same issue

**Comment by Njiallu** [comment]
Also I investigated and found that this :

https://github.com/mantinedev/mantine/blob/master/src/mantine-modals/src/ModalsProvider.tsx#L125

Tends to do funky stuff when called by an async function.
It checks for it's length but the length can change before being handled.
So an uniform behavior might be preferred here.
