### ISSUE TITLE
`allowFreeInput` not working

### ISSUE THREAD

**Issue by samthomson** [mantinedev/mantine#3302]
### What package has an issue

@mantine/dates

### Describe the bug

I expect to be able to add `allowFreeInput` to a `<DateRangePicker />` as per the [documentation](https://mantine.dev/dates/date-picker/#allow-free-input) but it doesn't seem to be a valid prop.

`  Property 'allowFreeInput' does not exist on type 'IntrinsicAttributes & DateRangePickerProps & RefAttributes<HTMLInputElement>'.ts(2322)`

I thought maybe the type got lost so tested modifying the type locally in the relevant node_modules file but that had no effect, the property doesn't seem to take effect.

### What version of @mantine/hooks page do you have in package.json?

^5.9.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/ancient-framework-09vjji?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
You've added `allowFreeInput`, not `allowSingleDateInRange`. DateRangePicker does not support `allowFreeInput` prop.

**Comment by samthomson** [comment]
My mistake, update the issue accordingly. 
Is this prop/feature on the road map? It would help my use case enormously.

**Comment by rtivital** [comment]
No, it is not planned to be supported in the future
