### ISSUE TITLE
Datepicker does not display value w/ initial useForm data

### ISSUE THREAD

**Issue by cwbuecheler** [mantinedev/mantine#3306]
### What package has an issue

@mantine/dates

### Describe the bug

When using Mantine datepickers with Mantine's custom useForm hook and providing an initial date as a value, they display the date properly as a placeholder, but don't display it as an actual value until something is chosen from the pop-up. This isn't a major issue (because the value IS recorded correctly when you submit the form, whether the datepicker's been used or not), but we detected it while doing some automated testing when we were unable to get the datepicker's value on initial load.

Code sandbox link below includes some regular inputs which DO display the form data as values.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/nice-easley-feiunw?file=/src/App.tsx:1355-1396

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Feels like lines `314` to `341` in `mantine/src/mantine-dates/src/components/DatePickerBase/DatePickerBase.tsx` where the input that gets displayed on the page is the issue, but I'm afraid I haven't had time to check into it further than that.

**Comment by rtivital** [comment]
DatePicker value must always be a Date object, you provide a string
https://codesandbox.io/s/strange-lake-1pwtik?file=/src/App.tsx

**Comment by cwbuecheler** [comment]
🤦‍♂️

Should've realized. Thanks for the quick response!
