### ISSUE TITLE
Validators dont work when used with validate as a function function

### ISSUE THREAD

**Issue by abdhass** [mantinedev/mantine#3308]
### What package has an issue

@mantine/form

### Describe the bug

`isInRange` doesnt work (throws error about a react component not being called)

```
validate: (values) => {
      if (active === 0) {
        return {
          qty: isInRange({ min: 1, max: maxTickets }, ''error msg'),
        };
      }
```

The isInRange is a closure which values should be passed to. Instead i got it working like this:

```
const isInMaxTicketRange = isInRange({ min: 1, max: maxTickets });

  const form = useForm({
    validate: (values) => {
      if (active === 0) {
        return {
          qty: isInMaxTicketRange(values.qty),
        };
      }
```

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Allow optional value param to be passed?

**Comment by rtivital** [comment]
Validators are designed to be used only in validation rules, not validation function
