### ISSUE TITLE
`GetInputProps['onChange']` is`any`; this would be more precise `({event: {currentTarget: any}}) => void` 

### ISSUE THREAD

**Issue by tianhuil** [mantinedev/mantine#3311]
### What package has an issue

@mantine/form

### Describe the bug

`GetInputProps['onChange']` is`any`.  We could make it more precise (e.g. `({event: {currentTarget: any}}) => void`)

See https://github.com/mantinedev/mantine/blob/567bcf289f72dec89ea016dc842b0ebb04dcacfb/src/mantine-form/src/types.ts#L62-L65

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

We could make it more precise (e.g. `({event: {currentTarget: any}}) => void`)

**Comment by rtivital** [comment]
That will be incorrect, `onChange` can be used with function that can accept any argument.
