### ISSUE TITLE
[ColorInput] onChangeEnd event 's params is always #000000

### ISSUE THREAD

**Issue by Valar103769** [mantinedev/mantine#3313]
### What package has an issue

@mantine/core

### Describe the bug

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/36926073/211141529-421d161e-c8ed-4b58-8d47-b4ad6d297458.png">

### What version of @mantine/hooks page do you have in package.json?

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://stackblitz.com/edit/react-ts-jwlq3k?file=App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
ColorInput and ColoPicker components support only hex, rgb and hsl formats. You set swatches to a string that does not have a correct format.

https://codesandbox.io/s/intelligent-lena-891wqs?file=/src/App.tsx

**Comment by Valar103769** [comment]
Can it be used as a feature request? Need to support color keywords, just like onChange, okay?

**Comment by rtivital** [comment]
It is not planned to support color keywords – it will require storing all colors in component, which will increase its bundle size significantly.
