### ISSUE TITLE
Datepicker should have month/year selection

### ISSUE THREAD

**Issue by tracker1** [mantinedev/mantine#332]
Datepicker title click should switch to a month picker, then the month picker a year spinner/picker.  The pattern was first really codified in the MS Ajax Toolkit, probably the only thing I liked in that framework.

The issue is that someone will use this library, and then use it for something like a date of birth field.

**Comment by gregorybellencontre** [comment]
Hello @rtivital 
Just for information : I don't find any option to turn the date picker into a month picker.
You were talking about the `withSelect` prop, but it seems it doesn't exist anymore.
I checked the releases notes, but I didn't find any information about it.

**Comment by gregorybellencontre** [comment]
Ok. And there's no other solution for month picking in Mantine ?

**Comment by elarens** [comment]
> 

Vitaly, is there any plan to add monthly picker functionality in foreseeable future? It's quite useful

**Comment by geoffreyhale** [comment]
Our team would love a MonthPicker

**Comment by Nzent** [comment]
Also, add a year picker too if you have time 👍

**Comment by barissayil** [comment]
Hi @rtivital I think adding `MonthPicker` and `YearPicker` which are slightly modified versions of `DatePicker` would be perfect. Do you think we could have this in the next few months, or if not at a later time?

**Comment by rtivital** [comment]
https://v6.mantine.dev/changelog/6-0-0/#updated-mantinedates-package

**Comment by Jshihs** [comment]
Hi rtivital,
how can i use mantinedates package (**month range picker**, single month allowed)  in dash plotly (python)?

**Comment by Jshihs** [comment]
hi rtivital,
thanks for quick reply. I am quite a newbie that I am not sure that i understand how to make it work in my coding.  Here below is a brief coding and that will shows dates in selection. Kindly advise how to have only month shown as **Mantine MonthPicker**  work in my python coding. thank you

import dash_bootstrap_components as dbc
import dash_mantine_components as dmc
from datetime import date, datetime

layout = dbc.Row([
                   dbc.Col([
                                  dmc.DatePicker(
                                      id='start_date',
                                      label='Start date:',
                                      value=datetime.now().date().replace(month=1,day=1),
                                  ),
                                  ],
                                  width={'size':4,}),  
                              dbc.Col([
                                  dmc.DatePicker(
                                      id='end_date',
                                      label='End date:',
                                      value=datetime.now().date().replace(month=12,day=31),
                                  ),
                                  ],
                                  width={'size':4,}), 
      ])
