### ISSUE TITLE
[TS]: Select and MultiSelect onChange event has not current typescript declare

### ISSUE THREAD

**Issue by Valar103769** [mantinedev/mantine#3321]
### What package has an issue

@mantine/core

### Describe the bug

 if not pass clearable prop, the value not be null | undefined, but typescript say it maybe null 

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
The value might be null when user clicks the same option and it is allowed to deselect, there are no plans to change that.

**Comment by Valar103769** [comment]
> The value might be null when user clicks the same option and it is allowed to deselect, there are no plans to change that.
I see, however, it seems that multi-select components do not support click cancel
