### ISSUE TITLE
SegmentedControl's active value size is calculated incorrectly

### ISSUE THREAD

**Issue by mattersj** [mantinedev/mantine#3330]
### What package has an issue

@mantine/core

### Describe the bug

1. Create a Modal **with transition** that uses `transform` under the hood. Let's say, `scale`.
2. Put `SegmentedControl` component inside of this modal.
3. Open the modal and observe that active value height (and sometimes width) is calculated incorrectly. The result depends on the selected transition in the first step so sometimes both height and width are 0 and sometimes width is correct but height is a bit larger than expected.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/28510814/211427083-3e6e0b88-6415-4854-8b8e-c73066cdf2d1.png">

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/reverent-jones-dq0icp?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

I believe the possible fix might be to detect any parent transition, wait till the `transitionend` (or `animationend` if necessary) and recalculate the size one more time.
I haven't really gone deep into the code so I'm not sure if this solution would be appropriate but from what I'm aware of it should kind of be.
Another thing to consider here: a user may want to implement some custom transitions around the modal or any parent container that contains `SegmentedControl` in there, so this should not only work with built-in `Transition` component.

Another fix is to change the way size is calculated but this one requires more investigation.

### Related Issues
#585
#2994

**Comment by rtivital** [comment]
I doubt that it is possible to fix it on library level. You can fix this issue on your side by rerendering SegmentedControl once animation completes – https://codesandbox.io/s/wandering-tdd-7f9o4k?file=/src/App.tsx

**Comment by rtivital** [comment]
It is not planned to fix this on library level

**Comment by heloineto** [comment]
I haven't looked in the code, but is it possible that a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) could help fix this?

**Comment by FenderStrat85** [comment]
Just a heads up, this fix does not work in version 7 of Matine => https://codesandbox.io/s/wandering-tdd-7f9o4k?file=/src/App.tsx

No value is highlighted in the SegmentedControl, until you click on a value that is not the default or first value (depending on how you have it set up). No worries that there's not plan to fix it on a library level, just wanted to give a heads up to those using v7.
![Uploading Screenshot 2024-02-07 at 16.49.59.png…]()
