### ISSUE TITLE
invalid HTML output with accordion

### ISSUE THREAD

**Issue by birdcoates** [mantinedev/mantine#3331]
### What package has an issue

@mantine/core

### Describe the bug

I don't know if this is even a big deal but the accordion component outputs divs nested in the button element which is invalid HTML.  

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Can these divs be changed to span elements or some other permitted element?

**Comment by rtivital** [comment]
Fixed in 6.0
