### ISSUE TITLE
CloseButton: Expression produces a union type that is too complex to represent

### ISSUE THREAD

**Issue by jannikbuschke** [mantinedev/mantine#3332]
### What package has an issue

@mantine/core

### Describe the bug

Currently I get the following error. I tried different prop combinations but did not found any working combination
![image](https://user-images.githubusercontent.com/5894881/211554247-08f17641-cf95-4b03-a641-87eb4a13449f.png)

### What version of @mantine/hooks page do you have in package.json?

mantine: 5.10.0

typescript: 4.9.4

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
I was unable to reproduce that, please provide a sandbox that replicates the issue
https://codesandbox.io/s/flamboyant-james-ijm832?file=/src/App.tsx

**Comment by rtivital** [comment]
@jannikbuschke you are welcome to reopen the issue if you can provide a reproduction
