### ISSUE TITLE
[Grid] Grid render an empty div unexpected

### ISSUE THREAD

**Issue by Valar103769** [mantinedev/mantine#3333]
### What package has an issue

@mantine/core

### Describe the bug

```jsx
 <Grid>
          <Grid.Col span={3}>
            <DateRange
              size="xs"
              field={
                Object.prototype.hasOwnProperty.call(props.form, 'date_range')
                  ? 'compare_dates'
                  : 'date_range'
              }
              form={form}
              value={form.getInputProps('date_range').value}
              onChange={(values) => form.setFieldValue('date_range', values)}
            ></DateRange>
          </Grid.Col>

          {visibleFilters.map((item) => {
            const cmp =
              item.data === 'api' ? (
                <CustomSelect
                  size="xs"
                  label={item.title}
                  {...form.getInputProps(item.name)}
                  name={item.name}
                  mode={form.getInputProps(`${item.name}__mode`)}
                />
              ) : item.data !== 'api' && item.type === 'select' ? (
                <Select
                  size="xs"
                  label={item.title}
                  {...form.getInputProps(item.name)}
                  data={Object.keys(item.data).map((key) => ({
                    label: key,
                    value: item.data[key],
                  }))}
                />
              ) : item.data !== 'api' &&
                (item.type === 'multi_select' || item.type === 'ad_type') ? (
                <MultiSelect
                  size="xs"
                  label={item.title}
                  {...form.getInputProps(item.name)}
                  data={Object.keys(item.data).map((key) => ({
                    label: key,
                    value: item.data[key],
                  }))}
                />
              ) : item.name === 'game_id' ? (
                <MultiSelect
                  size="xs"
                  clearable
                  label="游戏"
                  data={games || []}
                  itemComponent={SelectItem}
                  {...form.getInputProps(item.name)}
                ></MultiSelect>
              ) : null

            return (
              <Grid.Col span={3} key={item.title}>
                {cmp}
              </Grid.Col>
            )
          })}
        </Grid> 
```

<img width="609" alt="image" src="https://user-images.githubusercontent.com/36926073/211579534-6cb4cbd0-388f-47e5-964d-898943936862.png">

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/36926073/211579582-54b300b7-a4d0-4ae7-a704-1ed366c212b4.png">

and Flex is work well 

### What version of @mantine/hooks page do you have in package.json?

^5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/nice-yonath-kytm9v?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please describe your issue and provide a sandbox with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example

It is not clear from the code what the issue is.

**Comment by Valar103769** [comment]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/36926073/211595620-d830ac2e-4975-431d-a5a6-151c681b530c.png">

My array has length 3, but it renders four divs

**Comment by rtivital** [comment]
Please provide a sandbox with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example
Minimal reproducible example must include only code that is related to the issue

**Comment by Valar103769** [comment]
https://codesandbox.io/s/nice-yonath-kytm9v?file=/src/App.tsx
hello, @rtivital   changed a few. This should be the minimum

**Comment by rtivital** [comment]
And what is the issue here? You always render 3 columns

**Comment by Valar103769** [comment]
As I understand it,
If the number of elements in the last row is less than cols, it should be arranged from left to right; Because in the first row, the number of elements is less than cols, so it should be left to right;

**Comment by rtivital** [comment]
https://codesandbox.io/s/priceless-rumple-tyi74k?file=/src/App.tsx

**Comment by Valar103769** [comment]
thanks
