### ISSUE TITLE
Error in SelectItem type for <Select> component

### ISSUE THREAD

**Issue by LarsEjaas** [mantinedev/mantine#3334]
### What package has an issue

@mantine/core

### Describe the bug

The `SelectItem` type for the `<Select>` component has the following definition:

```
export interface SelectItem {
    value: string;
    label?: string;
    disabled?: boolean;
    group?: string;
    [key: string]: any;
}
```
But if I omit the label on one of the items the component throws an error.

Unfortunately I get an empty error thrown:

```
The above error occurred in the <@mantine/core/Select> component:
```
So not much more to work with here.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Make `label` required in `SelectItem`.

**Comment by rtivital** [comment]
Please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by rtivital** [comment]
@LarsEjaas you are welcome to reopen the issue if you can provide a sandbox with reproduction

**Comment by LarsEjaas** [comment]
I am sorry for never replying. We ended up taking a deeper look at the implementation in our app and discovered a flaw on our side causing the issue.
