### ISSUE TITLE
Stepper.Step "allowStepSelect" props not working

### ISSUE THREAD

**Issue by AnthonyBettollo** [mantinedev/mantine#3335]
### What package has an issue

@mantine/core

### Describe the bug

allowStepSelect is not working on Mantine 5.10 (seems to be the same problem on the website doc)

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/stepper/#allow-step-select

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Was working well on previous versions

**Comment by rtivital** [comment]
Fixed in 5.10.1, thanks @rmzNadir!
