### ISSUE TITLE
Disabled Date Bug on RangeCalendar component

### ISSUE THREAD

**Issue by Nattachai12** [mantinedev/mantine#3339]
### What package has an issue

@mantine/dates

### Describe the bug

When I use `excludeDate` props together with `hideOutsideDates` props, it will disabled the date outside of the current month wich is not a desired experience. Below is the explanation.

The calendar disabled date 26-28. It can make user think the last day he/she can pick is Jan 1st. 
![Screenshot 2023-01-10 at 4 15 00 PM](https://user-images.githubusercontent.com/90889459/211689064-e13a9b9c-782e-44ee-8849-15ffe52ceedb.png)

However, If we click on previous month button then we will see date 29-31 Dec are available.

![Screenshot 2023-01-10 at 4 15 07 PM](https://user-images.githubusercontent.com/90889459/211689322-1d449b89-5a05-4c84-bb09-428eb31ae38d.png)

I found out that version 5.0 and above have this problem. Prior versions don't have this problem.

Here is the code
import { useState } from "react";
import { RangeCalendar } from '@mantine/dates';
import dayjs from "dayjs";

export default function App() {
  const [value, setValue] = useState([
    new Date(2021, 11, 1),
    new Date(2021, 11, 5),
  ]);

  return <RangeCalendar paginateBy={1} amountOfMonths={2} hideOutsideDates value={value} onChange={setValue} excludeDate={(date) => dayjs().subtract(13, 'days').isAfter(dayjs(date))}/>;
}

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by kagannikita** [comment]
if you do not take into account the year, then you can disable dates through styles with dayClassName or dayStyles

**Comment by rtivital** [comment]
Fixed in 6.0
