### ISSUE TITLE
useForm return form is not a stable ref

### ISSUE THREAD

**Issue by Valar103769** [mantinedev/mantine#3343]
### What package has an issue

@mantine/form

### Describe the bug

```jsx
cnst form = useForm()

useEffect(() => {
    form.setValues(data)
  }, [form])
```
cause below error

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/36926073/211789453-490ea9f8-df05-4bad-ad1a-714959f716e9.png">

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is intended, you do not need to subscribe to `form` variable updated in useEffect dependencies. There are no plans of changing this.
