### ISSUE TITLE
Switch component's height is incorrect

### ISSUE THREAD

**Issue by pengtikui** [mantinedev/mantine#3344]
### What package has an issue

@mantine/core

### Describe the bug

<img width="814" alt="image" src="https://user-images.githubusercontent.com/12391445/211841973-69e4b287-5776-4e4f-acb1-12114e30bfc8.png">

This screenshot from official docs.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 5.10.1
