### ISSUE TITLE
FOUC with Mantine 5.10 and NextJs 13

### ISSUE THREAD

**Issue by jopfre** [mantinedev/mantine#3346]
### What package has an issue

@mantine/core

### Describe the bug

I was getting a FOUC with mantine 5.10 but then I realised that @mantine/next was only on 5.9. 

### What version of @mantine/hooks page do you have in package.json?

5.10

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Upgrading mantine/next fixed the issue. I am using yarn and the problem maybe related to dependencies in that mantine 5.10 needs 5.10 mantine/next. Just a guess.

**Comment by jakub-sekula** [comment]
Having the same issue on Next 13.1.2 and Mantine 5.10. Paper elements are unstyled for a moment after each reload even on static pages from next-build.

**Comment by takufunkai** [comment]
Upgrading @mantine/next to the latest version worked for me
`yarn upgrade @mantine/next --latest`

**Comment by rtivital** [comment]
You can find a working example with latest version of next.js and mantine here – https://github.com/mantinedev/mantine-next-template

**Comment by premier213** [comment]
i have this problem, how to resolve?
```javascript
"use client";
import createCache from "@emotion/cache";
import { CacheProvider } from "@emotion/react";
import { MantineProvider } from "@mantine/core";
import { useServerInsertedHTML } from "next/navigation";
import { useState } from "react";

import { rtlCache, theme } from "../../shared";
import { AppProvider } from "./app-provider";

export function ThemeProvider({ children }: { children: React.ReactNode }) {
  const [cache] = useState(() => {
    const cache = createCache({ key: "css" });

    return cache;
  });

  useServerInsertedHTML(() => (
    <style
      data-emotion={`${cache.key} ${Object.keys(cache.inserted).join(" ")}`}
      dangerouslySetInnerHTML={{
        __html: Object.values(cache.inserted).join(" "),
      }}
    />
  ));

  return (
    <div dir="rtl">
      <CacheProvider value={rtlCache}>
        <MantineProvider
          withGlobalStyles
          withNormalizeCSS
          emotionCache={rtlCache}
          theme={theme}
        >
          <AppProvider>{children}</AppProvider>
        </MantineProvider>
      </CacheProvider>
    </div>
  );
}
```

**Comment by dragorwyin** [comment]
Same issue here, FOUC on first render in dark mode.

**Comment by sinafath** [comment]
same problem

**Comment by johnnyrwest** [comment]
ditto! FUOC on first render in dark mode.

**Comment by Elko-Lemiso** [comment]
heyo, same issue here, next 13.3.0

**Comment by FullstackJack** [comment]
For me, I think it's finally fixed by `defaultColorScheme="dark" on both `ColorSchemeScript` and `MantineProvider`.

```
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body className={inter.className}>
        <MantineProvider defaultColorScheme="dark" theme={theme}>
          <main className="dark text-foreground bg-background">{children}</main>
        </MantineProvider>
      </body>
    </html>
  );
}

**Comment by baonhat27** [comment]
@FullstackJack  it works, thank you
