### ISSUE TITLE
Select filter function does not work as stated in docs

### ISSUE THREAD

**Issue by mlarcher** [mantinedev/mantine#3353]
### Link to the page where something nasty is located

https://mantine.dev/core/select/

### Exact quote of what is wrong

doc give an example for the `filter` function in the `Select` component that looks like
```js 
 filter={(value, item) =>
        item.label.toLowerCase().includes(value.toLowerCase().trim()) ||
        item.description.toLowerCase().includes(value.toLowerCase().trim())
      }
```
But when I set a filter function, it receives 3 parameters (in code: `filter(value: string, selected: boolean, item: SelectItem): boolean;`).

I believe doc should be updated to reflect this

Note: we can find a correct version in the MultiSelect documentation on https://mantine.dev/core/multi-select/

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
Filter function is called with 2 arguments as described in documentation – https://github.com/mantinedev/mantine/blob/rem/src/mantine-core/src/Select/filter-data/filter-data.ts#L47

**Comment by rtivital** [comment]
Same on codesandbox, filter function is called with 2 arguments – https://codesandbox.io/s/empty-microservice-hgpfd9?file=/src/App.tsx

**Comment by mlarcher** [comment]
My bad, I got confused between Select and MultiSelect, assuming both were handling filters the same way. Sorry about that and thanks for the quick reply. Keep up the good work !
