### ISSUE TITLE
[use-set-state] setState function  is not stable ref

### ISSUE THREAD

**Issue by Valar103769** [mantinedev/mantine#3357]
### What package has an issue

@mantine/hooks

### Describe the bug

```jsx
import { useWhyDidYouUpdate } from 'ahooks'

  const [pagination, setPagination] = useSetState({
    page: 1,
    perPage: 10,
    total: 0,
  })

 <MyTable
          pagination={pagination}
          onPaginationChange={setPagination}
        />
```

```jsx
const MyTable = ({pagination,onPaginationChange})=>{

  useWhyDidYouUpdate('MyTable', {
    columns,
    data,
    loading,
    title,
    pagination,
    onPaginationChange,
    defaultColDef: _defaultColDef,
    ...props,
  })
// ... 
}
```

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

<img width="704" alt="image" src="https://user-images.githubusercontent.com/36926073/212234968-979b9ecf-98d7-40ee-bb14-02e9d8b1ef0f.png">

**Comment by rtivital** [comment]
Fixed in 5.10.1
