### ISSUE TITLE
Tooltips are not rendered in production build

### ISSUE THREAD

**Issue by DiOnFire** [mantinedev/mantine#3362]
### What package has an issue

@mantine/core

### Describe the bug

Tooltips are rendered without problems in dev mode, but when assembled in production using Vite, they completely stop working.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Please provide a repository with minimal reproduction

**Comment by DiOnFire** [comment]
upd: solved it. It was necessary to create a new project from the mantine-vite sample and move all the project files there.

**Comment by jansedlon** [comment]
I've got this issue as well in a well settled project. I'll try to make a reproducible repo

**Comment by jansedlon** [comment]
Okay, I tried almost everything imaginable, but what fixed it was `rm -rf ./node_modules ./pnpm-lock.yaml` and `pnpm i` 🤷‍♂️

**Comment by DiOnFire** [comment]
Magic
