### ISSUE TITLE
All items in Select component re-render on item hover

### ISSUE THREAD

**Issue by art-litv** [mantinedev/mantine#3367]
### What package has an issue

@mantine/core

### Describe the bug

All items in the **Select** component re-render on item hover. In especially large lists it noticeably worsens experience. I could solve this issue by creating a custom item and passing it to **itemComponent** prop. The custom item doesn't use onMouseEnter from props and uses css for hover styling instead

### What version of @mantine/hooks page do you have in package.json?

^5.10.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
It is expected behavior, hovered index is used for keyboard support – up and down arrows. It is not planned to change this behavior any time soon.

**Comment by art-litv** [comment]
@rtivital The solution above did not affect up/down arrows usability for me. Other than that, the list not no longer "staggers" on simultaneous scroll and hover.

Possibly, is it used for something else related to keyboard support? 

I can provide a Code Sandbox if needed

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
