### ISSUE TITLE
404 Page "from a link on the Mantine website"

### ISSUE THREAD

**Issue by Proyas21** [mantinedev/mantine#3371]
Goto: [lead-grid](https://ui.mantine.dev/category/grids#lead-grid)

Check out the **Component dependencies**
![image](https://user-images.githubusercontent.com/37238596/212538821-68be9c1f-b80f-4626-90d5-b958728bcfc9.png)

The last one here takes me to [https://mantine.dev/core/](https://mantine.dev/core/) which told me to create a issue here

**Comment by rtivital** [comment]
Thanks for reporting, the issue will be fixed in one of next releases
