### ISSUE TITLE
Switch out deprecated `@floating-ui/react-dom-interactions` for `@floating-ui/react`

### ISSUE THREAD

**Issue by mcmxcdev** [mantinedev/mantine#3376]
### What package has an issue

@mantine/core

### Describe the bug

`pnpm` reports the following when running install: ` WARN  deprecated @floating-ui/react-dom-interactions@0.10.3: Package renamed to @floating-ui/react`

You can also see the deprecation message on: https://www.npmjs.com/package/@floating-ui/react-dom-interactions

### What version of @mantine/hooks page do you have in package.json?

^5.10.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 5.10.3
