### ISSUE TITLE
Modal push content to the left 

### ISSUE THREAD

**Issue by onehalla** [mantinedev/mantine#3377]
### What package has an issue

@mantine/core

## Issue

I encountered an issue when opening the modal where the page content was pushed to the left. This caused some inconvenience and made it difficult to interact with the page.

## Solution

I found a solution to this problem by adding the following code to my CSS file:
```css
body {
  --removed-scroll-width: 0 !important;
}
```
## Future improvement
However, I believe that this issue could be prevented in the future by implementing a scroll-width property within the modal component. This would give users more control over the modal's behavior and enhance the overall user experience.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Fixed in 6.0, see https://mantine.dev/core/modal/#fixed-elements-offset
