### ISSUE TITLE
Datepicker dropdown not fully visible

### ISSUE THREAD

**Issue by aaly00** [mantinedev/mantine#3380]
### What package has an issue

@mantine/core
@mantine/dates

### Describe the bug

When a date drop down is inside a Card component, the drop down is not full visible on v5.10.0
<img width="534" alt="image" src="https://user-images.githubusercontent.com/11652379/212710653-85c573c7-0594-4c0d-8b97-58f0b095a598.png">

see stackblitz https://stackblitz.com/edit/react-ts-c5of6u?file=App.tsx

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://stackblitz.com/edit/react-ts-c5of6u?file=App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Set withinPortal – https://stackblitz.com/edit/react-ts-jyp9nh?file=App.tsx

**Comment by aaly00** [comment]
Thanks!!

**Comment by moontum** [comment]
Just a reminder for anyone who comes across this question:

in `v6.0.0` now, you should use `withinPortal` in `DatePickerInput` and `DateTimePicker` like:

```
<DateTimePicker popoverProps={{ withinPortal: true }}/>
```
