### ISSUE TITLE
Form field errors object not populating when validator returns a string.

### ISSUE THREAD

**Issue by raparri01** [mantinedev/mantine#3381]
### What package has an issue

@mantine/form

### Describe the bug

Current Behavior:
When a validator field, specified in the `useForm` config returns a string representing an error message, the form's error object does not have the corresponding error.

Expected Behavior:
When an input is provided that causes a validator to return a string, the form's error state should reflect the failed validator.

Screenshot:
![image](https://user-images.githubusercontent.com/32496022/212725396-fd6483b9-4f10-4b6c-89c8-1bcb84ece15c.png)

### What version of @mantine/hooks page do you have in package.json?

5.10

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/frosty-euclid-7r8bwh?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Base on your sandbox it works as expected. If you want to perform live validation set corresponding properties on useForm – https://codesandbox.io/s/unruffled-villani-lrj8dn
