### ISSUE TITLE
Hovering over placeholder shows default cursor instead of text

### ISSUE THREAD

**Issue by imranbarbhuiya** [mantinedev/mantine#3382]
### What package has an issue

@mantine/tiptap

### Describe the bug

Hovering over placeholder shows the default cursor instead of the text

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

add `cursor: pointer` to placeholder class

**Comment by rtivital** [comment]
Fixed in 5.10.1
