### ISSUE TITLE
[Select]: Custom item component is not emit inner click event

### ISSUE THREAD

**Issue by Valar103769** [mantinedev/mantine#3384]
### What package has an issue

@mantine/core

### Describe the bug

the ActionIcon 's onClick event is not emit , it is a bug ? 

```jsx
const SelectItem = forwardRef<HTMLDivElement, any>(
    ({ label, id, ...others }: any, ref) => (
      <div ref={ref} {...others}>
        <Group noWrap position="apart">
          <Text size="sm">{label}</Text>
          <ActionIcon
            color={"red"}
            onClick={(event) => {
              event.stopPropagation();
              console.log("delete", event);
              setText("delete");
            }}
          >
            <IconTrash size={14} />
          </ActionIcon>
        </Group>
      </div>
    )
  );
```
https://codesandbox.io/s/aged-field-wqq32v?file=/src/App.tsx

### What version of @mantine/hooks page do you have in package.json?

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/aged-field-wqq32v?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It works as expected. Select items cannot include any interactive elements – it will be an accessibility violation. We do not support use cases that are not accessible.
