### ISSUE TITLE
[DatePicker]&[DateInput] allowFreeInput shows wrong date in popup when controlled

### ISSUE THREAD

**Issue by hunterwilhelm** [mantinedev/mantine#3385]
### What package has an issue

@mantine/dates

### Describe the bug

When using a controlled `allowFreeInput` in `DatePicker` the dropdown date selector shows a different date many times than what the input is showing.

To reproduce the bug:
1. Select a date
2. Click one of the `Button`s to change the date
3. Open the date picker, the date in the popup will often be wrong.

This bug is appearing in 5.10.1.
And also in `mantine-dates-6` https://codesandbox.io/s/mantine-report-controlled-datepicker-v6-bug-ghost-date-lr68zm

https://user-images.githubusercontent.com/71348224/213018445-1dd7db74-d2bc-4761-9ec0-81047cc8f7a5.mov

### What version of @mantine/hooks page do you have in package.json?

5.10.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-report-controlled-datepicker-bug-ghost-date-1e6bs0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by hunterwilhelm** [comment]
Following up on this. Is this going to be fixed in 6.0?

**Comment by rtivital** [comment]
You can install 6.0 alpha version and check – https://v6.mantine.dev/changelog/6-0-0/

**Comment by hunterwilhelm** [comment]
The bug is still present in version `6.0.0-alpha.0` https://replit.com/@yeskindofday/mantine-report-controlled-DatePicker-600-alpha0-bug-ghos

**Comment by rtivital** [comment]
I've fixed the issue in v6 for DateInput component (worked fine in DatePickerInput), it will be available with next alpha release

**Comment by hunterwilhelm** [comment]
Thank you, it is now live in our production code. 🙏
