### ISSUE TITLE
Does MultiSelect support highlight item and allowDeselect recently or v6?

### ISSUE THREAD

**Issue by Valar103769** [mantinedev/mantine#3386]
### What package has an issue

@mantine/core

### Describe the bug

the  mui  and  antd  all  support  this  feature   
i think  it  just  remove  array.filter  in filterData fn and add highlight selectItem style 
then it is ok

 i very  very  need  this feature ,please  conside  it 
### What version of @mantine/hooks page do you have in package.json?

v5

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please use GitHub issues only to report issues. To ask questions, use GitHub discussions or Discord.
