### ISSUE TITLE
RTL feature for Navigation progress

### ISSUE THREAD

**Issue by majeeddl** [mantinedev/mantine#3390]
### Discussed in https://github.com/mantinedev/mantine/discussions/3389

<div type='discussions-op-text'>

<sup>Originally posted by **majeeddl** January 18, 2023</sup>
I need the possibility of setting rtl for navigation progress component</div>

**Comment by rtivital** [comment]
Please do not duplicate your feature requests to issues. Use issues only to report bugs.
