### ISSUE TITLE
Styles in components in global MantineProvider should be Partial

### ISSUE THREAD

**Issue by h2dthien** [mantinedev/mantine#3398]
### Link to the page where something nasty is located

https://mantine.dev/styles/styles-api/#styles-api-with-mantineprovider

### Exact quote of what is wrong

In the code example of the linked section:

```
// Subscribe to theme and component params
styles: (theme, params: ButtonStylesParams) => ({
```

This should instead be:

```
// Subscribe to theme and component params
styles: (theme, params: Partial<ButtonStylesParams>) => ({
```

Because unlike the "styles" prop of a specific component, the "styles" prop at global is partial. I also think this is better emphasised as a sentence outside of the code example 🤔 

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
> Because unlike the "styles" prop of a specific component, the "styles" prop at global is partial

Why? Global styles work the same way as `styles` prop

**Comment by h2dthien** [comment]
One minute, let me prepare an example 🙏

**Comment by h2dthien** [comment]
@rtivital , sorry, my bad, `styles.params` works the same whether it's `Button.styles` or `MantineProvider.theme.components.Button.styles` 🙏 

However, in both cases, they are partial objects, not full. They do have keys, but the values are optional. For example, if we log the `params` object in both cases:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/122243953/213676772-42d2a97e-c44e-46e7-b796-051542ea0b2d.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/122243953/213676808-415ce616-d023-43b7-9455-e6ecb29f8a3e.png">

We will see it doesn't have values for all properties. This is expected, but contrast with the typing (`params: ButtonStylesParams`):

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/122243953/213676666-499f7fd0-e205-4ee1-ac22-f5d4341f71c6.png">

<img width="486" alt="image" src="https://user-images.githubusercontent.com/122243953/213677172-fc9457a7-a5a7-440c-b0f2-01c9b66d5e19.png">

So I think the problem here lies in the typing of `ButtonStylesParams` or `params`?

For example, `Button.styles.params.color.ToUpperCase()` would yield a run-time error, but TypeScript can't catch it even in strict mode.

**Comment by rtivital** [comment]
The issue is with `ButtonStylesParams`, styles work as expected. Mantine does not use strict mode – it is not important for internal codebase.

**Comment by h2dthien** [comment]
Oh I see, thanks @rtivital !

**Comment by h2dthien** [comment]
Btw do you want to put it somewhere on the docs that Mantine's typing is not strict typing? I could help if you think it's useful!

**Comment by rtivital** [comment]
Mantine types should be compatible with strict mode. You are welcome to change ButtonStylesParams and other exported *StylesParams type to work correctly in strict mode.
