### ISSUE TITLE
TimeInput is missing readonly property

### ISSUE THREAD

**Issue by kollster** [mantinedev/mantine#3400]
### What package has an issue

@mantine/dates

### Describe the bug

The ```TimeInput``` component is missing the ```readonly``` property.

Most other Mantine input components have a property named ```readonly``` which sets a given component in a state where the user cannot input data, but without making it grayed out as with ```disabled```.

![image](https://user-images.githubusercontent.com/3436707/213681923-b3de5e4f-d76d-4ab7-bc01-2161e2b9d054.png)

Is it possible to add the ```readonly``` property to ```TimeInput```?

Keep up the good work with this great library 👍

### What version of @mantine/hooks page do you have in package.json?

5.10.1

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 6.0
