### ISSUE TITLE
Replace @tabler/icons with @tabler/icons-react

### ISSUE THREAD

**Issue by nonam4** [mantinedev/mantine#3415]
### What package has an issue

@mantine/tiptap

### Describe the bug

As @tabler/icons is not working with react anymore you must replace it with the new 2.0.0 [released package](https://github.com/tabler/tabler-icons/releases/tag/v2.0.0)

### What version of @mantine/hooks page do you have in package.json?

5.10.1

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by gfazioli** [comment]
@rtivital 
another way is replace `@tabler/icons` with `@tabler/icons-react` which start from `2.0.0`
of course, we should change also any `import { Icon...} from "@tabler/icons` in `import { Icon...} from "@tabler/icons-react`
I did it and it worked fine for me 👍

**Comment by israelins85** [comment]
Please update the matine exemples.

**Comment by rtivital** [comment]
All demos will be updated with 6.0 release.

**Comment by rtivital** [comment]
Fixed in 6.0
