### ISSUE TITLE
Why useNotifications().showNotification() not memoized?

### ISSUE THREAD

**Issue by nmedvedev1** [mantinedev/mantine#342]
@mantine/notifications  3.0.5

Following code cause infinity rerenders loop:
```typescript
const notifications = useNotifications();
const [error] = useState("some error text");

useEffect(() => {
 if (error) {
   notifications.showNotification({title: error});
 }
}, [notifications, error]);
```

Methods of useNotifications() hook does not memoized, why?

**Comment by lmachens** [comment]
Same issue here. I have a use-case in which I have to use `notifications` in `useEffect` (show error notifications coming from Remix `useActionData`).

What's the issue of memorizing `showNotification`, `updateNotification` and `updateNotification` in https://github.com/mantinedev/mantine/blob/master/src/mantine-notifications/src/NotificationsProvider/use-notifications-state/use-notifications-state.ts?

**Comment by rtivital** [comment]
Why it should be memoized?

**Comment by lmachens** [comment]
To fix the issue described by Meyzz.
I think it's error-prone, because I wouldn't expect that it leads to infinite re-renders if it's used in `useEffect` as dependency.
If this is not possible, I guess a note in the docs would be good.

**Comment by frec-hansen** [comment]
We also run into issue regarding the infinite loop as well. We have apollo client that uses the `useNotification` hook to show notification when an error was received. The hook exposes a showNotification method which would change when a notification is shown so the graphql client would get reinitialized every time a notification was shown, which would blow away the cache and trigger all queries, which would trigger errors (if the issue with a query is persistent) and would cause an infinite loop.
