### ISSUE TITLE
Container doesn't respect `sizes` prop

### ISSUE THREAD

**Issue by edu-stx** [mantinedev/mantine#3420]
### What package has an issue

@mantine/core

### Describe the bug

The `Container` component does not respect the `sizes` prop, and always renders at the default `md` or `960` width.

The `sizes` prop doesn't work regardless of whether it is set directly on the `Container` or it's default props in the theme object.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/modest-bessie-wecjhz?file=/src/App.tsx&resolutionWidth=1036&resolutionHeight=675

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Sizes prop works as intended, it allows configuring Container sizes depending on `size` prop – https://codesandbox.io/s/elated-cookies-646x4c?file=/src/App.tsx

**Comment by aryzing** [comment]
Much appreciate the lightning fast response, thanks for clarifying.
