### ISSUE TITLE
Missing docs for theme.fn.size

### ISSUE THREAD

**Issue by aryzing** [mantinedev/mantine#3422]
### Link to the page where something nasty is located

https://mantine.dev/theming/functions/

### Exact quote of what is wrong

The `size` theme function is missing from the docs. E.g., being used here,

https://github.com/mantinedev/mantine/blob/c757c11d36e1c4e5976b05439da9d96d90e2d254/src/mantine-core/src/Container/Container.styles.ts#L13

### Are you willing to create pull request with the fix?

None

**Comment by rtivital** [comment]
This function as well as the majority of other functions are considered to be internal. Undocumented functions are not recommended to be used – they can have breaking changes in minor/patch releases without any notice. It is not planned to make these functions public.

**Comment by aryzing** [comment]
Fair enough. You may want to consider handling the privacy differently as both public and internal functions are all part of the same interface, and appear all together in intellisense suggestions, so users have no indication as to which ones are internal and which are meant to be used.
