### ISSUE TITLE
Multiple data-emotion references let page slow

### ISSUE THREAD

**Issue by ecatugy** [mantinedev/mantine#3423]
### What package has an issue

@mantine/core

### Describe the bug

Why does MantineUI create multiple data-emotion references within the head tag? This is making my app very heavy, is there a way to disable it?

![01](https://user-images.githubusercontent.com/22201052/214663609-4742074b-265e-4655-b10d-607f32c37057.jpg)

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is how emotion works in development, in production there are only several style tags.
