### ISSUE TITLE
TimeInput compatibility with react testing library fireEvent

### ISSUE THREAD

**Issue by oiqwrwer1** [mantinedev/mantine#3426]
### What package has an issue

@mantine/dates

### Describe the bug

I'm using a couple of TimeInput fields in a custom component.
In writing unit tests for my component, I encountered issues with fireEvent.change not actually triggering onChange handlers for TimeInput components.
```
<TimeInput
              data-testid={testToTime}
              onChange={value => {
                 console.log(value)
              }}
            />
```

I tried `fireEvent.change(screen.getByTestId(testToTime), {target: {value: new Date() }` but that didn't work.
I tried to see if I could act on the underlying HTML elements instead and was able to use
the below code to get the "hours" element, but running a fireEvent.change on that does not trigger the TimeInput-level onChange handler.
```
return render(<MyComponent>).getByRole("textbox", {
        name: "StartTime",
      }); 
```

It seems like this should work with React Testing Library.
I saw Enzyme shallow at least will trigger the onChange, but I am on React 18 and Enzyme is not compatible.

### What version of @mantine/hooks page do you have in package.json?

5.9.4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 6.0: TimeInput is now `input[type="time"]`
