### ISSUE TITLE
NumberInput allows Non numerical values 

### ISSUE THREAD

**Issue by DenisIrkhin** [mantinedev/mantine#3427]
### What package has an issue

@mantine/core

### Describe the bug

NumberInput allows Non numerical values 

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/20629939/214743148-d995b98f-8e29-4915-9a38-fb684f2322f2.png">

### What version of @mantine/hooks page do you have in package.json?

5.10.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is expected behavior, NumberInput supports custom formatters, there is no way of knowing which format you will use. Value is formatted correctly on blur.
