### ISSUE TITLE
Form reset not working on Multiselect

### ISSUE THREAD

**Issue by rgmvisser** [mantinedev/mantine#3434]
### What package has an issue

@mantine/core

### Describe the bug

When I call .reset() on the form where the multiselect is in, it doesn't clear the multiselect input. 

### What version of @mantine/hooks page do you have in package.json?

5.8.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/interesting-tree-y9i9gz?file=/src/App.tsxdenavigation=1&theme=dark)

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
It is expected behavior, MultiSelect is not a native input, it cannot be cleared with form event. If you need to clear input on your side, use controlled component.

**Comment by rgmvisser** [comment]
Hi @rtivital ! Thanks for the quick response. That's unfortunate as, any reason why this behavior would not be added anyway even though it's not a native input?

**Comment by rtivital** [comment]
I do not know how to add it

**Comment by rgmvisser** [comment]
Gotcha, yeah I am not sure either how this would be achievable 🤔
