### ISSUE TITLE
MultiSelect does not flip dropdown position by default

### ISSUE THREAD

**Issue by billop** [mantinedev/mantine#3437]
### What package has an issue

@mantine/core

### Describe the bug

The [documentation](https://mantine.dev/core/multi-select/#dropdown-position) states
> By default, dropdown is placed below the input and when there is not enough space, it flips to be above the input.

However, on that very page you can see that this is not true if you check the "bare minimum example": https://mantine.dev/core/multi-select/#usage

This is easily worked around by setting `dropdownPosition='flip'` but this shouldn't be necessary.

### What version of @mantine/hooks page do you have in package.json?

5.10.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/twilight-dew-hh0ie1?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by mcmxcdev** [comment]
I think this was fixed in https://github.com/mantinedev/mantine/releases/tag/5.10.4 and can be closed.
