### ISSUE TITLE
Pagination spacing does not work with zero

### ISSUE THREAD

**Issue by h2dthien** [mantinedev/mantine#3441]
### What package has an issue

@mantine/core

### Describe the bug

The "spacing={0}" doesn't set spacing to zero but to default value:

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/122243953/215303177-276a74cd-c661-4bbd-8337-d754cfa3ab40.png">

A workaround could be set it to "-1" as negative value will be used as 0

### What version of @mantine/hooks page do you have in package.json?

5.10.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/stoic-scooby-ypkuuq

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I guess there is a place where `||` or loose falsy check was used, where it should instead use `??` or strict check?

**Comment by rtivital** [comment]
Fixed in 5.10.3
