### ISSUE TITLE
isEmail validator regex TLD is too short

### ISSUE THREAD

**Issue by anri-asaturov** [mantinedev/mantine#3443]
### What package has an issue

@mantine/form

### Describe the bug

I could be misunderstanding the context, but email TLDs can be longer than 3 characters (up to 63 according to MDN).

https://github.com/mantinedev/mantine/blob/2fe9c4ab078ec03ddcc97613a1059e7db8b4e4ed/src/mantine-form/src/validators/is-email/is-email.ts#L5

### What version of @mantine/hooks page do you have in package.json?

5.10.1

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Fixed in 5.10.3
