### ISSUE TITLE
 Property 'children' is missing in type

### ISSUE THREAD

**Issue by cstffx** [mantinedev/mantine#3449]
### What package has an issue

@mantine/core

### Describe the bug

I'm using @mantine/core: 5.10.2 and React: 18.2.0 with Typescript 

And I getting this error when using some mantine components: 

``
TS2741: Property 'children' is missing in type '{ colorScheme: any; toggleColorScheme: (value?: ColorScheme) => any; }' but required in type 'ColorSchemeProviderProps'. 
``

For example in: 
```tsx
<React.StrictMode>
            <ColorSchemeProvider colorScheme={colorScheme} toggleColorScheme={toggleColorScheme}>
                <MantineProvider theme={{colorScheme}} withGlobalStyles withNormalizeCSS>
                    <UserContext.Provider>
                        <RouterProvider router={router}/>
                    </UserContext.Provider>
                </MantineProvider>
            </ColorSchemeProvider>
        </React.StrictMode>
```

Both ``ColorSchemeProvider`` and ``MantineProvider`` have the same error. 

### What version of @mantine/hooks page do you have in package.json?

5.10.2

**Comment by rtivital** [comment]
Hi @cstffx, you are welcome to reopen the issue if you can provide a sandbox
