### ISSUE TITLE
Type issue with polymorphic components

### ISSUE THREAD

**Issue by gdostie** [mantinedev/mantine#3450]
### What package has an issue

@mantine/core

### Describe the bug

When using a polymorphic component (like Box for instance), a TypeScript error is shown on additional props that are passed on the component. It is easier to understand what I mean by looking at some code so feel free to open the code sandbox.

```tsx
// error shown on prop "variant"
<Box component={Button} variant="outline">
    Button 2
</Box>
```

```
Property 'variant' does not exist on type 'IntrinsicAttributes & BoxProps & ComponentProp<(<C = "button">(props: PolymorphicComponentProps<C, ButtonProps>) => ReactElement<...>) & Omit<...> & { ...; }> & Omit<...> & { ...; }'.ts(2322)
```

Side node:

Before anyone suggest I just use `Button` directly, the use-case here is just an example of the problem I want to illustrate, not an actual thing that I'm trying to implement.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/xenodochial-bird-9s9u3o?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
That is a limitation of polymorphic components in typescript. They do not support other polymorphic components in `component` prop. It is not planned to be fixed – their purpose is to provide a way to change root element to other HTML element or `Link` components exported from third-party libraries.

**Comment by gdostie** [comment]
Alright, thanks for the explanations. Any pointers as to why it works for the `Link` component, is it a special case?

**Comment by rtivital** [comment]
Because `Link` is not a polymorphic component, its props are statically defined. Props types of polymorphic components are defined dynamically based on `component` prop.
