### ISSUE TITLE
Space in SimpleGrid does not work when is in breakpoints

### ISSUE THREAD

**Issue by asfwebmaster** [mantinedev/mantine#3453]
### What package has an issue

@mantine/core

### Describe the bug

When breakpoints are set with space or vertivalSpace, they are not applied when maxWidth is changed. Space is always stays the same.

### What version of @mantine/hooks page do you have in package.json?

^5.10.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/confident-pine-ct8hd5?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 5.10.3
