### ISSUE TITLE
Select: `required` props does not work.

### ISSUE THREAD

**Issue by sunadoi** [mantinedev/mantine#3454]
### What package has an issue

@mantine/core

### Describe the bug

When I set `required` props in the `Select` component, the asterisk is displayed, but HTML Form Validation does not work.

There seems to be no difference in behavior between `required` and `withAsterisk`.

Is this expected behavior?

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/clever-chihiro-ien3zx?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Select is not a native input, it is not possible to make it work with native browser validation correctly. If you need this feature, use NativeSelect component instead.

**Comment by sunadoi** [comment]
I like the UI of the `Select` component.
So I wanted to do native browser validation with the `Select` component, but I understand that this is not possible.
I will consider using the `NativeSelect` component.

Thank you for your prompt response!

**Comment by ustun-rn** [comment]
It actually works (properly unintended?) if `searchable` prop is set. Then `required` is honored.
