### ISSUE TITLE
Theme object does not maintain referential equality

### ISSUE THREAD

**Issue by Slapbox** [mantinedev/mantine#3459]
### What package has an issue

@mantine/core

### Describe the bug

This has downstream consequences for any function that memoizes based on the theme object, and probably marginally increases memory requirements due to multiple instances of the theme object being stored in memory before the garbage collector removes the outdated ones

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

This appears to be because the contents of `theme.fn` are recreated every time, even if `MantineProvider` is given an object which maintains referential equality. eg `theme.fn.largerThan`

**Comment by rtivital** [comment]
Please provide an example where this behavior is an issue.

**Comment by rtivital** [comment]
Hi @Slapbox, you are welcome to reopen the issue if you can provide a sandbox
