### ISSUE TITLE
[useLocalStorage] always returns the default-value (null) via F5-page-refresh

### ISSUE THREAD

**Issue by michaelhuber1937** [mantinedev/mantine#3463]
I have a problem with the useLocalStorage-hook. I am using this storage to store an auth-token.

`const [token, setToken] = useLocalStorage({ key: 'token', defaultValue: null });`

Obviously when initialized, the default-value is null. When the user has authenticated sucessfully, I am storing the token using setToken.

`setToken(data.token);`

This works perfectly when click through my app via react-router-dom. Reading from the store gives me the current token which then I use to make the API-request.

But when I refresh a page via F5 in the browser (so calling a direct route), useLocalStorage always gives me "null", which is obviously the default value. The token in the store is definitely there, I can the this is the Firefox-Development-Tools for Local Storage.

Why is that? Is this a bug?

**Comment by rtivital** [comment]
Please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by michaelhuber1937** [comment]
Here you go:

https://codesandbox.io/s/billowing-fog-0nwqz9?file=/src/App.tsx

It seems that App is called twice when using the useLocalStorage-Hook:

first time: token == null (default value)
second time: token == 'fcngr9u77tgjt5sa4qki7kln6ic370xz3dzj72j9sf10ulh8g2'

This happens with a small delay. How to read the token-value directly with the actual value?

**Comment by rtivital** [comment]
useLocalStorage hook retrieves value from localStorage in useEffect by default to provide full compatibility with ssr. If it is unwanted behavior, and you want to get value during hook initialization, set `getInitialValueInEffect: false`.

https://codesandbox.io/s/dreamy-haibt-qpv41t?file=/src/App.tsx

**Comment by michaelhuber1937** [comment]
Thank you so much! Works like a charm now!
