### ISSUE TITLE
5.8.4 and beyond lead to our Drawer contents not being displayed

### ISSUE THREAD

**Issue by Slapbox** [mantinedev/mantine#3468]
### What package has an issue

@mantine/core

### Describe the bug

5.8.0 and 5.8.3 works great, but everything above that we get an empty white drawer.

It works in the docs, but it no longer works for us.

I traced Mantine as the source by manually bisecting versions.

**The fix for #3056 appears to be an undocumented breaking change**

I'm not sure how the change breaks it though: https://github.com/mantinedev/mantine/commit/fd08c2fa4e52720d62c07f7cda1e547b37900079

This appears to be because it breaks restyling the component with Emotion by defining an exclusive `className` on the component.

```js

const StyledDrawer = styled(Drawer)`
  contain: strict;
  animation: ${animations.fadeIn} 500ms;
`;
```

### What version of @mantine/hooks page do you have in package.json?

5.8.4

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please check if `6.0.0-alpha.2` resolves your issue with Drawer

**Comment by Slapbox** [comment]
Unfortunately the Drawer fails to open with both `alpha.2` and `alpha.3`. No error appears in the console.

I'm not sure if maybe this is due to an API change or if it's a bug.

Also, my supposition about the cause of this bug is wrong. It's definitely something in 5.8.4, but using the `Drawer` component instead of `styled(Drawer)` yields the same problems.

It appears to be caused by using CSS `contain` (with any option besides "none") inside of the Drawer.

**Comment by Slapbox** [comment]
Apparently this is fixed by applying `height: 100%` to `.mantine-Drawer-body`.

**Comment by rtivital** [comment]
Please provide a sandbox then, I do not understand the issue – Drawer works correctly on mantine.dev website
