### ISSUE TITLE
MultiSelect doesn't overflow scrollable containers

### ISSUE THREAD

**Issue by akd-io** [mantinedev/mantine#3472]
### What package has an issue

@mantine/core

### Describe the bug

The Mantine MultiSelect component (which is amazing, as with everything Mantine, thank you very much) does not overflow containers that have `overflow: hidden` or `overflow: scroll`.

![Screenshot 2023-02-02 at 12 28 12](https://user-images.githubusercontent.com/30059155/216313580-5c7743dd-a6bc-4cb9-9e21-ff6fe3a19d04.png)
In this screenshot, I modified one of the examples in the docs to give the container `overflow: hidden`.

I'd argue that it would create better user experiences if the popup would overflow these container.

### What version of @mantine/hooks page do you have in package.json?

5.10.1

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I think it would make sense for the popup of MultiSelect to break free from its container, and be rendered with other popups, modals, and such. I assume you are doing this with React portals already.

**Comment by rtivital** [comment]
Set `withinPortal`

**Comment by akd-io** [comment]
Sorry, I should have definitely taken a look at the [MultiSelect props list](https://mantine.dev/core/multi-select/?t=props) in the docs 🤦‍♂️

Thanks a lot, @rtivital!

I can only hope this issue will prove helpful to other developers who don't know how to RTFM.
