### ISSUE TITLE
Modal layout shift when overflow-x: hidden is setted on html & body

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#3482]
### What package has an issue

@mantine/core

### Describe the bug

I have a [requirement](https://stackoverflow.com/a/69291962) to have `overflow: hidden` on `html,body` elements for go away with different overflow issues.
But now I have a problem with modal from mantine lib - I have layout shift when modal opens.
Demo attached.

### What version of @mantine/hooks page do you have in package.json?

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/admiring-mahavira-rpy9j0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 6.0. See https://v6.mantine.dev/core/modal/#fixed-elements-offset

**Comment by rtivital** [comment]
Fixed in 6.0
