### ISSUE TITLE
Text component missing typescript declare

### ISSUE THREAD

**Issue by Valar103769** [mantinedev/mantine#3485]
### What package has an issue

@mantine/core

### Describe the bug

<img width="594" alt="image" src="https://user-images.githubusercontent.com/36926073/216578079-ed971974-c065-4785-87ee-466bb7d0dc52.png">

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Text component does not miss it, it works correctly with TypeScript. You did not import it. vs code does not show autocomplete because Text is a native constructor. This issue is not fixable.
