### ISSUE TITLE
Datepicker should open calendar at max date if it is in the past

### ISSUE THREAD

**Issue by KilianB** [mantinedev/mantine#3496]
### What package has an issue

@mantine/dates

### Describe the bug

If specifying a maximum date in the past the calendar still opens at the current day not allowing the user to move back and forth to a different month due to the arrows being disabled. 

A possible workaround is opening the calendar at a yearly interval, still it is very bad user experience if the user has to click many times before he can select a date. 

````ts
<DatePicker maxDate={new Date('1.1.1960')}/>
````

### What version of @mantine/hooks page do you have in package.json?

5.10.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/xenodochial-architecture-6j82bo?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

I would propose that the calendar either initially opens at the max date if it is in the past or that we are able to set an _initialOpenDate_ while the value is undefined in case of controlled state if it hasn't been touched yet

**Comment by rtivital** [comment]
Fixed in 6.0
