### ISSUE TITLE
Icon inline

### ISSUE THREAD

**Issue by alexbakers** [mantinedev/mantine#3497]
### What package has an issue

@mantine/core

### Describe the bug

Icon inline show

<img width="58" alt="image" src="https://user-images.githubusercontent.com/98721968/216790452-fa76ab05-0259-4dae-b0ce-e47432ffda29.png">

<img width="558" alt="image" src="https://user-images.githubusercontent.com/98721968/216790528-5df5ef95-1bd2-4777-a33c-b4c002ef9e8a.png">

```
import { Avatar } from "@mantine/core";
import { IconStar } from "@tabler/icons";

<Avatar color="blue" radius="sm">
  <IconStar />
</Avatar>
```

### What version of @mantine/hooks page do you have in package.json?

5.10.3

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by alexbakers** [comment]
Yup. I didn't add a provider.

**Comment by alexbakers** [comment]
Everything is set up, the error has not disappeared.

**Comment by alexbakers** [comment]
`yarn create vite mantine-vite --template react-ts`
`cd mantine-vite`
`yarn add @mantine/core @mantine/hooks @emotion/react`
`yarn add @tabler/icons`
`yarn dev`

This example: https://mantine.dev/core/avatar/#usage

<img width="362" alt="image" src="https://user-images.githubusercontent.com/98721968/216792306-6e5a5221-64c6-44cd-aea5-bdaf10c1f2a6.png">

**Comment by alexbakers** [comment]
Fix (`@tabler/icons` not work):

`yarn add @tabler/icons-react`

```
import { IconStar } from "@tabler/icons-react";
```

**Comment by rtivital** [comment]
Use `@tabler/icons-react`, documentation will be updated in 6.0.
