### ISSUE TITLE
[Feature Request] Internationalisation/RTL support

### ISSUE THREAD

**Issue by dukesx** [mantinedev/mantine#350]
### Brief
I have seen that in documentation that RTL can be enabled via stylis plugin but there is lack of detail over its implementation. I suppose there is no official or complete support for it. 

I hope Mantine can support a "togglleable" support for RTL like Ant Design does in its Provider. Although this won't be easy since this may need tampering with stylis middleware (which you have already done) and emotion's use styles hook to change "theme", mimicking a toggle. I am not sure if this is the way but this is just a superficial speculation. 

### Why 
Internationalisation is a very important part of an app, because English is not primary language of many countries and I suppose in many countries its not even preferred to be used to communicate internally (China, North Korea, Some parts of Russia, many parts of Pakistan etc). So I believe such a need advocates support for this feature.

**Comment by rtivital** [comment]
We now have rtl guide, hope that helps – https://mantine.dev/theming/rtl/
We are still leaving rtl support for community, if everything is not correct, please report

**Comment by dukesx** [comment]
> We now have rtl guide, hope that helps – https://mantine.dev/theming/rtl/ We are still leaving rtl support for community, if everything is not correct, please report

Thank you ! Much appreciated !
