### ISSUE TITLE
[v6] - Dropdown in modal gets cut off

### ISSUE THREAD

**Issue by justinsmid** [mantinedev/mantine#3503]
### What package has an issue

@mantine/modals

### Describe the bug

As of v6, dropdowns inside of a modal get cut off:

![image](https://user-images.githubusercontent.com/34271675/216920060-8a0555ca-bb80-41c3-bd9d-2aeaa2cfd00d.png)

This is not the case in v5, where the dropdown gets rendered above the modal:

![image](https://user-images.githubusercontent.com/34271675/216920243-99980f0d-da57-47c9-8ae1-5919069a6744.png)

Not sure if this is intentional or not. If it is, what would be the recommended solution?

I've tried specifying a higher `zIndex` on the dropdown, but with no success. I suppose I could use `withinPortal`, but that would break other things, so I'd rather not use that solution.

### What version of @mantine/hooks page do you have in package.json?

6.0.0-alpha.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/vigilant-water-ltjwqj?file=/src/Inner.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Modal has hidden overflow, to enable scrolling with ScrollArea. You can customize styles with styles API or use `withinPortal`. It is not planned to change current behavior.

> I suppose I could use withinPortal, but that would break other things

What exactly will it break?

**Comment by justinsmid** [comment]
> What exactly will it break?

Mostly tests; we have tests and utility functions that rely on the dropdown being within the Select's root. I'm sure I **could** change those, but I think it makes a lot more sense to have the dropdown be part of the root.

> Modal has hidden overflow, to enable scrolling with ScrollArea.

Would it be possible to have this behavior be configurable through a prop? For us, the use case of a modal that isn't scrollable and works like it did in v5 is **much** more common than that of a modal that is scrollable by default.

Alternatively, could you point me to which styles I'd have to modify to get it to work like before in my given codesandbox? I tried playing around with the modal's `overflow`, but was unsuccessful.

**Comment by rtivital** [comment]
You can find ModalBase source code here – https://github.com/mantinedev/mantine/tree/v6/src/mantine-core/src/ModalBase

**Comment by justinsmid** [comment]
> It is not planned to change current behavior.

Understood. I'll make it work using `withinPortal` for now - thanks!

**Comment by hilmia** [comment]
> You can find ModalBase source code here – https://github.com/mantinedev/mantine/tree/v6/src/mantine-core/src/ModalBase

Hi, I have the same issue with a dropdown cutoff, I couldn't find the overflow style setting, I tried to change all the modal component styles api with "overflow: "visible"" but I couldn't make it work. How do I make this work?

**Comment by AJIJIi** [comment]
The best solution is to use `withinPortal` or `popoverProps={{withinPortal:true}}.` But as was mentioned not all components have this property. So alternative is to customise styles for your `Modal`. 

[Here](https://github.com/mantinedev/mantine/issues/3732#issuecomment-1462302013) was an example how to do it, but for me it didn't work because one of the children still had `overflow == scroll`. So maybe my solution will help someone:

```
styles={theme => ({
   header: { borderRadius: theme.spacing.xs },
   inner: {
      '> section': {
         overflowY: 'visible',
      },
      '.mantine-ScrollArea-root': {
         overflow: 'visible',
      },
      '.mantine-ScrollArea-viewport': {
         overflow: 'visible !important',
      },
   },
})}
```

P.S. In any solution don't forget to check `zIndex` of elements
