### ISSUE TITLE
Header is responsive with Navbar on AppShell with layout="alt"

### ISSUE THREAD

**Issue by Dominic-Preap** [mantinedev/mantine#3507]
### What package has an issue

@mantine/core

### Describe the bug

We're having an issue with `<AppShell layout="alt"/>`. When screen size is around 768px to 990px, the `Header` and `Navbar` are not responsive correctly.

Video & Codesandbox below:

https://user-images.githubusercontent.com/14802170/217010995-bafe6fa8-421a-4c97-b987-17dab6a02cb0.mp4

### What version of @mantine/hooks page do you have in package.json?

5.10.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/sandbox/dominic-mantine-appshell-demo-wpnqx2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You've set breakpoint to md, but did not provide width for md – https://codesandbox.io/s/sleepy-galois-ucucy7?file=/src/App.tsx

**Comment by Dominic-Preap** [comment]
Thank you.
