### ISSUE TITLE
Menu Keyboard Interactions

### ISSUE THREAD

**Issue by noahsb** [mantinedev/mantine#3508]
### Link to the page where something nasty is located

https://mantine.dev/core/menu/#keyboard-interactions

### Exact quote of what is wrong

The docs say:

> Space/Enter: Opens/closes dropdown

When Space/Enter are actually used to "click" the target element. Assuming this is just a documentation error (it appears the examples function the same way), I'd update the docs to say:

> Space/Enter: Simulates the click of a Menu Item

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
How are these descriptions different? Space/Enter keys simulate clicks and open/close dropdown.

**Comment by noahsb** [comment]
I think it’s a little confusing because:

Escape is what closes the Dropdown

Space/Enter is what is used to simulate a click when on a target element 

Space/Enter is also used to activate the menu Dropdown

Maybe it just needs another entry? I found it a little confusing but I see why you worded it that way. If you feel it’s self explanatory I’m okay with leaving it be. 

I felt it was a little confusing at first because it wasn’t immediately obvious Space/Enter is what actives the Dropdown *and* what simulates click. 

So adding the detail those buttons simulates the click provided a little extra context 

Maybe it makes more sense to put it into two categories?

Space/Enter: expands Dropdown menu
Space/Enter: simulates click of targeted element

Not a problem if you decide it’s unnecessary. Thanks!

**Comment by rtivital** [comment]
> I felt it was a little confusing at first because it wasn’t immediately obvious Space/Enter simulated click on target elements

There is no extra “click simulation” logic for Enter/Space key – all buttons work this way. It is common knowledge, and it should not be included in documentation.
