### ISSUE TITLE
"Edit this page" link broken

### ISSUE THREAD

**Issue by akd-io** [mantinedev/mantine#3514]
### Link to the page where something nasty is located

https://mantine.dev/dates/date-picker/

### Exact quote of what is wrong

"Edit this page" link links to
https://github.com/mantinedev/mantine/blob/master/docs/src/docs/dates/DatePicker.mdx
instead of
https://github.com/mantinedev/mantine/blob/master/docs/src/docs/dates/date-picker.mdx

### Are you willing to create pull request with the fix?

Yes

**Comment by akd-io** [comment]
Might be a good idea to set up some automation to check for broken links

**Comment by akd-io** [comment]
I guess it's broken for all docs files after some Pascal case to kebab case conversion?
I can do a find replace for you if you'd like

**Comment by rtivital** [comment]
The issue will be fixed in 6.0

**Comment by rtivital** [comment]
Fixed in 6.0
