### ISSUE TITLE
Multiple notification providers

### ISSUE THREAD

**Issue by ramiel** [mantinedev/mantine#3522]
### What package has an issue

@mantine/notifications

### Describe the bug

All the notifications provider in an app, receive the notifications sent through `showNotification`. There's not a way to have two provider and so, to only show notification in the first parent provider which is the normal functionality of a provider

### What version of @mantine/hooks page do you have in package.json?

5.10.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/multiple-notifications-provider-g6diys

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Do not use a global `showNotification` but rely on a hook, something similar to

```ts
const { showNotification } = useNotifications();
```

which works with the current context

**Comment by rtivital** [comment]
You can have only one NotificationsProvider in your application. Unlike hook, `showNotification` function can be called who anywhere – from a regular function, state library (e.g., zustand or redux), axios interceptor, etc. It is not planned to change this behavior.

**Comment by ramiel** [comment]
This is what I feared :)
If this can help, my use case is to use, in the notifications, components that need a specific provider (one of mines). When the notification is shown in the top NotificationProvider, it crashes because it's not child of my provider.

**Comment by rtivital** [comment]
You can render NotificationsProvider anywhere in your application, it is not required to be the first element in the tree. In v6 it will not even be a provider, just Notifications component – https://v6.mantine.dev/others/notifications/#usage

**Comment by ramiel** [comment]
So the idea is to have the provider as deep as possible :) ok
