### ISSUE TITLE
Mantine Carousel's indicators and Controls are transparent.

### ISSUE THREAD

**Issue by HashaamKhan19** [mantinedev/mantine#3529]
### What package has an issue

@mantine/core

### Describe the bug

The controls and Indicators of my mantine carousel are transparent. Even with sx prop color do not apply.
By deafult(no styles applied) they are transparent.
![image](https://user-images.githubusercontent.com/57043401/217781181-8e83dea5-451e-45ce-b653-2263e1db4b2b.png)
![image](https://user-images.githubusercontent.com/57043401/217781350-7c07db9f-14e7-4eb8-9922-535fecd02aac.png)

### What version of @mantine/hooks page do you have in package.json?

^5.10.3

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by HashaamKhan19** [comment]
not working on deployed link aswell
@rtivital

**Comment by rtivital** [comment]
Work fine – https://codesandbox.io/s/flamboyant-neumann-q46x1e

**Comment by praiseisaac** [comment]
@HashaamKhan19 can you check what styles are applied to the element using the inspector? You might have a global theme that overwrites the element (in this case Button or ActionIcon) styling.

**Comment by HashaamKhan19** [comment]
> @HashaamKhan19 can you check what styles are applied to the element using the inspector? You might have a global theme that overwrites the element (in this case Button or ActionIcon) styling.

Yes i've checked it. Its basically a third party installed thats overriding my mantine's styles. I've used emotion cache from mantine to get rid of this problem. It works fine now
