### ISSUE TITLE
Wrong styling for DatePicker in Table

### ISSUE THREAD

**Issue by lausek** [mantinedev/mantine#3539]
### What package has an issue

@mantine/dates

### Describe the bug

When opening a DatePicker inside a table row, the styling of the month view is messed up. This is probably due to cell padding of the outer table being inherited (`tbody tr td`).

![Screenshot from 2023-02-11 16-12-12](https://user-images.githubusercontent.com/32076279/218266244-e5b5748d-6e5f-4eaf-aaee-f28135dc9cc8.png)

### What version of @mantine/hooks page do you have in package.json?

5.10.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/autumn-surf-t3mmdp

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Set withinPortal – https://codesandbox.io/s/objective-frog-wnw1b1

**Comment by kettil** [comment]
@rtivital I have the same problem, which can theoretically be solved with `withinPortal`.

But if you activate the fullscreen mode for the table, the overlay with the datePicker is not displayed at all. If I remove the `withinPortal`, the data picker is displayed again, but the formatting is broken.

I use version 6.0.13

**Comment by rtivital** [comment]
Fixed in 7.0 by migrating table to compound components – https://v7.mantine.dev/core/table
