### ISSUE TITLE
Notifications with very long messages with many words overflow

### ISSUE THREAD

**Issue by billop** [mantinedev/mantine#3540]
### What package has an issue

@mantine/notifications

### Describe the bug

Notifications with very long messages with many words overflow. As opposed to very long messages with no spaces which truncate nicely.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/keen-payne-sohtrf?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Fixed in 5.10.4
