### ISSUE TITLE
forms: resetDirty not working properly or setInitialValues is needed

### ISSUE THREAD

**Issue by cristianghita24** [mantinedev/mantine#3541]
### What package has an issue

@mantine/form

### Describe the bug

I have a form to register a client. After entering the ID number - if the client exists it is retrieved from an API.

Upon retrieval,  I want to use `setValues` to set the retrieved object to form value.

I want to `resetDirty` so that changes to the object retrieved from API will be caught in `isDirty`. 

It doesn't work - the fields changed still show as dirty. If when calling `isDirty` it is still comparing to `initialValues` it means that we need a `setInitialValues` function.

### What version of @mantine/hooks page do you have in package.json?

5.10.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
To update values that are used for dirty comparison, call resetDirty with new values: `form.resetDirty(newValues)`

**Comment by cristianghita24** [comment]
True
