### ISSUE TITLE
List component overflows its height

### ISSUE THREAD

**Issue by Mekan89** [mantinedev/mantine#3547]
### What package has an issue

@mantine/core

### Describe the bug

List component overflows it's content. It's working when I use only Text component without List.Item.
```
<List listStyleType='none' size={15} spacing={20}>
            <List.Item>
                        <Text span w={170} opacity={0.5} display='inline-block'> Country : </Text>
                        <Text span c={dark_2}> USA </Text>
            <List.Item>
           .......
</List>
```

![image](https://user-images.githubusercontent.com/40357987/218756552-eb600231-c0e1-415e-92b0-a3e95f20b2b8.png)

### What version of @mantine/hooks page do you have in package.json?

5.10.3

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Set `sx={{ overflow: 'hidden' }}`, if it is unwanted behavior. It is not an issue with the library.

**Comment by Mekan89** [comment]
Ok. thank you very much.
