### ISSUE TITLE
TimeInput AmLabel & PmLabel don't work with capital letters

### ISSUE THREAD

**Issue by maradney** [mantinedev/mantine#3567]
In [TimeInput](https://mantine.dev/dates/time-input/) AmLabel and PmLabel don't work if you use capital letters.
ex: `AmLabel="Am"` or `"aM"` or `"AM"` will break the component (am/pm wise) and won't switch.
Using small letters like `amLabel="night"` will work though.

https://user-images.githubusercontent.com/20243713/219419537-5b0e1a5b-2519-4635-b8b1-9035248e557b.mov

---

Also `mantine-TimeInput-amPmInput` should have a width of fit-content or something as using more than 3 letters it won't show correctly

<img width="835" alt="Screen Shot 2023-02-16 at 6 05 08 PM" src="https://user-images.githubusercontent.com/20243713/219421626-e36ed75d-9cac-4e94-ba49-cc6f9989dd1e.png">

**Comment by rtivital** [comment]
In 6.0 TimeInput will be replaced with native `input[type=time]`. This issue is not planned to be fixed.

**Comment by maradney** [comment]
Alright, I'll close this then.

If anyone faces the same issue you can always hack it with css
```
'input.mantine-TimeInput-amPmInput': {
      width: 'fit-content',
      textTransform: 'uppercase',
},
```
