### ISSUE TITLE
[MultiSelect]: disableSelectedItemFiltering props cause style error

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#3571]
### What package has an issue

@mantine/core

### Describe the bug

```jsx
       <MultiSelect
            label="指标"
            value={targets}
            onChange={setTargets}
            data={
              metaData?.normal.map((item) => ({
                label: item.title,
                value: item.key,
              })) || []
            }
            disableSelectedItemFiltering
          />
```

<img width="678" alt="image" src="https://user-images.githubusercontent.com/124666577/219585883-a7f2da60-cbf2-4785-bb18-8cc793cd3af7.png">

and, When using this props, can I reduce the number of props displayed in the input  or let me custom? 

### What version of @mantine/hooks page do you have in package.json?

    "@mantine/core": "^5.10.4",

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
What kind of style error? Your screenshot looks as expected.

**Comment by vaynevayne** [comment]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/124666577/220003571-dba01eb6-db9e-4f72-b073-e983d12aceae.png">

 should has some margin-top  ?

**Comment by rtivital** [comment]
You can add this with Styles API in your application
