### ISSUE TITLE
RadioGroup is not available in mantine core

### ISSUE THREAD

**Issue by ankur1163** [mantinedev/mantine#3577]
### What package has an issue

@mantine/core

### Describe the bug

I am trying to use radiogroup, radio in my project. 
`import {  RadioGroup} from "@mantine/core";`

I see this error on my page 
https://prnt.sc/Ev0ShTvp1OAj

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
There is no `RadioGroup` component, there is `Radio.Group`

**Comment by Jordan466** [comment]
Maybe a note for people who land here - Be careful what version of the docs you read, Google Indexed the V2 docs which does mention a `RadioGroup`, and I too was confused why my import wasn't working

**Comment by ankur1163** [comment]
thats the thing. I later on realized, i was reading wrong docs. Thanks
