### ISSUE TITLE
[Select] value/defaultValue is not set when out of select data 

### ISSUE THREAD

**Issue by nghiepit** [mantinedev/mantine#358]
Hi,
I think the `value` can be set even if it's not on the list of select data. At least in case `creatable`.

```tsx
     <Select
        label="Select one"
        data={["a", "b", "c"]}
        creatable
        searchable
        value="not set"
        getCreateLabel={(query) => `+ Create ${query}`}
      />
```

Please provide following information:
- What package has an issue (@mantine/core, mantine/hooks or other)? **@mantine/core**
- What package version are you using? **3.1.0**
- In which browser and operating system issue occurred? **Chrome, macOS**
- If possible please attach link to codesandbox with reproduced issue. https://codesandbox.io/s/wild-paper-yctty?file=/src/App.tsx

**Comment by rtivital** [comment]
We cannot support setting value that is not included in data, it will break more advanced use cases (custom item renderer in Select and custom value renderer in MultiSelect).

**Comment by nghiepit** [comment]
@rtivital  But why `MultiSelect` can setting value is not included in data.

**Comment by rtivital** [comment]
Thanks for noticing, it's a bug that may lead to unexpected behavior with custom value component. I'll fix it in future releases

**Comment by nghieptiki** [comment]
What do you think if the value is not included in data, `Select` should append that value into data.

**Comment by nghiepit** [comment]
What do you think if the value is not included in data, Select should append that value into data.

**Comment by rtivital** [comment]
It's a good solution, but we cannot make it – this will be incorrect for data with custom shape and may break some applications that rely on certain data shape.
