### ISSUE TITLE
It is possible to use updates on defaultValue in Accordion component?

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#3582]
### What package has an issue

@mantine/core

### Describe the bug

Hi.
I want to receive updates (somewhere from parent component or store value, or when navigating between pages with the common section which have Accordion) when passed defaultValue changes from outside.

How to do that?
See repro example

I want to keep all accordion items opened, but I don't want to control state of Accordion internally (**I mean to use controlled variant with `value` prop)** (with redundant creation of useState and a component wrapper just for this case)

It is possible?
Thanks!

### What version of @mantine/hooks page do you have in package.json?

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/bitter-cloud-6g0ero?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
`<Accordion onChange={yourChangeHandler} />`

**Comment by 7iomka** [comment]
> `<Accordion onChange={yourChangeHandler} />`

How I to fix example with this and to keep use `defaultValue`? What yourChangeHandler means? I just have changes in value passed as defaulValue.
The only way is to create a controlled wrapper?

**Comment by rtivital** [comment]
I do not really know what you need. You say that you want a controlled component that is not controlled. Accordion and other components provide three props:
- `devaultValue` – initial value, its updates are ignored
- `value` – controlled value, its updates are applied to component
- `onChange` – function that is called when value changes, does not matter whether component is controlled or uncontrolled

There are no other props to manage component state.
