### ISSUE TITLE
[LoadingOverlay]: default zIndex (400) should set to less then 300 

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#3587]
### What package has an issue

@mantine/core

### Describe the bug

If we have a select component on top and a container with loadingOverlay applied below, then the select dropdown will be blocked when loading.
The zIndex of the select component is 300,
loadingOverlay zIndex should be less than 300, now it is 400

**Comment by rtivital** [comment]
You can use `zIndex` prop to set LoadingOverlay z-index.

**Comment by vaynevayne** [comment]
I know, I did, but I think this is a boundary clearing that mantine didn't take into account. Should it be treated as a bug?
