### ISSUE TITLE
components of mantine/dates could not call custom theme

### ISSUE THREAD

**Issue by calebinit** [mantinedev/mantine#3593]
### What package has an issue

@mantine/dates

### Describe the bug

I set custom theme on MantineProvider
But Calendar componenets call a default theme when i use theme object in styles function.

### What version of @mantine/hooks page do you have in package.json?

5.10.3

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by calebinit** [comment]
I have updated  here https://codesandbox.io/s/friendly-sun-ezu9it?file=/src/Page.tsx
But there is no bugs...
I set with same version of packages In my project.
