### ISSUE TITLE
Autofocus on TextInput in Menu doesn't work

### ISSUE THREAD

**Issue by bastiengrignon** [mantinedev/mantine#3595]
### What package has an issue

@mantine/core

### Describe the bug

When using a `Menu` component with a `TextInput` in a `Menu.Label` to search for items (`Menu.Item`), clicking on the Target does not autoFocus on the input even when using the hook `useFocusTrap()` like in the sandbox provided.
That could be nice to have the same behavior as a `Modal`

### What version of @mantine/hooks page do you have in package.json?

5.10.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/misty-sound-cgzvji?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by bastiengrignon** [comment]
Thanks a lot but there is no other solution that using `setTimeout()` ?

**Comment by rtivital** [comment]
> Thanks a lot but there is no other solution that using setTimeout() ?

I do not think so

> And this seems to not work the first time the menu is clicked

Works for me on the codesandbox all the time

**Comment by bastiengrignon** [comment]
For me the first time it doesn't work in the Codesandbox but in my code it's ok so thanks :smile:

And thanks for all the work you've done with Mantine !!
