### ISSUE TITLE
Wrong Mantine import for Switch example

### ISSUE THREAD

**Issue by sgrobert** [mantinedev/mantine#3599]
### Link to the page where something nasty is located

https://mantine.dev/core/switch/

### Exact quote of what is wrong

The `import` statement for the following: `import { Checkbox } from '@mantine/core';` should be `import { Switch } from '@mantine/core';`

[Controlled Switch.Group](https://mantine.dev/core/switch/#controlled-switchgroup)

```
import { useState } from 'react';
import { Checkbox } from '@mantine/core';

function Demo() {
  const [value, setValue] = useState<string[]>([]);

  return (
    <Switch.Group value={value} onChange={setValue}>
      <Switch value="react" label="React" />
      <Switch value="svelte" label="Svelte" />
    </Switch.Group>
  );
}
```

The correct one should be:

```
import { useState } from 'react';
import { Switch } from '@mantine/core';

function Demo() {
  const [value, setValue] = useState<string[]>([]);

  return (
    <Switch.Group value={value} onChange={setValue}>
      <Switch value="react" label="React" />
      <Switch value="svelte" label="Svelte" />
    </Switch.Group>
  );
}
```

Though I am open to helping set up a PR, not too sure how the `Mantine` does it for their `docs`. So please do advise me, else I'm good with `Mantine`'s team handling the PR.

Cheers!

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Thanks for reporting an issue, you are welcome to submit a PR with a fix

**Comment by sgrobert** [comment]
Hi @rtivital ,

Thank you for the feedback. Could you help to navigate me as to where I may find the specific docs page https://mantine.dev/core/switch/ on the repo?

Thank you.

**Comment by cyantree** [comment]
The doc page contains a link to it in the header: "Edit this page" - https://github.com/mantinedev/mantine/blob/master/docs/src/docs/core/Switch.mdx

**Comment by sgrobert** [comment]
Hi @cyantree,

Thanks for the pinpoint. I've submitted a PR here: https://github.com/mantinedev/mantine/pull/3603

Cheers!
