### ISSUE TITLE
Modal manager ID assignment

### ISSUE THREAD

**Issue by specOper99** [mantinedev/mantine#3600]
### What package has an issue

@mantine/modals

### Describe the bug

When I try to assign a value to the mantine modal manager with openModal function I get the following error

`TypeError: Attempted to assign to readonly property.`

Which is some how weird because it must take my ID without generating an id on its own

### What version of @mantine/hooks page do you have in package.json?

5.10.4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by specOper99** [comment]
Here it is https://codesandbox.io/s/modal-with-id-error-p6inkc?file=/src/App.tsx
once you remove the id everything works fine but with it, we are having a big issue

**Comment by cyantree** [comment]
I think this is a duplicate of #3393.

Did you possibly mean to use `modalId` instead of `id`?

FYI see my comment for a bit background about the issue:
https://github.com/mantinedev/mantine/issues/3393#issuecomment-1416873129

**Comment by specOper99** [comment]
Thank you, yes exactly.

I searched for it but I didn't found anything till you wrote the id of issue.

> You made my day ❤️
