### ISSUE TITLE
[Select] options not showing correctly if wrapped within Card

### ISSUE THREAD

**Issue by iamyuu** [mantinedev/mantine#3608]
### What package has an issue

@mantine/core

### Describe the bug

When using the Select component and wrapping it into the Card component, the options only show part of it (based on the height of the card, I guess)

![r8LwUHHc 2023-02-25 at 02 40 AM@2x](https://user-images.githubusercontent.com/45778229/221275546-8b9d2e81-6eab-40d1-b2cf-46df6e01ca10.jpg)

Expected: the options should be rendered even outside of the card

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-select-on-card-repro-0sx0or

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Maybe the option / select item should render on the portal

**Comment by iamyuu** [comment]
![eZsc4CzJ 2023-02-25 at 02 46 AM@2x](https://user-images.githubusercontent.com/45778229/221276531-15902b00-bb10-494b-8598-576fed84ebb0.jpg)

`MultiSelect` also has the same behavior

**Comment by rtivital** [comment]
https://codesandbox.io/s/mantine-select-on-card-repro-forked-s02p7c?file=/src/App.tsx
