### ISSUE TITLE
[@mantine/core] MultiSelect hiding searchable values after losing focus

### ISSUE THREAD

**Issue by cooervo** [mantinedev/mantine#3610]
### What package has an issue

@mantine/core

### Describe the bug

1. Go to https://mantine.dev/core/multi-select/#searchable
2. Write something in the Multiselect, example "React" then write a partial string and don't select it, example I wrote `sv` as you can see here:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/11219268/221294407-8f10ccd1-04bd-418b-b168-beb52deb8755.png">
3. click out or press tab to loose focus the partial string is hidden. As seen here: 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/11219268/221294625-94d1fec6-3f3e-47c3-8342-160948d76478.png">
4. Now click back into multiselect `sv` field is visible once again

### What version of @mantine/hooks page do you have in package.json?

^5.9.4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

i believe what is happening is that when focus is lost the input inside the multiselect has a hidden class `mantine-MultiSelect-searchInputInputHidden`, this is what browser currently has when focus lost:

```
<input type="search" id="mantine-Ra85aqnap"
   class="mantine-MultiSelect-searchInput mantine-MultiSelect-searchInputInputHidden mantine-idmm9i" data-mantine- 
   stop-propagation="false"  
   autocomplete="off" 
   value="sv">
```

notice value='sv' is correctly hold inside the input

**Comment by rtivital** [comment]
MultiSelect component is designed to work this way, it is not a bug. When the component is not focused, search value is hidden to make it clear there are no selected values apart from the displayed options.

**Comment by cooervo** [comment]
hi @rtivital then behavior is a bit inconsistent if you type a query without selecting a value and then you blur or loose focus then the query is still visible.
