### ISSUE TITLE
Centered modals flicker on close

### ISSUE THREAD

**Issue by whoisandy** [mantinedev/mantine#3613]
### What package has an issue

@mantine/modals

### Describe the bug

Modals created using the modals provider with centered flag and a custom exitTransitionDuration properties flickers on close. The modal shifts up before being removed from the dom. Also sometimes the exitTransitionDuration property does not take effect. Apparently this behavior is only observed with modals created using the scoped modals package. Check out the behavior in the attached gif.

![CleanShot 2023-02-25 at 19 04 52](https://user-images.githubusercontent.com/297132/221359795-15825199-30c8-4d24-ae59-51a4e6615c49.gif)

### What version of @mantine/hooks page do you have in package.json?

5.10.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/compassionate-brahmagupta-wozuzv?file=/src/App.tsx

_No response_

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment]
Already reported in #3409. There's the pending PR #3570 for it.

**Comment by whoisandy** [comment]
@cyantree Thanks for pointing out 🙏
