### ISSUE TITLE
Select component data has no differentiation between `data.value` and `data.label`

### ISSUE THREAD

**Issue by AmirabbasJ** [mantinedev/mantine#3618]
### What package has an issue

@mantine/core

### Describe the bug

to qoute from the doc we use `label` when we want to have separation between how we show something vs how we use something 
let's say we have an gender select option, we might want to use other words (even other translations) to show options to the user, like:

```jsx
<Select data={[ {lable: "boy", value: "male"}, {lable: "girl", value: "female"} ]}
```

but the value is equal to the label not the specified value

### What version of @mantine/hooks page do you have in package.json?

5.10.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-playground-forked-tztoxh

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by nitedani** [comment]
Your example seems to work correctly. Add `onChange={console.log}` and you will see the correct value logged.

**Comment by rtivital** [comment]
Which value is not correct exactly?
