### ISSUE TITLE
Ctrl K of the search bar collapse when the search bar is selected

### ISSUE THREAD

**Issue by MrHBS** [mantinedev/mantine#362]
Ctrl K of the search bar collapse when the search bar is selected

![1](https://user-images.githubusercontent.com/30705623/139617096-bb7f62f0-0ac7-422f-bf36-38796f73340f.PNG)

**Comment by rtivital** [comment]
It tells you that you need to press enter to search docs

**Comment by MrHBS** [comment]
Oh lmao I somehow missed the icon

**Comment by MrHBS** [comment]
Maybe center the icon?
