### ISSUE TITLE
Carousel sliding in rtl mode problem

### ISSUE THREAD

**Issue by aliasadolahi74** [mantinedev/mantine#3621]
### What package has an issue

@mantine/carousel

### Describe the bug

There is a problem with sliding in RTL mode. My slides are 561px wide and there is no gap between them. but when I click on the arrow button, first item margin is equal to 569px and makes subsequent slides show up.

### What version of @mantine/hooks page do you have in package.json?

5.3.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please provide a codesandbox (template– https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6) with minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example. It is not possible to identify the issue without reproduction.

**Comment by aliasadolahi74** [comment]
my problem has been resolved. It was because I didn't refresh the page and with changing data because of a live view of the server I could not see all of the new changes and just some states changed with that. 
https://codesandbox.io/s/green-cookies-2q8sd1?file=/src/Slides/Slides.jsx
