### ISSUE TITLE
Switch errors not spread with getInputProps

### ISSUE THREAD

**Issue by noahsb** [mantinedev/mantine#3624]
### What package has an issue

@mantine/form

### Describe the bug

Errors from `form` when using the `Switch` component are not spread via `getInputProps`. Error only appears if manually passing the prop in via:

```
<Switch error={form.errors.inputName} />
```

### What version of @mantine/hooks page do you have in package.json?

5.10.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/old-sun-s7u5r3?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
https://codesandbox.io/s/jovial-brook-znow5c?file=/src/App.tsx

**Comment by noahsb** [comment]
Missed this in the docs, thanks!
