### ISSUE TITLE
Use `insertionPoint` instead of `prepend` for attaching `style` elements with `emotion`

### ISSUE THREAD

**Issue by mcmxcdev** [mantinedev/mantine#3628]
### What package has an issue

@mantine/core

### Describe the bug

I reported an issue about `<meta charset="utf-8">` position in the DOM to `emotion`, but it seems it's up to Mantine to fix this:
https://github.com/emotion-js/emotion/issues/3004

### What version of @mantine/hooks page do you have in package.json?

5.10.4

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You can provide custom emotion cache, see docs – https://mantine.dev/theming/emotion-cache/

**Comment by mcmxcdev** [comment]
Hmm, but this should be a general solution to avoid the issue reported by webhint: https://webhint.io/docs/user-guide/hints/hint-meta-charset-utf-8/

I understand that styles are prepended to avoid overriding others, but could they not be prepended but AFTER meta tags to solve this?

**Comment by mcmxcdev** [comment]
Hmm, but this should be a general solution to avoid the issue reported by webhint: https://webhint.io/docs/user-guide/hints/hint-meta-charset-utf-8/

I understand that styles are prepended to avoid overriding others, but could they not be prepended but AFTER meta tags to solve this?

**Comment by rtivital** [comment]
It is tricky to make it work with ssr. For now, you can implement it on your side with a custom emotion cache.

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
