### ISSUE TITLE
CSSObject from Mantine and one from emotion are not compatible

### ISSUE THREAD

**Issue by strblr** [mantinedev/mantine#3633]
### What package has an issue

@mantine/core

### Describe the bug

Hello,

Here is a minimal reproduction of the bug:

```ts
import { Global, CSSObject } from "@mantine/core";

const hover: CSSObject = {}

export function App() {
  return (
      <Global
        styles={{
          ".my-box": {
            ...hover
          }
        }}
      />
  );
}
```

This code gives me a TS error on the ".my-box" key that reads as follows:

```
TS2322: Type '{ [propertiesName: string]: CSSInterpolation; accentColor?: Property.AccentColor | (Property.AccentColor | undefined)[] | Property.AccentColor[] | undefined; ... 909 more ...; ref?: string | undefined; }' is not assignable to type 'CSSInterpolation'.
Type '{ [propertiesName: string]: CSSInterpolation; accentColor?: Property.AccentColor | (Property.AccentColor | undefined)[] | Property.AccentColor[] | undefined; ... 909 more ...; ref?: string | undefined; }' is not assignable to type 'undefined'.
```

It looks like `CSSObject` from Mantine and `CSSObject` from `@emotion/react` are not compatible.

I was unable to reproduce this in codesandbox.
I'm using `@emotion/react` version 11.10.6, and the latest Mantine alpha version.

### What version of @mantine/hooks page do you have in package.json?

next

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Global component type was fixed in 6.0
