### ISSUE TITLE
create your own variants. For example, if I want to create a new button (and I don't want to override the existing variants) I 

### ISSUE THREAD

**Issue by zakidze** [mantinedev/mantine#3634]
Before Mantine I was using Chakra. In Chakra you could create your own variants. For example, if I want to create a new button (and I don't want to override the existing variants) I could create my own variant and use it like this:

```javascript
<Button variant="myVariant">Click me</Button>
```

I tried to do the same in Mantine but didn't work. My solution was to create a new component `<MyNewButton />`. But I think it would be nice to have the variant alternative.

_Originally posted by @rfsan in https://github.com/mantinedev/mantine/discussions/1454_
      
_____________
addition take a look at this looking for the same api :
https://chakra-ui.com/docs/styled-system/component-style

**Comment by zakidze** [comment]
https://chakra-ui.com/docs/styled-system/component-style

take look at this

**Comment by rtivital** [comment]
You can do it in 6.0 – https://v6.mantine.dev/changelog/6-0-0/#variants-and-sizes-on-mantineprovider

**Comment by zakidze** [comment]
exactly cant wait for version 6 to be released ..also please add example
costum names : insted of "variant"  i wanna name it "intent" or  i can add
compltly  anathor prop with costum name and costum  variables "same as
variants"

example i can have button


<button variant="grayish" size="xl" modifierVariant="superbig">

also provide typescript intelesecse for thoes costum variants

in chakra there is a CLI that generate  intelesece for costum variants

Le mer. 1 mars 2023, 09:21, Vitaly Rtishchev ***@***.***> a
écrit :
