### ISSUE TITLE
Providing `styles` for List.Item doesn't apply styles

### ISSUE THREAD

**Issue by DenisIrkhin** [mantinedev/mantine#3637]
### What package has an issue

@mantine/core

### Describe the bug

Providing `styles` for List.Item doesn't apply styles

https://stackblitz.com/edit/react-ts-edldxw?file=App.tsx

we see [Object object] on the Item 

<img width="2788" alt="image" src="https://user-images.githubusercontent.com/20629939/222262180-6133a649-c86d-4589-871a-ca1610dc41e5.png">

### What version of @mantine/hooks page do you have in package.json?

5.10.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://stackblitz.com/edit/react-ts-edldxw?file=App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is correct behavior, `styles` ca only be added to `List` component. This is how styles api works in all components.
