### ISSUE TITLE
Potential wording mistake on Hovercard Target error

### ISSUE THREAD

**Issue by oenu** [mantinedev/mantine#3638]
https://github.com/mantinedev/mantine/blob/194eb15650d480aa349ebcd5cadc4ad92c8f27ac/src/mantine-core/src/HoverCard/HoverCard.errors.ts#L4
Current error is not clear as it states a component should be of a type not supported (run on sentence), suggest change to
```
HoverCard.Target component children should be an element or a component that accepts ref. Fragments, strings, numbers and other primitive values are not supported
```
if I understand it correctly

**Comment by rtivital** [comment]
Fixed in 6.0.1
