### ISSUE TITLE
NumberInput controls not rendered properly in Safari

### ISSUE THREAD

**Issue by tibotiber** [mantinedev/mantine#364]
Hello.

I'm using `NumberInput` from `@mantine/core` version 3.1.0 and getting the following controls on Safari 14.0.2 (macOS):

<img width="78" alt="Screenshot 2021-11-01 at 2 19 58 PM" src="https://user-images.githubusercontent.com/5635553/139630140-6a1b473e-6ff4-474b-96d2-a8a8978b9e05.png">

It goes away if I zoom out the browser (Cmd -) and appears at the default or higher zoom levels. I'm not able to reproduce that on the docs page. I can fix it by adding `margin-top: 0; margin-bottom: 0;`. That's a pretty bare repo with not much that could interfere with the CSS so not sure where this comes from. Is it on my end or a fix could be added?

**Comment by rtivital** [comment]
Hi @tibotiber did you include `GlobalStyles` component – https://mantine.dev/theming/create-styles/#globalstyles-component

It sets box-sizing to border-box in all elements, maybe that is the case

**Comment by tibotiber** [comment]
I was not using `GlobalStyles`, I tried adding it but it doesn't fix the issue.

**Comment by tibotiber** [comment]
I seems the docs have margins set to 0 on `button`, which my local install doesn't. Does that help?

**Comment by rtivital** [comment]
Maybe that's NomalizeCSS, can you try including it? https://mantine.dev/theming/create-styles/#normalizecss

**Comment by tibotiber** [comment]
Bingo! Thank you very much for the super quick support and sorry for not finding that in the docs first.

**Comment by rtivital** [comment]
I'll fix it in future releases to not rely on normalize css in Safari

**Comment by tibotiber** [comment]
Superb! That will help with using the components in apps that are not compatible with normalize css.

**Comment by rtivital** [comment]
Fix was released in `3.1.4`, you can now use NumberInput without normalize.css
