### ISSUE TITLE
Accordion defaultValue not working

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#3644]
### What package has an issue

@mantine/core

### Describe the bug

When using a list for Accordion items, the `defaultValue` doesn't work.

### What version of @mantine/hooks page do you have in package.json?

5.10.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/vibrant-cherry-2mptvg

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by atumas-bananamilk** [comment]
I noticed the issue is caused by `value={opened}` and `onChange={setOpened}` affecting `defaultValue`.

**Comment by atumas-bananamilk** [comment]
This can be fixed by putting `defaultValue` values into the `value` useState when declaring.

**Comment by yverby** [comment]
This is the correct behavior of the component, `defaultValue` is used if the component is not controlled, otherwise if you explicitly pass `value` and `onChange` handler then the component becomes controlled and `defaultValue` is ignored
