### ISSUE TITLE
TextInput Props in 6.0

### ISSUE THREAD

**Issue by charleslabit** [mantinedev/mantine#3646]
### What package has an issue

@mantine/core

### Describe the bug

Label props display warning type
![image](https://user-images.githubusercontent.com/60958454/222414165-dae79dd2-4512-45a5-90bc-71d41763d56e.png)

### What version of @mantine/hooks page do you have in package.json?

5.10.4

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Works correctly on codesandbox – https://codesandbox.io/s/dry-sun-bmelx3?file=/src/App.tsx

**Comment by charleslabit** [comment]
thanks for replying. i just reinstalled and no more warning lol.
