### ISSUE TITLE
Anchor color props doesn't work as expected

### ISSUE THREAD

**Issue by gfazioli** [mantinedev/mantine#3655]
### What package has an issue

@mantine/core

### Describe the bug

In the previous version, the `Anchor` color prop was able to take the right primary shade

```tsx
// v5 works
<Anchor color="myColor">Hello</Anchor>
```

Now, you have to use the index

```tsx
// v6 wrong color
<Anchor color="myColor">Hello</Anchor>
```

```tsx
// v6 works
<Anchor color="myColor.0">Hello</Anchor>
```

The `Title` component works fine

```tsx
// v6
<Title color="myColor">Hello</Title>
```

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in  6.0.1
