### ISSUE TITLE
Unexpected margin with Grid component

### ISSUE THREAD

**Issue by toyi** [mantinedev/mantine#3658]
### What package has an issue

@mantine/core

### Describe the bug

I only tested this on Next 13.1 and 13.2.

Consider this minimal code snippet:

```tsx
import { Grid } from "@mantine/core";

export default function Test() {
  return (
    <Grid>
      <Grid.Col>a</Grid.Col>
    </Grid>
  );
}
```

When you go on this page, a horizontal scrollbar appears. 

This margin `margin: calc(-1rem / 2);` applied to the grid root is the culprit. The scrollbar car be removed by removing the margin.

The code sandbox provides a reproduction of this issue.

### What version of @mantine/hooks page do you have in package.json?

^6.0.0 (6.0.0 locked)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/sandbox/smoosh-butterfly-h34p3s

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Remove the margin, even if I know it's probably there for a good reason.

I'm too new to Mantine to produce a PR right away and it might just be a misunderstanding of how this component works.

**Comment by rtivital** [comment]
https://mantine.dev/core/grid/#negative-margins
