### ISSUE TITLE
DatePickerInput: Missing `clickOutsideEvents` from v5

### ISSUE THREAD

**Issue by filiptammergard** [mantinedev/mantine#3659]
### What package has an issue

@mantine/dates

### Describe the bug

It's not possible to control what types of events should close the date picker when clicking outside. Use repro and first click the date picker input and then the menu. The date picker does not close when the menu opens. 

Radix UI listens to `onPointerDown` on the menu trigger for opening the menu and runs `preventDefault` on the event for the correct focus behavior. That prevents the `onMouseDown` in the date picker to be triggered and it doesn't close. 

Created an issue for it over at Radix UI here: https://github.com/radix-ui/primitives/issues/1903

With Mantine v5 it was solvable by changing `clickOutsideEvents` to `["pointerdown"]`: https://github.com/einride/ui/blob/92bdeb824ffc46988c3f3ac84fec51c2ff2d478b/src/components/controls/dates/DatePicker/DatePicker.tsx#LL84C19

But in v6 that prop is removed. Could it be added?

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/inspiring-phoebe-2bht31?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Add `clickOutsideEvents` in the same way as in v5.

**Comment by rtivital** [comment]
`<DatePickerInput popoverProps={{ clickOutsideEvents: ["pointerdown"] }} />`

**Comment by filiptammergard** [comment]
Ah, that makes sense. Thanks!
