### ISSUE TITLE
Unexpected keyboard interactions in calendar components

### ISSUE THREAD

**Issue by filiptammergard** [mantinedev/mantine#3662]
### What package has an issue

@mantine/dates

### Describe the bug

The keyboard interactions adhere to the accessibility documentation in Mantine: https://mantine.dev/dates/date-picker/#keyboard-interactions

> ArrowRight | Focuses next date in a row that is not disabled
ArrowLeft | Focuses previous date in a row that is not disabled
ArrowDown | Focuses next date in a column that is not disabled
ArrowUp | Focuses previous date in a column that is not disabled

However, I would argue these interactions are unexpected for a number of reasons, since it does not adhere to the [APG guidelines for date grids](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/). You can also compare with the native `<input type="date">`. Guidelines that differ from Mantine behavior include:

- ArrowRight | Moves focus to the next day.
In Mantine you can only move focus within the same week with ArrowRight. If you have focus on the last day of the week, you can't move focus to the first day of the next week with ArrowRight.
- ArrowLeft | Moves focus to the previous day.
In Mantine you can only move focus within the same week with ArrowLeft. If you have focus on the first day of the week, you can't move focus to the last day of the previous week with ArrowLeft.
- ArrowDown | Moves focus to the same day of the next week.
In Mantine you can only move focus within the same month with ArrowDown. If you have focus on the last week of the month, you can't move focus to the first week of the next month with ArrowDown.
- ArrowUp | Moves focus to the same day of the previous week.
In Mantine you can only move focus within the same month with ArrowUp. If you have focus on the first week of the month, you can't move focus to the last week och the previous month with ArrowUp.

I think native keyboard interaction patterns should be used rather than inventing new patterns.

I can see how this is not trivial for example with `minDate` and `maxDate` that disable ranges of days, but it's not impossible.

Happy to help out if you want to do this!

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Focus behavior should be updated to match the guidelines and the native behavior.

**Comment by rtivital** [comment]
Same as with previous issue – you are welcome to submit a PR, please include tests
