### ISSUE TITLE
MediaQuery not working [v6]

### ISSUE THREAD

**Issue by ahetawal-p** [mantinedev/mantine#3671]
### What package has an issue

@mantine/core

### Describe the bug

We are trying to upgrade to v6. 
And seeing this issue with the usage of MediaQuery, v5 seems to be working fine.

```
const renderTitle = () => {
    return (
      <Box>
        <MediaQuery
          largerThan="sm"
          styles={{ display: 'none' }}
        >
          <Text>See me mobile</Text>
        </MediaQuery>
        <MediaQuery
          smallerThan="sm"
          styles={{ display: 'none' }}
        >
          <Text>See me desktop</Text>
        </MediaQuery>
      </Box>
    )
  }
```
On rendering we are seeing both the `Text` instead. 
Also related to this, is we have ThemeOverrides defined like this:
```
export const themeOverride: MantineThemeOverride = {
 breakpoints: {
    xs: 500,
    sm: 800,
    md: 1000,
    lg: 1200,
    xl: 1400,
  },
}
```
This has started complaining: `Type 'number' is not assignable to type 'string'.ts(2322)` 
Do need to update these to strings now ?

### What version of @mantine/hooks page do you have in package.json?

6.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You need to update breakpoints using em – https://mantine.dev/styles/responsive/#configure-breakpoints

**Comment by ahetawal-p** [comment]
Thank you, it seems like code sample here, needs to be updated with the above breakpoint usage. 
https://mantine.dev/core/media-query/#configure-breakpoints

**Comment by rtivital** [comment]
Docs were updated
