### ISSUE TITLE
Nested modal in a drawer, the overlay's z-index is incorrect

### ISSUE THREAD

**Issue by ShookLyngs** [mantinedev/mantine#3675]
### What package has an issue

@mantine/core

### Describe the bug

The problem is that when you put a `Modal` inside a `Drawer`, the nested modal z-index will be incorrect.
It looks like the overlays are covered under the modal and the drawer, here's a scrrensot:
![image](https://user-images.githubusercontent.com/44739165/222886193-5aab9294-fb8f-488c-9833-8bfd68c81dae.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-6-0-0-nested-overlay-zindex-issue-6vbw2o

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You can change modal/drawer z-index with `zIndex` on your side. It is not possible to know what is rendered beneath the modal/drawer – https://codesandbox.io/s/mantine-6-0-0-nested-overlay-zindex-issue-forked-ptmf9j?file=/src/App.tsx

It is not planned to implement any fixes related to this issue on library level.
