### ISSUE TITLE
Test Snapshot failing in Mantine v6, Regenerated className gash

### ISSUE THREAD

**Issue by rasyidf** [mantinedev/mantine#3676]
### What package has an issue

@mantine/core

### Describe the bug

A problem has been identified with Mantine v6 library that is impacting snapshot testing. When attempting to match the snapshot, it is observed that the snapshot keeps changing with each update, making it challenging to perform reliable tests. This issue was not present in the previous version, Mantine v5.

Based on the available information, it appears that the issue may be related to the class hash generator (as shown below). However, further investigation is necessary to confirm this hypothesis and identify the root cause of the problem.

![image](https://user-images.githubusercontent.com/28984914/222902460-2d5682f0-4e6e-4668-b206-89834503fc7c.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
You can provide a static id if you do not want a random id to be generated – `id="your-static-id"`.

**Comment by 7iomka** [comment]
> You can provide a static id if you do not want a random id to be generated – `id="your-static-id"`.

hm, but why this behavior differs from v5?

**Comment by rtivital** [comment]
Logic to generate ids was changed to prevent incorrect browser autocomplete to show up in Chrome and Safari.

**Comment by rasyidf** [comment]
thank you, I've solved this problem by setting the `Math.radom` to constant in the test setup.
