### ISSUE TITLE
AppShell padding error

### ISSUE THREAD

**Issue by Pivigor** [mantinedev/mantine#3678]
### What package has an issue

@mantine/core

### Describe the bug

AppShell uses CSS variables for padding definition like this:

<html>
<body>

    paddingTop: `calc(var(--mantine-header-height, 0) + ${padding})`,
    paddingBottom: `calc(var(--mantine-footer-height, 0) + ${padding})`,
    paddingLeft: `calc(var(--mantine-navbar-width, 0) + ${padding})`,
    paddingRight: `calc(var(--mantine-aside-width, 0) + ${padding})`,

</body>
</html>

If one of these variables is not declared, for example --mantine-header-height, then we get:
<html>
<body>

    paddingTop: `calc(0 + 1rem)`,

</body>
</html>

There will be an error here, and this padding property will be skipped.

I think this is a problem because padding will not work if there is no corresponding component.
For example, if a component was temporarily hidden, this leads to unexpected jumps.

https://github.com/mantinedev/mantine/blob/c2f0c51d610fb0dfd30d44858b414178d4a18aff/src/mantine-core/src/AppShell/AppShell.styles.ts#L35-L38

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

It seems to me that it should be like this:

<html>
<body>

    paddingTop: `calc(var(--mantine-header-height, 0rem) + ${padding})`,
    paddingBottom: `calc(var(--mantine-footer-height, 0rem) + ${padding})`,
    paddingLeft: `calc(var(--mantine-navbar-width, 0rem) + ${padding})`,
    paddingRight: `calc(var(--mantine-aside-width, 0rem) + ${padding})`,

</body>
</html>

**Comment by samzmann** [comment]
AppShell content has no paddingRight after upgrading to v6. I guess it's related to this issue.

**Comment by rtivital** [comment]
Fixed in 6.0.1
