### ISSUE TITLE
Mantine doesn't upgrade to the latest version. It always give a conflict with the previous version of packages.

### ISSUE THREAD

**Issue by FahadJrdev** [mantinedev/mantine#3679]
### What package has an issue

@mantine/core

### Describe the bug

npm install @mantine/core gives error

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
All `@mantine/` packages must have the same version.
