### ISSUE TITLE
Horizontal scrollbar on small screens

### ISSUE THREAD

**Issue by MrHBS** [mantinedev/mantine#368]
![image](https://user-images.githubusercontent.com/30705623/139784373-03f4f1c0-755c-4b1e-a40e-fb8c2863d727.jpeg)

**Comment by rtivital** [comment]
Horizontal scrollbars appear when code overflows its container, it is expected behavior. If you think that this is a bug, please reopen issue with more details.

**Comment by daniel-johnsson** [comment]
Had this issue where I wanted to use a horizontal scroll area, but it would create this tiny scrollbar in the bottom as well. 
Setting `overflow:"hidden"`in appShell will solve this issue
e.g. 
```
styles={{ main: { overflow: "hidden" } }}
```
