### ISSUE TITLE
Title component default styles

### ISSUE THREAD

**Issue by farzindev** [mantinedev/mantine#3680]
### What package has an issue

@mantine/core

### Describe the bug

Is there a reason that we have 2 sets of font styles and line-heights in the Title component by default?

![image](https://user-images.githubusercontent.com/6384978/222918682-f43438f8-31a1-46e7-98ee-69a6a253f3fa.png)

You can also inspect it in this example:
https://ui.mantine.dev/category/hero

Which in that example we have actually 3 font-family. I asume the third one is the custom one.

![image](https://user-images.githubusercontent.com/6384978/222918837-0127e4a7-e3a4-4bcc-86be-d7cdfb9230cb.png)

### What version of @mantine/hooks page do you have in package.json?

6

### If possible, please include a link to a codesandbox with the reproduced problem

provided the link

### Do you know how to fix the issue

I'm not sure if it's intentional.

### Are you willing to participate in fixing this issue and create a pull request with the fix

I'm not sure yet.

### Possible fix

https://github.com/mantinedev/mantine/blob/c2f0c51d610fb0dfd30d44858b414178d4a18aff/src/mantine-core/src/Title/Title.styles.ts#L30

**Comment by rtivital** [comment]
It is expected behavior, Title component extends Text, both components add font-family styles which can be different.
