### ISSUE TITLE
v6 Changelog subdomain defaults to v5

### ISSUE THREAD

**Issue by voctory** [mantinedev/mantine#3684]
### Link to the page
From https://mantine.dev/pages/changelog/, when clicking on "Version 6.0.0", the user is redirected to https://v5.mantine.dev/changelog/6-0-0/.

Some working alternatives are:
- https://mantine.dev/changelog/6-0-0/
- https://v6.mantine.dev/changelog/6-0-0/

### Screenshots

![image](https://user-images.githubusercontent.com/21225415/222945680-18a087d0-1717-4322-94a6-0d9f63e51534.png)

![image](https://user-images.githubusercontent.com/21225415/222945708-993176d7-f3f4-4134-accf-db71875fde88.png)

**Comment by rtivital** [comment]
Fixed
