### ISSUE TITLE
Datepicker shows misaligned weekdays (Mo, Tu, We, Th, Fr, Sa, Su) [v6]

### ISSUE THREAD

**Issue by thomasdvd** [mantinedev/mantine#3686]
### What package has an issue

@mantine/dates

### Describe the bug

see picture below

the 4th of march is not a sunday, it's saturday, and so on...

![image](https://user-images.githubusercontent.com/69515894/222950663-ab4c1d6e-316d-43f0-8294-a2e05667c99f.png)

maybe related to : [issue-2334](https://github.com/mantinedev/mantine/issues/2334) ?

### What version of @mantine/hooks page do you have in package.json?

v6

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Please provide a sandbox that reproduces the issue, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6
It works correctly on the docs website – https://mantine.dev/dates/date-picker/#usage

**Comment by thomasdvd** [comment]
Sorry, tried to recreate it but noticed I had a conflicting dayjs provider
