### ISSUE TITLE
TypeError: value.getTime is not a function

### ISSUE THREAD

**Issue by bogordesaincom** [mantinedev/mantine#3703]
### What package has an issue

@mantine/dates

### Describe the bug

I got error when submit form 

```
TypeError: value.getTime is not a function
```

this:

```
node_modules/@mantine/dates/esm/components/TimeInput/TimeInput.js (150:0)
```
<img width="1137" alt="Jepretan Layar 2023-03-07 pukul 17 33 59" src="https://user-images.githubusercontent.com/51335197/223397444-565769d3-990c-4e63-872e-693815098f38.png">

### What version of @mantine/hooks page do you have in package.json?

5.10.5

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Provide a sandbox with minimal reproduction, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

**Comment by rtivital** [comment]
Most likely you've set date as string, if you can provide a sandbox, feel free to reopen the issue
