### ISSUE TITLE
Wrong link in the pagination documentation leading to 404

### ISSUE THREAD

**Issue by parnavh** [mantinedev/mantine#3704]
### Link to the page where something nasty is located

https://mantine.dev/core/pagination/#controls-as-links

### Exact quote of what is wrong

![preview](https://user-images.githubusercontent.com/45985534/223417580-72c66672-f8da-4d5f-92b0-0df04b1fd8eb.png)

If any of the links on the first pagination is clicked then we are directed to a 404 page. This is happening due to the missing "core" path in the url

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Fixed
