### ISSUE TITLE
v6 DatePicker is missing fullWidth prop

### ISSUE THREAD

**Issue by magnattic** [mantinedev/mantine#3707]
### What package has an issue

@mantine/dates

### Describe the bug

As far as I understand, the v6 `DatePicker` is supposed to replace the v5 `Calendar`.

While trying to update mantine, I noticed though that there is no way to make the `DatePicker` full width.

We need this for our application to stretch the calendar over the whole parent container.
![image](https://user-images.githubusercontent.com/7560166/223485296-88b34b68-f0f8-46cf-9037-0c2ca438c4fc.png)

With v5 we could do this with `<Calendar fullWidth />`.

- Are there any plans to bring this back? 
- Is there a workaround to achieve the same?

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by magnattic** [comment]
Nevermind, I was able to style this with the Styles Api in the end. (https://mantine.dev/dates/date-picker/?t=styles-api)

It's a bit of a hassle because you have to set the width of almost every class, but that's why it's called breaking change, right? ;)

**Comment by DHFW** [comment]
For others (i'm using Tailwind CSS for styling in my app):
```
 classNames={{
              month: 'w-full',
              calendarHeader: '!max-w-full',
              monthCell: 'text-center',
              decadeLevel: 'w-full',
              yearLevel: 'w-full',
              yearsList: 'w-full',
              monthLevel: 'w-full',
              monthsList: 'w-full',
            }}
```

**Comment by dominik-mrugalski** [comment]
I used this styles, and it works fine:

```
.mantine-Calendar-calendarHeader {
  max-width: initial;
}

.mantine-Calendar-month {
  width:100%;
}
```
