### ISSUE TITLE
DatePickerInput: Warning: React does not recognize the `valueFormat` prop on a DOM element

### ISSUE THREAD

**Issue by freva** [mantinedev/mantine#3709]
### What package has an issue

@mantine/dates

### Describe the bug

Adding `valueFormat` to `defaultProps` for `DatePickerInput` gives the following warning in the console:
```
Warning: React does not recognize the `valueFormat` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `valueformat` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-dates-datepickerinput-defaultprops-valueformat-bug-qolxed

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment]
Same problem as in #3702. Unsupported props get spreaded to DOM element and therefore trigger this warning.

This might be the line that spreads the properties. However I haven't really checked this case.
https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/PickerInputBase/PickerInputBase.tsx#L179
