### ISSUE TITLE
Style issue with some months in date picker

### ISSUE THREAD

**Issue by hckhanh** [mantinedev/mantine#3711]
### What package has an issue

@mantine/dates

### Describe the bug

You can see there is the missing part on the top of the picker:

![image](https://user-images.githubusercontent.com/6380436/223602776-83340e54-f41a-4cd9-9da5-397e8cdca04a.png)

This is the normal state of other months:

![image](https://user-images.githubusercontent.com/6380436/223599499-b3b89606-913f-422c-972f-55fdc70f8321.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/dates/date-input/#usage

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed
