### ISSUE TITLE
Breakpoints media queries in the wrong order

### ISSUE THREAD

**Issue by DenisIrkhin** [mantinedev/mantine#3719]
### What package has an issue

@mantine/core

### Describe the bug

Smaller breakpoint media query has higher order than the bigger breakpoint media query
<img width="2571" alt="image" src="https://user-images.githubusercontent.com/20629939/223858931-a5d41536-98f8-4923-993b-18737d3e7b30.png">

It looks like a race or CSS specificity conditions applies here.
If we change `mt={{ base: 24, md: 6,sm: 0 }}` the media queries are back to normal: bigger breakpoint is over smaller one

<img width="2571" alt="image" src="https://user-images.githubusercontent.com/20629939/223859893-735b16c9-c065-4427-a48f-7d10bb3cbb59.png">

### What version of @mantine/hooks page do you have in package.json?

v6.0.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/billowing-dew-7jwwgc?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by DenisIrkhin** [comment]
Probably it's worth to document queries order in here https://mantine.dev/styles/style-props/#responsive-styles ?

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
