### ISSUE TITLE
Modal breaks image crop

### ISSUE THREAD

**Issue by petersamokhin** [mantinedev/mantine#3720]
### What package has an issue

@mantine/core

### The problem
Inside the Mantine popup, the image cropper that uses image transform is broken.
When you try to move the crop area, you can't move it close to the edges.

### Works properly: reactjs-popup
https://codesandbox.io/s/react-easy-crop-forked-yeroj8

### Broken: @mantine/core -> Modal
https://codesandbox.io/s/react-easy-crop-forked-72j6q4
Both v5 and v6 have the same issue.
The code example is minimal: I tried to tweak a thousand params (padding, transform, shadows, normalize CSS, etc) — this doesn't help. 

### Demo
![gif](https://user-images.githubusercontent.com/20628184/223882966-a3f4fbad-a3f4-4636-988b-94b5b2185ca5.gif)

### What version of @mantine/hooks page do you have in package.json?

6.0.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/react-easy-crop-forked-72j6q4

Safari (macOS), Chrome (macOS), Safari (iOS).

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Unfortunately, I have no idea what could go wrong, I tried fixing it myself already.
The issue is related to a 3rd party lib, however, other modals/popups implementations don't have this issue.

### Possible fix

If the modal is open by default, there is no issue, however, if it's closed, then when opening the issue reproduces.
Keeping mounted doesn't help.

### P.S.
Thanks a lot for Mantine! моё увожение, Виталий 😄

**Comment by rtivital** [comment]
Update key once transition ends – https://codesandbox.io/s/react-easy-crop-forked-nm6bde?file=/src/index.js

**Comment by petersamokhin** [comment]
@rtivital thanks a lot! What kind of magic is this, would you be so kind to explain?

**Comment by rtivital** [comment]
set key to rerender component after transition ends
