### ISSUE TITLE
In Multiselect downdown doesnot open after using rightSection props

### ISSUE THREAD

**Issue by ks-himanshub** [mantinedev/mantine#3726]
### What package has an issue

@mantine/core

### Describe the bug

Actually Drop down is opening when I click on Value Area but doesn't open when i click on icon, which I just customised.

`rightSection={<ChevronDown size={14} className="-mt-1" />}`

This is how I am using rightSection props in multiselect component

### What version of @mantine/hooks page do you have in package.json?

^5.10.4

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
From FAQ:

**I've added custom `rightSection` to NativeSelect/Select/MultiSelect, but when I click on dropdown does not open**
Disable pointer events for right section – add `styles={{ rightSection: { pointerEvents: 'none' } }}`

**I've added tooltip/popover/other interactive element to TextInput/Select/DateInput/other input `icon`, but is not working when I hover/click it**
Enable pointer events for icon – add `styles={{ icon: { pointerEvents: 'all' } }}`

**Comment by ks-himanshub** [comment]
Thanks, It worked.

FYI, we can also use 

rightSection: "pointer-events-none"

inside classNames with tailwind css
