### ISSUE TITLE
NumberInput clamp on blur not working with useForm and manually typed numbers

### ISSUE THREAD

**Issue by disillusionedowl** [mantinedev/mantine#3729]
### What package has an issue

@mantine/form

### Describe the bug

Manually type in number 6 or greater and click away in this sandbox:

https://codesandbox.io/s/reverent-firefly-qzf89m?file=/src/App.tsx

### What version of @mantine/hooks page do you have in package.json?

6.0.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/reverent-firefly-qzf89m?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment]
Feel free to checkout the patched version in this sandbox:
https://codesandbox.io/s/mantine-numberinput-issues-2x16u7

You may also try out the patched version in your project to verify the fix.
However there's still a small glitch where the old value reappears for a split second when blurring the component.

**Comment by disillusionedowl** [comment]
@cyantree It works great now, thank you for the fast fix!!

Found one small edge case though, not sure if it's a bug or expected behavior.
Submit via Enter key (before blur) does not clamp&set the new number before the form executes onSubmit.
Repro here, the last input at the bottom:

https://codesandbox.io/s/mantine-numberinput-issues-forked-z4tl0w?file=/src/App.tsx

**Comment by cyantree** [comment]
@disillusionedowl You're welcome!

Thanks for the good catch. That's definitely a bug.
I've fixed it and updated my sandbox accordingly.
Please have a look again:
https://codesandbox.io/s/mantine-numberinput-issues-2x16u7?file=/src/App.tsx

**Comment by disillusionedowl** [comment]
@cyantree Yes, it is perfect now, thank you again!

**Comment by rtivital** [comment]
Fixed in 6.0.3
