### ISSUE TITLE
Select inside Modal is hidden

### ISSUE THREAD

**Issue by vitalijalbu** [mantinedev/mantine#3732]
### What package has an issue

@mantine/core

### Describe the bug

I've created a simple select component inside a Moda, this is the result:
![Screenshot 2023-03-09 alle 15 45 00](https://user-images.githubusercontent.com/40239902/224060372-ba610112-f8d5-4de4-95c3-464f51b9ed4d.png)

```
      <Modal opened={opened} onClose={toggle} title="Crea un log ore" centered size={'lg'}>
        <form onSubmit={form.onSubmit((values) => console.log(values))}>
        <Select data={['React', 'Angular', 'Svelte', 'Vue']} />

        <Checkbox
          mt="md"
          label="I agree to sell my privacy"
          {...form.getInputProps('termsOfService', { type: 'checkbox' })}
        />

        <Group position="right" mt="md">
          <Button type="submit">Submit</Button>
        </Group>
      </form>
      </Modal>
```

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Need maybe to set a default modal body height, or introduce a modal body sub-component.

**Comment by vladgafarov** [comment]
https://github.com/mantinedev/mantine/issues/3503 here is a similar issue with an answer.
But I did this in Modal to fix overflow, worked for me
```javascript
styles={theme => ({
   header: { borderRadius: theme.spacing.xs },
   inner: {
      '> section': {
         overflowY: 'visible',
      },
      '.mantine-ScrollArea-root': {
         overflow: 'visible',
      },
   },
})}

```

**Comment by cyantree** [comment]
Please consider that this workaround might use things that aren't part of the public API and therefore might break in future versions.

If possible I would recommend the solution from #3503. It came also up here: https://github.com/mantinedev/mantine/issues/3725#issuecomment-1461416516

**Comment by rtivital** [comment]
`<Select withinPortal />`

**Comment by vitalijalbu** [comment]
> `<Select withinPortal />`

Thanks, would be useful if you can add it also on doc page 🦾

**Comment by vincenzoraco** [comment]
> > `<Select withinPortal />`
> 
> Thanks, would be useful if you can add it also on doc page 🦾

It is, [https://mantine.dev/core/select/?t=props](https://mantine.dev/core/select/?t=props), third last

**Comment by cyantree** [comment]
I think as frequently as this comes up right now it would be helpful to add an own section that describes use in Modals.

And maybe also add it to the list of breaking changes as IMHO this is one.

**Comment by AJIJIi** [comment]
The best solution is to use `withinPortal` or `popoverProps={{withinPortal:true}}.` But as was mentioned in a lot of places you can customise styles for your `Modal`. 

[Here](https://github.com/mantinedev/mantine/issues/3732#issuecomment-1462302013) was an example how to do it, but for me it didn't work because one of the children still had `overflow == scroll`. So maybe my solution will help someone:

styles={theme => ({
   header: { borderRadius: theme.spacing.xs },
   inner: {
      '> section': {
         overflowY: 'visible',
      },
      '.mantine-ScrollArea-root': {
         overflow: 'visible',
      },
      '.mantine-ScrollArea-viewport': {
         overflow: 'visible !important',
      },
   },
})}

P.S. In any solution don't forget to check `zIndex` of elements
