### ISSUE TITLE
Allow NumberInput to have the ability to be empty

### ISSUE THREAD

**Issue by TrashPandacoot** [mantinedev/mantine#375]
As mentioned in the Github discussion I'd like to implement the ability for the NumberInput component to have the ability to be empty.

The way I'm proposing to do will introduce a breaking change in the `onChange` prop signature from `onChange?(value: number): void` to `onChange?(value: number | undefined): void`

Basically, I'm thinking that onBlur we just check if the input is empty and if it is then call the `handleValueChange` with undefined and that'll bubble up right. And if it's not an empty input it'll work the same as before/use the same logic as before. 

Would have to change the input from `type="number"` to `type="text"` because some browsers (for example safari) the input's onChange `event.target.value` is `""` if the text inputted into the field isn't deemed a valid number string by the browser (i.e. can't distinguish between the field being empty and the value typed being "1." as far as I know). Switching it to `type="text"` and adding the `inputmode` attribute might not be such a bad thing given the [input type for numbers has a handful of downsides](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/)

### Discussed in https://github.com/mantinedev/mantine/discussions/356

<div type='discussions-op-text'>

<sup>Originally posted by **TrashPandacoot** October 29, 2021</sup>
Basically in my use case I have a decent amount of number fields that are optional fields that don't have a natural default value. They're usually things that will be entered at a later date by editing an existing record so currently if one of these optional number fields is left blank it's "we don't know what the value is going to be at this time". 

I took a peak at the NumberInput source and I'm pretty sure this behavior I'm describing is not possible with the current implementation. I'm guessing just based on the `onChange` signature it'd be a breaking change in order to do though.

Is adding this sort of behavior something that makes sense for this library? I'd be happy to contribute if it is, although I'd likely need a bit of guidance as I am a little lost trying to follow the current implementation</div>

**Comment by rtivital** [comment]
Hi @TrashPandacoot, sounds good, you can start development by forking mantine repo, please use `next-minor` as a base branch for your work and PR

**Comment by rtivital** [comment]
Feature implemented and merged, will be released as part of 3.2 release

**Comment by rtivital** [comment]
Released in 3.2, @TrashPandacoot thanks again for your work
