### ISSUE TITLE
initialValues not updating when props changed.

### ISSUE THREAD

**Issue by philldev** [mantinedev/mantine#3750]
### What package has an issue

@mantine/form

### Describe the bug

My expectation is when the props.initialValues changed the form.initialValues should change. I don't know if this is the intended behaviour or it is a bug. 

I needed the initialValues to changed when the component props changes.

```jsx
  const form = useForm({
    initialValues: props.initialValues,
  })
```

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
That is why they are called *initial*Values, not just *values*. It is intended behavior.

**Comment by philldev** [comment]
Thanks for the response. I was able to change the initial value by putting a unique key in the component.
