### ISSUE TITLE
data-autofocus on TextInput doesn't work inside child modal

### ISSUE THREAD

**Issue by farzindev** [mantinedev/mantine#3755]
### What package has an issue

@mantine/form

### Describe the bug

Using `openModal` to create new modal and inside of it there's a component that is using another `openModal`.

Inside of child modal I have a form with `data-autofocus` and it doesn't work. but works with native `autoFocus`.

provided the codesandbox. maybe I'm using openModal in a bad way or something! thanks for the help.

### What version of @mantine/hooks page do you have in package.json?

6.0.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/wizardly-meadow-riofnk?file=/src/Component.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It does not work because it is the same Modal, you can use `autoFocus` in this case. It is not planned to be fixed on library level.
