### ISSUE TITLE
ContextStylesParams size is incompatible with MantineSize

### ISSUE THREAD

**Issue by h2thien** [mantinedev/mantine#3759]
### What package has an issue

@mantine/core

### Describe the bug

The `size` property of `ContextStylesParams` has this type:

https://github.com/mantinedev/mantine/blob/5c1d77209f92fb14377d75c7cdc8d36f84705b63/src/mantine-styles/src/theme/types/MantineTheme.ts#L109

Which is a bit incompatible with the `size` property of most components, which use `MantineSize` and has a `| (style & {})`:

https://github.com/mantinedev/mantine/blob/5c1d77209f92fb14377d75c7cdc8d36f84705b63/src/mantine-styles/src/theme/types/MantineSize.ts#LL1C76-L1C76

### What version of @mantine/hooks page do you have in package.json?

6.0.1

### If possible, please include a link to a codesandbox with the reproduced problem

N/A

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

```tsx
ContextStylesParams {
  size?: string | number | MantineSize
}
```

**Comment by rtivital** [comment]
Types are fully compatible, you can assign MantineSize to `string | number` – https://www.typescriptlang.org/play?#code/C4TwDgpgBAsghgO2ASwRAysgXtAvFAcgA8BnAqAH0JIFtyqCaATewgGwHNXi3WAKEsABOqDlABkUAN4BfAJQBuALAAoUJCiYcUfIJEIxVBAFcaAIwhDlK1QGMA9gkFQ4ALliIUaLXkKkC1g5OwFBm7j46LgpAA

`string | number` is more broad type that allows using any values

**Comment by h2thien** [comment]
My bad, sorry!

<img width="503" alt="image" src="https://user-images.githubusercontent.com/122243953/224706405-316acbf3-c864-476e-bb43-b8fcdebfd2f2.png">
