### ISSUE TITLE
Form controls overflow Modal Header

### ISSUE THREAD

**Issue by isnifer** [mantinedev/mantine#3761]
### What package has an issue

@mantine/core

### Describe the bug

Form controls overflow Modal Header

https://user-images.githubusercontent.com/1788245/224561690-9cace90a-ef55-4d22-badf-6214b798f1ee.mov

### What version of @mantine/hooks page do you have in package.json?

6.0.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/modal/#fullscreen

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by mirel25** [comment]
I also have this issue, you need to add zIndex to make it work, happens on every modal with scroll

**Comment by isnifer** [comment]
@mirel25 in this case header is overflow scroll bat

**Comment by jucopera** [comment]
Same issue, then I wrap my components into a `div` tag, and style it with a fixed `height` and `overflow: hidden auto` to avoid this problem.

**Comment by rtivital** [comment]
Fixed in 6.0.4
