### ISSUE TITLE
JsonInput seems to be completely busted and escapes everything nonstop

### ISSUE THREAD

**Issue by cole21771** [mantinedev/mantine#3763]
Entering text into the box works fine, as you can see here:
![image](https://user-images.githubusercontent.com/14830521/224600888-9473f866-20bc-4691-9ecc-c4fb3f021933.png)

Until you leave the text box. Then it gets escape characters added everywhere:
![image](https://user-images.githubusercontent.com/14830521/224600926-f20be9a9-ccc2-405f-941c-a5683a5c0489.png)

This happens every single time you enter the textbox and leave the textbox which makes it double the amount of escapes every time. This happens with any input including valid JSON:
![image](https://user-images.githubusercontent.com/14830521/224601073-b910643d-d9ce-4f0a-a782-5b275d0814eb.png)

This is happening on my local version as well as the one in the docs right now:
https://mantine.dev/core/json-input/

**Comment by cole21771** [comment]
Just to show it happens with valid JSON too: `{}`
![image](https://user-images.githubusercontent.com/14830521/224601298-1c923d4f-aa81-479b-b07a-7c9b382190c2.png)
![image](https://user-images.githubusercontent.com/14830521/224601214-aa916a65-88f5-4973-9fdb-adaff4b4bf38.png)
![image](https://user-images.githubusercontent.com/14830521/224601242-cce95b6d-17d6-4e3a-8d57-fd2af9aa225a.png)

**Comment by cyantree** [comment]
Seems just to be a little mixup:
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/JsonInput/JsonInput.tsx#L40
It should be `JSON.parse` instead of `JSON.stringify`.
So as a workaround just pass `deserialize={JSON.stringify}` and you should be fine in the meanwhile.

I'll create a PR and try to add tests for it.
