### ISSUE TITLE
@mantine/core loader is cpu intensive

### ISSUE THREAD

**Issue by teaguestockwell** [mantinedev/mantine#3764]
### What package has an issue

@mantine/core

### Describe the bug
I noticed a higher than normal idle cpu usage shortly after replacing ```<span>loading...</span>``` with ```<Loader />``` at the end of a list of cards (around 30% vs 1% previously).

# given a list of items [code sandbox](https://codesandbox.io/s/loader-repro-x9mr7q?file=/src/App.tsx)
![Screen Shot 2023-03-12 at 23 15 00](https://user-images.githubusercontent.com/71202372/224622416-5f2bb91a-a7e2-44e2-bf29-e7c614d27d18.png)

# when a mantine loader is rendered under them
![Screen Shot 2023-03-12 at 23 15 25](https://user-images.githubusercontent.com/71202372/224622477-c1a43e7d-6658-4e0b-959b-30d793346234.png)

# then the cpu usage should be lower or equivalent to a a spinner using keyframes
![Screen Shot 2023-03-12 at 23 15 17](https://user-images.githubusercontent.com/71202372/224622655-f5530225-b22a-4785-adc6-febabddd852b.png)

```
.spinner {
  display: inline-block;
  position: relative;
  width: 80px;
  height: 80px;
  background-color: initial;
}
.spinner div {
  box-sizing: border-box;
  display: block;
  position: absolute;
  width: 64px;
  height: 64px;
  margin: 8px;
  border: 8px solid blue;
  border-radius: 50%;
  animation: spinner 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
  border-color: blue transparent transparent transparent;
}
.spinner div:nth-child(1) {
  animation-delay: -0.45s;
}
.spinner div:nth-child(2) {
  animation-delay: -0.3s;
}
.spinner div:nth-child(3) {
  animation-delay: -0.15s;
}
@keyframes spinner {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}


const OtherLoader = () => {
  return (
    <div className="spinner">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  );
};
```

### What version of @mantine/hooks page do you have in package.json?

6.0.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/loader-repro-x9mr7q?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by teaguestockwell** [comment]
- do you know if there is a way to make this more performant
- if this is not the intended use because this component has an animation should it be a warning in the docs so other dont make the same mistake?

**Comment by rtivital** [comment]
> do you know if there is a way to make this more performant

No

> if this is not the intended use because this component has an animation should it be a warning in the docs so other dont make the same mistake?

I do not understand what you mean. You render Loader component, it outputs svg element with animation, it is all that component does.

**Comment by cyantree** [comment]
Maybe it's because one is a SVG and one is just a set of animated divs?

For me the difference isn't as huge (around 8% vs. 1%) but still remarkable.

If you activate `Layouts / sec` it's quite shoking:
- The Mantine loader has 60 layouts/sec whereas the other loader has 0.

The difference for style recalcs/sec is also quite high: Mantine 60, other loader 20.

So it could be an approach to redo the Mantine loader with DIVs instead of SVG animations.

**Comment by teaguestockwell** [comment]
The example above does not show a huge perf hit, but when I came across this I found that because I had around 5k dom nodes in a flex right above the loader. That perf hit was significant. 

I think this is a common use case that it should be performant in:

```
const EntityList = () => {
  const {data, isLoading, fetchMore, hasNextPage} = useEntites()
  return <div>
    {data.pages.map((page, i) => (
        <React.Fragment key={i}>
          {page.map((row) => (
            <p key={row.id}>{row.name}</p>
          ))}
        </React.Fragment>
      ))}
    <UseInViewport cb={(inView) => inView && hasNextPage && fetchMore()} />
    {isLoading && <Loader />}
  </div>
}
```

should the mantine loader use the keyframes instead of  animateTransform?

**Comment by rtivital** [comment]
It is not planned to change loader to a div element instead of svg

**Comment by teaguestockwell** [comment]
> It is not planned to change loader to a div element instead of svg

I understand. I don't think it absolutely has to be changed either. It is worth considering adding a note about this is the docs because this is a common use case that can lead to higher then expected cpu draw at idle.
