### ISSUE TITLE
incompatibility issue between the PaperProps and PageProps types. The OmitWithTag function

### ISSUE THREAD

**Issue by rayorole** [mantinedev/mantine#3767]
### What package has an issue

@mantine/core

### Describe the bug

Trying to build Nextjs 13 with Mantine UI gives following error:

Type error: Type 'OmitWithTag<PaperProps, keyof PageProps, "default">' does not satisfy the constraint '{ [x: string]: never; }'.
  Property 'children' is incompatible with index signature.
    Type 'string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal | null' is not assignable to type 'never'.
      Type 'null' is not assignable to type 'never'.

  21 |
  22 | // Check the prop type of the entry function
> 23 | checkFields<Diff<PageProps, FirstArg<TEntry['default']>, 'default'>>()
     |             ^
  24 |
  25 | // Check the arguments and return type of the generateMetadata function
  26 | if ('generateMetadata' in entry) {
error Command failed with exit code 1.

How do I fix this?

### What version of @mantine/hooks page do you have in package.json?

^6.0.1

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Please provide a sandbox that reproduces the issue

**Comment by rtivital** [comment]
@rayorole you are welcome to reopen the issue if you can provide a reproduction
