### ISSUE TITLE
NextJs 12 Link omits component styles, Mantine 6.0 Polymorphic components (Buttons / MenuItems etc)

### ISSUE THREAD

**Issue by zeestack** [mantinedev/mantine#3768]
### What package has an issue

@mantine/core

### Describe the bug

We are using nextjs12 and noticed inconsistent behavior of polymorphic components with nextjs NextLink component. Is there anything we are missing on how to use Link? I also noticed that @mantine/next does not export NextLink component as well. 

Secondly, NextLink works with buttons but all styles are being messed up.

`<Menu.Item
        component={NextLink}
        href="/users/"
        icon={<ImProfile size={26} color={theme.colors[theme.primaryColor][6]} />}
      >
        User Management
      </Menu.Item>`

### What version of @mantine/hooks page do you have in package.json?

"@mantine/hooks": "^6.0.1"

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Not sure at this time.

**Comment by rtivital** [comment]
You can use `NextLink` component with Mantine 5.x. You can use `Link` component from `next/link` with Mantine 6.x. It is not planned to add `NextLink` component back in 6.x versions of Mantine. You can either upgrade Next.js to 13 or continue using Mantine 5.x.
