### ISSUE TITLE
DateTimePicker - there is no ability to switch time to 24h format

### ISSUE THREAD

**Issue by Bluepuper** [mantinedev/mantine#3776]
### What package has an issue

@mantine/dates

### Describe the bug

There is no ability in DateTimePicker component to switch to 24h format, so i can't properly localize that component. If i use `locale='ru'` all is translating except PM AM stuff. Users in my country don't even know about existing of AM PM, we use 24h format

### What version of @mantine/hooks page do you have in package.json?

v6.0.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by ForeshadowRU** [comment]
I bet components just use dayjs formatter,
https://day.js.org/docs/en/display/format

Make sure that you are using big H in format
![image](https://user-images.githubusercontent.com/24393965/225217162-22ac9daa-f68e-4795-8a1b-d90ba97a9c69.png)

**Comment by ForeshadowRU** [comment]
And if you don't need AM/PM just remove this
![image](https://user-images.githubusercontent.com/24393965/225217353-a95a9b20-f3d7-4ae7-9826-59d0fe8a1585.png)
from valueFormat

**Comment by rtivital** [comment]
TimeInput component uses input[type=time]. It changes time format based on user preference/language. For example, for a user in the US or GB time input will show input in 12h format, while for a user in Russia it will be 24h format.

**Comment by Bluepuper** [comment]
> And if you don't need AM/PM just remove this ![image](https://user-images.githubusercontent.com/24393965/225217353-a95a9b20-f3d7-4ae7-9826-59d0fe8a1585.png) from valueFormat

Thanks for you answer, fixes one of two problems with AM PM: value format when chosen value displays in input. But actually there is still one AM PM that it doesn't change. This one
![Screen Shot 2023-03-15 at 8 55 08 AM](https://user-images.githubusercontent.com/79052139/225219616-3f3b02fd-cffc-404a-8702-33226b119089.png)

**Comment by Bluepuper** [comment]
> TimeInput component uses input[type=time]. It changes time format based on user preference/language. For example, for a user in the US or GB time input will show input in 12h format, while for a user in Russia it will be 24h format.

It automatically chooses which time format to display? Because I thought it would be changed when the locale property is changed.

**Comment by rtivital** [comment]
Yes, `input[type="time"]` changes it automatically not depending on `locale` prop.
