### ISSUE TITLE
DatePicker doesnt show correct days

### ISSUE THREAD

**Issue by kresogalic8** [mantinedev/mantine#3779]
### What package has an issue

@mantine/dates

### Describe the bug

I am getting the wrong dates in the DatePickerInput. Screenshot is attached for today. I dont have any configuration except importing the DatePickerInput 

![Screenshot 2023-03-15 at 07 52 59](https://user-images.githubusercontent.com/7289406/225229818-8d18d788-b559-4771-b6c5-577e4baaa843.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Does component work correctly for you on the docs website?
https://mantine.dev/dates/date-picker-input/#usage

**Comment by kresogalic8** [comment]
Yeah works fine. I dont know what i am missing in my project.

**Comment by cyantree** [comment]
- Is the problem that the first day of the week is incorrect or do the days not map correctly to the weekdays? In your screenshot your week starts on Tuesday.
- Is it possibly related to timezones and times around midnight?
- I which timezone do you live, UTC +1?

**Comment by cyantree** [comment]
I can't reproduce the issue with your example.
I converted it into a working sandbox:
https://codesandbox.io/s/gallant-mayer-wucozh?file=/src/App.tsx

In your screenshot the first day of the week is Monday, however `firstDayOfWeek={0}` specifies Sunday. Does the screenshot belong to your code snippet?
In this case the labeling of the week days might be the issue.

**Comment by jeanvalentin** [comment]
I tried tweaking a few things and found some interesting information. Using the DatePickerInput on its own works fine. However, I am using it in Next.js and _app.js contains the following:

```javascript
import dayjs from 'dayjs';
import 'dayjs/locale/fr';
dayjs.locale('fr');
```

It seems to conflict with the DatePicker in a way. Removing it solves the issue.

Moreover, in French the first day of the week is Monday, no questions asked. I assume the dayjs `fr` locale shifts the days by 1. By `firstDayOfWeek={0}` I absolutely meant I wanted Monday to be the first day of the week. Dropping the dayjs locale made the first day Sunday. Changing to `firstDayOfWeek={1}` made it Monday again.

From all this, when you say "the labeling of the week days might be the issue", you are probably right, good call.

**Comment by cyantree** [comment]
Thanks for the input @jeanvalentin.
This makes the issue reproducible for me!
I also updated the sandbox:
https://codesandbox.io/s/gallant-mayer-wucozh?file=/src/App.tsx
