### ISSUE TITLE
[SpotlightProvider]:  actionsWrapperComponent  , bottom is miss

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#3783]
### What package has an issue

@mantine/spotlight

### Describe the bug

<img width="725" alt="image" src="https://user-images.githubusercontent.com/124666577/225301151-cfa20749-02bd-4f62-81b9-1bc9ebaf4296.png">

 bottom is miss

```jsx
function ActionsWrapper({ children }: { children: React.ReactNode }) {
    return (
      <div>
        {children}
        <Group
          position="apart"
          px={15}
          py="xs"
          sx={(theme) => ({
            borderTop: `${rem(1)} solid ${
              theme.colorScheme === 'dark'
                ? theme.colors.dark[4]
                : theme.colors.gray[2]
            }`,
          })}
        >
          <Text size="xs" color="dimmed" />
          <Anchor
            size="xs"
            href="#"
            target={'_blank'}
          >
            ChatGPT
          </Anchor>
        </Group>
      </div>
    )
  }

 <SpotlightProvider
      actions={actions}
      highlightQuery
      searchIcon={<IconSearch size={18} />}
      searchPlaceholder="Search..."
      nothingFoundMessage="Nothing found..."
      actionsWrapperComponent={ActionsWrapper}
    >

</SpotlightProvider>
```

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/charming-leakey-jmvsyy?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
- Your sandbox does not work, it throws error
- You can find a working example with actions wrapper component here – https://mantine.dev/others/spotlight/#custom-actions-wrapper-component

**Comment by vaynevayne** [comment]
i fixed the demo https://codesandbox.io/s/charming-leakey-jmvsyy?file=/src/App.tsx

If the content is long, the bottom will disappear.

**Comment by rtivital** [comment]
You can add absolute position to it
