### ISSUE TITLE
SSR breaks in Next.js app with Mantine 6.0.2

### ISSUE THREAD

**Issue by AkshayBarad** [mantinedev/mantine#3785]
### What package has an issue

@mantine/core

### Describe the bug

Hello,

I'm currently working on a Next.js project using the TypeScript template, and I've run into some strange issues with Mantine's SSR. Previously, we were using version 6.0.0 of Mantine, and we did not notice any issues with SSR. However, after upgrading to Mantine 6.0.2, the SSR of styles broke.

We attempted to reproduce the issue on StackBlitz, but we were unable to consistently reproduce it. We don't know exactly what's causing the issue, but we do know that the SSR of Mantine styles is not working properly. When we downgraded our Mantine packages to version 6.0.0, we were unable to reproduce the style flash, indicating that the SSR of Mantine styles is working properly with this version.

Unfortunately, we don't have much time to try to reproduce the issue again right now. However, we'll do so when we have some spare time.

Thank you to all the maintainers for your contributions. We're grateful users of the library.

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You can find a working example in next template – https://github.com/mantinedev/mantine-next-template
It does not have any SSR issues with the latest versions of Mantine and Next.js.

**Comment by jinalskothari** [comment]
Akshay's colleague here.

Thank you for the response. I see; we'll try to learn from it and hopefully be able to get the latest mantine version to work correctly as in the repo.
