### ISSUE TITLE
Disabling modal scrolling in version 6

### ISSUE THREAD

**Issue by alexle-dev** [mantinedev/mantine#3791]
### What package has an issue

@mantine/core

### Describe the bug

In previous versions of mantine, modals didn't have ScrollArea by default, and so I could fit my components inside of them and use ScrollAreas myself when needed. Now, the content doesn't fit in the modal but overflows and a scroll bar is created horizontally which I don't want.

### What version of @mantine/hooks page do you have in package.json?

6.0.1

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Readd the possibility to disable ScrollArea in Modals.

**Comment by ThatOneAwkwardGuy** [comment]
Did you find a way to disable scroll for specific modals?

**Comment by rtivital** [comment]
ScrollArea is not included as part of the Modal in recent releases.

**Comment by conor-kelleher** [comment]
Ah, thanks @rtivital - we had been trying to override the behaviour with a custom `scrollAreaComponent` prop on and older version and didn't realise since upgrading that we can just omit the prop entirely. Thanks 👌

**Comment by tylertyssedal** [comment]
> ScrollArea is not included as part of the Modal in recent releases.

@rtivital How do you recommend disabling the scroll when using `react-beautiful-dnd` inside of a Modal? 

https://ui.mantine.dev/category/dnd

Doesn't seem like there's a way to override the Modal section with the classes `mantine-Paper-root mantine-Modal-content`, and putting a `<ScrollArea />` component in the Modal children doesn't affect the `<DragDropContext />` overflow.

**Comment by tylertyssedal** [comment]
I went ahead and tested out dnd-kit (https://github.com/clauderic/dnd-kit) and it works properly within the modal.

**Comment by pckilgore** [comment]
In case searching sends anyone else here looking simply to disable scroll-area injection:

```tsc
scrollAreaComponent={({ children }) => children}
```
