### ISSUE TITLE
Title: <Text> component flips "/" character when using truncate='start' with file paths

### ISSUE THREAD

**Issue by yousefhany77** [mantinedev/mantine#3792]
### What package has an issue

@mantine/core

### Describe the bug

When using the `<Text>` component from the Mantine library with file paths and the` truncate='start'` prop, the "/" character at the beginning of the path gets flipped to the end of the path. 
For example, the original path `/file/subFile/sample.pdf` becomes `file/subFile/sample.pdf/` 
when using `<Text truncate='start'>`. This behaviour is unexpected and can lead to confusion for users. It would be ideal to have the `<Text>` component preserve the original order of characters in file paths when using the truncate='start' prop.

### What version of @mantine/hooks page do you have in package.json?

5.10.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/frosty-chandrasekhar-96icvk?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Mantine add this `direction: rtl`  to the CSS Class and this is what flips the "/"

**Comment by rtivital** [comment]
`truncate="start"` will not work without `direction: rtl`. It is not planned to be fixed.
