### ISSUE TITLE
Components not visible when using `use-fullscreen` hook

### ISSUE THREAD

**Issue by snowmanwangyal** [mantinedev/mantine#3795]
### What package has an issue

@mantine/core

### Describe the bug

When using the `use-fullscreen` hook, certain components are not visible such as `Select`, `Menu`, `Popover` and etc.

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Can you provide a sandbox that reproduces the issue? Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

**Comment by rtivital** [comment]
@snowmanwangyal you are welcome to reopen the issue if you can provide a reproduction

**Comment by ironmanvim** [comment]
@rtivital  Here is the sandbox that I reproduced for modals - https://codesandbox.io/s/cranky-dawn-gd8tg2?file=/src/App.tsx

**Comment by rtivital** [comment]
Modals are rendered in portal by default, they are not included in the DOM tree of the specific element you want to go fullscreen with. To fix the issue, make sure that all modals are rendered inside that element and set `withinPortal={false}`.
