### ISSUE TITLE
Mantine DateInput and Select overflow with Mantine Modal

### ISSUE THREAD

**Issue by chanhhanh** [mantinedev/mantine#3798]
### What package has an issue

@mantine/core

### Describe the bug

Mantine DateInput and Select overflows with Mantine Modal
![image](https://user-images.githubusercontent.com/72182093/225536976-3e9d0236-dc34-4f1c-9e79-8002e7024376.png)
![image](https://user-images.githubusercontent.com/72182093/225537128-4845fca6-5e24-4d1c-949a-dd11ab35d16b.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/dreamy-noether-jduyiu

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
https://codesandbox.io/s/holy-cdn-2cbp9w?file=/src/App.tsx
