### ISSUE TITLE
Autocomplete does not register diacritic dead keys

### ISSUE THREAD

**Issue by EivydasKoc** [mantinedev/mantine#3799]
### What package has an issue

@mantine/core

### Describe the bug

When using diacritic dead keys 2 characters are typed into Autocomplete instead of a diacritic modified character. e.g.: 

typing on a  Hungarian keyboard layout. If I type AltGr+8 and then 'Z', I should get `Ż`, instead I get `˙Z`. This can be easily replicated in your own [autocomplete demo](https://mantine.dev/core/autocomplete/).

### What version of @mantine/hooks page do you have in package.json?

"@mantine/core": "^5.10.2", "@mantine/hooks": "^5.10.2"

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by gergelyfabian** [comment]
Thank you for this bug report!

**Comment by gergelyfabian** [comment]
To be more exact, this is an issue only in Firefox, it works in Chrome.

To be exact only `˙` appears when I type `˙Z`, on Firefox.

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
