### ISSUE TITLE
Intermediate !== Indeterminate

### ISSUE THREAD

**Issue by rubjo** [mantinedev/mantine#38]
Sorry to be that guy. :D

![Skjermbilde 2021-05-07 kl  10 43 46](https://user-images.githubusercontent.com/42270947/117423627-37360200-af21-11eb-84f0-4740f8463a7e.png)

**Comment by rtivital** [comment]
Oh, my brain always reads Indeterminate as intermediate, thanks for reporting

**Comment by khushal87** [comment]
@rtivital Only the text needs to be changed here right?

**Comment by khushal87** [comment]
Can I solve this issue, if you haven't started @rtivital?

**Comment by rtivital** [comment]
Yes, sure, please create a PR to next-1.1.0

**Comment by khushal87** [comment]
Thanks :)

**Comment by khushal87** [comment]
Can be closed now. @rtivital

**Comment by rtivital** [comment]
No, let's keep issue open until 1.1.0 release – it will be much more easier to remember what was done

**Comment by khushal87** [comment]
Agreed 💯
