### ISSUE TITLE
Skeleton still appearing when data is loaded on iOS

### ISSUE THREAD

**Issue by enmanuelmag** [mantinedev/mantine#3800]
### What package has an issue

@mantine/core

### Describe the bug

The Skeleton component is displayed even if the content has already been loaded. This only happens on iOS operating system, on desktop browsers (Windows and MacOS) I do not experience this problem. Attached are screenshots of the problem and how it works on desktop browsers.

Example of expected behavior:
https://user-images.githubusercontent.com/7991036/225607324-a20db1c9-8bab-401b-9bd4-55d45bbe8827.mp4

iOS behavior:
https://user-images.githubusercontent.com/7991036/225607748-32aaf068-03e0-4d51-a2ee-2b8f04817e78.mp4

### What version of @mantine/hooks page do you have in package.json?

^5.4.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Please provide a sandbox with minimal reproduction. Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6
Skeleton seems to be working correctly on mantine.dev website.

**Comment by rtivital** [comment]
@enmanuelmag you are welcome to reopen the issue if you can provide a sandbox with reproduction

**Comment by arel** [comment]
I also encountered this issue on Mantine version 4.2.4 (which is old, but it looks like this issue was never addressed) on iOS only.

I couldn't easily reproduce it on codesandbox on either version 4.2.4 or the latest (6.0.8), so no help there, sorry.
