### ISSUE TITLE
Accordion - several lowercase letters are cut off

### ISSUE THREAD

**Issue by zachspiel** [mantinedev/mantine#3810]
### What package has an issue

@mantine/core

### Describe the bug

Within the Accordion.Control component, the bottom part of several letters are cut off. Some examples are g,y,p, and q.

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-core-accordion-bug-6sckmd?file=/src/App.tsx:265-329

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Increase the padding of the Accordion.Control component to account for these letters.

**Comment by cyantree** [comment]
An easy fix might be moving the padding from the `button.mantine-Accordion-control` to `span.mantine-Accordion-label`.

**Comment by zachspiel** [comment]
> An easy fix might be moving the padding from the `button.mantine-Accordion-control` to `span.mantine-Accordion-label`.

Thanks for pointing me in the right direction!
