### ISSUE TITLE
Mantine Date Language issue

### ISSUE THREAD

**Issue by LarryTheFatCat** [mantinedev/mantine#3811]
### Link to the page where something nasty is located

https://mantine.dev/dates/dates-provider/

### Exact quote of what is wrong

Not a quote but the issue is that in the clickable date is written in kyrgyz, not sure if that was on purpose 
![image](https://user-images.githubusercontent.com/83801755/225789307-3550ef3e-7219-43b8-b12d-e35e2187546a.png)

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
It is not kyrgyz, it is Russian. Demo shows how to change language on DatesProvider. `ru` locale stands for Russian language.
