### ISSUE TITLE
DateInput: Sometimes the value changes when editing the form value directly

### ISSUE THREAD

**Issue by ot07** [mantinedev/mantine#3818]
### What package has an issue

@mantine/dates

### Describe the bug

When deleting characters one by one in the `DateInput` form, the year field will convert to four digits when it reaches two digits in length.

https://user-images.githubusercontent.com/22608727/225989686-29ee0099-b04c-4692-a604-b52537c90ce8.mov

This issue occurs under the following circumstances:
- When controlling the state (using `value` and `onChange` props).
- When the calendar (dropdown) inside `DateInput` is not open.

When the calendar is open, you can delete the form values normally as shown in the following video.

https://user-images.githubusercontent.com/22608727/225990045-9233cbca-d993-4bb5-8ce0-c49d4f23ade9.mov

### What version of @mantine/hooks page do you have in package.json?

6.0.0, 6.0.2 (I have checked with these two versions.)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-v6-date-input-issue-i8j54d?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I have a potential solution (at least, it passes the `DateInput` test suite). So if this behavior is not expected, I would like to work on a pull request.

**Comment by ot07** [comment]
@rtivital 

Hello, I've created a pull request to address this issue. As this is my first time creating a pull request, I'm a bit concerned that I might have missed something. If you notice any problems, please let me know.
Thank you!

**Comment by rtivital** [comment]
Fixed in [7.2.2](https://github.com/mantinedev/mantine/releases/tag/7.2.2)
