### ISSUE TITLE
[@mantine/form] Form reorderListItem doesn't update validation errors

### ISSUE THREAD

**Issue by Alf-Melmac** [mantinedev/mantine#3827]
### What package has an issue

@mantine/form

### Describe the bug

While reordering list items I would expect the errors to update accordingly. Means that the errors are also reorder. Currently, an error remains at the index where the validation failed.
In the codesandbox click in the second input to trigger the on blur validation and swap the form list items with the button afterwards

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/form-list-reorder-validation-update-yuyw1x

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Reorder the error state the same way the values change

**Comment by rtivital** [comment]
Fixed in 6.0.5
