### ISSUE TITLE
[@mantine/dates][v5.x] Calendar - Setting max date to the first of month has some unintended behaviors and breaks UI

### ISSUE THREAD

**Issue by MarcieMarc425** [mantinedev/mantine#3830]
### What package has an issue

@mantine/dates

### Describe the bug

When setting the maxDate of the Calendar component to the first day of any month, the first date value does not seem to actually register in the calendar. It causes weird behavior such as not being able to go to the next month (ie max date is April 1st, but I am only able to select as far as March in the month selector, or in the screenshot example, when used with `hideOutsideDates`, somehow the outside dates show up in the Calendar view, and the max date becomes blank.) The screenshot below uses this setting (the parse function is from date-fns, which converts to native Date. Just using native Date also causes same issue):

```jsx
<Calendar
  maxDate={parse('01/03/2023', 'dd/MM/yyyy', new Date())}
  hideOutsideDates
/>
```

![CleanShot 2023-03-20 at 11 32 10](https://user-images.githubusercontent.com/32941251/226240369-22e667c5-fd81-4b68-9eb9-fa9577d6deb9.png)

### What version of @mantine/hooks page do you have in package.json?

5.10.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Upgrade to v6.x of @mantine/dates.

**Comment by rtivital** [comment]
Please provide a sandbox that reproduces the issue. Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

Note that, patches for 5.x versions are not planned to be released.

**Comment by MarcieMarc425** [comment]
> Please provide a sandbox that reproduces the issue. Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6
> 
> Note that, patches for 5.x versions are not planned to be released.

Here is the [link](https://codesandbox.io/s/mantine-dates-v5-x-max-dates-calendar-view-bug-ipi1k4) to the reproduced issue in sandbox.

I have also looked into 6.x versions, seems like this is no longer reproducible and fixed in 6.x versions of @mantine/dates. So I guess the resolution is just to upgrade to v6.

**Comment by rtivital** [comment]
Okay, then the issue if considered to be fixed – there are no patches planned for 5.x version.
