### ISSUE TITLE
onBlur issue with NumberInput when using formatter on numbers greater than 999 in 6.0.3+

### ISSUE THREAD

**Issue by disillusionedowl** [mantinedev/mantine#3850]
### What package has an issue

@mantine/core

### Describe the bug

Click once into input and then immediately click once outside input on canvas:

https://codesandbox.io/s/mantine-numberinput-issues-forked-pqqlmf?file=/src/App.tsx

Happens with any number greater than 999.

Is it a bug or is my formatter function incorrect somehow?

Possibly related to #3756.

### What version of @mantine/hooks page do you have in package.json?

special build because 6.0.3 was not available in sandbox yet

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-numberinput-issues-forked-pqqlmf?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Generally I think that by default any formatting should be stripped during editing and reapplied during onBlur, serving only as a visual aid this way. Such approach would probably work around this bug (if it's a bug).

**Comment by cyantree** [comment]
Generally, when you set a custom `formatter` you may need to set an appropriate `parser` to otherwise your as DE formatted number will be interpreted back as EN which interprets "." (thousands separator in DE) as fraction in EN.

See my modified example:
https://codesandbox.io/s/mantine-numberinput-issues-forked-rdc64q

**Comment by disillusionedowl** [comment]
Thank you @cyantree , I must have missed the existence of the `parser` prop in the docs, I am sorry about that! I was too focused on the `formatter` prop alone and did not realize I would also need one more function to convert it back to a raw model number. Makes total sense now.

Here is the solution again for anyone else reading this:

```js
<NumberInput
  min={1}
  max={1000000}
  step={1}
  precision={2}
  parser={(numberString) => {
    return numberString.replace(/[. €]+/g, '').replace(',', '.');
  }}
  formatter={(number) => {
    return new Intl.NumberFormat("de-DE", {
      notation: "standard",
      style: "currency",
      currencyDisplay: "narrowSymbol",
      currency: "EUR",
      maximumFractionDigits: 2
    }).format(number);
  }}
  {...mantineForm.getInputProps("someNumber")}
/>
```
