### ISSUE TITLE
Wrong overlay z-index when calling openConfirmModal in an open modal

### ISSUE THREAD

**Issue by Elvincth** [mantinedev/mantine#3859]
### What package has an issue

@mantine/modals

### Describe the bug

When calling the openConfirmModal function with a parent modal opened, the overlay z-index seems to be wrong, making the overlay behind the parent modal.

Before:
<img width="658" alt="Screenshot 2023-03-22 at 11 44 13 AM" src="https://user-images.githubusercontent.com/6602723/226877794-39890d40-55b8-400e-b44c-5a5600f26f29.png">
023-03-22 at 11.44.42 AM.png…]()

Fixed by altering the z-index:
<img width="1125" alt="Screenshot 2023-03-22 at 11 44 42 AM" src="https://user-images.githubusercontent.com/6602723/226877744-feedb3c9-17d8-4d49-ba35-24d47b0bada2.png">

### What version of @mantine/hooks page do you have in package.json?

v6.0.4

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Change the overlay z-index higher?

**Comment by rtivital** [comment]
You can specify z-index on your side. There is no way of knowing how you will open the modal on library side.

`openConfirmModal({ zIndex: 1000 })`

**Comment by Elvincth** [comment]
> You can specify z-index on your side. There is no way of knowing how you will open the modal on library side.
> 
> `openConfirmModal({ zIndex: 1000 })`

Understand, thx!
