### ISSUE TITLE
Default button variant has different height/padding

### ISSUE THREAD

**Issue by LeunensMichiel** [mantinedev/mantine#3864]
### What package has an issue

@mantine/core

### Describe the bug

See title.
Default button has a different height/padding than all the other variants. (one or two pixels though):

**My Project:**
![My project](https://user-images.githubusercontent.com/18447679/226946773-46641eb3-4f62-4bc4-9842-4f7fba503217.png)

Basic setup:
```
<Flex gap="sm" mt={18} justify="flex-end">
	<Button variant="default">Cancel</Button>
	<Button variant="outline" color={color}>
		Confirm
	</Button>
</Flex>
```

**From the docs:**
![From the docs](https://user-images.githubusercontent.com/18447679/226946949-a5a3a01b-479a-48fb-8b04-b28fa617f992.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.4

**Comment by rtivital** [comment]
All buttons have exactly the same height, it can be seen clearly on both of your screenshot. You can also measure elements in your devtools to get exact height values or use rulers.

<img width="1340" alt="Снимок экрана 2023-03-22 в 19 13 10" src="https://user-images.githubusercontent.com/10353856/226950865-87a605e5-4255-4f40-aad5-fed7a452ce4d.png">

**Comment by LeunensMichiel** [comment]
I'm sorry, you're right. Optical weight makes it look like it's smaller. Closing this issue.
