### ISSUE TITLE
DatePickerInput's Calendar is clipped when placed inside Modol

### ISSUE THREAD

**Issue by cyc1ingsir** [mantinedev/mantine#3865]
### What package has an issue

@mantine/dates

### Describe the bug

It can be reproduced with this minimal code:
```js
<Modal opened={true}>
        <Stack>
          <Button>One</Button>
          <Button>Two</Button>
          <DatePickerInput/>
          <Button>Three</Button>
        </Stack>
</Modal>
```
When this is used with `v6.0.4` it looks like this:
![image](https://user-images.githubusercontent.com/2297037/227013360-37e2df04-c9e8-4b36-9ee5-d52d01a08353.png)

With `v6.0.2` like this:
![image](https://user-images.githubusercontent.com/2297037/227013812-d69aebcf-cf0f-4a7d-8547-b8de1b4fec09.png)

whilst with `v5.10.5` (and `DatePicker`) the calendar is floating above the `Modal`
![image](https://user-images.githubusercontent.com/2297037/227014782-8219a1c1-847b-42c1-9a97-aa2c229f02a5.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://stackblitz.com/edit/vitejs-vite-gspkfn?file=src%2FApp.jsx&terminal=dev

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment]
Please see https://github.com/mantinedev/mantine/issues/3503#issuecomment-1418753806 for the solution.

**Comment by cyc1ingsir** [comment]
Thanks for the hint:
Just for further reference. `withinPortal` needs to passed on to the popover:
```js
<Modal opened={true}>
        <Stack>
          <Button>One</Button>
          <Button>Two</Button>
          <DatePickerInput popoverProps={{ withinPortal: true }}/>
          <Button>Three</Button>
        </Stack>
      </Modal>
```
This seems to solve the issue.
Having seen all the references now, it seems to be a common issue when migrating.

**Comment by cyantree** [comment]
> Just for further reference. `withinPortal` needs to passed on to the popover:
> ```<DatePickerInput popoverProps={{ withinPortal: true }}/>```

You're right. Thanks for the clarification!

**Comment by AJIJIi** [comment]
The best solution is to use `withinPortal` or `popoverProps={{withinPortal:true}}.` But as was mentioned not all components have this property. So alternative is to customise styles for your `Modal`. 

[Here](https://github.com/mantinedev/mantine/issues/3732#issuecomment-1462302013) was an example how to do it, but for me it didn't work because one of the children still had `overflow == scroll`. So maybe my solution will help someone:

```
styles={theme => ({
   header: { borderRadius: theme.spacing.xs },
   inner: {
      '> section': {
         overflowY: 'visible',
      },
      '.mantine-ScrollArea-root': {
         overflow: 'visible',
      },
      '.mantine-ScrollArea-viewport': {
         overflow: 'visible !important',
      },
   },
})}
```

P.S. In any solution don't forget to check `zIndex` of elements
