### ISSUE TITLE
PasswordInput's mask toggle icon overlaps with password manager icons

### ISSUE THREAD

**Issue by justinsmid** [mantinedev/mantine#387]
- What package has an issue: `mantine/core`
- What package version are you using: `"@mantine/core": "3.1.4"`

- In which browser and operating system issue occurred: I have tested it in Chrome and Firefox on Linux, but I assume it also occurs on other browsers & OS's.

- Steps to reproduce: Install a password manager extension (such as [LastPass](https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd)), then visit a page with a `PasswordInput` component (like [the docs page](https://mantine.dev/core/password-input/))
![image](https://user-images.githubusercontent.com/34271675/140530946-0a8d24d1-8b91-4259-a9ad-9d3a802551a5.png)

- Do you have an idea how to fix the issue: Shrink the `PasswordInput`'s actual `input` element a bit and style its `rightSection` to match the input such that they are visually indistinguishable. This will cause the mask icon to appear next to password manager icons.
![image](https://user-images.githubusercontent.com/34271675/140530869-f9e5078a-8dd3-4e66-aeb0-01eb361a4c69.png)

- Are you willing to participate in fixing this issue (it's totally fine if not) and create a pull request with the fix: I would prefer not to, but if it's otherwise going to be put on a long backlog I would be willing to do so.

**Comment by rtivital** [comment]
Hi Justin, thanks for reporting, I'll try to fix this issue in next minor release

**Comment by rtivital** [comment]
Fixed in 3.1.5 patch, validated to work with lasspass
<img width="353" alt="Снимок экрана 2021-11-05 в 20 26 04" src="https://user-images.githubusercontent.com/10353856/140555815-19f23b04-ca02-48f1-95e1-f3912ce14bd5.png">
