### ISSUE TITLE
@mantine/core - Appshell's main components padding doesn't update

### ISSUE THREAD

**Issue by LeunensMichiel** [mantinedev/mantine#3879]
### What package has an issue

@mantine/core

### Describe the bug

I have this piece of code in which I want to animate the open/close state of the navbar and sidebar. 
They both change and animate, however the `main` component still has the old `padding-left` value, which is `calc(var(--mantine-navbar-width, 0px) + 1rem);` (with `mantine-navbar-width` still on 15rem instead of 48px). 

Thus the middle part of the `Appshell` stays the same width instead of growing in size. If I manually change `--mantine-navbar-width` to 48px in my devtools, the desired effect is achieved. 

```
<AppShell
	fixed
	header={<Header />}
	styles={{
		main: {
			transition: "padding-left 1000ms ease",
			height: "100%",
		},
		body: {
			height: "100%",
		},
	}}
	navbar={
		<Navbar
			width={{ base: isLeftSideBarOpen ? "15rem" : 48 }}
			sx={{
				overflow: "hidden",
				transition: "width 1000ms ease, min-width 1000ms ease",
			}}
		>
			<ActionIcon variant="default" onClick={toggleLeftSideBar}>
				&#9776;
			</ActionIcon>
		</Navbar>
	}
	aside={
		<Aside width={{ base: isRightSideBarOpen ? '15rem' : 48 }}>
			<ActionIcon variant="default" onClick={toggleRightSideBar}>
				&#9776;
			</ActionIcon>{" "}
		</Aside>
	}
>
	{children}
</AppShell>
```

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by LeunensMichiel** [comment]
Hey, thanks for the quick reply! 
As you can see, I did that in my code example: `width={{ base: isLeftSideBarOpen ? "15rem" : 48 }}`

But the css variable doesn't update after a state switch.

**Comment by rtivital** [comment]
Can you provide a sandbox with minimal reproduction? Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

**Comment by LeunensMichiel** [comment]
Strange, when copying my exact setup to the codesandbox it did update. Perhaps it has something to do with NextJS 13 as this sandbox was a pure React one? 

I'm using this from your comment: https://github.com/mantinedev/mantine/issues/2815#issuecomment-1293214788

I will try to make a NextJS  example asap.

**Comment by rtivital** [comment]
@LeunensMichiel you are welcome to reopen the issue if you can provide a reproduction

**Comment by LeunensMichiel** [comment]
Hi! I've managed to reproduce it: https://codesandbox.io/p/sandbox/agitated-hofstadter-2hlmvb?file=%2FREADME.md
