### ISSUE TITLE
20+ forms causing performance issue because of unneeded re-render when typing

### ISSUE THREAD

**Issue by shakhzodkudratov** [mantinedev/mantine#3881]
### What package has an issue

@mantine/core

### Describe the bug

I have the following [code](https://codesandbox.io/s/sweet-babbage-7z1f4p?file=/src/App.tsx).

When I'm typing, every component is re-rendered because of `const form = useForm()` updates.

Is there any solution for optimizing such components? Is it better to split forms into 3-4 properties each?
<details>
  <summary>Profiling</summary>

![image](https://user-images.githubusercontent.com/37299109/227275449-5c0a16af-d5bf-4898-b601-63eedd20e805.png)
![image](https://user-images.githubusercontent.com/37299109/227275605-7b23b2aa-49c4-49dd-b0a3-026e7c69ca53.png)
![image](https://user-images.githubusercontent.com/37299109/227275723-49ec68ca-30d1-4f06-9983-96c0bafc4dce.png)
</details>

### What version of @mantine/hooks page do you have in package.json?

5.10.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/sweet-babbage-7z1f4p?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
> Is there any solution for optimizing such components?

No, there is no solution for this. `useForm` makes relies on all components being controlled, thus updates are inevitable (parent component rerender with state change).

**Comment by twiddler** [comment]
@shakhzodkudratov Did you stick with your workaround? Or did you find another solution? We are also hitting performance issues with `useForm`. I am wondering whether [`react-hook-form`](https://github.com/react-hook-form/react-hook-form) might be faster. :thinking:

**Comment by twiddler** [comment]
Can you maybe share the key idea of your workaround? I tried wrapping `const form_ = useMemo(() => form), []` and passed on `form_` instead of `form`, but that seems to not make any difference.

**Comment by shakhzodkudratov** [comment]
@twiddler instead of 
```tsx
const form = useForm({
  initialValues: {
    // a lot of properties
  }
})
```

I done:
```tsx
const form1 = useForm({
  initialValues: {
    // some properties
  }
})

const form1Memo = useMemo(() => (<>
  <TextInput {...form1.getInputProps('prop1')} />
</>), [form1.values])
```

**Comment by twiddler** [comment]
Thanks for sharing! :pray:
