### ISSUE TITLE
Hovercard and tooltip text overflows when stacked inside a breadcrumb

### ISSUE THREAD

**Issue by laubonghaudoi** [mantinedev/mantine#3887]
### What package has an issue

@mantine/core

### Describe the bug

As shown in the code sandbox I linked, when a hovercard or a tooltip component is stacked as a breadcrumb item, the hovercard dropdown becomes unable to wrap texts and the text overflows. How to make the dropdown wrap the text with a fixed width just like the non-stacked breadcrumb item?

![image](https://user-images.githubusercontent.com/11172180/227415142-89b4abe5-97b0-411b-84f1-b2616a79ca6b.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/sandbox/objective-zhukovsky-7lfi4w

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Set withinPortal – https://codesandbox.io/p/sandbox/headless-currying-orlz27?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A20%2C%22endLineNumber%22%3A15%2C%22startColumn%22%3A20%2C%22startLineNumber%22%3A15%7D%5D
