### ISSUE TITLE
Bug: Breakpoint issue in the Col component with xs size

### ISSUE THREAD

**Issue by KhaledMohamedP** [mantinedev/mantine#389]
`Bug` 
---
Started using the `Grid` & `Col` components and realized there is a possible bug in the theme settings.  

The min-width for `xs` size should be `0` not `576px` to style for mobile screens.

**Bootstrap settings**

<img width="250" alt="Screen Shot 2021-11-05 at 10 29 47 PM" src="https://user-images.githubusercontent.com/5921853/140594910-2374cc14-f969-4c71-845e-bbdf526c06dc.png">

https://getbootstrap.com/docs/5.0/layout/breakpoints/

`V.S.`

**Mantine settings**

<img width="513" alt="Screen Shot 2021-11-05 at 10 30 12 PM" src="https://user-images.githubusercontent.com/5921853/140594925-8f7dd5d5-e688-411a-a00e-1c9fdb14741a.png">

https://mantine.dev/theming/extend-theme/#breakpoints

Suggestion fix
---

Update the global theme settings 

```
breakpoints: {
    xs: 0,
    sm: 576,
    md: 768,
    lg: 992,
    xl: 1200,
  }
```

---

Please provide following information:
- What package has an issue (@mantine/core, mantine/hooks or other)?
`@mantine/core`

- What package version are you using?
`v3.1.6`

- In which browser and operating system issue occurred?
`Version 95.0.4638.69 (Official Build) (arm64)` on Mac Big Sur

- If possible please attach link to codesandbox with reproduced issue
n/a

- Do you have an idea how to fix the issue?
Yes, update theme setting 

- Are you willing to participate in fixing this issue (it's totally fine if not) and create a pull request with the fix?
Yes, once its confirmed as a bug by others

**Comment by rtivital** [comment]
Hi, configuration is correct, here is how Col works:
- `<Col span={12} />` – 12 span at all sizes
- `<Col span={10} xs={8} />` – 12 span at 0 – 576px, 8 span 577+px
- `<Col span={12} xs={8} sm={6} />` – 12 span at 0 – 576px, 8 span 577px–768px, 6 span 769+px
