### ISSUE TITLE
@mantine/core - Pagination

### ISSUE THREAD

**Issue by catolicasc** [mantinedev/mantine#3893]
### What package has an issue

@mantine/core

### Describe the bug

In version 5 of mantine, the `page` attribute was working with the core update, it stopped working

![image](https://user-images.githubusercontent.com/13219621/227533925-e26bfeec-e32f-40d0-926f-f99f3d688278.png)

![image](https://user-images.githubusercontent.com/13219621/227533987-7e6c8fe7-b4f5-483a-a1db-32a2288d3a8c.png)

My libs 
`
"@mantine/core": "^6.0.4",
"@mantine/hooks": "^6.0.4",
"@mantine/tiptap": "^6.0.4",
`

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/sand-pagination-g72myv

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
It was changed to `value`. Documentation will be updated with next patch.

**Comment by catolicasc** [comment]
> It was changed to `value`. Documentation will be updated with next patch.

Working for me, thanks <3
