### ISSUE TITLE
Style provided in Mantine override style API in Button hover

### ISSUE THREAD

**Issue by wisnupramoedya** [mantinedev/mantine#3899]
### What package has an issue

@mantine/core

### Describe the bug

I utilized the Button using the custom class name with Tailwind. Though, I encountered a problem with the hover when it doesn't change the color as I intended.
![image](https://user-images.githubusercontent.com/62658181/227726503-008c1d11-04b2-4158-8a03-8b99c7aa90bb.png)
The code as shown below.
```
<Button
  classNames={{
    root: 'bg-transparent hover:bg-red-200',
  }}
  styles={{
    root: {
      // I added this after delete the related className (ignore the color difference)
      ':hover': { backgroundColor: '#9CD2F9' },
    },
  }}
>
  Simpan
</Button>
```

When I tried to check, there was an added className that replace all my code.
![image](https://user-images.githubusercontent.com/62658181/227726745-8cc6aed7-8d73-442a-860b-b442ed29de14.png)

I don't know how to resolve this since the not disabled is not on the `styles` parameterization.colour

### What version of @mantine/hooks page do you have in package.json?

^6.0.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/embed/awesome-cannon-81uebd?fontsize=14&hidenavigation=1&theme=dark

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

It might be that custom style should be placed as the important one

**Comment by rtivital** [comment]
Use `&:not([data-disabled]):hover` instead of `:hover`

**Comment by rtivital** [comment]
Fixed in 6.0.5

**Comment by dominictobias** [comment]
How can this be done in the theme object? Would be great if the guide had an example. This seems to do nothing:

```ts
components: {
    Button: {
      classNames: {
        root: {
          '&:not([data-disabled]):hover': 'SOME-CLASS',
        },
      },
      styles: {
        root: {
          '&:not([data-disabled]):hover': {
            background: 'red',
          },
        },
      },
    },
  },
  ```

**Comment by rtivital** [comment]
https://help.mantine.dev/q/nested-inline-styles

**Comment by dominictobias** [comment]
> https://help.mantine.dev/q/nested-inline-styles

Thanks I wanted to style all from a theme override which I managed to do like this:

```ts
components: {
    Button: Button.extend({
      vars: (_theme, props) => {
        if (props.color === 'gray') {
          return {
            root: {
              // Make it more legible otherwise hover is the same as the bg
              '--button-bg': 'var(--mantine-color-gray-7)',
              '--button-hover': 'var(--mantine-color-gray-8)',
            },
          }
        }

        return { root: {} }
      },
    }),
  },
  ```
