### ISSUE TITLE
LoadingOverlay doesn't fit parent container - rather fits entire screen

### ISSUE THREAD

**Issue by cstrat** [mantinedev/mantine#39]
https://codesandbox.io/s/mantine-loadingoverlay-toomuch-g8uqv?file=/src/App.js

> Overlay had absolute position and will take 100% of width and height of parent container. Use it when you need to disable user interactions and indicate loading state, for example, while form is submitting.

Haven't looked under the hood to see why this is happening.

See the example codesandbox, the loading overlay covers the screen including the header div when it should be bound by the `<Paper>` element.

**Comment by rtivital** [comment]
Overlays have position absolute and will take the 100% width and height of first parent with `position: 'relative'`. Guess, need to this to the docs as this is not obvious.

**Comment by cstrat** [comment]
Sorry I didn't get that, I updated the codesandbox and yeah thats perfect.

**Comment by rtivital** [comment]
I'll keep this open to remember to add this to docs

**Comment by rtivital** [comment]
[Released in 1.0.4](https://github.com/mantinedev/mantine/releases/tag/1.0.4)
