### ISSUE TITLE
[V6] Fix mediaQueries in some cases and in docs

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#3901]
### What package has an issue

@mantine/core

### Describe the bug

Related old issue, that I helped with #2550
I see that some parts of the documentation need editing, and maybe also some parts of the code and the docs (like [this one](https://github.com/mantinedev/mantine/blob/fb8170d828684cf3be3e14128119e0eee18df28c/docs/src/docs/theming/functions.mdx))

Only in some places there may have wrong (old) logic (this may have been done unintentionally, but due to refactoring of a large code base)

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You are welcome to submit a PR

**Comment by 7iomka** [comment]
> You are welcome to submit a PR

Can you please tell me which branch I should fork and into which branch I should open pr? dev or master?
