### ISSUE TITLE
Border radius of Card disables for a few milliseconds on hover in Safari browser

### ISSUE THREAD

**Issue by stackrus** [mantinedev/mantine#3917]
### What package has an issue

@mantine/core

### Describe the bug

Description: When hovering over the Card component in Safari browser, the border radius seems to disappear for a split second before reappearing. This issue does not occur on other browsers like Chrome or Firefox.

Steps to reproduce:

- Open the project on Safari browser ([mantine.dev](https://ui.mantine.dev/component/image-card) also)
- Hover over the Card component
- Observe the border radius disappearing momentarily before reappearing
- Expected behavior: The border radius should remain consistent and not disappear on hover.

Actual behavior: The border radius disappears for a few milliseconds on hover.

Additional information:
[Same issue ref](https://github.com/mantinedev/mantine/issues/3216)

**Google Chrome (on Card hover):**
<img width="1728" alt="Screen Shot 2023-03-27 at 13 15 18" src="https://user-images.githubusercontent.com/37145367/227913427-dfa322b0-80d3-49c4-9596-dd33590fa8ae.png">

**Safari (on Card hover):**
<img width="1397" alt="Screen Shot 2023-03-27 at 13 17 43" src="https://user-images.githubusercontent.com/37145367/227913920-c285929b-1a51-4ba9-8701-f11741e34b5b.png">

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

All you need to do is just to add high z-index value for the Image parent 

Mantine library e.g. 

 card: {
        **_zIndex: 1,_**
        position: 'relative',
        height: rem(280),
        backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[6] : theme.colors.gray[0],
        [&:hover .${getStylesRef('image')}]: {
            transform: 'scale(1.03)',
        },
    },

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
