### ISSUE TITLE
DatePickerInput crashes on `type` prop change

### ISSUE THREAD

**Issue by emad-ms** [mantinedev/mantine#3919]
### What package has an issue

@mantine/dates

### Describe the bug

The `type` prop can not be updated since it affects the value type and some other properties as well. I'm not sure this limitation is on purpose and probably can be fixed internally.

By changing  the `type` from `default` to `multiple` or `range` it throws this error:
```
Error in /turbo_modules/@mantine/dates@6.0.4/cjs/utils/get-formatted-date.js (23:17)
Cannot read properties of null (reading 'map')
```

By changing from `multiple` or `range` to `default` it won't throw error but the input entry will get change to `invalid Date`.

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://stackblitz.com/edit/react-ts-scbkog?file=index.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Currently I change the DatePickerInput `key` and `value` by changing `type`

**Comment by cyantree** [comment]
Can you explain why you need this?

I don't know if that's an expected feature as it also changes the data structure as you already mentioned.
So what would be an expected behaviour here? Reset the value when the type changes? Or try to convert it somehow?

For controlled components you also need to make sure to pass the correct value type when changing the type.

**Comment by emad-ms** [comment]
My use case was not an actual user scenario and I hit it while playing around with `<DatePickerInput />` in my local StoryBook controllers.

But what is the point of `permanent` properties? I think the common expectation would be that if there is a `prop` for a React component, then the React component observes it and applies changes respectively.

Maybe it makes sense to have a definition for these sorts of permanent props like "type" and maybe it can throw a descriptive error/warning message into the console. For example how React throws an error if an input changes from an uncontrolled to a controlled state.
React example:

```
A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.
```

**Comment by cyantree** [comment]
I agree that the common expectation is that properties are changable. However I also think it's acceptable if there are exceptions for this. E. g. when changing a specific property isn't considered a common task and making it changable has major implications.

For these cases I think your suggestion of printing a meaningful warning/error is the correct way to go.

Let's get @rtivital 's take on this:
Do you think `type` should be changable without relying on `key` for recreating the whole component? Or should we output a meaningful message describing this limitation.

**Comment by rtivital** [comment]
Yes, it should be possible to have dynamic type. When type changes value should be cleared

**Comment by emad-ms** [comment]
I think it would be helpful in a controlled scenario to throw a warning/error if `type` and `value` are not relevant.
