### ISSUE TITLE
[V6] All hover styles broken (overridden) by internal :not([data-disabled]):hover

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#3920]
### What package has an issue

@mantine/core

### Describe the bug

Last days I try to migrate to v6.

All `&:hover` styles defined for Button (at least, but if you search in source code, you can find also `Chip`, `PaginationControl`) is overridden by internal hover rule, that have the biggest specificity with `:not([data-disabled])`

<img width="332" alt="image" src="https://user-images.githubusercontent.com/18473137/228007622-718c5678-67ca-427f-aad0-c1fb0b9b0c70.png">

The documentation doesn't say how to get around this, I found in the documentation `theme.fn.hover` usage (even if it's not documented) and I thought that it can help me, but not, it is just a wrapper around `&:hover`.

This addition broke all variants of use `&:hover` in Button: in variants on provider level, in sx and styles on component level.

See the repro demo.
This breaking change is not mentioned in the migration guide - maybe this is a bug, maybe not, but, anyway - lets discuss how users who migrate to v6 need to refactor their code for this specific case, and maybe for similar one?
Even if the only advice on how this should be used now is to add `:not([data-disabled])` condition everywhere - it should be reflected somewhere in the documentation in components that can be disabled and whose styles are closely related to hover state styling.

Related: #3899

### What version of @mantine/hooks page do you have in package.json?

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/heuristic-sun-q7div5?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 6.0.5

**Comment by Zenb0t** [comment]
@rtivital Sorry to ping you on a closed issue, but I'm running mantine/core 6.0.10 and the same bug seems to be happening with `ActionIcon` , I assume that  it is related and should have a similar fix. 

Using `&:not([data-disabled]):hover` works as a hot-fix.

**Comment by nammi-kobler** [comment]
``` 
'&[data-selected]': {
   '&, &:hover': {
```

this worked for me. should be added to documentation, instead of being buried in the documentation only for the Select component

**Comment by nammi-kobler** [comment]
for future reference, problem was the `border:` short hand.
splitting them up into `borderWidth`, `borderStyle` and `borderColor` fixed it
