### ISSUE TITLE
style issue with modal overlay

### ISSUE THREAD

**Issue by amr86elgendy** [mantinedev/mantine#3931]
### What package has an issue

@mantine/core

### Describe the bug

we have an issue with modal component exported from @mantine/core
when we are trying to open a modal from inside another modal, we get an unexpected **style issue** (the second modal's overlay position).

export default function App() {
  const [openFirst, setOpenFirst] = useState(false);
  const [openSecond, setOpenSecond] = useState(false);
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <Button onClick={() => setOpenFirst(!openFirst)}>open first modal</Button>
      <Modal opened={openFirst} onClose={() => setOpenFirst(false)}>
        <Text>first modal</Text>
        <Button onClick={() => setOpenSecond(!openSecond)}>
          open Second modal
        </Button>
        <Modal opened={openSecond} onClose={() => setOpenSecond(false)}>
          Second modal
        </Modal>
      </Modal>
    </MantineProvider>
  );
}

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

when we provide the first modal with a property zIndex={-1} it works as expected

**Comment by rtivital** [comment]
Provide a sandbox with **_minimal_** reproduction, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

**Comment by amr86elgendy** [comment]
@rtivital https://codesandbox.io/embed/priceless-glade-kk0guw?fontsize=14&hidenavigation=1&theme=dark
