### ISSUE TITLE
style issue with select component inside a modal

### ISSUE THREAD

**Issue by amr86elgendy** [mantinedev/mantine#3932]
### What package has an issue

@mantine/core

### Describe the bug

we have an issue with Select dropdown list inside a modal.
when we open a select inside a modal whose height is less than dropdown list height, the dropdown list doesn't appear as expected.

export default function App() {
  const [openFirst, setOpenFirst] = useState(false);
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <Button onClick={() => setOpenFirst(true)}>open first modal</Button>
      <Modal opened={openFirst} onClose={() => setOpenFirst(false)}>
      <Select data={[
          'one', 'two', 'three', 'four', 'five'
        ]} />
        <Text>text</Text>
        <Text>text</Text>    
      </Modal>
    </MantineProvider>
  );
}

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by PointSingularity** [comment]
You need to set the ```withinPortal``` (to true) in the ```Select``` component.
