### ISSUE TITLE
[V6] Accordion control padding wrong value

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#3933]
### What package has an issue

@mantine/core

### Describe the bug

After refactor to v6 seems you are mistaken
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/18473137/228281806-2ee8fe4c-0dd7-4b81-8c21-00504a88e3a9.png">

Expected equivalent for `calc(${theme.spacing.sm}px + 4px)` code is one of 2 variants:
1) `calc(${theme.spacing.sm} + ${rem(4)})`
2) theme.spacing.md

Actual value: `calc(${theme.spacing.md} + ${rem(4)})`

So we have wrong result
![image](https://user-images.githubusercontent.com/18473137/228282980-fa089757-512d-4465-8b82-fbb004641141.png)
This isn't critical for me, since I have locally redefined padding, but it may come as a surprise for other users, so bring this small fix in the next update

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
