### ISSUE TITLE
[V6] Accordion Control chevron size still in pixels

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#3935]
### What package has an issue

@mantine/core

### Describe the bug

Chevron size defined in provider: https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Accordion/Accordion.tsx#L27

Then, it used without any transformation in rem: https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Accordion/AccordionControl/AccordionControl.styles.ts#L41

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 6.0.8
