### ISSUE TITLE
Wrong CloseButton position in Modal if no title provided

### ISSUE THREAD

**Issue by alimehasin** [mantinedev/mantine#3936]
### What package has an issue

@mantine/core

### Describe the bug

The CloseButton "X" shows on the left if no title provided

### What version of @mantine/hooks page do you have in package.json?

v6.0.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/ecstatic-sun-5w515r?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Render `ModalBase.Title` even if no title provided

**Comment by 7iomka** [comment]
@alimehasin You don't need to remove condition.
Instead, please add additional styles for close button
```
    marginLeft: 'auto';
    marginRight: 0
```
Since spaceBetween on the parent element controls relations between children, if title is not provided, close button will always be in the same place - on the right.

**Comment by alimehasin** [comment]
@7iomka Make more sense, thanks
