### ISSUE TITLE
Hide Menu with withinPortal when it target is hidden (itself or one of parents)

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#3942]
### What package has an issue

@mantine/core

### Describe the bug

#2535 Happens again, seems previous solution was reverted, and now we all are without fix.
So, community help wanted

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Not planned to be fixed, use Menu with `withinPortal={false}`
