### ISSUE TITLE
[MultiSelect] has enought width but value show ...

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#3949]
### What package has an issue

@mantine/core

### Describe the bug

when wraped by `<Flex>`

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/124666577/228497972-dc47f797-a28c-4181-9fd2-585fbc12da35.png">

I guess the value of the `max- width` is incorrect.
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/124666577/228498353-a9804b8a-ac41-45a0-91cd-730ede4d7559.png">

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/fast-wave-l9kjrl?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by 7iomka** [comment]
Confirm the issue.
In v5 we have this computed styles (I didn't go into detail in source code)
```
    max-width: calc(100% - 20px);
    margin: calc(10px / 2 - 2px) calc(10px / 2);

```

In v6 we have
```
max-width: calc(100% - 1.25rem);
margin: calc(0.625rem / 2 - 0.125rem) calc(0.625rem / 2);

```

But expected value for max-width is
```
max-width: calc(100% - 0.625rem);
```
So this is easy to fix with an PR if you now where is this part in styles in MultiSelect

**Comment by vaynevayne** [comment]
https://github.com/mantinedev/mantine/pull/3958
Thank you, I submitted a pull request.
