### ISSUE TITLE
[Feature Request] RangePicker - option to show two months

### ISSUE THREAD

**Issue by MiguelKorn** [mantinedev/mantine#396]
As the title says, add an option to the RangePicker component to show two months next to each other. See the example below.

![image](https://user-images.githubusercontent.com/15876051/140907869-d3439455-9423-4192-9d13-efd582c72c08.png)

If you're ok with this feature, I'm willing to implement this.

**Comment by rtivital** [comment]
Duplicate of #232
Hi @MiguelKorn thanks for suggestion! @EmilMalanczak have you started working on this issue? If not @MiguelKorn you can work on this.

**Comment by EmilMalanczak** [comment]
Nah, I started working on a Month/Year pickers. If @MiguelKorn wants to work on this maybe I'll leave it for now because a lot of conflicts might appear, what's your opinion @rtivital?

**Comment by rtivital** [comment]
It's fine, I think we will be able to manage conflicts as these features do not intersect that much. @MiguelKorn you can work on this feature, fell free to reach out on Discord in Contributing channel if you have any questions.

**Comment by rtivital** [comment]
Released in 3.2
