### ISSUE TITLE
Upgrade to latest tiptap version

### ISSUE THREAD

**Issue by viennv1709** [mantinedev/mantine#3962]
### What package has an issue

@mantine/tiptap

### Describe the bug

Please upgrade to stable version of tiptap

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment]
Where do you see this?

`@mantine/tiptap` only specifies it as `peerDependency`. So you need to install it separately as is described in the docs: https://mantine.dev/others/tiptap/
Also requesting a beta semver should also satisfy stable releases.

I've tried the install procedure and got stable tiptap packages.
