### ISSUE TITLE
[v6] @mantine/modals does not export `closeContextModal` function

### ISSUE THREAD

**Issue by filipditrich** [mantinedev/mantine#3963]
Exports in [main index file](https://github.com/mantinedev/mantine/blob/f5f19f7f9600bfb5c056cf2c80bf45b50c6d9fa7/src/mantine-modals/src/index.ts) within mantine-modals package is missing `closeContextModal` function from events file.
```
export {
  openModal,
  closeModal,
  closeAllModals,
  openConfirmModal,
  openContextModal,
  modals,
} from './events';
```

Would you look at it please? Thank you!

**Comment by rtivital** [comment]
`closeContextModal` function was never exported from the library – there is not (and was not) such function. To close modal use `closeModal` function.

**Comment by treemmett** [comment]
I'm also confused about this. The docs are referencing a `closeContextModel` as an exported function.

https://github.com/mantinedev/mantine/blob/f70f97f82f1a0a217f95f2feb025534fb5256de9/docs/src/docs/others/modals.mdx#L154-L167
