### ISSUE TITLE
[Feature Request] Add rounded cap option to `RingProgress`

### ISSUE THREAD

**Issue by csandman** [mantinedev/mantine#397]
For the package `RingProgress` from `@mantine/core`, it would be nice to have a `capIsRound` prop to round the ends of the progress bar.  Chakra UI has a similar option in their `CircularProgress` component:

- https://chakra-ui.com/docs/feedback/circular-progress#props
- https://github.com/chakra-ui/chakra-ui/blob/a25203e4d869d66037b2e8fae81a9e7e587de9eb/packages/progress/src/circular-progress.tsx#L174

**Comment by rtivital** [comment]
Thanks for proposal! We will try things out and see if it works as expected for multiple sections

**Comment by rtivital** [comment]
I've tried out `strokeLinecap="round"` like in Chakra and it does not seem to work well with multiple sections, leaving this issue for community to solve.

**Comment by amithkk** [comment]
When multiple sections are involved, is this the expected look for the progressbar? (See Below)

![image](https://user-images.githubusercontent.com/1029727/145842260-7efc6e63-c18c-4cc5-bdb3-025d390abfef.png)

**Comment by rtivital** [comment]
@amithkk the first one

**Comment by amithkk** [comment]
In that case I think I'll pick this up since I need it for a personal project I'm working on anyway.

**Comment by rtivital** [comment]
Okay, thanks!

**Comment by rtivital** [comment]
PR is merged, feature will be available with next minor release 3.5

**Comment by rtivital** [comment]
Added in 3.5.0
