### ISSUE TITLE
[@mantine/core] Select input not expanding on focus if searchable is false 

### ISSUE THREAD

**Issue by KilianB** [mantinedev/mantine#3981]
### What package has an issue

@mantine/core

### Describe the bug

If `searchable` is not set, the `Select` item does not expand on gaining focus with keyboard navigation. This is working if searchable is true.

- Add a select item to the page
- Press **tab** until the select item is focused

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/flamboyant-diffie-itjlo7?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is intended behavior

**Comment by KilianB** [comment]
Is there a possibility and make it controlled with listeners like onFocus?  

And can you please explain the rationality behind this decision as I would like to know if our change would impact accessibility or break any other best practices. 
We have users using the same form hundred times a week and they were confused (and it will save time) when we switched to mantine and it did not open automatically. 

Having a prop to change this behavior would be great, and not opening it results in an inconsistent user experience as some dropdown fields expand on keyboard navigation and others do not.

**Comment by rtivital** [comment]
> Is there a possibility and make it controlled with listeners like onFocus?

Currently, dropdown opened state cannot be controlled.

> And can you please explain the rationality behind this decision

Native select element does not open when it receives focus. On the other hand, you will receive browser autocomplete when you focus/click an input element (which is used for searchable select).

> Having a prop to change this behavior would be great

There are no changes planned to Select (and other components) with its current implementation. It is planned to be revamped in 7.0, after that adjustments to it can be made.
