### ISSUE TITLE
`<Image />`: Styles API doesn't work when using `imageProps`

### ISSUE THREAD

**Issue by SomiDivian** [mantinedev/mantine#3985]
### What package has an issue

@mantine/core

### Describe the bug

`imageProps` prop overrides everything you setup before

```ts
      <Image
        src={url}
        height={250} // 👈
        width={250} // 👈
        styles={{
          image: {
            objectFit: 'cover', // 👈
          }
        }}
        imageProps={{
          style: {
            border: '5px tomato solid'
          }
        }}
      />
```

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/nostalgic-herschel-t1jvpo

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

why not deep-merge the styles?

**Comment by rtivital** [comment]
Fixed in 6.0.6
