### ISSUE TITLE
`useLocalStorage` does not update its state value on `key` change

### ISSUE THREAD

**Issue by klswn** [mantinedev/mantine#3987]
### What package has an issue

@mantine/hooks

### Describe the bug

If a `useLocalStorage` hook's `key` value changes, the `readStorageValue` and `setStorageValue` functions are redefined, but the underlying `value` state is not reset. This causes an incorrect value to be returned from the hook if the `key` changes after initial mount.

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/prod-star-93xppn

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I was able to fix this by adding `useEffect(() => setValue(readStorageValue()), [key])` to the `useStorage` function. I'm unsure if this causes any issues with SSR as I've only tested on a client side application.

**Comment by rtivital** [comment]
Can you please provide a use case where you need dynamic key?

**Comment by klswn** [comment]
Sure, [here's a simple version](https://codesandbox.io/s/practical-lucy-zhf7l6) of how we're using it. Basically we have a component that paginates through a list of objects and we apply a front end filter to an array on that object. We want to save the user's filter preference for each individual object but it's not important enough to save in the db, so we're using `useLocalStorage` for that filter value.

**Comment by rtivital** [comment]
Thanks, I'll see how we can fix it

**Comment by rtivital** [comment]
Fixed in 6.0.9
