### ISSUE TITLE
NumberInput always change the decimalSeparator to "." 

### ISSUE THREAD

**Issue by lmeniconi** [mantinedev/mantine#3988]
### What package has an issue
@mantine/core
### Description
In the Spanish representation of numbers we separate the thousands as "." and the decimals as ",".

The problem in NumberInput is when you put decimalSeparator="," and the component at the moment of calling the parser function changes the decimalSeparator to ".".

This causes the parser function to receive values that cannot differentiate the thousands from the decimals because previously in the formatter function I changed the thousands to ".".

### Do you know how to fix the issue
You could add a prop to check if you want to alter the value passed to the parser, so you can handle the value yourself.
Maybe something like this:

![image](https://user-images.githubusercontent.com/56926557/229600184-01b2143c-7282-4f4a-bf14-9f32250cb07c.png)

**Comment by cyantree** [comment]
Can you please elaborate a bit more or provide an example?
The example in the docs generally seems to work:
https://mantine.dev/core/number-input/#decimal-separator

However where it fails (is this your issue?) is when you input with thousands separator like "10.000,30".

**Comment by lmeniconi** [comment]
An example would be: "10.000,355" in this case if the decimalSeprator was "," the value passed to the parser function would be "10.000.355" because it is modified before being passed. 
In the parser function I would not be able to know what are the thousands and decimals of the value "10.000.355".

**Comment by cyantree** [comment]
I suggest adding an optional prop `thousandsSeparator` which might be a good fit for the current api and easy enough to use.
So in your case you would set `thousandsSeparator='.'`.

The component then would strip these separators in `parseNum()`.

As a future improvement it might also be used to format the number with thousand separators.

What do you think about this?

**Comment by lmeniconi** [comment]
Yes, it sounds nice, plus it fits the current api much better.

**Comment by cyantree** [comment]
Please try out this sandbox which uses the patched version provided in #3990:
https://codesandbox.io/s/thirsty-star-vuh4v4?file=/src/App.tsx
