### ISSUE TITLE
SimpleGrid spacing in breakpoints doesn't work

### ISSUE THREAD

**Issue by kinoli** [mantinedev/mantine#3991]
### What package has an issue

@mantine/core

### Describe the bug

In SimpleGrid, the spacing has no effect in the breakpoints prop.

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
