### ISSUE TITLE
DatePickerInput component inside a modal

### ISSUE THREAD

**Issue by VeniMitev** [mantinedev/mantine#3992]
### What package has an issue

@mantine/dates

### Describe the bug

I have a couple of DatePickerInput components that are contained within a Modal component. When selecting the component, the calendar pop-up gets cut off on top/on bottom where the modal ends. This prevents the selection of certain dates that get cut off. 

Screenshots of issue:

<img width="360" alt="Screenshot 2023-04-03 at 5 12 22 PM" src="https://user-images.githubusercontent.com/97586359/229653805-a7197f1d-7100-40c1-af4c-eb25880dc0a6.png">
<img width="460" alt="Screenshot 2023-04-03 at 5 12 59 PM" src="https://user-images.githubusercontent.com/97586359/229653809-47f488e8-eb60-4b4d-b5a0-18c66a6174d4.png">

### What version of @mantine/hooks page do you have in package.json?

"@mantine/hooks": "^6.0.4",

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Adding a withinPortal or zIndex props, just like the Select component which had the same issue a while back.

**Comment by VeniMitev** [comment]
Forgot to mention. This issue appeared after migrating from v5 to v6 and switching between DatePicker to DatePickerInput components

**Comment by rtivital** [comment]
Set `popoverProps={{ withinPortal:true }}`
