### ISSUE TITLE
Ref passed to the child element inside Modal is initially undefined

### ISSUE THREAD

**Issue by daksh-sagar** [mantinedev/mantine#4002]
### What package has an issue

@mantine/core

### Describe the bug

i've passed a `ref` to the top level element of the child of the Modal but when i try to access it inside an effect using `ref.current` it comes off as `undefined`. I expect the `ref` to hold the value of the underlying dom node.

Please check the below linked sandbox for a reproducible example.

Steps to reproduce - Open the sandbox and check the `console`, it outputs `undefined`.

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/focused-dew-ygzrus?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
If you need this, then create a separate component that will handle this logic – https://codesandbox.io/s/inspiring-pasteur-9id7yq?file=/src/App.js

It is not planned to be changed on Mantine side.
