### ISSUE TITLE
Checkbox input and label same behavior on click handling in CheckboxGroup

### ISSUE THREAD

**Issue by Mudassarali222** [mantinedev/mantine#4005]
### What package has an issue

@mantine/core

### Describe the bug

Hi,
I am using "@mantine/core": "4.2.2" .
My issue about checkboxs in CheckboxGroup.If user click on checkbox input its fine,On the other hand if user click on checkbox lable checkbox changed.No need to this type of behavior.
I need both are clickable with different  behavior.

here is my checkbox code with in checkboxGroup

`
                <Checkbox
                  value={item?.installments?.[1]?.id + ''}
                  disabled={item?.installments?.[1]?.expire}
                  className="handleCheckBoxWidth"
                  style={{ width: '100%' }}
                  wrapperProps={{
                    onClick: item?.coupon_id ? ()=> removeCouponFromInstallment : ()=> handleLabelClick,
                  }}
                  label={
                    <Grid>
                      <Grid.Col span={7}>
                        <Text sx={{ fontSize: '10px' }}>
                          {`${t['second-installment']}`}{' '}
                          <span
                            style={{
                              color: '#298EAE',
                              fontSize: '12px',
                              lineHeight: 1.55,
                              fontWeight: 500,
                            }}
                          >
                            {`${parseInt(item?.installments?.[1]?.amount || 0)}KWD`}.
                          </span>
                        </Text>
                        <Text sx={{ fontSize: '10px' }}>
                          {`${t.Due_date}`}{' '}
                          <span style={{ color: '#666666', fontSize: '10px', lineHeight: '1.55' }}>
                            {momentWithTimeZone
                              .utc(item?.installments?.[1]?.due_date)
                              .tz(Intl.DateTimeFormat().resolvedOptions().timeZone)
                              .format('YYYY-MM-DD')}
                          </span>
                        </Text>

                        {/* <CheckboxLabel
                          label={[
                            `${t['second-installment']}`,
                            `${parseInt(item?.installments?.[1]?.amount || 0)}KWD.`,
                            `${t.Due_date}`,
                            momentWithTimeZone
                              .utc(item?.installments?.[1]?.due_date)
                              .tz(Intl.DateTimeFormat().resolvedOptions().timeZone)
                              .format('YYYY-MM-DD'),
                          ]}
                        /> */}
                      </Grid.Col>
                      <Grid.Col sx={{ textAlign: 'end' }} span={5}>
                        {item?.coupon_id ? (
                          <Text
                            **onClick={()=>console.log('this click is not working ')}**
                            sx={{
                              fontSize: '10px',
                              marginTop: '8px',
                              fontWeight: 700,
                              color: 'red',
                            }}
                          >
                            Remove Coupon
                          </Text>
                        ) : item?.total_installments.length >= 2 ? (
                          <Text
                          **onClick={()=>console.log('this click is not working ')}**
                            sx={{
                              fontSize: '10px',
                              marginTop: '8px',
                              fontWeight: 700,
                              color: '#298EAE',
                            }}
                          >
                            Apply Coupon
                          </Text>
                        ) : null}
                      </Grid.Col>
                    </Grid>
                  }
                />
`
Thanks

@beeman 
@arthurgeek 
@nfbuckley 
@medihack 

#3527 

### What version of @mantine/hooks page do you have in package.json?

4.2.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by Mudassarali222** [comment]
@rtivital sir , 
here are my prevoius code like this

        <CheckboxGroup
          defaultValue={['react']}
          orientation="vertical"
          label="Select your favorite framework/library"
          description="This is anonymous"
          required
        >
          <Checkbox value="react"/>
          <Checkbox value="svelte" label="Svelte" />
          <Checkbox value="ng" label="Angular" />
          <Checkbox value="vue" label="Vue" />
        </CheckboxGroup>
above code result:
![image](https://user-images.githubusercontent.com/75826150/230268465-77d355f6-f192-4220-bde9-8a6dbaad84ef.png)

than i changed 
        <CheckboxGroup
          defaultValue={['react']}
          orientation="vertical"
          label="Select your favorite framework/library"
          description="This is anonymous"
          required
        >
          <div>
          <Checkbox value="react" label="react"/>
          <Text onClick={()=>console.log('line 772')}>here i want to trigger click</Text>
          </div>
          <Checkbox value="svelte" label="Svelte" />
          <Checkbox value="ng" label="Angular" />
          <Checkbox value="vue" label="Vue" />
        </CheckboxGroup>
Screen shot of this code is here
![image](https://user-images.githubusercontent.com/75826150/230268857-ea7b50db-b571-4494-9b2b-44cc7ba128df.png)

this code remove the first element in CheckboxGroup.

Thanks for your answer please guide me

**Comment by zsubzwary** [comment]
@rtivital I am facing the same issue that @Mudassarali222 explained in last comment.
Can you clarify this ?
