### ISSUE TITLE
Drawer not working as expected (probably new user error)

### ISSUE THREAD

**Issue by psantoro** [mantinedev/mantine#4007]
### What package has an issue

@mantine/core

### Describe the bug

I've attached a minimal sample vite/react/typescript app that includes a Drawer.  The Drawer component isn't opening as expected.  When I click the Open Drawer Left button, the drawer is opened, but hidden to the right.  Given that I'm a new mantine user and that the Drawer component is working on the mantine website, I'm sure that I'm doing something wrong and/or maybe I missed something in the documentation/sample code.  The other Drawer open buttons do not appear to work either.

To run the minimal sample after unzipping:
1) npm install
2) npm run dev
3) press o key to open in browser
4) click Open Drawer Left button

Thank you for your assistance.

[drawer-sample.zip](https://github.com/mantinedev/mantine/files/11158320/drawer-sample.zip)

### What version of @mantine/hooks page do you have in package.json?

6.0.6

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please share your example as a sandbox. Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6
