### ISSUE TITLE
DatePickerInput incorrectly displays date range

### ISSUE THREAD

**Issue by Stekac** [mantinedev/mantine#4014]
### What package has an issue

@mantine/dates

### Describe the bug

DatePickerInput component incorrectly displays the date range given the initial value if the value has hours/minutes/seconds or milliseconds more then 0 to a given day.

In my case the values are:
```
[
  new Date("Sat Apr 01 2023 02:35:58 GMT+0200"),
  new Date("Thu Apr 06 2023 02:35:58 GMT+0200"),
]
```

if i try 

```
[
  new Date("Sat Apr 01 2023 02:35:58 GMT+0200"),
  new Date("Thu Apr 06 2023 00:00:00 GMT+0200"),
]
```

it works as expected.

[Image preview](https://ibb.co/WxZVFPC)

### What version of @mantine/hooks page do you have in package.json?

6.0.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/wandering-brook-ricjp4?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Probably trim out the time part from a date before displaying it in the calendar.

**Comment by Stekac** [comment]
@movoid12  thanks i corrected it, its for @mantine/dates

Yes i could trim the "time" part, but i don't think thats the correct way since "Thu Apr 06 2023 59:59:59 GMT+0200" is still 6th of April

**Comment by cyantree** [comment]
I've created the PR #4028 for it.

**Comment by Stekac** [comment]
@cyantree thanks!
