### ISSUE TITLE
`createConverter` function does not take into account user's browser font size setting

### ISSUE THREAD

**Issue by fpolic-profico** [mantinedev/mantine#4018]
### What package has an issue

@mantine/core

### Describe the bug

When using the `rem` unit converter the `createConverter` function does not take into account the user's browser font size setting.

### What version of @mantine/hooks page do you have in package.json?

^6.0.2

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Instead of hardcoding the divisor value to 16, set the value to be `parseFloat(getComputedStyle(document.documentElement).fontSize)`.

**Comment by rtivital** [comment]
`document.documentElement` is not available on server, the function will not work with ssr.

**Comment by fpolic-profico** [comment]
You're right. Same goes for `getComputedStyle`, but I think it makes sense to fix it only on the client side for projects that don't use SSR.

Maybe modifying the existing function is not the best idea, but exporting a new client side function or creating a wrapper class/object that would encapsulate all of the converters could be a better solution?

**Comment by rtivital** [comment]
I'm not planning to introduce this feature anyway. It will not translate well to native CSS in which direction Mantine is going as it relies on dynamic runtime values to set styles of ALL components.

**Comment by fpolic-profico** [comment]
Ok
