### ISSUE TITLE
[Mantine-V6] Modal is cropping Select dropdowns.

### ISSUE THREAD

**Issue by AmitNeuhaus** [mantinedev/mantine#4024]
### What package has an issue

@mantine/core

### Describe the bug

In V6 when scroll is only available inside the modal it seems like the current implementation with scroll-y auto is cropping the dropdown content. See attached picture:

What i have tried:
1. Setting overflow-y of modal-content styles api to visible.(still modal's css class wouldn't let me override this one)
2. Setting select dropdown to position absolute / fixed using style-api.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/51485322/230444835-5f1c95d0-a4fa-4871-b8fb-75c917cb7249.png">

What i chose to do:
3. limiting select dropdown max height.
This solution is not very good because modal should be pretty small in size until openning dropdown. And the dropdown size should not be related to modal size.

What i expect: (Mantine v5)
<img width="497" alt="image" src="https://user-images.githubusercontent.com/51485322/230444643-921992be-4d18-4ac4-926a-5645dc22d15e.png">

### What version of @mantine/hooks page do you have in package.json?

v6

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Set `<Select withinPortal />`
