### ISSUE TITLE
Incompatibility of AppShell with new routers (RouteProvider)

### ISSUE THREAD

**Issue by Francois-BONNIN** [mantinedev/mantine#4026]
### What package has an issue

@mantine/core

### Describe the bug

The structure of the new React-Router (RouteProvider) cannot be used with an AppShell component 

### What version of @mantine/hooks page do you have in package.json?

^6.0.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Hi @Francois-BONNIN you are welcome to reopen the issue if you can provide more information or a sandbox that reproduces the issue
