### ISSUE TITLE
SegmentedControl animation broken

### ISSUE THREAD

**Issue by a35026** [mantinedev/mantine#4032]
### Link to the page where something nasty is located

https://mantine.dev/core/segmented-control/

### Exact quote of what is wrong

Looks like the tab switching animation is broken. 
`transitionDuration` also has no effect. 

### Are you willing to create pull request with the fix?

None

**Comment by rtivital** [comment]
Animations work correctly. For more information see – https://mantine.dev/theming/theme-object/#respectreducemotion
