### ISSUE TITLE
Documentation typo on Calendar plus rewrite

### ISSUE THREAD

**Issue by Qodestackr** [mantinedev/mantine#4040]
### Link to the page where something nasty is located

https://mantine.dev/dates/calendar/

### Exact quote of what is wrong

[Static prop](https://mantine.dev/dates/calendar/#static-prop)
Set static prop to display a calendar that use cannot interact with. It is useful when you want to display data with in calendar view but do not want it to be interactive.

`Set static prop to display a calendar that use cannot interact with`.

Plus, I believe my PR will involve much to improve readability on the entire calendar piece. :+1: 

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
Thanks for reporting, the issue is fixed
