### ISSUE TITLE
React 18 Global Styles Hydration failures

### ISSUE THREAD

**Issue by dr3** [mantinedev/mantine#4047]
### What package has an issue

@mantine/core

### Describe the bug

**Not strictly an issue with the package. Creating this issue to track the issue and help others**

There is a [known hydration issue in React 18](https://github.com/facebook/react/issues/24430). In my experience it only affects Mantine via the use of `<Global />`.

If a user has a unlucky refresh with certain chrome extensions react 18 will fail hydration. When that happens mantine recovers well, except for styles inside a `<Global />` tag. 

The only work around i've found is to avoid use of `<Global />`

### What version of @mantine/hooks page do you have in package.json?

6.0.6

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

May be worth looking into how Mantine could better recover in hydration failures to restore the styles

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
