### ISSUE TITLE
@mantine/notifications, @mantine/form could not be resolved

### ISSUE THREAD

**Issue by elibroftw** [mantinedev/mantine#4053]
### What package has an issue

@mantine/notifications
@mantine/form

### Describe the bug

Error: The following dependencies are imported but could not be resolved:

  @mantine/notifications (imported by C:/Users/maste/Downloads/test-proj/src/App.jsx)

Failed to resolve import "@mantine/form" from "src\Schedules\Schedule8.jsx". Does the file exist?

App works with notifications set to 6.0.6, but not 6.0.7 which is probably why I was confused why the app was breaking all of a sudden when I went to upgrade my deps.

### What version of @mantine/hooks page do you have in package.json?

6.0.7

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Dependencies are resolved correctly on codesandbox – https://codesandbox.io/s/gallant-shadow-tmobht?file=/src/App.tsx
Try reinstalling dependencies and restarting your ide.

**Comment by rtivital** [comment]
The advise is the same – reinstall dependencies

**Comment by elibroftw** [comment]
when I filed the report, I had created a new project just to double check it wasn't my fault. I'll try again but still.
