### ISSUE TITLE
`visible` prop treat `undefined` as `true` in Skeleton

### ISSUE THREAD

**Issue by hckhanh** [mantinedev/mantine#4055]
### What package has an issue

@mantine/core

### Describe the bug

When using `Skeleton` with `visible` and `children`, `Skeleton` will show up when `visible` received `undefined`

### What version of @mantine/hooks page do you have in package.json?

6.0.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/lucid-rain-umnj5w?file=/src/App.js

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by TeLoardBruh** [comment]
The thing is that it can be passed, `undefined` as a boolean as well, it can be fixed as 
`visible?: boolean | undefined = 0;` in the `src/mantine-core/src/Skeleton/Skeleton.tsx` then it will be fixed. But i do not know how to create pull-request for open source.  

Reference for undefined as boolean in ts `https://www.tektutorialshub.com/typescript/typescript-undefined/#:~:text=Undefined%20is%20a%20special%20value,as%20falsy%20for%20boolean%20operations.`

**Comment by cyantree** [comment]
Why do you think this is a problem?
Passing `undefined` is often used equally to not passing the property at all. So in case you omit `visible` the skeleton also stays visible.

**Comment by hckhanh** [comment]
@cyantree @TeLoardBruh  So the default value of `visible` is `true`. I think if `children` still exist, it should not be `true` by default. I think that will make sense.

**Comment by TeLoardBruh** [comment]
oops, I confuse the objective of the skeleton, yes by default it is the correct logic.

**Comment by cyantree** [comment]
> I think if `children` still exist, it should not be `true` by default, it will make sense.

I think changing this would be a breaking change as the documentation explicitly describes the current behaviour:
https://mantine.dev/core/skeleton/#with-content

So IMHO for v6 there's nothing to be done. And for v7 it's for @rtivital to decide whether to change this behaviour. I don't have an opinion on this however I don't see the current behaviour as problematic.
