### ISSUE TITLE
Modal component does not support sx prop

### ISSUE THREAD

**Issue by alexe-dev** [mantinedev/mantine#4058]
### What package has an issue

@mantine/core

### Describe the bug

`<Modal />` component does not support `sx` prop after a change to `ModalProps` type in this commit:

https://github.com/mantinedev/mantine/commit/a013d988540620bc551a6a0af5a1b9dff69a0a80 

`export interface ModalProps
   extends Omit<DefaultProps<ModalStylesNames, ModalStylesParams>, MantineStyleSystemSize>,
     Omit<React.ComponentPropsWithoutRef<'div'>, 'title'>`
 
changed to 
     
`export interface ModalProps extends ModalRootProps`

and as ModalRootProps does not have `sx` prop in it, `<Modal />` does not accept `sx` prop anymore 

my exact usecase is `sx={{ maxHeight: '90vh' }}`

if it was an intended breaking change, then it should be added to CHANGELOG. And please let me know if there is another proper way to handle my use case.
     

### What version of @mantine/hooks page do you have in package.json?

6.0.7

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

add `sx` prop to `ModalRootProps`

**Comment by alexe-dev** [comment]
ps I will use style api to target Modal root for now

**Comment by rtivital** [comment]
Fixed in 6.0.8
