### ISSUE TITLE
Mantine does not mention its non-mobile-first (i.e. "desktop-first") approach anywhere

### ISSUE THREAD

**Issue by dallanlee** [mantinedev/mantine#407]
### Discussed in https://github.com/mantinedev/mantine/discussions/374

<div type='discussions-op-text'>

<sup>Originally posted by **dallanlee** November  2, 2021</sup>
It seems like Mantine follows the mobile first development approach as seen in [Grid - Responsive columns](https://mantine.dev/core/grid/#responsive-columns) (and other components?). There is the initial `span` value for `<Grid />` and the `sm`, `md`, `lg`, etc values change the column span at that size and up. However, in [SimpleGrid - Breakpoints](https://mantine.dev/core/simple-grid/#breakpoints), `cols` sets the starting number of columns but is changed in `breakpoints` with `maxWidth` values, going down rather than up (i.e. not mobile first). Either I'm missing something or this is backwards, isn't it?</div>

**Comment by rtivital** [comment]
@dallanlee please check 3.2 changelog to find out about mobile first approach, I think that we've managed to do everything correctly

**Comment by dallanlee** [comment]
I've been following the progress and it looks great! Well done 👏🏼
