### ISSUE TITLE
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>

### ISSUE THREAD

**Issue by cath-fmarie** [mantinedev/mantine#4070]
### What package has an issue

@mantine/core

### Describe the bug

I tried using a copy button in a menu item but get a nesting warning, when the menu shows up.

<img width="580" alt="Screenshot 2023-04-13 at 14 54 56" src="https://user-images.githubusercontent.com/60520236/231765046-3cb73f3a-bb59-4609-b9db-640ef3dcfcf8.png">

here is the code (litteraly copy pasted from the doc)

```
<Menu.Dropdown style={{display: "flex", justifyContent: "center", alignItems:"center" }}>

                            <Menu.Item>
                                    <Center>

                                <QRCode 
                                    id={`qrCode-${rewardId}`} 
                                    size={140}
                                    style={{marginTop:10,}}
                                    value={"value"} /> 
                                    </Center>
                            </Menu.Item>
                            <Menu.Item>
                            <CopyButton value="https://mantine.dev">
                                {({ copied, copy }) => (
                                    <Button color={copied ? 'teal' : 'blue'} onClick={copy}>
                                    {copied ? 'Copied url' : 'Copy url'}
                                    </Button>
                                )}
                                </CopyButton>
                            </Menu.Item>
```

### What version of @mantine/hooks page do you have in package.json?

6.0.7

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Error message is correct – you should not render button inside another button. Pass `copy` directly to Menu.Item.

**Comment by cath-fmarie** [comment]
That worked thanks a lot! but the copyButton code comes from the documentation, so shouldn't it work?

**Comment by rtivital** [comment]
You've put code from documentation in a wrong place, that is why you've got an error from React.
