### ISSUE TITLE
Fit column content edit

### ISSUE THREAD

**Issue by marinanicolai** [mantinedev/mantine#4073]
### What package has an issue

@mantine/core

### Describe the bug

edit the  tag <Col> to the correct tag <Grid.Col>

### What version of @mantine/hooks page do you have in package.json?

6.0.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/grid-fit-column-content-1ffkuj?file=/src/App.js

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

 <Grid>
     <Grid.Col span="auto">fit content</Grid.Col>    
     <Grid.Col span={6}>2</Grid.Col>
 </Grid>

**Comment by marinanicolai** [comment]
@rtivital 

In the documentation at https://mantine.dev/core/grid/, there is a typo. Instead of 'Col', it should be 'Grid.Col'

![Screenshot from 2023-04-13 13-50-01](https://user-images.githubusercontent.com/22110654/231843663-58e28e7b-4de9-4616-91e4-253fcea92fca.png)

**Comment by rtivital** [comment]
Thanks for reporting, the issue is fixed
