### ISSUE TITLE
`FocusTrap` doesn't remove `aria-hidden=true` attribute

### ISSUE THREAD

**Issue by klswn** [mantinedev/mantine#4079]
### What package has an issue

@mantine/core

### Describe the bug

If a component that renders a `FocusTrap` (Modal, Drawer, etc) is opened via a click handler on a `Menu.Item` that's rendered within a portal, the `aria-hidden=true` attribute is not cleared when the Modal/Drawer is closed, and the page becomes inaccessible.

### What version of @mantine/hooks page do you have in package.json?

6.0.7

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/angry-rgb-x46ub2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by Ben-Kincaid** [comment]
@DanB-dev Do you have a source for your fix? Was it resolved in `use-focus-trap`/`create-aria-hider` or was your fix specific to the closing/listener behavior in `MenuDropdown`/`PopoverDropdown`?

**Comment by Ben-Kincaid** [comment]
Opened a PR that addresses this issue by providing a mechanism for tracking focus trap identity & avoiding the restoration of `aria-hidden` attributes on root nodes if another `useFocusTrap` has already operated on those root nodes. https://github.com/mantinedev/mantine/pull/4118
