### ISSUE TITLE
Error when using Tooltip - Warning: Function components cannot be given refs

### ISSUE THREAD

**Issue by Dan6erbond** [mantinedev/mantine#4080]
### What package has an issue

@mantine/core

### Describe the bug

When I wrap an icon with the `Tooltip` component, I get the following error in the browser, and the tooltip doesn't work:

```js
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `@mantine/core/Tooltip`.
 ````

My code:

```tsx
<Tooltip label="You are seeing this because you haven't added a review yet">
  <IconExclamationCircle color={theme.colors.gray[6]} />
</Tooltip>
```

### What version of @mantine/hooks page do you have in package.json?

^6.0.6 (6.0.7 installed)

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Use `React.forwardRef()` in the `Tooltip` component.

**Comment by rtivital** [comment]
See https://mantine.dev/core/tooltip/#required-ref-prop

**Comment by 7iomka** [comment]
> See https://mantine.dev/core/tooltip/#required-ref-prop

I've been observing lately how more and more users are forcing not to use forwardRef 
because of problems with inheritance and type redefinition
Instead, they use the ref as a prop but with another name, like `inputRef`, `someNeededRef`.
Using such components inside a tooltip will probably be a problem for some users.

**Comment by rtivital** [comment]
Prop to get ref can be configured with `refProp`.
