### ISSUE TITLE
Layout shift on nextjs 13.3.0 using SSR (NOT with new App directory)

### ISSUE THREAD

**Issue by neilgd** [mantinedev/mantine#4081]
### What package has an issue

@mantine/core

### Describe the bug

I'm using nextjs, but not with the new app folder (which I know there are problems with when using Mantine). I am using SSR.

I'm getting massive layout shifts - the initial layout seems to be completely without styles. I'm following (as far as I can tell) the appropriate examples you've kindly provided.

Here's the initial page that flashes up:
![image](https://user-images.githubusercontent.com/1759173/232312246-af1aa36f-4a6c-4823-9675-7d3fe3ebafa1.png)

And here it is once it's rendered properly:

![image](https://user-images.githubusercontent.com/1759173/232312276-80995e86-400d-4463-ae4c-2ef3201c368a.png)

I am doing various things in, eg, the app.getInitiaProps function so I am wondering if this is preventing Mantine from doing its proper initial render?

If you have any ideas on how to troubleshoot this then I'd love to know! You can see it yourself by going here:

https://rawumberstudios.com/n/log-in

And hitting refresh. Thanks!

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Use mantine-next-template as reference, it is known to not have any issues with ssr

**Comment by neilgd** [comment]
@rtivital - Thanks for the reply! I thought I was, but I was overriding the Document classs and using Document.getInitialProps rather than your createInitialProps.

Thanks for pointing me in the right direction!
