### ISSUE TITLE
[V6] Nested modals are broken

### ISSUE THREAD

**Issue by omerfarukdogan** [mantinedev/mantine#4082]
### What package has an issue

@mantine/core

### Describe the bug

I've been using nested modals (multiple modals on top of each other) with Mantine v5.x. Upon upgrading to 6.x, they no longer work as expected. The second modal has no overlay displayed.

### What version of @mantine/hooks page do you have in package.json?

^6.0.7

### If possible, please include a link to a codesandbox with the reproduced problem

v5: https://codesandbox.io/s/wonderful-meadow-zhcpeh?file=/src/App.tsx ; v6 = https://codesandbox.io/s/vigorous-cookies-xlph05

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Set `zIndex` prop – https://codesandbox.io/s/charming-chaum-6k79ls
