### ISSUE TITLE
Loader animation not start until page loads

### ISSUE THREAD

**Issue by zoubingwu** [mantinedev/mantine#4084]
### What package has an issue

@mantine/core

### Describe the bug

Loader is using SVG animation and browser will not start the animation until page loaded. This sometimes made the webpage feels like frozen and cause bad user experience.

There is an article explaining about this issue: https://docs.iconify.design/articles/svg-animation-issues/#:~:text=When%20using%20inline,in%20an%20iframe.

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Maybe switch to a css animtion

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
