### ISSUE TITLE
Bug with the dialog component on mobile devices

### ISSUE THREAD

**Issue by plastininikolay** [mantinedev/mantine#4090]
### What package has an issue

@mantine/core

### Describe the bug

On mobile devices, the dialog component does not adapt to the width of the device. This is because the max-width style is not working properly. The value 100% is not readable by the browser in any way, due to position: fixed
[picture](https://ibb.co/GsgK1wD)

### What version of @mantine/hooks page do you have in package.json?

6.0.7

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

I suggest replacing the max-width: 100% style with max-width: 90vw for better mobile compatibility

**Comment by rtivital** [comment]
Fixed in 6.0.8
