### ISSUE TITLE
[Modal]: Select in Modal is overflow:hidden

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4095]
### What package has an issue

@mantine/core

### Describe the bug

current
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/124666577/232721661-f4f961da-ea9b-424e-a060-d50bb4315bc3.png">

expect :
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/124666577/232721818-936f955a-6f3a-4291-b4b2-52e9b41e5ccc.png">

### What version of @mantine/hooks page do you have in package.json?

6.0.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/modest-bassi-vi3je9?file=/src/Demo.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Set `<MultiSelect withinPortal />`

**Comment by vaynevayne** [comment]
> Set `<MultiSelect withinPortal />`

dalao, consider set  `withinPortal`  as defaultValue ? @rtivital
