### ISSUE TITLE
Fixed Onlabel & OffLabel in Switch in RTL mode

### ISSUE THREAD

**Issue by saeedkefayati** [mantinedev/mantine#4096]
### What package has an issue

@mantine/core

### Describe the bug

there is bug when use switch component in rtl direction and using onlabel & offlabel.

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

you should update margin style in rtl mode.

**Comment by rtivital** [comment]
Please provide a sandbox that reproduces the issue, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

**Comment by mustaphaboudouch** [comment]
> Please provide a sandbox that reproduces the issue, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

I think he is talking about the problem that there is no gap between the switch and the label in the RTL direction.
Reproduced problem : https://codesandbox.io/s/elegant-elion-53qe7b?file=/src/App.tsx

**Solution: using flexbox gap instead of padding-left**
