### ISSUE TITLE
V6 Input and MultiSelect placeholder offcentered on Ubuntu - Firefox and Chrome

### ISSUE THREAD

**Issue by Ingi-Hong** [mantinedev/mantine#4098]
### What package has an issue

@mantine/core

### Describe the bug

Firefox version: 102.0.1 (64-bit) 
Chrome version: Version 110.0.5481.100 (Official Build) (64-bit)

Input placeholder not centered: 

![image](https://user-images.githubusercontent.com/73002018/232914545-8b642559-a7d7-41d8-9f31-e4c3a36a1646.png)

I wonder if its related to [#1962](https://github.com/mantinedev/mantine/issues/1962)

### What version of @mantine/hooks page do you have in package.json?

V6.0.6

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Which browser on Ubuntu is this?

**Comment by Ingi-Hong** [comment]
Screenshot is from Firefox version: 102.0.1 (64-bit), but Chrome Version 110.0.5481.100 (Official Build) (64-bit) had the same behavior

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
