### ISSUE TITLE
Modal overflow with DatePickerInput

### ISSUE THREAD

**Issue by mirel25** [mantinedev/mantine#4100]
### What package has an issue

@mantine/core

### Describe the bug

When opening a modal with a single DatePickerInput it overflows and the picker is not visible. I had the same issue with Select but the select worked with the property withinPortal
![image](https://user-images.githubusercontent.com/114673923/232997397-cc501ad5-aa13-4acf-940e-b1a4e8fac747.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
`<DatePickerInput popoverProps={{ withinPortal: true }} />`
