### ISSUE TITLE
DatePickerInput type=range popoverProp onClose event prevents it from closing

### ISSUE THREAD

**Issue by fozzarelo** [mantinedev/mantine#4105]
### What package has an issue

@mantine/dates

### Describe the bug

Dates/DatePickerInput/type=range/popoverProp/onClose event prevents it from closing.

I'm trying to append a footer to the dropDown component. I want to use the onOpen and onClose events in popoverProp to bring my footer about(by triggering a setState)

onOpen works with no issues: triggers then closes
onClose when clicking in the input box it works as expected: triggers and closes 
**onClose when clicking outside triggers, but the dropdown remains open.** 

Is this intended functionality?
Can I close it programmatically? Call a close inside the onClose
or can you suggest another workaround?

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/interesting-sun-qmt8j6?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by hassanzohdy** [comment]
It seems to me it works fine, put the welcome text outside the `InfoBox` so outsideClick prop would work as expected.

https://codesandbox.io/s/charming-lovelace-oj94ec

**Comment by fozzarelo** [comment]
Hi, thank you @hassanzohdy 

Sorry, it seems I kept working on the fork until I hit a solution.  Here is a more straightforward reproduction of the bug.

https://codesandbox.io/s/onclosebug-qmt8j6?file=/src/App.tsx

I also found adding the 'opened' prop keeps onOned from triggering. Here is a reproduction with a workaround. 

https://codesandbox.io/s/opened-onopenbug-txtyzj?file=/src/App.tsx

**Comment by fozzarelo** [comment]
The footer is still doable the bugs can be worked around, here goes an example in case someone finds it useful 

https://codesandbox.io/s/works-using-click-outside-uj42ek?file=/src/App.tsx

**Comment by rtivital** [comment]
Fixed in [7.6.1](https://github.com/mantinedev/mantine/releases/tag/7.6.1)
