### ISSUE TITLE
Unable to extend the type interface of an existing Mantine component

### ISSUE THREAD

**Issue by zac18992** [mantinedev/mantine#4107]
### What package has an issue

@mantine/core

### Describe the bug

I am struggling to extend the type interface of a Mantine component in order to create my own wrapper.

I do apologise as this could be a lack of understanding on my part, regarding Mantine or TypeScript. However, I was unable to find this use case in the [documentation](https://mantine.dev/guides/typescript/).

Here is one example of what I'm trying to achieve. Say I want to wrap the Anchor component but add my own custom prop:

```ts
import React from 'react';
import { Anchor } from '@mantine/core';
import type { AnchorProps } from '@mantine/core';

interface AnchorCustomProps extends AnchorProps {
  opensInNewTab: boolean
}

const AnchorCustom: React.FC<AnchorCustomProps> = ({ opensInNewTab = false, ...props }: AnchorCustomProps) => {
  return (
    <Anchor {...props} target={opensInNewTab ? "_blank" : undefined}>
      Extended Anchor
    </Anchor>
  );
};

export default AnchorCustom;
```

However, when I do this, I lose the ability to pass in props related to the <a /> tag, which were previously accepted by the original Mantine Anchor component.

```ts
<Anchor
  href="https://react.dev/" // Prop accepted
>
  Mantine Anchor
</Anchor>

<AnchorExtended
  href="https://react.dev/" // "Property 'href' does not exist"
  opensInNewTab
>
  Extended Anchor
</AnchorExtended>
```

Thanks in advance for your support.

### What version of @mantine/hooks page do you have in package.json?

6.0.7

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by zac18992** [comment]
Thanks so much for the swift pointer @rtivital, really helpful. I was able to achieve the desired result using both of the following:

```ts
interface AnchorExtendedProps extends AnchorProps {
  opensInNewTab?: boolean
}

// Create intermediate component with default ref type and props
const _AnchorExtended = forwardRef<HTMLAnchorElement, AnchorExtendedProps>(({ opensInNewTab, ...props }, ref) => (
  <Anchor {...props} target={opensInNewTab ? "_blank" : undefined} ref={ref}>
    Extended Anchor
  </Anchor>
));

const AnchorExtended = createPolymorphicComponent<'a', AnchorExtendedProps>(_AnchorExtended);
```

```ts
interface AnchorExtendedProps extends AnchorProps {
  opensInNewTab?: boolean
}

const _AnchorExtended = forwardRef<HTMLAnchorElement, AnchorExtendedProps>(({ opensInNewTab, ...props }, ref) => (
  <Box {...props} target={opensInNewTab ? "_blank" : undefined} ref={ref} component='a'>
    Extended Anchor
  </Box>
));

const AnchorExtended = createPolymorphicComponent<'a', AnchorExtendedProps>(_AnchorExtended);
```

Is there technically any difference between the two approaches?
Is one preferred over the other?

**Comment by rtivital** [comment]
There is no difference

**Comment by zac-az** [comment]
Thanks again for your help. Really appreciate it!
