### ISSUE TITLE
createPolymorphicComponent causes Expression produces a union type that is too complex to represent.

### ISSUE THREAD

**Issue by joshuaavalon** [mantinedev/mantine#4110]
### What package has an issue

@mantine/core

### Describe the bug

```tsx
import {
  createPolymorphicComponent,
  Header
} from "@mantine/core";
import styled from "@emotion/styled";
import type { HeaderProps } from "@mantine/core";

const StyledHeader = createPolymorphicComponent<"header", HeaderProps>(
  styled(Header)`
    display: flex;
    align-items: center;
  `
);

// Expression produces a union type that is too complex to represent.
<StyledHeader height={50} p="md">
```

VSCode show `Expression produces a union type that is too complex to represent.`

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/purple-sun-l0jo1n

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

1. Remove `"jsxImportSource": "@emotion/react"` from `tsconfig.json`
2. Use `styled` without `createPolymorphicComponent`

**Comment by rtivital** [comment]
The issue is no longer reproducible in the provided sandbox
