### ISSUE TITLE
MultiSelect placeholder does not respect primaryShade on error state

### ISSUE THREAD

**Issue by Cuzart** [mantinedev/mantine#4111]
### What package has an issue

@mantine/core

### Describe the bug

The MultiSelect component from @mantine/core does not respect the primaryShade set in theme.

MultiSelect.styles.ts
` '&::placeholder': {
      opacity: 1,
      color: invalid
        ? theme.colors.red[theme.colorScheme === 'dark' ? 6 : 7]
        : theme.colorScheme === 'dark'
        ? theme.colors.dark[3]
        : theme.colors.gray[5],
   },`

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/nifty-diffie-jcq0xf?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Get the shade value dynamically from theme.fn.primaryShade( )

` color: invalid ? theme.colors.red[theme.fn.primaryShade()]`

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
