### ISSUE TITLE
NumberInput erroring when value is null

### ISSUE THREAD

**Issue by mmahalwy** [mantinedev/mantine#4117]
### What package has an issue

@mantine/core

### Describe the bug

Prior to Mantine 6.0.6, `NumberInput` would handle `null` value without erroring. Now, errors with `Cannot read properties of null (reading 'toFixed')`.

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/vibrant-clarke-7xo770?file=/src/App.tsx:343-364

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Check for against when value is `null` and `undefined`

**Comment by dankolesnikov** [comment]
Mantine team, it would be awesome for null | undefined to be a valid value that can be passed to the component.

**Comment by rtivital** [comment]
NumberInput value type is  `number | ''` (number or empty string) – it does not support other values types. This type was changed in 6.0, before that value type was `number | undefined`. `null` was never stated as supported value. It is not planned to support these values in the future.

**Comment by mmahalwy** [comment]
@rtivital interesting. So it was not erroring out before although it's not the intended type. 
I think we may want to support `null` as APIs typically return `null` for fields. So if the component is fetching from API and adding default values to inputs, `null` is a valid type.

**Comment by dankolesnikov** [comment]
+1 to @mmahalwy

**Comment by homwel** [comment]
Even if `null` is not a supported value for `NumberInput`, the resulting error is unhelpful. Better would be to produce a meaningful error message. Better yet would be for the component not to _crash._ Can we reopen this issue? I'm happy to contribute a fix.

**Comment by arel** [comment]
Even if `null` is not a supported value for `NumberInput`, the resulting error is unhelpful. Better would be to produce a meaningful error message. Better yet would be for the component not to _crash_. Can we reopen this issue? I'm happy to contribute a fix.
