### ISSUE TITLE
Submiting form inside a modal is calling the outer form submit event

### ISSUE THREAD

**Issue by philldev** [mantinedev/mantine#4125]
### What package has an issue

@mantine/form

### Describe the bug

I'm trying to submit a form inside another form within a modal. but when submit the inner form within a modal the outer form submit event is called. you can see the example code in codesandbox that I provided 

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/relaxed-mayer-v15m7v?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I'm able to fix the issue temporarly by comparing the submit event currentTarget and target
```js
if(event.currentTarget && event.target) handleSubmit(e)
```

**Comment by rtivital** [comment]
The included sandbox does not reproduce the issue, please update it

**Comment by philldev** [comment]
sorry about that. I just updated the codesandbox.

**Comment by chewhx** [comment]
One possible solution is to not have two `<form>` elements within the page. My experience is that button with type=submit will trigger the submissions of all `<forms>`s on the webpage.

Within each component, you can still access the form values and handle each form submissions independently.
```tsx
const form = useForm({...});

const handleSubmit = () => {
  doSomething(form.values)
}
```

Don't think this issue is specific to the library.

**Comment by philldev** [comment]
> One possible solution is to not have two `<form>` elements within the page. My experience is that button with type=submit will trigger the submissions of all `<forms>`s on the webpage.
> 
> Within each component, you can still access the form values and handle each form submissions independently.
> 
> ```tsx
> const form = useForm({...});
> 
> const handleSubmit = () => {
>   doSomething(form.values)
> }
> ```
> 
> Don't think this issue is specific to the library.

if this is the default behaviour of the dom than I think you're right this is not the issue for the library. but i think a callback fn property eg "beforeOnSubmit" inside useForm hook that would have a event argument before submit so that i can check or validate the event target.

**Comment by Adel-ak** [comment]
I faced the same problem a while back and it's not a library issue.

This was my solution and it works great

```js
<form
onSubmit={(event) => {
  // Since this is a nested form we should prevent propagation
  // So the parent form doesn't get submitted as well
  event.stopPropagation();

 const onSubmit = handleSubmit(() => setLoading(false)); // returns on submit from useForm 
 onSubmit(event);
}}>
``` 

I think adding something like beforeOnSubmit as said by @philldev would make things cleaner
