### ISSUE TITLE
MonthPicker, YearPicker won't locate to correct position in popover

### ISSUE THREAD

**Issue by congyaqwq** [mantinedev/mantine#4129]
### What package has an issue

@mantine/dates

### Describe the bug

I need to customize a date picker dropdown component, but every time I open it, the value is not located on the correct page. It only locates to the correct position when I pass in `defaultDate`, and I am not sure if this is a bug. I believe the normal behavior should be to locate the position of its value.

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/nifty-goldstine-8g8q9i?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by congyaqwq** [comment]
I found DatePicker DatePicker<'range'> have the same behavior too. maybe the same problem.

**Comment by milhamm** [comment]
I think it's the intended behavior (?)

We have `date` and `defaultDate` props used to determine which year should be displayed initially. Day, minutes, and seconds are ignored in provided date object, only year and month data is used – you can specify any date value. 

So if you want your picker to be on the correct page, pass the  `date` or `defaultDate` with the same year as the `value` or `defaultValue`.

**Comment by congyaqwq** [comment]
> I think it's the intended behavior (?)
> 
> We have `date` and `defaultDate` props used to determine which year should be displayed initially. Day, minutes, and seconds are ignored in provided date object, only year and month data is used – you can specify any date value.
> 
> So if you want your picker to be on the correct page, pass the `date` or `defaultDate` with the same year as the `value` or `defaultValue`.

Thank you. I saw the usage of `defaultDate` in the document, which says it is only used in uncontrolled components. I did not look into the specific implementation carefully.
