### ISSUE TITLE
Password Input has smaller line height in mozilla firefox

### ISSUE THREAD

**Issue by mrityunjaygr8** [mantinedev/mantine#413]
Package: "@mantine/core"
Version: 3.1.6
Browser+OS: Mozilla Firefox Developer Edition 94.0b3 and Firefox 94.0.1 on Manjaro Linux
It seems to be working well in Codesandbox so I dont know how useful will that be
Manually setting the line height, equal to the line height on the input element above in the screenshot , on the `<input type="password">` element seems to fix the issue
I am willing to participate in fixing this issue, but i dont know how and where to make this change.

Screenshots from firefox:
![mantine-password-input-wonky](https://user-images.githubusercontent.com/14573967/141488691-5ce626d6-3f80-4d06-bfed-4f7c44f1a0d5.png)

Screenshot from firefox using the debug CSS extension to show the layout/boxes:
![password-input-firefox-wonky-debug-css](https://user-images.githubusercontent.com/14573967/141488788-731c9cf3-f2e6-4893-b071-9c5f923baaf9.png)

Screenshot from Chromium:
![chromium-pass-input-ok](https://user-images.githubusercontent.com/14573967/141488875-a109fb41-120c-4c17-8025-258c55696479.png)

Screenshot from Chromium using debug CSS extension:
![chromium-password-input-debug-css-ok](https://user-images.githubusercontent.com/14573967/141488868-81126375-0bec-4f2b-b177-3025d57eef1c.png)

**Comment by rtivital** [comment]
Hi @mrityunjaygr8 thanks for reporting! Issues that you've reported are already fixed and will be out in next minor release 3.2, meanwhile you can downgrade to version `3.1.4` – PasswordInput has correct styles in that version.

**Comment by mrityunjaygr8** [comment]
thanks for the info @rtivital, i will downgrade to `3.1.4` while waiting for the `3.2` release.
Do you have a rough estimate of when that will be?

Either ways, thanks and have good weekend.

PS: should i close this issue? Or, you will do that.

**Comment by rtivital** [comment]
I'll close this issue once 3.2 is out. It's planned to be released on December 3rd or earlier.

**Comment by rtivital** [comment]
Fixed in 3.1.9
