### ISSUE TITLE
[NumberInput] Thousand separator does not work

### ISSUE THREAD

**Issue by nhatncb** [mantinedev/mantine#4132]
### What package has an issue

@mantine/core

### Describe the bug

https://mantine.dev/core/number-input/

Follow the example in this link, the **thousandsSeparator** props seems **not working.** 

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment]
Are you expecting it to be added automatically when entering large numbers?
Currently it's only used for removing thousands separators when parsing the user input. So it's a limitation.

**Comment by nhatncb** [comment]
> Are you expecting it to be added automatically when entering large numbers? Currently it's only used for removing thousands separators when parsing the user input. So it's a limitation.

I saw there are some changes in ver 6.0.6. 
It works in the version below 6.0.6: https://codesandbox.io/s/mantine-format-numberinput-while-typing-nh4l6r

**Comment by cyantree** [comment]
That's right however it had various other issues (e. g. with enabled precision). Also entering numbers can be a bit fiddly as the cursor easily jumps around during editing.
So we disabled the automatic reformatting during editing.

However you can get your behaviour also with `6.0.9`. The only difference is that is reformats on blur and not on input. This also has the benefit that the cursor doesn't jump around anymore:
https://codesandbox.io/s/mantine-format-numberinput-while-typing-forked-wmvg4u

**Comment by fer-ri** [comment]
> That's right however it had various other issues (e. g. with enabled precision). Also entering numbers can be a bit fiddly as the cursor easily jumps around during editing. So we disabled the automatic reformatting during editing.
> 
> However you can get your behaviour also with `6.0.9`. The only difference is that is reformats on blur and not on input. This also has the benefit that the cursor doesn't jump around anymore: https://codesandbox.io/s/mantine-format-numberinput-while-typing-forked-wmvg4u

Hi,

Your codesandbox is dead, can you reupload? Thanks

**Comment by cyantree** [comment]
I'm sorry. I cleaned up my sandboxes and therefore can't restore it.

**Comment by fer-ri** [comment]
> I'm sorry. I cleaned up my sandboxes and therefore can't restore it.

It's ok, I found another way to make it :smile: 

Thanks for replied

**Comment by Mefedim** [comment]
> > I'm sorry. I cleaned up my sandboxes and therefore can't restore it.
> 
> It's ok, I found another way to make it 😄
> 
> Thanks for replied

Hello! Faced with this, could you please advise how you solved this?

**Comment by fer-ri** [comment]
> > > I'm sorry. I cleaned up my sandboxes and therefore can't restore it.
> > 
> > 
> > It's ok, I found another way to make it 😄
> > Thanks for replied
> 
> Hello! Faced with this, could you please advise how you solved this?

Something like this

```ts
import { IMaskInput } from 'react-imask';

<Input.Wrapper
            id={priceId}
            label="Price"
            required
            error={errors?.price}
          >
            <Input<any>
              component={IMaskInput}
              defaultValue={data.price}
              unmask={true}
              onAccept={(value: string) => setData('price', value)}
              mask="num"
              blocks={{
                num: {
                  mask: Number,
                  scale: 2,
                  signed: false,
                  thousandsSeparator: '.',
                  min: 0,
                  max: 99999999999,
                },
              }}
              id={priceId}
              placeholder="Price"
            />
          </Input.Wrapper>
 ```
 
 hope it helps

**Comment by Mefedim** [comment]
Ah yes, it's just that this method doesn't really work in my situation, thought maybe you found a solution with NumberInput.
Thanks for the reply!

**Comment by fer-ri** [comment]
> Ah yes, it's just that this method doesn't really work in my situation, thought maybe you found a solution with NumberInput. Thanks for the reply!

Ok. Hope you can find a solution
