### ISSUE TITLE
Polymorphic components don't work with Tanstack Router

### ISSUE THREAD

**Issue by max-programming** [mantinedev/mantine#4134]
### What package has an issue

@mantine/core

### Describe the bug

So I was using the [Tanstack Router](https://tanstack.com/router/v1) and I tried using the polymorphic components and that throws some sort of error. I think it has something to do with the `to` attribute which is dynamic based on the routes we define

![image](https://user-images.githubusercontent.com/51731966/234250054-d66ec390-7abd-45a9-a073-38f1fdb20324.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.9

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-tanstack-router-issue-guns2c

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Polymorphic components can only work correctly with components that are not generic. It is not possible to implement them other way.

**Comment by yhranik** [comment]
I made it work with tanstack router using the following wrapper component:
```
// Mantine's polymorphic `component` prop can't preserve TanStack Router's
// per-route `params` typing for a component as generic as `Link` (see
// https://tanstack.com/router/latest/docs/guide/custom-link) - `createLink`
// is the router's own sanctioned fix: it wraps a plain forwardRef component
// so `to`/`params` stay fully typed.
type AnchorLinkProps = Omit<AnchorProps, "href">

const MantineAnchor = forwardRef<HTMLAnchorElement, AnchorLinkProps>((props, ref) => (
  <Anchor ref={ref} {...props} />
))

const CreatedLinkComponent = createLink(MantineAnchor)

export const AnchorLink: LinkComponent<typeof MantineAnchor> = (props) => (
  <CreatedLinkComponent {...props} />
)
```
