### ISSUE TITLE
DatePicker borderRadius not working in some styles: monthsListCell yearsListCell

### ISSUE THREAD

**Issue by fozzarelo** [mantinedev/mantine#4139]
### What package has an issue

@mantine/dates

### Describe the bug

DatePicker/styles prop: 

When applying borderRadius to monthsListCell  or yearsListCell styles, the element takes the new radius, but the border doesn't. here goes a pic and a reproduction. I hope it helps. 

The cells and example are using the same style:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/17816946/234396686-ce52ad5d-f35b-46bb-abb4-249ee337552c.png">

 

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/borderradius-qocjmo?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Table cells with `border-collpase: collpase` cannot have border radius. You should probably change display of the tr to flex and to block of td. Or just add these styles to controls instead.

**Comment by fozzarelo** [comment]
thank you @rtivital.
