### ISSUE TITLE
Password text is black even in dark mode

### ISSUE THREAD

**Issue by mrityunjaygr8** [mantinedev/mantine#414]
Package: "@mantine/core"
Version: 3.1.6
Browser+OS: Mozilla Firefox Developer Edition 94.0b3 and Firefox 94.0.1 and Chromium 94.0.4606.81 on Manjaro Linux

The text in the Password Input Element has black/dark color even in dark mode.
[Codesandbox](https://codesandbox.io/embed/serverless-thunder-e0o62?fontsize=14&hidenavigation=1&theme=dark)

Screenshots:
![chromium-password-input-text-black](https://user-images.githubusercontent.com/14573967/141490647-f6118c36-1ac1-4421-ad13-240d5dd6d5c7.png)
![firefox-password-text-black](https://user-images.githubusercontent.com/14573967/141490657-8a5331f6-efae-4f4f-aa97-0258a530d057.png)

Manually setting the `color` css property to the one in the TextInput seems to fix the issue.
I have no idea how to fix this, but I am willing to give it a go you can give me a few pointers in terms of where to start looking.

**Comment by rtivital** [comment]
Fixed in 3.1.9
