### ISSUE TITLE
JsonInput has invalid autocomplete default

### ISSUE THREAD

**Issue by noahsb** [mantinedev/mantine#4140]
### What package has an issue

@mantine/core

### Describe the bug

`JsonInput` has an autocomplete default of `"nope"` as seen [here](https://github.com/mantinedev/mantine/blob/fb1dfdeba53f78548412d12d88e8486fee7dac6c/src/mantine-core/src/JsonInput/JsonInput.tsx#L98).

This is an invalid autocomplete value according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values) and is causing warnings with axe DevTools scanner unless `autoComplete ` is overriden to a valid value.

### What version of @mantine/hooks page do you have in package.json?

6.0.9

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

`autoComplete="nope"` -> `autoComplete="off"`

**Comment by KilianB** [comment]
Probably due to: https://stackoverflow.com/a/38961567/3394605 . I also faced issues witu autocomplete off having no effect in chrome

**Comment by rtivital** [comment]
Fixed in 6.0.10
