### ISSUE TITLE
marginBottom on Tab Buttons with noWrap and overflowX: auto causes an overflow in the Y direction

### ISSUE THREAD

**Issue by Angusross111** [mantinedev/mantine#4143]
### What package has an issue

@mantine/core

### Describe the bug

When adding `flexWrap: "nowrap"` and `overflowX: "scroll"` to the `tabsList` styles on `Tabs` a vertial scrollbar appears due to a `borderBottom: -0.125rem` that is added to each button.

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/infallible-poincare-b1hgnw

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by Angusross111** [comment]
I can see its done that way to make it look like the borderBottom on the active tab is over the top of the divider. I flagged it as i was not sure if it was expected behavour to cause the overflow in that particular use case. If it is expected then happy to move it to a discussion and find a way to work around it.

**Comment by rtivital** [comment]
I do not see an issue here:
- Component provided by the library works as expected
- If you use custom styles, then it is your job to make sure that these styles work well with other component styles. For example, in this case, you will need to remove the negative margin on the tabs list.
