### ISSUE TITLE
Component theme override do not pass params properly

### ISSUE THREAD

**Issue by Crocsx** [mantinedev/mantine#4147]
### What package has an issue

@mantine/core

### Describe the bug

Sorry for the title that might be confusing, I am not quite sure how to name it.

I have the following case.

I am using Mantine to create my own set of component. I basically extends Mantine components, and assign my own layer of style on top of it using the `components` props of the `MantineProvider` `theme`

Here my steps : 

1) I create a theme with my colors and some specific property including my overidden component theme 
```
  components: {
    Checkbox: CheckboxTheme
 },
```
  
2) My CheckboxTheme contains some specific css class to apply to the default checkbox of Mantine :
  ```
export const CheckboxTheme: ThemeComponent = {
  defaultProps: {
    size: "xs",
    color: "blue"
  },
  styles: (theme, params) => {
    return {
      root: {
        // Focused on root element
        "&:focus": {
          input: {
            outline: "none",
            borderColor: `${theme.fn.themeColor(params.color, 6)}`,
            "&:checked": {
              borderColor: `${theme.fn.themeColor(params.color, 9)}`
            }
          }
        },
      }
    };
  }
};
```
        
3) I then use my component with a specific parameter color  :
`<Checkbox color="red" label="Test Value" />`

RESULT =>
![Screenshot 2023-04-27 at 12 01 18](https://user-images.githubusercontent.com/6420140/234748804-3faea670-680b-43e3-bfce-08c1ecfeb7ff.png)
I am getting some part of the component with the correct parameter color, but some remain blue.

EXPECTED => 
![Screenshot 2023-04-27 at 12 06 33](https://user-images.githubusercontent.com/6420140/234749393-6d160f84-c1c0-48ce-86bc-a5ef98136431.png)
The component should be red like I requested

When I do 
```
  styles: (theme, params) => {
    console.log(params.color);
  }
```

I see the value twice with the proper `params.color` and twice `undefined` which cause the issue I believe.

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/keen-scooby-c9ywnb

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
