### ISSUE TITLE
The required prop is not working for Select

### ISSUE THREAD

**Issue by lahin31** [mantinedev/mantine#4149]
### What package has an issue

@mantine/core

### Describe the bug

The required prop is not working when I use Select. 

This is the code,

```
<form onSubmit={e => e.preventDefault()}>
  <label htmlFor="my-select">Select an option:</label>
  <Select
    id="my-select"
    required
    data={options}
    placeholder="Select an option"
  />
  <button type="submit">Submit</button>
 </form>
```

The version of 

"@mantine/core": "^5.10.0",
"@mantine/hooks": "^5.10.0"

### What version of @mantine/hooks page do you have in package.json?

^5.10.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
See https://github.com/mantinedev/mantine/issues/3454
