### ISSUE TITLE
[vite]: Rollup failed to resolve import "@emotion/cache" from "/data/data/ads-v3/ads-v3-react-build/node_modules/.pnpm/@mantine+styles@6.0.6_sogmqz4enknxtkxk3k5s6bqwnq/node_modules/@mantine/styles/esm/index.js".  This is most likely unintended because it can break your application at runtime.  If you do want to externalize this module explicitly add it to  `build.rollupOptions.external`  error during build:  Error: [vite]: Rollup failed to resolve import "@emotion/cache" from "/data/data/ads-v3/ads-v3-react-build/node_modules/.pnpm/@mantine+styles@6.0.6_sogmqz4enknxtkxk3k5s6bqwnq/node_modules/@mantine/styles/esm/index.js".

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4150]
### What package has an issue

@mantine/core

### Describe the bug

build error 

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/124666577/234801955-c585f2f1-2d43-4802-b53d-9cd877ad4966.png">

### What version of @mantine/hooks page do you have in package.json?

no

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
The error says that you are missing `@emotion/cache` dependency. Install it.
