### ISSUE TITLE
[ColorInput] Color passed to onChangeEnd can be off by one when color entered manually

### ISSUE THREAD

**Issue by DanielGibbsNZ** [mantinedev/mantine#4154]
### What package has an issue

@mantine/core

### Describe the bug

1. Enter a color manually into a `ColorInput` (e.g. `#123456`)
2. The value passed to the `onChangeEnd` callback is often off by one (e.g. `#123457`)

Reproduction:

```
import React from "react";
import { MantineProvider, ColorInput } from "@mantine/core";

export default function App() {
  const [parsedColor, setParsedColor] = React.useState<string>("");

  const handleChangeEnd = (color: string) => {
    setParsedColor(color);
  };

  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <p>Reproduction steps: Enter "#123456" in the color input.</p>
      <ColorInput onChangeEnd={handleChangeEnd} />
      <p>Parsed color: {parsedColor}</p>
    </MantineProvider>
  );
}
```

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/magical-newton-3v17lq?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

This seems to be caused by converting every value to HSV and then back when parsing the input. I presume some loss of precision somewhere causes the off-by-one error.

**Comment by cyantree** [comment]
It might be as simple as increasing the precision in this block:
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/ColorPicker/converters/parsers.ts#L59
