### ISSUE TITLE
DatePicker: clicking on the same (already choosen) date clears the choosen date in the field

### ISSUE THREAD

**Issue by ChrisSime** [mantinedev/mantine#4157]
### What package has an issue

@mantine/dates

### Describe the bug

Clicking on the same (already choosen) date clears the choosen date in the field.

Steps:
1. Open datepicker
2. Click on date ex. 25/03/2023
3. Open datepicker again and choose the same date

Result:
Date in field is deleted

Expected:
Date in field should stay as user have chosen

Video: 
![ezgif com-crop](https://user-images.githubusercontent.com/132053754/235127996-36310304-f3e9-408b-8984-96d67c0a182a.gif)
. 

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
What is the issue with this? This behavior is configurable and is described in documentation – https://mantine.dev/dates/date-picker/#allow-deselect
