### ISSUE TITLE
Prevent onClick action of parent elements in Popover component

### ISSUE THREAD

**Issue by avkash1** [mantinedev/mantine#4161]
### What package has an issue

@mantine/core

### Describe the bug

I have a parent **NavLink** component. In that I have child **Popover** component which should trigger popover on click.

_**I have redirection integrateed onClick of NavLink, and I don't want that to be called when I click on Popover.**_

I can do that with nested Button component in NavLink by using `event.stopPropagation()`, but there is no way to do the same for Popover.

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/funny-newton-hglk69?file=/src/App.js

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Current `onClick` behavior of Popover is correct and is not planned to be changed. Implementing this change will break other components, for example HoverCard.
