### ISSUE TITLE
How to focus on first element when matched in multiselect?

### ISSUE THREAD

**Issue by Sasha95** [mantinedev/mantine#4164]
### What package has an issue

@mantine/core

### Describe the bug

now we have this behavior:
![image](https://user-images.githubusercontent.com/12782629/235301887-4ffbf201-d80c-4a4b-9c96-44a438b60b0d.png)
But I would like the first element to have focus by default. And if I press the enter key, then for this element to be selected.
I need:

![image](https://user-images.githubusercontent.com/12782629/235301996-9bf3ad45-fb32-409a-87b9-af8c4f580550.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.9

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/thirsty-waterfall-snj3qt?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by milhamm** [comment]
Add the  `hoverOnSearchChange` props

It is stated here https://mantine.dev/core/select/?t=props

**Comment by magicznyleszek** [comment]
Sorry for doing necromancy on the thread, but I found this through search and the prop changed the name to `selectFirstOptionOnChange` 🫡
