### ISSUE TITLE
A Snackbar/Toast component

### ISSUE THREAD

**Issue by AkeemAllen** [mantinedev/mantine#4169]
I was surprised to realize that mantineui never included a snackbar component (either that or I don't know where to find it/how to use it).
This is a feature proposal for a simple snackbar/toast component. If there are already plans for one or if it exists in some form, please let me know!

**Comment by rtivital** [comment]
- Please use GitHub issues to report bugs with the code. To request new features or ask questions, use GitHub discussions
- Mantine provides notifications package – https://mantine.dev/others/notifications/
