### ISSUE TITLE
Multiselect defaultValue not working with dynamic data

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#4173]
### What package has an issue

@mantine/core

### Describe the bug

✅ When `defaultValue` is static, and `data` is static - dropdown updates, and default values update.
❌ When `defaultValue` is static, but `data` is dynamic - dropdown updates, but default values don't.

However, in our app `defaultValue` comes from SSR, and `data` comes from CSR, so how do we make it work?
Only viable solution that worked was to use `useSWR` with `{ suspense: true }` but it freezes the UI until it loads `data`.

Any other solution?

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/xenodochial-microservice-5tyrrs

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
See https://codesandbox.io/s/silly-swirles-34x1wq

**Comment by atumas-bananamilk** [comment]
@rtivital 

Thanks it worked, no idea why we need to use random numbers for it to reload but thanks!

**Comment by mlarcher** [comment]
When I do this trick, defaultValue works, but I can't manually select a value. Can we reopen and investigate please ?
