### ISSUE TITLE
Select has scroll x enabled for long values after upgrading

### ISSUE THREAD

**Issue by ibenjelloun** [mantinedev/mantine#4177]
### What package has an issue

@mantine/core

### Describe the bug

After upgrading from `5.10.5` to `6.0.10`, the Select component bahavior changed for long values, an horizontal scroll bar is displayed instead of wrapping item content :

Observed :

![image](https://user-images.githubusercontent.com/1528304/235637203-e9168bdb-480b-4ae4-8cb8-f43e386d73b1.png)

Expected :

![image](https://user-images.githubusercontent.com/1528304/235638149-1800ec9b-c384-46c9-845c-d7ef18d00f4e.png)

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### If possible, please include a link to a codesandbox with the reproduced problem

https://stackblitz.com/edit/react-ts-1k2vpc?file=App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by mustaphaboudouch** [comment]
I solved the issue, here is the solution : https://stackblitz.com/edit/react-ts-9cnamk?file=App.tsx

**Comment by ibenjelloun** [comment]
> I solved the issue, here is the solution : https://stackblitz.com/edit/react-ts-9cnamk?file=App.tsx

Hello @mustaphaboudouch, thank you for your suggestion, the behavior is better than the default but still not the same as the version 5, you can see the expected result in the issue description.

**Comment by ibenjelloun** [comment]
Can go back to previous behavior with this style change :

```
const useStyles = createStyles(() => ({
  item: {
    whiteSpace: 'break-spaces',
  },
}));
```
https://stackblitz.com/edit/react-ts-z8tsan?file=App.tsx

**Comment by ibenjelloun** [comment]
Is the horizontal scroll supposed to be the default behavior ?

**Comment by mustaphaboudouch** [comment]
Yes, because the popover is wrapped in a scrollarea component 👇

<img width="808" alt="Capture d’écran 2023-05-03 à 10 21 01" src="https://user-images.githubusercontent.com/64332287/235865508-5ac10285-7e38-4f37-a561-0864fc8735e1.png">

**Comment by ibenjelloun** [comment]
> Yes, because the select popover is wrapped in a scrollarea component 👇
> 
> <img alt="Capture d’écran 2023-05-03 à 10 21 01" width="808" src="https://user-images.githubusercontent.com/64332287/235865508-5ac10285-7e38-4f37-a561-0864fc8735e1.png">

I understand that the horizontal scrollbar comes from the usage of `ScrollArea`, but do we really want this to be the default behavior ?
From my subjective point of view, this change is a regression and the default behavior should wrap text instead of adding an horizontal scrollbar.

**Comment by mustaphaboudouch** [comment]
I agree with you, but this is a rare case, because if you want the user to select between options with large text, I don't think `select` component is the best option , you can use a radio button or checkable custom items...

**Comment by vaynevayne** [comment]
Bad, this seems to be my pr up, the purpose is to solve the problem of multiple spaces in the label, the ultimate expectation is to keep the space, but can be automatically wrapped, maybe have to try other parameters
