### ISSUE TITLE
TextInput required and placeholder do not respond to color changes enough for contrast requirements

### ISSUE THREAD

**Issue by oiqwrwer1** [mantinedev/mantine#4178]
### What package has an issue

@mantine/core

### Describe the bug

TextInput's required icon and placeholder do not respond to color changes enough to meet contrast requirements for accessibility.

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
You can customize component styles with Styles API to meet the requirements of your application.

**Comment by oiqwrwer1** [comment]
I have tried this. The actual text input ghost text and asterisk icon do not respond appropriately to the style API nor to the MantineTheme.colorScheme value.
`backgroundColor: theme.colorScheme === 'dark' ? 
    theme.colors.dark[3] : 
    theme.colors.blue[1],
    color: theme.colorScheme === 'dark' ? 
    theme.colors.dark[3] : 
    theme.colors.blue[1],`

`<TextInput
        className={style.classes.track}
        placeholder={t("Environment.Prompt") ?? ""}
        label={t("Environment.Label")}
        withAsterisk
        required />`

![image](https://user-images.githubusercontent.com/102306502/235737288-07e8a14a-606e-4fbb-be44-9641dd54a2ea.png)

**Comment by rtivital** [comment]
`className` prop adds given class to the root element. If you want to customize styles of the asterisk, use `classNames` instead:

```tsx
<TextInput classNames={{ required: 'your-class' }} />
```

See styles api documentation for more info

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
