### ISSUE TITLE
Button.Group does not group buttons correctly when using mixed polymorphic buttons

### ISSUE THREAD

**Issue by jvllmr** [mantinedev/mantine#4182]
### What package has an issue

@mantine/core

### Describe the bug

Buttons in ButtonGroup don't group together when using Button with different components, e.g. button, a, React-Router Link.

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/amazing-flower-dmm1nl?file=%2Fsrc%2FApp.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Use :first-child selector and :last-child selector instead of :first-of-type and :last-of-type in ButtonGroup styles.
Bad side effect would be that other non-button elements in ButtonGroup can have an effect on the button grouping.

**Comment by rtivital** [comment]
The issue was fixed in 7.0
