### ISSUE TITLE
Components missing pointer cursor on hover

### ISSUE THREAD

**Issue by cehenriques** [mantinedev/mantine#4192]
### What package has an issue

@mantine/core

### Describe the bug

Some components like the Checkbox, Radio, and Switch don't have a `cursor: pointer` style when hovering them.

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
https://mantine.dev/theming/theme-object/#cursortype
