### ISSUE TITLE
Nested Menu's lead to Type Error when using arrow keys

### ISSUE THREAD

**Issue by Cuzart** [mantinedev/mantine#4193]
### What package has an issue

@mantine/core

### Describe the bug

I have a very special use case where I have to nest a Select within two nested Menu components which works perfectly fine. When I try using ArrowUp/Down the following error is evoked 
"TypeError Cannot read properties of undefined (reading 'focus')"

Reproduce: 
Click on first Menu target
Hover second Menu target
Click on Select and use ArrowUp or ArrowDown
See Error

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/xenodochial-bell-jdj4hz?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

There is a Key event handler in MenuDropdown which focuses the first menu item on ArrowUp/Down. There is no logic to prevent the focus when the element is undefined 

`  
const handleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (event.key === 'ArrowUp' || event.key === 'ArrowDown') {
      event.preventDefault();
      wrapperRef.current.querySelectorAll<HTMLButtonElement>('[data-menu-item]')[0].focus();
    }
  };
`
To fix this check for the element to be defined before calling focus() like so
wrapperRef.current.querySelectorAll<HTMLButtonElement>('[data-menu-item]')[0]**?**.focus();

**Comment by rtivital** [comment]
Mantine does not provide nested Menus currently, it is a complex task that is not planned to be released soon (definitely not as a part of 6.x releases).

**Comment by Cuzart** [comment]
Got you. At the moment it is still possible to nest them and achieve something similar which works totally fine in my case. I think catching the case that the ref is undefined would not hurt and could provide additionally stability to the code base. I could create a PR if you would not mind.

**Comment by pzehle** [comment]
> Mantine does not provide nested Menus currently

This is not entirely true, you can nest as many menus as you'd like, considering that the trigger has to be "hover". I have it in my project and it works just fine...

**Comment by Cuzart** [comment]
I think it is definitely possible to build something like this but it is not fully supported considering the responsiveness of the Popover Dropdowns which do not detect their position properly (in case there is only limited space and a repositioning is necessary e.g. when there is limited space at the bottom or on mobile screens. At least this is my impression but I would love to see your code if you would like to share or create a sandbox :) Another problem I was facing is that clicking within a nested menu is like an outside click for the root menu and closes the popover.

**Comment by Eve-Sama** [comment]
We need nested menus too.
