### ISSUE TITLE
Modal's `onClose` bug

### ISSUE THREAD

**Issue by michalzard** [mantinedev/mantine#4194]
### What package has an issue

@mantine/core

### Describe the bug

![image](https://user-images.githubusercontent.com/58849789/236509757-40efce69-a107-449c-947b-08fcb37c0fd9.png)
When passing React `useState` setter to change value from `true` to `false` your onClose triggers however the setter doesnt change value,it appears like it skips the setter,since when im console logging currenct `boolean` value it always returns true when opened even when i hit X in header or even if i just click away from modal. Does this mean using `useDisclosure` hook is required ? 

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by michalzard** [comment]
It appears i run into this even when using `useDisclosure(false)` hook,perhaps there might be issue with the `onClose` ?

**Comment by rtivital** [comment]
Modal works correctly on sandbox – https://codesandbox.io/s/nice-jang-pikvv9?file=/src/App.tsx
Most likely, the issue is with your code.

**Comment by michalzard** [comment]
Thanks for the reply,will revisit this later on

**Comment by alzeebum** [comment]
I understand this is a few years old but I want to comment here.  I've run into the same issue and it seems to me this property just has a misleading name.  In most architectures I would say it's expected that an `onClose` handler is fired whenever the associated "thing" is closed.

Instead it seems like this property is used to direct **how** to close the modal when built in close "methods" like pressing escape or clicking outside the modal is used.  It does not fire when you actually close the modal which is what I and I would think most people expect.

I have modal with the escape and click-outside close methods disabled, and without the builtin close button.  I have a normal button to close the modal, and in the onclick for that button, I close the modal with a `close` handler from `useDisclosure`.  This does not cause the `onClose` event to fire, which is what and perhaps the OP expected.

An update to the documentation would probably clear this up, and a new event that does fire in the more traditionally expected way would be greatly appreciated!
