### ISSUE TITLE
Drawer transition when inside a parent element

### ISSUE THREAD

**Issue by ahetawal-p** [mantinedev/mantine#4195]
### What package has an issue

@mantine/core

### Describe the bug

Hello, 
I am opening a drawer from inside a fixed height <Box> element, and performing a slide-up transition for the opening the drawer. 
The `open` transition seems to be happening from the bottom of the screen or window instead of the parent <Box> element, which is set as target for this Drawer. 
Here is the sample setup:
```
<Box
      w="100%"
      h={400}
      pos="relative"
      id="map-container"
    >
       <Drawer
                  opened={Boolean(opened)}
                  onClose={close}
                  target="#map-container"
                  withCloseButton={false}
                  withinPortal={true}
                  scrollAreaComponent={Drawer.NativeScrollArea}
                   transitionProps={{
                     transition: 'slide-up',
                     duration: 300,
                     timingFunction: 'ease',
                   }}
             // some content...
      </Drawer>
</Box>
```
How can I force the transition to be in respect to the parent div instead of the screen/window bottom.

### What version of @mantine/hooks page do you have in package.json?

^6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/embed/cranky-sound-r4yldr?fontsize=14&hidenavigation=1&theme=dark

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Drawer component has `fixed` position. If you want it to be over a certain element, you need to modify its styles to `absolute` position. You can do that with Styles API.

**Comment by ahetawal-p** [comment]
Thanks @rtivital 
In my actual code I do have the styles applied

```
 drawerInner: {
      position: 'absolute',
      height: containerHeight,
      width: isMobileDimension ? '100%' : 428,
      padding: '12px 0 0 12px',
     },
    drawerOverlay: {
      position: 'absolute',
      height: containerHeight,
      width: '100%',
    },
    drawerBody: {
      padding: 0,
    },

classNames={{
                    body: classes.drawerBody,
                    inner: classes.drawerInner,
                    overlay: classes.drawerOverlay,
                  }}
```
And I am still seeing the drawer being slide-up from the bottom of the screen instead of target element ?
Any other ideas ?

**Comment by lawff** [comment]
> Thanks @rtivital In my actual code I do have the styles applied
> 
> ```
>  drawerInner: {
>       position: 'absolute',
>       height: containerHeight,
>       width:  428,
>       padding: '12px 0 0 12px',
>      },
>     drawerOverlay: {
>       position: 'absolute',
>       height: containerHeight,
>       width: '100%',
>     },
>     drawerBody: {
>       padding: 0,
>     },
> 
> classNames={{
>                     body: classes.drawerBody,
>                     inner: classes.drawerInner,
>                     overlay: classes.drawerOverlay,
>                   }}
> ```
> 
> And I am still seeing the drawer being slide-up from the bottom of the screen instead of target element ? Any other ideas ?
> 
> Updated the codesandbox with above styles as well. https://codesandbox.io/s/youthful-bhaskara-4r2k7v?file=/src/App.tsx
> 
>  Screen.Recording.2023-05-05.at.11.35.28.PM.mov

![image](https://github.com/mantinedev/mantine/assets/103186898/7d93ce01-1994-4244-aa55-4e18fbcc55ba)
try to add this

**Comment by premier213** [comment]
example with mantine 7 without class.

```js
<Drawer
        withinPortal
        portalProps={{ target: "#test" }}
        opened={opened}
        onClose={toggle}
        withCloseButton={false}
        size={250}
        overlayProps={{ center: true }}
        transitionProps={{ transition: "slide-left", duration: 150, timingFunction: "linear" }}>
        4545
</Drawer>
```
