### ISSUE TITLE
Sorting the Props in the props table in Alphabetical order

### ISSUE THREAD

**Issue by khushal87** [mantinedev/mantine#42]
The props in the prop table of Components are not sorted in alphabetical order. It would be much more appealing if we can sort it in Alphabetical order and display the props.

Eg:
![burger](https://user-images.githubusercontent.com/39884168/117451002-9286e500-af5f-11eb-8689-c9438514b4d2.PNG)

**Comment by rtivital** [comment]
Yep, seems reasonable, please create a PR

**Comment by khushal87** [comment]
@rtivital Branch in which I can raise the PR?
