### ISSUE TITLE
Not able to define theme according to styles for official Mantine docs

### ISSUE THREAD

**Issue by matthewoates** [mantinedev/mantine#420]
I'm looking at https://mantine.dev/theming/extend-theme/ and notice that the headers have a pure white text color. There doesn't seem to be a way to get this working in the themes, which feels really awkward. I don't think we should need to resort to using CSS (the docs advise against using styling patterns other than Mantine's) and I don't want to have to apply a font color each time I render a Title component.

Am I missing something?

Here's my current theme:

```js
<MantineProvider
  theme={{
    headings: {
      fontFamily: 'Open Sans', // this took me a while to find. I feel like theme.headings.fontFamily should inherit from theme.fontFamily
      color: '#fff' // doesn't work. no way to set color globally for headings
    },
    colorScheme: 'dark', // had to dig around to see that the body background is magically set to theme.colors.dark[7] if and only if colorScheme is 'dark'
    fontFamily: 'Open Sans',
    fontFamilyMonospace: 'Cousine'
  }}
>
```

The next best solution appears to be the following ugly CSS:

```css
:is(h1, h2, h3, h4, h5, h6)[class^="mantine-"] {
  color: white;
}
```

**Comment by rtivital** [comment]
Hi @matthewoates you cannot set Title color in your theme – this will now work for dark/light color scheme toggle.
You can set Title color globally with styles API on MantineProvider:
```tsx
<MantineProvider
  styles={{
    Title: (theme) => ({
      root: {
        color: theme.colorScheme === 'dark' ? 'blue' : 'red',
      },
    }),
  }}
>
  <Title order={1}>MantineProvider styles</Title>
</MantineProvider>
```

**Comment by matthewoates** [comment]
Thanks for the quick response @rtivital - I completely missed the `Styles API with MantineProvider` section.

**Comment by Strajk** [comment]
For future passers-by, this worked for me:
```js
Title: Title.extend({
  defaultProps: {
    c: 'orange',
  },
}),
```
