### ISSUE TITLE
SimpleGrid component doc page create confusion about css grid and flexbox

### ISSUE THREAD

**Issue by thatanjan** [mantinedev/mantine#4203]
### Link to the page where something nasty is located

https://mantine.dev/core/simple-grid/

### Exact quote of what is wrong

On the SimpleGrid component doc page, it says:
```
SimpleGrid is a simple flexbox container where each child is ...
```
![image](https://user-images.githubusercontent.com/71136371/236656400-83e77cd1-6e99-42f2-abf9-41a76f34f8d3.png)

But this component is actually using a CSS grid behind the scenes. Also at the end of the page, it says: 
```
Simple grid uses CSS Grid Layout ...
```
![image](https://user-images.githubusercontent.com/71136371/236656379-7255d8e1-74ee-4381-9a1b-7991183d1cc3.png)

This can create confusion. So, I think we should fix it.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
