### ISSUE TITLE
Header buttons and links do not work due to console error

### ISSUE THREAD

**Issue by creme332** [mantinedev/mantine#4204]
### Link to the page where something nasty is located

https://mantine.dev/core/action-icon/

### Exact quote of what is wrong

This error is actually present on all pages following the format: `https://mantine.dev/core/<something>/`
Open developer console. A similar error is present:
![console error](https://user-images.githubusercontent.com/65414576/236661122-081d8c90-fd62-4859-a99a-9ace88a09617.png)

# Consequences of this error
This error causes the following buttons and the search bar in the header to become unusable:
![image](https://user-images.githubusercontent.com/65414576/236661288-37fb49a4-ed34-446c-b16a-97b8cdde691e.png)

Clicking on any of these buttons does nothing.
The only way to get around this is to use shortcuts. example `CTRL + J` to toggle theme.

# Info about browser

<html>
<body>

Google Chrome | 112.0.5615.138 (Official Build) (64-bit) (cohort: Stable)
-- | --
OS | Windows 10 Version 22H2 (Build 19045.2846)
JavaScript | V8 11.2.214.14

</body>
</html>

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
I cannot reproduce that neither on Windows nor on macOS in Chrome.

**Comment by rtivital** [comment]
Furthermore, there aren't any files like `tabPrompt.chunk.js` on mantine.dev website, most likely they are coming from one of your extensition.

**Comment by creme332** [comment]
I think you are right. I disabled the LastPass extension, refreshed the mantine website then re-enabled the extension again. Everything now works properly. I am not able to reproduce the bug again after enabling the extension again though.
