### ISSUE TITLE
[Radio]   Multiple radio with the same name,   onChange will not trigger

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4211]
### What package has an issue

@mantine/core

### Describe the bug

The radio tag of h5 supports multiple radio using the same name.
In this way, radio can be scattered in different components. Is there any way for mantine to support name?
The following code does not take effect
When switching another label, two events should be triggered
The previous one is checked false, the next one is checked:true

```
const [list,setList] = useImmer([
{label:'a',checked:true}
])

list.map((item,index)=>
<Radio 
 value={item.label} 
 label={item.label}  
 name='name' 
 checked={item.checked} 
onChange={()=> item[index]['checked']=> event.target.checked}>
 )

```

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please provide a sandbox with minimal reproduction. Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

**Comment by vaynevayne** [comment]
<img width="832" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/0c373520-e4c8-40c4-bf0d-1df6bf2fce45">
It's all right. It's a html restriction.
