### ISSUE TITLE
how to show week number on calendar 

### ISSUE THREAD

**Issue by ntkhoinguyen** [mantinedev/mantine#4214]
### What package has an issue

@mantine/dates

### Describe the bug

Hi !

I want to show week number on the calendar and DatePicker. But I can't find any prop that support this?

![image](https://github.com/mantinedev/mantine/assets/43131830/06af44b2-5f9c-4f96-91c6-7f8b40b3f46d)

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please use Issues to report bugs. To ask questions or request features, use GitHub Discussions.
Showing week numbers is not supported.
