### ISSUE TITLE
BUG: Using MultiSelect on Safari jumps to the top of the page. 

### ISSUE THREAD

**Issue by hunterwilhelm** [mantinedev/mantine#4220]
### What package has an issue

@mantine/core

### Describe the bug

When selecting an item on the https://mantine.dev/core/multi-select/ page it jumps to the top. But only on Safari.

I am using Safari Version 16.4 (18615.1.26.110.1)

Here's a video of it in action

https://github.com/mantinedev/mantine/assets/71348224/09482b4e-03a0-464c-baa9-772eb3fcbd77

### What version of @mantine/hooks page do you have in package.json?

v6.0.10

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/multi-select/

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 6.0.11
