### ISSUE TITLE
Background color for TextArea with label is not working correctly

### ISSUE THREAD

**Issue by xoitx** [mantinedev/mantine#4222]
### What package has an issue

@mantine/core

### Describe the bug

TextArea with label is not styling properly.
If I put a background color its styling the label and not the area

bg={'#F1F5F9'}

![image](https://github.com/mantinedev/mantine/assets/18355529/457dddc5-0f16-42cc-98d5-b990f7fca7d3)

### What version of @mantine/hooks page do you have in package.json?

6.0.4

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
`bg` property changes background color or root element. You can change input background with Styles API: `<Textarea styles={{ background: 'red' }} />`.

**Comment by xoitx** [comment]
It seems to be doing the same thing

**Comment by rtivital** [comment]
`<Textarea styles={{ input: { background: 'red' } }} />`
