### ISSUE TITLE
[Issue] Cannot clear Select value with creatable prop

### ISSUE THREAD

**Issue by jharrelson** [mantinedev/mantine#423]
When the creatable prop is being used for a Select, the value is not clearable.  I've attached a code sandbox below to demo.

Select a value in the select and then click the reset button. 

https://codesandbox.io/s/blue-breeze-ts023?file=/src/App.js

EDIT: It seems like there is a workaround using the `useForceUpdate` utility hook.

**Comment by rtivital** [comment]
Thanks for reporting, @achmurali can you have a look at this?

**Comment by achmurali** [comment]
> Thanks for reporting, @achmurali can you have a look at this?

Yeah definitely, @rtivital .

**Comment by rtivital** [comment]
Fix was released in 3.2.0, @jharrelson please check if everything works correctly and reopen this issue if you are still experiencing any problems
