### ISSUE TITLE
Where is controlled TimeInput gone?

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#4232]
### What package has an issue

@mantine/core

### Describe the bug

Just upgraded to `6.0` from `5.10`, which took hours to update due to tons of changes, I see there's no way to control TimeInput anymore?

How can we control it now?
We need it for our app..

![Screenshot 2023-05-12 at 08 56 16](https://github.com/mantinedev/mantine/assets/22228431/9e67602d-16f9-467a-bb89-6346f2813829)

**Before:**

![Screenshot 2023-05-12 at 08 59 48](https://github.com/mantinedev/mantine/assets/22228431/4fd583d7-20f7-4c35-9540-dde7116a9053)

**After upgrading:**

![Screenshot 2023-05-12 at 08 59 19](https://github.com/mantinedev/mantine/assets/22228431/1e84959c-6821-43b0-af57-8057805c7207)

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please use Issues to report bugs, for questions use Discussions. 
TimeInput in 6.0 is regular `input[type="time"]` you can control its value the same way as you would regular input element.

**Comment by atumas-bananamilk** [comment]
How?
All Mantine wrappers for these expose a `value` & `onChange`. We obviously want to avoid vanilla JS.
https://mantine.dev/hooks/use-input-state

**Comment by rtivital** [comment]
https://codesandbox.io/s/brave-paper-w1lizo?file=/src/App.tsx

**Comment by atumas-bananamilk** [comment]
@rtivital what about `format="12"` being gone? Our users use different meridiems.

**Comment by rtivital** [comment]
`input[type="time"]` automatically changes format based on user language

**Comment by atumas-bananamilk** [comment]
"User language"? It means it's related to the browser?
What if we have a setting in our application to change between 12 / 24?
It's not related to the browser then.

Is it still possible to force the format without relying on "user language"?
