### ISSUE TITLE
Button with icon has different sizing than without it

### ISSUE THREAD

**Issue by mlanin** [mantinedev/mantine#4233]
### What package has an issue

@mantine/core

### Describe the bug

For some reason button without icon and with icon or loading state have different size/positioning. If you try to make horizontal form it will look pretty weird. Especially in action https://codesandbox.io/s/magical-bose-xryt48?file=/src/App.tsx Tried in Google Chrome and Safari.

<img width="414" alt="Screenshot 2023-05-12 at 12 03 00" src="https://github.com/mantinedev/mantine/assets/467159/c4b75b58-d413-49ef-9ccc-1d5a9154f0dc">

### What version of @mantine/hooks page do you have in package.json?

^6.0.10

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/magical-bose-xryt48

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by Clifford18** [comment]
ighugyu

**Comment by Profex1999** [comment]
If you analyze the dimensions with inspect element, the height of the components it's the same. The issue is caused by the align property. You set "baseline", if you don't set that prop it works as expected.

**Comment by mlanin** [comment]
First, I need baseline, because input itself could spawn error message that will increase input height.
Second, if you inspect all three buttons in the given example, you will see that all of them have the same height: 2.25rem that is 36px.

**Comment by mlanin** [comment]
@Profex1999 I found the problem. You were right. It's because of the baseline. My bad :)
