### ISSUE TITLE
AutoImport for Text element not working?

### ISSUE THREAD

**Issue by oliverkidd** [mantinedev/mantine#4239]
### What package has an issue

@mantine/core

### Describe the bug

When using the matinee <Text> component my auto imports never seem to pick it up? Everything else works as expected its just the auto import so I have to manually import from core each time.

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by vaynevayne** [comment]
This is normal behavior, because Text seems to be in dom. When the name is repeated, the priority is given to dom. I don't know if there is a relevant ts configuration, and you can specify which one to resolve.

**Comment by rtivital** [comment]
Text is a native constructor, it is not possible
