### ISSUE TITLE
useLocaleStorageValue in @mantine/hooks provides null for first render despite given defaultValue

### ISSUE THREAD

**Issue by JohannesKlauss** [mantinedev/mantine#424]
Using the `useLocalStorageValue` in 3.1.9 has a bug. The first render will always return `null`, because the defaultValue gets set in an `useEffect`.

Reproduction (check the console.logs and change the locale storage key to a non existing one if you missed it):
https://codesandbox.io/s/nice-perlman-fmmtb?file=/src/App.js

the second render will return the `defaultValue`, but this behavior is inconsistent with the typings which imply that a `string` will always be returned if `defaultValue` is given.

I am not sure, but I think changing the return from

```ts
return [value, setLocalStorageValue] as const;
```

to

```ts
return [value || defaultValue, setLocalStorageValue] as const;
```

should be sufficient enough to fix it.

**Comment by rtivital** [comment]
Fix was released in 3.2.0
