### ISSUE TITLE
NumberInput formatter: doesn't reformat on formatter change

### ISSUE THREAD

**Issue by finnharbeke** [mantinedev/mantine#4247]
### What package has an issue

@mantine/core

### Describe the bug

I have a NumberInput component that takes a money amount as input. Hence I have a formatter function as follows:

```jsx
<NumberInput
    formatter={s => currency.code + ' ' + s}
    ...
/>
```

When currency gets changed from e.g USD to EUR the numberinput string value stays `USD 5.00`, since the value doesn't change and hence no reformat is triggered. If I'd then change the amount it correctly formats to EUR.

It's possible to make an ugly workaround by setting the value to some other number for a few milliseconds and setting it back to the originial value but it's visible and obviously not a fix.

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/numberinput-formatter-change-zmqigi?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by finnharbeke** [comment]
@4m1n83 thanks! this already looks promising.
But it raises an issue of the difference between the ref.current.value and the value set by mantine.

try this:
- enter 5 into the numberinput, it will correctly be formatted to `5.00` as no currency is selected
- select euros and the numberinput will be correctly formatted to `EUR 5.00` by the `useEffect`
- now focus on the number input, notice how the value jumps back to `5.00`. Then, simply by leaving the focus (or changing the number) it will reformat correctly
- same thing if from `EUR 5.00` you choose dollars; `useEffect` makes it `USD 5.00`, if you then focus on the numberinput it jumps back to `EUR 5.00`. Leaving focus or changing the number afterwards will format correctly to `USD 5.00`

**Comment by 4m1n83** [comment]
@finnharbeke 
Maybe it is not using "formatter" but how do you find this solution?
https://codesandbox.io/s/numberinput-formatter-change-forked-ul3jzc?file=/src/App.tsx

**Comment by finnharbeke** [comment]
@4m1n83 thank you! didn't think of that but works perfectly.

i'm probably going to do `icon={(code && value !== "") ? code + " " : ""}` so that the code is not there when the input is empty, but that's just details:)

ig it's just a workaround but i'll cöose the issue
