### ISSUE TITLE
DateInput with time not working

### ISSUE THREAD

**Issue by levytskyiTaras** [mantinedev/mantine#4255]
### What package has an issue

@mantine/dates

### Describe the bug

- try to open and select the date but less than the 12th of any month then try to edit seconds and click outside. 
- Day changing places with month.

https://github.com/mantinedev/mantine/assets/88840211/2bdc561b-4765-4a58-a160-86f2fcaecef7

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by 4m1n83** [comment]
a working solution using dateParser: https://codesandbox.io/s/unruffled-rubin-257l87?file=/src/App.tsx

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
