### ISSUE TITLE
doc: broken link to GlobalStyles from Dark theme

### ISSUE THREAD

**Issue by pimartin** [mantinedev/mantine#426]
Hi,

On the [Dark theme page](https://mantine.dev/theming/dark-theme/), in the section [Global Styles](https://mantine.dev/theming/dark-theme/#global-styles), there is a link to the documentation for the `GlobalStyle` component: https://mantine.dev/theming/global-styles/

However, that page is a 404.

I don't know if the link is just broken or if the GlobalStyle component is deprecated (I'm discovering the theming API).

(Also, I ❤️ mantine. Thanks for your work)

**Comment by rtivital** [comment]
Thanks for reporting! We will fix this issue in next minor release

**Comment by rtivital** [comment]
Fix was released in 3.2.0
