### ISSUE TITLE
nested theme  not working

### ISSUE THREAD

**Issue by lanyusan** [mantinedev/mantine#4262]
### What package has an issue

@mantine/core

### Describe the bug

I am using mantine with nextjs. 

The global theme is light. I wish to get an area to dark using nested themeprovider. But it is not working.

```
        <MantineProvider
          theme={{
            colorScheme: 'dark',
          }}
        >
          <Box
            p="md"
            sx={{
              ...baseSx,
              borderRadius: '4px',
            }}
          >
            <Text fz="sm">xxx/Text>
          </Box>

          <Box
            p="md"
            sx={{
              ...baseSx,
              flexGrow: 1,

              borderRadius: '4px',
            }}
          >
            <Group>
              <Text fz="sm">xxx</Text>
              <Text fz="sm">xxx</Text>
            </Group>
          </Box>
        </MantineProvider>
```

There is another provider at the very root of _app.tsx.

The nested theme is not able to set subcomponents to dark mode correctly.

### What version of @mantine/hooks page do you have in package.json?

6.0.11

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.
