### ISSUE TITLE
Error setting custom primary color

### ISSUE THREAD

**Issue by ivangomestr** [mantinedev/mantine#4279]
### What package has an issue

@mantine/core

### Describe the bug

I'm trying to customize primary color with my colors, but it returns the following error:

```
properties of undefined (reading 'startsWith')
     at toRgba (to-rgba.ts:37:13
```

I tried to customize it as described in the documentation. Strangely, the custom colors of 'ocean-blue' described in the documentation work. But with my own colors, it is returning error:

```
<Wrapper>
        <MantineProvider
          withGlobalStyles
          withNormalizeCSS
          theme={{
            colors: {
              blue: [
                '#e6f7ff',
                '#bae7ff',
                '#91d5ff',
                '#69c0ff',
                '#40a9ff',
                '#1890ff',
                '#096dd9',
                '#0050b3',
                '#003a8c',
                '#212e3e',
              ],
              green: ['#648E94', '#43767D', '#225E66', '#143F47', '#28FF52'],
            },
            fontFamily: 'FTBase Regular, sans-serif',
            primaryColor: 'green'
          }}
        >
          <CustomFonts />
          <Notifications />
          <Router />
        </MantineProvider>
      </Wrapper>
```

### What version of @mantine/hooks page do you have in package.json?

6.0.11

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Colors must have 10 elements
