### ISSUE TITLE
Carousel onNextSlide and onPreviousSlide does not work

### ISSUE THREAD

**Issue by alimehasin** [mantinedev/mantine#4286]
### What package has an issue

@mantine/core

### Describe the bug

It seems like the onNextSlide and onPreviousSlide callbacks don't get called

### What version of @mantine/hooks page do you have in package.json?

v6.11

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/heuristic-wind-90x99m?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Use embla 7.x – https://codesandbox.io/s/divine-brook-twingb?file=/src/App.tsx
