### ISSUE TITLE
[V7] Ideas for improvements and fixes

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#4287]
### What package has an issue

@mantine/core

### Describe the bug

Hi.
In this topic if you allow me to write my ideas for the problems I observe in the [V7 alpha version](https://v7.mantine.dev/)
I don't want to create this in the discussions because it's a problem and ideas may be challenged or corrected by other participants and it's more in plain sight than in the discussions where few people look.

### What version of @mantine/hooks page do you have in package.json?

[v7]

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by 7iomka** [comment]
### Borders for buttons
I see that you are using the kss variables to the maximum.
This is good, but bad in terms of bloating html with more code in the style attribute.
So I think you should only put there what needs customization at the place of use, not at any use.
So, for example, at the moment I see that you are using the code for button border:
```css
border: var(--_button-bd, var(--button-bd));
```
The first css variable `--_button-bd` can be settled internally 
The second one `--button-bd` is always settled in `style` prop and can be overrided by user:
```css
--button-bd: calc(0.0625rem * var(--mantine-scale)) solid transparent;
```
For outline variant of button instead of transparent color we will see some solid color.
The size of border is always the same, as well as the border style (`solid`);
Why we always use this constant values each time in style attribute?
Instead of doing this, my suggestion is to use the base styles for border inside css of component
```css
border: calc(0.0625rem * var(--mantine-scale)) solid var(--_button-bd-color, var(--button-bd-color));
```
Now we can control the button border color
- internally through `--_button-bd-color` (for example for disabled state of outline variant we can change border color to disabled one). Has no default value settled
- Basically through `--button-bd-color` which can also be optionally set only if the border needs to be seen visually,  otherwise we can use fallback value (`var(--button-bd-color, <fallbackvalue>)`) with `transparent` or with `var(--button-bg)` for solid variant or if you force the best practices.

This rule can be followed for most css properties. This will avoid problems with priorities or the need to rewrite the rule entirely for the sake of a single value. Moreover, in the future you can easily add the ability to control other parts of the property, such as thickness or style for border, with variables. 

In the example with the button, I will demonstrate the problem
1) Open [Link from the docs](https://v7.mantine.dev/theming/colors#colors-variant-resolver)
2) Open browser devtools and add `disabled` prop for all three variants of button
3) You will see the unexpected border color for outline button variant
![image](https://github.com/mantinedev/mantine/assets/18473137/7f2725da-ab61-46af-9a1f-be75fe5156c6)

**Comment by rtivital** [comment]
Some variants like `gradient` do not have a border. Changing the logic from `--button-bd` to `--button-bd-color` will require addiotion of extra variable to control border-width.

**Comment by 7iomka** [comment]
@rtivital
`Some variants like gradient do not have a border.` - ok, `transparent` as fallback will be a good solution.

`Changing the logic from --button-bd to --button-bd-color will require addiotion of extra variable to control border-width`
- if you don't know and don't want to know what values is for border style or border color, and just want to change border size - now you need to know it to change just one part of prop. Otherwise - you just add inline style like `border-width: rem(5)`. This is not differs from one when you will change this through separate css variable for border width (if this is really usefull for someone.

**Comment by 7iomka** [comment]
### Styles for light and dark theme - both in different mixins

Since I observe in the documentation for version 7 that the recommended approach for declaring `light` and `dark` theme styles is to use **_mixins_** - for each [separate one](https://v7.mantine.dev/styles/postcss-preset#dark-and-light-mixins), it seems that this is done for reasons of support for setting the theme on demand for nested DOM elements.



But it doesn't work - if we choose a dark theme and then put a date-attribute on some element of the container of the light theme, its content will not become light, because apparently the priority is given to the dark theme, as styles for it follow in order after the light theme styles.

<img width="671" alt="image" src="https://github.com/mantinedev/mantine/assets/18473137/de4d5463-84f0-44f3-a093-02fae6428b1d">

Hence the question - why do we need to muxin the styles for the light theme, instead of just using one dark theme muxin to override the variables we need?

**Comment by rtivital** [comment]
dark and light mixins as well as light-dark function is a shorthand for media query + data-mantine-color-scheme attribute.

**Comment by 7iomka** [comment]
> dark and light mixins as well as light-dark function is a shorthand for media query + data-mantine-color-scheme attribute.

I understand this, but I don't understand why we need to defined some styles inside `light` mixin? What actual use case for this whereas
- We don't have light styles working on a particular section if the overall theme is set as dark. In fact, none of the solutions (including the most popular ones such as tawildind) support this on the grounds that it is not needed in 99.9% of cases.
- The same rare case is when the site was originally designed in dark colors, and somehow miraculously the developer decides to meet the needs of users accustomed to the light colors.

From my experience, the best solution is to write code for the normal color scheme, and apply overrides for the dark theme through the mixin.

Users on their sites usually have two options for theme switches:
1) A toggler between a dark and light theme, the value of which is determined automatically from the system settings, the user can toggle the values but after the page reloads the preference will be selected again from the system
2) Toggler between dark, light and system theme (optional) with user preferences retained. Initial value can be light or system theme, calculation value is saved in cookies or localstorage, when user toggles the value is re-saved and after reloading the page it will see the previously selected.

The second case is used more often.
As I can see you used hybrid approach: 1st, but after user changed the value it stored in localstorage, and after user changes the system preference it will never be reset to system definition.

as long as the user doesn't select anything you put an auto value which equates to no attribute and that's where the argument for using additional styles with media queries is?

If you are using setting a data attribute on the root element using media queries via js, then why do we need to additionally use them in css? Are just attributes not enough for us?

Here's how I set up my theme switcher in V6.
https://codesandbox.io/s/bitter-dream-x4nq8r?file=/src/App.tsx
(I cut it out of my next.js app, where the initial value is taken from the cookie from app.getInitialProps)

This approach is considered best practice at the moment as it allows the user to stay on the system theme.
As for styles (media queries), as for me, they can be optionally included through some condition in the postcss plugin for users who really want to see them as a result.
For example, I do not see the need for my code to be 2 times heavier without the need for it.

**Comment by rtivital** [comment]
Thanks for the feedback, I've simplified dark/light color schemes logic. Now it is possible to use `dark` mixin without `light` and vice versa:

```css
.demo {
  background: red;

  @mixin dark {
    background: blue;
  }
}
```

**Comment by 7iomka** [comment]
## Postcss functions

## `rem` function
Do we really need this function?
As we use postcss, we can use a special plugin that will solve the problems with having to manually wrap all values into a function. especially any multiple values (box-shadow) or expressions within calc.

Currently I'm used `postcss-pxtorem` plugin,
```js
    'postcss-pxtorem': {
      rootValue: 16, // we use 1rem = 16px (browser's default)
      unitPrecision: 5,
      propList: ['*', '!letter-spacing'],
      /**
       * ignore html,body {} rule - fixes issue with min-width on the body that requires real pixel value
       * ignore scrollbar styles - fixes big scrollbars issue
       */
      selectorBlackList: [/^html[^body]+body$/, /^\.container/, /::-webkit-scrollbar/, /:export/],
      replace: true,
      mediaQuery: false,
      minPixelValue: 1,
      exclude: () => {
        return false;
      },
    },
```

and I don't care about manually wrapping each value in a function in my code.
I keep writing it in pixels that I feel comfortable with, and the output is a value in rem with a preconfigured scale (rootValue).

Users who, like me, are planning to migrate to v7 may be concerned about migration

I've looked at the [approach of using a css variable for this](https://github.com/mantinedev/postcss-preset-mantine/blob/master/postcss-rem-em.js#L1), to which the rem function multiplies the value in the rem when scale is turned on, but for myself I can't find a real case where the user would need to maintain a dynamically configurable scale and still write the pixel value, it doesn't make any sense. Scale setting makes sense when the user writes rem values immediately from the understanding of what scale they have. A common reason for this is that it is difficult to calculate rem values in the user's mind, so users prefer to set the scale to 10px instead of 16px and use the rem values directly, which is easily obtained by dividing the original value by 10.

If I am wrong, please explain your view on this.
Many thanks!

**Comment by rtivital** [comment]
rem function is completely optional – it is not required to be used to convert px to rem. You can install `postcss-pxtorem` and it will work correctly. rem units scaling is implemented mostly for users who will choose alternative styling methods, for example Tailwind, emotion or styled-components. So, it actually gives you more freedom to pick the tools that you want to use for styling.

**Comment by hichemfantar** [comment]
I like the move to pure CSS and the introduction of a headless option.
I was hoping you would consider moving to tailwind CSS. Maybe in v8.
Tailwind makes writing pure CSS a bliss and the ecosystem around it is amazing.
