### ISSUE TITLE
Group Direction does not work.

### ISSUE THREAD

**Issue by abdul-mustapha** [mantinedev/mantine#4288]
Error: 
![image](https://github.com/mantinedev/mantine/assets/52088263/fb329e20-965c-41de-947a-2facaa1d0b42)

Error Message: 
```
Type '{ children: (Element | undefined)[]; grow: true; direction: string; spacing: "xl"; }' is not assignable to type 'IntrinsicAttributes & GroupProps & RefAttributes<HTMLDivElement>'.
  Property 'direction' does not exist on type 'IntrinsicAttributes & GroupProps & RefAttributes<HTMLDivElement>'.
```

**Comment by rtivital** [comment]
The Group component does not have a direction prop. If you need a vertical flexbox container, use the Stack component instead.

**Comment by ziimakc** [comment]
@rtivital example needs to be updated then https://v3.mantine.dev/core/group/
