### ISSUE TITLE
DateTimePicker inconsistent time format 24h vs 12h format in Firefox

### ISSUE THREAD

**Issue by fbucek** [mantinedev/mantine#4294]
### What package has an issue

@mantine/core

### Describe the bug

I cannot change format for TimeInput, but problem is that it does not work as expected and time format differs in Firefox

21:57 vs 09:57 PM

Main example: https://mantine.dev/dates/date-time-picker/

![image](https://github.com/mantinedev/mantine/assets/3756242/6508f827-4cc3-4736-a523-ddb6885f41f1)

Would be nice to have posibility to force 24 or 12h format.

Often application are developed in one language only so automatic change base on localization can only cause problem.

### What version of @mantine/hooks page do you have in package.json?

6.0.11

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by fbucek** [comment]
Thanks for clariication.  So only option for me is to create custom component, which wont use input[type="time"].
I would expect that both shown times are in 24 format or both in AM/PM  or possible to change both, but DateTimePicker can change only part using `valueFormat`. 

So problem is that time input using some kind of native implementation which is browser dependend and other is using different implementation which is browser independent.

**Comment by rtivital** [comment]
You can also try changing value format based on user locale

**Comment by guvenaltunsoyy** [comment]
Why does not support custom time formatter or rendering?
