### ISSUE TITLE
Modal - body scroll behavior needed

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#4297]
### What package has an issue

@mantine/core

### Describe the bug

Is it possible to use scrolling on the body element instead of scrolling on the content container in the modal?
I have a custom component that consists of Input from mantine and unordered list (ul) with suggestions that appears (position absolute) when user type in input.

So, when I use this component anywhere except modal - all works fine.
Inside modal it was cutted.

I tried to wrap the `ul` with `Portal`, but I don't know how to configure it position in relation to the input - Portal just render my list at the end of body.

Of course I understand that all your components are prepared correctly (`withinPortal` prop), but what about users who are not ready for this behaviour and can't switch to your components completely (for example I can't switch to autocomplete component instead of my custom implementation yet)

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Modal component lock body scroll when opened. If this is unwanted behavior, set `<Modal lockScroll={false} />`. Then you will be able to change Modal styles with Styles API.
