### ISSUE TITLE
Carousel navigation  buttons do not have accessible names

### ISSUE THREAD

**Issue by creme332** [mantinedev/mantine#4309]
### What package has an issue

@mantine/carousel

### Describe the bug

According to [PageSpeed Insights](https://pagespeed.web.dev/), the carousel component navigation buttons do not have an accessible name. This causes the accessibility rating of a webpage using the carousel to decrease. Paste this URL (https://mantine.dev/others/carousel/) into PageSpeed Insights website to see:

![image](https://github.com/mantinedev/mantine/assets/65414576/f9eb9cd3-6c25-4c67-8805-02606eb7f7bc)

Mantine version: `v6.0.11`

### What version of @mantine/hooks page do you have in package.json?

not applicable

### If possible, please include a link to a codesandbox with the reproduced problem

not applicable

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Add aria-label to buttons

**Comment by rtivital** [comment]
You can set these attributes in your application with `nextControlLabel` and `previousControlLabel` props

**Comment by dannya** [comment]
`nextControlLabel` and `previousControlLabel` have changed as of Mantine v7, are now expressed as:

```
previousControlProps={{
    'aria-label': 'Previous',
}}
nextControlProps={{
    'aria-label': 'Next',
}}
```
