### ISSUE TITLE
NumberInput controls are not displayed as disabled if min/max reached

### ISSUE THREAD

**Issue by richardboehme** [mantinedev/mantine#4313]
### What package has an issue

@mantine/core

### Describe the bug

In versions prior to Mantine 6 the controls of a NumberInput were styled as disabled buttons when min/max were reached. 

![image](https://github.com/mantinedev/mantine/assets/61323346/3c37333c-58c5-4f8b-b0d6-ec5f1087ba24)

In version 6 of Mantine this disabled style vanished away:

![image](https://github.com/mantinedev/mantine/assets/61323346/f1e19a37-fb14-4dc8-9526-d067239053c0)

The button cannot be clicked and has the disabled property, however the style does not exist anymore. I looked through the changes and it seems to be related to this change: https://github.com/mantinedev/mantine/pull/4152/files#diff-a207d6f87884b9bf6bd9f50f0f89b02c78c12fbfe9f65ba0f5ba29bdcf364680

Is this change intended?

### What version of @mantine/hooks page do you have in package.json?

6.0.11

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/vigilant-merkle-1jbsl3?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Revert the change in NumberInput.styles.ts (https://github.com/mantinedev/mantine/pull/4152/files#diff-a207d6f87884b9bf6bd9f50f0f89b02c78c12fbfe9f65ba0f5ba29bdcf364680). However, I'm not sure if it's an intended change.

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
