### ISSUE TITLE
Select component's dropdown is rendered inside Modal

### ISSUE THREAD

**Issue by DoronTorangy** [mantinedev/mantine#4316]
### What package has an issue

@mantine/core

### Describe the bug

When a `Select` component is rendered inside a `Modal`. Its dropdown is cut, and limited only to the box of the modal.
So if I have a large dropdown, not all items will be shown.

Even if you add `zIndex` the dropdown will be rendered over the modal's title, but still within its box.

Is this intentional?  how can I render the dropdown outside the modal?

I tried the following, didn't work:
```ts
<Select {...someProps} styles={{
            dropdown: {
                zIndex: 1000000
            }
        }}
 />
```

### What version of @mantine/hooks page do you have in package.json?

6.0.11

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/twilight-pond-qjljz2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
https://codesandbox.io/s/angry-rain-m5ldeo
