### ISSUE TITLE
Font not rendering in Tiptap Rich Text Editor: NextJS 13 App Router

### ISSUE THREAD

**Issue by gurbaaz27** [mantinedev/mantine#4317]
### What package has an issue

@mantine/tiptap

### Describe the bug

I am currently using the Tiptap-based rich text editor provided [here](https://mantine.dev/others/tiptap/). I am using Lato font across my web application, and for some reason the text editor contents (including the placeholder text) does not render Lato font, but rather some other as can be seen in the image. I'm new to using Mantine, and it would be very helpful if i can get some help on the same.

![Screenshot from 2023-05-28 16-38-58](https://github.com/mantinedev/mantine/assets/60743677/0e3d5be6-a18a-45b1-b204-1216d9a03422)
![Screenshot from 2023-05-28 16-39-07](https://github.com/mantinedev/mantine/assets/60743677/7bd96daf-1a72-4f5e-b5ea-5f0d6772062e)
![image](https://github.com/mantinedev/mantine/assets/60743677/7dc201b0-603e-41e3-aa99-41058ee21679)

### What version of @mantine/hooks page do you have in package.json?

^6.0.11

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You can customize components styles with Styles API

**Comment by gurbaaz27** [comment]
@rtivital can you point me to relevant documentation or links? Thanks.

**Comment by rtivital** [comment]
https://mantine.dev/styles/styles-api/
