### ISSUE TITLE
Select, and DateInput components get cut off in Modal, and there is no scroll to see the cut off parts

### ISSUE THREAD

**Issue by naishe** [mantinedev/mantine#4321]
### What package has an issue

@mantine/core

### Describe the bug

I have a `Modal` component that hosts a three field form including a `Select` and a `DateInput` components. Both these components get cut off and there is no way to scroll to reach to cut off parts as shown in the attached images.

```jsx
<Modal
        opened={opened}
        onClose={close}
        title="Create new Session"
      >
        <CreateSessionForm />
      </Modal>
```

The dependencies versions are as follows:

```json
    "@mantine/core": "^6.0.10",
    "@mantine/dates": "^6.0.10",
    "@mantine/form": "^6.0.10",
    "@mantine/hooks": "^6.0.10",
    "@mantine/notifications": "^6.0.10",
```

<img width="468" alt="Screen Shot 2023-05-29 at 1 02 07 AM" src="https://github.com/mantinedev/mantine/assets/845424/9dc1fe8f-3cc7-4c82-bd81-43485d701018">
<img width="465" alt="Screen Shot 2023-05-29 at 1 02 21 AM" src="https://github.com/mantinedev/mantine/assets/845424/f17df386-faa0-45ff-b088-433717f59640">

### What version of @mantine/hooks page do you have in package.json?

^6.0.10

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Set `<Select withinPortal />`, `<DateInput popoverProps={{ withinPortal: true }} />`
