### ISSUE TITLE
Z-index overlay is wrong with multiple modals

### ISSUE THREAD

**Issue by stijnvanderlaan** [mantinedev/mantine#4332]
### What package has an issue

@mantine/core

### Describe the bug

In mantine v5, when you open 2 modals the overlay of top modal is above the other, in v6 this is not the case.

You can see difference in the codesandbox by switching @mantine/core version between v5 and v6.

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/falling-sound-suuge8?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You can control Modal z-index with `zIndex` prop. It is not possible to know the order of the modals that you will render in your application.

**Comment by stijnvanderlaan** [comment]
Ah right, thanks you!
