### ISSUE TITLE
Disabled TextInput with right section disables entire input

### ISSUE THREAD

**Issue by noahsb** [mantinedev/mantine#4334]
### What package has an issue

@mantine/core

### Describe the bug

When rendering a `TextInput` with a `rightSection` that has a `NativeSelect` in it, disabling the `TextInput` causes the `rightSection` to disappear visually and the entire input becomes disabled

I would expect that only the `TextInput` would become disabled, not the `NativeSelect` or at least the `rightSection` to remain visible when disabled

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/peaceful-field-s775wl?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by mkroemer** [comment]
I'm running in the same problem. Having several numeric inputs where you can select the unit in the right section. I would at least expect to be able to see the select value. Best would be to be able define if the right section should be disabled as well or not.

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
