### ISSUE TITLE
MultiSelect hoverOnSearchChange not respected when creatable

### ISSUE THREAD

**Issue by noahsb** [mantinedev/mantine#4335]
### What package has an issue

@mantine/core

### Describe the bug

As per https://github.com/mantinedev/mantine/issues/4164, I would expect that adding `hoverOnSearchChange` to `MultiSelect` would focus the first element

I believe this was working at one point (as early as 6.0.8) but is no longer working as expected

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/trusting-jennings-ydqxbh?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by AdleyJulian** [comment]
If you have data in the Multiselect then it selects the first element during your search. I don't understand the issue. 

![image](https://github.com/mantinedev/mantine/assets/1316426/6375e99d-ea60-40d6-98dc-c2b06707e1f0)

https://codesandbox.io/s/wizardly-james-h92ln4

**Comment by noahsb** [comment]
@AdleyJulian It works fine for values already present in the data array. But it should also work for adding new values. You can see that in the original codesandbox example where adding a new value does not hover when the search changes

![Untitled](https://github.com/mantinedev/mantine/assets/49932437/f25bcc05-c2ae-4ebc-ab71-60aa3922f22f)

**Comment by rtivital** [comment]
Fixed by #4389, will be available in 6.0.14
