### ISSUE TITLE
Overlay color not work with named color

### ISSUE THREAD

**Issue by hwookim** [mantinedev/mantine#4337]
### What package has an issue

@mantine/core

### Describe the bug

`<Overlay />` not work with named color like `white`, `gary`

```
<Overlay opacity={0.7} color="white" blur={3} />
```
This return 
```css
    position: absolute;
    top: 0rem;
    right: 0rem;
    left: 0rem;
    bottom: 0rem;
    background-color: rgba(0, 0, 0, 0.7); // not work!
    -webkit-backdrop-filter: blur(0.1875rem); 
    backdrop-filter: blur(0.1875rem);
    border-radius: 0rem;
    z-index: 200;
```

```tsx
<Overlay opacity={0.7} color="#fff" blur={3} />
```
This return
```css
    position: absolute;
    top: 0rem;
    right: 0rem;
    left: 0rem;
    bottom: 0rem;
    background-color: rgba(255, 255, 255, 0.7);
    -webkit-backdrop-filter: blur(0.1875rem);
    backdrop-filter: blur(0.1875rem);
    border-radius: 0rem;
    z-index: 200;
```

### What version of @mantine/hooks page do you have in package.json?

6.0.11

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/zealous-blackburn-n64gmm

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Fix [`theme.fn.rgba(color, opacity)`](https://github.com/mantinedev/mantine/blob/8c12a76c56da51af34213f18dd67c8b72a0ddb44/src/mantine-core/src/Overlay/Overlay.styles.ts#LL18C47-L18C76)

The fastest way is to separate color and opacity.

**Comment by rtivital** [comment]
It is not an option to change opacity as it will also change the opacity of the overlay children. Named colors are not planned to be suppotred.

**Comment by hwookim** [comment]
@rtivital 
In version 5, named color was supported.
When I migrated to version 6, that part stopped working.
Was this an unintended situation before?

**Comment by rtivital** [comment]
It is correct behavior starting from version 6.0.0
