### ISSUE TITLE
Input.Wrapper label is not block

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4339]
### What package has an issue

@mantine/core

### Describe the bug

<img width="912" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/5e736e20-04ad-4883-bdc9-8099a7ba40b5">

```jsx
 <Grid.Col md={12}>
              <Input.Wrapper label="接口权限">
                <OtherSelect />
              </Input.Wrapper>
```

In fact it is inline

<img width="581" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/894a4e16-8516-4556-a2da-1464a88a2d99">

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is correct behavior, if label was block then when user clicked on empty space it will shift focus to the input.

**Comment by vaynevayne** [comment]
<img width="582" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/72a9b77d-1776-4450-9791-a44460f93ef2">


so, why inputBase is block, why Input 's label is block
```jsx
 <InputBase
                label="接口权限"
                component={() => (
                  <Select
                    style={{ width: '100%' }}
                    placeholder="接口权限"
                    mode="multiple"
                    maxTagCount={'responsive'}
                    options={permissionsOptions2}
                    {...form.getInputProps('permissions')}
                  />
                )}
              />
```

**Comment by vaynevayne** [comment]
> It is correct behavior, if label was block then when user clicked on empty space it will shift focus to the input.

And why is the ui effect on the document a block?
