### ISSUE TITLE
Menu/Popover fallback placement broken in 3.2.1

### ISSUE THREAD

**Issue by jvdsande** [mantinedev/mantine#434]
Hello!

I've come across an issue with the latest version of Mantine, where `Menu` and `Popover` fallback placement don't seem to work anymore.

Version information:
- @mantine/core@3.2.1
- @mantine/hooks@3.2.1
- Chromium: 95.0.4638.69

Here is an attached screenshot of the behavior I'm observing:

![image](https://user-images.githubusercontent.com/12484011/142668754-adc17f54-76d6-43ba-b370-97d1e91135b3.png)

The Menu placement is `end`, the position is `bottom`. With 3.1.x in this situation the placement correctly flipped to `start`, but not anymore.

I've seen than if editing the `Popper` component and adding `bottom-start` and `bottom-end` to the `fallbackPlacements` prop, I get the correct behavior back.

Maybe `fallbackPlacements` should be available on `Menu` and `Popover` and passed down to `Popper` to make this customizable?

Anyway, thanks for the awesome library, it's been a pleasure trying it out lately :)

**Comment by rtivital** [comment]
Hi @jvdsande, thanks for reporting! @EmilMalanczak can you please have a look at this?

**Comment by EmilMalanczak** [comment]
Yes, I'll look on that. In apart from the issue, shall I add `fallbackPlacements ` prop to `Menu` and `Popover` components?

**Comment by rtivital** [comment]
I do not have any idea how it's working right now, so it's up to you. Just one question – cannot we make it fully automatic, the same it was before on Popper component level? For example, if it receives bottom-end placement, it will automatically create a fallback for top-end placement.

**Comment by EmilMalanczak** [comment]
possibly but I'm not sure if that automatic behaviour would be expected in 100%. I'll make it as something similar to `fallbackPlacements || getDefaultFallbackPlacement(placement)`

**Comment by jvdsande** [comment]
For my use case I'd be perfectly fine with just having access to `fallbackPlacements` on the Popover and Menu components. I've tried manually patching the dist with this and it worked perfectly.

I guess it's not easy - maybe even not possible - to have a config that cover all cases, so the ideal is to allow this to be set case by case through a prop

**Comment by rtivital** [comment]
Fixed in 3.2.3, @jvdsande can you please update to this patch and see if it resolves your issue?

**Comment by jvdsande** [comment]
I'll try that as soon as I can :)

**Comment by jvdsande** [comment]
Chiming in here a bit late: finally had the time to test latest release, the comportement is fixed now, thanks!

**Comment by rtivital** [comment]
Cool, thanks for collaboration!

**Comment by dexter4life** [comment]
Hello, sorry if this is the wrong place.

I am having something similar as a problem. any idea what I have to do to fix it?

![image](https://user-images.githubusercontent.com/10168414/198917610-80668a5b-21e3-4c68-8bee-09e950ec53b1.png)
