### ISSUE TITLE
for size, Text use  fz, other component use size, why ?

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4340]
### What package has an issue

@mantine/core

### Describe the bug

<Text fz='small'>

other component
<Input size='small' />

Why isn't it uniform? It's so damn hard to use

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please use Discussions to ask questions.

`fz` is a style prop that sets font-size in all components.

**Comment by vaynevayne** [comment]
There's something wrong with the design here
 ```jsx
fz='small' // ✅
font-size: 'small' // ❌

```
This is not a thing at all, and secondly, I'm going to set the font size, and I'm going to use style, or classname, instead of memorizing mantine's component prop
