### ISSUE TITLE
typesafe context modals - MantineModalsOverride doesnt work

### ISSUE THREAD

**Issue by mpsenicka** [mantinedev/mantine#4341]
### What package has an issue

@mantine/modals

### Describe the bug

I am trying to let typescript hint me names of context modals, as listed in [this](https://mantine.dev/others/modals/#typesafe-context-modals) chapter.

By providing modals override through MantineModalsOverride interface, i successfully extend modals by "testOverride", as shown in picture below:
![image](https://github.com/mantinedev/mantine/assets/55763666/cf698b17-0638-4e87-a136-f1033687885a)

But even though i extend it, MantineModal type still extracts only "string" value, as shown here:
![image](https://github.com/mantinedev/mantine/assets/55763666/9a43cc9e-5a0c-48d4-b3e0-f72f8960d036)

I think wanted behaviour is as follows:
![image](https://github.com/mantinedev/mantine/assets/55763666/95b587fb-f558-4b8b-83ec-5fde7191558b)

Do you have an idea on how to solve this? Or am i doing something wrong?

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/musing-lehmann-wbj8lp?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Don't check whether overrides structure has modals property, just let user override it as he would like. Typically if someone changes d.ts files, he usually knows what he's doing

**Comment by mpsenicka** [comment]
PR: https://github.com/mantinedev/mantine/pull/4343

**Comment by rtivital** [comment]
Fixed in #6443
