### ISSUE TITLE
Getting started page suggests installing @emotion/server @emotion/react without explanation

### ISSUE THREAD

**Issue by nicolassanmar** [mantinedev/mantine#4345]
### Link to the page where something nasty is located

https://mantine.dev/guides/next/

### Exact quote of what is wrong

"
Install dependencies:
```
yarn add @mantine/core @mantine/hooks @mantine/next @emotion/server @emotion/react
```
"

I myself am not sure why installing those `@emotion` packages is recommended, as I've tried not installing those and my next app works just fine.
I think we should explain why it's useful to install those packages (in all the guides), or remove them if they are not necessary.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
These packages are peer dependencies of `@mantine/core` and `@mantine/next` packages. If you do not have these installed, Mantine will either not work at all or might have issues.
