### ISSUE TITLE
Password input visibility toggler moves cursor to beginning

### ISSUE THREAD

**Issue by onderbakirtas** [mantinedev/mantine#4346]
### What package has an issue

@mantine/core

### Describe the bug

When searching for a UI framework for my new NextJS projects, I discovered this beauty. It's feature packed and looks so clean. But when playing with components, I encountered an issue that if you filled password input with some text and pressed toggle (the eye icon), the cursor moves to the beginning of the input. Not a major issue but it's quality of life improvement I have seen and developed before.

### What version of @mantine/hooks page do you have in package.json?

The version which Mantine website uses

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
I cannot reproduce the issue 

https://github.com/mantinedev/mantine/assets/10353856/4abb938f-524f-4136-9300-2f61e574e3ce

**Comment by onderbakirtas** [comment]
> I cannot reproduce the issue
> 
>  2023-06-02.09.48.10.mov

It's on https://mantine.dev , on the section where title is "100+ components". I'm using Mac.

**Comment by rtivital** [comment]
https://github.com/mantinedev/mantine/assets/10353856/bd3a0bd0-eec0-4778-acb3-f2be1b279e6f

I cannot reproduce it on the home page either, I've tested it in Safari, Chrome and Firefox on macOS

**Comment by onderbakirtas** [comment]
> https://mantine.dev

https://github.com/mantinedev/mantine/assets/6013550/5937d7fd-6b67-4acc-88ca-e733ac44696d

Here is my screen recording. MacOS 13.4, Microsoft Edge latest.

**Comment by rtivital** [comment]
I cannot reproduce it in the Edge browser on macos with version 7.0:

https://github.com/mantinedev/mantine/assets/10353856/2f1c1266-5378-4b06-8626-95fe5b1bfaf9
