### ISSUE TITLE
eslint raises warning Component definition is missing display nameeslintreact/display-name in Select.demo.itemComponent.tsx

### ISSUE THREAD

**Issue by tonytony2020** [mantinedev/mantine#4347]
Run this snippet with mantine ^6.0.7, eslint raises warning `Component definition is missing display nameeslintreact/display-name`
https://github.com/mantinedev/mantine/blob/8c12a76c56da51af34213f18dd67c8b72a0ddb44/src/mantine-demos/src/demos/core/Select/Select.demo.itemComponent.tsx#LL113C7-L113C17

<img width="1047" alt="Screenshot 2023-06-02 at 11 20 09" src="https://github.com/mantinedev/mantine/assets/63030915/27c5a80e-c1e8-4de4-9a24-0dffe5e00bdd">

I try to walk around it:
```
// keep following make eslint happy https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/display-name.md
SelectItemRegion.displayName = "";
```

**Comment by rtivital** [comment]
Mantine demos provide source code that is required for components to work. If you need display name for components in your application, add it on your side or disabled this eslint rule.
