### ISSUE TITLE
Nextjs13 Mantine SSR config?

### ISSUE THREAD

**Issue by enesdmc0** [mantinedev/mantine#4353]
### What package has an issue

@mantine/core

### Describe the bug

I want to use nextjs13 app dic Mantine but it gives use client error. How to use Mantine in SSR There is not enough information in the document

### What version of @mantine/hooks page do you have in package.json?

@mantine/ssr

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
See https://github.com/mantinedev/mantine/issues/2815

**Comment by enesdmc0** [comment]
I want to use mantine as ssr with nextjs13 but I can't use it, I don't know how to make settings

**Comment by rtivital** [comment]
Follow the issue that I've shared to learn about available options to use Mantine with Next.js app dir
