### ISSUE TITLE
TextInput validation error message doesn't disappear when TextInput is hidden

### ISSUE THREAD

**Issue by starkbtc** [mantinedev/mantine#4355]
### What package has an issue

@mantine/core

### Describe the bug

TextInput validation error message doesn't disappear when TextInput is hidden
<img width="350" alt="image" src="https://github.com/mantinedev/mantine/assets/43443357/c58c2f13-4239-43fe-a8f1-329b264ac618">

### What version of @mantine/hooks page do you have in package.json?

Latest

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
How is it supposed to appear of the input is hidden?
