### ISSUE TITLE
AppShell inside AppShell breaks Navbar

### ISSUE THREAD

**Issue by alexle-dev** [mantinedev/mantine#4356]
### What package has an issue

@mantine/core

### Describe the bug

Hi, when I try to created a fixed={false} AppShell inside another AppShell, the Navbar bugs out and the space of the navbar is occupied even in the parent AppShell, despite it not having a Navbar.
I attached a CodeSandbox link to explain it better.

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hopeful-pascal-dfysq4?file=/src/App.tsx:0-841

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Make it so the outer AppShell doesn't take the Navbar width from the inner AppShell.

**Comment by alexle-dev** [comment]
This is also fixable by setting a very large number as navbarOffsetBreakpoint, like 9999999. But it's not a good solution in my opinion so I'd like an official fix.

**Comment by rtivital** [comment]
Nested AppShell components are not supported. It is also not planned to support this feature in the future – it is outside of the project scope.
