### ISSUE TITLE
Carousel: Don't need to use clickAllowed anymore

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#4357]
### What package has an issue

@mantine/carousel

### Describe the bug

The latest Embla handles this automatically ([davidjerleke/embla-carousel#423](https://github.com/davidjerleke/embla-carousel/pull/423))

But your source code contains missed property
https://github.com/mantinedev/mantine/blob/master/src/mantine-carousel/src/CarouselSlide/CarouselSlide.tsx#LL41C24-L41C38

```ts
if (ctx.embla?.clickAllowed()) {
   onClick?.(event);
}
```
Now `clickAllowed` is removed (I can't find it in the documentation either).

Since users can use versions 7.x and 8x at the same time (I am not sure which version removed this feature yet),
I propose to rewrite the above code as follows:
```ts
const canAutoHandleClick = typeof ctx.embla?.clickAllowed === 'undefined';

if(!canAutoHandleClick) {
  if(ctx.embla?.clickAllowed?.()) {
      onClick?.(event);
  }
} else {
   onClick?.(event);
}
```

Someone please do a PR with this little change.

This will unlock the ability to update users who want to use the current version of the carousel.

The funny thing is that carousel author was probably in such a hurry to roll out updates that now rc versions are installed with normal yarn install command (including plugins), so number of users who will potentially get an error
![image](https://github.com/mantinedev/mantine/assets/18473137/702a3507-66f4-4601-af0a-b1f4b1b026f5)

 when using mantine will be more than can be expected.

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 6.0.17 – clickAllowed is no longer called
