### ISSUE TITLE
Drawer position doesn't work well when dir=rtl && position='right'

### ISSUE THREAD

**Issue by starkbtc** [mantinedev/mantine#4359]
### What package has an issue

@mantine/core

### Describe the bug

Drawer position doesn't work well when dir=rtl && position='right'
Position is overflow the screen
<img width="233" alt="image" src="https://github.com/mantinedev/mantine/assets/43443357/27397c41-b588-4ee5-bdf4-5a65df8ecce9">

### What version of @mantine/hooks page do you have in package.json?

Latest

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is expected behavior, Drawer position is flipped in rtl
