### ISSUE TITLE
Nested Navlinks doesn't work well in rtl direction

### ISSUE THREAD

**Issue by starkbtc** [mantinedev/mantine#4361]
### What package has an issue

@mantine/core

### Describe the bug

Nested Navlinks doesn't work well in rtl direction
the arrow should point left in rtl direction
![image](https://github.com/mantinedev/mantine/assets/43443357/a55461c6-d114-4c2e-8261-3cc3cac75424)

### What version of @mantine/hooks page do you have in package.json?

Latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by aalirezamoradii** [comment]
still exist on 7.2.2
