### ISSUE TITLE
Select dropdown in a modal is briefly visible while modal opens when searchable and rendered in a portal

### ISSUE THREAD

**Issue by ChapterSevenSeeds** [mantinedev/mantine#4363]
### What package has an issue

@mantine/core

### Describe the bug

If you have a `<Select />` component rendered inside a modal with the `withinPortal` and `searchable` props set to true, the dropdown of the select appears visible for what seems like one frame right when the modal is opened. It then disappears and behaves normally, opening and closing as requested by the user.

In the codesandbox, you might have to have a monitor with at least a 60 Hz refresh rate in order to see the dropdown appear. I recorded a video at 60 FPS and the dropdown is visible for exactly one frame, as shown in the image below.

<img width="1565" alt="image" src="https://github.com/mantinedev/mantine/assets/63123355/48241c5f-bf5a-4a73-ac9c-fdaf97dd6580">

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/jovial-dust-00t76c

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Both Modal and Select components work as intended. To fix the issue, make sure that Select is not focused before Modal animation finishes playing.
