### ISSUE TITLE
PinInput deleting more than 1 character when backspacing 

### ISSUE THREAD

**Issue by cooervo** [mantinedev/mantine#4366]
### What package has an issue

@mantine/core

### Describe the bug

steps to reproduce

1. on any pininput with more than 3 slots fill it out
2. now click on front of first character in first slot
3. press backspace
4. notice 2 characters are removed

video for reference

https://github.com/mantinedev/mantine/assets/11219268/b5289c6b-c96d-44fd-9d57-689a2ed85367

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by kangwritescode** [comment]
what's the expected behavior? should it erase all character after and including the current focused one?

**Comment by Thomas-DevArk** [comment]
I would presume that when deleting a character, all other characters remain in their current positions. As for example a mis-input, they will just want to change the one character that was meant just for that position, but i guess in other ways it will turn out different depending on the mistake aka entering more than 1 character in a row as a mistake. 

Possible solution: Have enum field for possible onDelete/onBackspace methods.
