### ISSUE TITLE
Select Input sends user to the top of the page

### ISSUE THREAD

**Issue by simonlehmannstonex** [mantinedev/mantine#4367]
### What package has an issue

@mantine/core

### Describe the bug

Hello,
we have found an issue with the Select Component. 
Using a Select with a large dataset and custom "itemComponent" and "searchable" prop, you will find yourself on the top of the page when double clicking on the input of the Select.
This happens in my codesnippet on first render, in most of our implementations the select needs to rerender because its a controlled component which sends the user every time he wants to mark the input of the search field to the top of the page.

### What version of @mantine/hooks page do you have in package.json?

6.0.11

### If possible, please include a link to a codesandbox with the reproduced problem

https://stackblitz.com/edit/stackblitz-starters-jcnrdi?file=src%2FApp.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Try updating all `@mantine/*` packages to the latest version
