### ISSUE TITLE
Autocomplete options inconsistent

### ISSUE THREAD

**Issue by p7gg** [mantinedev/mantine#4377]
### What package has an issue

@mantine/core

### Describe the bug

Am I doing something wrong here? I feel like it should be working, but somehow it isn't.

When I type an ID in the input (i.e. 1, 2, 3 ...) after the fetch it only shows 1 item, if it even shows anything.

thats what I get with ID 1:
![image](https://github.com/mantinedev/mantine/assets/69444613/6d0fcf13-daa9-43b0-bc3e-10da5d097cc8)

with ID 2 it doesn't even show anything:
![image](https://github.com/mantinedev/mantine/assets/69444613/07d781de-c4d3-4b6b-8c44-668864c77c92)

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/sandbox/mantine-playground-1xu3hp?file=%2Fsrc%2FApp.tsx%3A1%2C1

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by julamb** [comment]
By default, Autocomplete only suggests items in `data` that start with the input value. 
It seems like the behavior you're expecting could be obtained by adding `filter={() => true}` as a prop on the `Autocomplete` component to disable filtering altogether?

**Comment by p7gg** [comment]
> By default, Autocomplete only suggests items in `data` that start with the input value. It seems like the behavior you're expecting could be obtained by adding `filter={() => true}` as a prop on the `Autocomplete` component to disable filtering altogether?

Yeah, you're right. this worked. Thanks a lot!
