### ISSUE TITLE
useMantineTheme & useStyle triggers unnecessary re-renders

### ISSUE THREAD

**Issue by Firullo96** [mantinedev/mantine#4378]
### What package has an issue

@mantine/core

### Describe the bug

I'm using mantine in my next.js 13 project.
I have a sidebar component that uses "useMantineTheme" hook, and I noticed that, when I change the page,  it keeps re-render even when nothing is changed inside it.
The problem disappears if I remove the "useMantineTheme" hook.

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
