### ISSUE TITLE
[use-storage] Accidental execution twice

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4382]
### What package has an issue

@mantine/hooks

### Describe the bug

```jsx
const [value, setValue] = useLocalStorage({ key: 'color-scheme', defaultValue: 'dark' });

  useEffect(() => {
    console.log('deps改变了', value)

    fetch()
  }, [value])
```

Will result in two fetch executions,

Normal should be like this, synchronous execution

```jsx
const [value] = useLocalStorage(localStorage.getItem('color-scheme'))
```

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
use-local-storage gets values in useEffect by default to prevent hydration mismatches in ssr environments. If you do not have ssr, you can change this logic by setting `getInitialValueInEffect` option.

**Comment by vaynevayne** [comment]
Awesome, tql
