### ISSUE TITLE
DateInput style issue with tailwind

### ISSUE THREAD

**Issue by reza-ebrahimi** [mantinedev/mantine#4387]
### What package has an issue

@mantine/dates

### Describe the bug

There is an styling problem with tailwind which `DateInput` takes full width with unknown style:

```jsx
<DateInput
    label="Birthday"
    maw="400px"
    mx="auto"
    {...form.getInputProps("birthday")} />
```

Provider:
```jsx
<MantineProvider
    withGlobalStyles
    withNormalizeCSS
    emotionCache={createEmotionCache({ key: "mantine", prepend: false })}
    theme={{
        globalStyles: (theme) => ({ body: { minHeight: "100vh" } }),
    }}>
    {children}
</MantineProvider>
```

![Screenshot from 2023-06-10 14-14-00](https://github.com/mantinedev/mantine/assets/11276982/47fef49d-1ebf-40ae-a458-09816db1f61b)

Versions:

```json
"@emotion/react": "^11.11.0",
"@mantine/core": "^6.0.11",
"@mantine/hooks": "^6.0.11",
"@mantine/dates": "^6.0.13",
"@mantine/form": "^6.0.11"
```

### What version of @mantine/hooks page do you have in package.json?

^6.0.11

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Hi @reza-ebrahimi, unfortunately we cannot provide any support for Tailwind. Mantine provides Styles API with which you can apply styles to any inner element with `classNames` and `styles` props. If you decide to use a third-party library for styling, you should resolve the issues on your side.

**Comment by reza-ebrahimi** [comment]
> Hi @reza-ebrahimi, unfortunately we cannot provide any support for Tailwind. Mantine provides Styles API with which you can apply styles to any inner element with `classNames` and `styles` props. If you decide to use a third-party library for styling, you should resolve the issues on your side.

I think the issue is not about tailwind support, and based on the code snippet in the issue description, its not using any tailwind stuff, or even the `classNames` and `styles` props.

With just using tailwind in a project mantine styles is not working. 
I followed the instructions to get this fixed and it worked for mantine `core` components (EmotionCache in provider), but with mantine `dates` components the style gets messy.

**Comment by paulfilipan23** [comment]
any fixes with this one? I'm having the same issue with DateInput in nextjs.
