### ISSUE TITLE
Highlighter function causes RegExp error if text to be highlighted has invalid regex expression

### ISSUE THREAD

**Issue by porkopek** [mantinedev/mantine#439]
**highlighter** function [here](https://github.com/mantinedev/mantine/blob/f48304c21257a6f8a089ab87c8b8826d76e3fc39/src/mantine-core/src/components/Highlight/highlighter/highlighter.ts#L1)  doesn't escape the input value (highlight:string), causing a regex error if the part you want to highlight has some invalid regex expression, like a no matched bracket

Example: 
```js
highlighter('a) article 22', 'a)')
```

- What package has an issue (@mantine/core, mantine/hooks or other)?
**mantine-core**

- What package version are you using?
**3.21**

- Do you have an idea how to fix the issue?
**Escaping input value in the highlighter function**

- Are you willing to participate in fixing this issue (it's totally fine if not) and create a pull request with the fix?
**Just reporting**

**Comment by porkopek** [comment]
Maybe this is a feature,  because it enables regex highlighting, and the user just have to escape the string  themselves, but then I think you should allow to choose the flags, that are hardcoded in the function.

**Comment by rtivital** [comment]
Thanks for reporting, we will fix that in next patch

**Comment by porkopek** [comment]
As I said in the second comment, maybe the way it is now is good, because it allows regex highlight. Just warn in the docs

**Comment by rtivital** [comment]
No, it's a security vulnerability, basically it's an eval wrapped in regex, already fixed it, patch will be out soon

**Comment by rtivital** [comment]
Fix was released in 3.2.2
