### ISSUE TITLE
Chip not working with icons

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#4390]
### What package has an issue

@mantine/core

### Describe the bug

Chip component isnt working with icons (when selected):

```
<Chip variant="light" value={category.label} color={category.color}>
  <div className='flex items-center gap-1 inline-block'>
    <Icon size={18}/>
    {category.label}
  </div>
</Chip>
```

![Screenshot 2023-06-11 at 08 14 50](https://github.com/mantinedev/mantine/assets/22228431/b9caab0d-8913-4d03-b1ec-93a7a520c305)

If unselected - all good.
If selected - not working.

Maybe this could also be a feature request - icons for Chip component.

### What version of @mantine/hooks page do you have in package.json?

^6.0.0

### If possible, please include a link to a codesandbox with the reproduced problem

-

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Try updating packages to the latest version, the issue was fixed recently

**Comment by atumas-bananamilk** [comment]
> 

Worked thanks
