### ISSUE TITLE
Select component does not display searchValue on component render

### ISSUE THREAD

**Issue by gitjeff05** [mantinedev/mantine#4398]
### What package has an issue

@mantine/core

### Describe the bug

When using the Select component as a controlled component with searchable, a few odd things seem to happen:

1.) When passing the the initial value to `useState` from a prop, the initial value in `Select` component is not visible in the select component.

2.) When calculating the value manually and setting state, the initial value renders properly. However, no clear button is visible (even if `clearable` is set)

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/jolly-austin-yc4v8t

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by cyantree** [comment]
Why do you need `searchValue` and `onSearchChange` instead of `value` and `onChange`? If you switch to these props everything works as expected.
https://codesandbox.io/s/autumn-thunder-q37fw3?file=/src/SelectFilter.js
