### ISSUE TITLE
Bug: Setting withGlobalStyles is not setting color to theme.black in light mode

### ISSUE THREAD

**Issue by nammi-kobler** [mantinedev/mantine#4403]
### What package has an issue

@mantine/core

### Describe the bug

Setting `withGlobalStyles` for `MantineProvider` doesn't set the color to `theme.black` for e.g. `Button` component.

Code Sandbox: https://codesandbox.io/s/headless-fast-fs7wrl?file=/src/theme.ts

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/headless-fast-fs7wrl?file=/src/theme.ts

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
`withGlobalStyles` do not change color of the Button component, it is intended behavior. You need to change that on your side.
