### ISSUE TITLE
type HotkeyItem for react hook not exported

### ISSUE THREAD

**Issue by Morriz** [mantinedev/mantine#4404]
### What package has an issue

@mantine/core

### Describe the bug

Running this code:
```ts
    const keys: HotkeyItem[] = [
      ['Escape', blur, { preventDefault: true }],
      ['ctrl+Enter', onSubmit, { preventDefault: true }],
    ]
    if (submitOnEnter) {
      keys.unshift(['Enter', onSubmit, { preventDefault: true }])
    }
    const handler = getHotkeyHandler(keys)
```

I get the following error when using the regular exported HotkeyItem:
```
Argument of type 'import("/Users/Morriz/Documents/Workspace/morriz/ai-assistant/app/node_modules/@mantine/hooks/lib/use-hotkeys/use-hotkeys").HotkeyItem[]' is not assignable to parameter of type 'HotkeyItem[]'.
  Type 'import("/Users/Morriz/Documents/Workspace/morriz/ai-assistant/app/node_modules/@mantine/hooks/lib/use-hotkeys/use-hotkeys").HotkeyItem' is not assignable to type 'HotkeyItem'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '(event: KeyboardEvent) => void' is not assignable to type '(event: KeyboardEvent | React.KeyboardEvent<HTMLElement>) => void'.
        Types of parameters 'event' and 'event' are incompatible.
          Type 'KeyboardEvent | React.KeyboardEvent<HTMLElement>' is not assignable to type 'KeyboardEvent'.
            Type 'KeyboardEvent<HTMLElement>' is missing the following properties from type 'KeyboardEvent': isComposing, initKeyboardEvent, DOM_KEY_LOCATION_STANDARD, DOM_KEY_LOCATION_LEFT, 
```

### What version of @mantine/hooks page do you have in package.json?

5.10.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

export the type as `ReactHotkeyItem`?

**Comment by rtivital** [comment]
There is not ReactHotkeyItem type. The error that you have is correct – hotkey handlers are added to the document, not some element that onSubmit is associated with. To get rid of the error, you can wrap it with a function: `() => onSubmit()`

**Comment by rtivital** [comment]
Send a sandbox with a minimal reproduction, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

**Comment by cyantree** [comment]
You `blur` or `onSubmit` handler is likely typed as `(event: KeyboardEvent) => void`.
However the expected type is `(event: React.KeyboardEvent<HTMLElement> | KeyboardEvent) => void` (so it has to accept the native `KeyboardEvent` and also the `React.KeyboardEvent`)

Therefore if you don't care about the passed argument at all you can simply omit it as shown in the official example and described by @rtivital:
https://mantine.dev/hooks/use-hotkeys/

If you need the event you have to adjust the type accordingly (see above).
