### ISSUE TITLE
Path in getInputProps does not work correctly if the value is null

### ISSUE THREAD

**Issue by gansmmm** [mantinedev/mantine#4406]
### What package has an issue

@mantine/form

### Describe the bug

```
export default function App() {
  const form = useForm({
    initialValues: {
      a: null,
      b: {
        b1: null
      },
      c: undefined,
      d: null
    }
  });
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <TextInput {...form.getInputProps("a")} label="a" />
      <TextInput {...form.getInputProps("b.b1")} label="b.b1" />
      <TextInput {...form.getInputProps("c.c1")} label="c.c1" />
      <TextInput {...form.getInputProps("d.d1")} label="d.d1" /> // error
    </MantineProvider>
  );
}
```

If the value is "null " there is an error when you try to refer to the child element, although everything works correctly with "undefined"

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/tender-panka-5yss86?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Change methods getPath and setPath

**Comment by rtivital** [comment]
TextInput value should not be null, empty value for `input[type="text"]` is an empty string (`''`). `undefined` is also an incorrect value – you may get an error for switching input from uncontrolled to controlled state.

**Comment by gansmmm** [comment]
Instead of "TextInput" there can be an arbitrary input (MyTextInput) which supports null and undefined

There is a need to receive initialValues from an asynchronous request (from back) and there in the hierarchy of objects can be null.

The problem is in the internal methods "getPath" and "setPath".
Error in "getPath" where one parent value is null.
Error in "setPath" where one parent value is null or undefined.

```
interface Names {
  shortName: string,
  name: string
}

interface Book {
  names?: Names | null
}

export default function App() {
  const form = useForm<Book>({
    initialValues: {}
  );
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <TextInput {...form.getInputProps("names.name")} label="Name" />
      <TextInput {...form.getInputProps("names.shortName")} label="Short name" />
    </MantineProvider>
  );
}

export default function App1() {
  const form = useForm<Book>({
    initialValues: {
      names: null
    }
  );
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <TextInput {...form.getInputProps("names.name")} label="Name" />
      <TextInput {...form.getInputProps("names.shortName")} label="Short name" />
    </MantineProvider>
  );
}
```
Error in App when change Name or Short name.
Error in App1 when rendering.

You can change the methods as follows:
```
function getPath(path, values) {
    const splittedPath = getSplittedPath(path);
    if (splittedPath.length === 0 || typeof values !== "object" || values === null) {
        return undefined;
    }
    let value = values[splittedPath[0]];
    for (let i = 1; i < splittedPath.length; i += 1) {
        if (value == undefined) {
            break;
        }
        value = value[splittedPath[i]];
    }
    return value ?? undefined;
}

function setPath(path, value, values) {
    const splittedPath = getSplittedPath(path);
    if (splittedPath.length === 0) {
        return values;
    }
    const cloned = klona(values) ?? {};
    if (splittedPath.length === 1) {
        cloned[splittedPath[0]] = value;
        return cloned;
    }
    let val = (cloned[splittedPath[0]] ??= {});
    for (let i = 1; i < splittedPath.length - 1; i += 1) {
        val = (val[splittedPath[i]] ??= {});
    }
    val[splittedPath[splittedPath.length - 1]] = value;
    return cloned;
}
```

**Comment by rtivital** [comment]
Well, anyway, I cannot reproduce it codesandbox – https://codesandbox.io/s/small-glade-9mg5dg?file=/src/App.tsx
`form.getInputProps` works as expected

**Comment by gansmmm** [comment]
I meant if the parent object is null, i.e. in your example it would be 
```
initialValues: {
      a: null
    },
```
Modified your example:
https://codesandbox.io/s/proud-leftpad-v5fjpz?file=/src/App.tsx

**Comment by rtivital** [comment]
That is not supported, initial values must have the exact shape of your form values

**Comment by gansmmm** [comment]
The `getPath` method is strangely implemented, as if it supports undefined and null, but only as a root value.
It would be convenient if the `getPath` and `setPath` methods used in `form.getInputProps` supported handling null and undefined
