### ISSUE TITLE
No matching version found for @mantine/next@^6.0.13

### ISSUE THREAD

**Issue by KevinLu** [mantinedev/mantine#4408]
### What package has an issue

@mantine/core

### Describe the bug

I just upgraded all my mantine packages to 6.0.13 from 6.0.4. Everything was working before.

I'm running a github actions build for my project using the following dependencies:
```
    "@mantine/carousel": "^6.0.13",
    "@mantine/core": "^6.0.13",
    "@mantine/form": "^6.0.13",
    "@mantine/hooks": "^6.0.13",
    "@mantine/next": "^6.0.13",
    "next": "13.2.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
```

The build is failing because of

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @mantine/next@^6.0.13.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Package is available on npm – https://www.npmjs.com/package/@mantine/next
The latest version in 6.0.13

**Comment by KevinLu** [comment]
> Package is available on npm – https://www.npmjs.com/package/@mantine/next The latest version in 6.0.13

Yeah I'm not sure why Github CI isn't picking it up. Installs locally fine too.

**Comment by rtivital** [comment]
Not an issue with `@mantine/next` package
