### ISSUE TITLE
Modal should allow overflow

### ISSUE THREAD

**Issue by unrealsolver** [mantinedev/mantine#4409]
### What package has an issue

@mantine/core

### Describe the bug

Using `Select` inside a `Modal` adds scroll bar when `Select` is open:
**Actual**
![image](https://github.com/mantinedev/mantine/assets/1101771/784e598b-e914-4fad-82a6-18bece8eba58)
(Scroll bar is not visible on this screenshot, but you can scroll down whole modal)
**Expected**:
![image](https://github.com/mantinedev/mantine/assets/1101771/9e9d8224-5286-4ba8-9ef8-4239bef6b9a0)

### What version of @mantine/hooks page do you have in package.json?

6.0.10 (6.0.11 is installed)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/priceless-sky-274dld?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

```ts
const defaultTheme: MantineThemeOverride = {
  components: {
    Modal: {
      styles: (theme) => ({
        content: {
          overflowY: 'visible',
        }
      })
    },
  }
}
```

**Comment by rtivital** [comment]
Set `<Select withinPortal />`. You can also change styles of any component with Styles API on MantineProvider.

**Comment by beardo01** [comment]
Do you have a solution for `DatePickerInput` @rtivital?

**Comment by rtivital** [comment]
`popoverProps={{ withinPortal: true }}`
