### ISSUE TITLE
Select Dropdown Show in Back of Modal

### ISSUE THREAD

**Issue by bogordesaincom** [mantinedev/mantine#441]
```
@mantine/core@3.2.1
@mantine/hooks@3.2.1
Chrome: 96.0.4664.55 
```
Select hide in modal show in back of modal
<img width="473" alt="444" src="https://user-images.githubusercontent.com/51335197/142746203-22fc0810-5ef4-4c65-963d-27cd861bc3ac.png">
<img width="386" alt="rr" src="https://user-images.githubusercontent.com/51335197/142746204-53123f62-28f8-44c9-9dff-7cfc5b4937d2.png">

**Comment by rtivital** [comment]
Thanks for reporting, we will provide a fix for this issue in next patch

**Comment by bogordesaincom** [comment]
I use this for solution 

```
        <Modal zIndex={100} size={550} opened={props.opened} onClose={handleCloseDialog}>
```

and change appshell

```
<Navbar zIndex={90}
```
