### ISSUE TITLE
Notifacition queue maybe has some error

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4415]
### What package has an issue

@mantine/core

### Describe the bug

When an interface reports an error, an error message is displayed, but the notification displays and hides it several times

I don't know if anyone else has

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by KilianB** [comment]
You will most likely be asked to provide a [reproducible example](https://codesandbox.io/s/mantine-template-9ze89)

**Comment by vaynevayne** [comment]
I won't say sometimes if I can repeat it, but think for myself if there's a problem with some internal logic,

**Comment by rtivital** [comment]
Please send a sandbox with a minimal reproduction, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6
