### ISSUE TITLE
Select  variant="unstyled" should not has width and rightSection

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4421]
### What package has an issue

@mantine/core

### Describe the bug

should't has  any input container style

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
`variant="unstyled"` works the same way in all inputs. If you want to remove the chevron, set `rightSection={<span />}`
