### ISSUE TITLE
Every time a rerender occurs, using the dropdownComponent in the Select component will cause the dropdown list to scroll to the top.

### ISSUE THREAD

**Issue by chu-bin** [mantinedev/mantine#4424]
### What package has an issue

@mantine/core

### Describe the bug

I want to combine Mantine's multiSelect to create a multiTreeSelect that renders a tree in a dropdown. However, I have encountered the following issue.

When using a custom dropdownComponent with select/MultiSelect, triggering a rerender (like change state) causes the dropdown content to scroll to the top automatically. The expected behavior is for the scrollbar to remain in its original position.

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-dropdowncomponent-w2tvph?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by teh23** [comment]
This does not solve the problem completely. However, this particular example can be solved by adding useCallback
https://codesandbox.io/s/mantine-dropdowncomponent-forked-g4gtp3?file=/src/App.tsx

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
