### ISSUE TITLE
form validation of array items that are not objects

### ISSUE THREAD

**Issue by samthomson** [mantinedev/mantine#4445]
### What package has an issue

@mantine/core

### Describe the bug

In the docs I can only see how to validate arrays when the array contains object - I would then specify a validation rule for each object property. What I want is to validate each item (test it is set and matches a certain format). At present I could do that by validating each contained item and flagging the whole array (`videoIds`) as invalid, but I would like to validate each id and show an error individually.

What works:
```
initialValues: {
	videoIds: ['id-456', 'id-789'],
},
validate: {
    videoIds: value => // pseudocode: check each value is valid, and return an error if one fails
}
```
What I would like is something like:
```
validate: {
    videoIds: {
        '*': value => // psuecode: my custom validator that matches for ['id'] + ['-'] + [int]
    }
}
```

Is there a way to do this without mutation my data to be an array of objects with a property `id` and then the value?
I've scoured the docs and couldn't find an answer. PS Big thanks for the outstanding libs.

### What version of @mantine/hooks page do you have in package.json?

^6.0.4

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
No, it is not supported, you need to wrap strings with an object

**Comment by samthomson** [comment]
Okay, thanks for confirming.
