### ISSUE TITLE
[Checkbox] Checkbox are marked as read-only.

### ISSUE THREAD

**Issue by Crocsx** [mantinedev/mantine#4447]
### What package has an issue

@mantine/core

### Describe the bug

When using Mantine Checkboxes while having special css styles for read-only input, checkboxes takes those styles even tho they are not readonly. This doesn't happen with native html checkboxes.

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/still-smoke-29g697

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

I have not checked the code so I have no idea what is wrong.

**Comment by ShaifArfan** [comment]
You can't put read-only style on input checkbox. Even if you have `readOnly` attribute on it.

Check out MDN docs for it: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly

The attribute is not supported or relevant to <select> or input types that are already not mutable, such as checkbox and radio or cannot, by definition, start with a value, such as the file input type. range and color, as both have default values. It is also not supported on hidden as it can not be expected that a user to fill out a form that is hidden. Nor is it supported on any of the button types, including image.

**Comment by rtivital** [comment]
Thanks for explanation @ShaifArfan!
