### ISSUE TITLE
useForm with flat object is throwing an error on edit

### ISSUE THREAD

**Issue by sridhar-uno** [mantinedev/mantine#4448]
### What package has an issue

@mantine/form

### Describe the bug

Using the [official example](https://mantine.dev/form/values/) but with a flat object.

```
import flatten from "flat";

  const initState: any = flatten({
    terms: false,
    user: {
      firstName: "",
      lastName: ""
    }
  });

  const form = useForm({
    initialValues: initState
  });

  <TextInput
    label="First name"
    placeholder="First name"
    value={form.values["user.firstName"]}
    onChange={(event) =>
      form.setFieldValue("user.firstName", event.currentTarget.value)
    }
    // {...form.getInputProps("user.firstName")}
  />

```

Getting this error

`Cannot set properties of undefined (setting 'firstName')`

### What version of @mantine/form page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/dazzling-https-92vf7p

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
`useForm` hook does not support dots `.` in fields names – it is used as an internal separator between fields in getInputProps. You can use different separator on your side if you need this feature. It is not planned to be changed.
