### ISSUE TITLE
Disabled prop on a Menu.Item with "div" as the component doesn't work

### ISSUE THREAD

**Issue by ChapterSevenSeeds** [mantinedev/mantine#4450]
### What package has an issue

@mantine/core

### Describe the bug

The `disabled` prop on a menu item with the component set to `div` doesn't work.

```jsx
<Menu.Item component="div" disabled>My Item</Menu.Item>
```

TypeScript complains and the prop no longer has any effect on the nature of the menu item. It can still be clicked.

### What version of @mantine/hooks page do you have in package.json?

6.0.14

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/unruffled-panna-4z3l9v?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Since the component is polymorphic, could the disabled prop be pulled out of the intrinsic props of the underlying component and made its own prop as part of the base component? As long as there are preexisting styles for disabled components, I don't think this would be a complicated fix.

**Comment by rtivital** [comment]
Currently, Menu component does not support nested items – it will not work correctly and keyboard events will not be supported. 

> I just dunno if that warning can be safely ignored on all browsers and platforms

This is a warning for invalid HTML

**Comment by rtivital** [comment]
No, if I had, I would just add this feature into the library
