### ISSUE TITLE
Textarea not compatible with useForm?

### ISSUE THREAD

**Issue by larissa-n** [mantinedev/mantine#4459]
### What package has an issue

@mantine/core

### Describe the bug

Adding a Textarea inside a useForm-connected form results in a crash with:
```
No fetch handler defined and no upstream to proxy to specified. Make sure you're calling addEventListener("fetch", ...).
```

### What version of @mantine/hooks page do you have in package.json?

Latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Send a sandbox that reproduces the issue – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

**Comment by ngthuongdoan** [comment]
@larissa-n Is there any problems, I've tried and it's working very well. You can check here:
https://codesandbox.io/s/cool-platform-xzz63j?file=/src/App.tsx:261-269
