### ISSUE TITLE
date picker input doesn't appear completely inside modal component 

### ISSUE THREAD

**Issue by amr86tawfiq** [mantinedev/mantine#4461]
### What package has an issue

@mantine/core

### Describe the bug

when we put a date picker input component inside a modal component and click on the input to open the calendar, the calendar doesn't appear completely 

### What version of @mantine/hooks page do you have in package.json?

6.0.14

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

i think it is a z-index issue

**Comment by rtivital** [comment]
Send a sandbox with a minimal reproduction, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

**Comment by cyantree** [comment]
Try passing `popoverProps={{withinPortal: true}}` to the `DatePickerInput`.
