### ISSUE TITLE
Disabled NumberInput Hides RightSection on Edge Browser

### ISSUE THREAD

**Issue by elibroftw** [mantinedev/mantine#4463]
### What package has an issue

@mantine/core

### Describe the bug

When using rightSection on a NumberInput, disabled=true will hide the rightSection text.

### What version of @mantine/hooks page do you have in package.json?

^6.0.14

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/stupefied-meadow-mfkpjt?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

6.0.10 works as expected.

**Comment by mkroemer** [comment]
Same issue also on Safari on iOS.

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.

**Comment by elibroftw** [comment]
I appreciate this thanks.
