### ISSUE TITLE
DateTimePicker submitButtonProps onClick is overridden

### ISSUE THREAD

**Issue by wojonet** [mantinedev/mantine#4464]
### What package has an issue

@mantine/dates

### Describe the bug

I would like some custom behavior to be executed when the user clicks the Submit button on the `DateTimePicker` component.

It appears the that spread operation defined [here](https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/DateTimePicker/DateTimePicker.tsx#L229) may override the `onClick` prop defined earlier [here](https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/DateTimePicker/DateTimePicker.tsx#L220)

This causes an issue since the `onClick` function provided to the `ActionIcon` component is supposed to execute my custom `onClick` function attached  `submitButtonProps`'s and then close the associated Popover (or Modal). Instead, that spread operation takes my `onClick` function and uses that in place of the one written.

### What version of @mantine/hooks page do you have in package.json?

6.0.14

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/determined-sinoussi-9f79f5?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Ensure that the spread operation on the submit button's props doesn't override the `onClick` handler defined earlier in the component.

**Comment by cyantree** [comment]
As seen [here](https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/DateTimePicker/DateTimePicker.tsx#L221) your usecase is supported so yeah, the spread shouldn't override `onClick` as described by you.

So feel free to submit a PR to fix this.

**Comment by wojonet** [comment]
Will do sometime today or tomorrow. Thanks!
