### ISSUE TITLE
DatePickerInput placeholder color does not reflect error state when there is an error

### ISSUE THREAD

**Issue by alessandroaw** [mantinedev/mantine#4467]
### What package has an issue

@mantine/dates

### Describe the bug

The placeholder color of the DatePickerInput component does not change to red to reflect the error state when there is an error. Currently, when an error is present in the DatePickerInput, the placeholder color remains unchanged, unlike other input components which turn red.

### What version of @mantine/hooks page do you have in package.json?

6.0.14

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-dateinputpicker-placeholder-wrong-color-m56w38

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

The error occurred due to a difference in behavior between the `DatePickerInput` component and the standard `Input` component. The `DatePickerInput` uses the `Input.Placeholder` component to implement the placeholder functionality, which requires customization to match the behavior of the `Input` component. In order to address this issue, it may be necessary to pass the error state to the `Input.Placeholder` component for consistent behavior.

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
