### ISSUE TITLE
[@mantine/core] Group Component -> Issues with gaps/spacing

### ISSUE THREAD

**Issue by cx0onl** [mantinedev/mantine#447]
Hello together!

First of all congratulations and thanks for Mantine! This is by far the best library for React out there!

I use the Group component very often in my UI. In doing so, I have noticed several bugs:

1.) An unwanted gap is inserted after the last item. Therefore the items do not use the whole available width.
![group-gap](https://user-images.githubusercontent.com/51824711/142833799-ebe78052-7a67-4f81-9270-7237f87ce979.png)

2.) With the combination of "grow" and "apart" the spacings between the items are no longer correct.

![group-spacing](https://user-images.githubusercontent.com/51824711/142833828-19179def-3136-470f-8359-fd0fae0a1057.png)

I would expect both variants ("left/grow" and "apart/grow") to give the same result: Three items of equal (grown) width with two correct spacings in between. 

Thanks!

- What package version are you using? 3.2.1
- In which browser and operating system issue occurred? Windows 11, Chrome
- If possible please attach link to codesandbox with reproduced issue: https://mantine.dev/core/group/

**Comment by rtivital** [comment]
Hi @cx0onl, thanks for reporting! I cannot think of a way we can fix it on our side, as it seems to be a browser behavior. Maybe you have any ideas?

**Comment by cx0onl** [comment]
It looks like the problem is comming from the calculation of the child width. 

https://github.com/mantinedev/mantine/blob/557594325b2c14158e12e8b9bfaef6096ed17f71/src/mantine-core/src/components/Group/Group.styles.ts#L39

**Comment by cx0onl** [comment]
You added this lines in July:
https://github.com/mantinedev/mantine/commit/53d903fd888fab38ea577a193a10e2865a3f4333#diff-d4b7b3ac6a72ceed5b7ac9cec0a0ad59f44f7615f87d0ed037202ab769b2e98b

**Comment by cx0onl** [comment]
`calc(${100 / count}% - ${(count - 1/count) * theme.fn.size({ size: spacing, sizes: theme.spacing })}px)`

Mayby this should fix it? Only add **count - 1 / count** (eg. 2/3) spacing to each child.

**Comment by rtivital** [comment]
I've released a patch 3.2.2 with a fix, can you please update and see if it works for you?

**Comment by cx0onl** [comment]
Yes. Now it works like a charm. :-)

Issue is closed.
