### ISSUE TITLE
Error about server-side rendering when using :first-child pseudo class in createStyles

### ISSUE THREAD

**Issue by ahmed-0011** [mantinedev/mantine#4472]
### What package has an issue

@mantine/core

### Describe the bug

I'm using Mantine UI with Vite.js for a client-side rendered app, but I'm getting an error about server-side rendering when using :first-child pseudo class in createStyles.

"The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".

### What version of @mantine/hooks page do you have in package.json?

6.0.15

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/damp-water-xvzg8w?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

-

**Comment by rtivital** [comment]
- It is not an error, it is a warning. You can sefely ignore it.
- The warning comes from emotion library. We cannot do anything about that on Mantine side.
- You can use `:fist-of-type` instead or ignore the warning.
