### ISSUE TITLE
Navbar hidden is not work

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4475]
### What package has an issue

@mantine/core

### Describe the bug

navbar is displayed even if hidden is true
```jsx
  console.log('hidden', !leftOpened)

 <Navbar
      width={{ sm: 250 }}
      hidden={!leftOpened}
      // style={{ height: 'calc(100vh - 56)' }}
      p="md"
      className={classes.navbar}
      {...props}
    >
```

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
As described in documentation `hidden` prop:
`hidden`– `boolean` – Set to true to hide component at hiddenBreakpoint

**Comment by vaynevayne** [comment]
i think hiddenBreakpoint It doesn't seem to be useful. The navbar is hidden on the xs screen,  but user need to show navbar so that navigate to some page,  the user has to be given an expanded button to switch, 

so it is still back to using hidden for control. Therefore, it is recommended to remove hiddenBreakpoint @rtivital
