### ISSUE TITLE
unknown bug  MediaQuery not work 

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4476]
### What package has an issue

@mantine/core

### Describe the bug

```jsx
 <MediaQuery smallerThan="sm" styles={{ display: 'none' }}>
            <div className="flex items-center">
              {topMenus.map((item, index) => (
                <NavLink
                  key={item.label}
                  active={item.label === collapse}
                  label={item.label}
                  icon={<item.icon size="1rem" stroke={1.5} />}
                  onClick={() => navigate(item.path)}
                  styles={{
                    root: {
                      width: 'unset',
                    },
                  }}
                />
              ))}
            </div>
          </MediaQuery>
```

<img width="519" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/688f38c2-b556-406a-ade2-ab30774d6d4b">

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

First, mediaQuery does not support multiple children,
then i wrapped as div, it works, 
 He stopped working after a while

**Comment by rtivital** [comment]
- MediaQuery supports only one child as described in the docs – https://mantine.dev/core/media-query/#mediaquery-children
- "He stopped working after a while" – I cannot help unless you explain the issue. Add a sandbox with minimal reproduction. If you do not do that in future your issues will be closed.
