### ISSUE TITLE
header zIndex should latgerThan navbar 

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4477]
### What package has an issue

@mantine/core

### Describe the bug

https://github.com/mantinedev/mantine/blob/master/src/mantine-styles/src/theme/utils/get-default-z-index/get-default-z-index.ts#L2C12-L2C12

Currently, the zIndex of both navbar and header is 100, but navbar renders after header, so the popover in navbar will be blocked by navbar.

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You can control z-index of Mantine components with `zIndex` prop.
