### ISSUE TITLE
when Navbar set hidden , should change --mantine-navbar-width

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4478]
### What package has an issue

@mantine/core

### Describe the bug

<img width="1305" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/2f7680bb-cc8d-4be1-a3e7-409b769f0ba7">

when <Navbar hidden> should set `--mantine-navbar-width = 0`

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is internal implementation.
