### ISSUE TITLE
Select is rendered under modal

### ISSUE THREAD

**Issue by ruessej** [mantinedev/mantine#448]
- What package has an issue: @mantine/core
- What package version are you using: v.3.2.1
- In which browser and operating system issue occurred: Edge@96.0.1054.29, Windows 10
- If possible please attach link to codesandbox with reproduced issue: https://codesandbox.io/s/practical-easley-juw68
- Do you have an idea how to fix the issue? zIndex???

![image](https://user-images.githubusercontent.com/85690286/142833424-c6f010c3-f2af-4bca-9d46-89855d036407.png)

**Comment by rtivital** [comment]
Thanks for reporting, we are working on this issue and will provide a fix in next patch

**Comment by rtivital** [comment]
To fix that issue now, you can set Modal zIndex to lower value:

```tsx
<Modal zIndex={10} />
```

**Comment by nghiepit** [comment]
@rtivital Why `zIndex` prop does not support on Select component?
I think zIndex of Select/MultiSelect component should be bigger zIndex of Modal/Popover by default.
And allow custom zIndex property on theme.

**Comment by rtivital** [comment]
I've released a patch 3.2.2, please update and see if it solves your issue
@nghiepit `zIndex` prop was added to Select, MultiSelect and Autocomplete components

**Comment by ruessej** [comment]
Thanks for the quick solve
