### ISSUE TITLE
Select Dropdown Defaulting to Bottom for Array Items with GUID Ids

### ISSUE THREAD

**Issue by tjmcdonough** [mantinedev/mantine#4480]
### What package has an issue

@mantine/core

### Describe the bug

# Description:

When using the Select component with an array of items where the id field is a GUID, the Select dropdown defaults to the bottom item of the array list.

# Steps to Reproduce:

1. Create a Select component in a Mantine application.
Populate the data prop of the Select component with an array of objects, each containing a label field (string) and a value field (GUID).
2. Open the Select dropdown in the application.
Expected Results:
3. When opening the Select dropdown, the first item in the array list should be selected or no item should be selected (if no default value has been set).

# Actual Results:
When opening the Select dropdown, the view defaults to the bottom item in the array list.

# Environment:

Mantine version: 6.0.15
React version: 18.0.2
Browser: Microsoft Edge
Additional Context:
Here is a code snippet which can reproduce the issue:

```
const postEndpoints = endpoints
    ?.filter((c) => c.methodType === "POST")
    .map((c) => ({ label: c.relativeUrl, value: c.id })) ?? [];

<Select
  label="Login Endpoint (POST)"
  description="The endpoint used to login to your API"
  placeholder="v1/login"
  data={postEndpoints}
  searchable
/>
```

### What version of @mantine/hooks page do you have in package.json?

6.0.15

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6
