### ISSUE TITLE
Toggle focused input state when Select dropdown is chosen

### ISSUE THREAD

**Issue by charliequin** [mantinedev/mantine#4482]
### What package has an issue

@mantine/core

### Describe the bug

By default the `<Select/>` component keeps your focus maintained when a user has selected an option from the dropdown. This specifically causes problems in iOS since it keeps your keyboard displayed even after an option has been chosen. 

I have tried to manually target the input element using a ref on `<Select/>`, and toggling the focus directly inside of an `onChange` event handler, but it doesn't seem to work.

```ts
  ...
  const ref = useRef<HTMLInputElement>(null);

  const handleChange = (value: string) => {
    onChange(value);

    if (ref) {
      ref.current?.focus();
    }
  };

  return (
    <Select
      ref={ref}
      onChange={handleChange}
      {...props}
    />
  )
  ```
  
From going through the Select component's documentation, it looks as though this behaviour is intended. Is there a solution that works around this and allows the behaviour I am describing?

### What version of @mantine/hooks page do you have in package.json?

5.8.3

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by mbibko** [comment]
@charliequin setTimeout and blur shoul help
```        
onChange={() => {
          setTimeout(function () {
            selectRef.current?.blur();
          }, 100);
}}
```

**Comment by charliequin** [comment]
> @charliequin setTimeout and blur should help
> 
> ```
> onChange={() => {
>           setTimeout(function () {
>             selectRef.current?.blur();
>           }, 100);
> }}
> ```

Thank you! This works perfectly.
