### ISSUE TITLE
I'm not able to import anything from @mantine/dates in my react app bundled with vite

### ISSUE THREAD

**Issue by aditya-kumarr** [mantinedev/mantine#4487]
### What package has an issue

@mantine/dates

### Describe the bug

I"m getting this error saying: 
`Uncaught SyntaxError: ambiguous indirect export: default`
which usually happens when I try to import something from an esmodule that doesn't have a default export

just this line of code is causing the error
![code](https://github.com/mantinedev/mantine/assets/95866943/426ac566-62f5-4b22-98d5-dc8993dffa05)

Is there any way to fix this ?

like is it a problem with @mantine/dates or just vite, because @mantine/core and other dependencies are working just fine and they have similar exports as well
![code](https://github.com/mantinedev/mantine/assets/95866943/eb881ff3-53df-4a87-b71f-a8ae9fa5239b)

### What version of @mantine/hooks page do you have in package.json?

^6.0.15

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
I cannot reproduce the issue with Vite, try updating/reinstalling dependencies
