### ISSUE TITLE
SpotlightProvider's target property does not work.

### ISSUE THREAD

**Issue by Handiwork** [mantinedev/mantine#4494]
### What package has an issue

@mantine/spotlight

### Describe the bug

SpotlightProvider's target property was passed to Spotlight, but Spotlight does not pass it to Modal.

https://github.com/mantinedev/mantine/blob/6beca530402db5719d7f1ee7950978ac5e0a8141/src/mantine-spotlight/src/Spotlight/Spotlight.tsx#L124

### What version of @mantine/hooks page do you have in package.json?

6.0.15

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/dawn-leftpad-l9jlln?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Pass it within `others`.

**Comment by rtivital** [comment]
Fixed in 6.0.17
