### ISSUE TITLE
Some components style got reloaded when Modal/Drawer opened or closed, Theme changed

### ISSUE THREAD

**Issue by un-hongly** [mantinedev/mantine#4498]
### What package has an issue

@mantine/core

### Describe the bug

I faced an issue which some of my components's style get reloaded when Modal/Drawer is open or close and it happen when I toggle theme also.

1. video.js component
2. Chat component

These two component has it own importing style in my .ts file. Ex. import 'video.js/dist/video-js.css';

See video here: https://www.loom.com/share/fbafaa8abce44baeabf0b89c9c433be4?sid=1df32ee1-e896-4092-9cb4-59da5f4c9952

### What version of @mantine/hooks page do you have in package.json?

6.0.15

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Seems like your video component reinitializes on each rerender, this is not related to styles. Make sure that you do not call third party handlers on each React state change. The issue is not related to Mantine.
