### ISSUE TITLE
Add variant and auto-suggest when used in component

### ISSUE THREAD

**Issue by nguyenbatranvan** [mantinedev/mantine#4503]
### What package has an issue

@mantine/core

### Describe the bug

- I added a new variant in my style like below: 

```
export const ButtonTheme = {
    defaultProps: {
        variant: 'custom'
    },
    variants: {
        custom: (theme) => ({
            root: {
                backgroundImage: theme.fn.linearGradient(
                    45,
                    theme.colors.cyan[theme.fn.primaryShade()],
                    theme.colors.teal[theme.fn.primaryShade()],
                    theme.colors.green[theme.fn.primaryShade()]
                ),
                color: theme.white,
            },
        })
    }
}

```

-  when using in component everything works fine
-  the problem here is variant doesn't suggest the string itself which i automatically added earlier. Instead, only the default variants of the library are suggested
- I tried adding override ButtonProps library like below:

```
declare module '@mantine/core' {
    export interface ButtonProps {
        variant?: Variants<'filled' | 'outline' | 'light' | 'white' | 'default' | 'subtle' | 'gradient' |'custom'>;
    }
}
```
**But unfortunately, a warning error occurred to me**
``` Subsequent property declarations must have the same type. Property 'variant' must be of type 'Variants<"filled" | "outline" | "light" | "white" | "default" | "subtle" | "gradient"> | undefined', but here has type 'Variants<"filled" | "outline" | "light" | "white" | "default" | "subtle" | "gradient" | "custom"> | undefined' ```

How do I add variants according to my style, and when I use it in a component, the variant will suggest the values that I have added?

### What version of @mantine/hooks page do you have in package.json?

6.0.15

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by chewhx** [comment]
You can create a new button using the mantine button as base component. Then declare your button props by extending from the props from mantine button. When you use your own custom button, it should have type suggestion.

**Comment by nguyenbatranvan** [comment]
> You can create a new button using the mantine button as base component. Then declare your button props by extending from the props from mantine button. When you use your own custom button, it should have type suggestion.

tks so much

**Comment by nguyenbatranvan** [comment]
> > You can create a new button using the mantine button as base component. Then declare your button props by extending from the props from mantine button. When you use your own custom button, it should have type suggestion.
> 
> tks so much

```
import styled from "@emotion/styled";
import {Button, ButtonProps, createPolymorphicComponent} from "@mantine/core";
import {FC} from "react";
import {Variants} from "@mantine/styles";
interface IProps extends Omit<ButtonProps, 'variant'> {
    variant?: Variants<'filled' | 'outline' | 'light' | 'white' | 'default' | 'subtle' | 'gradient' | 'custom'>;
}

const _ButtonStyled = styled(Button)``;
const StyledButton = createPolymorphicComponent<'button', IProps>(_ButtonStyled);


export const CustomButton: FC<IProps> = (props) => {
    return <StyledButton {...props}>
    </StyledButton>
}

```
