### ISSUE TITLE
Provide access to Quill instance object when using the RichTextEditor component.

### ISSUE THREAD

**Issue by brochington** [mantinedev/mantine#451]
Since the `RichTextEditor` component is build on top of the Quill library, it would be nice to offer a means of accessing the underlying Quill instance object so that the editor may be used imperatively, extended, etc.

**Comment by rtivital** [comment]
Thanks for proposal, we will add this feature in one of the 3.x releases

**Comment by rtivital** [comment]
Released in 3.3, documentation on how to get quill ref — https://mantine.dev/others/rte/#get-editor-ref
