### ISSUE TITLE
RTL issues on switch inner labels

### ISSUE THREAD

**Issue by CripyIce** [mantinedev/mantine#4515]
### What package has an issue

@mantine/core

### Describe the bug

Using inner labels on `Switch` with RTL has UI bugs.
Code:
```html
<Switch size="xl" onLabel="טופל" offLabel="לא טופל" />
```
![Screenshot 2023-07-07 at 16 13 07](https://github.com/mantinedev/mantine/assets/26387823/ce14fc07-07e7-491b-aafa-bd548d41dd81)
![image](https://github.com/mantinedev/mantine/assets/26387823/2871702f-e1e1-4450-ab0c-929bc201f688)
**Don't mind the button below - he works great**

It also seems like the width is changing, but perhaps it's normal due to the length of the text.

### What version of @mantine/hooks page do you have in package.json?

6.0.16

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in 6.0.17
