### ISSUE TITLE
 Encountered two children with the same key in the manitne select

### ISSUE THREAD

**Issue by Danztee** [mantinedev/mantine#4523]
### What package has an issue

@mantine/core

### Describe the bug

            <Select
              searchable
              required
              label="Select Address:"
              placeholder="Select one of your saved addresses"
              data={savedAddress.map((address) => address.addressName)}
              onChange={(e) => {
                setAddressName(e!);
              }}
              value={addressName}
              nothingFound="no address found"
              error={error && type === "saved_address" && !addressName}
            />
            
I thinks mantine uses the data i map to the data prop as the key of the SELECT component behind the scenes... so now that i have some values that has same name, i get that  `Encountered two children with the same key`.

-----
part of the select component code
    const selected = typeof isItemSelected === "function" ? isItemSelected(item.value) : false;
    return /* @__PURE__ */react__WEBPACK_IMPORTED_MODULE_0___default().createElement(Item, __spreadValues({
      key: item.value,
-----

the key is the item value and i have some value to be of the same name.

How can i fix it?
Is there a way to pass an index value to the data prop? so i can fix this error... if i have over ten thousands of data, it will cause  a serious error... i'm having a little bit a thousand of data and i'm experiencing some lagging in my application.

### What version of @mantine/hooks page do you have in package.json?

6.0.16

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

we should be able to pass an index value to be used as the key or mantine should use the index as the key instead of the  item.value

**Comment by rtivital** [comment]
Select values must be unique, for example `<Select data={['1', '1']} />` and `<Select data={[{ value: '1', label: '1' }, { value: '1', label: '2' }]} />` will show this warning.

**Comment by Danztee** [comment]
So, if my values are not unique, I can use the select component?? Why don't mantine use the index as key? Why value?

**Comment by rtivital** [comment]
Index keys do not work correctly when items are reordered/removed/added/updated.
