### ISSUE TITLE
allowDeselect is ignored when clearable is enabled

### ISSUE THREAD

**Issue by DanielGibbsNZ** [mantinedev/mantine#4524]
### What package has an issue

@mantine/dates

### Describe the bug

When using a `DateInput` with the `clearable` prop set, the value of the `allowDeselect` prop is ignored.

While I can see why this may be intended behaviour, it would be nicer for the user to be able to control deselection using the `allowDeselect` prop even when `clearable` is set.

My use case is this:

* When typing a date in the date field, some users click the date in the date picker to confirm the date however this then deselects the date, which isn't a very nice UX
* The `clearable` prop already enables the ability to clear the date field by clicking the clear button or by deleting all the text from the text field, so being able to deselect by clicking a date isn't really necessary

My proposed solution doesn't change the default behaviour when `allowDeselect` is not explicitly given, but it does allow `allowDeselect` to have an effect when `clearable` is set. Is this acceptable?

### What version of @mantine/hooks page do you have in package.json?

6.0.16

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

The simplest fix would be to change:
```
const _allowDeselect = clearable || allowDeselect;
```
to something like
```
const _allowDeselect = allowDeselect !== undefined ? allowDeselect : clearable;
```

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
