### ISSUE TITLE
Richt Text Editor LinkControl Popover wrongly positioned in Safari

### ISSUE THREAD

**Issue by Cuzart** [mantinedev/mantine#4529]
### What package has an issue

@mantine/tiptap

### Describe the bug

LinkControl Popover is misplaced in Safari. 

To reproduce select some text in the Editor from the codesandbox and click on the link control. See how the PopoverDropdown is positioned at the left top corner with (top: -44; left: 0).

This only appears on Safari (also tested in Chrome, Brave, Edge and Firefox)

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/admiring-pare-44fydg?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
No longer reproducible in the latest Safari 

https://github.com/mantinedev/mantine/assets/10353856/e6058a7a-9d0e-4bad-ae8d-e146de6f8821
