### ISSUE TITLE
[TextInput]: event.currentTarget is null

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4533]
### What package has an issue

@mantine/core

### Describe the bug

<img width="744" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/2f21f462-e190-43b6-8303-0478524e0bd0">

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please provide a sandbox with minimal reproduction.

**Comment by vaynevayne** [comment]
Native onChange events are bound to event.target.value,

Why is mantine a currenttarget? Is this a custom property? @rtivital

**Comment by vaynevayne** [comment]
![image](https://github.com/mantinedev/mantine/assets/124666577/5e051fba-ede5-4436-8948-36c826229a70)

```jsx
 <TextInput
              value={form.name}
              onChange={(e) => {
                const value = e.currentTarget.value // here 
                setForm((prev) => ({
                  ...prev,
                  name: value,
                }))
              }}
            />
```
Wondering why we use eventTarget instead of target?

**Comment by vaynevayne** [comment]
<img width="852" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/820031b0-6e17-4e2d-93f2-d94ad52ba4c8">

for mantine-ui , Does we must get Value from currentTarget ?
