### ISSUE TITLE
Select not open on button click 

### ISSUE THREAD

**Issue by mbibko** [mantinedev/mantine#4534]
This example not working on latest mantine version. 

https://codesandbox.io/s/eager-hoover-b2vd9o?file=/src/App.tsx

_Originally posted by @rtivital in https://github.com/mantinedev/mantine/discussions/2949#discussioncomment-4127261_

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
