### ISSUE TITLE
borderBottomRightRadius has been replaced with borderBottomRightRadius in drawer

### ISSUE THREAD

**Issue by aliasadolahi74** [mantinedev/mantine#4535]
### What package has an issue

@mantine/core

### Describe the bug

Hi. When I use borderBottomRightRadius for styling the content of the Drawer, it applies to the bottom left radius. it might have been like this because I'm using the RTL feature

### What version of @mantine/hooks page do you have in package.json?

6.0.15

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

styles has been replaced and it should resolve by putting the correct prop in the right place.

**Comment by rtivital** [comment]
This is the default behavior of stylis-plugin-rtl – https://www.npmjs.com/package/stylis-plugin-rtl
If you do not like this behavior, do not use it. Note that in this case, Mantine components styles may be incorrect, and you will need to override them for RTL. It is not planned to change this behavior as it is outside of the library scope.

**Comment by aliasadolahi74** [comment]
RTL should not change the fact that the right is right and the left is left. it's like going to the middle east street and while driving instead of turning right you turn left.
