### ISSUE TITLE
when will use next 13 app directory ?

### ISSUE THREAD

**Issue by zgame555** [mantinedev/mantine#4536]
### What package has an issue

@mantine/core

### Describe the bug

when will use next 13 app directory ?

### What version of @mantine/hooks page do you have in package.json?

when will use next 13 app directory ?

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
See https://github.com/mantinedev/mantine/issues/2815
