### ISSUE TITLE
<Select /> valueComponent

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#4537]
### What package has an issue

@mantine/core

### Describe the bug

Can we get a valueComponent for Select (https://mantine.dev/core/select)?

![Screenshot 2023-07-16 at 00 32 31](https://github.com/mantinedev/mantine/assets/22228431/170f7069-303e-4af9-ad7c-8abc8da50563)

It already has itemComponent so why not valueComponent?

It'd help us preview a badge after selecting:

![Screenshot 2023-07-16 at 00 34 05](https://github.com/mantinedev/mantine/assets/22228431/a11f59fd-c260-4944-a48d-56daaf03f763)

### What version of @mantine/hooks page do you have in package.json?

^6.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please use GitHub issues to report bugs. To ask questions and request features, use GitHub discussions. To answer your question – it is implemented in v7 – https://v7.mantine.dev/combobox?e=SelectOptionComponent
