### ISSUE TITLE
Slider with decimal steps broken

### ISSUE THREAD

**Issue by JohannesIBK** [mantinedev/mantine#4538]
### What package has an issue

@mantine/core

### Describe the bug

Using a decimal value like 0.1 will instead use 1. 

### What version of @mantine/hooks page do you have in package.json?

^6.0.16

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/slider/#min-max-and-step

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

It seems like it broke in 6.0.15, maybe commit 149fbd912a63e604aea2fd11894bfdcd0086bbc5

**Comment by rtivital** [comment]
Fixed in 6.0.17
