### ISSUE TITLE
Select should remember the selected item index and start from there

### ISSUE THREAD

**Issue by porkopek** [mantinedev/mantine#454]
- What package has an issue (@mantine/core, mantine/hooks or other)?
**core**
- What package version are you using?
**3.2.2**

The select should keep the state of the index of the selected item once closed.
At this moment, if you select an item, let's say the 4th of a list of 6, you close the select and you open again, the selected item is the 1st of the list.
It's true that the selected item remains with the visuals of selected, but if you press key down or key up, the cursor moves from the first item of the list.

Example:
![select](https://user-images.githubusercontent.com/13745954/143136245-166c77d8-87f2-4df9-b7f5-7a01e97af165.gif)

The right behavior would be:

![select2](https://user-images.githubusercontent.com/13745954/143137001-f53885c7-fdb3-4743-8743-30ea937a1c4c.gif)

Please, note how after opening the select again, it remembers the position where the cursor was

**Comment by rtivital** [comment]
Thanks for reporting! Your assumption is incorrect, though – native select does not remember where the mouse was – it highlights the selected item. I think we can work on this to bring the same behavior.

**Comment by porkopek** [comment]
I'm referring to keyboard, not mouse. Native select remembers which element is selected and when you open the select again and  you do key down or key up, the cursor moves from the selected item, not from the start.
In Mantine's case, the gray background that represents the cursor and the blue background that represents the selected item have to be in the same index when you open the select again after selecting something.

See this as an example https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by rtivital** [comment]
Released in 3.3
