### ISSUE TITLE
Select can't open 

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4544]
### What package has an issue

@mantine/core

### Describe the bug

<img width="1415" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/e366bdc8-425e-4f4a-9bce-0fbff2f682a3">

```jsx
 <Grid.Col lg={12}>
          <Select
            label="游戏选择"
            placeholder="游戏选择"
            data={[
              { label: 'aa', value: 'aa' },
              { label: 'bb', value: 'bb' },
            ]}
            // data={gameList}
            value={form.game_id}
            onChange={(value) => {
              updateForm((draft) => {
                draft.game_id = value
              })
            }}
          />
        </Grid.Col>
```

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction
