### ISSUE TITLE
Modal is closed when you click on the body

### ISSUE THREAD

**Issue by ruessej** [mantinedev/mantine#455]
- What package has an issue? @mantine/core
- What package version are you using? v3.2.2
- In which browser and operating system issue occurred? Edge@96.0.1054.29, Windows 10
- If possible please attach link to codesandbox with reproduced issue: https://codesandbox.io/s/mystifying-pasteur-h8iqq

**Comment by rtivital** [comment]
It is a normal modal behavior, if you want to disable modal closing with outside clicks set `closeOnClickOutside={false}`, here is an example – https://codesandbox.io/s/happy-tree-hhuim

**Comment by ruessej** [comment]
But I want to close the modal when I click the Outside, and not when I click the body, for example the text.

**Comment by rtivital** [comment]
Can you please explain more? I do not understand the issue. Is it specific for Edge? Can you replicate that in Chrome?

https://user-images.githubusercontent.com/10353856/143203302-9cd507c6-440d-41db-b687-1b8197c30636.mov

**Comment by ruessej** [comment]
I have tested it on Brave and there is no problem there

**Comment by rtivital** [comment]
Okay, I'll check on Edge then

**Comment by rtivital** [comment]
Cannot replicate on Microsoft Edge | 95.0.1020.30 (Official build) (64-bit)

https://imgur.com/a/yekDY2p

**Comment by ruessej** [comment]
I think its a problem with my project or with my work pc.
But thanks for the try

**Comment by kierien** [comment]
Hi @rtivital, I'm facing the same issue. 

Here's a minimal reproducible example:
[https://codesandbox.io/s/funny-voice-kpfi6?file=/src/App.tsx](https://codesandbox.io/s/funny-voice-kpfi6?file=/src/App.tsx)

Upon inspection it seems like the click outside overlay lives inside the modal inner div, not sure if that's intentional?

**Comment by rtivital** [comment]
Thanks for reporting @kierien, we will fix clickoutside overlay position in next minor version, meanwhile you can fix this issue by setting z-index in styles api – https://codesandbox.io/s/quizzical-montalcini-md0es?file=/src/App.tsx

**Comment by rtivital** [comment]
This issue was resolved in 3.3.0, now click outside overlay has a fixed position, and it is not a part of modal body. Feel free to reopen or report if you are still have this behavior.
