### ISSUE TITLE
Styled custom components 

### ISSUE THREAD

**Issue by sridhar-uno** [mantinedev/mantine#4551]
### What package has an issue

@mantine/core

### Describe the bug

Trying to implement code from here: https://mantine.dev/styles/styled/

**Code:**

```
import { NavLink as RRNavLink } from '@remix-run/react';
import { NavLink } from '@mantine/core';
import { ReactNode } from 'react';
import styled from '@emotion/styled';

const StyledLink = styled(NavLink)`
  & .mantine-NavLink-root {
    background-color: ${({ theme }) => theme.colors.gray[0]},
    padding: '8.5px 8px',
    borderRadius: '32px',
    height: '26px',
    gap: '4px',
    &:hover: {
      color: ${({ theme }) => theme.colors.brand[7]},
    },
  }
`;

export default function Link({
  to,
  label,
  icon,
}: {
  to: string;
  label: string;
  icon?: ReactNode;
}) {
  return <StyledLink component={RRNavLink} to={to} label={label} />;
}
```

**Result:** 
The styles are not getting applied.
Also there is TS error saying
`Property 'component' does not exist on type 'IntrinsicAttributes & { theme?: Theme | undefined; }'`

### What version of @mantine/hooks page do you have in package.json?

6.0.16

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/sandbox/cool-frost-93pxff

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
> The styles are not getting applied.

Change selector to `&.mantine-NavLink-root`, `& .mantine-NavLink-root` is not correct.

> Also there is TS error saying

https://mantine.dev/styles/styled/#polymorphic-components

**Comment by sridhar-uno** [comment]
See this sandbox, that change doesnt work

https://codesandbox.io/p/sandbox/cool-frost-93pxff?file=%2Fapp%2Fcomponents%2FLink.tsx%3A7%2C27

**Comment by rtivital** [comment]
Your sandbox does not include `createPolymorphicComponent` function, it is required for types to work correctly.
