### ISSUE TITLE
Size of icons inside ThemeIcon

### ISSUE THREAD

**Issue by peacepostman** [mantinedev/mantine#4562]
### What package has an issue

@mantine/core

### Describe the bug

Hello,

It is confusing that ThemeIcon is using hardcoded sizes instead of inheriting the ones configurated on a theme.

Best regards,

### What version of @mantine/hooks page do you have in package.json?

6.0.16

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

It would be good to specify this in the doc or allow theme heritage.

**Comment by ItaiAxelrad** [comment]
Same as issue #4576. This has been resolved with recently merged PR #4600

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
