### ISSUE TITLE
InputPassword exposes passwords in console because of `autocomplete`

### ISSUE THREAD

**Issue by j-pendlebury** [mantinedev/mantine#4564]
### What package has an issue

@mantine/core

### Describe the bug

When using `InputPassword` on Chrome, the password field with value gets exposed because of a Chrome "feature": https://www.chromium.org/developers/design-documents/create-amazing-password-forms.

Adding `autocomplete` prop to component solves the issue but this should probably be listed as a required prop in docs.

![Screenshot 2023-07-25 at 11 07 22](https://github.com/mantinedev/mantine/assets/13763899/26ed4755-e741-46a9-b862-12eb824969f0)

### What version of @mantine/hooks page do you have in package.json?

^6.0.14

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Add `autocomplete: 'on'` or `autocomplete: 'off'` to `InputPassword` component + include in docs.

**Comment by rtivital** [comment]
Fixed in 6.0.20
