### ISSUE TITLE
[@mantine/core] RadioGroup not compatible with React Hook Form

### ISSUE THREAD

**Issue by LucasLemanowicz** [mantinedev/mantine#457]
Mantine's RadioGroup (and likely other form elements) are not compatible with React Hook Form, a popular forms library.

Repro is here, where I try to register the RadioGroup input with the form: https://codesandbox.io/s/frosty-vaughan-0j0xb

Specifically it seems like the `onChange` parameter has a different type in Mantine and react-hook-form:
```
Type '{ children: Element[]; onChange: ChangeHandler; onBlur: ChangeHandler; ref: RefCallBack; name: string; }' is not assignable to type 'RadioGroupProps'.
  Types of property 'onChange' are incompatible.
    Type 'ChangeHandler' is not assignable to type '(value: string) => void'.
      Types of parameters 'event' and 'value' are incompatible.
        Type 'string' is not assignable to type '{ target: any; type?: any; }'.ts(2322)
```

Package versions:
```
  "dependencies": {
    "@mantine/core": "3.2.2",
    "@mantine/hooks": "3.2.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-hook-form": "7.20.2",
    "react-scripts": "4.0.3"
  },
```

**Comment by LucasLemanowicz** [comment]
Seems to be this override: https://github.com/mantinedev/mantine/blob/55fcf58/src/mantine-core/src/components/RadioGroup/RadioGroup.tsx#L86-L87

**Comment by rtivital** [comment]
Unfortunately, we cannot support all existing form libraries APIs. You can use https://react-hook-form.com/api/useform/setvalue to set field value manually to set value in `onChange` handler.

**Comment by iDavidB** [comment]
If you have a choice in form library I'd recommend using [React Final Form](https://github.com/final-form/react-final-form). This being one of the reasons why you probably should. It's a React abstraction over the regular Final Form JS library, which makes problems like these easier to tackle. `register` in React Hook Form for example tends to have a lot of issues with custom components due to what it expects and constantly requires you to add in dirty fixes to make it work.

**Comment by getTobiasNielsen** [comment]
https://codesandbox.io/s/frosty-mahavira-jexit?file=/src/App.tsx

**Comment by LucasLemanowicz** [comment]
Thanks for the help over Discord, @getTobiasNielsen 

I'll use this controller method for now, and look into getting a PR in at RHF to use the `getControllerValue` helper in register's onChange implementation in the next week or two.
