### ISSUE TITLE
Pagination: clicking Link buttons still change the URL when they are disabled

### ISSUE THREAD

**Issue by HoHieuLuc** [mantinedev/mantine#4574]
### What package has an issue

@mantine/core

### Describe the bug

When using Pagination with links, clicking the previous, first, next and last button still change the URL when they are disabled because disabled attribute doesn't work on anchor element.

### What version of @mantine/hooks page do you have in package.json?

6.0.17

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/pagination/#controls-as-links

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by saadsiddiqui07** [comment]
Could you please provide a code example of your issue?

**Comment by HoHieuLuc** [comment]
> Could you please provide a code example of your issue?

Go to https://mantine.dev/core/pagination/#controls-as-links and try clicking on previous or first button

**Comment by ItaiAxelrad** [comment]
The Pagination element is missing `pointerEvents: 'none'` in its disabled style. I'd be more than happy to submit a PR

**Comment by verheyenkoen** [comment]
@ItaiAxelrad Any specific reason you chose to add this fix to the `[data-disabled]` rule and not `:disabled` pseudo-class or `[disabled]` rule? Anyhow I don't see this working in Mantine 7 (with Next.js Link as the component and the `disabled` prop set: `<Button as={Link} href="url" disabled={true}>Link text</Button>`). Or is that another issue and is this one pagination specific?

**Comment by ItaiAxelrad** [comment]
@verheyenkoen I was following the package convention [https://mantine.dev/styles/data-attributes/](https://mantine.dev/styles/data-attributes/). This was a pagination-specific issue but I'm happy to check it out if you open a new issue for it
