### ISSUE TITLE
Nextjs Guide with Mantine page is Stale (Not upto date)

### ISSUE THREAD

**Issue by CodeMode365** [mantinedev/mantine#4586]
### Link to the page where something nasty is located

https://mantine.dev/guides/next/

### Exact quote of what is wrong

What page has an issue
guides/next

Describe the bug
Hello,

It's been more than a few months since the Nextjs team stabilized the /app dir, but the mantine guide still has the documentation for an older version using _pages.tsx and _document.tsx which doesn't work in the same way in version ^13.4.x

Best regards,

What version of page do you have in package.json?
6.0.17

If possible, please include a link to a codesandbox with the reproduced problem
No response

Do you know how to fix the issue
Update the code of: /docs/src/docs/guides/next.mdx

Are you willing to participate in fixing this issue and create a pull request with the fix
Yes

Possible fix
It would be good to specify this in the doc or update the guide page.

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment]
See https://github.com/mantinedev/mantine/issues/2815
