### ISSUE TITLE
Missing fontStyles function in build file

### ISSUE THREAD

**Issue by sreepati** [mantinedev/mantine#4588]
### What package has an issue

@mantine/core

### Describe the bug

I'm using parcel for building. Local run works fine sometimes, but build fails always. I get the below error and nothing works. The fontstyles functions seems to be missing. This issue comes up on local run also sometimes but with multiple restarts seems to work properly. I was using 5.10.2. Upgraded to 5.10.5, then upgraded to 6.0.17. The issues seems to persist. Might be parcel issue as parcel seems to be polyfilling process each time I upgrade the version. Adding that also, might be of some concern with some conflicts.

![image](https://github.com/mantinedev/mantine/assets/6230135/d1eeb37d-4f14-4c0d-91d0-f86ec6d7228b)
![image](https://github.com/mantinedev/mantine/assets/6230135/a5c316da-1d2f-4c5f-823d-f867afdc4ec5)

### What version of @mantine/hooks page do you have in package.json?

6.0.17

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by sreepati** [comment]
ok seems to be issue with parcel. when built with parcel 2.8.3 works fine. Breaks with latest parcel. with latest parcel need to use `--no-scope-hoist` to build properly. might have to check why fails with normal parcel build.

**Comment by rtivital** [comment]
This is issue of Parcel, not Mantine. Try updating Parcel to the latest version, if that does not help, please report the issue in Parcel repository.
