### ISSUE TITLE
[Popover/Popper] How to avoid click outside when select item of Select/MultiSelect?

### ISSUE THREAD

**Issue by nghiepit** [mantinedev/mantine#459]
Since version 3.2.2 Autocomplete, Select, and MultiSelect dropdowns are now rendered within Popper.
When selecting the select item the Popover auto close.
To temporarily solve the issue set `noClickOutSide: true`, But that's not a long-term solution.

Related https://github.com/mantinedev/mantine/issues/458

Please provide following information:
- What package has an issue (@mantine/core, mantine/hooks or other)? **3.2.2**
- What package version are you using?: **Yarn**
- In which browser and operating system issue occurred?: **Chrome and macOS**
- If possible please attach link to codesandbox with reproduced issue
https://codesandbox.io/s/great-mestorf-hsvg7?file=/src/App.tsx

**Comment by rtivital** [comment]
We already solved this by rendering dropdowns without portal by default, it should be out with 3.3

**Comment by rtivital** [comment]
Released in 3.3, here is documentation on how to use components with Popper in Popover – https://mantine.dev/core/popover/#usage-with-other-overlays

**Comment by nghiepit** [comment]
Hey @rtivital 
What do you think if `withinPortal` prop is false by default? To avoid many break changes.

I'm not sure, But, Why the position is `relative` instead of `fixed`?
https://github.com/mantinedev/mantine/blob/8d94c190446c85b4e598906ab379de1c2c912fd0/src/mantine-core/src/components/Popper/PopperContainer/PopperContainer.tsx#L34

**Comment by rtivital** [comment]
I've considered setting `withinPortal` to false by default, but in this case, we will have inconsistent behavior across different components, so no, we will use portal by default in all components, and you can disable that with a prop. Anyway, you would want to use portal in most of the cases. 

It is set to relative position just to configure z-index, Popper handles position styles internally, it's not related to PopperContainer component.
