### ISSUE TITLE
Mantine Modals - Empty space in modal after fetch

### ISSUE THREAD

**Issue by SimponGoril** [mantinedev/mantine#4590]
### What package has an issue

@mantine/core

### Describe the bug

![image](https://github.com/mantinedev/mantine/assets/70171397/752406a3-ba33-4230-969b-6bc56e850ce6)

Weird behavior in Safari. When I open modal that fires a fetch/resolves a fetch request, I can see a weird empty space in the middle of the element. See screenshot for more info and check [this code](https://codesandbox.io/s/inspiring-aj-hdyqtx?file=/src/App.js) to reproduce the issue (Safari only)

### What version of @mantine/hooks page do you have in package.json?

6.0.17

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/inspiring-aj-hdyqtx?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

So far, the only workaround is to set an empty element when the modal is loading, that pre-fill space for content. Also - consecutive re-render of component will make this gap disappear

**Comment by rtivital** [comment]
I doubt that there is much we can do about it

![Group 1](https://github.com/mantinedev/mantine/assets/10353856/30739365-3537-4ae9-9a32-0a9615429386)

**Comment by SimponGoril** [comment]
At least its documented... I dont have my hopes up about it, but someone familiar with Webkit might come with some inexpensive fix

**Comment by elvezpablo** [comment]
We are seeing this as well with Safari 16.5.1 and Mantine 6.0.6. Will follow up with a work around if we find a reasonable one.

**Comment by SimponGoril** [comment]
Wow @elvezpablo, we can use this - thanks a lot!

```
 <MantineProvider withCSSVariables withGlobalStyles withNormalizeCSS theme={{
        colorScheme: "light", components: {
          Modal: {
            styles: {
              // Fix empty space bug in Safari
              content: { boxShadow: 'none' }
            }
          }
        }
      }} >
      ...
</MantineProvider>
```

**Comment by rtivital** [comment]
The issue is with Safari, we cannot do anything on our side
