### ISSUE TITLE
Documentation offers components that can't be imported.

### ISSUE THREAD

**Issue by lostfutures** [mantinedev/mantine#4599]
### What package has an issue

@mantine/core

### Describe the bug

![CleanShot 2023-08-01 at 20 11 41@2x](https://github.com/mantinedev/mantine/assets/82697673/1a5652a9-d019-4631-9db2-38ea56f59eb4)

For example, look at the screenshot, it claims that the version 7.0.0-alpha.20 offers a component called PinInput and it even shows how to import it, yet copying this exact import code throws an error claiming the component to be not existing.

### What version of @mantine/hooks page do you have in package.json?

7.0.0-alpha.20

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Was it just forgotten to be exported?

**Comment by ItaiAxelrad** [comment]
Many of the components have not been merged into mantine 7 yet. It's still in alpha

**Comment by blueagler** [comment]
It should be fixed in the next version. https://github.com/mantinedev/mantine-v7/pull/30
