### ISSUE TITLE
[bigbug]form.setValues() Will merge with initial

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4603]
### What package has an issue

@mantine/core

### Describe the bug

```jsx
const row = 
{
    "id": 25,
    "channel_data": []
}
 const form = useForm({
    initialValues:{
        need_server_data: true,
        need_organic_data: true,
    },
  })

form.setValues(row)

// form.values
{
 "id": 25,
    "channel_data": [],
    need_server_data: true,
    need_organic_data: true,
}

```

My data has been changed, 

### What version of @mantine/hooks page do you have in package.json?

all

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by ItaiAxelrad** [comment]
This is the expected behaviour. Per the docs [https://mantine.dev/form/values/#setvalues-partial](https://mantine.dev/form/values/#setvalues-partial) `setValues` is shallow merged with the current state (in your case, the initial values).

**Comment by vaynevayne** [comment]
> This is the expected behaviour. Per the docs https://mantine.dev/form/values/#setvalues-partial `setValues` is shallow merged with the current state (in your case, the initial values).

ok,  Is there any way to empty it?

**Comment by ItaiAxelrad** [comment]
There isn't a documented method for deleting `initialValues` but you could pass a function into `setValues` to do so

```js
form.setValues((prev) => {
   delete prev.need_organic_data;
   delete prev.need_server_data;
   return { ...prev, ...row };
})
```

Wondering if there is any chance the `initialValues` (need_server_data, and  need_organic_data) could be stored outside of the forms hook  instead? Might be cleaner
