### ISSUE TITLE
Module '"@mantine/core"' has no exported member 'Stepper'.

### ISSUE THREAD

**Issue by Freshu23** [mantinedev/mantine#4604]
### What package has an issue

@mantine/core

### Describe the bug

In mantine v7 alpha version I am getting the following error:
`Module '"@mantine/core"' has no exported member 'Stepper'.ts(2305)`
also https://v7.mantine.dev/core/stepper page returns 404

### What version of @mantine/hooks page do you have in package.json?

7.0.0-alpha.11

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by ShaikRehan123** [comment]
I'm pretty much sure Stepper component hast not been migrated to v7 yet.

**Comment by ShaikRehan123** [comment]
@Freshu23 It's available now, you can close this issue.

https://v7.mantine.dev/core/stepper
