### ISSUE TITLE
Tooltip for toggle direction button in header

### ISSUE THREAD

**Issue by pnkll** [mantinedev/mantine#4605]
### Link to the page where something nasty is located

https://mantine.dev/

### Exact quote of what is wrong

Tooltip remains active if you switch the direction even though we are no longer focusing on the button
![image](https://github.com/mantinedev/mantine/assets/93367917/d7acc54a-695a-4836-a783-f1cd771e906e)

### Are you willing to create pull request with the fix?

None

**Comment by rtivital** [comment]
Duplicate of #4772
Other issue contains more info
