### ISSUE TITLE
Doesn't allow add images

### ISSUE THREAD

**Issue by goseivietnam** [mantinedev/mantine#4608]
### What package has an issue

@mantine/tiptap

### Describe the bug

a WYSIWYG should allow users to upload images

### What version of @mantine/hooks page do you have in package.json?

6.0.14

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
1. Please use GitHub issues to report bugs, to request new features, use GitHub discussions.
2. You can use any tiptap extensions with `@mantine/tiptap` package, including image – https://tiptap.dev/api/nodes/image
