### ISSUE TITLE
PinInput doesn't allow paste from Gboard paste button

### ISSUE THREAD

**Issue by boredland** [mantinedev/mantine#4609]
### What package has an issue

@mantine/core

### Describe the bug

When pasting from the Gboard Paste button on Android (I heard 🍎 has sth similar), only the last character seems to be inserted, using the demo field from the docs.

https://github.com/mantinedev/mantine/assets/4662748/01f9064e-99a6-44de-a97f-2b43bf32865e

Behaves identically for chrome and Firefox mobile.
Using regular paste, everything works as intended.

### What version of @mantine/hooks page do you have in package.json?

Latest

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by saeidalidadi** [comment]
I am interested in fixing this issue

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix

**Comment by rtivital** [comment]
Fixed in 6.0.20
