### ISSUE TITLE
[MantineProvider] (v3.2.2) theme prop's `other` field typescript typing issue

### ISSUE THREAD

**Issue by lydianlights** [mantinedev/mantine#461]
Hello, I've been using Mantine in a typescript-based React app and I'm having some issues with the typing of the MantineProvider theme prop -- specifically the `other` field.

I have something like the following:
```
function App() {
  return (
    <MantineProvider theme={{
      colorScheme: 'light',
      primaryColor: 'blue',
      other: {
        headerHeight: '70px',
        drawerOpenWidth: '600px',
        drawerClosedWidth: '40px',
      },
    }}>
      <Main />
    </MantineProvider>
  );
}
```

But I get an error on headerHeight that `Type 'string' is not assignable to type 'DeepPartial<any> | undefined'`. However I can currently work around this problem by just defining my theme as an `any` type and passing it to the provider anyway, and everything seems to work. As far as I understand, `other` is supposed to be an object with whatever data you want, so I think this is a bug with the typings.

**Comment by rtivital** [comment]
Thanks for reporting, I've released a patch 3.2.3 with a fix for this issue, can you please update and see if that works for you?

**Comment by lydianlights** [comment]
Yep! I've downloaded the patched version and the bug is gone. Thank you!

**Comment by rtivital** [comment]
Thanks, feel free to report any other issues
