### ISSUE TITLE
Version 6.0.17 source map invalid

### ISSUE THREAD

**Issue by mcurros2** [mantinedev/mantine#4611]
### What package has an issue

@mantine/core

### Describe the bug

I am trying to debug a mantine component and found that the source maps doesn't match the source code. 

### What version of @mantine/hooks page do you have in package.json?

6.0.17

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
I could not reproduce the issue – source maps work fine for me in 6.0.20.
