### ISSUE TITLE
DatePickerInput, DateTimePicker label click does not focus input

### ISSUE THREAD

**Issue by Plesin** [mantinedev/mantine#4616]
### What package has an issue

@mantine/dates

### Describe the bug

Clicking on the input label does not focus the input.

### What version of @mantine/hooks page do you have in package.json?

6.0.16

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/silly-elgamal-6hlm59?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I have not looked at the code, but should be an easy fix. The `<label for=""...` does not match the `<button id...`
If I have time in the following days, I'd like to create a PR.

**Comment by rtivital** [comment]
You are welcome to investigate the issue and send a PR with a fix

**Comment by Plesin** [comment]
Had a look and it seems the correct id is overwritten by accesibleProps.id from the [PopoverTarget](https://github.com/mantinedev/mantine/blob/cf0f85faec56615ea5fbd7813e83bac60dbaefb7/src/mantine-core/src/Popover/PopoverTarget/PopoverTarget.tsx#L45)

So in this case there are three elements involved which needs to be in sync, label, input, dropdown as opposed to a regular input, where there is only label and input.

I'm not sure how to fix it right now. If I have more time, I'll investigate more but the free time available is very limited on my side.
Btw, thanks for such great component library with accesibility, localisation support and more!

**Comment by rtivital** [comment]
Fixed in 6.0.20

**Comment by Plesin** [comment]
Awesome @rommelmamedov Thanks a lot for fixing this! 🚀
