### ISSUE TITLE
The Button cannot be customized with a custom color code.

### ISSUE THREAD

**Issue by A-afflatus** [mantinedev/mantine#4619]
### What package has an issue

@mantine/core

### Describe the bug

```tsx
<Button variant="outline" color={'#202123'} w={'80%'} leftIcon={<IconPlus size="1rem" />}>
     new chat
</Button>
```
The color code setting failed to take effect, and the result turned into the default color, as shown in the following picture.
<img width="224" alt="image" src="https://github.com/mantinedev/mantine/assets/130149563/58b456bd-ea8f-4296-8de1-e9c8ce631d5c">

### What version of @mantine/hooks page do you have in package.json?

6.0.16

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by mcurros2** [comment]
Hi, if you look at the docs, color is of type MantineColor, it means that it accept a color name defined in Mantine theme. Take a look in theming to change theme colors. It's a good thing to have theme colors and not spread hardcoded colors in your components ;)

Cheers!

**Comment by A-afflatus** [comment]
Thank you for the response, but the user may have some custom requirements.
