### ISSUE TITLE
Creatable multiselect navigation issues

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#4625]
### What package has an issue

@mantine/core

### Describe the bug

<img width="428" alt="image" src="https://github.com/mantinedev/mantine/assets/18473137/9c7a8d50-c072-46d5-a3f6-848d8a7239e8">

I add some attributes like k:v, then with arrow down I selected createLabel, then item is added.
After I added some items, I want to remove, for example the first one.
How to do this without mouse through keyboard?
I know that this component has only separate input for type the text for the new item, but we have not access to added items, I'm not even talking about being able to edit the specific, I'm talking about the focus on the delete button of the specific.

Has no one encountered this problem?
I use this component to simulate functionality of TagInput.

### What version of @mantine/hooks page do you have in package.json?

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You can use a custom value component – https://mantine.dev/core/multi-select/#custom-label-component
In this value component you can render any elements, including a button which can be used to remove the value.
To handle keyboard events, pass `onKeyDown` prop
