### ISSUE TITLE
Wrapping Select in Skeleton renders dropdown underneath elements

### ISSUE THREAD

**Issue by aMoniker** [mantinedev/mantine#4626]
### What package has an issue

@mantine/core

### Describe the bug

Wrapping a `<Select>` in a `<Skeleton>` will render the opened select list underneath another select that has been wrapped in a skeleton below it. It might also do this with other elements, but I haven't checked.

See the [codesandbox demo](https://codesandbox.io/s/affectionate-goldwasser-sh66zl?file=/src/App.tsx) where the first select renders underneath the second.

### What version of @mantine/hooks page do you have in package.json?

6.0.17

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/affectionate-goldwasser-sh66zl?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

My fix for now is simply not using Skeletons around Selects.

**Comment by rtivital** [comment]
https://codesandbox.io/s/keen-ritchie-j9zwrv?file=/src/App.tsx
