### ISSUE TITLE
RadioGroup doesn't work with an array of Radio elements

### ISSUE THREAD

**Issue by marcus-sa** [mantinedev/mantine#4627]
### What package has an issue

@mantine/core

### Describe the bug

RadioGroup + Radio doesn't work as expected.

```tsx
const items = [{ value: '1', label: '1' }, { value: '2', label: '2' }];

<RadioGroup>
  {items.map(item => <Radio key={item.value} {...item} />)}
</RadioGroup>
```

Nothing happens when you click any of the radio inputs.
It works fine when the elements aren't dynamically created.

### What version of @mantine/hooks page do you have in package.json?

?

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by ItaiAxelrad** [comment]
It's `Radio.Group` not `RadioGroup`. If that's not the issue you'll have to reproduce in a sandbox cause it works fine for me.

**Comment by ItaiAxelrad** [comment]
Oh, I see. The Radio component is an input type="radio" which takes a string value only. If you need an integer you'll have to parse the selected value outside the Radio component
