### ISSUE TITLE
[Feature Request] hook for non window element events (useElementEvent)

### ISSUE THREAD

**Issue by MiguelKorn** [mantinedev/mantine#463]
Discussed in discord and just as the title says. A hook for non window elements so you can handle them as easy as with the `use-window-event` hook

**Comment by rtivital** [comment]
Can you please provide a use case for this hook?

**Comment by MiguelKorn** [comment]
Well, we'll have to write `closeOnScroll` logic ourselves for the `Menu` component, since it only checks the window scroll event (IIRC this will possibly be removed). So when the menu component is in a scrollable container it won't work. This hook would not only add this scroll event just as easy as the `use-window-event` hook, but also abstracting code that's needed for eventlisteners

**Comment by rtivital** [comment]
And how it will differ from:

```tsx
<div onScroll={() => {}} />
```

**Comment by MiguelKorn** [comment]
In the above case you'll have to wrap the child with a `forwardRef` and need to make a ref for each child.
```typescript
const Child = forwardRef((props, ref) => {
  useImperativeHandle(ref, () => ({
    onScroll() {
      alert("parent scrolling");
    }
  }));

  return <p>child</p>;
});

const Parent = () => {
  const childRef = useRef();

  return (
    <div onScroll={() => childRef.current.onScroll()}>
      <Child ref={childRef} />
    </div>
  );
};
```
But what if the child is nested within multiple components? you cant keep forwarding the ref till you reach the child. With this hook you can pass the ref (directly or with a context) of the scroll container and let the child handle the event.
```typescript
const Child = (props) => {
  useElementEvent(props.containerRef, "scroll", () => alert("parent scrolling"))  

  return <p>child</p>;
});

const Parent = () => {
  const containerRef = useRef();

  return (
    <div ref={containerRef}>
      <Child containerRef={containerRef} />
    </div>
  );
};
```

**Comment by rtivital** [comment]
use-event-listener hook was added in 3.6.0
