### ISSUE TITLE
maxSelectedValues causing one extra value if defaultValue is equal to maxSelectedValues

### ISSUE THREAD

**Issue by prateekm03** [mantinedev/mantine#4633]
### What package has an issue

@mantine/core

### Describe the bug

When maxSelectedValues is equal to defaultValue provided, it is causing dropdown to open, and it is causing issue.
If defaultValue length is more than maxSelectedValues, then its not allowing but getting extra selection because of that.

### What version of @mantine/hooks page do you have in package.json?

5.10.5

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by azizChebbi** [comment]
@prateekm03 which component is causing this? can u please specify.

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
