### ISSUE TITLE
Full screen Modal with ScrollArea.Autosize has empty space at the bottom

### ISSUE THREAD

**Issue by omerfarukdogan** [mantinedev/mantine#4637]
### What package has an issue

@mantine/core

### Describe the bug

If a Modal is used with both `fullScreen={true}` and `scrollAreaComponent={ScrollArea.Autosize}`, an empty space appears at the bottom of the modal content.

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/focused-water-mz5k75?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by saeidalidadi** [comment]
I can work on this.

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix

**Comment by saeidalidadi** [comment]
If you pass `yOffset={0}` as your modal props the empty space will be gone.

```javascript
<Modal yOffset={0} fullScreen> </Modal>
```

**Comment by saeidalidadi** [comment]
Hi @rtivital , I need to make a decision on fixing this issue by adding a condition to remove the default `yOffset = 10` but it would be helpful if I could get your thoughts on `calc(100vh - x)`  which results in 90vh for this issue.

**Comment by rtivital** [comment]
It is better just to ignore `yOffset` value when `fullScreen` prop is set – no need to modify default props.

**Comment by saeidalidadi** [comment]
it seems that this issue has been resolved in version 7.

**Comment by rtivital** [comment]
Are you sure? There weren't any changes to the styles.

**Comment by saeidalidadi** [comment]
I have created a story use case inside the latest version and the bug does not exist.
```javascript
export function FullScreenAutosizeScrollarea() {
  return (
    <div style={{ padding: 40 }}>
      <Modal
        opened
        onClose={() => {}}
        title="Just a Modal"
        fullScreen
        scrollAreaComponent={ScrollArea.Autosize}
      >
        <Box h={2000} bg="red"></Box>
      </Modal>
    </div>
  );
}
```
![Screenshot 2023-09-23 235431](https://github.com/mantinedev/mantine/assets/2406828/ec863aea-d5f1-4ae1-a7d2-b5ba627f2340)

**Comment by rtivital** [comment]
Great, thanks for reporting
