### ISSUE TITLE
`Calendar`: `withNext`, `withPrevious`, `nextDisabled`, `previousDisabled` props are not working

### ISSUE THREAD

**Issue by Kangdyu** [mantinedev/mantine#4638]
### What package has an issue

@mantine/dates

### Describe the bug

`Calendar` component's `withNext`, `withPrevious`, `nextDisabled`, `previousDisabled` props are not working.

These props cause warning in console:
> React does not recognize the `withNext` prop on a DOM element

Furthermore, this issue appears to extend to other components that utilize the `Calendar` component, such as `DatePicker`.

### What version of @mantine/hooks page do you have in package.json?

6.0.18

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/charming-zeh-6nlggs?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Thanks for reporting, incorrect props are removed from the Calendar props type. The fix will be available in next patch.
