### ISSUE TITLE
Button with variant=filled is only visible on hover

### ISSUE THREAD

**Issue by kunal00000** [mantinedev/mantine#4639]
https://github.com/mantinedev/mantine/assets/92316166/4d26ec84-88b0-4237-9ff9-6cbfeb8b57de

**Comment by Native-dev-afk** [comment]
I have the same issue with react

**Comment by rtivital** [comment]
You have installed a third party library that overrides mantine styles. (Most likely tailwind). To fix that, remove global styles of that library. Documentation for tailwind – https://tailwindcss.com/docs/preflight#disabling-preflight
