### ISSUE TITLE
ButtonProps type is not optimized

### ISSUE THREAD

**Issue by GetWrecked99** [mantinedev/mantine#4646]
### What package has an issue

@mantine/core

### Describe the bug

hey, 
just wanted to let you guys know that the ButtonProps type does not fully support the Button component.

i just wrapped the Mantine Button inside a custom button component with  ButtonProps type. 
i do not have access to props like component and also html button attributes as props and etc ...

it is just because ButtonProps type declaration is part of Button component declaration . . .

### What version of @mantine/hooks page do you have in package.json?

6.0.18

**Comment by saeidalidadi** [comment]
please share the example code you were working on.

**Comment by GetWrecked99** [comment]
![Screenshot_1](https://github.com/mantinedev/mantine/assets/124883615/92ecb794-70f0-4413-bdae-d249ac9224ff)

**Comment by saeidalidadi** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/124883615/260215508-92ecb794-70f0-4413-bdae-d249ac9224ff.png)

As the `Button` is a polymorphic component you should wrap it like this:

```js
const CButton = createPolymorphicComponent<'button', ButtonProps>(CustomButton);

<CButton component="a" />
```

**Comment by GetWrecked99** [comment]
thank you mate <3
