### ISSUE TITLE
<Menu.Item disabled> Property 'disabled' does not exist on type 

### ISSUE THREAD

**Issue by nghiepit** [mantinedev/mantine#465]
- What package has an issue (@mantine/core, mantine/hooks or other)? **3.2.3**
- What package version are you using? **Yarn**

**Comment by rtivital** [comment]
We currently do not support disabled items in Menu, this feature will be added in future releases

**Comment by nghiepit** [comment]
@rtivital  But currently shows up as expected.
https://codesandbox.io/s/autumn-paper-8nd3q?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/4768095/143753190-5911ec5f-47b0-4632-928a-95c350ba4915.png)

**Comment by rtivital** [comment]
Yes, it shows as expected, but it's not officially supported — some mouse events are broken, I would not recommend using it

**Comment by rtivital** [comment]
I'll add this in 3.3 release

**Comment by rtivital** [comment]
Menu.Item can now have a disabled prop in 3.3
