### ISSUE TITLE
Notifications System props page doesn't load properly

### ISSUE THREAD

**Issue by mjfaga** [mantinedev/mantine#4654]
### Link to the page where something nasty is located

https://v7.mantine.dev/others/notifications?t=props

### Exact quote of what is wrong

```
Error loading component props data. If you see this message please let us know by [opening an issue on GitHub](https://github.com/mantinedev/mantine/issues/new?assignees=&labels=&template=docs_report.yml).
```

### Are you willing to create pull request with the fix?

No

**Comment by CodeMode365** [comment]
<img width="740" alt="image" src="https://github.com/mantinedev/mantine/assets/102400760/125e684d-0a79-4821-8fb0-a055615d3ae8">

**Comment by rtivital** [comment]
The issue is fixed, thanks for reporting
