### ISSUE TITLE
React `warning` about recognize prop `classNames` from `styles api`

### ISSUE THREAD

**Issue by pnkll** [mantinedev/mantine#4658]
### What package has an issue

@mantine/core

### Describe the bug

Error in the console if we use the `classNames` property from the styles api

![image](https://github.com/mantinedev/mantine/assets/93367917/b73e3141-61c3-4480-b26b-d4dfda8ce9b9)

### What version of @mantine/hooks page do you have in package.json?

6.0.17

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Please send a sandbox that reproduces the issue

**Comment by ronaldaraujo** [comment]
The same here. In my case, the error happens when using the [Input component](https://ui.mantine.dev/component/contained-inputs). My application runs NextJs.

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction.
