### ISSUE TITLE
NavLink (or some components) colors changed to full black after updating to 6.0.19

### ISSUE THREAD

**Issue by ray-1337** [mantinedev/mantine#4661]
### What package has an issue

@mantine/core

### Describe the bug

Hello!

I don't know what happened after updating to **6.0.19**, the NavLink color suddenly set to black as default.

I never had thoughts to change their styles, because they already looked great and I like to keep it default.

For now, I only encountered NavLink, I'm not sure about other components.

## 6.0.19
![image](https://github.com/mantinedev/mantine/assets/33544674/dbe10429-b1c0-4f0e-8c2d-7ba3ffb4f8ab)

## <=6.0.18
![image](https://github.com/mantinedev/mantine/assets/33544674/ec3dd8a1-29fc-4b84-ae77-652c3a7b1fea)

## Code
```ts
<NavLink
     active={modulePage === "commands"}
     disabled={!isHumanValidated}
     label="Bot commands list"
     icon={<IconAlignBoxBottomCenter strokeWidth={"1.5"} />}
     color="indigo" variant="filled"
     onClick={() => runFunction("commands")}
/>
```

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Downgrade to **<=6.0.18**, or edit the styles manually; but I'd rather keep it default.

**Comment by rtivital** [comment]
I cannot reproduce the issue on codesandbox – https://codesandbox.io/s/great-thunder-rzj26r?file=/src/App.tsx
You are welcome to reopen the issue if you can provide a reproduction
