### ISSUE TITLE
Next/Link styling issue in mantine AppShell specifically for firefox browser

### ISSUE THREAD

**Issue by Ashkumar7** [mantinedev/mantine#4669]
### What package has an issue

@mantine/core

### Describe the bug

when putting `Link`  inside Mantine `AppShell` navbar it create 2 issue :-

For Firefox :
1. it creates dotted borderline around the layout (attaching picture for that)
2. it retains anchor tag styling like `text-decoration: underline` and `color --> for active tab` (its in picture also)

In ChromeBased Browsers:
1. it dont create dotted borderline
2. but retains achor tag styling

![image](https://github.com/mantinedev/mantine/assets/58642607/1277423f-dd45-4e47-b6bd-eeafefe87c84)

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by apoco** [comment]
I don't know if it's the exact same things, but I also see broken styles after upgrading.

![Before](https://github.com/mantinedev/mantine/assets/551316/233c578b-488f-4d54-936c-d5a087b2449a)
![After](https://github.com/mantinedev/mantine/assets/551316/296dc129-acb8-4347-b3ff-0c9619c56a3c)

**Comment by rtivital** [comment]
I cannot reproduce the issue with Mantine 7 in Firefox
