### ISSUE TITLE
useColorScheme hook doesn't return correct value

### ISSUE THREAD

**Issue by ryanerringtonbd** [mantinedev/mantine#4671]
### What package has an issue

@mantine/hooks

### Describe the bug

The useColorScheme hook is returning the wrong value both on page refresh and when toggling the theme using a hotkey.

https://codesandbox.io/s/mantine-forked-9h65zr?file=/src/App.tsx 

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-forked-9h65zr?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
useColorScheme hook works correctly – it returns OS color scheme value.

**Comment by ryanerringtonbd** [comment]
Thanks - I guess it was useMantineColorScheme I was looking for, but can't find any docs on that.

**Comment by rtivital** [comment]
You can get that from theme object – `theme.colorScheme`
