### ISSUE TITLE
Menu on Modal -> zIndex issue

### ISSUE THREAD

**Issue by cx0onl** [mantinedev/mantine#468]
There is a zIndex problem when a menu is displayed on modals.

![image](https://user-images.githubusercontent.com/51824711/144019650-21f09d11-8dcf-477f-92ea-75353f9457b2.png)

https://codesandbox.io/s/bold-glitter-ugbbe

Please provide following information:
- @mantine/core
- 3.2.2
- Chrome, Windows 11

**Comment by rtivital** [comment]
You need to set z-index on Menu component – https://codesandbox.io/s/youthful-mcclintock-hbvpl

**Comment by cx0onl** [comment]
But that's just a workaround, right?
Setting the zIndex manually for each component is not really intuitive, is it?
(If this is the right way to do it, it should be mentioned in the doc).

Is there no fixed zIndex order of the mantine components?

Or is there a way to set zIndex automatically somehow? child.zindex (Menu) = parent.zindex (Modal) + 1?

**Comment by rtivital** [comment]
I'll increase menu z-index to 10000 in 3.3

**Comment by rtivital** [comment]
Fixed in 3.3, there should not be any z-index issue with any elements inside modals/drawers anymore. Feel free to reopen if it does not resolve your issue.

**Comment by suraj-klearmoney** [comment]
we are using mantine modal manager, when a modal is opened by doing some action in a modal, it is coming behind it. is this happening to anyone?

**Comment by emilesabatier** [comment]
> we are using mantine modal manager, when a modal is opened by doing some action in a modal, it is coming behind it. is this happening to anyone? we wrapped in _app.tsx

_You might have already found an answer to your problem but it could help somebody else._ 

For me the first modal is the modal component from the `@mantine/core` lib and the second modal from the modal manager. The first one has a `zIndex` root set to `200` by default (seems to come from [this file](https://github.com/mantinedev/mantine/blob/4fa634ebddf15a8515a9018e37b1e86d2e00883a/src/mantine-styles/src/theme/utils/get-default-z-index/get-default-z-index.ts)) , so I just had to set `zIndex: 201` to my `openConfirmModal` parameter object and it finally appeared above.

Note that it's also possible to change the zIndex in the first modal.

**Comment by brentarias** [comment]
My App Shell's `Aside`, which I took straight from the documentation, is eclipsing a `Menu` I added to the Header.  Notice:
![image](https://user-images.githubusercontent.com/1289327/209581561-5dae8e59-309c-41f0-bbb9-5b58755d4676.png)
I have made the following `zIndex` adjustments:
```
<Menu shadow="md" width={200} zIndex={100000}>
 ...
<Aside p="md" hiddenBreakpoint="sm" width={{ sm: 200, lg: 300 }} zIndex={300}>
```
Despite the explicit zIndex values, the problem persists.  Here are my dependency versions:
```
  "dependencies": {
    "@emotion/react": "^11.10.5",
    "@mantine/core": "^5.9.4",
    "@mantine/dates": "^5.9.4",
    "@mantine/hooks": "^5.9.4",
    "dayjs": "^1.11.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.6.1",
    "tabler-icons-react": "^1.56.0"
  },
```
Can we re-open this issue? 

I am building within Vite.
