### ISSUE TITLE
onChange of Select Component  should return the full data-structure and not just the value

### ISSUE THREAD

**Issue by emmanuelonah** [mantinedev/mantine#4683]
### What package has an issue

@mantine/core

### Describe the bug

My assumption of the onChange behaviour is that it should return the full data-structure and not just the value because users might want to use the full data-structure(object of `{label:string, value:string,....})`. 

### What version of @mantine/hooks page do you have in package.json?

6.0.14

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/select/

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by yshterev** [comment]
@emmanuelonah The value that goes into the select `data` prop usually is created from your own data structure. You should be able to access it in the `onChange` handler and find whatever you need.

**Comment by emmanuelonah** [comment]
> @emmanuelonah The value that goes into the select `data` prop usually is created from your own data structure. You should be able to access it in the `onChange` handler and find whatever you need.

Exactly thats my point, why do i need to run a _**derivative search**_ to find what i have selected when i could just get it from `onChange`.

<img width="1175" alt="Screenshot 2023-08-23 at 15 27 15" src="https://github.com/mantinedev/mantine/assets/37575223/eadb00b6-1c32-4111-98d3-1d966e4d1547">

**Comment by yshterev** [comment]
@emmanuelonah The obvious answer to this is that developers of Mantine UI don't want to add unnecessary logic to components and couple them with external data, unless really necessary. Increasing code complexity over time always leads to more bugs and more test cases to be covered. Accepting a request like yours ☝️ opens up the door to more similar requests.

TBH I also really like the current approach of Mantine to keep things simple.

**Comment by brrinta** [comment]
Or at least there can be a second option just like Ant Design Select onChange that contains the full option.
https://ant.design/components/select#select-props
