### ISSUE TITLE
ESLint error: MantineProvider not found in '@mantine/core' 

### ISSUE THREAD

**Issue by skrzepij** [mantinedev/mantine#4687]
### What package has an issue

@mantine/core

### Describe the bug

Hi! 
In my app, I'm using Next.js (v13) with Mantine (v6.0.x). 

List of all packages that I'm currently using from Mantine: 
```
    "@mantine/carousel": "^6.0.1",
    "@mantine/core": "^6.0.1",
    "@mantine/form": "^6.0.1",
    "@mantine/hooks": "^6.0.1",
    "@mantine/notifications": "^6.0.19",
```

Recently, I've added the `/notifications` package, based on the official documentation, and it works great!

The only problem, I run into is that, ESLint returns an error in `_app.tsx` to the `@mantine/notifications` import declaration.

```tsx
import { MantineProvider } from "@mantine/core"  // error: MantineProvider not found in '@mantine/core' 
...

<SessionProvider>
    <QueryClientProvider client={queryClient}>
      <MantineProvider withNormalizeCSS withGlobalStyles>
        <Notifications  />
           ...
      </MantineProvider>
    </QueryClientProvider>
</SessionProvider>
```

I've already tried to update other packages to `6.0.19` but without any success.

### What version of @mantine/hooks page do you have in package.json?

^6.0.1

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

It looks like the error is caused by a missing named import.
The only solution I came with is to add: 

```ts
// eslint-disable-next-line import/named
```
above the MantineProvider import line 🤷🏻 

Or to remove `plugin:import/recommended` from the `.eslintrc` config file.

**Comment by rtivital** [comment]
Try reinstalling dependencies, also make sure that all of your `@mantine/*` packages have the same version

**Comment by skrzepij** [comment]
Thanks @rtivital, but unfortunately, it's not any of that. I've reinstalled deps, cleared cache, updated all `@mantine/*` deps to 6.0.19, without any results.

After further investigation, it appears to be an issue related to the ESLint configuration (maybe even in conjunction with `pnpm`). 
Therefore, I don't think it's worth taking up more of your time :) 

Have a wonderful weekend!

**Comment by sathvik00123** [comment]
> Try reinstalling dependencies, also make sure that all of your `@mantine/*` packages have the same version

This really helped me to resolve the issue, grateful to you.
