### ISSUE TITLE
Able to embed Invalid URLs @mantine/rte

### ISSUE THREAD

**Issue by Jithinqw** [mantinedev/mantine#469]
- What package has an issue ? --> @mantine/rte
- What package version are you using? --> @latest
- In which browser and operating system issue occurred? --> Chrome / MacOS 10.15.1
- Are you willing to participate in fixing this issue (it's totally fine if not) and create a pull request with the fix? --> yes

Able to embed invalid URL to rte URL embed. Especially adding system like path to embed websites like 
``../`` ``../../``

**Comment by rtivital** [comment]
Honestly, I doubt that this is an issue — it's a default quill behavior. Let's say we would try to fix it, how would you tell that URL is incorrect?

**Comment by rtivital** [comment]
And `../../` seems to be a valid working [url](../../)
