### ISSUE TITLE
2 PasswordInputs inside Group component with 100% width are shrinking not like TextInput

### ISSUE THREAD

**Issue by imnash21** [mantinedev/mantine#4697]
### What package has an issue

@mantine/core

### Describe the bug

Inside **Group** component with 100% width, the 2 **PasswordInput** components are shrinking.

I set the **Group** component to _noWrap_.

I fixed this issue by modifying the **PasswordInput** component to:

MantineProvider -> theme -> components -> PasswordInput -> defaultProps -> w: "100%" 

![IMG_20230827_093242](https://github.com/mantinedev/mantine/assets/108371844/e9825d3a-84fb-44a4-bd79-2a12b8308a0f)

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
If you want inputs not to shrink, set `<Group grow />`
