### ISSUE TITLE
useform validation does not return errors in mantine/form 6.0.19

### ISSUE THREAD

**Issue by raychunghk** [mantinedev/mantine#4698]
### What package has an issue

@mantine/core

### Describe the bug

The form validation works well up to  @mantine/form 6.0.17, but not working in 6.0.19
Let's give a simple form obj
`
 const form = useForm({
    initialValues: { ...formValues, username, password, email },
    validate: (values) => {

        const rtn = {
          username:
            values.username.trim().length < 6
              ? 'Username must include at least 6 characters'
              : null,
          password:
            values.password.length < 5
              ? 'Password must include at least 6 characters'
              : null,
          email: /^\S+@\S+$/.test(values.email) ? null : 'Invalid email',
        };
        return rtn;
}

const nextStep = async () => {
    if (active === 0) {
      const isValid = await validateStep0(
        form.values.username,
        form.values.email,
      );
      if (!isValid) {
        return;
      }
    }
 const errors = await form.validate();
    console.log('set active step error', errors);
    if (form.validate().hasErrors) {
      return;
    }
    setActive((current) => {
      // if (form.validate().hasErrors) {
      //   return current;
      // }
      return current < 3 ? current + 1 : current;
    });
  };

`

I then have a function to turn to different steps , this function prevent going next step if form is invalid.

 
  
  It does not working in @mantine/form 6.0.19, but works in 6.0.17

### What version of @mantine/hooks page do you have in package.json?

useForm

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction.

**Comment by sebasfavaron** [comment]
@raychunghk make sure the submit button is not disabled while the form has errors (as on disabled=true, you can style it to look disabled id you want). I had errors with validation before and that was it.
I know the issue is old, but maybe it helps someone googling for this
