### ISSUE TITLE
Slider component

### ISSUE THREAD

**Issue by rtivital** [mantinedev/mantine#47]
@mantine/core should export Slider component.

[Example on codepen](https://codepen.io/donalfonsnisnoni/pen/eYgMJEj)

Features for initial version:
- Single handle (range support may be added in future versions)
- Tooltip over handle
- Min, max and step support
- Horizontal orientation only
- Only controlled variant
- Component should follow [WAI ARIA practices](https://www.w3.org/TR/wai-aria-practices/#slider)

Component props:
- **size (defaults to md)** – defines track height – xs, sm, md, lg, xl – predefined in component styles, should be exported from @mantine/core as SLIDER_SIZES variable (see other components) + number value to set height in px.
- **thumbSize (defaults to md)** – defines thumb size – predefined in component styles + number value to set height and width in px.
- **thumbRadius (defaults to sm)** – xs, sm, md, lg, xl – defines thumb border-radius – predefined in theme.radius + number value to set border-radius in px.
- **thumbShadow (defaults to xs)** –  xs, sm, md, lg, xl – defines thumb box-shadow – predefined in theme.shadows + string value to set custom box-shadow.
- **min = 0**, **max = 100**, **step = 1** – all `number`
- **value (required)** – `number` – current value
- **onChange (required)** – `(value: number) => void` – calls when value changes
- **noLabel (defaults to false)** – hides tooltip over thumb
- **formatLabel** – `(value: number) => ReactNode` – function which is used to format label content, e.g. `(value) => value.toString() + '%'`
- **color** – `string` – active track color from theme.colors, defaults to `theme.primaryColor`

**Comment by arpitBhalla** [comment]
hey @rtivital May I work on this?

**Comment by rtivital** [comment]
Yes, sure, thanks, [here are contributions guideline](https://mantine.dev/pages/contribute/). Please create pull request to next-1.1.0 branch, if you have any questions regarding implementation contact me in this issue or [in Telegram](https://t.me/rtivital)

**Comment by arpitBhalla** [comment]
Sure, should I have to take that codepen and convert it into react?

**Comment by arpitBhalla** [comment]
@rtivital How can I add tooltip over thumb?

**Comment by rtivital** [comment]
When mouse is over thumb display tooltip

**Comment by arpitBhalla** [comment]
I mean do I need to make a div or I sholud use Tooltip component

**Comment by rtivital** [comment]
Use div with Transition component

**Comment by arpitBhalla** [comment]
Okie Sir

**Comment by arpitBhalla** [comment]
Hey @rtivital I apologize for being late, but I am not able to do this!
