### ISSUE TITLE
DatePickerInput cannot be used in modals or drawers

### ISSUE THREAD

**Issue by TechPiranja** [mantinedev/mantine#4702]
### What package has an issue

@mantine/core

### Describe the bug

The DatePickerInput component from @mantine/dates (version 6.0.19) does not open the actual date picker box over the modal / drawer when used inside of a Modal or Drawer component. You can only see a port of it.

Tested in Chrome on Mac. 

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/late-night-hz7ggx

### Do you know how to fix the issue

No

**Comment by TechPiranja** [comment]
i figured out, that adding this is the solution:

```css
.mantine-Modal-content {
  overflow: visible;
}
```

**Comment by rtivital** [comment]
https://codesandbox.io/s/funny-snyder-jwlx24?file=/src/App.tsx
