### ISSUE TITLE
Modal is off-center by default

### ISSUE THREAD

**Issue by arel** [mantinedev/mantine#4705]
### What package has an issue

@mantine/core

### Describe the bug

Modals appear to be off-center by default.

![Screenshot 2023-08-29 12 50 42 PM](https://github.com/mantinedev/mantine/assets/153497/27f6d83e-65fe-4c7e-a2b8-2e50d85a3224)

It appears that the `xOffset` is creating a padding of `5vw` by default (as stated in the documentation.) However, the inner part of the modal does not account for this space, pushing the modal to the side.

If the **`withGlobalStyles`** prop is set, the modal is correctly positioned, but the documentation for `withGlobalStyles` does not explain why this should be the case.

Similarly, setting the **`xOffset`** to 0 also fixes the problem, but I don't believe that's the solution either because the example in the documentation does not set `xOffset` and it is correctly centered in that example.

I believe this is a bug.

I am using Chrome (115.0.5790.182).

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/prod-rgb-mffqyh

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
