### ISSUE TITLE
modal closing

### ISSUE THREAD

**Issue by johngeorge1998** [mantinedev/mantine#4708]
### What package has an issue

@mantine/modals

### Describe the bug

I've set closeOnClickOutside={ false } so that the modal closes when it's clicked outside of the modal, But it isn't working why?

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Please send a sandbox that reproduces the issue, template – desandbox.io/s/mantine-template-9ze89?file=/src/App.tsx
