### ISSUE TITLE
Link in RichTextEditor opens twice in browser

### ISSUE THREAD

**Issue by TruePadawan** [mantinedev/mantine#4711]
### What package has an issue

@mantine/tiptap

### Describe the bug

Clicking on any link in the editor opens it twice in the browser. It loads in the same page and opens another in a new tab.

https://github.com/mantinedev/mantine/assets/71678062/dc6f1bc8-d5ee-42ab-bc10-38732b8b1e4b

### What version of @mantine/hooks page do you have in package.json?

6.0.16

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
I cannot reproduce the issue on mantine.dev website in Edge browser, you are welcome to reopen the issue if you can provide a way for me to reproduce the issue
