### ISSUE TITLE
Select does not clear when value is undefined

### ISSUE THREAD

**Issue by karan316** [mantinedev/mantine#4716]
### What package has an issue

@mantine/core

### Describe the bug

The select component does not clear if the value is undefined but it works for null

### What version of @mantine/hooks page do you have in package.json?

^6.0.19

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is expected behavior – when value is undefined, Select is in uncontrolled mode. To clear select value, use `null` instead.
