### ISSUE TITLE
root styles take precedence over variant styles

### ISSUE THREAD

**Issue by OhadBaehr** [mantinedev/mantine#4719]
### What package has an issue

@mantine/core

### Describe the bug

```
  components: {
        Table: {
            styles: {
                root: {
                    tr: {
                        height: 52
                    },
                },
            },
            variants: {
                narrow: () => ({
                    root: {
                        tr: {
                            height: 36
                        }
                    }
                })
            }
        },
}
```

In this case `<Table variant="narrow"/> `won't have any effect on the height because the root styles are overriding them.
I don't think it should be this way as it reduces the value of enabling variants in the first place.

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.
