### ISSUE TITLE
Tabs component breaks focus trap

### ISSUE THREAD

**Issue by ivanbrykov** [mantinedev/mantine#4723]
### What package has an issue

@mantine/core

### Describe the bug

When using `Tabs` with input controls as tab children, it breaks focus trap for the parent element (e.g. a `Drawer`). An example app: 
```
import React from "react";
import { Drawer, Tabs, Textarea, TextInput } from "@mantine/core";

export const App = () => {
  return (
    <>
      <Drawer
        withinPortal
        lockScroll
        position="bottom"
        opened
        onClose={() => undefined}
      >
        <Tabs defaultValue="comment">
            <Tabs.List>
              <Tabs.Tab value="comment">Comment</Tabs.Tab>
              <Tabs.Tab value="task">Task</Tabs.Tab>
            </Tabs.List>

            <Tabs.Panel value="comment">
              <Textarea />
            </Tabs.Panel>

            <Tabs.Panel value="task">
              <TextInput />
            </Tabs.Panel>
        </Tabs>
      </Drawer>
    </>
  );
};
```

It's available here: https://codesandbox.io/p/sandbox/intelligent-river-f7z8j9?welcome=true

To reproduce, open the example and start pressing the Tab button on your keyboard. Eventually the focus breaks out of the `Drawer` component.

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/sandbox/intelligent-river-f7z8j9

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

No idea..

**Comment by rtivital** [comment]
I cannot reproduce the issue with 7.0.0. You can view the stories that I've added for testing here - https://github.com/mantinedev/mantine/commit/a36173b3d862c818c8368d46152b353fa1dd8631

https://github.com/mantinedev/mantine/assets/10353856/f4405a41-e18e-485a-8e19-26e3459fddbe
