### ISSUE TITLE
Using media query desktop view gets rendered first in mobile phone than the mobile view appears late.

### ISSUE THREAD

**Issue by Unmoy** [mantinedev/mantine#4729]
### What package has an issue

@mantine/hooks

### Describe the bug

I am using next JS and Mantine in a project, I tried using the use media query hook to make the components responsive, which is working fine. But the problem is when I open the website in mobile, desktop view is getting rendered first, than the mobile view appears late, which is creating a poor user experience. I tried passing the default pops to true, but in result what happens is when I open in the desktop view the mobile view appears first then the desktop view is appearing. How can I fix this issue to open mobile view when I open on mobile and desktop view when I open desktop?

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is described in documentation – https://mantine.dev/hooks/use-media-query/#server-side-rendering
Do not use this hook If you have ssr in your application. You can find responsive guide here – https://mantine.dev/styles/responsive/

**Comment by Unmoy** [comment]
It still creates the same problem? Desktop view comes first in mobile!!

**Comment by Unmoy** [comment]
I am trying to render two components like this which is not happening using media query component.

{mobile ? <MobileVideoPlayer /> : <VideoPlayer />}

**Comment by rtivital** [comment]
See https://mantine.dev/styles/responsive/#changing-component-size-based-on-media-query
