### ISSUE TITLE
@mantine/core Unable to wrap Stepper.Step sub-component

### ISSUE THREAD

**Issue by jonathanhudak** [mantinedev/mantine#4734]
### What package has an issue

@mantine/core

### Describe the bug

I'd like to be able to wrap the compound components to prevent re-renders due to context, but I can't because the styles are mysteriously removed. Is there anything I am doing wrong here?

Reproduction: https://codesandbox.io/s/mantine-forked-ygn4fx?file=/src/App.tsx

### What version of @mantine/hooks page do you have in package.json?

none

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-forked-ygn4fx?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
It is described in documentation – https://mantine.dev/core/stepper/#wrap-stepperstep
