### ISSUE TITLE
useComponentDefaultProps produce 'TS2590: Expression produces a union type that is too complex to represent.'

### ISSUE THREAD

**Issue by marcocavanna** [mantinedev/mantine#4743]
### What package has an issue

@mantine/styles

#### Description
When using the hook `useComponentDefaultProps('MyComponent', defaultProps, props);` in the way described on the official documentation (link [here)](https://mantine.dev/guides/custom-components/#add-default-props-support), I am facing a TypeScript issue:

> **TS2590: Expression produces a union type that is too complex to represent**.

I use WebStorm in my work, I don't know if the problem also occurs on Visual Studio Code

#### Investigation
I think the problem is due to the definition of the type returned by the function, in [MantineProvider.tsx line 50-52](https://github.com/mantinedev/mantine/blob/0455a0f3c47938c0dcae69e5093ce6c28a6bc73b/src/mantine-styles/src/theme/MantineProvider.tsx#L51) and the wrong declaration of the `defaultProps` type (Partial<Props>) written in the documentation at the link above.

### What version of @mantine/hooks page do you have in package.json?

6.0.20

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

#### Partial Solution
A partial solution to the problem could be to modify the declaration of the`defaultProps: Partial<CustomComponentProps>` variable, omitting the type declaration, but using the`satisfies Partial<CustomComponentProps>` constraint.
It would therefore be necessary to modify the documentation linked from
```typescript
const defaultProps: Partial<CustomComponentProps> = {
  radius: 6,
};
```
to
```typescript
const defaultProps = {
  radius: 6,
} satisfies Partial<CustomComponentProps>;
```

#### Full Solution
Using what I described in the partial solution, the final type derived from `useComponentDefaultProps` is correct from a code point of view, but is represented incorrectly when inspecting the result of the function:

Example:
```typescript
/** Define CustomComponent Props */
interface MyComponentProps {
  align?: 'left' | 'center' | 'right';
}

/** Define CustomComponent default props */
const defaultProps = {
  align: 'left'
} satisfies Partial<MyComponentProps>;

/** Define CustomComponent */
const MyComponent: React.FunctionComponent<MyComponentProps> = (props) => {

  const { align } = useComponentDefaultProps('MyComponent', defaultProps, props);

  // typeof align returns 
  // ("left" & "left") | "left" | ("center" & "left") | "center" | ("right" & "left") | "right"
  type AlignType = typeof align;

  return (
    <Box ta={align}>
      My wonderful Component
    </Box>
  );
};
```

I think the problem is caused by the fact that the declaration of the keys for which a default value has been passed from the type returned by the hook are not omitted from the starting type.
My proposal is to change the type returned by useComponentDefaultProps from
```typescript
T & { [Key in Extract<keyof T, keyof U>]-?: U[Key] | NonNullable<T[Key]>; }
```
to
```typescript
Omit<T, keyof U> & { [Key in Extract<keyof T, keyof U>]-?: NonNullable<T[Key]>; }
```

`U[Key]` must be removed too because the `satisfies` constraints won't return the exact type of the key, but the generic type used.
If used as in the example above, a generic variable (a string in this case) will be returned instead the original declaration in MyComponentProps

**Comment by rtivital** [comment]
I cannot reproduce the issue with typescript 5.1.6 and [useProps](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/core/MantineProvider/use-props/use-props.ts#L18) hook (7.0 replacement for useComponentDefaultProps). If you can send a PR with a failing example and steps to reproduce in VS Code or cli (I do not have WebStorm license) I can have a look.

**Comment by marcocavanna** [comment]
Hi @rtivital, thanks for your reply! I had this problem with old version of matinee (6.x), I can't check if the problem is still present as I have no way to update to the latest major.
I'll try to to that as soon as possible

**Comment by rtivital** [comment]
Great, please reopen the issue when you can provide a reproduction
