### ISSUE TITLE
Useless scrollbars (TransferList)

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#475]
- What package has an issue (@mantine/core, mantine/hooks or other)? @mantine/core
- What package version are you using? v3.3.0
- In which browser and operating system issue occurred? Brave@96.0.4664.45, Windows 11
- If possible please attach link to codesandbox with reproduced issue: https://mantine.dev/core/transfer-list/

![image](https://user-images.githubusercontent.com/49494752/144514376-62e11570-32eb-4795-b4f1-0ecde2441baf.png)

**Comment by rtivital** [comment]
Thanks for reporting! This issue was fixed in 3.3.1 patch.
