### ISSUE TITLE
Multiselect required + searchable prop

### ISSUE THREAD

**Issue by djole90-dev** [mantinedev/mantine#4752]
### What package has an issue

@mantine/core

### Describe the bug

If we use searchable + required prop, we get an error that the field is required even if we have selected items (probably because the search is empty) 

happening on 7.0.0.beta.5

### What version of @mantine/hooks page do you have in package.json?

7.0.0.beta.5

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
MultiSelect component does not support native browser validation and it is also impossible to add this feature. If you need to display red astersik, set `withAsterisk` prop instead.
