### ISSUE TITLE
Mantine Accordion height bug after rerender

### ISSUE THREAD

**Issue by FearZee** [mantinedev/mantine#4753]
### What package has an issue

@mantine/core

### Describe the bug

There is a bug with accordion height on open accordion when item rerenders.

Reproduce:
Having a form with validation and at least 2 input fields inside a accordion.panel.
In accordion.control have eg. a switch to trigger rerender.

Open the accordion with unchecked switch
Click on the switch so it's checked
Enter bad input in both forms (eg. navigate between with tab key)

Expected:
I can see the error message below both input fields and the item will be resized

Actually:
The accordion stays at the height and i cannot see both error messages.
The css height prop is not removed.

![233127175-35bca376-df46-43f6-a20f-0ffc3a6cd6fe](https://github.com/mantinedev/mantine/assets/38909210/3d69ec21-99e5-4c50-acc7-25957a553629)
![233127163-9d6cf68f-4637-497b-a9df-e73f44a4883c](https://github.com/mantinedev/mantine/assets/38909210/59c48bb4-fd4a-43cc-9b39-74137846b782)

### What version of @mantine/hooks page do you have in package.json?

6.0.20

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/holy-lake-9l7svc?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Rendering Switch inside Accordion.Control is an accessibility violation – you should not render input inside a button. It is not planned to support use cases with accessibility violations on library level. If you want to compose controls, see https://mantine.dev/core/accordion/#compose-controls.
