### ISSUE TITLE
NumberInput broken in Edge 84 - Uncaught TypeError: t.replaceAll is not a function

### ISSUE THREAD

**Issue by arel** [mantinedev/mantine#4759]
### What package has an issue

@mantine/core

### Describe the bug

Supported versions of Chromium browsers (e.g., Edge 84) break when using the `NumberInput` component because `replaceAll()` is not supported and results in the error:

```
Uncaught TypeError: t.replaceAll is not a function
```

Yet, version 84 [should be supported](https://mantine.dev/pages/about):

> All Mantine components and hooks were tested to work in the following browsers:
> ...
> Chromium browsers 84+ – Chrome, Edge, Chrome for Android, etc. (released July 2020)

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Use `replace` with a global regex instead of `replaceAll`.

See, for instance: https://www.designcise.com/web/tutorial/how-to-fix-replaceall-is-not-a-function-javascript-error

**Comment by arel** [comment]
@rtivital, would you be open to reviewing #4760 so we can fix this in version 6.X as well?

**Comment by rtivital** [comment]
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.

**Comment by arel** [comment]
I think this issue still impacts version 7.0 because `replaceAll` is still used in the codebase here: https://github.com/mantinedev/mantine/blob/4bf60419e19aa84f4db302521b0aa72c6d165978/src/mantine-form/src/resolvers/yup-resolver/yup-resolver.ts#L28

**Comment by rtivital** [comment]
Starting from 7.0 minimum supported versions were updated – https://mantine.dev/about/#browser-support
Although most of the features will work in older browsers, some components are using new JS and CSS features. For replaceAll, you can include a polyfill – https://vanillajstoolkit.com/polyfills/stringreplaceall/
