### ISSUE TITLE
Color of individual tabs is broken (Tabs)

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#476]
- What package has an issue (@mantine/core, mantine/hooks or other)? @mantine/core
- What package version are you using? v3.3.0
- In which browser and operating system issue occurred? Brave@96.0.4664.45, Windows 11
- If possible please attach link to codesandbox with reproduced issue: https://mantine.dev/core/tabs/#change-colors

![image](https://user-images.githubusercontent.com/49494752/144517285-954edc80-14a9-4bee-a7b3-b9f2e27a41cd.png)

**Comment by rtivital** [comment]
Thanks for reporting! This issue was fixed in 3.3.1 patch.
