### ISSUE TITLE
Text Input with type="search"

### ISSUE THREAD

**Issue by kimfucious** [mantinedev/mantine#4764]
### What package has an issue

@mantine/core

### Describe the bug

When I add type="search" to a TextInput component there is no little "x" that clears the content of the field with a click.

In a normal HTML5 input, this is available.

What's the proper way to do this with Mantine?

### What version of @mantine/hooks page do you have in package.json?

5.10.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
`X` is hidden with styles to make input look the same in all browsers. It is expected behavior. If you want this button to be displayed, you can override component styles with Styles API or create a custom clear button by rendering `CloseButton` in the `rightSection`.
