### ISSUE TITLE
Expose Search component from docs as a seperate CmdK component

### ISSUE THREAD

**Issue by voladelta** [mantinedev/mantine#477]
Thank you for this impressive react component library 👍🤟

I'm gonna migrate from Chakra UI to Mantine!

The Search in the header is really nice. I really like it. Is there any chance you could expose as a component to Mantine?
Or maybe in @matine/extra?

**Comment by rtivital** [comment]
Search is just an Autocomplete with a custom item component and Kbd, you can build your own custom search with these components
