### ISSUE TITLE
Uncontrolled tooltips can remain visible indefinitely

### ISSUE THREAD

**Issue by Slapbox** [mantinedev/mantine#4772]
### What package has an issue

@mantine/core

### Describe the bug

The circumstances to reproduce this are unclear to me even after seeing this for over a year, just upgraded to `6.x` and still see it, so I figured I might as well report it since it seems to persist into `6.x`

I've seen it on Linux and Windows, with mouse inputs sending `pointerType` of `mouse` and `pointer`. It occurs in all combinations.

It occurs very infrequently, but I wouldn't call it extremely rare. I've seen it probably 40-50 times over the 12-18 months out of thousands of times hovering elements.

Hovering back over the reference element and away again resolves the persistent tooltip.

### What version of @mantine/hooks page do you have in package.json?

~6.0.0

### If possible, please include a link to a codesandbox with the reproduced problem

Unknown how to reliably reproduce

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Unknown. This is possibly an issue in `floating-ui`, but I've only ever seen it with Mantine so I kind of doubt it.

**Comment by Slapbox** [comment]
Actually, just got very luck and hit it twice in a row in Mantine 6.x. Maybe this suggests the issue is actually worse for some reason? 

I'll update as I learn more.

**Comment by rtivital** [comment]
It usually happens when a heavy operation happens before the tooltip is supposed to close, for example if you click direction control on the docs website.

**Comment by Slapbox** [comment]
Ah yes that reproduces it very reliably. Is there some way we can clean those up? It makes things feel janky when they stick around after they're supposed to be gone.

**Comment by rtivital** [comment]
I do not know, I wasn't able to fix that

**Comment by nmay231** [comment]
Looking into this, I don't think it has to do with a heavy workload; it matters which (part of the) element you're clicking. Using the RTL/LTR button on the docs site, it matters if you are clicking on the svg or on the padding of the button.

Maybe something funky is going on with event bubbling such that clicking the svg keeps the tooltip while clicking the button padding allows it to go away? I couldn't reproduce the issue in storyboard by putting an svg in a button, but I still have to try a couple of other ideas that might be able to narrow the issue down.

**Comment by Slapbox** [comment]
That's an excellent find @nmay231. It looks like this can be _mostly_ resolved by setting `pointer-events: none` on the inner `svg` _and_ `path` - but I say mostly because the tooltip still does flash on the element after it moved and so it doesn't seem like a 100% fix, but perhaps I'm being too much of a stickler.

**Comment by nmay231** [comment]
@Slapbox I think I got it. It's because the element is deleted from the DOM and therefore events are no longer bubbling (the svg in the button switchs to/from `<IconTextDirectionLtr />` and `<IconTextDirectionRtl />`)

Here's a storybook example.

```typescript
export function MovingTarget() {
  const [isOffset, setIsOffset] = useState(false);

  return (
    <div
      style={{ position: 'relative', width: '500px', height: '500px', outline: '1px solid green' }}
    >
      <div style={{ height: isOffset ? '150px' : '0px' }}></div>
      <Tooltip
        label="Should not stick around after moving"
        openDelay={100}
        closeDelay={100}
        position="bottom-end"
      >
        <Button
          onClick={() => {
            setIsOffset((toBe) => /* or */ !toBe);
          }}
        >
          Can&lsquo;t touch this
          {isOffset ? <IconSquare /> : <IconCircle />}
        </Button>
      </Tooltip>
    </div>
  );
}
```

**Comment by nmay231** [comment]
I was gonna say this probably can't be resolved since this is the fault of the user, but perhaps it can be prevented if event handling is done in the capture phase instead of the bubble phase.

**Comment by Slapbox** [comment]
@nmay231 thanks for your work on this. I wonder if you had any additional thoughts on how to fully fix this?

**Comment by Slapbox** [comment]
I wouldn't say it works _entirely_ correctly, but I understand if there's no way to make it work 100% as I'd think it should (ie the tooltip should not flash on the moved element.)

**Comment by rtivital** [comment]
I've added this logic to the rtl/ltr button with uncontrolled tooltip on mantine.dev. I do not see any issues there. What do you mean by it not working entirely correctly?

**Comment by Slapbox** [comment]
What I mean is that the tooltip jumps to the new location of the button and then fades out per usual, but the fully correct behavior in my mind would be for the tooltip to instantly be hidden in such a circumstance.

I know that's nitpicky and it's understandable if it's not worth the headaches that it would entail to achieve that. Thanks for such a wonderful project @rtivital.
