### ISSUE TITLE
Impossible to use specific loader with LoadingOverlay and Mantine 7

### ISSUE THREAD

**Issue by nacimgoura** [mantinedev/mantine#4780]
### What package has an issue

@mantine/core

### Describe the bug

With previous mantine version, it's possible to use specific loader with `loader` param, like this :
```
<LoadingOverlay
  visible={loading}
  loader={<GraphLoader />}
/>
```

Now `loader` doesn't exist, so It's impossible to work correctly.
Even in the [doc](https://mantine.dev/core/loading-overlay), this case is not mentioned now 

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

mantine 7.0.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Implement `loader` param again

**Comment by rassie** [comment]
I'm by no means an expert, but I think the intended way now is to set `loaderProps` (especially `type` inside it) and [register your loader as a type](https://mantine.dev/core/loader/#adding-custom-loaders).

**Comment by naivefun** [comment]
You should use `loaderProps` now.

**Comment by nacimgoura** [comment]
> I'm by no means an expert, but I think the intended way now is to set `loaderProps` (especially `type` inside it) and [register your loader as a type](https://mantine.dev/core/loader/#adding-custom-loaders).

Yes it's work correctly, even if It was simple before
