### ISSUE TITLE
Attempted import error: 'packSx' is not exported from '@mantine/core'

### ISSUE THREAD

**Issue by JawadFadel** [mantinedev/mantine#4782]
### What package has an issue

@mantine/core

### Describe the bug

Attempted import error: 'packSx' is not exported from '@mantine/core'

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Starting from 7.0 `@mantine/core` components no longer support `sx` prop, everything related to this prop was removed from the packages. If you want to continue using `sx` prop and other emotion features, you can install 6.0.21 version instead.

**Comment by JawadFadel** [comment]
Thanks
