### ISSUE TITLE
V7 DatePickerInput styles broken

### ISSUE THREAD

**Issue by ImamAlfariziSyahputra** [mantinedev/mantine#4790]
### What package has an issue

@mantine/dates

### Describe the bug

i just copy paste the code from https://mantine.dev/dates/date-picker-input and using the provided example code from https://github.com/mantinedev/next-pages-template. it is working fine on mantine v6 but broke at v7

<img width="1264" alt="image" src="https://github.com/mantinedev/mantine/assets/63343105/fe091f63-5bdc-4e05-9520-77175cf79c8a">

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

"@mantine/core": "^7.0.0", "@mantine/dates": "^7.0.0", "@mantine/hooks": "^7.0.0"

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by ImamAlfariziSyahputra** [comment]
i'm sorry i forgot to import the @mantine/dates styles 😅, AFAIK in v6 no need to import the dates styles😁
`import '@mantine/dates/styles.css';`

**Comment by jfilipeferreira96** [comment]
Thanks importing the styles fixed the issue, but this is still an issue in the V7.
