### ISSUE TITLE
SegmentControl does not honor color='primary'

### ISSUE THREAD

**Issue by naivefun** [mantinedev/mantine#4805]
### What package has an issue

@mantine/core

### Describe the bug

SegmentControl does not honor color='primary'

We need explicitly use color='teal'

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### If possible, please include a link to a codesandbox with the reproduced problem

(the template still uses 6.x, please provide a new template for v7)

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is expected behavior, none of the components support `color="primary"`

**Comment by naivefun** [comment]
> It is expected behavior, none of the components support `color="primary"`

I see. Now it seems primary color (configured in createTheme) serve as default color. But for segment control it does not (always white and black). What if I want to use primary color for segment control too? This can be done in v6 with color='primary' so that if user change primary color it also changes along. Now this is not possible with v7.
