### ISSUE TITLE
Mantine Date Input Tab focus behaviour not working for Calendar 

### ISSUE THREAD

**Issue by Snivio** [mantinedev/mantine#4808]
### What package has an issue

@mantine/dates

### Current Behavior:
The date input component doesn't handle tab or arrow focus behaviour for the calendar pop-up .

The date input component with the trapFocus prop set to true focuses on the top arrow inside the popup calendar, but it breaks the behavior when clicking outside the popup. Additionally, the focus doesn't move to the next item in the popup; it gets stuck on the arrow.

### Screenshots/Code Snippets:
`
popoverProps={{
  trapFocus: true
}}
`

<img width="338" alt="image" src="https://github.com/mantinedev/mantine/assets/31371104/22082be6-f0bc-4d53-a030-11ab1a744410">

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.17 and Latest as well

**Comment by rtivital** [comment]
DatePicker component as well as other Mantine components use a soft focus trap – if you escape it by clicking something outside the input, the focus will not be forced to stay on the element. The component is fully accessible with keyboard. It is not planned to change this behavior.

**Comment by Snivio** [comment]
@rtivital Its Date Input im referring to not DatePicker
