### ISSUE TITLE
V7 Table highlight doesn't work on striped dark rows

### ISSUE THREAD

**Issue by najibghadri** [mantinedev/mantine#4812]
### What package has an issue

@mantine/core

### Describe the bug

Can be tested on https://mantine.dev/core/table/#striped-and-rows-hover if you check striped and highlight. On darker rows highlight doesn't work. 

Example of it working well on v6: https://v6.mantine.dev/core/table/#striped-and-rows-hover

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

-

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by mateuscqueiros** [comment]
Hello! There was a problem with the specificity of the classes that styled the background of the rows. Darker rows had a style that overrode the hover change.

**Comment by najibghadri** [comment]
Thank you for the fix!
