### ISSUE TITLE
'@mantine/core/styles.css' not found

### ISSUE THREAD

**Issue by massanishi** [mantinedev/mantine#4819]
### What package has an issue

@mantine/core

### Describe the bug

I have no trouble importing all the modules like "@mantine/core", but it fails to import "@mantine/core/styles.css" following the getting started example.

I'm using vite SSR. It's probably my project setup issue. Can I go on using Mantine without core/styles.css import?

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.21

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
You are using documentation for version 7.x while using version 6.x. You can find documentation for 6.x here – https://v6.mantine.dev/
