### ISSUE TITLE
`NumberInput` doesn't allow `type="number"` (add "number" to `NumberInputProps["type"]`)

### ISSUE THREAD

**Issue by jakeboone02** [mantinedev/mantine#4821]
### What package has an issue

@mantine/core

### Describe the bug

When using the `NumberInput` component, the `type` prop (from the `NumberInputProps` interface) only allows "text" , "tel", or "password".

https://github.com/mantinedev/mantine/blob/41d11eec2fcf06a6ad4ee1d02762476bce9d8da2/src/mantine-core/src/components/NumberInput/NumberInput.tsx#L123

`react-number-format` [has the same list](https://github.com/s-yadav/react-number-format/blob/e2179f9e9d2c4ddd1ab714ff385412b53e9ed3e7/src/types.ts#L69C38-L69C38), but [their docs](https://s-yadav.github.io/react-number-format/docs/props#type-string) say `type` is `string`. Those three strings are listed as _possible_ values. `react-number-format` and Mantine v7 actually limit the `type` prop to _only_ those three values.

`NumberInputProps["type"]` should be `string`, the same as `HTMLInputElement["type"]`.

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

```diff
-  type?: 'text' | 'tel' | 'password';
+  type?: string;
```

**Comment by rtivital** [comment]
Why do you need type number? What do you want to achieve with it?

**Comment by jakeboone02** [comment]
**Short answer:**

In v6 the `type` prop was typed as `"number" | "text"` and that made sense. Having "password" as an option for a "NumberInput" component but not allowing "number" seems strange to me.

For what it's worth, `type="number"` _does_ work as I expect it to, I just have to ignore the TypeScript errors.

**Long answer:**

I maintain a React component library called [`react-querybuilder`](https://github.com/react-querybuilder/react-querybuilder), and I publish compatibility packages for different style libraries like Mantine. My test suite uses [the `toHaveValue` method](https://github.com/testing-library/jest-dom/blob/main/src/to-have-value.js) from [`@testing-library/jest-dom`](https://github.com/testing-library/jest-dom#tohavevalue).

The issue with the `toHaveValue` method for "number"-type inputs boils down to [this line](https://github.com/testing-library/jest-dom/blob/6d659995665076d78b9f874bec75545bfc56e5ab/src/utils.js#L192).

All the other style libraries I support evaluate their values to a `number` when `type="number"`, so I can use a common test for all of them: something like `expect(el).toHaveValue(12)`.

I'd like to keep using that common test like I could with Mantine v6, instead of having to check if it's a `string` or a `number`.

_Side note: the [CodeSandbox template](https://codesandbox.io/s/mantine-template-9ze89) linked in the [bug report issue template](https://github.com/mantinedev/mantine/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) is still using Mantine v6._

**Comment by rtivital** [comment]
I've checked the type value comes from `react-number-format` library, its type is:

```tsx
declare type NumberFormatBase = {
    type?: 'text' | 'tel' | 'password';
    displayType?: 'input' | 'text';
    inputMode?: InputAttributes['inputMode'];
    renderText?: (formattedValue: string, otherProps: Partial<NumberFormatBase>) => React.ReactNode;
    format?: FormatInputValueFunction;
    removeFormatting?: RemoveFormattingFunction;
    getInputRef?: ((el: HTMLInputElement) => void) | React.Ref<any>;
    value?: number | string | null;
    defaultValue?: number | string | null;
    valueIsNumericString?: boolean;
    onValueChange?: OnValueChange;
    isAllowed?: (values: NumberFormatValues) => boolean;
    onKeyDown?: InputAttributes['onKeyDown'];
    onMouseUp?: InputAttributes['onMouseUp'];
    onChange?: InputAttributes['onChange'];
    onFocus?: InputAttributes['onFocus'];
    onBlur?: InputAttributes['onBlur'];
    getCaretBoundary?: (formattedValue: string) => boolean[];
    isValidInputCharacter?: (character: string) => boolean;
};
```

So, their documentation does not show the real type used.

**Comment by jakeboone02** [comment]
Right, I guess that's kind of my point. The documentation shows the actual accepted usage during execution by a JS runtime (any `string` is valid), outside the context of TypeScript. You can see this by updating the demo below the [`type` prop docs](https://s-yadav.github.io/react-number-format/docs/props#type-string) (screenshot below).

If the JS accepts any `string` for that prop, I don't understand why the types restrict it to specific values. IMO, the types are wrong and the documentation is more indicative of the overall intent.

Should I open a ticket in that repo to get feedback?

![image](https://github.com/mantinedev/mantine/assets/366438/0197974b-413f-4e7f-a561-a74593197ca6)

**Comment by rtivital** [comment]
Yes, there might be some issues with other type, so it is better to discuss it with `react-number-format` maintainers

**Comment by jakeboone02** [comment]
Thanks, @rtivital. See s-yadav/react-number-format#799.

**Comment by jakeboone02** [comment]
@rtivital - s-yadav/react-number-format#799 was closed with an explanation so I'm closing this one.
