### ISSUE TITLE
ActionIcon does not seem to have the color property properly ported

### ISSUE THREAD

**Issue by dvmoritzschoefl** [mantinedev/mantine#4823]
### What package has an issue

@mantine/core

### Describe the bug

settings the **color** property on an ActionIcon works, but is not marked as deprecated as in other components (like Text). Also setting the **c** shorthand for it does not seem to have any effect

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
- `color` prop is not deprecated on ActionIcon and other components
- `c` prop works correctly on ActionIcon component

https://mantine.dev/theming/colors/#difference-between-color-and-c-props
