### ISSUE TITLE
[Feature Request] Change order of elements in TransferList

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#483]
I think it would be good to have the possibility to change the order of the elements.

For example, if you want to use TransferList to display only selected fields in a table and change the order of the selected fields

**Comment by rtivital** [comment]
TransferList is a simple component that was designed to do one thing — move data from one place to another. I do not think that dnd would make much sense in terms of UX, it is not obvious that you are supposed to reorder items in this list.
