### ISSUE TITLE
Scroll wheel not working in ScrollArea present page body while Drawer is open

### ISSUE THREAD

**Issue by Shadowfita** [mantinedev/mantine#4834]
### What package has an issue

@mantine/core

### Describe the bug

Scroll wheel not working in ScrollArea present page body while Drawer is open. 

I have a drawer with the following props -

`position="left"
size={220}
opened={open}
onClose={() => setOpened(false)}
withOverlay={false}
withCloseButton={false}
zIndex={1}`

While this drawer is visible, scroll areas present within the body of my page (AppShell children) are not activated by mouse scroll. This has worked in previous versions, I've not been able to find the cause.

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.14

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
When Drawer component is opened, scroll is locked. If you do not need this behavior, set `<Drawer lockScroll={false} />`

**Comment by Shadowfita** [comment]
Perfect, thanks so much @rtivital
