### ISSUE TITLE
TimeInput showPicker not working in FireFox browser

### ISSUE THREAD

**Issue by christy-anto** [mantinedev/mantine#4839]
### What package has an issue

@mantine/core

### Describe the bug

TimeInput showPicker not showing in Firefox browser

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.12

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is expected behavior – Firefox does not support this feature, you can view it on the mdn website – https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#try_it
We cannot do this on the library level to support this feature.
