### ISSUE TITLE
[Select] Warning: value prop on input should not be null. Consider using an empty string to clear the component or undefined for uncontrolled components.

### ISSUE THREAD

**Issue by nghiepit** [mantinedev/mantine#484]
Please provide following information:
- What package has an issue (@mantine/core, mantine/hooks or other)? **3.3.2**
- What package version are you using? **Yarn**
- In which browser and operating system issue occurred? **Chrome and macOS**
- If possible please attach link to codesandbox with reproduced issue
https://codesandbox.io/s/admiring-meninsky-gytjc?file=/src/App.tsx

From 3.3 when to use Select without set value/defaultValue
> Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.

**Comment by rtivital** [comment]
Thanks for reporting, we will fix this issue in next patch

**Comment by rtivital** [comment]
Fixed in 3.3.3
