### ISSUE TITLE
Component "title" font not being set by global config

### ISSUE THREAD

**Issue by mmorley0395** [mantinedev/mantine#4843]
### What package has an issue

@mantine/core

### Describe the bug

I have a global theme file, which contains my default font, colors, etc. It works, for things like button text, but for components with an internal title, such as drawer or modal, the title font is unaffected by the config file. I've set it as roboto, which is a sans serif font, but in the drawer, the title shows up as a serif font. 

mantineTheme.js
```export const themeConfig = {
  colorScheme: "dark",
  primaryColor: "blue",
  fontFamily: "Roboto, sans-serif",
  fontFamilyMonospace: "Roboto, sans-serif",
  headings: {
    fontFamily: "Roboto",
  },
  components: {
    Button: {
      defaultProps: {
        // variant: "gradient",
        variant: "outline",
        size: "xs",
        color: "gray",
        radius: "md",
      },
    },

    Switch: {
      defaultProps: {
        size: "xs",
        onLabel: "ON",
        offLabel: "OFF",
      },
    },
    Drawer: {
      defaultProps: {
        position: "left",
      },
    },
  },
};
```

![image](https://github.com/mantinedev/mantine/assets/77309089/bb5ea00b-adde-430e-8fbf-3727262b07b9)

Screenshot shows an empty drawer with the word "Projects" which should be a sans-serif roboto font, but is an unknown serif font. 

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.19

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
It works correctly on codesandbox – https://codesandbox.io/s/modest-pine-f7cdkz?file=/src/App.tsx
Make sure that you are loading Roboto font on your website. The font can be loaded with Google fonts – https://fonts.google.com/specimen/Roboto

**Comment by mmorley0395** [comment]
Adding withGlobalStyles to my Mantine Provider tag fixed the issue. 

```
export default function App() {
  const [draw, setDraw] = useState(null);
  const [connectionType, setConnectionType] = useState("bike");

  return (
    <MantineProvider theme={themeConfig} withGlobalStyles>
      <div className="parent">
        <HeaderSimple
          connectionType={connectionType}
          setConnectionType={setConnectionType}
        />
        <AnalyzeButton draw={draw} />
        <MapboxMap setDraw={setDraw} connectionType={connectionType} />
      </div>
    </MantineProvider>
  );
}
```
