### ISSUE TITLE
Unable to change the size of chevron in Accordion component

### ISSUE THREAD

**Issue by aliazlanpro** [mantinedev/mantine#4846]
### What package has an issue

@mantine/core

### Describe the bug

I’m unable to change the size of the chevron in the Accordion component. I have used the css module and inline styling options but both of them are not working.

```javascript
<Accordion chevronPosition=“right” variant=“separated” chevron={<IconCircleChevronRight style={{color: ‘blue’}} className={classes.largeicon} />}>
{items}
</Accordion>
``` 
The color of the chevron changes as required, but the size remains same.
The `Accordion.module.css` file is:
```css
.largeicon {
     width: rem(20px);
height : rem(20px);
}
``` 

i also tried the inline styling but it also didn’t work:
```javascript
<Accordion chevronPosition=“right” variant=“separated” chevron={<IconCircleChevronRight style={{color: ‘blue’, height: rem(80), width: rem(80) }} />}>
{items}
</Accordion>
``` 

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Make sure that the size of the icon is synced with `chevronSize` prop. For example:

```tsx
<Accordion chevronSize={80} chevron={<IconCircleChevronRight style={{ height: rem(80), width: rem(80) }} />}>
</Accordion>
```

**Comment by rtivital** [comment]
https://codesandbox.io/s/nervous-mountain-85fjdy?file=/src/App.tsx
