### ISSUE TITLE
theme.variantColorResolver - `hover-color` needed

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#4849]
### What package has an issue

@mantine/core

### Describe the bug

Hi.
I'm in the process of figuring out how variantColorResolver works
And I don't see any example to change text color on hover.
In v6 I made some hardcode like this

```ts


export function getButtonVariantStyles({
  variant,
  theme,
  color,
  gradient,
}: GetVariantStyles): CSSObject | null {
  if (!variant || !BUTTON_VARIANTS.includes(variant)) {
    return null;
  }

  const getThemeVariant = themeVariant(theme);

  const colors = getThemeVariant({ color, variant, gradient });
  const hoverColors = colors.hover ?? {};

  if (variant === 'gradient') {
    return {
      border: 0,
      backgroundImage: colors.background,
      color: colors.color,
      ...theme.fn.hover({ backgroundSize: '200%' }),
    };
  }

  return {
    border: `${rem(1)} solid ${colors.border}`,
    backgroundColor: colors.background,
    color: colors.color,
    ...theme.fn.hover({
      backgroundColor: hoverColors.background ?? undefined,
      color: hoverColors.color ?? undefined,
      borderColor: hoverColors.border ?? undefined,
    }),
  };
}
```

So, How you see I was able to declare text, border and background colors on default and hover states, but now if I'm not missing something, it is possible to change just background.

My fr is to add at least posibility to change the same props but on hover state. If it is hard to do - at least text color, because this is the common case with high/low contrast backgrounds

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

```ts

interface RequiredBaseProps {
  background: string;
  color: string;
  border: string;
}

interface VariantColorResolverResult extends RequiredBaseProps {
  hover: string | Pick<RequiredBaseProps, 'background'> & Omit<Partial<RequiredBaseProps>, 'background'>;
}

```

This avoids breaking changed with current implementation
So, if user wants to add hover values - needed to pass a string value (resolved for background), or and object with at least `background` prop required (this is helpfull in most cases when you don't want to duplicate all props)

Of course, at the component level you also need to handle this values in variables and styles

**Comment by 7iomka** [comment]
In v6 in code that I provided that is `themeVariant` function code
https://gist.github.com/7iomka/4dfd93afec586423c0f0cb4fc75b75dd#file-theme-color-variant-ts
And it makes my hair stand on end to see how to port it all over to v7.

**Comment by rtivital** [comment]
I'll add an option to change buttons color when hovered in one of the next patches

**Comment by 7iomka** [comment]
@stasa-87 my proposal was to support for the same props for hover and to make part of it optional.
```ts
interface RequiredBaseProps {
  background: string;
  color: string;
  border: string;
}

interface VariantColorResolverResult extends RequiredBaseProps {
  hover: string | Pick<RequiredBaseProps, 'background'> & Omit<Partial<RequiredBaseProps>, 'background'>;
}
```

if @rtivital will made this - you'll be able to customise this in your variants once.

**Comment by 7iomka** [comment]
> it looks like some temporary solution for me what if i want on hover to decrease the width/height on all buttons with 10px based on their current size? he has to add support for width and height properties but i can contiune with more and more props also i may need it on focus or with any other pseudo-class or even combination of them this way it is not possible to support all props and pseudo-classes i think whatever hi does it can't be as flexible as the previous css in js

Partially I agree with you, but, variants are based on pre-defined css variables on component mantine styles, which is different from cssinjs.
So, the main goal for this proposal is to add at least base and common needed units that available in default state also for hover state.
Rest of ideas, badly, you need to handle somehow at module css level by adding by your side needed css vars in style tag on the root element, based on props that you need, as well as data attributes, then use it in css module.
Yes, it is a nightmare for new users, but, in most cases it is possible.

**Comment by rtivital** [comment]
Added in 7.2.0
