### ISSUE TITLE
Warning: validateDOMNesting(...): <p> cannot appear as a child of <tbody>.

### ISSUE THREAD

**Issue by CoderJaez** [mantinedev/mantine#4850]
### What package has an issue

@mantine/core

### Describe the bug

I am having a warning on the table. 

![image](https://github.com/mantinedev/mantine/assets/27282828/61c6f9b2-b4b5-4be3-9d0f-ce0023475bd3)

Heres the code 
""""
 <Container fluid p="lg">
      <Card shadow="sm" p="md" radius="sm" withBorder>
        <Card.Section>
          <Title order={2} p="sm">
            Classrooms
          </Title>
        </Card.Section>
        <Table>
          <Table.Thead>
            <Table.Tr>
              <Table.Th>Room No</Table.Th>
              <Table.Th>Occupied</Table.Th>
              <Table.Th>Created At</Table.Th>
              <Table.Th>Updated At</Table.Th>
              <Table.Th>Action</Table.Th>
            </Table.Tr>
          </Table.Thead>
          <Table.Tbody>
            {!loading ? (
              classrooms.map((element) => (
                <Table.Tr key={element._id}>
                  <Table.Td>{element.roomNo.toUpperCase()}</Table.Td>
                  <Table.Td>
                    {element.isOccupied ? "Occupied" : "Vacant"}
                  </Table.Td>
                  <Table.Td>
                    {moment(element.createdAt.toString()).format(
                      "MM DD, YYYY hh:mm:ss a",
                    )}
                  </Table.Td>
                  <Table.Td>
                    {moment(element.updatedAt.toString()).format(
                      "MM DD, YYYY hh:mm:ss a",
                    )}
                  </Table.Td>
                  <Table.Td>hello</Table.Td>
                </Table.Tr>
              ))
            ) : (
              <Text>Loading</Text>
            )}
          </Table.Tbody>
        </Table>
      </Card>
    </Container>
""""

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

"@mantine/core": "^7.0.0",

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please send a sandbox with a minimal reproduction

**Comment by wuifdesign** [comment]
the problem is our "Loading". You can't just write insite a tbody, this is incorrect html syntax.

And also you are missing a `Table` element.

```
<Table>
  <Table.Thead>
    <Table.Tr>
      <Table.Th>Room No</Table.Th>
      <Table.Th>Occupied</Table.Th>
      <Table.Th>Created At</Table.Th>
      <Table.Th>Updated At</Table.Th>
      <Table.Th>Action</Table.Th>
    </Table.Tr>
  </Table.Thead>
  <Table.Tbody>
    {!loading ? (
      classrooms.map((element) => (
        <Table.Tr key={element._id}>
          <Table.Td>{element.roomNo.toUpperCase()}</Table.Td>
          <Table.Td>
            {element.isOccupied ? "Occupied" : "Vacant"}
          </Table.Td>
          <Table.Td>
            {moment(element.createdAt.toString()).format(
              "MM DD, YYYY hh:mm:ss a",
            )}
          </Table.Td>
          <Table.Td>
            {moment(element.updatedAt.toString()).format(
              "MM DD, YYYY hh:mm:ss a",
            )}
          </Table.Td>
          <Table.Td>hello</Table.Td>
        </Table.Tr>
      ))
    ) : (
      <Table.Tr>
        <Table.Td colSpan={5}>Loading</Table.Td>
      </Table.Tr>
    )}
  </Table.Tbody>
</Table>
```

**Comment by rtivital** [comment]
Thanks @wuifdesign!

**Comment by CoderJaez** [comment]
Thanks @wuifdesign.
