### ISSUE TITLE
Nested elements have styles overridden by parents

### ISSUE THREAD

**Issue by rossmeredith** [mantinedev/mantine#4859]
### What package has an issue

@mantine/core

### Describe the bug

I've noticed one example:

1. A non-fluid container nested within a fluid container is fluid.

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in [7.1.1](https://github.com/mantinedev/mantine/releases/tag/7.1.1)
