### ISSUE TITLE
Tabs - it does not work

### ISSUE THREAD

**Issue by bajoski34** [mantinedev/mantine#486]
- @mantine/core: using the the Tabs comp
-  3.2.3
- I macOS and Chrome
- nope
- sure

**Comment by rtivital** [comment]
I see that Tabs component works in documentation – https://mantine.dev/core/tabs/
Please provide code or sandbox where tabs do not work

**Comment by bajoski34** [comment]
it works on the sandboxes but for some reason. the value does not change when the next tab is pressed.
@rtivital

**Comment by rtivital** [comment]
I cannot tell more without issue reproduction, maybe this is an issue with your environment?

**Comment by bajoski34** [comment]
this works. thanks @rtivital
