### ISSUE TITLE
Styles do not load through SSR

### ISSUE THREAD

**Issue by jamesporl** [mantinedev/mantine#4863]
### What package has an issue

@mantine/core

### Describe the bug

I installed the latest [Mantine Next App template](https://github.com/mantinedev/next-app-template) and loaded it in the browser with **disabled javascript**. The styles do not load.

<img width="793" alt="Screenshot 2023-09-25 at 2 35 38 PM" src="https://github.com/mantinedev/mantine/assets/10388757/3d80b339-c69f-495d-bafb-233e53afc062">

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Styles are loading correctly, you just do not have color scheme set. If you need to support applications without javascript support, you will need to set `data-mantine-color-scheme="light"` on `html` attribute during server side rendering.

**Comment by jamesporl** [comment]
Worked like a charm. Thanks for the prompt help there!
