### ISSUE TITLE
Drawer target no longer supported in v7

### ISSUE THREAD

**Issue by chrisbendel** [mantinedev/mantine#4871]
### What package has an issue

@mantine/core

### Describe the bug

After upgrading to v7, the `Drawer.Root` component seems to be missing the `target` prop. I was previously rendering this drawer inside of a smaller component. Without this option it just defaults to rendering to the body.

I can't seem to find anything in the documentation or changelog about this change, wondering if it was missed or intentionally removed - or perhaps there is an alternative that I am not seeing in the documentation.

Thanks so much in advance!

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.1-alpha.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Add the target property back and allow the drawer to render to a different target

**Comment by rtivital** [comment]
You can add props to the Portal component with `portalProps`, for example, `portalProps={{ target: '#your-element' }}`

**Comment by chrisbendel** [comment]
Thanks @rtivital for the super speedy response

I created a quick PR to add this to the changelog file #4872 4872
