### ISSUE TITLE
No styles for DatePicker, Calendar, DatePickerInput and so on

### ISSUE THREAD

**Issue by MakeItLonger** [mantinedev/mantine#4874]
### What package has an issue

@mantine/dates

### Describe the bug

If you try to use examples from documentaion all connected with datePicker you don't have any styles in UI.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.1

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
You did not import styles `import '@mantine/dates/styles.css';`
