### ISSUE TITLE
SegmentedControl indicator is not initially aligned correctly inside a modal

### ISSUE THREAD

**Issue by heloineto** [mantinedev/mantine#4878]
### What package has an issue

@mantine/core

### Describe the bug

Hi there. It appears that the initial position of the SegmentedControl indicator is a bit off when the component is inside a Modal that is initially closed.

Preview image:
![image](https://github.com/mantinedev/mantine/assets/52178665/63cd61a1-3974-446a-b2fa-6b13340469e5)

I encountered this issue when upgrading my code from 6.x.x to 7.0.1

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-issue-segmentedcontrol-indicator-is-not-initially-aligned-correctly-inside-a-modal-l595g2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
See https://github.com/mantinedev/mantine/issues/3330

**Comment by jt561** [comment]
Do we know what was changed between v6 and v7 to cause this? If it was fine in v6 then surely it should also be fine in v7 unless there is a bug? @rtivital

**Comment by rtivital** [comment]
It always worked this way, the original issue is for version 5.x. There were no changes between 6 -> 7 to this logic.

**Comment by jt561** [comment]
I don't believe that's completely true. The OP mentioned that this occurred to him after migrating from v6 to v7 and I can vouch for him because my application using v6 has segmented controls in modals that work fine but after I migrated to v7, this issue started to occur which is why I am confused and have a feeling that it might be a bug. Apologies if I am wrong

**Comment by jt561** [comment]
I personally think this is worth looking into. Might be an issue within Modal or Segmented Controls itself.

**Comment by rtivital** [comment]
It is the issue described in the issue, to solve that set key on SegmentedControl

**Comment by jt561** [comment]
I understand. And don't worry, I don't want to stress you out about this. I have implemented the 'key' solution you suggested. I was just wondering why I didn't need it previously.

Thanks!
