### ISSUE TITLE
useColorScheme doesn't initialize with browser's preferred color scheme

### ISSUE THREAD

**Issue by Bastian** [mantinedev/mantine#4888]
### What package has an issue

@mantine/hooks

### Describe the bug

When calling the `useColorScheme` hook without providing an initial value, it always starts with `'light'`. This behavior is anticipated with SSR, but it also happens on the client side.

Reproduction Steps: 
1. Set your preferred color scheme to dark.
2. Visit the provided Code Sandbox link.
3. Observe the output in the console. Initially, it will log "light" followed by "dark".

https://github.com/mantinedev/mantine/assets/5033001/f6e3b406-4a83-42d8-9d12-8225dd6ade76

This implicitly also affects the `useComputedColorScheme` hook which requires a default value to be set.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-color-scheme-bug-gzkrsy?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

#### Cause of the Problem

The problem is caused by the `useColorScheme` hook, which always sets an `initialValue` boolean value when calling the `useMediaQuery` hook:

https://github.com/mantinedev/mantine/blob/f6f93081f28fc30cd8dce3936ced74780fcec884/src/mantine-hooks/src/use-color-scheme/use-color-scheme.ts#L4

The `useMediaQuery` hook then initializes its state with the provided initial value and later updates it within a `useEffect` call:

https://github.com/mantinedev/mantine/blob/f6f93081f28fc30cd8dce3936ced74780fcec884/src/mantine-hooks/src/use-media-query/use-media-query.ts#L42-L44 https://github.com/mantinedev/mantine/blob/f6f93081f28fc30cd8dce3936ced74780fcec884/src/mantine-hooks/src/use-media-query/use-media-query.ts#L23-L26 

#### Suggested Fix

There are two possible fixes I can think of:

1. Modify the `useColorScheme` hook to only set an `initialValue` when its own `initialValue` is provided:
   ```ts
   export function useColorScheme(initialValue?: 'dark' | 'light', options?: UseMediaQueryOptions) {
     return useMediaQuery('(prefers-color-scheme: dark)', initialValue ? initialValue === 'dark' : undefined, options)
       ? 'dark'
       : 'light';
   }
   ```

2. Update the logic in the `getInitialValue` helper function to not return the initalValue. To me, this seems like the logical behavior since the `getInitialValueInEffect` property can be used to control this behavior. However, I'm uncertain about the potential side-effects this change might introduce for other consumers of the `useMediaQuery` hook.

Regardless of the solution chosen, the `defaultValue`parameter of the `useComputedColorScheme` hook should be made optional.

**Comment by rtivital** [comment]
'light' is the default value. It is the default to prevent unexpected color scheme switches if you develop the website only for one color scheme. If you want the color scheme to have the same value as your OS, set `defaultColorScheme="auto"` both on `MantineProvider` and `ColorSchemeScript` – https://mantine.dev/theming/color-schemes/#default-color-scheme.

I'll add more documentation about the `auto` option in one of the next releases, but apart from that, there are no changes planned regarding this logic.

**Comment by rtivital** [comment]
It is designed behavior to prevent hydration mismatches. You should not access color scheme value to render content or change props based on this value. You can read more about this here – https://mantine.dev/theming/color-schemes/#color-scheme-value-caveats

**Comment by rtivital** [comment]
But this applies only to the ssr, if you do not have this, you can use color scheme value any way you like

**Comment by Bastian** [comment]
The flickering also happens without SSR. See the Codesandbox example from before, it's flickering and it is not using SSR.

**Comment by c0nd3v** [comment]
This is still a problem for me
