### ISSUE TITLE
Combobox Select examples attempt to submit form

### ISSUE THREAD

**Issue by Yhprum** [mantinedev/mantine#4889]
### Link to the page where something nasty is located

https://mantine.dev/combobox/?e=BasicSelect

### Exact quote of what is wrong

If you include the example Combobox Select inside a form, clicking the input to open the dropdown submits (or attempts to submit) the form. 

Tried with BasicSelect and SelectOptionComponent and got same results. Put the component in it's own file, the first one works as expected but the second one breaks.

    <div>
      <CustomSelect />
      <form>
        <CustomSelect />
      </form>
    </div>

### Are you willing to create pull request with the fix?

None

**Comment by rtivital** [comment]
Set type="button" on the button element of your input to prevent from submitting forms

**Comment by Yhprum** [comment]
Confirmed working for me, thanks!
