### ISSUE TITLE
closeButtonProps missing from NotificationsProps type

### ISSUE THREAD

**Issue by noahsb** [mantinedev/mantine#4893]
### What package has an issue

@mantine/notifications

### Describe the bug

`NotificationsProps` has a prop `closeButtonProps` on the `<Notification>` component but it is not found in `NotificationsProps` type

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/red-voice-9458zt?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by noahsb** [comment]
Looks like the export moved from `@mantine/notifications` to `@mantine/core` which works fine. Closing this as a non-issue

**Comment by Intaria** [comment]
@mantine/core contain Notification component, not Notification**s**
