### ISSUE TITLE
Select dropdown can't open

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4895]
### What package has an issue

@mantine/core

### Describe the bug

In my project, the select component didn't work, and when I switched the Drawer to mantine's drawer, it worked.

Normally, there is another div under role="combobox" to display the dropdown list, but I don't have it in my project, but in the demo, there is.
I don't know what's causing this.

<img width="1470" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/77379d2b-1e9f-4e0a-a141-badcb82dea89">

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.19

### If possible, please include a link to a codesandbox with the reproduced problem

https://stackblitz.com/edit/react-5oxgip?file=demo.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
<img width="830" alt="Снимок экрана 2023-09-28 в 09 47 17" src="https://github.com/mantinedev/mantine/assets/10353856/486b5934-3c0a-4e9b-a52e-39e57a60ff45">

The dropdown in the sandbox is displayed correctly

**Comment by vaynevayne** [comment]
In my project, the select component didn't work, and when I switched the Drawer to mantine's drawer, it worked.

Normally, there is another div under role="combobox" to display the dropdown list, but I don't have it in my project, but in the demo, there is.
I don't know what's causing this.

**Comment by rtivital** [comment]
If you can reproduce the issue on codesandbox, I can take a look. Otherwise, I cannot really help without a reproduction.

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction
