### ISSUE TITLE
Select wont submit form when hitting enter

### ISSUE THREAD

**Issue by christoferolaison** [mantinedev/mantine#4896]
### What package has an issue

@mantine/core

### Describe the bug

Making a `Select` searchable wont submit the form when hitting enter within the input if the form is using the form attribute.

[_"The form attribute lets you place an input anywhere in the document but have it included with a form elsewhere in the document."_](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.21

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-select-form-submit-dkyvsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Supplying [`form` prop](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/Select/Select.tsx#L121) to InputBase could potentially fix this issue

**Comment by msv96** [comment]
I think this is the correct behavior as we need to select the option from dropdown when searchable prop is true.
Better you can create your custom Select dropdown with search using ComboBox.

**Comment by christoferolaison** [comment]
No, correct behaviour would be to submit the form when enter is pressed. I mean it do work if the input is rendered within a form, see sandbox. To make a form that are using the form attribute behave as a form that has its controls rendered within it we need to add the form attribute to the input. 

See screen recording for an example.

https://github.com/mantinedev/mantine/assets/6023146/fb828828-9c81-43e5-82b5-e0ba256612c4

**Comment by rtivital** [comment]
Select component works as intended – the Enter key submits the form only when the dropdown is closed. When the dropdown is opened, the Enter key is used to select the value. It is not planned to change this behavior.

**Comment by christoferolaison** [comment]
> Select component works as intended – the Enter key submits the form only when the dropdown is closed

@rtivital Can you please try the sandbox. When using the form attribute Enter key wont submit the form even though the dropdown is closed. If you compare the two forms in https://codesandbox.io/s/mantine-select-form-submit-dkyvsx they don't behave in the same. The form under "A form using the form attr (this wont submit when hitting enter from the Select)" doesn't submit when dropdown is closed. When the form gets submitted you should have a console.log in the console. 

I don't think this one should be closed.

**Comment by rtivital** [comment]
The form submits correctly – https://codesandbox.io/s/bold-euler-h6drl5
If the form does not submit when form attr is set, then just do not set it.
`form` and `name` attributes of Select component are added to the hidden input to allow uncontrolled behavior usage. This behavior is not planned to be changed as well.

**Comment by christoferolaison** [comment]
> The form submits correctly – https://codesandbox.io/s/bold-euler-h6drl5
Yes, and I have not said anything else

> If the form does not submit when form attr is set, then just do not set it.
I need to set it because my form controls lives outside of the form element. Read this section: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#form on what the form attribute is used for. 

Then try this - https://codesandbox.io/s/quizzical-kowalevski-hgzvjt?file=/src/App.tsx . It's a fork from yours but the form doesn't wrap the form control in this case. Instead it is using the from attribute to associate the Select with the form element.
