### ISSUE TITLE
MantineProvider was not found in component tree

### ISSUE THREAD

**Issue by ManishaSwain8** [mantinedev/mantine#4898]
### What package has an issue

@mantine/core

### Describe the bug

I was trying to add SegmentedControl component , but it gives an error of  **MantineProvider was not found in component tree** even after using 
npm i @mantine/core.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

"@mantine/core": "^7.0.2",     "@mantine/hooks": "^7.0.2"

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is required to wrap your application with MantineProvider component. You can learn more about how to set up Mantine on the getting started page – https://mantine.dev/getting-started/

**Comment by ManishaSwain8** [comment]
@rtivital Got it thanks!😅
