### ISSUE TITLE
ScrollArea.AutoSize is showing vertical scrollbar background on hover

### ISSUE THREAD

**Issue by KaivG** [mantinedev/mantine#4904]
### What package has an issue

@mantine/core

### Describe the bug

The bug can be seen on the example page: https://mantine.dev/core/scroll-area/#scrollareaautosize-with-popover

When the Popover.Dropdown opens it appears with a vertical Scrollbar as wanted. However, when you hover over the last item on the bottom of dropdown, the background gray color of a horizontal scrollbar appears and covers the content in that area.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.02

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/scroll-area/#scrollareaautosize-with-popover

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Fixed in [7.3.1](https://github.com/mantinedev/mantine/releases/tag/7.3.1)
