### ISSUE TITLE
TypeScript Key Prop Type Error

### ISSUE THREAD

**Issue by ayuhito** [mantinedev/mantine#4906]
### What package has an issue

@mantine/core

### Describe the bug

Ever since migrating to Mantine V7, a multitude of components I use that just pass their props with a spread operator show a type error particularly on the key property.

```tsx
// ExampleComponent.ts
import type { SliderProps } from '@mantine/core';
import { Slider as MantineSlider } from '@mantine/core';

const Slider = (props: SliderProps) => <MantineSlider {...props} />;

export { Slider };
```

![image](https://github.com/mantinedev/mantine/assets/38220115/286126b5-dbd7-4a54-bba7-cab1967407f8)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

mantine@7.1.0, react@18, typescript@5.2.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
I cannot reproduce this error on codesandbox – https://codesandbox.io/s/jovial-cdn-r7xc5g?file=/src/App.tsx
Can you provide a reproduction?

**Comment by ayuhito** [comment]
I can't reproduce it, unfortunately. I tried CodeSandBox and Codespaces for reproductions, and also changing my `tsconfig.json`  to match the templates or updating all type packages (both locally and in repros) with no luck. I want to blame my IDE but a quick dry run with `tsc --noEmit` also leads to the same error which means it could be somewhere else. 

For now, I'll workaround with `@ts-expect-error` since I can still compile it with Remix v1. But maybe we can reopen this if other users end up experiencing this.
