### ISSUE TITLE
Controlled Select not working with searchable

### ISSUE THREAD

**Issue by baba43** [mantinedev/mantine#4909]
### What package has an issue

@mantine/core

### Describe the bug

I want to migrate this code from Mantine 6 to Mantine 7:

```
const [value, setValue] = useState("React");
return (
    <Select
      value={value}
      onChange={(value) => setValue(value || "")}
      data={["React", "Angular", "Svelte", "Vue"]}
      searchable
    />
);
```

In Mantine 6 this worked as expected, but with Mantine 7 (latest release) it is impossible to enter a search value because the component is overwriting the search with `value` on every render.

Now I am not sure if this is a bug or if this is on purpose and I have do something else.

Thanks for any help!

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by baba43** [comment]
@noahsb arg, looks very verbose just to get a prop working.

However, thank you very much for pointing that out.

If this behaviour stays at it is, I think it should be added to the documentation that `searchable` is not working in controlled mode.

**Comment by wuifdesign** [comment]
i think searchable should work, its just a bug. having the same issue currently

**Comment by wuifdesign** [comment]
i created a PR for this issue: https://github.com/mantinedev/mantine/pull/4915
