### ISSUE TITLE
[Feature Request] Radius on Modal props

### ISSUE THREAD

**Issue by ruessej** [mantinedev/mantine#491]
I don't know if this is intentional that it's not there, but I would like to change the radius of my modal

**Comment by rtivital** [comment]
You can set modal border radius with Styles API:
```tsx
<Modal styles={{ modal: { borderRadius: 40 } }} />
```

**Comment by rtivital** [comment]
I think we can add it, leaving this for community to contribute

**Comment by snehilvj** [comment]
Hi @rtivital raised a PR for this..

**Comment by rtivital** [comment]
Feature is merged and will be available in next minor release

**Comment by rtivital** [comment]
Released in 3.4.0
