### ISSUE TITLE
Spoiler adds margin bottom when "Show more" is hidden

### ISSUE THREAD

**Issue by Jacouille** [mantinedev/mantine#4910]
### What package has an issue

@mantine/core

### Describe the bug

The Spoiler component adds a margin-bottom, which I understand is for the "Show more" button. However, when the button isn't shown, the margin-bottom is still there and it uses space.

![image](https://github.com/mantinedev/mantine/assets/49291068/29433a05-26ce-4637-8782-64f60eb9748d)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Remove the margin-bottom when the spoiler button isn't shown.

**Comment by MA-MacDonald** [comment]
It looks like the change happened in 7.01
https://github.com/mantinedev/mantine/issues/3183

+1 for removing the margin-bottom when the spoiler button isn't shown.
