### ISSUE TITLE
NumberInput bug on Smaprtphone

### ISSUE THREAD

**Issue by Kenzo-Wada** [mantinedev/mantine#4912]
### What package has an issue

@mantine/core

### Describe the bug

- When entering a number in NumberInput, the input value becomes incorrect if you input more than two digits on a smartphone using japanese keyboard. Specifically, it occurs in the following way:

10 -> 11010
23 -> 22323

- Olso, is entering number larger than 1111111111111111, the rest of the number will become 0. (ex. 1111111111111111200000000000). when this occurs, increment or decrement will now work at all. this occurs not only japanese keyboard.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

There is a possibility that there may be something wrong with the event handler or state management, so those should be corrected. Additionally, it might be worthwhile to consider whether the NumberInput should really have type="number" as the default.

**Comment by Kenzo-Wada** [comment]
this only happens on japanese keybord...

**Comment by saeidalidadi** [comment]
This issue also exists on all devices. numbers with a length of 16 digits and more have this issue.
I can work on this if.

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix if #4916 does not resolve the issue

**Comment by saeidalidadi** [comment]
#4916 fixes this one too.

**Comment by rtivital** [comment]
Great, thanks!
