### ISSUE TITLE
Drawer animation direction doesn't change in rtl

### ISSUE THREAD

**Issue by PPHelios** [mantinedev/mantine#4917]
### What package has an issue

@mantine/core

### Describe the bug

Hi,
opening the drawer in while in rtl makes the opening animation starts from left to right , you can easily reproduce it on the mantine drawer website , change layout to rtl and open the drawer in the examples.

i used:
 `  @mixin rtl{
     transform-origin: right center !important;
  transform: translateX(0px)!important; 
  }`
 on the drawer content className as a temporary fix.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

changing the transform animation values while in rtl

**Comment by rtivital** [comment]
Fixed in [7.1.1](https://github.com/mantinedev/mantine/releases/tag/7.1.1)
