### ISSUE TITLE
NextJS vanilla extract: Document not defined

### ISSUE THREAD

**Issue by BengtHagemeister** [mantinedev/mantine#4922]
### What package has an issue

@mantine/vanilla-extract

### Describe the bug

When using mantine in combination with NextJS (pages) and vanilla extract, the following error is throwing:

`
./src/styles/Demo.css.js
NonErrorEmittedError: (Emitted value instead of an instance of Error) ReferenceError: document is not defined
`

Similar (or the same??) issue is also described here: https://github.com/vanilla-extract-css/vanilla-extract/issues/1043#issuecomment-1733631588

Reproducing the issue is possible by running the server and opening the start page.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://github.com/BengtHagemeister/mantine-next-vanilla-extract-document-bug

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
The issue, as you pointed out, is with Vanilla Extract, not Mantine, you can track the progress in Vanilla Extract repository. The fix for this issue cannot be implemented on Mantine side.

**Comment by tobysmith568** [comment]
For those who are still finding this issue, I have found I can get around it by adding the Next.JS "app directory" to my project - even if I don't then use it.

(See this reply to this thread](https://github.com/vanilla-extract-css/vanilla-extract/issues/1043#issuecomment-2403661469)
