### ISSUE TITLE
Is there any function like form.insertListItem() for inserting validation, such as form.insertListItemValidation()?

### ISSUE THREAD

**Issue by shiam-technext** [mantinedev/mantine#4924]
### Link to the page where something nasty is located

https://mantine.dev/form/nested/#nested-arrays

### Exact quote of what is wrong

Form Validation code:

```
const form = useForm({
    initialValues: {
      employees: [{ name: '', job: '' }],
    },
    validate: {
      employees: [{ name: hasLength({ min: 2, max: 10 }, 'Name must be 2-10 characters long'), job: isNotEmpty('Enter your current job') }],
    },
  });
```
We could insert items by:

`form.insertListItem('employees', { name: '', job: '' })`

But is there any function to add validation for this item like:

`form.insertListItemValidation('employees', { name: isNotEmpty('This field is required'), job: isNotEmpty('This field is required') })`

### Are you willing to create pull request with the fix?

None

**Comment by rtivital** [comment]
Please use GitHub Issues to report bugs. To request features or ask questions, please use GitHub Discussions. Please do not duplicate your question/feature request in multiple places.

To answer your questions: no, use-form hook does not provide such feature.
