### ISSUE TITLE
Mantine 7 increases the bundle size of NextJS substantially

### ISSUE THREAD

**Issue by iampava** [mantinedev/mantine#4926]
### What package has an issue

@mantine/core

### Describe the bug

I noticed a HUGE difference in the loaded JS for a NextJS app that uses Mantine 7.

Here's 2 screenshots of the same Next build. Notice the JS is increased by

* 140kb gzipped JS
* more than 500kb minified JS

<img width="1053" alt="no-mantine" src="https://github.com/mantinedev/mantine/assets/11327761/36b763fa-265c-4649-82f0-f0f8e404fe38">
<img width="1052" alt="mantine" src="https://github.com/mantinedev/mantine/assets/11327761/c85438c8-8eb3-4c82-bb61-5a65ac7138d9">

---

The only difference between the 2 screenshots is the wrapping of `<MantineProvider>`, like so:

```jsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-mantine-color-scheme="dark">
      <body className={inter.className}>
        <MantineProvider defaultColorScheme='dark'>
          {children}
        </MantineProvider>
      </body>
    </html>
  )
}
```

More details:
* NextJS version: 13.5.3
* the app is just the normal one created after running `npx create-next-app@latest`. Nothing extra. I followed all the default prompts from NextJS wizard, so it has Tailwind

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
It is a known issue with Next.js – https://github.com/vercel/next.js/issues/49742
Basically, tree shaking does not work with app router, it works correctly with pages router and all other frameworks. We cannot provide fix on our side – it is an issue with Next.js bundler.

**Comment by iampava** [comment]
Got it. Thanks for the answer and for the library. Really awesome!

**Comment by DenisBessa** [comment]
I think the experimental option `optimizePackageImports` solves this. But it does not work with libraries with components marked as "use client" yet. See https://github.com/vercel/next.js/pull/56020

**Comment by BengtHagemeister** [comment]
There is some explanation for `optimizePackageImports` here: https://nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports

They do write: 

> Libraries like @mui/icons-material, @mui/material, date-fns, lodash, lodash-es, react-bootstrap, @headlessui/react, @heroicons/react, and lucide-react are already optimized by default.


I quickly tested `react-bootstrap` and they don't seem do have a problem with tree shaking. I had a very quick glance into both packages and the only obvious difference is the use of `"use client";`. `@mantine/core` has only one `"use client";` in index.mjs whereas `react-bootstrap` puts them into the different components.

I also observed that after manually adding `@mantine/core` to `optimizePackageImports` I get errors referring to missing `"use client";`.

```js
You're importing a component that needs useEffect. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

   ╭─[/Users/code/node_modules/.pnpm/@mantine+core@7.1.0_@mantine+hooks@7.1.0_@types+react@18.0.31_react-dom@18.2.0_react@18.2.0/node_modules/@mantine/core/esm/components/Floating/use-delayed-hover.mjs:1:1]
 1 │ import { useRef, useEffect } from 'react';
   ·                  ─────────
 2 │
 3 │ function useDelayedHover({ open, close, openDelay, closeDelay }) {
 4 │   const openTimeout = useRef(-1);
   ╰────

The error was caused by importing '@mantine/core/esm/index.mjs' in './src/components/elements/Actions/Actions.tsx'.

Maybe one of these should be marked as a client entry with "use client":
  ./src/components/elements/Actions/Actions.tsx
  ./src/components/elements/Page/Page.tsx

./src/components/elements/Actions/Actions.tsx
ReactServerComponentsError:

```

**Comment by rtivital** [comment]
Fixed in 7.1.1, `'use client';` was moved to each component separately instead of `index.js`. Still, tree-shaking works only with `optimizePackageImports` experimental feature. 7.1.1 patch will be published later today.

Config that I've used from next-app-template:

```tsx
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});

module.exports = withBundleAnalyzer({
  reactStrictMode: false,
  eslint: {
    ignoreDuringBuilds: true,
  },
  experimental: {
    optimizePackageImports: ['@mantine/core', '@mantine/hooks'],
  },
});
```

Bundle analyzer results:

7.1.0:
<img width="1276" alt="Снимок экрана 2023-10-02 в 16 38 28" src="https://github.com/mantinedev/mantine/assets/10353856/c13106b3-d5cc-4221-ac78-24e4957ccc3c">

7.1.1:
<img width="1273" alt="Снимок экрана 2023-10-02 в 16 38 50" src="https://github.com/mantinedev/mantine/assets/10353856/521c71e3-2b25-4caf-89cb-b130222b0ddc">

**Comment by BengtHagemeister** [comment]
Maybe its an option to add @mantine/core to the NextJS default optimizePackageImports. I would make a pr against the NextJS repo, I just think it would be more considered if its coming from you @rtivital ;)

See:

https://github.com/vercel/next.js/blob/ecd94c1a4d9f8ca32ac7f8bfac7f22658df70855/packages/next/src/server/config.ts#L708C6-L708C6

and
 
https://github.com/vercel/next.js/blob/ecd94c1a4d9f8ca32ac7f8bfac7f22658df70855/packages/next/src/server/config.ts#L648

**Comment by rtivital** [comment]
You are welcome to submit a PR in Next.js repo. Note that Mantine does not support modularized imports.
