### ISSUE TITLE
[V7] Bug: portalProps doesn't accept className without breaking whole app 

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#4935]
### What package has an issue

@mantine/core

### Describe the bug

<img width="600" alt="image" src="https://github.com/mantinedev/mantine/assets/18473137/b96bfbb9-b074-4c1e-8f08-0457937dde6d">

When I added className in portalProps in Menu component (at least), I have clientside error:
`InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('hidden xl:block') contains HTML space characters, which are not valid in tokens.`

<img width="991" alt="image" src="https://github.com/mantinedev/mantine/assets/18473137/ee905e45-2183-4e74-b6f9-3da7d90bdcb6">

When className is not passed to portalProps, or it doesn't consist any space, error is gone.

This is critical bug or I'm missing something?

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in [7.1.1](https://github.com/mantinedev/mantine/releases/tag/7.1.1)
