### ISSUE TITLE
Menu.Item is not RTL

### ISSUE THREAD

**Issue by CripyIce** [mantinedev/mantine#4936]
### What package has an issue

@mantine/core

### Describe the bug

Menu basically working good on RTL layout except for `Menu.Item`.
Screenshot for example (can also reproduce on `mantine.dev` website when switching to RTL layout):
![image](https://github.com/mantinedev/mantine/assets/26387823/ce35d380-b04a-490d-bca6-e736a812cb9d)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in [7.1.1](https://github.com/mantinedev/mantine/releases/tag/7.1.1)
