### ISSUE TITLE
ScrollAreaViewport child's display:table breaking relative sizing

### ISSUE THREAD

**Issue by wokes** [mantinedev/mantine#4941]
### What package has an issue

@mantine/core

### Describe the bug

https://github.com/mantinedev/mantine/blob/88947083046c2c485b69f3c0ce70e2e326bc09f3/src/mantine-core/src/components/ScrollArea/ScrollAreaViewport/ScrollAreaViewport.tsx#L23
ScrollAreaViewport has a child div that has a rigidly defined style and no class name, making it a pain to override.

In my case, I have an app layout with ScrollArea that accepts pages as children.
The goal is to have a global scroll container, but only vertically, pretty common.
After upgrading to v7 and fixing up all of the styles, I stumbled into a problem with applying width constraints to the content in a ScrollArea. I tracked it down to the div's `display: table` linked above, it prevents its children's width from being set relative to their parent.

I'm sure there's a reason for this particular approach, so no pull request for now.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/nameless-wildflower-rwzcgc?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

It can be rectified by setting that div to `display: block !important` but it seems kinda ugly.
Included in the CSS import in codesandbox.

Options I see:
- Replace `display: table` with something else
- Allow passing style overrides in ScrollAreaViewportProps
- Add a class that can be easily overriden

**Comment by rtivital** [comment]
`display: table` is required for ScrollArea to work in all cases that are provided in the documentation. It is an internal implementation detail that is not supposed to be changed. If you still need to change it, you can use `!important`. It is not planned to provide props to change these styles.
