### ISSUE TITLE
TagsInput IME issue

### ISSUE THREAD

**Issue by a-ryang** [mantinedev/mantine#4946]
### What package has an issue

@mantine/core

### Describe the bug

https://github.com/mantinedev/mantine/assets/105474635/a910c7c9-09de-4151-9d72-5a99e42f4fc7

When using IME languages, pressing 'Enter' will leave the previous character or word behind.
(Korean, Japanese, and Chinese)

A similar issue with the following link:
https://github.com/mantinedev/mantine/issues/1565

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^7.1

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
