### ISSUE TITLE
AppShell hydration error in NextJS

### ISSUE THREAD

**Issue by oconr** [mantinedev/mantine#4949]
### What package has an issue

@mantine/core

### Describe the bug

I am trying to use AppShell within NextJS pages directory and I'm getting a hydration error.

`Error: Hydration failed because the initial UI does not match what was rendered on the server.`

I have tried removing the AppShell and that resolves the error so I know that it's AppShell that's creating the error, and I have have tried testing it with a blank and barebones AppShell and the error still occurs.

Mantine ver: 7.1.0
Next ver: 13.5.3

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Provide a repository with minimal reproduction, it is impossible to tell where the issue is without reproduction.
