### ISSUE TITLE
Popover closes when selecting option from select input

### ISSUE THREAD

**Issue by ShaharIlany** [mantinedev/mantine#4952]
### What package has an issue

@mantine/core

### Describe the bug

When placing Select element inside a Popover element, the selection of option closes the popover

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-popover-select-78lqsr

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

The Select Dropdown is rendered outside the context of the popover (as portal).
I think that the Popover Dropdown detects outside clicks from the Select Dropdown and thinks that the click was outside the context.

On mantine v6 it didn't happend

**Comment by rtivital** [comment]
Set `comboboxProps={{  withinPortal: false }}` – https://codesandbox.io/s/agitated-resonance-z6lm47?file=/src/App.tsx
Documentation will be updated in one of the minor releases to include this.
