### ISSUE TITLE
MultiSelect: incorrect space distribution

### ISSUE THREAD

**Issue by AryamnovEugeniy** [mantinedev/mantine#4954]
### What package has an issue

@mantine/core

### Describe the bug

Hello!

There is an issue with MultiSelect in Mantine v7. There is a big empty space after selected values (possibly, place where placeholder is rendered, but I do not specify a placeholder, so it should not take any space at all):

<img width="305" alt="image" src="https://github.com/mantinedev/mantine/assets/51905811/78a6410e-c12e-4821-af90-c7ecff431d18">
<img width="305" alt="image" src="https://github.com/mantinedev/mantine/assets/51905811/750322db-b882-44f2-9820-71f85a0a0c2a">

Even if I specify a placeholder, I think it should disappear when I select at least one value, but it does not:

<img width="305" alt="image" src="https://github.com/mantinedev/mantine/assets/51905811/0608f32c-a77a-4413-a352-d5ddcb1c716a">

Both of these issues are present in this demo: https://codesandbox.io/s/mantine-forked-klsvqh?file=/src/App.tsx

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-forked-klsvqh?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
The issue has been resolved in [7.1.3](https://github.com/mantinedev/mantine/releases/tag/7.1.3)
