### ISSUE TITLE
CodeHighlightTabs tabs look different since v7.1.1

### ISSUE THREAD

**Issue by hundehausen** [mantinedev/mantine#4955]
### What package has an issue

@mantine/core

### Describe the bug

Since version 7.1.1 the tabs look different. 7.1.2 is affected as well. With 7.1.0 the tab look like on [the website](https://mantine.dev/others/code-highlight/#tabs-with-icons).

**v7.1.0**
![Screenshot 2023-10-03 at 08-13-56 Monero Suite](https://github.com/mantinedev/mantine/assets/25672277/6bc6d849-da24-4d7c-96ba-cd2187ac62ef)

**v7.1.1 and v7.1.2**
![Screenshot 2023-10-03 at 08-18-55 Monero Suite](https://github.com/mantinedev/mantine/assets/25672277/4d6fa6e5-3878-4fb5-921c-77b8c5e2cad1)

The copy button is now orange, but I like this!

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Can you provide a sandbox with a reproduction? I wasn't able to reproduce the issue – https://codesandbox.io/s/hardcore-stonebraker-27yymk?file=/src/App.tsx

**Comment by hundehausen** [comment]
Are you okay with trying my repo? It's a simple Website:

https://github.com/hundehausen/monero-suite

`npm i @mantine/hooks@7.1.0 @mantine/core@7.1.0 @mantine/code-highlight@7.1.0`

`npm i @mantine/hooks@latest @mantine/core@latest @mantine/code-highlight@latest`

**Comment by HoHieuLuc** [comment]
I'm also facing the same issue using the [next-app-min-template](https://github.com/mantinedev/next-app-min-template) template.
Codesandbox: https://codesandbox.io/p/sandbox/mantine-code-highlight-issue-l8h5ny

**Comment by reschandreas** [comment]
Hi @HoHieuLuc !


I had a similar issue some time ago so I thought I'd chime in. I was able to fix it for your sandbox. I simply imported the mantine and code-highlight styles in your `theme.ts` and removed the import in `layout.tsx`. Now it looks as it should, check it out here https://codesandbox.io/p/sandbox/mantine-code-highlight-issue-forked-vcplvt

**Comment by hundehausen** [comment]
I can confirm, this is fixing the problem.
