### ISSUE TITLE
form.getInputProps with select forces select state 

### ISSUE THREAD

**Issue by roee-hersh** [mantinedev/mantine#4961]
### What package has an issue

@mantine/core

### Describe the bug

when using select with @mantine/form:
```
                                <Select
                                    withAsterisk
                                    label="Namespace"
                                    {...form.getInputProps("namespace")}
                                    searchable
                                    clearable
                                    name="namespace"
                                    placeholder="search namespace"
                                    description="namespace to apply"
                                    data={namespaces}
                                />
```
causes the select input to no longer be editable after you assign the first value, which causes the "clearable" and "searchable" attribute not to work at all and the only way to select new value is by manually selecting an option.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

@mantine/core:7.1.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
The issue has been resolved in 7.1.2 – https://codesandbox.io/s/exciting-darkness-5fy7t5?file=/src/App.tsx
