### ISSUE TITLE
Extending useForm's type while using generics does not work

### ISSUE THREAD

**Issue by melihcoban** [mantinedev/mantine#4962]
### What package has an issue

@mantine/form

### Describe the bug

Extending useForm hook's type does not work correctly.

Type of processQuantity is number or undefined.

`selectedItem.setFieldValue('processQuantity', undefined)` or `selectedItem.setFieldValue('processQuantity', 0);` gives error "Argument of type 'undefined' is not assignable to parameter of type '"processQuantity" extends keyof T ? T[keyof T & "processQuantity"] : unknown'"

```
function useProcess<T extends Item>() {
  const selectedItem = useForm<T>({
    initialValues: items.at(0),

    validate: validationSchema ? zodResolver(validationSchema) : undefined,
  });
}
```

I believe that useForm<T> does not extend Item. Using `useForm<T extends Item>` gives '?' expected error. Leaving `useForm<T>` does not allow me to access the properties of the extended type.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.18

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/naughty-haslett-26r9h7?file=/src/form.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Ability to extend generic type of useForm might be able to solve the issue.

**Comment by rtivital** [comment]
If you found a solution for your problem with `useForm<T extends Item>`, why do you need to change it?

**Comment by melihcoban** [comment]
@rtivital `useForm<T extends Item>` is not a solution unfortunately. ESLint gives me `'?' is expected`, and I can't run the code. I tried it in the codesandbox, it gives error as well.

**Comment by rtivital** [comment]
Well, I do not know how to fix the issue and even whether the issue should be fixed (as changes might break existing functionality). You are welcome to explore it and send a PR with a fix.

**Comment by melihcoban** [comment]
Sure, I can take a look at it to see if I can implement it. I will report back if I can come up with a solution.

**Comment by martitv** [comment]
I get the TypeScript error "'T' could be instantiated with an arbitrary type which could be unrelated to '{ insert.my.union.form.type.keys }'" when i try to create a generic form component. Error message is on initialValues.

```
function GenericForm<T extends UnionFormType>(props: GenericFormProps<T>) {
 ...
  const params = useParams();
 
  const form = useForm<T>({
    initialValues: {
      ...props.initialValues,
      $type: props.type,
      otherValue: params.otherValue as string,
      someId: -1,
    },
  });
```
