### ISSUE TITLE
[@mantine/hooks] useTimeout callback not running after state change

### ISSUE THREAD

**Issue by Jacouille** [mantinedev/mantine#4965]
### What package has an issue

@mantine/hooks

### Describe the bug

Setting a state before the useTimeout callback has been called causes the useTimeout to "reset". The callback is not being called.

Very similar to #3789

When comparing with V6 implementation of the useTimeout hook, it looks like we use the callback as a dependency of the internal `useCallback`. [V6](https://github.com/mantinedev/mantine/blob/cdf1179358c6d4591f5de76a2a41935ff4c91ec6/src/mantine-hooks/src/use-timeout/use-timeout.ts#L20) vs [V7](https://github.com/mantinedev/mantine/blob/34e52affc566161481d21e58d9926a9aeb52ec40/src/mantine-hooks/src/use-timeout/use-timeout.ts#L19C21-L19C21)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/funny-snow-nzjv8p

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Simply remove the callback from the dependency of the `useCallback`, just like the V6 implementation.

For the moment, I have to wrap all of my timeout callbacks inside a useCallback and everything works like before. I don't know if this was an intended change in V7

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
