### ISSUE TITLE
DatePicker controlled value not update month page

### ISSUE THREAD

**Issue by israelins85** [mantinedev/mantine#4967]
### What package has an issue

@mantine/dates

### Describe the bug

When controlled value altered the current page don't be updated;

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/intelligent-hermann-v34m83?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

The picker show the correct month page.

**Comment by DoubleJ-G** [comment]
Use the `date` and `onDateChange` prop to control the currently displayed page, this is separate to the `value` and `onChange` props that represent the currently selected value. 

https://codesandbox.io/s/staging-dream-sy2wp4?file=/src/App.tsx

**Comment by israelins85** [comment]
Oh, great. Thanks a lot @DoubleJ-G.
