### ISSUE TITLE
[Bug] PortalProps doesn't apply css vars passed in style prop

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#4974]
### What package has an issue

@mantine/core

### Describe the bug
```tsx
portalProps={{
          style: {
            'color': 'red', // <-- this works
            '--max-height': '100px',  // <-- this not!
          },
}}

```

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is not planned to support CSS variables on Portal element with new implementation, you can apply styles to children elements instead. CSS variables are forbidden by types – https://codesandbox.io/s/infallible-ptolemy-mfwym9?file=/src/App.tsx
