### ISSUE TITLE
Nightmare with css-variables authority

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#4975]
### What package has an issue

@mantine/core

### Describe the bug

On input component you defined css variables not on the root element but on the input element
```css
   --input-height-xs: calc(1.875rem*var(--mantine-scale));
    --input-height-sm: calc(2.25rem*var(--mantine-scale));
    --input-height-md: calc(2.625rem*var(--mantine-scale));
    --input-height-lg: calc(3.125rem*var(--mantine-scale));
    --input-height-xl: calc(3.75rem*var(--mantine-scale));
```
Then, in style tag on input element: `--input-height: var(--input-height-md);` based on size prop.

When I tried to get --input-height value in my custom css styles for `label` element, it not working, because this styles is not defined at the root of page or at the root element of input component, but on the neighbour element.

First step was for me is to use vars resolver

```ts
export const cssVarsResolver: CSSVariablesResolver = (theme) => ({
  variables: {
   // my custom input sizes
    ...Object.keys(inputSizes).reduce((acc, curr) => {
      return {
        ...acc,
        [`--input-height-${curr}`]: inputSizes[curr],
      };
    }, {}),
  },
  light: {},
  dark: {},
});

```
So now I have access to --input-height-md for example, but for input element value is different, because css vars defined on element take precedence, and is impossible to only with vars resolver to override this values.

I need somehow to find a workaround to have re-declare this values globally for all inputs without custom <style> tag for each component instance AND without duplicates in style attributes (if we can do receive this result when define through vars in  theme config 
Can you help me with this? 

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

latest

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by 7iomka** [comment]
I tried this
```ts
      vars: (_, props) => {
        return {
          wrapper: {
            // override local variable to use global one
            [`--input-height-${props.size}`]: `var(--input-height-${props.size})`,
          },
        };
      },
```

but is not working because local variable try to write itself but not the global one

The only workaround is to pass at root of input component css variable 
```
       root: {
            '--input-height': `var(--input-height-${props.size})`,
          },

```

and for wrapper use `inherit`
```css
      wrapper: {
            '--input-height': 'inherit',
          },
```

BUT this is impossible, because for `vars` is only `wrapper` available.
So, we have to use come wrappers for each input to pass by hand in style attribute...

It is weird!

**Comment by alecmce-maltedai** [comment]
How was this completed? I'm also trying to modify `--input-height` and no obvious path presents itself.

**Comment by rtivital** [comment]
https://mantine.dev/styles/variants-sizes/
