### ISSUE TITLE
AppShell with Navbar

### ISSUE THREAD

**Issue by imnash21** [mantinedev/mantine#4978]
### What package has an issue

@mantine/core

### Describe the bug

Something bug here when I add the AppShell.Navbar then the AppShell.Main padding top will removed, then the AppShell.Header and AppShell.Main are overlapping.

When I remove the AppShell.Navbar then the padding top of the AppShell.Main will be set again to its default padding top, but I didn't touch the offset property of the header, I just set the height only.

`<AppShell
    header={{ height: 60 }}
    navbar={{ width: 270, breakpoint="md" }}
    padding="lg">

    <AppShell.Header>
        ...
    </AppShell.Header>

    <AppShell.Navbar>
        ...
    </AppShell.Navbar>

    <AppShell.Main>
        ...
    </AppShell.Main>

</AppShell>`

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

@mantine/core (7.1.2)

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by imnash21** [comment]
It doesn't work they are still overlapping, I moved the MantineProvider from main.tsx to App.tsx, I'm using Vite with React Router from react-router-dom.

**Comment by rtivital** [comment]
I cannot help without a reproduction, it is hard to tell where the issue is

**Comment by bgoosmanviz** [comment]
I just ran into this issue. Discovered `--mantine-header-height` is undefined. Possible root cause? Will continue investigating.
<img width="1889" alt="image" src="https://github.com/mantinedev/mantine/assets/78885081/79678f6e-45c9-461e-8358-1a20d4524d67">

**Comment by imnash21** [comment]
I found the issue.

Because of the AppShell.Navbar that it doesn't exist if the isLoggedIn is equals to false then the AppShell.Header's height will set to undefined

`<AppShell
header={{ height: 60 }}
navbar={{ width: isLoggedIn ? 270 : 0, breakpoint="md" }}
padding="lg">

<AppShell.Header>
    ...
</AppShell.Header>

{isLoggedIn ? (
    <AppShell.Navbar>
        ...
    </AppShell.Navbar>
) : null}

<AppShell.Main>
    ...
</AppShell.Main>

</AppShell>
`

But if I set the navbar property to undefined too then the AppShell.Header height will set to 60 that I want

Changed:

navbar={isLoggedIn ? { width: 270, breakpoint="md" } : undefined}
