### ISSUE TITLE
AppShell compound components aren't compatible with server components

### ISSUE THREAD

**Issue by mellow-fellow** [mantinedev/mantine#4980]
### What package has an issue

@mantine/core

### Describe the bug

Importing AppShell and using its compound components in a server component will result in the following:

```Cannot access AppShell.Navbar on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.```

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

v7.1.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/sandbox/keen-jerry-g6dxng?file=%2Fapp%2Flayout.tsx%3A8%2C1

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
See https://mantine.dev/guides/next/#compound-components-in-server-components
