### ISSUE TITLE
PinInput uses ComponentPropsWithoutRef thus it's not possible to pass refs

### ISSUE THREAD

**Issue by devdanetra** [mantinedev/mantine#4984]
### What package has an issue

@mantine/core

### Describe the bug

`PinInput` uses `ComponentPropsWithoutRef` thus it's not possible to pass refs to the component, even though the ref argument is defined in the factory component.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.11

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Replacing `React.ComponentPropsWithoutRef` with `React.ComponentPropsWithRef`

Similar fix was applied in #2504

**Comment by rtivital** [comment]
The issue has been resolved in 7.0.0 – https://codesandbox.io/s/gracious-forest-2tgsj6?file=/src/App.tsx
