### ISSUE TITLE
Carousel previousControlProps not worked

### ISSUE THREAD

**Issue by kolobok001** [mantinedev/mantine#4985]
### What package has an issue

@mantine/carousel

### Describe the bug

Good afternoon. Carousel previousControlProps not worked. Moreover, for the right control everything works as expected. 
I'll do a PR a little later

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/funny-poitras-j4tx6z?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
The issue has been resolved in [7.1.3](https://github.com/mantinedev/mantine/releases/tag/7.1.3)
