### ISSUE TITLE
Mantine Select not cleared in the DOM when using form.reset method

### ISSUE THREAD

**Issue by FenderStrat85** [mantinedev/mantine#4987]
### What package has an issue

@mantine/core

### Describe the bug

After submitting a Mantine Form which contains 3 text inputs and a mantine select. We are calling the form.reset() method on submission. The form values are updating, however the select still holds the value that was submitted in the DOM. 

In Mantine v6 this was working

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Do you used `@mantine/form` form.reset?

**Comment by FenderStrat85** [comment]
> Do you used `@mantine/form` form.reset?

Yes indeed. I can used form.setValues to set the select to a null, but this then causes a number of other errors/issues so it is not an option

**Comment by rtivital** [comment]
I was unable to reproduce the issue – https://codesandbox.io/s/modest-davinci-ry4f4k?file=/src/App.tsx

**Comment by FenderStrat85** [comment]
We are using the form in a slightly different way. The initial value is an array of form values which can be added to as user tries to invite multiple users using multiple forms in the same component. I was able to build a work around, but could the fact we are using the form in this manner be the reason it is not working? It was working v6, but is not working in v7

**Comment by rtivital** [comment]
If you can provide a minimal reproduction, I can have a look

**Comment by woodjs** [comment]
> If you can provide a minimal reproduction, I can have a look

I also came across this problem. It occurs if you set the default value "" rather than null in InitialValues.

**Comment by bichkhe** [comment]
The same issue with woodjs

**Comment by Pyakz** [comment]
Same here, form.reset() does not reset my Custom MultiSelect Combobox

**Comment by rtivital** [comment]
The issue was closed because there is no reproduction.

**Comment by jpmonette** [comment]
I'm facing the same issue!

**Comment by jpmonette** [comment]
@rtivital I'll try to clean up my code and provide a reproducible / focused demo, but here's a recording demonstrating the issue.

https://github.com/mantinedev/mantine/assets/1114325/407a15a2-88a7-43b4-8791-f7a53b3a9c06

## Notes

- Using `"next": "^14.0.4",` with App Router
- Modified `node_modules/@mantine/form/esm/use-form.mjs` to output the values passed to `_setValues` on reset
- Seems like the form on `reset()` is clearing all but the first lowercased letter of the values in each field

```ts
    "@mantine/carousel": "^7.6.1",
    "@mantine/core": "7.6.1",
    "@mantine/form": "^7.6.1",
    "@mantine/hooks": "7.6.1",
    "@mantine/notifications": "^7.6.1",
```

Hopefully this helps troubleshoot the issue.

**Comment by jpmonette** [comment]
@rtivital Here's a reproducible demo on CodeSandbox:

https://codesandbox.io/p/sandbox/mantine-form-approuter-bug-mjny9g

1. Fill up the field
2. Press `reset`

Result: 1 letter remains.

**Comment by rtivital** [comment]
To use `form.reset`, you must provide initial values

**Comment by gursahibsahni** [comment]
If anyone is still looking for a fix for this - you need to set the initial value of the form select input to `null`. The reset doesn't work without a `default null` value.

**Comment by ceciiiron** [comment]
> If anyone is still looking for a fix for this - you need to set the initial value of the form select input to `null`. The reset doesn't work without a `default null` value.

I am using react-hook-form and I set the value using `setValue("select_input", null)`, and it worked. Thanks!

**Comment by eisa-rezaei** [comment]
same here...

**Comment by dominictobias** [comment]
I found the opposite - it's cleared when using with useForm, but as a controlled input it doesn't get reset. But if I just open and close the Select then the selected value disappears.

**Comment by jessie975** [comment]
If my field is required, initializing to null will cause my type validation to fail. What should I do? Or is there any other solution?

**Comment by rtivital** [comment]
If the field must have a value, then give it an initial value.

**Comment by jessie975** [comment]
https://codesandbox.io/p/sandbox/blissful-wright-gnqgqt?file=%2Fsrc%2FApp.tsx%3A9%2C6  

If my field is a string type, reset cannot take effect when using "" instead of null as the initial value.

In addition to that, if my field is of type enum and is required, it doesn't seem good to have to give an initial value for reset to take effect.

**Comment by dominictobias** [comment]
> I found the opposite - it's cleared when using with useForm, but as a controlled input it doesn't get reset. But if I just open and close the Select then the selected value disappears.

I take it back, it doesn't clear after `form.reset` or `form.setValues`. I had to get a ref to the select and clear it via DOM methods after calling them :|

```ts
setTimeout(() => {
  if (selectRef.current) {
    selectRef.current.value = ''
    selectRef.current.dispatchEvent(
      new Event('input', {
        bubbles: true,
        cancelable: true,
      })
    )
  }
}, 0)
```

**Comment by rafaelsorto** [comment]
@jon23d that works because when you key changes your whole component is removed by react and a new one is created. This issue is reported for Select component I suppose you didn't mean to use TextInput as the example for how you fixed the issue.

I think the issue here is that Select in the documentation for a Controlled Select starts with an empty string but for it to actually work and be cleared the controlled piece of state has to change to `null` otherwise select tries to find the option with an empty string value '' and when not found it defaults to show the last selected value that actually has a equivalent value in its data prop array.

Here is a link to a repo that reproduces this https://stackblitz.com/github/rafaelsorto/vite-template?file=src/App.tsx

What I've done is that my value prop has a hack to use null if the state is empty string which I normally use to denote empty value in my react projects inputs with controlled state.

**Comment by geeron** [comment]
> I discovered that if you supply a key to the input, then the reset will work.
> 
> `<TextInput key={form.key('myField')} />`

Adding `null` as initial value, and adding a key solved it for me

**Comment by SSTPIERRE2** [comment]
> I discovered that if you supply a key to the input, then the reset will work.
> 
> `<TextInput key={form.key('myField')} />`

Legend 👏 I ran into this exact issue with both a `Select` and a `DatePickerInput` and it appears to be a rendering issue that is most noticeable in `uncontrolled` mode. If you ever need to programmatically set the value of certain fields like those, it appears you'll have to either set a key on each of them, or switch to `controlled` mode - this makes it so each field re-renders whenever the value changes which fixes the issue. I want to clarify that setting the initial value of the field to `null` did **not** work for me; the only thing that worked is forcing the field(s) to re-render when the value changes. To be fair, the [uncontrolled mode docs](https://mantine.dev/form/uncontrolled/#formgetinputprops) mention this, but it seems to only really matter for certain types of inputs. Anyway I hope this helps someone.
