### ISSUE TITLE
Select input on drawer not working on safari browser

### ISSUE THREAD

**Issue by kitavidavis** [mantinedev/mantine#4990]
### What package has an issue

@mantine/core

### Describe the bug

I have a drawer that has various inputs. All of them works fine in browsers on windows. However, when the same site is running on a safari browser on mac, the select input appears to be frozen, and the user cannot select any item. Is there further configuration for mac users?

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^6.0.17

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Have you tried isolating the issue?

- Are you certain that this happens only when Select is inside the Drawer? Can you try rendering it outside the Drawer and see whether it freezes in this case?
- Are you certain that this happens only to your Select component? Do you have other inputs in the same area?

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide further information.

**Comment by dezguell** [comment]
I'm experiencing the same issue. I have a select component inside a Drawer that does not show the options. I have other selects components outside that are working fine! I'm using a NativeSelect that is working fine. But I need more features for these elements that are supported in the Select component, then I need to fix this issue!

**Comment by rtivital** [comment]
Make sure that your select dropdown has high enough z-index
