### ISSUE TITLE
`TypeError: Cannot read properties of undefined (reading 'transitionProperty')`

### ISSUE THREAD

**Issue by devcshort** [mantinedev/mantine#5004]
### What package has an issue

@mantine/core

### Describe the bug

I'm reporting this simply so it can be looked in to in case others run in to it. We have tight deadlines so we're moving away from Mantine.

Currently the application runs find in development, but as soon as we build it for production it quits working and clicking on the hamburger menu causes the application to crash. The error that it throws is `TypeError: Cannot read properties of undefined (reading 'transitionProperty')`.

Below is a link to a site that currently has that error, however our header rewrite will be done and pushed by end of day so after that it won't be viewable anymore.
[Live link](https://search.wa211.org/)

Useful info
- We're using Nextjs
- We're using NX for managing our monorepo
- [Here's the code for the header causing issues](https://github.com/211-Connect/Norse/blob/main/packages/client/components/organisms/AppHeader.tsx)
- We're using @mantine/core@6.0.21

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.21

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

No idea

**Comment by rtivital** [comment]
Issue with Next.js, see https://github.com/mantinedev/mantine/issues/4548
