### ISSUE TITLE
Notification transition problem (@mantine/notifications)

### ISSUE THREAD

**Issue by Wiwida** [mantinedev/mantine#5007]
### What package has an issue

@mantine/notifications

### Describe the bug

Since V7 I've had a transition problem when the notification appears and disappears.
I did some digging and found the problem, which is due to the "style" property of the show method.
Without the "style" property, the transition occurs, but if I add it (ex : style: {"backgroundColor": "red"}), the transition at the notification's appearance and disappearance is suppressed.
Everything works fine in V6. 
What's more, the documentation tells me that this shouldn't be a problem. 
Is this intentional or is it a mistake on my part ?

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
How do you set style property?

**Comment by rommni** [comment]
Can reproduce with this code sample : 
https://codesandbox.io/s/nostalgic-dream-n6qdj8?file=/src/App.tsx

**Comment by rtivital** [comment]
Thanks, the issue will be resolved in one of the next patches

**Comment by NinhUTCK61** [comment]
@rommni I have noticed that the attribute limit notification is not functioning properly

**Comment by rtivital** [comment]
The issue has been resolved in [7.1.3](https://github.com/mantinedev/mantine/releases/tag/7.1.3)
