### ISSUE TITLE
Spotlight overflow doesn't scroll

### ISSUE THREAD

**Issue by hichemfantar** [mantinedev/mantine#5010]
### What package has an issue

@mantine/spotlight

### Describe the bug

When the number of elements exceeds the screen height, the overflowing elements are hidden.
To reproduce in the example below, open the spotlight and zoom in the page until the elements overflow

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/others/spotlight/#limit-prop

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is intended behavior, to make list scrollable, set `scrollable` and `maxHeight` props. I wasn't able to find a way to have both scrollable list and dynamic height. https://mantine.dev/others/spotlight/#scrollable-actions-list
