### ISSUE TITLE
next js (latest) graphic error on DatePicker 

### ISSUE THREAD

**Issue by Army-99** [mantinedev/mantine#5011]
### What package has an issue

@mantine/dates

### Describe the bug

Seems next can't find the right css for init the component (i already imported all the css components )

![1_mantine_datePicker](https://github.com/mantinedev/mantine/assets/101435102/ed70309c-83cb-4b0a-8c92-c90e75d94e3d)

code: 
`
import { useState } from "react";
import { DateInput } from "@mantine/dates";

export default function CustomDatePicker() {
    const [value, setValue] = useState<Date | null>(null);
    return (
        <DateInput
            //Must force the left and right icon
            // previousIcon={<IconArrowLeft />}
            // nextIcon={<IconArrowRight />}
            // styles={{ wrapper: { display: "flex", alignContent: "center", fontSize: 26, backgroundColor: "red" } }}
            value={value}
            onChange={setValue}
            label="Date input"
            placeholder="Date input"
        />
    );
}
`

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

"@mantine/dates": "^7.1.2"

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by 7iomka** [comment]
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';

Do you have this style imports in _app file?

**Comment by rtivital** [comment]
You did not import `import '@mantine/dates/styles.css';`. See getting started https://mantine.dev/dates/getting-started/

**Comment by dalmasonto** [comment]
![image](https://github.com/mantinedev/mantine/assets/49430208/ce2004ab-3cf4-4bc9-ad54-7af3dce87985)
![image](https://github.com/mantinedev/mantine/assets/49430208/020fcb89-77f4-4dbf-ad7e-45611e61783d)

I have both mantine/core and mantine/dates imported but still getting this styling bug like the picker is not displayed with the correct css
