### ISSUE TITLE
NumberInput becomes unfocused when using controls

### ISSUE THREAD

**Issue by Slapbox** [mantinedev/mantine#5013]
### What package has an issue

@mantine/core

### Describe the bug

When using controls the NumberInput now becomes unfocused, which was not the case in 5.x and 6.x.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://v7.mantine.dev/core/number-input/

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
The issue has been resolved in [7.1.3](https://github.com/mantinedev/mantine/releases/tag/7.1.3)
