### ISSUE TITLE
TagsInput: required prop doesn't work as intended.

### ISSUE THREAD

**Issue by sunadoi** [mantinedev/mantine#5016]
### What package has an issue

@mantine/core

### Describe the bug

When `required` prop is given to the `TagsInput` component, after entering some tags and then submitting the form, the "Please fill out this field" form validation is displayed and the form cannot be submitted.

I think this is because `_searchValue` is empty immediately after pressing `EnterKey` or `splitChars` key.

In addition, the asterisk is not displayed when I give a `required` prop

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/headless-smoke-dp3qg4?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

- Passing `required` to `PillInput` component to display asterisks when `required` prop is given.
- Set `required` prop in `PillsInput.Field` to `required && values.length === 0`.

The following video shows the behavior of the above fix in local.
It appears to be working as intended.

https://github.com/mantinedev/mantine/assets/57832553/da982daf-d7d6-4022-90c6-1ee0f73c5310

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
