### ISSUE TITLE
Mantine Radio Button circle is not perfectly rounded.

### ISSUE THREAD

**Issue by danyalarif** [mantinedev/mantine#5018]
### What package has an issue

@mantine/core

### Describe the bug

I just came across this issue, in which mantine v7's radio button is not perfectly rounded. Please check the attached screenshot for better understanding of the problem.
![image](https://github.com/mantinedev/mantine/assets/87372881/da76593a-a2f6-4a86-a6f4-178c1ebd7ab3)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by 7iomka** [comment]
What browser / OS are you seeing this in and with what size radio button?
