### ISSUE TITLE
ScrollArea does not work with Preact

### ISSUE THREAD

**Issue by crstffr** [mantinedev/mantine#502]
## Description

Interacting with a `<Select/>` or `<MultiSelect/>` component causes the browser tab to use 100% CPU, and the tab must be force-quit. I have put together a barebones demonstration of the problem using Vite & Preact. When it loads, you can interact with the `<TextInput/>` without problem. As soon as you click on the `<Select/>` input, the tab crashes.

## Details

- What package has an issue: `@mantine/core` 
- What package version are you using: `v3.3.5`
- In which browser and operating system issue occurred: `macOs: Chrome & Firefox`
- Please attach link to code sandbox with reproduced issue:
  - Demo: https://crstffr.github.io/mantine-vite-demo/
  - Source: https://github.com/crstffr/mantine-vite-demo
- Do you have an idea how to fix the issue: `No`
- Are you willing to participate in fixing this issue: `Perhaps`

**Comment by crstffr** [comment]
I looked back through your release notes and noticed that you implemented the ScrollArea component as the default dropdown element for the `<Select/>` and `<MultiSelect/>` components in `v3.3.0`. 

I rolled back to `@mantine/core v3.2.3` and the select dropdown works as expected.

This may just be an issue with the Mantine ScrollArea + Preact. I have not tested it with React.

**Comment by rtivital** [comment]
Yep, that is the case, radix does not support preact, so scrollarea component will be unavailable until we rewrite it to support preact. The workaround is to disable ScrollArea on Select by setting dropdown component to a div – https://mantine.dev/core/select/#native-scrollbars
