### ISSUE TITLE
Add back Mantine Select createable prop and related features

### ISSUE THREAD

**Issue by svn1991** [mantinedev/mantine#5022]
### What package has an issue

@mantine/core

### Describe the bug

Mantine Select does not allow dynamic creation as the "createable" and related props are missing.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7+

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
You can find an explanation why these props were removed here – https://github.com/mantinedev/mantine/pull/4981#issuecomment-1751255801

You can find creatable select example here – https://mantine.dev/combobox/?e=SelectCreatable
