### ISSUE TITLE
[DatePicker] css is empty for all date related components

### ISSUE THREAD

**Issue by john-subba** [mantinedev/mantine#5025]
### What package has an issue

@mantine/dates

### Describe the bug

The styles of @mantine/dates is not working as you can see in the screenshot. I tried downgrading the version and also upgrading to version 7.1.2 still it's same.
![Screenshot 2023-10-12 123045](https://github.com/mantinedev/mantine/assets/75922945/ebb3728c-1233-4354-b708-59b7e9c5ca21)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

v7.1.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
- https://mantine.dev/dates/getting-started/
- `import '@mantine/dates/styles.css';`

**Comment by john-subba** [comment]
Thanks. My bad for not reading docs properly. Did not had to do this in v6 so i was confused.
