### ISSUE TITLE
Mantine v5 Rating component select issue

### ISSUE THREAD

**Issue by raseltechnext** [mantinedev/mantine#5028]
### Link to the page where something nasty is located

https://v5.mantine.dev/core/rating/

### Exact quote of what is wrong

When I select fraction on Rating component, in desktop view this work fine.
But in mobile view, when select a fraction value and then click outside of this Rating component it will be round value. Such as, select 2.5 rating then it will be 3 or select 3.5 rating it will be 4.
Can anyone response?

### Are you willing to create pull request with the fix?

None

**Comment by rtivital** [comment]
The issue has been resolved in 7.1.3, it is not planned to release 5.x versions

**Comment by raseltechnext** [comment]
> The issue has been resolved in 7.1.3, it is not planned to release 5.x versions

But we already implemented our project with mantine version 5.
Is it possible for solve this problem with version 5?

**Comment by rtivital** [comment]
No, the fix is available only in version 7.1.3
