### ISSUE TITLE
NumberInput rightSectionWidth extends beyond right section and prevents clicking into input in that area

### ISSUE THREAD

**Issue by Slapbox** [mantinedev/mantine#5033]
### What package has an issue

@mantine/core

### Describe the bug

The area just before the `rightSection` cannot be clicked to activate the input in v7. This was not an issue in v5/v6 and it's particularly problematic with small NumberInputs like shown below. The `rightSection`'s extents are highlighted in red.

![image](https://github.com/mantinedev/mantine/assets/6835891/5fe8f83c-01e7-4f04-a21f-57f2d7d4d522)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.3

### If possible, please include a link to a codesandbox with the reproduced problem

It can be reproduced by adjusting the width of the inputs on the demo page https://mantine.dev/core/number-input/

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by 7iomka** [comment]
This happens because rightSectionWidth by default have value equal to the input height, and controls is position inside of it.
This behavior can be improved by override rightSectionWidth value under the hood if it doesn't passed from props and if rightSection is not used for something else with NumberInput.

**Comment by Slapbox** [comment]
Thanks for the reply @7iomka. If we define a custom `rightSectionWidth` then the values become uncentered:

### With rightSectionWidth defined
![image](https://github.com/mantinedev/mantine/assets/6835891/f8003067-40d7-4659-af29-c98b8246bc56)


### Default positionining
![image](https://github.com/mantinedev/mantine/assets/6835891/070acbd8-2a39-4ba0-929d-9afc4a65eac4)

**Comment by 7iomka** [comment]
> Thanks for the reply @7iomka. If we define a custom `rightSectionWidth` then the values become uncentered:
> 
> ### With rightSectionWidth defined
> ![image](https://user-images.githubusercontent.com/6835891/275279690-f8003067-40d7-4659-af29-c98b8246bc56.png)
> 
> ### Default positionining
> ![image](https://user-images.githubusercontent.com/6835891/275279797-070acbd8-2a39-4ba0-929d-9afc4a65eac4.png)

I saw that rightSectionWidth needed to have default override under the hood by library, not on your side.
In this case padding-x will contain this value + default padding and position will remain centered.

**Comment by Slapbox** [comment]
Thanks for your reply @7iomka. Sorry if I'm still not understanding correctly, you're saying this should be considered a bug in Mantine?

**Comment by 7iomka** [comment]
> Thanks for your reply @7iomka. Sorry if I'm still not understanding correctly, you're saying this should be considered a bug in Mantine?

I suppose this is an overlooked issue that can be fixed in the above way by the author of the library

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1).
