### ISSUE TITLE
ComboboxStore: selectedOptionIndex is not updated.

### ISSUE THREAD

**Issue by icrocket** [mantinedev/mantine#5036]
### What package has an issue

@mantine/core

### Describe the bug

Hi, the selectedOptionIndex property of the comboboxStore instance seems not to update.

In the example, see the Combo.tsx component and its onKeyDown and onOptionSubmit events.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/vigorous-kowalevski-wncccl

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
`selectedOptionIndex` value is stored in ref, not is state. It is done purposely to avoid rerenders of all items when the next/previous item is selected. Also, the attached sandbox does not work.

**Comment by icrocket** [comment]
> `selectedOptionIndex` value is stored in ref, not is state. It is done purposely to avoid rerenders of all items when the next/previous item is selected. Also, the attached sandbox does not work.

Ok but how can I get the current selected option index? I programmatically use the selectNextOption and selectPreviousOption methods and I need to understand which index is selected.

P.s thanks so much for the quick response

**Comment by freva** [comment]
I have the same issue. I'm trying to find which option is selected when the `Tab` key is pressed, but `combobox.selectedOptionIndex` always returns -1. 

The attached sandbox works for me; try changing the selected item using arrow keys and then press any other key to trigger `onKeyDown`, -1 is logged.

Would it be an option to make `selectedOptionIndex` a function to avoid triggering re-render?

**Comment by rtivital** [comment]
Will be resolved in 7.3.1 – a new method `combobox.getSelectedOptionIndex()` will return the selected index value. I am not sure why it does not work with current approach.
