### ISSUE TITLE
Vitest fails with MantineProvider

### ISSUE THREAD

**Issue by Duckling92** [mantinedev/mantine#5043]
### What package has an issue

@mantine/core

### Description
When I test otherwise working components of a React app wrapped in `MantineProvider` with [Vitest](https://vitest.dev/), Vitest throws errors. If `MantineProvider` is removed, no errors occur.

### Example
With this app
```typescript
import { MantineProvider } from "@mantine/core"
import MyComponent from "./SomeComponent"

function App() {
  return (
  <MantineProvider>
    App
    <MyComponent />
  </MantineProvider>
)}

export default App
```
with this component
```typescript
import { Button } from "@mantine/core"
function MyComponent() {
  return <Button>My button</Button>
}

export default MyComponent
```

the following test throws
```
 FAIL  src/App.test.jsx > simple test
TypeError: window.matchMedia is not a function
```
```react
import { render } from '@testing-library/react';
import { test } from 'vitest';

import App from './App';

test('simple test', () => {
  const window = render(<App />);
  window.debug();
});
```
and 
```
FAIL  src/SomeComponent.test.tsx > Another test
Error: @mantine/core: MantineProvider was not found in component tree, make sure you have it in your app
```
```typescript
import { render } from '@testing-library/react';
import { test } from 'vitest';

import MyComponent from './SomeComponent';


test('Another test', () => {
  const window = render(<MyComponent />);

  window.debug();
});
```

### Steps to reproduce
I've added a minimally working app [here](https://github.com/Duckling92/mantine-bug).

1. Clone the repository
2. run `npm install`
3. run `npm run test`

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^7.1.3

### If possible, please include a link to a codesandbox with the reproduced problem

I've added a minimally working app here: https://github.com/Duckling92/mantine-bug

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes, but I doubt my typescript-skills will be sufficient...

**Comment by rtivital** [comment]
See https://github.com/vitest-dev/vitest/issues/821 for window.matchMedia
For MantineProvider, you can follow jest setup – https://mantine.dev/guides/jest/
