### ISSUE TITLE
Incorrect highlighting when one word is a substring of another

### ISSUE THREAD

**Issue by wgpsutherland** [mantinedev/mantine#5044]
### What package has an issue

@mantine/core

### Describe the bug

In the Highlight component, if you want to highlight a string where one word you want to highlight is a substring of another word you want to highlight, only the shorter part of the word gets highlighted.

Please see the code sandbox to see a minimal repro - the words Mr and Mrs should be highlighted, but only the Mr part of both words gets highlighted. 

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/gifted-wiles-zn4l4g?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

The file highlight.js creates a regex by `|` concatenating all words you are wanting to be highlighted (in `_highlight`), and then splits the input on this regex. This list of split chunks is then tested one by one on the regex to see if it should be highlighted or not. 

If you are trying to highlight the string: `"Welcome Mr and Mrs Smith"`, with the words: `["Mr", "Mrs"]`

Then the string you are trying to highlight gets split first on `Mr`, resulting in this: `['Welcome ', 'Mr', ' and ', 'Mr', 's ', 'Smith', '']`

Then when this is looped over to see if it should be highlighted, `Mr` gets highlighted twice, and the `s` of `Mrs` does not get highligheted.

A quick fix would be first to order `_highlight` by longest word first, so that matches to the longer options get matched first before the shorter ones, so your string split results in this:
`['Welcome ', 'Mr', ' and ', 'Mrs', ' ', 'Smith', '']`

Which gets highlighted correctly.

**Comment by wgpsutherland** [comment]
PR here https://github.com/wgpsutherland/mantine/pull/1

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix

**Comment by wgpsutherland** [comment]
Hi @rtivital - i already did, please see my previous comment :)

**Comment by rtivital** [comment]
You've sent PR to your forked repo, not to the main repo.

**Comment by wgpsutherland** [comment]
ah I see - thanks - fixed https://github.com/mantinedev/mantine/pull/5045
