### ISSUE TITLE
Focus issue on SegmentedControl from '@mantine/core';

### ISSUE THREAD

**Issue by mthores** [mantinedev/mantine#5058]
### What package has an issue

@mantine/core

### Describe the bug

The inactive "tabs" are not accessible/focusable via tab key.  They are unfocusable it seems. 

This is bad for accessibility. 
![2023-10-17 10 29 32](https://github.com/mantinedev/mantine/assets/17404260/88b1a807-ba81-4147-b27f-c3554a779018)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/segmented-control/

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by mthores** [comment]
Possible solution would to use <UnstyledButton/> inside instead of label element.

**Comment by rtivital** [comment]
It is correct behavior, SegmentedControl is a set of radio inputs, the component is fully accessible with keyboard arrows.
