### ISSUE TITLE
Indicator rendered not as expected when using it as Accordion.Item children

### ISSUE THREAD

**Issue by BOHDANff** [mantinedev/mantine#5059]
### What package has an issue

@mantine/core

### Describe the bug

Hello, when I was working with `Accordion` and `Indicator` I've noticed that `Indicator` rendered not as expected when using it as `Accordion.Item` children.

Example of code (also add link to sandbox):
```js
<Accordion>
  <Accordion.Item value={'1'}>
    <Indicator label={'NEW'} color={'red'}>
      <Button>Hello</Button>
    </Indicator>
  </Accordion.Item>
</Accordion>
```

Problem visualization:
![image](https://github.com/mantinedev/mantine/assets/45514703/1212a828-debe-43bb-9d1a-4dbebf83a19c)

Problem in html is that `Indicator` root div takes all the width of `Accordion.Item` but not only width of wrapped component (in this case - button)

Is there any way to solve this problem and make indicator appear near the wrapped component but on on the end of `Accordion.Item`?

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hopeful-sunset-xhn2hq?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
To use Indicator with inline elements, set `inline` prop – https://codesandbox.io/s/blissful-gwen-g5zfvq

**Comment by BOHDANff** [comment]
Thank you for the answer
