### ISSUE TITLE
First run of useMediaQuery returns undefined if no initial value was provided

### ISSUE THREAD

**Issue by sowizz** [mantinedev/mantine#5065]
### What package has an issue

@mantine/hooks

### Describe the bug

According to the docs one can use the `useMediaQuery` hook with just one parameter - the query. The problem is that in this case undefined is returned on the first run.

Here is the demo: https://codesandbox.io/s/happy-wing-3ls46l?file=/src/Demo.tsx
(please open the console to see the console.log output)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^6.0.17
(but happens in 7.1.3 version as well)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/happy-wing-3ls46l?file=/src/Demo.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
It is intended behavior to prevent hydration mismatch during ssr. If you need to get value in the initial state, set `getInitialValueInEffect` option – https://codesandbox.io/s/blissful-wildflower-d56fmf?file=/src/Demo.tsx

**Comment by sowizz** [comment]
So let's say I'm rendering two different components depending on the result of the query. If it returns `undefined` in the first run, how do I decide which one should I render? If I use `false` as initial value and the hook returns `true` in the next run there might a bit of flickering / layout shifting.

**Comment by alolis** [comment]
> [@rtivital](https://github.com/rtivital) So let's say I'm rendering two different components depending on the result of the query. If it returns `undefined` in the first run, how do I decide which one should I render? If I use `false` as initial value and the hook returns `true` in the next run there might a bit of flickering / layout shifting.

Same issue here. Did you ever manage to solve this properly?

**Comment by sowizz** [comment]
> > [@rtivital](https://github.com/rtivital) So let's say I'm rendering two different components depending on the result of the query. If it returns `undefined` in the first run, how do I decide which one should I render? If I use `false` as initial value and the hook returns `true` in the next run there might a bit of flickering / layout shifting.
> 
> Same issue here. Did you ever manage to solve this properly?

I think calling `useMediaQuery` like so:
```js
useMediaQuery(`(min-width: ${breakpoints.lg})`, undefined, {
  getInitialValueInEffect: false,
})
```
did the trick for us. I don't remember if we took any other steps, sorry.

**Comment by alolis** [comment]
@sowizz thanks for the time. I will check it out.
