### ISSUE TITLE
Multiselect doesn't allow non-string values

### ISSUE THREAD

**Issue by BryceBlankinship** [mantinedev/mantine#5066]
### What package has an issue

@mantine/core

### Describe the bug

Let's say I use Multiselect with labels that could have the same value. Therefore I want to do something like this to differentiate their keys in the list:  [{ label: obj.name, value: obj.id }], but with the v7 update, this no longer works as it applies a toLowerCase() function to the values. This means I have to go back and refactor all my MultiSelects (I use them a lot) to apply .toString() to the id. Although I can do that, I feel that Multiselect should do that itself before calling toLowerCase() to avoid this ever being an issue.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

    "@mantine/core": "^7.1.3"

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/stupefied-dawn-9lxrks?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Just apply .toString() before .toLowerCase() as part of the package, I'll gladly make this change to gain some opensource clout 😤

**Comment by rtivital** [comment]
MultiSelect as well as other combobox components never allowed non-string values in prior versions. It is explicitly defined in the type definition. It is not planned to introduce this feature in v7.
