### ISSUE TITLE
Select has an additional scroll bar on "Large data set"

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#507]
If you scroll to the end of the "Large data set" example, a second scroll bar appears. (see the image)

- What package has an issue (@mantine/core, mantine/hooks or other)? @mantine/core
- What package version are you using? 3.3.5
- In which browser and operating system issue occurred? Windows 11 Brave@1.32.115 Chromium: 96.0.4664.93
- If possible please attach link to codesandbox with reproduced issue: [codesandbox](https://codesandbox.io/s/blissful-surf-weeql) or [mantine docs](https://mantine.dev/core/select/#large-data-set)

![image](https://user-images.githubusercontent.com/49494752/145693711-4d91c103-33e2-4674-a697-3b9a1b7b0ab6.png)

**Comment by rtivital** [comment]
Thanks for reporting, we will fix this issue in next minor release

**Comment by rtivital** [comment]
Fixed in 3.4.0
