### ISSUE TITLE
Menu and Select items focus issue

### ISSUE THREAD

**Issue by gamegee** [mantinedev/mantine#5077]
### What package has an issue

@mantine/core

### Describe the bug

Hello,

I am experiencing an issue with the Select and Menu components. Both of them open a popover with a list of items. The problem is that each item cannot be focused using the tab key. While it's possible to navigate using the arrow keys, many users are accustomed to using the tab key to move to the next focusable element.

You can try it on the documentation directly:
https://mantine.dev/core/select
https://mantine.dev/core/menu

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

## First solution
- Allow to pass `tabIndex={0}` to `<Menu.Item />`
- For the select won't work since we pass an array of data

## Second solution
- Make it configurable through a property
e.g.
```tsx
<Menu allowItemsFocus />
<Select allowItemsFocus />
```

**Comment by 7iomka** [comment]
According to example
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/
I don't think that each item need to be focusable with tab key
Or maybe I'm missing something?

**Comment by gamegee** [comment]
Yes you're right 👍 

My point is the combobox components you build with Mantine are more complex and advanced components than a simple select.
For Mantine `Select` component it's still pretty much the same, but for the `Menu` it could make sense to enable tab focus.
Some large app like Github or Jira have tab focusable dropdown-menu.

**Comment by rtivital** [comment]
Menu and Select components work according to WAI ARIA specification – it is not planned to introduce this feature.
