### ISSUE TITLE
@mantine@7.1.5  "ScrollArea.Autosize" is not functioning properly within the "Modal" component, and the scrollbar cannot be displayed correctly.

### ISSUE THREAD

**Issue by bao76296** [mantinedev/mantine#5084]
### What package has an issue

@mantine/core

### Describe the bug

"ScrollArea.Autosize" is not functioning properly within the "Modal" component, and the scrollbar cannot be displayed correctly.
The examples in the development documentation also have the same issue.
https://mantine.dev/core/modal/#usage-with-scrollarea

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.5

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1).
