### ISSUE TITLE
useSessionStorage will throw if sessionStorage is blocked by window

### ISSUE THREAD

**Issue by yongwee** [mantinedev/mantine#5089]
### What package has an issue

@mantine/hooks

### Describe the bug

If `useSessionStorage` is used on a blocked context (e.g. iframed 3rd party site embedded on another website in incognito mode), `window['sessionStorage']` will throw when executed

https://github.com/mantinedev/mantine/blob/05e26d79c050f29838985ff6875739b60ddd6a63/src/mantine-hooks/src/use-local-storage/create-storage.ts#L87

<img width="1128" alt="image" src="https://github.com/mantinedev/mantine/assets/7090189/4538225a-b275-4ded-84d2-43903ffd3cab">

I imagine it'd be the same for localStorage as well

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.3

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Wrap the checks in try-catch block

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix

**Comment by yongwee** [comment]
Sure! Just submitted #5091 :)
