### ISSUE TITLE
While using the keyframes for simple animation its throwing warning

### ISSUE THREAD

**Issue by just-be-weird** [mantinedev/mantine#509]
``keyframes` output got interpolated into plain string, please wrap it with `css`.` I'm not sure if I'm being noob here while using the keyframes. I did referred the [docs](https://mantine.dev/theming/create-styles/#keyframes) and tried the similar animation but no luck every solution leads to this same error.

- What package has an issue (@mantine/core, mantine/hooks or other)?
- @mantine/core
- What package version are you using?
- 3.3.5
- In which browser and operating system issue occurred?
- Windows 11, chrome, edge and others
- If possible please attach link to codesandbox with reproduced issue
- [codesandbox ](https://codesandbox.io/s/gracious-ellis-22beb?file=/pages/index.js:1073-1084)
- Do you have an idea how to fix the issue?
- No tried to use the css from emotion-react, as suggested in console but didn't work

Thank you @rtivital for mantine. It really is a work of art, I really appreciate the work!!

**Comment by rtivital** [comment]
Hi @just-be-weird, thanks for kind words! You are using `getRef` function incorrectly, here is a valid example – https://codesandbox.io/s/polished-snowflake-zzgvq?file=/pages/index.js

**Comment by just-be-weird** [comment]
> Hi @just-be-weird, thanks for kind words! You are using `getRef` function incorrectly, here is a valid example – https://codesandbox.io/s/polished-snowflake-zzgvq?file=/pages/index.js

Yes indeed that was the root cause!
