### ISSUE TITLE
Switch loses animation when calling toggleColorScheme

### ISSUE THREAD

**Issue by kirankunigiri** [mantinedev/mantine#5092]
### What package has an issue

@mantine/core

### Describe the bug

I wanted to create a component that is able to toggle the color scheme with a Switch component. A standard Switch that I copied from the docs has a nice toggling animation. However, when setting `onChange` to run the `toggleColorScheme` function (from the docs, see sandbox), the Switch toggle animation does not run and it instantly changes.

https://github.com/mantinedev/mantine/assets/9154932/099ff38d-4380-4212-9d86-a244059fd8b9

Note: I'm using 7.1.5 in my own project, but in the sandbox (which uses 7.1.3) the bug also appears.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/sharp-dawn-k54q7k

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 7.1.6, you can now pass the option to keep transitions to `useMantineColorScheme({ keepTransitions: true })`
