### ISSUE TITLE
Carousel incorrectly calculates slide offset

### ISSUE THREAD

**Issue by ameotoko** [mantinedev/mantine#5093]
### What package has an issue

@mantine/carousel

### Describe the bug

I am not exactly sure, whether it belongs to Mantine or Embla itself, but I'll start here.

`Carousel` inside a `Card` and a `Modal` incorrectly calculates the scroll length of the slides container. This results in each slide having an offset which accumulates – each slide has bigger offset against viewport than the previous (see code sandbox).

https://github.com/mantinedev/mantine/assets/10257912/b33ead91-97b1-46d0-b38f-92d496755a05

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/infallible-flower-hhvgfv?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

TS and React are not my strenghs, but I can make a PR if I have help finding the cause of the issue.

**Comment by rtivital** [comment]
https://mantine.dev/others/carousel/#carousel-container-animation-offset
