### ISSUE TITLE
[V7] When TagsInput use label/value as data, the onchange event emits data.label as value instead of data.value

### ISSUE THREAD

**Issue by naivefun** [mantinedev/mantine#5100]
### What package has an issue

@mantine/core

### Describe the bug

TagsInput accepts {label, value} array for its data options. However the onChange event should use {value} rather than {label} as its value.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.5

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is expected behavior, `{ value, label }` format is not supported in TagsInput. It is already fixed in documentation and the fix will be released with the next patch.

**Comment by rtivital** [comment]
Fixed in 7.1.6, documentation was updated

**Comment by cybae0804** [comment]
Hello, is it an intentional decision to not support this label value format for the TagsInput component??

**Comment by rtivital** [comment]
https://help.mantine.dev/q/autocomplete-value-label
