### ISSUE TITLE
@mantine/notifications v7.15 | Notifications limit prop is not functioning correctly

### ISSUE THREAD

**Issue by SeakMengs** [mantinedev/mantine#5105]
### What package has an issue

@mantine/notifications

### Describe the bug

The limit parameter doesn't appear to be functioning correctly. The notifications do pop up as usual, but the limit feature seems to be broken, let me know if this is confirmed as an issue. I would like to work on this issue :)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

@mantine/notifications v7.15 

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/sandbox/mantine-notification-system-v7-15-limit-bug-vkg6nn

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1).
