### ISSUE TITLE
Mantine layer styles do not override Panda layer styles.

### ISSUE THREAD

**Issue by muco-rolle** [mantinedev/mantine#5106]
### What package has an issue

@mantine/core

### Describe the bug

I'm not sure if I'm doing something wrong, but the layer styles import order doesn't seem to be working with Panda CSS. Here's a reproducible sandbox.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://stackblitz.com/edit/remix-run-remix-g1ghv1?file=package.json,panda.config.ts,remix.config.js,tsconfig.json,app%2Findex.css,app%2Froot.tsx,app%2Froutes%2F_index.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by manuelbosi** [comment]
> ### What package has an issue
> @mantine/core
> 
> ### Describe the bug
> I'm not sure if I'm doing something wrong, but the layer styles import order doesn't seem to be working with Panda CSS. Here's a reproducible sandbox.
> 
> ### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)
> 7.1.5
> 
> ### If possible, please include a link to a codesandbox with the reproduced problem
> https://stackblitz.com/edit/remix-run-remix-g1ghv1?file=package.json,panda.config.ts,remix.config.js,tsconfig.json,app%2Findex.css,app%2Froot.tsx,app%2Froutes%2F_index.tsx
> 
> ### Do you know how to fix the issue
> No
> 
> ### Are you willing to participate in fixing this issue and create a pull request with the fix
> Yes
> 
> ### Possible fix
> _No response_

By following the remix setup from the docs it works.
To fix this replace your styles import from `import '@mantine/core/styles.layer.css';` to `import '@mantine/core/styles.css';` at the top of `root.tsx` file

<img width="455" alt="image" src="https://github.com/mantinedev/mantine/assets/8373470/6ac133d8-4c55-477f-a888-ecaa891fdc49">

**Comment by muco-rolle** [comment]
This does @manuelbosi with Mantine layer styles
