### ISSUE TITLE
Can't pinch-to-zoom on modals

### ISSUE THREAD

**Issue by enchorb** [mantinedev/mantine#5115]
### What package has an issue

@mantine/core

### Describe the bug

Am unable to pinch-to-zoom on modals on mobile (iOS). This causes major issues with fullscreen modals and inputs and by focusing on an input the screen zooms in and then you can't zoom back out to close out of the modal.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/modal/ 

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by enchorb** [comment]
Inputs autozoom whe nthey have `type='text'`. This can be disabled with the following (https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone) however has accessibility ramifications and breaks on Androids

**Comment by PPHelios** [comment]
I'm facing the same issue on android, when i open a modal I can't use pinch to zoom (I'm using it as a carousel).

**Comment by rtivital** [comment]
Scaling is controlled by this meta tag:

```html
<meta
  name="viewport"
  content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
/>
```

If you would like to keep scaling, remove `user-scalable=no`:

```html
<meta
  name="viewport"
  content="minimum-scale=1, initial-scale=1, width=device-width"
/>
```

**Comment by PPHelios** [comment]
I already don't have " user-scalable=no",
and zooming is working fine on the website except when i open a modal.

**Comment by rtivital** [comment]
I've found the options on react-remove-scroll to enable pinch to zoom – https://github.com/theKashey/react-remove-scroll#usage
I'll add an option to customize these settings in one of the next releases.

**Comment by rtivital** [comment]
You can now pass props to RemoveScroll component with `removeScrollProps` in Modal ddn Drawer components
