### ISSUE TITLE
Hopefully there will still be memo to optimize the TabsPanel

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#5118]
### What package has an issue

@mantine/core

### Describe the bug

I'd like to optimize the panel component, with a layer of memo

list only has two members, but it's hard to switch between them

```jsx
 {!isEmpty(list) &&
        list.map((tab, index) => (
          <Tabs.Panel value={String(index)} pt="xs" key={index}>
            <Other
              defaultVisible={commonVisible}
              dataIndex={tab.dataIndex}
              onCreateTab={onCreateTab}
              formValues={tab.formValues}
              updateList={updateList}
              index={index}
            />
          </Tabs.Panel>
        ))}
```

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.x

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Please do not open issues with unclear problems – these issues are usually closed. If you have a question, you can open a discussion. If you want to report a bug with the library, please be sure to include a reproduction.
