### ISSUE TITLE
[Feature Request] TransferList add Grouping items

### ISSUE THREAD

**Issue by ruessej** [mantinedev/mantine#512]
Add group to the TransferList like Select, MultiSelect ...

**Comment by Ultra-Instinct-05** [comment]
Can you elaborate more on what do you mean by "group" ? Are you perhaps referring to a "select all" kind of checkbox ?

**Comment by ruessej** [comment]
I mean to visual group them like Select (https://mantine.dev/core/select/#grouping-items)

![image](https://user-images.githubusercontent.com/85690286/145832564-1f2a5a06-fff0-4cd2-8d72-ffbc430d96ba.png)

**Comment by rtivital** [comment]
Fixed in 3.5.0
