### ISSUE TITLE
For Text component unitless size prop leads to giant line-height

### ISSUE THREAD

**Issue by ivandenysenko** [mantinedev/mantine#5125]
### What package has an issue

@mantine/core

### Describe the bug

When using size without units in Text component

```<Text size="10">```

`line-height` property is equal to `size` value, which is multiplication of `font-size` and leads to such kind of results:

<img width="917" alt="Screenshot 2023-10-25 at 17 10 57" src="https://github.com/mantinedev/mantine/assets/795560/2e942c72-25b4-4eea-8489-947d8d648718">

Is this made on purpose? And if such, what is the use case?

And if it is a bug, the simplest way is always `line-height` to convert to `rem` in `get-size` module.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.5

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

```diff --git a/src/mantine-core/src/core/utils/get-size/get-size.ts b/src/mantine-core/src/core/utils/get-size/get-size.ts
index 2ed74510b..0f11b297c 100644
--- a/src/mantine-core/src/core/utils/get-size/get-size.ts
+++ b/src/mantine-core/src/core/utils/get-size/get-size.ts
@@ -1,16 +1,12 @@
 import { isNumberLike } from '../is-number-like/is-number-like';
 import { rem } from '../units-converters';
 
-export function getSize(size: unknown, prefix = 'size', convertToRem = true): string | undefined {
+export function getSize(size: unknown, prefix = 'size'): string | undefined {
   if (size === undefined) {
     return undefined;
   }
 
-  return isNumberLike(size)
-    ? convertToRem
-      ? rem(size)
-      : (size as string)
-    : `var(--${prefix}-${size})`;
+  return isNumberLike(size) ? rem(size) : `var(--${prefix}-${size})`;
 }
 
 export function getSpacing(size: unknown) {
@@ -30,7 +26,7 @@ export function getFontSize(size: unknown) {
 }
 
 export function getLineHeight(size: unknown) {
-  return getSize(size, 'mantine-line-height', false);
+  return getSize(size, 'mantine-line-height');
 }
 
 export function getShadow(size: unknown) {```

**Comment by rtivital** [comment]
Text component size prop supports only `xs`, `sm`, `md`, `lg` and `xl` values. It is used to set both font-size and line-height values. You can use `fz` and `lh` props separately in case you need to set these properties separately. It is not planned to support other values in `size` prop.

**Comment by ivandenysenko** [comment]
@rtivital got it.
Why not leaving `size?: MantineSize` type then? It will warn in case other than `MantineSize` string passed. What is the purpose of `(string & {})` ?

**Comment by rtivital** [comment]
`(string & {})` allows adding custom sizes, for example, you can add `xxs` or `2xl` size.
Example – https://mantine.dev/styles/variants-sizes/#sizes-with-components-css-variables
