### ISSUE TITLE
Button styling bug @7.1.6

### ISSUE THREAD

**Issue by bricesuazo** [mantinedev/mantine#5128]
### What package has an issue

@mantine/core

### Describe the bug

Here's the repro:

https://stackblitz.com/edit/stackblitz-starters-35lkqp

![image](https://github.com/mantinedev/mantine/assets/74240706/1b71dd49-dbfe-4ff7-97a1-f8acd9ee77e7)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://stackblitz.com/edit/stackblitz-starters-35lkqp

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in 7.1.7
