### ISSUE TITLE
SegmentedControl unexpected behavior with Next js

### ISSUE THREAD

**Issue by ibatukhtin** [mantinedev/mantine#5129]
### What package has an issue

@mantine/core

### Describe the bug

When the state changes outside of SegmentedControl then the previous state in SegmentedControl is not selected after that.

everything works fine with react
https://codesandbox.io/s/blissful-poincare-zz9t2k

but not work with next js
https://codesandbox.io/p/sandbox/naughty-moon-vz8djp

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.6

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/sandbox/naughty-moon-vz8djp

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by dmityabondar** [comment]
Hello! Got the same problem

**Comment by Zachary-Kaye** [comment]
Just a heads up, upgrading to Next.js 14 (without any other changes to the supplied sandbox: https://codesandbox.io/p/sandbox/naughty-moon-vz8djp) seems to resolve this issue. See here: https://codesandbox.io/p/sandbox/async-star-l3zmht

**Comment by rtivital** [comment]
Thanks for reporting @Zachary-Kaye
