### ISSUE TITLE
Inputs with section width set to "auto" removes all paddings

### ISSUE THREAD

**Issue by th3fallen** [mantinedev/mantine#5132]
### What package has an issue

@mantine/core

### Describe the bug

If you provide `rightSectionWidth="auto"` all paddings will be removed from the input.

while i can understand the right side paddings getting stripped since they're based off of that width i can't find how or why the left side paddings are also removed?

Example:
https://codesandbox.io/p/sandbox/hidden-glade-x9ld6c

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/sandbox/hidden-glade-x9ld6c

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
It is expected behavior, sections have absolute position and input offset is based on a given width value. If you set `rightSectionWidth="auto"`, it will set `padding-right: auto` on the input, which does not work. It is not planned to be changed.
