### ISSUE TITLE
[Calendar] Custom styles demo - Next month button doesn't work 

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#514]
- What package has an issue (@mantine/core, mantine/hooks or other)? @mantine/dates
- What package version are you using? 3.4.0
- In which browser and operating system issue occurred? Windows 11 Brave@96.0.4664.93
- If possible please attach link to codesandbox with reproduced issue: https://mantine.dev/dates/calendar/#customize-with-styles-api
- Do you have an idea how to fix the issue? Yes remove the ```month={value}```

**Comment by rtivital** [comment]
Fixed
