### ISSUE TITLE
useHash using empty string in the first render

### ISSUE THREAD

**Issue by iGoodie** [mantinedev/mantine#5140]
### What package has an issue

@mantine/hooks

### Describe the bug

`useHash` renders with `""` in the first render, making it impossible to declare initial state values with it.
Here's an overly simplified version of my case:

```ts
  const [hash, setHash] = useHash();

  const [currentTab, setCurrentTab] = useState(isValidTab(hash) ? hash : Tabs.DESCRIPTION);
```

However, since internally its initial value is set as an effect on the second render, I can't use it as a barebone for a state initializer.
https://github.com/mantinedev/mantine/blob/b10a09646e3359b144e6b3ad57db6c1bdfa71a8d/src/mantine-hooks/src/use-hash/use-hash.ts#L20-L22

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.0.21

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

My solution suggestion would be to replace the following line:
https://github.com/mantinedev/mantine/blob/b10a09646e3359b144e6b3ad57db6c1bdfa71a8d/src/mantine-hooks/src/use-hash/use-hash.ts#L5
with
```ts
  const [hash, setHash] = useState(window.location.hash);
```

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1). See https://mantine.dev/hooks/use-hash/#initial-state-value

**Comment by iGoodie** [comment]
Isn't this statement reversed? @rtivital 

https://github.com/mantinedev/mantine/blob/5f2b2150afed4d51a0b6ce50b626bf5c398dbf78/src/mantine-hooks/src/use-hash/use-hash.ts#L8-L11

If the option to use `useEffect` is set, it uses immediately from window. I think it should be the opposite
```js
getInitialValueInEffect ? '' : window.location.hash || '' 
```

**Comment by rtivital** [comment]
Thanks for reporting, the issue will be resolved in the next minor release
