### ISSUE TITLE
Event not fired in Select component

### ISSUE THREAD

**Issue by uporot1k** [mantinedev/mantine#5147]
### What package has an issue

@mantine/core

### Describe the bug

Hi!

We encountered a problem with popup events in the input returned from the ref component Select

Expected behavior:
When the value in the Select component changes, an event will pop up in the internal input that is returned via ref

Current behavior:
When the value in the Select component is changed, no event pops up in the internal input that is returned via ref

I have created a reproduction where I have shown the problem on the example of Input and Select component

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/damp-lake-6hdvgf?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Events do not fire because there are no events from the user – nothing is entered inside the field. It is expected behavior.
