### ISSUE TITLE
Rich text edit placeholder

### ISSUE THREAD

**Issue by rafbgarcia** [mantinedev/mantine#5148]
### What package has an issue

_Not sure if this is an issue for Mantine or Tiptap itself._

@mantine/tiptap

### Describe the bug

Rich text editor does not adjust height when placeholder has multiple lines:

<img width="717" alt="Team_members___GrowinCo" src="https://github.com/mantinedev/mantine/assets/1904314/6f2d4572-aa0c-4f6e-bcd9-bfd3ace4170d">

- Tiptap v2.1.12
- Mantine v7.1.7

```tsx
import { Box, Text, TextareaProps } from "@mantine/core"
import { RichTextEditor } from "@mantine/tiptap"
import { useEditor } from "@tiptap/react"
import StarterKit from "@tiptap/starter-kit"
import Placeholder from "@tiptap/extension-placeholder"

const Editor = ({ value, onChange, placeholder }: TextareaProps) => {
  const editor = useEditor({
    extensions: [StarterKit, Placeholder.configure({ placeholder })],
    content: value?.toString(),
    onUpdate(props) {
      onChange && onChange(props.editor.getHTML() as any)
    },
  })

  return (
    <RichTextEditor editor={editor}>
      <RichTextEditor.Toolbar>
        <RichTextEditor.ControlsGroup>
          <RichTextEditor.Bold />
          <RichTextEditor.Italic />
          <RichTextEditor.Strikethrough />
          <RichTextEditor.ClearFormatting />
        </RichTextEditor.ControlsGroup>

        <RichTextEditor.ControlsGroup>
          <RichTextEditor.H1 />
          <RichTextEditor.H2 />
          <RichTextEditor.H3 />
          <RichTextEditor.H4 />
        </RichTextEditor.ControlsGroup>

        <RichTextEditor.ControlsGroup>
          <RichTextEditor.Hr />
          <RichTextEditor.BulletList />
          <RichTextEditor.OrderedList />
        </RichTextEditor.ControlsGroup>
      </RichTextEditor.Toolbar>

      <RichTextEditor.Content fz={"sm"} />
    </RichTextEditor>
  )
}
```

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.7

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by ronit044** [comment]
hey there!!
As I can see, there is no declaration of height adjustment statements in the code segment shown as a result of which it is not adjusting the height automatically.
I can rectify this issue. 
Kindly assign it to me!!

**Comment by rtivital** [comment]
Placeholder is implemented according to TipTap documentation – https://tiptap.dev/api/extensions/placeholder
I cannot think of any way of fixing this issue.

**Comment by rafbgarcia** [comment]
FWIW this is how I dealt with it:

```css
.content > div > div {
  min-height: rem(100);
}
```

```tsx
    <RichTextEditor editor={editor}>
      <RichTextEditor.Content className={classes.content} />
    </RichTextEditor>
```

**Comment by rtivital** [comment]
I was not able to find the solution for the issue based on how placeholder works in tiptap. It is not planned to implement the fix on the library side.
