### ISSUE TITLE
PasswordInput inside a disabled AppShell have cursor: not-allowed

### ISSUE THREAD

**Issue by Yhprum** [mantinedev/mantine#5149]
### What package has an issue

@mantine/core

### Describe the bug

My PasswordInput has css `cursor: not-allowed` which is executed because the AppShell has the `data-disabled` attribute

Component's css from mantine
```
.m-f2d85dd2:disabled, [data-disabled] .m-f2d85dd2 {
  cursor: not-allowed;
}
```

Minimum reproduction
```
<AppShell disabled>
  <PasswordInput />
</AppShell>
```

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^7.1.2

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1).
