### ISSUE TITLE
Can't use component prop on TextInput

### ISSUE THREAD

**Issue by mg-aceik** [mantinedev/mantine#5153]
### What package has an issue

@mantine/core

### Describe the bug

Assigning `component` to a TextInput throws a typescript warning

```
Type '{ component: string; }' is not assignable to type 'IntrinsicAttributes & TextInputProps & RefAttributes<HTMLInputElement>'.
  Property 'component' does not exist on type 'IntrinsicAttributes & TextInputProps & RefAttributes<HTMLInputElement>'.
```

It does actually work fine, seems to just be an issue with the types.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.7

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/quizzical-architecture-gmnrsw?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
`component` prop is available only on polymorphic components. If you need that with input, use InputBase component instead – https://mantine.dev/core/input/#inputbase-component
