### ISSUE TITLE
Style Nonce for 7.x

### ISSUE THREAD

**Issue by SkyHyve** [mantinedev/mantine#5156]
### What package has an issue

@mantine/core

### Describe the bug

In 6.x, once could pass a nonce to emotionCacheProvider to allow for the styles to have the nonce, however with the chances in 7.x, there is no cacheProvider to user. The docs seem to suggest adding an attribute to MantineProvider called 'getStyleNonce' that is a function returning a string. Despite doing this, there seems to not be any nonc eadded to the '<style data-mantine-styles="true'> which I assume is the style tag this is supposed to have the nonce added to.

Thanks

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.7

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by jonisapp** [comment]
I am face with the same issue. Have you found a way to solve it ?
