### ISSUE TITLE
styles prop no longer works after migrating to 7.0

### ISSUE THREAD

**Issue by SkyHyve** [mantinedev/mantine#5158]
### What package has an issue

@mantine/core

### Describe the bug

After migrating to 7.0 (7.1.7) from 6.x I have noticed that the styles prop
e.g.
`              <Button
                styles={{
                  root:{
                    left: '12.5%',
                    top: '10%',
                    height: '80%',
                    width: '25%',
                    backgroundColor: 'var(--bs-dark)',
                    border: '1px solid #FFFFFF',
                    fontSize: '6ex',
                  }
                }}`
No longer works, this seems to be the case for all styles props in the entire application. Documentation for 7.0 seems to suggest this should still work. I also tried using the classNames prop but same result, the elements don't seem to be having any styles added. There are some other issues aswell that might be related, such as BackroundImage not having any styles for 'backround-image' added when using the 'src' prop

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

**Comment by rtivital** [comment]
`styles` prop works correctly on codesandbox – https://codesandbox.io/s/elegant-swirles-dg4sdd?file=/src/App.tsx
