### ISSUE TITLE
Numberinput doesn't trigger a onChange

### ISSUE THREAD

**Issue by ruessej** [mantinedev/mantine#516]
I am not sure if this is really a problem.

If you have precision on for example 2 and you write a number like 0.0012 and then blur the input field the value of the state is still 0.0012 but the UI shows 0.00

- What package has an issue (@mantine/core, mantine/hooks or other)? @mantine/core
- What package version are you using? 3.4.0
- In which browser and operating system issue occurred? Windows 10 Edge@96.0.1054.53
- If possible please attach link to codesandbox with reproduced issue: https://codesandbox.io/s/nice-moore-4tgf3

![image](https://user-images.githubusercontent.com/85690286/146034528-157483d8-838e-4332-be03-871516893eab.png)

**Comment by rtivital** [comment]
Thanks for reporting, I'll try to fix it, but you (or anyone else) are welcome to contribute this feature if “Help wanted” label is still on the issue

**Comment by rtivital** [comment]
Fixed in 3.4.1
