### ISSUE TITLE
Mantine overrides some css properties

### ISSUE THREAD

**Issue by yusufulusoy** [mantinedev/mantine#5161]
### What package has an issue

@mantine/core

### Describe the bug

When I want to use some css properties and variables from mantine, component's original css properties overrides my custom css.

For example in this case from Mantine UI: https://ui.mantine.dev/category/headers/#header-mega-menu
UnstyledButton's overrides custom css paddings and looks like this: 

<img width="637" alt="Screenshot 2023-10-31 at 18 01 29" src="https://github.com/mantinedev/mantine/assets/16897237/d47d17e7-eb3c-4492-9061-daf34024e8a5">

<img width="332" alt="Screenshot 2023-10-31 at 17 57 56" src="https://github.com/mantinedev/mantine/assets/16897237/a63d40fc-f99e-4c18-b218-8b778f1fe178">

Do I always have to use !important when writing CSS in such results, or is there another solution?

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

@mantine/*

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
If you have issues with styles import order, use CSS layers – https://mantine.dev/styles/mantine-styles/#css-layers
