### ISSUE TITLE
MultiSelect `required` not validating 

### ISSUE THREAD

**Issue by jamestouri** [mantinedev/mantine#5162]
### What package has an issue

@mantine/core

### Describe the bug

I have a form where I have both inputs as required

```
    <form
      onSubmit={(e: React.SyntheticEvent) => {
        e.preventDefault();
        console.log(e.target);
      }}
    >
      <TextInput
        id={"name"}
        label={"Name"}
        name={"name"}
        required
        value={text}
        onChange={(e) => setText(e.target.value)}
      />
      <MultiSelect
        label="Your favorite libraries"
        placeholder="Pick value"
        required
        data={["React", "Angular", "Vue", "Svelte"]}
        value={multi}
        onChange={setMulti}
      />
      <Button type="submit">Submit</Button>
    </form>
```

The TextInput correctly checks if there is value in the input however MultiSelect doesn't. 

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.7

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
MultiSelect as well as other Combobox based components do not support native browser validation. You can use use-form hook or other form library to perform validation. It is not planned to be changed.
