### ISSUE TITLE
release/tag mismatch in 7.1.7

### ISSUE THREAD

**Issue by jgravois** [mantinedev/mantine#5163]
### What package has an issue

@mantine/core

### Describe the bug

https://github.com/mantinedev/mantine/releases/tag/7.1.6

![Screenshot 2023-10-31 at 10 55 29 AM](https://github.com/mantinedev/mantine/assets/3011734/1e844ed3-588d-4735-b6de-bedcd9f832ce)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.7

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

create a `v7.1.7` tag that points at the exact same SHA

**Comment by rtivital** [comment]
It is not planned to be fixed
