### ISSUE TITLE
`RichTextEditor.Link` missing key `control` in `styles` and `classNames` props although functionality works

### ISSUE THREAD

**Issue by HariVP03** [mantinedev/mantine#5171]
### What package has an issue

@mantine/tiptap

### Describe the bug

The `RichTextEditor.Link` component accepts a key in the `styles` or `classNames` like other Rich Text Button if someone wants to override the default styles. However, the type does not have the `control` key and I had to `@ts-ignore` it.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.7

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Add the `control` key in the type for `RichTextEditor.Link` for `styles` and `classNames` props

**Comment by rtivital** [comment]
Fixed in [7.3.1](https://github.com/mantinedev/mantine/releases/tag/7.3.1)
