### ISSUE TITLE
Border-radius for Modal component compilation error

### ISSUE THREAD

**Issue by ivandenysenko** [mantinedev/mantine#5174]
### What package has an issue

@mantine/core

### Describe the bug

In Modal component prop `radius` you can pass _any valid CSS value_.

However, in case passing a shorthand for constituent properties (e.g. `radius="0 0 1rem 1rem"`) it will be compiled to: 

`--paper-radius: calc(0 0 1rem 1rem * var(--mantine-scale));`

 which is not valid css value and ignored by browser.

Clearly it was meant for using 1 value, but also docs says _any valid CSS value_ can be passed.

P.S. Of course passing `radius="1rem"` works as expected.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I believe the expected result would be `--paper-radius: 0 0 calc(1rem * var(--mantine-scale)) calc(1rem * var(--mantine-scale))`

From what I can see, it is handled in `utils/get-size/get-size.ts` and also can be relevant to other similar cases, not just this prop and this component.

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1).
