### ISSUE TITLE
Not specifying the language prop in CodeHighlightTabs causes a crash

### ISSUE THREAD

**Issue by jesse-r2c** [mantinedev/mantine#5178]
### What package has an issue

@mantine/code-highlight

### Describe the bug

The [language prop](https://github.com/mantinedev/mantine/blob/master/src/mantine-code-highlight/src/CodeHighlightTabs.tsx#L48) in `CodeHighlightTabs` is defined as optional, but not setting that property causes a crash.

![image](https://github.com/mantinedev/mantine/assets/99560876/3ab1f0c6-efe9-4d9b-bced-3c9320022069)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.7

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/condescending-https-mzkldz?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

- Make `language` a required prop
- Add a fallback to `plaintext` if language is undefined

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1).
