### ISSUE TITLE
Rich text editor within Fieldset

### ISSUE THREAD

**Issue by rafbgarcia** [mantinedev/mantine#5179]
### What package has an issue

@mantine/core

### Describe the bug

When placed inside a fieldset, the rich text editor grows to fit its content.

See codesandbox.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.7

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mutable-river-w89qsc?file=/src/App.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

The issue seems to be with `min-inline-size: min-content;` that's applied to the fieldset tag.

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1).
