### ISSUE TITLE
Usage with ScrollArea not working in Mantine docs

### ISSUE THREAD

**Issue by Sajarin-M** [mantinedev/mantine#5189]
### Discussed in https://github.com/orgs/mantinedev/discussions/5187

<div type='discussions-op-text'>

<sup>Originally posted by **Sajarin-M** November  4, 2023</sup>
![image](https://github.com/mantinedev/mantine/assets/68892162/b4a96d49-0755-4eb9-ac85-ad7e01094224)
</div>

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1).
