### ISSUE TITLE
Alert component without children

### ISSUE THREAD

**Issue by mnakhli** [mantinedev/mantine#5196]
### What package has an issue

@mantine/core

### Describe the bug

In Alert component, when we remove children, there is more distance from the bottom of the title to the frame border.
<img width="639" alt="Screenshot 1402-08-15 at 10 32 59" src="https://github.com/mantinedev/mantine/assets/21153535/0f3140d7-3f2d-4169-a587-0a20b7e2b903">

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

latest

### If possible, please include a link to a codesandbox with the reproduced problem

https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/Alert/Alert.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

You should give the children the **margin-top** instead of the title the margin-bottom.

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1).
