### ISSUE TITLE
MantineProvider becoming required in v7

### ISSUE THREAD

**Issue by filiptammergard** [mantinedev/mantine#5198]
### What package has an issue

@mantine/core

### Describe the bug

Hey!

When trying to upgrade to v7, I noticed that `<MantineProvider>` is required: https://codesandbox.io/s/romantic-poincare-cx9h83?file=/src/App.tsx

In v6, it's not: https://codesandbox.io/s/funny-chatelet-247n6r?file=/src/App.tsx

Is that intended? I can't find anything about that in the changelog or upgrade guide.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.7

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/romantic-poincare-cx9h83?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Yes, it is intended.

**Comment by filiptammergard** [comment]
What functionality is dependent on MantineProvider, that wasn't required in v6?

**Comment by rtivital** [comment]
Color scheme manager, css variables resolving
