### ISSUE TITLE
Table.Thead has body color as background-color

### ISSUE THREAD

**Issue by DammersCode** [mantinedev/mantine#5215]
### What package has an issue?

@mantine/core

### Describe the bug

The table header has an unexpected mantine-color-body as background-color.
![image](https://github.com/mantinedev/mantine/assets/87079296/71d81bd9-fd63-48fe-b7f3-7d462ba25174)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.0

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by rtivital** [comment]
It is intended for tables with sticky header. You can override background-color with Styles API if it does not fit in your application.
