### ISSUE TITLE
SrollArea.Autosize does not work with Modal

### ISSUE THREAD

**Issue by Akela114** [mantinedev/mantine#5216]
### What package has an issue
@mantine/core

### Describe the bug
Native scrollbar is used in **Modal** even if **SrollArea.Autosize** component is passed as a value of _scrollAreaComponent_ prop.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)
7.2.0

### If possible, please include a link to a codesandbox with the reproduced problem
[https://codesandbox.io/s/gracious-borg-45q7vk?file=/src/App.js:469-501](url)

**Comment by rtivital** [comment]
Fixed in [7.2.1](https://github.com/mantinedev/mantine/releases/tag/7.2.1).
