### ISSUE TITLE
validateInputOnBlur does not update errors on NumberInput blur using zodResolver

### ISSUE THREAD

**Issue by MartinMuzatko** [mantinedev/mantine#5217]
### What package has an issue?

@mantine/form

### Describe the bug

`validateInputOnBlur` does not update errors for invalid NumberInputs when clicking away or tabbing out of the input. 

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.0

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/s/adoring-newton-pt79dw?file=/src/Demo.tsx

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

Yes

### Possible fix

onBlur is consumed in NumberInput component. I can also set a manual onBlur event handler and that works fine.
It could happen here, when the resolver not report back correctly or the function?
https://github.com/mantinedev/mantine/blob/master/src/mantine-form/src/use-form.ts#L214

**Comment by rtivital** [comment]
Fixed in [7.2.2](https://github.com/mantinedev/mantine/releases/tag/7.2.2)

**Comment by MartinMuzatko** [comment]
That was quick! Thank you very much :)
