### ISSUE TITLE
Deleting a row form that contains <Select> transfers value to below <Select>

### ISSUE THREAD

**Issue by PFernandezTorres** [mantinedev/mantine#5221]
### What package has an issue?

@mantine/form

### Describe the bug

I am using Form package along Core package to build a Form containing three rows with each three <NumberInputs> and one <Select> with two buttons for deleting and duplicate row. When a value has been selected for the <Select> component, and immediately deleting that row, all the values have been deleted successfully but the <Select> value remains untouched in the row below. Also the value is not selected but only displayed, if the <Select> is clicked to see its options, none of the options appear to have the tick icon. 

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

"@mantine/core": "7.1.7", "@mantine/form": "^7.2.1", "@mantine/hooks": "7.1.7"

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

### Possible fix

Do not know how to fix it.

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx

**Comment by PFernandezTorres** [comment]
Sorry for not providing the sandbox, haven't had any time. Were you able to fix the issue or do you need the example code. If it is necessary I will provide the necessary information. Sorry for the inconvenience

**Comment by rtivital** [comment]
Issues without reproduction are closed after a certain period of time. If you can provide a sandbox with reproduction, you are welcome to reopen the issue.

**Comment by PFernandezTorres** [comment]
Here is the link with the reproduction: [https://codesandbox.io/s/nice-resonance-vnj8qy](https://codesandbox.io/s/nice-resonance-vnj8qy)

**Comment by PFernandezTorres** [comment]
@rtivital this is the URL of the reopened issue: [https://github.com/mantinedev/mantine/issues/5241](https://github.com/mantinedev/mantine/issues/5241)
