### ISSUE TITLE
MultiSelect validation fails when using required and searchable props together

### ISSUE THREAD

**Issue by joemcg617** [mantinedev/mantine#5222]
### What package has an issue?

@mantine/core

### Describe the bug

Adding the `required` and `searchable` properties at the same time to a MultiSelect component will break form validation.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.0

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/s/mantine-multiselect-validation-issue-smwvy4?file=/src/Form.tsx

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

### Possible fix

Overwrite/filter out the `required` prop on the MultiSelect's search input field component

**Comment by rtivital** [comment]
MultiSelect, as well as other Combobox based components, does not support native browser validation. If you want to provide an indication that the field is required, use `withAsterisk` instead – https://codesandbox.io/s/mantine-multiselect-validation-issue-forked-6hl3hp?file=/src/Form.tsx
