### ISSUE TITLE
Rich text editor RTL issue

### ISSUE THREAD

**Issue by CripyIce** [mantinedev/mantine#5223]
### What package has an issue?

@mantine/tiptap

### Describe the bug

The editor's menu buttons border are shown incorrectly in RTL - you can see it at the docs (https://mantine.dev/others/tiptap/).

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.1

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
Fixed in [7.2.2](https://github.com/mantinedev/mantine/releases/tag/7.2.2)
