### ISSUE TITLE
Incorrect Mantine Version in Installation Code on v6 Documentation Page

### ISSUE THREAD

**Issue by CodePhilanthropist** [mantinedev/mantine#5226]
### Link to the page where something is not right

https://v6.mantine.dev/pages/getting-started/

### Exact quote of what is wrong

 
**Bug Description:**
When users visit the v6 documentation page at the provided URL and attempt to copy the code for installing Mantine, the generated code refers to version v7 instead of v6. This is misleading and may cause users to unintentionally install the wrong version.

**Expected Behavior:**
The installation code on the v6 documentation page should generate code for installing Mantine v6, corresponding to the version of the documentation being viewed.

Like:
`npm install @mantine/core@6 @mantine/hooks@6 @emotion/react`

**Steps to Reproduce:**
1. Visit [https://v6.mantine.dev/pages/getting-started/](https://v6.mantine.dev/pages/getting-started/)
2. Locate the code snippet for installing Mantine.
3. Copy the code and observe that it refers to Mantine v7 instead of v6.

**Additional Information:**
- This issue may cause confusion for users relying on the v6 documentation.
- It is essential to ensure consistency between the documentation version and the generated code to prevent users from unintentionally using the wrong version.

**Screenshot:**
![Bug Screenshot](https://i.imgur.com/StEYy71.png)

*Please resolve this issue to provide users with accurate and version-specific installation instructions since most users are still using the old mantine styles api.*

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix – https://github.com/rtivital/mantine-v6-docs
I'm not planning to work on it myself.
