### ISSUE TITLE
Chevron icons and borders in Transfer list component

### ISSUE THREAD

**Issue by mnakhli** [mantinedev/mantine#5227]
### What package has an issue?

@mantine/core

### Describe the bug

Chevron icons and borders is incorrect at [Transfer list component](https://mantine.dev/combobox/?e=TransferList) when dir is RTL:
<img width="1049" alt="image" src="https://github.com/mantinedev/mantine/assets/21153535/58b9ab1d-8bcc-460d-887e-191660bee3a4">

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

latest

### Do you know how to fix the issue

Yes

### Do you want to send a pull request with a fix?

No

**Comment by rtivital** [comment]
Fixed in [7.2.2](https://github.com/mantinedev/mantine/releases/tag/7.2.2)

**Comment by mnakhli** [comment]
What happened?
Did you just remove RTL option on the examples page
or
It's not possible to RTL this component completely?
If it's not possible, this should happen for the checkboxes inside.

**Comment by rtivital** [comment]
It is possible to add support for rtl. I do not want to maintain it on the examples page. In your application, you can change styles to match the requirements.
