### ISSUE TITLE
Template repository with NX, GraphQL, Storybook, CSS Modules, Mantine and React Hook Form

### ISSUE THREAD

**Issue by dipiash** [mantinedev/mantine#5229]
### Link to the repository on GitHub

https://github.com/dipiash/nx-vite-react-ts-mantine-boilerplate

### Features of the template, describe how it is different from other templates

NX monorepo with: Vite, GraphQL / Apollo, Typescript, Storybook / CSS Modules / Mantine, React Hook Form

Contain the real app example to work GitHub GraphQL API that allow view repositories list with different filters

**Comment by rtivital** [comment]
Thanks for submitting the template! It will be available on the getting started page with the next patch.
