### ISSUE TITLE
Nested fields in `useForm` error without `initialValues`

### ISSUE THREAD

**Issue by zubendan** [mantinedev/mantine#5232]
### What package has an issue?

@mantine/form

### Describe the bug

when defining a form schema for `useForm` with nested fields , if no `initialValues` are provided for the nested fields the application crashes when the input is typed in because "val" is undefined

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.1

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-nested-fields-test-v389qt?file=%2Fsrc%2Fform.tsx%3A12%2C38

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
It is intended behavior. `@mantine/form` is a fully controlled form – all initial values are required.
