### ISSUE TITLE
DatePickerInput styling not working in 7.2

### ISSUE THREAD

**Issue by igomest** [mantinedev/mantine#5233]
### What package has an issue?

@mantine/core

### Describe the bug

I'm trying to use the DatePickerInput component, using the latest version of Mantine.

But the styling isn't working.

If I'm missing some configuration, can you help me?

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.1

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/nifty-rui-dd43xz?file=%2FREADME.md

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by zubendan** [comment]
you have to add `import "@mantine/dates/styles.css"` and with any part of mantine except for form and hooks you need to add `import "@mantine/<package>/styles.css`
