### ISSUE TITLE
Bug in @mantine/core RangeSlider Component with dir:rtl in HTML Tag

### ISSUE THREAD

**Issue by MonaAghili** [mantinedev/mantine#5234]
### What package has an issue?

@mantine/core

### Describe the bug

I am currently working with the latest version of Next.js, utilizing Mantine Core version "@mantine/core": "^7.1.5". An issue has surfaced with the RangeSlider component. Specifically, I've implemented dir="rtl" in the HTML tag of my layout:
```
<html lang="fa" dir="rtl"></html>
```
adding dir="ltr" to the parent div did not resolve the problem.
```
 <div className="col-span-3" dir="ltr">
    <RangeSlider
        step={1}
        min={2}
        max={30}
        color="#284B8B"
        size="sm"
        labelAlwaysOn
        defaultValue={[10, 20]}
    />
</div>
```

To illustrate the problem comprehensively, I have attached a video showcasing the issue.

https://github.com/mantinedev/mantine/assets/28711325/18d51a10-e257-4ca6-b3b9-28eca6907f2b

PS: I managed to resolve the issue temporarily by applying the following CSS and remove dir="rtl" from html:
```
html {
    direction: rtl;
  }
```
However, it's important to note that this solution is not suitable for multilingual sites where directional preferences are contingent upon the selected language.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.5

**Comment by rtivital** [comment]
You need to follow rtl guide – https://mantine.dev/styles/rtl/
You did not add DirectionProvider to your application.
