### ISSUE TITLE
Using suffix in a controlled NumberInput triggers onChange when a value prop is changed programatically

### ISSUE THREAD

**Issue by dryu** [mantinedev/mantine#5235]
### What package has an issue?

@mantine/core

### Describe the bug

When a controlled NumberInput is used with a suffix, changing its value externally (programmatically) causes onChange to be triggered, which is unexpected. Without a suffix prop, onChange is not triggered, which is expected.

To illustrate this, please refer to the linked codesandbox. To reproduce:
- Open a sandbox
- Click on "Set value to 1" button. Notice that the control is now set to "35" and further clicks on buttons are not doing anything.
- Remove the suffix prop from the code.
- Now try clicking on buttons again - the value in the NumberInput should now be changing as expected.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.1

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/s/romantic-morse-69shyf?file=/src/App.tsx:401-424

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by rtivital** [comment]
Fixed in [7.2.2](https://github.com/mantinedev/mantine/releases/tag/7.2.2)
