### ISSUE TITLE
Autocomplete returns label even if a value is specified in the data prop

### ISSUE THREAD

**Issue by aaly00** [mantinedev/mantine#5238]
### What package has an issue?

@mantine/core

### Describe the bug

In the autoComplete component. When you specify a value prop, it's ignored and you get the label inside the onchange. 

```jsx
  <Autocomplete
     miw="8.5rem"
     label="Make"
    data={[
      {
        label: "Mantine",
        value: "1234",
        },
       ]}
      onChange={(value) => {
       console.log(value)       //Mantine. Should be 1234
      }}
    />
```

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.1

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by rtivital** [comment]
It is intended behavior, see data formats documentation – https://mantine.dev/core/autocomplete/#data-formats
If you need to get value in onChange, use searchable Select instead.
