### ISSUE TITLE
hover does not work with styles api

### ISSUE THREAD

**Issue by smyja** [mantinedev/mantine#5239]
### What package has an issue?

@mantine/core

### Describe the bug

I have been trying to set hover for the button and it doesn't work, its not being recognized as a valid variable
```
        <Button
                styles={{
                  root:
                  {
                    "width": 250,
                    "backgroundColor": "black",
                    "color": "white",
                    "&:hover": {
                      "backgroundColor": "gray"
                    }
                  },
                }}
                leftSection={<IconFile size={14} />}
                variant="default">Documents</Button>
```

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.3

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
Starting from version 7.0 nested selectors are not supported in `styles` property, use `classNames` instead.
