### ISSUE TITLE
RTL issues

### ISSUE THREAD

**Issue by CripyIce** [mantinedev/mantine#5250]
### What package has an issue?

@mantine/core

### Describe the bug

- Icons and text have no space between them - https://mantine.dev/core/segmented-control/#react-node-as-label
![image](https://github.com/mantinedev/mantine/assets/26387823/6cbb7285-530f-4251-8d18-64e6820c2873)

- No space between text and divider - https://mantine.dev/core/autocomplete/#group-options
![image](https://github.com/mantinedev/mantine/assets/26387823/d1168847-6a9f-4879-ac0a-aa3d8eecc6b1)

- Text is too close to the edge - https://mantine.dev/core/pill/
![image](https://github.com/mantinedev/mantine/assets/26387823/d7ef0fcf-699e-49bd-aa02-92bbf0126f88)

- Text stays on the left (also in nested) - https://mantine.dev/core/nav-link/
- No padding for the content - https://mantine.dev/core/tabs/#vertical-tabs-placement
![image](https://github.com/mantinedev/mantine/assets/26387823/9f10de32-df06-4f93-b601-0454856695d9)

- Extra padding on the right - https://mantine.dev/core/drawer/
![image](https://github.com/mantinedev/mantine/assets/26387823/beae6c4a-3fd2-4e69-bee9-70979c3dc25f)

- Extra padding on the right and too close to the edge on the left - https://mantine.dev/core/modal/#fullscreen
![image](https://github.com/mantinedev/mantine/assets/26387823/321db790-c44c-4748-88b2-795eb0ebb6d8)
![image](https://github.com/mantinedev/mantine/assets/26387823/c3393597-4ea7-45d1-8206-30c3f52613f4)

- Positions start/end are not truly working - https://mantine.dev/core/indicator/
![image](https://github.com/mantinedev/mantine/assets/26387823/890b2e1d-940b-435e-87b5-f149ac8cfee0)

- Order is incorrect (should be command->shift->m rather then command->m->shift) - https://mantine.dev/core/kbd/
- “Show more” stays in the left - https://mantine.dev/core/spoiler/
![image](https://github.com/mantinedev/mantine/assets/26387823/c3b00cf4-c8bb-44fc-990c-6c00de577980)

- Icons and text are too close - https://mantine.dev/others/spotlight/
![image](https://github.com/mantinedev/mantine/assets/26387823/72819406-1593-4242-ae92-f4e9a06a99cc)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by aalirezamoradii** [comment]
Also for AppShellNavbar when app shell layout is alt

**Comment by abdullahahmeda** [comment]
Another issue with `<Switch />` is that the direction of the circle inside the switch (it is called the "label" in docs) is not reversed for RTL.
![image](https://github.com/mantinedev/mantine/assets/23556281/58cc2107-4218-4697-8d2b-e2a08e77fbbd)
This is how it looks in English:
![image](https://github.com/mantinedev/mantine/assets/23556281/249ba7c4-77eb-435b-b636-f05634928ae4)

**Comment by mmounirf** [comment]
@CripyIce For the segmented control component, react node as a label demo has `ml={10}` you can simply change it in your use case. 

For other issues, I'm currently looking into them and hopefully contribute with a PR

**Comment by CripyIce** [comment]
@rtivital Thanks for fixing those issues!
But regarding `Indicator`, shouldn't `start` (for example) work as left in LTR and right in RTL, because right now `start` is left in both directions.

**Comment by abdullahahmeda** [comment]
There is a problem with `rightSection` prop in `<NumberInput />`. It should be shifted to the right a bit instead of hitting the edge of the input.
![image](https://github.com/mantinedev/mantine/assets/23556281/f2399d5e-ac5c-49d3-aabe-61ce632a9a07)

**Comment by audelqua** [comment]
**drawer** element opening animation got reversed.
