### ISSUE TITLE
Styles are missing during Remix SSR

### ISSUE THREAD

**Issue by alvaro-cuesta** [mantinedev/mantine#5253]
### What package has an issue?

@mantine/core

### Describe the bug

I'm following the [Remix guide](https://mantine.dev/guides/remix/) and I noticed that styles are not properly rendering during SSR.

This is easily reproducible if you disable JavaScript. After loading, it renders a page with some base styles (e.g. background is dark for example, since I use dark mode) but there are lots of styles missing (for example, buttons have no colors).

Using the [Remix template](https://github.com/mantinedev/remix-template) exhibits the same behavior. Happens on https://mantine.dev/ too (see the "Customize components" section with JS disabled).

Unsure if this is expected, but I was under the impression Mantine would work (visually, even if no state is handled) even if SSR'd, right?

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^7.2.2

### If possible, please include a link to a codesandbox with a minimal reproduction

Cannot include CodeSandbox since this requires Remix SSR. You can use the template here https://github.com/mantinedev/remix-template (you can use "Open in a codespace").

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No (I'd be willing if I knew how to fix this)

**Comment by alvaro-cuesta** [comment]
Noticed it happens on https://mantine.dev/ too (see e.g. the "Customize components" section with JS disabled). Added to description.

**Comment by michalkvasnicak** [comment]
This seems to be caused by color theme detection based on local storage reading. If the `data-mantine-color-scheme` is missing on `html` tag then no color theme is applied.
