### ISSUE TITLE
SegmentedControl label too big in modal

### ISSUE THREAD

**Issue by dfrazao** [mantinedev/mantine#5259]
### What package has an issue?

@mantine/core

### Describe the bug

1. Create a Modal with a Segmented Control.
2. Open the modal and observe that the active value height and width are bigger than they're supposed to be. After selecting another option, the label fixes itself.
When the modal is opened:
![image](https://github.com/mantinedev/mantine/assets/26813660/23601db9-e088-4718-8c14-88fcdb41a395)
After selecting another option:
![image](https://github.com/mantinedev/mantine/assets/26813660/b8498ae6-a3bd-44c1-9f5c-08be8b19054d)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/s/fancy-cache-76mf2x?file=/src/App.tsx

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
- https://codesandbox.io/s/trusting-dust-7lg4ml?file=/src/App.tsx
- See https://github.com/mantinedev/mantine/issues/3330
