### ISSUE TITLE
Modal and comboxbox z-index

### ISSUE THREAD

**Issue by jamalsoueidan** [mantinedev/mantine#5264]
### Link to the page where something is not right

I attached screenshot

### Exact quote of what is wrong

![chrome_KpwHNYhwOn](https://github.com/mantinedev/mantine/assets/115714/d61d83a3-20c2-472e-944b-92fee3c7d924)

I tried to put the z-index to higher number, but the combox box stay visible within the modal.

### Do you want to send a pull request with a fix?

No

**Comment by jamalsoueidan** [comment]
![chrome_ZYoFhTNCdO](https://github.com/mantinedev/mantine/assets/115714/01e42124-7e4f-4036-bcc5-8267f4e77eb3)

**Comment by rtivital** [comment]
You've set `withinPortal: false` in your code. Remove it and the issue will be fixed.
