### ISSUE TITLE
@mantine/notifications: Notification stretches across screen width

### ISSUE THREAD

**Issue by Avishayy** [mantinedev/mantine#5274]
### What package has an issue?

@mantine/notifications

### Describe the bug

When spawning a new notification using `showNotification()`, the notification spans the whole width of the screen
![Screenshot_2023-11-17T17:19:42](https://github.com/mantinedev/mantine/assets/5567310/ab6bbc2e-3ffd-4461-923b-137b16c47968)

My code:
```typescript
export default function App() {
  return (
    <MantineProvider theme={theme}>
      <Notifications />
      <Router />
    </MantineProvider>
  );
}
```

And the eventual call to `showNotification()`:
```typescript
      showNotification({
        title: "Error",
        message: "Login failed",
        autoClose: false,
      });
```
(I added autoClose just so I'll be able to print screen it)

See sandbox link for reproducer

Is this the intentional behavior? [The docs](https://mantine.dev/others/notifications/#notification-props) mention nothing about this and it looks much better by default there, I can set the width of a notification manually
```typescript
      showNotification({
        style: { width: 100 },
        title: "Error",
        message: "Login failed",
      });
```

but this doesn't seem right at all

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/s/agitated-moser-4jh5px?file=/src/App.tsx

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

None

**Comment by akwirick** [comment]
Think you need to import the styles for notifications.  Same thing happened to me.

```
import '@mantine/notifications/styles.css';
```

It's up in the [Installation](https://mantine.dev/others/notifications/#installation) portion of the docs you referenced.

**Comment by Avishayy** [comment]
> Think you need to import the styles for notifications. Same thing happened to me.
> 
> ```
> import '@mantine/notifications/styles.css';
> ```
> 
> It's up in the [Installation](https://mantine.dev/others/notifications/#installation) portion of the docs you referenced.

I missed that, whoops! Thank you, it works!
