### ISSUE TITLE
NumberInput formatter not formatting the value on change

### ISSUE THREAD

**Issue by msiric** [mantinedev/mantine#5277]
### What package has an issue?

@mantine/core

### Describe the bug

I'm using the `NumberInput` component with defined formatter and parser methods (Mantine v6).
I can log the formatted value every time the input changes, but it only gets displayed on blur (similar to the demo you have in your docs: https://v6.mantine.dev/core/number-input/#parser-and-formatter).

Is there a way to apply the formatted value as soon as the input changes instead of waiting for the `onBlur` action to fire?

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

V6

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
It is not planned to release 6.x versions, this issue does not exist in 7.x
