### ISSUE TITLE
"auto" column in nested Grid is incorrect width

### ISSUE THREAD

**Issue by itsravenous** [mantinedev/mantine#5278]
### What package has an issue?

@mantine/core

### Describe the bug

"auto" columns don't take up the correct width when rendered within a Grid that is itself rendered in a Grid column. See screenshot and codesandbox.

![image](https://github.com/mantinedev/mantine/assets/1737376/1c1afbd4-78d9-46da-82f3-08a1b92792da)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/s/nervous-snowflake-7kq6nq

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
Fixed in [7.3.1](https://github.com/mantinedev/mantine/releases/tag/7.3.1)
