### ISSUE TITLE
useForm not work in 'use server' pages and components nextjs `...useForm) is not a function`

### ISSUE THREAD

**Issue by mehdiraized** [mantinedev/mantine#5281]
### What package has an issue?

@mantine/form

### Describe the bug

```
TypeError: (0 , _mantine_form__WEBPACK_IMPORTED_MODULE_10__.useForm) is not a function
```
hi
all of exports as '@mantine/form' not work in server side pages and server side components
please add to document you need use 'use client'

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

Yes

### Do you want to send a pull request with a fix?

None

### Possible fix

add 'use client'

**Comment by rtivital** [comment]
All Mantine hooks follow the same rules are react hooks, there is no need to update documentation.
