### ISSUE TITLE
MultiSelect/TagsInput (regression): placeholder doesn't dissapear in uncontrolled mode

### ISSUE THREAD

**Issue by LazyLahtak** [mantinedev/mantine#5288]
### What package has an issue?

@mantine/core

### Describe the bug

MultiSelect and TagsInput components in uncontrolled mode always have a placeholder, even if the value is not empty. The controlled mode works correctly. SingleSelect works correctly.

The issue doesn't reproduce in v6.0.21. Reproduces after v7.0.0.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
It is intended behavior which is the same both for controlled and uncontrolled mode. If you would like to change it, use Combobox component to build a custom multi select component that matches the requirements of your application.

**Comment by LazyLahtak** [comment]
> It is intended behavior which is the same both for controlled and uncontrolled mode.

This behavior is not the same for controlled and uncontrolled mode. In controlled mode, placeholder disappear, when value exists. At same time, when I set a value to uncontrolled component, the placeholder doesn't disappear. See screenshot below.

<img width="418" alt="image" src="https://github.com/mantinedev/mantine/assets/43685423/8a98f932-1625-47cf-9847-b397315cbb9b">

**Comment by rtivital** [comment]
The behavior is consistent, I cannot reproduce it – https://codesandbox.io/p/sandbox/nostalgic-chaum-w34jm6?file=%2Fsrc%2FApp.tsx%3A28%2C15

**Comment by LazyLahtak** [comment]
Thanks for your example. Unfortunately, I was unable to reproduce the bug in CodeSandbox. However, it reproduces in my application.
Also, I have not seen such behavior in MultiSelect components with placeholder in other libraries. That was confusing for me. If this behavior is considered correct, I have no questions left.
Thank you very much for your time!
