### ISSUE TITLE
Browser Autofill does not work with Select component

### ISSUE THREAD

**Issue by jasonlewicki** [mantinedev/mantine#5295]
### What package has an issue?

@mantine/form

### Describe the bug

Autocomplete/autofill for the select component in Chrome does not work

![Screenshot 2023-11-20 at 9 44 15 PM](https://github.com/mantinedev/mantine/assets/2465418/89f1d15b-fb02-48d8-a002-023cb6e50fdd)

**This works:**
```
<TextInput 
    mt="sm" 
    label="State" 
    autoComplete="address-level1" 
    {...locationForm.getInputProps("state")} />
```

**This does not work:**
```
<Select
    mt="sm"
    label="State"
    autoComplete="address-level1"
    data={states.map((state) => ({value: state.code, label: state.name}))}
    {...locationForm.getInputProps("state")}
/>
```

Interestingly, if i set the Select to `searchable` it searches for it, but does not blur focus and requires a manual click from the dropdown

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.5

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by rtivital** [comment]
Browser autofill and some other features may not work with custom select/multi-select components built with Combobox. If you need this feature, use NativeSelect component instead.
