### ISSUE TITLE
Exported "modals" constant lost typings for "openContextModal"

### ISSUE THREAD

**Issue by isnifer** [mantinedev/mantine#5298]
### What package has an issue?

@mantine/modals

### Describe the bug

Found out today that `openContextModal` included in `modals` constant from package `@mantine/modals` lost its typing:

```ts
openContextModal: <TKey extends string>(payload: OpenContextModal<any> & {
  modal: TKey;
}) => void;
```

Instead of:
```ts
openContextModal: <TKey extends MantineModal>(payload: OpenContextModal<Parameters<MantineModals[TKey]>[0]['innerProps']> & {
  modal: TKey;
}) => void;
```

I reviewed my colleague PR today and requested him to check `innerProps` type inference. And it didn't work when `modals.openContextModal` called, but when I changed call to just imported `openContextModal` from `@mantine/modals` type inference started working.

I started investigation, found out that `modals.openContextModal` lost its typing. I'm not sure how to do this correct, but temporary solution is to define explicitly typings for `export const modals = { ... }`

P.S. If you really need a repro for obvious problem, just ping me.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

Yes

### Do you want to send a pull request with a fix?

Yes

### Possible fix

Explicitly define types for `modals` properties in events.ts:
```ts
export const modals: {
  open: ModalsEvents['openModal'];
  close: ModalsEvents['closeModal'];
  closeAll: ModalsEvents['closeAllModals'];
  openConfirmModal: ModalsEvents['openConfirmModal'];
  openContextModal: ModalsEvents['openContextModal'];
} = {
  open: openModal,
  close: closeModal,
  closeAll: closeAllModals,
  openConfirmModal,
  openContextModal,
};
```

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
