### ISSUE TITLE
TextInput icon not red on error

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#5304]
### What package has an issue?

@mantine/core

### Describe the bug

TextInput icon not red on error?

v7:
<img width="407" alt="Screenshot 2023-11-22 at 13 55 30" src="https://github.com/mantinedev/mantine/assets/22228431/cc726097-73a9-46e1-852c-d2e19cce829a">

v6:
<img width="413" alt="Screenshot 2023-11-22 at 13 56 34" src="https://github.com/mantinedev/mantine/assets/22228431/ed422f2b-6a3c-4ecc-aaa1-49f70609706b">

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^7.2.2

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
Fixed in [7.3.1](https://github.com/mantinedev/mantine/releases/tag/7.3.1)
