### ISSUE TITLE
NumberInput: min/max partially overwrites startValue

### ISSUE THREAD

**Issue by julihereu** [mantinedev/mantine#5308]
### What package has an issue?

@mantine/core

### Describe the bug

If using the NumberInput in Mantine with a combination of **startValue** and **min**, the value of **min** overwrites that of **startValue**. When clicking the increment control on the right, it initiates with the value of **min** (decrement works like intended). The same thing happens the other way round with the combination of **max** and clicking on decrement. Without **min** or **max**, the **startValue** functions perfectly fine.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/s/magical-smoke-gsqp8j

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
Attached sandbox does not have a reproduction

**Comment by julihereu** [comment]
I beg your pardon now it should work. I have assembled two NumberInputs with the same **startValue** and the first one has a **min**.

1. Click the increment control button of the first input. The initial value is the value of **min** (-1000).
2. Click the increment control button of the second input. The initial value is the value of **startValue** (20).

**Comment by rtivital** [comment]
Fixed in [7.3.1](https://github.com/mantinedev/mantine/releases/tag/7.3.1)
