### ISSUE TITLE
Jest test cases is not working for "Select" component from Mantine V6.0.21 When we try to find options or trying click event. Please help with this.

### ISSUE THREAD

**Issue by pranaliMohite** [mantinedev/mantine#5309]
### Link to the page where something is not right

https://v6.mantine.dev/core/select/

### Exact quote of what is wrong

I am using Mantine V6.0.21 and using Select box in my applictaion.While testing application , I noticed we are not able to find "options" of combobox in DOM also not able to fire click/change event to select box.

**Below is just sample example  where both cases are failed.**

import { render, screen, fireEvent } from '@testing-library/react'
import { Select } from '@mantine/core'

describe('Select component', () => {
  it('renders select component with options', () => {
    const options = [
      { value: '1', label: 'Option 1' },
      { value: '2', label: 'Option 2' },
      { value: '3', label: 'Option 3' },
    ]

    render(<Select data-testid='select' data={options} />)

    const selectElement = screen.getByTestId('select')
    expect(selectElement).toBeInTheDocument()

    // Check if options are present
    options.forEach((option) => {
      const optionElement = screen.getByText(option.label)
      **expect(optionElement).toBeInTheDocument()**
    })
  })

  it('calls onChange handler when an option is selected', () => {
    const handleChange = jest.fn()
    const options = [
      { value: '1', label: 'Option 1' },
      { value: '2', label: 'Option 2' },
      { value: '3', label: 'Option 3' },
    ]

    render(<Select data-testid='select' data={options} onChange={handleChange} />)

    const selectElement = screen.getByTestId('select')
    fireEvent.change(selectElement, { target: { value: '2' } })

    **expect(handleChange).toHaveBeenCalledTimes(1)
    expect(handleChange).toHaveBeenCalledWith('2')**
  })
})

### Do you want to send a pull request with a fix?

None

**Comment by pranaliMohite** [comment]
@rtivital   could you please help?

**Comment by elleeffe** [comment]
[](https://testing-library.com/docs/user-event/intro/ ) you can try this, it works for me

**Comment by elleeffe** [comment]
[try this](https://testing-library.com/docs/user-event/intro/)

**Comment by rtivital** [comment]
You can explore components jest tests in this repository. I cannot provide any additional assistance with other tests.

**Comment by germanny** [comment]
It's disappointing that this issue was closed. There isn't a good example of this specific test in this repo.

**Comment by DaleSalcedo** [comment]
i'm having trouble with this exact scenario as well and am not able to change the value of the Select

**Comment by DaleSalcedo** [comment]
okay i figured this out.  if you inspect Elements of how the Mantine select works, it's not a _true_ html select component.  that's why traditional methods do not work.

when you open the Select, it creates a whole new div with the class ".mantine-Select-dropdown" which holds the option choices

so something like this worked for me.

`await act(async () => {
      const getTopicsSelect = screen.getByLabelText('Label Text Here');
      await userEvent.click(getTopicsSelect);
    });

    await waitFor(() => {
      const dropdownMenu = document.querySelector('.mantine-Select-dropdown');
      userEvent.click(screen.getByText('Menu Option Here'));
    });`

**Comment by szduda** [comment]
I experience a similar issue when trying to unit test a component which uses `MultiSelect`. I tried multiple approaches to open the dropdown and select an item, but it seems the dropdown never gets opened. Neither `click()` nor `focus()` did the job. I tried performing that on elements with `role="combobox` or `type="search`, but then I tried all other divs and wrappers as well. I tried both `fireEvent` and `userEvent`. No success as far...

**Comment by Aman1706** [comment]
Based on what @DaleSalcedo added, I modified it a bit and this worked for me 

```
//get the select component via the placeholder text
const clientListSelect = getByPlaceholderText('Select from the Drop Down');

// Trigger opening the select component
fireEvent.click(clientListSelect);

//Trigger the selection of the option you want 
fireEvent.click(getByText('Client A'));
```
