### ISSUE TITLE
v7 Collapse.extend is not a function

### ISSUE THREAD

**Issue by wrk25** [mantinedev/mantine#5313]
### What package has an issue?

@mantine/core

### Describe the bug

Cannot define default props for Collapse because Collapse.extend function does not exist.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
Fixed in [7.3.1](https://github.com/mantinedev/mantine/releases/tag/7.3.1)
