### ISSUE TITLE
useMantineColorScheme is not a function

### ISSUE THREAD

**Issue by JuanM2020** [mantinedev/mantine#5314]
### What package has an issue?

@mantine/core

### Describe the bug

Fresh installation testing demo code and get the following error

`Error: (0 , _mantine_core__WEBPACK_IMPORTED_MODULE_2__.useMantineColorScheme) is not a function
`
![Screenshot 2023-11-23 125105](https://github.com/mantinedev/mantine/assets/52183370/baf17a61-e515-4e2e-b118-05bd22c0184b)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by rtivital** [comment]
You need to add `'use client';` to the top of the file if you want to use hooks.
