### ISSUE TITLE
Select searchValue is not cleared when value is cleared programmatically via useForm.

### ISSUE THREAD

**Issue by elijah-irwin** [mantinedev/mantine#5316]
### What package has an issue?

@mantine/core

#### Context
I'm trying to use `@mantine/core` Select component  with `@mantine/form`. I would like the selection of one form Select input to change the value for another Select input depending on the selection. 

#### Issue
When providing custom onChange handlers and using `form.setFieldValue` or `form.setValues` to clear the Select input, the value is removed but the `searchValue` is still present in the effected Select input. Focusing/blurring the input does then result in the `searchValue` being updated/cleared.

#### Code Sandbox Reproduction Steps
1. Change the `Operating System` input.
2. Notice the clearable X button has been removed from the `Framework` input indicating the value has been cleared.
3. Click/Focus and blur the `Framework` input to see the `searchValue` text be cleared.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/divine-haze-hxsvpy

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by elijah-irwin** [comment]
After looking at the source code for the Select component, it seems this behavior can be avoided by setting the value of the input to be cleared as `null` instead of an empty string. 

I'll have to adjust my Typescript interface to allow this solution which maybe isn't ideal, but I can proceed for now.

If this is read and deemed like a useful addition (clear search on setting value as `null` or `undefined` or `''` I can look to raise a PR.

Cheers,
Eli

**Comment by rtivital** [comment]
Select supports `null` as an empty values. `undefined` means that the component is uncontrolled. Empty string can be used in `data` and can be a value. It is not planned to change this logic.

**Comment by dizefurkan** [comment]
I don't know if you're still having trouble with this problem, but the solution is the same as what @rtivital suggested.

```js
<Select
  value={value1|| null}
/>
<Select
  value={value2 || null}
/>
```
Let's say you have two <Select> components. Whenever Select1 changes and you want to clear the data and value of Select2, just set its value to null.
