### ISSUE TITLE
Alignment issues with `Alert` when used with icon only

### ISSUE THREAD

**Issue by IgnisDa** [mantinedev/mantine#5333]
### What package has an issue?

@mantine/core

### Describe the bug

There is an alignment issue in the alert when used with only an icon.

![image](https://github.com/mantinedev/mantine/assets/60938164/5016ad99-12cc-457a-aeb5-058313783d94)

Here is the code:

```tsx
<Alert icon={<IconAlertCircle />}>No posts found</Alert>
```

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.1

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

None

### Possible fix

This was probably introduced in `7.2.0` according to the changelog.

**Comment by julihereu** [comment]
There is already an open issue mentioning the same bug (#5305).
