### ISSUE TITLE
NavLink root color (on active) not working in v7

### ISSUE THREAD

**Issue by atumas-bananamilk** [mantinedev/mantine#5337]
### What package has an issue?

@mantine/core

### Describe the bug

This used to work in v6 when overriding a theme:
```
NavLink: {
  defaultProps: (theme: MantineTheme) => ({

  }),
  styles: (theme: MantineTheme) => ({
    root: {
      '&:not(active)': {
          color: isLight(colorScheme) ? theme.colors.dark[3] : theme.colors.dark[1],
        },
    },
  }),
},
```

However, it's not working in v7 anymore, I tried different ways, such as:
- `&:not([data-active])`
- `:not([data-active])`

I even tried:
- `&:[data-active]`
- `[data-active]`

None of them work. How do we change color for non-active NavLink items?

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^7.2.2

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
https://codesandbox.io/s/sad-jang-lyv7hp?file=/src/App.tsx

**Comment by atumas-bananamilk** [comment]
Thanks!

For Tailwind users:
```
classNames: {
  root: 'data-[inactive]:text-dark-3',
},
```

**Comment by nealoke** [comment]
For me it is not clear how do adjust the styles at top level. I tried similar things as @atumas-bananamilk, even with the link of @rtivital I don't get it working. What obvious thing am I missing 🙄

```
NavLink: NavLink.extend({
	styles: (theme, { active }) => ({
		root: {
			'&[data-active]': {
				background: 'red',
			},

			'&:not([data-active])': {
				background: 'transparent',
			},
		},
	}),
}),
```

**Comment by rtivital** [comment]
https://help.mantine.dev/q/nested-inline-styles
