### ISSUE TITLE
ScrollView and Carousel

### ISSUE THREAD

**Issue by jamalsoueidan** [mantinedev/mantine#5339]
### What package has an issue?

@mantine/core

### Describe the bug

When placing a Carousel inside a scroll, the carousel doesn't respect the width of the ScrollView

<img width="586" alt="Screenshot 2023-11-27 at 21 04 39" src="https://github.com/mantinedev/mantine/assets/115714/2cc7e34f-93e0-4ed1-a624-36001a9b41a8">

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

latest

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction. Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx

**Comment by jamalsoueidan** [comment]
```js
 <SimpleGrid cols={2}>
    <HalfOfScreenImage />
    <ScrollArea
      style={{height: 'calc(100vh)'}}
      type="always"
      offsetScrollbars
      scrollbarSize={18}
    >
      <Outlet />
  </ScrollArea>
</SimpleGrid>
```

The other page contains carousel.

**Comment by rtivital** [comment]
You are welcome to reopen the issue, if you can provide a sandbox with a minimal reproduction.
