### ISSUE TITLE
DatePicker wrong show date on change local

### ISSUE THREAD

**Issue by aalirezamoradii** [mantinedev/mantine#5343]
### What package has an issue?

@mantine/dates

### Describe the bug

When set DatesProvider settings based on fa local and import dayjs fa local
Still, the date is selected based on the default settings and no changes are made

![Screen Shot 2023-11-29 at 2 27 46 AM](https://github.com/mantinedev/mantine/assets/56014923/c8957014-7688-4626-9842-fdc23c74183b)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

### Possible fix

Use jalali calendar

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction and more description. Note that jalali calendar is not supported and is not planned to be added.

**Comment by aalirezamoradii** [comment]
https://codesandbox.io/p/sandbox/mantine-dateprovider-xccf8m

**Comment by rtivital** [comment]
jalali calendar is not supported and is not planned to be added.

**Comment by aalirezamoradii** [comment]
Thanks for response

**Comment by aalirezamoradii** [comment]
https://www.npmjs.com/package/mantine-dates-jalali

**Comment by baravak** [comment]
fixed it #7302
