### ISSUE TITLE
in xs screen, the font-size is still 14px, it should is 12px

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#5344]
### What package has an issue?

@mantine/core

### Describe the bug

<img width="1398" alt="image" src="https://github.com/mantinedev/mantine/assets/124666577/a3315dab-4de9-4d11-b1b3-7162d27aef9b">

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

6.x

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
Please do not open issues without reproduction
