### ISSUE TITLE
DatePickerInput does not have a built-in option to set the timezone to UTC.

### ISSUE THREAD

**Issue by GandoPlay** [mantinedev/mantine#5349]
### What package has an issue?

@mantine/dates

### Describe the bug

There is no way to change the time-zone so all of the dates are represented incorrectly 

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
https://mantine.dev/dates/dates-provider/#timezone

**Comment by catfo435** [comment]
@rtivital I didn't find the `timezone` setting for `DateProvider`. Seems like the `timezone` prop was dropped in v8. Is this intentional? Is there an alternative setting available?

**Comment by rtivital** [comment]
Starting from v8 Mantine dates component use strings dates values, no timezone information is attached. In your application, you can easily convert the date string to any other format.
