### ISSUE TITLE
Vike + Vite +React + Mantine Template

### ISSUE THREAD

**Issue by Kenzo-Wada** [mantinedev/mantine#5358]
### Link to the repository on GitHub

https://github.com/Kenzo-Wada/vike-mantine-template

### Features of the template, describe how it is different from other templates

This template usues
- [Vike](vike.dev)
- Vite
- React

If there is any trouble of needed fixes, just let me know and i'll fix it.

**Comment by rtivital** [comment]
Thanks for sharing! The template will be available in documentation with the next release
