### ISSUE TITLE
Autocomplete stores label as value

### ISSUE THREAD

**Issue by acontreras89** [mantinedev/mantine#5361]
### What package has an issue?

@mantine/core

### Describe the bug

The `Autocomplete` component stores the `label` of the selected option as value, rather than the actual `value` of the option. At least when it is an uncontrolled component with no `defaultValue` (I have not tried other scenarios).

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.5

### If possible, please include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/pensive-rgb-56pyzw

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by acontreras89** [comment]
Well, this may not actually be an issue with the document, since the docs state that:

> Autocomplete provides user a list of suggestions based on the input, however **user is not limited to suggestions and can type anything**.

**Comment by mrspartak** [comment]
But why it is intended? I saw an example, that value and label can be passed and only label is shown and returned. So:
1. what is the purpose to set value then?
2. this is quite often used scenario, with ids and labels, and instead directly hooking Autocomplete as input, I have to make a transformation onChange

**Comment by rtivital** [comment]
> what is the purpose to set value then?

There is no purpose, that is why it is not supported.

> this is quite often used scenario, with ids and labels, and instead directly hooking Autocomplete as input, I have to make a transformation onChange

The user has an option to enter one string in the component, which is a label. There is no option for the user to enter both value and label.

**Comment by acontreras89** [comment]
@rtivital have you looked at the example (from the official docs) pointed out by @mrspartak?

Also in the [options filtering section](https://mantine.dev/core/autocomplete/#options-filtering) there's a hint to the data format `{ value: string, label: string, disabled?: boolean }` being supported.

This is also supported according to type definitions:

```tsx
// typings simplified for clarity

interface AutocompleteProps extends ComboboxLikeProps { ... }

interface ComboboxLikeProps {
  /** Data used to generate options */
  data?: ComboboxData;
}

type ComboboxData = (string | ComboboxItem | ComboboxItemGroup)[];

export interface ComboboxItem {
  value: string;
  label: string;
  disabled?: boolean;
}
```

> As seen in [Autocomplete.tsx](https://github.com/mantinedev/mantine/blob/260a4d6af4c2b9397271b745b08d04ce85a3d2ac/packages/%40mantine/core/src/components/Autocomplete/Autocomplete.tsx#L26-L40) and [Combobox.types.ts](https://github.com/mantinedev/mantine/blob/260a4d6af4c2b9397271b745b08d04ce85a3d2ac/packages/%40mantine/core/src/components/Combobox/Combobox.types.ts#L4-L8)

So what's all the fuzz about?

**Comment by mrspartak** [comment]
I can maybe give a bit more information on my use-case:
I wanted to build reusable components for async enums, like languages, countries, etc. So basically normal components get prefilled select with search and events. I was using mantine form and it was a mistake, because Autocomplete returns onChange on each letter typed as search, which was quite unexpected and there is another method to actually get selected option, and that method can actually return the value. The problem is that Autocomplete must select a proper selection, but for this it uses label and it.
I made it work somehow with Combobox, but still with more code that I should have used if kv would be respected.

**Comment by rtivital** [comment]
Autocomplete is to get user input that is not restricted to suggestions. Based on your description, you need a searchable Select component, not Autocomplete. Treat Autocomplete like something you would see on the Google home page.

Types are reused for all Combobox components. It is not planned to change them. Follow the documentation to learn about how to use the component, the behavior there is described correctly.

**Comment by mrspartak** [comment]
Thanks @rtivital , did not see a [filter ](https://mantine.dev/core/select/#options-filtering)option on select, gonna take a look
