### ISSUE TITLE
Programmatically set focus on PinInput element

### ISSUE THREAD

**Issue by SihirliDev** [mantinedev/mantine#5365]
### What package has an issue?

@mantine/core

### Describe the bug

Hello,

After a wrong code is entered I display an error message and set the PinInput value to "".
I want to focus on to the first digit of the PinInput element as well, but no luck.

Here is the code I use:

```
const pinInputRef = useRef<HTMLInputElement>(null);

if (pinInputRef.current) {
    pinInputRef.current.focus();
}
```

Thank you for your help in advance and a big thank you for such a great UI library. Much appreciated.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
Fixed in [7.3.1](https://github.com/mantinedev/mantine/releases/tag/7.3.1)
