### ISSUE TITLE
createPolymorphicComponent

### ISSUE THREAD

**Issue by zeestack** [mantinedev/mantine#5367]
### What package has an issue?

@mantine/core

### Describe the bug

Can we please remove this "use client" directive from createPolymorphicComponent function. Its just a plane function and it should be callable from both the client and the server.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

Yes

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
Fixed in [7.3.1](https://github.com/mantinedev/mantine/releases/tag/7.3.1)
