### ISSUE TITLE
Remove Combobox.Search z-index

### ISSUE THREAD

**Issue by dimbslmh** [mantinedev/mantine#5368]
The `z-index: 1000;` is causing input sections to be hidden behind it. 

Looks to me that `Combobox.Search` is always nested in the `Combobox.Dropdown`, so it doesn't look like it's required to have?

https://github.com/mantinedev/mantine/blob/406d6f2d42b556b222f27e6d25e58891caa1504f/packages/%40mantine/core/src/components/Input/Input.module.css#L246-L249

https://github.com/mantinedev/mantine/blob/3efbaa02bbfa8db2597de694cdcc79eb69d3ccbe/packages/%40mantine/core/src/components/Combobox/Combobox.module.css#L56-L69

**Comment by rtivital** [comment]
Can you provide an example that causes the issue? Screenshot with explanation or video

**Comment by dimbslmh** [comment]
> Can you provide an example that causes the issue? Screenshot with explanation or video

Sure.

https://codesandbox.io/p/sandbox/friendly-snow-7flnpj?file=%2Fsrc%2FSelectDropdownSearch.tsx%3A42%2C33

https://github.com/mantinedev/mantine/assets/745635/a1495255-4e53-4d50-b9f9-d02eccedde95

**Comment by rtivital** [comment]
Fixed in [7.3.2](https://github.com/mantinedev/mantine/releases/tag/7.3.2)
