### ISSUE TITLE
Bottom Border for Tabs outline is incorrect

### ISSUE THREAD

**Issue by Snivio** [mantinedev/mantine#5370]
### What package has an issue?

@mantine/core

### Describe the bug

There is slight clip on the bottom border  for the tabs in outline variant  
here:
![image](https://github.com/mantinedev/mantine/assets/31371104/75a3b50a-5d19-4378-9f9f-a85ca30c11eb)

It should have a proper bottom without any clip 
![image](https://github.com/mantinedev/mantine/assets/31371104/a465e6bc-1cee-4292-bf9d-e14f34269213)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.5

### Do you know how to fix the issue

Yes

### Do you want to send a pull request with a fix?

None

### Possible fix

```
'&[data-variant=outline]': {
    '&[data-orientation=horizontal]': {
      '&[data-active]': {
        borderColor: `black black var(--mantine-color-body)black`,

        '&::after': {
          content: '""',
          position: 'absolute',
          left: '-2px',
          bottom: '-2px',
          width: '105%',
          height: '2px',
          backgroundImage: `linear-gradient(to right, black 2px, white 2px, white calc(100% - 2px), black calc(100% - 4px))`,
        },
      },
    },
    '&[data-orientation=vertical]': {
      '&[data-active]': {
        borderColor: `black var(--mantine-color-body) black black}`,

        '&::after': {
          content: '""',
          position: 'absolute',
          right: ' -2px',
          top: ' -2px',
          width: '2px',
          height: '109%',
          backgroundImage: `linear-gradient(to bottom, black 2px, white 2px, white calc(100% - 2px), black calc(100% - 2px))`,
        },
      },
    },
  },
```

had to add the :after for both vertical and horizontal when active to the tabs element

**Comment by rtivital** [comment]
Fixed in [7.3.2](https://github.com/mantinedev/mantine/releases/tag/7.3.2)
