### ISSUE TITLE
<Select /> prop rightSectionPointerEvents default is not the same as the docs

### ISSUE THREAD

**Issue by pjnicolas** [mantinedev/mantine#5371]
### What package has an issue?

@mantine/core

### Describe the bug

When using the prop `rightSection` in the `<Select />` component, the right section is not clickable unless you're using the prop `rightSectionPointerEvents="all"`. This is the opposite as the docs says.

### From [the docs](https://mantine.dev/core/select/)
> - **rightSectionPointerEvents/leftSectionPointerEvents** – controls pointer-events property of the section. **By default, all pointer events are enabled**. If you want to render a non-interactive element, set it to none to pass clicks through to the input.

### Bugged code (you can't click the button)
```tsx
import { Select, ActionIcon } from '@mantine/core'

<Select
  data={['React', 'Angular', 'Vue', 'Svelte']}
  rightSection={
    <ActionIcon onClick={() => alert('clicked')}>x</ActionIcon>
  }
/>
```

### Working code
```tsx
import { Select, ActionIcon } from '@mantine/core'

<Select
  data={['React', 'Angular', 'Vue', 'Svelte']}
  rightSection={
    <ActionIcon onClick={() => alert('clicked')}>x</ActionIcon>
  }
  rightSectionPointerEvents="all"
/>
```

Also, if you pass the `clearable` prop to the `<Select />` component the button is clickable without using the `rightSectionPointerEvents="all"` prop, but only when an element is selected. 

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^7.2.2

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by rtivital** [comment]
Fixed in [7.3.2](https://github.com/mantinedev/mantine/releases/tag/7.3.2)
