### ISSUE TITLE
Unable to deselect a chip from Chip.Group when multiple is set to false

### ISSUE THREAD

**Issue by MA-MacDonald** [mantinedev/mantine#5374]
### What package has an issue?

@mantine/core

### Describe the bug

The Chip.Group component can be initialized with no chips selected, however once you select a chip you are unable to deselect it to get to the original state. 

Using the example from the docs. Once a chip on the top row is selected it cant be deselected.

![image](https://github.com/mantinedev/mantine/assets/7886459/3c48f13b-e0f6-486b-99bf-86c257e30713)

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.3.0

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
It is intended behavior, Chip uses `input[type="radio"]` which does not allow deselecting elements. If you need this feature, use controlled Chip component.
