### ISSUE TITLE
FOUC before hydration.

### ISSUE THREAD

**Issue by nawbc** [mantinedev/mantine#5379]
### What package has an issue?

@mantine/core

### Env:
Docusaurus 3.0 

`<Flex/>` `<Group />` lost style before hydration.

https://github.com/mantinedev/mantine/assets/45007226/7e7bfc60-3726-41e5-8c1e-e07f743eac07

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

@mantine/core 7.3.0

### Do you know how to fix the issue

None

### Do you want to send a pull request with a fix?

None

**Comment by rtivital** [comment]
Please include a minimal reproduction.

**Comment by alvaro-cuesta** [comment]
Might be related to #5254

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction.
