### ISSUE TITLE
Bug in Timeline element

### ISSUE THREAD

**Issue by LeWolOnline** [mantinedev/mantine#5382]
Hi. In the interactive demo of the Timeline element (https://mantine.dev/core/timeline/) with these settings the points are not positioned in the middle of the line, it looks like a bug
![image](https://github.com/mantinedev/mantine/assets/50781135/c8ee0899-938d-4b42-ac0d-828edb53eece)
</div>

**Comment by rtivital** [comment]
Fixed in [7.3.2](https://github.com/mantinedev/mantine/releases/tag/7.3.2)
