### ISSUE TITLE
form.reset does not reset the visual value in the DOM of the Select component

### ISSUE THREAD

**Issue by woodjs** [mantinedev/mantine#5391]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

If you set initialValues ​​to the default '', then select the item and reset the form, but the value remains in the DOM.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/bold-waterfall-84h779?file=%2Fsrc%2FApp.tsx

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Empty string != empty Select value. Empty Select value is null, use it and the component will work as expected – https://codesandbox.io/p/sandbox/magical-carson-fj878v
