### ISSUE TITLE
Textarea autosize causing tests to break with "type is invalid" error

### ISSUE THREAD

**Issue by superflav** [mantinedev/mantine#5393]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

When running tests against a component that uses `Textarea` with `autosize` specified, the following error is encountered: 

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

    Check the render method of `@mantine/core/Box`.
```

To recreate this problem:

1. Clone https://github.com/mantinedev/next-app-template
2. Add a `Textarea` with `autosize` to Welcome.tsx
```
<Textarea autosize minRows={4} maxRows={4} />
```
3. Run tests
```
yarn run test
```
4. Welcome.test.tsx fails with
```
 FAIL  components/Welcome/Welcome.test.tsx
  Welcome component
    ✕ has correct Next.js theming section link (88 ms)

  ● Welcome component › has correct Next.js theming section link

    Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

    Check the render method of `@mantine/core/Box`.

      4 |
      5 | export function render(ui: React.ReactNode) {
    > 6 |   return testingLibraryRender(<>{ui}</>, {
        |                              ^
      7 |     wrapper: ({ children }: { children: React.ReactNode }) => (
      8 |       <MantineProvider theme={theme}>{children}</MantineProvider>
      9 |     ),
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.3.2](https://github.com/mantinedev/mantine/releases/tag/7.3.2)
