### ISSUE TITLE
Import error using hooks from mantine/* packages

### ISSUE THREAD

**Issue by amanda-diniz** [mantinedev/mantine#5397]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.1

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

I'm getting the following error message every time I try to use a hook from Mantine.

` ⨯ TypeError: (0 , _barrel_optimize_names_useDisclosure_mantine_hooks__WEBPACK_IMPORTED_MODULE_1__.useDisclosure) is not a function or its return value is not iterable`

I created a fresh project from `next-app-template` and tried to use both `useDisclosure` from `@mantine/hooks` and `useForm` from `@mantine/form`.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/github/amanda-diniz/crossfit-app/weightlift-form

### Possible fix

During packages installation I received the following errors:

```
➤ YN0002: │ mantine-next-template@workspace:. doesn't provide webpack (p1c5da), requested by @storybook/addon-styling-webpack.
➤ YN0002: │ mantine-next-template@workspace:. doesn't provide webpack (p768bd), requested by babel-loader.
```

I believe this might be related.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
If you use hooks in a file, you must add `'use client';` to the top of the file.
