### ISSUE TITLE
I am getting a typescript error with mantine select grouping

### ISSUE THREAD

**Issue by aayushsapkota9** [mantinedev/mantine#5399]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

5.2.4

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I am getting a typescript error on mantine select while using group options. 

Code is copy paste as of docs 

```Type '{ group: string; items: string[]; }' is not assignable to type 'string | SelectItem'.
  Property 'value' is missing in type '{ group: string; items: string[]; }' but required in type 'SelectItem'.ts(2322)
types.d.ts(6, 5): 'value' is declared here.
```
![Screenshot from 2023-12-09 22-31-08](https://github.com/mantinedev/mantine/assets/120156314/64620cde-4217-4312-b58f-6f90e7ec4132)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are using documentation for version 7 while using version 5. Use the documentation for the version of the library that you have installed.
