### ISSUE TITLE
'Edit this page' button links to 404 page on github

### ISSUE THREAD

**Issue by nsztyk** [mantinedev/mantine#5402]
### Link to the page where something is not right

https://mantine.dev/core/app-shell/

### What is wrong?

The `Edit this page` button links to the invalid page in a GitHub repository

for `app-shell` component the link is
`https://github.com/mantinedev/mantine/blob/master/docs/pages/core/app-shell.mdx` 
instead of 
`https://github.com/mantinedev/mantine/blob/master/docs/src/pages/app-shell.tsx`

![image](https://github.com/mantinedev/mantine/assets/24680812/a1091cec-1059-4996-9c76-a7d727c1d028)

![image](https://github.com/mantinedev/mantine/assets/24680812/83b4419c-bfad-4a82-bd74-8263a5f0962d)

The problem occurs for all pages inside folders
- Mantine hook
- Mantine form
- Mantine core
- Mantine dates
- Other packages

### Self-service

- [x] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The issue has been fixed in one of the previous PRs. The fix will be available with the next patch release on Thursday.
