### ISSUE TITLE
in mantine carousel 5.0.2 when I want to display slides depends on array that can be removed but the indicators doesnt follow

### ISSUE THREAD

**Issue by Juanryhn** [mantinedev/mantine#5406]
The indicators in mantine 5.0.2 doesn't depends on slides. If I have 3 slides then I remove 1 slide the indicators carousel still have 3 indicators

**Comment by rtivital** [comment]
Version 5.x is no longer supported. You are welcome to reopen the issue if you can reproduce the issue with the latest version (7.x)
