### ISSUE TITLE
@types/react dropped `placeholder` property from HTMLAttributes

### ISSUE THREAD

**Issue by isnifer** [mantinedev/mantine#5407]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.1

### What package has an issue?

@mantine/dates

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

`@types/react@18.2.43` dropped `placeholder` property from HTMLAttributes in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67170
<img width="516" alt="image" src="https://github.com/mantinedev/mantine/assets/1788245/0efa62c9-4ab4-471b-958f-56806eede27f">

### Possible fix

I'm not sure, but locally extended https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/components/Input/Input.tsx#L59 this interface — it's worked. But I'm not sure that this is a right place for this change.

```tsx
/** Sets `placeholder` attribute on the `input` element */
placeholder?: string | undefined;
```

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.0](https://github.com/mantinedev/mantine/releases/tag/7.4.0)
