### ISSUE TITLE
classNames does not work with few components. eg. Switch

### ISSUE THREAD

**Issue by zeestack** [mantinedev/mantine#5409]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

classNames prop does not work. I have to use styles prop instead which is not desirable.

```
export const ThemeSwitcher = () => {
  const { colorScheme, toggleColorScheme } = useColorScheme();

  const theme = useTheme();

  return (
    <Switch
      checked={colorScheme === 'dark'}
      color={theme.colors[theme.primaryColor][9]}
      onChange={toggleColorScheme}
      onLabel={<IconSun color={theme.white} size={20} stroke={1.5} />}
      offLabel={<IconMoonStars color={theme.colors.gray[6]} size={20} stroke={1.5} />}
      **styles={{ track: { cursor: 'pointer' } }}**
      size="lg"
    />
  );
};

```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
Could you plz tell us any other components that reproduce this issue if you know?

**Comment by rtivital** [comment]
`classNames` property on Switch component works as intended – https://codesandbox.io/p/sandbox/jolly-raman-csk6vd?file=%2Fsrc%2FApp.tsx%3A3%2C33
