### ISSUE TITLE
There is no scrollbars prop in ScrollArea component

### ISSUE THREAD

**Issue by daler-sz** [mantinedev/mantine#5417]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

When I try to specify `scrollbars` prop in `ScrollArea` component as it is showed [there](https://mantine.dev/core/scroll-area/#disable-horizontal-scrollbars), I get a TypeScript error.

Unfortunately, I can not provide a codesandbox reproduction as it is not working in my browsers by some reason.

```Type '{ children: Element; scrollbarSize: number; h: string; scrollbars: string; }' is not assignable to type 'IntrinsicAttributes & ScrollAreaProps & RefAttributes<HTMLDivElement> & { component?: any; renderRoot?: ((props: Record<...>) => ReactNode) | undefined; }'.
Property 'scrollbars' does not exist on type 'IntrinsicAttributes & ScrollAreaProps & RefAttributes<HTMLDivElement> & { component?: any; renderRoot?: ((props: Record<...>) => ReactNode) | undefined; }'. Did you mean 'scrollbarSize'?ts(2322)

**Comment by rtivital** [comment]
You have checked ` I have verified that I use latest version of all @mantine/* packages` while not having the latest version installed. Update `@mantine/*` packages to the latest version.
