### ISSUE TITLE
TransferList has an additional scroll bar on large data sets

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#542]
### What package has an issue

@mantine/core

### Describe the bug

If you scroll to the end of a large data set a second scroll bar appears. (see the image)

![image](https://user-images.githubusercontent.com/49494752/146694875-f921815e-c677-4eab-bc26-5c7e2f0c212c.png)

### In which browser did the problem occur

Brave

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/youthful-field-3nv0h

**Comment by rtivital** [comment]
Fixed in 3.4.3
