### ISSUE TITLE
Button content disappears within TextInput right section

### ISSUE THREAD

**Issue by jvllmr** [mantinedev/mantine#5422]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Other, I will specify in the bug description

### Describe the bug

When using a Button with an Icon from tabler icons in the right section of a TextInput the icon disappears.
The icon is viewable again when applying p={0} to the button, but then there is a margin between button and text input border.
Using in the icon in the leftSection of the button works, but the icon will have an offset.
I tested on Firefox and Google Chrome with different icons.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/serene-mccarthy-9dlxcz?file=%2Fsrc%2FApp.tsx%3A26%2C27

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by jvllmr** [comment]
Just realised: This also applies to text inside the Button

**Comment by jvllmr** [comment]
Same example with Mantine v6: https://codesandbox.io/p/sandbox/determined-browser-3njpj8?file=%2Fsrc%2FApp.tsx%3A18%2C11
There it works "as expected"

**Comment by jvllmr** [comment]
Applying p={0} and (fullWidth or w="100%") to the Button is a workaround:
```typescript
<TextInput
            rightSection={
              <Button px={0} fullWidth>
                Text
              </Button>
            }
/>

<TextInput
            rightSection={
              <Button px={0} w="100%">
                Text
              </Button>
            }
/>


```

**Comment by rtivital** [comment]
It is intended behavior, Button has overflow hidden and padding on left and right. If you need to display button in the right/left sections, use `rightSectionWidth`/`leftSectionWidth` props to increase sections sizes and remove padding from the button.
