### ISSUE TITLE
useScrollIntoView returns RefObject instead of MutableRefObject

### ISSUE THREAD

**Issue by daler-sz** [mantinedev/mantine#5426]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/hooks

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

The `scrollableRef` and `targetRef` fields of result of `useScrollIntoView` hook are `RefObject`, not `MutableRefObject` as it is presented [here](https://mantine.dev/hooks/use-scroll-into-view/#definition) 

### Possible fix

I think it can be fixed by fixing type declarations, namely just replacing RefObject by MutableRefObject in `useScrollIntoView` declaration and by changing this line https://github.com/mantinedev/mantine/blob/260a4d6af4c2b9397271b745b08d04ce85a3d2ac/packages/%40mantine/hooks/src/use-scroll-into-view/use-scroll-into-view.ts#L38 to 
```ts 
Target extends HTMLElement | null
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.1](https://github.com/mantinedev/mantine/releases/tag/7.4.1)
