### ISSUE TITLE
Styles not applying when using CSS modules

### ISSUE THREAD

**Issue by MahirAlam** [mantinedev/mantine#5435]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Firefox

### When I use a style on container, It Just Doesn't work!
**It shows the Style Name But doesn't show the styles or apply it!**
_You can see It Here_
![Screenshot 2023-12-18 040432](https://github.com/mantinedev/mantine/assets/103423298/0600d9d5-5129-4efb-ad97-c2a1bf13f193)
![Screenshot 2023-12-18 040506](https://github.com/mantinedev/mantine/assets/103423298/6332eeaf-cc0e-433b-8206-94c9d1823d81)
![Screenshot 2023-12-18 040532](https://github.com/mantinedev/mantine/assets/103423298/8f4888c4-5c45-42a9-bf75-eaef70680666)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by bunge12** [comment]
I'm experiencing the same issue. I need to stop and start Next again in order for the styles to apply properly

**Comment by MahirAlam** [comment]
Yeah, same here!!

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction. Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx

**Comment by UmarFKhawaja** [comment]
I had this issue as well, but using layers helped.

**Comment by MahirAlam** [comment]
> **[UmarFKhawaja](/UmarFKhawaja) ** commented

can you tell me how exactly?

**Comment by MahirAlam** [comment]
> Please provide a sandbox with a minimal reproduction. Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx

But reproduction wont work!
It seems when I restart the server then sometimes it works (most of the time).
I tried deleting the cache (.next) files.
But nothing seems to be working!

**Comment by rtivital** [comment]
If the issue cannot be reproduced, it cannot be fixed.
You can use one of the templates to get started or as a reference, they do not have issues with styles.

**Comment by monopolo11** [comment]
Could it be the different capitalization on the file name and the import?

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction.

**Comment by neo7BF** [comment]
How do I open this issue? This is a sandbox where you can test the issue: https://codesandbox.io/p/sandbox/mantine-forked-ps75cv

**Comment by rtivital** [comment]
1. To open new issue, go to the Issues tab and press "New issue"
2. Your codesandbox is private and is not visible
