### ISSUE TITLE
Mantine + T3 (App Directory) Template

### ISSUE THREAD

**Issue by WillKirkmanM** [mantinedev/mantine#5441]
### Link to the repository on GitHub

https://github.com/WillKirkmanM/mantine-t3-template

### Features of the template, describe how it is different from other templates

# Features:
- T3 Stack
- Prisma
- NextAuth
- TRPC

Submitted a Pull Request on October 11th regarding my community template (https://github.com/mantinedev/mantine/pull/5019). Glad to see you are accepting community made templates.

**Comment by rtivital** [comment]
Thanks for submitting the template! It will be available on the getting started page with next patch release.
