### ISSUE TITLE
Dropzone.Accept and Dropzone.Reject don't work on Safari

### ISSUE THREAD

**Issue by abird** [mantinedev/mantine#5443]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/dropzone

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

With Safari on macOS only the Dropzone.Idle component displays. The Dropzone.Accept and Dropzone.Reject components are never  displayed when the appropriate files are dragged over the Dropzone component. 

This is easy to reproduce by opening the Mantine documentation to the [Dropzone component](https://mantine.dev/others/dropzone/) and dragging either an image file or a non-image file over the Dropzone sample under Usage. 

This feature may have never worked with Safari as I can reproduce the problem in the documentation for Mantine versions 4-6.

I am using Safari version 17.2. I haven't tried it with older versions of Safari.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is broken in react-dropzone. Example on the documentation website does not work as well – https://react-dropzone.js.org/#section-styling-dropzone

I cannot do much until the bug is resolved on the react-dropzone side.
