### ISSUE TITLE
DatePickerInput keyboard accessibility

### ISSUE THREAD

**Issue by smokey-de** [mantinedev/mantine#5444]
### Link to the page where something is not right

https://v6.mantine.dev/dates/date-picker-input/

### What is wrong?

Hi there! I'm using DatePickerInput for range. I want use keyboard accessibility but I did not find anything for keyboard . I know DateInput has access but DateInput doesn't has date range . How can I use 

https://codesandbox.io/p/sandbox/distracted-nova-tknkqw?file=%2Fsrc%2FApp.tsx%3A5%2C1

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://github.com/mantinedev/mantine/assets/10353856/526e9153-f4ff-4423-a444-7009e4c3784d

DatePickerInput is fully accessible with keyboard, it traps focus, supports arrow keys to navigate between dates and Enter key to select date.
