### ISSUE TITLE
Can't customize Input/TextInput using CSS Modules

### ISSUE THREAD

**Issue by Tiaansu** [mantinedev/mantine#5445]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Other, I will specify in the bug description

### Describe the bug

First, I would like to tell you that I have only reproduce the issues on Brave, Microsoft Edge, and Google Chrome as I don't have any time to install other browsers.

So, while following this example [[https://mantine.dev/core/input/#change-focus-styles](https://mantine.dev/core/input/#change-focus-styles)] I have encountered an error:
```
./src/app/test/Test.module.css:4:5
Syntax error: Selector "&:focus-within" is not pure (pure selectors must contain at least one local class or id)

  2 |     transition: none;
  3 | 
> 4 |     &:focus-within {
    |     ^
  5 |         outline: rem(2px) solid var(--mantine-color-blue-filled);
  6 |         border-color: transparent;
```

src/app/test/page.tsx:
```tsx
import { TextInput } from '@mantine/core';
import classes from './Test.module.css';

export default function Test() {
    return <TextInput label="Test" placeholder="Test" classNames={classes} />;
}
```

src/app/test/Test.module.css:
```css
.input {
    transition: none;

    &:focus-within {
        outline: rem(2px) solid var(--mantine-color-blue-filled);
        border-color: transparent;
    }
}
```

Does anyone know why this happens or does anyone know how to fix it? Thanks in advance.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Which tool gives you this error?

**Comment by rtivital** [comment]
I doubt that Next.js gives you this error

**Comment by Tiaansu** [comment]
Well, do you have a working example of customizing `TextInput`? I'll try to reproduce it later on a new next.js app and send you the repo if I managed to reproduce it.
