### ISSUE TITLE
Show browser picker for TimeInput does not work on safari

### ISSUE THREAD

**Issue by StyxOfDynamite** [mantinedev/mantine#5446]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.1.5

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

When using Safari, the open browser picker button does nothing.

As seen in Mantine docs here, https://mantine.dev/dates/time-input/#show-browser-picker

### If possible, include a link to a codesandbox with a minimal reproduction

https://ptlg22.csb.app/

### Possible fix

I don't believe safari has a browser picker available, I added a native input type =`time` and it doesn't attempt to render one.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by StyxOfDynamite** [comment]
It looks as though support for this was added to safari, at least according to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#browser_compatibility

**Comment by StyxOfDynamite** [comment]
So I did some more digging, and safari doesn't have a native picker element, but apparently supports `time` inputs without it, wondering if we can / could conditionally render the picker on decent browsers

**Comment by StyxOfDynamite** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker#browser_compatibility

**Comment by rtivital** [comment]
TimeInput uses `input[type="time"]`, `showPicker` is not available in desktop Safari. Currently, it is not planned to add custom picker support.
