### ISSUE TITLE
Expression produces a union type that is too complex to represent

### ISSUE THREAD

**Issue by ronsper** [mantinedev/mantine#5448]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

Flex Component is broken with basic parameters. I get "Expression produces a union type that is too complex to represent." when building a project with any Flex Components. 

`<Flex gap={0} direction={"row"}></Flex>`

Error: 
`TS2590: Expression produces a union type that is too complex to represent.
    66 |                 }}
    67 |             >
  > 68 |                 <Flex gap={0} direction={"row"}>
       |                       ^^^^^^^^^^^^^^^^^^^^^^^^^
    69 |                     {fieldState.options.map((option) => {
    70 |                         return (
    71 |                             <Radio

`

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I cannot reproduce the issue neither in sandbox – https://codesandbox.io/s/laughing-tree-st9sxs?file=/src/App.tsx
nor in any official templates.

**Comment by vladkens** [comment]
Hi. Have same issues with Flex elements. Solution from [this comment](https://github.com/chakra-ui/chakra-ui/issues/7526#issuecomment-1713912823) worked for me.

In `tsconfig.json` replace line `"jsxImportSource": "@emotion/react"` with `"types": ["@emotion/react/types/css-prop"]` (add extra types if required)

Probably something wrong with `@emotion/react` and it randomly overcomplicate types tree.

**Comment by danicc097** [comment]
For the record, this wasn't an issue at least in v7.1.7 with `"jsxImportSource": "@emotion/react"`. Got this error upgrading to v7.4.1

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction.
