### ISSUE TITLE
themeToVars isn't build time compatible

### ISSUE THREAD

**Issue by godiagonal** [mantinedev/mantine#5451]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/vanilla-extract

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

When referencing `vars` resulting from `themeToVars` in a Next.js server component I get the following error:
```
Error: _mantine_vanilla_extract__WEBPACK_IMPORTED_MODULE_2__.themeToVars is not a function
```

The problem stems from the `theme-to-vars` module (and some of the imported `@mantine/core` modules) being marked as `'use_client'`. The modules in question don't need the `'use_client'` directive.

As far as I understand this means `themeToVars` (and the resulting `vars` object) cannot be referenced in build time code, which defeats the purpose of using vanilla-extract.

### Possible fix

Add the following files to [scripts/build/rollup/rollup-exclude-use-client.ts](https://github.com/mantinedev/mantine/blob/master/scripts/build/rollup/rollup-exclude-use-client.ts):
- `theme-to-vars`
- `core/MantineProvider/merge-mantine-theme/merge-mantine-theme`
- `core/utils/deep-merge/deep-merge`

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix. Please check that built files do not contain `use client` directives (in `esm` folder).

**Comment by godiagonal** [comment]
@rtivital Thanks for the quick reply! Will submit a PR.
