### ISSUE TITLE
`Fieldset`: Strange padding in Safari

### ISSUE THREAD

**Issue by smorimoto** [mantinedev/mantine#5455]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

I found strange padding on the `Fieldset` with the latest Safari. As far as I can confirm, this is not happening in Chrome, and it could be a bug in Safari, but I just wanted to confirm it here first.

Typing and deleting characters will remove the padding 🤷‍♂️

https://github.com/mantinedev/mantine/assets/38746192/8aede823-98e9-4217-8690-7c72498b0a06

Safari: Version 17.2.1 (19617.1.17.11.12)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by smorimoto** [comment]
For a minimal reproduction case, this should be enough:

```tsx
<Fieldset legend="Fieldset">
  <TextInput />
</Fieldset>
```

**Comment by rtivital** [comment]
I cannot fix it on the library side. It should be fixed in Safari. Alternatively, you can use Fieldset without Stack
