### ISSUE TITLE
breakpoints set in pixels are not working with hiddenFrom and visibleFrom props

### ISSUE THREAD

**Issue by misha3228** [mantinedev/mantine#5457]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I set the breakpoints in pixels in the theme -

<img width="379" alt="image" src="https://github.com/mantinedev/mantine/assets/40370454/c3a177c9-3ce2-44ba-b0f5-085020cbec76">

Breakpoints variables in CSS modules work in pixels as expected.

But when using hiddenFrom and visibleFrom props, media queries use em units -

<img width="336" alt="image" src="https://github.com/mantinedev/mantine/assets/40370454/a8f4a288-070b-4b80-999a-cba6cbb57770">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.1](https://github.com/mantinedev/mantine/releases/tag/7.4.1)
