### ISSUE TITLE
`Select`, `MultiSelect`, and similar do not allow `readonly []` arrays as `data` prop

### ISSUE THREAD

**Issue by hexcowboy** [mantinedev/mantine#5467]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

```tsx
const COMPANY_SIZE = ["1-9", "10-49", "50-499", "500+"] as const;

<Select
  label="Size"
  placeholder="Company Size"
  data={COMPANY_SIZE} // <- The type 'readonly ["1-9", "10-49", "50-499", "500+"]' is 'readonly' and cannot be assigned to the mutable type '(string | ComboboxItem | ComboboxItemGroup)[]'.
  {...form.getInputProps("size")}
/>
```

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
