### ISSUE TITLE
The styles of style.layer and style are different !!

### ISSUE THREAD

**Issue by issam-seghir** [mantinedev/mantine#5468]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

when importing the style.layer.css instead of style.css i see that there is diffrernt style applaied 
- `import '@mantine/core/styles.css'; ` 

![image](https://github.com/mantinedev/mantine/assets/74573675/9ef0ba5d-c702-4e4e-befa-be7894785d15)

- `import '@mantine/core/styles.layer.css';`
![image](https://github.com/mantinedev/mantine/assets/74573675/ab2d698c-df71-4856-ba76-2e1d047a6ae9)
 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You have third-party styles injected by some other library or your project that override Mantine styles.
Styles are the same:
- https://codesandbox.io/s/young-frog-pgqd6p?file=/src/App.tsx
- https://codesandbox.io/s/loving-christian-dy37wc?file=/src/App.tsx

**Comment by issam-seghir** [comment]
![image](https://github.com/mantinedev/mantine/assets/74573675/a678ab23-8bc9-44f4-9345-a6b626c95dc7)

Manitne style is always the first layer. That's why it's overridden. I'm using Sass partial. I tried to add Manitne layer at the end, but nothing changed.

![image](https://github.com/mantinedev/mantine/assets/74573675/dddf0cdf-af33-48a6-a8c6-46d5f60de04e)
