### ISSUE TITLE
Rating size type

### ISSUE THREAD

**Issue by CripyIce** [mantinedev/mantine#5470]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

All

### Describe the bug

`Rating` size type is `MantineSize` while entering a number works great but gives lints error.

### Possible fix

Make size attribute accept number also

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.1](https://github.com/mantinedev/mantine/releases/tag/7.4.1)
