### ISSUE TITLE
MultiSelect does not open when clicking on arrows

### ISSUE THREAD

**Issue by ifeltsweet** [mantinedev/mantine#5472]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The [MultiSelect](https://mantine.dev/core/multi-select/) dropdown does not open when clicking on the arrows in the right side of the component. A normal [Select](https://mantine.dev/core/select/) component does not have this issue.

<img width="370" alt="image" src="https://github.com/mantinedev/mantine/assets/1529466/4b949fd6-c6a0-41d7-a0ea-633c7bac967b">

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/core/multi-select/

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.1](https://github.com/mantinedev/mantine/releases/tag/7.4.1)
