### ISSUE TITLE
Error when using the Table component in Next JS

### ISSUE THREAD

**Issue by vitalygallyamov** [mantinedev/mantine#5474]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

When using the Table component in page markup, a build error occurs on the server
```
<Table stickyHeader stickyHeaderOffset={60}>
  <Table.Thead>
    <Table.Tr>
      <Table.Th>Element position</Table.Th>
      <Table.Th>Element name</Table.Th>
      <Table.Th>Symbol</Table.Th>
      <Table.Th>Atomic mass</Table.Th>
    </Table.Tr>
  </Table.Thead>
  <Table.Caption>Scroll page to see sticky thead</Table.Caption>
</Table>
```
Unhandled Runtime Error
Error: Could not find the module "...\node_modules\@mantine\core\esm\components\Table\Table.mjs#Table#Thead" in the React Client Manifest. This is probably a bug in the React Server Components bundler.

![image](https://github.com/mantinedev/mantine/assets/3092742/43729e4a-ac8c-480a-a7fc-4dad5d48118d)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/guides/next/#compound-components-in-server-components
