### ISSUE TITLE
New dark theme colors mismatch

### ISSUE THREAD

**Issue by jmcmahon443** [mantinedev/mantine#5480]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

The latest default theme color scheme changes produced what appears to be an unintentional color mismatch between borders and dividers. Where mantine borders and dividers used to be the same color, now they are different colors. Specifically:
- --_divider-color: var(--mantine-color-dark-3)
- --_app-shell-border-color: var(--mantine-color-dark-4)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/jovial-liskov-62zl8t

### Possible fix

Change `mantine/packages/@mantine/core/src/components/Divider/Divider.module.css` lines 10 & 14:
Line 10: Change --mantine-color-gray-4 to --mantine-color-gray-3
Line 14: Change --mantine-color-dark-3 to --mantine-color-dark-4

### Self-service

- [X] I would be willing to implement a fix for this issue
Tested these changes locally, and they worked. Not sure how to submit a pull request without access, need to speak to a maintainer first.

**Comment by rtivital** [comment]
Fixed in [7.4.2](https://github.com/mantinedev/mantine/releases/tag/7.4.2)
