### ISSUE TITLE
CSS error term expected css(css-termexpected)

### ISSUE THREAD

**Issue by mzavattaro** [mantinedev/mantine#5487]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

Within the example.module.css file, css shows an linting error `term expectedcss(css-termexpected)` when using a Mantine css variable.
<img width="741" alt="Screenshot 2023-12-29 at 5 21 08 pm" src="https://github.com/mantinedev/mantine/assets/22721781/dacd036a-45e7-411d-88f0-dfb64bb347bb">
```
.title {
  color: light-dark(var(--mantine-color-black), var(--mantine-color-white));
  font-size: rem(100px);
  font-weight: 900;
  letter-spacing: rem(-2px);

  @media (max-width: $mantine-breakpoint-md) {
    font-size: rem(50px);
  }
}
```

It doesn't impact the styling and everything works as expected. However, is there a way to eliminate this error?

I'm using the `next-app-template` and I haven't made any configuration changes, completely new project.

### If possible, include a link to a codesandbox with a minimal reproduction

[Repo here](https://github.com/mzavattaro/chronopass-ai)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
See a guide to get started in VSCode – https://mantine.dev/getting-started/#set-up-vs-code

**Comment by henningsieh** [comment]
I've set up VS Code as described, but... nothing changed, I get the same error:

![grafik](https://github.com/mantinedev/mantine/assets/34573859/941342fb-efc6-4499-bfce-ee853491452b)

What could be my failure?

**Comment by rtivital** [comment]
You did not install postcss extension or it is not activated for CSS files.

**Comment by henningsieh** [comment]
Thanks for your reply and help!

I think, I have everything you mentioned in place!?

![grafik](https://github.com/mantinedev/mantine/assets/34573859/1620a480-1f9d-4e63-8183-0fcd373f26d6)

Don't I?

**Comment by henningsieh** [comment]
The error is gone by disabling the tailwind extension, but there are still NO SUGGESTIONS!?

![grafik](https://github.com/mantinedev/mantine/assets/34573859/93123d5f-b8c3-4060-906c-0488b5f05bef)

**Comment by max-degterev** [comment]
@henningsieh it's happening due to a conflict with tailwind extension. change "language" (bottom right) to postcss
