### ISSUE TITLE
DatePickerInput onChange incorrectly called

### ISSUE THREAD

**Issue by testerez** [mantinedev/mantine#5501]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

6.0.21

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

Note: I'm still using Mantine 6

On Next.js, I'm using a controlled `DatePickerInput` with `type="range"`.
In the `onChange`, I'm using next router to push new query params with the selected values.
My issue is that once `onChange` is called with both start and end dates, It gets called a second time with `[null, null]`.
This is happening only when I use next router. Though, no new render occurs between the two consecutive onChange, so I'm not sure why it behaves differently.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/hungry-sanderson-pjcd4g?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqwtysiz00053b6qk1gsgr94%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqwtysiz00023b6qohb9ndr4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqwtysiz00033b6qkppwm4b0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqwtysiz00043b6qei8tzuxv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqwtysiz00023b6qohb9ndr4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqwtysiz00013b6qdk6atsdc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqwunx9601ma3b6qo428c96c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqwtysiz00023b6qohb9ndr4%2522%252C%2522activeTabId%2522%253A%2522clqwunx9601ma3b6qo428c96c%2522%257D%252C%2522clqwtysiz00043b6qei8tzuxv%2522%253A%257B%2522id%2522%253A%2522clqwtysiz00043b6qei8tzuxv%2522%252C%2522activeTabId%2522%253A%2522clqwu0jq0005k3b6qoc15u0o2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqwu0jq0005k3b6qoc15u0o2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%253Fmin%253D%2526max%253D%2522%257D%255D%257D%252C%2522clqwtysiz00033b6qkppwm4b0%2522%253A%257B%2522id%2522%253A%2522clqwtysiz00033b6qkppwm4b0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqwu0ea300493b6qpfhu0qti%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqwu0ea300493b6qpfhu0qti%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix

**Comment by testerez** [comment]
I'll try to find time for this. In the meantime, here is a workaround that worked for me:

```tsx
import { DatePickerInput } from '@mantine/dates'
import type { DatePickerInputProps } from '@mantine/dates'
import { useEffect, useState } from 'react'

export function DateRangePicker(props: DatePickerInputProps<'range'>) {
  // DatePickerInput has a bug where it calls onChange with stale values when controlled value is not set synchronously.
  // As a workaround, we use local state to store the value and update it synchronously.
  // See: https://github.com/mantinedev/mantine/issues/5501
  const [value, setValue] = useState(props.value)
  useEffect(() => setValue(props.value), [props.value])
  return (
    <DatePickerInput
      type="range"
      { ...props }
      value={value}
      onChange={(values: any) => {
        setValue(values)
        props.onChange?.(values)
      }}
    />
  )
}
```

**Comment by rtivital** [comment]
Changes to v6 are not planned to be introduced

**Comment by lukasbash** [comment]
Happening on 7.11.0 as well 😢
