### ISSUE TITLE
Make `<AppShell>` and friends account for safe area insets

### ISSUE THREAD

**Issue by odnamrataizem** [mantinedev/mantine#5502]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

The `<AppShell>` components are not taking into account the [safe area environment variables](https://developer.mozilla.org/en-US/docs/Web/CSS/env#safe-area-inset-top). These normally take place on PWAs. E.g., in the following iOS Safari screenshot taken from [an example in Mantine docs](https://mantine.dev/app-shell/?e=FullLayout), the footer padding should be increased by `env(safe-area-inset-bottom)` to avoid getting obscured by the black bar at the bottom (depending on the footer's height and contents).

![IMG_A1DCA12592CB-1](https://github.com/mantinedev/mantine/assets/363904/96be8674-103e-490f-b213-5d2266eb5301)

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/app-shell/?e=FullLayout

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.1.1](https://github.com/mantinedev/mantine/releases/tag/7.7.1)
