### ISSUE TITLE
Y-axis in RTL charts

### ISSUE THREAD

**Issue by mnakhli** [mantinedev/mantine#5505]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

Latest

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

In RTL mode, the Y-axis enters the graph in terms of design and it is not correct.

### Possible fix

In the chart, there is not much difference between RTL and LTR.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.1](https://github.com/mantinedev/mantine/releases/tag/7.4.1)
