### ISSUE TITLE
Use component `extend` function in server component cause error

### ISSUE THREAD

**Issue by zation** [mantinedev/mantine#5506]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Create theme and use it directly in layout without any 'use client' will cause error. For example:
```ts
import { createTheme, Button } from '@mantine/core'

export default createTheme({
  components: {
    Button: Button.extend({
      defaultProps: {
        color: 'black',
      },
    }),
  }
})
```
Error: `Error: Attempted to call extend() from the server but extend is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.`

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Add `'use client'` to the top of the file. It is not planned to change this logic.
