### ISSUE TITLE
[Feature Request] NumberInput custom parse/format function

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#551]
### Usage example, including component/hook API

I think it would be good to give the developer the possibility to create his own parse/format functions

### Possible implementation – describe how the feature can be implemented

Add a parseNum and formatNum prop to the NumberInput

### Do you want to contribute this feature and create a pull request

Yes

**Comment by jerebtw** [comment]
This would only work onBlur @rtivital

**Comment by rtivital** [comment]
Well, I guess this will make your decimal separator feature obsolete, so feel free to work on it

**Comment by rtivital** [comment]
As I was thinking about it, I doubt that this will be a great idea to format numbers in NumberInput. I would prefer to add this feature via separate MaskInput component to not overload the NumberInput.

**Comment by jerebtw** [comment]
Yes, I think this is best because it would we really complex to add this function to NumberInput
