### ISSUE TITLE
AppHeader height 0 layout issues

### ISSUE THREAD

**Issue by chris-feist** [mantinedev/mantine#5514]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.4

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

None

### Describe the bug

I am trying to hide the AppShell header on larger screens, and only use the header on mobile devices to control the nav menu. When setting the header height to 0, the the main content no longer accounts for the nav bar width and is rendered underneath it. I can set the height to 0.1 and it works, but the header border is still rendered

<img width="1200" alt="image" src="https://github.com/mantinedev/mantine/assets/5295555/f9fe2ddc-47f4-41e6-8dba-2209b2da69fd">

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/zealous-hamilton-3gxlfy?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqzaq9qv00063b6bltwitrhd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqzaq9qv00023b6b3buuvm0g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqzaq9qv00033b6bo9gftn1i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqzaq9qv00053b6bfxudde3e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqzaq9qv00023b6b3buuvm0g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqzaq9qv00013b6b48paa1by%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clqzaq9qv00023b6b3buuvm0g%2522%252C%2522activeTabId%2522%253A%2522clqzaq9qv00013b6b48paa1by%2522%257D%252C%2522clqzaq9qv00053b6bfxudde3e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqzaq9qv00043b6bpxnuklnz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqzaq9qv00053b6bfxudde3e%2522%252C%2522activeTabId%2522%253A%2522clqzaq9qv00043b6bpxnuklnz%2522%257D%252C%2522clqzaq9qv00033b6bo9gftn1i%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqzaq9qv00033b6bo9gftn1i%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.1](https://github.com/mantinedev/mantine/releases/tag/7.4.1)
