### ISSUE TITLE
hidden prop does not work on Menu.Item

### ISSUE THREAD

**Issue by VaZark** [mantinedev/mantine#5521]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Firefox & Chromium

### Describe the bug

The `hidden` prop hides elements like `Menu.Label ` & `Menu.Divider` but does not work with `Menu.Item`  (I've noted something similar happens with TextInput component)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/twilight-dream-l97cwz?file=%2Fsrc%2FApp.tsx%3A22%2C23

### Possible fix

Maybe the prop is not propagated to the base component or is being overridden ? 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`hidden` prop is not something Mantine provides, it comes from html element attributes. The prop is not supported on the library level.
