### ISSUE TITLE
hook useHotkey to doesn't work if I focus on html element having contenteditable="true"

### ISSUE THREAD

**Issue by Dilanjer** [mantinedev/mantine#5528]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.0

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Create div element and add `contentEditable={true}` focus on this element and use hotkey

```
function Component() {
  useHotkeys([['mod+p', () => console.log('Used hotkeys')]], []);

  return (
    <div contentEditable={true}>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore,
      temporibus.
    </div>
  );
}

```

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/usehotkey-bug-j67fnc?file=%2Fsrc%2FApp.tsx

### Possible fix

this packege [react-use-hotkeys](https://github.com/reecelucas/react-use-hotkeys) have option `enableOnContentEditable`

By default, the hook will ignore keydown events originating from `INPUT `and `TEXTAREA `elements, since this behaviour is normally what you want. If you want to override this behaviour you can use `ignoredElementWhitelist`:

```
useHotkeys(
  "Escape",
  () => {
    console.log("Some action");
  },
  { enableOnContentEditable: true }
);
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
1. https://mantine.dev/hooks/use-hotkeys/#definition
2. https://codesandbox.io/p/sandbox/usehotkey-bug-forked-gc6dnj?file=%2Fsrc%2FApp.tsx%3A10%2C18

**Comment by Dilanjer** [comment]
thank you and sorry for wasting your time
