### ISSUE TITLE
allowLeadingZeroes does not work with useForm

### ISSUE THREAD

**Issue by elibroftw** [mantinedev/mantine#5530]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

When using allowLeadingZeroes, the leading zeros are not given to the onChange function.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.1](https://github.com/mantinedev/mantine/releases/tag/7.4.1)
