### ISSUE TITLE
`mantine-Menu-dropdown` appears twice

### ISSUE THREAD

**Issue by crabvk** [mantinedev/mantine#5537]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Go to the Menu docs page https://mantine.dev/core/menu/#hover-menu, press "Toggle menu" button, select the dropdown in DevTools Inspector, look at the class attribute: `mantine-Menu-dropdown` appears twice.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.2](https://github.com/mantinedev/mantine/releases/tag/7.4.2)
