### ISSUE TITLE
Changing PinInput length breaks layout on small screen

### ISSUE THREAD

**Issue by HoHieuLuc** [mantinedev/mantine#5541]
### Link to the page where something is not right

https://mantine.dev/core/pin-input/#usage

### What is wrong?

https://github.com/mantinedev/mantine/assets/62865718/9d335cba-4255-4b06-bb05-63cc3bf10ad6

The same thing happens when changing Table spacing
https://mantine.dev/core/table/#spacing
![brave_jdpIDrCpFk](https://github.com/mantinedev/mantine/assets/62865718/e617c053-75c0-449a-b835-70d7be48ede6)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by aaqib-javed** [comment]
> ### Link to the page where something is not right
> https://mantine.dev/core/pin-input/#usage
> 
> ### What is wrong?
>  brave_rBFgYkJQpz.mp4 
> The same thing happens when changing Table spacing https://mantine.dev/core/table/#spacing ![brave_jdpIDrCpFk](https://private-user-images.githubusercontent.com/62865718/295490858-e617c053-75c0-449a-b835-70d7be48ede6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTczNzAsIm5iZiI6MTcwNTA1NzA3MCwicGF0aCI6Ii82Mjg2NTcxOC8yOTU0OTA4NTgtZTYxN2MwNTMtNzVjMC00NDlhLWI4MzUtNzBkN2JlNDhlZGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEwNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMmYzY2Y1YmM0ZTA0NTIwYTI1YTk0NDJmOGMwMmIzNTVmZWVlZTYxMjllNGQ4Mzg3YWVmMjk4MGRkNjI1ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gqhf7c6jUGGpcx0Sv1sh5hAg6gvcEiskQrOmOF9o1ME)
> 
> ### Self-service
> * [ ]  I would be willing to implement a fix for this issue

I want to contribute in this, If you can give me a chance to fix this?
Thanks

**Comment by rtivital** [comment]
Fixed in [7.4.2](https://github.com/mantinedev/mantine/releases/tag/7.4.2)
