### ISSUE TITLE
`useComputedColorScheme` with `getInitialValueInEffect: true` won't work

### ISSUE THREAD

**Issue by Songkeys** [mantinedev/mantine#5549]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

because the config is not passed into the `useMantineColorScheme` hook:

https://github.com/mantinedev/mantine/blob/eae084e15fcf069a284b7836a8d063bdcd1654db/packages/%40mantine/core/src/core/MantineProvider/use-mantine-color-scheme/use-computed-color-scheme.ts#L9

https://github.com/mantinedev/mantine/blob/eae084e15fcf069a284b7836a8d063bdcd1654db/packages/%40mantine/core/src/core/MantineProvider/use-mantine-color-scheme/use-mantine-color-scheme.ts#L45

### Possible fix

Pass the configuration down to make it take effect?

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.2](https://github.com/mantinedev/mantine/releases/tag/7.4.2)

**Comment by Songkeys** [comment]
I don't think this fixed the issue? When the colorScheme is auto, it'll always fall into the  `getInitialValueInEffect: false` call inside the use-mantine-color-scheme hook. Please see my pasted code link ⬆️
