### ISSUE TITLE
[bug:docs] menu components are over navbar

### ISSUE THREAD

**Issue by soham2k06** [mantinedev/mantine#5556]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Every components like menus, selects, comboboxes are overlaying on navbar.
It means navigation bar has lower z-index than these components.
Not talking about modals or drawers.

### Possible fix

Give higher z-index to navigation bar but make sure to keep it lower than modal.

### Self-service

- [x] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.2](https://github.com/mantinedev/mantine/releases/tag/7.4.2)
