### ISSUE TITLE
MultiSelect: multiple `combobox.closeDropdown()` in `onBlur`

### ISSUE THREAD

**Issue by Toshinaki** [mantinedev/mantine#5561]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

None

### Describe the bug

https://github.com/mantinedev/mantine/blob/master/packages/@mantine/core/src/components/MultiSelect/MultiSelect.tsx#L358C7-L358C7

```
onBlur={(event) => {
  onBlur?.(event);
  combobox.closeDropdown();
  searchable && combobox.closeDropdown();
  setSearchValue('');
}}
```
Multiple calls of `combobox.closeDropdown()`, this might be a bug.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.2](https://github.com/mantinedev/mantine/releases/tag/7.4.2)
