### ISSUE TITLE
[bug:docs] version menu is not stable while scrolling

### ISSUE THREAD

**Issue by soham2k06** [mantinedev/mantine#5562]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

While scrolling, the select menu for version selection is not stable.

Uploading Screen Recording 2024-01-13 at 6.41.49 PM.mov…

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.4.2](https://github.com/mantinedev/mantine/releases/tag/7.4.2)
