### ISSUE TITLE
Columns property from Grid does not accept values by breakpoint

### ISSUE THREAD

**Issue by arctouch-richardlopes** [mantinedev/mantine#5566]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The `columns` property does not behave like other properties which accept values by breakpoint like `gutter`. Is it possible to change the `columns` property to accept breakpoint values?

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/beautiful-pond-5sj8p2

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior, columns prop does not support this feature. It is not planned to add this feature in the future.

**Comment by arctouch-richardlopes** [comment]
@rtivital Thanks for the quick answer. Is there any other way to achieve this behavior?
