### ISSUE TITLE
`Menu.Item`'s component bugs out with 'next/link'

### ISSUE THREAD

**Issue by ethanbonin** [mantinedev/mantine#5571]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.4.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

We've got a quirky issue in our dropdown menu. When hovering over either Link 1 or Link 2, both items trigger their hover states simultaneously. Oddly enough, this doesn't happen with Link 3 and Link 4. The twist? This glitch only occurs when we use any non-string component for our Menu.Item components.

In this particular example, I am using `next/link` but you can easily recreate this with creating a custom anchor component like below:

```jsx
Anchor(props) => <a {...props} />
```

#### Package Versions
@mantine/* = ^7.4.1
next = 13.4.12

Here are some screenshots to show you what I mean:

- No Hover
![no hover](https://github.com/mantinedev/mantine/assets/20937454/91ffc245-cf36-44f9-86c0-baf9ffdd50ed)

- Hover on link 1 or link 2
![hover on link 1](https://github.com/mantinedev/mantine/assets/20937454/33a21cbd-60f4-47f3-bc09-ce1b56a7674c)

- Hover on link 3
![image](https://github.com/mantinedev/mantine/assets/20937454/e8a359c1-7e9d-4d48-98e3-82ba7e7c8ae6)

- Hover on link 4
![image](https://github.com/mantinedev/mantine/assets/20937454/21b12c6d-f376-4916-b1c5-fa3862da9554)

- Code Snippet to reproduce the error
```jsx
 <Header>
  <Menu.Target>
    <div>
      <Icon icon="bars" color="white" />
    </div>
  </Menu.Target>
  <Menu.Dropdown>
    <Menu.Item component={Link} href="/link-1">
      Link 1
    </Menu.Item>
    <Menu.Item component={Link} href="/link-2">
      Link 2
    </Menu.Item>
    <Menu.Item component="a" href="/link-3">
      Link 3
    </Menu.Item>
    <Menu.Item component="a" href="/link-4">
      Link 4
    </Menu.Item>
  </Menu.Dropdown>
</Header>
```

- This little snippet shows up in the console log errors.
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `@mantine/core/Box`.
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The error is correct, in order for the component logic to work, it is required to wrap your custom components with `forwardRef`. If you do not own the component, create a wrapper with `forwardRef` which ensures that `ref` prop can be accessed by `Menu.Item`.
