### ISSUE TITLE
Image dont resize with fit = "cover"

### ISSUE THREAD

**Issue by enmanuelmag** [mantinedev/mantine#5573]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I trying to show a image inside a container with a fixed height (175px) but when I use the `Image` tag provided by mantine the image dont resize to cover the available space:

Actual behaviour:
<img width="683" alt="image" src="https://github.com/mantinedev/mantine/assets/7991036/58bf801f-c2e9-4d69-aa6b-0c7c567a0190">

Code:
<img width="318" alt="image" src="https://github.com/mantinedev/mantine/assets/7991036/9a8264bd-937e-4f3a-a391-a0dc00240c9e">

In the other hand, if I use the `img` html tag and set the same styles the image is render as I spected:
<img width="715" alt="image" src="https://github.com/mantinedev/mantine/assets/7991036/4b7e845e-3144-4507-b2a7-44c4cf243a00">

Code:
<img width="590" alt="image" src="https://github.com/mantinedev/mantine/assets/7991036/b495361c-a4a3-465c-b6bf-67a4b24f772e">

Maybe there ir a mismatch condition of use a `Image` tag inside a `Group`, but I think that is strange that if I use `img` tag works good.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction of the issue. Template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx

**Comment by enmanuelmag** [comment]
Here is the bug reproduction: https://codesandbox.io/p/sandbox/infallible-haze-vw9ghm?file=%2Fsrc%2FApp.tsx

**Comment by rtivital** [comment]
The issue is that you use Image in the Group which is a flex container. If you want the image to take the entire width of the Group, set `flex="1"` on the `Image` component. `fit` property works as intended.

**Comment by enmanuelmag** [comment]
Thanks! I was thinking that the problem was a missing prop/config but I didn't what could be.
