### ISSUE TITLE
useColorScheme doesn't return OS color scheme on first load

### ISSUE THREAD

**Issue by c0nd3v** [mantinedev/mantine#5575]
![image](https://github.com/mantinedev/mantine/assets/32241825/e420449a-1862-430f-b800-e7dbfda28499)
useColorScheme always returns 'light', and then after that it will return the correct color scheme.

### Possible fix
![image](https://github.com/mantinedev/mantine/assets/32241825/5c2f12d6-674e-46a3-a3a4-e340bcc638fc)
https://github.com/mantinedev/mantine/blob/703bf447b1a751daee7f3c2fff9c418bd13f5779/packages/%40mantine/hooks/src/use-media-query/use-media-query.ts#L24C2-L26C4
I believe the code above to be the problem. I only see `useColorScheme` and `useReducedMotion` actually using `useMediaQuery`... I think removing these lines won't break anything and will fix the problem.

Why are we returning the initialValue only if its a boolean? I don't understand the purpose of this.

**Comment by c0nd3v** [comment]
!!! P.S I am not using SSR

**Comment by rtivital** [comment]
Fixed in [7.4.2](https://github.com/mantinedev/mantine/releases/tag/7.4.2)

**Comment by c0nd3v** [comment]
Just tested it on 7.4.2, it's not fixed.
