### ISSUE TITLE
AppShell backdrop support

### ISSUE THREAD

**Issue by keval6706** [mantinedev/mantine#5576]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

[AppShell](https://mantine.dev/core/app-shell/)

Provide backdrop support for the components below: 
1. AppShell.Aside.
2. AppShell.Navbar

Let's say in the mobile view, AppShell.Navbar and AppShell.Aside open in full screen. Instead of opening in the full screen, I want them to open in 70% of the screen, with the remaining 30% of the screen covered by a backdrop or overlay, similar to [Modal](https://mantine.dev/core/modal/).

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This feature is not planned to be implemented in the AppShell component. It is already available in Drawer.
