### ISSUE TITLE
basic grid behavior breaks after migrating from version 6

### ISSUE THREAD

**Issue by Devisione** [mantinedev/mantine#5579]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

When migrating from version 6 to version 7, as well as in the documentation on the mantine website, a problem appears starting from version 7.3.1.

In the attached example you can see that if you do not add overflow: hidden which was previously by default, a trace of the html page remains due to the negative indentation.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-v7-forked-3dtpdm?file=%2Fsrc%2FApp.js%3A6%2C11

### Possible fix

or make overflow: hidden by default.

or add a section to the migration guide.

but the best solution is to roll back the default behavior.

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I've added the change to 7.0 changelog
