### ISSUE TITLE
useMantineColorScheme causes component to be rendered twice 

### ISSUE THREAD

**Issue by c0nd3v** [mantinedev/mantine#5584]
### Describe the bug

For some reason, if I am using useMantineColorScheme, it makes my component render twice for seemingly no reason when the page loads.

(If I’m using StrictMode, the component will render 4 times in total. So the problem is not StrictMode)

**Comment by rtivital** [comment]
Duplicate of #5575

**Comment by c0nd3v** [comment]
Just tested it on 7.4.2, it's not fixed.

**Comment by c0nd3v** [comment]
Okay sure
