### ISSUE TITLE
Select not clearable if using a custom rightSection to override the default svg

### ISSUE THREAD

**Issue by sindrefl** [mantinedev/mantine#5585]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When using the rightSection prop to give a custom chevron (regardless of what it is) while setting clearable to "true", the clearable X is not shown and it is not possible to clear the state

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/clearable-option-7rjrnt

### Possible fix

Reverse the ordering of the clearable and rightsection, such that the clearable X takes precedence if it should exist

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is a breaking change. It is not planned to be implemented. You can easily do that on your side – https://codesandbox.io/p/sandbox/clearable-option-forked-kk7nph?file=%2Fsrc%2FApp.tsx%3A17%2C11
