### ISSUE TITLE
DateInput not rendering properly in nextjs

### ISSUE THREAD

**Issue by Azasratruth** [mantinedev/mantine#5589]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.4.2

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I'm using the mantine next template, only added the form and date packages after upgrading to the latest version.  
The date picker isn't rendering properly. 

![Screenshot (724)](https://github.com/mantinedev/mantine/assets/66676690/9fa89a44-acb0-4d79-a1a1-cce364a3c8e7)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/frosty-stallman-d6wl9f?file=%2Fapp%2Fpage.tsx%3A12%2C1&workspaceId=d1ca2d2d-e2d9-4af2-ba3c-a9774ee07580

### Possible fix

Haven't found any.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by FinnAlexanderWalker** [comment]
Hi!
I think you might be missing some styles?

Have you imported the core and dates styles for mantine?
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";

**Comment by rtivital** [comment]
https://help.mantine.dev/q/dates-missing-styles
