### ISSUE TITLE
Header menu dropdown is obscured by the sidebar navigation

### ISSUE THREAD

**Issue by AprilNEA** [mantinedev/mantine#5591]
### Link to the page where something is not right

https://mantine.dev/getting-started/

### What is wrong?

When expanding the 'Versions' menu in the Header on the mantine.dev website, the dropdown is partially obscured by the sidebar navigation on the left. This occurs on pages where the sidebar navigation is present and affects the usability of the dropdown menu.

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Thanks for reporting, the issue has been fixed
