### ISSUE TITLE
Drawer doesn't work with 'mt' or 'mb' styling props.

### ISSUE THREAD

**Issue by JasonWeise** [mantinedev/mantine#5595]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.2

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I am trying to create a "secondary" navbar using a Drawer for my navigation solution and have found that the "Drawer" component can have a margin from the left side of the screen using 'ml' style prop, but all other margin props do nothing.
I thought I might be able to use offset,  but unfortunately that is a single value that affects all sides.

Is this a bug or is it intended that the Drawer component cannot have a margin at the top or bottom?

Note: I also tried to set position:absolute instead of fixed, but that didn't actually do anything either.

Thanks for the awesome UI library. I absolutely love it!

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Style props are applied correctly to the drawer component, they are added to the root element the same way as in all other components. Elements with absolute or fixed position cannot have margins, their position is controlled with `top`, `right`, `left` and `bottom` CSS properties.
