### ISSUE TITLE
The csp still blocks styles, even using the getStyleNonce function

### ISSUE THREAD

**Issue by igomest** [mantinedev/mantine#5596]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.2.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

I need to put the 'style-src' self 'security directive in my application's csp. Without using the 'unsafe-inline' clause.

Even using the getStyleNonce function, my styles are still being blocked.

I create the settings in vite.config and assign the csp settings in index.html:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%- csp %>
    
    <title>Vite + React + TS</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>

```

If you remove the 'style-src 'self' directive in vite.config you will see that styles will be enabled:

```jsx
createHtmlPlugin({
          minify: true,
          inject: {
            data: {
              csp: `<meta http-equiv="Content-Security-Policy" content="img-src 'self' blob: data: ; 
              style-src 'self';
              object-src 'none';
              upgrade-insecure-requests;
              block-all-mixed-content;
              form-action 'self';
              script-src 'self' 'unsafe-inline' 'unsafe-eval';
              worker-src 'self' blob:;">`,
              viteDev: `<script type="module" src="http://localhost:3000/@vite/client"></script>`,
            },
          },
        }),
```

```jsx
import { SHA256 } from "crypto-js";

function generateRandomHash() {
  const randomString =
    Math.random().toString(36).substring(2, 15) +
    Math.random().toString(36).substring(2, 15);
  return SHA256(randomString).toString();
}

<MantineProvider getStyleNonce={generateRandomHash}>
...
```

Even using the nonce, I was unable to enable my styles. Can you help me find a way to enable them?

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/staging-dew-jwcfw4?file=%2Fvite.config.js%3A96%2C15

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Return value of `getStyleNonce` is applied to all `style` tags generated by Mantine. It can be a static value or a random. You need to define specified value in  the `Content-Security-Policy` header as described on MDN website in order for random hash to work.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce
