### ISSUE TITLE
[Feature Request] Tooltip: Add radius

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#560]
### Do you want to contribute this feature and create a pull request

Yes

**Comment by jerebtw** [comment]
That's my only problem with the radius:

![image](https://user-images.githubusercontent.com/49494752/147039406-107d39cc-8996-4be7-a423-bed3863fb0af.png)

**Comment by rtivital** [comment]
I cannot think of a good way to enable arrow for round tooltip, maybe you should set placement to center

**Comment by jerebtw** [comment]
Yes this only happens when you put the placement to the beginning or ending

**Comment by rtivital** [comment]
Fixed in 3.5.0
