### ISSUE TITLE
Next.js Template With Redux Toolkit and Husky and Commitizen Setup

### ISSUE THREAD

**Issue by mr-burhanuddin** [mantinedev/mantine#5604]
### Link to the repository on GitHub

https://github.com/mr-burhanuddin/starter-temp-redux-mantine-nextjs.git

### Features of the template, describe how it is different from other templates

1. Redux Toolkit Is Added
2. Huskey Is Added
3. Commitizen is Added which follows conventional commit guidelines

**Comment by rtivital** [comment]
Please update the README of the template to include a list of included features.

**Comment by mr-burhanuddin** [comment]
@rtivital  Done
