### ISSUE TITLE
Version select menu is hidden behind side nav bar

### ISSUE THREAD

**Issue by tobycm** [mantinedev/mantine#5607]
### Link to the page where something is not right

https://mantine.dev/form/use-form/

### What is wrong?
Version select menu is hidden behind side nav bar on both Firefox and Chromium

![image](https://github.com/mantinedev/mantine/assets/62174797/9d609e52-9f44-42bf-b54b-1282683ebe8c)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Thanks for reporting, the issue has been fixed
