### ISSUE TITLE
[docs] Slider source link is broken, shows 404

### ISSUE THREAD

**Issue by TheAlan404** [mantinedev/mantine#5610]
### Link to the page where something is not right

https://mantine.dev/core/slider/

### What is wrong?

When clicked on the Show Source button, it takes you to [this link](https://github.com/mantinedev/mantine/blob/master/packages/@mantine/core/src/components/Slider/Slider.tsx) which is a 404

It should be changed to either the directory since the page contains info about RangeSlider in my opinion

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
