### ISSUE TITLE
Menu odd behaviour while triggering opening 

### ISSUE THREAD

**Issue by kitavidavis** [mantinedev/mantine#5611]
### Dependencies check up

- [ ] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

5.3.3

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

I have been using @mantine/core version 5.3.3 since september 2022. All menu components have been working well until recently when I observed a weird behaviour when triggering a menu open. I am rendering a dynamic table and one of the columns is an action column with a menu button. The menu will sometimes open but then two more triggers will freeze the screen, and the menu won't open. Sometimes it does not open at all and it freezes the entire screen. This is my Menu implementation in each row:

`                                            <Menu>
                                            <Menu.Target>
                                                <Button variant="light" rightIcon={<ChevronDown />}>Action</Button>
                                            </Menu.Target>
                                            <Menu.Dropdown>
                                                <Menu.Item onClick={() => {editInvoice(item._id, item.invoices.total)}}>Edit Invoice</Menu.Item>
                                                <Menu.Item>Send by SMS</Menu.Item>
                                                <Menu.Item>Send by email</Menu.Item>
                                                <Menu.Item>Send by WhatsApp</Menu.Item>
                                                <Menu.Item onClick={() => {saveInvoice(item.invoices)}}>Download copy</Menu.Item>
                                                <Menu.Divider />
                                                <Menu.Item color="red" onClick={() => {askDelete(item._id,1, item.invoices.invoice_number)}}>Delete Invoice</Menu.Item>
                                            </Menu.Dropdown>
                                        </Menu>`

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please update to the lastest version and provide a reproduction. Version 5 is no longer supported.

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction.
