### ISSUE TITLE
Carousel: keyboard navigation only works when its child element is focused

### ISSUE THREAD

**Issue by HoHieuLuc** [mantinedev/mantine#5613]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.2

### What package has an issue?

@mantine/carousel

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

The root element can't receive focus so the event handler doesn't trigger, is this the expected behavior?
https://github.com/mantinedev/mantine/blob/06bd805748d68df5e4a62ea5c9d1b2ca1251296f/packages/%40mantine/carousel/src/Carousel.tsx#L339-L345

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/mantine-carousel-wxcsvm

### Possible fix

add tabIndex to the root element so that it can receive focus

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior. Arrow keys work when the focus is somewhere inside the carousel.
