### ISSUE TITLE
Can't change --mantine-color-body variable via cssVariablesResolver

### ISSUE THREAD

**Issue by hitfm00** [mantinedev/mantine#5618]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

```
const resolver: CSSVariablesResolver = (theme) => ({
  variables: {
    '--mantine-color-body': 'violet',
  },
})

```

And in the MantineProvider

```
  <MantineProvider
      theme={theme}
      withCssVariables
      cssVariablesResolver={resolver}
 >

```

Variable cannot change, still `#fff`

> but when I reload the page I see changes half a second, and after this if I use in other components this variable it still '#fff'

---

And in this code I have a typescript error
```
const resolver: CSSVariablesResolver = (theme) => ({
  variables: {
    '--mantine-color-body': 'violet',
  },
})

```

`Type '{ variables: { '--mantine-color-body': string; }; }' is missing the following properties from type 'ConvertCSSVariablesInput': dark, light`

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by hitfm00** [comment]
Mantine use `:root[data-mantine-color-scheme="light"]`
and I just use this and works finally: 
```
const resolver: CSSVariablesResolver = (theme) => ({
  light: {
    '--mantine-color-body': 'violet',
  },
})
``` 

But problem with typescript error still have

**Comment by rtivital** [comment]
https://codesandbox.io/s/damp-cherry-hhgf87?file=/src/App.tsx
