### ISSUE TITLE
[@mantine/core] NumberInput: Jest error

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#562]
### What package has an issue

@mantine/core

### Describe the bug

I get a error when running jest (On dev branch)

```cmd
Summary of all failing tests
 FAIL  src/mantine-core/src/components/NumberInput/NumberInput.test.tsx
  ● @mantine/core/NumberInput › steps value with controls on hold mousedown with a function delay

    expect(jest.fn()).toHaveBeenLastCalledWith(...expected)

    Expected: 50
    Received
           3: 30
    ->     4: 40

    Number of calls: 4

      276 |     });
      277 |
    > 278 |     expect(spy).toHaveBeenLastCalledWith(50);
          |                 ^
      279 |   });
      280 |
      281 |   it('steps value with controls on hold keydown and stepHoldInterval', async () => {

      at Object.<anonymous> (src/mantine-core/src/components/NumberInput/NumberInput.test.tsx:278:17)
```

### In which browser did the problem occur

Jest

**Comment by nrayburn-tech** [comment]
I am pretty sure the tests passed in CI and they are passing for me as well.  Using the `next-minor` branch.

I wonder if the use of timers is causing some flakiness?

**Comment by jerebtw** [comment]
Probably because sometimes I get an error and sometimes not

**Comment by jerebtw** [comment]
I also received another error message after running jest a few times:

```cmd
 FAIL  src/mantine-core/src/components/NumberInput/NumberInput.test.tsx
  ● @mantine/core/NumberInput › steps value with controls on hold mousedown with a millisecond delay value

    expect(jest.fn()).toHaveBeenLastCalledWith(...expected)

    Expected: 40
    Received
           2: 20
    ->     3: 30

    Number of calls: 3

      249 |     });
      250 |
    > 251 |     expect(spy).toHaveBeenLastCalledWith(40);
          |                 ^
      252 |   });
      253 |
      254 |   it('steps value with controls on hold mousedown with a function delay', async () => {

      at Object.<anonymous> (src/mantine-core/src/components/NumberInput/NumberInput.test.tsx:251:17)
```

**Comment by rtivital** [comment]
I do not have any issues that you are referring to in this PR, please verify that your fork is synced with the main repo.

**Comment by jerebtw** [comment]
My fork is synced with the main repo and I get this error only sometimes. (Not every run will show this fails)

**Comment by rtivital** [comment]
Hmm, maybe there should be timers mock (https://jestjs.io/docs/timer-mocks), can you check if mocking helps (I cannot reproduce it on my machine, so there is no way of knowing if I've fixed the issue)?

**Comment by nrayburn-tech** [comment]
Changing the timeout to 301, instead of 350 will reproduce the issue more frequently.
https://github.com/mantinedev/mantine/blob/15efa0613515634c1878a41f491bb1b6c77918cc/src/mantine-core/src/components/NumberInput/NumberInput.test.tsx#L247

I don't have any experience mocking timers, but I do think that is the solution.  It might take me a while before I can get to it though.

**Comment by jerebtw** [comment]
Fixed by https://github.com/mantinedev/mantine/pull/582
