### ISSUE TITLE
@mantine/form form.initialize inconsistent with the official documentation description

### ISSUE THREAD

**Issue by jackyleefu** [mantinedev/mantine#5623]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.2

### What package has an issue?

@mantine/form

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

All

### Describe the bug

form.initialize no set values snapshot, as a result, the values and snapshot may not be consistent after call form.initialize

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.5.1](https://github.com/mantinedev/mantine/releases/tag/7.5.1)
