### ISSUE TITLE
When `TagsInput` `onOptionSubmit` is just called on submitting with Enter key with focus on the input, but the return value is not used ever.

### ISSUE THREAD

**Issue by zepc007** [mantinedev/mantine#5631]
### Dependencies check up

- [ ] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When `TagsInput` `onOptionSubmit` is just called on submitting with Enter key with focus on the input, but the return value is not used ever.
The source code is below that pics:
![image](https://github.com/mantinedev/mantine/assets/38693407/0d5e872e-2b2c-43f6-9e00-a4389b83c63e)
![image](https://github.com/mantinedev/mantine/assets/38693407/07a73b38-3e33-4046-95e7-dc375fe49283)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I do not understand what do you mean by "return value is not used ever". The value can be accessed by the function that is being passed to the component.

**Comment by zepc007** [comment]
> I do not understand what do you mean by "return value is not used ever". The value can be accessed by the function that is being passed to the component.

As I mentioned above, if i change `inputValue` in function  `onOptionSubmit` , like "a" -> "abc", the `inputValue` is still "a", not "abc".

**Comment by zepc007** [comment]
> I do not understand what do you mean by "return value is not used ever". The value can be accessed by the function that is being passed to the component.

As I mentioned above, if i check `inputValue` in function  `onOptionSubmit` , for example, I need the `inputValue` is all number like `123`, but I input and sumbit was `abc`, so I will throw a notice error and return `null` in function `onOptionSubmit`,  but `abc` still be submited and displayed

**Comment by zepc007** [comment]
In Another case: 
when I input `abc`, and I want to add a prefix like `GIT-`, so the final value I want was `GIT-abc`. Actually, the final value was still `abc`.

**Comment by rtivital** [comment]
I do not understand the issue. You can add prefix or customize value in any way in the onChange function.

https://codesandbox.io/p/sandbox/heuristic-solomon-vymg5x?file=%2Fsrc%2FApp.tsx%3A8%2C17

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction with further explanation.
