### ISSUE TITLE
Accordion with ThemeIcon has incorrect chevron rotation

### ISSUE THREAD

**Issue by nguyenkhois** [mantinedev/mantine#5637]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

Accordion with ThemeIcon has incorrect chevron rotation.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/mantine-accordion-example-c8m9m5

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by msv96** [comment]
Hi @nguyenkhois, adding width to chevron style resolves this issue.
https://codesandbox.io/p/devbox/mantine-accordion-example-forked-ngk47y?file=%2Fsrc%2FAccordionWithThemeIcon.tsx%3A13%2C19

**Comment by rtivital** [comment]
You need to make sure that your icon has the same width as chevron size – https://codesandbox.io/p/devbox/mantine-accordion-example-forked-hfzkyp?file=%2Fsrc%2FAccordionWithThemeIcon.tsx%3A7%2C14

**Comment by nguyenkhois** [comment]
Thanks a lot!
