### ISSUE TITLE
[Docs] "View full default theme source on Github" points to a dead link

### ISSUE THREAD

**Issue by szpytfire** [mantinedev/mantine#5646]
# Steps to reproduce

1. Head over to https://v1.mantine.dev/pages/theming/#default-theme
2. Click on `View full default theme source on Github`
3. Get redirected to dead link

**Comment by rtivital** [comment]
v1 website is no longer maintained and may include broken links. It is not planned to fix it. To get up-to-date information about the project, use mantine.dev website.
