### ISSUE TITLE
Disabled styles cannot be overwritten

### ISSUE THREAD

**Issue by trevordebard** [mantinedev/mantine#5651]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

When disabling a TextInput, I want to change the color of the value inside of the TextInput element. 

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/nnaughty-leaf-vx5f26

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by yverby** [comment]
For such cases, you can use CSS modules
```tsx
import classes from '../styles.module.css';

<TextInput classNames={{ input: classes.disabled }} />
```

**Comment by trevordebard** [comment]
> For such cases, you can use CSS modules
> 
> ```tsx
> 
> import classes from '../styles.module.css';
> 
> 
> 
> <TextInput classNames={{ input: classes.disabled }} />
> 
> ```

Which selector do you use in that situation? When I tested with css modules I was unable to use the data-disabled selector due to it not being pure.

**Comment by yverby** [comment]
> > For such cases, you can use CSS modules
> > ```tsx
> > import classes from '../styles.module.css';
> > 
> > <TextInput classNames={{ input: classes.disabled }} />
> > ```
> 
> @yverby Which selector do you use in that situation? When I tested with css modules I was unable to use the &[data-disabled] selector due to it not being pure.
> 
> The exact error was: Selector &[data-disabled] is not pure (pure selectors must contain at least one local class or id)

The same selector that you use in your codesandbox

`styles.module.css`
```css
.input {
  &[data-disabled] {
    ...
  }
}
```
`component.tsx`
```js
import classes from './styles.module.css`;

<TextInput classNames={{ input: classes.input }} />
```

**Comment by trevordebard** [comment]
> > > For such cases, you can use CSS modules
> > > ```tsx
> > > import classes from '../styles.module.css';
> > > 
> > > <TextInput classNames={{ input: classes.disabled }} />
> > > ```
> > 
> > 
> > @yverby Which selector do you use in that situation? When I tested with css modules I was unable to use the &[data-disabled] selector due to it not being pure.
> > The exact error was: Selector &[data-disabled] is not pure (pure selectors must contain at least one local class or id)
> 
> The same selector that you use in your codesandbox
> 
> `styles.module.css`
> 
> ```css
> .input {
>   &[data-disabled] {
>     ...
>   }
> }
> ```
> 
> `component.tsx`
> 
> ```js
> import classes from './styles.module.css`;
> 
> <TextInput classNames={{ input: classes.input }} />
> ```

@yverby Because that selector is not pure, it does not work with css modules in Next js. Please see this Codesandbox for an example. Am I missing something? 

https://codesandbox.io/p/devbox/solitary-wildflower-forked-r9ptp9?file=%2Fpages%2Findex.tsx

`Syntax error: Selector "&[data-disabled]" is not pure (pure selectors must contain at least one local class or id)`

**Comment by yverby** [comment]
@trevordebard That's because you need to install `postcss`, follow this [guide](https://mantine.dev/guides/next/#postcss-setup)

Or if you don't have `postcss` installed, don't use nested selectors
```css
.input[data-disabled] {
  ...
}
```
