### ISSUE TITLE
Checkbox layout is broken in 7.5.0

### ISSUE THREAD

**Issue by julienben** [mantinedev/mantine#5652]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Hey there,
I noticed that the styling of the Checkbox component is broken in the latest version.
The label is always on the left and there is no margin between the label and the checkbox itself.
You can see it here: 
<img width="236" alt="image" src="https://github.com/mantinedev/mantine/assets/8948127/f6bb9e2c-651b-4112-8eb5-19cad2691cbd">
and on the [relevant docs page](https://mantine.dev/core/checkbox/).

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by pavlyutkin** [comment]
+1

**Comment by mpham-hai** [comment]
same for switch

**Comment by ozerenes** [comment]
The error is not just related to layout corruption. Label position attribute was not working. (Radio, Switch, Checkbox). @rtivital

**Comment by julienben** [comment]
Closing as I see a PR to fix this has been merged a few minutes ago. Thanks 🙏
