### ISSUE TITLE
ActionIcon size not working.

### ISSUE THREAD

**Issue by nawbc** [mantinedev/mantine#5669]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

None

### Describe the bug

7.4.0
![image](https://github.com/mantinedev/mantine/assets/45007226/f9da2337-8206-48a9-858f-5efd7d9e7569)
7.5.0
![image](https://github.com/mantinedev/mantine/assets/45007226/d826d6bc-a086-496a-b10f-a73fc8f856f0)

```tsx
 <ActionIcon
    c="gray.7"
    size="xs"
    onClick={() => {
      explorer.toggle();
    }}
  >
    <IconArrowsVertical />
  </ActionIcon>
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
ActionIcon size prop controls width and height of the button itself. It does not change the size of the child icon. You need to set it on your side:

```tsx
<ActionIcon
    c="gray.7"
    size="xs"
    onClick={() => {
      explorer.toggle();
    }}
  >
    <IconArrowsVertical size={10} />
  </ActionIcon>
```
