### ISSUE TITLE
Checkbox label position right doesn't work

### ISSUE THREAD

**Issue by Pukka922** [mantinedev/mantine#5674]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Checkbox label position right has no effect. Can also reproduced on the demo page from mantine
[https://mantine.dev/core/checkbox](https://mantine.dev/core/checkbox)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Pukka922** [comment]
The "Switch"-Component has the same problem
[https://mantine.dev/core/switch/](https://mantine.dev/core/switch/)

**Comment by trevordebard** [comment]
"Radio" has the same issue

https://mantine.dev/core/radio/

**Comment by matthiasfeist** [comment]
For all of them there also seems to be the gap between the label and the element missing that was there before.

**Comment by rtivital** [comment]
The issue has been resolved, the fix will be available with the next patch.

**Comment by tks-sugita** [comment]
Thank you for your response. Approximately when is the release expected?

**Comment by rtivital** [comment]
Fixed in [7.5.1](https://github.com/mantinedev/mantine/releases/tag/7.5.1)
