### ISSUE TITLE
Redundant styles for `ScrollArea` in `Autocomplete` and `Select` dropdown lists

### ISSUE THREAD

**Issue by yverby** [mantinedev/mantine#5676]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.0

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

All

### Describe the bug

`Autocomplete` and `Select` components use `ScrollArea` component for dropdown lists by default, but `padding` is displayed incorrectly for dropdown lists. This is most noticeable in [this example](https://mantine.dev/core/autocomplete/#dropdown-padding).

It looks like [these styles](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/components/Combobox/Combobox.module.css#L192) are redundant for [this component](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/components/Combobox/OptionsDropdown/OptionsDropdown.tsx#L137).

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
