### ISSUE TITLE
onClick prop not working in legendProps in charts

### ISSUE THREAD

**Issue by bastiengrignon** [mantinedev/mantine#5681]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.0

### What package has an issue?

@mantine/charts

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

When using a `<LineChart />` mantine component and using `legendProps={{}}` to passed prop to Recharts `Legend` component, the onClick in not working. 
I've dig a little bit in the mantine code and you spread well the legendProps to the **Legend** component: 
https://github.com/mantinedev/mantine/blob/259b74f5cac97170c76d917daebfc32b4bd1b14d/packages/%40mantine/charts/src/LineChart/LineChart.tsx#L263

But you're using custom `content` prop from **Legend** to render the series so the **onClick** handler you be passed to the `ChartLegend` component: 
https://github.com/mantinedev/mantine/blob/259b74f5cac97170c76d917daebfc32b4bd1b14d/packages/%40mantine/charts/src/LineChart/LineChart.tsx#L253 

### Possible fix

It could be fixed by passing down `onClick={legendProps?.onClick}` to `<ChartLegend />` component and applying the onClick prop here: https://github.com/mantinedev/mantine/blob/259b74f5cac97170c76d917daebfc32b4bd1b14d/packages/%40mantine/charts/src/ChartLegend/ChartLegend.tsx#L84

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Default legend provided by `@mantine/charts` package is not supposed to handle any events. If you need this functionality, override the legend component by setting `legendProps={{ content }}`.
