### ISSUE TITLE
Error loading component Styles API data for Pie Chart

### ISSUE THREAD

**Issue by MohammedShams** [mantinedev/mantine#5686]
### Link to the page where something is not right

https://mantine.dev/charts/pie-chart/?t=styles-api

### What is wrong?

The styles API are not visible in Mantine Pie Chart.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.5.2](https://github.com/mantinedev/mantine/releases/tag/7.5.2)
