### ISSUE TITLE
@mantine/dates DateInput defining date props does not allow selection of previous dates

### ISSUE THREAD

**Issue by Leon-Avanade-Carbonell** [mantinedev/mantine#5692]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.0

### What package has an issue?

@mantine/dates

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

```typescript
<DateInput
  label='label goes here'
  date={
    form.values.applyStartDate
      ? dayjs(
          form.values.applyStartDate
        ).toDate()
      : undefined
  }
  maxDate={dayjs(
    form.values.applyStartDate
  ).toDate()}
  error={form.errors.activationDate}
  {...form.getInputProps('activationDate')}
  data-testid="test-activation-date"
/>
```

In the example above, when I click on the DateInput component, the date is shown (expected behaviour).
However, it does not allow me to select dates from previous months and earlier.

Additional observations:
It seems like setting the date will lock the user in the month of the currently selected date. The left and right buttons will be enabled but would not work.

### Possible fix

When I use an uncontrolled component (using the same form) and use the associated properties, I am able to select the days from previous months.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`date` property controls the date. If you do not provide `onDateChange` handler, the value cannot be changed. You can also use `defaultDate` instead if you would rather not store date state.
