### ISSUE TITLE
RangeError: Invalid time value at Date.toISOString

### ISSUE THREAD

**Issue by Juanryhn** [mantinedev/mantine#5701]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

6.0.21

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

when I try to run a unit test this error occured, I have checked in the browser and the defaultValue always filled. and there is no problem when I run it in the browser this error occur just when I run the unit test. I used jest and React Testing Library

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Juanryhn** [comment]
![image](https://github.com/mantinedev/mantine/assets/87475729/14656757-873d-4423-b4a7-01441a133136)

**Comment by rtivital** [comment]
Please provide a repository with a minimal reproduction of the error.
