### ISSUE TITLE
Initial state in DatePickerInput type="range"

### ISSUE THREAD

**Issue by bastiengrignon** [mantinedev/mantine#5719]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/dates

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When adding default values in `useState` for a `DatePickerInput` component like this: 
```
const [dateRange, setDateRange] = useState([dayjs(), dayjs().subtract(7, 'day')])
```
You can see on the screenshot below that only the **first** and **last** day are colored :
![Screen at 02-05-2024_14:53:42](https://github.com/mantinedev/mantine/assets/41306995/630b257c-d2be-4068-8c48-e459bff0dd3d)

Compared to when you select manually using the mouse, all days inside the range are colored: 
![Screen at 02-05-2024_14:55:33](https://github.com/mantinedev/mantine/assets/41306995/b40c640d-6cf1-4bda-8d1d-f8fbe22437cb)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-default-value-z6kjzk

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`@mantine/dates` components work with `Date` object, not with `dayjs` instances.
https://codesandbox.io/p/sandbox/mantine-default-value-forked-wtj4cf?file=%2Fsrc%2FApp.tsx%3A10%2C34
