### ISSUE TITLE
Is there has a way to change notification global width?

### ISSUE THREAD

**Issue by Mayvis** [mantinedev/mantine#5720]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/notifications

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

I using below code to change notification global width

```ts
import { createTheme } from '@mantine/core'
import { Notifications } from '@mantine/notifications'

export const mantineTheme = createTheme({
  components: {
    Notification: Notifications.extend({
      styles: {
        root: {
          width: '300px',
        },
      },
    }),
  },
})
```

When I change the width, it children width successfully go to 300px, but I still got `calc(100% - var(--mantine-spacing-md)*2)` width in notification root DOM that will make the position not correctly. Is there has a way to fix this?

<img width="519" alt="截圖 2024-02-05 晚上9 55 50" src="https://github.com/mantinedev/mantine/assets/12667910/c1fc4704-e539-4de8-b2b1-349c6f003096">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by yshterev** [comment]
@Mayvis `Notfication` component has a `containerWidth` prop
https://mantine.dev/x/notifications/?t=props

**Comment by Mayvis** [comment]
@yshterev thank you
