### ISSUE TITLE
Appshell demo page is broken

### ISSUE THREAD

**Issue by techterbium** [mantinedev/mantine#5721]
### Link to the page where something is not right

https://mantine.dev/app-shell/?e=BasicAppShell

### What is wrong?

The mentioned URL doesn't display the examples. Tried in both Chrome and Safari. No console errors and network failures. 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The url is fully functional both in Chrome and Safari. If you are not sure how it works, click different buttons at the bottom right of the screen.

**Comment by MPiland** [comment]
I know this is closed, but I want to add I'm having the same issue. See screenshot.

**Comment by MPiland** [comment]
I know this is closed, but I want to add I'm having the same issue. See screenshot.
