### ISSUE TITLE
PolymorphicComponentProps/PolymorphicRef types are not exported, causing errors when using "NodeNext" resolution

### ISSUE THREAD

**Issue by waweber** [mantinedev/mantine#5722]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

When creating a library with TS settings `"declaration": true, "moduleResolution": "NodeNext"`, exporting a component created with `createPolymorphicComponent` throws an error:

> The inferred type of 'MyComponent' cannot be named without a reference to './node_modules/@mantine/core/lib/core/factory/create-polymorphic-component.js'. This is likely not portable. A type annotation is necessary.

From what I gather, this is because TypeScript decides it is necessary to annotate the exported type in the declarations file using `PolymorphicComponentProps`, and this type is not reachable via the package exports.

### Possible fix

Just adding

`export type { PolymorphicComponentProps, PolymorphicRef } from './create-polymorphic-component'`

to `@mantine/core/src/core/factory/index.ts` should fix the issue.

Example project:
[example.zip](https://github.com/mantinedev/mantine/files/14173145/example.zip)

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
