### ISSUE TITLE
<Select /> is always clearable, even with `clearble` set to false

### ISSUE THREAD

**Issue by dr15** [mantinedev/mantine#5726]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

tl:dr All selects are clearable by toggling the selected option.

1. Go to any select in the documentation where the `clearable` flag wasn't added.
2. Select an option.
3. Open dropdown again and click on the same option.

Expected result: 
Value remains the same.

Actual result:
Selection is cleared and returned value is `null`

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/core/select/#clearable

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This logic is not related to `clearable` prop. If you want to change this behavior, set `allowDeselect={false}` prop.
