### ISSUE TITLE
<Combobox /> `keepMounted` should be false by default

### ISSUE THREAD

**Issue by dr15** [mantinedev/mantine#5727]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Documentation claims the the <Combobox /> `keepMounted` prop is set to `false` by default, yet unless it is explicitly set to `false`, the dropdown content is still attached to the DOM in the Portal.

Go to the `<Combobox />` documentation, open the DOM and look through the portals, you will find the options of the different comboboxes attached.

This affects the `<Select />` and `<MultiSelect />` as well, and the same DOM check can be done on their respective documentation too.

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/core/combobox/

### Possible fix
https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/components/Combobox/Combobox.tsx
```
const defaultProps: Partial<ComboboxProps> = {
  keepMounted: true,
  withinPortal: true,
  resetSelectionOnOptionHover: false,
  width: 'target',
  transitionProps: { transition: 'fade', duration: 0 },
};
```
`keepMounted` should probably be `false`

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by LeunensMichiel** [comment]
I'm having the same issue. Rendering a large list of select fields was very hard to render. By setting keepmounted=false the performance was improved drastically.
