### ISSUE TITLE
Enable "color" prop of <Input /> and its derivatives (<TextInput />, etc...)

### ISSUE THREAD

**Issue by kenzaflow** [mantinedev/mantine#5728]
### Discussed in https://github.com/orgs/mantinedev/discussions/5373

<div type='discussions-op-text'>

<sup>Originally posted by **kenzaflow** December  5, 2023</sup>
Today, if I want to change the color (the border), I have to use CSS or through the style prop of input. But the color prop exists, and does nothing on that element. the "c" prop yes, changes the text color</div>

I'm sorry to open this here, but I don't think anyone looks at the Feature requests

**Comment by rtivital** [comment]
CSS is the intended way to style components. Mantine provides Styles API feature to customize styles. It is not planned to add more props for styling inputs.
