### ISSUE TITLE
`defaultRadius` has no effect on <Badge/> component

### ISSUE THREAD

**Issue by Mich0232** [mantinedev/mantine#5729]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Setting `defaultRadius` doesn't change how <Badge/> components are rendered

### Setup
```typescript
const theme = createTheme({
  defaultRadius: 'xs',
});
```
```
return <Badge>Badge with no radius defined</Badge>
```

### Result
<img width="295" alt="Screenshot 2024-02-06 at 16 54 03" src="https://github.com/mantinedev/mantine/assets/16597494/8000b1cc-4a8d-4d09-81a0-93217a74d08d">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The Badge component has xl radius by default. It is intended, as it is usually this way in design systems. This is not planned to be changed. If you want to change border-radius of all badges, use default props instead – https://mantine.dev/theming/default-props/
