### ISSUE TITLE
Status wont change for accept/unaccepted types on Dropzone

### ISSUE THREAD

**Issue by dukesx** [mantinedev/mantine#573]
### What package has an issue

@mantine/dropzone

### Describe the bug

When i select/drop files onto drop zone, the "status" doesnt change at all. Either i upload an image or a document, it wont judge the mime type , causing accepted and rejected to be always false. 

I am using mantine 3.4.0 with dropzone also on 3.4.0

```jsx

 <Dropzone
                  className="mt-10"
                  onDrop={(file) => {
                    console.log(file);
                  }}
                  maxSize={3 * 1024 ** 2}
                  accept={[
                    "image/png",
                    "image/jpeg",
                    "image/jpg",
                    "image/sgv+xml",
                    "image/gif",
                  ]}
                  loading={loadingUpload}
                >
                  {(status) => (
                    <Group
                      position="center"
                      spacing="xl"
                      style={{ minHeight: 220, pointerEvents: "none" }}
                    >
                      <ImageUploadIcon
                        status={status}
                        style={{
                          width: 80,
                          height: 80,
                        }}
                      />

                      <div>
                        <Text size="sm" inline>
                          Drag images here or click to select files
                        </Text>
                        <Text size="sm" color="dimmed" inline mt={7}>
                          Attach as many files as you like, each file should not
                          exceed 5mb
                        </Text>
                      </div>
                    </Group>
                  )}
                </Dropzone>
```

### In which browser did the problem occur

All

### Do you know how to fix the issue

No

### Possible fix

I have no idea what went wrong.

**Comment by rtivital** [comment]
I cannot replicate that in sandbox – https://codesandbox.io/s/staging-bird-c9vsn?file=/src/App.tsx

**Comment by dukesx** [comment]
@rtivital Check it now, i have added console.log and debugging to the example. You will see , whether you upload an exe or a jpg , status of accepted and rejected dont change

**Comment by dukesx** [comment]
Oh and the icons also dont change with rejected or accepted status

**Comment by rtivital** [comment]
Yeah, there might be something strange happening, I think we may need to remove react-dropzone dependency

**Comment by dukesx** [comment]
I am sure something got missing inside this component, must be a typo or something , because everything else is fine.  React Dropzone and their demos seem to function exactly the way it should but this component doesn't differentiate.

**Comment by Ultra-Instinct-05** [comment]
@dukesx I can't reproduce this as well using your sandbox. The icons seem to be changing correctly and the `isDragAccept` & `isDragReject` values appear to be set correct as well (Checking your sandbox).

![image](https://user-images.githubusercontent.com/34304644/147647905-17b58742-997c-4772-8bb9-af26ac973016.png)

**Comment by dukesx** [comment]
> @dukesx I can't reproduce this as well using your sandbox. The icons seem to be changing correctly and the `isDragAccept` & `isDragReject` values appear to be set correct as well (Checking your sandbox).
> 
> ![image](https://user-images.githubusercontent.com/34304644/147647905-17b58742-997c-4772-8bb9-af26ac973016.png)

did you select an mp4 with accepted params set as image mime type ?

**Comment by Ultra-Instinct-05** [comment]
> did you select an mp4 with accepted params set as image mime type ?

I just dragged a file that is different from the `image` mime type.

> and the sandbox has changed. the above one does not have my changes anymore

The linked sandbox https://codesandbox.io/s/staging-bird-c9vsn?file=/src/App.tsx contains the same code that you posted. I don't see any difference.

**Comment by dukesx** [comment]
> > did you select an mp4 with accepted params set as image mime type ?
> 
> I just dragged a file that is different from the `image` mime type.
> 
> > and the sandbox has changed. the above one does not have my changes anymore
> 
> The linked sandbox https://codesandbox.io/s/staging-bird-c9vsn?file=/src/App.tsx contains the same code that you posted. I don't see any difference.

The sandbox has been tampered. that is not my code. My code had console.logs in almost every place to debug. @rtivital had seen it when i posted it.

**Comment by Ultra-Instinct-05** [comment]
Well, can you then post a fresh sample/codesandbox that reproduces the issue ?

**Comment by dukesx** [comment]
@Ultra-Instinct-05 I will post one as soon as possible but a busy with my Clinic. I am closing this for now.

**Comment by pavi2410** [comment]
It isn't working for me too.

**Comment by perroudsky** [comment]
It's still the case.
File is accepted but status won't change.

Demo : https://codesandbox.io/s/jovial-kapitsa-q78pjk?file=/src/App.tsx

**Comment by rtivital** [comment]
@perroudsky your sandbox
- uses 3.x version while current version is 4.x
- works fine for me – status changes as expected

If you are using react 18 you need to wait for 4.3 release for react-dropzone bug fixes

**Comment by perroudsky** [comment]
Hi @rtivital thanks for the quick answer!
I don't get it, I've updated the packages to 4.x and it still does not work.

I'm on react 17

**Comment by TimisRobert** [comment]
Hello, I'm having the same issue with React 17 and Mantine 5.0.0-alpha.11.
This sandbox also doesn't work: https://codesandbox.io/s/staging-bird-c9vsn?file=/src/App.tsx

**Comment by mlarcher** [comment]
@rtivital any ETA for the release of v5 ?

**Comment by mlarcher** [comment]
sorry, I forgot I already asked recently there https://github.com/mantinedev/mantine/discussions/1610#discussioncomment-2931218

**Comment by imranbarbhuiya** [comment]
This isn't working for me. Even it's not working in mantine webisite

**Comment by rtivital** [comment]
Status changes correctly when a file is dragged over the dropzone, it was tested in all major browsers.

**Comment by imranbarbhuiya** [comment]
Oh, I thought it'll change the state when we upload a file. But if it's only for drag then It's working fine. Also thanks for the quick response
