### ISSUE TITLE
ScrollArea's offsetScrollbars property does not work

### ISSUE THREAD

**Issue by KeiKawashima-HEROZ** [mantinedev/mantine#5733]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

ScrollArea's offsetScrollbars property does not work.

https://mantine.dev/core/scroll-area/ is also not working.

It was working fine in 7.2.2.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by koktajlik** [comment]
+1, I have the same problem

**Comment by Kukwa** [comment]
+1, I have the same problem

**Comment by rtivital** [comment]
Fixed in [7.5.2](https://github.com/mantinedev/mantine/releases/tag/7.5.2)
