### ISSUE TITLE
NumberInput field is causing an error in the console when it's empty

### ISSUE THREAD

**Issue by ziadeh** [mantinedev/mantine#5735]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When the NumberInput field is empty and you navigate to it using the Tab key on the keyboard before switching to another input, an error is displayed in the console. The same issue is observed on your website. To check it, clear a field and press Tab on your keyboard, then observe the error that appears in the console.

![Screenshot](https://github.com/mantinedev/mantine/assets/120175/046634e0-e317-487e-9b97-950bb98fe1d4)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by jadamita** [comment]
I am unable to reproduce this issue. What browers and version?

**Comment by ziadeh** [comment]
I'm using Arc browser version 1.28.0.
It seems to be a browser issue, I have tested it on Chrome, and no errors were detected.

**Comment by rtivital** [comment]
I cannot reproduce issue in any of the supported browsers (https://mantine.dev/about/#browser-support).
