### ISSUE TITLE
ButtonGroup focus ring overlaps

### ISSUE THREAD

**Issue by Songkeys** [mantinedev/mantine#5736]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

<img width="293" alt="SCR-20240207-sjgl" src="https://github.com/mantinedev/mantine/assets/22665058/c8337627-cc3a-425f-b659-c3ca3b779033">

<img width="270" alt="SCR-20240207-sjob" src="https://github.com/mantinedev/mantine/assets/22665058/a628dc51-b29f-492a-b7fd-8dfa92153391">

<img width="278" alt="SCR-20240207-sjqd" src="https://github.com/mantinedev/mantine/assets/22665058/b3930dec-5e70-4050-b378-f18fd3be5813">

Only the last one is shown normally.

### If possible, include a link to a codesandbox with a minimal reproduction

<https://mantine.dev/core/button/#buttongroup>

### Possible fix

[Set `position: relative; z-index: 1000` when `:hover`](https://stackoverflow.com/questions/11802399/outline-getting-hidden-by-the-next-element)

### Self-service

- [x] I would be willing to implement a fix for this issue

**Comment by kiranvarma01** [comment]
Is this issue still open?
if Yes, can you provide the some steps to reproduce this issue.

**Comment by rtivital** [comment]
Fixed in [7.6.1](https://github.com/mantinedev/mantine/releases/tag/7.6.1)
