### ISSUE TITLE
`showNotification()` doesn't work

### ISSUE THREAD

**Issue by NriotHrreion** [mantinedev/mantine#5744]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/notifications

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

**Description**

I use `showNotification` to display a notification in my page, but it doesn't work.

My code:

```tsx
// ...

const Page: React.FC = () => {
  useEffect(() => {
    // ...
    showNotification({
      title: "Registered successfully!",
      message: "Please enter the user name and password again to login.",
      color: "teal"
    });
  }, []);

  return (
    <div>
      {/* ... */}
    </div>
  );
}
```

**Expected Behavior**

Show the notification when opening the page.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Have you followed all installation instructions?
https://mantine.dev/x/notifications/

**Comment by NriotHrreion** [comment]
solved.

**Comment by kinoli** [comment]
I'm guessing @NriotHrreion forgot to import the css file like I did. Works now.

`import '@mantine/notifications/styles.css';`

**Comment by NriotHrreion** [comment]
> I'm guessing @NriotHrreion forgot to import the css file like I did. Works now.
> 
> `import '@mantine/notifications/styles.css';`

Yes, I did forget this. But soon I found it in the docs.
