### ISSUE TITLE
PilsInput rightSection icon does not render

### ISSUE THREAD

**Issue by LarsEjaas** [mantinedev/mantine#5747]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Adding a `leftSection` prop to the `<PillsInput>` component is working as intended. However, adding a `rightSection` prop, the element will not render in the DOM.
For now, I have fixed this by re-positioning the `leftSection` - but it would be nice to get this fixed.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rilrom** [comment]
I'm unable to replicate this issue in v7.5.1. You'll see in the demo below that both `leftSection` and `rightSection` are showing.

https://codesandbox.io/p/sandbox/jolly-forest-ymsw4j?file=%2Fsrc%2FApp.js

**Comment by LarsEjaas** [comment]
> I'm unable to replicate this issue in v7.5.1. You'll see in the demo below that both `leftSection` and `rightSection` are showing.
> 
> https://codesandbox.io/p/sandbox/jolly-forest-ymsw4j
> 
> Are you able to provide a reproducible demo?

Thanks a lot for taking the time to help! 

After looking into you codeSandbox and some additional debugging I discovered I was accidentally spreading a loading state into the pils-input field.
