### ISSUE TITLE
Please update Redwood instructions to configure Vite instead of Webpack

### ISSUE THREAD

**Issue by beardo01** [mantinedev/mantine#5750]
### Link to the page where something is not right

https://mantine.dev/guides/redwood/

### What is wrong?

The instructions on https://mantine.dev/guides/redwood/ include details about how to configure PostCSS for Webpack instead of Vite. Vite is now the preferred build tool in Redwood so it would be beneficial to update these instructions for Vite instead of Webpack (or include both).

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The guide has been updated
