### ISSUE TITLE
use-resize-observer demo doesn't work on Firefox

### ISSUE THREAD

**Issue by Eldemarkki** [mantinedev/mantine#576]
### Link to the page where something nasty is located

https://mantine.dev/hooks/use-resize-observer/#usage

### Exact quote of what is wrong

The demo prompts the user to "Resize textarea by moving its left bottom corner". However, in Firefox I'm not able to resize the textarea at all. The cursor doesn't even change to the resizing icon. In Chrome it worked correctly. 

I was able to reproduce the bug locally by creating an empty React project, installing Mantine there, and copy-pasting the demo code to my project. Then I removed `pointerEvents: 'none'` from the textarea's style, and after that it worked in both Firefox and Chrome. I'm not sure if that is the correct way of fixing this though, which is why I'm not making a pull request. If someone confirms that this is a good fix, I'd be happy to make the pull request then! Here is the [broken line](https://github.com/mantinedev/mantine/blob/master/docs/src/demos/hooks/use-resize-observer.tsx#L15), where I removed `pointerEvents: 'none'`.

Firefox version: 95.0.2 (64-bit)

Also, the text says to resize from the left bottom corner, but on both Firefox and Chrome the resize handle is on the right bottom corner. I can create the pull request for this.

### Are you willing to create pull request with the fix?

Yes

**Comment by Eldemarkki** [comment]
> Also, the text says to resize from the left bottom corner, but on both Firefox and Chrome the resize handle is on the right bottom corner. I can create the pull request for this.

Created #577 for this

**Comment by rtivital** [comment]
Thanks for reporting, this happens because we have `pointer-events: none` on textarea, if it is removed, then textarea will be resizable

**Comment by rtivital** [comment]
Fixed in 3.5.0
