### ISSUE TITLE
ColorScheme is not exported by @mantine/core

### ISSUE THREAD

**Issue by IMNOTIKE** [mantinedev/mantine#5760]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.2

### What package has an issue?

@mantine/core

### What framework do you use?

Gatsby

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

The documentation for [use-local-storage](https://mantine.dev/hooks/use-local-storage/#example) on the website refers to an import from @mantine/core called 'ColorScheme' but the ide cannot find it in the package.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rilrom** [comment]
Looks like `ColorScheme` was removed in v7, a new example will need to be created for `useLocalStorage`.

**Comment by rtivital** [comment]
Fixed in [7.5.3](https://github.com/mantinedev/mantine/releases/tag/7.5.3)
