### ISSUE TITLE
`reset` and `setInitialValues` methods of form hook do not work in Next.js when the initial props com from props. 

### ISSUE THREAD

**Issue by saeidalidadi** [mantinedev/mantine#5767]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/form

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When I use `form.reset` and `form.setInitialValues` inside a hook or `onClick` action of a button to set form values it does not work.
but `setValues` works fine as expected.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`form.reset` resets values to the current `initialValues`. `initialValues` captures the first object given to the form. If the data is changed, values are not updated, you need to handle that on your side.

`form.setInitialValues` does not update form values, it updates `initiaValues` to the given value. This value is later used in `form.reset`.

If you are using fetching library, follow this guide – https://mantine.dev/form/values/#initialize-form
