### ISSUE TITLE
PinInput backward compatibility is broken with last commit

### ISSUE THREAD

**Issue by ctretyak** [mantinedev/mantine#5771]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

onComplete functions added to deps array of useEffect hook and it leads to unxpected calls
you can repoduce it in my example:
- fill input
- press rerender

and you will see in console that pininput call onComplete on every render. I don't think that we should wrap every onComplete function in useCallback, even it worked in previous versions

### If possible, include a link to a codesandbox with a minimal reproduction

https://stackblitz.com/edit/stackblitz-starters-nrptb8?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx,src%2Findex.tsx&title=React%20Starter

### Possible fix

remove onComplete from deps here https://github.com/mantinedev/mantine/commit/4be1392b500b436cb34cff88f841ba397189e1da#diff-2fc5a97aeb8b04f916703021c0e4bc31b80f204d010975f3bcc47439bd01af73R333

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.5.3](https://github.com/mantinedev/mantine/releases/tag/7.5.3)
