### ISSUE TITLE
Grid issues: Margin spacing and breaks server component

### ISSUE THREAD

**Issue by dasveloper** [mantinedev/mantine#5773]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I'm experiencing two issues with the Grid component.

1) When giving a parent `min-height: 100vh`, and putting a Grid inside it, it creates an empty margin equivalent to the Grid's gutter size at the bottom. This margin is created by the `--grid-gutter` style, when unchecked in dev tools the page goes back to full height.

Screenshot: (the black border is the browser window, the red box is set to 100vh, the white is the margin created by the grid)
<img width="1317" alt="Screenshot 2024-02-15 at 11 21 50 AM" src="https://github.com/mantinedev/mantine/assets/28981975/692e7b00-81f9-47ed-8593-57dc65ff3b8b">

2) Grid.Col causes Next.js server components to break forcing you to set `'use client'` on the page/component using a Grid. Grid by itself does not throw the error, but once you add in Col it throws the error.

Screenshot:
<img width="1058" alt="Screenshot 2024-02-15 at 11 27 02 AM" src="https://github.com/mantinedev/mantine/assets/28981975/5428820b-5993-4972-a62b-1bdc8bfffff1">

Example repo: (remove the 'use client' in GridExample.tsx to see issue 2)
https://github.com/dasveloper/grid-issues

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
1. Intended behavior. If you want to remove margins, use Styles API to change styles.
2. https://mantine.dev/guides/next/#compound-components-in-server-components
