### ISSUE TITLE
Please provide a possibility to customize the elements box of NavLink component

### ISSUE THREAD

**Issue by lukasfoidl** [mantinedev/mantine#5776]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The box with the children of the NavLink component has no possibility to be customized except of using css selectors. Please provide a possibility to customize the style of the box of NavLink component (highlighted in the screenshot from the NavLink component of the mantine page)
![Screenshot from 2024-02-16 09-23-02](https://github.com/mantinedev/mantine/assets/83663996/2100252a-f18e-46ae-a6f4-611d05ca8e74)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.5.3](https://github.com/mantinedev/mantine/releases/tag/7.5.3)
