### ISSUE TITLE
Pills with remove button are not compatible with RTL

### ISSUE THREAD

**Issue by AlonMiz** [mantinedev/mantine#5779]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

pills in RTL have been degraded in one of the recent versions
<img width="876" alt="image" src="https://github.com/mantinedev/mantine/assets/1812912/0230774b-bad6-45e6-a145-6cdda97d910f">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in 7.6.0
