### ISSUE TITLE
Resize prop of TextArea component is not working

### ISSUE THREAD

**Issue by waseemk-786** [mantinedev/mantine#5790]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.0

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

For Textarea component resize prop is not working. Instead we've to use resize property in CSS.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Update to the latest version.
