### ISSUE TITLE
Cannot add placeholder to RichTextEditor

### ISSUE THREAD

**Issue by souhagaa** [mantinedev/mantine#5791]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.2

### What package has an issue?

@mantine/tiptap

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

same issue as #3012 

 ```
const editor = useEditor(
    {
      extensions: [
        StarterKit,
        Underline,
        Link,
        TextAlign.configure({ types: ['heading', 'paragraph'] }),
        Placeholder.configure({
          placeholder: placeholder || 'Write something …', // NOT WORKING
        }),
      ],
      content: value,
      editable: disabled,
      onUpdate({ editor }) {
        const currentContent = editor.getHTML();
        onChange?.({ [name]: content });
      },
      onBlur() {
        onBlur?.(name);
      },
    },
    [name, onChange, onBlur],
  );
```
I also tried to use the placeholder prop and it doesn't work 
and `editor.isEmpty `shows `true`

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction.

**Comment by rilrom** [comment]
@souhagaa it looks like the `placeholder` does not show if `editable` is set to `false`. You may need to set it to `editable: !disabled` for it to functionally make sense.

**Comment by souhagaa** [comment]
yes that was my mistake thank you @rilrom , it works now I will close this
