### ISSUE TITLE
Skeleton CSS applies translateZ(0) which breaks the "fixed" position property

### ISSUE THREAD

**Issue by dvmoritzschoefl** [mantinedev/mantine#5792]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.3

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

All

### Describe the bug

When using a list of elements that is drag-and-droppable with a library like **react-beautiful-dnd** that uses **fixed** position properties to animate the elements, then it will not work when mounted as a children of a Skeleton element.

The reason for that seems to be that the Skeleton css applies

`  transform: translateZ(0);
  -webkit-transform: translateZ(0);`

(see https://github.com/mantinedev/mantine/blob/0409b7b2c050e9103d333cf2ace5cb7ec6bb667f/packages/%40mantine/core/src/components/Skeleton/Skeleton.module.css#L17)

which creates a new stacking context and handles fixed position elements as if they were absolute positioned.

This css property seems a bit weird for me, is the intention a browser "hack" for more efficient rendering?

### Possible fix

Remove the transform in the css module.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This CSS property was added intentionally to fix issues in Safari. It is not planned to be removed.
