### ISSUE TITLE
CodeHighlight inside modal scroll issues

### ISSUE THREAD

**Issue by CripyIce** [mantinedev/mantine#5794]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.3

### What package has an issue?

@mantine/code-highlight

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I have an issue with scrolling inside `CodeHighlight` when in RTL layout and inside a `modal`.
When wrapping the `CodeHighlight` inside a `ScrollArea` it works but the layout start on the right instead of the left (when showing code, it should always be LTR even when in RTL layout).
Tried adding `dir="rtl"` to `ScrollArea` but it goes back to the original issue.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-54hklx?file=%2Fpackage.json%3A34%2C43&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsu7t7ia00063b6itu5o59pm%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsu7t7ia00023b6ifmt1hx5x%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsu7t7ia00033b6iytk46ora%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsu7t7ia00053b6i9bl2c011%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsu7t7ia00023b6ifmt1hx5x%2522%253A%257B%2522id%2522%253A%2522clsu7t7ia00023b6ifmt1hx5x%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsu7uusc00513b6icgtv488j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A32%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsu7uusc00513b6icgtv488j%2522%257D%252C%2522clsu7t7ia00053b6i9bl2c011%2522%253A%257B%2522id%2522%253A%2522clsu7t7ia00053b6i9bl2c011%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsu7t7ia00043b6i6vy9syai%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsu7t7ia00043b6i6vy9syai%2522%257D%252C%2522clsu7t7ia00033b6iytk46ora%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsu7t7ia00033b6iytk46ora%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
To fix this issue, set `lockScroll: false` – https://codesandbox.io/p/sandbox/mantine-react-template-forked-dq52pt?file=%2Fsrc%2FApp.tsx%3A64%2C18
