### ISSUE TITLE
`useLocalStorage` doesn't allow to store value without `getInitialValueInEffect` set to `true`

### ISSUE THREAD

**Issue by lgaspari** [mantinedev/mantine#5796]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.3

### What package has an issue?

@mantine/hooks

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Hello folks,

Looking at the `useLocalStorage` hook, even though there's a `useEffect()` for saving the value on storage when `value` is `undefined` but `defaultValue` is not (see [here](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/hooks/src/use-local-storage/create-storage.ts#L147)), it never runs because `value` is always populated with `defaultValue` (see [here as well](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/hooks/src/use-local-storage/create-storage.ts#L101)).

I'm thinking that maybe it has been done this way for SSR because they need the Local Storage available before running, therefore a side-effect would be ideal, but if we are not using SSR and need the value to persist on stage on mount, I have to set `getInitialValueInEffect` to `true`. Is this actually the case? If so, that side-effect seems redundant.

As a side question, is it possible that there are no tests for this hook?

Thanks a lot!

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-wdsz8j

### Possible fix

We could remove the `defaultValue` from [this line](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/hooks/src/use-local-storage/create-storage.ts#L101) but that would certainly break other things. Otherwise, the `useEffect()` could be removed if redundant.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.6.1](https://github.com/mantinedev/mantine/releases/tag/7.6.1)

**Comment by lgaspari** [comment]
> Fixed in [7.6.1](https://github.com/mantinedev/mantine/releases/tag/7.6.1)

It works like a charm, thank you 👍🏼 

I was wondering if you were able to take a look at the `useEffect()` I mentioned above that doesn't actually run ([here](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/hooks/src/use-local-storage/create-storage.ts#L147)). I believe it's redundant giving the fact that there's always a value but I could totally create a separate issue for that, lmk!
