### ISSUE TITLE
[@mantine/dates] TimeInput: not possible to set empty value

### ISSUE THREAD

**Issue by jerguslejko** [mantinedev/mantine#580]
### What package has an issue

@mantine/dates

### Describe the bug

When setting the `value` prop of `<TimeInput />` to `undefined` (eg. `<TimeInput value={undefined} />`, the time value is still displayed (it uses the current timestamp by default).

My use-case: I have `<TimeInput />` as a form input. The default value is `undefined` as I want the user to fill it in. However, the user always sees a timestamp so they don't fill in the field assuming the current timestamp is being used. Under the hood however, the value is still `undefined`.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/competent-sammet-t6mje?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by jerebtw** [comment]
The sandbox is empty

![image](https://user-images.githubusercontent.com/49494752/147519328-be3625b3-f3ca-4df7-b1f9-9e3d2d2d5822.png)

**Comment by jerguslejko** [comment]
whops, fixed. thanks @jerebtw

**Comment by jerebtw** [comment]
Is it important for you to have empty inputs, or can it just be `00:00`?

**Comment by rtivital** [comment]
It already can be set to 00:00, I think providing an option to have a blank field is common case, so we should implement this

**Comment by jerebtw** [comment]
@rtivital can I try this?

**Comment by jerebtw** [comment]
Should it only be possible to leave the input blank at the beginning, or should the user also be able to clear the input?

**Comment by jerguslejko** [comment]
@jerebtw for my current use-case, "just at the beginning" works just fine but in general, it'd be great to support a `clearable` prop

**Comment by rtivital** [comment]
Alright, so what we can do about it:
- Allow input to be empty initially
- Add `clearable`prop, that will show clear button
- When value is filled, it can be cleared only with clear button 

@jerebtw you can work on it, you can do it in the same PR as your `format` on time input to avoid conflicts
