### ISSUE TITLE
[Feature Request] 12 hour format for TimeInput comopnent

### ISSUE THREAD

**Issue by jerguslejko** [mantinedev/mantine#581]
### Usage example, including component/hook API

The `<TimeInput />` component only allows to input a timestamp in a 24-hour format. This is not ideal for US-based users who use a 12-hour format.

The idea here is to support entering a 12-hour format while also being able to specify `am`/`pm`. 

### Possible implementation – describe how the feature can be implemented

The API could be:

```tsx
<TimeInput format="12" /> // this implicitly shows the AM/PM selector
<TimeInput format="24" />
```

### Do you want to contribute this feature and create a pull request

_No response_ - I'd love to help out! Just not sure I can actually implement this in a nice way

**Comment by rtivital** [comment]
How would you advise implementing am/pm selector? Should it be select or text input?

**Comment by jerebtw** [comment]
This could work

![image](https://user-images.githubusercontent.com/49494752/147383581-2ec4ca98-eee9-468b-94e7-98b5a68d5d81.png)

**Comment by jerguslejko** [comment]
yeah something like that would be great @jerebtw! showing the selector if `format == 12`, hiding it if `format == 24`. there should also be some validation (not allowing to input `18:20` if `format == 12`)

**Comment by rtivital** [comment]
Added in 3.6.0
