### ISSUE TITLE
Combobox dropdown position not following custom component target

### ISSUE THREAD

**Issue by SimStm** [mantinedev/mantine#5810]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.3

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

I have a custom component which receive some parameters like Icon/Click Event/Text, so I could reuse the same structure/styling for multiple elements, avoiding excessive copy/paste dozens of lines.

The problem is that when I use the custom component inside `Dropdown.Target`, the dropdown shows at the `top: 0, left: 0` position, instead of showing right below my custom component. This behavior doesn't happen when I put the code from my custom component directly into the `Dropdown.Target`.

![CleanShot 2024-02-23 at 02 20 57](https://github.com/mantinedev/mantine/assets/7052502/03a9351a-3db9-481d-9cec-b02795bd8be4)

I don't know if this should be considered as a bug, but I think it should worth checking.

Thanks!

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/brave-platform-sv8p92

### Possible fix

I kind of "fixed" in my code by putting the custom component (which already is a `<Group>`) inside another `<Group>` in `Dropdown.Target`, but I don't know if this is the definitive solution.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rilrom** [comment]
You need to use `forwardRef` for the `ref` to be used by your custom component.

```
const FilterItemBlock = forwardRef(function FilterItemBlock(
  { icon, emptyText, value, onClick }: any,
  ref: any
) {
  return (
    <Group ref={ref} onClick={onClick} style={{ cursor: "pointer" }}>
      {icon}
      <Text>{value ?? emptyText}</Text>
    </Group>
  );
});
```

This will render the dropdown in the correct spot.

**Comment by rtivital** [comment]
For position to work correctly, your custom component must support `ref` prop that can be used to retrieve DOM node. Use `forwardRef` as described above.

**Comment by JoshGlazebrook** [comment]
It may be worth adding another note to the docs to clarify this.
