### ISSUE TITLE
False error: MantineProvider was not found in component tree, make sure you have it in your app (reopening with reproduction)

### ISSUE THREAD

**Issue by simonszalai** [mantinedev/mantine#5811]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.3

### What package has an issue?

@mantine/notifications

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The issue is described in [this previously closed](https://github.com/mantinedev/mantine/issues/5306) issue. I still have this problem, so I created a [reproduction](https://github.com/simonszalai/mantine_repro/tree/main).

The project is pretty much an Epic Stack template. There are many files, but they are not relevant here. I kept all of my dependencies in the package.json file, maybe one of them is causing the issue. Also kept my root.tsx file mostly intact.

The error is the following:

```Error: @mantine/core: MantineProvider was not found in component tree, make sure you have it in your app
    at useMantineTheme [...]```

Which disappears if I remove <Notifications /> AND <ModalsProvider>. If either of those is included in my JSX, I'm getting this error.

In the original issue there were suggestions about removing node_modules and lockfile, I tried those, they did not help. I'm also not using pnpm, just plain npm.

### If possible, include a link to a codesandbox with a minimal reproduction

_No response_

### Possible fix

_No response_

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by jgravois** [comment]
thats a pretty massive repro case. i don't have the patience to look through all that boilerplate code but generally that error means that you're attempting to render a mantine component somewhere that isn't within `<MantineProvider />`.

the first thing i'd try if i were you would be to wrap your entire App and ErrorBoundary in it.

https://github.com/simonszalai/mantine_repro/blob/main/app/root.tsx#L169C10-L172

**Comment by simonszalai** [comment]
I know what the error says and obviously thats the first thing I checked, and the provider is there. The reason I sent a repro so massive because I could not reproduce it in a fresh project, there it worked. Eventually I just started over and moved my code to a new project and got it working, but there is something in here that triggers that error incorrectly.

**Comment by Vurmevska** [comment]
I can reproduce this one on a freshly created project when trying to start storybook with mantine.

**Comment by robert-j-webb** [comment]
Hey i made a much smaller Repro case: https://github.com/mantinedev/mantine/issues/5898

Sorry I didn't see this issue before I made my own issue 😓

**Comment by reboottime** [comment]
I have the same issue.

Package versions

```json
    "@mantine/core": "^7.7.1",
    "@mantine/form": "^7.7.1",
    "@mantine/hooks": "^7.7.1",
    "@mantine/modals": "^7.7.1",
    "@mantine/notifications": "^7.7.1",
    "@mantine/styles": "^6.0.21",
    
    ```

**Comment by leonschwanitz** [comment]
One option is to replace all instances of useMantineTheme() in the code with useMantineSafeTheme(). This would resolve the issue, but it would require users of a monorepo to individually apply styles to components, which could be considered a disadvantage. but that could be done via css variables.

What do you think?

[https://mantine.dev/styles/css-variables/](https://mantine.dev/styles/css-variables/)

Code here: [https://github.com/mantinedev/mantine/blob/4c9a875a823daf8132c034e62f247a6960c84b93/packages/%40mantine/core/src/core/MantineProvider/MantineThemeProvider/MantineThemeProvider.tsx#L8](https://github.com/mantinedev/mantine/blob/4c9a875a823daf8132c034e62f247a6960c84b93/packages/%40mantine/core/src/core/MantineProvider/MantineThemeProvider/MantineThemeProvider.tsx#L8)

**Comment by rtivital** [comment]
It is a bad idea that will lead to more frustration.

**Comment by DenisBessa** [comment]
I also have this problem with Next.js 14. I'm 100% sure that every single bit of my app is wrapped under MantineProvider, and this error shows up in Sentry from time to time.

**Comment by DenisBessa** [comment]
I finally found the issue. I was using Mantine Components inside the `global-error.js` file of Next.js.
Since the `global-error.js` file is rendered above the app, the MantineProvider was not present, leading to the error.
Adding the MantineProvider to it fixed the issue.

**Comment by evolfo** [comment]
> I finally found the issue. I was using Mantine Components inside the `global-error.js` file of Next.js. Since the `global-error.js` file is rendered above the app, the MantineProvider was not present, leading to the error. Adding the MantineProvider to it fixed the issue.

Do you have any more details about how you were able to fix this? Where was your `global-error.js` file located?

**Comment by DenisBessa** [comment]
The `global-error.js` should be inside `app` directory (see docs [here](https://nextjs.org/docs/app/api-reference/file-conventions/error#global-errorjs)).

The docs say: 
> global-error.js replaces the root layout.js when active and so must define its own <html> and <body> tags.

So, if it replaces layout.js, it will replace the `MantineProvider` as well. If you use Mantine Components in your `global-error.js`, then it will lead to the error.

**Comment by jkhaui** [comment]
I didn't realise there was another open issue for this - resharing my findings for visibility: https://github.com/mantinedev/mantine/issues/5306#issuecomment-2211624818

Please chime in if anyone understands peer dependencies well; specifically, how npm now handles them, and how to override transitive peer dependency versions such that only a single version of react exists within a project's dependency graph

**Comment by mattkindy** [comment]
Strangely enough, my use of `@mantinex/dev-icons` triggered this most recently. Removing them solved my problem, although I can't understand why

**Comment by LQR471814** [comment]
Adding this for anyone who uses `pnpm`. This can happen when you link a package that also uses `@mantine/core` using something like:

```
"dependencies": {
  "package": "link:./path/to/pkg"
}
```

I'm not sure why this happens, it probably has something to do with `pnpm`, but if you include the package path in `pnpm-workspace.yaml` it will fix the issue:

```yaml
//pnpm-workspace.yaml
packages:
  - ./path/to/pkg
```

**Comment by rtivital** [comment]
The issue has been discussed multiple times, everything is described either in this issue or in the Help Center article – https://help.mantine.dev/q/mantine-provider-missing

The issue is not related to Mantine itself in any of the cases – it is either user error or misconfigured bundler.
