### ISSUE TITLE
Select "autoComplete" prop not working

### ISSUE THREAD

**Issue by joshua-webdev** [mantinedev/mantine#5813]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.3

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When setting the `autoComplete` prop on a `<Select>` component, the input's `autocomplete` attribute does not use the provided value - it uses the default value `off`. This is an issue when using the `searchable` prop since it allows user input, which can trigger the browser autocomplete.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-c3f42c?file=%2Fsrc%2FApp.tsx

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rilrom** [comment]
```
comboboxProps={{
  autoComplete: "input-autocomplete",
}}
```

This looks like it applies the `autoComplete` value as expected in your example, however it does look cause typescript to complain of a missing type.

**Comment by rtivital** [comment]
Fixed in [7.6.1](https://github.com/mantinedev/mantine/releases/tag/7.6.1)
