### ISSUE TITLE
Need to publish latest @mantine-tests/core package

### ISSUE THREAD

**Issue by casamia918** [mantinedev/mantine#5820]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.3

### What package has an issue?

@mantine-tests/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

It seems that 'mod' prop was added to parameter of "itSupportsSystemProps", 

commit id : 14b6d38753c5c0044c824a9c7b5a14653d779fd0

But the package's version is not upgraded, still 1.0.1 

Can you publish @mantine-tests/core package to a latest version? 

Thanks

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The new version has been published
