### ISSUE TITLE
Checkbox - left side label

### ISSUE THREAD

**Issue by matanmaze** [mantinedev/mantine#5823]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When the checkbox label is on the left side it's not aligned to the center and without a space.
Reproducible in [mantine website](https://mantine.dev/core/checkbox/)
<img width="258" alt="image" src="https://github.com/mantinedev/mantine/assets/154054715/77517023-e9ea-49b7-8dec-02fb0a352763">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.6.1](https://github.com/mantinedev/mantine/releases/tag/7.6.1)
