### ISSUE TITLE
Timeinput 

### ISSUE THREAD

**Issue by johngeorge3275** [mantinedev/mantine#5830]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

None

### Describe the bug

Timinput unable to open in Mozilla web browser

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
TimeInput is based on `input[type="time"]`. Native browser dropdown may not be available in all browsers. It is not part of  the library, so it is not planned to be fixed.
