### ISSUE TITLE
discord invite link is invalid

### ISSUE THREAD

**Issue by adamfratino** [mantinedev/mantine#5837]
### Link to the page where something is not right

https://mantine.dev/

### What is wrong?

[discord link](https://discord.com/invite/wbH82zuWMN) in footer, repo README, issue template, etc. is invalid
<img width="622" alt="Screenshot 2024-02-27 at 6 58 16 PM" src="https://github.com/mantinedev/mantine/assets/6173742/2ae01c5d-b585-4f54-8877-170f26834b34">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I've checked it and it works fine. If it does not work for you, try this link – https://discord.gg/RQaF2wnP

**Comment by adamfratino** [comment]
new link still doesn't work for me, but i guess it's on my end
