### ISSUE TITLE
DatePickerInput is off by one day when using timezone

### ISSUE THREAD

**Issue by mlarcher** [mantinedev/mantine#5840]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.0

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

since v7.5.0, picking a date in the DatePickerInput ends up showing and saving a date one day after the one we picked.

Not sure exactly what is happening there... it might be dur to an interaction with mantine forms.

version 7.4.2 is working fine, something broke when upgrading to 7.5.0

Here are the relevant parts of the setup we have:
```js
// in _app.js
import dayjs from 'dayjs';
import 'dayjs/locale/fr';
import localizedFormat from 'dayjs/plugin/localizedFormat';

dayjs.extend(localizedFormat);

// ...

    <MantineProvider>
        <DatesProvider settings={{ locale:'fr', firstDayOfWeek: 1, timezone: 'UTC' }}>

                    <DatePickerInput valueFormat={'LL'} locale={'fr'} {...form.getInputProps('startDate')}/>

        </DatesProvider>
      </MantineProvider>

```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Help wanted with this issue, I'm not planning to work on it.

**Comment by karlpablo** [comment]
I had the same issue and am looking into this.

**Comment by mlarcher** [comment]
Glad to read that. That's kind of a blocker here but I didn't have time to dig intoit yet, and it seems it might become tough if even @rtivital won't look into it 😅

**Comment by 1g0rrr** [comment]
@rtivital Hi! 
I was able to reproduce the issude. 
Can I deal with it and implement a fix for it?

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
