### ISSUE TITLE
ESLint: Missing display name when use createPolymorphicComponent

### ISSUE THREAD

**Issue by manuelbosi** [mantinedev/mantine#5842]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.2.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I'm trying to wrap the mantine MenuItem with `createPolymorphicComponent` function, but when I run the project build breaks with this error
```
./src/components/Menu/MenuItem.tsx
9:3  Error: Component definition is missing display name  react/display-name
```
On my side I already added the displayName
```jsx

import React, { forwardRef } from "react";
import {
  createPolymorphicComponent,
  MenuItem as BaseMenuItem,
} from "@mantine/core";
import { MenuItemProps } from "@/components/Menu/types";

const MenuItem = createPolymorphicComponent<"button", MenuItemProps>(
  forwardRef<HTMLButtonElement, MenuItemProps>(
    ({ children, ...props }, ref) => (
      <BaseMenuItem {...props} ref={ref}>
        {children}
      </BaseMenuItem>
    ),
  ),
);

MenuItem.displayName = "MenuItem";

export default MenuItem;
```

Am I forgetting something?
Thanks

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is a bug of ESLint, not Mantine
