### ISSUE TITLE
Wrong minus margin of `CardSection` when default `p` of `Paper` is set in the theme

### ISSUE THREAD

**Issue by Arichy** [mantinedev/mantine#5844]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

When the defaultProps `p` is set on `Paper`, it will affect `Card`.

Behavior:
![image](https://github.com/mantinedev/mantine/assets/29599723/1f6747b5-3fb8-42dc-899a-81cb5d5a1a25)

Code:
![image](https://github.com/mantinedev/mantine/assets/29599723/ef19ad27-e207-421f-9f85-62ba9c57350e)

### Possible fix

It is because the default `p: sm` would be applied to the `Paper` inside `Card`, but the `padding` would be used to calculate the minus margin of `CardSection`
So the result is, the final padding of the card is `sm` (12px), while the margin-left, margin-right, margin-bottom of the card section is `lg` (16px).

![image](https://github.com/mantinedev/mantine/assets/29599723/4b924fc8-cb18-473e-aa88-a3519bbd4f90)

I know it could be fixed by setting a `p: "lg"` on the `Card`, but it's wired and redundant to declare like `<Card p="lg" padding="lg">`.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You need to set `padding`, not `p` – https://mantine.dev/core/card/#cardsection

**Comment by Arichy** [comment]
It is `padding` that is set on `Card`. `p` is a default prop set on `Paper`, not `Card`.
