### ISSUE TITLE
Value does not change when the value is assigned

### ISSUE THREAD

**Issue by oxcakmak** [mantinedev/mantine#5845]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.3

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

All

### Describe the bug

The slider or select value does not change in the default value assignment. I can't change the value in any way.

The default value between 1 and 5 via mongodb (let it be 5), but when I want to make 3 or select it, it is assigned to 5 again.

```
<Select
  label={t("round_per_time")}
  placeholder={t("round_per_time")}
  value={room.roundDuration + " " + t("second")}
  data={[
    "1 " + t("second"),
    "2 " + t("second"),
    "3 " + t("second"),
    "4 " + t("second"),
    "5 " + t("second"),
    "6 " + t("second"),
    "7 " + t("second"),
    "8 " + t("second"),
    "9 " + t("second"),
    "10 " + t("second"),
  ]}
/>
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by jgravois** [comment]
check out the [controlled](https://mantine.dev/core/select/#controlled) example in the documentation

**Comment by oxcakmak** [comment]
i solved the problem by assigning a default value with the controlled function. Thank you so much @jgravois <3
