### ISSUE TITLE
use-resize-observer typescript return type as any

### ISSUE THREAD

**Issue by tobeycodes** [mantinedev/mantine#5847]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

In this change the return type is changed to `any` https://github.com/mantinedev/mantine/commit/ec4fcf77d83a63ef050547e82d69bd3a03e1ef34

This causes an issue where we are using @typescript-eslint

```
Unsafe array destructuring of a tuple element with an `any` value  @typescript-eslint/no-unsafe-assignment
Unsafe member access .current on an `any` value                    @typescript-eslint/no-unsafe-member-access
```

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.6.2](https://github.com/mantinedev/mantine/releases/tag/7.6.2)
