### ISSUE TITLE
Transitions still randomly animate instantly

### ISSUE THREAD

**Issue by macjuul** [mantinedev/mantine#5849]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Possibly related to #5193 and #3126 however I am still experiencing transition issues on the latest version of Mantine, in my case when using Modals, Drawers, etc.

I can reproduce this issue on all chromium browsers including on Android, however Safari appears to be unaffected.

I'm experiencing this issue in both my main application as well as fresh reproduction project, however the frequency of it happening seems to vary wildly, sometimes occurring 50% of the time while other times it's significantly less frequent.

Here is a recording showing the issue in action

https://github.com/mantinedev/mantine/assets/7606171/96d8e440-bf8b-4a26-97c2-1b31f52af3bb

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.6.2](https://github.com/mantinedev/mantine/releases/tag/7.6.2)
