### ISSUE TITLE
SegmentedControl's value is shifted to the left after opening it in a Modal

### ISSUE THREAD

**Issue by Eldemarkki** [mantinedev/mantine#585]
### What package has an issue

@mantine/core

### Describe the bug

Create a Modal with a SegmentedControl inside of it, and store the SegmentedControl's value with `useState`. Click the SegmentedControl to change it's value. Close the modal, and open it again. Now the displayed handle is shifted to the left by a bit (I'm not sure if it's called a "handle", but [this](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/SegmentedControl/SegmentedControl.tsx#L157-L163) is what I mean).

In this picture I have "Value 4" selected: 
![](https://user-images.githubusercontent.com/38920928/147412182-2d967780-fb2f-4ea9-a913-110571c19f66.png)

Here's a video where I show the steps to reproduce the bug:

https://user-images.githubusercontent.com/38920928/147412465-305fca23-9b90-4e0a-9a73-98dfb1e7df1c.mp4

### In which browser did the problem occur

Firefox, Chrome, Edge

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/priceless-bassi-yozl1

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Thanks for reporting with a sandbox!

**Comment by Eldemarkki** [comment]
I was playing around a bit with this, and it seems like the Modal's animation causes the bug. Animations which have movement (such as the default animation) will break the SegmentedControl, but animations that don't have movement (such as "fade"), will work correctly.

A (very bad) workaround is to set the Modal's prop `transition` to `transition="fade"`. I also tried testing with `transitionDuration={0}`, but it didn't fix the bug.

**Comment by Eldemarkki** [comment]
After some more digging, I think the bug is caused by all animations which have scaling. Just a basic animated `transform: scale(0.75)` is enough to cause the bug: https://codesandbox.io/s/romantic-breeze-q3e99?file=/src/App.js. In the demo, if you make the segmented control small by clicking the button, and then start changing its value, the handle will be misplaced:
![image](https://user-images.githubusercontent.com/38920928/148154774-a22bedbc-ee67-43a7-a8a2-f1dbdfa0c778.png)

**Comment by rtivital** [comment]
Thanks for debugging, resize observer must be getting confused by transforms, we'll see how to make it work. @achmurali you were interested in the root cause of this issue

**Comment by rtivital** [comment]
Fixed in 3.5.2, thanks to @achmurali:
- Scale – https://codesandbox.io/s/nervous-zeh-e749o?file=/src/App.js
- Modal – https://codesandbox.io/s/sleepy-ardinghelli-t4280?file=/src/App.js

**Comment by rtivital** [comment]
@Eldemarkki thanks for investigation, it helped a lot!
