### ISSUE TITLE
SegmentedControl indicator is missing

### ISSUE THREAD

**Issue by upauliushchyk** [mantinedev/mantine#5854]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

In your website demo you have Segmented control indicator
But when i use in in your remix template with updated lib its gone
<img width="1214" alt="image" src="https://github.com/mantinedev/mantine/assets/129177259/14b25023-9a26-4fd6-9090-d6aadb539cf9">

Usage
`import {SegmentedControl} from "@mantine/core";`
`<SegmentedControl data={[{ label: "Parent", value: 0 }, { label: "School", value: 1 },]} name='type' />`

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
SegmentedControl value cannot be a number, it should be a string. It works correctly on codesandbox – https://codesandbox.io/p/sandbox/mantine-react-template-forked-gvcy9z?file=%2Fsrc%2FApp.tsx%3A20%2C7
