### ISSUE TITLE
Increment/decrement `NumberInput` with arrow keys doesn't trigger `onValueChange` callback

### ISSUE THREAD

**Issue by stevezhu** [mantinedev/mantine#5856]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

With a simple setup like below, typing in the input will log for both callbacks, but using the arrow keys will only log for `onChange` and not `onValueChange`.
```tsx
<NumberInput
  label="Amount"
  onChange={(value) => {
    console.log({ value });
  }}
  onValueChange={(values, sourceInfo) => {
    console.log({ values, sourceInfo });
  }}
/>
```

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-tj3h3l?file=%2Fsrc%2FApp.tsx%3A8%2C23

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.6.2](https://github.com/mantinedev/mantine/releases/tag/7.6.2)
