### ISSUE TITLE
Error barrel_optimize in @mantine/notifications/esm/index.mjs

### ISSUE THREAD

**Issue by eugeniudedin** [mantinedev/mantine#5859]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/notifications

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

Run on dev mode or build i get:
Import trace for requested module:
__barrel_optimize__?names=Notifications!=!./node_modules/@mantine/notifications/esm/index.mjs

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a sandbox or repository with a minimal reproduction

**Comment by apeck14** [comment]
Shouldn't need a reproduction. Here's the same issue: https://github.com/mantinedev/mantine/issues/5882

**Comment by rtivital** [comment]
Duplicate of #5882
