### ISSUE TITLE
labelProps are not passed to the label component in TextInput and TextArea

### ISSUE THREAD

**Issue by devnaumov** [mantinedev/mantine#5862]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Try to pass props to the label in TextInput or TextArea via labelProps prop:

	<TextInput
	  labelProps={{ className: classes.label, style: { color: 'red' } }}
	  wrapperProps={{ className: classes.wrapper, style: { color: 'red' } }}
	/>
	
**expected**: labelProps are applied
**actual**: labelProps are not applied (wrapperProps works correctly for example)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rilrom** [comment]
Can confirm that `className` and `style` are not being applied to `labelProps`, `descriptionProps` and `errorProps`.

Have narrowed it down to the use of `ctx?.getStyles`. If `_getStyles` is used they are applied correctly.

**Comment by rtivital** [comment]
Fixed in [7.6.2](https://github.com/mantinedev/mantine/releases/tag/7.6.2)
