### ISSUE TITLE
useForm validation fails when validating nested fields using a function

### ISSUE THREAD

**Issue by BB-BenBridges** [mantinedev/mantine#5864]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/form

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Firefox

### Describe the bug

useForm validation will fail when trying to validate nested fields using a validation function. IDE returns a type error and the browser will not validate the fields.

Please see the code sand box for type error. Sandbox also demos the non-nested fields validating whilst the nested fields do not.

### If possible, include a link to a codesandbox with a minimal reproduction

[Link to codesandbox](https://codesandbox.io/p/sandbox/mantine-react-template-forked-dzwvdv?file=%2Fsrc%2FApp.tsx%3A19%2C19)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`validate` function must return an object of errors, in which the key is a field path and the value is an error that will be passed to the input. `validate` function must not return nested objects. If you need to reference nested field, do that with dot notation. For example: `const errors = { 'path.to.field': 'Error message' }`.

**Comment by rtivital** [comment]
`validate` function must return an object where key is path to the value, for example `validate => ({ 'path.to.field': 'Error message' })` will set error for field `{ path: { to: { field: 'Here' } } }`

**Comment by BB-BenBridges** [comment]
Perfect thank you! A quick validate snippet for anyone else that struggles on this like me:
```javascript
validate: (values) => {
      //random test for example - will be used with stepped form in prod
      if (true) {
        return {
          job: values.job === "" ? "Job is required" : null,
          department:
            values.department === "" ? "Department is required" : null,
          "deliveryAddress.line1":
            values.deliveryAddress.line1 === "" ? "Line 1 is required" : null,
        };
      }
    },
    ```
