### ISSUE TITLE
SegmentedControl design breaks when inside a modal

### ISSUE THREAD

**Issue by liron-navon** [mantinedev/mantine#5868]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

When the segmented control is inside a modal, and we open the modal, the design for the segmented control seems to be miscalculated, causing a small UI bug with it.

<img width="230" alt="Screenshot 2024-03-04 at 15 08 22" src="https://github.com/mantinedev/mantine/assets/18119833/d8685d90-216e-4cad-a8c5-b8108e936fe4">

### If possible, include a link to a codesandbox with a minimal reproduction

[https://codesandbox.io/p/sandbox/youthful-dew-pmy8zf](https://codesandbox.io/p/sandbox/youthful-dew-pmy8zf)

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.7.0](https://github.com/mantinedev/mantine/releases/tag/7.7.0)
