### ISSUE TITLE
Error: "There are multiple modules with names that only differ in casing."

### ISSUE THREAD

**Issue by apeck14** [mantinedev/mantine#5882]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/notifications

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

There are 2 exports coming from `@mantine/notifications`: `Notifications` & `notifications`. Something behind the scenes when using NextJS does not like this. Example:

```js
// theme.js
import { Notifications } from "@mantine/notifications"

export default function ThemeProvider() {
   return <...>
      <Notifications />
   <.../>
}
```
```js
// SomeComponent.js
import { notifications } from "@mantine/notifications"

export default function Component() {
   const handleSomething = () => {
      notifications.show(...)
   }
   
   return <>....</>
}
```

Full error stack:
```
__barrel_optimize__?names=Notifications!=!./node_modules/@mantine/notifications/esm/index.mjs
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers.
```

### Possible fix

Modify the names of the exports slightly.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by apeck14** [comment]
@rtivital This causes a runtime error with NextJS after cold starts when using Serverless Functions. I've been trying to pin-point the root cause of that for several days now. Would be great to see this change!

**Comment by rtivital** [comment]
It is not planned to be fixed, there is no reason to add `@mantine/notifications` package to `optimizePackageImports` – the package is small and does not require this feature.

**Comment by apeck14** [comment]
Ahh ok, that's the root cause? Sounds good, thanks.
