### ISSUE TITLE
Error: @mantine/core: MantineProvider was not found in component tree

### ISSUE THREAD

**Issue by jeanbenoit-richez** [mantinedev/mantine#5884]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

Hi,
I got the bug "Error: @mantine/core: MantineProvider was not found in component tree, make sure you have it in your app" like this:
![Capture d’écran 2024-03-07 à 11 08 12](https://github.com/mantinedev/mantine/assets/119856665/af2007bb-7ec5-4498-96b6-d76197d89bac)
Its seems really weird as i didn't import myself "MantineThemeProvider" anywhere, and MantineProvider is in the top of my app.tsx file.

Package.json:
 "next": "12.1.5",
 "react": "18.2.0",
 "react-dom": "18.2.0",

### Possible fix

i dont know 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a repository with a minimal reproduction. The issue is not reproducible in any of the templates that are provided in documentation.

**Comment by jeanbenoit-richez** [comment]
The error is coming from a big project. I don't know if the error can be reproduct in a small repo.

**Comment by leonschwanitz** [comment]
I have the same issue. We have our own module system with multiple modules depending on our UI module. When we update our UI module, the other modules that rely on it must also be updated, otherwise the same error persists, even though we're using the same Mantine version.

**Comment by jeanbenoit-richez** [comment]
> I have the same issue. We have our own module system with multiple modules depending on our UI module. When we update our UI module, the other modules that rely on it must also be updated, otherwise the same error persists, even though we're using the same Mantine version.

Hi,
What do you mean by "the other modules that rely on it must also be updated" ?

**Comment by leonschwanitz** [comment]
@jeanbenoit-richez Our project structure appears as follows:

The main project incorporates various dependencies:

@mycompany/ui
@mycompany/forms
@mycompany/email

...
Within the forms module, we utilize our custom UI module. Consequently, whenever we update the UI module, it's necessary to update the forms module as well. Otherwise, we encounter an error indicating that the provider cannot be found.

**Comment by jeanbenoit-richez** [comment]
Ok i have the same architecture here.
By updating do you say: recompiling ?

**Comment by leonschwanitz** [comment]
@jeanbenoit-richez Yeah, installing the new ui module into your package and rebuild it.

**Comment by jeanbenoit-richez** [comment]
> @jeanbenoit-richez Yeah, installing the new ui module into your package and rebuild it.

Hmm ok i see. in my case i have only one package bundled by rollup.
All @mantine/* packages has been set has external

**Comment by jeanbenoit-richez** [comment]
In my case the Provider is in a component I created called: MantineProviders (it import every provider my apps needs).
Then when I tried with this it crashed, but if i had manually MantineProvider in my app its works.

But if i remove MantineProviders from my MantineProviders then it crashed again.

**Comment by jeanbenoit-richez** [comment]
The problem seems to comes when my bundle is loaded as commonJs

**Comment by jeanbenoit-richez** [comment]
@rtivital Not close finally... the bug appears again...

**Comment by jeanbenoit-richez** [comment]
![Capture d’écran 2024-02-16 à 16 02 42](https://github.com/mantinedev/mantine/assets/119856665/1c49f90b-bfc5-4f3d-a975-41dbf11abfd7)
As you can see here, there is two MantineProvider because the second one is not recognize

**Comment by rtivital** [comment]
It is not a bug of the library. The issue is related to your build system, which does not resolve node_modules correctly. 
It is described in https://help.mantine.dev/q/mantine-provider-missing

**Comment by Akshat424** [comment]
It is not a bug of the library. In my case removing  '@tanstack/react-query' from experimental `optimizePackageImports` solved the issue. But the error thrown was incorrect.
I was using nx workspace with `pnpm` as package manager.
