### ISSUE TITLE
[Bug] [Safari] The `processing` property of the `Indicator` component has a display problem.

### ISSUE THREAD

**Issue by JonZhang3** [mantinedev/mantine#5887]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

In Safari, there is a problem with the animation display when using the `processing` property of the `Indicator` component.

![Mar-08-2024 01-10-40](https://github.com/mantinedev/mantine/assets/53330083/c11ad15d-ad1c-4f2e-91e6-2aa85d18c2b4)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rilrom** [comment]
Could this be related to #5849?
