### ISSUE TITLE
CSS variables resolver doesn't work with Nextjs 13 +

### ISSUE THREAD

**Issue by ankittchaurasia** [mantinedev/mantine#5889]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

```typescript
//layout.tsx

const cssresolver: CSSVariablesResolver = (theme) => {
  return {
  
    variables: {},
    light: { '--mantine-color-body': '#fff' },
    dark: { '--mantine-color-body': '#111' },
}};


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <head><ColorSchemeScript /></head>
     <body>
      <MantineProvider theme={theme} cssVariablesResolver={cssresolver} >
        {children}
      </MantineProvider>
     </body>
    </html>
  );
}
```

<img width="1013" alt="Screenshot 2024-03-08 at 12 31 23 PM" src="https://github.com/mantinedev/mantine/assets/74493798/092de4cd-696f-4700-bb79-77ba16d0b520">

### Possible fix

1. Works when i make layout.tsx client side using "use client"
2. Make separate client file for CSSVariablesResolver and MantineProvider and use in layout

## Better fix is to use server actions something like this

```typescript
//layout.tsx
...
const cssresolver: CSSVariablesResolver = async (theme) => {
"use server" //server action
  return {
    variables: {},
    light: { '--mantine-color-body': '#fff' },
    dark: { '--mantine-color-body': '#111' },
}};


export default function RootLayout({  children }: Readonly<{ children: React.ReactNode; }> ) {
  return (
    <html lang="en">
     <body>
      <MantineProvider cssVariablesResolver={cssresolver} >
        {children}
      </MantineProvider>
     </body>
    </html>
  );
}
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You cannot pass functions as arguments to components unless you set `'use client';` at the top of the file.
For FAQ about server component visit https://help.mantine.dev/q/server-components
