### ISSUE TITLE
NextJS experimental.optimizePackageImports failing with @mantine/modals

### ISSUE THREAD

**Issue by robert-j-webb** [mantinedev/mantine#5898]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/modals

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Hey awesome work here, thought I'd help by tying up a common issue for NextJS Modal users:

Previous issue: https://github.com/mantinedev/mantine/issues/5306

Hey I saw this issue didn't have a repro case so I thought I would open one. I didn't use code sandbox because it didn't have the NextJs template, instead I forked the template repo and added a commit [Commit SHA](https://github.com/robert-j-webb/next-pages-template/commit/39c5877a9f9e2cb410aef0e2f1eb4f67dcac0f47a)

If you need a code sandbox I can take some time to make that too. 

Error Message:

```
Server Error
Error: @mantine/core: MantineProvider was not found in component tree, make sure you have it in your app

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

Like mentioned in the previous issue, the work around is to remove `optimizePackageImports` from `next.config.mjs` 

### If possible, include a link to a codesandbox with a minimal reproduction

https://github.com/robert-j-webb/next-pages-template/commit/39c5877a9f9e2cb410aef0e2f1eb4f67dcac0f47a

### Possible fix

I'm not sure at all how NextJS's complicated bundler works but it would be awesome to properly deliver a fix for that.

If it's too difficult then I recommend documenting this behavior in the [@mantine/modals page](https://mantine.dev/x/modals/)

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is not planned to be fixed, there is no reason to add `@mantine/modals` package to `optimizePackageImports` – the package is small and does not required this feature.

**Comment by robert-j-webb** [comment]
Hey sorry if I wasn't clear about this but the issue isn't `'@mantine/modals'` in the next.js `experiment.optimizePackageImports` config, but it's actually `'@mantine/core', '@mantine/hooks',` as well.

This is an issue because of this recommendation in the nextjs install guide: https://mantine.dev/guides/next/#app-router-tree-shaking

So most users of Mantine, NextJS and Mantine modals will encounter this failure and not be sure what to do

**Comment by msngupta** [comment]
I get the same error all of a sudden. It was working and suddenly I got this error. I tried reinstalling all the nextjs modules in a fresh project. I still have the same issue.  Really appreciate if anyone could help.

**Comment by mmounirf** [comment]
@robert-j-webb @msngupta I've just created a [sandbox](https://codesandbox.io/p/devbox/mantine-nextjs-gvjqfm) trying to reproduce the issue, however it seems it works just fine. Do I miss something here?

**Comment by robert-j-webb** [comment]
@mmounirf   Yeah it looks like it's working in code sandbox, but not in my clone of the next-pages-template repo, weird. I even tried changing the package json to match yours. I do use `pages` instead of `app` router but that shouldn't matter reallistically

If you can fork this sample reproduction - https://github.com/robert-j-webb/next-pages-template and see how to fix it to match yours, then that would be interesting.

**Comment by rtivital** [comment]
1. I cannot reproduce the issue in https://github.com/mantinedev/next-pages-template
2. `optimizePackageImports` is not intended to be used with pages router. It is explicitly mentioned in documentation that it is needed only for app router – https://mantine.dev/guides/next/#app-router-tree-shaking
