### ISSUE TITLE
[@mantine/core] List elements don't have the correct width.

### ISSUE THREAD

**Issue by gl3nn** [mantinedev/mantine#5902]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

<img width="551" alt="Screenshot 2024-03-11 at 15 09 17" src="https://github.com/mantinedev/mantine/assets/1133073/db610b7f-48b0-457a-8222-c6e527a1de21">

The width of the list elements is too wide. It seems to not wrap when it should which has most likely to do something with the marker in front.

### Possible fix

I think the CSS needs to be adjusted.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by gl3nn** [comment]
I solved this for myself by overwriting the styling with: 
```
  list-style-position: outside;
  margin-left: 1.5rem;
```

**Comment by rtivital** [comment]
It was discussed previously in https://github.com/mantinedev/mantine/issues/2778
This behavior is not planned to be changed.
