### ISSUE TITLE
Overriding Popover dropdown color is not working 

### ISSUE THREAD

**Issue by waseemk-786** [mantinedev/mantine#5903]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I've tried to over the default color of popOver dropDown component, but it is not allowing to do so. Then I've tried to hard override it with `!important` css property. Then it worked. But user should easy change color of popOver without hard override. Please check and fix it.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.6.2](https://github.com/mantinedev/mantine/releases/tag/7.6.2)
