### ISSUE TITLE
CSS variable overrides not being applied to table styles

### ISSUE THREAD

**Issue by finn-orsini** [mantinedev/mantine#5909]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

We are no longer able to override table css variables (`--table-hover-color`, `--table-striped-color`, and `--table-border-color`) as expected, Mantine defaults are taking precedence. 

### Possible fix

Add back the fallback behavior which was removed in [ab2e3482](https://github.com/mantinedev/mantine/commit/ab2e3482d54db82c6f7c9abfd41b5a3b104d267d)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide an example of the code that does not work

**Comment by finn-orsini** [comment]
@rtivital If reproductions are required, I suggest you update the issue template to remove the optional wording. 

[Here is an example sandbox](https://codesandbox.io/p/sandbox/mantine-react-template-forked-c8twk4). 

If you update the classname on `Table` from `styles.oldOverrides` to `styles.newOverrides`, you can see the difference in necessary selectors to override the table border, [due to the change referenced above](https://github.com/mantinedev/mantine/commit/ab2e3482d54db82c6f7c9abfd41b5a3b104d267d) no longer using `--table_border_color` var.

**Comment by rtivital** [comment]
Can you advise how should I update the template to make it more clear? I'm not native english speaker, current one sounds like: "If it is possible, provide a sandbox reproduction, otherwise if it is impossible to provide a sandbox, we can discuss issue in more details (but only if it is really impossible to provide a reproduction)".

The issue in your example is incorrect CSS variable name, you've defined `--table_border_color` instead of `--table-border-color`.

https://codesandbox.io/p/sandbox/mantine-react-template-forked-flh6sv?file=%2Fsrc%2Foverrides.module.css

**Comment by finn-orsini** [comment]
Ah, you are correct - my mistake in that reproduction. 

To mimic what we currently had in production, I've updated the [sandbox](https://codesandbox.io/p/sandbox/mantine-react-template-forked-c8twk4?file=%2Fsrc%2FApp.tsx%3A10%2C16). We were previously able to define the border color on a wrapping element of the table, instead of needing that class directly on the Table. Let me know if the updated reproduction makes more sense! Made sure to use the correct variable name this time 🙃 

Regarding the wording of the prompt, I would simply remove `If possible` and leave only `Include a link to a codesandbox with a minimal reproduction`. I understand not making the field required to submit the form, but I think that stronger wording may help a bit!

**Comment by Dylan-Brandenburg** [comment]
Similarly, applying `  <Table highlightOnHoverColor="#ff00ff" highlightOnHover>` would not actually change the background row color, but I suspect this is more of a var naming issue than a specificity issue.

**Comment by rtivital** [comment]
This change is intended to reduce the output markup. It is not planned to be changed.
