### ISSUE TITLE
Select in popover doesn't work

### ISSUE THREAD

**Issue by woody146** [mantinedev/mantine#5912]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.2

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

All

### Describe the bug

This is my code

```jsx
<Popover width={200} position="bottom" withArrow shadow="md">
  <Popover.Target>
    <Button>Toggle popover</Button>
  </Popover.Target>
  <Popover.Dropdown>
    <div>
      <Text size="xs">
        This is uncontrolled popover, it is opened when button is clicked
      </Text>
      <Select
        label="Your favorite library"
        placeholder="Pick value"
        data={["React", "Angular", "Vue", "Svelte"]}
      />
    </div>
  </Popover.Dropdown>
</Popover>
```

If select option of Select component, it will close popover and nothing is selected

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/core/select/#inside-popover
