### ISSUE TITLE
Overlapping Legend and Chart Bar Issue

### ISSUE THREAD

**Issue by leonschwanitz** [mantinedev/mantine#5915]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/charts

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

There appears to be an issue with the stacked bar chart on our dashboard where the legend overlaps with the bars of the chart, obscuring part of the visualization.

<img width="736" alt="Bildschirmfoto 2024-03-13 um 12 51 34" src="https://github.com/mantinedev/mantine/assets/36971798/4d00cc67-ad17-4ea9-8253-545ea9191f2c">

### Possible fix

The legend should be displayed adjacent to or separate from the chart without covering any portion of it, ensuring that all data visualizations are fully visible.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by leonschwanitz** [comment]
thanks @Kenzo-Wada !! :)

**Comment by Kenzo-Wada** [comment]
@leonschwanitz your welcome!
