### ISSUE TITLE
form.validateField is setting error incorrectly on the form with nested fields

### ISSUE THREAD

**Issue by ruslan-simonenko** [mantinedev/mantine#5925]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.2

### What package has an issue?

@mantine/form

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

`form.validateField` incorrectly sets `form.errors` when used on a higher level object in a form with nested fields.

#### Given 
- Use schema-based validation with Zod;
- Use form with nested fields;

```
const SimpleFormSchema = z.object({
  items: z.array(z.string().url()),
});
const form = useForm({ validate: zodResolver(SimpleFormSchema) });
form.setFieldValue("items", ["invalid link"]);
```

#### When
`form.validateField` is used on an object that contains an invalid field:
```
form.validateField('items');
```

#### Then 
`form.errors` contains error at the level of the object, rather than at the level of the field that is actually invalid:
```
console.log(form.errors); 
```
Actual value: `{"items":"Invalid url"}`
Expected value: `{"items.0":"Invalid url"}`

Actual behaviour is not in accord with `form.validate()`.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-msx44v?file=%2Fsrc%2FSimpleForm.tsx%3A8%2C29

### Possible fix

Pretty sure current behaviour is caused by this line:
https://github.com/mantinedev/mantine/blob/e3e3bb834de1f2f75a27dbc757dc0a2fc6a6cba8/packages/%40mantine/form/src/use-form.ts#L213

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior, use-form hook supports nested values only as objects. An array of strings is not considered to be a nested value. To resolve the issue, change the data format to `{ url: string }[]`.
