### ISSUE TITLE
Carousel is missing props for styles, classes, and classNames

### ISSUE THREAD

**Issue by TheMikeL** [mantinedev/mantine#5927]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.0

### What package has an issue?

@mantine/carousel

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Carousel component is missing styles api with styles or classNames

### Possible fix

Include props to handle overriding styles

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Carousel styles api features work correctly – https://codesandbox.io/p/sandbox/mantine-react-template-q4dd5d?file=%2Fsrc%2FApp.tsx%3A6%2C1
I cannot reproduce any issues.
