### ISSUE TITLE
[@mantine/core] Divider: Orientation `vertical` is broken

### ISSUE THREAD

**Issue by jerebtw** [mantinedev/mantine#593]
### What package has an issue

@mantine/core

### Describe the bug

When you set Orientation to `vertical` it doesn't show anything

### In which browser did the problem occur

Brave

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/solitary-dew-de1vg?file=/src/App.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Thanks for reporting! This issue will be fixed in next minor release

**Comment by Ultra-Instinct-05** [comment]
It looks like the `vertical` class just lacks `height` for it to be visible. The `sizes` are defined in `Divider.styles.tsx` which are which are very small so some factor is needed to multiply to make it visible. 

```diff
--- G:\mantine\src\mantine-core\src\components\Divider\Divider.styles.ts	Thu Dec 30 10:32:14 2021
+++ G:\mantine\src\mantine-core\src\components\Divider\Divider.styles.ts	Thu Dec 30 10:32:19 2021
@@ -72,6 +72,7 @@
     borderLeftWidth: theme.fn.size({ size, sizes }),
     borderLeftColor: theme.fn.themeColor(color, 4),
     borderLeftStyle: variant as any,
+    height: theme.fn.size({ size, sizes }) * 100
   },
 }));
 
```

**Comment by rtivital** [comment]
Fixed in 3.5.0, height is set to 100%

**Comment by nghiepit** [comment]
@rtivital issue is sill in 3.5.0 and 3.5.1 
https://codesandbox.io/s/hopeful-scott-j65j9?file=/src/App.tsx

**Comment by Ultra-Instinct-05** [comment]
@nghiepit You need to set some `height` on the parent div for the divider to be visible. The vertical divider takes 100% of the parent height so if there is no height, it won't be visible.

**Comment by rtivital** [comment]
https://codesandbox.io/s/admiring-kalam-cx2lx
