### ISSUE TITLE
Combobox Submits Focused Option on Enter Key with IME Conversion

### ISSUE THREAD

**Issue by elecdeer** [mantinedev/mantine#5934]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Related: #1565 

When using a Combobox and confirming a conversion with the Enter key while using an IME, the focused option is being submitted. I am a Japanese user, but I believe this issue also affects users who type in Chinese.

This becomes a particular problem with examples like ["Select first option on type."](https://mantine.dev/combobox/?e=AutocompleteSelectFirstOption) Here is a reference to the issue demonstrated: 

https://github.com/mantinedev/mantine/assets/37701077/bd00ee52-1f15-4971-b42b-53a9c223743e

In the video, I am using an IME called ATOK, but the issue occurs with the standard Apple IME as well.

I think the ideal behavior would be as demonstrated in this video.

https://github.com/mantinedev/mantine/assets/37701077/35a1fc96-545a-421c-a0c6-d2bfbcc70416

### Possible fix

This can be resolved by checking the `isComposing` property of the KeyboardEvent.
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing

If there are no objections, I will proceed to create a pull request.
https://github.com/elecdeer/mantine/commit/b7a12045ec920602e88ddddd77d09faef5e3cf9e

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
