### ISSUE TITLE
Typo in FocusTrap.InitialFocus section

### ISSUE THREAD

**Issue by Jufrench** [mantinedev/mantine#5936]
### Link to the page where something is not right

https://mantine.dev/core/focus-trap/

### What is wrong?

The first paragraph in the description of `[FocusTrap.InitialFocus](https://mantine.dev/core/focus-trap/#focustrapinitialfocus)` has a typo. The last sentence in the paragraph has "remove". It should be spelled "removed".

<img width="781" alt="image" src="https://github.com/mantinedev/mantine/assets/29068597/6a090a0c-536e-409f-8894-32b302f6d20e">

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Thanks for reporting!
