### ISSUE TITLE
Disabled TagsInput Pills can be removed

### ISSUE THREAD

**Issue by snturk** [mantinedev/mantine#5959]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Disabled TagsInput pills can be removed by just clicking them on the side where the "cross" button appears when not disabled.

Example video on Mantine website:

https://github.com/mantinedev/mantine/assets/41567673/dce35323-c912-4a12-b139-42468dbf3c44

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.1.1](https://github.com/mantinedev/mantine/releases/tag/7.7.1)
