### ISSUE TITLE
AppShell Styles API not Functioning

### ISSUE THREAD

**Issue by 3mpireGamer** [mantinedev/mantine#5967]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.6.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Other, I will specify in the bug description

### Describe the bug

Browsers:
I do not have the capability to test on Safari, but I tested it in Chrome, Edge, and Firefox (my main dev browser)

Testing:
Confirmed `npm update @mantine/core` doesn't change the dependencies, I am on ^7.6.2.
Confirmed `'use client'` directive is present where the MantineProvider and All Mantine Components are used.
Confirmed with React Dev Tools that the context is working properly and that my theme is being passed down to each file.

Issue: 
I am attempting to override the style of the AppShell Component using the Styles API, and the styles I apply aren't applying from my theme. They do however apply when I apply them directly to the component. However, there will be logic in my app that can change the theme based on certain conditions, and I would rather not have to do that logic for theming and then all over again for the AppShell Component itself, hence why I've been working on integrating the Styles API to override/extend it. 

Theory: 
I am pretty much brand new to this library and am mocking up the layout of an app I plan to develop. I could very well be implementing something wrong or missing something. I've scoured the docs (I've tried `classNames` and `styles` to override the style, but neither works) and I can't find anything conclusive. Due to the fact that I've followed the docs, I presume it's an issue with AppShell's implementation of the Styles API, but I am not ruling out user error (given that I've also tried the same override on other components to no avail). Any clarity on what I can do to fix this would be greatly appreciated! 

### Chrome
![Chrome](https://github.com/mantinedev/mantine/assets/44933728/01cc7c6b-0d7a-479e-a3ef-4c99919832f8)
### Edge
![Edge](https://github.com/mantinedev/mantine/assets/44933728/437e8f94-c65f-41e1-b7c0-9e70feb2457e)
### Firefox
_(with screenshots of React Component Trees)_
![Firefox 1](https://github.com/mantinedev/mantine/assets/44933728/eaf9e53e-f638-4668-a86c-234cb440c8ab)
![Firefox 2](https://github.com/mantinedev/mantine/assets/44933728/23602948-ab27-46a2-bc81-7523395975d9)
![Firefox 3](https://github.com/mantinedev/mantine/assets/44933728/8107e980-037c-4923-87b6-98bfeda6ce2f)
### VSCode 
_with screenshots of my implementation 
(there is a codesandbox link included with issue submission for a minimal reproduction)_
![VSCode 1](https://github.com/mantinedev/mantine/assets/44933728/d24b4af9-1244-48a7-9869-9d35e8a60ef6)
![VSCode 2](https://github.com/mantinedev/mantine/assets/44933728/995794c8-c235-478b-a973-75ddef8b7777)

Regards, 
 - 3mpireGamer

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-s3glty

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The sandbox does not work, it must be made public

**Comment by 3mpireGamer** [comment]
My apologies, I've never used Code Sandbox before and I didn't think to check. It should be public now. 
Thank you for the swift response! 

![image](https://github.com/mantinedev/mantine/assets/44933728/93704567-e971-4ad5-9624-0260f4341a8c)

**Comment by 3mpireGamer** [comment]
Yes that worked!

I was following the formatting given here: [https://mantine.dev/theming/default-props/#default-props-for-compound-components](https://mantine.dev/theming/default-props/#default-props-for-compound-components)
![image](https://github.com/mantinedev/mantine/assets/44933728/22425bdb-a611-4870-8565-40ef9530df47)
To me, it cleary shows that each sub-component gets overridden separately, which must have been what caused my confusion. I presume this is the difference between the StylesAPI and the Default Props override, and I must have missed that by assuming it worked the same way. 
Thanks for clearing that up!
