### ISSUE TITLE
Extended className not applied in Combobox.Search component

### ISSUE THREAD

**Issue by elecdeer** [mantinedev/mantine#5969]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.2

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

It seems that classNames in `theme.components` are not being applied to some components. 

I extended the `Combobox.Search` component and specified a className as shown in the code below, but the actual DOM does not have the `"custom-search-input"` className applied.

```tsx
const theme = createTheme({
  components: {
    ComboboxSearch: Combobox.Search.extend({
      classNames: {
        input: "custom-search-input",
      },
    }),
  },
});

export default function App() {
  return (
    <MantineProvider theme={theme}>
      <Demo />
    </MantineProvider>
  );
}
```

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-hxnjmy?file=%2Fsrc%2FApp.tsx%3A19%2C22

### Possible fix

`ComboboxSearch` component should use `useStyles` hook?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Stuj1** [comment]
I believe this is a specificity issue introduced in `7.6.2` with the `:where` pseudo classes. 

I have a similar repro [here](https://codesandbox.io/p/sandbox/mantine-react-template-forked-drygyy?file=%2Fsrc%2Foverrides.module.css) that highlights the issue.

If you inspect your element with dev tools, you'll probably see the `:where` rules overwriting yours. 

There is a hack to increase specificity of your rules that are being overwritten, by using 
```css
&& {
  your: rule;
}
```

Or roll back to `7.5.3` and you should see it is not an issue.

**Comment by wasamistake** [comment]
Hi @elecdeer. I'm not sure if those subcomponents are meant to be extended (even though it works sometimes), as they don't seem to have an `extend` property applied. Also, type errors are raised if you extend most of them that way.

I think it will work as intended if you extend the top-level component instead.

```tsx
const theme = createTheme({
  components: {
    Combobox: Combobox.extend({
      classNames: {
        search: "custom-search-input",
      },
    }),
  },
})
```

**Comment by rtivital** [comment]
It is intended behavior, the solution described above.

**Comment by elecdeer** [comment]
Thank you for your response.

My example might not have been sufficient.
Indeed, regarding the `input` of the `Search` subcomponent, it is possible to assign a classname by extending the`Combobox`. However, this method does not allow for the assignment of classnames to the `wrapper` or `section` within the Search subcomponent...

I can assign classnames to them using `defaultProps`, but unlike `classname`, they might be overwritten.

**Comment by rtivital** [comment]
defaultProps are good then. Input and Combobox do not share the same styles api context so, it is not supported
