### ISSUE TITLE
In AppShell "alt" layout mode, "Header right side " is hiding behind "Aside", Ideally it should be between Navbar and Aside.

### ISSUE THREAD

**Issue by roker15** [mantinedev/mantine#5974]
### Link to the page where something is not right

https://mantine.dev/app-shell/?e=AltLayout

### What is wrong?

In layout it looks like that `AppShell.Header` is between `AppShell.Navbar` and `AppShell.Aside` but in fact Header is hiding behind Aside, which creates propblem. I want to place login button at right side of Header but it hides behind `Aside `section.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It works correctly on the docs website – the logo is not hidden by the navbar.
If you want to ask for help from the community, use Discussions tab and provide a minimal reproduction.

**Comment by roker15** [comment]
> It works correctly on the docs website – the logo is not hidden by the navbar. If you want to ask for help from the community, use Discussions tab and provide a minimal reproduction.

You perhaps did not get my question correctly, `Header `is not hiding in `Navbar`, It's perfectly fine. **Right portion of Header** is hiding behind `Aside `section... And Aside appears on the top of header , which is not desirable.

**Comment by roker15** [comment]
@rtivital please don't close, read carefully , my issue is there.

**Comment by roker15** [comment]
@rtivital what could be possible solution?

**Comment by rtivital** [comment]
Fixed in [7.1.1](https://github.com/mantinedev/mantine/releases/tag/7.7.1)

**Comment by roker16** [comment]
@rtivital yes this is fixed but , then i have a <SegmentedControl/> which behaves weird after this update. It changes focus of a button when stick to the top.

**This is happening after upgrade.....**

<SegmentedControl/> is inside AppShell.Header, which is expected to stick at top when scroll down. It sticks perfectly but changes focus to the first button.

Here is sbap before scroll
![image](https://github.com/mantinedev/mantine/assets/154746611/b6f72a46-818c-4eae-b3a5-66aed87e589f)

Here is snap after scroll, focus shift from button 2 to button1 automatically --

![image](https://github.com/mantinedev/mantine/assets/154746611/f62ceae9-95b4-478b-b376-3960cbca85a6)

**Here is my code -**

`import { UserMenu } from "@/components/UserMenu";
import { createClient } from "@/utils/supabase/client";
import {
  AppShell,
  Burger,
  Button,
  Group,
  Paper,
  ScrollArea,
  SegmentedControl,
  Space,
  Tabs,
  rem,
  useMantineTheme,
} from "@mantine/core";
import { useDisclosure, useHeadroom } from "@mantine/hooks";
import { User } from "@supabase/supabase-js";
import { IconEdit, IconNotebook } from "@tabler/icons-react";
import Link from "next/link";
import { Suspense, useEffect, useState } from "react";
export default function ManageSyllabusLayout({
  children,
  filter,
  notes,
  index,
}: {
  children: React.ReactNode;
  filter: React.ReactNode;
  notes: React.ReactNode;
  index: React.ReactNode;
}) {
  const [opened, { toggle }] = useDisclosure();
  const [value, setValue] = useState("react");
  const theme = useMantineTheme();
  const pinned = useHeadroom({ fixedAt: 120 });
  const supabase = createClient();
  const [user, setUser] = useState<User | null>(null);
  useEffect(() => {
    const getUser = async () => {
      setUser((await supabase.auth.getUser()).data.user);
    };

    getUser();
  }, [supabase.auth]);

  return (
    <AppShell
      layout="alt"
      header={{ height: 60, collapsed: !pinned, offset: false }}
      padding={{ base: 0, md: 1, xl: 90 }}
      // header={{ height: 50 }}
      // footer={{ height: 60 }}
      navbar={{
        width: 300,
        breakpoint: "md",
        collapsed: { mobile: !opened },
      }}
      aside={{
        width: 0,
        breakpoint: "lg",
        collapsed: { desktop: false, mobile: true },
      }}
    >
      <AppShell.Header withBorder={true} >
        <Group h="100%" px="md" >
          <Burger opened={opened} onClick={toggle} hiddenFrom="md" size="sm" />
          <IconNotebook size={30} />
          <Button
            variant="subtle"
            size="compact-sm"
            color={"dark"}
            component={Link}
            href="/manage-index"
          >
            Pricing
          </Button>
          <Button
            variant="subtle"
            size="compact-sm"
            color="dark"
            component={Link}
            href="/manage-index"
          >
            Guide
          </Button>
          <Button
            variant="subtle"
            size="compact-sm"
            color="dark"
            component={Link}
            href="/manage-index"
            rightSection={<IconEdit size={14} />}
          >
            Index
          </Button>
          {/* <Flex justify={"center"}>
            <NotesSearch />
          </Flex> */}
        </Group>
      

        <Paper
          shadow="xs"
          bg={!pinned ? theme.colors.gray[2] : "white"}
          radius={"0px"}
          h={52}
          style={{
            position: "sticky",
            top: "0px",
            zIndex: "100",
          }}
        >
          <SegmentedControl
            fullWidth
            withItemsBorders={false}
            h={50}
            size={"md"}
            value={value}
         
            radius="xl"
            // style={{"backgroundColor":theme.primaryColor,"opacity":"90%"}}
            color={!pinned ? theme.colors.indigo[6] : theme.colors.gray[8]}
            bg={!pinned ? theme.colors.gray[2] : "white"}
            onChange={setValue}
            data={[
              { label: "Button1", value: "react" },
              { label: "Button2", value: "ng" },
              { label: "Button3", value: "vue" },
              { label: "Svelte1", value: "svelte" },

            ]}
          />
        </Paper>
      </AppShell.Header>
      <AppShell.Navbar  withBorder={false} h={"full"} bg={"var(--mantine-color-gray-1)"}>
        <Group justify="space-between" p={2} bg={"var(--mantine-color-gray-1)"} >
          <Group >
            <UserMenu user={user} />

            <Button
              variant="subtle"
              size="compact-lg"
              color="dark"
              component={Link}
              href="/manage-index"
              rightSection={<IconEdit size={14} />}
            >
              Index
            </Button>
          </Group>
          <Burger opened={opened} onClick={toggle} hiddenFrom="sm" size="sm" />
        </Group>

        <ScrollArea scrollbarSize={4} scrollHideDelay={0} h={"100vh"}>
          {filter}
          {index}
        </ScrollArea>
        {/* </AppShell.Section> */}
      </AppShell.Navbar>
      <AppShell.Main  pt={`calc(${rem(60)} + var(--mantine-spacing-md))`}>
        <Space h={80} />
        <Suspense fallback={<div>loading...</div>}>{notes}</Suspense>
      </AppShell.Main>
      {/* <AppShell.Aside withBorder={true} p="md">Aside</AppShell.Aside> */}
      {/* <AppShell.Footer p="md">Footer</AppShell.Footer> */}
    </AppShell>
  );
}

`
