### ISSUE TITLE
Switches are disabled when used in useForm

### ISSUE THREAD

**Issue by rexwreyes** [mantinedev/mantine#5983]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.2

### What package has an issue?

@mantine/form

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When i am using a <Switch> in useForm, it is disabled and cannot be interacted with.  If i change to a standard Checkbox it's fine.

DOES NOT WORK
`<Switch mt='xs' size='md' {...form.getInputProps(`item.versions.items.${index}.validations.dependenciesmet`, { type: 'checkbox' })} />`

WORKS
`<Checkbox mt='xs' size='md' {...form.getInputProps(`item.versions.items.${index}.validations.dependenciesmet`, { type: 'checkbox' })} />`

The weird thing is when i include BOTH of these then BOTH work.  If i include just the Checkbox it works.  If I include just the Switch it is disabled.

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Both Switch and use-form work correctly on codesandbox – https://codesandbox.io/p/sandbox/mantine-react-template-forked-k7hnyl?file=%2Fsrc%2FApp.tsx%3A8%2C21
I cannot reproduce any issues.

**Comment by nevenhsu** [comment]
Hello @rtivital , I also encountered the same problem and can reproduce this bug.

Issue:
When the useForm default value is set to true, the Switch UI still shows false.

Version: 7.9.1

[codesandbox](https://codesandbox.io/p/sandbox/mantine-react-template-forked-9p792r?file=%2Fsrc%2FApp.tsx%3A10%2C6)

**Comment by rtivital** [comment]
You are missing type: 'checkbox' in getInputProps options.
