### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

### ISSUE THREAD

**Issue by iamnewton** [mantinedev/mantine#5987]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Been trying to get Drawer to work within a storybook.  Followed the docs, but continue to get the error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined
```

The drawer works fine when used in a reduced test case sandbox, but the following code, as reduced as possible does not.

```typescript
// panel.tsx
import { Drawer, Button, Card, Text } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import * as React from "react";

export interface PanelProps {
	isOpened?: boolean;
}

export function Panel (props: PanelProps) {
	const {
		isOpened = true,
	} = props;
	const [opened, { open, close }] = useDisclosure(isOpened);
	console.log({ isOpened }) // true

	return (
		<Drawer position="bottom" opened={isOpened} onClose={close} title="Test">
			foo
		</Drawer>
	);
}

// panel.story.ts
import type { Meta, StoryObj } from "@storybook/react";
import { Panel } from "./panel";

const meta = {
	component: Panel,
	tags: ["autodocs"],
	title: "Panel",
} satisfies Meta<typeof Panel>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
	args: {
		isOpened: true,
	}
};
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by iamnewton** [comment]
@rtivital I can't seem to recreate it, but when I try to console.log anything from `@mantine/core` I get `undefined`, but I have several other components that work just fine.  Any thoughts?

**Comment by rtivital** [comment]
If the issue cannot be reproduced on coesandbox or in another project, it means that the issue is related to your project/setup.

**Comment by Kenzo-Wada** [comment]
I had same issue before.

@iamnewton 
I would like to ask, for the sake of reproducibility research, are you using App Router or Pages?

**Comment by iamnewton** [comment]
@Kenzo-Wada I'm using the App Router.

**Comment by anotherliam** [comment]
Hi, we are having the same issue - Using the mantine next js app router template, the drawer will not work within storybook.

**Comment by Kenzo-Wada** [comment]
In my Enviroment, removing `optimizePacakgeImport` in next.config.json worked.

```
  // experimental: {
  //   optimizePackageImports: ['@haram/ui'],
  // },

```

**Comment by rtivital** [comment]
Issue is closed because this is no reproduction.

**Comment by rtivital** [comment]
https://mantine.dev/guides/next/#compound-components-in-server-components

**Comment by Ali-0111** [comment]
well, i had the same issue and solved this way:

Added: 'use client' and used this way:
Table.Thead was working fine.

this way also worked: 
in server components i directly imported;
import TableThead from '@mantine/core'

[reference](https://mantine.dev/guides/next/#compound-components-in-server-components)
