### ISSUE TITLE
Mantine menu item not working as expected

### ISSUE THREAD

**Issue by RupenAnjaria** [mantinedev/mantine#5996]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

We are using Menu component to show navigation menu on top. It works fine, however, for menu item, the click area is restricted to only where we have text. If we click on the remaining area then the menu just closes itself. I tried inspecting and found that the hyper link is only applied to the text.

![image](https://github.com/mantinedev/mantine/assets/17281745/c408b356-64bc-4479-9f9c-fb1898a85850)

For example, if we click on the space near green dot then it closes the menu. The hyperlink only works if we click on the blue line area.

see image below, about what we get when we inspect the element, as we can see, the button element doesn't have any click event and hyperlink element (a) is way under it.

![image](https://github.com/mantinedev/mantine/assets/17281745/088cc2e6-bd46-4fb7-bf26-3840084d0058)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/core/menu/#custom-component-as-menuitem

**Comment by RupenAnjaria** [comment]
that works if we have href, in my case, we have to call a javascript function. Again, it works, but only if you click on the text and not on the entire menu item.

**Comment by rtivital** [comment]
href accepts a string with a link, not a js function. If you want to call a function, use onClick instead.

**Comment by RupenAnjaria** [comment]
ok, the issue is that, the onClick only works for the text, so user have to click very precise location within menu item. Clicking on entire menu item doesn't work.
