### ISSUE TITLE
SegmentedControl doesn't work well in RTL

### ISSUE THREAD

**Issue by mnakhli** [mantinedev/mantine#6002]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

Latest

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

https://github.com/mantinedev/mantine/assets/21153535/c76f80f1-ef9a-44e3-93de-56d12c063dec

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The component work correctly in rtl. Follow the guide – https://mantine.dev/styles/rtl/
