### ISSUE TITLE
useRef does not react to props passed as initial values.

### ISSUE THREAD

**Issue by ugeshgupta000** [mantinedev/mantine#6009]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.2

### What package has an issue?

@mantine/form

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I want to achieve the functionality based on below:

```

export const Test = (props: any) => {
    const { initialObj } = props;

    const form = useForm({
        initialValues: initialObj
    });

    return <>
        <TextInput
            {.... form.getInputProps('myfield')}
        />
        <Button onClick={() => console.log(form.values)}>Show form</Button> 
    </>
}
```

I want to reuse the same form for different initialObj. However, when initialObj changes, the form does not change the values. 
Just to provide a reference, in React hook form, there is a way to support reactive udpates.
https://react-hook-form.com/docs/useform#values

### Possible fix

A way of achieving this could be to use useEffect, and listen for props changes. Based on props changes, call the form.setValues method.

However, if there is some children using form, that does not get notified with this hack, since setValues is a in-place update to the form. Is there a proper way of achieving this.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
- If you want to set values – https://mantine.dev/form/values/#setvalues-partial
- If you want to set initial values – https://mantine.dev/form/values/#setinitialvalues-handler
