### ISSUE TITLE
Modal "xOffset" property is not working as expected

### ISSUE THREAD

**Issue by mikamiel** [mantinedev/mantine#6012]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Actual behaviour: "xOffset" property just shrinks modal window evenly from both left and right sides so it stays centered but shrinked.

Expected behaviour: "xOffset" property should move modal window left and right (horizontally) inside browser window and its width should stay the same.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`xOffset` prop works as intended, it adds offset on right and left sides.
