### ISSUE TITLE
useLocalStorage causes infinite re-renders

### ISSUE THREAD

**Issue by NimmLor** [mantinedev/mantine#6017]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/hooks

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

v7.7.1 break my useLocalStorage states. The following PR updates the memo dependencies and causes infinite re-renders.

https://github.com/mantinedev/mantine/pull/5910/files

I suspect that the useEffect on [Line 145](https://github.com/israelins85/mantine/blob/148705be0ffbfed2a7c2174b649c0c808f80a86c/packages/%40mantine/hooks/src/use-local-storage/create-storage.ts#L145) causes this.

![image](https://github.com/mantinedev/mantine/assets/32486857/c601a759-ee98-4f46-b211-fb6a2c74f0be)

### Possible fix

Revert memo dependencies back to how they were in v7.7.0

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by wuifdesign** [comment]
i was just typing the same issue when this popped up. if you use simple values like string this doesn't happen, but when you use an object and the deserialize is triggered it runs into an infinite loop,

**Comment by MathiasGr** [comment]
👍 We're seeing the same here

**Comment by wuifdesign** [comment]
i prepared a fix here: https://github.com/mantinedev/mantine/pull/6019

**Comment by LuckyLukas98** [comment]
> ### Dependencies check up
> * [x]  I have verified that I use latest version of all @mantine/* packages
> 
> ### What version of @mantine/* packages do you have in package.json?
> 7.1.1
> 
> ### What package has an issue?
> @mantine/hooks
> 
> ### What framework do you use?
> Vite
> 
> ### In which browsers you can reproduce the issue?
> Chrome
> 
> ### Describe the bug
> v7.1.1 break my useLocalStorage states. The following PR updates the memo dependencies and causes infinite re-renders.
> 
> https://github.com/mantinedev/mantine/pull/5910/files
> 
> I suspect that the useEffect on [Line 145](https://github.com/israelins85/mantine/blob/148705be0ffbfed2a7c2174b649c0c808f80a86c/packages/%40mantine/hooks/src/use-local-storage/create-storage.ts#L145) causes this.
> 
> ![image](https://private-user-images.githubusercontent.com/32486857/318703136-c601a759-ee98-4f46-b211-fb6a2c74f0be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTUyNzYsIm5iZiI6MTcxMjA1NDk3NiwicGF0aCI6Ii8zMjQ4Njg1Ny8zMTg3MDMxMzYtYzYwMWE3NTktZWU5OC00ZjQ2LWIyMTEtZmI2YTJjNzRmMGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDEwNDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NTEwYjczMDUzM2U1YjkwN2Q0NzVlYjBjNjI0NmU0YjdiN2Y2ZTYzNzkwZTk0YTg0NjUzMmFiMTlmNDJiZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5aFq1Hj8MzYTewGTyEewnrwjBRIErnhqJxToV56QZYk)
> 
> ### If possible, include a link to a codesandbox with a minimal reproduction
> _No response_
> 
> ### Possible fix
> Revert memo dependencies back to how they were in v7.1.0
> 
> ### Self-service
> * [ ]  I would be willing to implement a fix for this issue

I think you probably meant v7.**7**.1 (and v7.**7**.0 respectively), do you?

If so, I'm experiencing the same issue you're describing.

**Comment by wuifdesign** [comment]
bug was introduced in ec1adbfab2e50376f6cbfbde94d17100644b529e

**Comment by wuifdesign** [comment]
after my fix it is still needed to memorize the `serialize` and `deserialize` if overwriting them in your own code.

**Comment by noxan** [comment]
found the same issue, got stuck on it for 3 hours - thanks for reporting and fixing @wuifdesign ❤️

**Comment by icflorescu** [comment]
The same issue breaks [Mantine DataTable](https://icflorescu.github.io/mantine-datatable/) on Mantine 7.7.1, see https://github.com/icflorescu/mantine-datatable/issues/564 - many thanks for investigating and coming up with the fix!

**Comment by Karakatiza666** [comment]
Having the same issue

**Comment by rtivital** [comment]
Fixed in [7.7.2](https://github.com/mantinedev/mantine/releases/tag/7.7.2)

**Comment by icflorescu** [comment]
Thanks a lot, @rtivital!
And many thanks for the new features in Mantine 7.8, especially the [uncontrolled form mode](https://mantine.dev/form/uncontrolled/) 🙏
