### ISSUE TITLE
MultiSelect onSeach ServerSide || Async

### ISSUE THREAD

**Issue by Number5768** [mantinedev/mantine#6030]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

all vser

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

When I perform an Async query for the first time, select the data. Next, search for more information and click to select the information, but what was shown before was the value but not the label.
![search](https://github.com/mantinedev/mantine/assets/52844429/e6733b08-8039-4289-ab02-9088d3154f9c)

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It works as intended. Labels are retrieved from the data array. If there is no item in the data array for selected option, it is not possible to retrieve it.
