### ISSUE TITLE
`ReturnType<Menu.extend>` returns `ExtendsRootComponent` which appears to not be exported, failing the build for libraries

### ISSUE THREAD

**Issue by alexmorleyfinch** [mantinedev/mantine#6033]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

# The error

When we extend components like Menu, we get a build error like:
```bash
src/overrides/Menu.override.ts:4:1 - error TS2742: The inferred type of 'default' cannot be named without a reference to '../../../../node_modules/@mantine/core/lib/core/factory/factory'. This is likely not portable. A type annotation is necessary.

4 export default Menu.extend({
5   defaultProps: {},
6   classNames: classes,
7 });
```

However this doesn't happen for *most* Mantine components, only the components where `.extend` returns a type of `ExtendsRootComponent`. From what I can see, only Menu, Popover and HoverCard use this as a return type of `.extend`. Most other components return a `MantineThemeComponent`. I've verified that I only get these errors for those 3 components, nothing else. This implies that ExtendsRootComponent is somehow the culprit.

# Important context

We use a monorepo pattern and split up our MantineProvider configuration code. As all the Mantine configuration is passed into the MantineProvider, we have a totally separate package where we configure all the theme/styles/extended-components for our brand etc. We then build this with Vite in library mode and export the fully configured MantineProvider in a wrapper like:
```
export function MyFullyConfiguredProvider({children}) {
  return <MantineProvider {...allConfigEtc}>{children}</MantineProvider>
}
```

with our current Vite config looking like:
```
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), dts({rollupTypes: true, tsconfigPath: 'tsconfig.json'})],

  build: {
    lib: {
      entry: 'src/index.ts',
      name: 'Manta',
      fileName: (format) => `manta.${format}.js`,
    },
    rollupOptions: {
      external: [
        'react',
        'react-dom',
        '@mantine/core',
        '@mantine/hooks',
        '@mantine/notification',
        '@mantine/dates',
        '@mantine/form',
      ],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
          '@mantine/core': 'MantineCore',
          // '@mantine/hooks': 'MantineHooks',
          // '@mantine/notification': 'MantineNotifications',
          // '@mantine/dates': 'MantineDates',
          // '@mantine/form': 'MantineForm',
        },
      },
    },
  },
});

```

This works well and we can import the entire configured MantineProvider into many of our other separate projects.

I think this is where the problem is, because we're building in library mode and the `ExtendsRootComponent` isn't exported from the Mantine core library. This may mean that consumers of the lib can't access this type, and I think the Vite bundler knows this because we're in library mode, meaning all used types need to be exportable, and `ExtendsRootComponent` appears not to be exported as part of the main `@mantine/core` bundle.

### Possible fix

I *think* this just means that if you export `ExtendsRootComponent` as a type available directly from '@mantine/core', then this won't be a problem anymore. I think it's because when we build in library mode, the typing information for purely locally used types aren't included in the outputted mantine.d.ts.

This is implied by the error message itself where it says `without a reference to '../../../../node_modules/@mantine/core/lib/core/factory/factory'`. The type cannot be found.

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are welcome to send a PR with a fix

**Comment by rtivital** [comment]
I cannot reproduce this issue in any templates on my side.
