### ISSUE TITLE
`TagsInput` with `useForm` does not properly validate user values

### ISSUE THREAD

**Issue by nicolassanmar** [mantinedev/mantine#6034]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

I'm trying to create a `<TagsInput />` where users can only enter emails. I'm using `useForm` to validate the inputs from the user (I'm also using zod, but I don't think it's relevant to the issue here).

The default `form.getInputProps` does not work for my use case here. Errors get reported in properties named `emails.0`, `emails.1` instead of `emails`, and validating the form with `onOptionSubmit` and `onRemove` manually does not work since those two fire before the form is updated (`form.validate()` will not take into account the most recently added/removed item.

### How I set up the `form.getInputProps`
``` ts
const ZLawyerInviteForm = z.object({
  emails: z.string().email().array(),
})
type ZLawyerInviteForm = z.infer<typeof ZLawyerInviteForm>

...

  const form = useForm<ZLawyerInviteForm>({
    initialValues: {
      emails: [],
    },
    validate: zodResolver(ZLawyerInviteForm),
  })

...
<TagsInput {...form.getInputProps('emails')} />

```

### How I set up "manual" validation on submit and remove (which did not work)

``` ts
// Display first error if any exist
  const errorInInput = useMemo(() => {
    const errors = Object.keys(form.errors)
    if (errors.length > 0 && errors[0]) {
      return form.errors[errors[0]]
    }
  }, [form.errors])

...

        <TagsInput
          {...form.getInputProps('emails')}
          onOptionSubmit={(newValue) => {
            // This validate happens before `newValue` is taken into account into the `form`
            // Wrapping this into a `setTimeout(..., 0)` did not work as a workaround to the issue
            form.validate()
          }}
          onRemove={(removed) => {
            // This validate happens before `removed` is removed from the `form`
            form.validate()
          }}
          error={errorInInput}
        />
```

### Possible fix

(Maybe this issue is should be tackled on @mantine/form)

Ideally, this would just work by using `form.getInputProps` but as this input uses an array of strings, it may be hard to do so.

What seems like an easier fix is to make sure that validating the form on the `onOptionSubmit` and `onRemove` validate the new state of the form, and not an outdated value. 

The only way to fix this using a `useEffect` would be to use `form.values` as a dependency, breaking the "exhaustiveness rule" by not including `form` or `form.validate` as that would lead to infinite re-renders:
``` ts
  useEffect(() => {
    form.validate()
  }, [form.values])

```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You can fix that by using a different validation method – https://codesandbox.io/p/sandbox/mantine-react-template-forked-gvdxsx?file=%2Fsrc%2FApp.tsx%3A9%2C7

**Comment by chunghn** [comment]
Encountered in the same condition, Zod is preferable since there is a list of forms. It seems mantine useForm did not pass the error properly.
