### ISSUE TITLE
Rating doesn't return to its original state after hover, especially in the case of custom icons.

### ISSUE THREAD

**Issue by rilmasaker** [mantinedev/mantine#6038]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

6.0.17 / 7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

On the https://mantine.dev/core/rating/#custom-symbol page, if we quickly move the mouse from left to right along the rating, sometimes the rating remains in the hover state and does not return to its original state. I experienced this in version 6.0.17 on Meteor framework, but I checked the new documentation and was able to manually reproduce the issue there as well. So, I suspect that it is still present in the current version
![image](https://github.com/mantinedev/mantine/assets/48757870/98f0fec4-e82a-4353-ba51-999c2292883c)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is not planned to be fixed
