### ISSUE TITLE
mantine v6 drawer animations not working

### ISSUE THREAD

**Issue by mkonecny** [mantinedev/mantine#6041]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^6.0.21

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Reproducible on the official doc website

https://v6.mantine.dev/core/drawer/#change-transition

Notice that there is no transition animation for an example that's supposed to showcase a transition animation. The v7 example works as expected: https://mantine.dev/core/drawer/#change-transition

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://v6.mantine.dev/theming/theme-object/#respectreducemotion
