### ISSUE TITLE
I've got an error from Mantine Carousel when I build my project

### ISSUE THREAD

**Issue by imnash21** [mantinedev/mantine#6045]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/carousel

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

None

### Describe the bug

Building my project got an errors.

![Screenshot 2024-04-06 142522](https://github.com/mantinedev/mantine/assets/108371844/14fe4175-912c-4983-8269-07a941f21b6e)

![Screenshot 2024-04-06 142532](https://github.com/mantinedev/mantine/assets/108371844/cfa77d59-8cc6-4b70-86bf-7ceb01f55237)

![Screenshot 2024-04-06 142549](https://github.com/mantinedev/mantine/assets/108371844/cee3a21d-2760-47e1-b355-1e0b30fda38b)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You've installed incorrect version of embla, use installation instructions from documentation – https://mantine.dev/x/carousel/#installation
