### ISSUE TITLE
Select's hidden input doesn't receive the "name" property

### ISSUE THREAD

**Issue by viczam** [mantinedev/mantine#6047]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I'm setting a `name` property on the <Select /> component, but it doesn't get passed on to the hidden input.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by syntralis** [comment]
Same here

**Comment by rtivital** [comment]
I cannot reproduce the issue. I can see the correct name in Select component hidden input in the sandbox – https://codesandbox.io/p/sandbox/mantine-react-template-forked-8wcth8?file=%2Fsrc%2FApp.tsx%3A11%2C9

`<input type="hidden" name="usage-select" value="First">`
