### ISSUE TITLE
AppShell and Modal|Drawer issue

### ISSUE THREAD

**Issue by jamalsoueidan** [mantinedev/mantine#6049]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When you open a modal while using appshall, the modal adds the below css to the header for unknown reason and breaks the width of the AppShell.Header

```
right-scroll-bar-position {
    right: 0px !important;
}
```

If you look at the css on the right side:
<img width="1461" alt="Screenshot 2024-04-06 at 18 51 48" src="https://github.com/mantinedev/mantine/assets/115714/05b88abd-5bc1-4d3f-aaa6-0ce9909f9e97">

I have top-radius on the AppShell.Height and the right top-radius is gone when opens modal

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You can disable offset scrollbars feature by setting `offsetScrollbars={false}` on the AppShell component.

**Comment by jamalsoueidan** [comment]
You faster then F16 👍🏻  Thank you
