### ISSUE TITLE
I Got An Error with Embla Carousel Autoplay Package when I Build My Project

### ISSUE THREAD

**Issue by imnash21** [mantinedev/mantine#6052]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/carousel

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

None

### Describe the bug

I followed the instructions based on this link https://mantine.dev/x/carousel/#embla-plugins but still got an error message when I build my project.

![Screenshot 2024-04-07 163909](https://github.com/mantinedev/mantine/assets/108371844/51d4a147-f7a5-4bdb-a1e2-f002977e73da)

![Screenshot 2024-04-07 163930](https://github.com/mantinedev/mantine/assets/108371844/7de5117b-b921-4e73-9d01-0b6d39a20037)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Make sure that your embla carousel and all plugins have the same version. If that does not help, provide a sandbox with a reproduction.

**Comment by imnash21** [comment]
I have TypeScript version 5.x.x then I tried to downgrade my TypeScript version to 4.9.5 then it's compatible/works to embla-carousel-autoplay 7.1.0
