### ISSUE TITLE
Async Server Components can't be children of Mantine elements

### ISSUE THREAD

**Issue by mfosterw** [mantinedev/mantine#6053]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

Using an async server component as a child of a Mantine component inside another server component results in `Error: Objects are not valid as a React child (found: object with keys {$$typeof, _payload, _init}).`

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-hjj5wy

### Possible fix

Making `Parent` a client component silences the error. I assume this has something to do with the fact that "[Mantine components cannot be used as server components](https://mantine.dev/guides/next/#server-components)," but it seems to contradict the Nextjs docs, which say you can [make server components children of client components](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#supported-pattern-passing-server-components-to-client-components-as-props). If this is expected behavior, why does it only occur when `Child` is `async`, and is it possible to provide a more straightforward error message? (I spent hours banging my head against a wall because I didn't know if the error came from React, Next, Mantine, or my own code).

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Mantine provides regular React component with 'use client'; at the top of the file. We do not have any logic that is specific to Next.js or server components. The issue is not related to Mantine.
