### ISSUE TITLE
SegementedControl layout is wrong when used in Accordion Header

### ISSUE THREAD

**Issue by cedstrom** [mantinedev/mantine#6054]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When putting a segemented control in the header of an accordion, it is truncated.

![image](https://github.com/mantinedev/mantine/assets/6175957/f98009fb-b4b8-4d7a-b140-6559861cc974)

Note that "This Month" is cut off on the right hand side.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-2396jr?file=%2Fsrc%2FApp.tsx%3A22%2C29

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The component works as intended, there is issue with styles in a flexbox container – https://codesandbox.io/p/sandbox/mantine-react-template-forked-nmqd5z?file=%2Fsrc%2FApp.tsx%3A20%2C23
