### ISSUE TITLE
NumberInput: Cursor jumps to the end when pressing backspace with cursor on the very left

### ISSUE THREAD

**Issue by jvllmr** [mantinedev/mantine#6056]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Other, I will specify in the bug description

### Describe the bug

When moving the cursor to the start on NumberInput, then pressing backspace, the cursor moves to the end of the input.

Tested with Chrome and Firefox.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-c4yvtd?file=%2Fsrc%2FApp.tsx%3A5%2C66

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.7.2](https://github.com/mantinedev/mantine/releases/tag/7.7.2)

**Comment by jvllmr** [comment]
I tested the example above with Mantine 7.7.2 and 7.8.0 and the behavior stayed the same.

https://github.com/mantinedev/mantine/assets/51451323/92ac04a6-1d70-4024-b750-a70b235babd8
