### ISSUE TITLE
Unhandled Runtime Error Error: Could not find the module "/Users~/node_modules/@mantine/core/esm/components/Grid/Grid.mjs#Grid#Col" in the React Client Manifest. This is probably a bug in the React Server Components bundler.

### ISSUE THREAD

**Issue by codetipster** [mantinedev/mantine#6057]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

i am trying to use the grid component in next like this: 

`import { Grid } from '@mantine/core';

function Demo() {
  return (
    <Grid>
      <Grid.Col span={4}>1</Grid.Col>
      <Grid.Col span={4}>2</Grid.Col>
      <Grid.Col span={4}>3</Grid.Col>
    </Grid>
  );
}

export default Demo;`

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/guides/next/#compound-components-in-server-components
