### ISSUE TITLE
AppShell Footer regression in version 7.7.1

### ISSUE THREAD

**Issue by shaneoliver** [mantinedev/mantine#6060]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

On iOS Chrome a noticeable gap is present between the AppShell Footer and the bottom of Chrome when scrolling. I have provided a code sandbox. Here is the link to open on iOS Chrome to view the issue https://wjt8cf.csb.app/

![IMG_4197B4D15810-1](https://github.com/mantinedev/mantine/assets/18100929/dab7d157-eaca-4456-a2cd-95ebe7018b20)

Adding viewport content tag viewport-fit=cover as suggested by MDN does not resolve the issue.

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover">

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/unruffled-wind-wjt8cf?file=%2Fsrc%2FApp.tsx%3A38%2C70

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.7.2](https://github.com/mantinedev/mantine/releases/tag/7.7.2)
