### ISSUE TITLE
Slider onChangeEnd event fires before onChange when using arrow keys

### ISSUE THREAD

**Issue by kgarner7** [mantinedev/mantine#6063]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When using a `Slider` component with `onChange` and `onChangeEnd` events, using arrow keys to change the value will cause the `onChangeEnd` event to fire before `onChange`

### Possible fix

Reorder the events at https://github.com/mantinedev/mantine/blob/4c9a875a823daf8132c034e62f247a6960c84b93/packages/%40mantine/core/src/components/Slider/Slider/Slider.tsx#L239-L240

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
onChnageEnd is called whenever the user stops any interactions with the component. onChange is called when value changes. The logic is correct, the order of functions calls does not matter.

**Comment by kgarner7** [comment]
I disagree. The order matters if you are relying on `onChangeEnd` to denote that seeking has finished. This caused a real bug https://github.com/jeffvli/feishin/issues/581

**Comment by rtivital** [comment]
Okay, I do not mind to merge the PR
