### ISSUE TITLE
TagsInput will override existing search text when value is pasted in

### ISSUE THREAD

**Issue by tjb1019** [mantinedev/mantine#6073]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

There are really two issues here:
1. Pasting a value into the input will automatically override the existing searchValue.  Example: I manually type "key", and then paste in "value".  "key" is removed and only "value" is what gets saved to state.
2. In a controlled instance of `TagsInput`, `value` should only get updated if I manually update it via `onChange`.  However, in its current state, `value` will be updated internally when a user pastes a value into the input.

### Possible fix

Looking at the [source code](https://github.com/mantinedev/mantine/blob/afc992942bdaf4e807e83b9fcb6df340c5e22f4a/packages/%40mantine/core/src/components/TagsInput/TagsInput.tsx#L291), the issue is within the `handlePaste` method.  It is explicitly setting value state, and clearing searchValue state.  There is no way to override this behavior.

```ts
  const handlePaste = (event: React.ClipboardEvent<HTMLInputElement>) => {
    onPaste?.(event);
    event.preventDefault();

    if (event.clipboardData) {
      const pastedText = event.clipboardData.getData('text/plain');
      setValue(
        getSplittedTags({
          splitChars,
          allowDuplicates,
          maxTags,
          value: pastedText,
          currentTags: _value,
        })
      );
      setSearchValue('');
    }
  };
```

This is all very explicit so I guess this is the intended behavior, but I would expect pasting a value in to simply concat the existing searchValue with the pasted value.  Hitting the enter key should be what commits the searchValue to state.  Something like this is a possible fix:
```ts
setSearchValue(existingSearchValue => existingSearchValue + pastedText)
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.9.2](https://github.com/mantinedev/mantine/releases/tag/7.9.2)
