### ISSUE TITLE
Drawer closeOnClickOutside did not work when withOverlay is false

### ISSUE THREAD

**Issue by zhy0216** [mantinedev/mantine#6076]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

although closeOnClickOutside is mentioned as `Determines whether the modal/drawer should be closed when user clicks on the overlay`, but from the function name it did not indicate it replied on overlay

### Possible fix

useClickOutside

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior, it is not planned to be changed.
