### ISSUE TITLE
Setting focus on TextInput and TextArea with styles &:focus does not work

### ISSUE THREAD

**Issue by tianhuil** [mantinedev/mantine#6079]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

TextInput and TextArea should be able to set input's &:focus. 

The documentation says you can use `classNames` props: https://help.mantine.dev/q/input-focus-styles
This Sandbox by @rtivital shows it worked in v5 https://codesandbox.io/p/sandbox/amazing-fast-n7edl5?file=%2Fsrc%2FApp.tsx%3A15%2C18

This sandbox indicates it does not work with `styles` or `style` props: https://codesandbox.io/p/sandbox/nifty-cdn-f8g8s6?file=%2Fsrc%2FApp.tsx%3A15%2C19

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/nifty-cdn-f8g8s6?file=%2Fsrc%2FApp.tsx%3A15%2C19

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
v7 is not v5. See documentation – https://mantine.dev/styles/styles-api/#styles-prop
Use classNames to apply focus styles like shown in the guide.
