### ISSUE TITLE
Tooltip label formatter not working

### ISSUE THREAD

**Issue by kaiqueaguilar** [mantinedev/mantine#6085]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/charts

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

I tried several formatters but the rendering did not respond to the changes, the "tooltipProps" > "labelFormatter" property is being completely ignored

I tried :

```
tooltipProps={{
  labelFormatter: (value) => "test",
}}
```

and 

```
tooltipProps={{
  labelFormatter: (value) => dayjs(value).format("MMM/YYYY").toUpperCase(),
}}
```

the result is always the same:

<img width="459" alt="image" src="https://github.com/mantinedev/mantine/assets/92055543/764212e3-1c88-4f67-b83f-f6a1280e45e7">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`tooltipProps` are passed down to the recharts tooltip component. Mantine uses custom tooltip which does not support recharts props. If you need to change formatting, change tooltip component instead – https://mantine.dev/charts/bar-chart/#custom-tooltip
