### ISSUE TITLE
"Props passed down to the Input.Label component" have no typings on <Select />

### ISSUE THREAD

**Issue by kenzaflow** [mantinedev/mantine#6089]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

Currently, it is accepting "Record<string, any>". So autocomplete doesn't work.

It's not a problem for me, but I understand that it can cause problems.

If not, close this :) I love this library

![image](https://github.com/mantinedev/mantine/assets/74398451/f1e81c4b-3d73-47a0-ad1e-bb786f69c89a)

### Possible fix

Should accept Input.Label props types

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior, it is not planned to be changed
