### ISSUE TITLE
Controlled range date picker bug when clearing the dates after selecting just one

### ISSUE THREAD

**Issue by FerranMontoliu** [mantinedev/mantine#6092]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/dates

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

## Brief explanation

I have a controlled `DatePicker` with `type="range"`. In my component, I have a button for users to clear the selection they are performing. The issue is that, if a user has selected the start date and not the end date, even if you set the value to [null, null], the calendar still has the start date selected.

## Steps to reproduce:

1. Open the stackblitz url provided.
![image](https://github.com/mantinedev/mantine/assets/43371834/753f70d5-bbdf-43c2-a1f6-580ea69cc872)

2. Select one date in the calendar.
  ![image](https://github.com/mantinedev/mantine/assets/43371834/1851bdd4-9ba4-4fe3-983a-a7cc6166e53c)

3. Click the button to clear the dates.
![image](https://github.com/mantinedev/mantine/assets/43371834/fb9534ca-c1ed-4f2e-8fb8-801e87952f45)

4. Move the cursor around the calendar. You will see that the start date does not appear to be selected, but the blue shadow is still there when you hover over the calendar.
![image](https://github.com/mantinedev/mantine/assets/43371834/a8203895-edf3-497c-9788-19735d6143a9)

5. Click on another day. Now your selection will take the first date (which should have been cleared), and the second date (the one you just selected).
![image](https://github.com/mantinedev/mantine/assets/43371834/90da6847-e21c-49f3-9e27-fe0208712424)

## Minimal example used

```javascript
export default function App() {
  const [value, setValue] = useState([null, null]);

  const handleChange = (val) => {
    setValue(val);
  };

  const clearRange = () => {
    setValue([null, null]);
  };

  return (
    <Stack>
      <DatePicker
        type="range"
        value={value}
        onChange={handleChange}
        allowSingleDateInRange
      />

      <Button onClick={clearRange}>CLEAR</Button>
    </Stack>
  );
}
```

### If possible, include a link to a codesandbox with a minimal reproduction

https://stackblitz.com/edit/react-ojxzj7?file=src%2FApp.js

### Possible fix

When setting the value to `[null, null]`, the dates should be cleared.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.8.1](https://github.com/mantinedev/mantine/releases/tag/7.8.1)
