### ISSUE TITLE
@mantine/dropzone keyboard activation not working

### ISSUE THREAD

**Issue by joshua-webdev** [mantinedev/mantine#6095]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.0

### What package has an issue?

@mantine/dropzone

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I can't seem to activate the file picker by focusing on the dropzone component and pressing either space or enter. V6 works, so I believe the issue relates to some interaction with `react-dropzone-esm` which was introduced in V7. More specifically, `rootRef` seems to be null, so we never make it past [this condition](https://github.com/rtivital/react-dropzone-esm/blob/master/src/index.jsx#L825).

### Possible fix

If you remove `ref` from `...getRootProps({ ref }),` on [this line](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/dropzone/src/Dropzone.tsx#L284), then the keyboard activation works, but I'm not sure if that's the best solution? I think also `...getRootProps` is creating a prop called `ref` which if you try to access it, even just looking at it via dev tools, you get the [special props warning](https://react.dev/warnings/special-props).

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.8.1](https://github.com/mantinedev/mantine/releases/tag/7.8.1)
