### ISSUE TITLE
RingProgress rendered wrong when default text size is overridden

### ISSUE THREAD

**Issue by dfaust** [mantinedev/mantine#6098]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Other, I will specify in the bug description

### Describe the bug

When setting the default font size in the browser settings to something other than the default value, the RingProgress component is rendered wrong. I tried it with Firefox and Chromium.

Here is a screenshot of the wrongly rendered RingProgress component from the Mantine documentation.
The text seems to be correctly centered, but the ring is moved to the top and right:
![image](https://github.com/mantinedev/mantine/assets/893710/573f0c33-2c49-4c36-87e9-c9bea5fa4b0d)

Firefox settings (font size 14, default is 16):
![image](https://github.com/mantinedev/mantine/assets/893710/e3589c4f-e09f-4f98-a58f-91cda1e497c6)

Chromium settings (font size small, default is medium):
![image](https://github.com/mantinedev/mantine/assets/893710/0121a745-91e2-4feb-a063-1fa87fc7d806)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is a known issue that cannot be fixed. If your application requires this feature, you can use a different component instead of RingProgress.

**Comment by eltongonc** [comment]
Sorry to reply on a closed ticket, but I noticed that if you wrap the circles in a `<g>` element, add a `translate(-10px)`. It centres it as expected:


Before:
<img width="236" alt="Screenshot 2024-05-03 at 00 09 36" src="https://github.com/mantinedev/mantine/assets/14180132/d7a46f27-00f0-4ff6-b7f8-8b90a681f49c">

After:
<img width="236" alt="Screenshot 2024-05-03 at 00 09 10" src="https://github.com/mantinedev/mantine/assets/14180132/fc71650e-2d91-443c-afda-6caa5798c08c">


Possible fix:
```html
<svg class="m-d43b5134 mantine-RingProgress-svg">
        <g style="transform: translate(-10px, -10px)"> 
          <circle class="m-b1ca1fbf mantine-RingProgress-curve" fill="none" stroke-linecap="butt" stroke-width="8" cx="60" cy="60" r="46" transform="scale(1, -1) translate(0, -120)" stroke-dasharray="216.7698930976957, 72.25663103256524" stroke-dashoffset="0"></circle>
          <circle class="m-b1ca1fbf mantine-RingProgress-curve" fill="none" stroke-linecap="round" stroke-width="8" cx="60" cy="60" r="46" stroke-dasharray="72.25663103256524, 216.7698930976957" stroke-dashoffset="289.02652413026095" style="--curve-color: #bd1d1d;"></circle>
        </g>
      </svg>
```

Why `10px`? Without setting the size, the circles combined have a total size of `92px`, and the SVG is `102px`.
Unfortunately, when you set a custom size, the 10px doesn't help

**Comment by rtivital** [comment]
No, it will not be removed/deprecated. This issue may impact only a very small fraction of users.

**Comment by HermesDE** [comment]
This also happens when you change the "scale" factor in the mantine theme.

**Comment by Toshinaki** [comment]
@HermesDE 
I'm facing exactly the same problem.
Do you have any workaround?

**Comment by HermesDE** [comment]
@Toshinaki sorry for the late reply. Sadly I did not solve this problem. :/
