### ISSUE TITLE
PasswordInput visibility icon duplicated

### ISSUE THREAD

**Issue by pedrodevelop** [mantinedev/mantine#6100]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Other, I will specify in the bug description

### Describe the bug

In the Microsoft Edge browser, when you enter any text in the field, two visibility icons appear simultaneously, you can see below.

![image](https://github.com/mantinedev/mantine/assets/51206522/5509f43c-f67b-4f94-a09e-4d08a5508cf6)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by codellyson** [comment]
Works fine for me on Microsoft Edge
![image](https://github.com/mantinedev/mantine/assets/26005272/58099943-991a-4282-b158-f91c6074b04b)

**Comment by adamint** [comment]
@codellyson this does reproduce on latest Edge on Mac.
<img width="402" alt="image" src="https://github.com/mantinedev/mantine/assets/20359921/8f91cccd-7d76-430d-b50a-a8a36ce55ac6">
