### ISSUE TITLE
Popover with ColorInput inside close after color selected 

### ISSUE THREAD

**Issue by shlitaTeam** [mantinedev/mantine#6104]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

when using ColorInput inside a Popover, after selecting color the Popover closes.

as you can see in this expmle:
https://codesandbox.io/p/sandbox/nifty-moon-7v4pdn

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/nifty-moon-7v4pdn

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
1. https://codesandbox.io/s/mantine-react-template-forked-5g4zhs?file=/src/App.tsx
2. https://mantine.dev/core/popover/#nested-popovers

**Comment by shlitaTeam** [comment]
> 1. https://codesandbox.io/s/mantine-react-template-forked-5g4zhs?file=/src/App.tsx
> 2. https://mantine.dev/core/popover/#nested-popovers

is there any solution for this in version 6?
