### ISSUE TITLE
Missing `innerProps`, `innerRef` and `disableTransition` properties to Modal Components

### ISSUE THREAD

**Issue by AndrejNemec** [mantinedev/mantine#6110]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

I'm currently working on a project that heavily utilizes the Mantine library, specifically the Modal components. I've encountered a couple of limitations that are impacting the usability and functionality of the modals. I would appreciate if we could discuss the possibility of adding these enhancements to the library.

**1. Addition of `innerProps` and `innerRef` to `<Modal.root>` and `<Modal.Content>` Components:**

Currently, it seems that the Modal component lacks a way to pass custom props and a ref to the inner elements of `<Modal.root>` and `<Modal.Content>`. This capability is crucial for managing focus, accessibility attributes, and other attributes that are essential for integration with third-party libraries and custom use-cases.

**Proposed Solution:**
- Implement `innerProps` and `innerRef` props where:
    - `innerProps` would allow developers to pass additional props directly to the inner component.
    - `innerRef` would facilitate access to the DOM node directly, enabling more nuanced manipulation and integration with other libraries that might require direct DOM access.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This feature is already available with compound components – https://mantine.dev/core/modal/#compound-components
It is not planned to implement it for Modal component itself.
