### ISSUE TITLE
Clearable TagsInput does not show dropdown after clearing

### ISSUE THREAD

**Issue by crabvk** [mantinedev/mantine#6115]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

A simple `TagsInput` component with `clearable` prop. When I select some tags from the TagsInput dropdown and press the `x` (clear) button, TagsInput dropdown is hidden (expected to be visible). I click on the TagsInput input element - dropdown does not appear. And only if I click outside of the input and then back on input dropdown becomes visible.

### If possible, include a link to a codesandbox with a minimal reproduction

https://stackblitz.com/~/github.com/crabvk/mantine-tagsinput-issue

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.9.2](https://github.com/mantinedev/mantine/releases/tag/7.9.2)
