### ISSUE TITLE
SegmentedControl design breaks when inside a popover

### ISSUE THREAD

**Issue by erdemPigon** [mantinedev/mantine#6116]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

SegmentedControl in a popover breaks when popover's keepMounted prop is set. Click popover and change the segmentedControl's state, close and open popover again, you see that segmentedControl's indicator is at wrong place.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/musing-river-mqklvk

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is not possible to fix on the library level, you can update key of SegmentedControl on your side when Popover opens – https://codesandbox.io/p/sandbox/staging-sea-64cqdz?file=%2Fsrc%2FApp.js%3A23%2C24
