### ISSUE TITLE
AppShell components crash when rendering server side in Next.js

### ISSUE THREAD

**Issue by specialblend** [mantinedev/mantine#6117]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Next.js 14 app crashes when using any `AppShell` sub components such as `AppShell.Header`, `AppShell.Navbar`, `AppShell.Main` with app router / server side rendering (default behavior in Next 14) with following error message

```
Error: Could not find the module "/Users/specialblend/workspace/example-next-mantine/node_modules/@mantine/core/esm/components/AppShell/AppShell.mjs#AppShell#Header" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
```

### If possible, include a link to a codesandbox with a minimal reproduction

https://github.com/specialblend/example-next-mantine

### Possible fix

Force client side render with 

```
"use client";
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/guides/next/#compound-components-in-server-components
