### ISSUE TITLE
Async Support For Select & Multi Select

### ISSUE THREAD

**Issue by dukesx** [mantinedev/mantine#612]
### Usage example, including component/hook API

should have loading prop along with onInit function , which can be used to fetch initial values. Should also support infinite loading for further loading. Search function should allow async look up and return array else fall back to default array (fetched during initial)

### Possible implementation – describe how the feature can be implemented

No idea. 

### Do you want to contribute this feature and create a pull request

No

**Comment by rtivital** [comment]
I do not think that we will add any of these features. You can create async selects with `onSearchChange` function and dynamic `data` prop.

**Comment by dukesx** [comment]
what if i want the initial data through async ?

**Comment by rtivital** [comment]
You can load data initially with `onFocus` event

**Comment by dukesx** [comment]
@rtivital on Focus requires interaction, isn't it? I just want the select component to load the items when the component itself gets mounted.

For example :
Select in a modal. The moment modal is shown, select should start fetching data array so that when user clicks on it, it has data inside it.

**Comment by rtivital** [comment]
Then create a simple wrapper component that will fetch data in useEffect

**Comment by dukesx** [comment]
If only async support could be added. Anyway, thanks for your time.
