### ISSUE TITLE
setFieldValue is not a stable ref. anymore

### ISSUE THREAD

**Issue by Francesco-Rizzi** [mantinedev/mantine#6120]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Hi @rtivital ,

First of all thank you for the huge effort on Mantine!

I need to set some form values as a result of an effect.
The form is not a stable ref., and it is expected as it has to re-render in case of value changes (in "controlled" mode at least).
The problem is that from v7.8.0 also the `setFieldValue` handler is not a stable ref. anymore.
Before I was doing something like this:
```ts
    const { setFieldValue, setFieldError } = form;
    useEffect(() => {
        if (myCondition) {
            setFieldValue(...);
        }
    }, [myCondition, setFieldValue]);
```
But now that doesn't work anymore, and it causes a loop as `setFieldValue` is seen as new on every render.

What's the right way to address this use case? 
Is it safe to just exclude `setFieldValue` from the dep. array, even if against the best practices?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Yes, it is safe to exclude it from the dependencies array

**Comment by rtivital** [comment]
form.setFieldValue is stable – https://github.com/mantinedev/mantine/blob/master/packages/@mantine/form/src/use-form.ts#L67-L100

If you want to avoid function from being changed on each render, make sure that onValuesChange and validate are memoized.
