### ISSUE TITLE
Failed to execute 'observe' on 'ResizeObserver'

### ISSUE THREAD

**Issue by hiddenLadder** [mantinedev/mantine#6129]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Starting from 7.7.0 the following error occurs: TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.

![image](https://github.com/mantinedev/mantine/assets/89526742/3d7e0eba-838b-4d45-8108-bea1f5ae7041)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Provide a sandbox with a minimal reproduction

**Comment by rtivital** [comment]
Fixed in [7.9.1](https://github.com/mantinedev/mantine/releases/tag/7.9.1)

**Comment by hiddenLadder** [comment]
Now i'm on 7.9.1 and i'm getting same error
![image](https://github.com/mantinedev/mantine/assets/89526742/3990ceae-5975-49fe-9aa4-63bfea206abb)
