### ISSUE TITLE
Carousel card component not render properly

### ISSUE THREAD

**Issue by DushanSenadheera** [mantinedev/mantine#6138]
### Link to the page where something is not right

https://ui.mantine.dev/category/carousels/

### What is wrong?

there is an issue with the CSS file and need to pass 2 values for all the rem() in the given code there's only one value 
`ex -  width: rem(4px); need to correct into width: rem(4px, 4px);`

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The code is correct, there is no issue.
