### ISSUE TITLE
Tooltip (no longer?) works on mobile

### ISSUE THREAD

**Issue by aeftimia** [mantinedev/mantine#6141]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.1

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Tooltip (no longer?) works on mobile with `events={{ hover: true, mobile: true }}`. 

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-t4p7fd?file=%2Fsrc%2FApp.tsx%3A7%2C27

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
mobile is not valid key – https://mantine.dev/core/tooltip/#change-events
