### ISSUE TITLE
"useDebounceCallback" is not exported by "node_modules/@mantine/hooks/esm/index.mjs"

### ISSUE THREAD

**Issue by romanpeganov** [mantinedev/mantine#6146]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.1

### What package has an issue?

@mantine/hooks

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

I launched the Remix + Mantine project build command and received a build error: "useDebounceCallback" is not exported by "node_modules/@mantine/hooks/esm/index.mjs". Builder - Vite 5.2.10 with Yarn 4.1.1 on Windows 10.
I renamed "useDebounceCallback" to "useDebounce**d**Callback" in the files indicated by the build errors. After that, build was successfully completed.
This files:
 - node_modules\@mantine\core\esm\components\ScrollArea\ScrollAreaScrollbar\Scrollbar.mjs
 - node_modules\@mantine\core\esm\components\ScrollArea\ScrollAreaScrollbar\ScrollAreaScrollbarAuto.mjs
 - node_modules\@mantine\core\esm\components\ScrollArea\ScrollAreaScrollbar\ScrollAreaScrollbarScroll.mjs
 - node_modules\@mantine\core\esm\components\ScrollArea\ScrollAreaThumb\ScrollAreaThumb.mjs[](url)

### Possible fix

I don’t know for sure, but it seems that the import and the name of the use of a hook in these files need to be renamed from  "useDebounceCallback" to "useDebounce**d**Callback".

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Make sure that all `@mantine/*` packages have the same version.

**Comment by romanpeganov** [comment]
Yes shure
![image](https://github.com/mantinedev/mantine/assets/16670523/54d4a17d-ee31-4495-a0f2-86b041d34759)

**Comment by romanpeganov** [comment]
I also completely removed the node_modules folder and installed all the packages again.

**Comment by romanpeganov** [comment]
From "@mantine/hooks" exporting the "useDebounce**d**" hook, but in "ScrollArea-" components importing the "useDebounce" hook.

**Comment by romanpeganov** [comment]
I apologize. I see that in the source code Mantine uses the correct name of hook. These are some problems with my project, I will try to solve it myself. Thank you for your attention.
