### ISSUE TITLE
Advanced mantine Dashboard template

### ISSUE THREAD

**Issue by auronvila** [mantinedev/mantine#6154]
### Link to the repository on GitHub

https://github.com/auronvila/mantine-template

### Features of the template, describe how it is different from other templates

The template offers a selection of layouts, including DeckedSideBar, SimpleSidebar, and CollapsedSideBar, from which users can choose. Currently, it comes with preconfigured routes using react-router, simplifying navigation. Adding or modifying routes can be effortlessly accomplished by updating the route and navigation files.

Moreover, the template integrates Internationalization using i18next and is equipped with redux, redux-toolkit, and redux-persist, all preconfigured for easy setup. Authentication and interacting with REST APIs are facilitated through axios setup, including special APIs tailored for such purposes.

This highly adaptable template is easily customizable and tweakable to suit specific needs. Additionally, it features a comprehensive wiki containing examples and explanations on how to utilize and enhance the template, available at [this link](https://github.com/auronvila/mantine-template/wiki).

**Comment by rtivital** [comment]
Thanks for submitting the template, it will be available with the next release on the getting started page.

**Comment by auronvila** [comment]
Thank you for approving my template. I will be upgrading and adding new features to the template when I add the features do I need to open a new Issue and explain the updates?

**Comment by auronvila** [comment]
Ok, Thank you for the fast response and for this amazing ui library.
