### ISSUE TITLE
Clicking the label of Checkbox crashes the browser when a Drawer is focused

### ISSUE THREAD

**Issue by KurtGokhan** [mantinedev/mantine#6157]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

MacOS Chrome (Version 124.0.6367.119 (Official Build) (arm64))

### Describe the bug

This is the weirdest bug I have seen in a while. 

Seems consistently reproducible only on MacOS Chrome. Also reproducible when all extensions are disabled and in incognito mode.

To reproduce, open the CodeSandbox example and click the label of the checkbox (not the icon). It crashes the browser tab.

If the crash doesn't happen, first click the Button inside the drawer, then click the checkbox label.

For some reason, it doesn't happen when last clicked element is not inside the Drawer.

Video:

https://github.com/mantinedev/mantine/assets/6034931/8f6fb54e-6022-4d6b-9b71-521e457bc23e

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-c9mk4m?file=%2Fsrc%2FApp.tsx%3A7%2C32

### Possible fix

Feels like a browser bug but it may not be. Seems like it is happening when clicking a `label` with `for`, but not otherwise.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by KurtGokhan** [comment]
I noticed this issue about 3 days ago and have been experiencing it since then.

I just restarted my PC and it doesn't happen anymore. Closing this.

**Comment by KurtGokhan** [comment]
Issue is back after a while. I am convinced it is a Chrome bug but if you have any idea if something in Mantine could cause this, let me know. Otherwise you can close the issue.

**Comment by rtivital** [comment]
Most likely, the issue is with the latest Chrome version. I doubt that we can do anything on Mantine side to fix that. Also, not reproducible in the docs with checkbox.

**Comment by KurtGokhan** [comment]
It is a Chrome bug. Narrowed it down to simple HTML elements with `aria-modal="true" role="dialog"` and a `label[for]` with checkbox. Mantine is not needed to reproduce.

Created a minimal reproducible example [here](https://codepen.io/KurtGokhan/pen/RwOzNxO) and reported to Chrome.

Closing this.
