### ISSUE TITLE
v7.9.0 @mantine/emotion does not work with @tanstack/router

### ISSUE THREAD

**Issue by StringKe** [mantinedev/mantine#6159]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Using `SegmentedControl` in one of the routed pages encounters a rendering error and no further rendering is possible.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-with-tanstack-router-template-kttscy

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.9.1](https://github.com/mantinedev/mantine/releases/tag/7.9.1)
