### ISSUE TITLE
Modal ScrollArea hides scrollbar

### ISSUE THREAD

**Issue by nreisingercres** [mantinedev/mantine#6175]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.0

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

ScrollArea's scroll bar hides behind header of Modal.
I also see this issue in the docs itself.
![image](https://github.com/mantinedev/mantine/assets/141150843/7e8570a9-06c3-41c3-a236-b13ea7c3715c)

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/core/modal/#usage-with-scrollarea

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.11.2](https://github.com/mantinedev/mantine/releases/tag/7.11.2)
