### ISSUE TITLE
@mantine/core error with Tooltip using @mantine/emotion

### ISSUE THREAD

**Issue by AdiiDev** [mantinedev/mantine#6179]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

While using `@mantine/emotion` Tooltip component crash application with error: `React has detected a change in the order of Hooks called by @mantine/core/Transition. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks`. Console also points out `@mantine/core/Transition` as possible root problem.

Will throw error:
```
<MantineProvider stylesTransform={emotionTransform}>
     <MantineEmotionProvider>
        <Tooltip label="Tooltip">
          <Button>Button with tooltip</Button>
        </Tooltip>
     </MantineEmotionProvider>
</MantineProvider>
```

But after removing `stylesTransform={emotionTransform}` from `MantineProvider` everything works.
```
<MantineProvider>
      <MantineEmotionProvider>
        <Tooltip label="Tooltip">
          <Button>Button with tooltip</Button>
        </Tooltip>
      </MantineEmotionProvider>
</MantineProvider>
```

Exchanging places between `MantineProvider` and `MantineEmotionProvider` does not resolve issue either.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-tj6qty?file=%2Fsrc%2FApp.tsx%3A11%2C32

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.9.1](https://github.com/mantinedev/mantine/releases/tag/7.9.1)
