### ISSUE TITLE
Mantine - supabase template

### ISSUE THREAD

**Issue by LanVukusic** [mantinedev/mantine#6183]
### Link to the repository on GitHub

https://github.com/LanVukusic/mantine-supabase-template

### Features of the template, describe how it is different from other templates

This is an opinionated template I've used and maintained for a year to create web apps quickly.  
The main feature is the tight supabase integration which offers fast iteration speed and development experience.

The template comes with out of the box configured:

- [Client side router](https://reactrouter.com/en/main)
- [Mantine theming](https://mantine.dev/theming/mantine-provider/)
- [Supabase database](https://supabase.com/database)
- [Supabase auth](https://supabase.com/auth) with ready-made login and register forms
- [Automatic type gen](https://supabase.com/docs/reference/javascript/typescript-support)
- [Spotlight, modals, forms and notifications from mantine](https://mantine.dev)
- [Nanostores - Global state](https://github.com/nanostores/nanostores)

I'm committed to maintaining this project and keeping up to date with new Mantine releases.

**Comment by rtivital** [comment]
Thanks for submitting the template, it will be available in the documentation with the next release.
