### ISSUE TITLE
Chip.Group with Chip value number type does not work

### ISSUE THREAD

**Issue by peterbodo** [mantinedev/mantine#6190]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

While Chip value allows the type number, it actually does not work with number, only string.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Chip component is based on checkbox and radio inputs depending on type. Props passed down to components are added to html `input` element, which supports only string values. Both Chip.Group and Chip components support only string values. They work as intended.

**Comment by rtivital** [comment]
Definitions are inherited from the input element, this is part of React types.
