### ISSUE TITLE
Click on Combobox Label should toggle the open state

### ISSUE THREAD

**Issue by AlonMiz** [mantinedev/mantine#6191]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The behavior of the Combobox with the label is unintuitive.
When the dropdown is open and the user clicks outside it should close, as expected, and it does.
But, when the click is on the label, it closes and immediately opens.
the expected behavior is actually to toggle the open state:
1. if the dropdown is open, a click on the label should close the dropdown
2. if the dropdown is open, a click on the label should open the dropdown

https://github.com/mantinedev/mantine/assets/1812912/88ef41ab-2f25-4661-bdd4-849831482367

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/core/select/#usage

### Possible fix

Click on the label should toggle the open state as mentioned in the bug description

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I do not see any issues here, the label works as per WAI ARIA specification for labels. Its purpose is to move focus to the associated input element for the click event. Changing this logic might lead to accessibility issues with the input. It is not planned to be implemented.

**Comment by AlonMiz** [comment]
Thanks for the prompt reply. I maintain that the OPEN behavior is distinct from the FOCUS behavior. 

For instance, in Material UI, clicking on a label merely focuses on the element rather than opening the select. This aligns with the WAI ARIA specification. I would suggest considering the option to modify the FOCUS state of a select/combobox.


https://github.com/mantinedev/mantine/assets/1812912/93895e08-c2b2-46a4-bf27-977c264940f7


Note: I attempted to override the combobox behavior by executing combobox.closeDropdown, but it appears unaffected by this action and remains open.
