### ISSUE TITLE
DateTimePicker style not working

### ISSUE THREAD

**Issue by peterbodo** [mantinedev/mantine#6195]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7,9,0

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

DateTimePicker appears like this:
![image](https://github.com/mantinedev/mantine/assets/14811093/86a24623-6bb3-4a07-82f0-0ef6040b0fe8)

Straight from the box. Copied example from the website, Only mantime styles applied.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://help.mantine.dev/q/dates-missing-styles
