### ISSUE TITLE
Wrong yaxis alignment with the grid axis on charts for the highest y value

### ISSUE THREAD

**Issue by clementmarcilhacy** [mantinedev/mantine#6196]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.0

### What package has an issue?

@mantine/charts

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

The yaxis highest value is not aligned properly with the grid axis

<img width="1141" alt="Screenshot 2024-05-07 at 17 01 44" src="https://github.com/mantinedev/mantine/assets/28105242/84b8508c-475d-4bdb-a907-4a50d9168966">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is managed by recharts library. The label is shifted to prevent overflow from the chart root element. It works as intended.
