### ISSUE TITLE
Loader not working with emotionTransform

### ISSUE THREAD

**Issue by TenViki** [mantinedev/mantine#6197]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

When switching `loading` state from false to true, I get React runtime error `Error: Rendered more hooks than during the previous render.` When doing the opposite thing, different error message can be seen: `Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.`

I was able to trace this error to the `<Transition/>` component, however I do not know what exactly causes this. It's also good to note that this error occurs only when the `stylesTransform={emotionTransform}` attribute of `<MantineProvider/>` is set.

### If possible, include a link to a codesandbox with a minimal reproduction

Link to [codesandbox](https://codesandbox.io/p/github/TenViki/next-app-min-template/master?file=%2Fapp%2Flayout.tsx%3A27%2C30&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvwpaw2q00063j6i0uainacc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvwpaw2p00023j6iy4m43gxj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvwpaw2p00043j6ivnn5mr2j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvwpaw2q00053j6i5uqq1rh5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvwpaw2p00023j6iy4m43gxj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvwpaw2p00013j6ixajeus4p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvwqgjdy00023j6ibt29qipa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A27%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A27%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Flayout.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvwpaw2p00023j6iy4m43gxj%2522%252C%2522activeTabId%2522%253A%2522clvwqgjdy00023j6ibt29qipa%2522%257D%252C%2522clvwpaw2q00053j6i5uqq1rh5%2522%253A%257B%2522id%2522%253A%2522clvwpaw2q00053j6i5uqq1rh5%2522%252C%2522activeTabId%2522%253A%2522clvwppvwg00u43j6iziu6p6e1%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A2222%252C%2522id%2522%253A%2522clvwpb49m003x3j6i64oxht83%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clvwpbpj3007c3j6iivad6coe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clvwppvwg00u43j6iziu6p6e1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clvwpaw2p00043j6ivnn5mr2j%2522%253A%257B%2522id%2522%253A%2522clvwpaw2p00043j6ivnn5mr2j%2522%252C%2522activeTabId%2522%253A%2522clvwpaw2p00033j6izcqym1z3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvwpaw2p00033j6izcqym1z3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvwpayrf000udlhnfigp3q4w%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clvwpbll8005e3j6ibh3wuifl%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Possible fix

I stated that I do not know, how to fix this issue. However, I was able to trace this back to `<Transition/>` component. 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by sosafe-ugonna-ofoegbu** [comment]
@rtivital currently having the same issues with Chip and Button
