### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation. Component `Rating`

### ISSUE THREAD

**Issue by camilozv21** [mantinedev/mantine#6202]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I am using the `rating` component to show the amount of ratings a product has because I am using readonly, however if I click on one of the stars for example by scrolling, an error appears in the browser.

```javascript
<Rating
  readOnly
  fractions={5}
  defaultValue={5}
  value={calculateRatingValue(product)}
/>
```

![image](https://github.com/mantinedev/mantine/assets/126104786/dd65fbb4-f1aa-4483-8eb3-280f0d3f9e14)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.9.2](https://github.com/mantinedev/mantine/releases/tag/7.9.2)
