### ISSUE TITLE
Multiselect doesn't update pillsList dynamically

### ISSUE THREAD

**Issue by iBuitron** [mantinedev/mantine#6203]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.1

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Hi!
i'm using Dash-Matine-Components (["REACT_VERSION"] = "18.2.0")  (an wrap for mantine in Python) 

There is any option with "combobox" or "css" (or anything) to "refresh" the pillsList values on Multiselect?

![image](https://github.com/mantinedev/mantine/assets/102157308/70472f40-2001-47a4-9e81-59d6ad41c0b0)

The logic is:

From top to botton, if i change one value in a previus multiselect, this update the next multiselect.
The arrays/list coming to the next multiselect has the values updates, but the "input boxes (who has the x for close) doesn't disappear"

Exampled

```
First MultiSelect:
val1: A
val2: B
```

```
Second MultiSelect:
v1: A1
v2: A2
v3: B1
v4: B2
```

if I remove "A" from First MultiSelect this gonna remove all "A*" on the second Multiselect:

```
Second MultiSelect:
v3: B1
v4: B2

```
In my code, the list incoming to update the Second Multiselect is [B1, B2], so all my code works as i spect.

But, for some reason Mantine Multiselect does not update the boxes inside and keeps the previous view.

```
Second MultiSelect:
v1: A1
v2: A2
v3: B1
v4: B2
```
This "A1, A2" is just a view, if i close his boxes, just disappear and don't change anything
There is any css for "autorefresh" this pillsList? 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is better to report this issue in dmc repository first

**Comment by rtivital** [comment]
Feel free to reopen the issue if you receive answer form dmc that it is Mantine issue.
