### ISSUE TITLE
DateTimePicker doesn't pick the time in the first selection 

### ISSUE THREAD

**Issue by souhagaa** [mantinedev/mantine#6211]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.1

### What package has an issue?

@mantine/dates

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

This can be seen on the documentation as well, the behavior of DateTimePicker is inconsistent and buggy.

- When you select the time it doesn't get picked/saved but when you close the popover, change the time, it gets saved then.

- Also we get a different view of the Time input 1st time 

![image](https://github.com/mantinedev/mantine/assets/34986304/61b82b70-696e-42f8-82ba-267744985b3e)
vs 2nd time 
![image](https://github.com/mantinedev/mantine/assets/34986304/4d2913c6-a061-49d5-80ee-086e4e991173)

see video attached for the details

https://github.com/mantinedev/mantine/assets/34986304/79ef3863-011c-4715-99ec-1e7c6db5a3ad

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by H3inst** [comment]
I don't know if this is related with this issue but something similar occurs whenever you open the popover any date picker and then you click another input, it loses the focus on the input you just clicked on. 🫤

And seems like the date picker keeps the focus on itself.

**Comment by rtivital** [comment]
DateTimePicker uses `input[type="time"]` to receive time from the user. `input[type="time"]` does not call `onChange` until the time can be fully determined. In this case, `AM/PM` input is a required part for user to enter to correctly determine time. This behavior is not planned to be changed in the near future.
