### ISSUE TITLE
ScrollArea scroll bar position flicker on hover

### ISSUE THREAD

**Issue by ottosson** [mantinedev/mantine#6218]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

If you scroll down a bit in a ScrollArea then mouse out so the scroll bar disappears, then mouse back over the scroll area again you will see the scroll bar appear at the top for a brief moment before landing where it should be.

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/core/scroll-area/#usage

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.10.1](https://github.com/mantinedev/mantine/releases/tag/7.10.1)
