### ISSUE TITLE
Leading zero NumberInput behavior less intuitive in v7 compared to v6

### ISSUE THREAD

**Issue by ibenjelloun** [mantinedev/mantine#6232]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.1

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

# Summary

The behavior with leading zero while editing changed in v7, the field value changes before blur which is disturbing in some cases.

- Case 1 : Change `100` to `200` by removing `1` and replacing by `2` 

v6: can remove only one character and replace it
![v6-100-to-200](https://github.com/mantinedev/mantine/assets/1528304/703ee7b0-f642-4835-8d0e-aca88819d463)
v7: removing one character removes all leading zeros
![v7-100-to-200](https://github.com/mantinedev/mantine/assets/1528304/b9cf2943-b121-4ef2-9170-1bc46f0db3c5)

- Case 2 : Change `0.1` to `0.2` by removing `1` and replacing by `2` 
v6: can remove only `1` character and replace it with `2`
![v6-0 1-to-0 2](https://github.com/mantinedev/mantine/assets/1528304/e31c2eb0-9b18-4645-b361-d11dab2ee9dc)
v7: removing the `1` charater removes also the decimal separator
![v7-0 1-to-0 2](https://github.com/mantinedev/mantine/assets/1528304/529fcad6-9efe-4275-a9ae-ba1292a3c9ed)

- Case 3 : Typing `0123`

v6: can type `0123` the value changes only on blur
![v6-0123](https://github.com/mantinedev/mantine/assets/1528304/4e1aab64-27fd-4487-b6e7-74cae8b964ce)
v7: can't type `0123` the value changes while typing
![v7-0123](https://github.com/mantinedev/mantine/assets/1528304/b4ce5bdb-0bfb-48ac-a9e6-481d2556677d)

All the gifs have been produced using the mantine.dev doc versions :
- v6 : https://v6.mantine.dev/core/number-input/
- v7 : https://mantine.dev/core/number-input/

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.10.1](https://github.com/mantinedev/mantine/releases/tag/7.10.1)
