### ISSUE TITLE
Charts are not animated

### ISSUE THREAD

**Issue by miroirstudiosrl** [mantinedev/mantine#6240]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.1

### What package has an issue?

@mantine/charts

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Rechart charts should have an entrance animation. On their website you can see them but the ones on Mantine doesn't seems to have animations. Is there any way to enable them or they aren't supported by Mantine?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I consider charts animations ugly and useless, they will not be added to the library. You can pass props down to specific recharts components using corresponding props. See https://github.com/orgs/mantinedev/discussions/5522.
