### ISSUE TITLE
Polymorphic component not giving right types

### ISSUE THREAD

**Issue by najibghadri** [mantinedev/mantine#6242]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

I'm using `component` prop to render a `Group` as a `form`. However the `onSubmit` type is failing. This time I can repro it in codesandbox:
https://codesandbox.io/p/sandbox/busy-christian-7drgvy?file=%2Fsrc%2FApp.tsx%3A34%2C11

Is there a workaround other than wrapping component with `form`?

<img width="827" alt="Screenshot 2024-05-16 at 12 03 08" src="https://github.com/mantinedev/mantine/assets/11639734/2d3e3e7e-f9c5-441a-8cb5-e1a713c6d177">

<img width="565" alt="Screenshot 2024-05-16 at 11 21 32" src="https://github.com/mantinedev/mantine/assets/11639734/29dc1476-d67f-484f-99fe-d31ab073ff89">

<img width="777" alt="Screenshot 2024-05-16 at 11 21 40" src="https://github.com/mantinedev/mantine/assets/11639734/5f27869b-ca4a-4c73-bff1-e0fc30990a7a">

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/busy-christian-7drgvy?file=%2Fsrc%2FApp.tsx%3A34%2C11

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Group is not polymorphic component. It does not include types for generic component prop. It is intended to improve performance of tsserver. It is not planned to be changed.
