### ISSUE TITLE
Passing step via timeInputProps has no effect

### ISSUE THREAD

**Issue by souhagaa** [mantinedev/mantine#6247]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.1

### What package has an issue?

@mantine/dates

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

When trying to pass `step` prop via `timeInputProps` to `DateTimePicker` but it is not working and if I change it manually in the HTML it works. 
It seems like Mantine `TimeInput` component ignores this prop here https://github.com/mantinedev/mantine/blob/0976f8aa5e0bc214a6bfd76fd773bd9742ff71bb/packages/%40mantine/dates/src/components/TimeInput/TimeInput.tsx#L124

a possible solution would be  to change that line to `step={props.step || withSeconds ? 1 : 60}`

### If possible, include a link to a codesandbox with a minimal reproduction

 https://rb.gy/jmrgpd

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.9.2](https://github.com/mantinedev/mantine/releases/tag/7.9.2)

**Comment by tianhuil** [comment]
Hi @rtivital: I'm not quite sure how https://github.com/mantinedev/mantine/pull/6204 helps solve the problem.  Ideally, we would have
```ts
step={props.step || withSeconds ? 1 : 60}
```
as suggested by @souhagaa and I would be happy to implement this and submit a PR.

**Comment by jannikbuschke** [comment]
Also running into this issue
