### ISSUE TITLE
Progress disappear in Group

### ISSUE THREAD

**Issue by zrll12** [mantinedev/mantine#6255]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

Progress wrapped in Group disappears.
<img width="312" alt="image" src="https://github.com/mantinedev/mantine/assets/46812903/7f6cb8dd-01db-46d2-9696-07b1f76c8bdc">
<img width="185" alt="image" src="https://github.com/mantinedev/mantine/assets/46812903/fbe4a9a7-5f77-4414-9e77-aaaf550a691e">

I tried to remove Text, only left Progress, but it does not work ether.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It has zero width or does not have enough space. Set `flex={1}` or `w={200}`.
