### ISSUE TITLE
Select: Browser / 1Password autocomplete not working properly

### ISSUE THREAD

**Issue by LucasLemanowicz** [mantinedev/mantine#626]
### What package has an issue

@mantine/core

### Describe the bug

Browser + Password Manager autofill does not seem to be working correctly on the `Select` component.

Example 1: A Select component with `searchable={true}` allows the browser to fill in a non-existing value and makes it _seem_ like an item was selected, even though it wasn't: https://codesandbox.io/s/funny-lake-h77zf?file=/src/App.tsx

https://user-images.githubusercontent.com/361348/148339118-b021be1a-a888-4c19-92dc-573f5cfddbee.mov

Example 2: In trying to debug this issue I compared it to React Bootstrap which appears to work fine, while Mantine doesn't correctly fill it out, or even if it fills it out, it leaves the dropdown open: https://codesandbox.io/s/hungry-feather-ot9f2?file=/src/App.tsx

<img width="645" alt="Screen Shot 2022-01-05 at 10 43 12 PM" src="https://user-images.githubusercontent.com/361348/148340519-06632654-7cc0-45fa-9801-3135f4a819c0.png">

Disabling autocomplete with `autoComplete="off"` also did not work on Chrome.

A lot of people use browser or password manager autofillers now, so it would be useful to support them more gracefully.

### In which browser did the problem occur

Chrome, Safari

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hungry-feather-ot9f2?file=/src/App.tsx

### Do you know how to fix the issue

No

### Possible fix

I'm not sure how to fix this. I attached a bunch of event handler logging in https://codesandbox.io/s/hungry-feather-ot9f2?file=/src/App.tsx and compared the differences between how Mantine and React-Bootstrap work when a Select component is filled in with an autocomplete:

<img width="245" alt="Screen Shot 2022-01-05 at 9 44 06 PM" src="https://user-images.githubusercontent.com/361348/148339822-862a8a6b-e13d-4ee9-99fc-c9844dd65efc.png">

In my own app I am combining Mantine with React Hook Form and wrapping the Select component with a controller. When I add `onInput={(e) => field.onChange((e.target as any).value)}` to the Select component, it gets me halfway to a solution. It's not very stable though. The values update properly - but there is still no error checking whether or not an item actually exists in `data`, and the dropdowns still stay open.

I'm not sure what to try next. I don't have the time to fully debug this and implement a proper fix, but happy to help with testing if that's useful.

**Comment by rtivital** [comment]
I'll try setting autocomplete to 'nope', but not sure if that will work, seem like a hack – https://stackoverflow.com/questions/35448269/angular-materials-can-you-disable-the-autocomplete-suggestions-for-an-input/60335213#60335213

**Comment by LucasLemanowicz** [comment]
This PR might also help address the issue: https://github.com/mantinedev/mantine/pull/620

**Comment by rtivital** [comment]
I do not think so, it just selects value on blur

**Comment by rtivital** [comment]
I've set `autocomplete="nope"` on Select and Autocomplete, it may have resolved the issue (at least for native browser autocomplete it works fine).
