### ISSUE TITLE
Segmented control inside a scaled container

### ISSUE THREAD

**Issue by matanmaze** [mantinedev/mantine#6268]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When segmented control is hosted inside of a scaled container the indicator is off
![image](https://github.com/mantinedev/mantine/assets/154054715/faf0bc0c-6e35-492b-b9d4-a992bc2c0255)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-segmented-scale-r58s7n?file=%2Fsrc%2FApp.tsx%3A7%2C11

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is a known issue, that is not planned to be fixed – I do not know of any ways that it could be possible to resolve.
