### ISSUE TITLE
form.watch() list value

### ISSUE THREAD

**Issue by matmill5** [mantinedev/mantine#6280]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/form

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

form.watch("aList", () => {}) doesn't effectively watch the value. The callback function is not triggered on list change.

However, form.watch("aValue", () => {}) does work as expected.

Please advise

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior, `form.watch` allows watching only values that are set with `form.setFieldValue` – it does not propagate events to parent fields. If implemented differently, it would most likely cause significant performance decrease. Currently, it is not planned to be changed.
