### ISSUE TITLE
@mantine/date: React 17 compatibility 

### ISSUE THREAD

**Issue by anuraghazra** [mantinedev/mantine#6288]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When integrating mantine datepicker with React17 codebase, facing an issue where the [useRandomClassname](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/core/Box/use-random-classname/use-random-classname.ts) is throwing error because React.useId doesn't exist. 

Is it possible to use the useId from @mantine/hooks instead of directly from React? 

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-17-s34vxg?file=%2Fsrc%2FApp.tsx%3A5%2C32

### Possible fix

Use useId() from mantine/hooks inside use-random-classname and in other places. 

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Starting from 7.0 Mantine packages are compatible only with React 18+. If you need support for React 17, use version 6.0.21.
