### ISSUE TITLE
Notification containerWidth not works and an error shows from console

### ISSUE THREAD

**Issue by Eve-Sama** [mantinedev/mantine#6289]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.2

### What package has an issue?

@mantine/notifications

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I wanna setting notification width. The [document](https://mantine.dev/x/notifications/?t=props) tell me `containerWidth` can do this. But it does not work in my code. And an error shows

```tsx
const StatusNotificationApp: React.FC<Props> = ({ enableAutoReading }) => {
  const notificationIdRef = useRef('status-change-notification-unique-id');
  const notificationRunningRef = useRef(false);
  const notificationData: NotificationData = {
    id: notificationIdRef.current,
    title: '操作成功!',
    message: `${enableAutoReading ? '开启自动阅读' : '关闭自动阅读'} `,
    color: 'green',
    autoClose: false,
    containerWidth: 110,
    onClose: () => (notificationRunningRef.current = false),
  };
  const isInitialRender = useRef(true);

  useEffect(() => {
    if (isInitialRender.current) {
      isInitialRender.current = false;
      return;
    }
    if (notificationRunningRef.current) {
      notifications.update(notificationData);
    } else {
      notificationRunningRef.current = true;
      notifications.show(notificationData);
    }

    const timer = setTimeout(() => notifications.hide(notificationIdRef.current), 3000);
    return () => clearTimeout(timer);
  }, [enableAutoReading]);

  return <></>;
};

export default StatusNotificationApp;
```

<img width="653" alt="图片" src="https://github.com/mantinedev/mantine/assets/30228406/53aaa4de-19d5-4499-99f2-0ab07ebc8d61">

How can I set the width?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`containerWidth` prop must be set on `<Notifications containerWidth={400} />`. It cannot be used in `notifications.show` function.

**Comment by Eve-Sama** [comment]
But different bussiness need different width. 

```tsx
import { MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';

function Demo() {
  return (
    <MantineProvider>
      <Notifications />
      {/* Your app here */}
    </MantineProvider>
  );
}
```
If I set `containerWidth`, it will effect all notifications?

**Comment by rtivital** [comment]
Yes, it will
