### ISSUE TITLE
Checkbox Check Misaligned

### ISSUE THREAD

**Issue by imnash21** [mantinedev/mantine#6291]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

None

### Describe the bug

After I update the package then this is what happened.

![Screenshot 2024-05-28 140854](https://github.com/mantinedev/mantine/assets/108371844/b0ecfbde-fc85-4eae-afa6-19aaa22253cc)

![Screenshot 2024-05-28 141323](https://github.com/mantinedev/mantine/assets/108371844/939e13c3-5bcb-468e-93ca-8a68b7aea0ca)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by arpitprod** [comment]
How you fixed this issue. I am facing same

**Comment by imnash21** [comment]
> How you fixed this issue. I am facing sam

Don't use Checkbox component inside the TypographyStylesProvider component.
