### ISSUE TITLE
Theme Not Passed Correctly to Emotion Styled Component

### ISSUE THREAD

**Issue by mnai01** [mantinedev/mantine#6297]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I'm using Mantine in a Vite/React app. I found a bug where the theme does not appear to be passed correctly to an emotion styled component. In this case, the theme object is empty ({}), resulting in the component not rendering the expected styles.

For reference, it looks like emotion fixed a similar bug last year: [emotion-js/emotion#2955](https://github.com/emotion-js/emotion/issues/2955).

When I wrap the component in a `MantineProvider` with the theme, the styles do not apply as expected:

```javascript
import styled from "@emotion/styled";

const MyDiv = styled.div`
  color: white;
  background-color: ${({ theme }) => {
    console.log("Theme here", theme, theme.colors);
    return theme.colors[theme.primaryColor][0];
  }};
  padding: 5rem;
  font-size: 24pt;
  font-family: sans-serif;
`;

function MyComponent() {
  return <MyDiv>This has some content</MyDiv>;
}

export default MyComponent;
```

**Console Output**
```
Theme here {}
```

**Additional Context**
I recently fixed my theme typing situation where the theme object was essentially empty in terms of its typing. I resolved this by adding the following to the `emotion.d.ts`. This process is somewhat documented in a [closed issue](https://github.com/mantinedev/mantine/issues/4265). The current issue I am facing is that while the theme is now typed correctly, it doesn't have any items associated with the Mantine theme, resulting in the default values being used instead.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/github/hpinkos/mantine-vitest-bug/csb-w5z4gl/draft/ecstatic-jackson?file=%2Fsrc%2FMyComponent.tsx%3A7%2C25-7%2C30

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Mantine does not include ThemeProvider from emotion. You need to set it up on your side:

```tsx
import { MantineProvider, useMantineTheme } from '@mantine/core';
import { ThemeProvider } from '@emotion/react';

function EmotionThemeProvider({ children }) {
  const theme = useMantineTheme();
  return <ThemeProvider theme={theme}>{children}</ThemeProvider>;
}

function App() {
  return (
    <MantineProvider>
      <EmotionThemeProvider>{/* Your app here */}</EmotionThemeProvider>
    </MantineProvider>
  );
}
```
