### ISSUE TITLE
pnpm add packages error

### ISSUE THREAD

**Issue by yunjin-kim** [mantinedev/mantine#6302]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core
@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

i use 
- nextjs 14.2.1 page dir
- typescript v5 
- node v20

i install @mantine/core @mantine/hooks
to `pnpm add @mantine/core @mantine/hooks`

but this error happen
```
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/@mantine%2Fcore: Value of "this" must be of type URLSearchParams
```

![스크린샷 2024-05-29 오후 11 10 12](https://github.com/mantinedev/mantine/assets/79692272/f132806e-0dec-41c4-85a1-be140926df92)

**cannot use @mantine/* at pnpm package manager?**

how can i install packages?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The issue is not related to Mantine. You can open an issue in pnpm repository to get support on that topic.
