### ISSUE TITLE
"Rendered Fewer / More hooks than previous" - Controlled Chip and Button Component

### ISSUE THREAD

**Issue by sosafe-ugonna-ofoegbu** [mantinedev/mantine#6310]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

None

### Describe the bug

Currently getting this error when trying to change the state of a controlled component.
Chip or Button.... Traced it to Transition component
<img width="1129" alt="Screenshot 2024-05-30 at 10 21 12" src="https://github.com/mantinedev/mantine/assets/168716729/530485ff-ef7a-4fe9-8465-439f4b5b2574">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Provide a sanbox that reproduces the issue.

**Comment by sosafe-ugonna-ofoegbu** [comment]
Closing this. This was due to the theme object we provide to mantineprovider
