### ISSUE TITLE
Accordion.Item Error: Could not find the module 

### ISSUE THREAD

**Issue by bocejo5** [mantinedev/mantine#6312]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I take the documentation example for the accordion:
```typescript
import { Accordion } from "@mantine/core";

export default function Navigation() {
    return (
        <Accordion variant="contained" radius="lg" defaultValue="Apples">
            <Accordion.Item key="1" value="1">
                <Accordion.Control icon="🍎">1</Accordion.Control>
                <Accordion.Panel>description</Accordion.Panel>
            </Accordion.Item>
        </Accordion>
    );
}
```
but I receive this error:
Error: Could not find the module "C:\Users\...\node_modules\@mantine\core\esm\components\Accordion\Accordion.mjs#Accordion#Item" in the React Client Manifest. This is probably a bug in the React Server Components bundler.

I'm working with:
- "next": "14.2.3",
- "react": "^18",
- "react-dom": "^18"

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/guides/next/#compound-components-in-server-components
