### ISSUE TITLE
Text cannot truncate inside `ScrollArea` and `ScrollAreaAutozise`

### ISSUE THREAD

**Issue by ahl-trifork** [mantinedev/mantine#6317]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

It's not possible to truncate text inside a scroll area. 

```
<ScrollAreaAutosize miw={0} viewportProps={{ style: { minWidth: 0 } }} scrollbars="y">
    <Text truncate>Lorem ipsum dolor sit amet consectetur adipisicing elit.</Text>
</ScrollAreaAutosize>
```
This results in: ![image](https://github.com/mantinedev/mantine/assets/108787421/10015650-33c1-410b-b244-ab5f169ec396)
But i expected: ![image](https://github.com/mantinedev/mantine/assets/108787421/a7fadf0f-d5f9-4514-9069-d7f2c5c271c0) (With ellipsis)

In this example it's minor, but when trying to truncate a string in eg. a list of cards, it makes the cards itself overflow, breaking the UI. 

I looked into the genrated HTML, and found that by editing it as follows, in the browser, that i was able to make it do as i expected. 
```html
<div style="display:flex;overflow:auto;min-width:0rem" class="">
  <div style="display:flex;flex-direction:column;flex:1;min-width: 0;" class="">                  <=== ADDED MIN_WIDTH: 0
    <div style="--sa-corner-width:0px;--sa-corner-height:0px;" class="m_d57069b5 mantine-ScrollArea-root">
      <div style="overflow: hidden scroll;" class="m_c0783ff9 mantine-ScrollArea-viewport" data-scrollbars="y">
        <div style="min-width:100%;/*! display:table; */">                                        <=== REMOVED DISPLAY: TABLE
          <p class="mantine-focus-auto m_b6d8b162 mantine-Text-root" data-truncate="end">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>;
```

I don't see that It's possible to alter those properties through the api provided by `ScrollAreaAutosize`.

### Possible fix

Maybe a separate scrollArea or an extra property to allow horizontal scrolling only. Not sure how that would affect other use cases.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by jacobwilson41** [comment]
try using the [lineCamp](https://mantine.dev/core/text/#line-clamp) prop instead.  This fixed it for me.

**Comment by ahl-trifork** [comment]
Thanks, that does the trick. :)
I'll leave this open as it still seems like a bug to me. Or at least non-intuitive behavior.

**Comment by mkf62** [comment]
I suggest this still needs to be fixed as the `lineClamp` workaround only works if the text needing to be truncated has spaces in it. If it is a single word, it does not work. See example: https://codesandbox.io/p/sandbox/mantine-react-template-forked-lfjdpt

**Comment by mkf62** [comment]
I was able to resolve this by adding a couple properties to one of the anonymous `div` elements that get added when you use `ScrollArea.Autosize` component. I added `table-layout: fixed` and `width: 100%` to it. 

<img width="597" alt="Screenshot 2025-01-06 at 1 49 42 PM" src="https://github.com/user-attachments/assets/05a7d69f-4271-42d3-aaac-9248c62bb7ad" />



I then changed my component (from my codesandbox linked in my previous comment) to look like this:
```javascript
<Box style={{ border: "1px solid green", width: "100px" }}>
   <ScrollArea.Autosize mah={100} miw={0} scrollbars="y">
       <Text truncate="end">
          HelloHelloHelloHello HelloHelloHelloHello HelloHelloHelloHello HelloHelloHelloHello
       </Text>
    </ScrollArea.Autosize>
</Box>
```

I think you'd just need to add the updated styles here: https://github.com/mantinedev/mantine/blob/8406155036e155a890d728f9f3d1ae79f7c15e43/packages/%40mantine/core/src/components/ScrollArea/ScrollArea.module.css#L33-L36
