### ISSUE TITLE
allowSingleDateInRange does not work on DatePickerInput even with range type

### ISSUE THREAD

**Issue by natatotte** [mantinedev/mantine#6322]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

None

### Describe the bug

Even with type="range" enabled in the component **DatePickerInput**, selecting just one date does not work. 

When I select just one date, the dropdow remains open and when I click on the outside, it closes and deletes the value.

```jsx
const [dateValue, setDateValue] = useState<[Date | null, Date | null]>([null, null])

            <DatePickerInput
                      label="Data Envio"
                      placeholder="Selecione o intervalo de datas"
                      w="30%"
                      type="range"
                      size="sm"
                      value={dateValue}
                      onChange={(date) => {
                        setPage(1)
                        setDateValue(date)
                      }}
                      valueFormat="DD/MM/YYYY"
                      clearable
                      allowSingleDateInRange
                    />
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`allowSingleDateInRange` allows single date to be in range, not forces it. To select single date as range, the user must click the same date twice.
