### ISSUE TITLE
CSSVariablesResolver does not apply to Storybook

### ISSUE THREAD

**Issue by likidu** [mantinedev/mantine#6327]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I am defining the following `CSSVariablesResolver` and adding it to the `MantineProvider` as usual.

```ts
import { CSSVariablesResolver } from '@mantine/core';

export const resolver: CSSVariablesResolver = (theme) => ({
  variables: {},
  light: {
    '--mantine-color-default-color': theme.colors.red[5],
  },
  dark: {
    '--mantine-color-default-color': theme.colors.red[8],
  },
});
```
I can verify that works in dev environment:
![image](https://github.com/mantinedev/mantine/assets/575981/a37f90ce-4aed-4a88-a458-e761ca1a455d)

However, it cannot be reflected in the Storybook:
![image](https://github.com/mantinedev/mantine/assets/575981/198c2d02-cd1d-4b1e-8e83-83df92b56398)

Wonder any Storybook specific settings I have to configure to make it work?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
To use Mantine theme with Storybook, you need to add the same properties to MantineProvider that is used by Storybook as in your application – https://mantine.dev/guides/storybook/
