### ISSUE TITLE
Text: Setting size={rem(...)} and truncate clips the bottom of text

### ISSUE THREAD

**Issue by mawallace** [mantinedev/mantine#6342]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

For `Text`, if `truncate` is set and `size` is set using `rem(...)`, then the bottom of text is clipped.

For example:

```
<Text truncate size={rem(22)}>
  Text with underlying dangly parts
</Text>
```

Notice the bottoms of 'y', 'g' and 'p' are clipped.

<img width="947" alt="Screenshot 2024-06-04 at 10 09 53 PM" src="https://github.com/mantinedev/mantine/assets/10112099/c69a74ab-2370-4a27-9e13-acfa6198af2c">

This seems to only happen under these two conditions (see codespace).

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-d7kqxn?file=%2Fsrc%2FApp.tsx%3A13%2C1

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by mawallace** [comment]
FYI: I'm currently working around this by also setting line height to something like 1.2.

**Comment by rtivital** [comment]
Text size prop supports only xs-xl values. If you want to change font-size, use `fz` prop instead. To change line-height, use `lh` prop.

**Comment by mawallace** [comment]
Super helpful, thank you!
