### ISSUE TITLE
scroll list with arrows buttons

### ISSUE THREAD

**Issue by ofirgo1** [mantinedev/mantine#6343]
### Dependencies check up

- [ ] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

6

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

hey, me and my team use yours library  and we really love it!
however we could not found component that show list of items with arrows buttons from the sides (or top and button) like shown in the images bellow from MUI tabs :(

![image](https://github.com/mantinedev/mantine/assets/152078954/bfec1f1d-f8ac-4f81-8ced-93b30d9e8ab8)
![image](https://github.com/mantinedev/mantine/assets/152078954/dbdba448-7f2a-4fe2-9bea-74dbfb9bd9e9)

we really like to know if there is similar component in your lib.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by ofirgo1** [comment]
solved.
i used this the carousel: https://mantine.dev/x/carousel/
with the prop containsScroll: "trimsnaps" :)

**Comment by hadar888** [comment]
mark this issue as closed :)

**Comment by ofirgo1** [comment]
.
