### ISSUE TITLE
cursorType pointer on Checkbox

### ISSUE THREAD

**Issue by kimfucious** [mantinedev/mantine#6345]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

The solution [here](https://mantine.dev/core/checkbox/#pointer-cursor) calls for wrapping the checkbox with MantineProvider.

For the record, I am using this in `_app.tsx`:

```ts
<ColorSchemeScript defaultColorScheme="dark" />
<MantineProvider
    colorSchemeManager={colorSchemeManager}
    defaultColorScheme="dark"
    theme={myTheme}
>
```

In the component where I'm trying to get the pointer cursor on the checkbox, I have:

```ts
const theme = useMantineTheme(); // thought this might help, but it doesn't
const pointerTheme = createTheme({ ...theme, cursorType: "pointer" });
```

and

```ts
<MantineProvider theme={pointerTheme}>
    <Checkbox
        label={`I confirm that I have read and agree Terms of Use`}
        checked={hasAgreedToTerms}
        disabled={
            isConfirming
        }
        mt="md"
        onChange={() => handleCheckbox()}
        size="sm"
    />
</MantineProvider>
```

When the component loads, the colorScheme changes to `light` (if it's dark), and I have no idea why.  If it's light, it remains light.

I'm not sure if this is a bug or the bug is me.

Any advice toward resolving this would be most appreciated.

Thanks.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by kimfucious** [comment]
Okay, I think I figured this out:

In the component:

```ts
const { colorScheme } = useMantineColorScheme();
const pointerTheme = createTheme({ cursorType: "pointer" });
```

and

```ts
<MantineProvider
    defaultColorScheme={colorScheme}
    theme={pointerTheme}
>
    <Checkbox
        label={`I confirm that I have read and agree Terms of Use`}
        checked={hasAgreedToTerms}
        disabled={isConfirming}
        mt="md"
        onChange={() => handleCheckbox()}
        size="sm"
    />
</MantineProvider>
```

Seems like a lot to do to get a pointer on a checkbox, so confirmation on if this is the correct way to do things would be apprecitated.

**Comment by rtivital** [comment]
To change cursor styles of a single checkbox, use Styles API – https://mantine.dev/styles/styles-api/
