### ISSUE TITLE
PasswordInput Component console error: Warning: React does not recognize the `withErrorStyles` prop on a DOM element.

### ISSUE THREAD

**Issue by tanihiroki** [mantinedev/mantine#6348]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

I set the `withErrorStyle` prop in the Mantine `PasswordInput` component, but it is not reflected.
and console error
```
Warning: React does not recognize the `withErrorStyles` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `witherrorstyles` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

### If possible, include a link to a codesandbox with a minimal reproduction
[codesandbox](https://codesandbox.io/p/sandbox/mantine-react-template-forked-7mp23m?file=%2Fsrc%2FApp.tsx%3A18%2C36&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx3k8mu30006356ikod5blwx%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx3k8mu30002356i8l8dv2zl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx3k8mu30003356i15x1ocgx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx3k8mu30005356iul6u2bmu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50.117459503758795%252C49.882540496241205%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx3k8mu30002356i8l8dv2zl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx3k8mu30001356icsohnosj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clx3kkq5f0002356ofvn3qnmo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A18%252C%2522startColumn%2522%253A36%252C%2522endLineNumber%2522%253A18%252C%2522endColumn%2522%253A36%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx3k8mu30002356i8l8dv2zl%2522%252C%2522activeTabId%2522%253A%2522clx3kkq5f0002356ofvn3qnmo%2522%257D%252C%2522clx3k8mu30005356iul6u2bmu%2522%253A%257B%2522id%2522%253A%2522clx3k8mu30005356iul6u2bmu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx3k8mu30004356i3mczev7j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clx3ko7hh001z356o04kv5v60%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx3ko7hh001z356o04kv5v60%2522%257D%252C%2522clx3k8mu30003356i15x1ocgx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx3k8mu30003356i15x1ocgx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A23.54430379746836%257D)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.10.2](https://github.com/mantinedev/mantine/releases/tag/7.10.2)
