### ISSUE TITLE
[MultiSelect] The component MultiSelect with renderOption doesn't remove element from the dropdown when selecting an item

### ISSUE THREAD

**Issue by oben01** [mantinedev/mantine#6350]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

When using the MultiSelect component with the RenderOption feature, the selected items are not being removed from the dropdown list. This behavior is inconsistent with the example provided in the documentation: [MultiSelect with RenderOption](https://mantine.dev/core/multi-select/#renderoption).

<img width="643" alt="Capture d’écran 2024-06-06 à 21 53 51" src="https://github.com/mantinedev/mantine/assets/22369027/016e59ec-d84e-40f1-9b1a-3bf78dbb2ccb">

Expected Behavior:
Selected items should be removed from the dropdown list as shown in the documentation example.

Actual Behavior:
Selected items remain in the dropdown list.

Additional Information:

Browser: Safari and Arc

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-ttvhns

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://codesandbox.io/p/sandbox/mantine-react-template-forked-mmhjgj?file=%2Fsrc%2FApp.tsx%3A35%2C16
