### ISSUE TITLE
Allow null in Sparkline data array since it supports connectNulls

### ISSUE THREAD

**Issue by fengye87** [mantinedev/mantine#6352]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/charts

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Since Sparkline supports `connectNulls`, we should change data prop type of `number[]` so to allow `null` element to be passed in.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.11.2](https://github.com/mantinedev/mantine/releases/tag/7.11.2)
