### ISSUE TITLE
getTransformedStyles error on webpack bundle for version 7.10.0

### ISSUE THREAD

**Issue by olivalex-david** [mantinedev/mantine#6355]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Updating mantine packages from 7.5.0 to 7.10.0, created an error when trying to access anything related to our web page that uses mantine, with the following error console.

![Screenshot from 2024-06-07 07-03-28](https://github.com/mantinedev/mantine/assets/57694883/497a329f-f0bd-48cc-ad39-053dbcd34652)

Browsers: Chrome/Chromium
Version: 85

This doesn't happen on up to date browsers, tested on:
Browsers: Chrome/Chromium
Version: 127

I think the issue could come from https://github.com/mantinedev/mantine/pull/5741, that changed `interop: 'auto'` on the create-package-config.ts file.

### Possible fix

Reverting the interop field to the defaults.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
1. Mantine does not support CRA – it is deprecated. Try using Vite instead.
2. You can find a list of supported browsers on this page – https://mantine.dev/about/#browser-support. Chrome 85 is not a supported version.
