### ISSUE TITLE
Unable to extend text selections in the Drawer (on mobile)

### ISSUE THREAD

**Issue by Jrns1** [mantinedev/mantine#6356]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

There is an issue with selecting text inside a drawer on mobile iOS devices:

- Double-tapping / holding on a word to select the single word works fine.
- **Extending** the selection from a single word **is not possible**.
- To select multiple words, you must tap and drag instead of double-tap and extend.

https://github.com/mantinedev/mantine/assets/35356069/813ccd8e-c45e-4130-a555-a90c23e80bfc

Desktop is totally fine. Any browser(safari or chrome) on Mac or Windows don't produce the issue. But Safari-IOS or Chrome-IOS 

### If possible, include a link to a codesandbox with a minimal reproduction

Try on mobile: https://mantine.dev/core/drawer/

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This is how react-remove-scroll works – https://github.com/theKashey/react-remove-scroll
Mantine uses this under the hood. You can pass to the library with `removeScrollProps`.
It is not planned to change this behavior on Mantine side. If you want to disable scroll lock, set `lockScroll={false}`.
