### ISSUE TITLE
Dropzone loader positioning is off

### ISSUE THREAD

**Issue by kimfucious** [mantinedev/mantine#6358]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/dropzone

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

After upgrading Mantine to 7.10.1 the Dropzone loader is not confined to the bounds of the Dropzone.

To fix this, I needed to add `position:relative` like so:
```ts
<Dropzone
    disabled={
        uploadType === UploadType.IMAGE &&
        !state.draftRecipe?.title?.length
    }
    loading={state.isUploading}
    onDrop={(files: File[]) => handleOnDrop(files)}
    onReject={(files: FileRejection[]) => handleOnReject(files)}
    maxSize={uploadType === UploadType.MARKDOWN ? 5000 : 1000000}
    accept={
        uploadType === UploadType.MARKDOWN
            ? { "text/markdown": [".md", ".markdown"] }
            : {
                    "image/jpeg": [".jpg", ".jpeg"],
                    "image/webp": [".webp"],
                }
    }
    style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        position: "relative", // <= right here
    }}
>
```
I did not have to this before in v 5.x, so this may be a bug, since adding position is not reflected in the docs anywhere I could see.

**Comment by rtivital** [comment]
I do not see any issues in the documentation, the loading overlay is positioned correctly above the dropzone – https://mantine.dev/x/dropzone/#loading-state
Make sure that you've imported package styles – https://mantine.dev/x/dropzone/#installation

**Comment by kimfucious** [comment]
My bad, loading the css file obviates the need to use `position: relative`.

Thanks.
