### ISSUE TITLE
Mantine Integration with Storybook on Next.js

### ISSUE THREAD

**Issue by mnakhli** [mantinedev/mantine#6362]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

Latest

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When integrating Mantine with Storybook on a Next.js project, an issue arises due to the requirements of Next.js for the value prop in the select tag to be defined and for components in a loop to have a unique key. This problem occurs when using the following example from the Mantine documentation:

```typescript
export const decorators = [
  (renderStory: any) => (
    <ColorSchemeWrapper>{renderStory()}</ColorSchemeWrapper>
  ),
  withMantineThemes({
    themes: [
      {
        id: 'light',
        name: 'Light',
        ...theme
      }
    ]
  })
];
```
When attempting to add the theme to the Mantine addon control panel in Storybook, a select element is created with a set of option elements. However, the select element lacks a defined value, and the option elements lack unique key props. As a result, the final output encounters errors.

Steps to Reproduce:

Set up a Next.js project.
Integrate Mantine and Storybook as per the Mantine documentation.
Use the provided example for decorators to add themes to the Mantine addon control panel in Storybook.
Open the Storybook preview and observe the console for errors.
Expected Behavior:
The select element should have a defined value prop, and each option element should have a unique key prop to avoid errors.

Actual Behavior:
The select element does not have a defined value prop, and the option elements do not have unique key props, resulting in errors.

Environment:

Next.js version: [your Next.js version]
Storybook version: 8
Mantine version: [your Mantine version]
Node.js version: [your Node.js version]
Browser: [browser name and version]
Additional Context:
This issue can be resolved by ensuring that the select element always has a defined value (e.g., an empty string "" when no value is selected) and that each option element has a unique key prop.

![telegram-cloud-photo-size-1-5132396686935698861-y](https://github.com/mantinedev/mantine/assets/21153535/4938465a-0c13-4028-933a-56bae5cc46fa)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
- Mantine does not provide `withMantineThemes` function – it is either a part of your application or a third-party library
- To learn how to setup storybook, follow the guide – https://mantine.dev/guides/storybook/
- If you have other issues, use one of the templates with preconfigured storybook – https://mantine.dev/getting-started/#get-started-with-a-template
