### ISSUE TITLE
Stepper component error: DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by Uniiq** [mantinedev/mantine#6364]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The App crashes when the user uses google translate and clicks on the "Next step" button in the Stepper component.

https://github.com/mantinedev/mantine/assets/30861773/c0ad0259-af71-4a6a-a44c-325073f49089

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Issue with React, not Mantine – https://github.com/facebook/react/issues/11538
You are welcome to research it and submit a PR with a fix if you are interested.

**Comment by yhranik-vp** [comment]
I managed to fix this issue in the app code by manually assigning a step icon (number) to each step. The icon needs to be wrapped in a `<span>` element

```
<Stepper.Step icon={<span>1</span>}>
```
