### ISSUE TITLE
use-form's setValues allows to pass undefined values

### ISSUE THREAD

**Issue by ValentinJS** [mantinedev/mantine#6366]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.1

### What package has an issue?

@mantine/form

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

When using use-form's setValues, it allows to pass undefined values to field that wouldn't allow it with setFieldValue

```tsx
const form = useForm<{a: string}>({
  initialValues: {
    a: '',
  },
});

// The following raises an error : undefined is not assignable to string
form.setFieldValue('a', undefined);

// The following won't raise an error, and undefined will be assigned to 'a', potentially breaking the form.
form.setValues({ a: undefined });
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is allowed because `form.setValues` supports partial values. https://mantine.dev/form/values/#setvalues-partial
This feature is not planned to be removed – stricter undefined checks are not planned.
