### ISSUE TITLE
Waku.gg + Mantine

### ISSUE THREAD

**Issue by doiska** [mantinedev/mantine#6379]
### Link to the repository on GitHub

https://github.com/doiska/waku-mantine-starter

### Features of the template, describe how it is different from other templates

Minimal template, can also be used as Waku.gg default template.

Includes:

[Waku | The minimal React framework](https://waku.gg/)
[Mantine](https://mantine.dev/)

**Comment by rtivital** [comment]
Thanks for submitting the template, it will be added to the getting started section with the next release.
