### ISSUE TITLE
Hydration error when doing conditional logic with color scheme 

### ISSUE THREAD

**Issue by kitze** [mantinedev/mantine#6380]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

The old Mantine UI site had a light/dark swich that switched the color of the ActionButton based on the `isDark` property.

I've read the new Mantine 7 migration and it says that for frameworks like Next js and Remix, it's enough to add <ColorSchemeScript/> in the head to get this to work without hydration errors.

But it still fails. This is not possible:

```
import React from "react";
import { ActionIcon, useMantineColorScheme } from "@mantine/core";
import { IconMoonStars, IconSun } from "@tabler/icons-react";

export const DarkLightSwitch = () => {
    const { colorScheme, toggleColorScheme } = useMantineColorScheme();

    const isDark = colorScheme === "dark";

    return (
        <ActionIcon
            variant="outline"
            color={isDark ? "yellow" : "blue"}
            onClick={() => toggleColorScheme()}
            title="Toggle color scheme"
        >
            {isDark ? <IconSun size="1.1rem" /> : <IconMoonStars size="1.1rem" />}
        </ActionIcon>
    );
};
```

When you switch the color scheme and refresh the page, you get this:

![CleanShot 2024-06-13 at 11 33 44@2x](https://github.com/mantinedev/mantine/assets/1160594/6f444f2f-0ea8-4406-ab17-b929327a521b)

Please don't suggest to use postcss mixins because the [current light/dark switch example](https://ui.mantine.dev/category/buttons/) is a bit ridiculous and there are a LOT of places in every app where you want to know "isDark" for javascript and conditional logic, not just for styling.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/s/github/kitze/hydration-repro-bug

### Possible fix

I don't care about SSR or performance or whatever I just care about the DX in my app, so I'd add whatever it takes to it if this works out of the box without weird hacks and css modules.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Starting from version 7, color scheme is not defined in js. Instead, it is provided as data-mantine-color-scheme attribute on the :root element. You can lean more about color scheme here:
- https://mantine.dev/theming/color-schemes/#color-scheme-value-caveats
- If you do not want to use postcss, you can use the same selectors with any framework, including emotion (with `u` variable in createStyles) – https://mantine.dev/styles/postcss-preset/#dark-and-light-mixins – see compiled css
- For the case with changing icon depending on the color scheme value, you can use light/dark hidden props – https://mantine.dev/theming/color-schemes/#lighthidden-and-darkhidden-props

**Comment by kitze** [comment]
@rtivital Thank you, I've read all of these docs, but they still don't fix my problem. How do I do a conditional prop based on the theme value?

**Comment by rtivital** [comment]
You cannot do that if you have server side rendering. The case you are referring to is described in the first link – render both elements, hide element that should not be visible with styles.

**Comment by kitze** [comment]
There has to be a way, how did this work with the previous version of Mantine? I'm using the emotion way of styling with v7 right now. I understand that we can render 2 elements and hide them (which is still bad DX) but conditional props or doing something in javascript based on the color mode has to be possible, there has to be a workaround ...

**Comment by rtivital** [comment]
Yes, it is possible if you do not have ssr in your application, then it works correctly.

**Comment by kitze** [comment]
It worked fine _with ssr_ in the previous version of Mantine. Man, I built an entire course around Mantine 6 and it's sad to tell people that some things are broken in 7 now.

**Comment by rtivital** [comment]
As I've mentioned before, if you want to fully control color scheme on your side, you can easily do that with `forceColorScheme` prop on MantineProvider. It will work exactly the same as in v6 but you will lose all v7 color scheme benefits.

**Comment by kitze** [comment]
I don't want to force it to one color scheme, I want to be able to switch color schemes and read the value of the current scheme in javascript. Why is this such a complicated question?

**Comment by rtivital** [comment]
```tsx
import { createContext, useState } from 'react';
import { MantineProvider } from '@mantine/core';

const ColorSchemeContext = createContext<{
  colorScheme: 'light' | 'dark';
  setColorScheme: (value: 'light' | 'dark') => void;
}>({
  colorScheme: 'light',
  setColorScheme: () => {},
});

export function MyApp() {
  const [colorScheme, setColorScheme] = useState<'light' | 'dark'>('light');
  return (
    <ColorSchemeContext.Provider value={{ colorScheme, setColorScheme }}>
      <MantineProvider forceColorScheme={colorScheme}>{/* Your app */}</MantineProvider>
    </ColorSchemeContext.Provider>
  );
}
```
