### ISSUE TITLE
PinInput component in RTL

### ISSUE THREAD

**Issue by mnakhli** [mantinedev/mantine#6382]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

Latest

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

In the PinInput component in RTL mode, the inputs should not be arranged from right to left as shown in the image.

![image](https://github.com/mantinedev/mantine/assets/21153535/806153f3-13a3-40d4-95bd-04839e0f9062)

### Possible fix

Since the input only accepts English letters and numbers, it should follow the LTR rule.
If the component is enhanced to support all characters from various languages worldwide, it should remain LTR and unchanged when `type="number"`. In the normal (Alphanumeric) mode, it will be up to the developer to decide whether to switch to RTL or not.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.11.1](https://github.com/mantinedev/mantine/releases/tag/7.11.1)
