### ISSUE TITLE
Next.js builds - Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by onlit** [mantinedev/mantine#6383]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.10.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

All our projects using Mantine have suddenly started showing:

> Error: Hydration failed because the initial UI does not match what was rendered on the server.

After wasting a couple hours investigating our code, we discovered the problem is with Mantine itself, even the official Next.js pages template has the same issue. What's going on? Is there a fix in progress?

![image](https://github.com/mantinedev/mantine/assets/59638792/c07bfe58-4cc4-455d-b0ef-ad4f07f4d2fd)

### If possible, include a link to a codesandbox with a minimal reproduction

https://github.com/mantinedev/next-pages-template

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I do not see any errors in the next-pages-template. Make sure that you do not have any browser extensions that change the markup.

**Comment by onlit** [comment]
> I do not see any errors in the next-pages-template. Make sure that you do not have any browser extensions that change the markup.

Interesting! Turns out it is actually _Dark Reader_ that is causing problems for everyone! Eagle eye!
