### ISSUE TITLE
When adding padding to Appshell.Main Main goes behind the Navbar

### ISSUE THREAD

**Issue by GokalpGokdogan** [mantinedev/mantine#6384]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

`<AppShell.Main p="lg">
    {children}
   </AppShell.Main>` 
When I use margins instead of paddings Navbar doesn't cover Main.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/core/app-shell/#padding-prop
