### ISSUE TITLE
Component override in theme object does not work for `Tooltip`

### ISSUE THREAD

**Issue by CHR-onicles** [mantinedev/mantine#6385]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

I've noticed even in earlier 7.x.x versions that the Tooltip component's overrides in my theme object does not work. Whether styles, default props or even classnames. Nothing gets applied, but everything works with the other components I use in the override. I'm not sure if there's something extra I'm missing but here's an illustration and I've attached a codesandbox:

![image](https://github.com/mantinedev/mantine/assets/44934037/671baa66-f5bb-4b5f-8404-7396ccaa668a)

I add an explicit classname in my override to all the components in it, but as you can see, it works for the others except the tooltip.
I'm able to use my global styles to fix this however, but I'll appreciate if the overrides work as expected. Thanks!

Edit: After attempting to recreate the bug again in codesandbox, it appears to no longer happen. The screenshot above is proof however that it does happen sometimes. Same with my personal projects.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/mw2fsj?migrateFrom=l4vqsn

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction. The sandbox that you've sent is empty.

**Comment by CHR-onicles** [comment]
The sandbox keeps reseting, but as I said earlier, I'm unable to reproduce the bug predictably. It seems to happen randomly, so for now I'll be closing this issue.
