### ISSUE TITLE
Mantine Select is rendered over parent elements when the page is scolled

### ISSUE THREAD

**Issue by ysalo** [mantinedev/mantine#6387]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

On the Docs Page for [Mantine Select ](https://mantine.dev/core/select/#usage) when you open the "Your favorite library" selector and continue to scroll the page the Menu is rendered on top of the page header. 
![image](https://github.com/mantinedev/mantine/assets/23597842/2146fdfb-6cd5-41f1-90ee-2519dd13d6e8)
![image](https://github.com/mantinedev/mantine/assets/23597842/8780bd77-f908-4b99-be16-b97156841e76)

### Possible fix

The Menu should either be closed when it's scrolled out of view, or it should not be visible. 

One possible workaround is to set comboboxProps={{ withinPortal: false }} however this cause an issue that when you scroll to the bottom of the select you start to scroll the page. 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It works as intended on the docs page. In your application, you can customize props based on your app requirements.
