### ISSUE TITLE
onValuesChange not used in dependency list of setFieldValue (use-form-values.ts)

### ISSUE THREAD

**Issue by rguryanov** [mantinedev/mantine#6392]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.2

### What package has an issue?

@mantine/form

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

If you change passed onValuesChange, some events will be fired with old handler

example
    const form = useForm({
        mode: 'uncontrolled',
        initialValues: selectedRecord as Cred,
        validate: {
            name: (value) => {
                return true
            }
        },
        // new handler every rerender
        onValuesChange: (values) => {
            // change some scoped value
            setValue({
              ...oldScopedValue,
              ...values
            }),
        },
    });

Let's see use-form-values.ts
https://github.com/mantinedev/mantine/blob/29f24e31d9c33316395b317cd152648d55c65ef9/packages/%40mantine/form/src/hooks/use-form-values/use-form-values.ts#L56

const setValues = useCallback(...,[onValuesChange])
 
setValues has onValuesChange in dependency list

const setFieldValue = useCallback(..., [])
const initialize = useCallback(..., [])
const resetValues = useCallback(..., [])

setFieldValue, initialize and resetValues has empty dependency list and will use ONLY first calculated setValues

### Self-service

- [x] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.11.1](https://github.com/mantinedev/mantine/releases/tag/7.11.1)
