### ISSUE TITLE
Mantine.dev is not accessible

### ISSUE THREAD

**Issue by 0x15F9** [mantinedev/mantine#6394]
### Link to the page where something is not right

mantine.dev

### What is wrong?

Cannot load the website

Ping returns timeout

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by sidarth-23** [comment]
I think this is a isolated instance for you. Try fixing your DNS. If not, then your isp has tweaked some settings which is not allowing connection to the server where maintine is hosted.  Coz it is working for me

It has happened to me once when only coc was not working but other things were working just fine

**Comment by rtivital** [comment]
The website is available, check your DNS settings.
