### ISSUE TITLE
gap style prop doesn't recognize custom spacing variants

### ISSUE THREAD

**Issue by kimshenberly** [mantinedev/mantine#6409]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

I created a couple custom spacing variants, one called "2xs". It works fine when I use it in many other style props 
`p='2xs'` or `h='2xs'` but when I'm trying to use it within the Stack element for the `gap='2xs'` value, it doesn't recognize it. When I do `gap='var(--mantine-spacing-2xs)'` it works great

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Spacing resolver cannot recognize sizes that start with numbers as part of `theme.spacing`. Change it to `xs2` and it will work as expected.

**Comment by kimshenberly** [comment]
ahhh interesting that it worked some of the time, will update our sizes for now though, thanks!
