### ISSUE TITLE
Modals are moved off-center by root content

### ISSUE THREAD

**Issue by fjwillemsen** [mantinedev/mantine#6413]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.2

### What package has an issue?

@mantine/modals

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When combined with the Mantine AppShell, modals are not centered.  

<img width="1312" alt="image" src="https://github.com/mantinedev/mantine/assets/6725103/b357546a-6d69-4c70-a415-fd360713e894">

As seen by inspecting the elements, the modal is offset by the width of the `AppShell.Main` content. 
<img width="1312" alt="image" src="https://github.com/mantinedev/mantine/assets/6725103/39179cb8-9032-4ffa-80b1-56b73bbd1c7c">

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-td7z6j?file=%2Fsrc%2FApp.tsx%3A51%2C2

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by fjwillemsen** [comment]
Apologies, turns out this was caused by a stylesheet in the [electron-vite-react template](https://github.com/electron-vite/electron-vite-react). Disabling `display: flex` has solved the issue. Thank you for this awesome library!

**Comment by TomasBen** [comment]
Had the exact same issue and was going crazy because I didn't know why the modal was outside the screen range. I don't even know why I set the body to be flex if the content was displayed correctly either way. Thank you very much 🙏🏾.
