### ISSUE TITLE
NumberInput with Select in left section incorrect arrow position

### ISSUE THREAD

**Issue by Tsyklop** [mantinedev/mantine#6418]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Select's arrow has the wrong place. It must be on the right side - but it is on the left. I've investigated and seen that `--section-start` style inherited from `NumberInput` - is incorrect. I disabled this style prop - all fine.
If I use just Select - all fine.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-numberinput-with-select-fs9h4n?file=%2Fsrc%2FApp.tsx%3A2%2C35

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://codesandbox.io/p/sandbox/mantine-react-template-forked-jq9jls?file=%2Fsrc%2FApp.tsx
