### ISSUE TITLE
TagsInput within a form only updates the `dirty` state after the second tag is inputed.

### ISSUE THREAD

**Issue by sosafe-uliana** [mantinedev/mantine#6431]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I am using a `TagsInput` inside a form, and I have noticed that it only updates the `dirty` state of the form after I add the second tag. You can see this reproduced in a codesandbox. 

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-8c6smp?file=%2Fsrc%2FApp.tsx%3A19%2C11

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rajivchaulagain** [comment]
@sosafe-uliana, The implementation of form.isDirty() is not suitable, which is causing the problem. Instead, you can directly use the form.isDirty() state without defining a separate state, as shown in the example below. This approach ensures that the form accurately reflects its dirty state when any input is modified.

```
import "@mantine/core/styles.css";
import { TagsInput, Button, Text } from "@mantine/core";
import { useForm } from "@mantine/form";
import { useState } from "react";

export function Welcome() {
  const form = useForm({
    initialValues: {
      names: [],
    },
  });

  const [enableSubmit, setEnableSubmit] = useState<boolean>(false);

  console.log({ isDirty: form.isDirty() });

  return (
    <>
      <form
        onSubmit={form.onSubmit(console.log)}
        onChange={() => setEnableSubmit(form.isDirty())}
      >
        <TagsInput {...form.getInputProps("names")} label="Add names" />
        <Text>Form is {form.isDirty() ? "dirty" : "clean"}</Text>
        <Button type="submit">Submit</Button>
      </form>
    </>
  );

```}

**Comment by sosafe-uliana** [comment]
@rajivchaulagain you are right!
I will be opening another issue, because I discovered that the `dirty` state is broken in `v7.11.0`, but works in `v7.7.1`

**Comment by sosafe-uliana** [comment]
Closing because it seems that the issue is different:
https://github.com/mantinedev/mantine/issues/6462
