### ISSUE TITLE
useIntervall - a missing dependency: 'interval' Typescript Error

### ISSUE THREAD

**Issue by bennik88** [mantinedev/mantine#6436]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.2

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

**Problem:**
Using `useInterval` like in your [example](https://mantine.dev/hooks/use-interval/) causes a Typescript Error.

```js
 const interval = useInterval(() => setSeconds((s) => s + 1), 1000);

  useEffect(() => {
    interval.start();
    return interval.stop;
  }, []); // Here will be the Error of the missing dependency
```

**Error Code:**
`React Hook useEffect has a missing dependency: 'interval'. Either include it or remove the dependency array.eslint[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)`

**What I've tried:**
I tried adding it to the dependency array but for obvious reasons, this would cause an infinite loop.
Other than that I thought of wrapping it in `useCallback` but I'm unsure if that would work and be a good practice.

**Expected:**
No typescript Error.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is not a TypeScript error. The error comes from ESLint rule. To fix the issue, disable that rule.

**Comment by bennik88** [comment]
So is it safe to ignore this linting rule? Is this the linter not fully able to correctly understand the hook?

**Comment by rtivital** [comment]
yes, it is the case
