### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by engin-can** [mantinedev/mantine#6439]
### Link to the page where something is not right

https://mantine.dev/core/password-input/#strength-meter-example

### What is wrong?

I'm getting `Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.` on the following example.
It happens because there is a `Box` within `Text` component without `component="div"`.
```
function PasswordRequirement({ meets, label }: { meets: boolean; label: string }) {
  return (
    <Text
      c={meets ? 'teal' : 'red'}
      style={{ display: 'flex', alignItems: 'center' }}
      mt={7}
      size="sm"
    >
      {meets ? (
        <IconCheck style={{ width: rem(14), height: rem(14) }} />
      ) : (
        <IconX style={{ width: rem(14), height: rem(14) }} />
      )}{' '}
      <Box ml={10}>{label}</Box>
    </Text>
  );
}
```

### Self-service

- [x ] I would be willing to implement a fix for this issue

**Fix**

```
function PasswordRequirement({ meets, label }: PasswordRequirementProps) {
  return (
    <Text
      component="div"
      c={meets ? 'teal' : 'red'}
      style={{ display: 'flex', alignItems: 'center' }}
      mt={7}
      size="sm"
    >
      {meets ? (
        <IconCheck style={{ width: rem(14), height: rem(14) }} />
      ) : (
        <IconX style={{ width: rem(14), height: rem(14) }} />
      )}{' '}
      <Box ml={10}>{label}</Box>
    </Text>
  );
}
```

**Comment by rtivital** [comment]
Text is `p` by default, it is intended behavior. If you do not need this, use `component="div"`.

**Comment by mrinmay7875** [comment]
Thanks for this! I encountered a similar issue today and was able to fix it using the information provided.
