### ISSUE TITLE
Missing Blockquote Type export

### ISSUE THREAD

**Issue by Chandher05** [mantinedev/mantine#644]
### What package has an issue

@mantine/core

### Describe the bug

Unable to get the props for Blockquote, so as to being able to extend it for our project. 

Missing BlockquoteProps export. 

### In which browser did the problem occur

NA

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Inserting the line in Blockquote.tsx 

`export type BlockquoteProps<C extends React.ElementType> = PolymorphicComponentProps<C, BlockquoteProps>;`

**Comment by rtivital** [comment]
@mantine/core package has `BlockquoteProps` export – https://codesandbox.io/s/modest-swartz-d5jsf?file=/src/App.tsx

**Comment by Chandher05** [comment]
I was looking for SharedHighlightprops. Thank you for the clarification so quickly.
