### ISSUE TITLE
Grid component has a weird margin

### ISSUE THREAD

**Issue by eakl** [mantinedev/mantine#645]
### What package has an issue

@mantine/core

### Describe the bug

Grid has a weird margin by default

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/nice-breeze-31dob?file=/src/App.js

### Do you know how to fix the issue

Yes

### Possible fix

Adding `style={{ margin: 0 }}` to `<Grid>`

**Comment by rtivital** [comment]
This margin is used to offset columns spacing and align grid content with the rest of the content. In your example, you are not using `Grid.Col` component and get unexpected negative margin. See alignment example – https://codesandbox.io/s/broken-resonance-j0o9n?file=/src/App.tsx
