### ISSUE TITLE
Mantine is loading dark theme for few ms before loading light theme

### ISSUE THREAD

**Issue by engin-can** [mantinedev/mantine#6452]
### Dependencies check up

- [x] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

I noticed my Mantine website renders the dark theme for a few ms before it renders the light theme, when I enable dark mode on MacOS. I tried setting ` forceColorScheme="light"` but it didn't make a difference. Any idea how I can fix that?

![CleanShot 2024-06-26 at 00 33 17](https://github.com/mantinedev/mantine/assets/2794116/8f7756ba-aea1-4d7b-bf96-b9ec17ee14dc)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You need to add ColorSchemeScript to your application – https://mantine.dev/theming/color-schemes/#force-color-scheme

**Comment by engin-can** [comment]
Yup, that fixed it, thanks a lot!
