### ISSUE TITLE
NavLink triggers onClick when pressing on Chevron (@tanstack/router integration)

### ISSUE THREAD

**Issue by jvllmr** [mantinedev/mantine#6455]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When creating a Link the recommended way in @tanstack/router with mantine's NavLink (allowing @tanstack/router's powerful type inference) , @tanstack/router passes an `onClick` to NavLink. This results in a navigation when clicking on the chevron.

### If possible, include a link to a codesandbox with a minimal reproduction

https://stackblitz.com/edit/tanstack-router-8h1e6e?file=src%2Fmain.tsx&preset=node

### Possible fix

Don't pass the onClick to the entire NavLink, but only to the Label. Maybe also provide an `chevronOnClick` prop. Unfortunately, this would a breaking change for Users.

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
If you want to disable propagation of click events, use `event.stopPropagation` – https://codesandbox.io/p/sandbox/mantine-react-template-forked-ttp2ff?file=%2Fsrc%2FApp.tsx%3A17%2C43
