### ISSUE TITLE
Popover not closing when clicked outside when used inside a modal

### ISSUE THREAD

**Issue by stijnvanderlaan** [mantinedev/mantine#646]
### What package has an issue

@mantine/core

### Describe the bug

When a Popover is used inside a modal, it is not closing when clicking outside the popover.

This used to work in version 3.4.1 but not anymore in 3.5.4.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/cranky-haibt-qj225?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by rtivital** [comment]
Fixed in 3.6.1

**Comment by 0papi** [comment]
please the popover closeOnClickOutside does not work..is the implementation different, could i get an example where this is working?

**Comment by Hmerac** [comment]
I found out that Popovers don't close when clicked outside, if SwiperJS is covering the screen.

Not sure what the solution would be, I tried:
`<Swiper preventClicks={false} preventClicksPropagation={false} touchStartPreventDefault={false}>`
No luck...
