### ISSUE TITLE
ActionIcon loading state applies :where([data-mantine-color-scheme='light']) class

### ISSUE THREAD

**Issue by isolde-a** [mantinedev/mantine#6460]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The loading state on the ActionIcon applies the class :where([data-mantine-color-scheme='light']) with the css background-color: rgba(255, 255, 255, 0.35); This affects the background color of non-white loading ActionIcons. This class/behavior is not seen in the Button loading state. It would help if the ActionIcon mirrored the Button component.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.11.1](https://github.com/mantinedev/mantine/releases/tag/7.11.1)
