### ISSUE TITLE
Mantine `form.isDirty()` seems to be broken in v7.10.0

### ISSUE THREAD

**Issue by sosafe-uliana** [mantinedev/mantine#6462]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

`form.isDirty()` is broken in 7.11.0, here is a codesandbox as proof:

Mantine version 7.7.1 **works**: https://codesandbox.io/p/sandbox/working-mantine-7-7-1-form-lnkgk7
Mantine version 7.11.0 **broken**: https://codesandbox.io/p/sandbox/mantine-react-taginput-issue-forked-76gfg6
Maneint version 7.10.0 **broken**: https://codesandbox.io/p/sandbox/mantine-react-taginput-issue-forked-mhzzqv

In my application I use 7.10.0 and it would be very hard to roll back to 7.7.1. I can't see any other reason why `isDirty` wouldn't work as expected here. Would really appreciate it if someone can double-check this.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by sosafe-yash-pandey** [comment]
I am also facing the same issue where `form.isDirty` works for a controlled form in the previous versions (`7.7.1` for example) but doesn't work as expected in the later versions.

Does anybody have an idea how we can approach this issue as the problem seems to appear in the later version of mantine?
Was there a breaking change somewhere which I am not aware about.

**Comment by rajivchaulagain** [comment]
@sosafe-uliana In the new build, they use uncontrolled mode with refs inside it, so the form does not re-render on every change. This is why form.isDirty() is always false during the onChange events of the fields. If you need the isDirty field to work correctly, you should switch from uncontrolled mode to controlled mode. Alternatively, you can manually update the state in useEffect, which will allow form.isDirty() to re-evaluate with every change.

**Comment by rajivchaulagain** [comment]
@sosafe-uliana @sosafe-yash-pandey you can also go through this docs below for detailed explanation.
https://mantine.dev/form/uncontrolled/#uncontrolled-mode

**Comment by sosafe-uliana** [comment]
@rajivchaulagain but then this bug https://github.com/mantinedev/mantine/issues/6431 and your reply there don't make sense to me

**Comment by rajivchaulagain** [comment]
@sosafe-uliana bug #6431 was working because there was no uncontrolled mode defined. By default, the form takes controlled mode, so the behavior was different. Here, you have defined the uncontrolled mode, which is causing the isDirty not to be rerender..

**Comment by rtivital** [comment]
`form.isDirty()` does not cause component to rerender. This feature might be added in future releases, but currently the function works as intended. If you want to keep the old behavior, use controlled mode instead.

**Comment by sosafe-uliana** [comment]
@rtivital thanks, it wasn't very clear from the documentation, to be honest.
