### ISSUE TITLE
Bug: bar graph always has 60 pixels reserved on the right by default

### ISSUE THREAD

**Issue by CurtisHumphrey** [mantinedev/mantine#6467]
Dependencies check up
 I have verified that I use latest version of all @mantine/* packages
What version of @mantine/* packages do you have in package.json?
7.11.0

What package has an issue?
@mantine/charts

What framework do you use?
Other, I will specify in the bug description

In which browsers you can reproduce the issue?
Chrome

Describe the bug
https://github.com/mantinedev/mantine/blame/0f66e8844c031878906b83ebf5bcf9d20c271254/packages/%40mantine/charts/src/BarChart/BarChart.tsx#L373

With this introduction even if no right y axis is used rechart reserves 60px of width making all bar charts narrower.

This is affecting both BarChart and LineChart

adding
```js
    <BarChart
         rightYAxisProps={{ width: 0 }}
         ...
```

restores the behavior for now but the right axis should only be added if it is used.

**Comment by rtivital** [comment]
Fixed in [7.11.1](https://github.com/mantinedev/mantine/releases/tag/7.11.1)
