### ISSUE TITLE
Combobox store property selectedOptionIndex does not change on click

### ISSUE THREAD

**Issue by mohammad-reza-rahbar** [mantinedev/mantine#6469]
### Dependencies check up

- [x] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

The value of the property `selectedOptionIndex` is always `-1` when I select an option by clicking on it, but it is correct when I select the option using keyboard with Enter key.  You can reproduce the bug by simply adding `console.log(combobox.selectedOptionIndex)`  to [this example](https://mantine.dev/combobox/?e=SelectActive).

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior to avoid rerenders, to get selected option index use `combobox.getSelectedOptionIndex()`

**Comment by mohammad-reza-rahbar** [comment]
When I use Enter, I get the updated index in the current render, but when I click on an option, I get the updated index in the next render, but I want the updated index in the current render.

**Comment by rtivital** [comment]
`combobox.getSelectedOptionIndex()` returns value of the ref, not state, it should be always up-to-date with the latest value.

**Comment by mohammad-reza-rahbar** [comment]
I am sorry, but still I cannot get the index using `combobox.getSelectedOptionIndex()` on click. It always returns `-1`. Here is the code:

```
import { useState } from "react";
import {
  CheckIcon,
  Combobox,
  Group,
  Input,
  InputBase,
  useCombobox,
} from "@mantine/core";

const groceries = [
  "🍎 Apples",
  "🍌 Bananas",
  "🥦 Broccoli",
  "🥕 Carrots",
  "🍫 Chocolate",
  "🍇 Grapes",
];

export function Component() {
  const combobox = useCombobox();
  const [value, setValue] = useState("🥦 Broccoli");

  console.log(combobox.getSelectedOptionIndex());

  const options = groceries.map((item) => (
    <Combobox.Option value={item} key={item} active={item === value}>
      <Group gap="xs">
        {item === value && <CheckIcon size={12} />}
        <span>{item}</span>
      </Group>
    </Combobox.Option>
  ));

  return (
    <Combobox
      store={combobox}
      resetSelectionOnOptionHover
      withinPortal={false}
      onOptionSubmit={(val) => {
        setValue(val);
        combobox.updateSelectedOptionIndex("active");
      }}
    >
      <Combobox.Target targetType="button">
        <InputBase
          component="button"
          type="button"
          pointer
          rightSection={<Combobox.Chevron />}
          rightSectionPointerEvents="none"
          onClick={() => combobox.toggleDropdown()}
        >
          {value || <Input.Placeholder>Pick value</Input.Placeholder>}
        </InputBase>
      </Combobox.Target>

      <Combobox.Dropdown>
        <Combobox.Options>{options}</Combobox.Options>
      </Combobox.Dropdown>
    </Combobox>
  );
}
```

**Comment by rtivital** [comment]
The function returns value of the ref object, it does not trigger rerenders by itself. It is intended to be used in event handlers or effects. Calling it during the render will always produce the same results.
