### ISSUE TITLE
DatePickerInput: React does not recognize the `highlightToday` prop on a DOM element.

### ISSUE THREAD

**Issue by Rllyyy** [mantinedev/mantine#6471]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.0

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Adding `highlightToday` prop to `DatePickerInput` gives the following warning in the console:

```
Warning: React does not recognize the `highlightToday` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `highlighttoday` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

`highlightToday` works fine with `Calendar` and `DatePicker`

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-qxjd7j

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.11.1](https://github.com/mantinedev/mantine/releases/tag/7.11.1)
