### ISSUE TITLE
use-form, NumberInput custom handle onChange inside func call form.setFieldValue(...) when keyin number cursor lost focus ?

### ISSUE THREAD

**Issue by azamak007** [mantinedev/mantine#6475]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Other, I will specify in the bug description

### Describe the bug

use-form, NumberInput custom handle onChange inside func call form.setFieldValue(...) when keyin number cursor lost focus ?

usecase Me want to set pricePoItem when qty change

func 1 Okay expected pricePoItem ✔️, but qty not change ❌
const handleQtyChange = (index: number, poItem: any, value: any) => {
    const tempPricePoItem = +(poItem.price * value).toFixed(2)
    form.setFieldValue(`purchaseItems.${index}.pricePoItem`, tempPricePoItem);
  };
  
  func 2 Okay expected pricePoItem ✔️, qty ✔️, but can not continue keyin ❌
const handleQtyChange = (index: number, poItem: any, value: any) => {
    form.setFieldValue(`purchaseItems.${index}.qty`, Number(value));
    const tempPricePoItem = +(poItem.price * value).toFixed(2)
    form.setFieldValue(`purchaseItems.${index}.pricePoItem`, tempPricePoItem);
  };
  
 How to solution? thankyou

ps. my English not good 
![Screenshot 2024-06-29 185054](https://github.com/mantinedev/mantine/assets/159739783/9deccfef-d28a-444b-aa79-d708f1b4fe1c)
![Screenshot 2024-06-29 185116](https://github.com/mantinedev/mantine/assets/159739783/613ff0d8-3310-4da0-9b72-c1ed1e5ca294)
![Screenshot 2024-06-29 185134](https://github.com/mantinedev/mantine/assets/159739783/0b2835b1-963f-4844-881b-6d2d00021a93)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by azamak007** [comment]
Maybe I think wrong purpose logic

Now, Me use solution

![image](https://github.com/mantinedev/mantine/assets/159739783/f713c9fe-98bb-4051-aa98-f262b83972be)

**Comment by rtivital** [comment]
Is your issue resolved?

**Comment by rtivital** [comment]
You are welcome to reopen an issue if it is not resolved
