### ISSUE TITLE
Support for defaultProps will be removed from function components in a future major release.

### ISSUE THREAD

**Issue by nileshmali** [mantinedev/mantine#6478]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.0

### What package has an issue?

@mantine/charts

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug
Below warning flashed on browser console for while using Chart components:

`Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Issue with recharts, not Mantine. See https://github.com/recharts/recharts/issues/3615
