### ISSUE TITLE
DateTimePicker won't change months and time when inside a Menu.Dropdown

### ISSUE THREAD

**Issue by phillinegistlens** [mantinedev/mantine#6480]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.3

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

`<Menu position="bottom-start" width={300}>
                  <Menu.Target>
                    <Button
                      variant="default"
                      leftSection={
                        <Text fw={800} size="sm">
                          {t('dataRange')}
                        </Text>
                      }
                      rightSection={<IconChevronDown size={15} />}
                    >
                      {range.ts.toLocaleDateString()} - {range.tf.toLocaleDateString()}
                    </Button>
                  </Menu.Target>
                  <Menu.Dropdown w={350}>
                    <Stack style={{ padding: 10 }}>
                      <DateProvider>
                        <Grid>
                          <Grid.Col span={6}>
                            <DateTimePicker
                              popoverProps={{ withinPortal: true, zIndex:10000  }} 
                              valueFormat="L LT"
                              value={range.ts}
                              onChange={(value) => value && setRange({ ts: value, tf: range.tf })}
                              label={t('dateStart')}
                            />
                          </Grid.Col>
                          <Grid.Col span={6}>
                            <DateTimePicker
                             popoverProps={{ withinPortal: true, zIndex:10000 }} 
                              valueFormat="L LT"
                              value={range.tf}
                              onChange={(value) => value && setRange({ ts: range.ts, tf: value })}
                              label={t('dateEnd')}
                            />
                          </Grid.Col>
                        </Grid>
                      </DateProvider>
                    </Stack>
                  </Menu.Dropdown>
                </Menu>`

I placed the DateTimePicker inside a menu dropdown. It will open, however, upon trying to click the arrows to change the months or clicking the input for time will just close the dropdown and wont do any change.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
DateTimePicker component cannot be used inside Menu.Dropdown component. If you need this functionality, use Popover component instead.
