### ISSUE TITLE
Controlled NumberInput doesn't clear input when value is set to undefined

### ISSUE THREAD

**Issue by amlehman** [mantinedev/mantine#6483]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

When using the NumberInput component with a controlled value, entering a value and then setting the value to undefined, the value displayed in the input is sometimes not getting cleared and displaying the placeholder. It's instead displaying some odd values. For example, if I enter 600 and then set the value prop to undefined, the input is displaying 6. 

![2024-07-02 14 13 56](https://github.com/mantinedev/mantine/assets/4624053/96308422-8d1d-47f4-ae53-42610e547e5f)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-q8zl3w

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior. `undefined` is not a valid controlled input value. To reset controlled NumberInput, set `value` to an empty string.
