### ISSUE TITLE
FileUpload does not invoke onChange within Menu.Item within Menu.Dropdown 

### ISSUE THREAD

**Issue by aeftimia** [mantinedev/mantine#6484]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.2

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

`<FileUpload>` fails to invoke `onChange` within a `<Menu.Item>` within a `<Menu.Dropdown>`. I've tried combining the `<FileUpload>` and `<Menu.Item>` like this
```
<FileButton>
{(props) => <Menu.Item {...props} ...>...</Menu.Item>
</FileButton>
```

I've also found just surrounding a working `<FileButton>` with a `<Menu.Item>` prevents it from invoking `onChange`. e.g.

```
<Menu.Item>
<FileButton>...</FileButton>
</Menu.Item>
```
I've found this happens if and only if the `<Menu.Item>` is contained within a `<Menu.Dropdown>`.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-jjgmqx?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly54b8wu00063b6m1ex87am5%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly54b8wu00023b6mfpljohez%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly54b8wu00033b6mnowx3a4u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly54b8wu00053b6mi6mbu5dx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly54b8wu00023b6mfpljohez%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly54b8wt00013b6m133d61th%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cly54d48m00353b6mlmk1yx9j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cly54b8wu00023b6mfpljohez%2522%252C%2522activeTabId%2522%253A%2522cly54d48m00353b6mlmk1yx9j%2522%257D%252C%2522cly54b8wu00053b6mi6mbu5dx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly54b8wu00043b6myz9hmzr7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cly54b8wu00053b6mi6mbu5dx%2522%252C%2522activeTabId%2522%253A%2522cly54b8wu00043b6myz9hmzr7%2522%257D%252C%2522cly54b8wu00033b6mnowx3a4u%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cly54b8wu00033b6mnowx3a4u%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A15%257D

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Set `closeOnItemClick={false}` on the Menu component.
