### ISSUE TITLE
[Feature Request] Adding a tooltip icon to TextInput label

### ISSUE THREAD

**Issue by eakl** [mantinedev/mantine#649]
### Usage example, including component/hook API

For complex form, it may be useful to have an icon on the input label that display a tooltip on hover.

### Possible implementation – describe how the feature can be implemented

Adding 2 props to TextInput. One for the tooltip icon and one for the text.

**Comment by eakl** [comment]
Thanks for the solution. However, adding a `required={true}` props to the TextInput disturb how the Component looks like

**Comment by jerebtw** [comment]
Just add `display: "inline"` to the `div` like so: https://codesandbox.io/s/strange-fire-to1pg?file=/src/App.tsx

**Comment by eakl** [comment]
Thank you @jerebtw. Shouldn't the asterisk appear right after the label  followed by the icon. It looks more standard to me.

**Comment by jerebtw** [comment]
If you want the asterisk right after the label you can create your own asterisk like so: https://codesandbox.io/s/hungry-tess-6qhk3
