### ISSUE TITLE
MultiSelect label problem

### ISSUE THREAD

**Issue by engin-can** [mantinedev/mantine#6494]
### Discussed in https://github.com/orgs/mantinedev/discussions/6493

<div type='discussions-op-text'>

<sup>Originally posted by **engin-can** July  5, 2024</sup>
I was wondering how I can use `MultiSelect` with `product.id` as `value` and `{product.name} ({product.company})` as `label`.
When I select an item from the list, it changes selected option to `product.id` instead of label:
![CleanShot 2024-07-05 at 18 34 14](https://github.com/mantinedev/mantine/assets/2794116/3d56a731-97c3-44fe-b707-21d3859d5c6b)
```  
  const [data, setData] = useState<Product[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [searchValue, setSearchValue] = useState('');
  const [debouncedSearch] = useDebouncedValue(searchValue, 300);

  useEffect(() => {
    const fetchOptions = async () => {
      if (debouncedSearch) {
        setIsLoading(true);
        try {
          const response = await axios.get(
            `/api/products/?q=${encodeURIComponent(debouncedSearch)}`
          );
          setData(response.data);
        } catch (error) {
          console.error('Error fetching products:', error);
        } finally {
          setIsLoading(false);
        }
      } else {
        setData([]);
      }
    };

    fetchOptions();
  }, [debouncedSearch]);

  return (
    <MultiSelect
      data={data.map((product) => ({
        value: product.id,
        label: `${product.name} - ${product.company}`,
      }))}
      label="Products"
      placeholder="Type to search for products..."
      searchValue={searchValue}
      onSearchChange={setSearchValue}
      nothingFoundMessage="No products found"
      rightSection={isLoading ? <Loader size="1rem" /> : null}
      searchable
      clearable
    />
  );
};
```

+-- @mantine/core@7.11.1
+-- @mantine/form@7.11.1
+-- @mantine/hooks@7.11.1
+-- @mantine/notifications@7.11.1
+-- @mantine/spotlight@7.11.1
</div>

**Comment by Prasiddha22** [comment]
This is happening because the pills label are rendered as `{optionsLockup[item]?.label || item}`. It is searching for the option in the option list with the selected value and displaying its label. As a fallback it is displaying the value itself. The options provided in the provided example is derived from the **data** . When API request is being made, it is affecting the data and that is affecting the options provided to the MultiSelect. So when the **data** is empty or does not contains the data for the previously selected value, the derived options from the data is reflected the same way and MultiSelect does not find the option with the value and in fallback it shows the value as the label.

You can work around this by making your component controlled and managing separate state for the options. I have updated your code in such as way to achieve the desired result.
`
  const [data, setData] = useState<Product[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [searchValue, setSearchValue] = useState('');
  const [debouncedSearch] = useDebouncedValue(searchValue, 300);
  const [values, setValues] = useState<string[]>([])

  const composeOption = (items) => {
    const tempData = [...data];
    items.forEach((product) => {
      if (!(data.find(item => item.value === product.id))) {
        tempData.push({
        value: product.id,
        label: `${product.name} - ${product.company}`,
      })
      }
    });
    setData(tempData)
  }

  const removeUnusedOptions = () => {
    setData((prev) => prev.filter(item => values.includes(item.value)))
  }

  useEffect(() => {
    const fetchOptions = async () => {
      if (debouncedSearch) {
        removeUnusedOptions()
        setIsLoading(true);
        try {
          const response = await axios.get(
            `/api/products/?q=${encodeURIComponent(debouncedSearch)}`
          );
          setData(response.data);
        } catch (error) {
          console.error('Error fetching products:', error);
        } finally {
          setIsLoading(false);
        }
      }
    };

    fetchOptions();
  }, [debouncedSearch]);

  return (
    <MultiSelect
      value={values}
      onChange={setValues}
      data={data}
      label="Products"
      placeholder="Type to search for products..."
      searchValue={searchValue}
      onSearchChange={setSearchValue}
      nothingFoundMessage="No products found"
      rightSection={isLoading ? <Loader size="1rem" /> : null}
      searchable
      clearable
    />
  );
};
`
BTW @rtivital we might need to figure out the proper handling of async options for autocomplete/multiselect

**Comment by engin-can** [comment]
How should I use `composeOption`?

**Comment by Prasiddha22** [comment]
Sorry my mistake. I have updated the code in previous comment.

```
useEffect(() => {
   const fetchOptions = async () => {
     if (debouncedSearch) {
       removeUnusedOptions()
       setIsLoading(true);
       try {
         const response = await axios.get(
           `/api/products/?q=${encodeURIComponent(debouncedSearch)}`
         );
         composeOption(response.data);
       } catch (error) {
         console.error('Error fetching products:', error);
       } finally {
         setIsLoading(false);
       }
     }
   };
   fetchOptions();
 }, [debouncedSearch]);
```

**Comment by engin-can** [comment]
Sharing my code in case it helps other people:

```
import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { Loader, MultiSelect } from '@mantine/core';
import axios from 'axios';
import useSWR from 'swr';
import { useDebouncedValue } from '@mantine/hooks';

interface Product {
  id: string;
  name: string;
  description: string;
  company: string;
}

interface ProductSelectProps {
  onSelect: (selectedIds: string[]) => void;
}

const fetcher = (url: string) => axios.get(url).then((res) => res.data);

const ProductSelect = ({ onSelect, ...props }: ProductSelectProps) => {
  const [data, setData] = useState<Product[]>([]);
  const [values, setValues] = useState<string[]>([]);
  const [searchValue, setSearchValue] = useState('');
  const [debouncedSearch] = useDebouncedValue(searchValue, 300);

  const {
    data: products,
    error,
    isValidating,
  } = useSWR(
    debouncedSearch ? `/api/products/?q=${encodeURIComponent(debouncedSearch)}` : null,
    fetcher
  );

  const composeOption = useCallback((items: Product[]) => {
    setData((prevData) => {
      const newItems = items.filter(
        (item) => !prevData.some((existingItem) => existingItem.id === item.id)
      );
      return [...prevData, ...newItems];
    });
  }, []);

  const removeUnusedOptions = useCallback(() => {
    setData((prevData) => prevData.filter((item) => values.includes(item.id)));
  }, [values]);

  const formatDataForDropdown = useMemo(
    () =>
      data.map((product) => ({
        value: product.id,
        label: `${product.name} - ${product.company}`,
      })),
    [data]
  );

  useEffect(() => {
    if (products) {
      removeUnusedOptions();
      composeOption(products);
    }
  }, [products, removeUnusedOptions, composeOption]);

  useEffect(() => {
    onSelect(values);
  }, [values, onSelect]);

  return (
    <MultiSelect
      data={formatDataForDropdown}
      value={values}
      onChange={setValues}
      label="Products"
      placeholder="Type to search for products..."
      searchValue={searchValue}
      onSearchChange={setSearchValue}
      rightSection={isValidating ? <Loader size="1rem" /> : null}
      checkIconPosition="right"
      searchable
      clearable
      error={error ? 'Error fetching products' : undefined}
      {...props}
    />
  );
};

export default ProductSelect;
```

**Comment by rtivital** [comment]
This behavior is intended
