### ISSUE TITLE
Missing the "variant" on Button props list

### ISSUE THREAD

**Issue by g5l** [mantinedev/mantine#6503]
### Link to the page where something is not right

https://mantine.dev/core/button/?t=props

### What is wrong?

It's missing the `variant` prop on the Button props list

![image](https://github.com/mantinedev/mantine/assets/20099133/7887719c-797c-4532-9245-5ee653d08de9)

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended. Shared props are not listed in the props table to avoid displaying 50-60 additional props per component.

**Comment by g5l** [comment]
How can I find the shared props?

**Comment by rtivital** [comment]
In the documentation examples

**Comment by g5l** [comment]
Isn't it a bad DX that the documentation is only in the examples? Wouldn't it be a good idea to create a separate list for shared props?

**Comment by olsonpm** [comment]
I got here looking for the list of available variants.  Is there a list documented or are we expected to look at the code ?
