### ISSUE TITLE
Warning: React does not recognize the `strokeColor` prop on a DOM element. 

### ISSUE THREAD

**Issue by dimosmera** [mantinedev/mantine#6507]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.1

### What package has an issue?

@mantine/charts

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Adding a `strokeColor` to a `DonutChart` produces the following warning

```
Warning: React does not recognize the `strokeColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `strokecolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-hjs9sp?file=%2Fsrc%2FApp.tsx

### Possible fix

Is it as simple as lowercasing to `strokecolor` before passing it to the DOM? I haven't checked

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.11.2](https://github.com/mantinedev/mantine/releases/tag/7.11.2)
