### ISSUE TITLE
ActionIcon error in Nextjs

### ISSUE THREAD

**Issue by mnakhli** [mantinedev/mantine#6519]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

Latest

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The errors you see in the image occur when using this component. It only happens in Next.js! That means I don't have this issue in Storybook.
These errors do not affect the component's functionality and are only present in the console.

![telegram-cloud-photo-size-1-4938527120234229114-y](https://github.com/user-attachments/assets/9dcd4de7-475d-4c91-b8c0-007daf6daad0)

![telegram-cloud-photo-size-1-4938527120234229115-y](https://github.com/user-attachments/assets/8362b5a5-f8c4-4cc2-a885-1a9178c706a4)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Provide a sandbox with a minimal reproduction

**Comment by mnakhli** [comment]
I checked again and noticed that when I use ActionIcon within an UnstyledButton, it throws an error.
However, if I set the UnstyledButton to a component and use anything other than "a" or "button", it works correctly. For example:
`<UnstyledButton component="div">
<ActionIcon></ActionIcon>
</UnstyledButton>
`

**Comment by rtivital** [comment]
https://stackoverflow.com/questions/39386497/can-i-nest-button-inside-another-button
