### ISSUE TITLE
[@mantine/dates] DatePicker allows valid free input of dates beyond `maxDate`

### ISSUE THREAD

**Issue by LucasLemanowicz** [mantinedev/mantine#652]
### What package has an issue

@mantine/dates

### Describe the bug

The `DatePicker` (and presumably other date components) allow free input selection dates beyond `maxDate`.

I would expect that inputs after `maxDate` and before `minDate` would either be rejected and the field value would remain what it was before the change, or the value would be clamped at min/maxDate.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/patient-star-jhsgh?file=/src/App.tsx

**Comment by rtivital** [comment]
Thanks for reporting, I think clamping the value onBlur is the best option because it will be disruptive to clamp the value when the user types in the value, although the onChange event is called with each valid date.

**Comment by rtivital** [comment]
Fixed, will be released with next minor

**Comment by rtivital** [comment]
Released in 3.6.0
