### ISSUE TITLE
"React does not recognize the `lineSize` prop on a DOM element" error in Burger component

### ISSUE THREAD

**Issue by mnakhli** [mantinedev/mantine#6520]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

Latest

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When using the lineSize prop for the Burger component, this error is displayed in the console.

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/00b68115-1455-4dd3-851f-42af63cc52cd">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.11.2](https://github.com/mantinedev/mantine/releases/tag/7.11.2)
