### ISSUE TITLE
Vite + Mantine + Vanilla Extract + tRPC Client + React Query + ESLint + CSpell + Commitlint + Lefthook + Yarn Workspaces

### ISSUE THREAD

**Issue by sotnikov-link** [mantinedev/mantine#6522]
### Link to the repository on GitHub

https://github.com/sotnikov-link/yarn-workspaces-eslint-cspell-commitlint-lefthook-template/tree/main/packages/vite-mantine-ve

### Features of the template, describe how it is different from other templates

The template with minimal configs and with useful well-known tools for a quick start

**Comment by rtivital** [comment]
Thanks for submitting the template! Unfortunately, it cannot be added to the documentation as it is not different enough from other templates.
