### ISSUE TITLE
SegmentedControl displays incorrect value after opening or collapsing AppShell Navbar

### ISSUE THREAD

**Issue by yorkeJohn** [mantinedev/mantine#6527]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

When a non-default option is selected in `SegmentedControl`, the incorrect value is **displayed** in SegmentedControl when the collapsed state of `AppShell.Navbar` changes. The actual state does not change, just the rendered value.

Steps to reproduce
1. See the attached CodeSandbox
2. Select 'Option 2' in the `SegmentedControl`
3. Open the `AppShell.Navbar` using the burger icon
4. Observe that the incorrect value is displayed

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-lg4dq7

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by ayovev** [comment]
Confirmed that this is also happening in my application and the Code Sandbox demonstrates the issue well 👍

**Comment by michaelperros** [comment]
I'd like to work on this issue.

The problem seems to be related to [this line of code](https://github.com/mantinedev/mantine/blob/c087030bbc67a895cb39475b0494ed5a6dc5e7ab/packages/%40mantine/core/src/components/FloatingIndicator/use-floating-indicator.ts#L106).

The opening of the AppShell Navbar changes the parent, which triggers the useEffect, which in turn calls the `updatePositionWithoutAnimation()` and causes the bug.

**Comment by rtivital** [comment]
You are welcome to send a pr

**Comment by michaelperros** [comment]
Please see #6622

**Comment by ayovev** [comment]
@michaelperros Thank you for putting that PR together! I was just in the middle of butting heads with this bug in my app and was about to dig in. If @rtivital is happy with it, it would be great to get this fix into the next minor/patch release 🙂
