### ISSUE TITLE
Graphs with nested values ignore "label" property

### ISSUE THREAD

**Issue by JonathanG-DC** [mantinedev/mantine#6529]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/charts

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Graphs that are using nested values now ignore the "label" property for tooltips and legends and instead use the last part of the "name" property.
Image from 7.11.1:
![image](https://github.com/user-attachments/assets/10a556f7-c854-4ff7-858e-e7de673d6709)

Image from 7.11.2:
![image](https://github.com/user-attachments/assets/99641f63-79a1-4a03-b880-6f488023143f)

The included code sandbox shows the issue and can be fixed by reverting the version of all mantine packages to 7.11.1.

I believe this is related to #5885 and its associated PR #5886.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-cxqmf8

### Possible fix

The following files had new functions added as part of the mentioned PR:
packages/@mantine/charts/src/ChartLegend/ChartLegend.tsx  updateChartTooltipPayload
packages/@mantine/charts/src/ChartTooltip/ChartTooltip.tsx  updateChartLegendPayload

These override the name with the nested property name, I assume these should instead be using label property with the fallback being the nested property name.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Sergio16T** [comment]
Beginning work on fix for this issue.

**Comment by JonathanG-DC** [comment]
Happy to raise this as a new issue if need be, but unfortunately this fix (using all 7.12.1 packages) doesn't work if nested values are more than one level deep.
See example here:
https://codesandbox.io/p/sandbox/mantine-react-template-forked-cxqmf8

![image](https://github.com/user-attachments/assets/bfc8bb89-bff0-4337-8d9c-3b0a1d58f6ac)


The AppleLabel is not displayed in the legend and the value is not shown in the tooltip.

**Comment by Sergio16T** [comment]
Hi @JonathanG-DC, I did not know there was a need to support multiple levels in original ask. Is this a common use-case with Line Chat Graph's? If so we would need to do additional dev work to support this.

**Comment by JonathanG-DC** [comment]
Hi @Sergio16T all good, I do appreciate your work in the initial issue.
My goal with this request was to get feature parity with 7.11.1 which supports multiple levels of nesting on all graphs.
The graph itself seems to be fine regardless of version and nesting level, this is just a issue with the Tooltip and Legend.

**Comment by Sergio16T** [comment]
Hi @JonathanG-DC, Thank you for providing more information about the original feature request. 

I can create a subsequent PR to address this feature request to attain feature parity with 7.11.1 to enable multi-level nesting of graph data for the Tooltip and Legend. 

We can re-open this issue.

FYI @rtivital

**Comment by rtivital** [comment]
If you want to submit a PR for this, I do not mind adding this feature

**Comment by JonathanG-DC** [comment]
@Sergio16T I've found another issue with the fix unfortunately.
If you have the same nested prop name the last ones label is used for all of them.
This occurs even when sticking within the existing single level of nesting.

![image](https://github.com/user-attachments/assets/24881f20-6570-4234-94d3-e9a156b95308)
![image](https://github.com/user-attachments/assets/9fd1a47e-1d0a-480e-b7fc-30c72a4bdf8b)

https://codesandbox.io/p/sandbox/mantine-react-template-forked-cxqmf8?file=%2Fsrc%2Fdata.ts%3A5%2C12

**Comment by Sergio16T** [comment]
@JonathanG-DC great QA. Appreciate the steps to replicate and details. I haven't had bandwidth to begin work on a fix. I plan to begin work on this in the near future.
