### ISSUE TITLE
[@mantine/core] Select component doesn't pre-scroll to selected value when `searchable={true}`

### ISSUE THREAD

**Issue by LucasLemanowicz** [mantinedev/mantine#653]
### What package has an issue

@mantine/core

### Describe the bug

Discussed on Discord last week. When an item below the scroll view is selected and you re-open the dropdown, the Select component doesn't pre-scroll to the selection.

https://user-images.githubusercontent.com/361348/149216275-e660cb0b-c591-416c-b26e-30dae68a2d1d.mov

https://codesandbox.io/s/gifted-buck-neeeq?file=/src/App.tsx

Repro:
1. Create a `Select` component with `searchable={true}` and more items than are visible in the scroll view
2. Select an item below the scroll view
3. Close the dropdown, and then reopen it

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/gifted-buck-neeeq?file=/src/App.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
This logic should not be located in input `onClick` handler – dropdown can also be opened with focus event, see video when Select is focused dropdown does not scroll to selected element

https://user-images.githubusercontent.com/10353856/149546997-75313403-0b19-412f-bd18-6276c7f9f5b7.mov

**Comment by jerebtw** [comment]
So should that logic be called from onClick and onFocus?
