### ISSUE TITLE
Switch size changes with the length of Label/Description

### ISSUE THREAD

**Issue by humpalum** [mantinedev/mantine#6531]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The Switch from the <Switch />  component reduces in size when the width is limited by a parent and the label or description is to large.
![image](https://github.com/user-attachments/assets/120b57fb-634b-4f22-aeef-39ec6fd12c03)

Bugged with
- Chrome
- Firefox

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-c593ff

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.12.1](https://github.com/mantinedev/mantine/releases/tag/7.12.1)
