### ISSUE TITLE
Bugs on Select & MultiSelect when using ComboData with Label & Value

### ISSUE THREAD

**Issue by josh-i386g** [mantinedev/mantine#6552]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

![image](https://github.com/user-attachments/assets/40658c8e-873c-4dfa-b744-45aa18a99099)

#### Code

```ts

  const [org, setOrg] = useState<string>("");
  const orgs = useItems("public", "organizations", org, true); // returns ComboboxData

  const [org2, setOrg2] = useState<string>("");
  const orgs2 = useItems("public", "organizations", org2, true); // returns ComboboxData

  const form = useForm<FormValues>({
    mode: "uncontrolled",
    initialValues: {
      organization: null,
      organizations: [],
    },
  });

<Select
  {...form.getInputProps("organization")}
  key={form.key("organization")}
  label="Organization"
  data={orgs || undefined}
  limit={10}
  searchable
  clearable
  onSearchChange={setOrg}
/>

<MultiSelect
  {...form.getInputProps("organizations")}
  key={form.key("organizations")}
  label="Organizations"
  data={orgs2 || undefined}
  limit={10}
  searchable
  clearable
  onSearchChange={setOrg2}
/>
```

#### Overview

- We listen to `onSearchChange` event.
- On search value change, we call an async function which updates data with array of `{ label: string, value: string }`
- Those values are displayed correctly at the dropdowns.

#### Select

- When I select an item, then I click outside the input, the label disappears.
- If I click inside input and click outside again, the label reappears.
- Doing it again and again cycles that reappear disappear.

#### MultiSelect

- When I select items from dropdown unfiltered items, they're okay. When I select items from filtered items, they display value instead of label.

#### What works

- If values are `string[]` everything is working as expected.
- If values are `{ label: string, value: string }` that's when these bugs appear.
- when I click submit, the useForm picks up the correct `value` of the selected items.

I will add a codesandbox reproduction shortly.

Thank you.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-g9zjwd

### Possible fix

No idea yet.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by josh-i386g** [comment]
Added codesandbox repro here: https://codesandbox.io/p/sandbox/mantine-react-template-forked-g9zjwd

**Comment by rtivital** [comment]
It is intended behavior, Select and MultiSelect components use `data` as a source to retrieve labels. If the label cannot be retrieved from the `data` array, then it is either displayed as a value itself or just ignored.

To fix this, make sure that your data array always includes items for selected values.
This logic is not planned to be changed on Mantine side.

**Comment by josh-i386g** [comment]
That worked!!!

When the input loses focus, `onSearchChange` is called with `value` equal to empty string. The fix I did in my code was to ensure the `data` only gets updated when the search value is a non-empty string, which results to it being able to find the item with correct value and label.

Thank you very much. Thank you, thank you, thank you!
