### ISSUE TITLE
DateTimePicker relies on deprecated element.ref

### ISSUE THREAD

**Issue by Punie** [mantinedev/mantine#6555]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I'm getting the following error when using the `DateTimePicker` from `@mantine/dates` with React 19. Very likely similar to #6492 

```
Warning: Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.

  <@mantine/dates/DateTimePicker> (async)
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I cannot reproduce the issue, most likely it has been resolved in the previous patches. Make sure that you have the latest version of all `@mantine/*` packages in your project.
