### ISSUE TITLE
Range thumb going to opposite direction on RTL

### ISSUE THREAD

**Issue by patrickchek** [mantinedev/mantine#6558]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

Slider thumb going to the opposite direction on dragging.
Video attached for better explanation.

https://github.com/user-attachments/assets/e4337c17-f94e-4c08-809e-9e09ee975277

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-994w99

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This happens because you do not have dir attribute – https://codesandbox.io/p/sandbox/mantine-react-template-forked-882p8w?file=%2Fpublic%2Findex.html%3A2%2C25

To learn more about rtl, see – https://mantine.dev/styles/rtl/
