### ISSUE TITLE
Wrong notification position in rtl mode

### ISSUE THREAD

**Issue by alimehasin** [mantinedev/mantine#6563]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/notifications

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

In LTR (default) mode the `showNotification` shows the notification from the bottom right by default, but when using LTR mode, the `showNotification` shows the notification from the same exact position which is not expected behavior, I did expect it to show from the `left-bottom` since the import bits (sidebar) in RTL now lives in the right section

### Possible fix

Dynamically calculate the `position` based on current dir

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It works correctly, if you set position to `right`, notifications are displayed on the right. You need to implement this logic on your side – it is not planned to be implemented as part of the library.
