### ISSUE TITLE
Property 'withProps' does not exist on type 'typeof Accordion'.

### ISSUE THREAD

**Issue by bradstdev** [mantinedev/mantine#6564]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Accordion seems to be missing the `withProps` function. According to the [changelog](https://mantine.dev/changelog/7-11-0/#withprops-function), all components should have the `withProps` function.

![image](https://github.com/user-attachments/assets/049009d3-d741-4139-b148-0538fb5ac30f)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by MKraust** [comment]
Same for `Box` component. Also using `7.11.2`.

**Comment by rtivital** [comment]
Fixed in [7.12.1](https://github.com/mantinedev/mantine/releases/tag/7.12.1)
