### ISSUE TITLE
Pill's remove icon is missing a border radius

### ISSUE THREAD

**Issue by HarleySalas** [mantinedev/mantine#6565]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Particularly inside of a multi-select, the "x" icon that is for removing an item overflows the pill.
![image](https://github.com/user-attachments/assets/6a990c89-d710-48fd-9512-523e7ea7838e)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.12.1](https://github.com/mantinedev/mantine/releases/tag/7.12.1)
