### ISSUE TITLE
Tooltip.Group is missing the theme extend function

### ISSUE THREAD

**Issue by kirankunigiri** [mantinedev/mantine#6576]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

`Tooltip.Group` is missing the `extend` function used to customize the Mantine theme. I initially thought that extending wasn't supposed to work for groups, until I noticed that the `Radio.Group` component does have an `extend` function, so it looks like the `Tooltip.Group` implementation may have just been missed.

A common use case example for implementing `extend` for `Tooltip.Group` is to set default props like `openDelay` and `closeDelay` for all groups, since `Tooltip.Group` will override the default delay used by a child `Tooltip` component.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.12.1](https://github.com/mantinedev/mantine/releases/tag/7.12.1)
