### ISSUE TITLE
having a different size of Area chart on local host and live url

### ISSUE THREAD

**Issue by Sanmidaniels07** [mantinedev/mantine#6578]
### Link to the page where something is not right

https://develop.d2w4towgn1rge4.amplifyapp.com/expenses

### What is wrong?

i'm experiencing a different view of the area chart on my live url compared to what i have in the local host

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The url that you've provided does not have AreaChart

**Comment by rtivital** [comment]
The issue is closed because there is no reproduction.

**Comment by Sanmidaniels07** [comment]
> The url that you've provided does not have AreaChart

@rtivital check the insight option in the expense page, there you will see the Areachart

**Comment by Sanmidaniels07** [comment]
@rtivital here is the url: https://develop.d2w4towgn1rge4.amplifyapp.com/expenses
