### ISSUE TITLE
`autoContrast` does not work with dark/light `primaryShade`

### ISSUE THREAD

**Issue by gillesdandrea** [mantinedev/mantine#6589]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Hello,
I'm trying to build a theme with a different shade for light and dark and `autoContrast` does not work properly to adjust the color of text on buttons.
```JavaScript
export const theme = createTheme({
  white: '#ffffff',
  black: '#242424',
  primaryColor: 'blue',
  primaryShade: {
    dark: 9,
    light: 1,
  },
  autoContrast: true,
  luminanceThreshold: 0.3,
});
```
In dark and light mode, text is always black. I would expect a white text in dark mode.
Because if I change `primaryShade: 9` the text is white and with `primaryShade: 1`, text is black as expected.

For the record, the theme I would like to use is something like that:
```JavaScript
export const theme = createTheme({
  white: '#ffffff',
  black: '#242424',
  primaryColor: 'primary',
  primaryShade: {
    dark: 4,
    light: 7,
  },
  autoContrast: true,
  luminanceThreshold: 0.3,
  colors: {
    primary: virtualColor({
      name: 'primary',
      dark: 'yellow',
      light: 'blue',
    }),
  },
});
```

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-autocontrast-issue-8wyts4

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is not possible to fix, Mantine is not aware of what color scheme is used until the code is executed in the browser, it cannot be decided which color should be used. It is not planned to be changed any time soon.
