### ISSUE TITLE
Mantine select drop down gets marked with aria-hidden=true when using inside modal

### ISSUE THREAD

**Issue by rayworthe** [mantinedev/mantine#6591]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

I am trying to test my Select component (which is inside a Modal) using React Testing Library (following these instructions: https://help.mantine.dev/q/combobox-testing)

When trying to get the element with the `option` role, it isn't defined on the page.

It seems there is some kind of conflict between the Select and the Modal as when it's inside of the Modal, the Select gets the `aria-hidden` property and the React Testing Library can longer see it.

### Possible fix

I can seem to get around this issue by telling the Select to not use Portal (using the withinPortal prop) on the Combobox but this doesn't seem like the ideal solution since it leads to a worse UX. 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
To resolve the issue, set `comboboxProps={{ withinPortal: false }}` on the Select component. This way, the dropdown node will be inside the Modal. It is not planned to change aria hider logic.

**Comment by DennyJohansson** [comment]
I get the same issue with Playwright, the data-portal element has aria-hidden=true, but only when building our Nextjs app

```<div data-portal="true" data-focus-id="mantine-m2vwiaqpw" aria-hidden="true">```
