### ISSUE TITLE
How to improve Slider and use-move hook user experience for mobile?

### ISSUE THREAD

**Issue by sebastien-prudhomme** [mantinedev/mantine#6592]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When I use a Slider component, or whatever component that is using the use-move hook, user experience is not great on mobile.

Each time the user is scrolling with his/her finger to just navigate in the application, it might touch by chance the Slider and change its value.

I didnt' find a way to prevent that behaviour.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This is intended behavior. I consider it to be correct and more user-friendly than other available options.
