### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by jaallaall** [mantinedev/mantine#6601]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

Why doesn't this powerful framework have a solar calendar?
 Why doesn't it have the ability to convert the Gregorian calendar to the solar calendar?
Why is there no such capability for Iranians?
That the Iranian community and countries that have a solar calendar are not counted in the statistics!

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Mantine does not support jalali and other calendars. It is not planned to be added, I do not have capacity and requirements in apps that I build to support this feature.

**Comment by baravak** [comment]
fixed it #7302
