### ISSUE TITLE
Cloning values is required – form will not work correctly without it as there will be possible side effects

### ISSUE THREAD

**Issue by atif** [mantinedev/mantine#6603]
Cloning values is required – form will not work correctly without it as there will be possible side effects.

_Originally posted by @rtivital in https://github.com/mantinedev/mantine/issues/2026#issuecomment-1207165104_
            

@rtivital I am also running into this issue. Is there a permanent fix for this one?

` useEffect(() => {
    form.setFieldValue("end", value);
  }, [form.values.start]);`

Above causes infinite loop even I updating the property`end` not `start`. My use case is to update end value if start changes

**Comment by rtivital** [comment]
Use uncontrolled form with `form.watch` – https://mantine.dev/form/values/#formwatch
