### ISSUE TITLE
Mantine is one day off

### ISSUE THREAD

**Issue by Pyakz** [mantinedev/mantine#6609]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Mantine Date pickers a one day off when picking

From Mantine:  2024-07-30T16:00:00.000Z
From Normal Input:  2024-07-31T00:00:00.000Z -- Correct Value

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Pyakz** [comment]
update: this is only happening when it is used on the Form

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction

**Comment by Pyakz** [comment]
**BEFORE SENDING TO THE SERVER**
<img width="628" alt="Screenshot 2024-07-31 at 8 47 57 PM" src="https://github.com/user-attachments/assets/ed0e2fbb-b514-47ae-93c9-247c7af05b16">


**it was changed in the request payload**
<img width="342" alt="Screenshot 2024-07-31 at 8 48 11 PM" src="https://github.com/user-attachments/assets/10c3548a-f365-47db-b634-bc66bb985c28">


sorry, but this might be nextjs

**Comment by masterbater** [comment]
> 
> 
> **BEFORE SENDING TO THE SERVER**
> 
> <img width="628" alt="Screenshot 2024-07-31 at 8 47 57 PM" src="https://github.com/user-attachments/assets/ed0e2fbb-b514-47ae-93c9-247c7af05b16">
> 
> 
> 
> 
> 
> **it was changed in the request payload**
> 
> <img width="342" alt="Screenshot 2024-07-31 at 8 48 11 PM" src="https://github.com/user-attachments/assets/10c3548a-f365-47db-b634-bc66bb985c28">
> 
> 
> 
> 
> 
> sorry, but this might be nextjs
> 
> 

Must be first time for you to work with dates bro, the first screenshot is your local time, server render it as utc in request

**Comment by Pyakz** [comment]
<img width="504" alt="Screenshot 2024-08-02 at 11 27 14 PM" src="https://github.com/user-attachments/assets/4008f779-f75a-41a6-892a-45dab94562c3">


> > **BEFORE SENDING TO THE SERVER**
> > <img alt="Screenshot 2024-07-31 at 8 47 57 PM" width="628" src="https://private-user-images.githubusercontent.com/49338297/353835458-ed0e2fbb-b514-47ae-93c9-247c7af05b16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTI3MzksIm5iZiI6MTcyMjYxMjQzOSwicGF0aCI6Ii80OTMzODI5Ny8zNTM4MzU0NTgtZWQwZTJmYmItYjUxNC00N2FlLTkzYzktMjQ3YzdhZjA1YjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE1MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NmY2YTY5YTY3ZGI1ZTUyYzU4OGY0MzZmMzIyZGU3Y2Q1N2Q3MjAwM2ZmY2M3NWNlMzNiNmQzMjk3N2VkMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5rkm4yTvcCJX-KEgEydEpjY4kW2H76SI9_g_hOqI9NQ">
> > **it was changed in the request payload**
> > <img alt="Screenshot 2024-07-31 at 8 48 11 PM" width="342" src="https://private-user-images.githubusercontent.com/49338297/353835524-10c3548a-f365-47db-b634-bc66bb985c28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTI3MzksIm5iZiI6MTcyMjYxMjQzOSwicGF0aCI6Ii80OTMzODI5Ny8zNTM4MzU1MjQtMTBjMzU0OGEtZjM2NS00N2RiLWI2MzQtYmM2NmJiOTg1YzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE1MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NTkyZGJiNjcxZjA2MDlhYmRkNmNlNmQ0M2E5NzA1ZWQ4YTg5ZTc1OThjNTU2MjQzNTE4YzFiZjEyODRhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.husCfc6Y58W8vtArc783hxNv9Yy01Z1jpLSl7C6vWHA">
> > sorry, but this might be nextjs
> 
> Must be first time for you to work with dates bro, the first screenshot is your local time, server render it as utc in request

<img width="504" alt="Screenshot 2024-08-02 at 11 27 14 PM" src="https://github.com/user-attachments/assets/9341abbb-9001-4596-b57f-317b2500a8dd">


Yup, this is my first time things deeply in dates,  i have setteld with this  solution i got somwhere in here



back to your response, does that mean i have to converto to UTC before sending to the request?

**Comment by masterbater** [comment]
> <img alt="Screenshot 2024-08-02 at 11 27 14 PM" width="504" src="https://private-user-images.githubusercontent.com/49338297/354645147-4008f779-f75a-41a6-892a-45dab94562c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjI1MjMsIm5iZiI6MTcyMjYyMjIyMywicGF0aCI6Ii80OTMzODI5Ny8zNTQ2NDUxNDctNDAwOGY3NzktZjc1YS00MWE2LTg5MmEtNDVkYWI5NDU2MmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE4MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzBkMzE0NzM1ZDczNjFmNDQ0YmU5NjViZmRjN2VkM2YyM2JhZmI4ODgzZjFmMzUxYmU0YmFiZjBmYTA1NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YnS_TWJgldaPIi4J_n3hKq5KnY1tVMqyb8p3Yo4fM3k">
> > > **BEFORE SENDING TO THE SERVER**
> > > <img alt="Screenshot 2024-07-31 at 8 47 57 PM" width="628" src="https://private-user-images.githubusercontent.com/49338297/353835458-ed0e2fbb-b514-47ae-93c9-247c7af05b16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTI3MzksIm5iZiI6MTcyMjYxMjQzOSwicGF0aCI6Ii80OTMzODI5Ny8zNTM4MzU0NTgtZWQwZTJmYmItYjUxNC00N2FlLTkzYzktMjQ3YzdhZjA1YjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE1MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NmY2YTY5YTY3ZGI1ZTUyYzU4OGY0MzZmMzIyZGU3Y2Q1N2Q3MjAwM2ZmY2M3NWNlMzNiNmQzMjk3N2VkMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5rkm4yTvcCJX-KEgEydEpjY4kW2H76SI9_g_hOqI9NQ">
> > > **it was changed in the request payload**
> > > <img alt="Screenshot 2024-07-31 at 8 48 11 PM" width="342" src="https://private-user-images.githubusercontent.com/49338297/353835524-10c3548a-f365-47db-b634-bc66bb985c28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTI3MzksIm5iZiI6MTcyMjYxMjQzOSwicGF0aCI6Ii80OTMzODI5Ny8zNTM4MzU1MjQtMTBjMzU0OGEtZjM2NS00N2RiLWI2MzQtYmM2NmJiOTg1YzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE1MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NTkyZGJiNjcxZjA2MDlhYmRkNmNlNmQ0M2E5NzA1ZWQ4YTg5ZTc1OThjNTU2MjQzNTE4YzFiZjEyODRhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.husCfc6Y58W8vtArc783hxNv9Yy01Z1jpLSl7C6vWHA">
> > > sorry, but this might be nextjs
> > 
> > 
> > Must be first time for you to work with dates bro, the first screenshot is your local time, server render it as utc in request
> 
> <img alt="Screenshot 2024-08-02 at 11 27 14 PM" width="504" src="https://private-user-images.githubusercontent.com/49338297/354645204-9341abbb-9001-4596-b57f-317b2500a8dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjI1MjMsIm5iZiI6MTcyMjYyMjIyMywicGF0aCI6Ii80OTMzODI5Ny8zNTQ2NDUyMDQtOTM0MWFiYmItOTAwMS00NTk2LWI1N2YtMzE3YjI1MDBhOGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE4MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MTA5NTk3MjQyYzlhMjM3YmE2MjhjMzcwMzgwYzJjZGNkNWMwMDg0ZTY3NmI5YTMwNjY1OGY1MzljMmI1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i0ax9X3NZcJ-capNJWQ5l53a3CDSGjuXpJk9dly82zw">
> Yup, this is my first time things deeply in dates, i have setteld with this solution i got somwhere in here
> 
> back to your response, does that mean i have to converto to UTC before sending to the request?

<img width="552" alt="image" src="https://github.com/user-attachments/assets/a5e42152-767c-445c-8632-4e211fe5d418">

**Comment by masterbater** [comment]
> <img alt="Screenshot 2024-08-02 at 11 27 14 PM" width="504" src="https://private-user-images.githubusercontent.com/49338297/354645147-4008f779-f75a-41a6-892a-45dab94562c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjI1MjMsIm5iZiI6MTcyMjYyMjIyMywicGF0aCI6Ii80OTMzODI5Ny8zNTQ2NDUxNDctNDAwOGY3NzktZjc1YS00MWE2LTg5MmEtNDVkYWI5NDU2MmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE4MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzBkMzE0NzM1ZDczNjFmNDQ0YmU5NjViZmRjN2VkM2YyM2JhZmI4ODgzZjFmMzUxYmU0YmFiZjBmYTA1NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YnS_TWJgldaPIi4J_n3hKq5KnY1tVMqyb8p3Yo4fM3k">
> > > **BEFORE SENDING TO THE SERVER**
> > > <img alt="Screenshot 2024-07-31 at 8 47 57 PM" width="628" src="https://private-user-images.githubusercontent.com/49338297/353835458-ed0e2fbb-b514-47ae-93c9-247c7af05b16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTI3MzksIm5iZiI6MTcyMjYxMjQzOSwicGF0aCI6Ii80OTMzODI5Ny8zNTM4MzU0NTgtZWQwZTJmYmItYjUxNC00N2FlLTkzYzktMjQ3YzdhZjA1YjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE1MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NmY2YTY5YTY3ZGI1ZTUyYzU4OGY0MzZmMzIyZGU3Y2Q1N2Q3MjAwM2ZmY2M3NWNlMzNiNmQzMjk3N2VkMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5rkm4yTvcCJX-KEgEydEpjY4kW2H76SI9_g_hOqI9NQ">
> > > **it was changed in the request payload**
> > > <img alt="Screenshot 2024-07-31 at 8 48 11 PM" width="342" src="https://private-user-images.githubusercontent.com/49338297/353835524-10c3548a-f365-47db-b634-bc66bb985c28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTI3MzksIm5iZiI6MTcyMjYxMjQzOSwicGF0aCI6Ii80OTMzODI5Ny8zNTM4MzU1MjQtMTBjMzU0OGEtZjM2NS00N2RiLWI2MzQtYmM2NmJiOTg1YzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE1MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NTkyZGJiNjcxZjA2MDlhYmRkNmNlNmQ0M2E5NzA1ZWQ4YTg5ZTc1OThjNTU2MjQzNTE4YzFiZjEyODRhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.husCfc6Y58W8vtArc783hxNv9Yy01Z1jpLSl7C6vWHA">
> > > sorry, but this might be nextjs
> > 
> > 
> > Must be first time for you to work with dates bro, the first screenshot is your local time, server render it as utc in request
> 
> <img alt="Screenshot 2024-08-02 at 11 27 14 PM" width="504" src="https://private-user-images.githubusercontent.com/49338297/354645204-9341abbb-9001-4596-b57f-317b2500a8dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjI1MjMsIm5iZiI6MTcyMjYyMjIyMywicGF0aCI6Ii80OTMzODI5Ny8zNTQ2NDUyMDQtOTM0MWFiYmItOTAwMS00NTk2LWI1N2YtMzE3YjI1MDBhOGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE4MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MTA5NTk3MjQyYzlhMjM3YmE2MjhjMzcwMzgwYzJjZGNkNWMwMDg0ZTY3NmI5YTMwNjY1OGY1MzljMmI1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i0ax9X3NZcJ-capNJWQ5l53a3CDSGjuXpJk9dly82zw">
> Yup, this is my first time things deeply in dates, i have setteld with this solution i got somwhere in here
> 
> back to your response, does that mean i have to converto to UTC before sending to the request?

```typescript
//  the local time will always depend on your browser timezone 
const startOfMonthInUtc = dayjs().startOf('month').utc().format();
const startOfMonthLocalTime = dayjs().startOf('month').format();
const convertLocalTimeToUtc = dayjs(startOfMonthLocalTime).utc().format();

This should output the same value
console.log('startOfMonthInUtc', JSON.stringify(startOfMonthInUtc, null, 2));
console.log('convertLocalTimeToUtc ', JSON.stringify(convertLocalTimeToUtc, null, 2))
```

**Comment by MilanDeruelle** [comment]
A little tipp for anyone running into the same issue:
`<DatesProvider settings={{ timezone: 'UTC', locale: 'de' }}>
      <DateInput/>
    </DatesProvider>`

will provide you with a date in UTC format from the start
