### ISSUE TITLE
Thousands separator does not work in NumberInput for mantine v6

### ISSUE THREAD

**Issue by FerranMontoliu** [mantinedev/mantine#6610]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

6.0.21

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

# Brief explanation

I have a NumberInput which I need to format to clearly indicate both the thousands separator and the decimal separator. Nevertheless, the example from the docs does not work properly, as the decimal separator appears, but the thousands separators do not appear.

# Steps to reproduce

Using the following code:
```jsx
import React from 'react';
import { NumberInput } from '@mantine/core';

export default function App() {
  // This example has been taken directly from the docs, without any modification:
  // https://v6.mantine.dev/core/number-input/#decimalthousands-separator
  return (
    <NumberInput
      decimalSeparator=","
      thousandsSeparator="."
      label="Number input with custom separators"
      defaultValue={0.5}
      precision={2}
      step={0.5}
    />
  );
}
```

The input that is created has the custom decimal separator (a comma), but does not have any thousands separator at all, as can be seen in the following image:

![image](https://github.com/user-attachments/assets/641c34be-4fbe-4701-8968-39901e7b2a4e)

> **_NOTE:_**  The example provided was taken from the official documentation, where this is also broken (more information in https://v6.mantine.dev/core/number-input/#decimalthousands-separator).

### If possible, include a link to a codesandbox with a minimal reproduction

https://stackblitz.com/edit/react-7lfwt9?file=src%2FApp.js

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by FerranMontoliu** [comment]
This feature works as expected in `mantine v7.11.2` as can be seen in https://mantine.dev/core/number-input/#thousand-separator, but due to other dependencies we cannot update to version 7 for our project.

Would it be possible to implement a fix for v6?

**Comment by rtivital** [comment]
Currently it is not planned to release new 6.x versions. If you want to continue using v6, then it will be easier to use another component for number formatting – https://www.npmjs.com/package/react-number-format
You can integrate it with Mantine styles using `InputBase` component

**Comment by FerranMontoliu** [comment]
Thanks for the quick answer @rtivital, I'll explore that option then!
