### ISSUE TITLE
Can't override label's size of TextInput component

### ISSUE THREAD

**Issue by viennv1709** [mantinedev/mantine#6611]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Can't override label's size of TextInput component
```tsx
<TextInput
  required
  label="Email"
  labelProps={{ size: 'sm' }}
  radius="sm"
  size="md"
/>
```

Because of `--input-label-size:var(--mantine-font-size-md)`

![image](https://github.com/user-attachments/assets/b17e1d7f-98b6-47b0-a752-7ab61304c830)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is not planned to change this behavior, in this case, you can use Styles API to change component styles.
