### ISSUE TITLE
Embla type is incorrect and returns any

### ISSUE THREAD

**Issue by anamsohail** [mantinedev/mantine#6612]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.2

### What package has an issue?

@mantine/carousel

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

The exported type of `Embla` from `@mantine/carousel` seems to be incorrect from v7 onwards. It always returns `any` now. Looking at the code in mantine, the type is being imported from `embla-carousel-react`:
`import type { EmblaCarouselType } from 'embla-carousel-react';`
which is not exactly returning the correct type.

Following the [docs](https://mantine.dev/x/carousel/#get-embla-instance) exactly and importing the type from this package leads the following issue:
![Screenshot 2024-07-31 at 20 51 44](https://github.com/user-attachments/assets/2b3b6c6a-0111-45a6-aec7-248d8581d8a0)

Similar issue was reported in `embla-carousel` here: [647](https://github.com/davidjerleke/embla-carousel/issues/647)

### Possible fix

https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Issue of pnpm, it is not recommended to use pnpm to install Mantine packages.

**Comment by cpannwitz** [comment]
Just for the record, running into this while using Yarn, not pnpm.

**Comment by rtivital** [comment]
You can import types from embla package directly like it is described in the embla discussion – https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239
