### ISSUE TITLE
Modal doesn't display in mobile "browser-in-app" from iOS

### ISSUE THREAD

**Issue by andrewhwanpark** [mantinedev/mantine#6615]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

I have a `<Modal>` to set the user's username on first login. Seems like the modal doesn't show in "browser-in-app" from iOS devices. If you directly visit the site in mobile safari or any other standalone browser, the modal displays fine. Is this something that's inherent to the browser-in-app iOS devices or mantine?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I cannot reproduce the issue, it opens fine on the documentation website. ![image](https://github.com/user-attachments/assets/5e976938-b744-43b4-9c3d-a71b91e442ff)
