### ISSUE TITLE
Spotlight limit prop behaves strangely with grouped actions

### ISSUE THREAD

**Issue by yorkeJohn** [mantinedev/mantine#6620]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/spotlight

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Limit prop does not correctly limit actions when the actions are grouped using `SpotlightActionGroupData[]`.

See codesandbox. Change the limit prop and observe that an incorrect number of actions is displayed.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-66k5jn

### Possible fix

Fix in `limit-actions.ts` (tested working as intended via `pnpm patch` in my project)

```ts
import { isActionsGroup } from './is-actions-group';
import type { SpotlightActionData, SpotlightActions } from './Spotlight';

export function limitActions(actions: SpotlightActions[], limit: number) {
  if (!Array.isArray(actions)) {
    return [];
  }

  let count = 0;
  return actions.reduce<SpotlightActions[]>((acc, item) => {
    if (count >= limit) {
      return acc;
    }

    if (isActionsGroup(item)) {
      const groupActions = limitActions(item.actions, limit - count);
      acc.push({
        group: item.group,
        actions: groupActions as SpotlightActionData[],
      });
      count += groupActions.length;
    } else {
      acc.push(item);
      count++;
    }

    return acc;
  }, []);
}
```

### Self-service

- [x] I would be willing to implement a fix for this issue

**Comment by yorkeJohn** [comment]
Edit: just tested the proposed fix via a `pnpm patch` in my project, and it works as intended.

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix
