### ISSUE TITLE
NumberInput onChange providing wrong type of value under certain circumstances

### ISSUE THREAD

**Issue by btnmasher** [mantinedev/mantine#6621]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

In the scenario I am having an issue with, I have a `NumberInput` with the properties `fixedDecimalScale` and `decimalScale={2}`

When a value of `0` is typed into the input, the displayed text shows the expected `'0.00'` in the input, but the value given to the `onChange` function is of a string type with the value `'0.00'` instead of the expected number type with the value `0`.

It appears the issue is pinpointed to this regex test here: https://github.com/mantinedev/mantine/blob/c087030bbc67a895cb39475b0494ed5a6dc5e7ab/packages/%40mantine/core/src/components/NumberInput/NumberInput.tsx#L244C1-L255C5

```TypeScript
const handleValueChange: OnValueChange = (payload, event) => {
  if (event.source === 'event') {
    setValue(
      isValidNumber(payload.floatValue) &&
        !leadingDecimalZeroPattern.test(payload.value) &&
        !(allowLeadingZeros ? leadingZerosPattern.test(payload.value) : false)
        ? payload.floatValue
        : payload.value
    );
  }
  onValueChange?.(payload, event);
};
```

Where `leadingDecimalZeroPattern.test()` matches the string `'0.00'` then is negated which results in the `value` key of `payload` being selected for `setValue()` instead of the desired `floatValue` key.

Only upon changing focus away from the `NumberInput` does the value provided to the `onChange` handler result in a correct numeric type and value.

This results in having to check the type of the value being provided in an `onChange` handler and then parsing that value manually in the scenario where `0.00` is a valid input. The problem I was running into specifically is if a user were to hit the enter key on the keyboard to submit the form, the value would not be corrected by that change of focus that would otherwise occur if the user instead clicked the submit button.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-rmqw3y?file=%2Fsrc%2FApp.tsx

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior that cannot be changed. If `0.0` and other similar values are treated simply as `0` the component would not be able to handle decimal values that start with `0.0` correctly (for example `0.001`). To fix the issue on your side, transform the value to number before sending data from your form.
