### ISSUE TITLE
Add "Start" and "End" style props

### ISSUE THREAD

**Issue by mnakhli** [mantinedev/mantine#6623]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

Latest

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

For example, in `Stack` component (In `fixed` state), I want to set its position to` start={0}`. when I set it to `left={0}`, it remains on the left in RTL, whereas it should move to the right.
(Although this issue is resolved by not setting the left prop, in some cases, it's necessary to ensure proper alignment in both RTL and LTR.)

### Possible fix

In addition to the `left` and `right` props, **`start`** and **`end`** props can also be added.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is not planned to introduce these props, if your application supports both rtl and ltr layouts, use CSS modulecs to apply styles.
