### ISSUE TITLE
Fix for validation rules to trigger when working with validateInputOnChange set to true

### ISSUE THREAD

**Issue by Yuri2b** [mantinedev/mantine#6635]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/form

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

When using form with `validateInputOnChange: true` and validation rules object like
```
validate: {
  name: validateRequired("Name is required"),
  email: firstOf([
    validateRequired("Email is required"),
    validateEmailFormat("Invalid Email format"),
  ]),
  ...
}
  ```
  the next points are frustrating:
  
  1. The validation rules check is triggered on every field value not only the changing one.
  2. At the same time, even if the validation rule is triggered on some value and passes validation, the error is not removed from that value.
  
  Thus, from my point of view, only one option is possible: either we validate all fields as we do now, but correctly handle the validation result (set or remove errors), or we should run validation only for the currently changing value.

  I've found that the current approach is frustrating when you have to work with dependent validations, where the validity of a value depends on another value of the form.
  

### Possible fix

Possible fixes when working with `validateInputOnChange: true` are:
1. Validate only currently changing field value
2. Validate all values but correctly handle the validation result (set or remove errors)

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is not planned to change this logic, functions provided as rules must not have any side effects.
