### ISSUE TITLE
NumberInput: Value in onChange is string if empty

### ISSUE THREAD

**Issue by HypeillingerChillinger** [mantinedev/mantine#6648]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

In a NumberInput, the onChange value is a empty string if the control was cleared while it is a number if a number is typed in.

I think it should be ```null``` or ```undefined``` (better null) if the control is cleared. A switch of types is unexpected.

![image](https://github.com/user-attachments/assets/8258314c-36a0-4059-a85e-4475bf346c02)

![image](https://github.com/user-attachments/assets/08d9f2d5-3600-448a-bf5f-59a9bb5dbbc1)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior, empty string is used for empty value and other cases where number cannot be used.
