### ISSUE TITLE
`cssVariablesResolver` doesn't come with custom colors

### ISSUE THREAD

**Issue by willpinha** [mantinedev/mantine#6649]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.12.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

I have the following theme override in my application:

```ts
const theme = createTheme({
  colors: {
    tomato: [
      "#fff0e4",
      "#ffe0cf",
      "#fac0a1",
      "#f69e6e",
      "#f28043",
      "#f06d27",
      "#f06418",
      "#d6530c",
      "#bf4906",
      "#a73c00"
    ]
  }
});
```

I also have the following `cssVariablesResolver`:

```ts
const resolver: CSSVariablesResolver = (theme) => {
  console.log(theme.colors);

  return {
    variables: {},
    dark: {},
    light: {
      "--mantine-color-body": theme.colors.tomato[0],
    },
  }
}
```

Finally, the two variables are used within the MantineProvider:

```tsx
<MantineProvider theme={theme} cssVariablesResolver={resolver} forceColorScheme="light">
  Hello world
</MantineProvider>
```

When I run my application, the `console.log` inside the resolver does not show my custom color "tomato", in addition to the error `Cannot read properties of undefined` being thrown because I try to access an index of `theme.colors.tomato` (which is undefined) inside the resolver

Is there any way to access customizable variables that I created within `cssVariablesResolver`?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Provide a sandbox with a minimal reproduction.

**Comment by willpinha** [comment]
I was creating the sandbox and it worked. Turns out there was a logic error on my part. Sorry!
