### ISSUE TITLE
Notification not fitting everything.

### ISSUE THREAD

**Issue by DKGH** [mantinedev/mantine#6651]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.0

### What package has an issue?

@mantine/notifications

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Steps to reproduce:
1. Install using `npm install @mantine/notifications`.
2. Put `import '@mantine/notifications/styles.css';` in `App.tsx` under the core and hooks styles.
3. Use any sample involving `notifications.show` from [the documentation](https://mantine.dev/x/notifications/).

Problem:
Notifications aren't tall enough to contain all the text. In fact, it can't even contain the title and a single word properly.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction

**Comment by DKGH** [comment]
While trying to create the sandbox, I discovered that the problem was happening because I had set `sm` line height in `theme.ts` to `0.5`. I need to keep that line height for the rest of my app. Is there a way make `sm` line height = `1` for Notifications alone? Please see if there also a way to re-classify this as a question at this point?

**Comment by rtivital** [comment]
To change styles of a specific component, use Styles API – https://mantine.dev/styles/styles-api/#classnames-in-themecomponents. In this case, you need to change styles of the `Notification` component.
