### ISSUE TITLE
RangeSlider is not working properly

### ISSUE THREAD

**Issue by DKGH** [mantinedev/mantine#6668]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Steps to reproduce:

1. Start with [basic-vite-template](https://github.com/mantinedev/vite-template)
2. Edit Home.page.tsx as below:
```
import { Welcome } from '../components/Welcome/Welcome';
import { ColorSchemeToggle } from '../components/ColorSchemeToggle/ColorSchemeToggle';
import { Card, RangeSlider, Stack, Text } from '@mantine/core';
import { useState } from 'react';

const minLeft = 0;
const maxRight = 10;

export function HomePage() {  
  const [rangeValue, setRangeValue] = useState<[number, number]>([minLeft, maxRight])

  return (
    <>
      <Welcome />
      <ColorSchemeToggle />
      <Card style={{ background: 'lightblue' }}>
        <Stack justify='center'>
          <Text>(${rangeValue[0]}, ${rangeValue[1]})</Text>
          <RangeSlider
            w={100}
            min={minLeft}
            max={maxRight}
            value={rangeValue}
            onChange={setRangeValue}/>
        </Stack>
      </Card>
    </>
  );
}
```
3. `npm install` and `npm run dev`
4. Launch browser.

Outcome:
The webpage has a slider which does not move.

Expected outcome:
Range slider is expected to move and update the values.

### If possible, include a link to a codesandbox with a minimal reproduction
[MWE](https://codesandbox.io/p/sandbox/epic-morse-wvvnn8)

_No response_

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Provide a sandbox with a minimal reproduction.

**Comment by DKGH** [comment]
> Provide a sandbox with a minimal reproduction.

Please see if this [link](https://codesandbox.io/p/sandbox/epic-morse-wvvnn8) helps.

**Comment by rtivital** [comment]
You need to set `minRange={0.01}`.

**Comment by aratai** [comment]
Why is it not by default at every example in the docs? I also had issue with that as range was not working.
