### ISSUE TITLE
Paralect Ship Template

### ISSUE THREAD

**Issue by fruneen** [mantinedev/mantine#6696]
### Link to the repository on GitHub

https://github.com/paralect/ship-template

### Features of the template, describe how it is different from other templates

Ship is a full-stack boilerplate with guidelines to build MVPs in days and scale your product for years.

# Features

## Front-end
- Mantine ❤️ 
- Next.js
- TanStack Query
- Storybook

## Back-end
- Koa.js
- Mongodb
- Redis

## Common
- Email/password and Google Oauth authentication 🔐
- Multiple environments support 📝
- Reactive MongoDB [configuration](https://ship.paralect.com/docs/packages/node-mongo) with CUD events publishing 🍃
- [Kubernetes](https://ship.paralect.com/docs/deployment/kubernetes/overview) and [DO Apps](https://ship.paralect.com/docs/deployment/digital-ocean-apps) deployment for AWS and Digital Ocean platforms ☁
- Turborepo packages sharing 🏎
- Files upload to cloud storage 🗃
- React Email 📧
- Websockets 🔌
- Database [migrations](https://ship.paralect.com/docs/migrator) 🌖
- [CRON jobs](https://ship.paralect.com/docs/scheduler) ⏰
- Logging and monitoring 📈
- Code linting and testing ⚙️
- CI/CD 🤖

Ship has been using Mantin since 2022. For the last 2 years, in [Paralect](https://www.paralect.com/), we have successfully launched dozens of projects thanks to Mantine.

In submitted template, I initialised basic version of Ship with Digital Ocean deployment type. 
This version is ready to use and is awaiting your approval to go to the "Getting Started" page.

Landing page: https://ship.paralect.com/
Main repository: https://github.com/paralect/ship

**Comment by rtivital** [comment]
Thanks for submitting a template, it will be added to the templates section with the next patch release.

**Comment by fruneen** [comment]
Thanks a lot!
