### ISSUE TITLE
NumberInput typing leading decimal followed by 0 overwrites decimal

### ISSUE THREAD

**Issue by Yhprum** [mantinedev/mantine#6709]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I want to type “.05” in the number input. Typing “.0” formats the input to “0”, so adding the 5 after makes the value “05” instead of “.05”. I can type “0.05” as a workaround but is there a way this behavior can work too?

### If possible, include a link to a codesandbox with a minimal reproduction

I reproduced this on the mantine.dev website number input example page

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by amir-grappetite** [comment]
Yes, you are right @Yhprum . though this is not the issue with v5 which I am currently using for my project. https://v5.mantine.dev/core/number-input/#decimal-steps .

**Comment by rtivital** [comment]
It is intended behavior `.05` is not a valid number format.
