### ISSUE TITLE
[@mantine/core] Timeline Component can't be wrapped?

### ISSUE THREAD

**Issue by eakl** [mantinedev/mantine#671]
### What package has an issue

@mantine/core

### Describe the bug

Timeline and Timeline.Item components can't be wrapped.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/lingering-haze-yowcv?file=/src/App.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
This is how Mantine components work with children, where filtering is required, there is no good way to solve this issue

**Comment by eakl** [comment]
Thanks for your reply

**Comment by Avataw** [comment]
Hey there ~ I don't want to necro, but I stumbled upon this very issue as well.

@rtivital I'd recommend at least updating the current documentation with a warning that neither can be wrapped.

Further I had a look and the reason for it not being able to be wrapped as you mentioned is the [filterChildrenByType](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/utils/filter-children-by-type/filter-children-by-type.ts) function. 

In the example provided by @eakl as far as I can tell it would work without any issues if the `filterChildrenByType` function was not used in the `timeLine` component -> His wrapper component fulfills all functional requirements, but it gets filtered out beforehand.

I am all for making sure people don't abuse lists by putting arbitrary stuff inside - but in this case I would have loved to get some sort of interface I can simply import in case I want to wrap my timeLineItems regardless.

**Comment by rtivital** [comment]
Documentation is updated in 5.0 version – https://v5.mantine.dev/core/timeline/#wrap-timelineitem

**Comment by Avataw** [comment]
That's dope :) Thank you very much!

Is there a roadmap where the timeline is going? 
I'd love to get a clickable bullet, or more customizable timelineItems :)

**Comment by rtivital** [comment]
No, we do not provide public roadmap
