### ISSUE TITLE
form setFieldValue does not match with form values

### ISSUE THREAD

**Issue by hyusetiawan** [mantinedev/mantine#6717]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/form

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

For some reason, while calling setFieldValue, the underlying values seem to be the initialized form values instead of the update form values, here's what I mean:

I initialize the form like so:
```
const form = useForm({
    validateInputOnChange: true,
    initialValues: {
      name: '',
      signals: [] as Array<SignalChoiceKind>,
      rental: null, // <-- NOTE rental here is null
      amenities: [] as SettingsAmenities,
    } as ScenarioFormSchema,
    validate: zodResolver(ScenarioFormSchema),
  })
```
and then when the user clicks into the rental form, I would initialize the default rental configuration like so:
```
useEffect(() => {
   if (
      form.values.signals.includes(SignalChoiceKind.RENTAL_CALCULATOR) &&
      isEmpty(form.values.rental)
    ) {
      form.setFieldValue(
        'rental',
        defaultRental() as ScenarioFormState['data']['values']['rental'],
      )
      setModalContentMode('rental')
    }
  }, [form.values.signals])

```
this initializes correctly as reflected in form.values in this screenshot, in the event handler that will call setFieldValue inside the "rehab" property
<img width="1050" alt="Screenshot 2024-08-23 at 11 33 52 AM" src="https://github.com/user-attachments/assets/79279013-c176-4b87-9e69-1917ee61865b">
as you can see `form.data.values` (ignore the data property) contains rehab object accordingly, `prefix` contains the path to the specific item, so the user can set the `name`, and the full data path is `rental.rehab.items.2.name`

however, after calling the `setFieldPath` with that data path, I am getting an exception like this:
<img width="925" alt="Screenshot 2024-08-23 at 11 37 02 AM" src="https://github.com/user-attachments/assets/a455bfcb-f680-4896-b92a-9a82747e21b5">
the `splittedPath` is correct `rental.rehab.items.2.name` as an array
but the values have `rental` as null, `amenities` as an empty array etc, just like the originally initialized value above but different from the form.values content with `rental` already set via `form.setFieldValue` above

Anything I should look out for? Note that, the only change I have made to the best of my knowledge is updating the mantine versions

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by hyusetiawan** [comment]
I just confirmed that it seems the 
```
form.setFieldValue(
        'rental',
        defaultRental() as ScenarioFormState['data']['values']['rental'],
      )
```
so, using setFieldValue above, I can access the value form.values.rental just fine and the value is correct but to update the value via another `setFieldValue` the "internals" seem to have a different copy, of the values, and that copy is the originally initialized value as if the setFieldValue above was never called.  I hope i am making sense

**Comment by rtivital** [comment]
I could not understand the issue, please provide a sandbox with a minimal reproduction

**Comment by hyusetiawan** [comment]
## Summary
There's a discrepancy between accessing and setting form values for nested objects in a Mantine form. While the values can be accessed correctly, attempting to set them throws an error due to the initial state not being properly updated.

## Initial Setup

1. Form is initialized with:
```javascript
{
  name: '',
  signals: [] as Array<SignalChoiceKind>,
  rental: null,
  amenities: [] as SettingsAmenities,
}
```
2. In another component, rental is initialized:
```javascript
form.setFieldValue('rental', defaultRental())
```
3. `defaultRental()` returns:
```javascript
{
  // ...other properties
  rehab: {
    items: [
      {name: 'HVAC'},
      {name: 'Cleanup'},
    ]
  }
}
```
## Behavior

1. Accessing the value works as expected:
```javascript
form.values.rental.rehab.items[0].name // Returns "HVAC"
```
for example: `<TextInput value={form.values.rental.rehab.items[0].name} />`
2. Setting the value throws an error:
```javascript
onChange={(e) => form.setFieldValue('rental.rehab.items.0.name', 'HVAC1')}
```

## Error
In the `getPath()` function of @mantine/form, the values parameter shows the initial state where rental is still null.
This suggests that the defaultRental() set using setFieldValue() is not properly updating the internal state used by getPath(). It is confirmed that this is the case because if the value was initialized with `defaultRental()` instead of `null`, both accessing value and setting field value would work.

## Expected
Both accessing and setting nested form values should work consistently, reflecting the updated state after defaultRental() is applied.

**Comment by rtivital** [comment]
please provide a sandbox with a minimal reproduction
