### ISSUE TITLE
Carousel orientation is set to `vertical` by default and can't be changed

### ISSUE THREAD

**Issue by arielclement** [mantinedev/mantine#6721]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.7.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Changing `<Carousel />` orientation  props to `horizontal` kept the elements stacked vertically

<img width="614" alt="Screenshot 2024-08-26 at 15 32 26" src="https://github.com/user-attachments/assets/f5889f49-4b27-46c2-829d-762873430f74">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Provide a sandbox with a minimal reproduction, it works correctly on mantine.dev website. Make sure that you've followed the installation guide accurately – https://mantine.dev/x/carousel/#installation

**Comment by arielclement** [comment]
> Provide a sandbox with a minimal reproduction, it works correctly on mantine.dev website. Make sure that you've followed the installation guide accurately – https://mantine.dev/x/carousel/#installation

My bad I forgot to import the css. Thanks!
