### ISSUE TITLE
useInterval is now a lot slower

### ISSUE THREAD

**Issue by kinoli** [mantinedev/mantine#6734]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/hooks

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

This useEffect inside the useInterval hook gets re-rendered everytime the interval runs, which can negatively impact the user experience.

```
useEffect(() => {
    fnRef.current = fn;
    active && start();
    return stop;
  }, [fn, active, interval]);
```

The slowness comes from the `return stop` getting run as the code in there seems to run every interval and not be desired.

### Possible fix

My suggestion is to remove the watch on `fn`, as that is what is causing the useEffect to fire constantly. Is there really a need to watch the `fn` anyways?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is required to watch `fn` to make sure that it does not use stale value. If you want to optimize the code, wrap your function with `useCallback`.
