### ISSUE TITLE
camelCaselCase instead of snake-case for hook page titles during search?

### ISSUE THREAD

**Issue by dylangrandmont** [mantinedev/mantine#6736]
### Link to the page where something is not right

https://mantine.dev/hooks/*

### What is wrong?

(I'm a huge fan of this library - thanks for the effort that has gone into it!)

One usability issue I find with the docs pages is all the hook pages are indexed by a snake-case name. This always trips me up when searching for hooks. When searching for components, I search by the component name; I would like to do the same for hooks.

https://github.com/user-attachments/assets/2da8345d-581e-43d3-a845-a81c345f6073

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.12.2](https://github.com/mantinedev/mantine/releases/tag/7.12.2)
