### ISSUE TITLE
[@mantine/core] Vertical Divider does not work in a Group

### ISSUE THREAD

**Issue by timvandam** [mantinedev/mantine#674]
### What package has an issue

@mantine/core

### Describe the bug

When placing a vertical divider inside of a group, I would expect it to show up. But it does not.

### In which browser did the problem occur

Google Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/peaceful-margulis-2f8s9?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I got the divider to show up by manually unticking `height: 100%` through Inspect Element

**Comment by rtivital** [comment]
You need to set `height: auto` in order for it to work in a Group – https://codesandbox.io/s/floral-leaf-95e24

**Comment by timvandam** [comment]
> You need to set `height: auto` in order for it to work in a Group – https://codesandbox.io/s/floral-leaf-95e24

I see. Is this something that can be fixed in Mantine? Or should I just remember to do this each time

**Comment by rtivital** [comment]
If we set height: auto, then in will not work in non flex containers, so just remember to set it when you use it in Group
