### ISSUE TITLE
onChange is already specified in PickerBaseProps

### ISSUE THREAD

**Issue by yuho-sumitomo** [mantinedev/mantine#6740]
### Link to the page where something is not right

https://mantine.dev/dates/date-picker-input/

### What is wrong?

```tsx
import { useState } from 'react';
import { DatePickerInput } from '@mantine/dates';

function Demo() {
  const [value, setValue] = useState<Date | null>(null);
  return (
    <DatePickerInput
      label="Pick date"
      placeholder="Pick date"
      value={value}
      onChange={setValue}
    />
  );
}
```
This usage causes the following error and does not work properly
`'onChange' is specified more than once, so this usage will be overwritten.ts(2783)`

I think it is because it is used in PickerBaseProps
```ts
(property) PickerBaseProps<"default">.onChange?: ((value: DateValue) => void) | undefined
Called when value changes
```

**Comment by rtivital** [comment]
I cannot reproduce the issue on codesandbox – https://codesandbox.io/p/sandbox/mantine-react-template-forked-lwk62y?file=%2Fsrc%2FApp.tsx%3A4%2C1&workspaceId=dd881b63-29f6-464c-bcdf-b5f78ad65b26

**Comment by yuho-sumitomo** [comment]
Sorry, it was a problem with my environment.
Thanks for checking.
