### ISSUE TITLE
Notifications insert div overlapping body

### ISSUE THREAD

**Issue by Toukassay** [mantinedev/mantine#6741]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/notifications

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

![image](https://github.com/user-attachments/assets/1af01d9f-2e56-4030-9571-baa8e413596a)
![image](https://github.com/user-attachments/assets/6d33ac50-ea05-416a-8aa1-9507aeb6622d)
![image](https://github.com/user-attachments/assets/b3a40c1e-c1d7-4c43-b50a-a4ee686924de)

Since updating from 7.11.2 to 7.12.1 I now have div overlapping my body. I've indeed use an overkill zindex in the component but even with "1" it's the same. It only doesn't bother me with "0" zindex but my notifications are behind pretty much everything... 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I cannot reproduce the same notifications container height in Chrome, its height is the same as height of all combined notifications. Make sure that you do not have any styles in your application that might cause this issue.

<img width="961" alt="Снимок экрана 2024-08-30 в 17 17 05" src="https://github.com/user-attachments/assets/722493fd-b034-4a99-b9ca-8c417d2a891f">

**Comment by Toukassay** [comment]
Nop I don't have custom style on it, like you can see :
![image](https://github.com/user-attachments/assets/b4de9f86-aacb-4628-be68-41d3a50371ab)

Edit: I think I've found it, it's when using `top={50}`
```js
      <Notifications
        classNames={notificationsStyles}
        position="top-center"
        top={50}
        zIndex={1000000}
        transitionDuration={500}
      />
 ```     
Without it it's ok and doesn't bother hovering things. But how can I have my notifications 50px form the top without using this props ?

**Comment by rtivital** [comment]
If you need to set top, then set bottom to auto.

**Comment by Toukassay** [comment]
> If you need to set top, then set bottom to auto.

Ok thanks, it works
