### ISSUE TITLE
Shadow prop on Paper component

### ISSUE THREAD

**Issue by devalirzayev** [mantinedev/mantine#6743]
Hi @rtivital. 

It says "shadow" prop is "none" by default, but it applies shadow when I don't set it. Is there something I have missed in documentation, or it could be a bug?

https://github.com/mantinedev/mantine/blob/133b7bf0c739c865e299e4886b22e086d975bd0b/packages/%40mantine/core/src/components/Paper/Paper.tsx#L23

Thanks for a great library!

**Comment by rtivital** [comment]
I do not see any shadow on Paper component – https://codesandbox.io/p/sandbox/mantine-react-template-forked-k4lv26?file=%2Fsrc%2FApp.tsx%3A10%2C9&workspaceId=dd881b63-29f6-464c-bcdf-b5f78ad65b26

**Comment by devalirzayev** [comment]
Please see this one: https://codesandbox.io/p/sandbox/mantine-react-template-forked-k4lv26

My guess is if a parent `Paper` component has a shadow, it will pass to children as `--paper-shadow` variable is declared in scope. I can see this is not something easy to change. But would like to know if this is intended (and why) or a bug that is not prioritized. If it is a bug, I would like to work on it.

**Comment by Kenzo-Wada** [comment]
At this case, I think you should use Card component(a wrapper component of Paper) because Paper is a polymorphic component and it is mainly used inside custom component. WDYT?

**Comment by rtivital** [comment]
To avoid inheritance, set shadow prop on the child Paper component. It is not planned to change this logic to keep component more performant:

```tsx
function NestedPapers() {
  return (
    <Paper p="md" withBorder shadow="md">
      Parent
      <Paper p="md" shadow="none">
        Child
      </Paper>
    </Paper>
  );
}
```
