### ISSUE TITLE
`Spotlight.Action` with `component={NavLink}` does not accept `to` prop

### ISSUE THREAD

**Issue by omerfarukdogan** [mantinedev/mantine#6749]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

When `Spotlight.Action` is being used with `component={NavLink}` prop, a TypeScript error is displayed for the `to` prop. The code works as expected when the error is ignored with `@ts-ignore`, but it should ideally work without needing this workaround.

![image](https://github.com/user-attachments/assets/3adb4de7-72b7-4b01-b6ad-a2b023582418)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior, Spotlight.Action component is not polymorphic, it does not accept props of other components. To learn about the difference between polymorphic and regular components, see https://mantine.dev/guides/polymorphic/
