### ISSUE TITLE
TimeInput: placeholder prop shown in usage example has no effect

### ISSUE THREAD

**Issue by julamb** [mantinedev/mantine#6758]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.9.0

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

The sample code for the `TimeInput` uses the placeholder props, but it has no effect.
https://mantine.dev/dates/time-input/#usage

### Possible fix

Update the docs to remove the misleading sample code?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by pratyush369** [comment]
Can this be assigned to me?

**Comment by harry-ignite** [comment]
In v8.3.8 `placeholder` is a valid property (inherited from Input), but has no visual effect.
Should be excluded from the type OR better - implemented, because it would make it consistent with other controls eg DateInput and provide better UX
