### ISSUE TITLE
[@mantine/core] SegmentedControl active button has a right border

### ISSUE THREAD

**Issue by timvandam** [mantinedev/mantine#676]
### What package has an issue

@mantine/core

### Describe the bug
The active button does not have a left border, but does have a border on the right (left-border of the next button) (after looking at the mantine code, it seems like this is unintentional) 

### In which browser did the problem occur

Google Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/serverless-cookies-m416d?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Fix the next button having a left-border (my first comment shows that this was already accounted for, but for some reason it doesn't work)

**Comment by timvandam** [comment]
After looking at the code, it seems like the intention is to remove the borders to the left and right of the active button

https://github.com/mantinedev/mantine/blob/974b251f4fad8feda6e1b67643b33f8de176e499/src/mantine-core/src/components/SegmentedControl/SegmentedControl.styles.ts#L120-L126

Currently, the right border is not removed. I will change the issue to that

**Comment by rtivital** [comment]
Thanks for reporting!

**Comment by timvandam** [comment]
Seems to be a problem with refs. In storybook the buttons all have `mantine-ref_control_4`, while `[\`& + .${control}\`]` resolves to `& + .mantine-ref_control_2`
