### ISSUE TITLE
Grid documentation outdated?

### ISSUE THREAD

**Issue by juan-manuel-alberro** [mantinedev/mantine#677]
### What package has an issue

@mantine/core

### Describe the bug

In the [documentation](https://mantine.dev/core/grid/#responsive-columns) for Grids, there's one example

```jsx
<Grid>
  <Grid.Col md={6} lg={3}>1</Grid.Col>
  <Grid.Col md={6} lg={3}>2</Grid.Col>
  <Grid.Col md={6} lg={3}>3</Grid.Col>
  <Grid.Col md={6} lg={3}>4</Grid.Col>
</Grid>
```
But it doesn't work since `<Grid.Col />` requires `span` prop based on the TS error

![image](https://user-images.githubusercontent.com/7114488/149626693-0e4c6a24-67cf-4d3d-b8f3-a7f9b7ed5ace.png)

Without the `span`, the content inside the `Grid.Col` is not rendered.

### In which browser did the problem occur

All

**Comment by rtivital** [comment]
Since version 3.6.0 span is no longer required and set to 12 by default – https://codesandbox.io/s/long-voice-ecpo4?file=/src/App.tsx

**Comment by juan-manuel-alberro** [comment]
Yes, I was using `3.5.4` and with `3.6` is no longer reproducible. Closing, thanks!

**Comment by ethanliu** [comment]
<img width="817" alt="Screen Shot 2022-03-30 at 21 43 13" src="https://user-images.githubusercontent.com/65704/160850450-4a81899f-462f-45c4-88ab-be7fa7e7c4dd.png">

If the `Grid.Col` component came from somewhere else, the grid will not render without `span` property.
Same behavior from v3.6.0 and v4.1.0.
