### ISSUE TITLE
Form validation resolvers in this repo should be removed

### ISSUE THREAD

**Issue by iharuya** [mantinedev/mantine#6770]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/form

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

None

### Describe the bug

According to documentation, the way to use zod with @mantine/form is to import the resolver in this way:

```ts
import { zodResolver } from 'mantine-form-zod-resolver';
```

However, resolvers are also in this repo so editors might suggest the following:

```ts
import { zodResolver } from '@mantine/form'
```

And I faced some issues since both interface and implementation are different in these two.

I do not know the background behind splitting these resolvers into separate repositories, but it is confusing to have them both  at the same time.

### Possible fix

Remove `packages/@mantine/form/src/resolvers` in this repo or exclude them in the published package.

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Form validation resolvers are kept in this repository to provide backwards compatibility. They are planned to be removed with the next major release. Until 8.0 is released it is not planned to remove them as it is a breaking change.
