### ISSUE TITLE
Safari Issue with light-dark() Function in Versions Below 17.5

### ISSUE THREAD

**Issue by seeratawan01** [mantinedev/mantine#6778]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Safari

## Description
We've identified an issue affecting Safari browsers versions below 17.5 when using the `light-dark()` color function. This impacts various components in Mantine, including but not limited to:

1. Border color on the Divider component
2. Modal background color disappearing in some cases

## Steps to Reproduce
1. Use Mantine components that utilize the `light-dark()` function for color management.
2. View the application in Safari version 17.4 or lower.

## Expected Behavior
Components should render correctly with appropriate colors in all supported browser versions.

## Actual Behavior
Components using `light-dark()` function display incorrectly or lose certain color properties in Safari versions below 17.5.

## Environment
- Mantine version: [Please specify]
- Safari version: Below 17.5

## Additional Context
- This issue is resolved when upgrading Safari to version 17.5 or higher.
- The root cause appears to be a bug in WebKit, documented here: https://bugs.webkit.org/show_bug.cgi?id=262914

## Impact
This issue affects users of older Safari versions, potentially a significant portion of the user base. Addressing this would improve cross-browser compatibility and user experience.

---

Please let me know if you need any additional information or if you'd like me to clarify any part of this report.

![image](https://github.com/user-attachments/assets/c7a9719d-898b-473f-bf2c-5d1e054dc417)

## Proposed Solution
We need Mantine to support older browser versions. Some possible approaches:
1. Implement a fallback mechanism for browsers that don't support `light-dark()`.
2. Provide alternative color management options for older browser versions.
3. Add clear documentation about this limitation and minimum supported browser versions.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`light-dark` is not a CSS function, it is provided by postcss-preset-mantine – https://mantine.dev/styles/postcss-preset/#light-dark-function
The source code of Mantine components does not include `light-dark`, it is transformed during the build step.

**Comment by seeratawan01** [comment]
Thank you for your response, @rtivital. I appreciate the clarification about `light-dark`. 

We are using the following PostCSS configuration:

```javascript
module.exports = {
  plugins: {
    autoprefixer: {},
    'postcss-import': {},
    'postcss-preset-mantine': {},
    'postcss-simple-vars': {
      // Mantine variables here...
    },
  },
};
```
And in our theme, we are using light-dark like this:
```
Divider: {
  styles: () => ({
    root: {
      borderColor: "light-dark(var(--mantine-color-gray-2), var(--mantine-color-dark-7))"
    }
  })
},
```

However, it seems that the light-dark function is not being transformed to CSS as expected. Could there be an issue with how the PostCSS plugins are processing this? Or is there something else I might be missing in my setup?

**Comment by rtivital** [comment]
postcss-preset-mantine functions can only be used in `.css` files, they cannot be used in js.

**Comment by seeratawan01** [comment]
What should be done here in the theme configuration for dark light custom settings?

**Comment by rtivital** [comment]
Use `classNames` instead of `styles`
