### ISSUE TITLE
Mantine Title does not inherit font family

### ISSUE THREAD

**Issue by NabilNYMansour** [mantinedev/mantine#6781]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The `<Title>` mantine component seems to have a different font and does not inherit from parent components.
```tsx
// layout.tsx
import { Protest_Guerrilla } from 'next/font/google'
const font = Protest_Guerrilla({
  weight: "400",
  subsets: ["latin"],
})

//...

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cx(classes.body, font.className)}>
        <MantineProvider defaultColorScheme="light" theme={theme}>
          <Navigation />
          <div className={classes.app}>
            {children}
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
```

```tsx
// page.tsx
import { Flex, Text, Title } from "@mantine/core";

export default async function HomePage() {
  return (
    <Flex direction="column" w="100%">
      <Text size="xl">Hello world</Text>
      <Title order={1}>Hello world</Title>
    </Flex>
  );
}
```
![Screenshot from 2024-09-05 18-15-17](https://github.com/user-attachments/assets/3163b3e8-f6ef-48b4-859b-8fe1784a874a)

### Possible fix

Using `ff="inherit"` fixed the problem. But it would be nice to have that as default.
```tsx
// page.tsx
import { Flex, Text, Title } from "@mantine/core";

export default async function HomePage() {
  return (
    <Flex direction="column" w="100%">
      <Text size="xl">Hello world</Text>
      <Title order={1} ff="inherit">Hello world</Title>
    </Flex>
  );
}
```
![image](https://github.com/user-attachments/assets/fcf19a57-284f-43f4-b338-3db0fbd37d45)

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
To change font-family in Mantine component see – https://mantine.dev/theming/typography/
