### ISSUE TITLE
Can't add CSS to mantine objects

### ISSUE THREAD

**Issue by Guarmanda** [mantinedev/mantine#6785]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Adding a CSS class to a mantine object won't change anything to it.
I don't really understand how to make it work on CodeSandbox 

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-q4dd5d?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0qqoejz0006356i66w7w5z6%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0qqoejy0002356iozejwt8q%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0qqoejy0003356itjbqj91a%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0qqoejy0005356i4luqy8nn%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0qqoejy0002356iozejwt8q%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qqoejy0001356irs6j43i9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cm0qqoejy0002356iozejwt8q%2522%252C%2522activeTabId%2522%253A%2522cm0qqoejy0001356irs6j43i9%2522%257D%252C%2522cm0qqoejy0005356i4luqy8nn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0qqoejy0004356iy0vcjaaf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm0qqoejy0005356i4luqy8nn%2522%252C%2522activeTabId%2522%253A%2522cm0qqoejy0004356iy0vcjaaf%2522%257D%252C%2522cm0qqoejy0003356itjbqj91a%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0qqoejy0003356itjbqj91a%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

![image](https://github.com/user-attachments/assets/4be8bc8e-1adf-43cf-b21e-0a24e854a7c5)
![image](https://github.com/user-attachments/assets/a01aafd0-f66f-4619-9731-ff3b893fd320)

**Comment by rtivital** [comment]
You are using the wrong prop. See Styles API documentation to learn more – https://mantine.dev/styles/styles-api/

**Comment by Guarmanda** [comment]
Well at first these wrong props were in a css file, but that wasn't doing anything either

**Comment by rtivital** [comment]
You can learn about all supported ways of applying styles on the linked page. `className` prop does not support style object, it accepts only a string with css class.
