### ISSUE TITLE
React Vite Mantine Boilerplate

### ISSUE THREAD

**Issue by d-agung-sungkono** [mantinedev/mantine#6786]
### Link to the repository on GitHub

https://github.com/d-agung-sungkono/react-vite-mantine-boilerplate

### Features of the template, describe how it is different from other templates

# React Vite Mantine Boilerplate

## Description
The **React Vite Mantine Boilerplate** is a ready-made development framework designed to help developers quickly build websites that combine both a landing page and a content management system (CMS) or admin dashboard within the same project. This boilerplate simplifies the development process by providing a pre-configured structure with essential features already in place.

### Key Features
- **Pre-built layout slicing**: The layout structure is already divided and prepared, allowing you to focus on content rather than layout design.
- **Role-based protected routes**: The routing system is configured to protect certain routes based on user roles (e.g., admin, regular users), ensuring security and proper access control.
- **Multi-language support**: The project is pre-configured to handle multiple languages, making it easy to localize your website for global users..
- **State management setup**: State management is already integrated, providing a solid foundation to manage the application’s state efficiently.
- **Reusable components**: A variety of commonly used UI components are included, so you can build your project faster without writing everything from scratch.

## Installation
To get started with **React Vite Mantine Boilerplate**, follow these steps:
1. Download or clone this repository:
```
git clone https://github.com/d-agung-sungkono/react-vite-mantine-boilerplate.git
```
2. Navigate into the project directory:
```
cd react-vite-mantine-boilerplate
```
3. Install dependencies:
```
npm i
```
4. Run the development server:
```
npm run dev
```
Your project will now run on a local development server and can be accessed through your browser.

## Usage
Once installed, you can immediately start adding content or new components to this boilerplate. Features like role-based route protection and localization are already set up and ready to go.

## Contributing
We welcome contributions from everyone. If you’d like to contribute, please follow these steps:
1. **Fork** this project
2. Create a new branch for the feature or fix you want to add:
```
git checkout -b feature/new-feature
```
3. **Commit** your changes:
```
git commit -m 'Add new feature'
```
4. **Push** to the new branch:
```
git push origin feature/new-feature
```
5. Open a **Pull Request** on GitHub for review.
All types of contributions are appreciated, from bug fixes and new features to improving documentation.

## License
This project is licensed under the MIT License.

**Comment by slk333** [comment]
should you mention that this template uses redux?

**Comment by d-agung-sungkono** [comment]
Yes I use redux

> should you mention that this template uses redux?

**Comment by rtivital** [comment]
Thanks for submitting a template, unfortunately it cannot be added as it is not very different from other templates and does not provide unique setup features.

**Comment by d-agung-sungkono** [comment]
Hi, thanks for your reply.

Actually, I'm glad that my code has been reviewed by
professional programmer like your team. Is it still an open opportunity for
me to develop something more with you guys?

Thanks

**Comment by rtivital** [comment]
You are welcome to contribute any bug fixed marked with "help wanted" tag
