### ISSUE TITLE
Customize icon for burger component

### ISSUE THREAD

**Issue by samuelbaizg** [mantinedev/mantine#6787]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

It is not a bug. I just request a new  requirement.   I don't like the default icon for Burger component, can you add a parameter to allow to change the open/close icon for Burger component ? 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Burger component is designed to work with specific elements, if you want a different icon, use ActionIcon instead.

**Comment by samuelbaizg** [comment]
Thanks for your quick reply.  I do like the burger open/close feature that ActionIcon does not support.  but the default icon of burger is not my favorite, so I want to change it conveniently instead developing open/close feature using ActionIcon by myself.
