### ISSUE TITLE
FileButton variant not a type but it works if you use it

### ISSUE THREAD

**Issue by kinoli** [mantinedev/mantine#6788]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

FileButton allows you to set `variant` prop, and it works fine, however, Typescript doesn't recognize it.

`Property 'variant' does not exist on type 'IntrinsicAttributes & FileButtonProps<false>'.`

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
FileButton does not render any nodes, it passes props down to child component. `variant` prop is not supported by FileButton, it is not a bug.
