### ISSUE TITLE
Pagination "getItemProps" not able to change label

### ISSUE THREAD

**Issue by waldimiro** [mantinedev/mantine#6789]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.11.1

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Thank you so much for the great work you do with Mantine!
I don't know if this is the right place to report the problem.

I have an array with letters:

letters = [“A”, “B”, “C”, ...]

Instead of numbers, I would like to display letters but it seems impossible with getItemProps(...)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.13.2](https://github.com/mantinedev/mantine/releases/tag/7.13.2)
