### ISSUE TITLE
Add fullscreen support for Loader component

### ISSUE THREAD

**Issue by erikdemarco** [mantinedev/mantine#6790]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

latest

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

when you navigate mantine.dev with very slow internet connection (try to emulate 2G/3G speed), you will see navigating between page doesnt show any loading feedback for client, they will keep waiting or clicking again and again because they dont know its still loading.

To fix this, we can use loader component but it can only be applied to children component, we doesnt have loader for fullscreen like:
https://mui.com/material-ui/react-backdrop/
https://primereact.org/blockui/

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/core/loading-overlay/
