### ISSUE TITLE
@mantine/carousel draggable option replaced with watchDrag

### ISSUE THREAD

**Issue by arslanovngc** [mantinedev/mantine#6791]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.0

### What package has an issue?

@mantine/carousel

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

In recent versions of embla-carousel, the draggable option seems to have been replaced with watchDrag option.

![image](https://github.com/user-attachments/assets/ce8adb2f-43b6-4e4a-9874-ce29b7fd7f1d)

Please can you add watchDrag option into @mantine/carousel. Draggable option is not working. If I will back to older versions of embla-carousel, I can not use latest features of embla-carousel

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
An upgrade to embla v8 is scheduled to be released with v8 release of Mantine. It is not planned to change dependency version in minor releases as it is a breaking change.
