### ISSUE TITLE
cannot find tablist in the package

### ISSUE THREAD

**Issue by amyming112** [mantinedev/mantine#6798]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Error: Could not find the module ".../node_modules/@mantine/core/esm/components/Tabs/Tabs.mjs#Tabs#Panel" in the React Client Manifest. This is probably a bug in the React Server Components bundler. 

This happened after I updated Next yesterday. Only happens to one page, not the other pages that also have other Tab components in so far. The error goes away and the page renders fine once I remove tabs.panel and tabs.list.

Using next 14.2.9
React 18
issue happens on both safari and chrome.
running in dev

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/guides/next/#compound-components-in-server-components
