### ISSUE TITLE
Bar chart console errors

### ISSUE THREAD

**Issue by crowbait** [mantinedev/mantine#6800]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/charts

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Using bar charts, the following errors pop up in the console (I'm aware the `defaultProps` one is known, I'm including it for completeness):

```
Warning: XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at XAxis2
    at svg
    at Surface
    at div
    at ChartLayoutContextProvider2
    at CategoricalChartWrapper
....
```
```
Warning: YAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at YAxis2
    at svg
    at Surface
    at div
    at ChartLayoutContextProvider2
    at CategoricalChartWrapper
...
```
```
Warning: React does not recognize the `parentViewBox` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `parentviewbox` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at text
    at BarLabel
    at Label
    at g
    at LabelList
    at g
    at Bar2
...
```
```
Warning: React does not recognize the `textBreakAll` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `textbreakall` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at text
    at BarLabel
    at Label
    at g
    at g
    at Bar2
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Issue with recharts, not Mantine. See https://github.com/recharts/recharts/issues/3615

**Comment by ckifer** [comment]
Recharts maintainer here. This is taken care of in recharts alpha as stated in the linked issue. I was waiting for R19 to release until releasing 2.13 but we'll see what that looks like. 

As for the other errors unrelated to the defaultProps warnings I can check to see if some unwanted props are getting spread onto the text elements in Label. This could also be a custom implementation thing on this side, not sure yet.

**Comment by ckifer** [comment]
Looks like the other two warnings are on Mantine, not recharts
https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/charts/src/BarChart/BarChart.tsx#L118-L130

@rtivital

**Comment by Kenzo-Wada** [comment]
@ckifer 

thanks! Ive made a PR! 
https://github.com/mantinedev/mantine/pull/6810
