### ISSUE TITLE
Number Input setSelectionRange Error

### ISSUE THREAD

**Issue by enchorb** [mantinedev/mantine#6803]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Firefox

### Describe the bug

More details along with the fix in this issue: https://github.com/alpinejs/alpine/issues/401

setSelectionRange will throw an exception on a number input

### Possible fix

Fix Here: https://github.com/alpinejs/alpine/issues/401 

Should be applied to the `adjustCursor` function in the `NumberInput` file

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I do not see how the issue in Alpine is related to NumberInput component, please provide a sandbox that throws error.

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide more details.
