### ISSUE TITLE
@mantine/carousel embla-carousel-react v8 support

### ISSUE THREAD

**Issue by enchorb** [mantinedev/mantine#6804]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Add `watchDrag` option instead of `draggable` if users are using  `embla-carousel` v8+. 

In [v8.0.0-rc01](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc01) `draggable` was renamed. Other than that everything seems to be working the same as `v7`. For now added a patch to allow use of v8.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
This would be a breaking change and I suggest releasing at v8 of mantine, not Now.

**Comment by Kenzo-Wada** [comment]
I thought this is a breaking change...

https://github.com/davidjerleke/embla-carousel/issues/594

**Comment by rtivital** [comment]
Duplicate of #6791
