### ISSUE TITLE
OnChange callback doesnt being called when setting defaultValue and deleting it on first time

### ISSUE THREAD

**Issue by daniel-aziz** [mantinedev/mantine#6805]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

OnChange callback doesn't being called when setting defaultValue and deleting it on first time.
im using react hook form to handle form in my app, but when setting  defaultValues, and input is populated, when deleting it for the first time the onChange callback doesnt invoke.

```
import "@mantine/core/styles.css";
import { MantineProvider, TextInput } from "@mantine/core";
import {
  Controller,
  FormProvider,
  useForm,
  useFormContext,
} from "react-hook-form";
export default function App() {
  const methods = useForm({
    defaultValues: async () => {
      // Simulating data fetching with a promise and timeout
      const data = new Promise((resolve) => {
        setTimeout(() => {
          resolve({ name: "defaultValue" });
        }, 4000);
      });
      return data;
    },
  });

  return (
    <MantineProvider>
      <FormProvider {...methods}>
        <InputComponent />
      </FormProvider>
    </MantineProvider>
  );
}

const InputComponent = () => {
  const { control } = useFormContext();

  return (
    <div>
      <label>Name:</label>
      <Controller
        control={control}
        name="name"
        render={({ field }) => (
          <TextInput
            defaultValue={field.value}
            onChange={(e) => {
              console.log("onChange invoked");
              console.log(e.target.value);
            }}
          />
        )}
      />
    </div>
  );
};

```

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-66vysd?file=%2Fsrc%2FApp.tsx%3A1%2C1-53%2C1&workspaceId=0bdb6b5c-75b0-41ff-ab06-3dc9acd83d3c

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
If you use Controller component of react-hook-form, it is required to use controlled Mantine components. 

https://codesandbox.io/p/sandbox/mantine-react-template-forked-vnf7cd?file=%2Fsrc%2FApp.tsx%3A43%2C29
