### ISSUE TITLE
data-autofocus not working in Modal with buttons

### ISSUE THREAD

**Issue by Meierschlumpf** [mantinedev/mantine#6808]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1 in code sandbox / 7.12.2 locally

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When opening a Modal (which has FocusTrap) by clicking on the button to open it `data-autofocus` does not work.
It does work for input fields (tested with `TextInput`)
And (whats weird) it does work when clicking the button by keyboard

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-845ssk

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It works as expected, the button component receives focus. The focus ring is visible only when the user navigates with keyboard. If you want to change focus ring styles, follow https://mantine.dev/theming/theme-object/#focusclassname

https://github.com/user-attachments/assets/684d355c-a1ca-4bb2-b2cc-58e044809709
