### ISSUE TITLE
TextInput selection handles unresponsiveness when used in modal dialog

### ISSUE THREAD

**Issue by tompetk** [mantinedev/mantine#6813]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

When TextInput is being used in modal, its text selection handles become unresponsive on iOS Safari.

I can select text, but cannot drag neither of text selection handles.

![IMG_2348](https://github.com/user-attachments/assets/35877f4e-d200-460a-8317-cf8fc8ae9e14)

This can be reproduced with official modal example: at: https://mantine.dev/core/modal/

Any clue how I could work this around?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This logic is controlled by react-remove-scroll library.
If you want to change this behavior, pass options to `removeScrollProps` prop of the Modal component.
For options reference, see https://github.com/theKashey/react-remove-scroll?tab=readme-ov-file#usage
It is not planned to be changed on the library side.
