### ISSUE TITLE
DateInput picker jumps when number of rows (weeks) in calendar changes

### ISSUE THREAD

**Issue by Runess** [mantinedev/mantine#6816]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

DatInput calendar jumps when number of rows / weeks changes. So when you click back or forward, you often miss your click or click out of the calendar completely.  

https://github.com/user-attachments/assets/4134281c-f550-49da-ba1b-3fa0ccba4bf7

https://mantine.dev/dates/date-input/ 

### Possible fix

A possible fix could be to have a prop called fixedRows=bool 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by stefanzmf** [comment]
A quick fix for this would be to add this to the `DatePickerInput` component. Not really the most elegant way to fix it, but I guess it s enough given the fact this problem happens only when the popover it s shown above the input

```
        styles={{
          levelsGroup: {
            height: '296px',
          },
        }}
```

PS: The hardcoded height above it s for the default size, `sm`.

**Comment by rtivital** [comment]
https://mantine.dev/dates/getting-started/#consistent-weeks

**Comment by Runess** [comment]
Awesome, thank you!
