### ISSUE TITLE
Errors are discarded if using custom path error in zod's refinment

### ISSUE THREAD

**Issue by nikita-sisutech** [mantinedev/mantine#6817]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/form

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Firefox

### Describe the bug

Consider following setup 
```tsx
import { useForm, zodResolver } from '@mantine/form';
import { z } from 'zod';

function Button() {
    const schema = z.object({
        first: z.string(),
        second: z.string(),
    }).refine(() => false, { path: 'first' });
        
    const form = useForm({
        mode: 'uncontrolled',
        initialValues: {},
        validate: zodResolver(schema),
    });
        
    function handleSubmit() {
        console.debug(form.validate();)
    }

      return <button onClick={handleSubmit}>Click</button>
  );
}
```

Console output will be empty, even though validation returns errors. 

### Possible fix

The problem is that after validation library check that all error paths matched current path: https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/form/src/validate/validate-field-value.ts#L15

For now there is only one workaround I found is to store errors in additional state and reset them to form: 
```tsx
import { useForm, zodResolver } from '@mantine/form';
import { z } from 'zod';
import { useState } from 'react';

function Button() {
    const [errors, setErrors] = useState<Record<string, any>>();
    const schema = z.object({
        first: z.string(),
        second: z.string(),
    }).refine(() => false, { path: 'first' });
        
    const form = useForm({
        mode: 'uncontrolled',
        initialValues: {},
        validate: (values) => {
            const result = zodResolver(schema)(values);
            if (Object.keys(result)) {
                setErrors(result);
            }
            return result;
        },
    });
    
    useEffect(() => {
        form.setErrors(errors);
    }, [errors]);
    
    function handleSubmit() {
        console.debug(form.validate();)
    }

    return <button onClick={handleSubmit}>Click</button>
}
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction.
