### ISSUE TITLE
Notifications containerWidth style is not applied

### ISSUE THREAD

**Issue by jacobwilson41** [mantinedev/mantine#6822]
```tsx
<Notifications position="top-right" limit={2} />
notifications.show({ message: "This is a test notification", autoClose: false });
```

https://github.com/user-attachments/assets/2dfa15b8-1b99-4d83-a854-0afb0895e7f9

**Comment by Kenzo-Wada** [comment]
I am wondering if there is something wrong with the style of the parent element. Can you provide a repro environment for us to investigate?

**Comment by rtivital** [comment]
Make sure that:
- You have followed installation instructions correctly and imported package styles – https://mantine.dev/x/notifications/
- You do not have any styles that overriding Mantine styles

If that does not help, reopen the issue with a sandbox with a reproduction.
