### ISSUE TITLE
DateTimePicker's hidden value does not respect DatesProvider timezone

### ISSUE THREAD

**Issue by dylantf** [mantinedev/mantine#6828]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/dates

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When setting a timezone through DatesProvider, it appears that the internal conversion is done correctly on the underlying Date object for the input's value. However, when inspecting the hidden input, there is a further conversion being done based on the browser's timezone, which results in the value being incorrect when submitting a plain HTML form.

Example:
- My browser's timezone is UTC +2
- I set the timezone to UTC in DatesProvider
- In a DateTimePicker, I select the a date with the time 21:00
  - The value is correctly displayed by default in the visible input as 21:00
  - The underlying Date object is correctly stored (with a serialized value of `2024-09-17T21:00:00.634Z`)
- The **hidden** input's value is **incorrectly** set to `2024-09-17T19:00:00.634Z` (2 hours off)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
Can you provide a reproduction sandbox?

**Comment by dylantf** [comment]
Sure, here's a sandbox: https://codesandbox.io/p/sandbox/mantine-react-template-forked-pm3mxg

You may need to adjust the timezone based on where you are to see the problem.

- My browser is using CEST (+2 UTC)
- The timezone in the sandbox is set to America/Los_Angeles (-7 UTC)
- I pick a datetime of 2024-09-18 00:00
- The form value is correctly set to that date with 07:00
- The hidden input's value is incorrectly set to 2023-09-17 22:00, 9 hours off from the time they picked

<img width="1175" alt="Screenshot 2024-09-19 at 4 21 37 PM" src="https://github.com/user-attachments/assets/148058d5-fcec-452a-b1ac-91c04b6ed342">

**Comment by mkf62** [comment]
I'm experiencing a them same or similar issue trying to use UTC with the DatePickerInput component (I am located in eastern TZ). [Codesandbox](https://codesandbox.io/p/sandbox/mantine-react-template-forked-pm3mxg?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm1fopp5p00063b6lx37mijby%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm1fopp5p00023b6l7a0fygg7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm1fopp5p00033b6lt7ymo7i5%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm1fopp5p00053b6lgl3alwmr%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm1fopp5p00023b6l7a0fygg7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm1fopp5p00013b6l8ox9s5mu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cm1fopp5p00023b6l7a0fygg7%2522%252C%2522activeTabId%2522%253A%2522cm1fopp5p00013b6l8ox9s5mu%2522%257D%252C%2522cm1fopp5p00053b6lgl3alwmr%2522%253A%257B%2522id%2522%253A%2522cm1fopp5p00053b6lgl3alwmr%2522%252C%2522activeTabId%2522%253A%2522cm1foq6fq00143b6lmu70lyli%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm1fopp5p00043b6l6yda6dnx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm1foq6fq00143b6lmu70lyli%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm1fopp5p00033b6lt7ymo7i5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm1fopp5p00033b6lt7ymo7i5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

![Screenshot 2024-09-23 at 8 28 15 PM](https://github.com/user-attachments/assets/765828e8-e075-4fec-89cc-8cda1a631e30)
