### ISSUE TITLE
Tooltip on Switch not showing up

### ISSUE THREAD

**Issue by josch0** [mantinedev/mantine#6829]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

If i place a Tooltip around a Switch, the Tooltip won't show up.
(see Sandbox)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-gnll7r

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
Here you go!

https://mantine.dev/core/switch/#with-tooltip
