### ISSUE TITLE
Getting Notifications.module.css.mjs.map not found and Cannot render a <style> error!

### ISSUE THREAD

**Issue by MahirAlam** [mantinedev/mantine#6830]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

# It seems mantine is trying to render styles tag. I guess something like this
![Screenshot 2024-09-17 205352](https://github.com/user-attachments/assets/e40235e8-0d43-46f7-b525-4703bc839f67)
### It's giving the following error...
![Screenshot 2024-09-17 204854](https://github.com/user-attachments/assets/2d38afd0-a487-4667-94d2-8b549519ccaf)a
![Screenshot 2024-09-17 204912](https://github.com/user-attachments/assets/64191a18-45dd-407f-93ca-85e0e593b690)
![Screenshot 2024-09-17 204941](https://github.com/user-attachments/assets/d6fedfc0-13c1-4e58-9aae-a448aa330b29)
![Screenshot 2024-09-17 205004](https://github.com/user-attachments/assets/9eeb787a-fbe2-4cc5-abe0-d7d769902e7f)
![Screenshot 2024-09-17 204837](https://github.com/user-attachments/assets/3ff00fbd-c359-4fab-b24b-981da9727526)

Note: you can't run this in codesandbox.io. So please clone the repository and use **`npm i --legacy-peer-deps`** when installing dependencies.

### If possible, include a link to a codesandbox with a minimal reproduction

https://github.com/MahirAlam/tera-tok

### Possible fix

I guess adding precedence="default" will solve the issue?

### Self-service

- [x] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
maybe this template will help you: https://github.com/mantinedev/next-app-template

**Comment by MahirAlam** [comment]
> maybe this template will help you: https://github.com/mantinedev/next-app-template

Thank you for your reply!
I have found the problem.

**_Pease help me update the docs._**

### **In next js,**
`<ColorSchemeScript />`
Should be used like this or it will give error (at least hydration error)
```
"use client";

import { ColorSchemeScript, MantineProvider as Provider } from "@mantine/core";
import Head from "next/head";

import { theme } from "@/utils/theme";

const MantineProvider = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <ColorSchemeScript nonce="8IBTHwOdqNKAWeKl7plt8g==" />
      </Head>
      <Provider theme={theme}>{children}</Provider>
    </>
  );
};

export default MantineProvider;
```

Note: **use client** is a must
