### ISSUE TITLE
useHotkeys does not listen to Spacebar key `" "`

### ISSUE THREAD

**Issue by Jacouille** [mantinedev/mantine#6831]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

The useHotkeys hook does not listen to the `" "` spacebar key. It seems that during the key parsing, we trim spaces causing the resulting space key to be no key. The `Spacebar` key code was used in older browsers but now they seem to all use the `" "` key code

### Possible fix

An easy fix would be to add an option in the `HotkeyItemOptions` to prevent trimming while parsing the key. This way we'd maintain backward compatibility and the space key would work.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
I think `"space"` works fine:)

**Comment by Jacouille** [comment]
Yeah you're right! I can't find the documentation on MDN saying the `space` code works as well. Thanks!
