### ISSUE TITLE
Calendar component aria labeling wrong and props to fix it don't work

### ISSUE THREAD

**Issue by astolman** [mantinedev/mantine#6835]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The Calendar component's forward and back buttons do not have proper aria labeling. Whether or not you use the nextLabel and previousLabel props, lighthouse is reporting that there is no accessible name for the buttons. The docs https://mantine.dev/dates/calendar/?t=props say that these nextLabel and previousLabel props should set these aria labels, but they aren't working.

Below is a screenshot of the lighthouse report. I have also included a code sandbox which i was able to run lighthouse over and replicate the issue.
![image](https://github.com/user-attachments/assets/fdd6fc4b-009f-40eb-9a10-bef0f75a0e8d)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-vstc7z

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
You can use `ariaLabels` props to set arialabels!

https://mantine.dev/dates/calendar/?t=props

**Comment by astolman** [comment]
> You can use `ariaLabels` props to set arialabels!
> 
> https://mantine.dev/dates/calendar/?t=props

I couldnt find any docs that described what type this prop takes. I guess I'll go take a look in the repo. Will update here with the results.

**Comment by astolman** [comment]
The ariaLabels prop does work, thank you! I think the broken props should probably just be removed or fixed and the docs updated.

**Comment by Kenzo-Wada** [comment]
@astolman 

YEAH, you are so right! I just now created a PR for the correction! :ok:
