### ISSUE TITLE
[Feature Request]  Support for Svelte?

### ISSUE THREAD

**Issue by elibroftw** [mantinedev/mantine#684]
### Usage example, including component/hook API

Mantine is super nice and combining it with svelte would be amazing in terms of Performance and Aesthetics. 

### Do you want to contribute this feature and create a pull request

No

**Comment by rtivital** [comment]
I do not use Svelte and currently not planning to add Svelte support, it will take at least 4 months of full-time work to migrate all components.

**Comment by elibroftw** [comment]
I mean of course I'm not expecting immediately. I'm talking about long term 1 year
