### ISSUE TITLE
Mantine LineChart Breaks with Custom Colors in Theme

### ISSUE THREAD

**Issue by sam-cuboh** [mantinedev/mantine#6849]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/charts

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Using the Mantine LineChart breaks when you are using custom colors (a theme with the MantineProvider). In the code sandbox below, the chart renders when the theme is removed. However it also renders fine with the theme when using a mantine BarChart. So it seems like there is a bug where the LineChart isn't able to read in the theme colors/variables properly. 

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-cmyfvt

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
I was unable to run the sandbox environment you provided, can you please fix it?

![Screenshot from 2024-09-19 22-16-40](https://github.com/user-attachments/assets/a369cdd1-8ce1-4b9d-8b49-5bb8b4b1baea)

**Comment by sam-cuboh** [comment]
> I was unable to run the sandbox environment you provided, can you please fix it?
> 
> ![Screenshot from 2024-09-19 22-16-40](https://private-user-images.githubusercontent.com/79452224/369006518-a369cdd1-8ce1-4b9d-8b49-5bb8b4b1baea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjE1OTAsIm5iZiI6MTcyNjc2MTI5MCwicGF0aCI6Ii83OTQ1MjIyNC8zNjkwMDY1MTgtYTM2OWNkZDEtOGNlMS00YjlkLThiNDktNWJiOGI0YjFiYWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE1NTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYzJjYzc4YmNmZmQ5Yzc2N2NhZWVjMDBhMDMzMmJkNjI4YWVlYzc3OWExYTdkZmJlNDliZjkxM2YzOTg5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QNQkAWVkL27If7D6ELEx6i8DPBoKPH7CKvhiEfgI2OU)

hi! that is the problem i'm facing. if you remove the theme, from the mantine provider it will work. Also if you switch the chart from a line chart to a bar chart it will also work. I have removed the "theme" now for you though

**Comment by Kenzo-Wada** [comment]
@sam-cuboh 

I see, I understand completely!

I also figured out the cause of the bug: each of the theme's colors must be passed an array of 10 values!

eg.) from your code,
```js
const theme = createTheme({
    // Color overrides
    colors: {
      blue: [
        colors.blue.x1,
        colors.blue.x1,
        colors.blue.x2,
        colors.blue.x3,
        colors.blue.x4,
        colors.blue.x5,
        colors.blue.x6,
        colors.blue.x7,
        colors.blue.x8,
        colors.blue.x9,
        colors.blue.x10,
      ],
```

**Comment by sam-cuboh** [comment]
@Kenzo-Wada ahh okay i will add other values thank you! But I am curious/confused why it would work for the BarChart with missing values.
