### ISSUE TITLE
AppShell causes hydration errors when using Suspense

### ISSUE THREAD

**Issue by RabeeAbuBaker** [mantinedev/mantine#6883]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.0

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

All

### Describe the bug

Using AppShell with Suspense inside causes the following error:

```
Uncaught Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.
```

I saw there was a related issue ([#5979](https://github.com/mantinedev/mantine/issues/5979)) that was fixed earlier, but it's still happening in the latest version (7.13.0). 

![image](https://github.com/user-attachments/assets/5a1b59ad-803d-459d-b814-41b33bbca6cd)

### If possible, include a link to a codesandbox with a minimal reproduction

https://github.com/RabeeAbuBaker/remix-defer/tree/simple-defer-app-shell

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by RabeeAbuBaker** [comment]
Is there anything we can do locally to overcome this? @rtivital 
This is preventing us from using defer which has a huge impact on user experience. 
Thanks!

**Comment by rtivital** [comment]
I do not know, I've never used Suspense

**Comment by RabeeAbuBaker** [comment]
> I do not know, I've never used Suspense

Since this was looked into and fixed before, is it possible to look into fixing this again? Or providing the functionality to disabled what's breaking it.

**Comment by rtivital** [comment]
Okay, I'll leave this issue with "help wanted" label, you and anyone else are welcome to research it and submit a PR with a fix

**Comment by RabeeAbuBaker** [comment]
@rtivital I've opened a PR that fixes the issue.
I've investigated the issue locally and the change resolved the error. I have added a screen recording for before and after the fix. Please review.

**Comment by rtivital** [comment]
Great, I will review and merge change with the next patch release
