### ISSUE TITLE
Tooltip.Floating doesn't allow openDelay

### ISSUE THREAD

**Issue by alexis-exaud** [mantinedev/mantine#6895]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Pretty much what it says in title. In addition, adding a wrapping `<Tooltip.Group />` component with an `openDelay` prop does not fix the issue and there's also no `openDelay` prop in `<Tooltip.Floating />` itself

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
There is no `openDelay` prop in Tooltip.Floating component because it does not support such feature. It is not the issue with the library, it is just not supported by this component.

**Comment by alexis-exaud** [comment]
Let's say the "intended" behaviour isn't very thoughtful...
