### ISSUE TITLE
Update dependencies for @mantine/eslint-config

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#690]
As of today (v3.6.1) if you install `@mantine/eslint-config` with `npx install-peerdeps @mantine/eslint-config --dev` it installs quite outdated dependencies.

Here is the output from `npm outdated`:
<img width="471" alt="Screen Shot 2022-01-17 at 10 01 58" src="https://user-images.githubusercontent.com/44101337/149783318-27ec7040-74f0-444e-982b-9b00a11c0267.png">

For instance, the outdated `eslint` may cause issues when installing other eslint plugins intended for newer versions.

**Comment by rtivital** [comment]
Already tried that, it does not work with newer dependencies, so we will use this configuration for now
