### ISSUE TITLE
[Template] A better way to integrate tailwind with mantine

### ISSUE THREAD

**Issue by songkeys** [mantinedev/mantine#6912]
### Link to the repository on GitHub

https://github.com/songkeys/next-app-mantine-tailwind-template

### Features of the template, describe how it is different from other templates

I saw there is already a tailwind template from the community https://github.com/hasib-rashid/next-app-tailwind-template but it's not perfect and well-mantianed.

This new template uses CSS layers along with a utility-level constructed Tailwind preset <https://github.com/songkeys/tailwind-preset-mantine> to ensure seamless integration without any style conflicts.

See also: https://github.com/orgs/mantinedev/discussions/1672#discussioncomment-10777394

**Comment by rtivital** [comment]
Thanks for submitting the template, it will be added with the next patch.
