### ISSUE TITLE
Defining Tree's data inside a React component together with useTree causes infinite re-render

### ISSUE THREAD

**Issue by mohammad-reza-rahbar** [mantinedev/mantine#6916]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

I spend hours to figure out defining Tree's data inside a React component when using `useTree` hook causes an infinite re-render!

```
import { Tree, useTree } from '@mantine/core';

export function Demo() {
  console.log('render');
  
  const tree = useTree();
  
  const data = [
    {
      label: 'mantine',
      value: 'mantine',
    },
  ];

  return <Tree data={data} tree={tree} />; 
}
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by mikhail-molchanov** [comment]
Most likely caused by some state change that happens upon tree controller initialization, in combination with the `data` array that is re-created from scratch on every render.  Little you can do about it except for moving your data outside the component to have a stable reference.

**Comment by rtivital** [comment]
To avoid this issue, you need to memoize the data – 

```tsx
const data = useMemo([
    {
      label: 'mantine',
      value: 'mantine',
    },
  ], []);
```

**Comment by niiloArction** [comment]
Also ran into this issue. Memoizing the data indeed helped me past, but this was difficult to realize from user point of view and was a blocking performance issue.

**Comment by warpdesign** [comment]
Also stumbled upon the problem: `useMemo` is not really working since I'm getting the state from MobX and have no idea when it's updated. Also noticed that hovering tree elements also causes re-renders.
