### ISSUE TITLE
DatePicker numberOfColumns issue when disabled future

### ISSUE THREAD

**Issue by vacuumdreams** [mantinedev/mantine#6919]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.1

### What package has an issue?

@mantine/dates

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

I'm using the DateRange picker to have a range selection for past dates. The UX becomes non-ideal when I want to disallow future dates from being selected, because the end date of the range is the one being used to determine which month to show in the first column. I'd want to put the month for the end date to the last shown column ideally, because the future is irrelevant and disabled in this use-case, we are forcing the user to do extra work here and navigate back. 

<img width="570" alt="Screenshot 2024-09-30 at 11 41 59" src="https://github.com/user-attachments/assets/c3a8ea66-2bd6-48ab-a423-99d499556eb0">

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/7ljjqv

### Possible fix

1. if there is a maxDate provided, use the last shown column to display the end date's month in.
2. provide a controlled way of handling the shown columns?

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You can control the displayed date – https://mantine.dev/dates/date-picker/#controlled-date

**Comment by vacuumdreams** [comment]
> You can control the displayed date – https://mantine.dev/dates/date-picker/#controlled-date

Ah, I assumed "controlled date" has to do with using the Date Picker value in a controlled way. This seems to help, I can achieve what I need to by adding a date. Thanks a lot for pointing this out!
