### ISSUE TITLE
[@mantine/core] NumberInput handlersRef type incorrect

### ISSUE THREAD

**Issue by timvandam** [mantinedev/mantine#692]
### What package has an issue

@mantine/core

### Describe the bug

The type of the `handlersRef` prop is incorrect.

The following documentation page features `handlersRef`.

This demo is also not type safe due to the onClick methods for the - and + buttons (see the codesandbox's complaints). The sizes are also mismatched in the preview code and the actual code (42 vs 36)
https://mantine.dev/core/number-input/#custom-incrementdecrement-controls

### In which browser did the problem occur

Google Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/magical-shape-lwnzd

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

- Change the type's generic to include undefined
- Change the docs to use optional chaining, and fix the sizes in the sample code

**Comment by timvandam** [comment]
If someone wants to fix their first issue this should be an easy one

**Comment by sohamsshah** [comment]
I would like to work on this issue @timvandam

**Comment by rtivital** [comment]
Feel free to submit a PR

**Comment by timvandam** [comment]
Go for it! 😃 @sohamsshah

**Comment by rtivital** [comment]
Fixed in 3.6.3
