### ISSUE TITLE
DatePicker Bug Specifically On Mobile Browser

### ISSUE THREAD

**Issue by enaluz** [mantinedev/mantine#6921]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.1

### What package has an issue?

@mantine/dates

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When on a mobile browser specifically (only tested on Chrome), input "0" as the first character, causes different behavior than inputting "0" on web. On web, the date gets set to "01-01-01", but on mobile web, it gets set to "00-1-12-31".

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/dates/date-input

You can also see that the label in the calendar picker is different on web vs mobile web.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I do not understand the issue, please explain it in more details. Also please explain why it is an issue for you.

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide further details.
