### ISSUE TITLE
Radio.Card warning:  <button> cannot be a descendant of <button> 

### ISSUE THREAD

**Issue by samuelbaizg** [mantinedev/mantine#6928]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Mantine is definitely excellent UI library, I like it very much. 

I got below warning 

```
app-index.js:33 Warning: In HTML, <button> cannot be a descendant of <button>.
This will cause a hydration error.
    at button
```

when I add ActionIcon inside Radio.Card, for example, 

```
<Radio.Card>
       <Group >
        <Radio.Indicator />
              <ActionIcon>
                  <IconX />
              </ActionIcon>
             <Text>description</Text>
          </Group>
<Radio.Card>

```

by the way, I want to embeded button inside RadioGroup as blow image shows: 
![image](https://github.com/user-attachments/assets/df8a9332-e55e-4545-941e-00059014aac7)

I dive into the source, I guess the reason is  RadioCard uses button element as ref. 

Could you please fix this issue ? 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The error message is correct, you cannot put ActionIcon inside Radio.Card – both components use button as the root element. To avoid this issue, render your ActionIcon next to Radio.Card in the dom tree and give it absolute position to replicate the desired layout.
