### ISSUE TITLE
TagsInput controlled - incorrect onChange callback

### ISSUE THREAD

**Issue by matanmaze** [mantinedev/mantine#6935]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

None

### Describe the bug

When working in the controlled option the wrong onChange callback is called with the removed value, instead of the new one, attached a video

https://github.com/user-attachments/assets/246ad905-78e3-45cf-ae82-e82ee253c3e7

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-tagsinput-controller-9r7lty

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by dxanh97** [comment]
Might related to this PR here: https://github.com/mantinedev/mantine/pull/6922

**Comment by rtivital** [comment]
Fixed in [7.13.2](https://github.com/mantinedev/mantine/releases/tag/7.13.2)
