### ISSUE TITLE
Nested NavLink - chevron rtl wrong direction

### ISSUE THREAD

**Issue by nadavhalfon** [mantinedev/mantine#6939]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

In RTL mode, the nested NavLink chevron is heading to the wrong position, as you can see here it's happening not only in my codebase but also in the docs:
![image](https://github.com/user-attachments/assets/19f85d00-9947-4697-b932-1021fcb32827)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.13.3](https://github.com/mantinedev/mantine/releases/tag/7.13.3)
