### ISSUE TITLE
Textarea Width Shifts on safari 18

### ISSUE THREAD

**Issue by Snivio** [mantinedev/mantine#6941]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.1.5

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

**Description**:
I'm encountering an issue where the width of the Mantine Textarea component is fluctuating unexpectedly in Safari 18. This behavior is inconsistent across different screen sizes and browser states.

**Steps to Reproduce:**

Create a React application using Mantine.
Incorporate a Textarea component into your layout.
Test the component's behavior in Safari 18.
Observe the inconsistent width changes, particularly when resizing the browser window or performing actions like typing or pasting text.

**Expected Behavior:**
The Textarea's width should remain consistent and responsive based on its defined styling or layout constraints.

**Actual Behavior:**
The Textarea's width is shifting erratically, leading to visual inconsistencies and potential user experience issues.
**

https://github.com/user-attachments/assets/958247bf-6c81-43b0-ac4c-53dacb89d76b

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I cannot reproduce the issue on mantine.dev website in Safari 18.


https://github.com/user-attachments/assets/9733be41-bf30-4cab-80cc-d86fd0b5c738

**Comment by Snivio** [comment]
Seems to be fixed when i upgraded to latest version of mac os seems like a minor safari version issue

**Comment by rtivital** [comment]
Okay, great
