### ISSUE TITLE
right/left section icon on button not working

### ISSUE THREAD

**Issue by amyming112** [mantinedev/mantine#6942]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

all the right section and left section icons have disappeared (the button seems to be making space for it, but the icon is not loading).

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction

**Comment by amyming112** [comment]
My codesandbox preview always have issues but this is the code (I have updated to v7.13 and the issu persists). 

`import { Button } from "@mantine/core";
import View from "../../../components/icons/view";
import "@mantine/core/styles.css";

export default function test() {
    return (
        <>
            <h1>Test</h1>

            <Button leftSection={<View />}>test</Button>
        </>
    );
}
`

this is the result

<img width="129" alt="Screenshot 2024-10-04 at 23 53 19" src="https://github.com/user-attachments/assets/49790de6-ed67-4213-b9c0-25edfbc13da4">

the icon is black and renders if I put it outside the button like <View />

**Comment by rtivital** [comment]
It is hard to tell what is not working without reproduction. Make sure that your `<View />` component root element has width and height styles.

**Comment by amyming112** [comment]
Hi - i think i figured this out. I use heroicon, up until the latest update, it is the className = size that controls the size of the icon. This came with thier copy SVG and it doesn't have height and width.  With the new update, I need to manually add in height and width to control the icon size, the size function that came with heroicon no longer works. once i add in height and width it works now. Thanks!
