### ISSUE TITLE
Nested NavLink - collapse animation frozen

### ISSUE THREAD

**Issue by iamyoki** [mantinedev/mantine#6943]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

![iShot_2024-10-04_23 33 50](https://github.com/user-attachments/assets/e2adc7c2-03eb-4dec-8a92-51d6d3e8de87)

Minimum reproduce link: https://codesandbox.io/p/sandbox/x5dnkl

## Unexpected
Nested Navlink collapse animation get frozen when wrap in a flex column + overflow:auto container

## Details
```jsx
<MantineProvider>
  <div
    className="App"
    style={{
      height: 200,
      backgroundColor: "gainsboro",
    }}
  >
    <div
      className="navigation"
      style={{
        display: "flex",
        flexDirection: "column",
        overflow: "auto",
        height: "inherit",
      }}
    >
      <NavLink href="/" label="Posts">
        <NavLink label="All" />
        <NavLink label="Published" />
        <NavLink label="Drafts" />
        <NavLink label="Archieved" />
        <NavLink label="Deleted" />
      </NavLink>
      <NavLink href="/" label="Discussions">
        <NavLink label="All" />
        <NavLink label="Published" />
        <NavLink label="Drafts" />
        <NavLink label="Archieved" />
        <NavLink label="Deleted" />
      </NavLink>
    </div>
  </div>
</MantineProvider>
```

div.navigation contains all NavLinks, it scrolls inside if height exceeded. But with flex column + overflow:auto it always frozen.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/x5dnkl

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by minosss** [comment]
If `Collapse` is inside a flex container, can set `flexShrink=0`.

```tsx
<NavLink
  styles={{
    collapse: { flexShrink: 0 },
  }}
>
  ...
</NavLink>
```

or wrap it in a div

```tsx
<div class="flex-and-scroll">
  <div>
    <NavLink>
    <NavLink>
  </div>
</div>
```


https://github.com/user-attachments/assets/df78ff37-fbda-44f5-a29d-317891ea1ba5

**Comment by rtivital** [comment]
@minosss thanks for the research, I've checked and it fixes the issue in the sandbox.
