### ISSUE TITLE
Anchor colour prop doesn't work for all colours

### ISSUE THREAD

**Issue by Billy-** [mantinedev/mantine#6944]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

Using the `c` prop from `Text` component on `Anchor` only works with some colours. Of the handful I have tested, `dimmed` and `red.6` work, but `body` and `error` don't.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-6kng69

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
Hey @Billy- , I dont see any Anchor on your reproduction url, can you fix it?

**Comment by Billy-** [comment]
> Hey @Billy- , I dont see any Anchor on your reproduction url, can you fix it?

@Kenzo-Wada sorry, fixed!

**Comment by Billy-** [comment]
Hmm, if you don't create your own theme, isn't Mantine providing a default one? I have dark and light colour schemes working. Also, isn't `dimmed` a theme colour, which does work in my repro?

**Comment by rtivital** [comment]
Mantine does not handle `error` and `body` values in `c` prop in any component. If you need to reference these values, you can use CSS variables directly: `c="var(--mantine-color-error)"`
