### ISSUE TITLE
Customize styles for different parts in `NumberFormatter` component

### ISSUE THREAD

**Issue by mnakhli** [mantinedev/mantine#6945]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

Latest

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

It is not possible to apply custom styles to different parts of the component. For example, I would like to style the `suffix` separately from the `value`, but currently, there doesn't seem to be an option to do so.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This feature is not supported and is not planned to be supported due to how react-number-format works, if you want to add different styles for suffix, render it separately from the component.
