### ISSUE TITLE
Dropzone should automatically set a data-attribute when disabled

### ISSUE THREAD

**Issue by pgrones** [mantinedev/mantine#6946]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/dropzone

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Currently `Dropzone` only adds a data-attribute when the input is `loading`. The documentation is asking the developer to implement their own disabled state if the loading state isn't enough. However I would argue that setting a `disabled` data-attribute when the `disabled` flag is set would help a lot in styling non-loading, disabled states.

To give a more tangible example, we override a lot of Mantine's default css behaviors in a custom package. When a developer uses the package and marks the `Dropzone` as `disabled` they would also need to set `mod={{ disabled }}` to make the css overrides work, as there is no way to differentiate between a disabled Dropzone and an active one.

### Possible fix

Simply add disabled to the list of data-attributes
```tsx
<Dropzone
  mod={[
    {
      accept: isDragAccept,
      reject: isDragReject,
      idle: isIdle,
      loading,
      disabled,
      'activate-on-click': activateOnClick,
    },
    mod,
  ]}
>
```

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by Aldomf** [comment]
Hello @pgrones, can i be assigned this task?

**Comment by pgrones** [comment]
> Hello @pgrones, can i be assigned this task?

Sure I don't mind who fixes the issue as long as there is no argument against implementing it
