### ISSUE TITLE
The px function lacks support for dynamic font size changes in the body

### ISSUE THREAD

**Issue by Ketamin** [mantinedev/mantine#6949]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

The `px` function has a hardcoded font size of 16px. This creates an issue when the default font size of the body or html is changed, leading to incorrect calculations

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior, as it is not possible to calculate value based on the html element font-size:
- The function must work the same way on client and server and server does not have access to DOM API
- font-size can have a dynamic value depending on the viewport size (for example media query) or a value that cannot be interpreted correctly in js (for example `min(10vw, 80px)`)
