### ISSUE TITLE
Inconsistent Date Format and Day Suffix for Japanese Locale in DateTimePicker and DatePickerInput

### ISSUE THREAD

**Issue by matamatanot** [mantinedev/mantine#6950]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/dates

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

## Description
There is an inconsistency in the date format between the `DateTimePicker` and `DatePickerInput` components when the locale is set to "ja" (Japanese).

In Japan, the standard date format is Year/Month/Day. The `DatePickerInput` correctly follows this format, but the `DateTimePicker` incorrectly displays the date in Day/Month/Year format. This should be consistent with the Japanese standard.

Additionally, for the DatePickerInput, the day suffix should be "日" (meaning "day" in Japanese), but it is currently missing.

## Steps to reproduce:

Import "dayjs/locale/ja"
Use `<DateTimePicker label="Pick date" locale="ja" />` and `<DatePickerInput label="Pick date" locale="ja" />`.
Observe the difference in the date format between the two components.
Check the missing "日" suffix in `DatePickerInput`.

## Expected behavior:

Both components should follow the Year/Month/Day format for the Japanese locale.
The DatePickerInput should display the day suffix "日".

## ScreenShot

![localhost_5173_dashboard_window_01J9NTZP1E6ZKBEHCDGQX1EPCF](https://github.com/user-attachments/assets/d14f18d4-d312-4537-bda9-68a2509e937b)

expected: 2024/10/19 or 2024年10月19日

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
Hi @matamatanot 

Thanks for the report!  (Also thanls from japan! :japan: )

This is the specification of the dayjs locale conversion, the dayjs format function converts for each yyyy, mm, dd, but it doesn't format the whole thing. FYI: https://day.js.org/docs/en/display/format
I think it would be possible to use the [localizedFormat](https://day.js.org/docs/en/plugin/localized-format) plugin, but it would be a breaking change, so it may be difficult to implement right away.


It may be difficult for us to fix this immediately, but I think we can use the `valueFormat` props.

e.g.

```js
import { DateTimePicker } from '@mantine/dates';

function Demo() {
  return (
    <DateTimePicker
      valueFormat="YYYY/MM/DD hh:mm A" // or maybe YYYY年MM月DD日 hh時mm分
      label="Pick date and time"
      placeholder="Pick date and time"
    />
  );
}
```

```js
import { DatePickerInput } from '@mantine/dates';

function Demo() {
  return (
    <DatePickerInput
      valueFormat="YYYY/MM/DD"
      type="multiple"
      label="Pick date"
      placeholder="Pick date"
    />
  );
}
```

**Comment by matamatanot** [comment]
@Kenzo-Wada 
`valueFormat` works as intended. Thanks!
Since the commonly used 24-hour time format in Japan didn't work, I use "A" instead.

**Comment by rtivital** [comment]
@matamatanot is your issue resolved?

**Comment by matamatanot** [comment]
@rtivital 

> I think it would be possible to use the [localizedFormat](https://day.js.org/docs/en/plugin/localized-format) plugin, but it would be a breaking change, so it may be difficult to implement right away.

If implemented as above, the problem would be completely solved. It is still possible to achieve this using `valueFormat`, but it would be helpful if it is clearly stated in the Document.
