### ISSUE TITLE
Reset does not reset inputs to their initial values when form is uncontrolled

### ISSUE THREAD

**Issue by thenick775-TST** [mantinedev/mantine#6955]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.13.2

### What package has an issue?

@mantine/form

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When using an uncontrolled mantine form, all reset hooks provided by `useForm` do not reset inputs to their `initialValues`.

Navigate into the code sandbox, enter text into the form fields

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/yk2rtr

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This happens because you did not set `key` like it is shown in the documentation – https://codesandbox.io/p/sandbox/mantine-uncontrolled-reset-forked-cjzsjj

**Comment by thenick775-TST** [comment]
Thank you, realized too late that there isn't an explicit callout that this won't work without the key!
