### ISSUE TITLE
MultiSelect doesn't allow 'null' value

### ISSUE THREAD

**Issue by RenaudLN** [mantinedev/mantine#6956]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

MultiSelect does not accept `null` as value, which requires to be converted to `undefined` upstream.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/silent-dew-c7dvxr

### Possible fix

MultiSelect should accept null value and treat it the same way as undefined

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`undefined` value means that the component is uncontrolled. `null` is not supported by MultiSelect, the empty value for this component is an empty array. To fix the issue, you need to `<MultiSelect value={yourValue === null ? [] : yourValue} />`. It is not planned to be changed in the library.

**Comment by RenaudLN** [comment]
Is there any good reason `null` is accepted in `Select` and the various inputs but not `MultiSelect`?
In our case, the data coming from the backend is nullable for those fields. Having to transform it to undefined or an empty array on every `MultiSelect` seems strange.

**Comment by rtivital** [comment]
`null` is supported in Select component as an empty controlled value. Empty controlled value for MultiSelect is an empty array.
