### ISSUE TITLE
Namespaced components not working in Next.js server components

### ISSUE THREAD

**Issue by tatibouet** [mantinedev/mantine#6962]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Firefox

### Describe the bug

When using namespaced components in Next.js page.tsx, it fails with the error:

```
 ⨯ Internal error: Error: Could not find the module "[...]/node_modules/@mantine/core/esm/components/Grid/Grid.mjs#Grid#Col" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
```

`<List>` and `<Grid>` work well but whenever I add `<List.Item>` or `<Grid.Col>` I get the error.

Did I miss a configuration? I tried with Next.js 14 and 15.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/inspiring-paper-h7xjdk?workspaceId=415aab69-ec9b-4b1d-9f66-784500b60112

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by AzzouQ** [comment]
You can't use compound components in server components.

See https://mantine.dev/guides/next/#compound-components-in-server-components for further explenations.

Either add 'use client' on top of your file, or use `ComponentXXX` instead of `Component.XXX` (`GridCol` instead of `Grid.Col` in your example).
