### ISSUE TITLE
Add blur prop to Overlay component

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#697]
### Usage example, including component/hook API

Overlay components such as `<Overlay>`, `<Drawer>`, `<Modal>`, `<LoadingOverlay>` should have a prop to enable blurred overlay to give them a sleek modern look.

Example: see drawer/burger menu in [Tailwind docs](https://tailwindcss.com/docs/configuration) on narrow (mobile) screen.

### Possible implementation – describe how the feature can be implemented

```
/* fallback for Firefox and legacy browsers */
.backdrop-blur {
  background-color: rgba(0, 0, 0, 0.2);
}

/* if backdrop is supported - Chrome, Safari, Edge, etc. */
@supports (backdrop-filter: blur(4px)) {
  .backdrop-blur {
    background-color: rgba(0, 0, 0, 0.2);
    backdrop-filter: blur(4px);
  }
}
```

### Do you want to contribute this feature and create a pull request

No

**Comment by rtivital** [comment]
You can add filter via sx like any other style:
```tsx
<Overlay sx={{ backdropFilter: 'blur(4px)' }} />
```

**Comment by albertbronsky** [comment]
> You can add filter via sx like any other style:
> 
> ```tsx
> <Overlay sx={{ backdropFilter: 'blur(4px)' }} />
> ```

Sure, but having that as a prop would be handy, just like `<Overlay>` has `gradient` and `opacity` props know.

**Comment by wes337** [comment]
There are 2 problems with implementing this prop:

1. Firefox does not support `backdrop-filter`. [There are some workarounds though](https://codepen.io/jonitrythall/pen/GJQBOp).
2. We cannot mix `opacity` and `backdrop-filter`. The opacity must be set in in the background color, as in `background-color: rgba(0, 0, 0, 0.3);`.  So simply adding `backdrop-filter` to the `sx` in the Overlay won't work.

I have found a solution, where we wrap the Box in the Overlay with another Box, which is completely transparent and only applies the blur filter.

![image](https://user-images.githubusercontent.com/9464690/154911451-575ede78-00da-4399-898a-c4eb9ba22dd1.png)

It also works as expected when used with the gradient prop.
![image](https://user-images.githubusercontent.com/9464690/154911602-1213316d-a9c6-4276-a0da-89f477e3df79.png)

**Comment by rtivital** [comment]
Great, thanks for inverstigation

**Comment by wes337** [comment]
I could open a PR and implement this if you'd like

**Comment by rtivital** [comment]
Yeah, sure, please use `dev` branch as target

**Comment by jameszhang-a** [comment]
Hey I think you forgot to close this issue! @rtivital
