### ISSUE TITLE
Select component when dropdown opens with keyboard down it visually selects first element, but doesn't really

### ISSUE THREAD

**Issue by rhyek** [mantinedev/mantine#6978]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

- Click on select
- Dropdown opens
- No option is selected
- Press escape
- Press keyboard down
- Dropdown opens
- First option is selected
- Press enter
- Nothing happens
- Press keyboard down again
- No visual change - first option is still selected
- Press enter
- First option is now the value of the select

This is reproducible on the documentation page for the component: https://mantine.dev/core/select/

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/core/select/

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by MariaBanaszkiewicz** [comment]
Hi! I have opened a pull request resolving the issue :)
