### ISSUE TITLE
BarChart: vertical orientation calls valueFormatter on the wrong axis

### ISSUE THREAD

**Issue by sedrik** [mantinedev/mantine#6979]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/charts

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

When I change the orientation to vertical the valueFormatter is called on the wrong axis. So my series names get NaN values in the y axis.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-ff7ncg

### Possible fix

Currently I work around the issue by checking the type of the value in the valueFormatter and only formatting numbers.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.13.3](https://github.com/mantinedev/mantine/releases/tag/7.13.3)

**Comment by sedrik** [comment]
Thanks for the quick resolution. Mantine is awesome! :)
