### ISSUE TITLE
TimeInput doesn't trigger onChange handler

### ISSUE THREAD

**Issue by jerguslejko** [mantinedev/mantine#698]
### What package has an issue

@mantine/dates

### Describe the bug

When I do

```tsx
<TimeInput onChange={(value) => alert(value)} />
```

the `onChange` handler is never triggered. I'd expect the `onChange` handler to be called on `blur` and when pressing `return`

### In which browser did the problem occur

chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/pensive-hugle-0mlk2?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Thanks for reporting, it will be fixed in next patch
