### ISSUE TITLE
LineChart withPointLabels: ValueFormatter not applied to point label values

### ISSUE THREAD

**Issue by me-gusta-v** [mantinedev/mantine#6989]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When using "withPointLabels" in the Line/Area/Composite chart, the points are not formatting using the provided valueFormatter.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-r386fh

### Possible fix

Pass the valueFormatter to the PointLabel component

Implemented in fork @ https://github.com/mantinedev/mantine/commit/a1a8fdcfa8aaade2e12c91f177f1ab2cb109374c

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.14.1](https://github.com/mantinedev/mantine/releases/tag/7.14.1)
