### ISSUE TITLE
withBarValueLabel not displaying in correct positions in BarChart

### ISSUE THREAD

**Issue by namakshenas** [mantinedev/mantine#6991]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/charts

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Hi,

I'm trying to use the `withBarValueLabel` property of BarChart. The value labels are not placed correctly. Here is the snapshot of the issue:

<img width="1151" alt="Screenshot 2024-10-17 at 16 08 52" src="https://github.com/user-attachments/assets/9a66280c-c8b2-494f-875f-e0b48151cc44">

Here is the working example in `@mantine/charts`:

```
<BarChart
          h={300}
          data={[
            { dmu: 'dmu1', 'Efficiency score': 100, Status: 'Efficient', color: '#32CD32' },
            { dmu: 'dmu2', 'Efficiency score': 78, Status: 'InEfficient', color: '#FFA500' },
            { dmu: 'dmu3', 'Efficiency score': 100, Status: 'Efficient', color: '#32CD32' },
            { dmu: 'dmu4', 'Efficiency score': 100, Status: 'Efficient', color: '#32CD32' },
            { dmu: 'dmu5', 'Efficiency score': 89, Status: 'InEfficient', color: '#FFA500' },
            { dmu: 'dmu6', 'Efficiency score': 95, Status: 'InEfficient', color: '#FFA500' },
          ]}
          withBarValueLabel
          orientation="vertical"
          gridAxis="y"
          barProps={{ radius: 5 }}
          dataKey="dmu"
          series={[{ name: 'Efficiency score' }]}
          tickLine="none"
/>
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by fsd-niraj** [comment]
I'd like to work on this. Please assign if not picked up.

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix

**Comment by fsd-niraj** [comment]
![image](https://github.com/user-attachments/assets/852291df-7f2e-411c-8233-843c9c96a48f)

Please let me know if this looks good? I'll quickly raise my PR.

**Comment by namakshenas** [comment]
> ![image](https://github.com/user-attachments/assets/852291df-7f2e-411c-8233-843c9c96a48f)
> 
> 
> 
> Please let me know if this looks good? I'll quickly raise my PR.

Thanks. But they should be aligned right, where just after each bar ends in the right hand side.

**Comment by fsd-niraj** [comment]
![image](https://github.com/user-attachments/assets/fc93db60-4fad-4562-a177-52d71eb4093d)

How about this?

**Comment by namakshenas** [comment]
> ![image](https://github.com/user-attachments/assets/fc93db60-4fad-4562-a177-52d71eb4093d)
> 
> ![image](https://github.com/user-attachments/assets/3b6290ab-2fce-4f84-94b2-aba59c404a42)
> 
> 
> 
> 
> 
> How about this?

Looks great. But consider another scenario: what if the user chooses the bar width to be thin. In that case, the values should be placed outside of the bar.

**Comment by fsd-niraj** [comment]
![image](https://github.com/user-attachments/assets/274ae394-49b1-494c-8b89-9cc0f271cbf2)

![image](https://github.com/user-attachments/assets/5f31d663-4716-4d41-a841-d4561e11e943)

![image](https://github.com/user-attachments/assets/d53d01a9-4e4f-4156-8a24-d52e06287412)

Hey, Let me know if this looks good to you.

**Comment by namakshenas** [comment]
> ![image](https://github.com/user-attachments/assets/274ae394-49b1-494c-8b89-9cc0f271cbf2)
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/5f31d663-4716-4d41-a841-d4561e11e943)
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/d53d01a9-4e4f-4156-8a24-d52e06287412)
> 
> 
> 
> Hey, Let me know if this looks good to you.

Well done!
I think you can now suggest your PR.

**Comment by fsd-niraj** [comment]
PR: https://github.com/mantinedev/mantine/pull/7011

**Comment by fsd-niraj** [comment]
Hey, I saw that the test case failed, is it still mergeable? I don't see any other problem than linting and prettier.

**Comment by rtivital** [comment]
To merge the PR, all tests must pass. To continue working on your PR, add more commits to the same branch and push them. You can run tests locally with `npm test` command.

**Comment by fsd-niraj** [comment]
Hey @rtivital , heres my new PR, please check.
https://github.com/mantinedev/mantine/pull/7042
