### ISSUE TITLE
An open Drawer with`hiddenFrom` property prevents scrolling

### ISSUE THREAD

**Issue by kenteramin** [mantinedev/mantine#6995]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.3

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

A `Drawer` with `opened=true` that is not visible on the page due to the `hiddenFrom` attribute still prevents scrolling

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is expected behavior. `hiddenFrom` prop hides element with CSS only. It does not prevent any JavaScript logic from executing. It is not planned to change this behavior.
