### ISSUE TITLE
NumberInput allows undesired empty strings

### ISSUE THREAD

**Issue by buchananwill** [mantinedev/mantine#6999]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.3

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

1. There is no option to disallow empty values for number inputs
2. Attempting to set the field value (with a controlled input) using onBlur does not update the UI

As a result, if the user deletes all the content from a NumberInput via backspace **and** then also presses delete, the field can seemingly be left blank, even when this is not allowed and min/max values have been supplied.

This was my workaround:

```
          <Controller
            name={'cycleLengthInWeeks'}
            control={control}
            render={({ field }) => (
              <NumberInput
                clampBehavior={'strict'}
                label={'Cycle Length in Weeks'}
                min={1}
                max={52}
                value={field.value}
                onBlur={(blurAction) => {
                  blurAction.currentTarget.value = String(field.value);
                }}
                onChange={(value) =>
                  field.onChange(isNumber(value) && value > 0 ? value : 1)
                }
              />
            )}
          />
```

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
1. It is intended behavior, empty string is used to indicate the empty value of the component.
2. Currently, NumberInput component cannot be fully controlled due to limitations of the underlying number formatting library, it is tracked separately in this issue – https://github.com/mantinedev/mantine/issues/6796

**Comment by buchananwill** [comment]
Thanks for the quick response.
