### ISSUE TITLE
MantineProvider causes hydration error on Nextjs 15

### ISSUE THREAD

**Issue by davidchalifoux** [mantinedev/mantine#7008]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.3

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Next.js just released version 15 today.
Testing Mantine with version 15 is resulting in a hydration error caused by `<MantineProvider>`, seemingly because the error suppression isn't working. I've included a minimal reproduction on StackBlitz.

Thanks for your work!

<img width="576" alt="Screenshot 2024-10-21 at 4 50 40 PM" src="https://github.com/user-attachments/assets/a9da3900-f4d3-4600-be41-a99ed624095b">

### If possible, include a link to a codesandbox with a minimal reproduction

https://stackblitz.com/edit/stackblitz-starters-avcjyw?file=app%2Flayout.tsx

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by davidchalifoux** [comment]
Looks like the error emitted by Next is in a slightly different format so [suppressNextjsWarning()](https://github.com/mantinedev/mantine/blob/6a067f1c90159b6c4b89586df3bcc98aea1aeecd/packages/%40mantine/core/src/core/MantineProvider/suppress-nextjs-warning.ts#L2) won't catch it.

In the meantime I was able to get rid of the error by manually adding `data-mantine-color-scheme="light"` to `<html>` in my root layout so there isn't a mismatch:
```tsx
<html lang="en" data-mantine-color-scheme="light">
```

This is fine for me because the project is only using the light scheme.

**Comment by Pirulax** [comment]
Interesting, according to the docs `data-mantine-color-scheme` should be set by `MantineProvider`. ([Source](https://mantine.dev/theming/color-schemes/#data-mantine-color-scheme-attribute))

**Comment by AIEPhoenix** [comment]
just add suppressHydrationWarning to html tag

**Comment by VibingCreator** [comment]
Getting rid of `<ColorSchemeScript />` from the head tag solves issues for me.

**Comment by alimehasin** [comment]
This PR might solve be relevant #5199

**Comment by rtivital** [comment]
To fix the issue, set `suppressHydrationWarning` on the `html` tag.

example of the full file `layout.tsx` in app router:

```tsx
import '@mantine/core/styles.css';

import React from 'react';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { theme } from '../theme';

export const metadata = {
  title: 'Mantine Next.js template',
  description: 'I am using Mantine with Next.js!',
};

export default function RootLayout({ children }: { children: any }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
```

Example for pages router in `_document.tsx` file:

```tsx
import { Head, Html, Main, NextScript } from 'next/document';
import { ColorSchemeScript } from '@mantine/core';

export default function Document() {
  return (
    <Html lang="en" suppressHydrationWarning>
      <Head>
        <ColorSchemeScript />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
```

**Comment by rtivital** [comment]
The issue has been resolved, the documentation has been updated to support next 15 release. All templates have been updated to next 15. You can find full working examples in the corresponding templates. Updated documentation can be found here – https://mantine.dev/guides/next/

**Comment by matheusvellone** [comment]
@rtivital does adding the `ColorSchemeScript` on `body` instead of `head` affects something? (cant test it right now)

Personaly, I would like not to supress the warnings if possible, as it might be reporting that something is possibly wrong.

**Comment by Juanryhn** [comment]
> The recommended way suppresses warning on the html element only. Hydration warning on the html element is completely useless – it can be produced by any browser extension that modifies html attributes, for example Grammarly, LanguageTool, etc.
> 
> Putting `ColorSchemeScript` in the body does not change anything – you get the error because an attribute is added to html element, not because there is an extra script in the head.

@rtivital I'm using next v14 and put it on body `<ColorSchemeScript/>` seperate it from root layout, and add `use client` on top of file it works fine. But when I add `suppressHydration` on `html` tag it doesn't change anything I still got the error. Do I have to upgrade next ?

**Comment by Leejha** [comment]
@rtivital 
Is it better to use `MantineProvider` and `ColorSchemScript` in client components or insert `suppressHydrationWarning` properties in html tags??

**Comment by rtivital** [comment]
It is not relevant client or server. Follow the guide, it will work correctly.
