### ISSUE TITLE
Missing documentation for `useCallbackRef`

### ISSUE THREAD

**Issue by lvchenyang** [mantinedev/mantine#7009]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.3

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

I originally wanted to write my own `useCallbackRef`, but when I was importing it, I found that `@mantine/hooks` had already exported this hook. However, I couldn’t find any documentation on how to use this hook in the Mantine UI documentation.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`useCallbackRef` is an internal hook that is used in some other Mantine hooks and components. Currently, it is not planned to expose it as a part of the public API.

**Comment by sontran0410** [comment]
Could you share why you decided not to export it? It seems like a very useful hook for many scenarios

**Comment by rtivital** [comment]
It is explained in the message above
