### ISSUE TITLE
Issue with CompositeChart

### ISSUE THREAD

**Issue by plantaest** [mantinedev/mantine#7010]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.3

### What package has an issue?

@mantine/charts

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I use CompositeChart with the following code:

```tsx
<CompositeChart
  h={185}
  data={chartData}
  dataKey="date"
  maxBarWidth={30}
  withRightYAxis
  series={[
    { name: 'views', label: 'Số lượt xem', color: 'yellow.8', type: 'area' },
    {
      name: 'edits',
      label: 'Số sửa đổi',
      color: 'rgba(18, 120, 255, 0.2)',
      yAxisId: 'right',
      type: 'bar',
    },
  ]}
  curveType="monotone"
  gridAxis="none"
/>
```

But the Chrome console shows this error:
<img width="1728" alt="Screenshot 2024-10-22 at 16 53 47" src="https://github.com/user-attachments/assets/a223cc86-bb55-4775-b2be-5361237422af">

I think we should add `key` prop to this line: https://github.com/mantinedev/mantine/blob/6a067f1c90159b6c4b89586df3bcc98aea1aeecd/packages/%40mantine/charts/src/CompositeChart/CompositeChart.tsx#L289

Regards,
Plantaest.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by mariakax3** [comment]
Hello, I'd love the opportunity to contribute to this issue.

**Comment by rtivital** [comment]
You are welcome to submit a PR with a fix

**Comment by Kenzo-Wada** [comment]
@plantaest  BTW, The UI design of your product is aaaaawesome!!! nice job!

**Comment by mariakax3** [comment]
@rtivital Could I request permission to push changes to the repository? Currently I'm encountering 403 response

**Comment by plantaest** [comment]
@mariakax3 I suggest you create a fork. You can read more about it here: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project.
