### ISSUE TITLE
Deprecated method of importing sass in Vite

### ISSUE THREAD

**Issue by DreamerGp2024** [mantinedev/mantine#7023]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

the documentation here https://mantine.dev/styles/sass/#usage-with-vite indicates the required import method, but when updating sass to version 1.80.4, this import method becomes deprecated

Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
1 │ @import "/src/_mantine";body {
  │         ^^^^^^^^^^^^^^^
  ╵
    src\index.scss 1:9  root stylesheet

### Possible fix

change additional data like this
additionalData: `@use "_mantine" as mantine;`,

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by borstessi** [comment]
Same behavior here.

**Comment by poloagustin** [comment]
same warning appears on nextjs apps with `sassOptions.prependData` set to `'@import "./_mantine.scss";'`. If there's a change that prevents this warning to appear, it'd be great to add it to the [docs](https://mantine.dev/styles/sass/#usage-with-nextjs)

**Comment by rtivital** [comment]
Fixed in [7.13.5](https://github.com/mantinedev/mantine/releases/tag/7.13.5). The documentation has been updated for Vite and Next.js.

**Comment by patrick-b6n** [comment]
Leaving this here for everyone else, after spending too much time to find the solution:

After updating `preprocessorOptions` in `vite.config.js` you have to adjust the usage of your CSS variables.
They are now scoped in `mantine`.
e.g.
```diff
-@media (max-width: $mantine-breakpoint-md) {
+@media (max-width: mantine.$mantine-breakpoint-md) {
```

Otherwise your build will fail with
```
npm run build

> mantine-vite-template@0.0.0 build
> tsc && vite build

vite v6.0.11 building for production...
✓ 108 modules transformed.
x Build failed in 389ms
error during build:
[vite:css] [sass] Error: Undefined variable.
  ╷
2 │   @media (max-width: $mantine-breakpoint-md) {
  │                      ^^^^^^^^^^^^^^^^^^^^^^
  ╵
  C:\Development\vite-template\src\global.scss 2:22  root stylesheet
file: C:/Development/vite-template/src/global.scss
```

**Comment by 4ortytwo** [comment]
@patrick-b6n legend. thanks a lot for this one. 

improved it a bit and it doesn't require adding `mantine.` before breakpoints.

```ts
 sassOptions: {
    implementation: 'sass-embedded',
    additionalData: `@use "mantine" as *;`,
    includePaths: [path.join(process.cwd(), '_mantine')],
  },
```
