### ISSUE TITLE
[FileInput] Required property not enforced when submitting forms

### ISSUE THREAD

**Issue by mazyar-kawa02** [mantinedev/mantine#7024]
### Dependencies check up

- [x] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.5.3

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

When using the FileInput component from Mantine, the required property does not seem to be enforced during form submission. Even if the required attribute is set, users can submit the form without selecting a file, and no validation error is triggered.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
FileInput component does not support native browser validation, it is a custom component that is built with `button` html element. It is not planned to introduce this feature in the future.
