### ISSUE TITLE
Hover color override for Mantine (v7) Button not working

### ISSUE THREAD

**Issue by ellieatmerqury** [mantinedev/mantine#7027]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.3

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I have this simple button using react and Mantine for testing an issue I have (v7.13.3)

```
import React from "react";
import ReactDOM from "react-dom/client";
import { MantineProvider, Button } from "@mantine/core";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <MantineProvider>
    <React.StrictMode>
      <Button
        size="md"
        styles={{
          root: {
            backgroundColor: 'blue',
            '&:hover': {
              backgroundColor: 'red',
            },
          },
        }}
      >
        TEST BUTTON
      </Button>
    </React.StrictMode>
  </MantineProvider>
);
```

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-grhyrs?workspaceId=3958677b-be1b-4518-bb39-dd3a350ac2f7

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
- https://help.mantine.dev/q/how-to-add-hover-styles
- https://help.mantine.dev/q/nested-inline-styles

**Comment by ellieatmerqury** [comment]
> * https://help.mantine.dev/q/how-to-add-hover-styles
> * https://help.mantine.dev/q/nested-inline-styles

thanks, totally missed the second link!
