### ISSUE TITLE
Blocked aria-hidden on a <button> element because the element that just received focus must not be hidden from ....

### ISSUE THREAD

**Issue by mauserez** [mantinedev/mantine#7035]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Hi i caught the bug when i used Mantine 7.13.4
How i can fix it.
I caught it when i use DateTimePicker.
When i clicked on DateTimePicker input.
At the screen you can see upper div with data-portal=true has aria-hidden="true" and of course all of his children focusable elements like button invoke error.

![2024-10-25 16 32 57](https://github.com/user-attachments/assets/c9f3d4cb-f2e1-4902-8703-d828e8d89930)
![2024-10-25 16 38 28](https://github.com/user-attachments/assets/c11dbe00-8bba-4437-aae1-9b4e5cd63ce2)

Structure was Drawer->Form->DateTimePicker.
Please if u have a decision or advice give it to me.

Many thanks

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.14.1](https://github.com/mantinedev/mantine/releases/tag/7.14.1)
