### ISSUE TITLE
onChange of Select is improperly typed for TypeScript

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#704]
### What package has an issue

@mantine/core

### Describe the bug

Using the ['Controlled' example from docs](https://mantine.dev/core/select/#controlled):
```
import { useState } from 'react';
import { Select } from '@mantine/core';

function Demo() {
  const [value, setValue] = useState('');
  return <Select value={value} onChange={setValue} />;
}
```

TypeScript raises this error for `onChange` prop:

<img width="887" alt="Screen Shot 2022-01-19 at 06 28 30" src="https://user-images.githubusercontent.com/44101337/150113135-4334dfcb-db7c-47c9-9786-34214081d33a.png">

### In which browser did the problem occur

Node

**Comment by rtivital** [comment]
Controlled example is correct when `strict` option is set to false. you will need to set type manually in your useState:

```tsx
import { useState } from 'react';
import { Select } from '@mantine/core';

function Demo() {
  const [value, setValue] = useState<string | null>(null);
  return <Select value={value} onChange={setValue} />;
}
```
