### ISSUE TITLE
Gutter does not show when background color is set on GridCol elements

### ISSUE THREAD

**Issue by Lovor01** [mantinedev/mantine#7041]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Using Grid in server component (`import { Grid, GridCol } from '@mantine/core'`) produces different html output compared to examples in mantine docs. This is the reason why gutter does not show. Specifically, GridCol component does not produce inner divs, which are necessary for gutter to work. That is, because GridCol uses padding internally to achieve gutter spacing.

I would also recommend modernizing this component by applying css `gap` property instead relying on paddings, this would enable simpler markup of the component.

### Possible fix

Check GridCol component to produce inned divs, similar to example in docs.

Currently, as a workaround, I found a not so convenient fix to wrap inner content of  GridCol in additional `div` and style GridCol root element with `display: flex` and inner `div` with `flex-grow: 1`, and give background color to this inner div.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior, gutter is implemented as column padding, to set the background, put a div element inside the column and set background there.
