### ISSUE TITLE
Charts are not displaying in next 15, mantine 7.13.4

### ISSUE THREAD

**Issue by adlid** [mantinedev/mantine#7044]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/charts

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

i cant view my barChart component in latest version with next 15 in mantine charts

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by adlid** [comment]
![Uploading Снимок экрана 2024-10-27 в 22.33.10.png…]()

**Comment by adlid** [comment]
<img width="644" alt="Снимок экрана 2024-10-27 в 22 33 29" src="https://github.com/user-attachments/assets/7ea5c307-ee3a-4532-8a38-bf681a9fab30">
<img width="1063" alt="Снимок экрана 2024-10-27 в 22 33 10" src="https://github.com/user-attachments/assets/0e01c1d8-9c48-4511-a21c-31a23551841b">

**Comment by rtivital** [comment]
See https://github.com/recharts/recharts/issues/5146

**Comment by adlid** [comment]
@rtivital  thnks

**Comment by rtivital** [comment]
Fixed in [7.13.5](https://github.com/mantinedev/mantine/releases/tag/7.13.5). The `recharts` package has been updated to the latest version, for react-is resolution solution, see recharts issue.
