### ISSUE TITLE
useForm resets component that is not registered inside the form

### ISSUE THREAD

**Issue by sosafe-uliana** [mantinedev/mantine#7047]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.1

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

useForm resets component that is not registered inside the form. I am using uncontrolled mode and I have a complex form and a Switch component inside. Switch is not part of the form and is only used to change the view. it works as expected but when I reset the form, the state of the switch resets too, although it shouldn't

I have reproduced it in a codesandbox.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-f7qx6w

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`@mantine/form` package works as intended. If you want to reset only fields that are related to useForm hook, do not use reset event of html form element and just call form.reset() directly on the button click. See example – https://codesandbox.io/p/sandbox/mantine-react-template-forked-krv2x4?file=%2Fsrc%2Fmy-form.tsx%3A7%2C10
