### ISSUE TITLE
[Feature Request] Table border option

### ISSUE THREAD

**Issue by neotericmatrix** [mantinedev/mantine#705]
### Usage example, including component/hook API

I realize it's fairly trivial to create a border around a table using `Group`, but it would be a bit of a time saver for those who have many tables throughout their application to not have to wrap every `Table` in a `Group`.

Example of use:
`<Table border="sm" ...>...</Table>`

or

`<Table bordered ...>...</Table>`.

### Do you want to contribute this feature and create a pull request

Yes

**Comment by rtivital** [comment]
You can add border to table using `sx` with just one line of code, there is no need to wrap it with Group – https://codesandbox.io/s/falling-https-p03oq?file=/src/App.tsx
