### ISSUE TITLE
ThemeIcon with tabler results in crashing of app

### ISSUE THREAD

**Issue by sethen** [mantinedev/mantine#7051]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Just started using Mantine today with the Vite template.  Followed the instructions here: https://mantine.dev/core/theme-icon/ for putting icons into the page.  This results in crashing of the app when I pull up the app using `vite dev`.  No matter what I try it will load forever and then eventually crash.

I did add the tabler icons with `yarn add @tabler/icons-react` and everything seemed to install fine.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Issue with tabler icons package, see https://github.com/tabler/tabler-icons/issues/1233
To fix it, downgrade `@tabler/icons-react` package to `"@tabler/icons-react": "3.17.0"` in your package.json and reinstall dependencies.

**Comment by sethen** [comment]
> Issue with tabler icons package, see [tabler/tabler-icons#1233](https://github.com/tabler/tabler-icons/issues/1233) To fix it, downgrade `@tabler/icons-react` package to `"@tabler/icons-react": "3.17.0"` in your package.json and reinstall dependencies.

Still broken even with downgrading -- guess we will have to wait for a fix
