### ISSUE TITLE
ComboBox Popover not closing on external click anymore

### ISSUE THREAD

**Issue by vektorblake** [mantinedev/mantine#7057]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

The dropdown in the Combobox used to expectedly close when a user clicked outside of it. As of 7.13.0, it no longer did so. For our case we added a manual `store.closeDropdown` in `onClose` to resolve it, but this wasn't needed before and seems unusual.
```
<Combobox
	store={combobox}
	onClose={combobox.closeDropdown}
	withinPortal={false}
	onOptionSubmit={handleOptionSelection}
	style={{ ...props.style }}
	{...props.comboboxProps}
>
	<Combobox.Target {...props.targetProps}>
		<TextInput
			onClick={() => combobox.toggleDropdown()}
                        {/* .... etc ..... */}
		/>
	</Combobox.Target>

	<Combobox.Dropdown>
		<Combobox.Options>
			{options.length > 0 ? options : <Combobox.Empty>Nothing found....</Combobox.Empty>}
		</Combobox.Options>
	</Combobox.Dropdown>
</Combobox>
```
That was based on 716194c2c6497d8a507bfb25cf00c2f1dfa87c1b .

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction

**Comment by yverby** [comment]
This issue seems to have appeared after this [commit](https://github.com/mantinedev/mantine/commit/716194c2c6497d8a507bfb25cf00c2f1dfa87c1b)
Below is an example using `Popover` component and `useDisclosure` hook with the latest version of `@mantine/core` (7.13.5)

https://stackblitz.com/edit/github-zmfexg

**Comment by rtivital** [comment]
It is not related to Combobox, see https://github.com/mantinedev/mantine/issues/7019 about Popover

**Comment by rtivital** [comment]
I cannot reproduce the issue on my side with the latest version, you are welcome to reopen the issue if you can provide a reproduction.
