### ISSUE TITLE
`<Spoiler />` component doesn't scale height appropriately when theme scale is not default  

### ISSUE THREAD

**Issue by gsmith-schlesinger** [mantinedev/mantine#7064]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The `<Spoiler>` component does not calculate the height correctly when a theme has a scale set below `1`. 

The spoiler will fail to render the full height of its contents in the expanded state.

<img width="754" alt="image" src="https://github.com/user-attachments/assets/0e73ce19-e0af-4ca5-82d8-4c7127292c96">

This might be because the `useElementSize()` doesn't consider the mantine theme scale. 

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-mm3w4h?workspaceId=a9e4a88d-4bfe-46f2-a80d-9914f53c354f

### Possible fix

`calc(${rem(height)} * var(--mantine-scale))`

```ts
<div
        {...getStyles('content', {
          style: { maxHeight: !show ? rem(maxHeight) : height ? `calc(${rem(height)} * var(--mantine-scale))` : undefined },
        })}
        data-reduce-motion
        role="region"
        id={regionId}
      >
        <div ref={contentRef}>{children}</div>
      </div>
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
`theme.scale` is designed to work with custom html font-size values, it is not meant to scale the interface. Changes to Spoiler component that may support this will most likely break some other functionality – the fix for this issue might be problematic and is not planned to be implemented.
