### ISSUE TITLE
Can't edit TextInput in Modal opened by Button in Tree node 

### ISSUE THREAD

**Issue by woody146** [mantinedev/mantine#7065]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I have a Button in Tree node (click it to open Modal). In Modal, there's a TextInput. When opening Modal, I can't edit TextInput

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-f8rqlm

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by mikhail-molchanov** [comment]
Generally speaking, rendering modal as a part of tree node by itself is not the best idea. You can try to move the modal outside the tree (thus having a single Modal instance per tree). When a button is clicked inside a tree node, use local state to provide context of what needs to be rendered to the modal and open it.

**Comment by rtivital** [comment]
In your example `renderNode` function is recreated on each render, it cannot preserve state correctly. To resolve the issue, make sure that the function is stable across renders and move all components that are related to state away from this function as described above. For more information, see – https://www.reddit.com/r/reactjs/comments/1bdc4sy/why_is_rendering_a_component_inside_a_component/
