### ISSUE TITLE
File Type Mismatch for .xlsm Files with useFsAccessApi Enabled in Mantine Dropzone

### ISSUE THREAD

**Issue by ajai-am** [mantinedev/mantine#7075]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/dropzone

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Description:
When using the `Dropzone` component from Mantine with `.xlsm` files, there is an inconsistency in file type detection depending on the file selection method. 

1. **Drag and Drop**: When I drag and drop a `.xlsm` file, the `onDrop` callback correctly identifies the MIME type as `application/vnd.ms-excel.sheet.macroenabled.12`.

![Screenshot 2024-11-05 at 10 00 38 AM](https://github.com/user-attachments/assets/3839d3cf-56e5-45d4-9214-04e88ee77ed7)

2. **File Selection with `useFsAccessApi`**: If I use the file selection dialog with `useFsAccessApi` enabled (set to `true`), the MIME type in the `onDrop` callback is an empty string. Consequently, the browser defaults to `application/octet-stream` when sending the file to the backend, causing issues with correct file type handling.

![Screenshot 2024-11-05 at 10 00 01 AM](https://github.com/user-attachments/assets/32147b4d-5365-4969-8177-bbe3307cea2a)

### Expected Behavior:
When selecting `.xlsm` files through the file selection dialog with `useFsAccessApi` enabled, the MIME type should be detected as `application/vnd.ms-excel.sheet.macroenabled.12`, consistent with the drag-and-drop method.

### Steps to Reproduce:
1. Use Mantine's Dropzone component with `useFsAccessApi` enabled.
2. Attempt to upload a `.xlsm` file using both drag-and-drop and file selection.
3. Observe the MIME type returned in the `onDrop` callback.

This discrepancy impacts handling of `.xlsm` files in applications that rely on correct MIME type detection.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This logic is handled in react-dropzone library, you are report the issue in their repository. Currently the issue cannot be fixed on Mantine side.

**Comment by ajai-am** [comment]
Hi @rtivital I tried using react-dropzone v14.2.9, there, this bug doesn't occur, probably they had this bug & got if fixed down the line. 

As I can see from the forked repo of yours https://github.com/rtivital/react-dropzone-esm it was lasted updated on 2023, could it be that this fix was not added into your forked version?

Since the mantine dropzone, directly depends on react-dropzone-esm & not react-dropzone, hence raising this request.

**Comment by rtivital** [comment]
Okay, I'll update react-dropzone-esm to the latest react-dropzone changes in one of the next patches

**Comment by ajai-am** [comment]
Thank you
