### ISSUE TITLE
levelOffSet prop in Tree component is appearing in the Dom 

### ISSUE THREAD

**Issue by Samy0412** [mantinedev/mantine#7086]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.0

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

Path: src/mantine-core/src/components/Tree/Tree.tsx

When adding the `levelOffset` prop to the Tree component, I get a warning in my console: 
![Capture d’écran, le 2024-11-05 à 15 48 59](https://github.com/user-attachments/assets/59e47d0b-32dc-4b63-909d-7b2d399a80f8)

### Possible fix

I understand the `levelOffSet` is added to the Box component props (Polymorphic as a `ul`), but not sure how. 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
This is fixed via v7.11.1:  https://github.com/mantinedev/mantine/pull/6461
