### ISSUE TITLE
Chip does not support Tooltip

### ISSUE THREAD

**Issue by dylangrandmont** [mantinedev/mantine#7093]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Wrapping a `<Tooltip />` component around `<Badge />`and all other mantine components renders correctly. However, wrapping a `<Tooltip />` around a `<Chip />` does not appear to render. The docs [appear to suggest that this should work](https://mantine.dev/core/tooltip/#tooltip-children).

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-rkvxyh

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/core/chip/#chip-with-tooltip
