### ISSUE TITLE
Type Error with adding `draggable: false` to `defaultProps` for `Image`

### ISSUE THREAD

**Issue by jared-jewitt** [mantinedev/mantine#7106]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I'm getting a type error when trying to set `draggable: false` as part of the `defaultProps` for the `Image` component. It does actually seem to work as intended, however I do have to add a `@ts-ignore` comment in order to remove the error. Is this intended?

<img width="1003" alt="Screenshot 2024-11-09 at 8 40 23 PM" src="https://github.com/user-attachments/assets/3a220de8-853b-41d8-8d8f-13d51bec5d68">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Image component is polymorphic, it has types only for props specific to the component itself. If you want to pass additional props that are related to html element, add `as any` to the defaultProps object. Currently, this logic is not planned to be changed.
