### ISSUE TITLE
defaultDate prop in MonthPickerInput and YearPickerInput is ignored (tested fix enclosed)

### ISSUE THREAD

**Issue by mkf62** [mantinedev/mantine#7108]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

Both MonthPickerInput and YearPickerInput have the `getDefaultClampedDate` function called when setting the `defaultDate` if  `_value` or `_value[0]` is `null`. When using these pickers in forms, where Mantine docs suggest using uncontrolled components for best performance of forms, the `defaultDate` prop becomes important. The `getDefaultClampedDate` function doesn't resolve how I would expect it to though because it derives the `defaultDate` from the `minDate` and `maxDate` props instead of using the developer-supplied `defaultDate`:

https://github.com/mantinedev/mantine/blob/1d07a3130b24b921c901ee69d9b3b43665303361/packages/%40mantine/dates/src/components/MonthPickerInput/MonthPickerInput.tsx#L138-L142

https://github.com/mantinedev/mantine/blob/1d07a3130b24b921c901ee69d9b3b43665303361/packages/%40mantine/dates/src/components/YearPickerInput/YearPickerInput.tsx#L133-L138

https://github.com/mantinedev/mantine/blob/1d07a3130b24b921c901ee69d9b3b43665303361/packages/%40mantine/dates/src/utils/get-default-clamped-date.ts#L10-L26

I think the MonthPickerInput and the YearPickerInput should operate the same way as the DatePickerInput when setting the `defaultDate`, otherwise the `defaultDate` prop on Month/Year pickers serves no purpose since it will always be derived from the `minDate` or `maxDate` props.

https://github.com/mantinedev/mantine/blob/1d07a3130b24b921c901ee69d9b3b43665303361/packages/%40mantine/dates/src/components/DatePickerInput/DatePickerInput.tsx#L108

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-zxhyqr

### Possible fix

I tested changing the code in the MonthPickerInput to this and it performed as I expected it to:
```
 defaultDate={ 
   Array.isArray(_value) 
     ? _value[0] || calendarProps.defaultDate || getDefaultDate({minDate, maxDate, timezone: ctx.getTimezone() })
     : _value || calendarProps.defaultDate || getDefaultDate({minDate, maxDate, timezone: ctx.getTimezone() })
 } 
```

I tested changing the code in the YearPickerInput to the same code above and it performed as I expected it to also.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.14.2](https://github.com/mantinedev/mantine/releases/tag/7.14.2)
