### ISSUE TITLE
Cannot clear select component when rightSection is used, clearable doesn't function.

### ISSUE THREAD

**Issue by AvgoustisW** [mantinedev/mantine#7110]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Hello, I have the following 2 select components. 

```
<Select
  data={["React", "Angular", "Svelte"]}
  placeholder="Clearable default"
  defaultValue="React"
  clearable
  value={value}
  onChange={setValue}
  rightSection={<IconChevronDown />}
  rightSectionPointerEvents={"none"}
/>
```
```
<Select
  data={["React", "Angular", "Svelte"]}
  placeholder="Clearable default"
  defaultValue="React"
  clearable
  value={value}
  onChange={setValue}
/>
```

They are both clearable but you will notice that on the 1st I cannot clear the value, there is no X icon displayed (it's not in the html either) so I cannot clear it, the 2nd one can be cleared however.

So the problem is that if I decide to use rightSection, I cannot clear the value if clearable prop is present. Any pointers?

![image](https://github.com/user-attachments/assets/64200d48-d222-4ac6-8aa9-974d6f20e8b9)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-dgxwq3?workspaceId=34e7e542-77db-4a0f-b5d7-8c2d71362e09

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior, clearable button is displayed in the right section of the component. This behavior is not planned to be change.
