### ISSUE TITLE
Top property is not converted to rem (stay in px)

### ISSUE THREAD

**Issue by bastiengrignon** [mantinedev/mantine#7112]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.5

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

There seems to be an issue with the `top` property, it is not converted to `rem` in CSS, other position property bottom, left, right) are converted to rem successfully but **top** is in _px_
You can see in the codesandbox by inspecting the Box element from Devtools

![image](https://github.com/user-attachments/assets/ec5d6a08-fefd-4632-aa0c-b37a98494609)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-v38dwq?file=%2Fsrc%2FApp.tsx%3A14%2C1

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by onkar-deshpande** [comment]
it doesn't look like a bug. The code is written in such a way that for 0 value it uses `rem` for rest if no measurement type specified then it takes `px` as default type.

If this needs to be fixed then possible fix would be to modify condition check in `px.ts` file.

**Comment by bastiengrignon** [comment]
I don't think the default behavior is `px` unit in Mantine library ! As mentionned in the docs [here](https://mantine.dev/styles/rem/#rem-units) all units are converted into `rem`
And as you can see in the **Codesanbox** provided before and the screen uploaded for `0` values or a any random value the `top` property is not converted to **rem** compared to other properties like **bottom**

**Comment by rtivital** [comment]
Fixed in [7.14.1](https://github.com/mantinedev/mantine/releases/tag/7.14.1)
