### ISSUE TITLE
Tooltip of Slider is flickerling

### ISSUE THREAD

**Issue by Kenzo-Wada** [mantinedev/mantine#7116]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

tooltip of Slider flickers onClick.

https://github.com/user-attachments/assets/6db5995d-ae3a-44ba-990a-ef24972c434a

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/core/slider/

### Possible fix

I'll dig into the codes later. Maybe we should set some delay time to show tooltip to prevent this issue.

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I think that it is fine, tooltip is opened when the slider is being dragged

**Comment by Kenzo-Wada** [comment]
Okay!
