### ISSUE TITLE
Inconsistency in overwriting style properties between Menu and Popover

### ISSUE THREAD

**Issue by MartinMuzatko** [mantinedev/mantine#7120]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.0

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

In the `Menu` component, I can overwrite the top and left styles in the `styles.dropdown` prop of the `Menu` oder the `Menu.Dropdown`, or I can set the `style` in `Menu.Dropdown`.

However in the `Popover` component, the only way to overwrite these styles already set by the component is to use the `Popover.Dropdown` style prop.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-x7rmkj

### Possible fix

I haven't checked the code out yet, but I believe there is an inconsistency with how the props are rendered or what the order of writing to the style is.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.14.1](https://github.com/mantinedev/mantine/releases/tag/7.14.1)
