### ISSUE TITLE
useHotkeys doesn't detect plus key

### ISSUE THREAD

**Issue by ianparkinson** [mantinedev/mantine#7123]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.0

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

`useHotkeys` from `@mantine/hooks` doesn't appear to allow binding actions to the `+` key. Other arithmetical operations (`/`, `*`, `-`) work as expected. In other words, with:

```
  useHotkeys([
    ['/', handle],
    ['*', handle],
    ['-', handle],
    ['+', handle],
  ]);
```

...`handle` gets triggered with any of the `/`, `*` or `-` keys, but not `+`.

The [use-hotkeys documentation](https://mantine.dev/hooks/use-hotkeys/#supported-formats) links to [Key values for keyboard events](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values) at MDN, which in turn suggests that the string `Add` might once have worked, but works no longer in modern browsers. I've also verified that the strings `Add`, `Multply` etc. don't work on Chrome 130.0.6723.116.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-zrxnsn

### Possible fix

[`parseHotkey`](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/hooks/src/use-hotkeys/parse-hotkey.ts#L16) supports strings like `alt+j` to specify modifiers. It starts with:

```
  const keys = hotkey
    .toLowerCase()
    .split('+')
    .map((part) => part.trim());
```

which splits the modifier string up into its individual parts. It goes on to check for modifier names such as `alt`, `shift` etc. This unfortunately removes any instances of '+' in the hotkey string. Any fix will presumably involve improving this parsing logic to support `+`, `alt++` etc.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed with adding this syntax: `shift+[plus]`. It will be available in 7.14.1 patch.
