### ISSUE TITLE
Issue with Help Center article "How can I change inputs focus styles?"

### ISSUE THREAD

**Issue by Dharmrajsinh-INX** [mantinedev/mantine#7126]
### Link to the page where something is not right

https://help.mantine.dev/q/input-focus-styles

### What is wrong?

not working in Mozilla firefox

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
All demos work correctly on the Help Center website in Firefox. I cannot reproduce the issue.

![Снимок экрана 2024-11-15 в 14 51 59](https://github.com/user-attachments/assets/f7979b1c-4ad0-4516-89f5-9af56c95e77b)
