### ISSUE TITLE
Carousel draggable={false} doesn't works

### ISSUE THREAD

**Issue by waldimiro** [mantinedev/mantine#7129]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.1

### What package has an issue?

@mantine/carousel

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Carousel draggable={false} can't be set, it acts everytime as it is true.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Make sure that you have the correct embla version in package.json. It should be 7.x. If that is not the case, downgrade it. If that does not help, provide a sandbox with a minimal reproduction.
