### ISSUE TITLE
Pressing escape within a child Modal, closes it and the parent Modal

### ISSUE THREAD

**Issue by rhyek** [mantinedev/mantine#7130]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.1

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Related to https://github.com/mantinedev/mantine/issues/6528. Basically, when I have a modal open within another, when pressing escape while the second modal is open it will close both.

I tried setting `data-mantine-stop-propagation` on the second modal, but it's not doing anything for me.

I read about the new `Modal.Stack` feature, which seems great, but I don't think it would be the best solution for my case since my second modal is a shared component that can be opened from multiple places in the application.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-c7gzkm

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior. Currently, the solution for multiple opened modals is to use Modal.Stack. It is not planned to change this logic in near future.

**Comment by rtivital** [comment]
To solve it for your case, you can have Modal.Stack at the root of your application next to MantineProvider and pass it down to modals that you expect to be opened at the same time.

**Comment by rhyek** [comment]
Thanks. I'll take that into consideration, but this really feels like unintended behavior since clicking on the close button for the top-most modal doesn't also close the previous one.

**Comment by ryami333** [comment]
> To solve it for your case, you can have Modal.Stack at the root of your application next to MantineProvider and pass it down to modals that you expect to be opened at the same time.

@rtivital this seems like sensible advise (moving Stack to app root) but it seems that Modals (and Drawers) do not remove themselves from the Stack when unmounted, so "phantom" modals will get stuck in the Modal stack context, for the entire app lifecycle. Should I open an issue for this?

https://github.com/mantinedev/mantine/blob/33b8c0f3c1ce6dbdd692d4c2ecc805875aad3d26/packages/%40mantine/core/src/components/Modal/Modal.tsx#L110

**Comment by rtivital** [comment]
Yes, please open a new issue
