### ISSUE TITLE
NavLink renders collapse element even if it has no child elements

### ISSUE THREAD

**Issue by shota-f** [mantinedev/mantine#7133]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.1

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

All

### Describe the bug

As the title suggests, elements with the "mantine-NavLink-collapse" class are rendered even if they have no child elements.

You can also check this in the [document](https://mantine.dev/core/nav-link/#nested-navlinks) using the developer tools.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.14.2](https://github.com/mantinedev/mantine/releases/tag/7.14.2)
