### ISSUE TITLE
Portal element disappears when minimizing window

### ISSUE THREAD

**Issue by kimshenberly** [mantinedev/mantine#7135]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

I have a layout component where I've put a portal div
```<div id="portal" />```

and in a child component i'm rendering a button to that parent div
```
<Portal target="#portal">
   <Button />
</Portal>
```

This is working great, however when i minimize the window to the mobile view, the portal div is there but is now empty. On refresh I get the button to appear again. Is there a way to get it to stay without a refresh?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction

**Comment by kimshenberly** [comment]
sorry, realized its because we are using a component that renders a Group for desktop and Stack for mobile and the portal was a child of that component. using a flex component instead!
