### ISSUE TITLE
Opacity on scroll possible to change only through styles prop on ScrollArea

### ISSUE THREAD

**Issue by dipiash** [mantinedev/mantine#7149]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Try to change `thumb` opacity through classes, but it's not possible. It's possible only through `styles` prop with important mark. I use `@maintine/emotion`.

### Example

Styles:
```
thumb: {
    backgroundColor: '#71717d',
    opacity: '30%',
  },
```

Component:
```tsx
<ScrollArea
  classNames={{ thumb: classes.thumb }}
  styles={{ thumb: { opacity: '0.3!important' } }}
>
  children}
</ScrollArea>
```

<img width="667" alt="image" src="https://github.com/user-attachments/assets/dc8c7fd5-01b6-4ed0-989c-b1cc6baa0e29">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.14.3](https://github.com/mantinedev/mantine/releases/tag/7.14.3)
