### ISSUE TITLE
Issue with Help Center article "Can I use an array of strings as a list in use-form?"

### ISSUE THREAD

**Issue by matthiasfeist** [mantinedev/mantine#7152]
### Link to the page where something is not right

https://help.mantine.dev/q/list-of-strings-in-use-form

### What is wrong?

It uses a hook called `randomId` that is not listed on the website.
So either the example is outdated or the website is :) 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/guides/functions-reference/#randomid

**Comment by matthiasfeist** [comment]
Ah OK sorry. I was looking in the hook section. I wasn't aware that there are functions in the hook package as well and therefore I need to look in a different place in the documentation :)
