### ISSUE TITLE
withBarValueLabel value not displaying in correct positions

### ISSUE THREAD

**Issue by namakshenas** [mantinedev/mantine#7156]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.1

### What package has an issue?

@mantine/charts

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

This issue was addressed in issue #6991, but still not working properly:

<img width="641" alt="Screenshot 2024-11-22 at 18 32 11" src="https://github.com/user-attachments/assets/5f32b3ab-b408-47c6-bade-a724b0de9b9a">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by minosss** [comment]
Hi @rtivital, I see that custom component `BarLabel` is used to plan to support more customizations?
 
Why not use `LabelList` from [recharts](https://recharts.org/en-US/api/LabelList).
```tsx
<Bar {...others}>
  {withBarValueLabel && <LabelList
    position={orientation === 'vertical' ? 'right' : 'top'}
    offset={8}
    fontSize={12}
    fill="var(--chart-bar-label-color, var(--mantine-color-dimmed))"
    // there are also a method to format the value
    // formatter={(v) => v}
  />}
</Bar>
```

**Comment by rtivital** [comment]
You are welcome to submit a PR that fixes the issue, if LabelsList is the right component, then it should be used

**Comment by minosss** [comment]
for now, `Label` or `LabelList` of recharts would be better for displaying labels, maybe remove `PointLabel` as well.
