### ISSUE TITLE
Select component selecting the same value should not trigger onChange event

### ISSUE THREAD

**Issue by wangchj** [mantinedev/mantine#7157]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

@mantine/core 7.14.0, @mantine/hooks 7.14.0

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Environment:
- Electron 33.2.0
- TypeScript 
- Webpack 5.69.1

The current behavior of the Select component triggers the `onChange` event when selecting the same option. However, the onChange event value is `null`. It'd make sense not to trigger the event in this case.

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Select component works as intended. If you want to disallow option deselect, set `allowDeselect={false}`. See https://codesandbox.io/p/sandbox/mantine-react-template-forked-9fq2jq
