### ISSUE TITLE
`withinPortal`-property can not be set using @mantine/dates package `DatePicker` e.g.

### ISSUE THREAD

**Issue by jviets** [mantinedev/mantine#7161]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.1

### What package has an issue?

@mantine/dates

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

All

### Describe the bug

I am creating micro-frontend components with mantine.
All components have a shadow root with the @mantine/*/styles.css scoped to the mfe component.

For the core components I can set `withPortal: false` using the theme overrides:
```typescript
Popover: Popover.extend({
  defaultProps: {
    withinPortal: false,
  },
}),
```

Unfortunately I cannot do this for the DatePicker e.g. and this is why the styles are not used correctly.
I am forced to import the styles to the parent website that is using my mfe-components.

It would be awesome, if I could set this property also to the @mantine/dates package-components.

### Possible fix

```typescript
DatePicker: DatePicker.extend({
  defaultProps: {
    withinPortal: false, // this property does not exist yet
  },
}),
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
DatePicker component is not rendered in Portal. If you want to pass props to Popover component in DatePickerInput component, use `popoverProps={{ witinPortal: false }}`.
