### ISSUE TITLE
The tooltip of the chart does not render properly.

### ISSUE THREAD

**Issue by NoCtrlZ1110** [mantinedev/mantine#7167]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.14.2

### What package has an issue?

@mantine/charts

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

![image](https://github.com/user-attachments/assets/5d3a92e9-f229-4730-aa06-0ca6f508f8f3)

I use [this template](https://github.com/mantinedev/vite-template) to create a new project and install chart & edit `Welcome.tsx` to this

```
import { AreaChart } from '@mantine/charts';

export const data = [
  {
    date: 'Mar 22',
    Apples: 2890,
    Oranges: 2338,
    Tomatoes: 2452,
  },
  {
    date: 'Mar 23',
    Apples: 2756,
    Oranges: 2103,
    Tomatoes: 2402,
  },
  {
    date: 'Mar 24',
    Apples: 3322,
    Oranges: 986,
    Tomatoes: 1821,
  },
  {
    date: 'Mar 25',
    Apples: 3470,
    Oranges: 2108,
    Tomatoes: 2809,
  },
  {
    date: 'Mar 26',
    Apples: 3129,
    Oranges: 1726,
    Tomatoes: 2290,
  },
];

export function Welcome() {
  return (
    <>
      <AreaChart
        h={300}
        data={data}
        dataKey="date"
        series={[
          { name: 'Apples', color: 'indigo.6' },
          { name: 'Oranges', color: 'blue.6' },
          { name: 'Tomatoes', color: 'teal.6' },
        ]}
        curveType="linear"
      />
    </>
  );
}

```

After that, back to the browser, the chart tooltip does not render normally.
Other chart types goes with the same error!

### Possible fix

N/A

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Have you imported styles like in the installation instructions? https://mantine.dev/charts/getting-started/#installation

**Comment by NoCtrlZ1110** [comment]
Oh, I missed this guide, thank you so much @rtivital
