### ISSUE TITLE
useHotkeys hook interfering with Input component

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#717]
### What package has an issue

@mantine/hooks

### Describe the bug

If you use `useHotkeys` hook to listen for certain hotkeys, for example `'Shift+D'` (which is a common hotkey on websites for toggling dark mode), it effectively blocks the user from typing uppercase 'D' in `Input` component field using the `'Shift+D'` combination, because `useHotkeys` hook is intercepting the keypress.

### In which browser did the problem occur

Chrome

### Possible fix

`Input` fields should have priority for keypresses over `useHotkeys` hook (or at least have a prop to enable this behavior).

**Comment by rtivital** [comment]
Thanks for reporting, this issue will be resolved in one of the next patches

**Comment by rtivital** [comment]
Duplicate of #792
