### ISSUE TITLE
Cannot use position='right' when set Table.Tr as Menu.Target

### ISSUE THREAD

**Issue by nikolai-shilin** [mantinedev/mantine#7170]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.2

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When I set table row as a menu target and set position as 'right' it stays on left. Other positioning values (bottom, top, left) work fine.

```
    <Menu trigger="hover" position='right'>
      <Menu.Target>
        <Table.Tr>
          <Table.Td>
           ...
          </Table.Td>
        </Table.Tr>
      </Menu.Target>
      <Menu.Dropdown>
        ...
      </Menu.Dropdown>
    </Menu>
```

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is the intended behavior of Popover. If there is not enough space on the given position, it is flipped. To disable this feature, use middlewares – https://mantine.dev/core/popover/#middlewares
