### ISSUE TITLE
Using Textarea autosize with useTextSelection causes infinite re-rendering

### ISSUE THREAD

**Issue by astolman** [mantinedev/mantine#7172]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I noticed this because I have a component that uses useTextSelection and elsewhere on the page is a Textarea. The component with the text selection hook was re-rendering infinitely. I was able to reproduce this in the code sandbox. If you add a couple blank lines you can see in the console that the whole component renders over and over again until you delete the content. It seems to require at least 2 lines in the sandbox, although in my original case it was happening before I added any content to the Textarea. Removing the autosize property from the textarea makes the problem go away.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-q4dd5d

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction
