### ISSUE TITLE
Add a missing CSS style dependency

### ISSUE THREAD

**Issue by andreisucman** [mantinedev/mantine#7173]
### Link to the page where something is not right

https://mantine.dev/styles/css-files-list/

### What is wrong?

The list of styles that are reused in components is missing this file: 

`@mantine/core/styles/FloatingIndicator.css`

It is used in the

`"@mantine/core/styles/SegmentedControl.css";`

and so the latter is broken without the former.

It should be added to the list.

Thank you

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.14.3](https://github.com/mantinedev/mantine/releases/tag/7.14.3)
