### ISSUE TITLE
Infinite useEffect rendering in Tabs.Panel

### ISSUE THREAD

**Issue by emad-ms** [mantinedev/mantine#7183]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

6.0.22

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Other, I will specify in the bug description

### Describe the bug

The [useEffect](https://github.com/mantinedev/mantine/blob/84e6d7177d221be47af5294b74e6dcdac8eb4f13/src/mantine-core/src/Tabs/TabsPanel/TabsPanel.tsx#L50) in Tabs.Panel goes in an infinite loop in the testing environment.

### Possible fix

It works fine if I pass an `id` prop to `<Tabs />` component

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I cannot reproduce this issue in Mantine tests, we have a log of them in the main repository. Seems like you already have a workaround, so I don't see much purpose in debugging it.
