### ISSUE TITLE
Vitest unit test error: TypeError: Cannot read properties of undefined (reading 'matches')

### ISSUE THREAD

**Issue by iamdejan** [mantinedev/mantine#7185]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.3

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

I got this error log when I run my unit test (using `vitest`):
```
TypeError: Cannot read properties of undefined (reading 'matches')
    at setColorSchemeAttribute (file:///Users/macbook-giovannidejan/VSCodeProjects/iamdejan/react-iam-dashboard/node_modules/.pnpm/@mantine+core@file+..+mantine+packages+@mantine+core_@mantine+hooks@file+..+mantine+packages+_74wiwvogszovmx2h66rqol7oqu/node_modules/@mantine/core/src/core/MantineProvider/use-mantine-color-scheme/use-provider-color-scheme.ts:5:138)
```

Upon investigating with `git bisect`, I narrow down the bug to commit bad9bc5f0. I wonder if there's anything that triggers the error.

Thank you.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/github/iamdejan/mantine-minimal-reproduction/main?import=true

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
See https://mantine.dev/guides/vitest/#configuration

**Comment by danny-vvv** [comment]
I am getting the same issue on 7.15.0 and 7.16.0.

It appears to only happen in Vitest tests which include Mantine Charts components.

The latest versions I can get running together are:

```
"@mantine/charts": "7.14.0",
"@mantine/core": "7.14.0",
"@mantine/form": "7.14.0",
"@mantine/hooks": "7.14.0",
"@mantine/next": "^6.0.21",
"@mantine/notifications": "7.14.0",
"recharts": "2"
```

**Comment by rtivital** [comment]
Provide a repository with a minimal reproduction.
