### ISSUE TITLE
Checkbox.Group with Checkbox.Card requires three clicks to deselect 

### ISSUE THREAD

**Issue by qgwr32** [mantinedev/mantine#7187]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.3

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When using `Checkbox.Group` with multiple `Checkbox.Card` elements inside, deselecting a previously selected option does not work correctly. Each card requires three clicks to deselect.

This is also reproducible on the Mantine website at https://mantine.dev/core/checkbox/#checkboxcard-component

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/core/checkbox/#checkboxcard-component

### Self-service

- [x] I would be willing to implement a fix for this issue

**Comment by ynssenem** [comment]
Yes, I am also experiencing this issue.

**Comment by X-Vneer** [comment]
i'm also experiencing this as well

**Comment by rtivital** [comment]
Fixed in [7.15.1](https://github.com/mantinedev/mantine/releases/tag/7.15.1)
