### ISSUE TITLE
Error in Modal manager doc example?

### ISSUE THREAD

**Issue by laugri** [mantinedev/mantine#7192]
### What is wrong?

In the doc of Modals manager (https://mantine.dev/x/modals/), in the Modal props section (https://mantine.dev/x/modals/#modal-props), the example uses `const modalId = modals.open(...`. However, `modals.open` is of type `(payload: ModalSettings) => void` so I think the doc is wrong ?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I do not see this behavior with the latest version – https://codesandbox.io/p/sandbox/mantine-react-template-forked-hq3vdn
Update all `@mantine/*` packages to the latest version.
