### ISSUE TITLE
The loop attribute does not work when the child element has too little content

### ISSUE THREAD

**Issue by PlutoCA** [mantinedev/mantine#7196]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.2

### What package has an issue?

@mantine/carousel

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Hi~, I have a problem

```javascript
        import React from 'react'; // ^18.3.1 |  vite - ^5.4.9
        import { Carousel } from '@mantine/carousel';
        
        <Carousel
            slideSize="70%" height={200} slideGap="md" loop
        >
            <Carousel.Slide style={{ background: 'blue' }}>1</Carousel.Slide>
            <Carousel.Slide style={{ background: 'yellow' }}>2</Carousel.Slide>
        </Carousel>
```
The loop attribute does not work when the child element has too little content
Thanks

### If possible, include a link to a codesandbox with a minimal reproduction

[Codesandbox Link](https://codesandbox.io/p/sandbox/qzxlng)

### Possible fix

I would expect loop to remain as long as there are child elements

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by PlutoCA** [comment]
> ### Dependencies check up
> * [x]  I have verified that I use latest version of all @mantine/* packages
> 
> ### What version of @mantine/* packages do you have in package.json?
> 7.14.2
> 
> ### What package has an issue?
> @mantine/carousel
> 
> ### What framework do you use?
> Vite
> 
> ### In which browsers you can reproduce the issue?
> Chrome
> 
> ### Describe the bug
> Hi~, I have a problem
> 
> ```js
>         import React from 'react'; // ^18.3.1 |  vite - ^5.4.9
>         import { Carousel } from '@mantine/carousel';
>         
>         <Carousel
>             slideSize="70%" height={200} slideGap="md" loop
>         >
>             <Carousel.Slide style={{ background: 'blue' }}>1</Carousel.Slide>
>             <Carousel.Slide style={{ background: 'yellow' }}>2</Carousel.Slide>
>         </Carousel>
> ```
> 
> The loop attribute does not work when the child element has too little content Thanks
> 
> ### If possible, include a link to a codesandbox with a minimal reproduction
> [Codesandbox Link](https://codesandbox.io/p/sandbox/qzxlng)
> 
> ### Possible fix
> I would expect loop to remain as long as there are child elements
> 
> ### Self-service
> * [ ]  I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This issue cannot be fixed on Mantine side – we use embla library under the hood and it fully controls this logic, you can report this issue in embla repository – https://www.embla-carousel.com/
