### ISSUE TITLE
FileInput - cannot style Placeholder

### ISSUE THREAD

**Issue by PandasProperty** [mantinedev/mantine#7202]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

I have this component

<$FileInput<Multiple>
      ref={ref}
      {...props}
      classNames={{
          root: '',
          input: '!h-11 input-area-fields-no-padding !justify-start !font-medium placeholder:!text-red-500 !text-black-black/50',
          wrapper: '!border-black-black/15',
          placeholder: '!font-medium !text-red-500 !truncate',
         section: '',
     }}
/>

None of my placeholder class names apply.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You do not use the latest version. Update to 7.14.3.
