### ISSUE TITLE
Extending polymorphic components strips out `component` prop types and others

### ISSUE THREAD

**Issue by justinwhall** [mantinedev/mantine#7209]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.3

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Using the "With TypeScript" example from [this page](https://mantine.dev/guides/typescript/#components-props-types), extending the type does in fact work but some of the types for polymorphic components are no longer available. In the example in the attached code sandbox, the `component` prop produces a type error as it missing from extended component. 

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-btn-ex-s5zx4p?file=%2Fsrc%2FApp.tsx%3A9%2C18

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://mantine.dev/guides/polymorphic/#wrapping-polymorphic-components
