### ISSUE TITLE
returnFocus Doesn't Work When Modal is Unmounted

### ISSUE THREAD

**Issue by ducdaoo** [mantinedev/mantine#7215]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Description:
It appears that the `returnFocus` prop does not work as expected when a modal is unmounted. The focus is not returned to the previously focused element, which is causing usability issues, especially for users relying on keyboard navigation or screen readers.

### Steps to Reproduce:
Render a modal component with `returnFocus` prop enabled.
Open the modal using a button or link.
Unmount the modal (e.g., conditional rendering removes it from the DOM).
Observe that focus does not return to the triggering element.

### Expected Behavior:
When the modal is unmounted, the focus should return to the element that triggered the modal.

### Actual Behavior:
The focus remains unset or moves to the body, causing a disorienting experience for keyboard and assistive technology users.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is intended behavior and is not planned to be fixed. Modal component should always be mounted, and opened state should be controlled with the `opened` prop to avoid any accessibility issues.
