### ISSUE TITLE
`zodResolver` infers wrong `values` type

### ISSUE THREAD

**Issue by youssefbenlemlih** [mantinedev/mantine#7218]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.3

### What package has an issue?

@mantine/form

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

When using `useForm` with `zodResolver`, the type of `values` is inferred incorrectly as `Record<string, any>`, instead of inferring the type from the provided zod scheme:

```tsx
 const form = useForm({
    mode: 'uncontrolled',
    validate: zodResolver(scheme),
  });

// values has the type `Record<string, any>` 
//                                 ↓
<form onSubmit={form.onSubmit((values) => {}}>
  ```
The problem seems to come from the type of zodResolver which is:
```tsx
export declare function zodResolver<T extends Record<string, any>>(schema: ZodSchema<T>): (values: T) => FormErrors;
```

### Possible fix

A solution would be to declare `zodResolver` with a type that infers the type of `values` from the provided the zod schema. Something like this:

```tsx
import { ZodSchema, ZodTypeDef, ZodError, infer } from 'zod';
export declare function zodResolver<S extends ZodSchema<any, ZodTypeDef>>(
  schema: S,
): (values: infer<S>) => FormErrors

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
```tsx
const form = useForm({
    mode: 'uncontrolled',
    validate: zodResolver(scheme),
  });

// values has the type `Record<string, any>` 
//                                 ↓
<form onSubmit={form.onSubmit((values) => {}}>
```

This example that you've shared does not provide any type information for use-form hook – it does not use validate function as a source for types. Instead you need to either supply `initialValues` or specify form values type via type argument:

```tsx
const schema = z.object({ /* .... */ })

type Values = z.infer<typeof schema>;

const form  = useForm<Values>({
   //...
});
```

**Comment by youssefbenlemlih** [comment]
Hi @rtivital, 
thanks for the fast reply and your solution.
Looking at the type declaration of useForm and its options, the type of values can also be inferred from the validate option. While I understand that using initialValues or a generic parameter as the type source is the recommended pattern, it would be a good developer experience to at least have the option to infer it from the zod schema, without having to add the generic type or an initial value. My proposition is to make the zodResolver infer the type from the schema, instead of wrongly inferring `Record<string, any>`, which is something that users of the library would expect.
Thanks again, (and awesome library btw :D )

**Comment by rtivital** [comment]
This is not supported because use-form is not meant to be used without `initialValues` as it is a requirement for most of the features to work correctly.
