### ISSUE TITLE
DatePicker hasNextLevel={false} it still allows to select the nextLevel

### ISSUE THREAD

**Issue by heybart** [mantinedev/mantine#7229]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.3

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

When I set `hasNextLevel={false}` on a DatePicker, it still allows me to select another level. If I set `maxLevel="month"` it won't show the next level but it still shows as a button with hover and pointer cursor. I would expect no hover and just a regular cursor.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/smoosh-brook-nff873

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is an error with prop leak. `hasNextLevel` prop will be removed with the next patch. To correctly change the level, use `maxLevel` prop instead.
