### ISSUE TITLE
Menu component's transition is glitchy and shifting in Chrome

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#723]
### What package has an issue

@mantine/core

### Describe the bug

The default transition of `Menu` component appears to be glitchy in Google Chrome. 

Also, I've tested every transition and all of them except `fade` have the same glitchy jumping behavior in Chrome (...but work just fine in both Safari 15.2 and Firefox 97).

OS: `macOS Monterey 12.1`
Browser: `Google Chrome 97.0.4692.71 (Official Build) (arm64)`

To demonstrate this, I am using [the official example from Menu docs](https://mantine.dev/core/menu/#usage) in Codesandbox. Here's the video:

https://user-images.githubusercontent.com/44101337/150616016-828b75f0-488b-4e87-9ff7-b090566c41a4.mov

https://user-images.githubusercontent.com/44101337/150616019-7b433625-209e-4014-bdaa-253fbf1ccd91.mov

### In which browser did the problem occur

Google Chrome 97

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/recursing-beaver-mlc7k?file=/src/App.tsx

**Comment by rtivital** [comment]
I guess that's just how Chrome works, I do not have an idea of what can be done on our side to resolve this

**Comment by albertbronsky** [comment]
> I guess that's just how Chrome works, I do not have an idea of what can be done on our side to resolve this

Does it behave the same way in Chrome for you?

**Comment by rtivital** [comment]
Yes, it behaves the same

**Comment by rtivital** [comment]
I think we cannot do anything about that, because it's how Chrome works
