### ISSUE TITLE
@mantine/carousel is missing in npm registry

### ISSUE THREAD

**Issue by kosgo** [mantinedev/mantine#7233]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/carousel

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

Hello, @mantine/carousel is missing in npm registry

https://mantine.dev/x/carousel/

https://www.npmjs.com/package/@mantine/carousel

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
It is not, see screenshot
![Снимок экрана 2024-12-08 в 23 10 38](https://github.com/user-attachments/assets/18902d7a-374a-4415-bf2c-efa41ce47c45)
