### ISSUE TITLE
Modal styles type error when trying to use with emotion

### ISSUE THREAD

**Issue by paulm17** [mantinedev/mantine#7236]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.3

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I'm using `@mantine/emotion`.

Using Modal normally.

```js
<Modal
styles={{
}}>
</Modal>
```

![Screenshot 1](https://i.ibb.co/JzGjMMS/Screenshot-2024-12-09-at-12-44-11.png)

Produces the correct styles for the Modal.

```js
<Badge>
styles={() => {
})}>
</Badge>
```

![Screenshot 2](https://i.ibb.co/H4zHJ4j/Screenshot-2024-12-09-at-12-44-36.png)

Produces the correct styles for Badge.

```js
<Modal>
styles={() => ({
})}>
</Modal>
```

I get the following type error if I try to call autocomplete with ""

```
Type '() => { "": any; }' has no properties in common with type 'Partial<Record<ModalBaseStylesNames, CSSProperties>>'.ts(2559)
```

![Screenshot 3](https://i.ibb.co/JFgJwNG/Screenshot-2024-12-09-at-12-45-55.png)

I've tested all the components.  All show the styles (for the emotion function) except `Modal` and `Drawer`.

I have created a sandbox to highlight the issue.

Thanks for taking the time to look at this!

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-2q24xv

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Unfortunately, this cannot be fixed, type augmentation on the BoxProps level can only support generic types, if types are added for all components, it will be required to add individual definitions for all Mantine components that support styles API in `.d.ts` file. You can try this approach, but I don't really want to maintain it as part of the library.
