### ISSUE TITLE
Rich text editor custom controls has no border anymore

### ISSUE THREAD

**Issue by daniel-heg** [mantinedev/mantine#7239]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.0

### What package has an issue?

@mantine/tiptap

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Safari

### Describe the bug

First of all thank you for this library!

Since 7.15.0 the outline of the custom rich text editor control is gone. 

From [mantine.de](https://mantine.dev/x/tiptap/#custom-controls):

<img width="354" alt="image" src="https://github.com/user-attachments/assets/77cfed03-e9b6-42b5-a592-e2149ec54885">

In my case it looks like this: 

<img width="173" alt="image" src="https://github.com/user-attachments/assets/7d52141c-b61c-4a3a-9794-dc4c9cc55d97">

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.15.1](https://github.com/mantinedev/mantine/releases/tag/7.15.1)
