### ISSUE TITLE
there is an error on the mantine homepage.

### ISSUE THREAD

**Issue by ryuhangyeong** [mantinedev/mantine#7240]
### Link to the page where something is not right

https://mantine.dev/form/create-form-context/

### What is wrong?

<img width="923" alt="image" src="https://github.com/user-attachments/assets/bb4830b0-6ffb-48e4-a086-efaddd798722">

put one upon another

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Thanks for reporting, the issue has been fixed
