### ISSUE TITLE
@mantinex/mantine-logo still declares react 18 peerDependencies

### ISSUE THREAD

**Issue by s-cork** [mantinedev/mantine#7243]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

1.0.1

### What package has an issue?

@mantinex/mantine-logo

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

I think the peerDependencies have been resolved in the package json
but there hasn't been a version bump
And so the the pulled in peerDependencies require react 18

### Possible fix

bump the version of @mantinex/mantine-logo

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I do not understand the issue, please provide more details.

**Comment by s-cork** [comment]
if you bump the version of react to react 19 in a project that uses `@mantinex/mantine-logo`
you get this error:
```txt
npm ERR! Conflicting peer dependency: react@18.3.1
npm ERR! node_modules/react
npm ERR!   peer react@"^18.2.0" from @mantinex/mantine-logo@1.0.1
npm ERR!   node_modules/@mantinex/mantine-logo
npm ERR!     dev @mantinex/mantine-logo@"^1.0.1" from the root project
```

whilst this has been fixed in `@mantinex/mantine-logo` (the peerDependencies support react 19)
https://github.com/mantinedev/mantine/blob/aae7b81cc3cd3ad897a970bb6233148813990da7/packages/%40mantinex/mantine-logo/package.json#L40

The version was never bumped on npm.
So the version of `@mantinex/mantine-logo` in node_modules still declares that the peerDependencies as react 18.2.0

```json
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
```

using the following fixes the issue
```json
  "overrides": {
    "@mantinex/mantine-logo": {
      "react": "^18.x || ^19.x",
      "react-dom": "^18.x || ^19.x"
    }
  }
```

But i think publishing a patched version of `@mantinex/mantine-logo` will also fix the issue

**Comment by rtivital** [comment]
`@mantinex/*` packages have been updated on npm
