### ISSUE TITLE
broken link: https://mantine.dev/templates-usage/

### ISSUE THREAD

**Issue by galdiolo** [mantinedev/mantine#7244]
### Link to the page where something is not right

https://mantine.dev/guides/vite/

### What is wrong?

The link in the following text is broken (404 not found):
"If you are not familiar with GitHub, you can find a detailed instruction on how to bootstrap a project from a template on [this page](https://mantine.dev/templates-usage/)." 

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Thanks for reporting, the issue is fixed
