### ISSUE TITLE
RadioCard exception focus

### ISSUE THREAD

**Issue by gvillo** [mantinedev/mantine#7249]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.0 (I just updated to 7.15.1, I'll see if the errors re-appears)

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I just found this Unhandled Exception in Sentry that Mantine is not handling it
![image](https://github.com/user-attachments/assets/dda832b7-9efc-4b77-9bd8-f8d884aab628)

Total Events 12
Users affected 7

It's not a big deal (for now), but I think it must be handled because for some reason it's not finding the element to focus it.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a minimal reproduction

**Comment by gvillo** [comment]
Yeah sorry, I couldn't reproduce it locally, I found another unhandled exception like 10 lines up.

![image](https://github.com/user-attachments/assets/3a20cc53-bea9-412a-b286-b566fd4a77e3)

Looks like it's hapenning on the transition between one page to another, the element might not be present and that's why it's blowing up?, I am guessing, but there is an issue there with the `focus` and `handleKeyDown`

**Comment by rtivital** [comment]
I can't tell much without a reproduction

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction
