### ISSUE TITLE
[Feature Request] Docs: Add an example of submenus

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#725]
### Usage example, including component/hook API

Submenus are a common use case so it would be useful if [Menu component docs](https://mantine.dev/core/menu/) had an example of their implementation in Mantine.

**Comment by rtivital** [comment]
Menu component does not support submenus, so there is nothing to add to the docs

**Comment by albertbronsky** [comment]
> Menu component does not support submenus, so there is nothing to add to the docs

Is it possible to achieve this in any way with Mantine components?

**Comment by rtivital** [comment]
No, I do not think so

**Comment by albertbronsky** [comment]
> No, I do not think so

That's a bummer.
Any plans to add this? Seems like a pretty common use case for any application.

**Comment by rtivital** [comment]
Maybe we'll add this, not a priority right now

**Comment by rtivital** [comment]
Submenus are already in our backlog, so I'm closing this issue

**Comment by Ridermansb** [comment]
Waiting for this :)

**Comment by yverby** [comment]
`Menu` seems to support nesting, although I don't know if this will cover most cases
https://codesandbox.io/s/snowy-grass-gt90ox?file=/src/App.tsx

**Comment by paynecodes** [comment]
> Menu seems to support nesting, although I don't know if that covers most cases https://codesandbox.io/s/snowy-grass-gt90ox?file=/src/App.tsx

This does not handle keyboard events (presumably a11y concerns). An officially supported submenu system would be great though.
