### ISSUE TITLE
Popover tracking is jittery/hitches/lags inside of a scrollable element

### ISSUE THREAD

**Issue by noahw3** [mantinedev/mantine#7253]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Popover tracking doesn't scroll in lockstep with the target element when the target element is inside of a scrollable element. Instead, it has a tendency to lag behind the target element, creating an unpleasant disconnect between the opened popover and its tracked target. This does not happen when the target element is present at the window level instead of inside of a scrollable element, though this makes sense because the popover isn't actually rerendering in this case.

It's pretty obvious in Chrome. I didn't see any noticeable lag in Firefox, though the popover does get displaced when running into the "end of scroll" animation (likely a different issue there). I can't tell if it presents in Safari.

This applies to all components that use popovers (select, menu, etc.).

To reproduce in the below example you just need to click the select to show the popover and then scroll the page. It's most obvious when doing large scroll increments (with a mouse wheel). You should be able to see that the red gap between the popover and the target either grows or shrinks, depending on which way you're scrolling. It's a bit subtle in this example, but in real world cases on a page with more going on it becomes much more obvious.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/5rtjh9?migrateFrom=q4dd5d

### Possible fix

I dug into this a bit. I saw this behavior previously when I was responding to window scroll events with react state (eg. using `use-window-scroll`) and saw similar behavior to this. Adding a native event listener fixed it by moving that reactivity up a render cycle. Something similar may be going on here where we're delaying the updated position too long. 

That said, when I tried to set up my own listener it almost seems like the scroll events on the element just aren't firing fast or often enough. In my real world component I was able to scroll a significant amount before the scroll callback even fired a single time, so that would certainly also explain it. It's also possible that this may be a floating-ui issue rather than a mantine issue.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by noahw3** [comment]
Hmm I think I've stumbled upon a workaround: setting the scrolling container to `position: relative` and disabling the portal seems to result in smooth scrolling.

**Comment by rtivital** [comment]
It is how floating ui works, if the element is rendered in portal it is required to recalculate its position on scroll. Your solution is the intended for this case.
