### ISSUE TITLE
Bug with Modal Components - Height is 32px even when not visible, and within portal

### ISSUE THREAD

**Issue by Shadowfita** [mantinedev/mantine#7263]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The modal component from mantine/core has a height of 32px even when not visible, or mounted, even when in portal. Seems to apply padding, and keepmounted is ignored. Display is never updated to none.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I do not understand the issue, provide a sandbox with a minimal reproduction and more detailed explanation.

**Comment by ShahmBarmada** [comment]
remove styling attributes from "root" element of the modal components and apply them to "content" element
https://mantine.dev/core/modal/?t=styles-api

**Comment by rtivital** [comment]
You are welcome to reopen the issue if you can provide a reproduction
