### ISSUE TITLE
TypeScript error with useModalsStack when using const in type parameter

### ISSUE THREAD

**Issue by Faetu** [mantinedev/mantine#7264]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

**Context**: Using [Wails](https://wails.io/) with the [react-ts](https://wails.io/docs/gettingstarted/firstproject) template. After that, I installed mantine as described on [usage with vite](https://mantine.dev/guides/vite/).

When using the `const` keyword in the type parameter of the `useModalsStack` function, TypeScript throws syntax errors:
```
typescript: Type parameter declaration expected. [1139]
typescript: An element access expression should take an argument. [1011]
typescript: ';' expected. [1005]
typescript: ')' expected. [1005]
typescript: ',' expected. [1005]
typescript: ',' expected. [1005]
typescript: Declaration or statement expected. [1128]
```

So `wails dev` fails to build the app. I had a older project with the same constellation, but with mantine version `7.11.1`, which works out of the box for me.

### Possible fix

The file in question used to look like this:
```typescript
interface ModalStackReturnType<T extends string> {
    state: Record<T, boolean>;
    open: (id: T) => void;
    close: (id: T) => void;
    toggle: (id: T) => void;
    closeAll: () => void;
    register: (id: T) => {
        opened: boolean;
        onClose: () => void;
        stackId: T;
    };
}
export declare function useModalsStack<const T extends string>(modals: T[]): ModalStackReturnType<T>;
export declare const useDrawersStack: typeof useModalsStack;
export {};
```

I just removed the `const` from the function `useModalsStack` and my wails app worked as expected.
But now the question is: should this file look like this? Have I maybe done something wrong in other places?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
- Make sure that you are using the latest version of typescript
- Make sure that you have skipLibCheck: true
- If that does not help, provide a sandbox with a minimal reproduction

**Comment by Faetu** [comment]
Hi @rtivital 

Thx! It was my mistake. My TypeScript version was `4.9.5`, but after updating to `5.7.2`, the errors disappeared.

Check TS version
```bash
npx tsc --version
```
If needed to update:
```bash
npm install typescript@latest --save-dev
```
