### ISSUE TITLE
Tooltip can overlap with Menu when close to window border because of flip

### ISSUE THREAD

**Issue by jvllmr** [mantinedev/mantine#7268]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

In my project I have a component which has both a menu and a tooltip and the tooltip is only visible when clicking the component / opening the menu. When the component gets close to the top window border because of scroll, the tooltip covers the menu. In this case I don't care if the tooltip would be cut off by the window border, but it is important that the menu is visible.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-vvtdj6

### Possible fix

Add a prop to tooltip which allows to disable/remove the flip floating-ui middleware. Maybe similar to Menu's middlewares prop.

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
You are welcome to submit a pr that adds an option to configure floating ui middlewares
