### ISSUE TITLE
Pagination: Disabled <a> element should prevent navigation and clicks

### ISSUE THREAD

**Issue by matamatanot** [mantinedev/mantine#7277]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Currently, when the `a` tag is in a disabled state, the `data-disabled="true"` attribute is correctly applied, and the cursor style is updated to reflect the disabled state. However, [the link is still clickable, and navigation occurs](https://mantine.dev/core/pagination/#controls-as-links), which is not expected behavior for a disabled element.

As per [the Button documentation](https://mantine.dev/core/button/), it is possible to prevent such behavior by using `onClick={(event) => event.preventDefault()}`. Could this approach be implemented for <a> elements in a disabled state?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
This is not planned to be implemented on the library side. You can do that on your side with `getItemProps` and `getControlProps`.
