### ISSUE TITLE
Unable to pick second date in range of MonthPicker after form reset

### ISSUE THREAD

**Issue by stampaaaron** [mantinedev/mantine#7278]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.3

### What package has an issue?

@mantine/dates

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When trying to reset a `MonthPicker` inside a form and only set the first date of the range (`[new Date(), null]`), it's not possible to directly pick the second date. When you try to pick the second date, it will be considered as the first date.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/friendly-northcutt-gpws5g

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.15.2](https://github.com/mantinedev/mantine/releases/tag/7.15.2)
