### ISSUE TITLE
.extend() type definition conflicts with working CSS properties

### ISSUE THREAD

**Issue by OctopBP** [mantinedev/mantine#7283]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Bug Description
When using `SegmentedControl.extend()` in a Mantine theme, there appears to be a type mismatch between the actual working implementation and TypeScript definitions.

### Current Behavior
The following code works correctly at runtime but produces a TypeScript error:

```typescript
SegmentedControl.extend({
  vars: (theme) => ({
    root: {
      background: theme.colors.dark[7] // This works visually but TypeScript complains
    }
  })
})
```

### Error Message
```
Type '(theme: MantineTheme) => { root: { background: string; }; }' is not assignable to type 'PartialVarsResolver<{ props: SegmentedControlProps; ref: HTMLDivElement; stylesNames: SegmentedControlStylesNames; vars: SegmentedControlCssVariables; }>'.
```

### Expected Behavior
Since the style works correctly at runtime, the TypeScript types should allow for standard CSS properties in the `root` object.

### Workaround
Adding `'--sc-shadow': 'none'` makes the TypeScript error go away:

```typescript
SegmentedControl.extend({
  vars: (theme) => ({
    root: {
      '--sc-shadow': 'none', // Adding any SegmentedControlCssVariables fixes TypeScript error
      background: theme.colors.dark[7]
    }
  })
})
```

### Environment
- Mantine version: 7.15.1
- TypeScript version: 5.6.2

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
The error is correct. You should not use `vars` to define CSS properties. To change styles, use `styles` prop instead of `vars` which is meant to be used only to set CSS variables, see https://mantine.dev/styles/styles-api/#styles-prop

**Comment by OctopBP** [comment]
Get it. Thank you
