### ISSUE TITLE
`useLocalStorage()` doesn't re-load from `localStorage` when `key` changes

### ISSUE THREAD

**Issue by mfulton26** [mantinedev/mantine#7286]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/hooks

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

`useLocalStorage()` doesn't re-load from `localStorage` when `key` changes

as a workaround, a `key` prop can be used

![image](https://github.com/user-attachments/assets/5c1cd4a3-428a-4a96-8be0-d956e9b5b99b)

oddly enough, if two usages of `useLocalStorage()` are used with the same `key` and the `key` prop workaround is used on the second one then the old value will flicker but will change while if it is used on the first one (like in the demo and screenshot) then the non-workaround value will not update even though it should

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-clnqdp

### Possible fix

there may be some missing hook dependency that should use the incoming `key` value to the hook

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.15.2](https://github.com/mantinedev/mantine/releases/tag/7.15.2)
