### ISSUE TITLE
[Feature Request] Anchor component should have a prop to toggle underline

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#729]
`Anchor` component has variants `link` and `text` but sometimes you don’t want the default `text-decoration: underline` when you are using `link`. Or vice versa, you are using `text` and may want to have it.

As of now, you need to manually override the styling with `!important`, which is an anti-pattern.

An ad hoc prop could be useful for that.

**Comment by albertbronsky** [comment]
`Anchor` component has variants `link` and `text` but sometimes you don’t want the default `text-decoration: underline` when you are using `link`. Or vice versa, you are using `text` and may want to have it.

As of now to achieve this you would have to override the styling with `!important` which is an anti-pattern.

A prop could be useful for that.

**Comment by jerebtw** [comment]
@rtivital should this be added to Text?

**Comment by rtivital** [comment]
Yep, it should be in Text

**Comment by jerebtw** [comment]
@rtivital Should I add another variant or prop to enable underlining?

**Comment by rtivital** [comment]
I've accidentally merged this into dev, so I guess it will be released only in about a month

**Comment by jerebtw** [comment]
Ohh i didn't know this should go in to master

**Comment by Brennvo** [comment]
Can this be closed as a result of #736?

**Comment by rtivital** [comment]
It will be closed when patch with this update is released

**Comment by rtivital** [comment]
Released in 3.6.5
