### ISSUE TITLE
Links to code in AppShell page do not work

### ISSUE THREAD

**Issue by jpet710122** [mantinedev/mantine#7291]
### Link to the page where something is not right

https://v5.mantine.dev/core/app-shell/

### What is wrong?

This link (used twice on AppShell page) results in 404 error:
[https://github.com/mantinedev/mantine/tree/master/src/mantine-demos/src/demos/core/AppShell]

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
5.0 website is no longer maintained, it is not planned to fix these.
