### ISSUE TITLE
Hydration failed because the server rendered HTML didn't match the client

### ISSUE THREAD

**Issue by jamalsoueidan** [mantinedev/mantine#7294]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/core

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I'm running with basic reactrouterv7 which is the latest remix version:

```js
export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta />
        <Links />
        <ColorSchemeScript />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}
```

I get the following error:

![Qh6v0qbK2O](https://github.com/user-attachments/assets/333a66a4-38af-4588-bb28-f49dd3025eba)

If I remove ColorSchemeScript, the error is gone.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by jamalsoueidan** [comment]
Could be related to this: https://github.com/TanStack/router/issues/1917

**Comment by rtivital** [comment]
Try setting `<html {...mantineHtmlProps} />` like in Next.js template – https://mantine.dev/guides/next/#setup-with-app-router

**Comment by jamalsoueidan** [comment]
> Try setting `<html {...mantineHtmlProps} />` like in Next.js template – https://mantine.dev/guides/next/#setup-with-app-router

That fixed the issue
