### ISSUE TITLE
carousel slide item position uncorrect

### ISSUE THREAD

**Issue by jamalsoueidan** [mantinedev/mantine#7299]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/carousel

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

A simple Carousel demo with 3 Card withborder actually render the first and last one correctly on 100% (base), while the second card border is not shown.

```js
export default function Home({ loaderData }: Route.ComponentProps) {
  return (
    <Container size="xl" m="xl">
      <Carousel
        slideSize={{ base: "100%", sm: "50%", md: "25%" }}
        slideGap={{ base: "0", sm: "md" }}
        withControls={false}
      >
        <Carousel.Slide>
          <Card withBorder>1</Card>
        </Carousel.Slide>
        <Carousel.Slide>
          <Card withBorder>2</Card>
        </Carousel.Slide>
        <Carousel.Slide>
          <Card withBorder>3</Card>
        </Carousel.Slide>
      </Carousel>
    </Container>
  );
}
```

Here is screenshot, I'm not sure where why only the second is actually not showing the full Card with border.

![LFMU9F2VQ1](https://github.com/user-attachments/assets/ec3cf97e-c640-4dc4-89b9-111e9e82fbc1)
![YgkYpjInTd](https://github.com/user-attachments/assets/2cc8b131-bd04-46ef-bb36-636d8a99e839)
![fqbc7hFwqw](https://github.com/user-attachments/assets/07e851f9-6c41-4b98-b528-797087c29af0)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by jamalsoueidan** [comment]
Here is video while actually resizing the screen,,,the above images was on the first load...

![chrome_3bvZG2dVmx](https://github.com/user-attachments/assets/7d8e1554-7134-4cfa-a527-b407bdc089ee)

**Comment by rtivital** [comment]
Please provide a sandbox with a minimal reproduction

**Comment by jamalsoueidan** [comment]
Is there any sandbox I can fork to create the example? Thank you
