### ISSUE TITLE
Docs: no mention of certain functions on Theme functions page

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#730]
### Link to the page where something nasty is located

https://mantine.dev/theming/functions/

### Exact quote of what is wrong

In version `3.2.0` [hexToRgba function was removed](https://mantine.dev/changelog/3-2-0/#breaking-changes) in favor of `theme.fn.rgba()`, but apparently there is no mention of the new function on [Theme functions page](https://mantine.dev/theming/functions/), which makes it hard to find otherwise.

Also, none of these functions are mentioned in the docs: `theme.fn.themeColor()`, `theme.fn.size()`.

**Comment by rtivital** [comment]
Yep, it's missing, feel free to submit a PR

**Comment by rtivital** [comment]
Fixed
