### ISSUE TITLE
'auto' color scheme support for SSR

### ISSUE THREAD

**Issue by sovetski** [mantinedev/mantine#7314]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

I followed the instructions from here: https://mantine.dev/theming/color-schemes/

What I want is to make `auto` the theme color, if it is user first visit it must automatically detected and I also want to add a `Switch` to give the ability to change the theme.

The problem is that with SSR, I am getting this error

![image](https://github.com/user-attachments/assets/3e8b54c3-e76d-45aa-822e-872fe33d21a0)

My code is:

```jsx
const { colorScheme, setColorScheme } = useMantineColorScheme();

// ...
                    <Switch
                        size="md"
                        color="dark.4"
                        onLabel={sunIcon}
                        offLabel={moonIcon}
                        checked={colorScheme === "light"}
                        onChange={(event) =>
                            event.currentTarget.checked ? setColorScheme("light") : setColorScheme("dark")
                        }
                    />
```

I see this from the documentation:

`If you have server side rendering in your application (for example, if you use [Next.js](https://mantine.dev/guides/next/) or [Remix](https://mantine.dev/guides/remix/)), then you cannot use colorScheme value in your application to avoid hydration issues. Instead, you can use dark and light mixins from [postcss-preset-mantine](https://mantine.dev/styles/postcss-preset/) to generate styles that will hide elements based on color scheme value`

But the given example is for `ActionIcon` and it support only `light/dark` but not the `auto`, any idea please?

I also tried with:

```js
const computedColorScheme = useComputedColorScheme("dark", { getInitialValueInEffect: true });
```

But still have the same problem

Thanks

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
See https://mantine.dev/theming/color-schemes/#color-scheme-value-caveats
This case is not supported. It is not possible to retrieve color scheme value on the backend, it is stored in local storage.

**Comment by sovetski** [comment]
> See https://mantine.dev/theming/color-schemes/#color-scheme-value-caveats This case is not supported. It is not possible to retrieve color scheme value on the backend, it is stored in local storage.

Server can access to the cookies, how we can change this behaviour to store it in cookies? I tried a custom color schema manager like suggested here: https://mantine.dev/theming/color-schemes/#color-scheme-manager but the problem persist
