### ISSUE TITLE
Container.extend is not a function

### ISSUE THREAD

**Issue by sovetski** [mantinedev/mantine#7316]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Follow the steps here: https://mantine.dev/core/container/#responsive-max-width

![image](https://github.com/user-attachments/assets/b0cef12a-f749-4e0d-8d17-e24ba1841f51)
![image](https://github.com/user-attachments/assets/1fabcc35-e5a4-4ae7-960a-a22a7dbd8c35)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
https://help.mantine.dev/q/server-components#error-attempted-to-call-extend-from-the-server

**Comment by sovetski** [comment]
> https://help.mantine.dev/q/server-components#error-attempted-to-call-extend-from-the-server

Why there is no any link to this from Container documentation page?

Just after opening this issue I added "use client", this error disappeared but now the problem is that I can not use anymore "theme.colors.dark.7" in any server component...
