### ISSUE TITLE
[Feature Request] Docs: "Getting started" section should include @mantine/eslint-config

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#737]
### Usage example, including component/hook API

I think that `@mantine/eslint-config` is super useful, especially for new devs, since it bootstraps you with ESLint & Plugins + Prettier + sensible defaults for your projects with zero effort. It's an awesome package and really underrated!

### Possible implementation – describe how the feature can be implemented

The instructions to install `@mantine/eslint-config` should be included in [Getting started](https://mantine.dev/getting-started/) section of the docs as an _Optional_ step.

### Do you want to contribute this feature and create a pull request

Yes

**Comment by rtivital** [comment]
No, Mantine eslint config is not something I would like to promote, it is meant for internal usage only since it includes some rules specific to Mantine stack (jest, older rules for react scope, etc.).
