### ISSUE TITLE
Group position styles broken in column layout

### ISSUE THREAD

**Issue by mattrunyon** [mantinedev/mantine#745]
### What package has an issue

@mantine/core

### Describe the bug

The Group component does not apply `alignItems` or `justifyContent` props for column groups. Based on the styles it just ignores these props if the group is set to column. Not sure why as they're both completely valid for column mode in flexbox.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/amazing-stallman-1vms9?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Remove the conditionals for `direction === 'row'` in `Group.styles.ts`

**Comment by rtivital** [comment]
Thanks for reporting! If you want, you can submit a PR with a fix
