### ISSUE TITLE
visiting website initially shows a flash of white mode

### ISSUE THREAD

**Issue by deadcoder0904** [mantinedev/mantine#747]
### Link to the page where something nasty is located

https://mantine.dev/

### Exact quote of what is wrong

when i open the website for the 1st time, it shows a flash of white mode. it should directly show dark mode.

ps: love every component on mantine. best thing i've seen since chakra. if i wasn't using tailwind, would've used this but might try to recreate some components in tailwind. so good :)

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
Yes, we are aware of this issue, but this is how Mantine works with dark theme on static websites (docs are built with Gatsby)
