### ISSUE TITLE
react-hook-form cannot find name on Select field

### ISSUE THREAD

**Issue by mmahalwy** [mantinedev/mantine#760]
### What package has an issue

@mantine/core

### Describe the bug

![image](https://user-images.githubusercontent.com/3749095/151496098-75f55d86-3f5d-430b-9943-e35192a687bb.png)

When using react-hook-form's `register` method, the `ref` that's passed requires the component have `name` prop. For `Select`, I noticed the name is placed on a separate hidden input, causing this error. 

### In which browser did the problem occur

chrome

### Do you know how to fix the issue

Yes

### Possible fix

Not use `register` but use `Controller` that's provided by react-hook-form. This is not ideal though

**Comment by rtivital** [comment]
I don't have any experience with react-hook-form. Is there a way to make it work with hidden input?

**Comment by mmahalwy** [comment]
@rtivital I dont think so. Most form libraries assume `name` and `onChange` are on the same element. This has them on different elements (one is `Input` and other is `input` hidden)

**Comment by mmahalwy** [comment]
Is there a way to not have hidden input?

**Comment by rtivital** [comment]
Sure, since it collides with form libraries it should be removed since it does not serve any other purpose

**Comment by mmahalwy** [comment]
Yeah, I think that'd be great! Having the value stored on the `Input` instead of the hidden input

**Comment by rtivital** [comment]
Select input is used for searching and displaying label, not actual value

**Comment by rtivital** [comment]
Hidden input was removed in 3.6.4
