### ISSUE TITLE
[Feature Request] ResizablePanel

### ISSUE THREAD

**Issue by stevenle** [mantinedev/mantine#764]
### Usage example, including component/hook API

Looking for a container object with two panels which can be resized between the two. A few usage examples are below:

Resize left<->right panels:

```jsx
<ResizablePanel>
  <ResizablePanel.Item>Left Panel</Resizable.Item>
  <ResizablePanel.Item>Right Panel</Resizable.Item>
</ResizablePanel>
```

Resize top/bottom panels (using `direction="column"`, similar to `<Group>`):

```jsx
<ResizablePanel direction="column">
  <ResizablePanel.Item>Top Panel</ResizablePanel.Item>
  <ResizablePanel.Item>Bottom Panel</ResizablePanel.Item>
</ResizablePanel>
```

Custom icon for the resize dragger:

```jsx
<ResizablePanel icon={<DraggerIcon />}>
  <ResizablePanel.Item>Left Panel</ResizablePanel.Item>
  <ResizablePanel.Item>Right Panel</ResizablePanel.Item>
</ResizablePanel>
```

Using an initial width (e.g. if the caller wishes to persist the value to localStorage):

```jsx
function MyComponent() {
  const [leftPanelWidth, setLeftPanelWidth] = useLocalStorageValue({ 
    key: 'leftPanelWidth', 
    defaultValue: '300' 
  });

  return (
    <ResizablePanel icon={<DraggerIcon />}>
      <ResizablePanel.Item 
        initialSize={Number(leftPanelWidth)} 
        onChange={(width: number) => setLeftPanelWidth(String(width))}
      >
        Left Panel
      </ResizablePanel.Item>
      <ResizablePanel.Item>Right Panel</ResizablePanel.Item>
    </ResizablePanel>
  );
}
```

### Possible implementation – describe how the feature can be implemented

An example of an existing implementation: https://danfessler.github.io/react-panelgroup/

### Do you want to contribute this feature and create a pull request

No

**Comment by rtivital** [comment]
I do not think that we should add it, this component is very situational, and I'd rather leave its implementation to other libraries
