### ISSUE TITLE
Modal doesn't trap focus

### ISSUE THREAD

**Issue by brykov** [mantinedev/mantine#770]
Hi. I stumbled upon a scenario when a modal can't trap focus. It goes like this:
- Open a drawer
- From the drawer open a modal
- Hide the drawer immediately in the same callback 

As a result, the modal is opened but it has no focus and doesn't close by pressing ESC. 

The reason it happens is that the drawer is animated. If I wait for 300ms before opening the modal, everything works as expected. 

I don't know what the fix here would be. Maybe I could tell the drawer to pass focus to the modal via ref in some callback?

**Comment by rtivital** [comment]
Thanks for reporting!

**Comment by auronsan** [comment]
I tried fix this bug. seems need change like 3 files.  on Drawer passRefModal, on Modal pass modalRef, and useFocusReturn pass the ref to trigger last active focus. but still not gonna work without setTimeout too on useFocusReturn.

so I think use setTimeout on 1 line code it's not gonna hurt

**Comment by rtivital** [comment]
Fixed in 5.1.4, Modal and Drawer components now support `withFocusReturn` prop, set it to false to prevent the component from returning focus to previous active element after Modal/Drawer is closed.

**Comment by adri1wald** [comment]
Hey @rtivital, would be awesome if you could make withFocusReturn dynamic. My use case is under certain circumstances I do want the focus to return when I close the modal, but other time I don't. E.g. in my modal there is an action that closes the modal and renders an input the main part of my app. This input should be focused after closing the modal. However, when the modal is closed through without taking this action the focus should return to where it was before. Could `withFocusReturn` accept a callback of signature `() => boolean`? Then I could set a ref to `true/false` in `onClose`.

**Comment by rtivital** [comment]
I'll make it dynamic without function in next patch
