### ISSUE TITLE
[Feature Request] Table sorting

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#771]
### Usage example, including component/hook API

`Table` component should have a prop to make it possible for users to sort table columns in ascending or descending order.

### Possible implementation – describe how the feature can be implemented

[Example of table sorting in MUI docs.](https://mui.com/components/data-grid/sorting/)

**Comment by Ultra-Instinct-05** [comment]
What you have linked above is a separate thing called `datagrid` or `datatables`. See #276 
The `Table` component is just a simple wrapper around HTML's `table` element. Ideally sorting and other stuff should be kept in a separate package.
