### ISSUE TITLE
[@mantine/core] Menu.Item onClick with next/router

### ISSUE THREAD

**Issue by dimbslmh** [mantinedev/mantine#776]
### What package has an issue

@mantine/core

### Describe the bug

`<Menu.Item onClick={() => router.push('/login')}>Login</Menu.Item>`

Navigating to another page using next/router from a Menu.Item triggers the following error:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Transition (webpack-internal:///./node_modules/@mantine/core/esm/components/Transition/Transition.js:14:3)
    at Popper (webpack-internal:///./node_modules/@mantine/core/esm/components/Popper/Popper.js:43:3)
    at div
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/components/Box/Box.js:42:18)
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/components/Menu/Menu.js:96:5)
```

Not sure why this is handled differently than the react-router-dom Link component

- Example react-router-dom: https://codesandbox.io/s/wizardly-glade-32yts
- Exampe next/router: https://codesandbox.io/s/red-dawn-jl812

### In which browser did the problem occur

Chromium Version 97.0.4692.99 (Official Build) snap (64-bit)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/red-dawn-jl812

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
You can ignore this warning, there is not a memory leak, it should be fixed in future versions of React
