### ISSUE TITLE
[Feature Request] Table component needs a prop for column alignment

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#781]
### Usage example, including component/hook API

`Table` component should have a prop to align columns with `text-align: center` and `text-align: right`.

**Comment by rtivital** [comment]
I think we do not really need that for Table component

**Comment by Brookke** [comment]
I don't think that this should be done at a table level, however ideally there would be a way to disable Mantines default `text-align: left` on the th element.

Currently I can't seem to override the alignment for a particular column header as Mantines styles take precedence.

I've added an example of this here:
https://github.com/Brookke/mantine-example/blob/master/pages/index.tsx#L26-L29
