### ISSUE TITLE
use-local-storage-value should support JSON values

### ISSUE THREAD

**Issue by melloware** [mantinedev/mantine#787]
### What package has an issue

@mantine/hooks

### Describe the bug

Currently the `useLocalStorageValue` enforces that the object must extend `String`.

```typescript
useLocalStorageValue<T extends string>
```

This way you can't use complex objects or primitives to store data which is a common use case such as...

```typescript
const [valueBoolean, setBoolean] = useLocalStorageValue<boolean>({
    key: "my-boolean",
    defaultValue: true
  });
```

### In which browser did the problem occur

ALL

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/agitated-gauss-8gk5r?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I am switching from my own personal local storage hook to Mantine Hooks and my old values I always store and retrieve as JSON makes this the most flexible it can be and allows users to convert directly from `useState`.

**Comment by rtivital** [comment]
Native local storage supports only strings as data, if this gets implemented hook should handle custom serialization/deserialization functions.

**Comment by melloware** [comment]
Agreed this is my current hook i have been using that I would like to replace with Mantine Hooks...

```typescript
import { Dispatch, SetStateAction, useEffect, useState } from "react";

/**
 * Hook to wrap around useState that stores the value in the browser local storage.
 * 
 * @param initialState the initial state of the value
 * @param key the key to store the value in local storage
 * @returns a stateful value, and a function to update it.
 */
export function useLocalStorage<S>(initialState: S | (() => S), key: string): [S, Dispatch<SetStateAction<S>>] {

    const [value, setValue] = useState<S>(() => {
        const stickyValue = window.localStorage.getItem(key);
        return stickyValue !== null
            ? JSON.parse(stickyValue)
            : initialState;
    });

    useEffect(() => {
        window.localStorage.setItem(key, JSON.stringify(value));
    }, [key, value]);

    return [value, setValue];
}
```

Been using this for a while successfully.

**Comment by melloware** [comment]
as pointed out this will break backward compaibility so a new hook is probably needed to handle `JSON` serialization.

**Comment by rtivital** [comment]
JSON serialization was added in 4.0.3 by default – https://mantine.dev/hooks/use-local-storage/#serializedeserialize-json

**Comment by melloware** [comment]
Excellent work!
