### ISSUE TITLE
Cannot work with vitejs.

### ISSUE THREAD

**Issue by blackcater** [mantinedev/mantine#79]
I'am using mantine in vitejs. But it's not work.

![image](https://user-images.githubusercontent.com/9465551/118445931-9c5bd580-b721-11eb-91d4-5bb989789fbf.png)

The source code is here. https://github.com/blackcater/vitejs-with-mantine.bug-report

**Comment by rtivital** [comment]
Hi Elon, thanks for reporting! I haven't used vite yet, so I cannot tell what's wrong here, if you can have a look at source code and help identify the issue that would be great.

Here is source code for Button component – https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Button/Button.tsx

**Comment by blackcater** [comment]
> Hi Elon, thanks for reporting! I haven't used vite yet, so I cannot tell what's wrong here, if you can have a look at source code and help identify the issue that would be great.
> 
> Here is source code for Button component – [https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Button/Button.tsx](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Button/Button.tsx?rgh-link-date=2021-05-17T07%3A19%3A33Z)

I don't think vitejs works well with umd modules.

I spend one day to refactoring build scripts of mantine, now It will output es module and umd module two version.

Every thing goes well.

![image](https://user-images.githubusercontent.com/9465551/118750376-e06de800-b891-11eb-9393-f43a07d3c186.png)

**Comment by rtivital** [comment]
Can you help me add esm support to build step with PR? Webpack configuration is located here – https://github.com/mantinedev/mantine/blob/master/configuration/webpack/create-package-config.ts

If not, please share what you've used to output both esm and umd, I think this is a great addition and should definitely be added in future versions

**Comment by blackcater** [comment]
> Can you help me add esm support to build step with PR? Webpack configuration is located here – [https://github.com/mantinedev/mantine/blob/master/configuration/webpack/create-package-config.ts](https://github.com/mantinedev/mantine/blob/master/configuration/webpack/create-package-config.ts?rgh-link-date=2021-05-19T06%3A47%3A29Z)
> 
> If not, please share what you've used to output both esm and umd, I think this is a great addition and should definitely be added in future versions

I hasn't finished it yet. I  have changed a lot of files. Such as:

1. use `esbuild` instead of `typescript` to compile `.ts` and `.tsx` files.
2. use `rollup` instead of `webpack` to bunde libraries.
3. remove `dependencies` from externals, so library will be larger.
4. use `storybook-addon-turbo-build` to reduce building time.
5. use `esbuild-jest` to replace `ts-jest`

You can see my changes in https://github.com/blackcater/mantine/tree/feature/fix-vitejs .

Because of the big changes. Now unit tests cannot passed.

**Comment by rtivital** [comment]
Alright, that will be super cool if you can make it work, thanks in advance!
