### ISSUE TITLE
Autocomplete and Select dropdown not showing with SSR

### ISSUE THREAD

**Issue by ericlam51** [mantinedev/mantine#791]
### What package has an issue

@mantine/core

### Describe the bug

I am using Mantine with Remix and realize that the Autocomplete and Select components are broken. I check the generated HTML using Chrome's "Inspect Element" and the dropdown does not get rendered.

```
// entry.server.tsx

import { renderToString } from "react-dom/server";
import { RemixServer } from "remix";
import type { EntryContext } from "remix";
import { injectStylesIntoStaticMarkup } from "@mantine/ssr";

export default function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext
) {
  const markup = renderToString(
    <RemixServer context={remixContext} url={request.url} />
  );
  responseHeaders.set("Content-Type", "text/html");

  return new Response(
    `<!DOCTYPE html>${injectStylesIntoStaticMarkup(markup)}`,
    {
      status: responseStatusCode,
      headers: responseHeaders,
    }
  );
}
```

```
// routes/index.tsx

export default function IndexRoute() {
  return (
    <div style={{ padding: 40, maxWidth: 400 }}>
      <Select
        label="Your favorite framework/library"
        placeholder="Pick one"
        data={[
          { value: "react", label: "React" },
          { value: "ng", label: "Angular" },
          { value: "svelte", label: "Svelte" },
          { value: "vue", label: "Vue" },
        ]}
      />
    </div>
  );
}
```

Renders:
![image](https://user-images.githubusercontent.com/7005230/152083119-92c765f9-7b1c-4ef6-ae8c-4d302f9c2405.png)

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
All dropdowns are rendered within Portal and portals do not support server side rendering.

**Comment by ericlam51** [comment]
Is there a way to make Mantine work with Remix without using SSR?

**Comment by rtivital** [comment]
Mantine works fine with remix with ssr, there is no way to disable ssr in Remix as far as I know

**Comment by ericlam51** [comment]
There should be a disclaimer or a flag indicating which components are not compatible with SSR. Using Mantine with Remix is not ideal because some components are not compatible.

**Comment by rtivital** [comment]
All components are compatible with ssr, Select/Autocomplete dropdowns cannot be opened without user interaction, so there is no point of rendering them anyway.

**Comment by rtivital** [comment]
If you have any other questions, feel free to reach out on Discord

**Comment by onlymipa** [comment]
> Is there a way to make Mantine work with Remix without using SSR?

You can just enable script in remix, and you'll just get want.
``` tsx 
// root.tsx
import { Scripts } from "remix";

<body>
    <Scripts />
</body>
```
Now mantine components all work.
