### ISSUE TITLE
use-hotkeys: Ignore keystrokes within input/select elements

### ISSUE THREAD

**Issue by ChaseMalik** [mantinedev/mantine#792]
### Usage example, including component/hook API

I tried to use useHotkeys to control a video player (space for play/pause, m for mute, f for fullscreen, etc), but when the user types in the search bar at the top of the page it triggers the hotkey instead. Ideally the listeners would ignore input on input tags by default (or at least optionally - for a non-breaking change)

### Possible implementation – describe how the feature can be implemented

It could be done similarly to https://react-hotkeys-hook.vercel.app/docs/api/use-hotkeys, which takes an options object as a parameter. One of the options is enableTags, which is an array of tags to enable listening for - as by default they ignore keystrokes on inputs, selects, and textareas.

For a non-breaking change, it could be implemented as a disabletags array

**Comment by melloware** [comment]
I agree with this request.

**Comment by rtivital** [comment]
Yep, I'll try fixing that in one of the next patches

**Comment by rtivital** [comment]
Fixed in 3.6.7 patch
