### ISSUE TITLE
Blue marks on iPad but not on laptop

### ISSUE THREAD

**Issue by eellio** [mantinedev/mantine#793]
Drawer, and Tabs, I think, have blue edges on iPad. They don’t on laptop under the same usage sequence. Guessing the blue is a focus thing, but it is unsightly and it’s not clear how to get the same behavior in mobile safari as in desktop chrome

**Comment by rtivital** [comment]
That is how mobile Safari handles :focus-visible selector when element is focused programmatically. You can disable focus styles with Styles API.
