### ISSUE TITLE
[Feature Request] Add "openDelay" prop to the Tooltip component

### ISSUE THREAD

**Issue by captchafree** [mantinedev/mantine#797]
### Usage example, including component/hook API

It would be nice if the `Tooltip` component had an additional `openDelay` prop that functioned exactly like the existing `delay` prop, but for the opening. [Here is an example of it in Chakra](https://chakra-ui.com/docs/overlay/tooltip#more-examples).

### Possible implementation – describe how the feature can be implemented

We can add an `openDelay` prop to the `Tooltip` component and modify the `handleOpen` function to behave like the existing `handleClose` function.

### Do you want to contribute this feature and create a pull request

Yes

**Comment by rtivital** [comment]
This is in our backlog as a breaking change, if you are planning to send a PR, please use `dev` branch as target and rename `delay` prop to `closeDelay` to avoid confusion

**Comment by rtivital** [comment]
Will be released as part of 4.0.0 release
