### ISSUE TITLE
Menu control issue

### ISSUE THREAD

**Issue by juan-manuel-alberro** [mantinedev/mantine#80]
Hi,

I'm trying to use an `<Avatar />`  as a control for a menu but it seems it doesn't work properly (I cannot click the element and open the menu) when you wrap the element between `<Suspense />`

I'm getting the initials from an async call, the _hardcoded_ example is just to recreate the issue

```jsx
        <Menu
          menuPosition={{ top: 40, right: 0 }}
          control={
            <Suspense fallback="...">
              <Avatar>JM</Avatar>
            </Suspense>
          }
        >
          <MenuItem icon={<RiSettings2Line />}>Settings</MenuItem>
          <MenuItem icon={<RiMessage3Line />}>Messages</MenuItem>
          <Hr />
          <MenuItem color="red">Delete account</MenuItem>
        </Menu>
```

Thanks.

**Comment by rtivital** [comment]
Hi Juan, Menu component relies on React.cloneElement to provide props to control – https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Menu/Menu.tsx#L131-L141

In your example these props are set on Suspense component instead of Avatar, to fix that you can wrap everything with div/span element:

```tsx
<Menu
  menuPosition={{ top: 40, right: 0 }}
  control={
    <div>
      <Suspense fallback="...">
        <Avatar>JM</Avatar>
      </Suspense>
    </div>
  }
>
  <MenuItem icon={<RiSettings2Line />}>Settings</MenuItem>
  <MenuItem icon={<RiMessage3Line />}>Messages</MenuItem>
  <Hr />
  <MenuItem color="red">Delete account</MenuItem>
</Menu>;
```

**Comment by rtivital** [comment]
Note that non-interactive elements like avatar are not supposed to be used with menu, as it will break accessibility and keyboard support, use regular button in case you care about that (it will require additional styling to remove default button appearance though)

**Comment by juan-manuel-alberro** [comment]
Hi @rtivital 
Yes, I tried that but no luck, I also use other components like `<Container>` as a parent but the click is not available.
I'll consider your comment and use a Button instead, thanks 😄

**Comment by juan-manuel-alberro** [comment]
I had to do this

```jsx
          control={
            <div>
              <MenuControl />
            </div>
          }
```
And worked as expected, if I include the `<div>` inside my component it doesn't work.
I'll close the issue then, thanks 😄

**Comment by rtivital** [comment]
I've created a demo with avatar, works fine – https://codesandbox.io/s/holy-bash-0emdw?file=/src/App.tsx

In your component you need to spread `...others` props to enable all events from Menu.

**Comment by juan-manuel-alberro** [comment]
Following your example, I added the other cases I tried before - https://codesandbox.io/s/musing-lovelace-unywp
For some reason including the parent inside the component didn't work.

**Comment by rtivital** [comment]
You need to spread props to target element – https://codesandbox.io/s/zealous-euclid-h6vly?file=/src/App.tsx
