### ISSUE TITLE
Getting started page leads to 404

### ISSUE THREAD

**Issue by Dokanix** [mantinedev/mantine#800]
Steps:

- Open https://mantine.dev/pages/basics/
- Go to Mantine packages
- Click on the "30+ React Hooks" link

You land at the 404 page

![image](https://user-images.githubusercontent.com/47307252/152363561-f79dc719-6926-437d-9aa8-eb543f0b898a.png)

**Comment by rtivital** [comment]
Thanks for reporting

**Comment by rtivital** [comment]
Fixed
