### ISSUE TITLE
disabled is a valid prop for Anchor but throws TS error

### ISSUE THREAD

**Issue by mmahalwy** [mantinedev/mantine#801]
### What package has an issue

@mantine/core

### Describe the bug

![image](https://user-images.githubusercontent.com/3749095/152449777-20821218-10e9-48c6-ab63-7c9714e45a7f.png)

### In which browser did the problem occur

Chrome

**Comment by rtivital** [comment]
Anchor props by default extends `React.ComponentPropsWithoutRef<'a'>`, React types do not consider disabled to be a valid prop an `a` tag (it does nothing), see example – https://codesandbox.io/s/confident-murdock-4kfi9?file=/src/App.tsx

**Comment by mmahalwy** [comment]
@rtivital got it. Thanks for investigating. Do we want to add a `disabled` prop and style for anchors?

**Comment by rtivital** [comment]
No

**Comment by mmahalwy** [comment]
@rtivital reason to why? Buttons have disabled state

**Comment by rtivital** [comment]
Anchors do not have disabled state, `disabled` prop does nothing

**Comment by mmahalwy** [comment]
@rtivital right, do we want to add that as a feature?

**Comment by rtivital** [comment]
No
