### ISSUE TITLE
I m trying to integrate RichTextEditor but facing this issue ):

### ISSUE THREAD

**Issue by jasbirrajrana** [mantinedev/mantine#811]
### What package has an issue

@mantine/rte

### Describe the bug

`yarn add @mantine/rte @mantine/core @mantine/hooks`

doing:

`const Editor = ()=>{
const [value,setValue]=useState('<p>hey there</p>')
return (
<RichTextEditor value={value} onChange={setValue}/>
)
}`

but showing:
![image](https://user-images.githubusercontent.com/68157847/152680789-a4ef390e-6581-4616-8004-a575b277faeb.png)

 PS: I m new to Mantine Please help me out!
Thanks :)

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

working fine in codesandbox 😶

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Please make sure you are using the latest version (3.6.6) of ALL Mantine packages

**Comment by jasbirrajrana** [comment]
yah its working now!
Thanks man 😊
