### ISSUE TITLE
[Feature Request] [Select] Do not filter searchable select by sected item

### ISSUE THREAD

**Issue by Tobolka** [mantinedev/mantine#815]
### Usage example, including component/hook API

**Problems**:
1.  Users think are no other options when want to switch something in searchable select, when something was selected. 
2.  Not possible to switch between items by keyboards when using searchable select, when something was selected. 

**Solution**
When re-opening `searchable` select with selected option, do not filter data, but show all data with the selected item.  

<img width="481" alt="Screenshot 2022-02-07 at 11 09 37" src="https://user-images.githubusercontent.com/959976/152768212-90dd3c86-7ee0-4ee8-bb4c-c8e5c8aadfa2.png">

Here is an example from the blueprint. 
https://blueprintjs.com/docs/#select/suggest

### Do you want to contribute this feature and create a pull request

No

**Comment by rtivital** [comment]
You are describing the behavior that was removed from Select component in one of previous versions. It is not coming back as most people reported it to be not intuitive. It also has many edge cases.

You can control options filtering by providing custom filter function, for example, to disable filtering, provide function that will always return true:
```tsx
<Select filter={() => true} />
```

You can change this function based on your current value and search term. See custom filter function example here – https://mantine.dev/core/select/#custom-item-component
