### ISSUE TITLE
useLocalStorageValue updates do not propagate through components

### ISSUE THREAD

**Issue by JohannesKlauss** [mantinedev/mantine#819]
### What package has an issue

@mantine/hooks

### Describe the bug

When I set a local storage value in component A and also use it in component B, the state in component B gets stale:

```tsx
export function Example() {
  const [value, setValue] = useLocalStorageValue<string>({
    key: "key",
    defaultValue: ""
  });

  return (
    <button onClick={() => setValue(Math.random().toString())}>
      Change value: {value}
    </button>
  );
}


export function OtherComponent() {
  const [value] = useLocalStorageValue<string>({
    key: "key",
    defaultValue: ""
  });

  return <div>Change value: {value}</div>; // When clicking the button in the Example component, this value gets stale
}
```

Not sure what in the code causes the problem.

### In which browser did the problem occur

Google Chrome 98

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/gifted-euler-efi1l?file=/src/Example.tsx

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
use-local-storage-value != context to store your state, browsers do not support subscriptions to local storage value in the same tab. You should not use it to communicate state between components, use context or state management library instead.
