### ISSUE TITLE
modal.openContextModal adds any extra props onto it's underlying `div` 

### ISSUE THREAD

**Issue by marinater** [mantinedev/mantine#820]
Hi! So I noticed an issue with `modal.openContextModal` where any extra props you provide end up as attributes on the underlying `div`. React raises a warning about this saying `Warning: React does not recognize the `myPropName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `mypropname` instead`

I've traced the issue back as follows:

- User calls `modal.openContextModal({ ..., categoryID })` with custom props, such as `categoryID`
- The [following snippet runs](https://github.com/mantinedev/mantine/blob/d414ad4f20ce4825d1f9e0e04ab59a7a7d1f40b2/src/mantine-modals/src/ModalsProvider.tsx#L86)
    - Note that `props` still contains the extra `categoryID` key
- The extra keys get sent to the Modal component as props by the [following snippet](https://github.com/mantinedev/mantine/blob/d414ad4f20ce4825d1f9e0e04ab59a7a7d1f40b2/src/mantine-modals/src/ModalsProvider.tsx#L138)
- The extra keys then get destructured as props onto a `<Box/>`, which will in turn destructure as props onto a `<div/>`
in the [following snippet](https://github.com/mantinedev/mantine/blob/d414ad4f20ce4825d1f9e0e04ab59a7a7d1f40b2/src/mantine-core/src/components/Modal/Modal.tsx#L169)

**Comment by rtivital** [comment]
Fixed in one of 4.0.x patches
