### ISSUE TITLE
Adding Nextjs Link to Menu.item

### ISSUE THREAD

**Issue by Angusross111** [mantinedev/mantine#824]
### What package has an issue

@mantine/core

### Describe the bug

Is there a better way to add a Nextjs Link to a Menu.item and keep the original look?
```
<Menu.Item icon={<ExitIcon />}>
    <Link href="/api/auth/signout" passHref>
        <Menu.Item component="a" style={{ padding: 0, margin: 0 }}>
            Sign out
        </Menu.Item>
    </Link>
</Menu.Item>;
```

### In which browser did the problem occur

Chrome - Version 97.0.4692.99 

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/divine-microservice-8bgty?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
You need to create a wrapper component:
```tsx
const NextLink = forwardRef((props, ref) => (
  <Link href={props.href}>
    <a {...props} ref={ref} />
  </Link>
));
```

And then pass it to Menu.Item:
```tsx
<Menu>
  <Menu.Item component={NextLink} href="/hello">
    Hello
  </Menu.Item>
</Menu>
```

**Comment by Angusross111** [comment]
Awesome thanks! Love the library by the way.
