### ISSUE TITLE
IE11 support Esc in keydown event handler

### ISSUE THREAD

**Issue by markoremus** [mantinedev/mantine#825]
### What package has an issue

@mantine/core

### Describe the bug

Components like Drawer, Menu or Modal are supposed to get closed using escape button on the keyboard. The corresponding handler currently checks for event.code === "Escape".
IE11 however uses the event.code = "Esc" thus those components currently cannot be closed using keyboard.

### In which browser did the problem occur

Internet Explorer 11

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Please include "Esc" as another supported value for the corresponding keydown eventHandlers

**Comment by rtivital** [comment]
IE11 is not officially supported, but we can accept PR that fixes it
