### ISSUE TITLE
AppShell has incorrect padding when used without normalize.css

### ISSUE THREAD

**Issue by gempain** [mantinedev/mantine#828]
### What package has an issue

@mantine/core

### Describe the bug

I couldn't find the words to say how your framework is a million times better than anything I've used so far, so I'll just go straight to the point.

When you enable `fixed` on `AppShell`, the `main` left and top paddings are much bigger than the right and bottom ones. As far as I can see, the code which controls this padding is [here](https://github.com/mantinedev/mantine/blob/3d84c2284570a6bda5a1e12afe35b9c3b5c2c53c/src/mantine-core/src/components/AppShell/AppShell.styles.ts#L38) and it uses the `padding` property of the `AppShell`.

Or maybe this is just me not understanding how to properly configure the `AppShell` component.

Keep up the great work!

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/crazy-fire-vvq7i?file=/src/App.js

**Comment by rtivital** [comment]
Thanks for kind words, in order for AppShell to work properly you can use `withNormalizeCSS` option on MantineProvider – https://codesandbox.io/s/pensive-sky-977l7

**Comment by gempain** [comment]
Are you sure this works ? I opened your codesandbox but I have 0 padding right and bottom:
![Screenshot 2022-02-14 at 12 06 25](https://user-images.githubusercontent.com/13135149/153852836-7d6927e1-026d-4897-a5c0-c9a8caea07bb.png)

**Comment by bogordesaincom** [comment]
use css 

```
.mantine-AppShell-main {
  padding-left: 0;
}
```

**Comment by rtivital** [comment]
Yeah, I see that there is some padding missing, I'll fix it in next patch or 4.0

**Comment by rtivital** [comment]
I've released a fix with correct padding in 3.6.8

**Comment by gempain** [comment]
Wow thank you so much for being so quick! I was actually going to give it a try at a PR tonight but you beat me to it.

**Comment by oliverkidd** [comment]
just to continue this thread im having some issues with padding on the app main too? Using a header and nav without an aside ive set the padding on the main AppShell to padding={0} and left/right looks great but there's still some top padding?
