### ISSUE TITLE
Confirm Modal should call onCancel when closed

### ISSUE THREAD

**Issue by mattrunyon** [mantinedev/mantine#837]
### Usage example, including component/hook API

Currently, if a confirm modal is closed in the `@mantine/modals` package, the `onCancel` handler is not called. There is a separate `onClose` handler, but I think it is reasonable to call `onCancel` when the modal is closed unless a separate `onClose` handler is provided. Seems reasonable that close = cancel from an interaction standpoint

Here's a code sandbox demonstrating
https://codesandbox.io/s/twilight-voice-rmgoj?file=/src/App.tsx

### Possible implementation – describe how the feature can be implemented

Make the modal call `onCancel` when it closes. Could make this only happen if there is no separate `onClose` prop passed to the modal

### Do you want to contribute this feature and create a pull request

Yes

**Comment by rtivital** [comment]
Feel free to send a PR to `dev` branch

**Comment by wes337** [comment]
I find this unclear. The `onCancel` is equal to `onClose`? You say the `onCancel` callback should be called when the _"X"_ in the top right of the modal is clicked. Should it also be called when the modal is closed by clicking outside of it?

If yes, then what is the purpose of having these 2 props? Should one have priority over the other, or should both be called if both `onCancel` and `onClose` are provided?

**Comment by rtivital** [comment]
`onClose` is called when modal is closed no matter the reason: when user confirms `onClose` is called. But you are right we probably should remove `onClose` entirely not to confuse people.

**Comment by wes337** [comment]
I have created a solution that will simply call whichever is provided. So if you provide `onCancel`, this will be called when the modal is closed. If you provide `onClose`, this will be called. If you provide both `onCancel` and `onClose`, both will be called synchronously. 

I can't think of a use case in this context where both would be needed, but wouldn't removing one cause backwards breaking changes?

**Comment by rtivital** [comment]
It would cause breaking changes, next version is 4.0, so that does not really matter

**Comment by mattrunyon** [comment]
I was saying from a user perspective that closing a confirmation is an equivalent action to hitting cancel.

You could say onClose should be called after both cancel and confirm if you wanted to keep all 3. If not I would say removing close and keeping cancel probably makes most sense to me

**Comment by wes337** [comment]
> `onClose` is called when modal is closed no matter the reason: when user confirms `onClose` is called

This makes sense, so `onClose` and `onCancel` are almost equivalent but not quite.

**Comment by mattrunyon** [comment]
Idk why this didn't auto close, but it looks like the commit made it in to 4.0 so I'll close the issue

https://github.com/mantinedev/mantine/commit/2fe2f91314953550a246084bb358fcf7ed7ced91 has 4.0.0 tag
