### ISSUE TITLE
Infinite recursion in DatePickerBase event handler

### ISSUE THREAD

**Issue by lukasmoellerch** [mantinedev/mantine#848]
### What package has an issue

@mantine/dates

### Describe the bug

When trying to open a Date input with the newest version of mantine an infinite recursion occurs in the openDropdown function when the allowFreeInput property is set: https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/src/components/DatePickerBase/DatePickerBase.tsx#L196

### In which browser did the problem occur

Safari 15.1 (17612.3.5)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/peaceful-dewdney-2iosre

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Call `setDropdownOpened(true);` instead.

**Comment by rtivital** [comment]
Thanks for reporting! This issue was fixed in 3.6.9 patch.
