### ISSUE TITLE
[Feature Request] npm keywords

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#850]
### Usage example, including component/hook API

As of now it's impossible for people to find Mantine when they search for something like 'React components' on [npm](https://www.npmjs.com).

That's why `@mantine/core` package needs to have proper keywords.

### Possible implementation – describe how the feature can be implemented

Examples of what other libraries do.

Chakra UI:
<img width="706" alt="Screen Shot 2022-02-17 at 19 02 53" src="https://user-images.githubusercontent.com/44101337/154586053-c019cf56-4e59-454a-b574-578710bf08ca.png">

Ant Design:
<img width="640" alt="Screen Shot 2022-02-17 at 19 04 01" src="https://user-images.githubusercontent.com/44101337/154586155-7fe0eda1-0cf8-4713-bae1-d7964a3bbd53.png">

MUI:
<img width="562" alt="Screen Shot 2022-02-17 at 19 04 44" src="https://user-images.githubusercontent.com/44101337/154586234-8c016110-2a49-41b7-8872-958e341287cf.png">

**Comment by rtivital** [comment]
Resolved by #867
