### ISSUE TITLE
[Feature Request] npm logo and short description

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#851]
### Usage example, including component/hook API

`@mantine/core` package needs to have a logo and short description of Mantine project. This way it looks more professional/production-ready and builds user trust when they just found the library.

### Possible implementation – describe how the feature can be implemented

Examples of how other libraries do it.

Ant Design:
<img width="524" alt="Screen Shot 2022-02-17 at 19 09 24" src="https://user-images.githubusercontent.com/44101337/154586892-c79bc467-45d6-4ff4-9f64-8468b6f07f83.png">

MUI:
<img width="744" alt="Screen Shot 2022-02-17 at 19 10 07" src="https://user-images.githubusercontent.com/44101337/154586944-48d4d811-e484-4cea-8313-02f1a1f1c0fc.png">

**Comment by rtivital** [comment]
I've decided that it is not required
