### ISSUE TITLE
The Notification docs page has a typo

### ISSUE THREAD

**Issue by Theboiboi8** [mantinedev/mantine#855]
### Link to the page where something nasty is located

https://mantine.dev/others/notifications/#notification-props

### Exact quote of what is wrong

in the `id` section of the `Notification Props` page there is a typo in the word `and`. In the page it is spelled as `adn` and the word `by` slightly later in the sentence is spelled as `be`:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/93494094/154719979-508889cb-ccd4-4297-bf1c-1e4684540396.png">

### Are you willing to create pull request with the fix?

No

**Comment by rtivital** [comment]
Thanks for reporting!

**Comment by rtivital** [comment]
Fixed in #856, will be out with 4.0
