### ISSUE TITLE
Avatar typings don't accept src={null}

### ISSUE THREAD

**Issue by canac** [mantinedev/mantine#864]
### What package has an issue

@mantine/core

### Describe the bug

The [example](https://mantine.dev/core/avatar/) shows a component `<Avatar src={null}>...</Avatar>`. However, the TypeScript typings only allow `string | undefined`, not `null`.

### In which browser did the problem occur

N/A

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Change https://github.com/mantinedev/mantine/blob/4339b8ab07207bb6c04062f49153d7b631a9044f/src/mantine-core/src/components/Avatar/Avatar.tsx#L18 to `alt?: string | null`;

**Comment by rtivital** [comment]
Thanks for reporting! Do you want to create a PR with a fix?
