### ISSUE TITLE
Shadow on <Paper> component (and perhaps in general) does not work very well with dark mode with `withGlobalStyles`

### ISSUE THREAD

**Issue by Theboiboi8** [mantinedev/mantine#866]
### What package has an issue

@mantine/core

### Describe the bug

When enabling `shadow` on a <Paper> component with dark mode enabled, the shadow isn't really a shadow and more of a scaled down darker version of the original `Paper` component.
Examples:
__Dark mode__: (brightness and exposure values edited for better visibility _(Most noticable on the codesandbox when zoomed in)_ )
![Screenshot 2022-02-19 220421](https://user-images.githubusercontent.com/93494094/154817365-06ce5268-248d-474d-8129-100335975da3.png)
__Light mode__:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/93494094/154817409-57cb6ca6-1d62-4070-ab37-94cefb0a4c51.png">

### In which browser did the problem occur

Opera 83.0.4254.62 (replicated on Firefox 97 on MacOS Mojave via BrowserStack)

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/snowy-fire-7q9bjg?file=/src/App.tsx

### Do you know how to fix the issue

No

### Possible fix

maybe `filter: blur`?

**Comment by rtivital** [comment]
That is intentional, dark theme uses the other way to indicate elevation – lighter color. I, personally, find shadows in dark theme inappropriate and ugly (see Twitter's dimmed theme) and not planning to change shadows behavior because of that.
