### ISSUE TITLE
Provide access to event in Modal's onClose

### ISSUE THREAD

**Issue by tim-coutinho** [mantinedev/mantine#869]
### What package has an issue

@mantine/core

### Describe the bug

When rendering a modal inside a parent element with an `onClick` handler, that handler is called when the modal is closed either by clicking the close button or clicking outside the modal, when those options are available. Granted I don't know all the ins and outs of event bubbling in JS, but I would assume since the modal is rendered outside of the parent node's hierarchy by default that the `onClose` event wouldn't bubble up to the parent element, but apparently not. I'm currently getting around this by wrapping the code in my parent element's `onClick` handler with `if (!e.target.classList.contains("mantine-Button-label"))` in order to check if the original element clicked belongs to the button activating the modal, though obviously that isn't ideal.

### In which browser did the problem occur

Firefox Nightly v. 99.0a1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/gallant-newton-3rriw8?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Provide access to the click event in `Modal`'s `onClose` so as to be able to call `e.stopPropagation()`, e.g. `onClose():  void` -> `onClose(e?: MouseEvent): void`

**Comment by rtivital** [comment]
Modal can be closed:
- With overlay mouse down
- With close button click
- With escape key press

All events are different, there is no way we can provide a shared event for that. 

I think you are trying to do something with a Modal that you are not supposed to do. What is your usage scenario?

**Comment by tim-coutinho** [comment]
I've provided a simplified example of my use case in the linked code sandbox, but essentially I have a list of items where clicking an item will provide details for the item elsewhere. Also rendered within the item is a delete button, which brings up the modal to delete the item. On the button itself I stop propagation to not also click the item the button is on, but the close button click and overlay click both trigger the item's click handler (escape is fine, as the parent doesn't have a keypress handler).
Honestly if it were just for me, I would just need access to the `stopPropagation` function on the event which all three methods of closing should have, but that would be a pretty niche solution.

**Comment by rtivital** [comment]
I think you can just render Modal outside your item – https://codesandbox.io/s/serene-snyder-052w2h?file=/src/App.tsx
This will solve the issue with events propagation

**Comment by tim-coutinho** [comment]
That is what I was doing originally, but after some reorganization of my project I'm trying to set it up a bit differently. Beforehand I would need to keep track of some global state storing the item ID marked for deletion which the list component would set and the component rendering the modal would read, which wasn't ideal. Now I'm rendering the modal within each item in the list component so that I can just pass the item ID into the modal directly.

**Comment by rtivital** [comment]
I can only advise to revert your changes to use "global" state, things that you are trying to achieve with onClose event capturing are 10x times dirtier,
