### ISSUE TITLE
CSS position expects a Position typed value, not a string, if used at sx and stored in a variable

### ISSUE THREAD

**Issue by nireak** [mantinedev/mantine#870]
### What package has an issue

@mantine/core

### Describe the bug

Hi,

If I store a  css style object that uses the position property and later I pass this as a parameter for sx styles, Typescript complains. If if pass the object directly everything seems to be ok.

This code gives me this Typescript error: 'Type 'string' is not assignable to type 'Position | Position[] | undefined'.ts(2322)'
```typescript
const styles = (theme: MantineTheme) => ({
	position: "absolute"
})
...
<Box sx={styles}></Box>
```

This code works:
```typescript
<Box sx={(theme: MantineTheme) => ({
	position: "absolute"
})}
```

Any other property seems to work, only position is affected.
Thanks

### In which browser did the problem occur

chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/async-night-9px4x5

**Comment by rtivital** [comment]
You need to add `CSSObject` return type, this will also give you autocomplete for styles – https://codesandbox.io/s/wonderful-newton-vio05f?file=/src/App.tsx

**Comment by nireak** [comment]
Thank you very much!  Perhaps you can add it to the documentation at
https://mantine.dev/theming/sx/#storing-styles-in-a-variable
in case other people stumble upon the same problem in the future.
