### ISSUE TITLE
[Feature Request] Tooltip open delay

### ISSUE THREAD

**Issue by baldwin-dev-co** [mantinedev/mantine#872]
### Usage example, including component/hook API

Currently, the `Tooltip` component  has a `delay` prop which delays un-mounting the component for a given amount of time. I would love to see the same for an open delay i.e. on `mouseEnter`  the component waits a given amount of time to mount the component.

### Possible implementation – describe how the feature can be implemented

Open delay can be implemented using the same logic as the current close delay. When the object is hovered set a timeout for the given amount of time, if the mouse leaves the element cancel the timeout, otherwise open the tooltip.

### Do you want to contribute this feature and create a pull request

Yes

**Comment by rtivital** [comment]
This feature is already done. It will be available with 4.0 release.

**Comment by rtivital** [comment]
Released in 4.0
