### ISSUE TITLE
[Feature Request]  Inline renaming of some text (Editable form)

### ISSUE THREAD

**Issue by jasbirrajrana** [mantinedev/mantine#880]
### Usage example, including component/hook API

https://chakra-ui.com/docs/form/editable

### Possible implementation – describe how the feature can be implemented

I will use custom controls to toggle the edit and read mode and the render prop pattern to provide access to the internal state of the component.

### Do you want to contribute this feature and create a pull request

Yes

**Comment by rtivital** [comment]
Thanks for a feature request, the use cases of such component seems to be very limited to certain scenarios (I haven't seen it being used in any production applications), so I do not think that Mantine should include such component.
