### ISSUE TITLE
Update to @emotion/react@11.8.1

### ISSUE THREAD

**Issue by albertbronsky** [mantinedev/mantine#883]
### What package has an issue

@mantine/core

### Describe the bug

When building Next.js app with Mantine I am getting this error:
`Attempted import error: 'useInsertionEffect' is not exported from 'react' (imported as 'useInsertionEffect$1').`
Apparently, it's a bug in emotion that has been fixed in version 11.8.1.

[https://stackoverflow.com/a/71187753](https://stackoverflow.com/a/71187753)

[https://github.com/emotion-js/emotion/pull/2651](https://github.com/emotion-js/emotion/pull/2651)

### In which browser did the problem occur

build

**Comment by rtivital** [comment]
Mantine depends on `^1.7.1` version of emotion, not `1.8.0`, nothing should be fixed on our side
