### ISSUE TITLE
Missing style on DatePicker when using SSR

### ISSUE THREAD

**Issue by brickpop** [mantinedev/mantine#884]
### What package has an issue

@mantine/dates

### Describe the bug

Navigating the web site with the NextJS dev server, the DatePicker popup looks perfect.

But then I export it as a static website, and the DatePicker input box looks fine, but the pop up doesn't. It can't even be clicked.

![image](https://user-images.githubusercontent.com/4456749/155114578-7fa387f5-380f-411d-8dc1-1fe74c4ef555.png)

I followed [the instructions](https://mantine.dev/theming/next/) for NextJS SSR, but it looks as if the `<ServerStyles>` component in `_document` was recognizing the input component but missing the calendar pop up styling.

### In which browser did the problem occur

Firefox, Chromium based

**Comment by rtivital** [comment]
Please create a new repository with issue reproduction using next template – https://github.com/mantinedev/mantine-next-template

**Comment by brickpop** [comment]
Thank you @rtivital, using the template it works so I'm closing the issue.

However, I'd suggest updating the documentation to at least mention the Next template as a reference.
Following the instructions on top of an existing Next app didn't work for me (will figure out the differences myself)

**Comment by brickpop** [comment]
In case someone faces a similar issue in the future (NextJS + Styled Components + Mantine):

```tsx
import React from "react";
import Document, {
  DocumentContext,
  Head,
  Main,
  NextScript,
} from "next/document";
import { ServerStyleSheet } from "styled-components";
import { createStylesServer, ServerStyles } from "@mantine/next";

const stylesServer = createStylesServer();

class AppDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    // Styled components style SSR extraction
    const sheet = new ServerStyleSheet();

    try {
      const originalRenderPage = ctx.renderPage;
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) =>
            (props) => sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      };
    } finally {
      sheet.seal();
    }
  }

  render() {
    return (
      <html>
        <Head>
          <link rel="icon" type="image/x-icon" href="/media/favicon.ico" />
          {/* Next and Styled components SSR styles */}
          {this.props.styles}
          {/* Mantine SSR styles */}
          <ServerStyles html={this.props.html} server={stylesServer} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}

export default AppDocument;

```
