### ISSUE TITLE
Fix the placement of the navbar when in RTL

### ISSUE THREAD

**Issue by alimehasin** [mantinedev/mantine#887]
### What package has an issue

@mantine/core

### Describe the bug

When using AppShell component in RTL the Navbar component placed on the left and there are no easy why to change that behavior

Notes
- the html tag looks like this `<html lang="ar" dir="rtl">`
- the theme.dir is equal to 'rtl'

### In which browser did the problem occur

Brave

### Do you know how to fix the issue

No

### Possible fix

- Automatically change the placement of the navbar when theme.dir === 'rtl'
- Provide placement prop to easily change the placement of the navbar

**Comment by rtivital** [comment]
Are you using stylis plugin rtl like it is described in docs?

**Comment by alimehasin** [comment]
Ohhh, no I don't, I will try it
