### ISSUE TITLE
[Bug] Mantine 3.6.7 introduced type errors

### ISSUE THREAD

**Issue by yhnavein** [mantinedev/mantine#893]
### What package has an issue

@mantine/core

### Describe the bug

After upgrading to `3.6.7` and newer I have a numerous errors when building my app, like the following one:

```
src/app/profile/Profile.tsx:29:6 - error TS2746: This JSX tag's 'children' prop expects a single child of type 'never', but multiple children were provided.

29     <StyledCard shadow="sm" padding="lg">

src/app/profile/Profile.tsx:29:17 - error TS2322: Type 'string' is not assignable to type 'never'.

29     <StyledCard shadow="sm" padding="lg">
                   ~~~~~~

src/app/profile/Profile.tsx:29:29 - error TS2322: Type 'string' is not assignable to type 'never'.

29     <StyledCard shadow="sm" padding="lg">

```

It looks like wrapping any Mantine components with Emotion's styled-components breaks types of wrapped component. Sample:

```
import styled from '@emotion/styled';

const StyledCard = styled(Card)`
  max-width: 720px;
  margin: 0 auto;

  && .mantine-Tabs-tabsListWrapper {
    margin: 0 -20px;
  }
`;
```

It looks like it's a consequence of implementing this issue https://github.com/mantinedev/mantine/issues/812 

Was that expected outcome, or an accidental one ? :)

Extending your components with styled-components is supported, right?

### In which browser did the problem occur

Opera/Chrome/Edge

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
> Was that expected outcome, or an accidental one

Accidental one

> Extending your components with styled-components is supported, right?

The main way to style Mantine components is with createStyles, we do not officially support styled syntax and these styling solutions may break in future (with TypeScript, not functionality itself) as we are exploring the options to make Mantine more performant. 

If you decide to use external packages to style Mantine components, then you should also take ownership over types. In your example with Card, you should define component types manually:

```tsx
import { Card, CardProps } from '@mantine/core';
import styled from '@emotion/styled';
 
type CardComponent = (<C = 'div'>(props: CardProps<C>) => React.ReactElement) & {
  displayName?: string;
  Section: typeof Card.Section;
};

const StyledCard : CardComponent = styled(Card)`
  max-width: 720px;
  margin: 0 auto;

  && .mantine-Tabs-tabsListWrapper {
    margin: 0 -20px;
  }
`;
```
