### ISSUE TITLE
Input Auto-complete Styling (Dark Mode)

### ISSUE THREAD

**Issue by ayush-lal** [mantinedev/mantine#896]
### What package has an issue

@mantine/core

### Describe the bug

Hi guys, 

It seems that the form input auto complete styling is off when on dark mode. Is there a way to restyle the input to align with the dark mode theme or perhaps completely disable auto completely on the form?

![image](https://user-images.githubusercontent.com/41420385/155604890-52880a08-e44c-42ba-a2a7-b8d8b478b365.png)

Thanks  in advance.

### In which browser did the problem occur

From my testing, this seems to affect Chrome and how they handle auto completes

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/compassionate-goldberg-lxfvci

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
I do not think that it will be a great idea to change default browser autofill styles on library level, you can do it on your side using styles api – https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/
