### ISSUE TITLE
Warning: Received false for a non-boolean attribute grow.

### ISSUE THREAD

**Issue by Jordan-Gilliam** [mantinedev/mantine#900]
### What package has an issue

@mantine/core

### Describe the bug

Transition api console warning.

![Screen Shot 2022-02-25 at 12 05 35 PM](https://user-images.githubusercontent.com/25993686/155756835-840517ac-0707-4893-a7d7-7b295b2b267a.png)
![Screen Shot 2022-02-25 at 12 06 48 PM](https://user-images.githubusercontent.com/25993686/155757043-f08d66eb-d7da-4797-85ab-f3c570da03fd.png)

### In which browser did the problem occur

chrome

**Comment by rtivital** [comment]
Please share the code which produces warning

**Comment by Twathik** [comment]
Hello 
I have the same issue this is my component

```
    <Grid justify="center">
      <Avatar
        style={{ height: '30vh', width: '30vh' }}
        src="./avatar.png"
      />
    </Grid>
```

this is the error

````
next-dev.js?36dd:32 Warning: Received `false` for a non-boolean attribute `grow`.

If you want to write it to the DOM, pass a string instead: grow="false" or grow={value.toString()}.

If you used to conditionally omit it with grow={condition && value}, pass grow={condition ? value : undefined} instead.
````

**Comment by rtivital** [comment]
@Twathik Grid component cannot have any children except `Grid.Col`
