### ISSUE TITLE
Select.unselectable has no effect when clearable is enabled

### ISSUE THREAD

**Issue by gempain** [mantinedev/mantine#906]
### What package has an issue

@mantine/core

### Describe the bug

When `clearable` is enabled on `Select`, `unselectable="off"` has no effect.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/polished-cherry-tnc233?file=/src/App.js

**Comment by rtivital** [comment]
Select does not `unselectable` prop.

**Comment by wes337** [comment]
I think you mean `disabled`.

And yes, there may be a bug here. You can still clear the value when `disabled` is true.

**Comment by gempain** [comment]
When clearable is enabled, I expect the value to be clearable: this is working fine. I would expect that unselectable=off makes it impossible to deselect the selected value by clicking it in the drop-down: this isn't what happens.

**Comment by rtivital** [comment]
`allowDeselect` props works fine, as described in documentation – https://codesandbox.io/s/blue-wood-2n5xng?file=/src/App.js
