### ISSUE TITLE
Select component is clearable when disabled

### ISSUE THREAD

**Issue by wes337** [mantinedev/mantine#907]
### What package has an issue

@mantine/core

### Describe the bug

When the Select component has `clearable` and is `disabled`, you can still clear the input.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/wonderful-ishizaka-pz11wz?file=/src/App.js

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

The button to clear the input should also be disabled if the Select component is disabled.

**Comment by rtivital** [comment]
Feel, free to create a PR, note that this issue most likely is also in MultiSelect component

**Comment by wes337** [comment]
Sure. Checking the MultiSelect component and it doesn't even seem to render the clear button if disabled:

![image](https://user-images.githubusercontent.com/9464690/155848508-63079bbf-4df8-45aa-9e34-7274da493c67.png)

Seems like a separate but related issue. I can fix it in the same PR though.
