### ISSUE TITLE
`List` skips child components that are indirectly composed of `List.Item`

### ISSUE THREAD

**Issue by pavi2410** [mantinedev/mantine#914]
### What package has an issue

@mantine/core

### Describe the bug

```jsx
function MyList() {
  return (
    <List>
      {
        ['a', 'b', 'c'].map((value, i) => (
          <MyListItem item={value} key={i} />
        )
      }
    </List>
  )
}

function MyListItem({ item }) {
  return (
    <List.Item>{item}</List.Item>
  )
}
```

The above code doesn't render anything inside the `List`. However, it is expected to render `List.Item`s

This is caused by `filterChildByType` function here: https://github.com/mantinedev/mantine/blob/a140cbca9dbf0f90b2314b25a64cc58413dacbc5/src/mantine-core/src/components/List/List.tsx#L68

### In which browser did the problem occur

Firefox

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

A possible fix is to introduce a new prop named `indirectItems` or `noFilterChildren` that skips filtering children.

**Comment by wes337** [comment]
New props named `indirectItems` or `noFilterChildren` feels like a confusing and over-engineered solution.

The workaround here seems simple to me,
```js
export default function App() {
  return (
    <List>
      {['a', 'b', 'c'].map((value, i) => (
        <List.Item>
          <MyListItem item={value} key={i} />
        </List.Item>
      ))}
    </List>
  );
}


function MyListItem({ item }) {
  return (
    <>{item}</>
  )
  ```

**Comment by otemler** [comment]
Workaround works, but doesn't fix the actual problem. Would be really cool to have a fix on this. 

I'm able to render child items inside group components with almost every other library without problems, so I was quite surprised.

**Comment by rtivital** [comment]
Fixed in 4.0.2

**Comment by saaymeen** [comment]
This bug possibly also exists in the `<Timeline/>` component!

**Comment by rtivital** [comment]
Timeline.Item depends on its index, there is no way of getting this index during ssr, so it will remain as is (it will not be migrated to context as List.Item).
