### ISSUE TITLE
Mantine component long initial render time.

### ISSUE THREAD

**Issue by linardsblk** [mantinedev/mantine#915]
### What package has an issue

@mantine/core

### Describe the bug

Whenever mantine components are first rendered or inteacted with there is a significant render delay. For example, when I open a page where mantine DatePicker exists the select component renders for a second then opening it takes additional 0.5 seconds. After the first rendering the components, they work smooth on open/close. 

I did some debugging and here are my results:

Profiler - 
On page load: 
![image](https://user-images.githubusercontent.com/47926386/156170831-77f54e6a-dddc-4de0-accf-06b1b881c423.png)

On date picker open: 
![image](https://user-images.githubusercontent.com/47926386/156170938-1f1488a1-4298-4df2-9ae9-e6faefbdfd6e.png)

Performance - 
It seems that always the most time is spent with useStyles and cx functions. 
![image](https://user-images.githubusercontent.com/47926386/156171171-c6917ae1-571e-4237-a71e-40bd6efcf671.png)

I figured that it might have issues merging large CSS file with mantine styles but after deleting all CSS content from my app, it didn't help.

I have tried eliminating all interactions with other code and returned DatePicker directly in App.jsx without anything else and no result.  

I tried a fresh project with my current tech stack (Meteor.js backend with React) and I cannot replicate this bug.

Any advice on debugging this high load time? I feel like I've tried everything at this point. Using Mantine v3.6.11.

### In which browser did the problem occur

Chrome 98, Safari 13.1

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Please provide more information:
- What build system you are using? (Next.js/vite/cra/other)
- Have you tried running the same code with next template? https://github.com/mantinedev/mantine-next-template
- Can you provide a repository that reproduces the issue?

**Comment by linardsblk** [comment]
If anyone else using Meteor has this problem, then read this issue with MUI that seems to exist also with Mantine.

https://forums.meteor.com/t/material-ui-v5-dialogs-and-menus-initial-open-lags-freezes/56842

The solution is updating Meteor to atleast 2.5.2. Unfortunately for me I have forked some meteor packages that disallow updating but maybe this helps for someone.
