### ISSUE TITLE
[Feature Request] Support split pane layout

### ISSUE THREAD

**Issue by percy507** [mantinedev/mantine#919]
### Usage example, including component/hook API

Split pane are usually used in desktop app. 

### Possible implementation – describe how the feature can be implemented

Here is a package which can be refer.

https://github.com/tomkp/react-split-pane

**Comment by rtivital** [comment]
I don't think that this will be added. Use a dedicated library to implement this.

**Comment by tombohub** [comment]
@percy507 primereact has this one

**Comment by percy507** [comment]
@tombohub I am using https://github.com/johnwalley/allotment now.

**Comment by gfazioli** [comment]
@percy507 I released a Mantine Spli pane component here 

https://gfazioli.github.io/mantine-split-pane/

I loved any feedback or suggestions

<img width="1128" alt="image" src="https://github.com/mantinedev/mantine/assets/432181/d789e147-73b7-4e49-b03e-71ae34401c76">

**Comment by percy507** [comment]
@gfazioli Looks great. It will be better if support `snap`. You can take a look at https://github.com/johnwalley/allotment.

**Comment by tombohub** [comment]
@gfazioli looks good!
