### ISSUE TITLE
Issue with the DatePicker components demo

### ISSUE THREAD

**Issue by MatteoGauthier** [mantinedev/mantine#920]
### Link to the page where something nasty is located

https://mantine.dev/dates/date-picker/

### Exact quote of what is wrong

The DatePicker close when the month fragment is clicked

https://user-images.githubusercontent.com/32040951/156360287-f5c62174-7e4e-4827-a0b6-2a49237c0888.mov

**Comment by rtivital** [comment]
Thanks for reporting!

**Comment by rtivital** [comment]
Fixed in 3.6.13
