### ISSUE TITLE
Modal does not properly scroll when using "centered"

### ISSUE THREAD

**Issue by kirankunigiri** [mantinedev/mantine#927]
### What package has an issue

@mantine/core

### Describe the bug

I was using the Modal component from @mantine/core. When I use the `centered` property and fill the modal with enough content that it starts to scroll vertically, the modal will not let me scroll to see the top of it's content. However, this issue is resolved when the `centered` property is removed. I've put in photos of an example, along with the CodeSandbox example.

[CodeSandbox Link](https://codesandbox.io/s/mantine-modal-issue-l4cem2?file=/src/App.tsx)

This is the original modal with `centered` removed. The entire modal properly scrolls.
![Original](https://i.imgur.com/tM4yXj6.png)

This is modal with `centered` added. The top of the modal is unreachable by scrolling.
![Centered Bug](https://i.imgur.com/guKxDot.png)

### In which browser did the problem occur

All

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-modal-issue-l4cem2?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Thanks for reporting!

**Comment by rtivital** [comment]
While we are fixing this issue, you can use centered modals that are not centered, they should not have such issue.

**Comment by wes337** [comment]
What's the expected result for the "janky modal"? 

Should it look just like the "working modal"?

Or should it have a max-height and it's content is scrollable:
![image](https://user-images.githubusercontent.com/9464690/156874240-71e79322-6dd1-4092-8bce-dfa530c8369e.png)

**Comment by rtivital** [comment]
It should depend of `overflow` prop

**Comment by wes337** [comment]
Yes true, I just noticed that changing `overflow === 'inside'` will fix the "janky modal" example.

So if the modal is `centered && overflow === 'outside'`, and the content of the modal is overflowing, it should look the same as when `centered` is false.

**Comment by rtivital** [comment]
That's right, no idea how to implement that though
