### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by pimartin** [mantinedev/mantine#93]
Package: @mantine/core
Version: 1.2.1
Codesandbox: https://codesandbox.io/s/recursing-kepler-vzdm8?file=/src/App.js

Hi,
I have started using mantine and it works great, but when using React.StrictMode, a warning is printed in the console when a tooltip is triggered:
> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

It appears to be linked to Transition (which I do not use directly in my code).

**Comment by rtivital** [comment]
Thanks for reporting, this is known issue with react-transition-group – https://github.com/reactjs/react-transition-group/issues/687

We need to implement new logic for ref usage as shown in 4.0.0 release

**Comment by rtivital** [comment]
Fixed in 2.3.0
