### ISSUE TITLE
Support additional languages for Mantine Prism code highlight

### ISSUE THREAD

**Issue by avestura** [mantinedev/mantine#941]
### What package has an issue

@mantine/prism

### Describe the bug

Mantine is using [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer) to highlight languages. By default prism-react-renderer only includes an [arbitrary subset of the languages](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js) that Prism supports.

`prism-react-renderer` has this code snippet in their repo for supporting additional language:

```js
import Prism from "prism-react-renderer/prism";

(typeof global !== "undefined" ? global : window).Prism = Prism;

require("prismjs/components/prism-kotlin");
require("prismjs/components/prism-csharp");
```

But this doesn't work with `@mantine/prism`.

Please add a capability to support additional languages that prism already supports.

### In which browser did the problem occur

All browsers

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment]
Here is an example of adding additional languages – https://codesandbox.io/s/stupefied-hellman-lfudm?file=/src/App.tsx

**Comment by avestura** [comment]
Thanks, this works great!

**Comment by whoisandy** [comment]
Is there an example of using the prism highlighter with Next.js? Also the above example of adding additional languages seems to be using a very old version of `@mantine/prism` package.
