### ISSUE TITLE
on use-form i can't use try {} catch {} inside handleSubmit() 

### ISSUE THREAD

**Issue by na0495** [mantinedev/mantine#952]
### What package has an issue

@mantine/hooks

### Describe the bug

I'm using use-hooks alongside redux toolkit in order to submit data to the back-end, but apparently  when i use "try  catch" the error that i get from dispatch don't seems to rigger the catch which still pop up the success notif and not the error notif.

here is an example code of what i'm trying to do 

```
  const handleSubmit = async () => {
    try {
      setServerError("");
      await dispatch(create(form.values));
      notifications.showNotification({
        color: "teal",
        title: "success",
        message: "success",
        icon: <CheckIcon />,
      });
      navigate(PATH_DASH.order.table);
    } catch (error: any) {
      setServerError(error.detail);
      setTimeout(() => {
        notifications.showNotification({
          color: "red",
          message: error.detail,
        });
      }, 2000);
    }
  };
```

### In which browser did the problem occur

chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
use-form hook does not throw any errors, if your code does not throw it, there is nothing to catch.

**Comment by na0495** [comment]
hmm i just tough it could had been the cause for me to catch the error thank you
