### ISSUE TITLE
Calendar month view does not respect fullWidth property

### ISSUE THREAD

**Issue by GV79** [mantinedev/mantine#958]
### What package has an issue

@mantine/dates

### Describe the bug

When you set the `fullWidth` property on the `Calendar` component from `@mantine/dates` it works until you switch to the month view (by clicking the icon to the right of the year at the top).

### In which browser did the problem occur

Google Chrome 98.0.4758.102

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-dates-calendar-month-view-bug-pwo7ig?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Fixed in 4.0.3
