### ISSUE TITLE
Radio button compressing when text is more

### ISSUE THREAD

**Issue by chenchunaidu** [mantinedev/mantine#961]
### What package has an issue

@mantine/core

### Describe the bug

Radio button is compressing when text is more
<img width="514" alt="image" src="https://user-images.githubusercontent.com/38114196/157433033-1b2abb0a-5544-4ce0-8c9f-44a738ff6ff4.png">

### In which browser did the problem occur

Google chrom, Safari

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Add label wrapper for span
```
 <Box
        className={cx(classes.radioWrapper, className)}
        style={style}
        title={title}
        sx={sx}
        {...margins}
      >
        <label className={cx(classes.label, { [classes.labelDisabled]: disabled })} htmlFor={uuid}>
          <input
            ref={ref}
            className={classes.radio}
            type="radio"
            id={uuid}
            disabled={disabled}
            {...rest}
          />
          {children && <span className={classes.labelWrapper}>{children}</span>}
        </label>
      </Box>
```

**Comment by wes337** [comment]
Here is a sandbox reproducing the issue:
https://codesandbox.io/s/headless-paper-u9x91r?file=/src/App.js
