### ISSUE TITLE
Password input doesn't allow styling the input element

### ISSUE THREAD

**Issue by krconv** [mantinedev/mantine#963]
### What package has an issue

@mantine/core

### Describe the bug

The `PasswordInput` styles API includes a class, `innerInput`, that is exposed to make updates to the input field. From testing and from looking at the code, I don't think setting that class actually has an effect on the component.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/busy-feynman-bdrb5j?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

<img width="816" alt="image" src="https://user-images.githubusercontent.com/1918630/157440953-fe071f47-efc1-4ea6-8eda-35df84a404fa.png">

**Comment by rtivital** [comment]
You have a solution to your problem, I do not see why it does not satisfy you

**Comment by rtivital** [comment]
Fixed in 4.0.1
