### ISSUE TITLE
Notification Default Color

### ISSUE THREAD

**Issue by genericblueprint** [mantinedev/mantine#964]
### What package has an issue

@mantine/notifications

### Describe the bug

I'm not sure if this is a bug, feature, or if I'm missing something, but I can't seem to set a default color for the Notification component. I assumed that setting the primaryColor in the MantineProvider would do it, but that didn't work. So then I tried setting different styles props on the Notification in the MantineProvider (root, body, etc.) and that didn't do it either. Finally, I saw there is a color prop on the NotificationsProvider so I tried setting that, but again, no change. Is there something I'm missing?

Thanks!

### In which browser did the problem occur

Chrome

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
You can set notification color:
```tsx
notifications.showNotification({
  color: 'teal',
  title: 'Data was loaded',
  message: 'Notification will close in 2 seconds, you can close this notification now',
 });
```

Other options are not currently supported

**Comment by genericblueprint** [comment]
Thank you for the response. This is the way I had been going about it, I just didn't know if there was a global approach to setting the default color. Is this something that is achievable at some point? In the meantime, I will continue to set the color in each place I use showNotification.

**Comment by mattrunyon** [comment]
This would be possible w/ Mantine 4.0 default props on the provider if `useMantineDefaultProps` was altered to merge without replacing defined values w/ undefined. Not sure if that would cause any issues elsewhere, but in the case of the notification system it's explicitly setting `color=undefined` if it's omitted which overwrites default.

```js
const default = { color: 'red' };
const props = { color: undefined };
const merged = { ...default, ...props }; // { color: undefined }
```

**Comment by mattrunyon** [comment]
This is possible w/ 4.0.1 now

https://codesandbox.io/s/compassionate-roman-v9krb6?file=/src/App.tsx

@rtivital Can probably close?

**Comment by rtivital** [comment]
Thanks @mattrunyon for an example!
