### ISSUE TITLE
DOMException in JSDOM tests with Portal component

### ISSUE THREAD

**Issue by Dor256** [mantinedev/mantine#965]
### What package has an issue

@mantine/core

### Describe the bug

When running `JSDOM` tests on `Popover` components I'm getting an error that crashes my tests.

> [DOMException [NotFoundError]: The node to be removed is not a child of this node.]
The above error occurred in the <@mantine/core/Portal> component:

### In which browser did the problem occur

JSDOM

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Please provide a repository with reproduction.

If you do not want content to render within Portal set `withinPortal` prop to `false`

**Comment by Dor256** [comment]
Can't provide a repo as it is private.
However, I was trying to render a `Tooltip` as a `target` for the `Popover` and it seems like setting `withinPortal` to `false` on the `Tooltip` fixed it.
