### ISSUE TITLE
v4: forms with RadioGroups causes crashes

### ISSUE THREAD

**Issue by josefssonemil** [mantinedev/mantine#978]
### What package has an issue

@mantine/core

### Describe the bug

I upgraded one of our apps to version 4, and noticed that when modals were opened the app would crash, yielding this error message:

`input
label
div
Box<@webpack-internal:///./node_modules/@mantine/core/esm/components/Box/Box.js:42:54
Radio<@webpack-internal:///./node_modules/@mantine/core/esm/components/RadioGroup/Radio/Radio.js:49:85
div
Box<@webpack-internal:///./node_modules/@mantine/core/esm/components/Box/Box.js:42:54
Group<@webpack-internal:///./node_modules/@mantine/core/esm/components/Group/Group.js:51:85
div
Box<@webpack-internal:///./node_modules/@mantine/core/esm/components/Box/Box.js:42:54
InputWrapper<@webpack-internal:///./node_modules/@mantine/core/esm/components/InputWrapper/InputWrapper.js:54:85
RadioGroup<@webpack-internal:///./node_modules/@mantine/core/esm/components/RadioGroup/RadioGroup.js:54:85
form
CreateGroupForm@webpack-internal:///./components/forms/CreateGroupForm.js:47:20
div
div
Box<@webpack-internal:///./node_modules/@mantine/core/esm/components/Box/Box.js:42:54
Paper<@webpack-internal:///./node_modules/@mantine/core/esm/components/Paper/Paper.js:45:85
div
div
Box<@webpack-internal:///./node_modules/@mantine/core/esm/components/Box/Box.js:42:54
GroupedTransition@webpack-internal:///./node_modules/@mantine/core/esm/components/Transition/GroupedTransition.js:13:27
div
Portal@webpack-internal:///./node_modules/@mantine/core/esm/components/Portal/Portal.js:21:132
OptionalPortal@webpack-internal:///./node_modules/@mantine/core/esm/components/Portal/OptionalPortal.js:40:52
Modal@webpack-internal:///./node_modules/@mantine/core/esm/components/Modal/Modal.js:75:85
ModalsProvider@webpack-internal:///./node_modules/@mantine/modals/esm/ModalsProvider.js:77:24
NotificationsProvider@webpack-internal:///./node_modules/@mantine/notifications/esm/NotificationsProvider/NotificationsProvider.js:75:7
MantineProvider@webpack-internal:///./node_modules/@mantine/styles/esm/theme/MantineProvider.js:79:25
div
ColorSchemeProvider@webpack-internal:///./node_modules/@mantine/styles/esm/theme/ColorSchemeProvider.js:18:29
App@webpack-internal:///./pages/_app.js:66:21
StyleRegistry@webpack-internal:///./node_modules/styled-jsx/dist/stylesheet-registry.js:231:28
ErrorBoundary@webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47
ReactDevOverlay@webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:90:20
Container@webpack-internal:///./node_modules/next/dist/client/index.js:331:24
AppContainer@webpack-internal:///./node_modules/next/dist/client/index.js:770:20
Root@webpack-internal:///./node_modules/next/dist/client/index.js:891:21
`

The following flow leads to the crash:

1) Open a modal

```
  const openCreateGroupModal = useCallback(() => {
    modals.openModal({
      title: 'TEST',
      centered: true,
      size: '70%',
      children: (
        <CreateGroupForm
          products={products}
          onCancel={() => modals.closeAll()}
          onSubmit={(values) => createGroup(values)}
        />
      ),
    })
  }, [modals, products, createGroup])
```

2) Use the new useForm from @mantine/form
```
import { useForm } from '@mantine/form'
  const form = useForm({
    initialValues: {
        val: someValue //used as input prop for RadioGroup
        ...otherstuff
    },
  })
```

3) Render the form, which has the component:

```
      <RadioGroup
        label='val'
        size='sm'
        className='mb-4'
        {...form.getInputProps('val', { type: 'checkbox' })} // type checkbox or input does not make a    difference
        required>
        <Radio value='1'>Nivå 1</Radio>
        <Radio value='2'>Nivå 2</Radio>
        <Radio value='3'>Nivå 3</Radio>
      </RadioGroup>
```

When the RadioGroup is removed from the form, the crash does not occur.

### In which browser did the problem occur

Firefox

**Comment by rtivital** [comment]
RadioGroup works fine with @mantine/form, example – https://codesandbox.io/s/divine-mountain-d4jxco?file=/src/App.tsx
You are using Radio component incorrectly, there was a breaking change in 4.0

**Comment by josefssonemil** [comment]
@rtivital thank you for the example and quick reply! Perhaps a clarification might be needed the changelog (in case anyone else runs into this problem)
