### ISSUE TITLE
Adding new item on Select doesn't work when used object as data

### ISSUE THREAD

**Issue by samundrak** [mantinedev/mantine#980]
### What package has an issue

@mantine/core

### Describe the bug

When we make `Select` creatable and pass data as objects in the expected schema and when we add a new item and click outside Select becomes empty but if we select the same item again then it can be seen selected. If we test this with only strings data then there is no problem. 

### In which browser did the problem occur

Google Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hardcore-vaughan-g9d580?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
I've checked the example provided in docs, it works correctly with data as object – https://codesandbox.io/s/focused-morse-qpdwrq?file=/src/App.tsx

**Comment by DillonStreator** [comment]
@samundrak In your example, the newly created object has a value which is different than the label. The Select internals are making an assumption that the value and label of the new object will both match the text that was typed into the input.

```js
<Select
  searchable
  creatable
  label="Type"
  placeholder="Pick one"
  autoComplete="off"
  nothingFound="No options"
  name="type"
  getCreateLabel={(query) => `+ Create ${query}`}
  onCreate={(d) =>
    setObjectOptions((items) => [
      ...items,
      {
        label: d,
        value: Date.now(), // Select is assuming that value will be whatever `d` is here
      }
    ])
  }
  data={objectOptions}
/>
```

I adjusted onCreate to allow it to respect returning of the new value incase you wanted to do some custom value creation like in your example.
Here is a WIP pull request https://github.com/mantinedev/mantine/pull/983 that could use some review of the proposed interface for onCreate.

**Comment by samundrak** [comment]
Thanks for the quick PR @DillonStreator, This will help add new items asynchronously.
