### ISSUE TITLE
inputMode setting on NumberInput makes it potentially impossible for a user to enter negative numbers on mobile

### ISSUE THREAD

**Issue by TrashPandacoot** [mantinedev/mantine#981]
### What package has an issue

@mantine/core

### Describe the bug

On mobile, the keyboards shown when inputMode="numeric" and inputMode="decimal" vary on whether they have a minus key and a decimal key and this can make it hard or impossible to enter negative numbers in an input on mobile.

**On iOS:**
 the inputMode="numeric" and inputMode="decimal" keyboard does not include a minus key. This makes it so if the min on the NumberInput is less than 0 the only way for a mobile user to enter a negative number on iOS is to use the inputs stepper to decrement to a negative number and then focus the input/open the keyboard to type a number.

**On Android:**
 I'm pretty sure inputMode="decimal" does not include a minus key, while inputMode="numeric" includes both a negative sign and decimal key.

<img width="839" alt="mobile_numeric_input_controls" src="https://user-images.githubusercontent.com/33368961/157711078-a470742b-ea24-4ce5-98df-bc7c611f71df.png">

| input  | Has Minus Key  | Has Decimal Key  |
|---|---|---|
| iOS numeric  | ❌  | ❌  |
| iOS decimal  | ❌  | ✅  |
| iOS text | ✅  | ✅  |
| Android numeric  | ❌  | ✅  |
| Android decimal  | ✅  | ✅  |
| Android text | ✅  | ✅  |

### In which browser did the problem occur

iOS Safari, Android Browsers

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

https://github.com/mantinedev/mantine/blob/e1244528b82e70dc22ecda6034bbed4eea90b8a3/src/mantine-core/src/components/NumberInput/NumberInput.tsx#L372

Change the above to work the following way:

- If the input is for positive integers, set the inputMode to "numeric"
- If the input is for positive decimals, set the inputMode to "decimal"
- If the input is for integers that can be negative, set the inputMode to "text" for iOS, "decimal" for Android, and "numeric" for anything else
- If the input is for decimals that can be negative, set the inputMode to "text" for iOS, "decimal" for Android, and "decimal" for anything else

Matrix summary of how it should work:
| OS   | min >= 0, precision = 0  | min >= 0, precision != 0  | min < 0, precision = 0   | min < 0, precision != 0   |
|---|---|---|---|---|
| iOS  | "numeric"  | "decimal"  | "text"  | "text"  |
| Android  | "numeric"  | "decimal"  | "decimal"  | "decimal"  |
| Other  | "numeric"  | "decimal"  | "numeric"  | "decimal"  |

Should be a straightforward PR for me to make if you agree with my proposed change. I'd use the `useOs` from `@mantine/hooks` to detect user OS

**Comment by rtivital** [comment]
Fixed in 4.0.8
