### ISSUE TITLE
Accordion HTML structure - div nested into button element

### ISSUE THREAD

**Issue by smellai** [mantinedev/mantine#992]
### What package has an issue

@mantine/core

### Describe the bug

The [accordion](https://mantine.dev/core/accordion/) trigger element is implemented using 2 `div` elements inside a `button` tag, but that shouldn't be done because of the reasons listed [here](https://caninclude.glitch.me/caninclude?child=div&parent=button).

What are the reasons for not using `summary` and `details` tags?

### In which browser did the problem occur

any

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

- use `summary` and `details` tags (I'm not sure if we have limitations in how interactions are implemented for them)
- replace `divs` with `spans` or other inline element

**Comment by rtivital** [comment]
div and span tags do not have semantic meaning, so it is fine to use then inside button (and any other element). You can see WAI ARIA Accordion specification and example here – https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

**Comment by smellai** [comment]
In that example they put a span inside the button. 
See [the specification](https://www.w3schools.com/html/html_blocks.asp): 

> Note: An inline element cannot contain a block-level element!
