### ISSUE TITLE
[Feature Request] On @Mantine/notifications, expose create notification outside react scope

### ISSUE THREAD

**Issue by eliomaria** [mantinedev/mantine#993]
### Usage example, including component/hook API

Can we create a default export for notifications. So it can be used outside the react scope?
For example, inside an interceptor for axios client configuration, on error in respnse show a popup with server message.

### Possible implementation – describe how the feature can be implemented

Expose the notification, not only from a hook but directly from an import.

**Comment by mattrunyon** [comment]
Part of the issue w/ this would be that the notifications rely on the notification provider.

You can pass the `notifications` object from the hook to other things as long as it's created within the provider. I'm not too familiar w/ Axios, but something like this might work for you? https://stackoverflow.com/questions/64296505/usecontext-inside-axios-interceptor

**Comment by bogordesaincom** [comment]
I think you must double async 

asume your service like this `register.js`
```
    const register = async (value) => {

        const response = await api.post('/register', value)
            .then(res => res)
            .catch(error => error.response)
        return response
    }

```
in component
```
    const handleSubmit = async () => {
        const res = await register(form.values)
        setTimeout(() => {
// define for error status code
            if(res.status !== 200) {
                notifications.showNotification({ title: 'Failed', color: 'red'})
            } else {
                notifications.showNotification({ title: 'Success', color: 'green'})    
        }, 1000);
    }
```

**Comment by eliomaria** [comment]
Thanks for the idea @mattrunyon, 

I created a wrapper after the notification provider and before my app with the Axios interceptor with just the response interceptor for the client. Its like this:

```
const AxiosInterceptor: React.FC = ({ children }) => {
  const notifications = useNotifications();

  useMemo(() => {
    client.interceptors.response.use(
      (success) => success.data,
      (error) => {
        notifications.showNotification({
          title: 'server error',
          message: error.message,
          color: 'red',
        });
        return error.response
      }
    );
  }, []);
  return <>{children}</>;
};

export default AxiosInterceptor;
```



And with it, every request i made in the app that gives me an error, the notification pops up ;)

**Comment by eliomaria** [comment]
> I think you must double async
> 
> asume your service like this `register.js`
> 
> ```
>     const register = async (value) => {
> 
>         const response = await api.post('/register', value)
>             .then(res => res)
>             .catch(error => error.response)
>         return response
>     }
> ```
> 
> in component
> 
> ```
>     const handleSubmit = async () => {
>         const res = await register(form.values)
>         setTimeout(() => {
> // define for error status code
>             if(res.status !== 200) {
>                 notifications.showNotification({ title: 'Failed', color: 'red'})
>             } else {
>                 notifications.showNotification({ title: 'Success', color: 'green'})    
>         }, 1000);
>     }
> ```

Thanks for the feedback. Inside each component i do a request, its easy to manage the notifications to show because its inside the react scope.The problem was that i need to add the logic the show popup in every request i do in my entire platform. I was looking for a more generic way to do it for every request, with the axios interceptors. The solution above solved it
