### ISSUE TITLE
Disabled state missing when Button with anchor component

### ISSUE THREAD

**Issue by jCobbSK** [mantinedev/mantine#994]
### What package has an issue

@mantine/core

### Describe the bug

TS types allow passing disabled prop to `<Button />` with `component="a"` but it doesn't have any effect. I think it would be useful feature to have this working or at least update type definitions so this combination is not allowed.

### In which browser did the problem occur

all

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/crimson-thunder-mkeqjh?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
Anchors (`a` tag) do not support disabled state, and thus styles are not applied. We will not add features that do not work.
